### ISSUE TITLE
Enhancement: Accept an expression in species layer to draw micro-species

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1051]
```
What steps will reproduce the problem?
1. Open Toy Models/Circle/Circle.gaml
2. add this line in display section, after line: species cell;

species simulation.cell;

What is the expected output? What do you see instead?
GAMA make a compilation error
Multiple markers at this line
- Error at:  '.'. Previous keyword may be out of place or the
   block introduced by '.' may not be correctly terminated.
- missing '}' at 'cell'

It should be accepted!!

Please use labels and text to provide additional information.

```

Original issue reported on code.google.com by `hqnghi88` on 2014-06-05 09:09:30

**Comment by AlexisDrogoul** [comment]
Pushing this to GAMA 1.7 final release.

**Comment by hqnghi88** [comment]
Dear Alexis,
I test this issue, your fix allow to write simulation.species in regular case, but not in the case of nested species layers. And from my point of view, species in micro-model are not children of current simulation, they are children of the simulation of the experiment agent in micro-model. So can we close this issue or wait for the fix of nested layers?
Cheers.

**Comment by AlexisDrogoul** [comment]
Closing this issue while cleansing the backlog. Please reopen if still needed.
