### ISSUE TITLE
Enhancement: reading dwg files

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1071]
```
Hi,

We are considering using GAMA for simulating the movements
of a crowd within a train station.

Currently the station 3D environment is in a DWG file, and we were wondering if it
will be possible to read that kind of file in some future development of the platform?

Best regards,

Johan




```

Original issue reported on code.google.com by `johan.barthelemy` on 2014-07-02 00:09:02

**Comment by ptaillandier** [comment]
I didn't find any good open-source lib to read dwg files, so I added the possibility to read dxf instead (text files used in CAD... all CAD sofwares should be able to convert dwg files to dxf files). 
Note that the import of DXF is rather basic for moment but should be enough for most of the users. I added as well an example model (model library/Features/Data Importation/DXF Agents).

**Comment by AlexisDrogoul** [comment]
I propose to close this issue since, as Patrick said, all CAD software should be able to export DXF files instead of DWG ones. We cannot afford reading ALL formats …
