### ISSUE TITLE
Something like a measure tool

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1085]
```
Describe which enhancement/addition to GAMA you would like to see:

Hi,

I would like to request if it is possible to a measure tool in the GUI that is similar
to measure tool on google earth and in arcgis, for quick approximate measurements of
distance in the GAMA world space, like this

https://support.google.com/earth/answer/148134?hl=en (line in particular, not a lot
of interest in area measurements) 

Not an urgent enhancement, but was curios if may be it is simple to implement?

many thanks
Srirama 



```

Original issue reported on code.google.com by `b.srirama` on 2014-07-29 10:53:00

**Comment by agrignard** [comment]
cannot be done until issue ##1085 is not fixed

**Comment by agrignard** [comment]
This is really a first version. 

I think we can imagine to be able to toggle a "measure tool" mode and give the possibility to the user to draw a line or even a polyline and different point by clicking on the map.

**Comment by AlexisDrogoul** [comment]
Hi,

With the enhancement done in #1661, we can consider this issue as resolved (the dimensions in X and Y of the ROI appear in the overlay).

Alexis
