### ISSUE TITLE
Spatial query operator: Farthest_to

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1095]
```
There is already a closest_to operator ("a_species closest_to self"), but there is not
any farthest_to operator ("a_species farthest_to self").

It is possible to use the with_max_of operator to achieve the same result, but it is
not optimized at all (does not use the quad tree):
my_species with_max_of (each distance_to self).
```

Original issue reported on code.google.com by `patrick.taillandier` on 2014-08-18 17:06:25

**Comment by AlexisDrogoul** [comment]
I have decided not to take any action on this one — except the addition, which I will commit, of a farthest_to operator (not optimized at all, just reusing the GAML code provided above, but in Java) for the sake of the symmetry …
