### ISSUE TITLE
Loading and drawing SVG image

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1119]
```
What steps will reproduce the problem?
1.Loading and drawing any SVG image, via "file" or "svg_file"

What is the expected output? What do you see instead?
i am excepting to see the image on the display, but all i see is a small square !

What version of the product are you using? On what operating system?
1.6.1 / Fedora19

Please provide any additional information below.

```

Original issue reported on code.google.com by `laatabi44` on 2014-09-24 19:00:52

**Comment by benoitgaudou** [comment]
The SVG parser is definitely (and on purpose) very simple.
As advised, to display such a complex image, it could be better for the moment to convert it into a bitmap image format and import it.
The SVG parser could be improved if there is a need of importing SVG data as GAMA geometry. If it is the case do not hesitate to reopen this issue.
