### ISSUE TITLE
unkown facet: priority. The facet priority, for rules statement under the section Rules_based architecture is still included in the documentation pages 437 to 438.

### ISSUE THREAD

**Issue by jmbangate** [gama-platform/gama#114]
**Describe the bug**

Hi.

Encountered unkown facet: priority.  

The facet priority, for rules statement under the section Rules_based architecture is still included in the documentation pages 437 to 438.

To reproduce:
```
global{
	
	init{
		create simple_rules_statements number:1;
	}
}

species simple_rules_statements control:rules{
	
	int priority_of_a <- 0 update:rnd(100);
	int priority_of_b <- 0 update:rnd(100);
	
	reflex show_priorities{
		write "Priority of rule a = "+priority_of_a + ", priority of rule b = "+ priority_of_b;
	}
		
	rule a when: priority_of_a < 50 priority: priority_of_a {
		write " Rule a fired with priority: " + priority_of_a;
	}
	
	rule b when: priority_of_b > 25 priority: priority_of_b {
		write " Rule b fired with priority: " + priority_of_b;
	}
	
}

experiment main{
	
}
```

**Expected behavior**

**Screenshots**
<img width="396" alt="Annotation 2024-03-07 143041_unk" src="https://github.com/gama-platform/gama/assets/4437331/e29a4da0-4a7e-497f-b1f7-6afe3482c34a">

**Desktop (please complete the following information):**
 - OS: Microsoft
 - PC Model: HP ZBook Power G7 Mobile Workstation
 - GAMA version: 202406 and 1.9.3
 - Java version: 1.8
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

Thanks :)

**Comment by lesquoyb** [comment]
just as a complement: I had a look and the facet priority is still described as a facet of the RuleStatement in the code base, so it's normal that it is still in the documentation, what is weird is that it is not recognized in the code editor as a facet and that it does not have a description when you hover it. It is also not present in the list of facets for the rule statement when hovering the rule keyword in the editor

**Comment by AlexisDrogoul** [comment]
The name of the 'rule' statement is actually now `do_rule` (to differentiate it from the `rule` statement in the BDI architecture). This is the cause of the confusion.

**Comment by jmbangate** [comment]
Merci. Tried, and do_rule works as expected. The example in the
documentation may need to be edited :)

Best regards,

Julius

**Comment by AlexisDrogoul** [comment]
Document has been updated to reflect this.
