### ISSUE TITLE
Add a command to get gama informations in the interactive console to help debugging

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#116]
**Is your request related to a problem? Please describe.**
In addition to the file packaged with release proposed in issue #115 we could add some runtime information by running a command in the interactive console of gama

**Describe the improvement you'd like**
Information returned by the command should be:

- all the info from #115 
- the jdk version + vendor actually used (could be different from the one packaged)
- name of the cpu
- Operating system + version
- name of the gpu

**Describe alternatives you've considered**
This could also be printed by default at the top of the interactive console. We could disable or not with a preference

**Comment by AlexisDrogoul** [comment]
I have implemented a new attribute in the `gama` agent, called `info`. It returns a string containing the elements wanted. 

Just typing `info` (or `gama.info`) in the interactive console provides this :

<img width="369" alt="New Model gaml - Gama 2024-03-09 13-49-15" src="https://github.com/gama-platform/gama/assets/579256/b4fde676-804c-4fdd-80bd-a95f743b780c">

Note that GAMA version and commit number are not available yet (depends on #115 ).

**Comment by lesquoyb** [comment]
Could we add the name/brand of the cpu to the list or is it something not available ?

**Comment by lesquoyb** [comment]
@AlexisDrogoul ?

**Comment by lesquoyb** [comment]
After a little bit of digging, it seems like there's no easy cross-platform way. So I'm closing for now, we'll see later if we really need that info or not
