### ISSUE TITLE
GAMA licence

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1172]
```
Hi,

I think that closely integrating GAMA in OpenMOLE will be very great for both communities.
However I am worried about licencing issues. At some point OpenMOLE will have to move
away from the Equinox OSGi bus to be consistent with it's AGPL lincence. We will use
felix or knopflerfish I guess.

How hard do you think it would be to produce standard (non-eclipse dependant) OSGi
bundles for the core of GAMA (we do depend on the GUI for the OpenMOLE GAMA plugins)?
How deep does GAMA core bundles depend on Equinox and Eclipse?

Given that the technical pb would be solvable do you think it would be possible to
double licence the core of GAMA under EPL and GPL?

cheers,
Romain
```

Original issue reported on code.google.com by `elmariac` on 2015-02-26 16:01:27

**Comment by AlexisDrogoul** [comment]
For the moment, and without a lot of further investigations, we've set GAMA license to be GPL 3.0. (see https://github.com/gama-platform/gama/blob/master/LICENSE). This does not take into account the inclusion of 3rd party libraries with their own license. Not does it cover the GUI components, which should be probably covered by a double license. But I guess we can safely undertake this one, and wait until specific problems are raised (in that case, open a new issue for a specific plugin / component).
