### ISSUE TITLE
Last release on Mac cannot be launched

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#120]
**Describe the bug**
Try to install a release on Mac with or without JDK from https://github.com/gama-platform/gama/releases. The JDK is not configured and the app cannot be launched

**Comment by AlexisDrogoul** [comment]
The precise error message I receive is :

<img width="130" alt="Gama 2024-03-13 14-16-35" src="https://github.com/gama-platform/gama/assets/579256/80f900e4-0d8f-4575-bb93-5831091a86d0">

Not clear exactly what it means though... And no log when launched from the Terminal...
