### ISSUE TITLE
Enhancement : system_time and system_date operators

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1209]
```
It would be usefull to have such operators accessing the system time/date.
Currently, we can't use as_time and as_date on machine_time to get this result (see
here : https://code.google.com/p/gama-platform/issues/detail?id=1200)

I think it's especially usefull for creating files/folders based on current time/date,
when running a lot of experiments and having to save the data.

It could either be an adaptation of as_time() and as_date() on machine_time(), or through
new operators, for instance system_time()/system_date().




```

Original issue reported on code.google.com by `robin.cura` on 2015-05-04 12:36:11

**Comment by ThibautDemare** [comment]
Hello,

I recently updated my local git repo and I get an error in GAMA when I use this operator.
It seems it has been deleted by this commit fae6c84e69fcdc0db818ceda24031ed0011f527c
but it is still in the doc (see: https://github.com/gama-platform/gama/wiki/OperatorsAC#as_system_date )
Could you make it work again please?

**Comment by AlexisDrogoul** [comment]
Yep. Sorry to answer so late. Dates are now first-class citizens in GAML and many things have changed. See this thread here for more information: https://groups.google.com/forum/#!topic/gama-dev/Hop-DUKzFa0

We will update the documentation soon. Sorry again for the inconvenience
