### ISSUE TITLE
No logic apparent in the numbering of alpha/beta/"clean (?)" versions.

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#122]
**Describe the bug**
The releases section of GitHub (https://github.com/gama-platform/gama/releases) is for the moment populated by two versions that are difficult to distinguish because there aren't any apparent logic in their numbering 

![gama 2024-03-13 23-18-11](https://github.com/gama-platform/gama/assets/579256/e8b58ec5-d3ef-4370-bac0-631c2e9d46db)

1) Could we stick to something simpler that also can hint at which version we are producing ? 

For instance, if we are to produce the next version of GAMA, `GAMA 2024-06`, we might want to produce intermediary versions with a consistent numbering hinting at this final version. For example: 

 `GAMA 2024-06a1`
 `GAMA 2024-06a2`
...
 `GAMA 2024-06an`

2) And can we remove the commit number (which can be better integrated in the text accompanying the release : `This release corresponds to commit xxxxxxxxxxxxxxxxxxxxxxxxxx`), as it doesn't provide any information at all ?

**Comment by lesquoyb** [comment]
just to clarify about the clean version it was a test to check if we could produce a release based on a branch and has been removed

**Comment by AlexisDrogoul** [comment]
OK. I close this issue then.
