### ISSUE TITLE
Enhancement: Cache complex shapes like textures in OpenGL2

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1225]
```
Describe which enhancement/addition to GAMA you would like to see:

Some models (for instance "Ant sorting") are exhibiting slow displays in OpenGL, mainly
because the shape used by agents is quite complex. However, they all use the same (the
only differences being its rotation and its color). A nice enhancement could be to
use the same strategy for shapes than the one we're using for textures: using a unique
identifier (maybe the original geometry itself) we should cache the display list that
represents them and reuse the same display list instead of recomputing it (color, rotation
and other attributes can be applied to display lists). 

The only problem is the "unique" identification: as I remember, a lot of copying of
geometries occurs behind the scene, and I wouldn't be surprised to find that all the
agents draw actually different geometries… 

This enhancement could in any case boost the display speed of a number of models. 

```

Original issue reported on code.google.com by `alexis.drogoul` on 2015-05-12 16:10:09

**Comment by agrignard** [comment]
Complex shapes (obj and SVG) are now cached in OpengL. Need to see how to pre-build a cache of usual shapes.

**Comment by AlexisDrogoul** [comment]
A quick way to test the interest of this enhancement would be to preload the following geometries (which correspond to built-in shapes) in the GeometryCache:

- [ ] cuboid of dimensions 1 x 1 x 1
- [ ] sphere of radius 1
- [ ] pyramid of basis 1x1 and side 1
- [ ] cylinder of radius 1 and height 1

Others ?

**Comment by AlexisDrogoul** [comment]
We need to address the concern raised in #1563 before caching any complex shapes. Right now, caching does only support polygons, but it should be able to support polylines.

**Comment by AlexisDrogoul** [comment]
I close this issue as, basically: 

1. The most important enhancements have been added
2. Caching "common" shapes is probably not very interesting in terms of computation time

Reopen if you have any other suggestions.
