### ISSUE TITLE
Create a workflow for pull-requests

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#123]
**Is your request related to a problem? Please describe.**
As some of you may already know, I'd like to push developers to contribute to gama more through pull-requests. The great advantage of using pull-requests instead of directly committing to the main branch is that we can use tools to automate code review. Those tools can be used to check for code quality, comments or even potential bugs.

**Describe the improvement you'd like**
So to bootstrap this kind of workflow I propose that we start by integrating the reports of a tool I have been using recently for code quality and bug spotting which is called [spotbugs](https://spotbugs.readthedocs.io/en/latest/).
What I'd like us to have is:
- [x] A way to generate a complete report on the code base that would could run anytime
- [x] A way to check the diff between reports from a given branch and the main one
- [x] The diff report being automatically generated and "posted" in the pull-request so reviewers can check it easily
- [ ] If possible try to add the spotbugs plugin [fb-contrib](https://fb-contrib.sourceforge.net/) that includes many other bug patterns from the community (it's somewhat recommended by spotbugs themselves but I haven't tried yet)

This could be the base of a workflow including other tools later.

**Additional context**

If I'm mentioning diff and not incremental in that case is because it doesn't seem that `spotbugs` is able to produce incremental by itself (according to this old but still open [issue](https://github.com/spotbugs/spotbugs-maven-plugin/issues/56)). Though I've seen this [maven plugin](https://worksapplications.github.io/incremental-analysis/spotbugs-mojo.html) that may do the trick ?

For the output format of the tool, I'm not sure yet what are the possibilities. From the GUI I can save an analysis in an xml file that looks like [this](https://github.com/gama-platform/gama/files/14598206/spotbugs.results.txt), the maven plugin generates a website per plugin scanned which is not very convenient.

I've seen some [github actions](https://github.com/jwgmeligmeyling/spotbugs-github-action) that could do the trick, so maybe there's really not much for us to do here.

**Comment by RoiArthurB** [comment]
Ping @WoodenMaiden

**Comment by WoodenMaiden** [comment]
I can start this this evening after my classes :)

**Comment by lesquoyb** [comment]
Btw I wanted to ping you but seems like I can't because you're not part of the organization or something. Do you want me to send you an invitation again ?

**Comment by WoodenMaiden** [comment]
sure!

**Comment by lesquoyb** [comment]
As an alternative for a first try there's also [codacy](https://docs.codacy.com/repositories-configure/integrations/github-integration/) that seems very easy to integrate to check pull-requests.
We could start with this one and then add spotbugs later ?

**Comment by lesquoyb** [comment]
I went with [codescene](https://codescene.io/projects) to check the code quality. 
There is a general gama [dashboard](https://codescene.io/projects/51964/jobs/2214107/results?scope=month#code-health) and I've added the possibility to process incremental progress and publish them as quality checks on pull request.
So for example here is the result on my current big [pull request](https://github.com/gama-platform/gama/pull/133#pullrequestreview-1978648861)

**Comment by lesquoyb** [comment]
Reopening because even though spotbugs is working now it's still not very usable. To make it work correctly we should be able to:
- select the level of priority of bugs to be written in the report via an option, because 5000 is a bit too much
- for the part that is executed on pull-request, only the bugs that are new compared to the main branch should be displayed else it just doesn't make sense
- if there are any NEW bugs in a pull request, it should result in a failed review

**Comment by lesquoyb** [comment]
I made a very stupid python script that takes two xml output from spotbugs and produces a new one containing only the bugs that are new:
```
from lxml import etree


def identical_nodes(node1: etree.Element, node2: etree.Element):
    if node1.tag == node2.tag:
        for name, value in node1.items():
            if not ((name, value) in node2.items()):
                return False
        for subNode in node1:
            found = False
            for subNode2 in node2:
                if identical_nodes(subNode, subNode2):
                    found = True
                    break
            if not found:
                return False
        return True
    return False


if __name__ == '__main__':
    new_root = etree.parse(open("new.xml")).getroot()
    old_root = etree.parse(open("old.xml")).getroot()
    out_root = etree.Element("BugCollection")
    for element in new_root:
        if element.tag == "BugInstance":
            found = False
            for element2 in old_root:
                if identical_nodes(element, element2):
                    found = True
                    break
            if not found:
                out_root.append(element)
    out_content = etree.tostring(out_root)
    out_file = open("out.xml", "w")
    out_file.write(out_content.decode())
```
It is really inefficient but it doesn't really matter for our purpose, we could use it to create a diff between latest commit from the pull-request and the main branch

**Comment by lesquoyb** [comment]
As of now the workflow is almost finished but I'd like to add that currently the spotbugs report is marked as neutral:
![image](https://github.com/gama-platform/gama/assets/6374469/08ac30ee-917f-42d8-b5cb-c0350e0ed584)
And I think it would be more useful if it was failing in case there are any bugs found

**Comment by RoiArthurB** [comment]
> I made a very stupid python script that takes two xml output from spotbugs and produces a new one containing only the bugs that are new:

I implement the scripts you pushed inside the PR workflow, need to be tested

> As of now the workflow is almost finished but I'd like to add that currently the spotbugs report is marked as neutral:

I also changed the spotbugs publish action to the one you identified fixing precisely this need

@lesquoyb => It's all to be tested now :) 

---

> **note**: something else we completely forgot is to check if it's possible to add the fb-contrib plugin, with the gui program it's just a jar to add in a folder, but I have no idea if it's that easy with the maven plugin

Can you remind me what is was all about ?

**Comment by lesquoyb** [comment]
fb-contrib is a jar file containing additional rules for spotbugs to run, it's basically an extension for the software. In the gui version of spotbugs you just have to drop it into the plugin folder of the spotbugs installation for all the new rules to be added during the scan, but I don't know how it works for the maven version of spotbugs.
The jar is available [here](https://sourceforge.net/projects/fb-contrib/) and also on [maven](https://mvnrepository.com/artifact/com.mebigfatguy.fb-contrib/fb-contrib)

**Comment by lesquoyb** [comment]
Everything works now!
![Image](https://github.com/gama-platform/gama/assets/6374469/d3bc7ba1-94e3-46a2-a9d6-b73bde658b3d)
