### ISSUE TITLE
Enhancement: GamaMatrix as Apache Matrix

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1231]
```
Make GAMAMatrix and in particular GamaFloatMatrix and GamaIntMatrix as Apache RealMatrix.
For the moment, GAMA converts GAMAMatrix to RealMatrix to apply Apache operators on
them.
```

Original issue reported on code.google.com by `patrick.taillandier` on 2015-05-27 01:17:57

**Comment by AlexisDrogoul** [comment]
Hi,

I've taken a look and I have some reservations against this move. One is about the performances. Int and Real matrices in GAMA are really "fast" in that they are just wrappers around arrays. The second is about memory consumption, as an array of int will always be smaller than an array of float/double… 

I can understand the necessity, though, when doing matrices operations… So I have got mixed feelings about this.

Alexis

**Comment by AlexisDrogoul** [comment]
I close this issue now. Maybe we'll come back to it later, but right now the priority is to clean the backlog.
