### ISSUE TITLE
Open GL Display on Windows 8.1 

### ISSUE THREAD

**Issue by PA-PINON** [gama-platform/gama#1239]
What steps will reproduce the problem?
1.Open any model that uses a display
2.Try to excute an experiment (1), stop experiment (1) with the red buttom, execute again and same experiment (2).

What is the expected output? What do you see instead?
Need to close the display in experiment (1) to start the second experiment.

Please use labels and text to provide additional information.
github - gama 1.7 - windows 64bits 8.1

**Comment by AlexisDrogoul** [comment]
OK. The problem has been reproduced (on Windows and MacOS) and only appears when using the "red" button and relaunching an experiment afterwards. GAMA acts as if the displays were closed by the forced interruption, but they are not (it's simply that the simulation perspective is not reachable), and reopening the perspective opens them again but they seem to be unreachable from the view manager.
