### ISSUE TITLE
[OpenGl] weird animation stop when synchronising the display

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#124]
**Describe the bug**
I noticed that on the model `OBJ file drawing.gaml`, when switching to synchronized the animation stops suddenly, but the cycles are still running. As soon as I switch back to unsynch, the animation continues where it was, it seems like all the frames were buffered and waiting for some lock to be released. 

**Additional context**
What is also weird is that when it's released it doesn't "jump" to where it's supposed to be according to the current cycle but continues the animation at the same rate as before instead of catching up.
I used the `write` statements in the reflex and aspect of the object species and they are triggered as they should so the problem really is in the display

**Comment by AlexisDrogoul** [comment]
See commit https://github.com/gama-platform/gama/commit/c379aba692b426ae5c9efe862cd27da03e9e5347
