### ISSUE TITLE
Feature model for signal variables

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1243]
There is in GAMA a powerful type of variable that concerns the signal diffusion. However, if it is well documented (at least in the code, did not check in the documentation), there is a lack of examples to show how to use it. It will be very nice to have a very simple example (not the ant model that is a bit complex and that do not show all the possibilities of the signal variables) illustrating how to use this type of variables. 

Concerning the documentation, it is necessary to well explain the difference between the signal variable and the diffusion statement.

**Comment by mazarsju** [comment]
I just added a model that show a quick overview of how to use this type.
