### ISSUE TITLE
American/English spelling

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1244]
In GAMA, some operators/built-in variables use the American spelling and others the English one.
Examples:

English:
 - neighbours operator

American:
 - color built-in variable
 - skeletonize operator

In the future, I think we should try to be more consistent (always choose American spelling for example). For existing operators, we should maybe try to add the possibility to use both spelling (at least for neighbours one if we chose the American spelling).

**Comment by AlexisDrogoul** [comment]
Agree. 

Besides "neighbours" are there other examples ?

**Comment by AlexisDrogoul** [comment]
I have normally caught all the non-US English uses in the operators. Old forms are still functional but marked as deprecated. I have taken this occasion, too, for cleansing a bit the deprecated operators, which are normally now all in the same class. Additionally, I have proposed alternate names for ill-formed names (doing the same: moving the "old" form to DeprecatedOperators, marking them as deprecated in the doc, simply calling the new one).
