### ISSUE TITLE
agent index doesnt show up in draw statement

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1247]
Hi,

in a draw statement if I use int(name), nothing is drawn in the display
if I use draw name, it is then drawn in the display.

species stations
{
	
	rgb my_color <-#pink;
		aspect ram
	{
		
		draw shape color:my_color;
		draw int(name)  color:#black; //this statement draws nothing
		
	}
}
please check
thanks
Srirama

**Comment by AlexisDrogoul** [comment]
Hi,

`int(name)` will try to transform the name of the agent into an integer number. So basically it will be 0 most of the time as the default names will be name_of_species+index. To obtain the index of an agent, you better use `int(self)` instead. 

Cheers
Alexis

**Comment by sriramab** [comment]
Thank you, But int(self) in draw statement also does not work (does not draw anything)

**Comment by AlexisDrogoul** [comment]
Strange. Have you tried `string(int(self))` ?

**Comment by sriramab** [comment]
Oki. With string.. it works. Thanks
