### ISSUE TITLE
Pause a simulation. Click on parameter. Value changes...

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1248]
Open and launch any model of the library (e.g. in Features / ODE / SIR (ABM vs EBM).gaml.
Do a pause in the simulation.
Click on any parameter but the first one (e.g. 'Number of infected'). When I click on the 5, it takes the value 495. In fact, is I click on any parameter value, it takes the value of the first parameter.

GAM GIT MACOSX

**Comment by AlexisDrogoul** [comment]
I've passed 6 hours on this one with no result. Incomprehensible. I catch all the focus/unfocus events, all the displays of the values, the changes of the value and so on. But it seems that, at one point, the SWT event manager gets confused about the widget which receives the focus event, and I dont know why. Will continue to investigate, but it would be worth knowing if the same bug affects Windows / Ubuntu (if not, then the SWT implementation in MacOS X is probably the cause).

**Comment by hqnghi88** [comment]
Hi,
It didn't happen on windows 8.1.

**Comment by AlexisDrogoul** [comment]
Still present in the Mars version of GAMA. It doesn't seem to be present on Windows (can someone confirm on Windows 10 and/or Ubuntu ?). Somehow, SWT gets confused about which widget gets the initial focus.

**Comment by RCura** [comment]
Seems to work on Ubuntu with latest git version. Not sure the test to apply though :/
I launched a model, changed a parameter value (so, not default), clicked on start, waited some steps, clicked on pause and clicked on the parameter as to change it. It value (so, the one I entered myself before) doesn't change.

**Comment by AlexisDrogoul** [comment]
The ParameterExpandBar was automatically giving focus to its first componnent, which resulted in a collision of focus gain/loss when another component was chosen. SWT was somehow confused by these simultaneous events. Now the ParameterExpandBar does not try to focus automatically anymore.
To track down this bug, I had to temporarily disable the automated focusing of input fields when hovering them. It can be added again without harm, but it has been mentioned in #1339 as an annoyance, so maybe we could keep things like this.

The solution works for me, can you confirm (esp. @benoitgaudou) that it works also for you ?

**Comment by benoitgaudou** [comment]
I works now for me.
Thanks
