### ISSUE TITLE
Error : ArrayIndexOutOfBoundsException after have modify one line in a csv file

### ISSUE THREAD

**Issue by PA-PINON** [gama-platform/gama#1249]
Models : SampleData from genstar
gaml : sample_data_conversion 

- Execute expirement, it's OK. 
- Check number of people in file : resultingDistribution1.csv  - > e.g. : "60 agriculteur"
- Add a new line in csv file : includes/PICURS_People_SampleData.csv  e.g. : "51:60 true agriculteur"
- Try to execute again, now -> error : ArrayIndexOutOfBoundsException
- Delete the project without it delete in the disk -> i.e. : no check "Delete project contents on disk" 
- Re-import the same project. 
- Execute experiment -> it's OK 
- Check in file : resultingDistribution1.csv  - > we see now  "61 agriculteur" 

Gama 1.7, version Git.  Windows 8.1.  JDK 1.8

**Comment by AlexisDrogoul** [comment]
Is the new line added in GAMA (and, if yes, with which editor: text or table ?) ? Or is it added from somewhere else ?

**Comment by PA-PINON** [comment]
Yes it is when added in GAMA with table or text. 

When it added with Excel for example, no problem.

**Comment by AlexisDrogoul** [comment]
I have committed some changes that should fix the issue. Could you please verify it in your setup ?
