### ISSUE TITLE
[OpenGl] Unused linear and quadratic attenuation facets in positional light

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#125]
**Describe the bug**
The documentation of [light](https://gama-platform.org/wiki/ManipulateLight) mentions linear, quadratic and constant(e) attenuation for positional lights, but looking at the code, linear and quadratic seem to just be set and never used, and constant is not even set.
You can check that by playing with the model `Lightning.gaml` and changing the values of quadratic_attenuation and see no difference.

**Expected behavior**
The `constant_attenuation` facet is created and the quadratic, linear and constant attenuation are taken into account for diffusion calculation

**Comment by AlexisDrogoul** [comment]
I have add `constant_attenuation` to the facets, and taken into account all 3 types of attenuation in the computation of the lights in OpenGL. Please test !
