### ISSUE TITLE
kmeans is not recognized

### ISSUE THREAD

**Issue by yjonas83** [gama-platform/gama#1250]
Hi,

Gama does not recognized the 'kmeans' operator. Was it replaced by another one?

Many thanks.

**Comment by ptaillandier** [comment]
Hi,

Which version of GAMA are you using? I tested with the current  github
version and it is working.

Cheers,

Patrick

2015-06-16 14:36 GMT+02:00 yjonas83 <notifications@github.com>:

**Comment by yjonas83** [comment]
thanks,

i am using GAMA - V1.6.1 - downloaded from the old googlecode site.
Should i download it again from github or should I somehow connect github to the 'available software sites' list?

Best,
Yonatan,

**Comment by ptaillandier** [comment]
ok, you are using GAMA 1.6.1. So you cannot use the kmeans (Apache)
operator that will be included in GAMA 1.7. However, you can use the
k_means operator of the weka plug-in (see the attached model).

To install the plug-in:

In the Menu "Help" -> Install New Software
As work with, choose: Gama 1.6.1 Update Site -
https://gama-platform.googlecode.com/svn/update_site/

Then, "Extensions for GAMA 1.6.1" -> "Weka", then "Next", accept the
Licence and "Next" and Finish, and restart GAMA.

Cheers,

Patrick

2015-06-16 22:27 GMT+02:00 yjonas83 <notifications@github.com>:

**Comment by yjonas83** [comment]
thanks, it worked!

**Comment by yjonas83** [comment]
hi,

i got a similar problem with 'all_pairs_shortest_paths' - does it also require an extension?

Thanks
