### ISSUE TITLE
Saving using shortcut CTRL + S tries to build workspace but still waiting

### ISSUE THREAD

**Issue by PA-PINON** [gama-platform/gama#1251]
Same problem of issue number : #1240 

The problem is occasionally. Sometimes, i can save with ctrl+S but sometimes, this command build workspace. 

Moreover, when i want stop with red square bottom, sometimes it's impossible. I need to kill the processus manuelly. Sometimes i can stop with red bottom. 

Windows 8.1 Java 1.8 Gama 1.7 version Git

**Comment by AlexisDrogoul** [comment]
It is clearly a duplicate of #1240. I will close it for this reason (no need to have twice the same issue). I will however modify a bit #1240 to indicate that it also concerns Windows 8.1.
