### ISSUE TITLE
possibility to read GML files

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1252]
We already read shape files. I could be nice to have the possibility to read as well GML files (another classic GIS file format). As geotools offers a reader for this kind of files, it should be easy to implement it.

**Comment by ptaillandier** [comment]
Easy to do with geotools but requires to add a lot of libraries (jar), so I think that I will propose this feature in a dedicated plug-in (with KML file importation) once GAMA 1.7 released.

**Comment by AlexisDrogoul** [comment]
I completely agree with this solution. The addition of GML + KML files would in fact add something like 30 new dependencies to the GeoTools library we currently use and something like ~20 Mb of libraries. Better put them in a separate plugin !

**Comment by AlexisDrogoul** [comment]
Moved to https://github.com/gama-platform/gama.experimental/issues/7
