### ISSUE TITLE
Problem with Factoriel function in  GAMA 1.6.1

### ISSUE THREAD

**Issue by DamPhil** [gama-platform/gama#1254]
Hi, I got a problem with the factoriel function in GAMA 1.6.1 : 
with a number as 10, everything is okay, but with a big number a 25, the result isn't the one expected, it returns 2076180480, instead of 15511210043330985984000000...

The problem would be the result parameter which is an int instead of a long / double...

Thank you ! 

Damien

**Comment by ptaillandier** [comment]
it is due to the use of an int for the return type of the fact operator. I have changed it to double and committed it. So this issue is fixed in the GAMA developer version (hope Alexis didn't do any change yet).
