### ISSUE TITLE
comparing paths on graph

### ISSUE THREAD

**Issue by yjonas83** [gama-platform/gama#1255]
Hi,
It is not clear to me how to compare path lengths over a graph, I am doing it right now in a way which seems pretty crooked and also does not work all the time.
Let's say I have an agent moving on a graph. There are several targets and I want the agent to pick the target which the path leading to it on the graph is the shortest considering weights (not the one with the shortest Euclidean distance like with 'distance_to' operator).
How do I find the closest target considering the graph? I guess I should use some of the graph operators but I don't understand how.
Many thanks!
Yonatan

**Comment by AlexisDrogoul** [comment]
Hi,

It would be better to ask this question on the GAMA mailing-list (https://groups.google.com/forum/#!forum/gama-platform). The issues are reserved for bugs or enhancement requests regarding the platform itself (not a particular model).

Thanks ! 

Cheers
Alexis
