### ISSUE TITLE
OpenGL: rotating and blinking lines in displaying vector layers

### ISSUE THREAD

**Issue by annalisapg** [gama-platform/gama#1257]
to reproduce the problem:
1. load an area vector layer
2. try to query it in GAMA opengl display clicking right button

..some random lines connecting area boundary nodes will rotate and blink until a left click of the mouse.

This happens on GAMA 1.6.1.1 svn version on Ubuntu Linux (14.04 LTS) compiled under Eclipse 3.8.

![blinkinglines](https://cloud.githubusercontent.com/assets/8994407/8496890/0031a20a-2179-11e5-9d2c-84186eaba72c.png)

**Comment by AlexisDrogoul** [comment]
Hi,

Would it be possible to have the code that displays the agents (both the aspect of the agents and the code of the display) ? And can you reproduce it with a simple example that you could submit to the issue ? (I think it is possible to attach almost anything to an issue, despite GitHub specifying only "images").

Alexis

**Comment by annalisapg** [comment]
ok, it doesn' supports other than png, gif an jpg..

https://github.com/annalisapg/maritimeSimulation/blob/master/blinkingLines.gaml

simpleFinistere.shp is a shape area vector file; the click in any point of the area produces blinking and rotating lines until a left click

Many thanks,
Annalisa

**Comment by agrignard** [comment]
I close this issue as it's impossible to reproduce without the shapefile. Feel free to reopen it.
