### ISSUE TITLE
manipulation of ontology

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1261]
I know that some users are interested in using ontology in GAMA (in a model). It should be easy to add a new type "ontology" with several dedicated operators and the possibility to build one from an owl file.

**Comment by AlexisDrogoul** [comment]
This enhancement calls for a dedicated plugin (new type, new file type,…). Who is in ?

**Comment by AlexisDrogoul** [comment]
moved to https://github.com/gama-platform/gama.experimental/issues/6
