### ISSUE TITLE
Possibility to get the "upper" scope from the current scope (Java)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1265]
For the BDI plug-in, we need to access the "upper" scope (i.e. myself) from the current scope in Java. So adding to the IScope interface, a getUpperScope() (or another name) will help us a lot.

**Comment by AlexisDrogoul** [comment]
Hi,

There is no "upper scope". All the agents share the same scope in which they are stacked in their order of execution. What I have done instead is to add a method called `getAgentsStack()` to `IScope`, which returns an array of agents (from the first, i.e. the world, to the last, the current agent). The array is safe in that it is a temporary copy of the stack of agents, not the stack itself. 

Alexis
