### ISSUE TITLE
Accented characters not showing in 1.7 (git master)

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#1267]
In the parameters tab of an experiment, when some parameters contains accented letters, those are cut at the first accented character. See picture:
![gama_issue_accents](https://cloud.githubusercontent.com/assets/807703/9526158/ff620a32-4ce7-11e5-8ee3-10a35201ce5a.png)

--> **The first parameter should be `Année`**

It works fine in the monitors though, which is kinda weird. My files are correctly encoded in UTF-8.

**Comment by RCura** [comment]
In fact, there's a major bug here :frowning: 

Let's say I have those parameters :
parameter "Année debut" var: debut_simulation category: "Simulation"; // == 1
parameter "Année fin" var: fin_simulation category: "Simulation"; // == 2

With the accent bug, Gama will only display the first one (the latter being considered as the same variable), and give it the value of the second one. A screenshot so it's more clear :
![bug_1267](https://cloud.githubusercontent.com/assets/807703/9610374/6621a21a-50d9-11e5-970f-d6cb0f56ba6c.png)

So, the GUI parameter, although it appears at the place of "Année 1", is in fact "Année 2", and controls this variable.

**Comment by AlexisDrogoul** [comment]
I have been able to reproduce it. Will try to investigate this soon.

**Comment by AlexisDrogoul** [comment]
Fixed by bc54247cec019dda25194493742ae358c9da6cd9 . Unicode strings were not correctly parsed.
