### ISSUE TITLE
Batch : init being called too late

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#1273]
Hi,

There's a bug concerning the batch mode : it seems the batch isn't calling the init{} when it should, thus resulting in errors when having to output species values.

I made a minimal reproducible example here : https://gist.github.com/RCura/c1458ce6997da3cdca1a

These are the lines exposing the problem :

```
experiment "GUI" type:gui {
    parameter number_people var: number_people min: 100 max: 400 step: 50;  
    output {
        display "GUI" refresh: every(1) {
                chart "PPl" type: series {
                        data "Infected" value: people count (each.is_immune) color: #red;
                }
        }
    }
}

experiment 'Bugged' type: batch repeat: 5 keep_seed: true until: ( time > 1000 ) {  
    parameter number_people var: number_people min: 100 max: 400 step: 50;  
    permanent {
        display "Bugged" refresh: every(1) {
                chart "PPl" type: series {
                        data "Infected" value: people count (each.is_immune) color: #red;
                }
        }
    }
}

experiment 'Working' type: batch repeat: 5 keep_seed: true until: ( time > 1000 ) { 
    parameter number_people var: number_people min: 100 max: 400 step: 50;  
    permanent {
        display "Working" refresh: every(1) {
                chart "PPl" type: series {
                        data "Infected" value: nb_infected color: #red;
                }
        }
    }
}

```

The "GUI" and "Bugged" experiments are the same,  but GUI is working when "Bugged" throw an error : 
![capture du 2015-09-24 14 51 10](https://cloud.githubusercontent.com/assets/807703/10073801/ba76b464-62cb-11e5-9985-ac81e8a1170c.png)

This seems to be because the people species isn't defined when the batch experiment starts.

I found a little workaround by outputting a global variable instead of a species variable, see the last experiment "Working".

This is really troublesome, as the workaround can not always be used in a "real model".

I'm using gama dev version (git pulled roday)

**Comment by AlexisDrogoul** [comment]
Hi,

I have begun investigating this more closely, and I dont know exactly yet where to look. My (wild) guess is that the problem lies with the "permanent" outputs being initialized too soon compared to the "standard outputs". I will debug more closely…
 
Alexis

**Comment by AlexisDrogoul** [comment]
It seems this issue has popped up again, due to a serious regression in the "charts" code (posted some months ago by @pcaillou . Basically, to determine the type of chart to draw, the expression in `data` is evaluated at step 0, while the batch experiment has not created a simulation yet. I'm working on it, but I reopen the issue in the meantime.
