### ISSUE TITLE
Grid definition: do not allow to have both file and width/height facets

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1275]
It could be nice to forbid the definition of grid with both file facet and width/height facets, in order to avoid confusion in modelers mind.

grid cell file: a_file width: grid_size height: grid_size neighbours: 8

Benoit

**Comment by AlexisDrogoul** [comment]
Yep. Same problem than in #1311. A more thorough validation of grid facets seems necessary.

**Comment by AlexisDrogoul** [comment]
However, it is contradictory with the documentation, which gives an example of using width:, height: and file: together...

**Comment by AlexisDrogoul** [comment]
I've fixed both #1311 and this one in my code base. Will commit soon.

**Comment by AlexisDrogoul** [comment]
Fixed in 73fe1d303a4d504ef4b1c53e38c4e48775f61c36
