### ISSUE TITLE
Triangulate operator on regular shapefiles

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1276]
I have trouble to triangulate a geometry with holes, when it has been processed from very regular , parrallel geometry.
In the attached model, I want to triangulate a space created from a rectangle, on which I remove some obstacles. When the obstacles are parrallel to axes rectangle, I have bad triangulation (the holes are also triangulated), but when I change a little bit the obstacle shapfile to have obstacle that are no more parralel to axes, the triangulate works perfectly.
I attached a simple model, with the 2 shapefiles.

Benoit

Note : change the extension from png to zip to get the model and the data:
![testgraphbuilding](https://cloud.githubusercontent.com/assets/1555274/10190251/94b13eee-676b-11e5-855d-16ac76334384.png)

**Comment by ptaillandier** [comment]
I thinks I fixed it. Can you test it?
