### ISSUE TITLE
HTML editor for model description

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1278]
Hi

I have noticed that GAMA generates a blank html file when a new model is created. This html can be used to write detailed description of the model. However, there is no editor available to edit this html file from within gama. 

I would like to request an editor, probably with some eclipse plugin if that can be quicker. I installed HTML editor (WTP) Luna but could not get it to work. If any of you experienced member could help me in installing this plugin or other to be able to edit the html file.... that would be great!

Thanks,
Srirama

**Comment by AlexisDrogoul** [comment]
Has someone tried to install the HTML editor plugin of Eclipse in GAMA (from the WTP project) ? I dont know if it works well in GAMA 1.6.1, but I can install it in the development version (by adding the required dependencies to the run configuration). The result is disappointing. It is slow, heavy, not really sexy and creates a lot of conflicts over file content types and associations.

The nice (and lightweight) alternative I have found is CKEditor (https://marketplace.eclipse.org/content/eclipse-ckeditor). It works pretty well, offers a WYSIWYG editor, and seems to integrate perfectly within GAMA.

As soon as the plugin is installed in the run configuration, you can right-click on any .html file (and I guess it supports many other extensions, by the way) and choose Open with… > CKEditor. 

Tell me if you need more information ! I consider that this closes this issue, if you dont mind. Please reopen in case more detailed explanation are needed (I also updated the documentation to include this new plugin: https://github.com/gama-platform/gama/wiki/G__InstallingPlugins).
