### ISSUE TITLE
geometry_collection

### ISSUE THREAD

**Issue by yjonas83** [gama-platform/gama#1279]
Hi,
my GAMA does not recognize 'geometry_collection' operator.
running 1.6.1 on windows, spatialoperators is updated.

thanks!

**Comment by ptaillandier** [comment]
Hi,

Indeed, this operator is only available in the developer version and not in
1.6.1 (even with the spatial operator plug-in).
By the way, why do you need this operator?

Cheers,

Patrick

2015-10-13 9:06 GMT+02:00 yjonas83 <notifications@github.com>:

**Comment by yjonas83** [comment]
thanks!
I wanted to create a convex hull geometry from a group of agents, I assumed that the convex_hull oparator needs a geometry collection as an input, since the group of agents was not a valid one.
So how do I do it?
Yonatan.

**Comment by ptaillandier** [comment]
Hi,

You can use the convex_hull operator like this:

model convexhull


global {

geometry convex_hull_simple;

init {

create dummy number: 20;

convex_hull_simple <- convex_hull(polygon(dummy collect each.location));

}

}


species dummy {

aspect default {

draw circle(2) color: #blue;

}

}


experiment convexhull type: gui {

output {

display map_convex_hull_simple {

graphics "convex_hull_simple" {draw convex_hull_simple color: #pink;}

species dummy;

}

}

}

Cheers,

Patrick

2015-10-14 10:20 GMT+02:00 yjonas83 <notifications@github.com>:

**Comment by yjonas83** [comment]
thanks! working great!
