### ISSUE TITLE
Addition of an on_grid skill

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1280]
Hi,
In some training sessions, first models presented used agents on a grid.
And in tutorial we always add : a cell and a neighbour attributes for all agents (as it is mainly for programmatic purpose, it is often not so intuitive to explain.

We could add a "on_grid" skill to add at least the 2 attributes : 
- my_cell : the cell on which the agent is located
- neighbours : the neighbours cell (at distance 1 for example).

These two attributes should be modified when the location of the agent changes.

We could also imagine a way to locate by default agents at the center of their cell ...

This skill could mainly dedicated to beginner users.

What do you think ?

Cheers

Benoit

**Comment by sriramab** [comment]
I support this enhancement.

**Comment by ptaillandier** [comment]
I am ok with this. I have just one question: if I have two grids, what
my_cell/neighbours is going to return? Or maybe, should we add a way (a
variable) to specify the concerned grid?

In addition, we could add a variable:
 - neigbors_distance/neigbours_distance that will 1 by default and that
will modify the neighbours/neighbors variable when using the setter.

Cheers,

Patrick

2015-10-27 19:51 GMT+01:00 Srirama Bhamidipati <notifications@github.com>:

**Comment by benoitgaudou** [comment]
> I am ok with this. I have just one question: if I have two grids, what
> my_cell/neighbours is going to return? Or maybe, should we add a way (a
> variable) to specify the concerned grid?
>

We could have parametrized skill ??
species people skills: [on_grid<cell1>] { ... }
(we could also imagine to have :
species people skills: [moving<graph>] { ... } or
species people skills: [communicating<protocol>]) ....

Or we could have a by default (when only 1 grid is defined .... which is
the case most of the time):
species people skills: [on_grid] { ... }

that is able to know which is the defined grid.


> In addition, we could add a variable:
> - neigbors_distance/neigbours_distance that will 1 by default and that
> will modify the neighbours/neighbors variable when using the setter.
>

I agree


Cheers

Benoit

**Comment by AlexisDrogoul** [comment]
Hi,

The idea of parametrizing skills is quite interesting, although it might raise some problems (and will require a lot of new checks w.r.t. inheritance of skills, for instance, etc.). I’m not completely sure, however, that the syntax 'skills: [on_grid<cell1>]’ is easier to understand for newcomers than an explicit declaration of ‘cell1 my_cell -> {cell1 at location};’. The problems of skills (which should be solved with a better documentation — even an interactive one which would add the variables automatically in the model file) is that there are lots of « hidden » things (attributes, actions)…

Cheers
Alexis


> Le 28 oct. 2015 à 14:28, benoitgaudou <notifications@github.com> a écrit :
> 
> > I am ok with this. I have just one question: if I have two grids, what
> > my_cell/neighbours is going to return? Or maybe, should we add a way (a
> > variable) to specify the concerned grid?
> >
> 
> We could have parametrized skill ??
> species people skills: [on_grid<cell1>] { ... }
> (we could also imagine to have :
> species people skills: [moving<graph>] { ... } or
> species people skills: [communicating<protocol>]) ....
> 
> Or we could have a by default (when only 1 grid is defined .... which is
> the case most of the time):
> species people skills: [on_grid] { ... }
> 
> that is able to know which is the defined grid.
> 
> 
> > In addition, we could add a variable:
> > - neigbors_distance/neigbours_distance that will 1 by default and that
> > will modify the neighbours/neighbors variable when using the setter.
> >
> 
> I agree
> 
> 
> Cheers
> 
> Benoit
> 
> 
> >
> > Cheers,
> >
> > Patrick
> >
> > 2015-10-27 19:51 GMT+01:00 Srirama Bhamidipati <notifications@github.com>:
> >
> > > I support this enhancement.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/gama-platform/gama/issues/1280#issuecomment-151608186>
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gama-platform/gama/issues/1280#issuecomment-151750008>
> > .
> >
> —
> Reply to this email directly or view it on GitHub.
> 

--
Senior Researcher, UMI UMMISCO 209, IRD & UPMC, France.
--
alexis.drogoul@gmail.com | http://goo.gl/4ewFdJ
[Vietnam] +84915088155 [France] +33608698845
--
GAMA: http://gama-platform.org

**Comment by ptaillandier** [comment]
For GAMA 1.7, we just have introduced a new variable to cell agents called neighbors and that represents the neighbors at a distance of 1 of the cell. 
The usefulness and the pedagogical interest of a skill (or species facet) to facilitate the use of grid is still under debate.

**Comment by AlexisDrogoul** [comment]
I propose to close this issue as its consequences are a bit unclear  -- and its usefulness not really perceptible for me. Feel free to reopen to show which concrete benefit a user might have in having an `on_grid` behavior.
