### ISSUE TITLE
Bad file path in texture does not throw an error

### ISSUE THREAD

**Issue by AhmedLaatabi** [gama-platform/gama#1281]
When i put a bad file path in texture attribute, it doesn't throw an error.
Example:
aspect default {
	draw shape depth: height texture: ["../includs/pic.jpg"];
}
Gama should say that "../includs/pic.jpg" is not found, but the simulation is executed with an empty output.

**Comment by AlexisDrogoul** [comment]
There are two cases here:

- when the texture is a constant: we can (and probably we should) verify its existence and emit a warning if nothing is found
- when it is a variable (or something that has to be entered by the user) then we have no way to do it during compilation, but we should, in that case, emit a runtime error and (maybe) display the whole scene without the missing texture.

Would you be ok with these two solutions ?

**Comment by ptaillandier** [comment]
I am ok with these two solutions :)

**Comment by AhmedLaatabi** [comment]
this will certainly help Gama users, since i lost a lot of time looking for why my texture was not displayed, and Gama should simply say that my path is bad.

**Comment by AlexisDrogoul** [comment]
I've fixed this in the latest commit. However, I chose to only implement the second solution (i.e. a runtime error is shown when opening the display) and not the first one, which should not be specific to texture files, but to all files.
