### ISSUE TITLE
closest_to counter-intuitive performances

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#1284]
The performances of the `closest_to` are, at the very least, very strange and counter-intuitive.

See [attached model for a Minimal Reproducible Example](https://gist.github.com/RCura/c95a2e34579a9f7b901f)

#### Methodology ####

In the [linked model](https://gist.github.com/RCura/c95a2e34579a9f7b901f), I compare 3 methods for finding the nearest agent :  

1. `closestTo` : The *basic* way : `A closest_to B` (eg. B the *caller* trying to find the closest A (*called*))
2. `optimClosestTo` : The [optimized](https://github.com/gama-platform/gama/wiki/G__OptimizingModels#accelerate-closest_to-with-a-first-spatial-filtering) way : `(A at_distance n) closest_to B; if (A = nil){A closest_to B}` 
3.   `minDistance` : A stupid but effective method : `one_of(A at_distance min(B collect each distance_to self))`

I tried those methods using different use cases :

1. High number (10k) of B and low number (100) of A
2. Low number of B and high number of A
3. High number of A and B
4. Low number of A and B
5. High number of B trying to find the closest B (same species search)
6. Low number of B (same species search)

Here are the benchmarks (in milliseconds, the lower the better) :

>HighCallerLowCalled
>closestTo : 15689 / OptimClosestTo : 92551 / minDistance : 1541
>LowCallerHighCalled
>closestTo : 11 / OptimClosestTo : 773 / minDistance : 570
>HighCallerHighCalled
>closestTo : 1904 / OptimClosestTo : 258563 / minDistance : 44096
>LowCallerLowCalled
>closestTo : 1 / OptimClosestTo : 10 / minDistance : 3
>sameCallerSameCalledLow
>closestTo : 2 / OptimClosestTo : 6 / minDistance : 3
>sameCallerSameCalledHigh
>closestTo : 968 / OptimClosestTo : 73031 / minDistance : 40672

#### What can we see ? ####

1. the `OptimClosestTo` is **never** more efficient than `closestTo`.  This should be changed in the documentation
2. When applying to the same type of agent, `closest_to` is the most effective command.
3. _And... what's really interesting (*i.e.* bogging me)_ : When the agents to find are less than the agents calling, it's way more effective to use the `minDistance` method.

I realised that trying to optimize a (model I'm building)[https://github.com/RCura/transition8], that took 15-20 minutes to run with `closest_to`, and now, with several use of `minDistance` tricks, runs in ~ 1 minute. 

#### And so what ? ####

This benchmark presents a real issue with the optimisation of those distance operators. I don't know if it's a spatial index problem, but I think some work could be done here, as the use of the `minDistance` method is really counter-intuitive and ugly.

#### System informations ####
I ran this model on a Linux x64 (Ubuntu 15.04) computer, running the git master version of Gama (1.7 dev).

**Comment by ptaillandier** [comment]
Hi Robin, 

You analyze is very interesting. Note that the optimization documentation has been written for GAMA 1.6.1 and is maybe not very relevant for GAMA 1.7.

BTW, in order to test at the same time the impact of using geometries for agents (and not just points), I propose to you a new version of the model:

model closest_to
global {
	int nb_agents_min <- 100;
	int nb_agents_max <- 10000;
	bool agent1_use_geom <- false;
	bool agent2_use_geom <- false;
	geometry agent1_geom <- circle(3);
	geometry agent2_geom <- circle(5);
	
	
	
	reflex init_cycle {
		write "\n ---------------------------------------";
		write("******* CYCLE:" + cycle +" ******");
		
		if cycle =1 {
			agent1_use_geom <- true;
			agent2_use_geom <- false;
		} else if cycle =1 {
			agent1_use_geom <- true;
			agent2_use_geom <- false;
		}else if cycle =3 {
			agent1_use_geom <- true;
			agent2_use_geom <- true;
		} else if cycle > 3 {
			do pause;
		}
		
	}
	reflex HighCallerLowCalled {
		create agent1 number: nb_agents_max {
			if agent1_use_geom {shape <- copy(agent1_geom) at_location location;}
		}
		create agent2 number: nb_agents_min  {
			if agent2_use_geom {shape <- copy(agent2_geom) at_location location;}
		}
		write("\n******* HighCallerLowCalled ******");
		float thisTime1 <- machine_time;
		ask agent1 {do closestTo; do re;}
		float time1 <- machine_time;
		float thisTime2 <- machine_time;
		ask agent1 {do optimClosestTo; do re;}
		float time2 <- machine_time;
		float thisTime3 <- machine_time;
		ask agent1 {do minDistance; do re;}
		float time3 <- machine_time;
		float thisTime4 <- machine_time;
		ask agent1 {do basicClosestTo; do re;}
		float time4 <- machine_time;
		ask agent1 {do die;}
		ask agent2 {do die;}
		write("closestTo : " + round(time1 - thisTime1) +
		" / OptimClosestTo : "+round(time2 - thisTime2) +
		" / minDistance : " + round(time3 - thisTime3) + 
		" / basicClosestTo : " + round(time4 - thisTime4));
	}
	reflex LowCallerHighCalled {
		create agent1 number: nb_agents_min {
			if agent1_use_geom {shape <- copy(agent1_geom) at_location location;}
		}
		create agent2 number: nb_agents_max  {
			if agent2_use_geom {shape <- copy(agent2_geom) at_location location;}
		}
		write("\n******* LowCallerHighCalled ******");
		float thisTime1 <- machine_time;
		ask agent1 {do closestTo; do re;}
		float time1 <- machine_time;
		float thisTime2 <- machine_time;
		ask agent1 {do optimClosestTo; do re;}
		float time2 <- machine_time;
		float thisTime3 <- machine_time;
		ask agent1 {do minDistance; do re;}
		float time3 <- machine_time;
		float thisTime4 <- machine_time;
		ask agent1 {do basicClosestTo; do re;}
		float time4 <- machine_time;
		ask agent1 {do die;}
		ask agent2 {do die;}
		write("closestTo : " + round(time1 - thisTime1) +
		" / OptimClosestTo : "+round(time2 - thisTime2) +
		" / minDistance : " + round(time3 - thisTime3) + 
		" / basicClosestTo : " + round(time4 - thisTime4));
	}
	reflex HighCallerHighCalled {
		create agent1 number: nb_agents_max {
			if agent1_use_geom {shape <- copy(agent1_geom) at_location location;}
		}
		create agent2 number: nb_agents_max  {
			if agent2_use_geom {shape <- copy(agent2_geom) at_location location;}
		}
		write("\n******* HighCallerHighCalled ******");
		float thisTime1 <- machine_time;
		ask agent1 {do closestTo; do re;}
		float time1 <- machine_time;
		float thisTime2 <- machine_time;
		ask agent1 {do optimClosestTo; do re;}
		float time2 <- machine_time;
		float thisTime3 <- machine_time;
		ask agent1 {do minDistance; do re;}
		float time3 <- machine_time;
		float thisTime4 <- machine_time;
		ask agent1 {do basicClosestTo; do re;}
		float time4 <- machine_time;
		ask agent1 {do die;}
		ask agent2 {do die;}
		write("closestTo : " + round(time1 - thisTime1) +
		" / OptimClosestTo : "+round(time2 - thisTime2) +
		" / minDistance : " + round(time3 - thisTime3) + 
		" / basicClosestTo : " + round(time4 - thisTime4));
	}
	reflex LowCallerLowCalled {
		create agent1 number: nb_agents_min {
			if agent1_use_geom {shape <- copy(agent1_geom) at_location location;}
		}
		create agent2 number: nb_agents_min  {
			if agent2_use_geom {shape <- copy(agent2_geom) at_location location;}
		}
		write("\n******* LowCallerLowCalled ******");
		float thisTime1 <- machine_time;
		ask agent1 {do closestTo; do re;}
		float time1 <- machine_time;
		float thisTime2 <- machine_time;
		ask agent1 {do optimClosestTo; do re;}
		float time2 <- machine_time;
		float thisTime3 <- machine_time;
		ask agent1 {do minDistance; do re;}
		float time3 <- machine_time;
		float thisTime4 <- machine_time;
		ask agent1 {do basicClosestTo; do re;}
		float time4 <- machine_time;
		ask agent1 {do die;}
		ask agent2 {do die;}
		write("closestTo : " + round(time1 - thisTime1) +
		" / OptimClosestTo : "+round(time2 - thisTime2) +
		" / minDistance : " + round(time3 - thisTime3) + 
		" / basicClosestTo : " + round(time4 - thisTime4));
	}
	reflex sameCallerSameCalledLow {
		create agent1 number: nb_agents_min {
			if agent1_use_geom {shape <- copy(agent1_geom) at_location location;}
		}
		write("\n******* sameCallerSameCalledLow ******");
		float thisTime1 <- machine_time;
		ask agent1 {
			 closestNeighbor <- agent1 closest_to self;
			do re;
		}
		float time1 <- machine_time;
		float thisTime2 <- machine_time;
		ask agent1 {
			 closestNeighbor <- (agent1 at_distance 30) closest_to self;
			if (closestNeighbor = nil){ closestNeighbor <- agent1 closest_to self;}
			do re;
		}
		float time2 <- machine_time;
		float thisTime3 <- machine_time;
		ask agent1 {
			 closestNeighbor <- one_of( agent1 at_distance min(agent1 collect (each distance_to self)));
			do re;
		}
		float time3 <- machine_time;
		float thisTime4 <- machine_time;
		ask agent1 {do basicClosestTo; do re;}
		float time4 <- machine_time;
		ask agent1 {do die;}
		ask agent2 {do die;}
		write("closestTo : " + round(time1 - thisTime1) +
		" / OptimClosestTo : "+round(time2 - thisTime2) +
		" / minDistance : " + round(time3 - thisTime3) + 
		" / basicClosestTo : " + round(time4 - thisTime4));
	}
	reflex sameCallerSameCalledHigh {
		create agent1 number: nb_agents_max {
			if agent1_use_geom {shape <- copy(agent1_geom) at_location location;}
		}
		write("\n******* sameCallerSameCalledHigh ******");
		float thisTime1 <- machine_time;
		ask agent1 {
			 closestNeighbor <- agent1 closest_to self;
			do re;
		}
		float time1 <- machine_time;
		float thisTime2 <- machine_time;
		ask agent1 {
			 closestNeighbor <- (agent1 at_distance 30) closest_to self;
			if (closestNeighbor = nil){ closestNeighbor <- agent1 closest_to self;}
			do re;
		}
		float time2 <- machine_time;
		float thisTime3 <- machine_time;
		ask agent1 {
			 closestNeighbor <- one_of( agent1 at_distance min(agent1 collect (each distance_to self)));
			do re;
		}
		float time3 <- machine_time;
		float thisTime4 <- machine_time;
		ask agent1 {do basicClosestTo; do re;}
		float time4 <- machine_time;
		ask agent1 {do die;}
		ask agent2 {do die;}
		write("closestTo : " + round(time1 - thisTime1) +
		" / OptimClosestTo : "+round(time2 - thisTime2) +
		" / minDistance : " + round(time3 - thisTime3) + 
		" / basicClosestTo : " + round(time4 - thisTime4));
	}
}
entities {
	species agent1 {
		agent closestNeighbor;
		action basicClosestTo{
			closestNeighbor <- agent2 with_min_of (self distance_to self);
		}
		action closestTo {
			 closestNeighbor <- agent2 closest_to self;
		}
		action optimClosestTo{
			 closestNeighbor <- (agent2 at_distance 30) closest_to self;
			if (closestNeighbor = nil){ closestNeighbor <- agent2 closest_to self;}
		}
		action minDistance{
			 closestNeighbor <- one_of( agent2 at_distance min(agent2 collect (each distance_to self)));
		}
		action re {  closestNeighbor <- nil;}
	}
	species agent2;
}
experiment closest_to type: gui {
}

**Comment by ptaillandier** [comment]
Here a new version of the model in which I have fixed some errors (sorry :p ).
[closest_to.txt](https://github.com/gama-platform/gama/files/24447/closest_to.txt)

**Comment by RCura** [comment]
Alright, I did run some new benchmarks with [the following model](https://gist.github.com/RCura/de70ab070f96fd7c413f), as enhanced by @Patrick

#### Methods ####

##### Functions #####

1. `closestTo` : `agent2 closest_to self;`
2. `optimClosestTo` : `(agent2 at_distance 30) closest_to self; if (closestNeighbor = nil){ closestNeighbor <- agent2 closest_to self;}`
3. `minDistance` : `one_of( agent2 at_distance min(agent2 collect (each distance_to self)));}`
4. `basicClosestTo` : `agent2 with_min_of (self distance_to each);}`

##### Context #####
1. `HighCallerLowCalled` : 5000 Caller (agent1) and 50 agent2 (Called)
2. `LowCallerHighCalled` : 50 agent1 / 5000 agent2
3. `HighCallerHighCalled` : 5000 agent1 / 5000 agent2
4. `LowCallerLowCalled` : 50 agent1 / 50 agent2
5. `sameCallerSameCalledLow` : agent1 calling themselves, 50 agent1
6. `sameCallerSameCalledHigh` : agent1 calling themselves, 5000 agent1

##### Types of Geom #####
* *Cycle 0* :  agent1 and agent2 are both points
* *Cycle 1* : agent1 : polygon / agent1 : point
* *Cycle 2* : agent1 : point / agent2 : polygon
* *Cycle 3* : agent1 and agent2 are both polygons
* *Cycle 4* : idem Cycle 3

#### Results ####

Here are the results (in milliseconds, the lower the better) :

##### Raw data #####

| Cycle        | Function                 | ClosestTo | OptimClosestTo | minDistance | basicClosestTo |
|--------------|--------------------------|-----------|----------------|-------------|----------------|
| 0            | HighCallerLowCalled      | 5 500     | 13 286         | 461         | 72             |
|              | LowCallerHighCalled      | 3         | 100            | 55          | 66             |
|              | HighCallerHighCalled     | 297       | 26 559         | 4 285       | 5 633          |
|              | LowCallerLowCalled       | 2         | 2              | 2           | 3              |
|              | sameCallerSameCalledLow  | 7         | 1              | 1           | 2              |
|              | sameCallerSameCalledHigh | 159       | 7 722          | 4 016       | 5 001          |
| 1            | HighCallerLowCalled      | 8 320     | 47 047         | 2 357       | 315            |
|              | LowCallerHighCalled      | 19        | 377            | 220         | 259            |
|              | HighCallerHighCalled     | 4 702     | 109 499        | 19 943      | 26 276         |
|              | LowCallerLowCalled       | 192       | 644            | 110         | 200            |
|              | sameCallerSameCalledLow  | 70        | 497            | 111         | 186            |
|              | sameCallerSameCalledHigh | 62 900    | 728 877        | 1 071 057   | 1 307 117      |
| 2            | HighCallerLowCalled      | 16 814    | 114 922        | 1 055       | 309            |
|              | LowCallerHighCalled      | 63        | 1 535          | 278         | 331            |
|              | HighCallerHighCalled     | 6 692     | 227 221        | 26 727      | 31 705         |
|              | LowCallerLowCalled       | 646       | 1 701          | 1           | 1              |
|              | sameCallerSameCalledLow  | 607       | 1 651          | 1           | -              |
|              | sameCallerSameCalledHigh | 1 484     | 157 247        | 4 307       | 5 020          |
| 3            | HighCallerLowCalled      | 15 183    | 342 970        | 14 570      | 17 740         |
|              | LowCallerHighCalled      | 914       | 11 080         | 11 162      | 12 809         |
|              | HighCallerHighCalled     | 99 459    | 1 295 466      | 1 111 570   | 1 288 853      |
|              | LowCallerLowCalled       | 98        | 3 157          | 112         | 187            |
|              | sameCallerSameCalledLow  | 201       | 3 348          | 111         | 185            |
|              | sameCallerSameCalledHigh | 76 312    | 1 170 847      | 1 078 034   | 1 316 701      |
| 4            | HighCallerLowCalled      | 42 368    | 676 479        | 17 513      | 18 158         |
|              | LowCallerHighCalled      | 996       | 13 810         | 11 146      | 13 176         |
|              | HighCallerHighCalled     | 107 846   | 1 637 930      | 1 124 545   | 1 298 193      |
|              | LowCallerLowCalled       | 735       | 7 125          | 116         | 195            |
|              | sameCallerSameCalledLow  | 1 202     | 6 255          | 114         | 189            |
|              | sameCallerSameCalledHigh | 83 208    | 1 539 968      | 1 106 644   | 1 337 424      |
| Mean         |                          | 17 900    | 271 577        | 187 021     | 222 877        |
| Sum          |                          | 536 999   | 8 147 323      | 5 610 624   | 6 686 306      |
| TimesFastest |                          | 18        | 2              | 9           | 5              |
| TimesLongest |                          | 1         | 25             | 0           | 4              |

*(Notice that all that test did run for like __6 hours__)*

##### Relative times #####
(The number is the ratio of time spend relatively to the fastest function : 1 means that this function was the fastest, and 2 means that this function took twice the time of the best other function for this case)

| Cycle | Function                 | ClosestToRel | OptimClosestToRel | minDistanceRel | basicClosestToRel |
|-------|--------------------------|--------------|-------------------|----------------|-------------------|
| 0     | HighCallerLowCalled      | 76           | 185               | 6              | 1                 |
|       | LowCallerHighCalled      | 1            | 33                | 18             | 22                |
|       | HighCallerHighCalled     | 1            | 89                | 14             | 19                |
|       | LowCallerLowCalled       | 1            | 1                 | 1              | 2                 |
|       | sameCallerSameCalledLow  | 7            | 1                 | 1              | 2                 |
|       | sameCallerSameCalledHigh | 1            | 49                | 25             | 31                |
| 1     | HighCallerLowCalled      | 26           | 149               | 7              | 1                 |
|       | LowCallerHighCalled      | 1            | 20                | 12             | 14                |
|       | HighCallerHighCalled     | 1            | 23                | 4              | 6                 |
|       | LowCallerLowCalled       | 2            | 6                 | 1              | 2                 |
|       | sameCallerSameCalledLow  | 1            | 7                 | 2              | 3                 |
|       | sameCallerSameCalledHigh | 1            | 12                | 17             | 21                |
| 2     | HighCallerLowCalled      | 54           | 372               | 3              | 1                 |
|       | LowCallerHighCalled      | 1            | 24                | 4              | 5                 |
|       | HighCallerHighCalled     | 1            | 34                | 4              | 5                 |
|       | LowCallerLowCalled       | 646          | 1701              | 1              | 1                 |
|       | sameCallerSameCalledLow  | 607          | 1651              | 1              | 1                 |
|       | sameCallerSameCalledHigh | 1            | 106               | 3              | 3                 |
| 3     | HighCallerLowCalled      | 1            | 24                | 1              | 1                 |
|       | LowCallerHighCalled      | 1            | 12                | 12             | 14                |
|       | HighCallerHighCalled     | 1            | 13                | 11             | 13                |
|       | LowCallerLowCalled       | 1            | 32                | 1              | 2                 |
|       | sameCallerSameCalledLow  | 2            | 30                | 1              | 2                 |
|       | sameCallerSameCalledHigh | 1            | 15                | 14             | 17                |
| 4     | HighCallerLowCalled      | 2            | 39                | 1              | 1                 |
|       | LowCallerHighCalled      | 1            | 14                | 11             | 13                |
|       | HighCallerHighCalled     | 1            | 15                | 10             | 12                |
|       | LowCallerLowCalled       | 6            | 61                | 1              | 2                 |
|       | sameCallerSameCalledLow  | 11           | 55                | 1              | 2                 |
|       | sameCallerSameCalledHigh | 1            | 19                | 13             | 16                |
| Mean  |                          | 49           | 160               | 7              | 8                 |


#### Analysis ####

1. The `OptimClosestTo` method is **never** the most efficient - it is, on average, 160 times longer than the best other method - This should just not be used
2. When involving polygon geometries, the `closestTo` method is almost always the most efficient.
3. When calling within the same species of agents, wathever their geometries, the `closestTo` method is faster.
4. In the particular case of having HighCallerLowCalled, it is *always* more efficient to use `basicClosestTo` 

#### Proposal ####

Could those results be included in the code somehow ? I mean the `closest_to` method could be redefined, with a test considering those use case (I could try to benchmark a ratio (or threshold number) between caller and called) so that the base method always use the most efficient function.

For my model, which is in the HighCallerLowCalled use case, I'll use the `basicClosestTo` method, but this is a trick, and I'm sure the optimisation could be, at least partially, done with a few lines of tests inside the `closest_to` function.

**Comment by AlexisDrogoul** [comment]
Good job ! And yes, I agree with your conclusion, although we have to be extra careful when doing such an addition: there are cases (I have no immediate examples, but maybe if you use an expression like ’(species_A + (species_B where some_test) + species_C) closest_to self’) where simply counting the number of agents (and then whether or not the « meta-species » on the left is larger than the species on the right) can be long depending on the condition used, so maybe we might not want to do it every time. We have to remember that using a species or a subset of a species in the left member of closest_to is just one of the use cases. 

Regarding the ‘optimClosestTo’, it is quite logical (in 1.7) to have not so good results as the spatial optimization (the ’trick’) is already included in the algorithm now. So, basically, you do the filtering 2 times now instead of one. To worsen things, when doing this filtering, you fall in a branch of the algorithm where the optimization we use with species in the left member is lost (you’re just in a ‘normal’ case of a list of agents). The doc will need to be updated to reflect this, you’re right.

I will see what to do to improve the code — thanks a lot for your comprehensive tests ! 

Cheers
Alexis




> Le 31 oct. 2015 à 21:16, Robin Cura <notifications@github.com> a écrit :
> 
> Alright, I did run some new benchmarks with the following model, as enhanced by @Patrick
> 
> Methods
> 
> Functions
> 
> 	• closestTo : agent2 closest_to self;
> 	• optimClosestTo : (agent2 at_distance 30) closest_to self; if (closestNeighbor = nil){ closestNeighbor <- agent2 closest_to self;}
> 	• minDistance : one_of( agent2 at_distance min(agent2 collect (each distance_to self)));}
> 	• basicClosestTo : agent2 with_min_of (self distance_to each);}
> Context
> 
> 	• HighCallerLowCalled : 5000 Caller (agent1) and 50 agent2 (Called)
> 	• LowCallerHighCalled : 50 agent1 / 5000 agent2
> 	• HighCallerHighCalled : 5000 agent1 / 5000 agent2
> 	• LowCallerLowCalled : 50 agent1 / 50 agent2
> 	• sameCallerSameCalledLow : agent1 calling themselves, 50 agent1
> 	• sameCallerSameCalledHigh : agent1 calling themselves, 5000 agent1
> Types of Geom
> 
> 	• Cycle 0 : agent1 and agent2 are both points
> 	• Cycle 1 : agent1 : polygon / agent1 : point
> 	• Cycle 2 : agent1 : point / agent2 : polygon
> 	• Cycle 3 : agent1 and agent2 are both polygons
> 	• Cycle 4 : idem Cycle 3
> Results
> 
> Here are the results (in milliseconds, the lower the better) :
> 
> Raw data
> 
> Cycle	Function	ClosestTo	OptimClosestTo	minDistance	basicClosestTo
> 0	HighCallerLowCalled	5 500	13 286	461	72
> LowCallerHighCalled	3	100	55	66
> HighCallerHighCalled	297	26 559	4 285	5 633
> LowCallerLowCalled	2	2	2	3
> sameCallerSameCalledLow	7	1	1	2
> sameCallerSameCalledHigh	159	7 722	4 016	5 001
> 1	HighCallerLowCalled	8 320	47 047	2 357	315
> LowCallerHighCalled	19	377	220	259
> HighCallerHighCalled	4 702	109 499	19 943	26 276
> LowCallerLowCalled	192	644	110	200
> sameCallerSameCalledLow	70	497	111	186
> sameCallerSameCalledHigh	62 900	728 877	1 071 057	1 307 117
> 2	HighCallerLowCalled	16 814	114 922	1 055	309
> LowCallerHighCalled	63	1 535	278	331
> HighCallerHighCalled	6 692	227 221	26 727	31 705
> LowCallerLowCalled	646	1 701	1	1
> sameCallerSameCalledLow	607	1 651	1	-
> sameCallerSameCalledHigh	1 484	157 247	4 307	5 020
> 3	HighCallerLowCalled	15 183	342 970	14 570	17 740
> LowCallerHighCalled	914	11 080	11 162	12 809
> HighCallerHighCalled	99 459	1 295 466	1 111 570	1 288 853
> LowCallerLowCalled	98	3 157	112	187
> sameCallerSameCalledLow	201	3 348	111	185
> sameCallerSameCalledHigh	76 312	1 170 847	1 078 034	1 316 701
> 4	HighCallerLowCalled	42 368	676 479	17 513	18 158
> LowCallerHighCalled	996	13 810	11 146	13 176
> HighCallerHighCalled	107 846	1 637 930	1 124 545	1 298 193
> LowCallerLowCalled	735	7 125	116	195
> sameCallerSameCalledLow	1 202	6 255	114	189
> sameCallerSameCalledHigh	83 208	1 539 968	1 106 644	1 337 424
> Mean		17 900	271 577	187 021	222 877
> Sum		536 999	8 147 323	5 610 624	6 686 306
> TimesFastest		18	2	9	5
> TimesLongest		1	25	0	4
> (Notice that all that test did run for like 6 hours)
> 
> Relative times
> 
> (The number is the ratio of time spend relatively to the fastest function : 1 means that this function was the fastest, and 2 means that this function took twice the time of the best other function for this case)
> 
> Cycle	Function	ClosestToRel	OptimClosestToRel	minDistanceRel	basicClosestToRel
> 0	HighCallerLowCalled	76	185	6	1
> LowCallerHighCalled	1	33	18	22
> HighCallerHighCalled	1	89	14	19
> LowCallerLowCalled	1	1	1	2
> sameCallerSameCalledLow	7	1	1	2
> sameCallerSameCalledHigh	1	49	25	31
> 1	HighCallerLowCalled	26	149	7	1
> LowCallerHighCalled	1	20	12	14
> HighCallerHighCalled	1	23	4	6
> LowCallerLowCalled	2	6	1	2
> sameCallerSameCalledLow	1	7	2	3
> sameCallerSameCalledHigh	1	12	17	21
> 2	HighCallerLowCalled	54	372	3	1
> LowCallerHighCalled	1	24	4	5
> HighCallerHighCalled	1	34	4	5
> LowCallerLowCalled	646	1701	1	1
> sameCallerSameCalledLow	607	1651	1	1
> sameCallerSameCalledHigh	1	106	3	3
> 3	HighCallerLowCalled	1	24	1	1
> LowCallerHighCalled	1	12	12	14
> HighCallerHighCalled	1	13	11	13
> LowCallerLowCalled	1	32	1	2
> sameCallerSameCalledLow	2	30	1	2
> sameCallerSameCalledHigh	1	15	14	17
> 4	HighCallerLowCalled	2	39	1	1
> LowCallerHighCalled	1	14	11	13
> HighCallerHighCalled	1	15	10	12
> LowCallerLowCalled	6	61	1	2
> sameCallerSameCalledLow	11	55	1	2
> sameCallerSameCalledHigh	1	19	13	16
> Mean		49	160	7	8
> Analysis
> 
> 	• The OptimClosestTo method is never the most efficient - it is, on average, 160 times longer than the best other method - This should just not be used
> 	• When involving polygon geometries, the closestTo method is almost always the most efficient.
> 	• When calling within the same species of agents, wathever their geometries, the closestTo method is faster.
> 	• In the particular case of having HighCallerLowCalled, it is always more efficient to use basicClosestTo
> Proposal
> 
> Could those results be included in the code somehow ? I mean the closest_to method could be redefined, with a test considering those use case (I could try to benchmark a ratio (or threshold number) between caller and called) so that the base method always use the most efficient function.
> 
> For my model, which is in the HighCallerLowCalled use case, I'll use the basicClosestTo method, but this is a trick, and I'm sure the optimisation could be, at least partially, done with a few lines of tests inside the closest_to function.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Senior Researcher, UMI UMMISCO 209, IRD & UPMC, France.
--
alexis.drogoul@gmail.com | http://goo.gl/4ewFdJ
[Vietnam] +84915088155 [France] +33608698845
--
GAMA: http://gama-platform.org

**Comment by ptaillandier** [comment]
As point out by Robin's experiments, the new version of the closest_to operator is well optimized for all cases, except for the one where there are many callers (applying the closest_to operator) and low number of called (closest_to among these agents). For this case, a possible optimization consists in replacing the line:
called closest_to a_caller;
by:
called with_min_of (a_caller distance_to each);

As it is very difficult to automatically detect this case, we propose to just document this optimisation trick.

**Comment by mazarsju** [comment]
Updated in OptimizingModels
