### ISSUE TITLE
Scroll for zoom in/out does not work in Windows environment.

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1291]
CF title.

**Comment by AlexisDrogoul** [comment]
The "Display all" tag is being mentioned; does it mean it affects equally the Java2D and the OpenGL displays ?

**Comment by mazarsju** [comment]
Yes it does... Same behavior.

**Comment by AlexisDrogoul** [comment]
Beside the particular case of a dysfunctional mouse (which seemed to have caused this issue report), I have committed (in c200c6b09467a48542e18938db8bdef45a1054fd) a permanent fix for erratic behaviors of the scrolling wheel. Please test.
