### ISSUE TITLE
Step value changed in init

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1293]
Hi everyone, 
I know that normally a step should'nt be declared in the init section but before in the global section. But i find something a bit interesting, that maybe is already fixed as I'm in 1.6.1 . In my model, I import an other model, which has already a step value equals to a month. In the init of the new model, I change the value of the step to 1 day. During the experiments, the dynamics is the one for a month step value but in the simulated time, it is considered as if it was for a one day value. 
Maybe something should be changed, because, even if it is understandable in terms of algorithms and error, it can be problematic. 

Thank you !

**Comment by AlexisDrogoul** [comment]
Hi,

I'm having difficulties understanding this issue. What do you mean by "the dynamics is the one for a month step value but in the simulated time, it is considered as if it was for a one day value. " ?

**Comment by dphilippon** [comment]
Hi,
well that was exactly my problem, to make it clear... If I write in the global section a step of one month, and in the init part I write a step of one day, when I launch an experiment, I got the dynamics of a one-month step model, but the interface of GAMA (In the simulate time) show me a step value of 1 day, so each step will increment the "Simulated Time" (present in the interface) by one day, but the dynamics are done for one month.

**Comment by AlexisDrogoul** [comment]
Would it be possible to provide a simple model that reproduces this behavior ?

**Comment by dphilippon** [comment]
Of course... 
The fact is that actually, the value of a step can be defined inside the init but if we have parameters related to the step, their values will be related to the previous value of the step ... So we can have dynamics or values of a previous value of the step while having step with an other value.


[error_step.zip](https://github.com/gama-platform/gama/files/67862/error_step.zip)

**Comment by AlexisDrogoul** [comment]
All right. This behavior is completely normal. You compute `rate` **before** you assign `step` a new value. And `rate` does not depend on the value of `step` anymore once it has been computed. If you want it to be dynamically dependent on the value of `step`, then you have to define it as a function, e.g.
`	float rate -> {10/(step/#day)};`

I close this issue, then.
