### ISSUE TITLE
Problem for Incremental Model 6

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1296]
Incoherence during the simulation (see screenshot)

![image1](https://cloud.githubusercontent.com/assets/12977635/11032012/106896e0-870b-11e5-8e93-28ae4a17f17b.png)

**Comment by mazarsju** [comment]
The infected persons inside building are not recorded :
The list "people_in_building" ```list<people_in_building> list_people_in_buildings update: (building accumulate each.people_inside) where (not dead(each));``` is always empty... Problem with the accumulate operator ?

**Comment by ptaillandier** [comment]
Hi,

I think that the problem is not coming from the accumulate operator but
more on the way the multi-level feature is used in this model.

Cheers,


Patrick

2015-11-11 10:37 GMT+01:00 mazarsju <notifications@github.com>:

**Comment by mazarsju** [comment]
people_inside is correct. I really think the problem comes from the accumulate operator (same problem in the Toy models "Infection", the list "hst" is always null...)

**Comment by ptaillandier** [comment]
Hi,

It seems to work now (maybe someone fixed the issue concerning the accumulate operator). Can you test it and close it if this issue does not exist anymore?

**Comment by AlexisDrogoul** [comment]
Any progress on this one ? It works well on my computer too. To my knowledge, nobody has fixed anything recently on "accumulate". So maybe we are facing the same obscure bug as the one described in #1290

**Comment by mazarsju** [comment]
Yes it's the same bug as #1290. I close this issue.
