### ISSUE TITLE
OpenGL dragging

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1297]
The OpenGL dragging should always be orthogonal to the screen plane (it is not the case after a rotation...). The 3D navigation would be much easier that way.

**Comment by agrignard** [comment]
The actual implementations are the arcball and the freefly camera which work like in google earth for example. I am not sure to understand what you mean by "should always be orthogonal". You can have a look for example at the googleearth camera and you will see that the Gama one behave more or less the same. I am not sure of what would be the result if the dragging is always orthogonal to the screen plane.

**Comment by mazarsju** [comment]
Sorry, it's always difficult to explain 3D with words... Maybe those two screenshot will illustrate more the problem (I'm talking only about the arcball here) :

This is the "correct" behaviour of the dragging, according to me. The 3D figure turns the same way as in google earth, as if it was in a big invisible sphere that we just flip with the hand.
![bien](https://cloud.githubusercontent.com/assets/12977635/11063056/8892135e-87e6-11e5-921e-98a4a623eb46.png)

And this is the behaviour after a rotation transformation (with a Ctrl+Left click). I think this behaviour is not very user friendly...
![pasbien](https://cloud.githubusercontent.com/assets/12977635/11063171/55e57102-87e7-11e5-8781-b291a30967fa.png)

**Comment by agrignard** [comment]
Could be quite "easy" to solve by working on this method moveXYPlan2() in the arcball camera.

It should move in the plan orthogonal to the lookposition vecteur.

Now the camera is only moving in the XY plan which is definitly not the best behavior...

**Comment by agrignard** [comment]
It can be more or less considered as fixed with the fixing of the issue 1568.

**Comment by AlexisDrogoul** [comment]
The simplification of moveXYPlan seems to do the trick. We can close this one, too, well done.

**Comment by mazarsju** [comment]
Is it, really ? I'm really not convinced... How can you see your world from the side with the current ArcBall ? 
Using the "Rotate scene" ? This is really not an intuitive way to do so, and once you have used the "Rotate scene", all the rotation / translation are completely not possible to use properly.

**Comment by AlexisDrogoul** [comment]
You can rotate a model using alt and the left and right  arrows. Navigating
in models is already a bit complex,  let's not add another layer of
complexity...

**Comment by mazarsju** [comment]
Ok I didn't knew about Alt + arrow.

Here is an image showing the behavior expected. This behavior is working when no rotation and no transformation have been done. But as soon as we combine those transformations, it becomes impossible to handle very soon. I want those behaviors to be the same, whatever was the transformations before.

![image1](https://cloud.githubusercontent.com/assets/12977635/13697716/ee9e580e-e7a1-11e5-803a-edc195633bed.png)

(the orange sphere is the world).

**Comment by agrignard** [comment]
Mmm complex issue. I think it's a bit like tastes and colors. it's a choice
that has been made it can be discussed but it's working. It is "more or
less" inspired by the Google Earth camera but maybe the difference is that
most of the time the "world" we observe in GAMA is a 2D plan and not a
sphere like the earth of google earth.

Maybe it is because I have implemented it that I am the only one to know
how to make it works but I have no problem to go anywhere in my model, once
you know the good key.

Quiet hard to explain by mail indeed... maybe it can be a good idea to mix
the arcball and the freefly to really have the same camera as the one in
google earth. see issue #1618

**Comment by mazarsju** [comment]
I have changed the camera navigation a bit (just for the mouse for the moment, the navigation with keyboard is still the same). I find it much more easy to manipulate. Feel free to share what do you think of it before a make this change for the keyboard.

**Comment by agrignard** [comment]
I tried it quickly it looks ok

**Comment by mazarsju** [comment]
I pushed my modifications. It seems to work nicely, feel free to share what you think. Here is a recapitulation of the changes I made :
- visual helper when using a rotation (this visual helper can be disable in the openGL preferences)
- all the transformations used are based on the spherical coordinates as they are described here : http://mathworld.wolfram.com/SphericalCoordinates.html
- alt + arrow has been disabled (some non harmful works are in progress to use this command in order to turn the upVector, but some problems still occurs (after doing a translation / rotation), so I decided to remove it for the moment).
- when phi <= 0, the value is automatically changed to 0.1. When phi >=180, the value is automatically changed to 179.9 (that "blocks" the camera on the poles, witch can seems weird, but this problem is related to the SphericalCoordinates, and the Arcball philosophy. At least the camera is stable, there are no "weird" behaviors anymore)
- if you want to revert the upVector, you can use the key "f" ("flip").
- for those who has a keypad, you can make quick rotation using the keypad numbers "2", "4", "6" and "8".
- click and click+ctrl has been improved (same as arrow and shift+arrow)

**Comment by agrignard** [comment]
nice job

**Comment by agrignard** [comment]
quickly some remark
- In the visual helper what is the point of the white line?
-The size of the green sphere is sometime too big, what about a gray color (more neutral)? 
- 2 and 8 are not working after few rotation
- Could be nice to draw a bit like what you did on the Z axis in white the current axis rotation
- a very small details when you drag and the tape on cmd to arcball (still with mouse on) the helper does not appear

**Comment by mazarsju** [comment]
Thanks for your remarks Arnaud.

The white line is displayed to show you until when you can increase/decrease the phi angle. It is the "pole" of your arcBall.

2 and 8 are not working when you try to overpass the pole of your arcBall. I'll try one more time to find a solution, but this is not an easy one...

What rotation axis do you want to be displayed ? Something like :
- when you Shift+up arrow a horizontal line is displayed ?
- when you Shift+up+left arrow an oblique line is displayed ?

Ok for the last point, I'll try to improve it.

**Comment by agrignard** [comment]
@mazarsju is there a place where we can find the final documentation of the different option for the camera?

**Comment by agrignard** [comment]
ok I think i found it

http://vps226121.ovh.net/references#Displays

sorry
