### ISSUE TITLE
Parameter not working with explicit create in experiment

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#130]
**Describe the bug**
When the experiment explicitly overload the ``_init_`` action to create a simulation parameters are not working anymore. It may be relatated to discussion #63

**To Reproduce**
copy-past this simple example model:
```
global {
	
	int nb <- 0 parameter:true;
	
	init { create o number:nb; write sample(nb);}
	
}

species o {}

experiment explicitinit {
	action _init_ {
		create simulation with:[name::"supercoolname"];
	}
}

experiment implicitinit {}
```
launch both experiment
edit: change the value of ``nb`` in the parameter panel 
Reload the simulation 
variable ``nb`` do not change with explicit init action

**Expected behavior**
either to warn modeler or to turn parameter active even with explicit _init_ action in experiment

**Additional context**
hence, all parameter of the pedestrian model examples are disable

**Comment by AlexisDrogoul** [comment]
Sorry -- I don't understand the issue. When I launch both experiments, I have the same result, with the difference that one is name `supercoolname` and not the other, but the parameter `nb` is displayed in both cases.

**Comment by chapuisk** [comment]
@AlexisDrogoul if you change the value of the parameter in UI and reload simulation, the value won't change in the supercoolname simulation !

**Comment by AlexisDrogoul** [comment]
Actually, if one uses a `create simulation` in a reflex in the experiment, the simulation is created with a value of `10` when launched, but after that it is created with 0. So the problem is that it seems to be the call to `create` that bypasses the UI parameters.

**Comment by AlexisDrogoul** [comment]
I have identified and -- normally -- fixed the problem in https://github.com/gama-platform/gama/commit/9d1a9d435c04e70d862dbae6fd1996c88adcbfd2. Please test as this is quite a sensitive area !
