### ISSUE TITLE
Agents statement: about required facet name

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1300]
In a display, we can display agents using the statement "agents" instead of species.
This statement requires a "name" statement.

But when it is omitted, the model seems to compile, but sometimes the error appears or only the symbol of old error appears.

See the model below:
global { }
species people {}

experiment TestAgents type: gui {
	output { 
		display d {
			agents value: people;
		}
	}
}

**Comment by AlexisDrogoul** [comment]
The model compiles but can't run (a NPE is raised somewhere). I guess I should enforce the use of the name facet in the validation.
