### ISSUE TITLE
Hovering the status control can lead to a freeze (needing a restart) under Windows

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1303]
The information bubble just under the "XX cycles elapsed" button sometime does not appear anymore with the mouse hover (same problem for the bar to set the minimum duration of a cycle)... I have not found yet how to be sure to reproduce this bug, but it occurs quite often on my computer (once it's happen, I have to restart the application to make the mouse hover work again)

**Comment by AlexisDrogoul** [comment]
Well, at one point, this information hover was not working at all under Windows, so I guess it is a progress :) I will try to investigate, but without a repeatable use-case, it will be difficult.

**Comment by AlexisDrogoul** [comment]
Did this issue pop up again recently ? If yes, it might be probably related to #1353 and #1625 .

**Comment by hqnghi88** [comment]
Hi, 
I must say yes, but i cant tell the exact steps to reproduce it, but yes it pop up frequently. More than "hover", it should be the stop-working of status block, i mean, the status bar won't change to any state if it occurs (some time at "Building agent", some time " at xx step" sometime at "Experiment ready"....).

**Comment by AlexisDrogoul** [comment]
And does this "blocking" occur only when you "hover" it or click on it ?

**Comment by hqnghi88** [comment]
Dear Alexis,
I have tested again. After clicked on experiment button, quickly hover the status bar, do it sometime and issue will occurs. I dont need to click on it.

**Comment by AlexisDrogoul** [comment]
And does it block the status so that you have to restart ? Or does it go away after a few seconds ? On Windows 10, I observe the second behavior, which is described in #1625 .

**Comment by hqnghi88** [comment]
Yes, i have to restart like Julien did. Clicking on or waiting seconds didnt help. And i dont see the "hang a few seconds" behavior.

**Comment by AlexisDrogoul** [comment]
OK. This is a critical bug, then. Why hasn't it be reported before as such ? I cant really understand, if it happened several times, why it has not been signaled before. I am not able to reproduce it (in my case, only a lag of several seconds occurs), but since you are 2 to report this, we need to investigate it urgently (at least before the release is out).

**Comment by AlexisDrogoul** [comment]
Closed as a duplicate of #1625
