### ISSUE TITLE
Signal : raise errors or warnings if values are not in the correct range of value

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1304]
The simulation crashes when : 
- ```variation``` facet value is negative
- ```proportion``` facet is > than 1.0 when ```gradient``` is chosen
- ...

It should be better to raise errors when wrong values are used (either in the editor mode or during the execution of the simulation).

**Comment by AlexisDrogoul** [comment]
Fixed in 483f674146cc0c5f0a3726026c87008a57660ca9 .
