### ISSUE TITLE
The model validation verdict is sometime not synchronized

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1307]
Sometime I can't launch the simulation from the launching experiment button. I can't reproduce 100% the problem, but it happens quite often for me...
![screenshot](https://cloud.githubusercontent.com/assets/12977635/11202680/41892d62-8d1d-11e5-9ea3-a534eb3c468f.png)

**Comment by AlexisDrogoul** [comment]
A reproducible test case would be necessary, because there are so many possible reasons for this behavior…

**Comment by AlexisDrogoul** [comment]
W/o a reproducible test case, I push this back to the final release.

**Comment by AlexisDrogoul** [comment]
One solution to this erratic behavior could be to transform the error button into an action that forces a clean rebuild of the model,  discarding any cached states

**Comment by AlexisDrogoul** [comment]
I have implemented a simple handler for the error button, which tries to revalidate the file. Not sure it fixes anything, as I haven't been able to reproduce the bug.
