### ISSUE TITLE
loop from: 0 to negative value

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1308]
I think that the loop has a strange behavior when the to: facet get a negative value.
In particular, consider the following model:

global {
	
	int stepLisflood <- 0;
	
	init {
		loop j from: 0 to: -5 step: 1{
			write "hello " + j;
		}
	}
}

The observed result is quite surprising:
hello 0
hello -1
hello -2
hello -3
hello -4
hello -5
In addition if I change the sign of the step : 
		loop j from: 0 to: -5 step: -1{
This has no influence on results.

Benoit

**Comment by AlexisDrogoul** [comment]
I believe this was a choice made some time ago (see https://code.google.com/p/gama-platform/issues/detail?id=1070&can=1&q=loop&colspec=Opened%20ID%20Type%20Status%20Priority%20Owner%20Summary%20Version%20OpSys%20Milestone%20Modified)

Positive steps are automatically negated. We can reverse this choice if you dont feel it is right.

**Comment by AlexisDrogoul** [comment]
OK. The choice has been made to keep the current behavior when no step is provided (i.e. the step is either 1 or -1 depending on the direction of the loop), but to respect the step when it is provided. So a positive step would not allow the loop to be run if the direction is towards negative numbers. If someone is not ok with this solution, please comment quickly !

**Comment by AlexisDrogoul** [comment]
Fixed by commit b66f403080c2f0e0fb5d214fa50a65b8fc29575c
