### ISSUE TITLE
Problem for display small geometry in Java2D

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1309]
The following very easy code works in #m, #dm and #km (it displays a circle in the center of the environment), but it does not work when using #cm or #mm...

model display_one_agent

global{
	float worldDimension <- 50#m;
	geometry shape <- square(worldDimension);
	init{
		point center <- {(worldDimension/2),(worldDimension/2)};
		create species:my_specie number:1 with:(location:center);
	}
}

species name:my_specie {
	aspect name:standard_aspect {
		draw geometry:circle(1#m);
	}
}

experiment my_experiment type:gui
{
	output{
		display myDisplay background:#green {
			species my_specie aspect:standard_aspect;
		}
	}
}

**Comment by AlexisDrogoul** [comment]
What does not work exactly ? Does it make an error or is it not displaying anything ? (in the latter case, this could be normal given the dimensions of the environment: a 1mm circle in a surface of 2500m2 …)

**Comment by mazarsju** [comment]
I mean when you change both the dimension of the environment and the dimension of the circle from #m to #cm, nothing is displayed. (to display a 1cm circle in a surface of 2500cm² for instance)

**Comment by ptaillandier** [comment]
Hi, 

I think it is not a problem with the unity but with the java2D display (that does not draw small geometries?). If you use an OpenGL display instead, it works well.

**Comment by mazarsju** [comment]
Yes indeed, only a problem in Java2D. Problem for small geometries, nothing to see with dimensions.

**Comment by AlexisDrogoul** [comment]
Fixed in 73fe1d303a4d504ef4b1c53e38c4e48775f61c36
