### ISSUE TITLE
Add warning when both width and cell_width facets are used in grid

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1311]
2 different ways of declaring a grid:
- Using "width:" and "height:" to fix the number of cells (the size of each cells will be determined thanks to the environment dimension)
- Using "cell_width:" and "cell_height:" to fix the size of each cells (the number cells will be determined thanks to the environment dimension)
For me, you can't mix both of those facets. Maybe we should raise an error or a warning ?

**Comment by AlexisDrogoul** [comment]
Fixed in the latest commit 73fe1d303a4d504ef4b1c53e38c4e48775f61c36 .
