### ISSUE TITLE
Move Java2D base to JavaFX

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1312]
The current Java2D base for the "simple" (i.e. 2D) displays is becoming more and more obsolete and complicated to maintain at each new JDK version. 

A nice (and somehow easy, now that we will probably require at least JDK 1.7 for GAMA) way to keep most of the code while using a newer technology would be to port it to JAVA FX.

Two links:

https://wiki.eclipse.org/GEF/GEF4/FX (integration of FX and SWT components)
https://github.com/jfree/fxgraphics2d (for reusing exactly the same Java2D codebase on a FX Canvas).

Once this transition is done, we will also be able to clean many things (esp. the zoom) and to change some things (because Java FX provides a complete scene graph) and maybe merge the two display technologies ? OpenGL + Java FX (they are interoperable).

**Comment by anvd** [comment]
In the following weeks, I will explore the possibility to develop an editor
to edit Genstar configuration file in a GAMA project using JavaFX. This
editor is similar to the CSV editor of GAMA.

For the moment, I have zero knowledge of JavaFX. I'm still wonder whether
we will have the compatibility issues (e.g., Thread) between JavaFX and
SWT/RCP environment or nor. I think this link may be useful:
http://www.eclipse.org/efxclipse/index.html

**Comment by AlexisDrogoul** [comment]
Moving this issue to https://github.com/gama-platform/gama.experimental/issues/3
