### ISSUE TITLE
return in a reflex (global or species)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1313]
When a return statement is called in a reflex (in global or in any species), the simulation stops.
Something should be do: 
- either in preventing the call of the return in a statement,
- or that it stops the current loop/if... but does not stop the simulation.

Example of model:

global {

	init {
		create human;
	}

	reflex testRet {
		write "global: hello";
	//	return 3;
		write "global: hello post return post return 3";
		
	}

}

**Comment by AlexisDrogoul** [comment]
Does it completely stop the simulation (like pause would do) ? Or does it simply skip the rest of the reflex ? AFAIK, "return" is allowed in reflexes (as a way to stop them, like in an action), but it shouldn't stop everything. Regarding loops, etc, "break" is more appropriate.

**Comment by benoitgaudou** [comment]
It stops the simulation (like pause), but in addition the next step button made nothing (I was not able to do one more step, like I can do after a pause).

**Comment by AlexisDrogoul** [comment]
OK. I figured it out and corrected it in my current codebase. Top-level statements (like reflexes, inits) were not correctly cleaning the action_halted status in the scope, which consequently appeared as "interrupted" to the scheduler. I will commit this later but we can safely close the issue.
