### ISSUE TITLE
copy on message

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1314]
The implementation of the copy operator for the type Message does not seem correct to me:

	@Override
	public IValue copy(final IScope scope) throws GamaRuntimeException {
		return this;
	}

It should return a clone of the Message.

Benoit

**Comment by AlexisDrogoul** [comment]
The question is how to clone the message: should we apply a deep copy to all fields, or simply keep the same pointers ?

**Comment by anvd** [comment]
In this context, it doesn't really make much sense to make a deep copy to
all fields. For example, deep copy the "conversation" fields is similar to
creating a new conversion between concerning agents which is not correct.

I think that we can return a clone by calling the current Message.clone()
method. In such way, we have a new message instance and still keep the same
pointers to other fields. From GAML, if we use "copy" operator to copy a
message. Then if we read the "content" field of the copied version, the
original version is not affected. However, I think that the copy(message)
use-case is not very useful for the modeller.

**Comment by anvd** [comment]
What do you think? If you agree with this, can you please help me modify
the "copy" method of Message then commit it? I'm a little bit busy on Gen*
and too lazy to resolve the conflicts in my Eclipse environment :)

Thanks a lot,
An.

**Comment by benoitgaudou** [comment]
Hi,
Yes I agree with An.
The use-case was only when there were bug with the CNP, to be able to
modify at hand a copy of a Message.
I ll do it .

Cheers

Benoit

2015-12-02 9:01 GMT+01:00 anvd <notifications@github.com>:

> What do you think? If you agree with this, can you please help me modify
> the "copy" method of Message then commit it? I'm a little bit busy on Gen*
> and too lazy to resolve the conflicts in my Eclipse environment :)
>
> Thanks a lot,
> An.
>
>
