### ISSUE TITLE
Scroll bar in error view does not appear right

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1315]
Impossible to use the scroll bar in the Error view (cf screenshot)

![balloon](https://cloud.githubusercontent.com/assets/12977635/11466669/352a9670-9775-11e5-857a-9fa2ce03e059.png)

**Comment by AlexisDrogoul** [comment]
I can't reproduce this on MacOS X. But just to be sure: is it the inner or the outer scroll bar that does not work (i.e. the one used to scroll inside an error or to scroll between errors) ?

**Comment by mazarsju** [comment]
It was the inner scroll bar.
But I con't reproduce this error... Now here is the behaviour I have :
When I first launch my model and I have an error, I don't have the inner scroll bar anymore :
![image1](https://cloud.githubusercontent.com/assets/12977635/11918484/15c47b92-a766-11e5-9df9-4da6a379a633.png)

Once I launch again the simulation (without closing the error view), the error is not displayed anymore
![do-not-keep-calm-it-s-our-housewarming-party](https://cloud.githubusercontent.com/assets/12977635/11918490/450cb4f0-a766-11e5-9fc1-8f9d6e696367.png)

**Comment by AlexisDrogoul** [comment]
The second behavior is normal (as the error belongs to the previous simulation). For the first one, does it mean you can't scroll anymore ?

**Comment by mazarsju** [comment]
I can with the mouse wheel, but the bar is not displayed anymore...

**Comment by AlexisDrogoul** [comment]
I've supposedly fixed this bad behavior. Please reopen if it is not the case.
