### ISSUE TITLE
Problem with the tool "toggle the folding of lines" with Global and Experiment

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1316]
Cf title and screenshot

![balloon](https://cloud.githubusercontent.com/assets/12977635/11496110/7415d598-9842-11e5-9dc3-b6c695fb0b63.png)

**Comment by mazarsju** [comment]
This bug is also present most of the time when you indent your code with curly brackets at the end of the line.

**Comment by AlexisDrogoul** [comment]
Looks like a known XText bug — see https://bugs.eclipse.org/bugs/show_bug.cgi?id=471460

Will try to see if there are any news on this one.

**Comment by AlexisDrogoul** [comment]
Closing this issue as the only fix (after having discussed with an XText developer) will come from XText itself in a forthcoming version.
