### ISSUE TITLE
Possibility to display 3D objects (with the draw statement - OpenGL display)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1318]
GAMA becomes more and more powerful in terms of visualization. However, I think that we can improve a lot the visual realism of simulations by just adding the possibility to use 3D objects (obj file for instance) for visualization (and only for visualization, the idea is not to define 3D geometries from these files, which is complex to do for the moment as the current definition of geometries lacks some important features and can be very time consuming in terms of computation, but just to let OpenGL displays them). 

I want to write something like:
species car {
    display default {
          draw my_3D_file size: 10 rotation:....;
    }
}

I think Arnaud had made some tests regarding this issue during the last coding camp and it was working quite nice (but I think he did not commit anything for the moment)

**Comment by agrignard** [comment]
See issue #761

**Comment by agrignard** [comment]
First version of .obj has been done. Everything works except the texture
