### ISSUE TITLE
OSM metadata viewer in GAMA

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1327]
It could be nice to have in GAMA an editor/viewer able to open an OSM file and display attribute columns and the various value each attribute can have.

**Comment by AlexisDrogoul** [comment]
I think we could enhance the shapefile viewer as well by letting the user open the attributes table (in a CSV like window).

**Comment by ptaillandier** [comment]
Just to say that I have added a simple OSM viewer.
It is based on the shapefile viewer, which is not perfect as OSM data include many types of data (concerning road, building, water....).

**Comment by AlexisDrogoul** [comment]
I think, with the recent commits that fix the icons, metadata, etc. that we can now close this issue. Open other ones if there is a need for more refinements in this viewer.

**Comment by ptaillandier** [comment]
I reopen this issue as I plan to improve (just a bit) the OSM viewer. In addition, we did not address the second part of the issue concerning the display of shapefile/OSM attributes.
