### ISSUE TITLE
Video of a simulation

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1329]
Add an easy way to do video from a simulation.
(or at least document how to do it by producing a snapshot folder and using external tool).

**Comment by AlexisDrogoul** [comment]
I think we will close this issue. I let it to @mazarsju (Julien) to include a small part in the documentation to use VLC or QuickTime to directly record the screen. Whatever we do, the performances (and functionalities) of external tools will always be better than what we could offer in GAMA.
