### ISSUE TITLE
charts: datalist histogram color parameter not working

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1331]
When using the color parameter with a datalist (for example in ant (chart example) model), the colors do not fit the color list given.
There is also a color problem when using the stack style with data statement.

**Comment by AlexisDrogoul** [comment]
Any chance we can have this on time for the first beta ?

**Comment by pcaillou** [comment]
I will try to finish the charts for the first beta (so this weekend...), 50% chance I would say :)

**Comment by AlexisDrogoul** [comment]
This one is one of the bugs keeping the release to be done -- any chance we have a fix soon ?

**Comment by pcaillou** [comment]
It is already fixed in chart branch.
I will do a release-version of the branch next week then, good motivation :)

Philippe

2016-04-02 10:51 GMT+02:00 Alexis Drogoul <notifications@github.com>:
