### ISSUE TITLE
Improve chart documentation

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1333]
Not clear in current documentation when tu use lists, lists of lists, lists of lists of lists, and the outcome.
Add an independant chart example model, and add nice pictures...

**Comment by AlexisDrogoul** [comment]
What is the state of this enhancement ? Has the documentation been improved ?

**Comment by pcaillou** [comment]
not yet... Waiting to finish the chart before writing the doc (so for 1.7 final or beta 2...)

**Comment by AlexisDrogoul** [comment]
Moved to https://github.com/mazarsju/gama_doc_17/issues/8
