### ISSUE TITLE
Keyboard Event

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1338]
Add Keyboard Events should be very useful (and easy to implement) for user interaction (not just mouse_down / mouse_up).

**Comment by AlexisDrogoul** [comment]
This now works partially under OpenGL but not in Java2D. It seems that keyboard events are generated but immediately consumed by the Swing. Still investigating. At least the infrastructure is in place (possibility to declare `event` layers with a letter as the trigger).

**Comment by AlexisDrogoul** [comment]
I have added some constraints on the execution of the action specified by the layer. Basically, the action will be synchronized with both the display and the simulation. If the simulation is paused, it is executed immediately, if not it is put at the end of the step and run at that time. 

Things seem to work smoothly for OpenGL displays, but I'm having a hard time figuring out how to make it work for Java2D. I have for instance a solution (using the KeyboardFocusManager of Swing) that works  fine when debugging GAMA but not when launching it ! Probably a very sensible thread adjustment behind... I keep digging (especially in never giving the focus to AWT/Swing but trying to rely on SWT instead).

**Comment by AlexisDrogoul** [comment]
OK. I have a solution that works without a hitch on my version for both Java2D and OpenGL. Since it involves a lot of modifications to the internal structures of the display, however, I'm not committing it yet -- but I will once I've done all the necessary tests on other aspects (interaction with OpenGL cameras, with the update of the bottom overlay, and with the listeners of AWT events). Stay tuned !

**Comment by AlexisDrogoul** [comment]
I have committed a version (with a small new 'Features' model for User Interaction, which shows one way of moving agents on screen). Please test !

**Comment by AlexisDrogoul** [comment]
I have uploaded a refinement of previous commit (to correct the interaction with the camera on OpenGL).
Also improved the "Moving Agents" feature model. Both displays are working very well, with just one caveat (maybe only on MacOS): mixing them (or juggling between Java2D and OpenGL displays) makes the OpenGL display sometimes non-responsive, with only the solution of moving out of and back in the view to solve the problem.

**Comment by AlexisDrogoul** [comment]
If no one is against this, I close the issue. Please open specific requirements or bugs related to the event layer separately.
