### ISSUE TITLE
Frequency slider in view (esp. display) toolbars does not reflect the frequency provided in the model

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1340]
When defining a display with `refresh: every(x)`, x is not taken into account to update the slider. Since this (new) facet can take any boolean expression as a parameter, it is probably difficult to extract the value when something else than `every` is used. Should we remove the slider altogether, then ?

**Comment by AlexisDrogoul** [comment]
I am in favor of removing these sliders, since I'm not completely sure anyone uses them anyway. @gama-platform/committers , what do you think ?

**Comment by ptaillandier** [comment]
I am ok with this proposition.
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Cet
e-mail a été envoyé depuis un ordinateur protégé par Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-08 9:54 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
OK. Done. We might perhaps think of a way to input a new frequency for displays (in the side controls, it might be a good idea) but i'm not sure anyone will be using it…
