### ISSUE TITLE
Voronoi toy model taking forever to run because of a change in the attribution of topologies

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1341]
Run the Voronoi toy model from the Models Library. It seems that nothing is happening at first, and one has to wait a long time before the first step is made. The culprit is this line:

`center closest_center <- nil update: center closest_to self.location;`

Now remove the `update:` facet and its expression, and put in `global`:

`	reflex {
				loop a over: cell {
			a.closest_center <- center closest_to a.location;
		}
	}`

The model runs normally (i.e. at a fast rate).

The two ways of writing the model basically do the same computation, with a catch: in the first model, `closest_to` is called on the grid topology (yielding, for each cell, a grid-based computation of distances and neighbors), while, in the second model, the call is made, because we are in the world, in the continuous topology. 

Since GAMA 1.6.1, there must have been a change somewhere on the detection of the "good" topology to use in such cases, because the model is running fine (with the `update:` facet) in the previous version of GAMA. 

However, this change is quite sound: the assumption made that the computation of `closest_to`should take place using the grid topology is correct without any more indications on the default topology to use. So, how can we solve this problem ? 

A first thing is to optimize the `closest_to` operation (and the related computations) on grids. Assuming a regular and immutable grid, we might be able to precompute distances or neighborhoods (the algorithm doesn't make use of what is used for signals, for example).

A second thing is to allow the modeler to specify the topology to use in spatial operators. This is partially done for some (`distance_between`, for instance), but not for all, and we should perhaps do it. A dedicated statement (`using`) exists for that purpose, but can't be used here as we are in a facet expression. Maybe creating a special operator with the same name could solve this problem  ? e.g. 

`center closest_center <- nil update:  (center closest_to self.location) using topology(world);` ??

**Comment by AlexisDrogoul** [comment]
A similar effect can be achieved with the two following forms of the global reflex:

**Happens in the world topology (because `loop` does not change the context)**
`reflex { loop a over: cell { a.closest_center <- center closest_to a.location; } }`

**Happens in the grid topology (because `ask` changes the context)**
`reflex {
		ask cell {
				closest_center <- center closest_to location;
		}
	}`

Although, here, we can explicitly specify the topology to use:

**In the world topology (specified by the `using` statement)**
	`reflex {
		using (topology(world)){
		ask cell {
				closest_center <- center closest_to location;
		}}
	}`

**Comment by ptaillandier** [comment]
Hi,

I think the "using" operator is a good idea.
By the way, without this operator, I think I would have written the model
with a reflex inside the cell species and the using statement:

reflex update {

using (topology(world)){

closest_center <- center closest_to location;

color <- (closest_center).color;

}

}

Cheers,


Patrick

2015-12-17 3:10 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
The `using` operator has been implemented and the Voronoi model updated consequently to reflect this addition (with `center closest_center <- nil update: (center closest_to self.location) using topology(world);`).
