### ISSUE TITLE
Be able to have access to the documentation even if the current model has some errors

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1347]
Be able to have access to the documentation with a mouse hover even if the current model has some errors.

**Comment by AlexisDrogoul** [comment]
OK. One way to do it is to enable a fallback when no syntactic/semantic information can be found, by detecting the current word and trying to find a correspondence with a keyword / operator / facet of GAML.  It should not be too complicated to do, so I add it to the GAML 1.7 milestone.

**Comment by AlexisDrogoul** [comment]
#1781 adds the possibility to display help (and contextual help) independently of the state of the model, on any GAML idiom. I then close this issue, which has become less necessary. Reopen if needed.
