### ISSUE TITLE
Chart (series) are not updated when GAMA is not in Simulation perspective

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1350]
Launch any model with chart series (e.g. ants), run the model.
Series are plotted.
Switch to modeling perspective and come back to simulation perspective.
We can observe that during time spent in modeling perspective, the simulation still ran but the series have not been plotted.

**Comment by AlexisDrogoul** [comment]
A choice has been made, some time ago, to stop refreshing the displays / monitors / browsers when the modeling perspective was invoked. They are paused using a special IPerspectiveListener which is created for every display. The behavior you describe is a consequence of this choice. I am ok to revert it (its role is to save some CPU/GPU power while a simulation is running), or to make it a preference.

**Comment by AlexisDrogoul** [comment]
I've just added a preference in the "Display" section to continue to draw displays in the background when in the Modeling perspective. The default initial value is 'false' as now.
