### ISSUE TITLE
Images corrupted in model displays (when model folder contains space caracter)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1351]
In the current GAMA Model Library, in Toy Models, the ants model is named "Ants (Foraging and Sorting)".
When I run the Ant Foraging (Classic).gaml model, the ants are not displayed with a picture whereas they should. It seems that the image cannot be found.

If I rename the folder 'Ants' (or any name without space), GAMA can find the pictures.

More strange, whatever is the name of the folder (with or without space), in the 'Uses' folder (inside the model file), GAMA can always find the image.

**Comment by AlexisDrogoul** [comment]
I cannot reproduce this. The ants are (normally) displayed with their pictures on my machine. Can you retry it, maybe in a different workspace ?

**Comment by benoitgaudou** [comment]
I tried several times to open GAMA with a new workspace, run the model (two or three times to get a correct display in the simulation perspective), and I have still wrong pictures for my ants.
(I tried to change name of the project and model, but without effect)

<img width="254" alt="capture d ecran 2015-12-31 a 14 34 32" src="https://cloud.githubusercontent.com/assets/1555274/12064771/d23e7f4e-afcb-11e5-8067-948cdade023c.png">

**Comment by AlexisDrogoul** [comment]
Is it the same issue ? In the original one, you said that pictures could not be found, whereas in the image provided, they seem to be corrupted.

**Comment by benoitgaudou** [comment]
Yes it is the same issue. 
My description of the issue was wrong indeed.

**Comment by AlexisDrogoul** [comment]
And when you open the images using the internal viewer or any other program on your Mac, do they appear normally ?

**Comment by benoitgaudou** [comment]
No problem to open them in GAMA or Mac image viewer.

**Comment by AlexisDrogoul** [comment]
I can't reproduce this issue. Does it happen for others ( @gama-platform/committers ) ?

**Comment by AlexisDrogoul** [comment]
So, the issue has been isolated: it seems to occur only with a certain video card (Nvidia GeForce GT 650M), on MacOS X, when the display mode is set to "Default". However, changing the display mode, in "System Preferences" to "More space" solves the problem. So there is a kind of workaround — but more probably it is a problem of initialization of the TextureCache in JOGL and we'll need to catch it.
