### ISSUE TITLE
Enhancement : Export agents as CSV & Export globals as CSV

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#1352]
Hi,
It would be useful to have an operator that exports all of the agents attributes to a CSV.
Currently, to do that, you have to write something like this :

    action save_Seigneurs {
        if (!file_exists(Seigneurs_file)){
            save ["Annee", "ID_Seigneur", "X", "Y", "type", "Puissance","Puissance_armee",
                "Loyer","HteJustice", "Banaux", "MBJustice","ID_Suzerain","Nb_FP"]
            to: Seigneurs_file type: "csv";    
        }
        ask Seigneurs {
            save [Annee, self, int(location.x), int(location.y), type, puissance with_precision 3, puissance_armee with_precision 3,
                droits_loyer, droits_hauteJustice, droits_banaux, droits_moyenneBasseJustice,
                monSuzerain, length(FP_assujettis)]
            to: Seigneurs_file type: "csv";
        }
    }

This is quite boring, as you have to update this command each time you change an attribute.
Considering such a table is dynamically generated in the population browser, having a quick operator doing this shouldn't be that hard to implement.
This would export a CSV with all agents and their properties, plus 1 column with the current date/time/step, and concatenate to this file for each step.

It could be something like `agents save_as_csv "file"`.

Having this could then be used in a reflex, possibily using the every() facet, which would give 

    reflex save_seigneurs every: 10 {
        seigneurs save_as_csv "seigneurs.csv";
    }

In the same idea, this would be really usefull to be able to do the same export with the world globals.

For example, here's my action to export my globals/parameters each step :

    action save_Parameters {
            if (!file_exists(Param_file)){
                save ["Année début simulation", "Année fin simulation", "Nombre de Foyers Paysans","Taux renouvellement",
                    "Taux mobilité des FP",   "Nombre d'agglomérations secondaires antiques",
                    "Nombre de villages",  "Nombre de Foyers Paysans par village (borne max)","Puissance Communautés",
                    "Nombre grands seigneurs", "Nombre petits seigneurs","Puissance Grand Seigneur 1", 
                    "Puissance Grand Seigneur 2", "Probabilité créer château GS", "Probabilité don château GS",
                     "Proba. gain droits haute justice sur château", 
                    "Proba. gain droits banaux sur château","Proba. gain droits BM Justice sur château",
                    "Probabilité créer château PS", "Proba. don droits sur ZP",
                    "%FP payant un loyer (Petit Seigneur) - Borne Min", "%FP payant un loyer (Petit Seigneur) - Borne Max",
                    "Rayon min Zone Prélevement - Petits Seigneurs", "Rayon max Zone Prélevement - Petits Seigneurs",
                     "Proba gain nouveaux droits banaux", "Proba gain nouveaux droits BM justice","Nombre visé de seigneurs en fin de simulation",
                     "Nombre d'églises", "Dont églises paroissiales", "Probabilité gain des droits paroissiaux", 
                     "Nombre max de paroissiens", "Nombre min de paroissiens"] to: Param_file type: "csv";
                save [debut_simulation, fin_simulation, nombre_foyers_paysans, taux_renouvellement, taux_mobilite,
                     nombre_agglos_antiques, nombre_villages, nombre_foyers_villages_max,
                    puissance_communautes, nombre_grands_seigneurs, nombre_petits_seigneurs,
                    puissance_grand_seigneur1, puissance_grand_seigneur2, proba_creer_chateau_GS, proba_don_chateau_GS,
                     proba_gain_droits_hauteJustice_chateau, proba_gain_droits_banaux_chateau,
                    proba_gain_droits_basseMoyenneJustice_chateau, proba_creer_chateau_PS,
                    proba_don_partie_ZP,  min_fourchette_loyers_PS, max_fourchette_loyers_PS, 
                    rayon_min_PS, rayon_max_PS,proba_creation_ZP_banaux, proba_creation_ZP_basseMoyenneJustice,
                    nombre_seigneurs_objectif, proba_collecter_loyer,
                    nombre_eglises,nb_eglises_paroissiales, proba_gain_droits_paroissiaux,
                    nb_max_paroissiens, nb_min_paroissiens] to: Param_file type: "csv";
            }
        }

This would become something like 
    reflex save_world every : 1 {
        save_globals_as_csv "parameters.csv"
    }

Or, I don't know how this work, but considering the world is an agent and globals its attributes, could just be the same operator as for the agents :

    reflex save_world every: 1 {
        world save_as_csv "parameters.csv"
    }

This would clarify the outputs, and help maintain a better code when changing the species attributes often :)

**Comment by RCura** [comment]
Nobody thinks this would be useful except me ? Could at least someone tag it as en enhancement ?

**Comment by ptaillandier** [comment]
Hi,

I

2015-12-31 14:09 GMT+01:00 Robin Cura <notifications@github.com>:

**Comment by ptaillandier** [comment]
Hi,

First, happy new year !
I have just committed a new way of using the save statement. 

You can now write:
save dummy to: "result.csv" type: "csv";
save world to: "resultw.csv" type: "csv";

That will save all the attribute values of the corresponding agents (one agent or a list of agents) into a csv file. Note that by default, the file is not rewritten (just append to the file if this one already existed) and that a header will be added if the file does not exist before. You can control that by using the rewrite and header facet:
save dummy to:"result.csv" type:"csv" header: false rewrite: true;

Can you test it and tell me if it fixes your issue?

**Comment by AlexisDrogoul** [comment]
Hi, 

I have not tested it yet, but I would be in favor of (1) giving also the possibility to specify the attributes to save (like in the inspect statement for browsing populations, facet `attributes:`). And if it is not specified, make that attributes like `host`, `peers`, `members`, `agents` are not saved by default; (2) using the `;` as the default for saving CSV files in the save statement, as the resulting file is not readable when you save lists, points, etc. — or maybe specify the separator to use.  

This clearly calls for completing the file architecture (I've just filed an issue about this) so that the `file` objects can be manipulable more easily and can be used to save data.

**Comment by ptaillandier** [comment]
Hi,

You are right, but I was not motivated enough on this first day of the year
to do something more "complex" ;). So, for this issue, I have just  added
5-10 lines of code to allow to directly save all the attributes contained
in the attributes map (+ cycle, name, location.x, location.y, location.z)
of a list of agents (or of a simple agent).

Lot of improvements (and tuning possibilities) could be made by refactoring
the file architecture.

2016-01-01 11:53 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
I have rewritten part of the solution to address 3 problems:

1) The values were taken from the (internal) `attributes` map of the agents, which only contains their "extra" attributes (not the ones defined in the species).
2) The use of the `,` delimiter could make saving lists impossible 
3) Uninteresting attributes (like `peers`, for instance) are eliminated by default.

I am also too lazy right now to specify the attributes to save or not but it can be easily done by reusing what we already use for shape files (`with:` facet).

Everything needs to be tested before we can close this one.

**Comment by RCura** [comment]
Seems to work quite well (thanks !!!).
I will run some tests on the possible flaws, like having quotes on names, using ";" inside values etc.

One of the good things that worried me is that it seems that list export is well managed.
For example, when exporting the subagents of my agent, it's well displayed like this [0 as species1, 1 as species1], but when the world is exporting, it's list(Species1), and it's really cool.

Thanks @ptaillandier & @AlexisDrogoul, I'll test more extensively asap :)

**Comment by AlexisDrogoul** [comment]
Having quotes shouldn't be a problem. However, the use of ';' inside values might. To get rid of this problem, we should always quote strings (or systematically escape ';' )— but this needs to be tested more thoroughly as the CSV format is really messy.

**Comment by AlexisDrogoul** [comment]
I have implemented a dirty workaround, which seems to work well… When saving CSV files, the delimiter character is systematically replaced if it appears in the values (by another delimiter: `;` becomes `,`, for instance. It's not beautiful, it's a hack, but since quotation or escaping are absolutely non-standard in the CSV format, it's probably the best solution. So I close this issue for now on. Feel free to reopen it if it does not fit your needs.
