### ISSUE TITLE
"Hovering" lost with Java2D displays on MacOS X

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1353]
I've noticed an issue (while working on #1248 and #1339), where the SWT custom components (such as FlatButtons, boolean switches, etc.) will not receive anymore a "hover" event as soon as a Java2D display is open — and even when it has been closed. The effect is simple to observe: buttons do not change color anymore when being hovered, the background of customs input fields does not change in the Parameters view, etc. And only clicking on these elements will produce the desired effect. Launching the same model with an OpenGL display does not create the same problems. 

The only workaround is to open the Preferences view (which presumably "recaptures" focus/hover events in a new Shell) and close it.

**Comment by AlexisDrogoul** [comment]
Can someone confirm it is (or not) doing the same on Windows and/or Linux ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Sorry that i dont understand clearly the case. On windows 10, when i hover fields in the Parameter views, the gray rectangle appear around the field, but the name of the field only change to yellow when i click in input field. For the boolean switche, it change to darkred when i click on it.


![hover](https://cloud.githubusercontent.com/assets/6105384/12013670/7e2b2012-ad4e-11e5-8afc-c613b9b1e981.png)

**Comment by AlexisDrogoul** [comment]
Sorry, I was not clear enough. Here are the steps to follow to reproduce (or not) my issue:

- Launch a model with a Java2D display. Any will fit.
- Click on the display (or even move the mouse over it).
- Now come back to the Parameters view and hover over a boolean switch (like the one on your example), or on an Experiment button in the Editor: are they "hovered" (i.e. displaying the gray rectangle around the field for the switch or changing color for the button) ?

**Comment by hqnghi88** [comment]
I confirm that on win10, Parameter view 's fields and Experiment button are hovered after the interraction (drag, zoom, select) in java2d display.

**Comment by AlexisDrogoul** [comment]
I almost give up after having spent 10 hours on this issue. SWT.MouseHover, SWT.MouseEnter, SWT.MouseMove and SWT.MouseExit events are not generated and are not delivered to the custom widgets concerned as soon as a Java2D display is active and has been traversed by the mouse. As if the AWT/Swing subsystem was not releasing these events once they had been "caught" once by the JComponent. What is even stranger is that this misbehavior persists even when the displays have been closed. Something is clearly wrong in the implementation, on MacOS X, of the Swing EventQueue… (or its use in the SWT_AWT bridge, which is not very regularly maintained).

I have tried every possible changes in setFocus(), forceFocus(), etc. that I could think of. I have tracked all the low-level events with no luck. These 4 events (maybe others) simply "vanish", contrary to the SWT.MouseClick or other events, which are still produced when desired.

The only hint has been the fact that opening a new shell and then hiding it (the Preferences view) was somehow temporarily reducing the problem. So I will create a workaround that will (only on MacOS X) open an invisible shell and hide it immediately when an AWT based view is exited or when an Editor gets activated — because it seems to worsen when editors and 2D displays are interacting.

But it will only be a workaround — and an ugly one. One more reason to move to another rendering subsystem to replace Swing / AWT…

**Comment by AlexisDrogoul** [comment]
A good news on this bug (well, sort of): this behavior only happens under JDK 8. I ran GAMA today on JDK 7 (latest "public" release: u66) and everything was ok. So maybe a subsequent JDK8 update will bring a fix to this...

**Comment by AlexisDrogoul** [comment]
To add some precision: it is a bug of the port of SWT in MacOS X. Whenever a Swing component is displayed, only the native SWT components (Table, Tree, Text) receive further mouse tracking events, but none of the custom ones (GAMA specific ones or even JFace ones. Even StyledText in the editor does not receive anything unless it is clicked). The same behavior does not occur under WIndows or Ubuntu. I will put this on hold because there is nothing I can do beside the workaround (which does not work so well...).

**Comment by AlexisDrogoul** [comment]
I close this issue -- the workaround is now working correctly and there is nothing more I can do... Please reopen if this arises again (on MacOS X -- also in other environments ?).
