### ISSUE TITLE
Redraw problem after dragging in Java2D display

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1354]
- Open any model, and launch with a Java2D display.
- Drag the view inside the display. 
Some thing happen with the redraw (or repaint) produce the attached shot. 
![drag](https://cloud.githubusercontent.com/assets/6105384/12014912/0fffeb9a-ad67-11e5-9faa-c9936f2d0350.png)

**Comment by AlexisDrogoul** [comment]
Seems to be a Windows-only problem, where the background is not repainted (it should be, however…). Do you have this bug since a long time or is it recent ? (i.e. can you back, say, one week in time in the Git version and try again ?).

**Comment by AlexisDrogoul** [comment]
I've just committed what might be a fix for this issue. Can you try it ?

**Comment by RCura** [comment]
For my part, on Linux/Ubuntu, it now works as it should :) Thanks ^^

**Comment by hqnghi88** [comment]
Dear Alexis,
It works on w10.
Thanks.
