### ISSUE TITLE
Using advanced driving skill on a simple road

### ISSUE THREAD

**Issue by stouhbi** [gama-platform/gama#1372]
Hi,
I am trying to use advanced driving skill on one road that was built as a rectangle, with each lane defined as a polyline. 
When I try to drive on the lane (a polyline) it does not work, I use this as a code
```
reflex time_to_go when: final_target = nil {
		    current_path <- compute_path(graph:  generator.road.lanes[generator.lane-1], 
                    target: the_target);
}
reflex move when: final_target != nil{
			do drive;	
            if final_target = location {
                final_target <- nil ;
                // reached the final destination
                do die;
            }
}	
```
where  generator.road.lanes[generator.lane-1] is the lane (the polyline)
and the_target is a point.
Is it feasible ?

**Comment by AlexisDrogoul** [comment]
I would rather post this kind of question on the GAMA mailing list: https://groups.google.com/forum/?fromgroups#!forum/gama-platform 

In addition, you should better explain what "does not work" and maybe post your data on the list. If a flaw is identified within the advanced driving plugin, then we will open an issue specifically on it.
