### ISSUE TITLE
The wiki page on operators documentation cannot be rendered anymore

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1375]
When accessing https://github.com/gama-platform/gama/wiki/G__Operators, nothing is displayed instead a message saying "The wiki page took too long to render".

Possibly a problem of size of file (maybe an update from github wiki...)

**Comment by benoitgaudou** [comment]
Hi,
Note that I had the same problem with the google code wiki and I had to
split
the operators documentation into 2 files (by alphabetic order).
It was made automatically, so I suppose we can reintroduce that for the
GitHub wiki.

Benoit

2016-01-08 10:23 GMT+01:00 mazarsju <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
We are apparently not the only ones… https://github.com/AnalyticalGraphicsInc/cesium/issues/3280

**Comment by mazarsju** [comment]
I spited the operator page into 2 pages (AK and LZ). Both pages start with the "Introduction" section. I ran a script to change all the links in all the pages in order to match with this new structure, hope I did right. Reopen this issue if you find some problems with links ! (For the wiki content in branch, we keep one unique file for all the operators for the moment)
