### ISSUE TITLE
Some colors in "dark mode" are not well chosen (ex : cf title of the "user input" popup)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1376]

**Comment by mazarsju** [comment]
The coloration I have (text in white, background in very light green) only exists in "dark mode" (from Preferences/UI).

**Comment by AlexisDrogoul** [comment]
Hi, regarding the colors, they are automatically chosen (by increasing the luminance), so it's difficult to change this for specific places. And in most buttons, menus, etc. the color of the text is determined automatically with respect to whether the background color is 'dark' or not. However, there are some places where the color of the text is not determined like this, like in the example you give. I have tried to address these in the next commit — if you find other places where the color of the text does not match that of the background, please reopen the issue.
