### ISSUE TITLE
Update documentation to include "plugin models"

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1378]

**Comment by AlexisDrogoul** [comment]
Looks like a reminder :)

**Comment by mazarsju** [comment]
Yes it is indeed ;)
A quick question about that : are the metadatas created automatically in the model library ?

**Comment by AlexisDrogoul** [comment]
Which metadata ? Currently, each file comes with two types of metadata, and both are generated automatically: the list of required plugins + the list of experiments, support files, and included models. We can generate more but it depends on your needs !

**Comment by mazarsju** [comment]
Ok. When does the metadata about the list of required plugins is generated ?
I can find easily the metadatas about the list of plugins, but not the other one... Where is it ?
