### ISSUE TITLE
[Graph] neighbors_of and neighbors_at raised wrong casting exception with topology graph

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#138]
**Describe the bug**
Trying to get neighbors at distance ``n`` of an agent within a graph raises an exception.

**To Reproduce**
Copy past the model below
```
global {
	
	graph<a,unknown> g;
	
	init {
		
	create a number:10;
        g <- graph([]);
        
        loop agt over: a { add node(agt) to: g; }
        loop i from: 0 to: length(g.vertices) - 2 {
            loop j from: i+1 to: length(g.vertices)-1 {
                add edge(g.vertices[i],g.vertices[j]) to: g;
            }
        }
        
        a caller <- any(a);
        ask g neighbors_of caller {write self;}
	ask neighbors_of (topology(g), caller, 1) {write self;}
        
	}
}

species a { }

experiment xp { }
```
2. Execute the model
3. See error

**Expected behavior**
return same results with both neighbors_of calls! Note that the same happens with the neighbors_at operator using graph topology  

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - GAMA version: 1.9.3

**Comment by chapuisk** [comment]
@ptaillandier now i understand. Imho, spatial graph should be the default, i.e. don't have to go through an operator to specify it. That means we could have an operator to "unspatialize" a graph, but is it usefull anyway? Because non spatial graph means non agent graph... May be it is necessary for performance issue, more or less like grid and fields. Otherwise i dont see the point to having both.

**Comment by ptaillandier** [comment]
Non-spatial graphs are interesting when you just need a graph structure for
example for argumentation graphs for which nodes represent arguments. The
notion of "location" does not make sense in this case.

Le mar. 2 avr. 2024 à 14:12, Kevin Chapuis ***@***.***> a
écrit :
