### ISSUE TITLE
Using FIPA ACL Documentation has to be written

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1382]

**Comment by AlexisDrogoul** [comment]
Maybe provide a link for entering this documentation in the wiki ?

**Comment by mazarsju** [comment]
https://github.com/gama-platform/gama/wiki/G__UsingFIPAACL

**Comment by anvd** [comment]
I remember that I have written the documentation for FIPA ACL. I will try
to ruse it.

**Comment by AlexisDrogoul** [comment]
It becomes now quite urgent to have at least a small documentation on this extension.

**Comment by anvd** [comment]
Done.
