### ISSUE TITLE
The 3 top left buttons in the display view sometimes are missing

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1385]
With some models and some application window size, the 3 top left buttons in the display view  (_toggle layers controls_, _toggle overlay_ and _browse through all displayed agents_) are not visible... They reappear again when I change the size of my GAMA window.
Important to note also that this bug is 100% reproducible while you find a specific combination model + application window size (for me for example, the problem happens when I run incremental models in full screen in my external screen).

**Comment by AlexisDrogoul** [comment]
The problem is that I cannot reproduce this — seems to be a Windows-specific bug.

**Comment by AlexisDrogoul** [comment]
I've tried all possible combinations of window size, view size and models and i can't reproduce it on Windows 10. Maybe something has changed recently in the handling of the toolbar. Anyway, I close the issue -- but please reopen it if it still happens.
