### ISSUE TITLE
[Graph] odd outcomes using node_species argument of operators that generates graph

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#139]
**Describe the bug**
Operators to generate graph (such as small world, scale free and the like) make it possible to specify the species of the node, i.e. argument node_species. Doing so leads to diverse odd outcomes: more nodes than agent of species created, node (vertice) that are actually not from defined species, spatial representation do not match, etc. 

**To Reproduce**
1. Copy past this simple model example:
```
global {
	
	graph<a,unknown> g;
	init {
		
        g <- generate_random_graph(10,10,false,a);
        
        write g.vertices;
        write g.edges;
        
        g <- as_spatial_graph(g);
        
        write g.vertices;
        write g.edges;
        
        ask a {
        	write sample(g contains_vertex self);
        	write sample(g neighbors_of self);
        }
        
	}
	
}

species a { aspect default {draw circle(1) color:#grey;} }

experiment xp { 
	output {
		display main {
			species a;
			graphics edges {loop e over:g.edges {draw geometry(e) color:#black;}}
		}
	} 
}
```
2. Execute model
3. See in console that 
5. See error

**Expected behavior**
Being able to build a graph using available methods without having to go through another operator (as_spatial_graph), having to maintain the link between inner graph representation of nodes and edges and my node species, being able to display it right away, etc.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - GAMA version: 1.9.3

**Side note**
It is counter intuitive to be forced to turn generated graph into a spatial graph to be able to manipulate and display it

**Comment by lesquoyb** [comment]
I also noticed some weird code in graphs while cleaning up the code base (see for example [here](https://github.com/gama-platform/gama/pull/133/commits/8add5ce111c72d3b0899bb7cbab5a558b113d20b) a property was used in some graph algorithms but actually never set) I think that part has been modified many many times and would benefit from some refactoring

**Comment by ptaillandier** [comment]
@chapuisk to be tested, but it should be fixed
