### ISSUE TITLE
3D Curpie without Texture generates Warning for Texture

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1390]
In Gama 1.7, in the Library Models in the 3D Visualization Folder in Features, the model Built-in Shapes generates an warning about a Geometry (curPie3D) on which a Texture can't be applied (because sphere and not a rectangle or quad) but it doesn't have any Texture variable and write something about the line curPie3D <- curPie3D + 1. Maybe the wrong line is linked to the warning message ?

**Comment by agrignard** [comment]
In this model a warning is raised for all the gamashape whose number of vertex is greater than 5.

So the warning is raised for the cylinder( gamashape = circle) and polyhedron. however for a point or a shpere the warning is not raised.

This can be enhanced...

**Comment by agrignard** [comment]
see #1299
