### ISSUE TITLE
Camera position and Camera Look position doesn't change anything in Java2D

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1392]
In gama 1.7, using the facets camera_pos and camera_look_pos of display doesn't change the view of a Java2D Display. I know that it works for 3D and there isn't really any camera in Java2D but maybe someone will want to follow a truck for example in a Java2D display of a road network, so basically it will be resumed as a zoom and just a point location in the display.

**Comment by agrignard** [comment]
I thnik that camera pos; look pos, etc will be move in a special scope and not anymore as a facet of the display.

The syntax could be

display view{
camera_parameter{
etc, etc, 
}
}
