### ISSUE TITLE
Copy Paste with Keyboard in the Navigator View of the model doesn't work anymore

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1393]
In Gama 1.7, trying to do a copy paste a model file thanks to the keyboard shortcuts in the navigator doesn't work anymore, whereas in the 1.6.1 version it was working (and even propose to rename it in case of conflict).

**Comment by AlexisDrogoul** [comment]
I had to make a choice between this and #1295, as the behavior in the navigator is a direct consequence of the deactivation of shortcuts necessary to address this previous issue. I have tried to isolate as much as possible this deactivation, but without much luck. My opinion is that the use of clipboard shortcuts in the navigator is more important than in the search field so I have reactivated them in the forthcoming commit.
