### ISSUE TITLE
Graph and SpatialGraph

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1394]
Both SpatialGraph and Graph should be unified.
Or at least the differences between both cases should be made clearer.

**Comment by AlexisDrogoul** [comment]
I come back to this "issue". The fact is that they are unified in GAML (i.e. only one type is available). In my opinion, this issue is more related to the documentation than to the code itself.

**Comment by AlexisDrogoul** [comment]
Moved to https://github.com/gama-platform/gama.doc/issues/29
