### ISSUE TITLE
Blocked in the state 'Closing previous displays'

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1397]
I run a model (ant foraging (Charts examples).gaml).
During the initialisation of the simulation, I switched from one perspective to the other.
As a consequence, displays are created in both perspective.

When I try to launch again the simulation, GAMA tries to close displays and stay blocked in the state 'Closing previous displays'.

**Comment by AlexisDrogoul** [comment]
Tested on MacOS X. This however needs to be tested on Ubuntu and Windows, as the mechanism and life-cycle of views is a bit different on these platforms.
