### ISSUE TITLE
Graph Generation using Watts Strogatz

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1399]
in Gama 1.7 (maybe 1.6.1?), the graph generated by the operator watts strogatz isn't right : the generated graph has more edges than it should, and two edges (maybe more) can be between the same couple of nodes. For example, creating 5 nodes, with a mean degree by vertices (k) equals to 4 and p (probability of redirecting an edge) equals to 1 (or lower),  should create a graph of 10 edges (a pentagram shaped graph) but in fact it creates 20 edges (duplicates the existing ones).

**Comment by ptaillandier** [comment]
The Graphstream Watts Strogatz operator is not so bad and seems sufficient for the moment (GAMA extensions providing more reliable graph generators could be proposed)
