### ISSUE TITLE
Graph Generation using Barabasi

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1401]
in Gama 1.7 (maybe 1.6.1?), the graph generated by the operator barabasi_albert isn't right : the generated graph has a low number of edges, it should be (according to the parameter m passed in the operator) higher than that.

**Comment by ptaillandier** [comment]
The Graphstream barabasi_albert operator is not so bad and seems sufficient for the moment (GAMA extensions providing more reliable graph generators could be proposed)
