### ISSUE TITLE
Reload does not refresh the population browser

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1402]
Open Ants (Complete) in Toy Models > Ants
Run a first simulation, then reload it.
The population browser display `nil` values for all the attributes (cf. screenshot).

<img width="589" alt="capture 2016-01-17 a 00 52 49" src="https://cloud.githubusercontent.com/assets/579256/12373717/099844ac-bcb5-11e5-8d6f-c20172a76586.PNG">

**Comment by sriramab** [comment]
Also try adding a new variable. Say some variable in your ant species, and reload the model. You will not see this variable in the population browser. Close GAMA and restart a eclipse application (GAMA) then you see this variable. Simple reloads will not show this variable.

**Comment by AlexisDrogoul** [comment]
It depends what you call "reload". Reload for me is the button next to run, step, pause, etc. in the main toolbar. Relaunch, on the other hand, is launching the simulation again from the editor. And in the second case, the variable appears. Can you precise which operation you were speaking about ?
