### ISSUE TITLE
Template to comment the models

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1403]
Hi everyone, here you'll find the template to comment your gama model to put at the top of your model file :
```
/**
* Name: Name_Of_The_Model
* Author: The_Author
* Description: Description_of_the_model_and_the_experiments
* Tag : Tag1, Tag2, TagN

*/
```
For the tag list, the tags already existing are here (it is possible to create new ones) : 

3D Display
Batch
Camera Positionning
Clustering
Color
Comparison
CSV
Directed Graph
GIS
Graph
Grid
Import Files
Movements of Agents
Multicriteria
Save Files
Shapefiles
Shapes
Skill
Textures

**Comment by AlexisDrogoul** [comment]
The documentation of models should be done now quite urgently. How many models are there without proper documentation ? I raise this "issue" to the highest priority

**Comment by AlexisDrogoul** [comment]
Linking (and closing) it with Issue #1345
