### ISSUE TITLE
Potential deadlock when running Gama

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1410]
When I run GAMA with the profiler, a potential deadlock appears. Here is the message.

Frozen threads found (potential deadlock)
 
It seems that the following threads have not changed their stack for more than 10 seconds.
These threads are possibly (but not necessarily!) in a deadlock or hung.
 
process reaper <--- Frozen for at least 2m 58 sec
java.lang.UNIXProcess$ProcessPipeInputStream.processExited() UNIXProcess.java:373
java.lang.UNIXProcess.processExited(int) UNIXProcess.java:239
java.lang.UNIXProcess$4.run() UNIXProcess.java:227
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1142
java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:617
java.lang.Thread.run() Thread.java:744

**Comment by AlexisDrogoul** [comment]
Actually, it doesn't seem to be a problem: this process is blocked, waiting for a `closeLock` to be notified. Nothing to do with GAMA at first glance.
