### ISSUE TITLE
An error in the init of Experiments/Models/Agents is only briefly shown.

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1411]
Create an empty model with an experiment doing something like this (to force raising an error):

```
experiment e {
    init {
        error "Error";
    }

}
```
The error view is only displayed briefly before being discarded. The same piece of code in `global` and any species does the same.

However, it works fine once the simulation is run and this code is inside a `reflex`, for instance.

**Comment by RCura** [comment]
This might be a problem when running batch /headless simulations. Could you
try with a simple batch model ?
I can do that too, but only in a few days.
Le 17 janv. 2016 6:06 AM, "Alexis Drogoul" <notifications@github.com> a
écrit :
