### ISSUE TITLE
Error in Balls, Groups and Clouds model of the Library 

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1413]
When I want to test the multilevel architecture and set create clouds to true, I got this error : 

1 occurence in balls_groups_clouds_model0 at cycle 592: java.util.ConcurrentModificationException
in migrate ball_in_group target: ball_in_cloud ;
java.util.ConcurrentModificationException
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
java.util.ArrayList$Itr.next(ArrayList.java:851)
msi.gama.metamodel.agent.GamlAgent.migrateMicroAgents(GamlAgent.java:305)
msi.gaml.statements.MigrateStatement.privateExecuteIn(MigrateStatement.java:131)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.statements.RemoteSequence.privateExecuteIn(RemoteSequence.java:38)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gama.runtime.AbstractScope.execute(AbstractScope.java:406)
msi.gaml.statements.AskStatement.privateExecuteIn(AskStatement.java:144)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.statements.LoopStatement.loopBody(LoopStatement.java:243)
msi.gaml.statements.LoopStatement$Over.runIn(LoopStatement.java:314)
msi.gaml.statements.LoopStatement.privateExecuteIn(LoopStatement.java:235)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.statements.LoopStatement.loopBody(LoopStatement.java:243)
msi.gaml.statements.LoopStatement$Over.runIn(LoopStatement.java:314)
msi.gaml.statements.LoopStatement.privateExecuteIn(LoopStatement.java:235)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:57)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:73)
msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:64)
msi.gama.runtime.AbstractScope.execute(AbstractScope.java:409)
msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:186)
msi.gama.kernel.simulation.SimulationAgent._step_(SimulationAgent.java:144)
msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:156)
msi.gama.runtime.AbstractScope.step(AbstractScope.java:488)
msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
msi.gama.runtime.AbstractScope.step(AbstractScope.java:488)
msi.gama.kernel.experiment.AgentScheduler.step(AgentScheduler.java:98)
msi.gama.runtime.AbstractScope.step(AbstractScope.java:488)
msi.gama.runtime.FrontEndScheduler.step(FrontEndScheduler.java:88)
msi.gama.runtime.FrontEndScheduler.run(FrontEndScheduler.java:127)
java.lang.Thread.run(Thread.java:745)
in agent balls_groups_clouds_model0

**Comment by agrignard** [comment]
I have the same issue:

2 occurrences in 2 agents at cycle 1359: Java error: ConcurrentModificationException
in draw 'Number of groups: ' + string(length(world.agents of_generic_species group)) color: #blue at: point((environment_bounds.x / 2) - 210,environment_bounds.y / 2) size: 40 ;
ConcurrentModificationException: null
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
com.google.common.collect.Iterators$6.computeNext(Iterators.java:616)
com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
msi.gama.util.GamaListFactory.create(GamaListFactory.java:150)
msi.gama.metamodel.population.GamaPopulation.getAgents(GamaPopulation.java:723)
in draw 'Number of groups: ' + string(length(world.agents of_generic_species group)) color: #blue at: point((environment_bounds.x / 2) - 210,environment_bounds.y / 2) size: 40 ;
in aspect default  {
	draw 'Number of groups: ' + string(length(world.agents of_generic_species group)) color: #blue at: point((environment_bounds.x / 2) - 210,environment_bounds.y / 2) size: 40 ;
}

in agents Simulation 0, group_agents_viewer0

GAMA 1.8

**Comment by benoitgaudou** [comment]
It seems that I open basically the same issue, in issue #2345
