### ISSUE TITLE
Grid Display Rendering when the camera is in the XY plan

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1414]
When initializing a grid in opengl, the lines are not visible, you nedd to move a bit the camera to see the lines.

**Comment by agrignard** [comment]
I reopen this issue even if it's a detail but at least it is documented (the rendering is still not "perfect" for grid.)

When using 
display Life type: opengl{
  grid cityMatrix lines:#black;
}

You still need to move a bit the camera to see the line.

Whereas using

display Life type: opengl{
  species cityMatrix;
}

it's ok.

Not a big deal but I prefer to track it as I was a bit surprised no to have a good rendering when building a very simple grid model.

**Comment by AlexisDrogoul** [comment]
I come back to this one in the light of a problem uncovered by @benoitgaudou , in terms of performance of the display. using `lines` seems to be extremely slow. I wonder if we should not, when `lines` is specified and when we are not drawing a DEM, skip the `grid` and directly display the agents using `species`
