### ISSUE TITLE
Add layout: point in display 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1416]
It would be simple to add a layout facet to display to automatically create a layout in a display for all the charts inside. e.g.

instead of:
display Ants background: #white type: opengl {
    chart name: 'Proportion of workers' position: { 0, 0 } size: quadrant_size {}
    chart name: 'Proportion of workers' position: { 0.5, 0.0 } size: quadrant_size {}
    chart name: 'Proportion of workers' position: { 0.0, 0.50 } size: quadrant_size {}
    chart name: 'Proportion of workers' position: { 0.5, 0.50 } size: quadrant_size {}
}

We could have:
display Ants background: #white type: opengl layout: {2,2}{
    chart name: 'Proportion of workers'  {}
    chart name: 'Proportion of workers'  {}
    chart name: 'Proportion of workers'  {}
    chart name: 'Proportion of workers'  {}
}

**Comment by AlexisDrogoul** [comment]
Actually, it would not be so simple... I'm considering removing this request for enhancement, as it would require quite a lot of work to verify the consistency of the layout, the number of layers, the ones with or without position/size, etc. for a benefit which is not completely evident. Your thought ?

**Comment by AlexisDrogoul** [comment]
I close this issue as the enhancements made for #2287 allow to define a layout at the displays level (allowing to obtain the same effect, albeit in a different manner).
