### ISSUE TITLE
Freeze of GAMA when zooming in OpenGL views with Text.

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1428]
When displaying an OpenGL display, a sudden zoom in, while the simulation is running, can freeze GAMA and require a restart. It does not happen when the simulation is paused.

See attached picture.
<img width="1920" alt="capture 2016-01-18 a 19 58 24" src="https://cloud.githubusercontent.com/assets/579256/12391993/388ba7b2-be1e-11e5-8f10-8ff165a81513.PNG">

**Comment by AlexisDrogoul** [comment]
Seems to happen only when drawing text is involved.

**Comment by agrignard** [comment]
Any link with this issue #1291 ?
