### ISSUE TITLE
Clicking on a facet deprecated warning highlights the value of the facet instead of the facet itself

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#143]
**Is your request related to a problem? Please describe.**
As the title says, when you have a facet deprecated warning in the validation console and click on it, the text that becomes selected in the editor is the value of that facet and not the facet itself.
I don't know if it's the case for all warnings of that kind but it is at least the case for the `type` facet of the `save` statement.

![image](https://github.com/gama-platform/gama/assets/6374469/b3195703-c110-452a-9c0d-b3f30507ff58)

**Describe the improvement you'd like**
Either only the facet is selected or both the facet and its value are selected, but only the value doesn't make sense for that warning

**Comment by AlexisDrogoul** [comment]
I have committed a possible fix. Please test and report !
