### ISSUE TITLE
Signal - Removing neighbours creates null pointer exception

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1432]
In the model Signal from the Models Library,
removing the neighbours attributes of the grid creates a Java Null Pointer Exception, 
whereas it is not (at least not explicitly) used in the model.

2 occurences in 2 agents at cycle 0: java.lang.NullPointerException
in create signalGenerator number: 1 with: [color::°yellow, location::point(5.0,5.0), frequency::20];
java.lang.NullPointerException
msi.gama.metamodel.topology.grid.GamaSpatialMatrix$GridDiffuser.<init>(GamaSpatialMatrix.java:1635)
msi.gama.metamodel.topology.grid.GamaSpatialMatrix.getDiffuser(GamaSpatialMatrix.java:766)
msi.gama.metamodel.topology.grid.GamaSpatialMatrix.diffuseVariable(GamaSpatialMatrix.java:783)
msi.gaml.variables.SignalVariable._setVal(SignalVariable.java:192)
msi.gaml.variables.Variable.setVal(Variable.java:388)
msi.gama.metamodel.population.GamaPopulation.updateVariables(GamaPopulation.java:155)
msi.gama.runtime.AbstractScope.update(AbstractScope.java:706)
msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:182)
msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:156)
msi.gama.runtime.AbstractScope.step(AbstractScope.java:488)
msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
msi.gama.runtime.AbstractScope.step(AbstractScope.java:488)
msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:200)
msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:188)
msi.gama.kernel.simulation.SimulationAgent._step_(SimulationAgent.java:137)
msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:156)
msi.gama.runtime.AbstractScope.step(AbstractScope.java:488)
msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
msi.gama.runtime.AbstractScope.step(AbstractScope.java:488)
msi.gama.kernel.experiment.AgentScheduler.step(AgentScheduler.java:98)
msi.gama.runtime.AbstractScope.step(AbstractScope.java:488)
msi.gama.runtime.FrontEndScheduler.step(FrontEndScheduler.java:88)
msi.gama.runtime.FrontEndScheduler.run(FrontEndScheduler.java:127)
java.lang.Thread.run(Thread.java:745)
in agents signalGenerator0, Signal_model0

**Comment by AlexisDrogoul** [comment]
This issue has been solved by implementing the `neighbors` attribute for #1280
