### ISSUE TITLE
Mix the 2 picking methods in Opengl

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1434]
Actually the opengl picking is not able to return several objects that are at the same location. We should see how to use the same picking as in Java2D in Opengl.

**Comment by AlexisDrogoul** [comment]
Basically, it means that we need to manipulate a list of picked objects (and not only one object). Another solution would be to manipulate a hidden ROI to do so (with the problem that ROI selection is not accurate at all as it relies on the shapes of the agents and not on how they decide to draw themselves...)

**Comment by AlexisDrogoul** [comment]
I think this "enhancement" will be solved by the proposal to make the ROI "sticky" (see #1670 ) and allow the control-click to inspect what's inside the ROI at anytime. I close it, as I think what could be interesting will be the reverse: that Java2D provides the possibility to define an ROI... Open a new request in that case !
