### ISSUE TITLE
distortion of images when used as texture for a grid

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#144]
**Describe the bug**
When an image is used as a texture for a grid, it can become distorted. 

**To Reproduce**
1. Run the attached model.

You can see that in the grid texture display the star is not located in the center of the image contrary to the two other displays. Note that the problem is particularly visible for a grid with a low dimension (2x2 for example). 

**Desktop (please complete the following information):**
 - GAMA version: git (2024) - same problem with GAMA 1.9.3 (and older versions?)

[texture.zip](https://github.com/gama-platform/gama/files/14772202/texture.zip)

**Comment by AlexisDrogoul** [comment]
I have added a possible fix, please test !
