### ISSUE TITLE
Change the GAMA/Eclipse preferences 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1440]
As an example, by default when clicking on the results of a search to open models, they are always open in the same editor.
To avoid that, the Preference : General/Search/ Reuse editors to show matches should be unchecked.

More generally it could interesting to redefine the default preferences coming from eclipse.

**Comment by AlexisDrogoul** [comment]
I have added this preference as a default. A good reference can be found here for how to customize these preferences at startup: http://www.vogella.com/tutorials/EclipsePreferences/article.html#resources.

In the `.metadata` folder of Eclipse workspace, a number of `.prefs` files can be found (in `plugins/org.eclipse.core.runtime/.settings`. If you find any you'd like to put as a default in GAMA, do not hesitate !
