### ISSUE TITLE
Error / Show in editor does not go to the right file

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1441]
In the following model, I have an exception when opening a file.
This exception occurs in the init of a  species in a file different from the one used to run the experiment.
I the Error pane, when clicking on the Show in editor button, it opens the block in which I create the agent raising the exception.

[modelImport1.gaml](https://files.zenhub.io/569df3d9490c91ab5cb62ed1)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

[modelImport2.gaml](https://files.zenhub.io/569df3d9490c91ab5cb62ed2)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by AlexisDrogoul** [comment]
It works for me without problem. The "Show in Editor" correctly goes to modelImport2 at the right place.

Maybe it has been fixed by another commit ?
