### ISSUE TITLE
Deadlock when opening several charts

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1443]
In the ants model with cahrts exemples, not always, but sometimes I have a freeze of GAMA when creating a display.
 In the profiler I get the following deadlock report:

Frozen threads found (potential deadlock)
 
It seems that the following threads have not changed their stack for more than 10 seconds.
These threads are possibly (but not necessarily!) in a deadlock or hung.
 
AWT-EventQueue-0 <--- Frozen for at least 13 sec
sun.lwawt.macosx.CPlatformView.nativeGetLocationOnScreen(long) CPlatformView.java (native)
sun.lwawt.macosx.CPlatformView.getLocationOnScreen() CPlatformView.java:171
sun.lwawt.macosx.CViewPlatformEmbeddedFrame.getLocationOnScreen() CViewPlatformEmbeddedFrame.java:103
sun.lwawt.LWWindowPeer.getLocationOnScreen() LWWindowPeer.java:358
sun.lwawt.LWComponentPeer.getLocationOnScreen() LWComponentPeer.java:610
sun.lwawt.LWComponentPeer$DelegateContainer.getLocationOnScreen() LWComponentPeer.java:182
sun.lwawt.LWComponentPeer$DelegateContainer.getLocation() LWComponentPeer.java:177
sun.lwawt.LWComponentPeer$DelegateContainer.getX() LWComponentPeer.java:187
javax.swing.SwingUtilities.convertPointToScreen(Point, Component) SwingUtilities.java:389
javax.swing.SwingUtilities.convertPoint(Component, Point, Component) SwingUtilities.java:180
javax.swing.SwingUtilities.convertRectangle(Component, Rectangle, Component) SwingUtilities.java:217
sun.lwawt.LWComponentPeer$1.addDirtyRegion(JComponent, int, int, int, int) LWComponentPeer.java:244
javax.swing.RepaintManager.addDirtyRegion(JComponent, int, int, int, int) RepaintManager.java:485
javax.swing.JComponent.repaint(long, int, int, int, int) JComponent.java:4793
java.awt.Component.repaint() Component.java:3313
java.awt.Component.repaintParentIfNeeded(int, int, int, int) Component.java:2334
java.awt.Component.reshape(int, int, int, int) Component.java:2320
javax.swing.JComponent.reshape(int, int, int, int) JComponent.java:4207
java.awt.Component.setBounds(int, int, int, int) Component.java:2263
java.awt.Component.setBounds(Rectangle) Component.java:2407
sun.lwawt.LWComponentPeer.setBounds(int, int, int, int, int, boolean, boolean) LWComponentPeer.java:574
sun.lwawt.LWComponentPeer.setBounds(int, int, int, int, int) LWComponentPeer.java:548
java.awt.Component.reshapeNativePeer(int, int, int, int, int) Component.java:2350
java.awt.Component.reshape(int, int, int, int) Component.java:2298
java.awt.Component.setBounds(int, int, int, int) Component.java:2263
java.awt.BorderLayout.layoutContainer(Container) BorderLayout.java:838
java.awt.Container.layout() Container.java:1510
java.awt.Container.doLayout() Container.java:1499
java.awt.Container.validateTree() Container.java:1695
java.awt.Container.validate() Container.java:1630
sun.lwawt.macosx.CViewEmbeddedFrame$1.run() CViewEmbeddedFrame.java:99
java.awt.event.InvocationEvent.dispatch() InvocationEvent.java:301
java.awt.EventQueue.dispatchEventImpl(AWTEvent, Object) EventQueue.java:756
java.awt.EventQueue.access$500(EventQueue, AWTEvent, Object) EventQueue.java:97
java.awt.EventQueue$3.run() EventQueue.java:709
java.awt.EventQueue$3.run() EventQueue.java:703
java.security.AccessController.doPrivileged(PrivilegedAction, AccessControlContext) AccessController.java (native)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(PrivilegedAction, AccessControlContext, AccessControlContext) ProtectionDomain.java:76
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(PrivilegedAction, AccessControlContext) ProtectionDomain.java:86
java.awt.EventQueue$4.run() EventQueue.java:731
java.awt.EventQueue$4.run() EventQueue.java:729
java.security.AccessController.doPrivileged(PrivilegedAction, AccessControlContext) AccessController.java (native)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(PrivilegedAction, AccessControlContext, AccessControlContext) ProtectionDomain.java:76
java.awt.EventQueue.dispatchEvent(AWTEvent) EventQueue.java:728
java.awt.EventDispatchThread.pumpOneEventForFilters(int) EventDispatchThread.java:201
java.awt.EventDispatchThread.pumpEventsForFilter(int, Conditional, EventFilter) EventDispatchThread.java:116
java.awt.EventDispatchThread.pumpEventsForHierarchy(int, Conditional, Component) EventDispatchThread.java:105
java.awt.EventDispatchThread.pumpEvents(int, Conditional) EventDispatchThread.java:101
java.awt.EventDispatchThread.pumpEvents(Conditional) EventDispatchThread.java:93
java.awt.EventDispatchThread.run() EventDispatchThread.java:82

main <--- Frozen for at least 13 sec
java.awt.Window.setGraphicsConfiguration(GraphicsConfiguration) Window.java:3179
java.awt.Window.initGC(GraphicsConfiguration) Window.java:478
java.awt.Window.init(GraphicsConfiguration) Window.java:495
java.awt.Window.<init>() Window.java:537
java.awt.Frame.<init>(String) Frame.java:420
java.awt.Frame.<init>() Frame.java:385
sun.awt.EmbeddedFrame.<init>(long, boolean) EmbeddedFrame.java:97
sun.awt.EmbeddedFrame.<init>(long) EmbeddedFrame.java:94
sun.awt.EmbeddedFrame.<init>() EmbeddedFrame.java:82
sun.lwawt.macosx.CViewEmbeddedFrame.<init>(long) CViewEmbeddedFrame.java:46
sun.reflect.GeneratedConstructorAccessor95.newInstance(Object[])
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Object[]) DelegatingConstructorAccessorImpl.java:45
java.lang.reflect.Constructor.newInstance(Object[]) Constructor.java:422
org.eclipse.swt.awt.SWT_AWT$1.run() SWT_AWT.java:176
org.eclipse.swt.awt.SWT_AWT.new_Frame(Composite) SWT_AWT.java:184
msi.gama.gui.swt.swing.SwingControl.createFrame() SwingControl.java:248
msi.gama.gui.swt.swing.SwingControl.populate() SwingControl.java:235
msi.gama.gui.swt.swing.SwingControl.handleSetBounds(int, int) SwingControl.java:904
msi.gama.gui.swt.swing.SwingControl.setBounds(int, int, int, int) SwingControl.java:1061
org.eclipse.swt.layout.GridLayout.layout(Composite, boolean, int, int, int, int, boolean) GridLayout.java:693
org.eclipse.swt.layout.GridLayout.layout(Composite, boolean) GridLayout.java:197
org.eclipse.swt.widgets.Composite.updateLayout(boolean) Composite.java:1201
org.eclipse.swt.widgets.Composite.layout(boolean, boolean) Composite.java:710
org.eclipse.swt.widgets.Composite.layout(boolean) Composite.java:668
org.eclipse.swt.widgets.Composite.layout() Composite.java:631
msi.gama.gui.views.LayeredDisplayView.ownCreatePartControl(Composite) LayeredDisplayView.java:112
msi.gama.gui.views.GamaViewPart.createPartControl(Composite) GamaViewPart.java:163
org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(IWorkbenchPart, Composite) CompatibilityPart.java:151
org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(IWorkbenchPart, Composite) CompatibilityView.java:143
org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create() CompatibilityPart.java:341
sun.reflect.GeneratedMethodAccessor70.invoke(Object, Object[])
sun.reflect.DelegatingMethodAccessorImpl.invoke(Object, Object[]) DelegatingMethodAccessorImpl.java:43
java.lang.reflect.Method.invoke(Object, Object[]) Method.java:497
org.eclipse.e4.core.internal.di.MethodRequestor.execute() MethodRequestor.java:56
org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(Class, Object, Class, PrimaryObjectSupplier, PrimaryObjectSupplier, ArrayList) InjectorImpl.java:879<2 recursive calls>
org.eclipse.e4.core.internal.di.InjectorImpl.inject(Object, PrimaryObjectSupplier, PrimaryObjectSupplier) InjectorImpl.java:121
org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(Class, PrimaryObjectSupplier, PrimaryObjectSupplier) InjectorImpl.java:345
org.eclipse.e4.core.internal.di.InjectorImpl.make(Class, PrimaryObjectSupplier) InjectorImpl.java:264
org.eclipse.e4.core.contexts.ContextInjectionFactory.make(Class, IEclipseContext) ContextInjectionFactory.java:162
org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(Bundle, IEclipseContext, IEclipseContext, URI) ReflectionContributionFactory.java:104
org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(String, IEclipseContext, IEclipseContext) ReflectionContributionFactory.java:73
org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(String, IEclipseContext) ReflectionContributionFactory.java:55
org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(MUIElement, Object) ContributedPartRenderer.java:129
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(MUIElement, Object) PartRenderingEngine.java:971
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) PartRenderingEngine.java:640
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run() PartRenderingEngine.java:525
org.eclipse.core.runtime.SafeRunner.run(ISafeRunnable) SafeRunner.java:42
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(MUIElement, Object, IEclipseContext) PartRenderingEngine.java:509
org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(MUIElement, Object) ElementReferenceRenderer.java:69
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(MUIElement, Object) PartRenderingEngine.java:971
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) PartRenderingEngine.java:640
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(MUIElement) PartRenderingEngine.java:746
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) PartRenderingEngine.java:717
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run() PartRenderingEngine.java:711
org.eclipse.core.runtime.SafeRunner.run(ISafeRunnable) SafeRunner.java:42
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(MUIElement) PartRenderingEngine.java:695
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.subscribeTopicToBeRendered(Event) PartRenderingEngine.java:142
sun.reflect.GeneratedMethodAccessor83.invoke(Object, Object[])
sun.reflect.DelegatingMethodAccessorImpl.invoke(Object, Object[]) DelegatingMethodAccessorImpl.java:43
java.lang.reflect.Method.invoke(Object, Object[]) Method.java:497
org.eclipse.e4.core.internal.di.MethodRequestor.execute() MethodRequestor.java:56
org.eclipse.e4.core.di.internal.extensions.EventObjectSupplier$DIEventHandler.handleEvent(Event) EventObjectSupplier.java:83
org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(Event, Permission) EventHandlerWrapper.java:197
org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerWrapper, Permission, int, Event) EventHandlerTracker.java:197
org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(Object, Object, int, Object) EventHandlerTracker.java:1
org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(Set, EventDispatcher, int, Object) EventManager.java:230
org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(int, Object) ListenerQueue.java:148
org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(Event, boolean) EventAdminImpl.java:135
org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(Event) EventAdminImpl.java:78
org.eclipse.equinox.internal.event.EventComponent.sendEvent(Event) EventComponent.java:39
org.eclipse.e4.ui.services.internal.events.EventBroker.send(String, Object) EventBroker.java:85
org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(Notification) UIEventPublisher.java:59
org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(Notification) BasicNotifierImpl.java:374
org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setToBeRendered(boolean) UIElementImpl.java:303
org.eclipse.e4.ui.internal.workbench.PartServiceImpl.createElement(MUIElement) PartServiceImpl.java:1189
org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(MPart, EPartService$PartState) PartServiceImpl.java:1170
org.eclipse.ui.internal.WorkbenchPage.showPart(int, MPart) WorkbenchPage.java:1301
org.eclipse.ui.internal.WorkbenchPage.busyShowView(String, int) WorkbenchPage.java:1266
org.eclipse.ui.internal.WorkbenchPage$12.run() WorkbenchPage.java:4211
org.eclipse.swt.custom.BusyIndicator.showWhile(Display, Runnable) BusyIndicator.java:70
org.eclipse.ui.internal.WorkbenchPage.showView(String, String, int) WorkbenchPage.java:4207
msi.gama.gui.swt.SwtGui$13.run() SwtGui.java:433
org.eclipse.swt.widgets.Synchronizer.syncExec(Runnable) Synchronizer.java:186
org.eclipse.ui.internal.UISynchronizer.syncExec(Runnable) UISynchronizer.java:145
org.eclipse.swt.widgets.Display.syncExec(Runnable) Display.java:4781
msi.gama.gui.swt.SwtGui.run(Runnable) SwtGui.java:917
msi.gama.gui.swt.SwtGui.internalShowView(String, String, int) SwtGui.java:425
msi.gama.gui.swt.SwtGui.showView(String, String, int) SwtGui.java:539
msi.gama.outputs.AbstractDisplayOutput$1.run() AbstractDisplayOutput.java:39
org.eclipse.swt.widgets.RunnableLock.run() RunnableLock.java:35
org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(boolean) Synchronizer.java:135
org.eclipse.swt.widgets.Display.runAsyncMessages(boolean) Display.java:4024
org.eclipse.swt.widgets.Display.observerProc(long, long, long) Display.java:3613
sun.lwawt.macosx.LWCToolkit.doAWTRunLoopImpl(long, boolean, boolean) LWCToolkit.java (native)
sun.lwawt.macosx.LWCToolkit.doAWTRunLoop(long, boolean) LWCToolkit.java:825
sun.lwawt.macosx.LWCToolkit.invokeAndWait(Runnable, Component) LWCToolkit.java:642
sun.lwawt.macosx.CViewEmbeddedFrame.validateWithBounds(int, int, int, int) CViewEmbeddedFrame.java:95
sun.reflect.GeneratedMethodAccessor89.invoke(Object, Object[])
sun.reflect.DelegatingMethodAccessorImpl.invoke(Object, Object[]) DelegatingMethodAccessorImpl.java:43
java.lang.reflect.Method.invoke(Object, Object[]) Method.java:497
org.eclipse.swt.awt.SWT_AWT$5.run() SWT_AWT.java:325
org.eclipse.swt.widgets.RunnableLock.run() RunnableLock.java:35
org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(boolean) Synchronizer.java:135
org.eclipse.swt.widgets.Display.runAsyncMessages(boolean) Display.java:4024
org.eclipse.swt.widgets.Display.readAndDispatch() Display.java:3700
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run() PartRenderingEngine.java:1127
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm, Runnable) Realm.java:337
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(MApplicationElement, IEclipseContext) PartRenderingEngine.java:1018
org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(MApplicationElement) E4Workbench.java:156
org.eclipse.ui.internal.Workbench$5.run() Workbench.java:654
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm, Runnable) Realm.java:337
org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Display, WorkbenchAdvisor) Workbench.java:598
org.eclipse.ui.PlatformUI.createAndRunWorkbench(Display, WorkbenchAdvisor) PlatformUI.java:150
msi.gama.application.Application.start(IApplicationContext) Application.java:124
org.eclipse.equinox.internal.app.EclipseAppHandle.run(Object) EclipseAppHandle.java:196
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Object) EclipseAppLauncher.java:134
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(Object) EclipseAppLauncher.java:104
org.eclipse.core.runtime.adaptor.EclipseStarter.run(Object) EclipseStarter.java:380
org.eclipse.core.runtime.adaptor.EclipseStarter.run(String[], Runnable) EclipseStarter.java:235
sun.reflect.NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) NativeMethodAccessorImpl.java (native)
sun.reflect.NativeMethodAccessorImpl.invoke(Object, Object[]) NativeMethodAccessorImpl.java:62
sun.reflect.DelegatingMethodAccessorImpl.invoke(Object, Object[]) DelegatingMethodAccessorImpl.java:43
java.lang.reflect.Method.invoke(Object, Object[]) Method.java:497
org.eclipse.equinox.launcher.Main.invokeFramework(String[], URL[]) Main.java:669
org.eclipse.equinox.launcher.Main.basicRun(String[]) Main.java:608
org.eclipse.equinox.launcher.Main.run(String[]) Main.java:1515
org.eclipse.equinox.launcher.Main.main(String[]) Main.java:1488

process reaper <--- Frozen for at least 2m 30 sec
java.lang.UNIXProcess$ProcessPipeInputStream.processExited() UNIXProcess.java:528
java.lang.UNIXProcess.lambda$initStreams$271() UNIXProcess.java:299
java.lang.UNIXProcess$$Lambda$7.run()
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1142
java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:617
java.lang.Thread.run() Thread.java:745

**Comment by AlexisDrogoul** [comment]
I cannot reproduce this. It seems to be linked to the GraphicsConfiguration (AWT) and I guess it is more or less related to the other issues you have posted (on OpenGL).

**Comment by AlexisDrogoul** [comment]
I have posted a bunch of modifications in relation to #1585 . Can you try to see if, by any chance, it also solves this issue ?
