### ISSUE TITLE
Weird reload of the experiment in User Control Architecture 

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1449]
In the model User Control Architecture, in the folder User Interaction, in Features inside the models Library,
Launch the experiment, reload it, and there isn't cell anymore.
If you launch the experiment and activate advanced user control, there isn't any cell (even if you don't kill them and create 20). I think this come from the same problem of updating...

**Comment by AlexisDrogoul** [comment]
I cannot reproduce it. Maybe it has been solved by a previous commit...
