### ISSUE TITLE
Result unexpected when we try to write the "name_of_model_model" from the experiment

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1451]
When running the following model, the output message will be "list(multi_simulations_model)", which is not the result expected...

```
model multi_simulations

global {
}

experiment my_experiment type:gui {
	init {
		create simulation;
		create simulation;
		write list(multi_simulations_model);
	}
	output {
	}
}
```

**Comment by AlexisDrogoul** [comment]
OK. There was a trivial mistake in the serialization of simulations. `list(a_species)` returns a population which, in turn, serializes itself as a `list(a_species)` and returns itself when casted to a `list`. I committed something that should close the issue (which is purely about how populations write themselves, not how they behave).
