### ISSUE TITLE
Only the first declared diffusion matrix is taken in account for "diffusion" statement

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1469]
cf title

**Comment by hqnghi88** [comment]
Hi Julien,
Did we have fix this issue? I test with Anisotropic Diffusion (Simple) with 3 different matrix variable, it seem to be used right in diffusion statement.

**Comment by mazarsju** [comment]
The thing is we cannot "mix" diffusions right now. I almost finished this, I'll pull my modifications today.

**Comment by mazarsju** [comment]
Fixed thanks to issue #623.
