### ISSUE TITLE
Find something to draw in Java2D for SVG and OBJ files

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1473]

**Comment by AlexisDrogoul** [comment]
SVG is already present as a GamaShape. Just needs to make the switch either before calling drawFile or   after (if all the facets are passed: rotate, location, color).
For OBJ, probably the best would be to draw a square representing the envelope.

**Comment by AlexisDrogoul** [comment]
Already done for SVG. OBJ files will probably be only displayed as their envelope.

**Comment by AlexisDrogoul** [comment]
Java2D and OpenGL displays can now display all types of geometrical files (defined in GAMA, of course). For Java2D, the process is transparent (but without cache for the moment) and the OBJ files or other formats are displayed without problem. For OpenGL, I have generalized the approach taken for SVG files, which allows to cache DXF files, SVG files, any type of geometrical file (as long as it can be transformed into an IShape: even shape files can be drawn — and cached — this way !). 

There will probably be some issues arising about this possibility, but it creates a nice framework for displaying the contents of files directly. I will close this issue, but feel free to reopen for more focused issues concerning this subject.
