### ISSUE TITLE
Enable the rotate scene using the keyboard arrow

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1474]
Actually the keyboard arrow rotate around x and y it could rotate around the z axis to have the same effect as the rotate feature

**Comment by agrignard** [comment]
In the actual implementation in CameraArcball when the arrow are pressed it only changes phi and theta of the camera. According to the code (animate() method in CameraArcball) it should work when doing alt+right/left arrow but is not...

**Comment by agrignard** [comment]
It seems that this method rotateCameraUpVectorOnZ() is not doing anything... it increases the attribute "curZRotation" then call the updateCamera but it has no effect on the screen

**Comment by AlexisDrogoul** [comment]
OK. I've made it work in the next commit. I simply reused what was used for the rotation of the scene, and made ALT+LEFT and ALT+RIGHT change the value of the current Z rotation.
