### ISSUE TITLE
Enhance the zoom behavior in Opengl

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1477]
Need to change a bit how the zoom is handle in opengl. It' s too slow now.

A first attempt has been done in this commit f07a0ff77e7ab07fabca2493a74adaa1147c10ac but I prefer to revert the old one for the beta release to have the same behavior as before instead of a worse behavior.

**Comment by agrignard** [comment]
note: the preference has no effect now

**Comment by AlexisDrogoul** [comment]
I have simply added a simple computation (the current factor — 10 — multiplied by the preference — between 0.1 and 1) and it works quite well. I've put the preference at 0.5 for the default. I propose to close this now. Feel free to reopen.
