### ISSUE TITLE
Geometry cache is taking too many time when drawing obj and svg file

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1478]
We need to check why.

First I need to see why I have to cache the goemetry in a asynchronous way it should be done in a synchrone way.

**Comment by AlexisDrogoul** [comment]
Fixed in the last commit (237f264ee44e43ebc97c68335b9e73c7502838c2). Generating a new list while a list was opened was clearly a bad idea… But it was difficult to find it, as no error was outputted by JOGL.
