### ISSUE TITLE
Master branch don't build on fresh install

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#1482]
Hi, 
On fresh install, the master branch don't compile with error about `GraphicSkill` and `GamlGenerator` : 

    GraphicSkill cannot be resolved to a type	 
    GamlAdditions.java	

and also in 

    The type GamlGenerator is already defined	
    GamlGenerator.java

**Comment by AlexisDrogoul** [comment]
Have you tried to make a full build of all GAMA projects ? Looks like the metadata produced by the annotation processor is outdated.

**Comment by reyman** [comment]
I make a git pull to take last modification at 23:00, then i make a clean + synchronize.

GamlGenerator error persist.

**Comment by AlexisDrogoul** [comment]
Which version of XText do you have in your environment ?

**Comment by reyman** [comment]
I'm using the MARS version of eclipse, with link given in the git tutorial    

Version: Mars.1 Release (4.5.1)
Build id: 20150924-1200
  
```
Xtext Complete SDK	2.8.4.v201508050135	org.eclipse.xtext.sdk.feature.group	Eclipse Modeling Project
```

**Comment by AlexisDrogoul** [comment]
So we have the same installation. Strange. It is as if XText was trying to recreate GamlGenerator (which is normally created only once). When you do a full build, it doesn't build the grammar also, does it ?

**Comment by ptaillandier** [comment]
Hi,

Can you test to delete the gaml folder (by hand) in the msg.gama.core
project and to clean again.

Cheers,

Patrick

2016-01-23 9:07 GMT+01:00 Rey <notifications@github.com>:

**Comment by reyman** [comment]
I `rm` the gaml folder like @ptaillandier say, the workspace automatically rebuild, but error persist after clean. 

How can i force a full build ? I usually clean / synchronize / launch .

Seb.

**Comment by AlexisDrogoul** [comment]
No, the `gaml` folders have nothing to do with this. `GamlGenerator` is generated when you build or re-build the grammar using an MWE workflow. I wonder what happens, since Eclipse shouldn't try to rebuild the grammar (unless you ask it explicitly, of course). 

One thing you can try is:

- [ ] Put away the actual `GamlGenerator.java` file (copy it elsewhere, to your desktop, for instance). It can be found in the `msi.gama.lang.gaml.generator` package.
- [ ] Do a clean build and see if this file is recreated or not (either as  `GamlGenerator.java` or  `GamlGenerator.xtend`. 
- [ ] Delete the new one, move back the old one.

If you do a clean build again, what happens ?

**Comment by reyman** [comment]
Ok,

The file `GamlGenerator.java` in `msi.gama.lang.gaml.generator` doesn't appear after clean > rebuild all.

**Comment by AlexisDrogoul** [comment]
I wonder where this error was coming from. I will close the issue, as it is solved, but feel free to reopen it if it manifests again.

**Comment by RCura** [comment]
Just tried to update gama to master (843c0a7), in order to test #1366 

I did a hard reset to master, did the proper cleaning and rebuild, and can't compile/launch gama.
Here's the error :

    !SESSION 2016-01-03 14:09:02.053 -----------------------------------------------
    eclipse.buildId=unknown
    java.version=1.8.0_66
    java.vendor=Oracle Corporation
    BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
    Framework arguments:  -product msi.gama.application.product --launcher.defaultAction openFile
    Command-line arguments:  -product msi.gama.application.product -data /home/robin/eclipse_workspace/../runtime-gama1.7.Eclipse3_8_2.product -dev file:/home/robin/eclipse_workspace/.metadata/.plugins/org.eclipse.pde.core/gama1.7.Eclipse3_8_2.product/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog -data @noDefault --launcher.defaultAction openFile

    !ENTRY org.eclipse.osgi 4 0 2016-01-03 14:10:03.460
    !MESSAGE Application error
    !STACK 1
    java.lang.IllegalStateException: Workbench has not been created yet.
        at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
        at msi.gama.application.Application.start(Application.java:113)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

Any idea ?

**Comment by AlexisDrogoul** [comment]
I'm supposing you can build & compile it, and that the stack trace is the result of you launching GAMA ? 
Have you tried by renaming (or removing) your old GAMA workspace ?

**Comment by RCura** [comment]
When I want to launch gama, there's this screen :
![capture du 2016-01-27 12 33 03](https://cloud.githubusercontent.com/assets/807703/12612322/30a8fa38-c4f2-11e5-8018-0865d820b16b.png)

So, a lot of errors inside the modules (213 errors), for example : 
* msi.gama.application/src/msi/gama/gui/navigator/NavigatorContentProvider.java (L125) :  

          l.add(new WrappedPlugins(f, contents, "Requires"));  
    -> WrappedPlugins type cannot be resolved to a type

* /msi.gama.application/src/msi/gama/gui/views/actions/GamaToolbarFactory.java (L212) :   

        CSVExportationController csv = new CSVExportationController((IToolbarDecoratedView.CSVExportable) view);

    ->Multiple markers at this line - CSVExportationController cannot be resolved to a 
	 type - CSVExportationController cannot be resolved to a 
	 type

What's the best way to share all my errors ?

**Comment by AlexisDrogoul** [comment]
No wonder, with so many errors, that you can't launch it… But these errors are not normal in a fresh install. Are you sure you are on master ? WrappedPlugins, etc. all exist in my master branch.

**Comment by RCura** [comment]
This for sure is a clean master.
I did git fetch origin / git reset --hard master / git clean -f

I tried to remove the projects from my eclipse workspace, and adding them again.
Then, I did clean the projects (clean all), and it rebuilds with the same number of errors.

Using Eclipse Mars.1 Release (4.5.1) (Build id: 20150924-1200), with xtext 2.8.4.v201508050135
Still the same errors :/

**Comment by RCura** [comment]
It's finally working, no idea why. I still have errors with a few modules, but it doesn't stop Gama from launching.

**Comment by reyman** [comment]
When the maven branch is ready, one idea to limit this problem of compilation on
different platform can be automated with “autobuild”.
Something like travis work with tycho and maven for example : http://muelder.blogspot.fr/2015/08/building-eclipse-plugins-with-maven.html

2016-01-27 14:09 GMT+01:00 Robin Cura < notifications@github.com > :
It's finally working, no idea why. I still have errors with a few modules, but
it doesn't stop Gama from launching.
