### ISSUE TITLE
Unable to draw SVG files

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1487]
Hi,

I've tried to replace the usage of the SVG geometry in the Ants Sorting model to benefit from the direct display of the SVG file, but I am unable to use it.

Whatever I write (esp. trying to guess a `scale`), I dont see anything besides the grid. GAMA seems to draw something (as the display is a bit stuttered), but where ?

I've tried something like:

`draw (svg_file("../images/ant_normal.svg")) rotate: -90 + heading at: location empty: false color: #black;`

As mentioned in the previous issue, I think it is important to reuse the `size` facet to pass a bounding box to the geometry (and we could probably remove `scale` in that case). This would also help in Java2D to display "fake" geometries.

**Comment by ptaillandier** [comment]
Hi,

On my computer, if I use:
	draw file("../images/ant_normal.svg") size:3 color: color rotate3D: 90.0 - heading ::{0,0.0,1} ;
	
It is working. However, there are two issues:
* the images are not displayed at step 0, but only from step 1
* when changing a bit the orientation of the camera, there are some "z-fighting" problems.

**Comment by AlexisDrogoul** [comment]
Fixed in the last commit (237f264ee44e43ebc97c68335b9e73c7502838c2)
