### ISSUE TITLE
distance using a graph is x100 / x1000 bigger than distance using continuous space

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#149]
**Describe the bug**
We notice that the distance between 2 geometries using a road graph network is much bigger (x100 / x1000 sometimes) than the distance between the same geometries using the distance in the continuous topology.

```
		using topology(the_graph) {			
			write "Distance sur le graph : " + (b1 distance_to b2);
		}	
		using topology(world) {			
			write "Distance sur le world : " + (b1 distance_to b2);
		}	
		
		write "Distance à vol d'oiseau : " + (b1 distance_to b2);
```

**To Reproduce**
1. Go to 'Tutorials / Road Traffic / models / model".gaml"
2. Add in the `init` the following lines:
```
		building b1 <- building[0];
		building b2 <- building[length(building)-1];
				
		using topology(the_graph) {			
			write "Distance sur le graph : " + (b1 distance_to b2);
		}	
		write "Distance à vol d'oiseau : " + (b1 distance_to b2);
```
3. We get the results:
```
Distance sur le graph : 64481.845243940996
Distance à vol d'oiseau : 160.09161422199193
```

**Expected behavior**
Even it is expected that the distance is different, the factor (x400) seems too big. 
In particular, the world is around 1000m x 1000m, so a distance of 64481 m seems to big...

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.9.3

**Comment by ptaillandier** [comment]
is because the "distance" calculated by the graph doesn't correspond to a distance in meters, but to the sum of the path weights. In the model you've used, there's a speed coefficient involved which gives much higher values than the distance in meters. If you want the distance in meters, you have to calculate the path and then you can have the perimeter of its geometry (shape).

**Comment by benoitgaudou** [comment]
Hi,
in the model 3 of the tutorial, no weight is specified ...
In this case what are the weights ?

**Comment by ptaillandier** [comment]
You are right, there was a bug here. I fixed it. Can you test it now?

**Comment by lesquoyb** [comment]
@benoitgaudou

**Comment by benoitgaudou** [comment]
It seems much better:
we get before you fix:
```
Distance sur le graph : 64481.845243940996
Distance à vol d'oiseau : 160.09161422199193
```
and now 
```
Distance sur le graph : 511.10537903591774
Distance à vol d'oiseau : 160.09161422199193
```
which is coherent.
