### ISSUE TITLE
Artefacts appearing in the first display when drawing OBJ and SVG files (only OpenGL)

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1490]
It seems that the creation of the display list containing a cache for OBJ and SVG contents makes the object appear and I dont really know how to prevent it. This manifests by an object being drawn at its "normal" size, like in the 2 pictures below.

<img width="1025" alt="capture 2016-01-23 a 21 54 39" src="https://cloud.githubusercontent.com/assets/579256/12531333/4f83d7e0-c22a-11e5-9f00-d1da5695d909.PNG">
<img width="683" alt="capture 2016-01-23 a 23 35 08" src="https://cloud.githubusercontent.com/assets/579256/12531335/4fdd9eec-c22a-11e5-8c22-4208fcc4d56c.PNG">

Another problem is that SVG geometries appear to be shifted, like in the example below.

<img width="1053" alt="capture 2016-01-23 a 21 54 51" src="https://cloud.githubusercontent.com/assets/579256/12531343/69b20ae2-c22a-11e5-8b04-6ca3332e430f.PNG">

**Comment by ptaillandier** [comment]
I think the offset issue is now fixed (but not the artefact one)
