### ISSUE TITLE
CSV Agents.gaml - Run finished in Closing previous displays state

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1491]
When I run the model from Features / Data Importation / models / CSV Agents.gaml, after clicking on the main button, the model finished in the state 'Closing previous display'.

If I look closely to the state bar , it seems that it reaches the 'Simulation ready' but go to the 'Closing previous display'.

(Note that I tried to run other models it works.)

**Comment by benoitgaudou** [comment]
Hi Alexis,
Could you check you pushed this commit (in the GitHub commit timeline, I
cannot find it ).
Thank you in advance
Benoit

2016-01-24 20:22 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Well.. Yes, I did it. Unless someone removed it, it should be available from the link above...

**Comment by benoitgaudou** [comment]
Thanks,
Perhaps a too long update of GitHub ...
I can it now

benoit

2016-01-25 7:57 GMT+01:00 Alexis Drogoul <notifications@github.com>:
