### ISSUE TITLE
Following directions for compiling GAMA results in 42 errors and 139 warnings

### ISSUE THREAD

**Issue by enabrintain** [gama-platform/gama#1492]
I'm following the directions found at https://code.google.com/p/gama-platform/wiki/G__InstallingSvnVersion for building GAMA Developer version. 

Unfortunately I got these errors:

Project 'idees.gama.mapcomparison' is missing required source folder: 'gaml'	idees.gama.mapcomparison		Build path	Build Path Problem
Project 'irit.gaml.extensions.database' is missing required source folder: 'gaml'	irit.gaml.extensions.database		Build path	Build Path Problem
Project 'irit.maelia.gaml.additions' is missing required library: 'bin'	irit.maelia.gaml.additions		Build path	Build Path Problem
Project 'irit.maelia.gaml.additions' is missing required source folder: 'gaml'	irit.maelia.gaml.additions		Build path	Build Path Problem
Project 'msi.gama.core' is missing required source folder: 'gaml'	msi.gama.core		Build path	Build Path Problem
Project 'msi.gaml.architecture.simplebdi' is missing required library: 'bin'	msi.gaml.architecture.simplebdi		Build path	Build Path Problem
Project 'msi.gaml.extensions.fipa' is missing required source folder: 'gaml'	msi.gaml.extensions.fipa		Build path	Build Path Problem
Project 'simtools.gaml.extensions.physics' is missing required source folder: 'gaml'	simtools.gaml.extensions.physics		Build path	Build Path Problem
Project 'ummisco.gaml.extensions.rjava' is missing required library: 'bin/'	ummisco.gaml.extensions.rjava		Build path	Build Path Problem
The project cannot be built until build path errors are resolved	idees.gama.mapcomparison		Unknown	Java Problem
The project cannot be built until build path errors are resolved	irit.gaml.extensions.database		Unknown	Java Problem
The project cannot be built until build path errors are resolved	irit.maelia.gaml.additions		Unknown	Java Problem
The project cannot be built until build path errors are resolved	msi.gama.core		Unknown	Java Problem
The project cannot be built until build path errors are resolved	msi.gaml.architecture.simplebdi		Unknown	Java Problem
The project cannot be built until build path errors are resolved	msi.gaml.extensions.fipa		Unknown	Java Problem
The project cannot be built until build path errors are resolved	simtools.gaml.extensions.physics		Unknown	Java Problem
The project cannot be built until build path errors are resolved	ummisco.gaml.extensions.rjava		Unknown	Java Problem
The project cannot be built until its prerequisite msi.gama.lang.gaml is built. Cleaning and building all projects is recommended	msi.gama.lang.gaml.ui		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	cenres.gaml.extensions.hydro		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	dream.gama.opengis		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	idees.gama.weka		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	irit.gaml.extensions.test		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	msi.gama.application		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	msi.gama.headless		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	msi.gama.hpc		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	msi.gama.lang.gaml		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	msi.gaml.extensions.cplex		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	msi.gaml.extensions.humanmoving		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	msi.gaml.extensions.traffic2d		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	simtools.gamanalyzer.fr		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	simtools.gaml.extensions.traffic		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	simtools.graphanalysis.fr		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	ummisco.gama.communicator		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	ummisco.gama.gpu		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	ummisco.gama.opengl		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	ummisco.gama.serialize		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	ummisco.gaml.extensions.maths		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	ummisco.gaml.extensions.sound		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	ummisco.gaml.extensions.stats		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	ummisco.miro.extension		Unknown	Java Problem
The project was not built since it depends on msi.gama.core, which has build path errors	ummisco.miro.extension.traffic		Unknown	Java Problem
Unsatisfied version constraint: 'org.eclipse.core.expressions: 3.5.0'	MANIFEST.MF	/msi.gama.lang.gaml.ui/META-INF	line 22	Plug-in Problem

This seems like a problem with the SVN-to-Git conversion.
Thank you
Phil

**Comment by ptaillandier** [comment]
Hi,

This page is not the good one. Indeed, several months ago, we passed from
googlecode (and SVN) to github (and git). The up to date wiki page
concerning the installation of the GAMA developer version is this one:
https://github.com/gama-platform/gama/wiki/G__InstallingGitVersion

Cheers,

Patrick

2016-01-24 18:35 GMT+01:00 enabrintain <notifications@github.com>:

**Comment by enabrintain** [comment]
Awesome!
Thank you!
Phil
