### ISSUE TITLE
'refresh: false' locks the layers too soon for some displays

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1496]
It would be important to check more thoroughly the models in the library. I've found (by chance) that "GIS visualization" display number 2 (called "gis_display_image") is blank. Can someone check if the "image" layers are still working ?

**Comment by dphilippon** [comment]
Seems to work if you put the parameter refresh to "true". By the way, seems strange that it doesn't fit the documentation header template, maybe one i've missed. Going to take care of it !

**Comment by AlexisDrogoul** [comment]
So there might be a bug here. An image layer without "refresh: true" will not display ?

**Comment by dphilippon** [comment]
If you just remove refresh: true, or put refresh : true, the image will be displayed at the step 1, but in the contrary nothing appears. So it might be a bug

**Comment by agrignard** [comment]
Just a note, it works in java2D.

**Comment by AlexisDrogoul** [comment]
It seems that the "static" layers are locked too soon. I will investigate.
