### ISSUE TITLE
Batch experiments stopped

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1501]
If you launch the experiment Batch or Genetic in the model Ant Foraging Complex in the Toy Models Library, it will stop at the first simulation and never go to the second simulation.

**Comment by AlexisDrogoul** [comment]
I can't reproduce the problem on my version. Can you check again ? Since I've made some modifications to the core (incl. ExperimentAgent), it is possible I have "solved" the problem...

**Comment by dphilippon** [comment]
Problem solved, nice work. 
I close the issue then .
