### ISSUE TITLE
Serious display problems with text layers in OpenGL and Java2D

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1503]
The `text` layer is (in my opinion) completely broken. Look at these screenshots (in both Java2D and OpenGL displays).

I propose to rewrite it so that the size of the font to use is specified like in the draw statement (and not by the height of the layer).

<img width="1920" alt="capture 2016-01-27 a 16 53 28" src="https://cloud.githubusercontent.com/assets/579256/12609907/3f506f56-c517-11e5-89ee-f70d5bbf57e4.PNG">
<img width="1920" alt="capture 2016-01-27 a 16 53 57" src="https://cloud.githubusercontent.com/assets/579256/12609908/3fda496a-c517-11e5-8a18-a0752afaffd0.PNG">
<img width="1920" alt="capture 2016-01-27 a 16 55 00" src="https://cloud.githubusercontent.com/assets/579256/12609909/3fdfd57e-c517-11e5-93e3-7123f39c2142.PNG">
<img width="1920" alt="capture 2016-01-27 a 16 55 09" src="https://cloud.githubusercontent.com/assets/579256/12609910/3fe4bd82-c517-11e5-8134-ca34defd107e.PNG">

**Comment by AlexisDrogoul** [comment]
Currently working on this one while addressing #1499.

**Comment by AlexisDrogoul** [comment]
In the wake of this issue, I have transmitted to game-dev a proposal to remove `text` layers altogether. The same effects can be achieved with a `graphics` layer, and with only one way to draw text, we would probably gain in maintainability. Please comment, @gama-platform/committers & @gama-platform/core !

**Comment by RCura** [comment]
Gama wiki should be updated with those changes, especially [G__DefiningOtherLayers#text-layer](https://github.com/gama-platform/gama/wiki/G__DefiningOtherLayers#text-layer), which now is deprecated.

For the users updating their model, you could maybe specify that the `position :` facet should now be replaced with `at :`, and so you have to update from {0,1} relative coordinates to world_extent coordinates.

Other problem : the `size` facet doesn't work : no matter the size I put (whatever the magnitude, be it 20 or 20000), the text stays the same size. This doesn't seem to match with the current example of [graphics layers](https://github.com/gama-platform/gama/wiki/G__DefiningOtherLayers#graphics-layer)

So, I went from this :  

    display "Carte" {
        species Paroisses transparency: 0.9 ;
        species Zones_Prelevement transparency: 0.9;
        agents "Eglises Paroissiales" value: Eglises where (each.eglise_paroissiale) aspect: base transparency: 0.5;
        species Chateaux aspect: base ;
        species Foyers_Paysans transparency: 0.5;
        species Agregats transparency: 0.3;
        text string(Annee) size: 10000 position: {0, 1} color: rgb("black");
    }

to that :  

    display "Carte" {
        species Paroisses transparency: 0.9 ;
        species Zones_Prelevement transparency: 0.9;
        agents "Eglises Paroissiales" value: Eglises where (each.eglise_paroissiale) aspect: base transparency: 0.5;
        species Chateaux aspect: base ;
        species Foyers_Paysans transparency: 0.5;
        species Agregats transparency: 0.3;
        graphics "Annee" {
            draw string(Annee) size: 20 at: {0, 50000} color: rgb("black") ;
        }
    }

And size not working :sad:

**Comment by AlexisDrogoul** [comment]
You're right, we need to better document this. The documentation has not yet been updated with the recent changes. 

Regarding `position`, note that it can be used on the `graphics` layer as well (you have the choice of positioning the layer (by default at 0,0) or the text you are drawing (with `at:`)).

Finally, size is not effective anymore for texts/strings (but it is not yet documented, even in the editor); instead, you have to use the `font:` facet together with the `font(name, size, style)` operator, where `name` is the type name (e.g., "Helvetica", "Times", and so on), `size` the size in points (and not in model units — it can be dynamic, for instance `12 * #zoom` will render a text of size 12 when the display is not zoomed and greater when the display is zoomed in), `style` one of the three values #bold, #italic or #plain (or a combination of them, like #bold + #italic).

so your `draw` statement should be written : 

```
 draw string(Annee) font: ("Helvetica", 20, #plain) at: {0, 50000} color: rgb("black") ;
```

**Comment by RCura** [comment]
Thanks a lot :smile: 
Just for the record (if someone else has the same problem), it's as Alexis said (and isn't in the snippet) : `font` facet should be used with `font()` function, in my case : 

    draw string(Annee) font: font("Helvetica", 32, #bold) at: {0, 95000} color: rgb("black") ;
