### ISSUE TITLE
Cant seem to make rotate3D work correctly for SVG files — its implementation is strange

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1504]
Maybe this issue is addressed elsewhere in one of the numerous issues on the draw statement, but I can't make the rotate3D facet work for SVG files. An example can be found in the model Ants Sorting.

I havent found the time to investigate for OBJ files, nor to debug what is really passed to the IGraphics, but it is time to have one (and only one) rotate facet — and to eliminate, also, the 'rotate3D' attribute put in the shapes (???).

**Comment by ptaillandier** [comment]
The rotate attribute seems to work now for svg files (the rotate3D facet does not exist anymore). 
The cleaning of the draw facet (and the IGraphics interface) is still in working progress.

**Comment by AlexisDrogoul** [comment]
Right. I can now make them work, but there is a glitch (probably just a small thing):

- For an OpenGL display, in Ant Sorting, I need to add 90 to the heading to display the agents correctly
- For a Java2D display (I just committed), I need to add 270 to the heading.

Probably we need to harmonize this (but I dont know which one is "right")

**Comment by AlexisDrogoul** [comment]
The new `rotate` facet produces a ClassCastException in some models. I'm working on it.
