### ISSUE TITLE
Mouse event : add mouse_on (pour un hover), remove mouse_drag

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1510]
Since the simulation is paused when the mouse button is pressed, I think we can remove the "mouse_drag", or at least put it "depreciated", what do you think ?

I think also that adding a new event such as "mouse_on" for hover should be a good thing. Is such a thing possible ?

**Comment by agrignard** [comment]
Sorry I don't understand this issue

what do you mean by "Since the simulation is paused when the mouse button is pressed"?

what is "pour un hover"?

**Comment by mazarsju** [comment]
Well, I just want to say that when you press the left click, the simulation cannot continue until the moment you release the button (at least in Windows), that is why I think the "mouse_drag" is a bit useless for the moment...
I think it would be good to catch the event returning the mouse position in anytime through the "event" statement, so that we can use it for a "hover" event, when we put out mouse above an agent during the simulation. Alexis told me that this event was already triggered in the "overlay" panel, to show the mouse position.

**Comment by AlexisDrogoul** [comment]
Yes, it is technically feasible by making the layer a listener of the MouseTrack events. I will do it soon.

**Comment by AlexisDrogoul** [comment]
I have implemented a solution where the layer can receive `mouse_enter`, `mouse_exit` and `mouse_move` events. It is still highly experimental, but I will close this issue so that the feedback is provided on more specific aspects. An example has been provided in `Boids.gaml` (also committed).
