### ISSUE TITLE
The trace/fading is always blended against the display background 

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1512]
When drawing a layer with a trace, if the background is an image (like in Boids.gaml or the various Ants models), the icons or the geometries are fading using the background of the display (not the actual image). See in these two cases with a red background:

<img width="768" alt="capture 2016-01-29 a 16 59 22" src="https://cloud.githubusercontent.com/assets/579256/12672643/356b4922-c6aa-11e5-8817-9d664558d800.PNG">
<img width="936" alt="capture 2016-01-29 a 16 59 43" src="https://cloud.githubusercontent.com/assets/579256/12672645/35bea824-c6aa-11e5-9689-b51f28dc64c3.PNG">

**Comment by agrignard** [comment]
Mmm indeed not so nice... and it's not like this in gama 1.6.1 so obviously something has changed...

I'll try to check it but I don't see exactly where it comes from...

**Comment by AlexisDrogoul** [comment]
A first hint to discover the cause of this behavior is that, if the background is "locked" (i.e. with `refresh: false`), the trace is correct (i.e. blended with the background).

**Comment by agrignard** [comment]
I did not "digest" all the improvement/modification made in the drawStatement. Where should I look if I want to check the ImageLayer drawer?

The nice thing is that it's work with a static background so it should not be too hard to fix this issue. 

In the worth case we set by default a static background? Does the image can be recomputed? I mean it's a file no ? Or can it come from the simulation?

**Comment by AlexisDrogoul** [comment]
Well, the ImageLayer now basically does one thing: get a filename and call `drawFile(…)`. The same as the `draw` statement with a file. And both can have, of course, dynamic files … (see in Boids, for instance, where 3 different PNGs are used to draw the birds.

**Comment by agrignard** [comment]
Ok so I guess something has changed with the new signature sceneBuffer.getSceneToUpdate().addFile(file, attributes);
instead of 
sceneBuffer.getSceneToUpdate().addFile(fileName, scope == null ? null : scope.getAgentScope(), color, 1.0,location, dimensions, rotate3D, rotate3DInit, env);

Which is by the way much more clean. I'll dig it

**Comment by AlexisDrogoul** [comment]
Solved with previous commit.

**Comment by agrignard** [comment]
cool!
