### ISSUE TITLE
problem with the rotate facet in the model library

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1513]
I did not follow exactly what was the different change with the usage of the rotate facet but I just discover that some model like Boids/Boids 3D Camera movement.gaml does not work anymore and throw this error:

java.lang.Double cannot be cast to msi.gama.metamodel.shape.GamaPoint

do we need to change the syntax in the model or is it something wrong in Java?
what about the retrocompatibility with the 1.6 version?

**Comment by AlexisDrogoul** [comment]
The error is fixed in my version. Normally, the retrocompatibility is ensured in that the `rotate` facet now accepts both floats and pairs (with the axis).
