### ISSUE TITLE
OpenGL, Java2D and 'rotated_by' rotations are not the same...

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1514]
The same model is displayed below both in Java2D and OpenGL. The red triangles represent a simple triangle with no rotation applied when drawing it (`draw triangle(15) color: #red;`). The yellow ones represent a similar triangle, this time obtained with `draw triangle(15) color: #yellow rotate: 90;`, which means (for the user) a clockwise rotation of +90°. 

When using the GAML operator `triangle(15) rotated_by 90`, however, both display the same(the one obtained in Java2D). It means that all our rotations are anti-clockwise, except when applying a rotation in OpenGL.

We have to harmonize this (either by choosing one or the other solution) so that the `rotate` facet is coherent with `rotated_by` and that both displays can be used with the same expressions...
<img width="1495" alt="capture 2016-02-01 a 03 26 00" src="https://cloud.githubusercontent.com/assets/579256/12704783/2ba824a4-c895-11e5-98e2-dae1c9f85b96.PNG">

**Comment by ptaillandier** [comment]
It is maybe due of the sign of y-component: in OpenGL, I think the rotation operator takes into account the fact that the y value is 0 at the top and max at the bottom. I am not sure for the GAMA operators that seem to work clockwise.

**Comment by AlexisDrogoul** [comment]
OK. But how should I do that ? Besides, I think glRotated and glRotatef are used everywhere in the code, and I'm a little bit nervous to break things by changing the rotation…

**Comment by AlexisDrogoul** [comment]
OK. Figured it out. It is simply a matter of inverting the rotation angle specified by the user. And the number of calls is not so important, so I'll fix them.
