### ISSUE TITLE
In "Built-In shapes" some shapes cannot be textured (and are not drawn)

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1517]
3 of the shapes cannot be drawn in this model when they are textured. Although I reckon that the algorithm for texturing are not present, we should perhaps render them untextured anyway.. 

<img width="517" alt="capture 2016-02-01 a 17 38 39" src="https://cloud.githubusercontent.com/assets/579256/12715083/db4152f8-c90a-11e5-801e-c083184012cb.PNG">

**Comment by agrignard** [comment]
The plan, the mulitplan and the pyramid does not handle yet the texture.

To fix it the drawPlan() method in the JTSDrawer should be motidify by adding something like:
if (is_textured) {...}

**Comment by agrignard** [comment]
plan and multiplan are now ok for the texture. what about the pyramid? is it really worth drawing it with a texture?

**Comment by AlexisDrogoul** [comment]
Well. I'm not completely sure `pyramid` is actually necessary at all, but since we are offering it as a way to build 3D shapes, I would expect they are all treated the same way with respect to their various possibilities. And being textured in the display is one of them. So, yes. Either we remove `pyramid` altogether, or we implement its `textured` display...

**Comment by agrignard** [comment]
ok. It's possible to texture it but the result will be arbitrary strange as we will have to map a square texture on each the 4 triangles... On the base of the pyramid it will be ok.

**Comment by agrignard** [comment]
what about this?
![screen shot 2016-02-02 at 19 02 38](https://cloud.githubusercontent.com/assets/3928502/12759011/4519659c-c9df-11e5-8979-75ae4430e6f4.png)

**Comment by agrignard** [comment]
last thing before to close this issue. the border of the textured plan and multiplan are yellow... it should not
