### ISSUE TITLE
Modification of the documentation of the size facet (of layer): case where the size facet is higher than 1

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1522]
For instance, in the toy Models/boids model:

add a size facet to the image:
image 'background' file:'../images/sky.jpg' size: {0.5,0.5};

in this case, it is going to work (both in java2D and opengl)

But if you write:
image 'background' file:'../images/sky.jpg' size: {1.5,1.5};

The image is not drawn anymore (both in java2D and opengl).

**Comment by AlexisDrogoul** [comment]
Actually, it is displayed, but the size of the layer is 1x1. So you probably have a pixel somewhere :)
We should maybe document it better, but all sizes <= 1 correspond to a percentage of the screen. All sizes > 1 to an actual size. The same is true for position.

**Comment by ptaillandier** [comment]
Ok, so it is just a documentation issue. I changed the title.
