### ISSUE TITLE
Performance of charts

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1524]
Besides the problems linked to the fact that we use a Java2D backend for displaying charts, they seem to have some problems when it comes to rendering thousands of values using series. I wonder if I am the only one to see this. 

I have created a modified ` XYLineAndShapeRenderer.java ` to check where the performances bottlenecks were. I think we can vastly improve some areas. Can someone test it (drop it in the package `msi.gama.outputs.layers`, add the necessary exports from `msi.gama.ext`) ? 

Other things we could do are:

- [ ] giving the possibility to remove the grid / crosshairs 
- [ ] promoting charts as `displays` (not as layers)
- [ ] other ideas ? 

[XYLineAndShapeRenderer.java.zip](https://github.com/gama-platform/gama/files/115677/XYLineAndShapeRenderer.java.zip)

**Comment by pcaillou** [comment]
Hi,

Is the problem present even with marker:false?
I tested with 1.6.1 and 1.7 with both cumulative series and scatter and 
I have no problem (nice curve after 10k steps).
I join the gaml.
I have some strange things (flickering) with markers, I will do a little 
profiling to optimize it, but markers are useless after 100 ticks anyway.
One solution: disable markers automatically after a high number of steps?

Philippe

(and code here just in case attached file doesn't work:
experiment my_experiment type: gui {
     output {
         display "data_cumulative_serie_chart" type:java2D {
             chart "data_cumulative_serie_chart" type:series {
                 data "A" value:cos(cycle)
                 marker:false;
             }
         }
}
Le 03/02/2016 14:22, Alexis Drogoul a écrit :
>
> Besides the problems linked to the fact that we use a Java2D backend 
> for displaying charts, they seem to have some problems when it comes 
> to rendering thousands of values using series I wonder if I am the 
> only one to see this
>
> I have created a modified |XYLineAndShapeRendererjava| to check where 
> the performances bottlenecks were I think we can vastly improve some 
> areas Can someone test it (drop it in the package 
> |msigamaoutputslayers|, add the necessary exports from |msigamaext|) ?
>
> Other things we could do are:
>
>   * giving the possibility to remove the grid / crosshairs
>   * promoting charts as |displays| (not as layers)
>   * other ideas ?
>
> XYLineAndShapeRendererjavazip 
> <https://githubcom/gama-platform/gama/files/115677/XYLineAndShapeRendererjavazip>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gama-platform/gama/issues/1524>.
>


/**
 *  SimpleSerie
 *  Author: HPhi
 *  Description: 
 */

model SimpleSerie
global
{
}

experiment my_experiment type: gui {
	output {
		display "data_cumulative_serie_chart" type:java2D {
			chart "data_cumulative_serie_chart" type:series {
				data "A" value:cos(cycle)
//				accumulate_values: true
//				marker_shape:marker_empty
				marker:false;
			}
		}
		display "data_cumulative_scatter_chart" type:java2D {
			chart "data_cumulative_scattr_chart" type:scatter {
				data "A" value:{cycle,cos(cycle)}
//				accumulate_values: true
//				marker_shape:marker_empty
				marker:false;
			}
		}

	}
}
/* Insert your model definition here */

**Comment by pcaillou** [comment]
Hi,
After some profiling, I found the main time-consuming Jfree code:
auto-range applied for each data item. I made a small commit to apply it
only at the end of serie updating, and the bug I had even with Markers seem
to have disappeared, tell me if you still have problems!

Philippe

2016-02-04 16:09 GMT+01:00 Philippe Caillou <pcaillou@gmail.com>:

**Comment by AlexisDrogoul** [comment]
Great ! I havent tried your fix yet, but having faster charts will definitely help a lot of people. Shall we close this issue, then ?

**Comment by AlexisDrogoul** [comment]
I dont know if the fix has been pushed or not to master (is it the case ?) but charts appear to be definitely snappier. We can close this issue for now on, I guess…
