### ISSUE TITLE
Gama icon is still the eclipse's icon

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1526]
Hi,
Testing with Gama 1.7 beta release, the icon of Gama.exe is belong to eclipse Mars.

**Comment by AlexisDrogoul** [comment]
I have labeled the issue — I think Nicolas has already fixed it.

**Comment by gnoubi** [comment]
Yes it is done

nicolas
-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06
