### ISSUE TITLE
Suppress the warnings in the model library

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1527]

**Comment by AlexisDrogoul** [comment]
A lot of "new" warnings have been added in the last two weeks, which explains the poor state of the library — the fact is that models have been left untouched since one or two years...

**Comment by mazarsju** [comment]
Yes sure, I know that ;). I'm almost done, but I have a problem with "Boids
With Flocks"...

2016-02-05 20:41 GMT+07:00 Alexis Drogoul <notifications@github.com>:
