### ISSUE TITLE
Boids With Flocks model has errors

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1528]
In my git version, I have errors in "Boids With Flocks" : "goal" is not declared, neither is "obstacle". "apply_goal" is not know either. It seems there is an include file missing, isn't it ?

**Comment by AlexisDrogoul** [comment]
Well, the included file should be Boids.gaml itself. However, I wonder if I have not uploaded a wrong version of this file recently. I will check

**Comment by AlexisDrogoul** [comment]
Fixed in the latest commit.
