### ISSUE TITLE
Problem with OpenGL display when a texture does not exist

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1532]
test the following model:

model testTexture
global {
	init {
		create dummy;
	}
}
species dummy {
	aspect default {
		draw cube(10) texture: "donotexist.png";
	}
}
experiment testTexture type: gui {
	output {
		display map type: opengl{
			species dummy;
		}
	}
}

Good luck !

The fact that a texture is not found should emit a GAMARunTime Error (or warning).

**Comment by agrignard** [comment]
Strange... 

this was an old issue that has been closed during the coding camp... see issue #1281

Maybe something to do with the fact that the texture are not transformed in BufferedImage anymore?
