### ISSUE TITLE
Preferences "Set the width of lines drawn on display" strange behavior

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1533]
I am trying to play with the width of the line to enhance the rendering.

In some case when I change the value in the preferences I have a strange behavior, the value is set to nil and I cannot change it anymore.

If I restart Gama, the value by default is 0.0 whereas it should be 1.2. 

If I create a new workspace then I get the initial 1.2 value.

**Comment by AlexisDrogoul** [comment]
The question here is "In some case…" : which case ? Because I cannot reproduce this (I've tried several combinations of values, even 'nil').

**Comment by agrignard** [comment]
Strange...
If I create a new worskpace the value is by default 0.0... see screenshot
![screen shot 2016-02-09 at 10 42 06](https://cloud.githubusercontent.com/assets/3928502/12912528/7ed844a8-cf19-11e5-8adf-590f2b27ec79.png)

Can it be related to the new version of xtext??

I get this error now when launching GAMA

org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.generator [538]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.xtext.generator; bundle-version="[2.9.0,3.0.0)"; visibility:="reexport"

**Comment by AlexisDrogoul** [comment]
These preferences are not dependent on the workspace, but they are shared across all workspaces. So if you set the value to 0.0 in one workspace, it will be the same in another one.
Regarding XText, it's probably unrelated, but you should not have this error on startup. Have you installed the new version (2.9.1) ? (see here: https://github.com/gama-platform/gama/wiki/G__InstallingGitVersion#install-the-latest-xtext-version-currently-291).

**Comment by agrignard** [comment]
Ok I didn't know it was for all the workspace...

Ok for xtext it's ok now I forgot to synchronize in the product.

So i close this issue that was not really an issue ;-)
