### ISSUE TITLE
Preferences menu not available by default

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1534]
In the GIT version, when I launch GAMA , if I want to change the preferences, by default the preferences are not available (I have the eclipse preferences). if I go to eclipse and come back to Gamaa (cmd+tab) then I get the Gama preferences.

I would expect to have the Gama preferences by default.

**Comment by AlexisDrogoul** [comment]
How do you access them on the first trial (using the menu or using the keyboard shortcut — which should be COMMAND+,) ? The GIT version suffers from a longstanding bug in Eclipse that prevents GAMA menus to be available (see #871) and there is nothing we can do. However, normally, the keyboard shortcut lets you access the GAMA preferences even if you havent switched back and forth.

**Comment by agrignard** [comment]
ok it's already in the issue #871 so I remove this one
