### ISSUE TITLE
Problem with texture on complex shape 

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1541]
Run the model: Model Lbrary/Features/3D Visualization/GIS Visualization.gaml

One of the buildings (in the bottom left corner) has a problem with its roof texture. Note that I have often seen similar problems when applying textures on more complex building GIS data (OSM data of a city)

**Comment by agrignard** [comment]
Strange indeed... the shape is a bit complex but it should work...
![screen shot 2016-02-23 at 14 56 02](https://cloud.githubusercontent.com/assets/3928502/13253615/279bfec6-da3d-11e5-8fa8-a6e0a9a8f9ed.png)

**Comment by agrignard** [comment]
I don't see what happen here. 

Just for info, the shape is triangulated before to be drawn with this method GeometryUtils.triangulationSimple(null, p);

Maybe there is something wrong in the triangulation, a question of clock or anticlockwise?

![screen shot 2016-02-24 at 11 22 08](https://cloud.githubusercontent.com/assets/3928502/13282293/84e59f82-dae8-11e5-9d2a-43ff8e8ab238.png)
