### ISSUE TITLE
Model Library: Clock model does not work anymore

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1542]
Run the Model: Model Library/Toy Models/Clock/Clock.gaml : the result is not convincing...

**Comment by AlexisDrogoul** [comment]
I reopen this issue, as I'm still not convinced by the result. To speak frankly, I'm a bit lost in all the code of this model, but I know for sure that the time displayed is not in sync with the time in the model...

**Comment by dphilippon** [comment]
I've something which seems to work, I'll commit it however, there is differences between the simulated time (in the display bar) but "normal" for me in the step... Can you test it ?

**Comment by AlexisDrogoul** [comment]
What do you mean by 'there is differences between the simulated time (in the display bar) but "normal" for me in the step' ??? I dont get it.

**Comment by dphilippon** [comment]
My mistake, forgotten to add #ms in the model at the step parameter definition. I thought it was the initial unit for a step (such a blasphemy).. My bad, just added it in the model and comitted it...

**Comment by AlexisDrogoul** [comment]
OK. Seems to work now. I'm just a bit puzzled by the parameter "Milliseconds/cycle" and its initial value (3600). Wouldn't it better be "Seconds/cycle" ? Anyway, I reclose the issue...

**Comment by dphilippon** [comment]
I've put the initial value to test hour and minutes, but yeah I agree with you that putting the seconds by cycle would be preferable instead of milliseconds..
