### ISSUE TITLE
forgotten image on the release

### ISSUE THREAD

**Issue by gnoubi** [gama-platform/gama#1543]
Debug: ERROR: Cannot find icon /icons/editor.serialize2.png in plugin: msi.gama.applicationGAMA Caught a workbench message : ERROR: Cannot find icon /icons/gaml/_cells.png in plugin: msi.gama.application
GAMA Caught a workbench message : ERROR: Cannot find icon /icons/gaml/_quick_cells.png in plugin: msi.gama.application

**Comment by AlexisDrogoul** [comment]
No, these images are not forgotten, they simply correspond to (1) a menu in the editor ("serialize") that I have decided to remove anyway; (2) non-existing icons of variables in the outline;

I will nevertheless suppress the messages.
