### ISSUE TITLE
Ubuntu 12.04 (on Parallels) - Experiment buttons are not displayed - no experiment runnable

### ISSUE THREAD

**Issue by gnoubi** [gama-platform/gama#1544]
Ubuntu 12.04 - 
parallels@parallels-Parallels-Virtual-Platform:~/Bureau/gama1_7_b1_linux64$ java  -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

console messages : 
Thread [main]
Resource Anisotropic%20Diffusion%20(Cycle%20Length).gaml building
****************************************************
Description of agent
	abstract model
		description of /Anisotropic Diffusion (Cycle Length).gaml
	Description of experiment
		Description of diffusion
	Description of graph_edge
	Description of graph_node
	Description of base_edge
	Description of Physical3DWorld
	Description of AgentDB
	Description of cells
	Description of quick_cells

GAMA Caught a workbench message : ASKING THE USER ABOUT CHANGING

**Comment by AlexisDrogoul** [comment]
Does it manifest only for this model ?

**Comment by gnoubi** [comment]
no, it it is the same for all
-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06

**Comment by AlexisDrogoul** [comment]
Is it possible to run the experiments from the navigator ? Is there any other log messages ? (because the last one lets suppose that an experiment is about to be launched). Does resizing the view change anything ? Is the button "Other…" available on the right side of the view ?

**Comment by gnoubi** [comment]
Hi
> Is it possible to run the experiments from the navigator ?
> 
no it isn’t. 

> Is there any other log messages ? (because the last one lets suppose that an experiment is about to be launched).
> 
there is no message. the experiment seems to be launched because the window is resized, the 2D display appear but without any tab. see the screenshot 


> Does resizing the view change anything ? Is the button "Other…" available on the right side of the view ?
> 
yes. I think there is a window refresh problem

**Comment by AlexisDrogoul** [comment]
Which screenshot ?

**Comment by AlexisDrogoul** [comment]
The screenshots need to be png or jpg (or zip files ?)

However, I've tried with the same configuration on Ubuntu 14.04 and it works perfectly. I dont know exactly the state of the Linux distros, but would it be difficult to recommend this version for people using GAMA ? It is already difficult to maintain the Linux version due to the lack of testers, so having one recommended environment would probably be quite helpful...

**Comment by RCura** [comment]
On Ubuntu 15.04, buttons are there (and so do the explorer buttons), and the experiments can be launched.

**Comment by AlexisDrogoul** [comment]
So I propose to close this issue and to state that Ubuntu needs (at least) to be at version 14.04.
