### ISSUE TITLE
Stupid model tutorials are outdated

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1547]
… and I wonder how they can still work… 

For instance, all of them use the now deprecated `cell.agents` form to access the agents inside a grid cell. 

The real question, of course, is whether we should keep this tutorial alive or not.

**Comment by ptaillandier** [comment]
Personally, I have no problem with the fact to remove this tutorial. It is
a bit redundant with the predator pray tutorial.

2016-02-15 22:50 GMT+01:00 Alexis Drogoul <notifications@github.com>:
