### ISSUE TITLE
Generate the model library in markdown format

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1552]
Need to build a script in the "documentation" project that will create the model library in md format. This script will:
- 1 : parse all the models of the model library, in order to build "input" files for a headless execution.
- 2 : browse a second time all the models, and call the headless script for each one of the models. For each models, build the md file, including the screenshot computed from the headless execution.

The whole process has to raise errors if some are found. The whole process may take a while !

NB : maybe add a handmade xml to determine what experiment/display/cycle for the screenshot. By default, screenshot for all the experiments/displays, when cycle=10.

**Comment by mazarsju** [comment]
I'll try to do that. But I need the gamaHeadless.bat first...

**Comment by AlexisDrogoul** [comment]
I've moved this issue to : https://github.com/mazarsju/gama_doc_17/issues/11
