### ISSUE TITLE
Multi-scale and agent references

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1556]
Working on serialization of simulation, I am facing difficulties to restore attributes that refer to another agent. As the serialization is based the SavedAgent introduce for the multi-scale, I checked how it is done there and this raises some questions. I use the simple following model:
```
model testMulti

global {
	init {
		create toto ;
		
		create yo number: 2{
			t <- one_of(toto);
			y <- one_of(yo);
		}
	}
	
	reflex w {
		write "toto " + list(toto);
		write "yo " + list(yo);
	}
}

species toto {
	
	reflex cap when: empty(members) {
		list<yo> ly <- list(one_of(yo));
		write "capture: " + ly;
		capture ly as: yo_in_toto;
	}
	
	reflex rel when: !empty(members) {
		write "release " + members;
		release members as: yo;
	}
	
	species yo_in_toto parent: yo {
		
	}
}

species yo {
	toto t ;
	yo y;
	
	reflex w {
		write " t : " + t + " yo " + y;
	}
}

experiment testMulti type: gui {
	output {}
}
```

When I browse the population of yo agents, I initially get a value for the y attribute, but I become nil after few steps (more precisely, after it becomes captured).

In addition I noticed something strange: in the console I write some information, and for example I have : 

toto [0 as toto]
yo [21 as yo,23 as yo]
capture: [21 as yo]
release [[22 as yo_in_toto]]
 t : toto0 yo yo0
 t : toto0 yo yo1

toto [0 as toto]
yo [23 as yo,24 as yo]
capture: [24 as yo]
release [[23 as yo_in_toto]]
 t : toto0 yo yo0
 t : toto0 yo yo1

First thing: the agents that were captured and then released are not the sames (they do not have the same id). But they still have the inital name (yo0 and yo1), we can check it in the browser.
Second, whereas the browser displays nil for y attribute, the write statement displays a non-nil value yo1 or yo0.

So I do not know whether this is the expected behavior for multi-scale (and I have to work more for the unserialization or if this is an issue.

**Comment by AlexisDrogoul** [comment]
Hi,

It's not completely evident to follow your example (the names of the species are not especially informative !). But I have a few comments.

Regarding the id: there are no methods in Populations to create (or recreate) agents with a given index. Instead the index is incremented for each creation or recreation (for instance the `22` becomes a `24` after having been captured and then released). The `capture` and `release` statements are not intended to recreate the exact identical agent, but a similar agent. Maybe we can discuss this if you feel it should recreate an identical agent (incl. its index).

Regarding the value of `y`: I debugged to understand what's happening here, and I understood the difference between the browser/inspector and the write statement. Browsers, inspectors and monitors use the serialization of values to display them (so as to have a GAML expression that can be reevaluated again if necessary), while `write` uses their conversion to a string. In the case of agents, the serialization produces `index as species_name` and `nil` if the agent is dead, which is the case here. I agree it was a bit misleading, so I have now replaced it with `species_name[index]` + the comment `/* dead */` if the agent is dead. In the conversion to a string, only the name of the agent is used; but an error prevented the correct name (`name (dead)`) to be displayed. It is also now corrected. 

So, in the forthcoming version (I still have to test it), the value of y in the browser will be `yo[0] /*dead*/`and the write statement will output `t: toto0 yo yo0 (dead)`.
