### ISSUE TITLE
Unify agents' attributes and shapes' attributes

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1558]
Right now, we have an attributes map in agents and another attributes map in shapes. Since an agent can only have one shape (and is required to have one), it would make sense that we unify these two maps and put it in GamaShape (the methods in agents doing transparently the reading / writing of this map instead of their own). It would allow (1) to speed up certain operations (like `get` or `read`); (2) to reduce the memory footprint of agents.

The only possible drawback (but wouldn't it be a feature instead ?) is that, when creating shapes from GIS files, and if agents declare an attribute with the same name as an attribute of the file, its values will be automatically set.

**Comment by ptaillandier** [comment]
Hi,

It seems a good idea for me.

Cheers,

Patrick

2016-02-18 20:12 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Closed by the previous commit. Now we need to see what it changes … Already it should allow to directly benefit from the fact that attributes with the same name as attributes in ShapeFiles will be directly initialized. But this may create some problems, especially if the type read and the type declared are not the same.
