### ISSUE TITLE
Diffuse needs to be improved

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1561]
"Diffuse" statement is working in the current git version, but it is a bit slow... Some improvements may be possible.

**Comment by AlexisDrogoul** [comment]
It would be interesting to do some benchmarking between `diffuse` and `signal` in the same models. My recent partial tests reveal that the gap is not so great. The only problem I see is that the result is not exactly the same (i.e. the diffusions do not follow the exact same pattern)

**Comment by mazarsju** [comment]
I don't see really how I can improve the algorithm... I close this issue, feel free to reopen it if it does not suit you
