### ISSUE TITLE
Generated doc for built-in is empty

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1562]
The generated doc files for "agent built-ins", "experiment built-ins" and "model built-ins" are empty currently.

**Comment by mazarsju** [comment]
Any news for this one ?

**Comment by AlexisDrogoul** [comment]
I dont clearly understand what this issue is about. Can you tell more precisely ? Is it a bug, a failure ?

**Comment by benoitgaudou** [comment]
More an enhancement or a lack to fix in fact.
Some information are not yet extracted by processor and generated in the docGAMA.xml (in particular everything related to generic/minimal agent like init, die and so on ... )

**Comment by mazarsju** [comment]
Any updates for this issue Benoit ?
