### ISSUE TITLE
Documentations on projects built with GAMA

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1565]
For the new website, a presentation of the different projects where GAMA is present is needed. For each one of the main projects, it would be nice to have :
- The name of the project
- Date of the project
- A quick description (4-5 lines)
- Link to the project page (if it exists)
- Screenshot(s) of the project

Here is the wiki link to add the descriptions : https://github.com/mazarsju/gama_doc_17/wiki/Projects

**Comment by AlexisDrogoul** [comment]
Moved to: https://github.com/mazarsju/gama_doc_17/issues/7
