### ISSUE TITLE
Fix the translation with mouse in OpenGL

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1568]
When running a model and displaying it in OpenGL, the side translation one can do with the mouse becomes unbearably slow when the zoom is important, almost to the point where it is impossible to do. We need to either propose a more important side translation or allow the user to adjust it using a preference.

**Comment by agrignard** [comment]
Ok I'll have a llok.

i think we just have to modify the transaltion value according to the Z in the moveXYPlan2() method

**Comment by agrignard** [comment]
Ok so now the translation value is 

translationValue = FastMath.abs(diffx) * ((z + 1) / w );

so when z is closed to 0 the translation has no effect. I don't know yet what formula to put instead but I will try different one

**Comment by agrignard** [comment]
What about this?

I have change the way to do it. The translation is computed according to the "RealWorld translation". It seems to work not so bad but it need to be test a bit before to close this issue.

**Comment by AlexisDrogoul** [comment]
I think we can close the issue. The translation in XY is working pretty well now.
