### ISSUE TITLE
list on a matrix

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1570]
Please the 2 lines of code:
	matrix<int> mat <- matrix([[1,2],[3,4]]);
	write list(mat);

I was expecting to get the list of all elements, but I get in the console:
[[I@1e0dd09c]

**Comment by AlexisDrogoul** [comment]
OK. This is due to the array of primitive types manipulated by GamaIntMatrix and GamaFloatMatrix. No problem if you had converted it to `list<int>(mat)`, but the case without explicit casting of the contents was not taken into account.
