### ISSUE TITLE
map initilisation at hand

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1571]
I was trying to initialize map at hand like: 
		map<string,int> mmmp <- map(["a"::1,"b"::6]);
		write mmmp;
		
		map<string, list<int>> mp <- map(['hello'::[1,2], 'titi'::[5,6]]);
		write mp;
		
		map<string, int> mmp;
		write mmp;
		put 4 at: 'r' in: mmp;
		write mmp;	
But the result of the 2 first displays shows empty maps (I was expecting it worked to initialize maps):
map([])
map([])
map([])
map(['r'::4])

**Comment by AlexisDrogoul** [comment]
OK. This is due to commit c0f42cfd5d45fbdcfe04972f91bc8a7d8dd95df7.

The immediate workaround is to turn off optimization of constant values in the preferences. I will commit later a fix.
