### ISSUE TITLE
Discrepancy between envelope and shape obtained from GamaDXFFile

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1572]
In the `house.dxf` file present in the models library, there is a discrepancy between the envelope (computer after doc.getBounds()) and the resulting GamaShape (where the 3 last points lie outside of the envelope). Is there a property that the DXF parser respects (but not GAMA) about omitting these points ?  This bug is one of the causes of #1563 . 
If it is too complicated, a workaround could be to return the intersection between the computer GamaShape and the envelope.

**Comment by ptaillandier** [comment]
I will have a

**Comment by AlexisDrogoul** [comment]
I have taken a look, and found suspicious items in the file. They are tagged "MURS" (while the other walls are tagged "walls"). Problem is, I dont know if they are being discarded or not when the envelope of the doc is built. If someone manipulating DXF files could have a look — it would at least allow us to understand the cause of this strange behavior.

**Comment by ptaillandier** [comment]
To be honest, I lost my faith in the DXF format after passing a day trying
to convert a DWG file to a DXF one with different CAD softwares without
success (and the DXF format seems to change every years.....).

So, I think, my workaround will be enough for the moment, and we will try
one day to propose a new plug-in for GAMA 1.7 dedicated to the reading of
other CAD file formats... (I hope we will find good java libraries for
that).

2016-02-24 10:08 GMT+01:00 Alexis Drogoul <notifications@github.com>:
