### ISSUE TITLE
current_date and starting_date are nil

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1573]
The world has 2 built-in variables initialized at nil (current_date and starting_date).
They should have an initial non-null value.

**Comment by AlexisDrogoul** [comment]
Actually (but I let @ptaillandier answer to this one) they can (and should in most cases) be  `nil`. This null value represents the fact that the management of dates obeys to the default management of GAMA (1 month = 30 days, etc.). When starting_date is not null (i.e. set by the modeler), we enter a management of dates that will obey to a realistic calendar.
