### ISSUE TITLE
Generate GAML main keywords for each model

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1576]
For the website, each model have to be tagged with GAML words.

A script should be written which compile all the models, and write for each model a small txt file with the gaml keywords used, respecting the format used in the database of the website :
- "statement_nameOfTheStatement"
- "species_nameOfTheSpecies"
- "operator_nameOfTheOperator"
- "architecture_nameOfTheArchitecture"
- "skill_nameOrTheSkill"
Only the keywords used in less than 20 models have to be written in the small txt file.

This script will then be integrated inside the java script #1552.

**Comment by AlexisDrogoul** [comment]
Another possibility would be to generate this file systematically in the
metadata of the models during compilation. There,  we have access to all
the structures used in each model.

**Comment by mazarsju** [comment]
Yes should be a good idea to generate this file systematically. Ok to generate all the keywords and to post-treat them after in the script of #1552.
Yes sure, I forgot about this one : "constant_nameOfConstant".

The signature of operators which have the same name are regrouped under the same name. "+" will be "operator_+". Those very "common" operators will not be present in the search of the website anyway.

**Comment by AlexisDrogoul** [comment]
What should go under "species" ? Only the built-in species ? 
And what about the types ?

**Comment by AlexisDrogoul** [comment]
Regarding the format of the file, wouldn't it be simpler to have the equivalent of a properties file ? There is already a class in msi.gama.processor called GamlProperties, which can be used for that purpose. 

Its usage is quite simple (creation, storage, reload,…). It maintains internally a multi-map.

The format of the .meta file would be, in that case (on a fake example):
```
plugins=msi.gama.aaa~msi.gama.bbb
statements=write~do~reflex
architectures=fsm
operators=+~-~collect
skills=moving~fipa
constants=m~px~s
… etc … 
```

The separator '~' is a constant of this class. And the keys can be defined in that class (some of them already exist).

**Comment by mazarsju** [comment]
Under "species" will go only the built-in species, yes. Under "types", it is types such as "list", "int", ...
Yes, using the current .meta generated file to add those information is a good idea. This format of the .meta suits me fine.

**Comment by AlexisDrogoul** [comment]
All right. Almost finished. 

Here are some examples of the new ".meta" files:

```
#
#Thu Feb 25 16:43:31 ICT 2016
operators=as~envelope~count~.~sum~collect~read~shuffle~*~\=~length~>\=~at~rnd~-~at_distance~first_with~>~\!~\!\=~circle~rgb~+~/~any_location_in~?~empty~\:~mean~square
plugins=msi.gama.core
statements=action~write~create~arg~set~ask~do~reflex~if~aspect~draw~add~remove~init~output~display~display_population~chart~data
skills=reflex
constants=white~black~blue~lightgray~green~yellow~red
types=list~int~unknown~string~file~geometry~point~agent~float~date~rgb~container~bool
actions=error~debug~tell~write~die~_step_~_init_~halt~pause
```

```
#
#Thu Feb 25 16:43:31 ICT 2016
operators=grid_file~envelope~shape_file~where~\=~.~shuffle~max_of~-~/~circle~as~distance_to~first~?~\:~internal_at~closest_to~using~+~neighbors_at~count~length~*~as_edge_graph~or~\!\=~sort_by~last
plugins=msi.gama.core~ummisco.gama.opengl
statements=action~let~ask~set~aspect~draw~using~return~init~create~do~reflex~output~display~display_grid~display_population
skills=reflex~grid
constants=cyan~black~white
types=list~int~unknown~string~file~geometry~point~agent~float~date~rgb~graph~container~topology~bool
actions=error~debug~tell~write~die~_step_~_init_~halt~pause
```

 Anything missing at first glance  ?

**Comment by AlexisDrogoul** [comment]
I will commit and close the issue. Please reopen if you find anything missing or wrongly outputted.
