### ISSUE TITLE
msi.gama.output.layers error

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1579]
Hi,

When I installed gama git version, I am getting error in msi gama core and specifically in msi.gama.output.layers in overlay statement and in setTarget(IupadterTarget)

could you please tell me what is wrong and how can i fix it?

thanks
Srirama

**Comment by ptaillandier** [comment]
Hi,

It is normal, we all have this error for the moment (Alexis is going to fix
it soon). Even with this error, you can normally run GAMA ;) .

Cheers,

Patrick


2016-02-24 18:30 GMT+01:00 Srirama Bhamidipati <notifications@github.com>:

**Comment by sriramab** [comment]
Oki Thank you :)
