### ISSUE TITLE
Create models for language-specific features

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1581]
In the continuation of Issue #1549 (which I close as this one is more general), we should enhance the Syntax subfolder of the Library models and create models for little known aspects of the language itself:
- [x] Create a model about the scheduler/scheduling properties
- [x] Create a model about the order of initialization of species (create blocks, attribute initialization, init block)
- [x] Remove and/or change the Syntax model (now a bit obsolete)
- [x] Create a model about the various constants/units (incl. the ones used in displays)
- [x] Create a model on tests
- [x] Create a model to show how to make loops (`loop`, `ask`, implicit loops by scheduling agents, implicit loops with side effects in container operators)
- [x] Create a model to show how to use conditions (`if`, `switch/match`, conditions in reflexes, transition in states)
- [x] Create a model on Matrices
- [x] Create a model on Graphs (with graph related species as well ?)
- [x] Create a model on accessing agents' attributes (with `agt.att`, `agent[att]`, `att of agent` and which attributes are present when loading shape files, for instance).
- [x] Create a model with different options for displays/aspects/, oriented towards drawing something specific ("drawing a title", "using transparency", "focusing on agents" …)
- [x] Create a model showing the different dynamics of the experiment and its simulation(s), in regular and batch experiments (i.e. when are the behaviors of the experiment executed, how does it access its simulations, etc.)
- [x] Create a model on mirror species
- [x] Create a model on benchmarking

It is always a pain to build such models, but I think they are necessary.

**Comment by dphilippon** [comment]
I think i can do it during the camp ... But most of the models in Features have already these ones. So basically, I understand the need of "typical" syntax models. However, as we can see in the Syntaxe one, they could be interesting if they had a "context", and not simply be syntax models...

**Comment by AlexisDrogoul** [comment]
We might also add:

- [ ] Create a model showing the different dynamics of the experiment and its simulation(s), in regular and batch experiments (i.e. when are the behaviors of the experiment executed, how does it access its simulations, etc.)

**Comment by agrignard** [comment]
- [ ] Create a model showing the different usage of the parameters controller (slider, checkbox, etc)

**Comment by benoitgaudou** [comment]
@chapuisk : We would need models illustrating `benchmark` statement and facets.

**Comment by benoitgaudou** [comment]
Given all the previous commit, it seems that we address all the requierements!
Feel free to reopen for new needs.
