### ISSUE TITLE
change all the "see also" deprecated

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1586]

**Comment by AlexisDrogoul** [comment]
You mean the "see also" that point to deprecated items ? I guess it is doable automatically when compiling the documentation, no ?

**Comment by mazarsju** [comment]
Yes, that was what I meant. And yes, to do it automatically would be the best !

**Comment by AlexisDrogoul** [comment]
I've completed the cleansing. Nothing automated, but it was not too long. Next time we deprecate operators, a simple CTRL+H on the name and a removal from the `see=` annotations will be perfect !
