### ISSUE TITLE
Information bar displays n times the number of cycle (instead of one ?)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1592]
cf image

![image1](https://cloud.githubusercontent.com/assets/12977635/13386158/ea14256c-dedb-11e5-9bdb-eb09afac420f.png)

**Comment by AlexisDrogoul** [comment]
I agree that it's a little bit weird in batch mode (although some simulations may end up earlier than the others depending on the condition). Maybe we should remove this information completely as it does not really make sense in this mode.
