### ISSUE TITLE
Problem with Multigraph in the model Library

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1593]
Hi everyone, i've seen that some changes have been made, some syntaxes are now deprecated and so on. So i tried to make the syntaxe a little bit more 1.7 in the model library, more precisely in the Graph Library. Actually, the Multigraph model doesn't work anymore, normally, according to the movement of the agents, the graph should change (as the agents are actually vertices of the graph).

**Comment by AlexisDrogoul** [comment]
Actually, it has been a long the "GamaLink" class does not work at all. I am working on a replacement at a lower level (adding a new kind of Geometry to JTS geometries), but we might as well suppress these dynamic geometries as it is quite easy to do it in GAML.

**Comment by AlexisDrogoul** [comment]
I am happy to announce that dynamic links work again (and much more efficiently than before). The trick was to create a special kind of JTS geometry (DynamicLineString), which builds and maintains its points dynamically.

This could be extended towards building dynamic polygons as well, if necessary… And this could be the basis of the geometry for paths. Please open new requests for enhancement if you feel it could be generalized.
