### ISSUE TITLE
using topology {... } to compute neighborhood

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1598]
In a model, I tried to compute the neighbor cells of a cell using and withtout using the using topology statement, in a cell agent. I get unexpected results.

In the model below everything is fine when I use the statement:
lc <- self neighbors_at 2;  
to compute the neighbors of the current cell.

But when I use the using topology statement:
using topology(self){
	lc <- self neighbors_at 2;
}
the results are unexpected and different:
- when neighbors: 4 in the cell, I get:
8 -> [cell[44],cell[54],cell[64],cell[45],cell[65],cell[46],cell[56],cell[66]]
- when neighbors: 8 in the cell, I get:
8 -> [cell[44],cell[54],cell[64],cell[45],cell[65],cell[46],cell[56],cell[66]]
- when neighbors: 6 in the cell, I get:
2 -> [cell[54],cell[64]]

I do not know whether it is an issue, or a misuse ...

global {
	init {
		ask (cell[5,5]) {
			color <- #yellow;
			rgb c <- rnd_color(255);
			list<cell> lc;
			// lc <- self neighbors_at 2;
			using topology(self){
				lc <- self neighbors_at 2;
			}
			write "" + length(lc) + " -> " + lc;
			ask lc {
				color <- c;
			}				
		}
	}
}

grid cell height: 10 width: 10 neighbors: 4 {
	rgb color <- #grey;
}

**Comment by ptaillandier** [comment]
If you replace "using topology(self)" by "using topology(species(self))" it is working.... I have no idea if it is the normal behavior or not :p .

**Comment by AlexisDrogoul** [comment]
OK. Got it. If you look at the documentation (and also at the code !), `topology(self)` returns a `ContinuousTopology` bounded by the geometry of the agent. `topology(species(self))` (or `topology(cell)`) will return the topology associated with the `cell` grid species. 

Looking at the topology used, it is normal that it returns the 8 neighbors of the cell, which share either a line or a point (for the diagonal cells) with the bounds of the topology.

So the behavior is normal. Shall we close the issue, then ?

**Comment by benoitgaudou** [comment]
ah OK, I will close it.
Thanks

Benoit

2016-03-01 18:01 GMT+01:00 Alexis Drogoul <notifications@github.com>:
