### ISSUE TITLE
First click on an experiment button does not run simulation

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1602]
After running GAMA, I open a model, e.g. ants with lot of charts.
When I click on the "Ant" button for the first time, the simulation is not run.
In the Eclipse console, I get following messages.
(after a second click, the simulation is run).

****************************************************
Thread [Worker-8] | Resource set [1 resources]
'Ant%20Foraging%20(Charts%20examples).gaml' validated in 48.921211 ms [ ~14245 kb used ]
****************************************************
Thread [main]
Resource Ant%20Foraging%20(Charts%20examples).gaml building
****************************************************
Description of agent
	abstract model
		description of /Ant Foraging (Charts examples).gaml
	Description of experiment
		Description of Ant
		Description of AntOneDisp
	Description of base_edge
	Description of graph_edge
	Description of graph_node
	Description of physical_world
	Description of AgentDB
	Description of ant
	Description of ant_grid

Running the perspective listener to automatically launch modeling
Running the perspective listener to automatically launch modeling
Removed perspective contribution to toolbar:msi.gama.lang.gaml.Gaml
GAMA Caught a workbench message : Unhandled event loop exception
Generation of expression compilers so far: 4
Description of agent
	abstract model
		description of /Ant Foraging (Charts examples).gaml
	Description of experiment
		Description of Ant
		Description of AntOneDisp
	Description of base_edge
	Description of graph_edge
	Description of graph_node
	Description of physical_world
	Description of AgentDB
	Description of ant
	Description of ant_grid

****************************************************
Thread [Worker-6] | Resource set [1 resources]
'Ant%20Foraging%20(Charts%20examples).gaml' validated in 19.642781 ms [ ~1889 kb used ]
****************************************************

**Comment by AlexisDrogoul** [comment]
This has been fixed in the forthcoming commit: I implemented a workaround to catch the NPE and then try again to set the perspective (see also https://bugs.eclipse.org/bugs/show_bug.cgi?id=459847). It seems to be the only solution for this bug in the compatibility layer...
