### ISSUE TITLE
Error in shapefile displaying (related to projection)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1603]
In a shapefile with a projection described below, I have the error below when displaying agents whereas with a Lambert-93 projection it seems to work fine.
```
Error loading metadata 10543_!_1236_!_PROJCS["NTF_France_II_degrees", 

  GEOGCS["GCS_NTF", 

    DATUM["D_NTF", 

      SPHEROID["Clarke_1880_IGN", 6378249.2, 293.46602]], 

    PRIMEM["Greenwich", 0.0], 

    UNIT["degree", 0.017453292519943295], 

    AXIS["Longitude", EAST], 

    AXIS["Latitude", NORTH]], 

  PROJECTION["Lambert_Conformal_Conic_2SP"], 

  PARAMETER["central_meridian", 2.3372291666666665], 

  PARAMETER["latitude_of_origin", 46.8], 

  PARAMETER["scale_factor", 0.99987742], 

  PARAMETER["false_easting", 600000.0], 

  PARAMETER["false_northing", 2200000.0], 

  UNIT["m", 1.0], 

  AXIS["x", EAST], 

  AXIS["y", NORTH]]_!_9303.749563667923_!_10755.014892837033_!_the_geom@%@FID_Parcel@%@Id@%@FID_OS2012@%@OSLAND12@%@ID_AUTO@%@NOMOSLAND1@%@Cover@%@Area_!_geometry@%@int@%@int@%@int@%@float@%@float@%@string@%@string@%@float : InvocationTargetException:null
```

**Comment by AlexisDrogoul** [comment]
I have managed (changed a bit the display of exceptions) to receive this from GAMA/GeoTools when trying to read the file:

```
Caused by: java.lang.IllegalArgumentException: Les latitudes 0°00.0'N et 0°00.0'N sont aux antipodes.
	at org.geotools.referencing.operation.projection.LambertConformal.<init>(LambertConformal.java:160)
	at org.geotools.referencing.operation.projection.LambertConformal.<init>(LambertConformal.java:123)
	at org.geotools.referencing.operation.projection.LambertConformal2SP.<init>(LambertConformal2SP.java:63)
	at org.geotools.referencing.operation.projection.LambertConformal2SP$Provider.createMathTransform(LambertConformal2SP.java:178)
…
```

Doesnt know what it means and why it's in French, but the real issue here is that GAMA keeps on looping on this metadata, trying again and again to acquire it in an endless loop which freezes the navigator (and the workspace).

Will issue a patch later !

**Comment by AlexisDrogoul** [comment]
I can confirm that this .prj information causes GAMA to fail. When opening the file in QGIS, it doesn't recognize the projection, either, and instead generates a "user generated" CRS. Saving it again produces another .prj file, with the following format:

```
PROJCS["Lambert_Conformal_Conic",GEOGCS["GCS_unnamed ellipse",DATUM["D_unknown",SPHEROID["Unknown",6378249.2,293.46602]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["latitude_of_origin",46.8],PARAMETER["central_meridian",2.337229166666667],PARAMETER["scale_factor",0.99987742],PARAMETER["false_easting",600000],PARAMETER["false_northing",2200000],UNIT["Meter",1],PARAMETER["standard_parallel_1",46.8]]
```

But using this (normally "corrected") projection does not work either, and fails with the same exception. I dont exactly know what happens (I am no "projection guru") and can't confirm whether this projection is correct or not. However, I will probably handle this case by refusing to load the CRS (at least as metadata — as GeoTools seems to correctly handle it while loading the shapefile) and explicitly stating it (describing it as an "unknown" or "unparsable" projection). 

Any comment on this ?

**Comment by ptaillandier** [comment]
Hi,

Just for information, the problem with QGIS seems to come from the way
Lambert Conformal Conic Projection is written. Indeed, for the same CRS,
you can found two ways to write it (see here
<http://spatialreference.org/ref/esri/ntf-france-ii-degrees/> : ERSI WKT
and OGS <http://www.opengeospatial.org> WKT). I think ERSI's one is an old
version. The only difference is the way the Lambert Conformal Conic
Projection is written (Lambert_Conformal_Conic_1SP for OGC and
Lambert_Conformal_Conic
for ERSI)
QGIS seems to prefer OGC version of the prj file.
For GAMA, with OGC version, Geotools does not seem to read the prj file (No
CRS)....

Patrick

2016-03-06 7:59 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Yep. Very strange. I'm wondering if the internal database of GeoTools (the ones it uses for reading projections) should not be updated. In any case, I have managed to at least deal with this kind of "unparsable" WKT by testing it before it is saved, so that it does not hang GAMA when being reloaded. I will then close this issue when it is committed . 
If you have the time, can you check the version of the database/file we use and see if a newer version is available ? Thanks.
