### ISSUE TITLE
Simplify the UI with only one "Synchronize" button

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1606]
Hi,

Right now, it is possible to synchronize every individual display with the simulation. However, in the case of several displays) I'm wondering if there would be a use case where the user would want to synchronize only one display and not the others. Maybe if we have a chart and a graphical display ? But even in that case, I'm not convinced it is useful. Furthermore, it is a bit cumbersome to use, as the user has to go through all displays to turn on/off the synchronize button.

I would then be in favor of having one — and only one — synchronize button in the main toolbar / menu, which would synchronize or desynchronize **all** the displays at once. 

What's your opinion on this ? 

Cheers

Alexis

**Comment by sriramab** [comment]
Yes, it should be like the check boxes , select all or deselect all. Then user only (un)selects what is needed.

**Comment by AlexisDrogoul** [comment]
Close this one as well since the `synchronised:` facet can be used to define displays, now. So models needing to have a "Synchronise All" command can declare an explicit boolean parameter and use this to set the value of this field.
