### ISSUE TITLE
batch experiment gives no output on git version

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1607]
Hi

I am using batch experiment in the git version of gama.

I have two problems:
1. When I use the save to csv, there is no csv in the output folder.
2. To temporarily avoid the problem in 1, i used the write statement to print the value of a variable, but nothing was printed in the console.

You can may be try any model and add this code along with a variable from your own model.?

Please see my code in batch experiment, am I doing something wrong? I consulted all the threads on user form, but cant find a solution. Please guide.

experiment AMStrategies type: batch repeat:5 keep_seed:true until:cycle>26

{

```
action _step_{
    ask asset_manager{
        write "budget value from batch experiment"+adjhmb;
        //save adjhmb to:"batch_output.csv" type:csv;
    }

}
```

}

**Comment by AlexisDrogoul** [comment]
Well, I've tested it (i.e. saving and writing something every step of the experiment) and it works. I'm however intrigued by the "ask asset_manager" present here. What is "asset_manager" ? A species of your model ?

**Comment by sriramab** [comment]
Yes, it is a species. I am trying to access a variable of that species at end of every experiment while exploring a parameter space on another variable.

**Comment by ptaillandier** [comment]
Do you still have a problem with batch experiments? If yes, can you share the complete model to test it?

**Comment by AlexisDrogoul** [comment]
Doing some cleansing on the issues... Is the problem remaining ?

**Comment by sriramab** [comment]
I change the model a lot, please give me a day to check.

**Comment by sriramab** [comment]
Yes, I still have this problem.  This block does not give any output. I wonder if the ask statement does not allow this? asset_manager is a species and adjhmb is its variable.

{
action _step_{
    ask asset_manager{
        write "budget value from batch experiment"+adjhmb;
        //save adjhmb to:"batch_output.csv" type:csv;
    }

}
}

**Comment by AlexisDrogoul** [comment]
Have you tried transforming the action into a reflex ? As a matter of fact, overwriting `_step_` is probably not necessary in your case.

**Comment by AlexisDrogoul** [comment]
Is this issue still present ? If not, feel free to close it.

**Comment by AlexisDrogoul** [comment]
Any update on this one ? If no, I quietly close it. Reopen if still present.
