### ISSUE TITLE
The error msg for a wrong value of rgb color does not show in the editor window.

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1608]
Hello,

GAMA 1.7 does not show an error message with a wrong value of rgb color. However the msg are showed in simulation times.
The version 1.6.1 works well with this error.

Thank you!

![wrong value of color](https://cloud.githubusercontent.com/assets/11825516/13492341/0750ab38-e16a-11e5-9407-fa2b10981701.png)

**Comment by AlexisDrogoul** [comment]
Strange, because I had the correct report of the error. Anyway, I have pushed a commit that should locate the error a bit more precisely in the code. Can you try again ?

**Comment by tcquang** [comment]
Thank you very much for your commit!
I got a new git version, but it still is not located in the GAML code.
Please find the model in the attachement!
Thank you

[image: Hình ảnh nội tuyến 1]

2016-03-03 19:13 GMT+07:00 Alexis Drogoul <notifications@github.com>:

> Strange, because I had the correct report of the error. Anyway, I have
> pushed a commit that should locate the error a bit more precisely in the
> code. Can you try again ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gama-platform/gama/issues/1608#issuecomment-191728472>
> .
>



-- 
Quang Chi TRUONG
Tel: 0939388153

**Comment by AlexisDrogoul** [comment]
I dont see any attachment.

**Comment by AlexisDrogoul** [comment]
It works for me. I suggest you either change your workspace or fully rebuild GAMA before launching it.
<img width="534" alt="capture 2016-03-04 a 08 49 45" src="https://cloud.githubusercontent.com/assets/579256/13515765/ce90df34-e1e6-11e5-873f-ef3db5000681.PNG">

**Comment by AlexisDrogoul** [comment]
Seems to be resolved from what I heard today.
