### ISSUE TITLE
max number of character in console not saved

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1613]
Hi,

When you change the "max number of characters to display in console" in preferences>UI, it cannot be changed back.

I think the default value was 20000 , I changed to 200. It works.  I change it back to 20000. It works. 
But when I restart GAMA, it is 200 and not 20000.

May be someone can quickly check this? I am unable to check further but I remember default was 20000 and I am unable to get back to 20000. It is now saved at 200.

thanks,
Srirama

**Comment by AlexisDrogoul** [comment]
I tried this exact sequence of settings, and I can come back without problems to whatever initial value was present (and change it again, etc.). Does it take place on MacOS X ? In that case, the preferences of gama are saved in a file called: com.apple.java.util.prefs.plist in /Users/your_account/Library/Preferences

You might want to check if the value is changed there or not.

**Comment by sriramab** [comment]
Yes, it is changed in plist. Please see picture. What must I do?

![console](https://cloud.githubusercontent.com/assets/12668606/13580356/237d9cc2-e4a2-11e5-9324-006e5e1fca33.jpg)

**Comment by AlexisDrogoul** [comment]
Is it still happening ? There is absolutely no reason you should have that kind of behavior…

**Comment by sriramab** [comment]
It is resolved, at least on mac. I cannot check for windows.
thank you.
