### ISSUE TITLE
Syntax error when access species of a simulation in Co-model

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1615]
When using the comodel, importing a micro-model alias A, in Gama 1.(before 7), i can write a sentence like:
write ((first(A.experiment_name)).simulation).species_in_model_A;

This will inform in console the list of species_in_model_A 
But with the enhancement of multi-simulation (i think), the accessing above is inhibited. It make an syntax error;
Multiple markers at this line
- No operator found for applying '.' to types [unknown, species]
   (operators available for [types [matrix, matrix], types [agent,
   unknown]])
- Field species_in_model_A unknown for type unknown

**Comment by ptaillandier** [comment]
As a side note, the model provided with GAMA to show how to use the co-modeling does not seem to work  (and lack of commentaries: even me, i do not understand at all what it is suppose to do).

**Comment by hqnghi88** [comment]
Dear Patrick, I try to post other example and try to make sense the existing with more comments.
The issue is fixed (with some recent commit).
