### ISSUE TITLE
GAMA 1.7.1b crashes after installing stat extension

### ISSUE THREAD

**Issue by allanlao** [gama-platform/gama#1616]
OS: OSX El Capitan

Last login: Wed Mar  9 12:58:29 on ttys000
MacBook-Pro:~ allanlao$ cd gama_workspace
MacBook-Pro:gama_workspace allanlao$ ls
BuildingInvasion	SimCity			schilling
CAModel			Unclassified Models	seg
MySegregation		UnpVigan		segragation_model
MyStupidModel		VietnamGIS		shared_ped
PedestrianSimFinal	infection		simple_ped
PedestrianSimV2		mainr02.gaml		test_gama
PedestrianSimV2.zip	myboid			test_segragation
PedestrianSimulation	pedestrian_evacuation	tester
Project4		rw
MacBook-Pro:gama_workspace allanlao$ cd .metadata/
MacBook-Pro:.metadata allanlao$ vi .log 

!ENTRY org.eclipse.update.configurator 4 0 2016-03-09 13:00:14.243
!MESSAGE Could not install bundle plugins/javax.inject_1.0.0.v20091030.jar   A bundle is already installed with the name "javax.inject" and version "1.0.0.v20091030"

!ENTRY org.eclipse.update.configurator 4 0 2016-03-09 13:00:14.246
!MESSAGE Could not install bundle plugins/javax.xml_1.3.4.v201005080400.jar   A bundle is already installed with the name "javax.xml" and version "1.3.4.v201005080400"

!ENTRY org.eclipse.update.configurator 4 0 2016-03-09 13:00:14.247
!MESSAGE Could not install bundle plugins/msi.gama.application_1.7.0.201602050012.jar   A bundle is already installed with the name "msi.gama.application" and version "1.7.0.201602050012"

!ENTRY org.eclipse.update.configurator 4 0 2016-03-09 13:00:14.250
!MESSAGE Could not install bundle plugins/msi.gama.core_1.6.1.201602050012.jar   A bundle is already installed with the name "msi.gama.core" and version "1.6.1.201602050012"

!ENTRY org.eclipse.update.configurator 4 0 2016-03-09 13:00:14.255
!MESSAGE Could not install bundle plugins/msi.gama.ext_1.0.0/   A bundle is alre
ady installed with the name "msi.gama.ext" and version "1.0.0"

**Comment by AlexisDrogoul** [comment]
The plugins that are available for GAMA 1.6.1 have not been updated for GAMA 1.7. It will come and we are committed to do it  !
