### ISSUE TITLE
Remove the FreeFly Camera

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1618]
In the trend of simplifying further the interface (see #1574), I would be in favor of dropping the FreeFly camera, as I'm not sure anyone uses this option.

**Comment by mazarsju** [comment]
For the moment, the FreeFly camera is the only possibility to view the model from the side, without having serious problems. So as soon as the arcball camera is not more usable (#1297), I don't think removing the FreeFly camera is a good idea...
I'll try to see what is going on with the ArcBall, because for the moment, I don't know you, but I'm completely not able to use this command properly.

**Comment by AlexisDrogoul** [comment]
But you can perfectly rotate a model to see it from its side. I don't see
the interest of the freefly camera other than a kind of 'first-person'
movement more adapted to games than to models.

**Comment by sriramab** [comment]
I would suggest to keep it or make it a plugin. Soon transport professional (those on abm) will move to studying connected cars/vehicles or driverless cars. First-person can be useful for model demonstration. May be someone can present at a confernce on connected cars Srirama

**Comment by agrignard** [comment]
Maybe we can remove it from the icon menu (for those who really don't like
these cameras) but let the advanced user use it maybe with a facet?

As mention in #1297 the ideal solution could be to mix the 2 camera in one
to have the "google earth like" camera but it implies many changes...

I agree with Srirama, if the freefly was working a bit better (I think one
of the main problem is that it moves too fast with small model (maybe only
one parameter too change manually or according to the size of the model))
it can be a great tool for demo.

**Comment by agrignard** [comment]
Regarding the different OpenGL option I think we can remove all of them (rotate scene is now possible with arrow, split layers is not used (and can be done programmatically) and triangualte scene is only useful to debug the rendering but the user don't wan to see it.

What I propose is too remove all of them but too keep the possibility to have the freefly with a facet?

**Comment by sriramab** [comment]
I use rotate scene and split layers a lot, especially to students to make it easier for them to visualize the concept. If we do away with the buttons, can I still rotate the scene at a certain speed? Split layers is also very useful. Do you think it could be implemented as a boolean switch in parameters window?

**Comment by AlexisDrogoul** [comment]
Again, this issue (of having 2 cameras), can be resolved probably by adding a facet to the `camera` layer with a more explicit name (`first_person`) so that it belongs to the predefined cameras.
