### ISSUE TITLE
Adding a warning when using a parameter statement referencing an experiment variable in a batch experiment

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#162]
**Describe the bug**
When defining a parameter in **a batch** experiment, it doesn't change the value of the variable linked with the facet `var` if that variable is defined in the experiment, but works normally with global variables.

**To Reproduce**
1. run this code:
```
experiment a type:batch until:cycle=1{
	int b;
	parameter var:b min:0 max:10;
	
	reflex e{
		write b;
	}
}
```
2. observe that b is always 0
3. you can move the declaration of b to the global and see that its value is varying from 0 to 10 as expected

**Comment by AlexisDrogoul** [comment]
To be honest, this is expected: batch experiments are supposed to automate the exploration of simulation parameters, not their own parameters. A possibility could be to put a warning to explain this ?

**Comment by lesquoyb** [comment]
Yes I think a warning could be nice indeed

**Comment by AlexisDrogoul** [comment]
I have added an info popup in https://github.com/gama-platform/gama/commit/910e680a322f368c4d8d2ab3bfbd206d32541073. Please test !
