### ISSUE TITLE
Ubuntu 14: menu items "Add monitor" and "Toggle console" are grayed out, "Agents" not working

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1624]
This does not happen under Windows or MacOS X.

**Comment by AlexisDrogoul** [comment]
The Ubuntu version of GAMA needs to be our focus for testing as it is in a very unstable state right now. 

@gama-platform/committers, can you try to test it on Ubuntu and open issues when necessary ? Any hint on how to fix this "dynamic menus in the main toolbar" problem would also be welcome...

**Comment by hqnghi88** [comment]
Dear Alexis,
On ubuntu 16.04 LTS, the Agents menu on system menu bar is working like on my Win OS.  Did we have special behaviors to reproduce this issue?

**Comment by AlexisDrogoul** [comment]
Seems like Ubuntu 16.04 definitely solves the problem. I would then advise Ubuntu users to upgrade as we dont have the capacity to maintain "old" OSes.
