### ISSUE TITLE
'equation' / 'solve' does not work in multi-simulation setups

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1631]
Probably because the statement is keeping / managing lists of agents instead of using the scope to store and retrieve them. Statement should be more or less stateless, at least w.r.t. the state of the simulation...

**Comment by AlexisDrogoul** [comment]
After further investigations, it appears that the systems of equations are building their lists of agents/external agents every step, storing them, and that the call to 'solve' simply uses this information. That creates an unnecessary need to store/retrieve this information. Couldn't the creation of the agents list be triggered by the call to solve (and the subsequent call to the different systems of equations) ? 
Furthermore, if some equations are simply declared but not solved, they will nevertheless build their lists of agents, which is not really interesting.

**Comment by AlexisDrogoul** [comment]
I have normally corrected this behavior — need to do some more tests, though. 

It would be interesting to add this constraint to the documentation, by the way, and to review the existing code. Could be also the occasion to add to the scope a way to store and retrieve "working values" easily (or to enable an easier way to do it, as it can already be done by setting/getting attributes to the simulation agent directly, i.e. `scope.getSimulationScope().setAttribute("…", …)` and `scope.getSimulationScope().getAttribute("…")`).

**Comment by hqnghi88** [comment]
Dear Alexis,
Would this issue be fixed in your forthcoming commit? I would like to review it soon.
Cheers.

**Comment by AlexisDrogoul** [comment]
I have pushed a commit that should solve this problem. In addition to some refactoring and simplification of the code, state-dependent variables are now pushed and retrieved from the current agent attributes (like in the skills), and I have added a critical section for the methods that cannot be called with a scope (i.e. the ones implementing the interface required by the integrator), so that they within the same "currentScope". Can you test it ?

**Comment by AlexisDrogoul** [comment]
If you have had the time to test this issue -- and if it is working -- please close it ! Thanks.
