### ISSUE TITLE
Warning suppression in GAML

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1632]
It should be fine (if it is not too complicated) to add a possibility to ignore a warning in the model. Indeed, the Syntax1.6 model for instance has some warnings ("wanted" warnings), and the yellow indicator is thus propagated to all the model library. I think that it is not very nice for a new user to launch gama and see this yellow color everywhere.

**Comment by AlexisDrogoul** [comment]
It is now possible to add "pragmas" to a GAML model.

They have to be put before the model definition, with the following syntax: `@name_of_pragma`. 
Two are recognized so far: `@no_warning` and `@no_info`, which respectively remove the warnings and info markers from the model (in both the editor and the explorer).

Example: 

```
@no_warning
model m

global {
     float f <- 1; // no warning should appear on this line. Comment the pragma and it should appear.
}

experiment "e" type: gui {}

I will commit soon.

**Comment by AlexisDrogoul** [comment]
I close the issue -- this pragmas answer the request.
