### ISSUE TITLE
Problem installing the Graphical Editor

### ISSUE THREAD

**Issue by alexiscourbet** [gama-platform/gama#1633]
Hi everyone,

First of all, thank you so much for developing GAMA and for keeping up the good work!

I am trying to install the graphical editor directly through Gama 1.6.1 Update Site - https://gama-platform.googlecode.com/svn/update_site/

But unfortunately I get the following error, which gets me a bit confused. Could you guys help me out whit this? What should I do?

Cannot complete the install because one or more required items could not be found.
  Software being installed: Graphical_modeling 0.9.0.201408111847 (idees.gama.feature.graphical_modeling.feature.group 0.9.0.201408111847)
  Missing requirement: Graphical Editing Framework Draw2d 3.7.2.v20111017-2020 (org.eclipse.draw2d 3.7.2.v20111017-2020) requires 'package com.ibm.icu.text [3.8.1,5.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Graphical_modeling 0.9.0.201408111847 (idees.gama.feature.graphical_modeling.feature.group 0.9.0.201408111847)
    To: org.eclipse.draw2d [3.7.2.v20111017-2020]

Thanks so much!

Cheers,

Alexis

**Comment by tcquang** [comment]
Dear Alexis,
I am also using the Graphical Modeling plugin, It's a good tool for
starting a model.
It work well with version of GAMA  1.6.1 latest version, but it is still
not working with  GAMA 1.7b1.
Cheers,

Quang

2016-03-18 8:49 GMT+07:00 Alexis Courbet <notifications@github.com>:

> Hi everyone,
>
> First of all, thank you so much for developing GAMA and for keeping up the
> good work!
>
> I am trying to install the graphical editor directly through Gama 1.6.1
> Update Site - https://gama-platform.googlecode.com/svn/update_site/
>
> But unfortunately I get the following error, which gets me a bit confused.
> Could you guys help me out whit this? What should I do?
>
> Cannot complete the install because one or more required items could not
> be found.
> Software being installed: Graphical_modeling 0.9.0.201408111847
> (idees.gama.feature.graphical_modeling.feature.group 0.9.0.201408111847)
> Missing requirement: Graphical Editing Framework Draw2d
> 3.7.2.v20111017-2020 (org.eclipse.draw2d 3.7.2.v20111017-2020) requires
> 'package com.ibm.icu.text [3.8.1,5.0.0)' but it could not be found
> Cannot satisfy dependency:
> From: Graphical_modeling 0.9.0.201408111847
> (idees.gama.feature.graphical_modeling.feature.group 0.9.0.201408111847)
> To: org.eclipse.draw2d [3.7.2.v20111017-2020]
>
> Thanks so much!
>
> Cheers,
>
> Alexis
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gama-platform/gama/issues/1633>
>



-- 
Quang Chi TRUONG
Tel: 0939388153

**Comment by alexiscourbet** [comment]
Thanks a lot Quang!

Cheers,

Alexis

**Comment by AlexisDrogoul** [comment]
Closing this issue -- the Graphical Editor in its current incarnation can only work with Gama 1.6.1
