### ISSUE TITLE
fillBuffer; geometry could not be added

### ISSUE THREAD

**Issue by inescarthage** [gama-platform/gama#1635]
Hello, 

Please what I have to do when I receive this error message "fillBuffer; geometry could not be added" which appears every time I want to integrate my GIS.

Thank you very much

**Comment by AlexisDrogoul** [comment]
Please provide more details on what you are trying to do:

- an example model would be nice
- a sample of your datafile (GIS file, etc.) too

Otherwise, we cannot say much more than what the error says: a geometry has not been added to the buffer of a GIS file...

**Comment by AlexisDrogoul** [comment]
As a follow-up, this message means that the geometry you'd like to add is either null or empty. I have added a more meaningful error message, which should be followed by the identifier of the object in the GIS file. Can you check it ? Thanks

**Comment by AlexisDrogoul** [comment]
In the absence of a repeatable use-case (or at least an example), I close this issue. Feel free to reopen if you can provide more information.
