### ISSUE TITLE
The "Revert parameter to their original values" buttons does not work after a "Reload"

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1637]
When you change the values of some parameters, and you click "Reload", the "original values" becomes the one just before the reload. Maybe it is the wanted behavior, but I think it is a bit strange, what do you think ?

**Comment by AlexisDrogoul** [comment]
This is the desired behavior. "Original" here means the ones that have been used for initializing the last simulation, not the ones defined in the model.
