### ISSUE TITLE
Problem with the graphical_editor

### ISSUE THREAD

**Issue by clairebqt** [gama-platform/gama#1638]
Hi,
I am trying to install the graphical editor with Gama 1.6.1 but I get the following error : 

Could not find https://gama-platform.googlecode.com/svn/update_site/
org.eclipse.equinox.p2.core.ProvisionException
Unable to read repository at https://gama-platform.googlecode.com/svn/update_site/content.xml.
Unable to read repository at https://gama-platform.googlecode.com/svn/update_site/content.xml.
Network is unreachable: connect

Is anybody can help me with this error?
Thanks

**Comment by AlexisDrogoul** [comment]
I would say that it is most likely a connection problem on your side: the site is (still) accessible otherwise. 

Please check your connections and/or a DNS problem.
