### ISSUE TITLE
After changing the type of camera (ArcBall / FreeFlight), the mouseevents and keyevents are triggered for both cameras

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1646]
The switch between the two cameras seems not very clean, since methods like "keyPressed" are called twice... This bug was not visible before, but now that we draw a sphere for rotation, it is very weird (the sphere appears in the freeflight mode, which should not be possible).
The laziest solution of this problem is to remove this freeflight camera (#1618)...

**Comment by AlexisDrogoul** [comment]
It's probably just a matter of removing the key/mouse listener at the right place (havent checked). But having only one camera would certainly be easier to maintain ;)

**Comment by AlexisDrogoul** [comment]
I may have fixed this bug (which I couldn't exactly reproduce, by the way) in the latest commit. Thanks to test it.

**Comment by mazarsju** [comment]
Yes, works fine now ! I close this issue
