### ISSUE TITLE
Switching from ArcBall to FreeFly camera sometimes leads to empty screen

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1651]
After having moved in 3D using the "regular" camera, a switch to FreeFly camera usually reveals an empty screen. It may be normal given the rotations done with the first camera, but it is nevertheless disturbing. Tweaking the parameters of the camera such that, immediately after a switch, something is seen onscreen might be a good idea.

**Comment by mazarsju** [comment]
Reset the camera position is also an other idea. Switching the camera and having the same view is a bit trickier, but I can do that if you think it is necessary.

**Comment by agrignard** [comment]
The more I think about it the more I think that we should have only one cam and give the possibility to switch the cam (e.g using  shift or cmd) exactly like in google earth. 

Note so easy to implement as the two existing cam has been developed in 2 different ways...

**Comment by AlexisDrogoul** [comment]
And the more I think about it, the more I wonder if we need the second camera :)

**Comment by mazarsju** [comment]
I think I can close this issue then.

**Comment by agrignard** [comment]
In the current version I agree it's still a bit hard to manipulate but for me this camera can be useful for the following reasons

- You can have some point of view that are not possible to have with the arcball (well maybe not now that we have the 3 rotations working with the arrow...)
- For a demo it can be a nice feature to "go for a ride" inside a model
- It will be useful when Gama will be compatible with the oculus rift ;-)

It can be one task for the next coding camp!
