### ISSUE TITLE
Cannot import model Ant Foraging (Complex).gaml, caused by inaccessible syntax xxxx_model

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1653]
I cant import the "Ant Foraging (Complex).gaml" in Toy Models with following code:

model Ants_importing
import "../../Toy Models/Ants (Foraging and Sorting)/models/Ant Foraging (Complex).gaml" 
experiment Ants_coupling_exp type:gui  parent:Ant{
	}

The eclipse console show the Exception:

!ENTRY org.eclipse.ui 4 4 2016-04-04 10:38:08.476
!MESSAGE GamlJavaValidator.validate
GAMA Caught a workbench message : GamlJavaValidator.validate null
One compilation error accepted: Syntax errors detected  thread: Worker-1
COMPILATION ERROR in data internal_data2117: The variable ants_model is not defined or accessible in this context. Check its name or declare it; source: Ant%20Foraging%20(Complex).gaml
COMPILATION ERROR in data internal_data2117: The variable ants_model is not defined or accessible in this context. Check its name or declare it; source: Ant%20Foraging%20(Complex).gaml
COMPILATION ERROR in data internal_data2118: The variable ants_model is not defined or accessible in this context. Check its name or declare it; source: Ant%20Foraging%20(Complex).gaml
COMPILATION ERROR in data internal_data2118: The variable ants_model is not defined or accessible in this context. Check its name or declare it; source: Ant%20Foraging%20(Complex).gaml
COMPILATION ERROR in data internal_data2119: The variable ants_model is not defined or accessible in this context. Check its name or declare it; source: Ant%20Foraging%20(Complex).gaml
COMPILATION ERROR in data internal_data2119: The variable ants_model is not defined or accessible in this context. Check its name or declare it; source: Ant%20Foraging%20(Complex).gaml
COMPILATION ERROR in data internal_data2120: The variable ants_model is not defined or accessible in this context. Check its name or declare it; source: Ant%20Foraging%20(Complex).gaml
COMPILATION ERROR in data internal_data2120: The variable ants_model is not defined or accessible in this context. Check its name or declare it; source: Ant%20Foraging%20(Complex).gaml

**Comment by AlexisDrogoul** [comment]
Probably because ants_model is used in the "4 simulations" experiment. Interesting to see that it throws an error: as a matter of fact, the name "ants_model" is erased when importing the model, because the name of the model species is now "Ants_importing_model"... Hadn't thought about this problem -- and I dont know how to solve it.

**Comment by AlexisDrogoul** [comment]
Yep, the intuition was correct. If one replaces `ants_model` by `species(simulation)` in `Ant Foraging (Complex).gaml`, it works...

**Comment by AlexisDrogoul** [comment]
The only fix I can think of is to catch the use of the "model species name" and make it a special expression that returns the `species of the current model` . I'll try to fix it soon.
