### ISSUE TITLE
No display of GamaShape coming from a Postgres/PostGIS datbase 

### ISSUE THREAD

**Issue by CelineLeCoq** [gama-platform/gama#1654]
Hi, 
I’m currently trying the new version of GAMA 1.7 b2 with the Git version.

I now have new issues I don’t know how to resolve:
 
![errorgamashape](https://cloud.githubusercontent.com/assets/18263825/14249887/324d4dac-fa7c-11e5-9e35-2124807698a0.PNG)

Here is the code I’m using to create my species from a PostGres/PostGIS database:

![image](https://cloud.githubusercontent.com/assets/18263825/14250203/ad6c00c2-fa7d-11e5-9492-a8769720f3a4.png)

[...]

![image](https://cloud.githubusercontent.com/assets/18263825/14250234/cbf2d494-fa7d-11e5-9fd5-7547566eeca0.png)

Is there a new way to define spatial data coming from database in 1.7 version? 

Thanks all, 
Céline

**Comment by AlexisDrogoul** [comment]
It seems to indicate that what you obtain from the field 'geom' is not a geometry but a list of geometries. However, I have no clue whether it is the intended behavior or not -- and how to fix it. @txviet , @truongminhthai , do you have an idea of what is happening ?

**Comment by hqnghi88** [comment]
Hi,
I dont have any idea about "integrated database" technical terms, but could you check your first sql query, plot_layon, from this point:
from "+table_ref+" "+ site_pilote+";";
Did you miss something between  table_ref and site_pilote ? I mean a comma or an "as". 
Please confirm your whole sql query is exact by writing it in the console and test it in postgres: 
write plot_layon;

So sorry if i'm outdated of sql syntax in postgres.
Cheers.

**Comment by hqnghi88** [comment]
Hi Céline,
Could you please try now and tell us if this issue have fixed or not? I have just pushed a commit.
Cheers.

**Comment by hqnghi88** [comment]
@AlexisDrogoul 
Dear Alexis,
As far as I dig, this issue is related with the ICreateDelegate(s) order. In this case, the CreateFromGeometriesDelegate 's condition are fulfilled before the check of the conditions in CreateFromDatabaseDelegate, so the wrong delegate have chosen. I adjust a bypass condition in CreateFromGeometriesDelegate but i have impression that it would not the best solution. Could you please revise it in a future time?
Thank you.
Cheers.

**Comment by CelineLeCoq** [comment]
HI all, 
The displays seem fine now, thanks a lot !

Cheers, 
Céline

**Comment by AlexisDrogoul** [comment]
I'm happy to see this issue solved. Thanks, @hqnghi88  !
