### ISSUE TITLE
at_distance operator and list of agents (same species)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1655]
test the following model:

model atdistancefilter
global {
	init {
		create toto number: 50;
		create lala with: [location::location];
		ask lala {
			write (toto at_distance 20);
			write ((toto - (2 among toto)) at_distance 20);
		}
	}
}
species toto {
	geometry shape <- square(1);
}
species lala {
	geometry shape <- square(1);
}
experiment atdistancefilter type: gui;

The second lines "write ((toto - (2 among toto)) at_distance 20);" returns a wrong result. The problem comes from the filter method from the GamaPopulation class. Indeed, the "((toto - (2 among toto)" build a new toto population that is not "==" to the toto population, so the test "a.getPopulation() != this" is never true in this case.

**Comment by AlexisDrogoul** [comment]
You seem to have all the cards in hand to handle this one :)

I will check -- but not immediately as I have other urgent things to do...
