### ISSUE TITLE
Themes for editor

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1656]
Just wanted to bring this to notice. http://ethanschoonover.com/solarized
May be there is some interest in the group :)
coming from here https://github.com/altercation/solarized

**Comment by AlexisDrogoul** [comment]
Very nice. If anyone is willing to port it to eclipse/gama,  I promise to
include it in the release...
Le 5 avr. 2016 22:32, "Srirama Bhamidipati" <notifications@github.com> a
écrit :

**Comment by sriramab** [comment]
Here are two references
https://github.com/jubalh/eclipse-solarized

**Comment by AlexisDrogoul** [comment]
Good news is that the Eclipse color themes plugin works well in GAMA.
Bad news is that it doesn't recognize XText-based languages. So basically, it changes the background of the editor, but not the colors of the keywords...

**Comment by sriramab** [comment]
Curios if something could be sorted out here? 
Thanks.

**Comment by AlexisDrogoul** [comment]
Actually not yet. The eclipse plugin uses a very special way of displaying its themes, and there is no bridge between XText-based languages and it right now...

**Comment by AlexisDrogoul** [comment]
Moved to https://github.com/gama-platform/gama.experimental/issues/8
