### ISSUE TITLE
Perspective change and inspection of an agent

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1657]
Open a model in the editing perspective, load one of its experiment, then run the model. Then inspect one of the agents, go back to the editing perspective (by clicking on the perspective change button).... the editing perspective is well opened, but the button is still the same one (and it is not possible to go back to the simulation perspective).

I get this message
!ENTRY org.eclipse.ui 4 4 2016-04-05 21:49:11.769
!MESSAGE Perspective msi.gama.application.perspectives.ModelingPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.ModelingPerspective open  null

**Comment by AlexisDrogoul** [comment]
Sorry -- I've tried many models on MacOS X and Windows on the latest build ... And I cant reproduce this bug. The simulations can be running, or not, but it does not occur.

**Comment by hqnghi88** [comment]
Dear Alexis,
One more time  , i must say "yes". In addition of the ModelingPerspective open null , I have some more:

!ENTRY org.eclipse.ui 4 4 2016-04-06 09:48:07.538
!MESSAGE Perspective msi.gama.application.perspectives.SimulationPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.SimulationPerspective open  null
experiment agent set seed: 0.7253853368659178
simulation agent set seed: 0.7253853368659178

!ENTRY org.eclipse.ui 4 4 2016-04-06 09:48:09.146
!MESSAGE Closing Error View
GAMA Caught a workbench message : Closing Error View null
experiment agent set seed: 0.8195045317538294

Sorry for the missed issue.

**Comment by AlexisDrogoul** [comment]
Still cant reproduce it. Please provide a reproducible use case (which model ? which sequence of actions? How is the inspector invoked? Does it the same with monitors or population browsers ?)

**Comment by hqnghi88** [comment]
Dear Alexis,
I have no specific actions regarding Patrick's post. I open a model in edit pers., launch experiment, run simulation. And by clicking on "Switch perspective" button, each time will cause an exception caught in eclipse console. But i dont have the last sequel of Patrick "(and it is not possible to go back to the simulation perspective)."

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:45.916
!MESSAGE Perspective msi.gama.application.perspectives.SimulationPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.SimulationPerspective open  null
experiment agent set seed: 0.07483297831656277
simulation agent set seed: 0.07483297831656277

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:47.436
!MESSAGE Closing Error View
GAMA Caught a workbench message : Closing Error View null
Agent constructor for Description of ant based on :class msi.gama.metamodel.agent.MinimalAgent
Overlay position: java.awt.Point[x=10,y=10] size: java.awt.Point[x=250,y=150]

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:51.102
!MESSAGE Perspective msi.gama.application.perspectives.ModelingPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.ModelingPerspective open  null

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:51.933
!MESSAGE Perspective msi.gama.application.perspectives.SimulationPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.SimulationPerspective open  null

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:52.689
!MESSAGE Perspective msi.gama.application.perspectives.ModelingPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.ModelingPerspective open  null

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:53.413
!MESSAGE Perspective msi.gama.application.perspectives.SimulationPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.SimulationPerspective open  null

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:54.125
!MESSAGE Perspective msi.gama.application.perspectives.ModelingPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.ModelingPerspective open  null

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:54.918
!MESSAGE Perspective msi.gama.application.perspectives.SimulationPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.SimulationPerspective open  null

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:57.591
!MESSAGE Perspective msi.gama.application.perspectives.ModelingPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.ModelingPerspective open  null

!ENTRY org.eclipse.ui 4 4 2016-04-06 10:57:58.569
!MESSAGE Perspective msi.gama.application.perspectives.SimulationPerspective open 
GAMA Caught a workbench message : Perspective msi.gama.application.perspectives.SimulationPerspective open  null

**Comment by AlexisDrogoul** [comment]
These are not exceptions but workbench messages that I post myself. As such, they are harmless.  So, basically, you cant reproduce what this issue is about (i.e. not being able to come back to the simulation perspective) ? That's quite a good news !

**Comment by ptaillandier** [comment]
I have just tested on my windows computer and on a "new" macbook pro and the bug does not appear. During lunch, I will try  on an older macbook pro (2013) and see if I get the bug.

**Comment by ptaillandier** [comment]
Good news, this bug has disappeared ..... no idea how (update of GAMA ? or of my OS/Java/others ?)
