### ISSUE TITLE
ROI selection mode not left after releasing shift key and obtaining menu 

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1659]
Invoking the ROI selection once (shift + drag), then dismissing the menu, lets the display in a state where a normal drag (without shift) acts like a ROI selection. Pressing shift once allows to leave this "strange" mode.

**Comment by mazarsju** [comment]
I cannot reproduce this one, maybe it was resolved with the last commit I just did. Can you check ?

**Comment by AlexisDrogoul** [comment]
Seems to be working now -- I replace it with another issue I'm having :)
