### ISSUE TITLE
add unitary tests for graph loading

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#166]
```
there is no test for graph loading.
Should:
- add example files for the tests
- write unitary tests.

```

Original issue reported on code.google.com by `Samuel.Thiriot.Asso` on 2012-03-22 02:55:32

**Comment by AlexisDrogoul** [comment]
Actually, we need unitary tests for most of GAMA features. I close this issue (focused on graphs) — feel free to open a more general one...
