### ISSUE TITLE
Initial 3D move (cmd/ctrl + drag) does not display the directional sphere

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1660]
Open any model with an OpenGL display. Then press CMD/CTRL and drag to enable 3D moves. The directional sphere is not displayed although is should be. Release CMD/CTRL and press it again. The directional sphere appears, and it's now the same for every subsequent 3D moves.

Not tested on Windows yet.

**Comment by mazarsju** [comment]
This one occurs also in Windows I think... I'll investigate.

**Comment by AlexisDrogoul** [comment]
Yep. Just tested it.
