### ISSUE TITLE
Add a default button for the User Command

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1663]
When creating a user command, within a user panel, we have to click on both buttons "Activate" and "Continue" to take in consideration our choice (validate the selected option by activate) and continue the simulation of the model. I personally think we could add a enhancement for the user to choose a default button between those two as they are quite redundant (rather it is Activate or Continue should be the user's choice).

**Comment by AlexisDrogoul** [comment]
Or, more specifically, we should allow any button (there can be several) to act as a one-shot selection, first executing the action and then moving on to the next step. Two things here: (1) add a facet (which name ?) to the `user_command` statement; (2) visually distinguish these buttons (color ? icon ?)

**Comment by AlexisDrogoul** [comment]
Should be done now. Can you test it and close this issue if ok ? 

Basically, `user_command` now accepts 2 more facets:
`color`: to specify the color of the button (works in parameters, inspectors and user panels)
`continue` (true/false): to specify whether clicking on the button will allow to continue (works in user panels only).

**Comment by dphilippon** [comment]
It works exactly as expected ! I close the issue.

**Comment by AlexisDrogoul** [comment]
I used an icon which is maybe not really appropriate for that (that's the one from the batch). Ideally, we should use a kind of "fast-forward" to keep in line with the "continue" button. If you have the time to do it (i.e. duplicate "small.run.png" and rename it "small.continue.png", then edit it to show a fast-forward arrow -- or anything meaningful --, then, in UserControlView.java replace "small.batch" par "small.continue").

**Comment by dphilippon** [comment]
I've added a New icon looking like a fast-forward arrow as asked ! Thank you again
