### ISSUE TITLE
Impossible to create a release from Windows platform

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1668]
While following step by step the documentation https://github.com/gama-platform/gama/wiki/G__CreatingAReleaseOfGama on Windows, the generation is stopped with the following message : 

```
'Export Product' has encountered a problem.

Unable to find feature "org.eclipse.e4.rcp" with version in range [1.4.1.v20160212-1350,1.4.1.v20160212-1350].
```

Note : the software "Eclipse e4 Tools Developer Resources" has been installed in my eclipse, but the same error message continues.

**Comment by AlexisDrogoul** [comment]
2 things:

- is the feature mentioned (`org.eclipse.e4.rcp`) part of this installation (`Eclipse e4 Developer Resources`) ? And in that case, does it have the right version number ?
- how is this feature imported into GAMA ? Added to the product ? Part of the dependencies feature ? Installing the library is not enough for building as it needs to be added somewhere as a dependency, so how is it declared ?

**Comment by mazarsju** [comment]
Eclipse e4 Developer Resources has been installed through the "Install New Software" of Eclipse, it has not been added explicitly to the product indeed. I'm not sure `org.eclipse.e4.rcp` is a part of `Eclipse e4 Developer Resources` anyway, it was more a desperate move than anything else...
Note that `org.eclipse.e4.rcp` appears in the list of the Features of the product, with the right version (1.4.1.v20160212-1350) !!

**Comment by AlexisDrogoul** [comment]
In that case, try to find out if (1) this feature exists in the Eclipse installation with the same version number (I would bet that it doesn't); (2) remove the requirement on the version number from the product (it is usually bad practice to restrict too much a version number: a lower bound is normally enough).

**Comment by mazarsju** [comment]
(1) : no, I cannot see this feature in the "Installation details" of eclipse.
(2) : how can I remove the requirement of the version number from the product ? You mean by selecting the feature, clicking "properties" and let an empty string ? (it is already the case)

**Comment by AlexisDrogoul** [comment]
Do you have a target definition ? Is the feature part of it ?

**Comment by mazarsju** [comment]
Ok, apparently the problem only occurs for me : Quang and Nghi can both generate a release. And they don't have `Eclipse e4 Developer Resources` installed, so the problem is not here. I checked all their configuration, it seems exactly the same as what I have... But well, if it only happens in my computer, it is not very important. I'll do without, that's all. I close this issue then.

**Comment by AlexisDrogoul** [comment]
Just as a side note: the important comment here is the one mentioning the target definition. 

The target platform (defined in `Eclipse > Preferences... > Plugin Development > Target Platform`) is the one that is used to manage the plugins available for building GAMA. This target platform is key to building GAMA in different configurations and this is where the builder will pick the plugins available. 

By default, GAMA should be easily built using the default target platform (which consists in the plugins currently loaded in Eclipse). If the export does not work, it is worth checking if the target platform contains the missing plugin or duplicate versions of the same plugin... And in that case, just create a new "default" one and make it active.

Probably we should add some warning in the documentation about it ?
