### ISSUE TITLE
Raise an error in the processor when an extension is defined twice

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1673]
The goal here is to reduce the number of problems when calling the operator "file()". According to the extension, the operator "file()" should cast to the right file type.
see also #1672.

**Comment by AlexisDrogoul** [comment]
I've tried several combinations and, unfortunately, there is no way we can do it using the actual processor. To state it clearer: it is feasible within one single plugin/project to detect doublons, but not accros plugins (each processor is independent and even static lists cannot be shared between them, as they seem to be created by different ClassLoaders. So, without the possibility to share any information between processors, it is impossible to implement. I close this issue then.
