### ISSUE TITLE
problem of colors in OpenGL displays

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1680]
Try the following model:

```
model new1

experiment ee type: gui
{
	output
	{
		display dd type: opengl
		{
			graphics "gg"
			{
				draw circle(10) color: # yellow at: any_location_in(shape);
				draw circle(10) color: # red at: any_location_in(shape);
				draw circle(10) color: # green at: any_location_in(shape);
				draw circle(10) color: # darkseagreen at: { 40, 40 };
				draw circle(10) color: # wheat at: { 20, 20 };
			}

		}

	}

}
```

Only the first 3 circles are displayed. The two last ones appear in white. It works fine in Java2D, though.

**Comment by AlexisDrogoul** [comment]
It seems to only concern "light" colors. For instance, `#navy` works just fine. I dont understand anything, to be frank.

**Comment by AlexisDrogoul** [comment]
To be sure, I made a test with a simple display.

```
			graphics "gg"
			{
				loop i from: 1 to: 255 {
					loop j from: 1 to: 255 {
						draw square(10) color: rgb(i, j, 200) at: { (i - 1)*10, (j-1)*10 };
					}
				}

			}
```

It works fine in Java2D (screen 1)

![ee2 - users drogoul documents gama_workspace dkdkd models new1 gaml 2016-04-13 17-27-39](https://cloud.githubusercontent.com/assets/579256/14490466/3a3765de-019d-11e6-9297-8e2eb2e35007.png)


But we effectively have a small problem in OpenGL

![ee2 - users drogoul documents gama_workspace dkdkd models new1 gaml 2016-04-13 17-26-35](https://cloud.githubusercontent.com/assets/579256/14490475/45e9613e-019d-11e6-8c16-7f9a667444df.png)

**Comment by AlexisDrogoul** [comment]
I'm completely lost on this one. Does anyone ( @gama-platform/committers @gama-platform/core ) have any clue ??

**Comment by mazarsju** [comment]
We saw it a bit with Damien, and it seems it is a problem of light... Indeed, when you disable the light just before drawing the polygon (method "drawTesselatedPolygon" in "JTSDrawer.java"), it appears just fine. By changing the ambient_light value to 40, you have the same result as in Java2D.

**Comment by mazarsju** [comment]
A solution would be to change the default ambient light to rgb(40,40,40) instead of rgb(125,125,125). But it seems a bit hazardous to chose this value "40", what do you think about that ?

**Comment by AlexisDrogoul** [comment]
Well. I'd say that the value of 40 is as arbitrary as the one already chosen (125) -- but if it allows to reflect the colors a bit more faithfully, I'd go for it.

**Comment by mazarsju** [comment]
In fact it was not even 125, but 100 (??). The documentation was wrong. Anyway, I changed it to 40.

**Comment by AlexisDrogoul** [comment]
Got the change. It's better, but far from perfect (all the colors appear more or less faded compared to Java2D). Why do we  need this ambient light, by the way ? Is it mandatory, or only here to provide some fancy effect ?

**Comment by hqnghi88** [comment]
HI,
I remember that we have an option in preference to chose to use ambien_light by default but i cant find it anymore, or i just dream about it?

**Comment by agrignard** [comment]
Quickly (first bug issue answer from US) yes the ambient light is mandatory otherwise you won't see anything. I think that 40 is a bit too low (too dark). The default (100) value was more or less the one that gave the same color as in java2D. I don't think that changing this value will fix the problem. This issue remind me a very old one but I can't find it

You can have a look here http://www.tomdalling.com/blog/modern-opengl/07-more-lighting-ambient-specular-attenuation-gamma/ to understand how light is working in an OpenGL world

**Comment by AlexisDrogoul** [comment]
Basically, if I set the facet `ambient_light` to zero in the display, I obtain the same color spectrum than in Java2D. So maybe something else has changed in the management of lighting in OpenGL displays, which makes the old value (100) inappropriate ?

**Comment by AlexisDrogoul** [comment]
I have tried to read the link, but I dont get most of the things, unfortunately.

**Comment by mazarsju** [comment]
Here is a small recap, with the short model I use : 

```
model new

global {}

grid cells width:2 height:2 {
	rgb color <- rgb(255,220,255,255);
	aspect base {
		draw square(100.0/2) color:rgb(255,220,255,255);
	}
}
grid cellsAlpha width:2 height:2 {
	rgb color <- rgb(255,220,255,100);
	aspect base {
		draw square(100.0/2) color:rgb(255,220,255,50);
	}
}

experiment my_experiment type:gui{
	output {
		display "alpha=255, ambient_light=40" type:opengl background:#white ambient_light:40 {
			grid cells;
		}
		display "alpha=255, ambient_light=100" type:opengl background:#white ambient_light:100 {
			grid cells;
		}
		display "alpha=100, ambient_light=40" type:opengl background:#white ambient_light:40 {
			grid cellsAlpha;
		}
		display "alpha=100, ambient_light=40 (species)" type:opengl background:#white ambient_light:40 {
			species cellsAlpha aspect:base;
		}
		display "alpha=100, ambient_light=100" type:opengl background:#white ambient_light:100 {
			grid cellsAlpha;
		}
		display "alpha=100, ambient_light=100 (species)" type:opengl background:#white ambient_light:100 {
			species cellsAlpha aspect:base;
		}
		display "java2D alpha=255" {
			grid cells;
		}
		display "java2D alpha=100" {
			grid cellsAlpha;
		}
	}
}
```

Here are the images i have (with the RGB values) : 

![image1](https://cloud.githubusercontent.com/assets/12977635/14661775/8a2290cc-06da-11e6-99ea-bf72cfd438a6.png)

After I tried with a diffuse light equal to 0 : 

![image2](https://cloud.githubusercontent.com/assets/12977635/14661782/a23da872-06da-11e6-9c6f-8de97cea354b.png)

Those results lead me to the following conclusions : 
- The diffusion light has to be removed by default !
- The ambient light has to be reset to 100
- There is a serious problem of color blending with the grid when the alpha is smaller than 255.

**Comment by AlexisDrogoul** [comment]
Good experiment. Another way to look at it would be to say that the only correct results (in both cases of grid and species) are the ones with ambient_light = 40 and diffuse_light on. 

By the way, in your model, the grid cellsAlpha have two different colors if they are displayed as a grid and as a species. It is what you wanted ?

**Comment by mazarsju** [comment]
I would be more in favor of removing completely the diffusion light by default, as it is a bit more complicated than the ambient light (a diffusion light need a position for instance). And more precise than 100, I found that the value 102 for ambient light gives the exact same results as for Java2D.

Woh ! That's clearly a mistake from me, indeed.

**Comment by mazarsju** [comment]
If the "goal" of this issue is to have exactly the same colors than in a Java2D display (by default), we definitely should remove this diffuse light.

**Comment by AlexisDrogoul** [comment]
Regarding the grid display problem, I'm happy to report that it is now solved. It was a problem with JOGL imposing a premultiplied alpha in the color model of custom images. The fix is a bit of a hack but it works well.

**Comment by agrignard** [comment]
I did not get everything in this issue but I see that you want to remove the diffuse light by default. Why not for the 2D rendering and in order to have java2D=Opengl. But It's definitively not the the best idea for 3D model that will look very weird and flat. Without diffuse light there is no way to render a "realistic" 3D scene.

See for instance a road traffic model with a diffuse_light= 0 , looks bad isn't it?
![screen shot 2016-04-20 at 11 03 04](https://cloud.githubusercontent.com/assets/3928502/14679367/8bf31b9e-06e7-11e6-9ef9-bae6ed2d16e9.png)

**Comment by AlexisDrogoul** [comment]
The problem raised by @agrignard is to be taken seriously. With all the changes made to the display of grids, etc. does the diffuse light still influence the rendering of colors compared to Java2D ?

**Comment by mazarsju** [comment]
Ok, I have to admit it, it is very ugly ^^'.

So we need both ambient and diffuse light (we forget about specular, way too fancy for what we want), and we have to find a balance between the two to have the "same" visual effects as in Java2D.

The value of the ambient light is the value determines the illumination of objects which are totally out of range of the diffuse light (the diffuse light is placed by default in the center of the world, with a z value twice the wider dimension of the world). I think we can use the value (0.2,0.2,0.2,1), as it is used in this [website](http://www.falloutsoftware.com/tutorials/gl/gl8.htm). That leads us to set the default value for diffuse light to 110 by default.

**Comment by mazarsju** [comment]
I just commited the changes. If no one is against those changes, I'll make the changes that are needed in the model library (and possibly in the tutorial).
Speaking about that, I think it would be more realistic to change the diffuse light instead of the ambient light for the models that simulate a night/day cycle. Indeed, "all cats are grey in the dark" ;). So I would be in favor in changing a bit the "incremental tutorial" about light to change the diffuse light instead of the ambient light, it makes more sense for me. What do you think @agrignard ?

**Comment by agrignard** [comment]
No probs for the tutorial if you want ot play also with tthe diffuse_light but if you want to have a night effect you still have to decrease the ambiant_light. If you just decrease the diffuse_light you won't get the night

**Comment by mazarsju** [comment]
No complains so far, I close this issue ! :) (I just made the changes for the model library and the tutorial)
