### ISSUE TITLE
batch and repeat

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1681]
Open the batch model (Model library/Features/batch/batch.gaml) and load the "run 5 simulations" experiment. The simulation is supposed to be run 5 times but seems to be run only once.

**Comment by hqnghi88** [comment]
Dear Patrick,
On my pc, it look like i have 5 simulations run parallel of 1 experiment "run 5 simulation". If i launch "Exhaustive optimization", the size of parameters space is  3x3  = 9 and i have exactly 45 simulations run (9 x 5 repeat ). Does it the same with your version? I have impression that "repeat 5 times" in experiment declaration is supposed to have 5 simulations in parralle, is it the same meaning as 5 times of doing experiments with exploration methods?
Cheers.

**Comment by ptaillandier** [comment]
You are right. My problem comes from the fact that with GAMA 1.6.1, the reflexes of an experiment were executed at the end of each simulation (i.e. each repetition). Now, it is only called at the end of the each parameter set (only once even if there are several repetitions). I don't know if it is the expected behavior of the experiment reflexes, but it poses some compatibility problems.

**Comment by AlexisDrogoul** [comment]
Do you observe the same behavior if you turn off the "multi-thread' simulations option ?

**Comment by hqnghi88** [comment]
Dear Alexis,
I switch off the "Multi-thread" in preference and i observe the same behaviors.

**Comment by AlexisDrogoul** [comment]
Well, this probably comes from the implementation of the "multi-simulation" scheme in any case, since the behavior of experiments has been aligned on that of the "normal" macro-agents. If it is too much of a burden, there is probably a way to come back to the "old" behavior.

**Comment by AlexisDrogoul** [comment]
So what should we do ? Basically, the experiment runs its behaviors, in batch mode, after all the repetitions of a set of parameters, but all the simulations are still "alive", so it means they can be browsed, saved, etc. I have added an attribute to experiments called `simulations`, that allows to obtain the list of currently running (or not yet disposed of) simulations.

**Comment by ptaillandier** [comment]
If we can access all the global variables of all the repeated simulations
in gaml, it is ok for me, we can close this issue. It will just be (very)
important to update all the models in the Library that use reflexes in
experiment (in particular the batch model that have to document this
change) and the documentation.


2016-04-20 4:52 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
How many models are impacted ? Do you have a list of them ? I havent touched the "batch models" in a while so I dont know exactly where to dig...

**Comment by ptaillandier** [comment]
Just a question, in the Model Library/Features/Batch/batch.gaml model, I have this experiment:
experiment 'Run 5 simulations' type: batch repeat: 5 keep_seed: true until: ( time > 1000 ) {
	int cpt <- 0;
	action _step_ {
		save people type:"shp" to:"people_shape" + cpt + ".shp" with: [is_infected::"INFECTED",is_immune::"IMMUNE"];
		cpt <- cpt + 1;
	}
}
How to write it using the simulations keyword?

**Comment by AlexisDrogoul** [comment]
Have you tried:

```
	action _step_
	{
		int cpt <- 0;
		ask simulations
		{
			save people type: "shp" to: "people_shape" + cpt + ".shp" with: [is_infected::"INFECTED", is_immune::"IMMUNE"];
			cpt <- cpt + 1;
		}

	}
```

?

**Comment by ptaillandier** [comment]
Ok, I have tested it and it works well (I really like this new way of managing simulations.... allows many new possibilities ;) ).. In addition, I have added commentaries to the batch feature model. So we can close this issue
