### ISSUE TITLE
Catch & translate Java exceptions

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1682]
Once again, the message "NullPointerException" appeared in my GAML console. Should it not be "NilPointerException" instead ? (or something similar).

![image1](https://cloud.githubusercontent.com/assets/12977635/14524220/8fbba05a-0261-11e6-92ef-f9771fed8121.png)

**Comment by ptaillandier** [comment]
If this message aims at being read and understood by a modeler, we should maybe throw a message easier to understand: "problem with a nil value" or something like this.

**Comment by AlexisDrogoul** [comment]
It is the case of all the exceptions raised in Java (i.e. the ones different from and not "transformed " into GamaRuntimeExceptions), especially the runtime Java  exceptions that we do not raise and catch explicitly. It is the case here (probably the argument is null ?). So, either we translate the possible exception messages to something "readable in GAML" or we hide any mention of Java and just say an error happened -- or we let it like this (which is quite explicit, by the way: it tells that something was "null" in Java which shouldn't have been -- and this does not always coincide with something "nil" in GAML, as it can be in a remote algorithm).

**Comment by mazarsju** [comment]
I would be in favor of having the name of the error (cf "java.lang.NullPointerException") transformed into something "readable in GAML", and keep the java error stack after (the java error "java.lang.NullPointerException" is said a second time in the stack, so we can name the error differently).

**Comment by AlexisDrogoul** [comment]
I agree that it would be more readable, but, again, a "null" value caught in Java does not always mean that something was "nil" in GAML. It can be a property of a field inside an object we dont even know about in GAML. 

The "good" way would be to verify in every operator the preconditions so that we can catch null pointer exception that make sense in GAML and give them explicit messages.

**Comment by mazarsju** [comment]
I see... Well, in this case, yes, to verify in every operator the preconditions should be the best way... 
That means that each java exception risen (not treated as a gaml exception) should be considered as a bug we should investigate, right ?

**Comment by AlexisDrogoul** [comment]
I have implemented a basic solution in the latest commit. I think it is enough for most users. Some common exceptions are translated to a readable form (including exceptions in specific libraries, such as JTS, GeoTools, etc.) and their exact name is reported on the second line. I close this issue until someone reopens it with more specific requirements...
