### ISSUE TITLE
Polymorphisme question : calling "mother_species" should return the list of "mother_species" + "species" ?

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1694]
When creating some "child" species, we don't get them by calling the "mother" species, like in the following example : 

```
model test

global
{
	init {
		create my_species number:1;
	}
	reflex update {
		write length(my_species_mother); // will write 0 instead of 1
	}
}

species my_species_mother {}

species my_species parent:my_species_mother {}

experiment my_experiment type:gui {}
```

This behavior is understandable, but I think "my_mother_species" should return the list of "my_mother_species" and the list of "my_species" together. What do you think ?

**Comment by AlexisDrogoul** [comment]
This is the intended behavior. The name of the species is a shortcut for `species_name.population` and it returns the direct instances of the species. A simple method to get all the instances can be found below:

```
model new

global {
	
	init {
		create mother;
		create child1;
		create child2 number: 2;

		write get_all_instances(mother);
	}
	
	
	list<agent> get_all_instances(species<agent> spec) {
		return spec.population +  spec.subspecies accumulate (get_all_instances(each));
	}
	
}


species mother;

species child1 parent: mother;

species child2 parent: child1;

experiment exp type: gui {}
```
