### ISSUE TITLE
Verdict message not clear when 2 imported files contains the same experiment name

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1697]
When a model imports 2 other models which both contains the same experiment name, the verdict message is "The model is functional, but error(s) were detected in imported files. Impossible to run any experiment". This is not very correct, since the imported files does not contains any error. An other message such as "The model is functional, but several experiments with the same name were detected in imported files. Impossible to run any experiment" should be more accurate.

**Comment by AlexisDrogoul** [comment]
I have fixed the problem by transforming the button on which the message is displayed into a trigger for a menu that lists the errors (and allows to jump to the model incriminated).

**Comment by mazarsju** [comment]
That sounds like a more sustainable solution indeed ;)
