### ISSUE TITLE
string user_input and "/' symbols

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1699]
In GAMA 1.7 (that was not the case in GAMA 1.6.1), when asking a _user_input_ to a user for a string variable, the user have to use the "" (or '') symbols, which is not very practical when the target users are not specialists of GAMA.

For example, in this simple model:
model userinput
global {
	string val <- "lala";
	reflex test {
		 map input_values <- user_input(["val" :: "lala"]);
		 write input_values;
	}
}
experiment userinput type: gui;

If I write in the dialog box "lili", it is working normally, but if I just write lulu (without the ""), it is not working (as it is not a correct string).

**Comment by AlexisDrogoul** [comment]
It is maybe not practical, but it is logic. GAMA expects in these boxes a valid GAML expression, so you need to enter quotes and/or double-quotes if you want to input a string. It allows, for example, to use variables and attributes (which was not possible before). One possibility to allow a "direct string" input would be to add another operator (like `string_input`, and why not `int_input`, `float_input`) that would already know the type expected and use a specific input field.

**Comment by AlexisDrogoul** [comment]
As an aside, please note that it is also in phase with the way string parameters can be entered by the user; having two ways of inputting strings would probably be a bit confusing...

**Comment by ptaillandier** [comment]
I am totally agree with you. It is just as GAMA is more and more used in
participatory simulation context, we should maybe think how we can
facilitate the interaction between the user and the simulation. You can
close this issue if you want.

2016-04-22 6:02 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
OK. I close it (unless `string_input` and the like are needed by someone -- but it's not too complicated to implement, just create a LabelEditor instead of a StringEditor when instantiating it).
