### ISSUE TITLE
Diffusion light is not affecting the grid and the species in the same way (when above saturation)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1702]
For important diffuse light, light colors are turned white for the species (which is normal), but not the grid, see example below : 

```
model new

global {
}

grid cells width:2 height:2 {
    rgb color <- rgb(255,220,255,255);
}

experiment my_experiment type:gui{
    output {
        display "grid" type:opengl background:#white diffuse_light:200  {
            grid cells;
        }
        display "species" type:opengl background:#white diffuse_light:200 {
            species cells;
        }
    }
}
```

![image2](https://cloud.githubusercontent.com/assets/12977635/14732302/a27db3b8-0883-11e6-8366-d0a2d5e957d5.png)

**Comment by agrignard** [comment]
Normal are not computed for Grid display (but yes when grid is displayed using the species) so the diffuse light has no effect. 

It's not a bug, it's a choice.  It's faster to render grid withtout computing normal. So maybe the solution would be to document it or to have a warning saying that when you use grid the diffuse_light has no effect (anyway it's useless and time consuming to compute the normal and try to define a diffuse_light to render a 2D grid).

**Comment by AlexisDrogoul** [comment]
Hum... 2D grids (not DEMs) like this one are actually displayed as images -- not cell by cell, so it might not be too slower to compute the normals to these 2D plans. I was wondering if we have the same defects when the world draws an image for its aspect (in a graphics statement) or when it draws its shape (rectangle or square) with the same texture.

**Comment by AlexisDrogoul** [comment]
Has anyone tried what I propose to test in the above comment ?

**Comment by AlexisDrogoul** [comment]
see #1716
