### ISSUE TITLE
Arcball sphere helper enhancement

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1703]
The idea of the sphere is good but I think it can be improve. 

- For beginner user this ok to display it by default but as soon as you know how to use this arcball it became useless  plus if you want to to demo you don't want to have this sphere in the middle of your model so I think we should definitely add a preference to activate/desactivate it.

- What does mean the radius of the current one? Shouldn't we draw the "real" arcball sphere (something that is around the model) like in the following picture (taken from GLC_Player) 
![screen shot 2016-04-20 at 15 02 16](https://cloud.githubusercontent.com/assets/3928502/14789499/d34f405c-0ada-11e6-826a-78227be8b9e9.png)

- We should keep the original referential and draw another one (like in the previous picture) at the center of the sphere, if found it a bit confusing to have this moving referential.

**Comment by mazarsju** [comment]
* About the first point : it is already possible to hide this sphere in the OpenGL preferences.
* About your second point : it's an open question... I like the wireframe effect of the sphere, and I think that if it is displayed bigger, it'll bring confusion...
* About your third point : I don't really see the second referential in the center of the sphere in your picture... But yes, maybe we should always keep the original referential (which corresponds to the real origin of the referential) and add another one in the corner of the image to show the position of the vectors, as it is displayed in your image, and as it is the case in most 3D design softwares. 

If we want to go even deeper in this field, we can also make this second referential more interactive, as it is the case for the Unity gizmos : by clicking in the axis, the camera changes its position to see the right "face" of the world : 

![image1](https://cloud.githubusercontent.com/assets/12977635/14804776/656384fc-0b90-11e6-95ef-eb995e269b48.png)

**Comment by agrignard** [comment]
first point: Ok sorry I did not see it was in the preferences.
2nd point: Yes the wireframe is cool but it could be a bit "lighter" "with less wire, in the picture I send its just a circle that gives the effect of a sphere. I am just sometime surprise by the radius of the sphere, how do you compute it? 
3rd point: The second referential is just behind the car in the picture I sent, I think we should definitely differentiate the model referential and the arcball one (this is not hard to do), and the idea to have an interactive referential in the corner is a great idea (but it's a bit trickier to implement)!

**Comment by mazarsju** [comment]
Drawing just a 2D circle to indicate that we are doing a rotation (3D !) is a bit confusing I think... The size of the sphere is compute to appear with always the same size, whatever zoom we are using, and whatever the size of our environment. The size has been chosen to be not too big and not too small...

I find the second referential of your picture a bit ugly to be honest ^^'. Having a second referential (with always the same size, whatever zoom / environment size) in the corner is a good idea. But then adding a new one inside the sphere will not make sense anymore.

**Comment by agrignard** [comment]
Ah taste & color.... ;-) 

Briefly:
It's not just a 2d circle, it's a 2D circle (the big one) and a kind of 3D cross (just above the mouse pointer) it's hard to see on the picture but there's no way to send video on github... or you can install GLC_Player (don't know if it works on windows). Well that's just an example but when you use it s practical. 

For the size of the sphere ok why not having a constant radius 

I think the main point of this issue is just:

- keep the original referential 
- draw another one in the center of the sphere in a first time and why not later having a more interactive one in the corner.

**Comment by AlexisDrogoul** [comment]
My two cents. I find the current presentation of the sphere and referential (moved to the center when rotating) extremely clear and providing a good feedback to the user. It avoids to pollute visually the display like the first image you show (well, it's my opinion, of course) where, clearly, there are ways to get lost with all these "guides" displayed everywhere. I have nothing, of course, against trying new approaches, but for me it is not a priority... What do the others ( @gama-platform/committers / @gama-platform/core ) think ?

**Comment by AlexisDrogoul** [comment]
Closing this one as it seems that nobody has nothing against the current presentation of rotation... Feel free to reopen with more ideas.
