### ISSUE TITLE
Equation solver facets

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#1705]
Hi,

I am working with Nghi on the equation package, and I have a few suggestions for improvement in order to make it clean with more natural keywords for mathematicians.

There is an ambiguity between the different steps used for the integration and for the Gama scheduler. There are several different kind of steps:

1) Cycle: the cycle is the unit for computation (each agent is updated once per cycle)
2) Integration step: the length of the step used for the numerical methods. It does not affect the dynamics, but only the accuracy of the numerical solution for the differential equation.
3) Visualization step: defines at which time step the numerical solution should be plotted. This is used because one may found that having one point for every cycle is not sufficient to represent the smoothness of a math solution, or to find remarkable points (a maximum which could occur at the middle of a cycle).

In addition, there is a scale factor used to make the time scales of agent scheduler and equation solver correspond, which is represented by the facet "cycle_length".

In my opinion, the current name are not explicit enough in order to avoid confusion. Furthermore, there are two different keywords named "step": 

- one used at the global level for the time scale of the simulation (step <- 3#sec means that a cycle duration is 3 seconds)
- one as an equation facet, which defines the integration step.

To remove the ambiguity in the names of the facets, I suggest to rename
- step (equation facet) to integration_step (the unit being one cycle ?)
- discretizing_step to visualization_steps
- integrated_times to visualization_times
- integrated_values to visualization_values

Regarding to the time scale factor, the information is provided by two facets : 

- "step" at the global level, which provides the duration of a cycle
- "cycle_length" which tells how many cycles correspond to 1 unit of time in the equation.

However, when designing an ODE, it is not very natural to talk about steps, because the parameters of the equation are associated to a time unit (eg: in physics, for a movement equation corresponding to free fall d2x/dt2 = g, g is expressed in m.s^-2). The time unit is never made explicit in other language or platform (matlab, maple...) because they are not meant for models coupling. In Gama, this is required, but itt would be more natural to express a time unit for the Gama scheduler and one for equation solver. Something like:

step <- 1#day for the scheduler;
equation_time_unit <- 1#day for the equation (or just time_unit if it does not introduce any other ambiguity).

cycle_length would then correspond to equation_time_unit/step, if there exists an arithmetic that allows such a division. If so, "cycle_length" would become obsolete as a facet.

If no value is given to step and equation_time_unit, it would be assumed that the time unit is the same for both (which will be generally the case).

If only one of the time unit is given, there should be a warning saying that it is implicitly assumed that the
time units are the same.

**Comment by AlexisDrogoul** [comment]
I noticed also the strange names and ambiguities. One (short) question: is it necessary to have both an integration_step and a visualization_step ? And another one: To what do the visualization_times and visualization_values facet correspond to ? What is their use ?

**Comment by tnguyenh** [comment]
integration_step is related to the numerical method and affect the accuracy of the solution. It's value is often very small (0.001), and is choosen for technical reasons (accuracy). The visualization_step is related to the user preference for curves display: sometimes only a few points are needed, sometimes it is better to have a smooth curve.

As an example, consider the following output. For the upper curve, vizualisation_step is high (here 25), so there are a lot of points displayed and the curve is smooth. For the second curve vizualisation_step is low, which means that it appears more like a discrete time series.

![original curve](https://cloud.githubusercontent.com/assets/18676913/14851127/2936d652-0c7e-11e6-8055-99f738358da7.PNG)

However, the integration_step is exactly the same, which means that the numerical solution is also exactly the same. e.g. the first curve has exactly the same value at point 75 than the second at point 3. If this curve was representing a chemical reaction, the user may want a smooth curve in order to see visually where the maximum is obtained. If this curves describe the demography of a population, it may not be relevant to display more than one point per year, so the second curve would be better, but a very small integration_step is still needed to get accurate values.

Moreover, some numerical methods use adaptative steps, which means that the interval two points may vary for integration. It makes technically difficult to link integration_step to the visualization_step.

visualization_times is a list (or vector ?) that contains the absisses, and visualization_values is a list of lists that contains the corresponding ordinates (it is a list of list because several curves could be displayed at the same time, like the red, blue and yellow ones in the figure).

**Comment by AlexisDrogoul** [comment]
I see. But why are the two last ones facets of the equation ? To pass the name of the variables used for that purpose, that's it ?

I think it would be much better if these variables could be accessed directly (my_equation.visualisaiton_times, for instance).

And would it be a heresy to have the same step for integration and visualization ? (because, obviously, one cannot be smaller than the other...)

**Comment by AlexisDrogoul** [comment]
After discussion with Nghi and Tri, we arrived to the following compromise:

- only `step` (or `integration_step`) will be passed to the `solve` statement (besides, of course, the specific facets for each solver).
- the integration step passed will always determine the previous `cycle_length` (simply by dividing the GAMA step by this integration step).
- the result of the previous integration will always be kept in memory by the equation (or the solver) as a map<string, list<float>> and the times of integration as well. 
- these values will be retrieved by hacking the parser and allowing to use `var_name[]` or `t[]`(this would trigger a verification that the var_name or t are effectively used in an equation and then return the latest computed values).

It will then be up to the modeler to choose to keep all the values or not, display all the values or not, etc... Which can be done by using these stored values.

Please comment if I made some mistake (esp. @hqnghi88 and @tnguyenh )

**Comment by tnguyenh** [comment]
OK for all points, except n°2. The integration step and cycle_length have very different purpose. 

Integration step always refers to a fraction of one cycle (for the scheduler): e.g: 0.001 means that you will have 1000 steps of integration for each cycle.

cycle_length refers to the relative scale of the equations. Presently, a cycle_length of 10 means that 10 cycles of the scheduler correspond to 1 unit of time in the equation. So cycle_length should be replaced by a time scale indicator. The most natural way would be in my opinion would be to have the ability to provide the time scale for both scheduler and equations (e.g: 1#day for the scheduler, 1#sec for the equations). The scaling would then be done automatically.

**Comment by AlexisDrogoul** [comment]
Sorry, I dont get it. Using units or not should not change anything. In GAML, it is the same if you write:

```
global {
     float step <- 1#sec;

     reflex {
          solve eq step: 1#ms;
     }

}

```

and

```
global {
     float step <- 1;

     reflex {
          solve eq step: 0.001;
     }

}

```

In both cases you obtain 1000 integration steps for one step of the scheduler. What would `cycle_length` bring here ?

**Comment by AlexisDrogoul** [comment]
OK. We have had a discussion with Tri, and we have come to the following conclusion concerning the point number 2 (about the `cycle_length`). This facet will be deprecated. Instead, we will be relying on the unit system of GAMA, *multiplying each parameter by the value of the global `step`* (1.0 by default). There will be 4 possible cases:
- no unit is used anywhere. No specific problem, as the temporal scales are considered as equal.
- units are used to declare the global `step` and the parameters of the equation. They will always scale according to the step of the model.
- the `step` of the model is declared with a unit but not the parameters. We can perhaps detect this case and emit an info on the equation, reminding the modeler to give its parameters units (if necessary). Changing the step of the global model in that way is actually a way to manipulate the previous `cycle_length`.
- same thing if the parameters have units and not the global `step`. 

Does everybody agree ? In that case, we can move on quickly to implement the 4 points and deprecate the previous facets... *And change the models in the model library*

**Comment by AlexisDrogoul** [comment]
Are these enhancements ready ? Do not forget  (1) they need to be documented; (2) the old facets need to be deprecated (and we have to explain why and how to move to the new ones); (3) the examples in the library need to be upgraded to the new facets.

**Comment by hqnghi88** [comment]
Dear Alexis,
I have: 
- Implement the [] to access the list of integrated values (also including the integrated times value). 
- The continous chart which use that syntax [] is work well thanks to Phiippe's enhancement. 
- cycle_length is deprecated by a warning. All the calculation take always 1s as the the time unit
- Example is added to the library

I must have to :
- exlain clearly why and how are the changes , may be on the site or in the documented popup.

I close this issue for the moment. Please feel free to reopen it or create a new issue about ODE.
Cheers.
