### ISSUE TITLE
World attribute "step" causes errors in equation solver

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#1706]
Hello,

giving a value to the attribute "step" introduce an error at each cycle of the agent scheduler. In the following example, it can be seen in the discrete chart that the solution is different when setting a value to "step".

Expected curves:

![original curve](https://cloud.githubusercontent.com/assets/18676913/14813596/b93da118-0ba2-11e6-9f39-3cfae1ca9107.PNG)

Obtained curves:

![wrong curve](https://cloud.githubusercontent.com/assets/18676913/14813621/d0a77874-0ba2-11e6-9352-f72b86a66339.PNG)

On the continuous curve display, it can be seen that the error occurs at every scheduler (cycle: 25 values are shown for each cycle). The model code is attached below.

[example.txt](https://github.com/gama-platform/gama/files/236294/example.txt)

Best regards

**Comment by hqnghi88** [comment]
It relates with #1705 and will be fixed after the normalization of facets.

**Comment by AlexisDrogoul** [comment]
Depends effectively on #1705 for its resolution.

**Comment by hqnghi88** [comment]
Fixed, the unit of step is now take into account with the  integrator's time initial and time final. It rest only the capability of display million of point in the chart. I'm trying to do it.
Cheers.
