### ISSUE TITLE
Hide simulation name in monitors

### ISSUE THREAD

**Issue by CelineLeCoq** [gama-platform/gama#1709]
Hi all, 

I was wondering if it was possible to « hide » the naming of monitors (_Simulation n of model_name_) in the monitors view? It is possible to do it by hand but it’s a little long given the amount of monitors.

![monitor](https://cloud.githubusercontent.com/assets/18263825/14856497/8ce6f35c-0c98-11e6-8763-64b8663c9a18.PNG)

I understand the interest of this fonction, but in our case monitor’s naming is interfering a bit with the readability of monitored variables. 

Cheers, 
Céline

**Comment by AlexisDrogoul** [comment]
I have changed the default policy on output naming by providing a preference (false by default) to append the name of the simulation to that of the output. Does it answer your request ? If so, please close the issue. Cheers
Alexis

**Comment by CelineLeCoq** [comment]
It's perfect !
Thanks a lot, 
Céline
