### ISSUE TITLE
Diffusion light on 2D shapes

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1710]
2D shapes such as squares, rectangles, circles... have only one face, affected by the color in the same way. When the diffusion light is "over" the plan z=0, the shapes (both faces !) will be illuminated, and when the light is "under" the plan z=0, the shapes are obscured (both faces !).
An enhancement would be to differentiate the illumination of the two faces.

**Comment by AlexisDrogoul** [comment]
see #1716
