### ISSUE TITLE
Directional light vs Point light (diffusion light)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1711]
There is currently a big problem of coherence for the diffusion light : it is currently a directional light and not a point light, which means that the light has no position, but only a direction. The direction of this light is equal to the vector from the "position" of the light (through the facet "diffusion_light_pos", which makes no sense as a directional light has no "position") to the origin of the world. That is really counter intuitive, and conceptually wrong. In addition with that, the facet "draw_diffuse_light" will add a shape at the position determined in the facet "diffusion_light_pos", which is also wrong : a real representation of this diffusion light should be a vector, and not a 3D position !

That leads us to 2 solutions : 
- Use Directional light : Keeping the light as a directional light, but changing the facet "diffusion_light_pos" to a facet more explicit, like "diffusion_light_direction". The display of this light (through the facet "draw_diffuse_light") must be a representation of a directional light (a vector), and not a sphere !
- Use Point light : Keeping the current facet and the current representation of the light (through the facet "draw_diffuse_light"), but changing the light to a real point light. We can also add very easily some "gadget" facets such as "diffuse_linear_attenuation" or "diffuse_quadratic_attenuation" to make the illumination changing according to the distance light - object.

What do you thing about that ? ( @agrignard what do you think ? )

**Comment by agrignard** [comment]
Well it makes a long time I did that and It seems that you're a master in this ;-) so feel free to enhance it if needed. Maybe it can be nice to have some comparative screenshot to validate the changes. 

Maybe you are right for the diffuse_light but if you draw a vector it has to be place somewhere right? So there's a position no? 

I think it's hard to understand for user so we should keep it simple but maybe you can try both (point and directional) and we choose the one that look the nicest. The attenuation can be a nice effect also if it's not too hard to implement and not to greedy.

**Comment by AlexisDrogoul** [comment]
I would be in favor of making it even simpler: why dont we have a diffuse_light which is always placed on the camera and always targeting the target of the camera ? So that only the intensity would need to be changed.

**Comment by AlexisDrogoul** [comment]
see #1716
