### ISSUE TITLE
Bad color rendering on complex shape due to diffuse_light and wrong normal computation

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1712]
I don't know if it comes from all the recent changes and discussions made about the diffuse_light but I noticed some strange rendering on GIS file (see attached file). 

I remember we did some change in the way to compute the normal in the last coding camp (January 2016) and as far as I remember it was working. I cannot get the exact commit but it was close to this one: https://github.com/gama-platform/gama/commit/92c00c8be3e402955122b44c4dc611b90ea8c84b

Basically what happens is that it seems that the normal are not well computed (they should be orthogonal to the XY plan) so the color looks a bit different regarding the complexity of the polygon.

This is clearly a big issue as it means that the color you think you are displaying is actually depending on the complexity of the polygon. In the schelling model we should only have yellow or red polygon whereas we have different tone.

Of course the dirty way to fix it is to set manually the diffuse light to 0...

![screen shot 2016-04-29 at 09 53 43](https://cloud.githubusercontent.com/assets/3928502/14918261/dfc4995e-0df0-11e6-8a09-8345cd442761.png)
![screen shot 2016-04-29 at 09 54 34](https://cloud.githubusercontent.com/assets/3928502/14918260/dfc0e4e4-0df0-11e6-864b-cdf5c8ae68d2.png)

**Comment by AlexisDrogoul** [comment]
see #1716
