### ISSUE TITLE
Having a full screen mode rendering

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1714]
I was wondering how hard it is to have real full screen rendering. 
- When you are doing a demo of your model to people that just want to see cool things on screen you don't want to have anything else than your display.
- If you want to project using a beamer you also do not need to see the GAMA Interface

Is it doable? or does it mean we need to launch the display in an other "executable/application"?

For instance in Processing when you run your programm, it opens a new java application and then you can have real fullscreen.

It would be great to have the possibility to add a facet "fullscreen" in a display.

**Comment by AlexisDrogoul** [comment]
It would be technically possible to do this. We would probably need to open the JOGL canvas within a new shell set to fullscreen, in which the control can be directly drawn (instead of being drawn in a composite inside a view). I will try to see if it is feasible (knowing that we would probably need to turn down a number of features -- buttons, overlay, etc. ).

**Comment by AlexisDrogoul** [comment]
To note: you can already detach a view (grab its tab outside the main window) and make it full-screen. It's not like a video-game, but at least you hide all the other views. Given this workaround, I will probably defer doing anything on this issue for now on.

**Comment by AlexisDrogoul** [comment]
Rejoice ! I have been able to implement it without too much difficulty.

The functionality is available in all OpenGL displays. Simply press `ESC` when it has the focus to go back and forth full screen mode. Additionally, displays accept the `fullscreen: true/false` facet (`false` by default). 

Caveats:
- I only tested it on MacOS X (it needs to be tested on all platforms)
- the key shortcuts for running experiments do not work (it seems general -- an issue about this should be written), so it is not practical to start in full screen mode unless you turn on the option of auto-running experiments (maybe we should a facet for this as well).
- the keys sometimes do not answer very well (when the model is running)
- I did not test it with several OpenGL displays running in the background
- I did not test whether opening a new view (e.g. an inspector) works in this mode

Please, in any case, test it first ! ( @agrignard , @mazarsju , @hqnghi88 for the 3 environments).

**Comment by agrignard** [comment]
Great!!! I don't why we did not have it before!! 

Seems ok also with several displays.

BTW:
I have the following error when running the experiment and switching between full and non full screen 

SWTAccessor.<init>: GTK Version: 0.0.0
May  3 10:19:26 dhcp-18-111-18-60.dyn.mit.edu java[789] <Error>: ripc_DrawWindowContents - Cannot acquire window image

**Comment by agrignard** [comment]
For several display as soon as you set on fullscreen mode to true then they can all be switch to fullscreen by pressing esc, which is fine for me. 

After all why not having this behaviour by default for every display? As soon as you press the "magic" key then your are in fullscreen (could be cmd+f for instance (or CMD+CTRL+F as many applications on Mac OS). Maybe not with esc as it may be pressed not by purpose by some user (and it strange to press esc to enter in a full screen mode).

**Comment by agrignard** [comment]
After using it a bit this morning the esc key is perfect to switch to fullscreen mode. I wish I had this before!! 

So I guess the best solution is to add (one more) preference for those like my that want it by default.

**Comment by AlexisDrogoul** [comment]
Regarding the error: on which version of OS X are you running GAMA ? This normally indicates an out-of-memory error of the Mac WindowServer.

Regarding setting it by default, I'm a bit concerned about what it would mean when you have several displays side by side. Will they all go fullscreen ? What would it mean ? 

And I need to fix the fact that the key shortcuts for running / pausing GAMA are not available when running fullscreen. I'll probably add something to the views key listeners to detect when they are in fullscreen mode.

Another issue is the unavailability of the overlay when in fullscreen mode. I've tried several combinations and none is working.

Finally, we need to test it on Windows and Linux.

**Comment by hqnghi88** [comment]
Dear all,
I have test on win10. It works well, i did not have the keys problems.
Cheers.

**Comment by AlexisDrogoul** [comment]
OK. So I propose to close this issue -- I will open more specific ones on the points above.

**Comment by agrignard** [comment]
The setting by default could be when you press "esc" the current display is in fullscreen. This is already how I use it now. I just put on option to true in any of my display and as soon as I want to go to full screen i press "esc". But I agree we could also think about having the N display in fullscreen but that would be another question.

**Comment by agrignard** [comment]
I have a small enhancement request: 
=>Specify on which display we want the fullscreen 

In the case you have several displays (typically one monitor and one projector) I know that in processing for instance you can give a number to specify on which screen you want the screen to be full (see https://processing.org/reference/fullScreen_.html)

It would be great to have something like that e.g fullscreen:2

**Comment by AlexisDrogoul** [comment]
I dont have a dual monitor setup so I can't test it, but you can now enter either a boolean or an int for the `fullscreen` value. `true` or `0` mean the primary monitor, `1` the second one, etc. Tell me if it works.

**Comment by agrignard** [comment]
Awesome!! works like a charm on Mac. I am going to test it in real condition with windows

**Comment by agrignard** [comment]
ok on windows 10 too
