### ISSUE TITLE
ToyModels/Evacuation/models/continuous_move.gaml

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1715]
In this model the camera position is constrained. is it normal or not? 

The idea is cool but the problem is that it's impossible to move in the model and I think we do not see very well what's happenning after due to this

display map type: opengl camera_pos: {world.location.x,-world.shape.height*1.5,70}
                        camera_look_pos:{world.location.x,0,0}    {
		...
}

It's a good idea to have a different view but it should be done in a way that the user can still move in the model. maybe using a facet just for the initialization of the camera position.

**Comment by AlexisDrogoul** [comment]
I've committed a fix for this. Simply passing `nil` to `camera_pos` and `camera_look_pos` allows to have the initial view fixed (at cycle=0) and then to move freely. I had to catch some NPE, though, as the facets were not supposed to receive `nil` values.
