### ISSUE TITLE
add a new geographic object in a SIG via GAMA

### ISSUE THREAD

**Issue by inescarthage** [gama-platform/gama#1717]
Hello, 

I need your help to resolve this question please:
How can I add a new geographic object in an existing layer (imported from a SIG) via GAMA. 

NB: (we tranformed each layer of the SIG into species exemple create building from: shape_file_buildings with: [type::string(read ("NATURE"))]) 

Thank you in advance

**Comment by AlexisDrogoul** [comment]
Hi,

This issue tracker is not exactly the good place to ask this type of question. Please use the gama group instead (https://groups.google.com/forum/#!forum/gama-platform). That said, you can simply create a new agent from this species (i.e. `create building with: [shape:: --your new geometry --];`);
