### ISSUE TITLE
Add an operator that allows to retrieve elements from a list every N elements

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1719]
Unless I'm wrong, there are no operators that allow to write something like this

`[1,2,3,4,5,6,7,8,9,10] every 3` and obtain `[1,4,7,10]`

It would be quite useful in line with #1705 (where the integration values are available as a list of float, from which the modeler will retrieve only a uniform subset every N integration values).

**Comment by sriramab** [comment]
Just a comment. in normal language every 3 could mean (1,2,3), (4,5,6), (7,8,9) , (10) in your example. 
more clearer could be at_every resulting in (3,6,9) or may be (1,4,7,10) depending how u define.
or could be even at_every(start, step). eg., at_every (0,3) will give (3,6,9) or at_every(1,3) will give (1,4,7,10)

srirama

**Comment by AlexisDrogoul** [comment]
Hum... What do you call `normal language` ? :)

If I stick by the definition in English, `every` is quite correct in that meaning, isn't it ? The second meaning would better be expressed by something like `group_by` (except that it is already taken).

**Comment by sriramab** [comment]
Sorry:P 
you are right in general, and not a big deal of difference. Here is the subtleness 

in (normal) english :)
if you say pick every third, (that is what you want to say I think), then `every` comes with an `ordinal` word. which would mean, skip 2 and take the 3rd "in" a container of objects

Now, if you say `every 3`  from a container of objects, that would mean: make a set of every 3 objects in sequence from the container. so 1 set contains 3 objects.

my suggestion was inclined more to other many operators you have with `at`: at_distance, agents_at_distance, neighbors_at, at_location etc.

just a comment, please ignore if it doesn't suit your conventions.

**Comment by RCura** [comment]
If I can make a suggestion here : 
Not sure a dedicated operator would really be that usefull.
*But*, from the languages I know, this would be quite easy expressed using a new operator, like `seq`, or `range`.
Such an operator would have 3 arguments : `from`, `to` and  `step`.
 This would allow to write :  

    list<int> thisrange <- seq(1,10,2);
    range :  [1,3,5,7,9]

This could be combined with an edit of the `at`operator, which would be able to select from a list :

    list<int>mysubset <- [1,2,3,4,5] at [1,2,4];
    mysubset : [2,3,5]

The whole `every` that you want to define could then be expressed with simpler non-dedicated components, like :  

    list<int> rawList <- [1,2,3,4,5,6,7,8,9,10]; // or seq(1,10,1)
    list<int> finalSubset <- rawList at seq(0,length(rawList) - 1,3);
    finalSubset : [1,4,7,10]

This would, _imho_, be usefull to way more of cases, as having to generate a sequence/range is quite common, and currently, I don't see how to do this without a loop.

**Comment by AlexisDrogoul** [comment]
Interesting. I keep your idea of generating sequences. This would actually be quite useful by itself (another dedicated issue, maybe ?). But having a simple and dedicated operator can help regarding the verbosity and therefore the accessibility for modelers (i.e. if you compare having to write `rawList at seq(0,length(rawList) - 1,3)` instead of `rawList every 3`, even if the latter is a shortcut for the more verbose operation and uses it behind the scene).

Regarding the use of multiple indexes by `at`, it is feasible (and normally accepted by the grammar when you write something like `a_container[index1, index2, index3]`, although only the first index is taken into account) but there are some limitations in the parser right now that prevent it to pass one argument if there is only one index and a list when there are several ones (this is necessary to determine the type of the result). I may workaround this one day (although this calls for another dedicated issue, as I'm always nervous to change things in the parser...).

Please post these requests if you are interested :)

**Comment by RCura** [comment]
I'll do that _asap_, hopefully before/while you're at the coding camp :)

**Comment by AlexisDrogoul** [comment]
I've already implemented the `range` operator, which comes in 3 flavors:

`range(end)` produces an increasing (or decreasing, if `end` is negative) range from 0 to `end` with a step of 1 (or -1).
`range(start, end)` produces an increasing (or decreasing, if `end < start`) range from `start` to `end` with a step of 1 (or -1).
`range(start, end, step)` produces an increasing (or decreasing, if `end < start` and `step` is negative) range from 0 to an_int with a step of `step`.
Exceptions are raised if `step` is equal to 0 or if the sign of `step` is not coherent with the direction of the range (e.g. a negative `step` with `end > start`). 

All will return a list of int (possibly a singleton list if `start` and `end` are equal).

**Comment by AlexisDrogoul** [comment]
`every` is now implemented as well. I also added a little syntactic trick, allowing to use the keyword `to` for the second form of `range` (with 2 arguments). 

This allows to define complete ranges using a very friendly syntax:

`list<int> result <- 1 to 10 every 2`

Note, however, that the step provided as an argument to `every` can only be positive, even for lists corresponding to decreasing ranges (actually `every` does not care about the type of the list). 

So, writing `0 to -10 every 2` is equivalent to `range(0,-10,-2)`, because the range operator follows the rule we use for loops (see #1308).

I propose to close this issue now. Feel free to add any new related issues (multi-index, ranges of float, etc.)

**Comment by sriramab** [comment]
every in reflex is accepting a float value. Could this be true? Step can be a float? Not sure it intends to do something specific in its float format that is not documented?

**Comment by AlexisDrogoul** [comment]
Hi Srirama,

there are several `every` operators. You can find their documentation in the application directly (using the top-right search box).

What you are talking about is the variant of `every` that applies to dates. In its single float argument form, it allows to describe a frequency in seconds (as opposed to cycles for its int form), starting from the current date. For instance: 'reflex r when: every(10 #months + 2 #hours) {}`
In its two arguments form, it allows to apply a step to a range of dates, for instance: `loop my_date over: ((#now - 3#months) to #now) every (2#hours + 30#min) {}`

Alexis

**Comment by sriramab** [comment]
Thank you. Now it is clear to me.
