### ISSUE TITLE
The chart won't update without a resize of display , after commit cc79476

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1722]
Try this simple model or any others chart, The display wont update the chart unless we double click the display title to maximize it. Critically, if we check the synchronize in Display Preference, it will block also the update of status beside the charts until a resizing. (winOS, may be related with the fix of "Hovering"?)
model steppb
global
{
	list<int> f2 <- [rnd(20), rnd(20), rnd(20)];
	reflex test
	{
		f2 <- f2 + [rnd(20), rnd(20), rnd(20)];
	}
}

experiment main_test type: gui
{
	output
	{
		display "sSSs"
		{
			chart 'chartcontinuous2' type : series background : rgb('lightGray')
			{
				data "s_mathsc" value : f2 color : # red;
			}
		}
	}
}

**Comment by AlexisDrogoul** [comment]
Works on MacOS X. The "hovering" fix is only installed on Cocoa platforms, anyway. Does it only happen with charts ?

**Comment by AlexisDrogoul** [comment]
OK. Got it, I accidentally removed the call to the fix implemented for #1594 .You can try now and close the issue if it is ok.
