### ISSUE TITLE
Moving certain items from editor to menubar

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1726]
Hi,

I have a very strong feeling that the following items: templates, built in attributes and operators should be moved from the editor interface to the main menubar at the top. I personally feel that the current positions are less intuitive for a new user and a medium level user. For advanced users, I wonder if they even ever use this menu?

Just my feeling and feedback after using it for a year and after introducing it to few students. 
That is why I gave it a low priority ☺️ 

Srirama

**Comment by sriramab** [comment]
Also within these menus, an example is the do statement, create statement, ask statement: there are a lot of create statements, couple of do statements, couple of ask statements. And unless you click one of them, it is not clear what they mean. Once clicked, and the snippet appears in the code, you feel that it is not the one you want, you have to edit it or delete it and go back to the menu again and try the next one. 

Could it be possible to already have an indication _on the menu_ for example: do without arguments, do with arguments. Similarly, with create: create with number, create with return, create with from

regards,
Srirama

**Comment by AlexisDrogoul** [comment]
Moving the menus up is not as easy as it could seem. They are quite tightly coupled with their editor, and it would mean of refactoring of what exists now (we would also probably lose some functionalities, which are possible to implement in sub-menus but more difficult in the main one -- not speaking of the recurring problems we have on Ubuntu with this main menu). But why not if it improves their access for modelers.

Regarding the names, you might have noticed that same are a bit more explicit than others. It is because templates are taken both from a hand-made internal database and from the documentation -- where the different usages do not have a specific name. It is probably something we should improve.

**Comment by sriramab** [comment]
I understand and I thought as much. I have a gentle suggestion/ solution for GAMA team to consider. 

Firstly, The difference is small. You can make user  feel  intuitive or making user feel inquisitive (curious).  For the buttons on the editor bar, I feel they make user curious. `hey look, there is a button, I dont know what it is, let me check`. This is because, the symbols/ icons used are uncommon. 

Now imagine, if the button read `templates` instead of icon, then user is: ` hey wow, how nice, they also have templates, let me click to see which template they have` . Yes, when mouse is hovered one can read =templates=, but this somehow does not trigger the intuition. 

Again, there could have been a higher level decision to have icons as buttons than to have textual buttons. So I have nothing to say there :) 

Secondly, I feel, irrespective of text or icon, the real estate given to each button is too little. for me atleast, i need to control the mouse carefully, especially because hitting the icon itself does not do anything, I have to carefully point to the small `tiny` arrow to drop the list. Could you perhaps make the list to drop even if someone clicks on the icon? if not, may be increase the width of the button. 

Thirdly, on a serious note, my current colleague and another one I had many years ago, are color blind. So may be use of color in the editor bar could be reduced? Or may be you could have some settings and options to let all colors go in grayscale. This is something to investigate. 

Although, all the issues here are low priority, but I feel they are important. 

regards,
Srirama

**Comment by AlexisDrogoul** [comment]
Just a quick sidenote about color blindness. OSes almost handle this situation so it is probably something we will not take into account in GAMA. See for instance how to pass MacOS X in grayscale globally: http://apple.stackexchange.com/questions/136063/force-mac-to-display-in-grayscale, or Windows (sort of): http://www.thewindowsclub.com/high-contrast-themes-windows.

**Comment by AlexisDrogoul** [comment]
Implemented with the latest commit. See also https://groups.google.com/forum/#!topic/gama-dev/NJKdU-nhBCk
