### ISSUE TITLE
How to improve the lag of the editor with large files ? 

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1728]
When editing large files (one example I tested was ~3000 lines long) a lag in the editor is quite noticeable after each edit. Several processes, some of them in the background, some of them requiring a lock on the document, are active when editing files:
1) reconciler : (lexing, linking and scoping) verifies that what is entered is syntactically correct and emits a first batch of warnings and errors. Needs a lock on the document.
2) validation & documentation: semantic validation, the one that produces the "green buttons" (or not) and emits other warnings, errors and associates online docs with words in the text. No lock necessary.
3) highlighting: produces (using a different lexical analysis) the coloring of the text. Needs a lock.
4) spelling: if enabled, checks the spelling of words in comments. No lock.
5) outlining: if the outline is opened, synchronizes the structure of the model with its outline. Needs a lock.
6) content assisting: verifies what is typed and checks that some special characters are not entered (the `.`, for instance, which triggers a menu of proposals). Needs a lock (not always).

That's a lot (and it's amazing to see how many messages are produced every time a key is typed !).

Recent commits have reduced the global time needed by (1) dividing the validation time by almost 3 (from 200ms to 60ms on the example file); (2) moving the documentation to another process; (3) reducing the highlighting computation by ⅓. It improves a bit the experience, but not that much, as the two first processes did not need to lock the document (so the user can continue typing while they are active -- actually they are usually cancelled quickly) and the third was already fast.

Manual improvements include of course turning off spelling and outlining (an on-demand outline is available in the menu bar of each editor, so the outline view is not necessary).

But the question of how to improve "locking" processes is not answered with these improvements, and inspecting the time spent on each method, it is easy to see that most of the time is spent on the parser (produced by XText + AntLR) and on the linking process (customized for GAML). The second one has already been heavily optimized, with almost every caching technique used. Difficult to do better. The first one is then where we should head our efforts: however; the problem is that it is completely dependent on the complexity of the grammar (the parser is automatically produced by the grammar).

So the whole issue of the editor "lagging" a bit when editing large files is ultimately a problem of parsing large texts using a complex grammar. One solution is of course to split these texts, but I guess we will have, at one point, to simplify and rationalize the grammar of GAML (which contains the support of outdated structures and does not employ the novelties introduced by Xtext 2.8 and 2.9), which also mean s simplifying and rationalizing the language itself. 

Do we need 3 different ways to pass arguments to actions/functions/operators ? 
Do we need to keep a compatibility with `environment`, `entities`, etc. ? 
Do we need 2 ways to declare vars (`var aaa type: int` or `int aaa`) ? 
Do we need to keep both the `set` statement and its `<-` equivalent ? 
... etc....

There are decisions to take on how we would like to simplify the language, keeping in mind that, ultimately, having a simpler language not only benefits the parser but also the modelers (wrt the learning process and the user experience when editing models). 

Any thoughts on this ? 

Cheers

PS: not to mention that having a simpler grammar also would make the code a bit less error-prone and would probably allow to share the same underpinnings with the graphical editor...

**Comment by hqnghi88** [comment]
Dear Alexis,
I don't have any details idea on how to improve 6 processes. But in general, I am support for the eliminate the outdated syntax and simplify the grammar. As far as I know, there are nowadays some body who still using the outdated syntax, the reason is "It still work, I don't need to change". Instead of supporting the outdated, I prefer to make a red marks and tell the modelers how to corrected it. So,
- 1 ways to pass arguments.
- red marks and shows how to declare environment, and "don't need an entities"?
- ...
Sorry for the inconvenient if the red marks is a nightmare.
Cheers.

**Comment by ptaillandier** [comment]
Hi Alexis,

I agree with Nghi, I think we should remove outdated syntax. This will be a
good way to be sure that the models provided with GAMA in the model library
are all clean ;) .

Do we need 3 different ways to pass arguments to
actions/functions/operators ? I don't know.... for some operators, I like
to use "operand1 op operand2" ("1 + 2"), for others, I prefer to use
"op(operand1, operand2)". For actions, it is the same, I often use
"my_action(arg1, ag2)" when I have defined myself the action, and
"my_action facet1:arg1 facet2: arg2" when I using a skill's action (i.e.
moving).
Do we need to keep a compatibility with environment, entities, etc. ? Wa
can remove these very old keywords
Do we need 2 ways to declare vars (var aaa type: int or int aaa) ? Wa
can only use only "int aaa"
Do we need to keep both the set statement and its <- equivalent ?  : We can
use only "<-"


Cheers,

Patrick

2016-05-09 18:27 GMT+02:00 hqnghi88 <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
OK. I'm progressively moving towards a more simplified version of the grammar in my local version. Which allows me to chase the `old` structures still employed in the Library.

Other proposals of simplification:

- removal of `const`, `var`, `set`, `signal`, `let` (variable definitions)
- removal of the possibility to have a first facet or not (example `species name: a` / `species a`, or `return value: 10` / `return 10`). For the statements that allow this for the moment, only the second form will be kept.
- removal of the `function:`/`->` facet. It has actually very little interest since we can use actions with a return value in expressions. This is an important change for those who use it, but it would simplify a lot the grammar (regarding the parsing of blocks). For instance:

```
    int a -> {rnd(10)};
    ...

   write a;
```

would turn into:

```
    int a { return rnd(10);}
    ...

    write a();
```

Potentially dangerous, however, as `write a` in the second example would write the reference to action `a` (and not its result !). 

Regarding parameters to functions/actions/primitives, I agree with Patrick and think we should keep only two ways to do it:
- not named (follows the order of the parameters of the action): `do a(p1,p2,p3)`
- named: `do a n2: p2 n3: p3`

**Comment by AlexisDrogoul** [comment]
I've turned off by default another process (I had been overlooking), which heavily relies on reconciliation: the folding of code structures. It can be turned on again on an editor basis with the small icon on the left hand. It should (again) decrease the lagging. Can you test it ?

**Comment by AlexisDrogoul** [comment]
Finally, adding the new "pragma" instructions (`@no_info` & 
`@no_warning`) can also help in reducing the overhead everytime you type something. 

With all of these tweaks and options, the ~4000 lines file is clearly much more responsive and lags, although perceptible sometimes, are much less frequent. 

Can you confirm this ?

**Comment by hqnghi88** [comment]
Hi all,
I dont have a "2000+ lines" model. The most complicated i have is the model of Viet, with several imports (20+) so in memory it seem to have a long model. I confirm that It works well with no lags

**Comment by AlexisDrogoul** [comment]
Although things are not perfect (but perfection is difficult to reach !), I think, from the tests I have conducted, that the edition of large files (> 2000 lines, the same "threshold'' than in Eclipse) has considerably improved with the various enhancements introduced in the latest commits and referenced here. In my opinion, there is nothing more we can do for GAMA 1.7 -- as we won't take the risk of completely changing the grammar. I then close this issue (but we should open a new one on the rationalization of the grammar).

**Comment by AlexisDrogoul** [comment]
Just to mention that the improvements introduced for #1738 also clearly help in the handling of these large files, both in terms of memory and speed. When profiling the edition of one of these files, the validation now only represents 30% of the total load. The remaining is taken by StyledTextRenderer...
