### ISSUE TITLE
Errors installing 1.7 beta on Mac OS/X

### ISSUE THREAD

**Issue by kduhaime** [gama-platform/gama#1732]
I am repeatedly getting errors trying to install version 1.7 beta on my Mac.  It seems the zip file I download is corrupt, but I have tried ti several times now.  Is there an alternate site to download it from?

**Comment by AlexisDrogoul** [comment]
Hi,

Can you explain which error you have ? 

Alexis

**Comment by kduhaime** [comment]
Alexis, when I unzip the download and run GAMA 1.7 app, I get an error telling me to go to an Eclipse log file, but for starters, I cannot find the file within the file system.  I've tried unzipping the package in Windows 7 as well and it indicates a problem with java jar file too.

**Comment by AlexisDrogoul** [comment]
Hi,

Sorry to insist, but a proper bug report should at least include some details about what is happening: the text of the error, a screenshot, anything that can help us to go beyond "I've got an error".

Thanks
Alexis

**Comment by AlexisDrogoul** [comment]
I will close this issue in the absence of more information. Alternatively, you can refer to this page: https://github.com/gama-platform/gama/wiki/InstallingGitVersion and to this page: https://github.com/gama-platform/gama/wiki/CreatingAReleaseOfGama to produce yourself a release of GAMA 1.7. 

Please reopen if you have more information to share.

**Comment by kduhaime** [comment]
Thanks Alexis!

I am going to try downloading it again and installing clean.  I am not sure why it is doing what it is.  Certainly more challenging than the 1.6.1 installation which was very easy.

Keith

______________________________________
Keith Duhaime M.Agr.
Ph.D. Candidate
School of Engineering
UBC- Okanagan

tel. (250) 215-6240
________________________________

**Comment by AlexisDrogoul** [comment]
We are still in a beta version, which might explain the problems you have -- the release will be (if everything goes well) even easier to install.

**Comment by kduhaime** [comment]
Alexis,

I have attached the log file it creates when I try to run it.

Keith

______________________________________
Keith Duhaime M.Agr.
Ph.D. Candidate
School of Engineering
UBC- Okanagan

tel. (250) 215-6240
________________________________

**Comment by AlexisDrogoul** [comment]
Sorry, nothing seems to be attached (neither to the mail nor to the issue).

**Comment by kduhaime** [comment]
It is showing here as attached to this email.  Do you have an alternate email address?

Keith

______________________________________
Keith Duhaime M.Agr.
Ph.D. Candidate
School of Engineering
UBC- Okanagan

tel. (250) 215-6240
________________________________

**Comment by AlexisDrogoul** [comment]
Hi, I post an answer here so that others may benefit from it. Your problem came from not having Java 1.7 installed. It is perfectly feasible to install both Java 1.6 (from Apple, necessary for GAMA 1.6.1) and Java 1.7 (from Oracle) on the same machine. The two versions of GAMA should manage which version they have to use by themselves.

**Comment by kduhaime** [comment]
Alexis, I installed Java version 8 from the Oracle website.  It still does not function.

**Comment by sriramab** [comment]
You have to change your default java on your Mac. Please google " how to
change default java to version 8 on Mac OS X"


Srirama
