### ISSUE TITLE
update the mac os doc for the java installation

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1733]
In this doc https://github.com/gama-platform/gama/wiki/InstallingGitVersion

we should add a line that explain how to install java

**Comment by AlexisDrogoul** [comment]
This issue does not really belong here,  but to the doc. In addition,  it
may be usefuk to update it for users,  ie indicate that java 17 or 18 need
to be instaled. But I doubt it would bring anything interesting for
developers, since it is required to run eclipse...

**Comment by AlexisDrogoul** [comment]
I guess the best is that you edit the corresponding wiki pages,  where you
have spotted inconsistencies,  with a link to Oracle download page.

**Comment by agrignard** [comment]
done
