### ISSUE TITLE
Java 2D screen are should be activated manually on ubuntu

### ISSUE THREAD

**Issue by romainreuillon** [gama-platform/gama#1734]
On Ubuntu 16.04 on ant charts example:
![capture du 2016-05-16 06-39-09](https://cloud.githubusercontent.com/assets/1270995/15280471/fe5d0ad4-1b30-11e6-879d-1d0b99c80c5d.png)

**Comment by AlexisDrogoul** [comment]
This issue should be addressed now. We might want to test it later on the second release of the day...
