### ISSUE TITLE
Memory retained when correcting/editing lot of files

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1738]
Correcting the MAELIA model, I had to open and edit one by one files.
After 15 to 20 files, the memory used is about 1900 of 2000 M.
Waiting for 2 to 5 minutes, the memory decreases to 1300 of 2000M.

When I close all the files and click on the trash button I get 250 M of 2000M.

**Comment by AlexisDrogoul** [comment]
I will probably need to profile it... Give me MAELIA :)

**Comment by AlexisDrogoul** [comment]
The question of the memory used and retained is linked to many different things, including the construction of caches by both XText and GAMA itself (symbol caches, documentation caches, resources caches...). Have you been able to profile memory before and after the opening of these files to see what is exactly retained ? We might be able to trash some caches sometimes.. .
