### ISSUE TITLE
Import archive does not maintain folder structure

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1740]
Hi, 

Export a project as archive. Now, try to import this same archive. 

You will asked for a folder to import to, while you have already selected your usermodels and right clicked to import this archive. Now, you cannot import unless you have an already existing project folder (this I think is already improper). Now, lets say, you already create a project folder, right click the project folder and import an archive 'into' this folder. You will see that with a project structure in place, the archive file is imported as a extra folder (name same as archive name) and this folder has its own gama project structure. This creates confusion !!

May be two possible ways:

1. in Model explorer, there should be 'new> folder' along with 'new > gama project'  
a) when you have a new folder: the imported archive creates a project with its name same as archive file.
b) when you have a new gama project: the imported archive creates a project with its name replaced by name of new gama project.

I think 1a is easier to implement?

srirama

**Comment by AlexisDrogoul** [comment]
There is a confusion, I guess, between "Import existing projects" (which lets you choose between reading them from disk or from archives, and which works well AFAIK) and Import from archive or filesystem. When you want to import a project, the first one should be chosen. When you want to import some resource **into** an existing project, you choose the second or third one -- that is why a folder is asked.
 i've made the text in the toolbar more explicit -- but I can't do anything for the popup menu.

**Comment by sriramab** [comment]
I will show you later.
