### ISSUE TITLE
exporting preferences to share with others 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1742]
Hi,

I think it would be nice to export a working preferences configuration to another user to that the simulations run in very similar `preferenced` GAMA

Srirama

**Comment by AlexisDrogoul** [comment]
I have committed the possibility to import and export preferences. It needs to be tested, however, between two machines (importing remote preferences will remove the selection of the "remembered" workspace, which is stored along the preferences of GAMA, forcing the user to reselect it in its environment. It is a minor annoyance, but there is not a lot of things I can do about this).
