### ISSUE TITLE
templates window can have insert button

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1743]
Hi,

In the editor I see there is a template button. When you click this button (no the drop down arrow), a small window opens. In this window, one can write own templates and save them. However, I think adding a insert button in this window could be useful. Otherwise, user has to create a template in this window, close it. Go to editor, click the drop down arrow and then insert it into the code, and user has to do  four or more extra clicks.

**Comment by AlexisDrogoul** [comment]
Actually, the purpose of this window is exactly the contrary of what you are describing :)

Select some text in the code, click on template, and the text will be used as a basis for creating a new template. 

So... No insert button, I guess !

**Comment by sriramab** [comment]
Clear
