### ISSUE TITLE
add a shortcut to search box 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1744]
Hi

The editor has a search box (blue background). But one has to reach it with a mouse, and it is quicker to hit CTRL+F and type quickly. May be a shortcut should be assigned to this search box within the editor, else it seems a bit redundant and it also claims premium and central real estate on the editor that can possibly be used for some other new buttons? or increase size of other existing buttons?

**Comment by AlexisDrogoul** [comment]
Implemented with the latest commit (CTRL-G or CMD-G)
