### ISSUE TITLE
Search Through Model Names

### ISSUE THREAD

**Issue by jdzucker** [gama-platform/gama#1748]
A very tiny enhancement would be to enable search in through the model "names".

**Comment by AlexisDrogoul** [comment]
This function is already present in the contextual menu of the navigator. See below:

![modeling - kdfj models new gaml - gama 2016-05-17 23-11-26](https://cloud.githubusercontent.com/assets/579256/15329952/e2aa6e30-1c84-11e6-803f-507f89f4eb5e.png)
