### ISSUE TITLE
Model Multi Simulation does not work anymore

### ISSUE THREAD

**Issue by jdzucker** [gama-platform/gama#1749]
Only one simulation is created although the code specifies 
	//we create a second simulation (the first simulation is always created by default) with the given parameters
		create simulation with: [nb_agents:: 5, agent_speed:: 3.0, agent_color:: #red];
		create simulation with: [nb_agents:: 15, agent_speed:: 6.0, agent_color:: #green];

Patrick is the author and said it used to work.

**Comment by AlexisDrogoul** [comment]
It works well on my computer. Does anyone also have this problem ?

**Comment by hqnghi88** [comment]
Hi, 
On my neon, only one "map" display is created. Is it supposed to have 3 in this case?

**Comment by hqnghi88** [comment]
Hi,
This issue come from two facts:
- the display must be unique, 2+ displays of same name is not allow.
- in the multi-simulation, the displays in added simulations will be separated with the original by the string "Simulation xxx". It have change from hard code, to a preference option. So if you go into the preference, Presentation tab, and switch true the "Append the name  of the simulation to the title", it will create the displays of multi-simulation.

Btw, this preference come from the requirement of users, to hide this prefix in the Monitors, but they didn't complain about the title of diplays, so i change the code to "the title of displays permanently have this prefix"
