### ISSUE TITLE
Having a console to test out GAML by interpreting it.

### ISSUE THREAD

**Issue by jdzucker** [gama-platform/gama#1753]
This would be particularly handy to test out Global and Species... Let us dream.

**Comment by AlexisDrogoul** [comment]
I've committed the first version of this console. Still a lot of work to do on it, but I close this issue to let others post more focused issues. In particular, we need to improve:
- [ ] the interaction between the output and the input
- [ ] the positioning of the caret (always wrong)
- [ ] the possibility to have a different "listener" agent
- [ ] the possibility to have consoles with different "listener" agents
