### ISSUE TITLE
Layers with 'refresh: false' create memory leaks

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1754]
Hello,
Open the model Toy\Traffic\Simple traffic  ( or an model that take more than 1GB in simulation)
- Run for around 700 steps
- Click pause button
- then right click to any object.
GAMA will be slow. The right click windows does not appear.

Cheers,

QUang

-- 
On eclipse

**Comment by AlexisDrogoul** [comment]
Can you try again with the latest commits ?

**Comment by agrignard** [comment]
Note:
It does not happen if you remove refresh:false

**Comment by tcquang** [comment]
You are right! It is Ok now!
Thank you,  agrinard!
Quang
