### ISSUE TITLE
GAML: hiding all comments at once

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1758]
Hi,

It is possible to hide all comments in gaml file `at once`? I would like to request this feature. For not so advanced users like me, we write lot of comments and we do lot of trials to get things done. Sometimes there are more than one ways to write a code block. In this sense we would like to hide non-working code blocks as comments, but in a long file, these can be many. So if there is anyway to hide all comments at once, that would be great.

Srirama

**Comment by sriramab** [comment]
It is possible in Eclipse editor, see here 
http://stackoverflow.com/questions/21968768/how-to-fold-comments-in-eclipse 

may be some minor tweak makes it possible also for GAML?

**Comment by AlexisDrogoul** [comment]
You can now ctrl+click on the left-side ruler, and, in the `Folding` submenu, you will find the `Collapse Comments` action.
