### ISSUE TITLE
Add a parameter for the percentage of the brighter operator

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#176]
**Is your request related to a problem? Please describe.**
Contrary to the [darker](https://gama-platform.org/wiki/OperatorsDH#darker) operator, the [brighter](https://gama-platform.org/wiki/OperatorsBC#brighter) one doesn't have a second parameter to set the percentage of change.

**Comment by AlexisDrogoul** [comment]
This should be fixed with https://github.com/gama-platform/gama/commit/00c7b27f54e568ad75910fa827ad8126f31ab284. Please test !
