### ISSUE TITLE
Right click on an action name to go to its definition does not work when a variable with the same name exists

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1761]
In the following model, when I cmd+click on the globalVariable name (aiming at going to the action definition), the editor highlight the variable definition.

global {
	int globalVariable;
	init {
		do globalVariable();
	}
	
	action globalVariable {}
}

**Comment by AlexisDrogoul** [comment]
Duplicate (sort of) of gama-platform/gama2#46 .
