### ISSUE TITLE
Dead function issue.

### ISSUE THREAD

**Issue by kust2708** [gama-platform/gama#1767]
Hello!

After some experimentations I noticed than the dead() function doesn't works properly.

I'm using the last GIT version on Linux with the Oracle's JDK.

Example :

```
model die

global {
	
	int cpt <- 0;
	 
	species a {
		
		reflex die {
			if(flip(0.1))
			{
				write("N°"+cpt+" Die.");
				cpt <- cpt + 1;
				do die;
			}
		}
	}
	
	species b {
		
		list<a> list_of_a; 
		
		reflex check {
			write("Check : Begin");
			write("Current list : "+self.list_of_a);
			ask list_of_a
			{
				if(dead(self)) // return always false
				{
					write("Remove an 'a' from the list");
					remove self from: myself.list_of_a;
				}
			}
			write("Check : End");
		}
		
		init
		{
			ask a
			{
				add self to: myself.list_of_a;
			}
		}
		
	}
	
	init
	{
		create a number: 10;
		create b number: 1;
	}

}

experiment TestDeadFunction type: gui {
	output {
	}
}
```

**Comment by AlexisDrogoul** [comment]
Hi,

Its complicated because a dead agent is not supposed to behave anymore… I have not checked, but I think they are filtered out from calls like ‘ask’, etc. Moreover, in your case, you want it to write something and then remove itself from a list. 

Maybe you can try another approach:

       reflex check {
           write("Check : Begin");
           write("Current list : "+self.list_of_a);
           loop my_agent over: list_of_a
           {
               if(dead(my_agent)) 
               {
                   write("Remove an 'a' from the list");
                   remove my_agent from: list_of_a;
               }
           }
           write("Check : End");
       }

I havent tested it, though. 

Cheers
Alexis

**Comment by AlexisDrogoul** [comment]
I close this issue (which is not really one, basically, as explained above)
