### ISSUE TITLE
network Skill: MQQT problem with Fetch

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1768]
In the following model it seems that the fetch method is not doing exactly what it is suppose to do.

It returns a map:
ping fetch this message: map(['from'::'ping','content'::'This message is sent by pong to ping'])
whereas it should returns this:
ping fetch this message: map(['from'::'pong','content'::'This message is sent by pong to ping'])

the from is not the right one

Run this model:

model MQQT_HelloWorld

global {	
	list<string> clients <-["ping","pong"];
	init
	{
		create NetworkingAgent number:1{
			name <-clients[0];
			dest <- clients[1];
			do connect to:"localhost" with_name:name;
		}
		create NetworkingAgent number:1{
		    name <-clients[1];
		    dest <- clients[0];
			do connect to:"localhost" with_name:name;
			do send_message to:dest content:"This message is sent by " + name + " to " + dest;
		}
	}
}

species NetworkingAgent skills:[network]{
	string name;
	string dest;
	reflex fetch when:has_received_message()
	{	
		map mess <- fetch_message();
		write name + " fecth this message: " + mess;	
	}
	reflex send
	{
		do send_message to:dest content:"This message is sent by " + name + "to " + dest;
	}
}

experiment testdd type: gui {
	output {
	}
}

**Comment by AlexisDrogoul** [comment]
Why dont you use the standard `message` type defined in the FIPA plugin ? This would provide a uniform way of describing messages exchanged between agents, notwithstanding the fact that it is already a complete type, etc. Maybe a bit of adaptation is necessary, but it would be much less error prone than a map (with no possibility of online validation).
