### ISSUE TITLE
Ambient light set to zero

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1769]
The ambient_light is now set to zero (to try to have the same rendering in opengl and java) but most of this model look now like blade runner so we must reset it to something like 125 by default.

**Comment by AlexisDrogoul** [comment]
Which model ?

**Comment by AlexisDrogoul** [comment]
Two comments on this:

1) It might be a good idea to propose a default ambient light that can be changed in the preferences or elsewhere

2) Maybe the problem can be solved by stating that, by default, when nothing is specified, the diffuse light is fixed on the camera and not in the 0,0,0 corner. 

Would it be possible to test the second one first ? @mazarsju

**Comment by mazarsju** [comment]
I tested to put the light in the position of the camera, it's not so bad, but it's a bit tricky with the zoom...

Anyway, I changed the ambient light to 127, and the diffuse light to 127, now the 3D is not so bad, and the colors are very similar to the java2D display. I think I'll keep it this way by default, if you have nothing against it. I close this issue, but feel free to reopen it if you are not satisfied !
