### ISSUE TITLE
Latest release - GAMA 1.7

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1770]
Hello,
When I launched the latest release on my Windows system 64bit, the experiment buttons are not appear in the Editor.
Here are the log files received in the cmd mode.
Cheers,

Quang
[err.txt](https://github.com/gama-platform/gama/files/269620/err.txt)
[std.txt](https://github.com/gama-platform/gama/files/269619/std.txt)

**Comment by AlexisDrogoul** [comment]
Hi,
Now that we have an integrated build system, thanks to:

1) Give an informative title (about the contents of the issue)
2) Provide the number of the release (or the tag) when it concerns a release.

Cheers
Alexis

**Comment by reyman** [comment]
We probably also can create two new tags : 
- concern mvn compilation
- concern latest dev release
