### ISSUE TITLE
Problem of memory of co-models using SimpleBDI component

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1774]
Hello,
When I have launched an experiment of my co-model several times,  the memory have been increased, it seems do not have enough memory to launch the graphical of the  simulation.
Thank you!
Quang
![memory_comodel](https://cloud.githubusercontent.com/assets/11825516/15369048/0bfb9d28-1d5b-11e6-9979-1d95df82351d.png)

**Comment by AlexisDrogoul** [comment]
Although it would be better to test this in real conditions (i.e. with an example), can you try the same without opening any display in the experiment and see if you observe the same behavior ? Are your displays OpenGL displays ? Do they have some layers with `refresh: false` ? That might be related to #1754 in that case.

**Comment by AlexisDrogoul** [comment]
Hi, is this issue solved ?

**Comment by hqnghi88** [comment]
Dear Alexis,
It didnt solved. I couldn't found the root cause.

**Comment by AlexisDrogoul** [comment]
As I understand it, there is a memory leak in the simple_bdi addition. Probably related to the fact that some of the statements are not stateless (or maybe they are not correctly releasing their links). I put @mathieuBourgais in copy of this one.

**Comment by ptaillandier** [comment]
Is it possible to have your model to test it?

**Comment by hqnghi88** [comment]
Dear Patrick,
The override of clearBehaviors() have fixed this issue on my pc.

**Comment by hqnghi88** [comment]
Sorry, my mistake, the memory still not go down.

**Comment by AlexisDrogoul** [comment]
So it is probably necessary to profile this model to understand which object still keep handles on the simulations, etc. after they're supposed to have been removed. @ptaillandier seems to say that removing the simple_bdi component does not change the increase in memory.

**Comment by hqnghi88** [comment]
Yes, I am profiling. Thanks for all your helps.
Cheers.

**Comment by hqnghi88** [comment]
Dear all, 
I have push 2 fix that eliminate the leaks. As my profiler shown, it related with the Argument which contains SimpleBDI Predicate (in MinimalAgent), and GamaShape in SimulationAgent. I have override dispose method in these two but it seems not a clean solutions. Please take time to give me guides about the clean one.
Cheers.

**Comment by tcquang** [comment]
Dear all,
I just get the new version git, the memory of the BDI model are well released. 
Thank you very much!
Cheers
PS: But in the batch mode (batch and exploration) the memory are still increasing
Quang
