### ISSUE TITLE
Comodeling: Calling action of sub-model does not work.

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1775]
Hello,
I am using the co-model.
In the sub model, I have an action "a" that uses the global variable of the sub model,
In the Comodel, when I call the action "a" in sub-model , it shows an error that there are no data in the variable of the action "a". But it work well when I launched my sub-model alone.

Cheers,
Quang

**Comment by AlexisDrogoul** [comment]
Can you produce a simple test model ? It is a bit difficult to follow from your description (although it might be that a "global variable" is registered as a "GlobalVariableExpression" and, as such, is searched in the main simulation (not in the simulation of the sub-model).

**Comment by tcquang** [comment]
Please try the following models:
1. The result of the sub-model: M1, var1:17
2. The result of the co-model : M1, var1:null
Thank you!



model model1

global {
	/** Insert the global definitions, variables and actions here */
	int var1 <-0;
	init {
		create specieA;
	}
	reflex M1_do{	
		var1 <- var1+1;	 
	}
	action calculate{
		var1 <- var1+10;	
		write "M1, var1:"  +var1;
	}

	reflex stop{
		if  (cycle = 6) {				// check every 6 cycles
			do calculate;
			do pause;	
		} 	
	}
	
}
species specieA{
	
	
}
experiment model1_exp type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
		display sim1{
			species specieA;
		}
			
	}
}
________________________________
The Co-model
model comodel
import "model1.gaml" as M1				
global {
	/** Insert the global definitions, variables and actions here */
	init {
		create M1.model1_exp;
		ask M1.model1_exp[0].simulation {
			loop times:1 {do _step_;}
		}
	}
	reflex stopSim{
		if  (cycle = 6) {		// check every 6 cycles
			ask M1.model1_exp[0].simulation {
				do calculate;	
			}
			do pause;
			  
		} 	
	}
}

experiment comodel type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
	}
}

**Comment by tcquang** [comment]
It works well,
Thank you!

2016-05-23 13:32 GMT+07:00 hqnghi88 <notifications@github.com>:

> Closed #1775 <https://github.com/gama-platform/gama/issues/1775> via
> eb10c94
> <https://github.com/gama-platform/gama/commit/eb10c94cd2d2a0c7a00a88bf0c61b3a60c4196e6>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gama-platform/gama/issues/1775#event-668528414>
>



-- 
Quang Chi TRUONG
Tel: 0939388153
