### ISSUE TITLE
Add a "search/Spotlight" tool in the operator menu

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1781]
In the editing mode, the operator menu (f(x)) is very useful and it would be even better if the user could do a research by entering a text.

E.g: I want to see all the operator that start with "neigh" and then it apply this filter and get all iterator containing the string "neigh" (a kind of spotlight)

**Comment by sriramab** [comment]
yes,  i agree. This is already possible on the new gama website, but would be nice to have it within editor.

**Comment by sriramab** [comment]
And how to use the search tool? :)

**Comment by AlexisDrogoul** [comment]
It's now a GAMA-wide search tool available in the top right corner of the window.

**Comment by sriramab** [comment]
Thank you. Last question and comment: Is there an assigned shortcut? could you please make it slightly wider. Thanks again. This helps a lot.

**Comment by AlexisDrogoul** [comment]
Last commit enlarges it a bit, adds a global shortcut (SHIFT+CTRL+H / SHIFT+CMD+H) and allows to act the shortcut to take into account the currently selected text in the editor (if any).
