### ISSUE TITLE
operator with skewness and kurtosis 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1782]
As discussed, Would like to request an operator to be able to generate random numbers from a skewed distribution and with a kurtosis value. 

thank you

**Comment by AlexisDrogoul** [comment]
Any idea of a possible syntax for this operator ?

**Comment by sriramab** [comment]
Yes, 

Here a R [library](https://cran.r-project.org/web/packages/sn/index.html) 
Here a Matlab [library](http://nl.mathworks.com/help/stats/pearsrnd.html?requestedDomain=www.mathworks.com) 
Here some [excel](http://www.mrexcel.com/forum/excel-questions/477702-generating-skewed-normal-distribution-random-numbers.html) tweaks 

thank you

**Comment by ptaillandier** [comment]
Could you be a bit more specific: how do you want to use these operators in GAML? :)

**Comment by sriramab** [comment]
I usually assign random values to agents with uniform or normal distribution. I would like to be able to assign values, where many agents fall within a short range of values, and few over a long range of values, like right skewed or left skewed. Kurtosis on the other hand is to control the value being assigned to these agents. I use more skewness than kurtosis. But usually they go together and may be easier to implement for you.

**Comment by ptaillandier** [comment]
Ok, I added two new operators - kurtosis(data) and skewness(data) - but I have no idea if it corresponds to your need (it is the kurtosis and skewness methods proposed by Apache).
I also added a new feature model in the statistic folder called Statistic Operators that shows  how to use them.

**Comment by sriramab** [comment]
Its actually the other way around. I would give the skewness, kurtosis, mean, sd and need to get a list of numbers.

**Comment by ptaillandier** [comment]
Ok (but at least, we have now two new operators :) )
Unfortunately, there is no method in Apache Math to build such skew distributions... we will have either to use another library or to implement by ourself the algorithm..... it will require more time (if you have somewhere an algorithm for that, it can help).

**Comment by sriramab** [comment]
I will look for libraries, I know there is a johnson distribution which allows this, can't find it right now. But I use this R package, may be this gives u some leads?
http://azzalini.stat.unipd.it/SN/

thank you.
