### ISSUE TITLE
fullscreen when 2 gama are open

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1783]
Open 2 GAMA
Put one of them in full screen

=> It's impossible to leave the fullscreen mode

**Comment by AlexisDrogoul** [comment]
I reversed the previous commit as it does not change anything. This "bug" will need to be tested with two releases of GAMA, however, as two instances launched from the same Eclipse probably share some resources, etc. What I did instead is to enable two fullscreen modes: one with the menu bar visible, one without, the latter being "modal", i.e. blocking most interactions with other applications.
