### ISSUE TITLE
Cannot save the result of intersection to a shapfile.

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1784]
Hello,
I am doing an intersection between 2 layers in GAMA, It works well, but I can't save the agents to the shapefile.

Thank you!
Quang

```
action create_land_unit_tmp{
		// overlap the soil and the soil_salinity layers
		loop soil1 over:soil{
			loop soil_salinity1 over: soil_salinity overlapping self{
				if soil_salinity1 overlaps soil1 {
					geometry geom_unit1 <- soil1 intersection soil_salinity1;
					write "Land unit:" + length(geom_unit1.geometries);
					list<geometry>geom_unit3;
					loop g over: geom_unit1.geometries {
						if g.area >0 {
							geom_unit3<<g;
						}
					}
					
					geometry geom_unit4 <- geometry_collection( geom_unit3);
					create land_unit{
								shape <- geom_unit4;
								land_unit_id <- rnd(1000);
					}		
//					if  geom_unit1.area >0 {
//							create land_unit{
//								shape <- geom_unit1;
//								land_unit_id <- rnd(1000);
//							}		
//					} 
//					
				}
			}
			
		}
		// loop the land_unit 
//		loop lu1  over:land_unit_tmp {
			
//		}
		write "Number of land_unit agents:" + length(land_unit);
		write "phase 2 finie";
		//save land_unit to:"land_unit_gama.shp" type:"shp";
		save land_unit to:"../includes/land_unit6.shp" type:"shp" with:[land_unit_id::"TYPE"];
	}
		
}
```

1 occurence in Simulation #0 of model Environment at cycle 0: java.lang.ClassCastException: com.vividsolutions.jts.geom.MultiPoint cannot be cast to com.vividsolutions.jts.geom.Point
in save land_unit to: '../includes/land_unit6.shp' type: shp ();
java.lang.ClassCastException: com.vividsolutions.jts.geom.MultiPoint cannot be cast to com.vividsolutions.jts.geom.Point
org.geotools.data.shapefile.shp.PointHandler.write(PointHandler.java:107)
org.geotools.data.shapefile.shp.ShapefileWriter.writeNonNullGeometry(ShapefileWriter.java:241)
org.geotools.data.shapefile.shp.ShapefileWriter.writeGeometry(ShapefileWriter.java:213)
org.geotools.data.shapefile.ShapefileFeatureWriter.write(ShapefileFeatureWriter.java:390)
org.geotools.data.shapefile.IndexedShapefileFeatureWriter.write(IndexedShapefileFeatureWriter.java:96)
org.geotools.data.store.EventContentFeatureWriter.write(EventContentFeatureWriter.java:125)
org.geotools.data.InProcessLockingManager$1.write(InProcessLockingManager.java:337)
msi.gaml.statements.SaveStatement.saveShapeFile(SaveStatement.java:457)
msi.gaml.statements.SaveStatement.saveShape(SaveStatement.java:312)
msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:170)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.statements.AbstractStatementSequenceWithArgs.privateExecuteIn(AbstractStatementSequenceWithArgs.java:49)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.DoStatement.privateExecuteIn(DoStatement.java:187)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:57)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:84)
msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:208)
msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:192)
msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:170)
msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:396)
msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:155)
msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:136)
msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:220)
msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:186)
msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:170)
msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:172)
msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:250)
msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:330)
msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:101)
java.lang.Thread.run(Unknown Source)
in save land_unit to: '../includes/land_unit6.shp' type: shp ();
in agent Simulation #0 of model Environment

**Comment by tcquang** [comment]
Hello,
When replacing the "geometry_collection" by "union" , the save statement works well.
Thank you Patrick!

Quang

**Comment by AlexisDrogoul** [comment]
Fixed by applying a recursive save in case of geometries.
