### ISSUE TITLE
Save agents in a CSV file (header)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1787]
I was trying to save sets of values in a csv file.
I wanted to fill the header too.

Saving in GAMA can be done with 2 statements =:    
- save : but the "header:" facet accepts only a boolean. And putting the header at true 
- file_output : the header facet accepts more than a boolean.

Shall we : 
- deprecate the file_output ?
- improve the header facet of the save statement ?

**Comment by AlexisDrogoul** [comment]
Closed as a duplicate of the more general issue #1362
