### ISSUE TITLE
Features / 3D Visualization / GISVizualization

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1788]
Running this model.
The displays (that displayed the buildings) become white.
When we pause or decrease the simulation speed, they appear.

**Comment by AlexisDrogoul** [comment]
That's a common problem for models that dont do anything. I propose to settle this by fixing the delay in this kind of models.

**Comment by AlexisDrogoul** [comment]
Another option is to synchronize the displays. I have committed the first solution.
