### ISSUE TITLE
Enhancement for union and intersection on species level

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1789]
Hello,
The actual operators on geometry agents (intersection and union) are quite good. But as my knowledge, these operators work with individual agent level, that are still difficult to use. 
If there are the same operators (union, intersect, identity, dissolve - merging a group of agents having a same attribute) for 2 species (or 2 list of agents ) would be perfect for users.
Thank you!
Quang

**Comment by AlexisDrogoul** [comment]
I dont understand what you want. Doing union on the geometries of agents ? `union(spec1 + spec2)` does not work ?

**Comment by AlexisDrogoul** [comment]
Basically, the easiest way to deal with this is to do the union and intersection between the geometries of the species. For instance, `geometry(spec1) + geometry(spec2)`.

**Comment by AlexisDrogoul** [comment]
And if I try to understand your question, `geometry(spec1 where (each.attr1 = 10))` is the way to do a "merge" in GAMA.
