### ISSUE TITLE
An option to save agents into a shapefile with all of attributes of the agents

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1790]
Hello,
It is not very important, but it will be nice if GAMA have an option to save agent to shapefile without define which attributes to save. I mean, could we save the shapefile automaticaly with the attributes of the species without the facet "with:" ?
Because some times we have a lot of attributes to save and of course we need to take all of these attributes to the shapefile.

Thank you!

Quang
P/S: So sorry if it exists and if I don't know how to do it.

**Comment by AlexisDrogoul** [comment]
Do you want to save the attributes defined in the species or the attributes present in the shape of each agent ?

**Comment by tcquang** [comment]
Hello,
I would like the attributes of the species please!
Thank you,
Quang

**Comment by AlexisDrogoul** [comment]
@ptaillandier so it's equivalent to what we are already doing with CSV files. Ready to do it ? :)

**Comment by AlexisDrogoul** [comment]
Since not all types are supported in shape files (only boolean, int, float, string and geometry), I propose to filter them and convert all the values that do not have one of these types to string.

**Comment by sriramab** [comment]
I support this enhancement. I think other than type of variable there is
also limit on length of attribute  name.
 As of yesterday there is a bug I reported for saving as shape files and
Patrick is investigating on it I think.

**Comment by tcquang** [comment]
It works well!
Thanks Patrick!
