### ISSUE TITLE
Neighbor value for a grid

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1795]
The neighbor value in a grid can be 4 or 8 but I notice that you can put any value in this facet.

Maybe we should force the user to put only 4 or 8?

**Comment by agrignard** [comment]
we can also put 6 of course ;-)

so 4,6,8 but no other values

**Comment by AlexisDrogoul** [comment]
There is no way to force the user into putting 4, 6 or 8, as the facet can be initialized via a variable or a parameter. The current behavior is to consider 8 as the "default" neighborhood if a wrong value is passed.
