### ISSUE TITLE
Button to Share

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1797]
Hi, during the coding camp I have seen that many developers when answering my queries, showed me how to change part of the code (in GAMA library models) to achieve what I wanted. Interesting as it may be, these working tweaks / snippets are not shared for the larger user community.  And no wonder, different developers have different versions of the same library model.

I propose if a share button (like the one you see in Mac finder) could be added to GAMA, so that when a user or a developer changes part of a code to create/ re-create / optimise the behaviour of the model, (s)he could then just hit the share button to put it out for the larger community. The share button could lead to a github site for instance `gama user-models` (just to differentiate them from model library) and to make sure that they are provided as-is from users.  This could be effective in long term as crowd-sourcing (read user-sourcing) increases. 

May be those teaching at educational institutes, could push or ask students to push their models to this git site and enter some comments to briefly explain the new model or just the changes (s)he made to achieve something different than the library models. 

This concept of click to share is much easier and could be encouraging to push models than asking users to take time out and put out and decorate their models.

srirama

**Comment by AlexisDrogoul** [comment]
Moved to https://github.com/gama-platform/gama.experimental/issues/9
