### ISSUE TITLE
GAMA ~~could~~ / should tweet 🐥

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1798]
Hi,

I have always been wondering why GAMA does not tweet !
These days it is perfectly acceptable (to tweet) during conferences that a participant watches something interesting from a presentation and tweets "hey check this new tool #GAMA from the one of the developers of @gama". or  " an interesting new approach with @gama " or "@gama now with r #gamr "

I know those were really silly examples, but the point is to consider tweeting !! 🐣 🐥 

I am (not) sure you know, that you could link twitter to Facebook, such that when you tweet, it also appears on your Facebook wall., so you could "defy science" and be in two places at one given time !! 😄

**Comment by sriramab** [comment]
Wondering if I should tag this as a bug 😄

**Comment by AlexisDrogoul** [comment]
Feel free to open the official account :)

**Comment by AlexisDrogoul** [comment]
Done. Thanks @sriramab and @agrignard ! https://twitter.com/gamaplatform (and hashtag #gamaplatform)
