### ISSUE TITLE
Permanent displays broken

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1800]
Permanent displays are not displayed anymore (opengl and java2D)
For example (working on 1.6.1)

/**
 *  new
 *  Author: HPhi
 *  Description: 
 */

model new

global
{
	float ssum init:0 update:rnd(20);
}

experiment my_experiment type: gui {
}

experiment Batchxp type: batch repeat: 5 keep_seed: true until: (time > 400) {
	method exhaustive maximize: ssum;
	
	reflex info_sim{
		write "Running a new simulation " + simulation; 
	}
	permanent {
	
		display Bonjour type:opengl
		{
			
		}
		display mychart type: java2D {
			chart "mychart" type: series {
				data "bonjour" value: rnd(10);
			}
		}
		
	}
	
}

**Comment by AlexisDrogoul** [comment]
Fixed with commit https://github.com/gama-platform/gama/commit/4a9de605b25c8dc73f55be613e81db1fc5460537
