### ISSUE TITLE
accessing R via console/system commands from GAML 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1806]
Hi,

Would it be possible to pass system commands from GAML? If possible, R can be accessed easily and may be many more system commands.

GAML could have something like knitr or markdown-like blocks/chunks containing R code to be executed. Or for example from R you can access with : system( "console commands") 

thanks

**Comment by AlexisDrogoul** [comment]
I have just committed a `console` operator, defined in `msi.gaml.operators.opConsole(IScope, String)`

It allows you to pass a string that will be executed in the directory of the model (like `more myModel.gaml`) and to receive a string representing the result. For instance, 

```
		write console("pwd");
```

It is fairly basic for the moment. In particular, on Unix-based systems (Linux/MacOS X), the full path of the executables must be specified (e.g. `/bin/ls - al`). 

The agent is blocked until the answer has arrived.

Can all the terminal / console wizards look at my code ? There might be things to improve in it, especially the possibility to run different commands, to use bash, to get the environment variables, etc. 

@gama-platform/committers

**Comment by AlexisDrogoul** [comment]
I've made some minor improvements to the console (documenting it and allowing to launch non-blocking processes using the " &" sequence.

It clearly opens a whole new world of possibilities.

I've been for example able to launch another copy of GAMA with a given model, and I guess it would be VERY easy to launch headless experiments too ( @gnoubi !) from one model.

Think also about distributing a model where, if some files are not present, you can run an "install.sh" or "install.bat" shell script to copy them over... 

I will not work so much on this, now that the basis has been created, so please use this as a starting point for building a more robust command subsystem. I close this issue (although I havent touched the "R" subject), in order for everyone to post more focused issues on the use of this command for R or other programs.

**Comment by sriramab** [comment]
Yes, this is exactly what I mean. It opens world of possibilities. I open many other command driven applications from this system command, for example charts generated can be opened in preview, files can be sent to some bash commands. Thank you very much. this was much needed. This in a way bypasses need for running R using and reading .R files and getting the results back.

**Comment by AlexisDrogoul** [comment]
Just to note that I have renamed `console` to `command`. The former was a bit confusing (since we have a console in GAMA);

**Comment by sriramab** [comment]
may be 'shell'? then you don't have conflict with user_command :)

**Comment by sriramab** [comment]
Could you please give me an example how to use this? At my terminal console, when I do `"matlab -nodisplay -nodesktop < script.m"` would run a script file and give me results. 

Now how can I do this with the command operator? When I use a simple command("matlab"), it gives me error and when I use write command("matlab"), it gives an error at runtime.

Could you show an example usage of this operator, for example may be for the command I have above for matlab?
