### ISSUE TITLE
Improve the appearance of the desktop icon on white backgrounds

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1807]
Right now, the desktop icon is directly built from the new logo, and its appearance, even if a subtle shadow underlines it, is not so great (too thin, not prominent enough esp. at small sizes).

One possibility could be to differentiate the icon from the logo by adding it a background or a half-background. E.g. something like in the image below.

Any comments welcome ! ( @gama-platform/committers )
![icon](https://cloud.githubusercontent.com/assets/579256/15459783/23553e36-20d3-11e6-9bd0-2f941d40ef24.png)

**Comment by sriramab** [comment]
My suggestion (if we could  do away with the current logo) is to use the greek letter `gamma` .. in its lower case. yes, it has an extra m but sounds the same as we call GAMA. And this could be artistically be coloured in  a abstract twirled ribbon ...see many examples [here](http://www.shutterstock.com/en/pic.mhtml?irgwc=1&utm_medium=Affiliate&utm_campaign=Graphic%20resources%20SL&&tpl=39422-174648&id=126869855&utm_source=39422)

**Comment by sriramab** [comment]
I think even the current logo with its elements can be transformed into artistic ribbons as in my link above and you could keep the same three colours as in the current logo. I think any good graphic designer can do this in available popular software.

**Comment by agrignard** [comment]
I agree the actual icon looks weird. Why not just englobing it in a white cirlcle (it seems that most of the app icon are circle in mac os right?). Something like this? 
<img width="191" alt="screen shot 2016-05-25 at 12 28 27" src="https://cloud.githubusercontent.com/assets/3928502/15547955/38875f3a-2274-11e6-96d6-ec4252acad25.png">

**Comment by AlexisDrogoul** [comment]
Well.. although the problem was more with clear backgrounds, I think that putting a circle around it is not so bad.  I have the following proposal:

![sans titre](https://cloud.githubusercontent.com/assets/579256/15801214/fe3b7fae-2ab7-11e6-85ef-bbdce8ab9a78.png)

**Comment by agrignard** [comment]
yeah cool!
