### ISSUE TITLE
Request an util to notify the systemUI in the code

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1808]
When doing simulation or explore parameter, the long-time tasks, i minimize GAMA or hide it behind many other windows. Is it possible to have a notifier statement or operator to blink the GAMA in taskbar, or something else, to bring the focus in GAMA, when it occurs at some condition (finish loading, finish a step, errors occurs)?

**Comment by hqnghi88** [comment]
Hi, for instant, I have recalled by Alexis the usage of  "tell" statement, i.e.
if(condition){ do tell message: "this is a notification"; }
can solve a part of the enhancement. I close the issue and reopen it in the future.
Cheers.

**Comment by AlexisDrogoul** [comment]
So does it work with a `tell` in the code ??

**Comment by AlexisDrogoul** [comment]
If it works well, no need to do more, I guess. We just need, probably, to add it to the documentation of the statement (i.e. "If GAMA is minimized, tell will issue a notification -- blinking icon, jumping icon -- in the system tray or dock"). Can you do it ? 

Thanks
