### ISSUE TITLE
Installation of 64 bit GAMA defaults to C:\Program Files (x86)\Gama

### ISSUE THREAD

**Issue by AukeHoekstra** [gama-platform/gama#1809]
When I execute "gama1_7_b1_win64.exe" (downloaded May 23rd) the installer proposes "C:\Program Files (x86)\Gama" as the default directory. 
However, the convention in Windows 64 bit versions is that "(x86)" is only added when 32 bit programs are installed. All 64 bit programs should default to "C:\Program Files\".

Not a big issue and users can easily change the directory themselves but many users might not be aware of this and others will just blindly click next. Later they might assume that some bugs or problems have to do with them installing in the wrong directory or not having a proper 64 bit installation.

So I propose to change the default installation directory for 64 bit Gama executables to C:Program Files\Gama.

**Comment by AlexisDrogoul** [comment]
Hi, actually the b1 included a setup executable and this behavior had been noted some time ago (#1550). The current release does not include this executable, so I guess we can close this issue (but we will remember it if we add a wizard !). Thanks for reporting it, anyway.

**Comment by AukeHoekstra** [comment]
I missed it because I looked at open issues. 
I would recommend including an executable if you really want to reach the Netlogo crowd. 
But whatever happens: great work on version 1.7. Really important that there finally is a good DSL based agent modeling tool.
