### ISSUE TITLE
Simulation continue run after a logic error of the model, but very fast

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1810]
Hello,
Please try the following model. In which I have an algorithm error. The simulation did not stop at cycle 6 or did not show an error a.
Thank you!

model model1

global {
	/** Insert the global definitions, variables and actions here */
	int var1 <-0;
	int i<-1 update:l[cycle] ;   // a logic error 
	list l;
	init {
		l<- [1,2,3,4,5];
	}
	reflex update{
		write "Value i:" + i;
	}
	reflex stop{
		if cycle >6{
			do pause;
		}
	}
}
experiment model1_exp type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
	
	}
}

**Comment by AlexisDrogoul** [comment]
Fixed. The update of agents attributes was actually a place where the exceptions/errors were not properly caught. This is now done properly.

**Comment by tcquang** [comment]
It works well, now I have to fix the errors of my model :) !
Thank you!

2016-05-23 17:54 GMT+07:00 Alexis Drogoul <notifications@github.com>:

> Closed #1810 <https://github.com/gama-platform/gama/issues/1810> via
> 20ff149
> <https://github.com/gama-platform/gama/commit/20ff14962e056dc9e45aa1318317121e0efbee97>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gama-platform/gama/issues/1810#event-668788165>
>



-- 
Quang Chi TRUONG
Tel: 0939388153
