### ISSUE TITLE
shapefile error:  headless vs GUI 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1811]
Hi,

When you run a simulation in GAMA gui, there is no error if you do not have the all 5/6 structural files that accompany shapefiles. That is, you can run a GUI simulation with just .shp. This is caught in console but simulation is not stopped. 

But when you run a headless mode of gama, the process is stopped. May be a small error check missing somewhere?

**Comment by AlexisDrogoul** [comment]
Does it output anything when stopping ?

**Comment by sriramab** [comment]
Yes, missing .shx file. I was just wondering why stop in interactive mode and not in GUI mode. But I think this a creeped into the standalone also, if I am not wrong. Now you cannot run a simulation if u have missing companion files of .shp

**Comment by sriramab** [comment]
I close this as may be it is a good idea to always have all the siblings of shapefile together, which this error forces.
