### ISSUE TITLE
Would check a wrong color name in the color facet.

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1812]
Hello,
GAMA did not show an error message for the wrong color values in the color facet. Could you adjust a check for the wrong color names ( or format )  in the color facet please! Because my English level sometimes lead me to this kind error.
Thank you!

Please try this model
model testcolor

global {
	/** Insert the global definitions, variables and actions here */
	init{
		create speciesA number:10;
	}
}

species speciesA{
//	rgb colorA <- rgb("yelow");				// 	the error is well caught
	aspect default{
//		draw  circle(2) color:rgb('255,255,0');// display as a circle in yellow, wrong color value but there is no error
		draw  circle(2) color:rgb('yelow');	// display as a circle in yellow, wrong color name but there is no error
		}	
}
experiment model1_exp type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
		display sim{
			species speciesA aspect:default;
		}
	}
}

**Comment by AlexisDrogoul** [comment]
The correct way to use named colors is to use `#` + their name.

All other ways (like the use of `rgb` with `'255,255,0` or `yelow` in your code) will result in the use of the default color for agents (which, incidentally, is yellow by default). Runtime errors, however, are not displayed by default when running aspect/draw statements. We can reverse this if you think it is important.

**Comment by tcquang** [comment]
Hello,
I think the color: rgb('100,100,0') or some things like that should be caugth at run time. That would help a lot for the beginners.
I have faced with many models with a little error ' ' (in the aspect   .... color: rgb('100,100,0') ) that the agent did not showed.

Thank you very much in advanced  for your support 

![color](https://cloud.githubusercontent.com/assets/11825516/15491665/fa7fa63e-219c-11e6-94b0-44f9112b11eb.png)

**Comment by tcquang** [comment]
Hello,
I found that the Custom color is the best way to set the color. 
Thank you very much, and please close this request!
