### ISSUE TITLE
Add mouse scroll behavior to the list menu in the toolbar's Gaml Editor

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1813]
In the long list menu - toolbar in GamlEditor, ie the list of color, the list alphabet of Operators, currently, the scroll gesture of mouse and touchpad dont work. The scrolling by keys, "click on triangle"  are working but the "mouse hovering at the end of list" only work sometimes.

**Comment by AlexisDrogoul** [comment]
I have *absolutely* no idea on how to implement this behavior. On MacOS X it is working out-of-the-box.

**Comment by hqnghi88** [comment]
I have no idea too, I just found that in eclipse ,that it dont have this behavior too. So i close the issue.
