### ISSUE TITLE
Welcome pages are not well displayed  - the git version - Windows 8 64 - 1366x768

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1817]
Hello,
When opening the Welcome page in GAMA window ( Menu View\Welcome page):
1. The buttons are not displayed when the window size is small ( please see the picture attached)
2. The Document button does not work
3. The Goback to wellcome page does not have a icon ( or missing), could we adjust one icon for this button( because when clicking to the Newgroups link, I can comback by back and forward button (need to click Home button)

Thank you

![welcome_this_size_is_good](https://cloud.githubusercontent.com/assets/11825516/15481674/e43a677a-2155-11e6-94ae-8bf96e49f6b7.png)
![welcome_this_state_of_windows_is_not_good](https://cloud.githubusercontent.com/assets/11825516/15481678/e722144c-2155-11e6-85e3-7a8ce5bf52d8.png)
![doccument_link not working](https://cloud.githubusercontent.com/assets/11825516/15481681/e9ae69b8-2155-11e6-9592-456003558640.png)

**Comment by AlexisDrogoul** [comment]
Regarding the non-display of the menu of the website -- please post a separate issue on https://github.com/mazarsju/gama_doc_17/issues. However, please note that the menu is accessible when clicking on the small GAMA icon on the top-right side. I guess it is a choice, although it is a strange place.

The documentation link points to "http://doc.gama-platform.org", which itself, for the moment, points to gama-platform.org -- we dont have any dedicated welcome page for documentation yet (I think it is already an issue).

For the home icon, it's a matter of taste :) But feel free to design and add one if you want !
