### ISSUE TITLE
Travis integration build timer could be set to a higher value

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1819]
Hi,

It seems that Travis is building GAMA almost every 10 minutes, which is a little bit too short in my opinion. Is there a way to make it build the repository at each commit or every day (or both) ? 

Thanks

**Comment by reyman** [comment]
I sent a mail to the admin of travis.

**Comment by AlexisDrogoul** [comment]
OK. Now it seems a bit asthenic :) But one per day is ok for us, I guess ! Thanks
