### ISSUE TITLE
Cycle displayed in the GUI

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1822]
When the model is running the cycle are displayed, once you click the green item then the cycle are not anymore displayed and it is replaced the “real” time in sec I guess?  I cannot always reproduce it.

**Comment by AlexisDrogoul** [comment]
This is the way it is working since GAMA 1.5, I believe...

**Comment by hqnghi88** [comment]
I am curious on why you can not always reproduce it? It should be in turn switched when you clicked on green status bar

**Comment by agrignard** [comment]
yeah sorry it's not new I never notice this feature in fact. The only drawback I see is that the display switch after a new iteration. Is it possible to switch between cycle and real time as soon as we click on the green button?
