### ISSUE TITLE
download link error

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1827]
Hi

On the website, downloads section. when you point to mac os x download, the link fails and the link points to an exe file for a mac download. Something fishy, please check

**Comment by AlexisDrogoul** [comment]
Right. I think the best would be to remove completely the 1.7 section (from the menu as well) and only keep for the moment the "Latest release (1.7)" label. The 1.7b1 is meaningless now.

**Comment by sriramab** [comment]
Yes, may be better to have an `archive` section for older versions?

**Comment by mazarsju** [comment]
I just removed the section 1.7 beta.

**Comment by AlexisDrogoul** [comment]
Well, I just messed up the download sections -- sorry for this. Dont add new issues. But we will have a much simpler layout whenever things will be sorted out again... :)

**Comment by AlexisDrogoul** [comment]
Everything should be in order now.
