### ISSUE TITLE
ants foraging (complex) looks weird?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1828]
Is there something wrong? We use to have 4 displays before right? 
<img width="924" alt="screen shot 2016-05-25 at 15 29 56" src="https://cloud.githubusercontent.com/assets/3928502/15554260/48ccbecc-2291-11e6-80ef-ae86e06d0f97.png">

If it's normal then the size of the environment should be changed

**Comment by AlexisDrogoul** [comment]
Well the goal was to show two completely different displays. Maybe we should add one or two charts or something else (the new nice charts made by Philippe, maybe). Feel free to change the model to your taste.

**Comment by agrignard** [comment]
problem of size once you run the simulation? 
<img width="644" alt="screen shot 2016-05-27 at 08 15 08" src="https://cloud.githubusercontent.com/assets/3928502/15607740/355c73ca-23e3-11e6-9bee-a0da29d64307.png">

**Comment by AlexisDrogoul** [comment]
Which problem of size ? The layers are normally moving back and forth.

**Comment by agrignard** [comment]
oh yes sorry i was surprised but indeed they are asked to move ;-)
