### ISSUE TITLE
Emit a warning when the header comment is not correct in models

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1832]
I propose to add a new validation warning in models, concerning the header multi-line comment. It would appear when:
- the name of the model does not match the name described
- the description is empty
- the author is empty
- the tags do not correspond to known tags

And it would propose to rewrite it using the template found in the regular "Skeleton" template.

**Comment by mazarsju** [comment]
Good idea indeed. Note that all the tags are listed in the file IConcept (inside the precompiler).

**Comment by AlexisDrogoul** [comment]
Probably too much trouble (build a parser, etc.) -- I close this one for now on.
