### ISSUE TITLE
Some things strange with multisimulation in batch mode.

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1836]
Please try the following model where I would launch the simulation 5 times with the batch mode. 

1. When I set the option "Run multiple simulation in multiple threads" = true, I found that there are 5 simulation have been started, but there are only 3 simulations have stopped. (please sea the following results )
Start the simulation 52
Start the simulation 90
Start the simulation 42
Start the simulation 36
Start the simulation 32
End of the simulation 32
End of the simulation 32
End of the simulation 32

2. When I set the option "Run multiple simulation in multiple threads" = false, I have the results as follows: 
(There are 5 simulation have been launched but there is only one simulation have stopped)
Start the simulation 70
Start the simulation 31
Start the simulation 79
Start the simulation 81
Start the simulation 22
End of the simulation 22

Thank you!
________________________________________________
model testMulti

global {
	/** Insert the global definitions, variables and actions here */
	
	int sim_number <- rnd(100);
	init{
	
		write'Start the simulation ' + sim_number;
	}

	reflex end_sim when: (cycle=6){
		write 'End of the simulation '+ sim_number;
		do pause;
	}
}

experiment batch_5sim type:batch repeat: 5 keep_seed: true until: time =6{
		
}

experiment oneSim type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
	}
}

**Comment by AlexisDrogoul** [comment]
Just a question: when did you notice this behavior ? Is it due to a recent commit ?

**Comment by tcquang** [comment]
I remember that I can't launch a bath mode during the coding camp, but at that moment, it was a error in batch mode. I remember that have also posted that error as an issue. I will check the issue.

**Comment by tcquang** [comment]
Thank you very much for fixing the issue.
It works well with multisimulation.

But please check the model  with the option "Run multiple simulation in
multi threads" = False, set in the Preferences window. The simulations are
still launched in same times (parallelly).
__________________
Here are the result with this one:
Start the simulation 20
Start the simulation 11
Start the simulation 67
Start the simulation 82
Start the simulation 47
End of the simulation 20
End of the simulation 11
End of the simulation 67
End of the simulation 82
End of the simulation 47

Could we have an option where the simulations in batch mode run one by one
( I mean the after the first simulation finished, the second simulation is
reloaded and run). Because I would like to loop the simulation 100 times.
It will load 100 simulations in same times (I can relaunch 20 times x 5 for
each but there is an error when a calculate the Fuzzy Kappa at the end of
the simulations).
For example:
Start the simulation 20
End of the simulation 20
Start the simulation 11
End of the simulation 11

Thank you very much!


2016-05-27 8:52 GMT+07:00 Alexis Drogoul <notifications@github.com>:

> Closed #1836 <https://github.com/gama-platform/gama/issues/1836> via
> 6cafe75
> <https://github.com/gama-platform/gama/commit/6cafe75a7a2b9ff7f7a253a0f72c6b14fea3fbe6>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gama-platform/gama/issues/1836#event-673944548>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ALRxbCG3r4qWAsW8-RyHaHk8QtSwIf0hks5qFk5PgaJpZM4InVcz>
> .
>



-- 
Quang Chi TRUONG
Tel: 0939388153

**Comment by AlexisDrogoul** [comment]
Can you please open a new issue for this ? So that we dont mix these two ones (which have nothing in common)
