### ISSUE TITLE
GAMA hang when species are writing too much in the console

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1838]
Try this simple - dummy model
model dummy
global
{
	init
	{
		create A number:100;
	}
}
species A skills:[moving]
{
	reflex t
	{
		do wander;
		write shape;
	}
}

experiment main type: gui
{
	output{
		display d{
			species A;
		}
	}
}

GAMA will be slown down after around 300 steps and need a restart if we stop simulation at about 5-600 steps.

**Comment by AlexisDrogoul** [comment]
Does not happen when you set a limit, does it ? Mine is working happily with a limit of 20000 chars (the default, I think).

**Comment by hqnghi88** [comment]
Dear Alexis,
In fact, with help of Quang, the Preference affected is the Synchornize display. This issue happen with the synchronize on. The length of console does not take any effects.

**Comment by AlexisDrogoul** [comment]
OK. I think the main problem is the time taken by an option I have introduced to ease reading the console (word wrap). I have now set it to false by default in a preference (warning the user that it might slow down the simulation when turned on).
