### ISSUE TITLE
new chart in OpenGL

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1843]
... the new chart looks great but it seems that are not working at all when using an opengl display.. it was the case before right? It can be usefull to display some chart in an opengl display

**Comment by AlexisDrogoul** [comment]
Probably fixed by the latest commit, but they look plain ugly on OpenGL. Definitely not the good way to draw charts, I guess (it was already the case before, by the way !)

**Comment by agrignard** [comment]
Well it's running but yes the result are strange (problem of scaling for instance)... before (in the 1.6) it was not so bad no? and I insist but I (and maybe I won't be the only one) 'd like to use them in an opengl display

**Comment by AlexisDrogoul** [comment]
Since the charts are drawn as images, did you check if the preference to always draw multiple of 2 is checked ? Otherwise, the fix is probably somewhere in the ImageDrawer and the creation of textures...

**Comment by AlexisDrogoul** [comment]
There is actually not a lot of things to do to improve the rendering, as the openGL displays (1) display their "world" much smaller than Java2D ones; (2) the unit is the world width/the world height (and not pixels) which has no meaning for charts --  we need to have the size in pixels to produce the chart image at the correct dimensions. We would need to allow some images to be larger than the "world" in OpenGL and I dont know how to do that and how to convey this information to OpenGL.

**Comment by AlexisDrogoul** [comment]
OK. I've implemented an ugly workaround that should 99% of the needs. Tell me how it is in your particular case.
