### ISSUE TITLE
Repetitions of simulations in batch mode should not be created at once

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1847]
Dear Developers,
Could you please have an option where the simulations in batch mode could run one by one ( I mean after the first simulation finished, the second simulation will be loaded and run). Because I would like to loop the simulation 100 times for a statistic the simulation's result. It will load 100 simulations in same times.
The output look like this one:
Start the simulation 20
End of the simulation 20
Start the simulation 11
End of the simulation 11
....
 I have check the option "Run multiple simulation in multi threads" = False, set in the Preferences window. The simulations are still launched in same times (parallelly).
__________________
Here are the result with this one:
Start the simulation 20
Start the simulation 11
Start the simulation 67
Start the simulation 82
Start the simulation 47
End of the simulation 20
End of the simulation 11
End of the simulation 67
End of the simulation 82
End of the simulation 47

Thank you very much!

______________________
model testMulti

global {
	/** Insert the global definitions, variables and actions here */
	
	int sim_number <- rnd(100);
	init{
	
		write 'Start the simulation ' + sim_number;
	}

	reflex end_sim when: (cycle=6){
		write 'End of the simulation '+ sim_number;
//		do pause;
	}
}

experiment batch_5sim type:batch repeat: 5 keep_seed: true until: time =7{
		
}

experiment oneSim type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
	}
}

**Comment by AlexisDrogoul** [comment]
Well. All the inits are made at once, it's true. After that the runs are sequential, but it nevertheless creates a problem for large simulations,  I agree. I will try to address this soon.

**Comment by tcquang** [comment]
It works very well,
Thank you!

2016-06-04 17:25 GMT+07:00 Alexis Drogoul <notifications@github.com>:

> Closed #1847 <https://github.com/gama-platform/gama/issues/1847> via
> e2e489e
> <https://github.com/gama-platform/gama/commit/e2e489e49293534d3737c05881c4a2472e1ede79>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gama-platform/gama/issues/1847#event-681899100>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ALRxbJ0cRV8QOkvgPSb6l2MpH_IUlBWOks5qIVKngaJpZM4IoIa3>
> .
>



-- 
Quang Chi TRUONG
Tel: 0939388153
