### ISSUE TITLE
map comparison model not compiling 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1848]
The plugin idees.gama.mapcomparison is required to run this model

**Comment by hqnghi88** [comment]
Hi Arnaud
Do you remember the Validation View? or a Clea, Build Project in GAMA will recompute the requirements. Map comparison plugin is merge into the core as far as i know.

**Comment by agrignard** [comment]
mmm ok, i tested on a build release and there is the same problem

**Comment by AlexisDrogoul** [comment]
You probably have an old workspace where this requirement is still noted as part of the hidden metadata of the model. It is not anymore in the latest version of the model library. If nothing works and you dont want to change workspace, simply delete the `.metadata` folder in `Features`.
