### ISSUE TITLE
Exporting the product does not export GAMA plugins

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1851]
### Steps to reproduce
1. Open `gama.product` in `msi.gama.application`

2. Select to export it as an application

### Expected behavior
The application should be produced with all plugins, those of eclipse and all the ones of GAMA (the ones included in the different features)

### Actual behavior
The application is correctly exported, but none of the plugins of GAMA show up, preventing the application to be runnable. No changes in the various preferences change this state, except one: unselecting `generate P2 repository`, which has a strange effect: it correctly exports GAMA plugins but then the resulting application is not functional (at least on MacOS X).

### System and version 
MacOS X, JDK8, latest git revision of GAMA (but this behavior is at least 3 days old, as it has already been reported by @tcquang, on Windows, in https://github.com/gama-platform/gama/issues/1816#issuecomment-221934305).

**Comment by AlexisDrogoul** [comment]
I have normally fixed the issue -- without knowing exactly how I did it, though. So it's worth testing it :)

**Comment by tcquang** [comment]
The version exported of GAMA works well with the normal models. But it still have errors with simple BDI plugin.
Thank you!

![gama_export_product](https://cloud.githubusercontent.com/assets/11825516/15675382/fe72c1d4-276b-11e6-9229-776e527dd17a.png)

**Comment by tcquang** [comment]
Thank you very much hqnghi88. The simple_bdi is well exported!

**Comment by AlexisDrogoul** [comment]
Bad news. Adding the property `installMode="root"` (in order to be able to update the application, see gama-platform/gama#1863 ) to the features seems to prevent them from installing their plugins in the application bundle... Which means we have to choose between generating releases with Tycho (with their own problems, see gama-platform/gama#1776) or with PDE (but the application will not be updatable). 

Probably the solution is to have two separate products (one for hand-made releases, the other for tycho). What do you think @reyman ?

**Comment by reyman** [comment]
Sorry for delay (too much gama dev message i didn't see the mail arg), i read the comment on gama-platform/gama#1776 
I ask a similar question here ( gama-platform/gama#146 ) about separating product and plugin, it can be a first step to have multiple process of product release i suppose.

**Comment by AlexisDrogoul** [comment]
There seems to be no proper solution for maintaining the same product and using it both for Tycho and PDE builds. I think the result of all this is that we have to face the fact that PDE builds are more or less dead. Because, either they produce a functional release, but this release will not be updatable, or they dont produce a correct release. The "death" of PDE builds is more or less acknowledged by the Eclipse community, by the way. Now, if only we had a "one-click" procedure (read: button) to produce a Tycho build, it  would be of a great help for the developers and the first-time downloaders of the source code... 

For the moment, moving out of Eclipse, launching the shell script (if bash is installed, which is not the case in pre-Windows 10 environments), making sure maven is installed at the right place, etc... is a bit cumbersome, even if we document it ( gama-platform/gama-platform.github.io#109). Wouldnt it be possible to have only one file (a maven task ?) that could be directly run from within Eclipse ? That would simplify a bit this step.

**Comment by reyman** [comment]
Hi @AlexisDrogoul . Ok ! 

It's easy to run maven into eclipse using "run as...", you only need some plugin : 

In market place, you first need to install Maven integration for Eclipse m2e  then you need to install and go here : 
`Tycho configurator : Windows > Preferences > Maven > Discovery > Open Catalog > tycho configurator`

With this two install, Tycho and Maven are linked, as you can see in `File > Properties > Maven > LifeCycle` mapping are green.

After that, you can "run as maven" by right clicking on pom.xml first on the `msi.gama.processor`, then `msi.gama.parent` . If we separate product from application plugin as discuted in https://github.com/gama-platform/gama/issues/146 , we can also run without option `-f` (needed to run pom.xml and pom-product.xml in one step) `msi.gama.application-plugin` then `msi.gama.application-product` . We can also make a general parent pom.xml to drive all this different steps in only one click, i need to seach in maven documentation, but i pretty sure it's possible.

**Comment by AlexisDrogoul** [comment]
I close this issue by adding a new product `gama.runtime.product`, dedicated for running GAMA from within Eclipse and for exporting releases using PDE (instead of Tycho). These releases cannot update but it is not really important as the "official" releases will now be produced by Tycho.
