### ISSUE TITLE
Having a data type "action"

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1852]
### Steps to reproduce
1. I have a list of conditions, and a list of actions.

	int x->{rnd(100)};
	bool c1 ->{x<50};
	bool c2 ->{x>=50};
	list<bool> conditions->{[c1,c2]};
	list actions<-[a,b];
	action a{
		write "an action a ";
	}
	action b{
		write "an action b";
	}
2. I want to call do statement of actions[i]

3. But it is not possible

### Expected behavior
I would like a solution to call the actions[i] to do its computations.

### Actual behavior
The syntax does not accept to write something as in lines 27 of attached model:
do actions[i];

### System and version 
GAMA git, JDK 8 , win10

model ActionCall
global{
	
	int x->{rnd(100)};
	bool c1 ->{x<50};
	bool c2 ->{x>=50};
	list<bool> conditions->{[c1,c2]};
	list actions<-[a,b];
	action a{
		write "an action a ";
	}
	action b{
		write "an action b";
	}
	
	reflex doing{
		loop i from:0 to:length(conditions)-1{
			if(conditions[i]){
//				is it possible to do this calling?
//				do actions[i];
				write actions[i];
			}
		}
	}
}

experiment simple type:gui{}

**Comment by AlexisDrogoul** [comment]
Hi,

It seems to be a bit complicated to do as there would be no possibility to check, at compile time, the correctness of the code (the `list actions <- [a,b]` is a constant in this model, but it could perfectly be the result of another computation, or a parameter chosen by the user, w/o any possibility to know whether or not the actions can be applied to the agents). Besides, what do you do about the parameters in this proposal ? 

Alexis

**Comment by hqnghi88** [comment]
Dear Alexis,
I think i have miss the declaration of list actions. It should be : list actions -> {[a,b]};   so actions[i] will recompute when it is called. Does it propose something better? 
Actually, i have playing with the parameters but it seem that GAMA dont have the polymorphism of actions. I imagined if i have 10+ actions with different name , i.e. compute0(int i), compute1(float i), compute2(string x, float i), so i tried to create a list of actions and conditions to call corresponding computations.

**Comment by AlexisDrogoul** [comment]
I'm sorry, I dont get it. Can you give an example of a code you could write using it, which cannot be written right now ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Here is the code:
model polymophism
global{
	init{		
		do op("hello");
		do op(1,1);
		do op(1.0);
	}
	action op(string i){
		write "string: "+i;
	}
	action op(int i, int j){
		write "int int :"+i+" "+j;
	}
	action op(float x){
		write "float "+x;
	}
}
experiment test type:gui{}

**Comment by AlexisDrogoul** [comment]
Yes, I know there is no polymorphism in actions, as it is not implemented (only the last definition is taken into account). And it will probably never be implemented, as primitives and actions can have a variable number of arguments (if you have default values). However, what does it have to with an "action" datatype ?

**Comment by AlexisDrogoul** [comment]
As said previously, it is not possible to have a set of actions and to apply them using a loop, unless they dont have arguments (but even in that case, they may return different results). It is far better, from a design point of view, to have a common interface (virtual species) from which your agents species derive, and to apply the same action to each.
