### ISSUE TITLE
Exploration output window: The explored parameters are not shown by default

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1854]
### Steps to reproduce
1. Please try this attached model. 

2.In exploration output, the parameters selected for the  Best fitness value are not showed by default
3. When move the mouse over the fields (Best fitness; last fitness..) the parameters appear. But the text are not very clear.

Like these images
![selected_para_are_not_showed](https://cloud.githubusercontent.com/assets/11825516/15683122/ff2b8268-278a-11e6-80f3-5a7cb210a80c.png)
 images

![selected_para](https://cloud.githubusercontent.com/assets/11825516/15683102/f0b87ab0-278a-11e6-800c-f16bac68e8b3.png)

### Expected behavior
Could you please keep this display as in GAMA version 1.6.1 where the values are showed automatically after the exploration
![exploration_161](https://cloud.githubusercontent.com/assets/11825516/15683258/a71d902e-278b-11e6-8e59-e4db07e369c4.png)

### System and version 
Versioin GIT, JDK 1.8 91, OS Windows 64b... (if necessary, copy Help>Installation Details>Configuration in GAMA)

Thank you!
____________________________________________________________
model explorePara

/* Insert your model definition here */

global{
	
	float a<-5;
	float b<- 5;
	int x<-1;
	float y <-0;
	float fitness <- 0;
	
	reflex {
		y<-x^2 +5;
		write  "X:" + x + ", Y:" +y;
	}
}
experiment test type:gui{
	
}
experiment explorePara type:batch keep_seed: true repeat: 1 until: ( cycle > 0){

 	parameter "weight x" var:x min: -5 max: 5 step: 1; 
	method exhaustive minimize: y;
 }

**Comment by AlexisDrogoul** [comment]
Hi,

It is not possible with the current implementation of the Parameters window (or it would require too any changes). 

Alexis

**Comment by AlexisDrogoul** [comment]
OK. I've fixed it with a kind of hack. The result is not really beautiful, but at least it is informative... Well, I hope.
