### ISSUE TITLE
Give the possibility to change the field of view in GAML

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1856]
It can be nice to give the possibility to change the field of view of the camera (the  kind of lens you use to see your model (28mm, 50mm, 80mm, etc...) 

It's easy to do in Opengl I'll try to add a facet or something like that that change the parameter used in glPerspective. I think it can be nice to have it in the release. 

It will be useful to project a simualtion on a table from a beamer (if you don't want to have a perpective effect you need to change this value); the default one is now 45f I think.

**Comment by sriramab** [comment]
may be u can do something with the cone operator? it works the same no?

**Comment by sriramab** [comment]
may be more useful is to be able to define the center of the cone-circle/ cone-base. Then the camera focuses at a point irrespective of the location of the camera. It is more or less like the focus point you have on SLR cameras

**Comment by agrignard** [comment]
... there should be somewhere a call to gluPerspective but I cannot find it..

@AlexisDrogoul @mazarsju any idea?

**Comment by agrignard** [comment]
ok ok I get it it has been replace by glFrustum right? I think we can do the same 

So basically I will add a facet that enables to change the fovY value (by default 45.0d)

**Comment by AlexisDrogoul** [comment]
Well... If we could avoid a Nth facet on `display` it would be nice :) And if it's not named `fovY` (but `lens` for instance) it would be nice too ! But if we can't avoid it... 

In any case, this addition will need move to the new `camera` layer as soon as this one is ready (see #579 and the others). BTW, it would probably be a good thing if you can take the responsibility on this one. Moving all the camera-related facets to `camera`, having predefined ones, and allowing to choose it from the layer side controls would be nice.

**Comment by agrignard** [comment]
Nope I won't name it fovY...;-) On my laptop I add camera_field_of_view facet it's working but I cannot commit as it seems that my Eclipse GIt is still playing with my nerves (only some project are mark as gama-master the rest are GAMA-NO_HEAD)... I'll try to have a look on the #579 but not sure I can handle it this week...

**Comment by agrignard** [comment]
I commited the camera_lens facet. It's doing what I want to do but I am not sure so many people will use it that's why I put it as internal for the time being
