### ISSUE TITLE
Console windows does not work when clicking on the "Reload the experiment with the current parameters" button

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1857]
### Steps to reproduce
1. Please try this test model.

2. Launch simulation, change the value of parameter "Var x" to another value ( 2 for example)

3.Then, click the button " Reload the experiment with the current parameters"
4. Click Run button to run the simulation

### Expected behavior
Model 1:20
Model 1:21
Model 1:22
...

### Actual behavior
- No thing appeared in the console window.
- But when click Stop the simulation, after that, click testPara_console1 button to relaunch simulation, the results of the previous simulation appear in the console window. 

**(When testing this model, I just found that we don't need to click the button " Reload the experiment with the current parameters" when changing the parameters. But when user click on it, there are something strange)**

Thank you!

### System and version 
Version Git, Windows 64
______________________________________
model testPara_console1

global {
	/** Insert the global definitions, variables and actions here */
	int x <-1 ;//parameter: true;
	reflex write{
		write "Model 1:" + x + cycle;
	}
	
}

experiment testPara_console1 type: gui {
	/** Insert here the definition of the input and output of the model */
	parameter " Var x:" var: x ;
	output {
	}
}

**Comment by AlexisDrogoul** [comment]
OK. I have fixed it, but I cannot commit it immediately as the code is intimately connected with the one I have written for implementing #1850 .
