### ISSUE TITLE
perspective not saved when re-launching gama

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1860]
### Steps to reproduce
1.Open several models in gama
2.Relaunch gama

### Expected behavior
The opened files should be the same as before shutting down the application

### Actual behavior
No files are open

### System and version 
Git version, OS Windows.

**Comment by AlexisDrogoul** [comment]
Are you sure the product (or the run configuration) does not include the parameter `-clearPersistedState` ?

**Comment by mazarsju** [comment]
it was that indeed !
