### ISSUE TITLE
problem with light interaction coupled with "rotate" facet of draw statement

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1861]
The light is not correct when drawing shapes with the facet "rotate" : indeed, the investigations I made lead me to the fact that when a rotation is done (through a "glRotate"), we have to rotate manually the light in the opposite direction to lighten the right face. This is not possible in the JTSDrawer : this part of the code is placed between a "glNewList" and a "glEndList", and we have no access to the light position in this part of the code.

**Comment by AlexisDrogoul** [comment]
I think this issue has been more or less fixed in the recent commits. Needs to be tested, however, in various settings.

**Comment by AlexisDrogoul** [comment]
Closing this issue while cleansing the backlog. Please reopen if the problem is still present.
