### ISSUE TITLE
syntax error: console in GIT/ Standalone

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1862]
### Steps to reproduce
1. Open standalone version and use the console operator in any model. works good

2. Open the above model with console operator in GIT version. gives syntax error. 

3.

### Expected behaviour
should be No syntax error for console operator

### Actual behaviour
gives error for console operator in git version

### System and version 
GAMA Git 63cdcae
GAMA standalone
MacOSX Mavericks, Java 1.8

**Comment by AlexisDrogoul** [comment]
Which model ?

**Comment by AlexisDrogoul** [comment]
OK. Sorry. I didn't catch your phrase. As of #1806 it has been renamed `command`, so that probably explains the error.

**Comment by sriramab** [comment]
Solved. Thank  you. Then I should probably download latest standalone.  Could you please post a high quality video of interactive console. It looks interesting. I close this.
