### ISSUE TITLE
Error UI components of GAMA

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1863]
### Steps to reproduce
1. Open standalone, click check for updates

2. Along with a few updates there is a core.UI.feature 

3. It shows an error indicating editbox has conflict with two versions.

May be something to fix?

Cannot complete the install because of a conflicting dependency.
  Software being installed: UI Components of GAMA 1.7.0.201606010729 (ummisco.gama.feature.core.ui.feature.group 1.7.0.201606010729)
  Software currently installed: Dependencies of GAMA 1.7.0.201605240752 (ummisco.gama.feature.dependencies.feature.group 1.7.0.201605240752)
  Only one of the following can be installed at once: 
    Editbox Plug-in for GAML 1.7.0.201606010729 (ummisco.gaml.editbox 1.7.0.201606010729)
    Editbox Plug-in for GAML 1.7.0.201605240752 (ummisco.gaml.editbox 1.7.0.201605240752)
  Cannot satisfy dependency:
    From: UI Components of GAMA 1.7.0.201606010729 (ummisco.gama.feature.core.ui.feature.group 1.7.0.201606010729)
    To: ummisco.gaml.editbox [1.7.0.201606010729]
  Cannot satisfy dependency:
    From: Dependencies of GAMA 1.7.0.201605240752 (ummisco.gama.feature.dependencies.feature.group 1.7.0.201605240752)
    To: ummisco.gaml.editbox [1.7.0.201605240752]

**Comment by AlexisDrogoul** [comment]
Entirely my fault, I fixed #1851 and forgot to reinstall the "hidden" property `installMode="root"` for the features. Which means the previous builds will not be updatable... Sorry for that. It's fixed now, but you have to reinstall a new standalone version.
