### ISSUE TITLE
An About Dialog indicating update number/date

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1864]
Hi 

Assuming standalone is now capable of updating itself from `check for updates`, Would it be possible to have an About dialog (Help>About), that could show the latest fix updated or the date of latest update when one updates the standalone GAMA. This could be the alphanumberic code of the latest update for eg., 382329a or say latest update from: 5/June/2016 etc so that I am sure I am in Sync with latest update.

**Comment by AlexisDrogoul** [comment]
In the release, Help > Installation Details brings you this:

![gama installation details 2016-06-05 18-44-50](https://cloud.githubusercontent.com/assets/579256/15805217/ad96ece6-2b4d-11e6-9139-40b6b321bca0.png)

From there, `Updates...` or `Check for updates` will always make sure that you have the latest.
