### ISSUE TITLE
split select all/ Unselect all in export

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1865]
### Steps to reproduce
1. Open any model that has many needed and unnecessary files in includes, models folders.

2. Do a file> export> archive and click next

3. Then you have two windows: on left is folder level selection, on right is file level selection.

4. When you click select all or deselect all, the action is applied to both windows. My question is if this action be separated for both windows. 

### Expected behaviour
I would like separate selection of contents. 

### Actual behaviour
By default all are selected on the files window. now imagine if you have many files, u want to export only a few. deselecting will take u long time as you have many files. so if you click deselect all button, you lose contents on both windows. and you have to start all over again. 

### System and version 
GAMA Standalone 1.7 pre-release, MacOSX

**Comment by sriramab** [comment]
If the select/ deselect option is available only for one window, I would like to request this be applicable to the files window rather than the folder window.

**Comment by AlexisDrogoul** [comment]
Actually, we have no controls on these windows, as they are standard Eclipse components. I will check but it's really beyond what we can do...

**Comment by AlexisDrogoul** [comment]
Hi,

I have checked, and you have exactly the same dialog in Eclipse (if you export as an archive). Modifying such complex dialogs is beyond what we can propose in GAMA, I'm sorry... So I will close this request (although I perfectly understand your needs !).

Alexis
