### ISSUE TITLE
Finalization of simulations in batch mode should not be execute at once

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1867]
### Steps to reproduce
1. As same as the Inits are changed to be run sequential (Issue  #1847 ). It is better for a large simulations. Now, we have the new situation: 
2. The large simulation is not release until the finalization (after the stop condition, may be 50, 100 times)
3.

### Expected behavior
Could it be a chance to release take the result (fitness) at the end of each simulation and release then the simulation itself , to reduce the memory. #1774

### Actual behavior
If we do batch repeat;100. It is impossible to do because of memory insufficient. I know some case the exploration method need to keep the finished simulation resources, but it seem to be better in most case that finished simulations release theirs resources.

### System and version 
Gama git, win 10 , jdk 8

**Comment by AlexisDrogoul** [comment]
Hi,

What you are asking for is not possible if you want to simultaneously be able to analyse other things than simply the fitness of each simulation. There are many batch procedures where, at the end of each step (incl. repetitions), statistics are being computed, or a chart is produced, etc. In those cases, the availability of the simulations in the variable `simulations` is necessary. The only possibility we could have is to introduce a new condition (for example a new facet) to the batch experiments, specifying whether or not the simulations have to be kept in memory or not). I put @ptaillandier in copy of this one for him to give his opinion. 

Alexis

**Comment by AlexisDrogoul** [comment]
I have added a facet to experiments called `keep_simulations: true/false` . It is `true` by default and, when set to false, will record the fitness and eliminate the simulations as soon as they are finished. You should however test it before closing the issue.
