### ISSUE TITLE
halt statement and prey predator model

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1868]
### Steps to reproduce
1. Run the prey-predator model 12.

### Expected behavior
The simulation should stop when either prey or predator disappear.

### Actual behavior
The simulation does not stop. 
After some steps, the displays disappear. 
I guess that when one population disappear (i.e. when the do halt is called), the displays are disposed but not the simulation.
I tried by changing the "do halt;" by a "do pause;" and it works as expected.

### System and version 
GAMA, MACOSX, Git

**Comment by AlexisDrogoul** [comment]
`halt` should actually be removed and completely deprecated... (isn't it the case, by the way ?)

**Comment by AlexisDrogoul** [comment]
`halt` is correctly noted as deprecated (maybe a warning should be emitted, by the way). I have replaced its use by `pause` everywhere in the library of models.
