### ISSUE TITLE
interactive console focus, inspect, highlight

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1871]
I very much like the new interactive console. It comes in very handy and is a time saver 👍 
I would however like to request to add three basic functions of interaction with the simulation. These already exist with mouse click. But I think for a randomised setting of agents, it is very difficult to select the agent we want to look into detail, also applicable when using grids. it would helpful to be able to type in interactive window: inspect(agent(22)), focus(agent(22)), highlight(agent(22)) 

I think this can be very useful and saves time in not first finding an agent concerned, right clicking, and select one of the three (inspect, focus, highlight) or having to open population table and selecting one of the three.

thank you for this console 👯

**Comment by sriramab** [comment]
I know interactive console is based on gaml, but i am not sure if gaml has inspect, focus, highlight? Am I wrong?

**Comment by AlexisDrogoul** [comment]
I was wondering how long it would take for someone to ask for these features :)

For the moment, inspect, browse, and all the others output-related things are declarative statements (i.e. they are not supposed to be used as imperative statements). But of course I understand the need to use them in declarative **and** imperative ways. And, moreover, it is perfectly in phase with the enhancement in gama-platform/gama2#9 . So we'll see what can be done -- although it may take some time as handling both declarative and imperative sides is a bit complicated.

**Comment by sriramab** [comment]
As long as men are free to ask what they must, free to say what they think, free to think what they will, freedom can never be lost and science can never regress.
Julius Robert Oppenheimer

**Comment by sriramab** [comment]
I was thinking along the lines of some other text editors that I use on mac. Just that there is no difficulty in combing the declarative or the imperative and to use the already existing dialogs of inspect. 

When you put GAMA in simulation mode, I noticed that ⌘G has no key binding. ⌘G in some software is used for GoTo. Lets say  ⌘G in simulation mode could bring a search like box. In this search box you could type say 22, and then press enter, this will result in a list showing all agents in different species having index 22. So its like `GoTo Agent`. The user can click the sought agent under a particular species, this slides another window. This window could actually be the same window that GAMA currently has as- inspection window - showing all the attributes of that agent. 

At the same time, when clicking on an agent from the return list of agents, the world could zoom in to that agent or highlight it? please see video on text search, but in case of GAMA this could be agent search.

Oops could not attach a video, so a screen shot showing the ⌘G window and the results.

I rest my case on this issue :)

![thesis_latex 2016-06-08](https://cloud.githubusercontent.com/assets/12668606/15882483/3571e402-2d3f-11e6-8091-e69a7e6ad127.png)

**Comment by AlexisDrogoul** [comment]
All three statements have been defined and are now operational. It is now possible, in the interactive console **but also in normal GAML code** to use `inspect`, `highlight` and `focus_on`.

- `inspect` works with agents or list of agents (or populations) and opens either an individual editor or a browser. 
- `highlight` works with 1 agent at a time. Optionaly, a color can be passed to it in order to change the default highlight value (e.g `highlight my_species(19) color: #red;`)
- `focus_on` takes anything in parameter that can be transformed into a geometry and forces all the displays to focus on the resulting agent or geometry.

Since it can be used in any GAML code, it would be nice to build 2-3 example models to show how to use it. For example a combination of user layer and this could allow to inspect agents just by clicking of  them... etc...

**Comment by sriramab** [comment]
Great ! Thank you.

**Comment by sriramab** [comment]
Thank you for this great feature. But, Could you please check: the focus_on statement does not bring the focussed agent to the centre of the display. It is somehow brought to the bottom right of the active display window.

**Comment by AlexisDrogoul** [comment]
In Java2D or OpenGL displays ?

**Comment by AlexisDrogoul** [comment]
OK, so that's outside the scope of this issue. Java2D focus is lousy to say the least and I will open a separate issue on this.
