### ISSUE TITLE
Problem in png file with transparency on OpenGL displays

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1872]
### Steps to reproduce
1. Open models/Toy Models/Boids/models/Boids.gaml

2. Move the mouse

3. 

### Expected behavior
There is some "flickering" effect and when you run the simulation the rendering is a bit wierd (see snapshot)

<img width="649" alt="screen shot 2016-06-07 at 09 43 41" src="https://cloud.githubusercontent.com/assets/3928502/15859826/a4fbd20c-2c94-11e6-8ee8-abfe93744ee6.png">

**Comment by AlexisDrogoul** [comment]
If you look inside the model, you'll understand why. The target agent is moving with the mouse. And, of course, that interferes with the normal rendering.

**Comment by agrignard** [comment]
Yes yes I saw it, it's cool to have this feature I was just wondering why it effects the boids rendering (well I can guess that it's a kind of thread issue) but in the ideal world it shouldn't have effect.

And also about the trace I just notice a strange rendering for the boids picture (maybe related to alpha? or to my retina display?
<img width="1003" alt="screen shot 2016-06-07 at 16 26 14" src="https://cloud.githubusercontent.com/assets/3928502/15873462/ced42e0c-2ccc-11e6-8a74-59c8c6d11fcf.png">
) I mean it's not related to the mouse because it happens if I remove the event.

**Comment by AlexisDrogoul** [comment]
Probably due to the z-index problems. Trace and actual displays have the same z-index, probably. Not a big deal, as far as I'm concerned.

**Comment by AlexisDrogoul** [comment]
Actually, I was wrong. All `.png` files exhibit the same problem: their transparent parts are taken into account (for example wrt to the sky image), but not between images in the same layer, which produces these strange artifacts. Adding a z-index allows to see the problem more clearly. I have absolutely no idea on how to solve this, and I suspect it has been around for a long time. The same problem appears for the Ant models, by the way.

**Comment by AlexisDrogoul** [comment]
OK. Found it (almost). 

Seems that one of these (or all of these) calls are needed:

```
		gl.glTexEnvi(GL2.GL_TEXTURE_ENV, GL2.GL_TEXTURE_ENV_MODE, GL2.GL_MODULATE);
		gl.glEnable(GL2.GL_ALPHA_TEST);
		gl.glAlphaFunc(GL2.GL_GREATER, 0.1f);
``

After that it works well.

**Comment by AlexisDrogoul** [comment]
I have committed some changes that improve the rendering of png files with transparent parts. It's far from perfect, but it works. Regarding the "trace", I think there are not a lot of things to do, as both alpha values and mipmap generation are at play there, rendering (when zooming on small images like these ones) a "moiré" effect...

**Comment by AlexisDrogoul** [comment]
I close this issue since almost everything is fixed. Only the interferences between images which are not and will probably never be....
