### ISSUE TITLE
Video projection mapping

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1873]
For different reason especially if we want to display GAMA simulation on a "table" it would be at some point useful to be able to warp the display onto any flat surface. 

This is done in Processing with this library for instance
http://keystonep5.sourceforge.net/

I think it's not a big big deal to do it in GAMA (only for 2D rendering for the time being)

I did not dig it too much but I guess/hope their is already some library to do it in java2D and Opengl.

**Comment by AlexisDrogoul** [comment]
Is it not possible to do it at the OS level ? Why include it in GAMA (i.e. what would you use if you want to project other images -- not necessarily from GAMA) ?

**Comment by agrignard** [comment]
For a picture why not doing it at the OS level but I mean for real time simulation? I used keystone in processing it's quiet easy and intuitive to use , you just move the 4 corner of your display to mathc the surface. I'll try (not now) to see how to do it in GAMA

**Comment by AlexisDrogoul** [comment]
Like #1897 , I move it to gama-experimental.
