### ISSUE TITLE
⌘+F flips the world

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1874]
### Steps to reproduce
1. Open any model, run the simulation

2. press ⌘+F 

3. the display is flipped 

### Expected behavior
-

### Actual behaviour
I wanted to search for something and pressed ⌘F (find) ...but to my surprise flipped the world. Not sure if this was meant to be so.

GAMA 1.7beta, MacOSX Mavericks, java 8

**Comment by mazarsju** [comment]
Hi Srirama,

Indeed, I added the "F" command to "Flip" the camera z axis, when the camera was not finished (cf : https://github.com/gama-platform/gama/wiki/Displays). I think I can remove this command now indeed.
