### ISSUE TITLE
change in gaml code and random seed gives different results

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1877]
### Steps to reproduce
1. Open a grid model, write a small piece of code: `random_cell <- one_of(cell);` colour it red or blue or any

2. place a seed in experiment, i used 0.5140073008712904

3. run the model and take note of the cell.

4. add this code ( i checked only this code), i placed it inside init block of cell grid.
my_4_ordered_neighbors <- neighbors sort_by (each direction_to self);

5. run the model and take note of the random_cell, its different. But Seed is the same.

### Expected behaviour
the randomly selected cell should remain same with given seed.

### Actual behaviour
random_cell  changed when I added just one line of code, as in step 4 above.

### System and version 
GAMA GIT and GAMA, java 8, mac mavericks

**Comment by AlexisDrogoul** [comment]
The call to `neighbors` will generate a call to the random number generation in order to shuffle the results. So, yes, the result is as expected...

**Comment by sriramab** [comment]
Yes, the neighbours (my_4_ordered_neighbors) can change, but why does random_cell change? :(

**Comment by AlexisDrogoul** [comment]
There are two things here in your code:

1) The seed should probably be in the simulation if you want it to be repeatable.
2) If you have a model with only `cell random_cell <- one_of(cell);` in `global` and nothing else, it will generate only one call to the random number generator. Now, if you add `my_4_ordered_neighbors <- neighbors sort_by (each direction_to self);` in the `init` section of cells, you will generate N calls to the random number generator (one for each call to `neighbors` in each cell), followed by the one for `one_of`. 

So it is not surprising if you end up with a different random cell.

**Comment by AlexisDrogoul** [comment]
Basically, if you change your model in any ways and if this change introduces a call to a random number (either directly or indirectly), you get a different model (with respect to the sequence of random numbers). So I close this issue if you dont mind...
