### ISSUE TITLE
unable to scroll error window

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1879]
### Steps to reproduce
1. A bit funny to say, but ... do some deliberate errors in your model, preferably in a grid model where a value cannot be calculated for all cells. run the model and the error window will show up. 

2. If you have more than one error in your error window. click the expand arrow on your top most error. 

3. Now you cannot scroll the error window anymore, you may be able to scroll the first error (the error you expanded) but not the subsequent  errors. 

4. if you collapse the first error, then u can scroll again. 

5. Is it necessary to be able to scroll through two errors. Yes, I think so. For comparison purpose it is useful. It helps to see if both errors (or more) are resulting from the same mistake in the code. 

### Expected behaviour
Should be able to scroll error window and be able to expand and collapse error list at will.

### Actual behaviour
Scrolling is locked as soon as you expand one error.

### System and version 
GAMA standalone, java 8, mac Mavericks.

**Comment by AlexisDrogoul** [comment]
Hi,

I can't reproduce it. Please notice that you have 2 scroll bars available (not visible on Macs, though). On inside the error to scroll it if necessary, one completely at the far right for scrolling through errors.

Alexis

**Comment by sriramab** [comment]
Could you please try this. Make a grid with 4 neighbors configuration. Now in the code, create a variable or a few and ask for neighbors as if with eight neighbor configuration. For example, suppose u create a 4 neighbor configuration of a grid, do these :

float cell_value <- neighbors[4].grid_value
float cell_angle  <- cos(neighbors[5].grid_value)
float cell_sum  <- sum([neighbors[5].grid_value,neighbors[2].grid_value])
float cell_mean  <- mean([neighbors[5].grid_value, neighbors[2].grid_value])
float cell_sin  <- sin(neighbors[5].grid_value)
float cell_combine<-cell_value+cell_angle+cell_mean;
this will give u 6 errors, now u can try scrolling as I mentioned in the first report.

**Comment by AlexisDrogoul** [comment]
I did exactly this, and obtained a consequent number of errors, but I can't, still, reproduce the behavior you describe (see attached zip file, which is actually a video).

[screencast 2016-06-11 15-59-03.mp4.zip](https://github.com/gama-platform/gama/files/310165/screencast.2016-06-11.15-59-03.mp4.zip)

**Comment by sriramab** [comment]
Hmm Strange. May be something got fixed meanwhile? I am using 10 days old GAMA. I will check again.

**Comment by sriramab** [comment]
Hi Alexis, Please see attachment, also a video. I am unable to scroll. 
My diagnosis is: in my grid I have like 9000 cells. I know for sure the error will be in at least 5000 cells. Now in the error, it lists all the cells where error has occurred. So listing these 5000 cells, i think in current GAMA, happen on one line. And someone the lines allocated for printing 5000 cells is not happening in multiple lines (as you will see, when I expand the top error, there is almost 10cm of blank screen space before the next error is printed. So all errors are  happening only in one line? 

Somehow this space allocation is restricting the scrolling behaviour ? I don't know how to say in more IT language. :) 

My idea is that you have tried a very small gird, may be 10 by 10?? and therefore you do not see this error. May be you should try it on 100 by 100 and see if you can replicate this behaviour. If not, i will send you my file. 

[screencast 2016-06-11 .mp4.zip](https://github.com/gama-platform/gama/files/310197/screencast.2016-06-11.mp4.zip)

**Comment by AlexisDrogoul** [comment]
I cannot reproduce this. Or, more accurately, I can reproduce it if my view is not wide enough. But if I give it a sufficient width, I can scroll both within and between the errors. The listing of errors is of a fixed dimension for speed concerns.

**Comment by sriramab** [comment]
Yes, I think width is of concern. Because I have like 300 hundred error or 500, I don't remember now.... and GAMA shows all the similar errors in one line, the width will never be sufficient and hence the inability to scroll. 
I think we are both on the same page that ill fitting width is the issue.
I rest my case.

**Comment by AlexisDrogoul** [comment]
Actually, I was speaking about the width of the view. Can you try again on a fresh (or the Git) version ? If you enlarge your view, you have normally access to the 2 scroll bars: one for the error itself, the other one for scrolling between the errors. Error "items" have a fixed width anyway, so if you enlarge your view sufficiently they will not cover all the width.

**Comment by AlexisDrogoul** [comment]
Yet another possible enhancement. If you can test it...

**Comment by AlexisDrogoul** [comment]
And a second one to test also. On this simple example:

```
model new2


global
{
}

grid c neighbors: 4 width: 100 height:100 
{
	float cell_value <- neighbors[4].grid_value;
	string cell_angle <- nil + "";
	float cell_sum <- sum([neighbors[5].grid_value, neighbors[2].grid_value]);
	float cell_mean <- mean([neighbors[5].grid_value, neighbors[2].grid_value]);
	float cell_sin <- sin(neighbors[5].grid_value);
}

experiment e;
```

the new architecture multiplies the speed of error throughput by an estimated factor of 1000...

**Comment by AlexisDrogoul** [comment]
Several new patches have improved the previous solutions. I know that the original bug (no scrolling) is not yet reached completely (it is better handled, but still a bit funny to maneuver). However, the comfort of runtime errors reporting is clearly improved (I think).

**Comment by AlexisDrogoul** [comment]
Shall we close this one ? (it is working quite well in my configuration).

**Comment by sriramab** [comment]
yes please.
