### ISSUE TITLE
Time to release V1.7.0 ?

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1881]
With the fact that Travis (and Tycho builds) now produces correct releases, and with the number of issues going down, I think it is now time to call it a day and to have a first official release of GAMA 1.7.

One point is that the documentation has still some issues ( @mazarsju, any update on this ?) and is a little bit lagging behind in terms of functionalities introduced recently. But I'm not sure it can be improved in the next weeks.

Another point is that the network ( #1343 ) and serialization ( #739 ) plugins are not quite ready for prime time (wrt the code, of  course, but also documentation and examples), and that the enhancements for the camera ( #1878 ) are not addressed. Are there any news about these ? 

All the other issues are either minor or depending on a large refactoring of GAMA itself, so I'm quite confident we will not address them immediately. 

So who would be in favor of using the current release made by Travis as the official one ?

**Comment by sriramab** [comment]
Hi, We a bunch of colleagues would really like issue gama-platform/gama#742 be addressed if possible. This is going to win scores of people towards GAMA.

**Comment by AlexisDrogoul** [comment]
Hi, gama-platform/gama#742 has now been superseded by gama-platform/gama2#12 . And yes, it is something we are looking, but dont expect a testable version too soon...

**Comment by agrignard** [comment]
Hi,

My opinion

I think it's important that the network plugins WORKS in the release (udp,
tcp, mqtt). For the serialization I don't know in detail what happens there
but it seems to be tricky no? For the big camera issue gama-platform/gama#1878 there is
several issues in one and lots of change to do it. I am afraid (and quiet
sure) it will introduce other bug, so for the camera I will say that "le
mieux est l'ennemi du bien".

I am busy until Thursday but I can spend some time at the end of the week
on network (and why not on camera but I really don't want to introduces new
bug)

Arnaud

**Comment by AlexisDrogoul** [comment]
What is the state of the network and serialization plugins ? @benoitgaudou, @gnoubi, @agrignard

**Comment by agrignard** [comment]
Hi there,

The only thing I can say from my side, is that I did not commit anything in
this plugin since the coding camp and the last update on this topic from me
is on the 22nd of June:

https://github.com/gama-platform/gama/issues/1343#issuecomment-224066219

I don't know for the other but I have the feeling that Network and
Serialization is still in a very "experimental" state maybe we could set a
meeting the 4 of us to know exactly where we are and prioritize the work ?

Arnaud

**Comment by agrignard** [comment]
BTW I know I already ask this question once (2 months ago) but still... how
to have network running in the current version of GAMA?

I did this in gama.product:
1. In gama.product Open Contents tab
2. add ummisco.gama.feature.serialize and ummisco.gama.feature.network.

But I don't see the model in the plugin models in GAMA

What do I miss? Maybe it's time to start a wiki page somewhere to document
how to make this stuff working?

Arnaud

**Comment by benoitgaudou** [comment]
Hi,

I just test to add the 2 plugins (network and serialize) in the feature.xml
of ummisco.gama.feature.core.extensions. After 1 or 2 synchronize, when I
run and update the model library in my current workspace, I can appear the
network models.

As far as I am concerned, the serialize plugin has not been modified (I
just hide the keywords and models of the serialize plugin, in order that
the network plugin can be added to the release  without having visible
unfinished GAML keywords).

Cheers

Benoit

2016-08-01 16:42 GMT+02:00 Arnaud Grignard notifications@github.com:

> BTW I know I already ask this question once (2 months ago) but still... how
> to have network running in the current version of GAMA?
> 
> I did this in gama.product:
> 1. In gama.product Open Contents tab
> 2. add ummisco.gama.feature.serialize and ummisco.gama.feature.network.
> 
> But I don't see the model in the plugin models in GAMA
> 
> What do I miss? Maybe it's time to start a wiki page somewhere to document
> how to make this stuff working?
> 
> Arnaud
>

**Comment by AlexisDrogoul** [comment]
Coming back to this issue of having an "official" version -- the current one is normally now ready for prime time (esp. in the compilation/validation, which has been revamped and is normally much more stable). It needs however to be tested on the following points:
- [x] headless run
- [x] addition / removal of plugins
- [x] update of the platform itself from the OVH website (see gama-platform/gama#1969 )

Who can run these tests to ensure the version is stable enough to be released ? Afterwards, we need to issue some mails (to the usual mailing-lists) detailing the changes/additions (see https://github.com/gama-platform/gama/wiki/NewVersionChanges), as well as announcements on Facebook/Twitter

**Comment by AlexisDrogoul** [comment]
Pretty much of the above tasks have been done. RC1 is quite stable, and RC2 is around the corner. Time to remove this issue !

**Comment by agrignard** [comment]
What about testing a RC2 soon?
