### ISSUE TITLE
init parameters vs simulation parameters

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1883]
I am wondering (we already had this discussion at the last coding camp) if there is a way to differentiate initialization parameters vs runtime parameter.

e.g in a schelling model:

width/height of the environment and density of people are initialization parameter (when you change that during the simulation they have no effect)
similarity and perception are runtime parameter (you can use them during the simulation)

I don't think it's a good idea to add a new facet by default because it may complexify the language but at some point it can be nice to be able to differentiate them.

**Comment by AlexisDrogoul** [comment]
We should not add another facet, I agree. The two strategies that can be used here:

- either you specify it in the name or using "unit:" 
- or you a user_input in the _init_ action of the experiment

**Comment by AlexisDrogoul** [comment]
By the way, I have added a simple example (in `Features>Init Action>Init Action.gaml`) to show how to input parameters **before** any simulation is run. I close this issue, then.
