### ISSUE TITLE
No image on welcome webpage in the release

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1891]
### Steps to reproduce
1. Launch GAMA.

### Actual behavior

The splash screen witht the GAMA logo does not appear

### System and version 
GAMA nightybuilt, MACOSX

**Comment by AlexisDrogoul** [comment]
Cannot reproduce it on my locally built version (with the same script). I will test on the downloaded version.

**Comment by AlexisDrogoul** [comment]
I downloaded the nightly build and it works fine.

**Comment by benoitgaudou** [comment]
Sorry I was unprecise: it is not the splashscreen, but  the GAMA logo in the welcome.html page.
(btw the Website and Documentation seem to link the same page)

**Comment by AlexisDrogoul** [comment]
Yeah. Right. I can reproduce it. The fact that the two links point to the same page is because there is still no page for the documentation on the website. See: https://github.com/mazarsju/gama_doc_17/issues/40
