### ISSUE TITLE
"Collapse All" strange behaviors

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1893]
### Steps to reproduce
1. Open a model
2. Right-click, Folding > Collapse All
### Expected behavior

I was expecting to have 1 line per top level statement, i.e. global, grid, species and experiment.
### Actual behavior

I get only 1 line for the global and the `+` button does not expand this line.
### System and version

GAMA nightybuilt, MACOSX

**Comment by AlexisDrogoul** [comment]
Cannot reproduce it on my locally built version (with the same script). I will test on the downloaded version.

**Comment by AlexisDrogoul** [comment]
I downloaded the nightly build and it works fine.

**Comment by AlexisDrogoul** [comment]
Still got the issue ?

**Comment by benoitgaudou** [comment]
Yes, I still got it.
Benoit

2016-06-27 12:35 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
We have very little control on the "Collapse all" / "Expand all" commands. There seems to be a miscomputation, somewhere, on the nodes to keep collapsed when expanding a super-node, but it seems quite complicated to override this behavior.

**Comment by AlexisDrogoul** [comment]
I've come back to this issue several times, but without luck. The miscomputation of nodes cannot be overridden, so it would require a complete new implementation. Please reopen if it something vital for you !
