### ISSUE TITLE
"No simulation running" appears funny when we launch the application (Windows)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1895]
See the following screenshot :

![image1](https://cloud.githubusercontent.com/assets/12977635/16300444/2c40779a-396a-11e6-9e52-5e874c4dea43.png)

**Comment by sriramab** [comment]
Yes, I have also experienced this on windows installation. When I load the experiment, there is no play pause step button. It just sits idle and user does not know what to do, no error no prompt is shown for any advice.

**Comment by AlexisDrogoul** [comment]
@sriramab no, this is not the same bug reported here. This one is purely cosmetic and due to the incapacity of Windows to give a correct height to toolbars if there is no icons. I'll try to find a solution (probably with an invisible icon).
