### ISSUE TITLE
Gama icon is not displayed anymore

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1896]
Windows problem maybe ?

![image1](https://cloud.githubusercontent.com/assets/12977635/16300597/e826135c-396a-11e6-82dc-56f2d5e14e5d.png)

**Comment by AlexisDrogoul** [comment]
To be confirmed by others. On MacOS X the icon is displayed.

**Comment by hqnghi88** [comment]
The icon in taskbar is displayed in release GAMA1.7-Win.x64_06.23.16.5415f2e.zip but the icon in the title bar is not displayed. The exact issue can reproduce in git version.

**Comment by tcquang** [comment]
I have the same results with Nghi, but I have tried with the exported
product from Eclipse and the Git version.

2016-06-23 23:58 GMT+07:00 hqnghi88 <notifications@github.com>:

> The icon in taskbar is displayed in release
> GAMA1.7-Win.x64_06.23.16.5415f2e.zip but the icon in the title bar is not
> displayed. The exact issue can reproduce in git version.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gama-platform/gama/issues/1896#issuecomment-228114055>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALRxbDp_1JSCbySevCuH4u7b_QY35-pUks5qOrskgaJpZM4I8rtU>
> .
>



-- 
Quang Chi TRUONG
Tel: 0939388153

**Comment by mazarsju** [comment]
In the git version, the GAMA icon appears normally now

**Comment by tcquang** [comment]
The released version also works well.
