### ISSUE TITLE
Sharing GAMA output in a Higher level video mapper

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1897]
Very raw idea...

I'd like to display GAMA output on a table but... there will be other output on this table (coming from other apps such as processing , unity, etc...)

The idea would be to have an super application that can mix all the output in one. There are  some already existing solutions for that such as http://www.madmapper.com/ and http://syphon.v002.info/ .

So the purpose of this issue/enhancement is to be make GAMA able to communicate with those video mapper.

**Comment by AlexisDrogoul** [comment]
Hi,

I think this does not really belong to the core gama issues. Probably it will be handled by a plugin based on https://github.com/Syphon/Java, and in that case it's better off to gama-experimental (where I'm going to move the issue).

Alexis
