### ISSUE TITLE
closest_to VS with_min_of distance_to

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1902]
### Steps to reproduce
1. In a model with grid land agents. From on land agent I want to get the closest one fulfilling a condition.
I tried with the closest_to operator and the with_min_of (distance_to)
			closest_village <- ((land where (each.type = 1)) ) closest_to(self.shape);
can return nil

			closest_village <- ((land where (each.type = 1)) with_min_of (each distance_to self));
works everytimes.

The model is : 

model test1

global {
//	geometry shape <- rectangle(20,16);
	map<int,rgb> COLORS const: true <- map([0::#blue, 1::#red, 2:: #green, 3::#darkgreen]);
	
	init {
		ask land {
			do updateProba;
		}
	}
	
	reflex t {
		ask land {
			do updateProba;
		}		
	}
}

grid land width: 20 height: 16 neighbors: 8 {
	int type <- rnd(1)+2;
	rgb color <- COLORS[type];
	
	float proba_animals;
	land closest_village;	
	
	init {
		// Init the lands
		if(grid_y = 15) or (grid_x = 13) {
			type <- 0;
			color <- COLORS[type];
		} 
		
		if((grid_x = 4) or (grid_x = 5)) and (grid_y = 14) {
			type <- 1;
			color <- COLORS[type];			
		}
	//	closest_to(a_container,a_geometry)
		// create animals

	}

	action updateProba {
		if(type > 1) {
//			closest_village <- (land where (each.type = 1)) closest_to(self);
			closest_village <- ((land where (each.type = 1)) ) closest_to(self.shape);

//			closest_village <- ((land where (each.type = 1)) with_min_of (each distance_to self));
			if(closest_village != nil) {
				

			write "" + self + "clo " + closest_village;
			float dist_village <- self distance_to(closest_village);
			proba_animals <- 1 / dist_village;
			}	else {color <- #yellow;}		
		}		
	}

	aspect closest {
		draw line([self,closest_village ]) color: #black;
	}
}

experiment test1 type: gui {
	output {
		display d {
			grid land lines: #black;
			species land aspect: closest;
			
		}
		display d2 {
			species land aspect: closest;
		}		
	}
}

### Actual behavior
The model colors some lands into yelloww when they have troubles.

### System and version 
JADS nightybuilt, MAC OSX

**Comment by ptaillandier** [comment]
It is linked to the use of the closest_to operator with the grid topology. 
If your write for line 64: using topology(world){closest_village <- ((land where (each.type = 1))) closest_to (self.shape);} it works well.

**Comment by benoitgaudou** [comment]
Hi,
Ah OK thanks.
But whatever the topology is, is it expected that:  

((land where (each.type = 1)) ) closest_to(self.shape)

can return nil ?

**Comment by ptaillandier** [comment]
No, it should not return nil ;). It is a real bug... but at least, we know that it is linked to the way the closest_to is computed with a grid topology.
