### ISSUE TITLE
website - syntax error

### ISSUE THREAD

**Issue by nbecu** [gama-platform/gama#1904]
Hi

On the website page 
http://vps226121.ovh.net/references#WorkspaceProjectsAndModels

The title is "Workpace, Projects and Models"
instead of "Workspace, Projects and Models"
Cheers

**Comment by mazarsju** [comment]
It's corrected. 
Note that if you find other errors like this, you can modify it directly in the wiki page (https://github.com/gama-platform/gama/wiki/WorkspaceProjectsAndModels), and the modification will be reported to the website for the next update.

Cheers !
