### ISSUE TITLE
Task tags TODO - FIXME

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1906]
Hi,

Is it possible to have a task view in GAMA. Similar to what already exists in Eclipse. This could help in using task tags within GAMA. I would like to request this feature (unless it already exists and I missed it)

This will help in having % TODO, % FIXME tags which are useful in collaborating and sharing gama models.

If possible to have those markers, red exclamation mark in the task view for % FIXME tags. 

thanks
Srirama

**Comment by AlexisDrogoul** [comment]
It is already the case. If you type TODO or FIXME in a comment, it will be marked with a special marker. However, there won't (and can't, for different reasons) be any difference between TODO and FIXME markers.
