### ISSUE TITLE
add_point 

### ISSUE THREAD

**Issue by nbecu** [gama-platform/gama#1907]
### Steps to reproduce
1.
write line([{0,0},{0,1}]) add_point {0,2};
'LINESTRING (0 0, 0 2, 0 1)'

### Expected behavior

We should expect that the point is added at the end of the line 
->(0 0,  0 1, 0 2)'

### Actual behavior
But instead the point is added in the middle of the geometry
--(0 0, 0 2, 0 1)'

### System and version 
GAMA 1.7

**Comment by AlexisDrogoul** [comment]
Right. `add_point` is a bit misleading in that particular case, in that (1) this operator tries, by default, to create a ring (or a contour) from the resulting point collection; (2) the points of geometries are always ordered in a particular orientation (clockwise) to facilitate further operations like computing the normals of geometries in 3D operations. 

I have changed the documentation of `add_point` to indicate this. 

And in your case, the correct operation would be:
```
geometry g <-  line([{0,0},{0,1}]);
g <- line (g.points +  {0,2});
```
