### ISSUE TITLE
Separator button visible in the UI on Windows

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1910]
cf image : 

![image1](https://cloud.githubusercontent.com/assets/12977635/16572800/ee3f1704-4296-11e6-9e09-bc4ccb76a2e4.png)

**Comment by AlexisDrogoul** [comment]
Only on Windows. And there is a choice to make between this and #1895, because of the stupid way with which Windows treats toolbars...

**Comment by mazarsju** [comment]
Mmm I see... It surprises me that there is no possibility to fix a minimum height for the "No simulation running" button though...

**Comment by AlexisDrogoul** [comment]
There are no possibilities in toolbars. The height of toolbars, on Windows, is computed (at creation, not dynamically) from the height of the ContributionItems that have an icon. No icons means you use the default height (16, I believe).

Anyway, I've found a hack that disables the item while retaining the icon for computations. We can close this issue, I guess.

**Comment by mazarsju** [comment]
yes, works fine now !
