### ISSUE TITLE
The syntax []  to access the list of values of an ODE variable does not work anymore

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1913]
### Steps to reproduce
1.Launch the experiment of the model Plugin Model/Ordinary Differential Equation/ContinousCurves.gaml

2.
1 occurence in Simulation 0 at cycle 0: Java error: wrong casting
in data 's_mathsc' color: °red value: my_SEIR_maths[0].Sm[] marker: false ;
ClassCastException: java.lang.Double cannot be cast to msi.gama.util.IContainer$Addressable
gaml.additions.GamlAdditions$301.run(GamlAdditions.java:340)
msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:83)
msi.gama.outputs.layers.charts.ChartDataSourceUnique.inferDatasetProperties(ChartDataSourceUnique.java:102)
msi.gama.outputs.layers.charts.ChartDataSourceUnique.createInitialSeries(ChartDataSourceUnique.java:122)
msi.gama.outputs.layers.charts.ChartDataStatement.createDataSource(ChartDataStatement.java:160)
msi.gama.outputs.layers.charts.ChartDataStatement.privateExecuteIn(ChartDataStatement.java:208)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:44)
when applying the internal_at operator on 0.0658 and []
in data 's_mathsc' color: °red value: my_SEIR_maths[0].Sm[] marker: false ;
in 
in agent Simulation 0

### Expected behavior
Tell us what should happen (include all relevant expectations)
It should work after the CC and before the re-organization of Grammar project.

### System and version 
GAMA GIT, windows 10

**Comment by AlexisDrogoul** [comment]
Is it the case for every example or just this one ?
