### ISSUE TITLE
Move all website, doc generation support files to GitHub

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1915]
This issue actually should belong to the newly established gama.doc repository (https://github.com/gama-platform/gama.doc), but it is still in its infancy... All the files needed to generate the website (scripts, databases, etc. ), as well as the projects related to the generation of the documentation (https://github.com/gama-platform/gama/tree/master/msi.gama.documentation) + the actual wiki files (accessible through git with https://github.com/gama-platform/gama.wiki) should be hosted in https://github.com/gama-platform/gama.doc so that anyone can contribute to fixing documentation related bugs. 

Moreover, these different subprojects should be bundled and accessible as Eclipse projects (not a great deal) so that we can keep the same workflow as the one we use for developing GAMA itself.

This also means that the website support files on OVH server needs to be updated regularly and continuously (probably through a cron script ?). 

I consider this reorganization as a high priority task, given the difficulty we have, currently, to update the website + doc.

**Comment by mazarsju** [comment]
@langthang I'll need a bit your help for this, I'm a bit lost in all this ^^'

The idea is to gather all the work you have done to this new "gama.doc" repository. So here is what I did and how I see things (tell me what is your opinion about that) : 
- I created a new repository called "gama.website" in which I put your bitbucket project "gamaws". This project has 2 branches : the master and dev (the dev modifications have to impact the dev website http://gamawsdev.langthang.me/). I changed the "gm_wiki" folder to a submodule of this repository, synchronized with the wiki repository (https://github.com/gama-platform/gama.wiki.git)
- I created an other repository called "gama.websiteGenerator" in which I put your bitbucket project "GamaWSBuildDB".
- I created a 3rd repository called "gama.dev" which contains nothing new for the moment, just a gathering of 3 submodules : 
  - One pointing on gama.website
  - One pointing on gama.websiteGenerator
  - One pointing on gama.wiki (Not really important, just to gather the "doc" part)

What is your opinion on that ? I guess you will have to change a bit the generation scripts "gamaws.sh" and "gamawscheckout.sh", no ?

I tried to summarize in this wiki page all the workflow : https://github.com/gama-platform/gama.doc/wiki. Do not hesitate to edit it if you see some errors.

@AlexisDrogoul @benoitgaudou : About the current project "documentation", what do you think is the best to do ? Removing it from the "gama" repository to put in in the "gama.doc" repository directly ? Or should it be integrated to "gama.doc" repository as a submodule ? (and the project documentation should be then in an other repository ?)

**Comment by AlexisDrogoul** [comment]
Hi,

As I see it, we should have one and only one repository with different folders for the different "modules" (website, website generator, wiki, wiki generator). In turn, these folders will eventually become Eclipse projects (just a matter of adding a .project file somewhere, so that we can have the same workflow as when we work on the code.
Additionally, this will only create one issue tracker (and not several, probably related, which might greatly confuse the users). 

Alexis

**Comment by mazarsju** [comment]
@langthang do you think Alexis' proposal is possible ? By tuning a bit the gamawscheckout.sh / gamawsdevcheckout.sh on the OVH server ?

**Comment by AlexisDrogoul** [comment]
So what is the state of this "issue" ? Are all the documentation files now on the new repo ?

**Comment by mazarsju** [comment]
The repo is now composed with 2 folders : one containing the Java project that can build the database, and one containing all the content of the website.
I was first thinking on adding a submodule containing the wiki content, but I have some problems with updating it, so maybe leaving it like this will be simpler for everybody (same for the current "documentation" java project. Maybe it is simpler to keep it in the main gama-platform repository).

All the instructions & documentation about the repository "gama-doc" can be read here https://github.com/gama-platform/gama.doc/wiki.

So if it is ok for you, we can close this issue.
