### ISSUE TITLE
"Minimum duration of a cycle" does not work anymore

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1917]
### Steps to reproduce
1. Launch an experiment

2. Change the value of the slider "minimum duration of a cycle"

### Expected behavior
The speed of the simulation should slow down...

### Actual behavior
But it does not.

### System and version 
GAMA Git, Windows 10

**Comment by jakofdarts** [comment]
Hi everyone,

I am running GAMA Platform - V1.7.0 and yes, the minimum duration of a cycle still does not work.
(I'm running GAMA on a macOS Sierra 10.12 with Java 1.8.0_65)

Is there a way to specify the minimum cycle duration within the model?

Many thanks,

Jacopo

**Comment by AlexisDrogoul** [comment]
Hi,

Can you tell more precisely what doesn't work in your case ? Because it's working well on my computer. And, by the way, you can specify it in an `experiment` by setting the value of its `minimum_cycle_duration` attribute. Takes value in seconds, but you can use units to specify smaller values, of course (e.g. `minimum_cycle_duration <- 10#ms`).

Alexis

**Comment by jakofdarts** [comment]
Hi, in my case if I try to set the minimum duration through the slider in the simulation perspective the speed of the simulation does not change.

By the way specifying the attribute within the experiment works for me as well.

Jacopo

**Comment by nordie69** [comment]
Hi, I can confirm, that using this slider has no effect on my simulation. I have implemented a small workaround, which seems to do the job actually.

_....
experiment testslider type:gui {
  float minimum_cycle_duration <- minimum_cycle_duration;
  parameter "Cycle duration [s]:" var: minimum_cycle_duration category: "Simulation";
....
}_

Stefan

**Comment by nordie69** [comment]
I can confirm, that with the actual latest release, this problem doesn't exist any more.

Stefan
