### ISSUE TITLE
Enrich listened events for event layers

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1918]
I will like to have the possibility to define as listened events:
- right-click on the mouse
  - combination of listened events: mouse click + one key pressed for example.

**Comment by AlexisDrogoul** [comment]
I understand -- but how to deal, then, with already registered "default" events for key+mouse ? (ctrl-click, alt-move, ctrl-move, etc...) ?

**Comment by ptaillandier** [comment]
We can just replace the default "event" by the new defined one.
