### ISSUE TITLE
Problem with ExperimentClock/SimulationClock and time/current_date information display

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1921]
### Steps to reproduce
1. Open one of the Model Library/Features/Date and Times models

2. Load the experiment and run one step

### Expected behavior
If you click on the cycle elapsed green rectangle, you should either have the current time (model simple : 1h) or date (something like 2011...)

### Actual behavior
but you have 1 second

The problem is that the starting time/current date/time/step are defined in the simulation clock (at the beginning of the model) and not in the experiment clock (used to display the information).

I not sure that there is a "good" solution to this problem.... but we should find one.

### System and version 
Git version

**Comment by AlexisDrogoul** [comment]
Yep. Complicated. And I'm not sure there is a "general" solution. One workaround would be to use the "status" statement to manually display the current date / time.
