### ISSUE TITLE
possibility to choose between slider or input box parameter interface for int and float values

### ISSUE THREAD

**Issue by nbecu** [gama-platform/gama#1922]
### Steps to reproduce
1.
model parameters that are float or int and thathave min and max, appear in the simulation perspective whith a slider input button.

It would be useful to be able to display the parameter input, with an input box such as it appears when it doesn't have a min and max

### Expected behavior
adding a facet   
slider:true or false

### System and version 
Gama 1.7

**Comment by AlexisDrogoul** [comment]
The `slider:` facet (which accepts a `bool` value) has been added to `parameter`.
