### ISSUE TITLE
"internal facets" should not be present in the documentation

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1925]
There is a "mouse_location" facet of the "event" layer... This facet need a string value (?!?!?). I don't think this is relevant...

**Comment by mazarsju** [comment]
"mouse_location" is in fact an "internal facet", that should be hidden for the user. The real issue is that those "internal facets" should not be present in the documentation.

**Comment by AlexisDrogoul** [comment]
Moved this one to the gama.doc tracker, as internal facets are not shown in the online/hover documentation.
