### ISSUE TITLE
Using Temurin 17.0.10 or 21.0.2+13 on macOS Sonoma breaks the UI of GAMA

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#193]
**Describe the bug**
When using either the 17.0.10 or 21.0.2+13 (and further) versions of the [Temurin](https://adoptium.net) JDK on macOS Sonoma, the UI of GAMA appears completely blank save for some icons. 

<img width="512" alt="NEW_WS - Gama 2024-06-04 19-27-31" src="https://github.com/gama-platform/gama/assets/579256/7febb829-0873-4d36-94ee-df4f6f84eb3e">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - PC Model: MBP M3
 - GAMA version: 2024-06
 - Java version: 17.0.10 or 21.0.2+13

**Additional context**
This bug is known and tracked here: https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012 ; only known (but possibly incomplete) fix is to wait for Eclipse 2024-06 (4.32).

**Comment by lesquoyb** [comment]
@RoiArthurB the rc1 of 2024-06 is available, could we already use it in the release process so we can check if it fixes it and/or adds new issues ?

**Comment by lesquoyb** [comment]
@AlexisDrogoul could you try the release made with 2024-06 and jdk 21 [here](https://github.com/gama-platform/gama/actions/runs/9558208245/artifacts/1611157835) ?

**Comment by lesquoyb** [comment]
I tested on sonoma with 21.0.3+9 and it works properly
