### ISSUE TITLE
alpha channel in "draw" statement in overlay is not computed

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1930]
Ex : 

```
overlay "Legend"
            {
            	draw square(5) color:#transparent;
            }
```

The square will have no transparency.

**Comment by AlexisDrogoul** [comment]
Actually, it works. But if you define an overlay without transparency, the background will be black (and your square will not be visible).

Something like:

```
overlay "Legend" transparency: 0.5
            {
                draw square(5) color:#transparent;
            }
```

will achieve what you want.
