### ISSUE TITLE
Allow some chart facets to be updated 

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1932]
All the facets x_label, x_chart_labels, x_tick_units etc... are not updated. So an adaptative scale is not possible to implement.

**Comment by AlexisDrogoul** [comment]
Most of these variables are computed once when creating the chart, and I dont know ( @pcaillou ?) if it would be possible to compute them at every refresh.

**Comment by AlexisDrogoul** [comment]
I've corrected the problem displayed in #1938, but I dont think the update of chart parameters can be implemented simply anytime soon, as they are all used in the `init(IScope)` method of ChartOutputs.

**Comment by AlexisDrogoul** [comment]
Subsumed by #2210
