### ISSUE TITLE
Experiment: raise warning when the initial value is not in the among values

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1935]
### Steps to reproduce
1. In an experiment, when such a parameter is defined:
parameter "my_param" value: my_var <- "a" among: ["b","c","d"];

### Expected behavior
Have a warning to warn that the initial value is not in the list.

### Actual behavior
The variable takes the first value of the among list, without warning.

### System and version 
MACOSX GAMA JTD release

**Comment by AlexisDrogoul** [comment]
This issue has been fixed. The warning is now raised. I have also fixed one model in the library where the batch experiments played with bad `init:` values.
