### ISSUE TITLE
To be able to declare local variable inside a display scope

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1936]
It would be nice to be allowed to declare local variable inside a display (for instance, if we do some computation inside the display...)

**Comment by AlexisDrogoul** [comment]
Difficult. Most of the layers inside the display declare their own scope (so as to not collide with the others), so this temporary variables will not be "reachable" by them. I will take a look, however, but I'm not too confident on this possibility.

**Comment by AlexisDrogoul** [comment]
Closing this issue while cleansing the backlog. Please reopen if still needed. This particular enhancement would require a rewrite of most of the layers, and it is not advised, in any case, to do too much computations in the display ...
