### ISSUE TITLE
"Set cannot be defined in overlay"

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1937]
I don't understand this constraint.

The following code generate an error : 

```
overlay "Legend"
{
	int variable <- 5;
	variable <- 3;
}
```

... but this following one does not : 

```
overlay "Legend"
{
	int variable <- 5;
	if (true) {
		variable <- 3;
	}
}
```

Which is a bit weird to me...

**Comment by AlexisDrogoul** [comment]
Right. The goal was to avoid having possible side effects on the simulation from the displays. So the list of possible statements is restricted. But this one is clearly missing, as well as some others (add, put, remove). I have corrected this.
