### ISSUE TITLE
Expression not resolved when passing a string variable as facet

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1938]
### Steps to reproduce
1. In the model Charts/Serie Examples (just an example), add the facet `x_label:cycle` in one of the `chart` statement. Launch the experiment.

### Expected behavior
To have a `0` as x label.

### Actual behavior
It is written `cycle` instead (and if we write `string(cycle)`, `string` will be written instead of `0`)

**Comment by AlexisDrogoul** [comment]
Well, that facet expects a label (a constant string) -- and I'd guess, in addition, that it is probably not updated (as in #1932). So the behavior does not seem completely stupid to me.

**Comment by mazarsju** [comment]
Mmm... Ok sry, I didn't see it was a label, I thought it was a string (and I don't understand why it is a label instead of a string !). I close this issue then, witch became a duplicate of #1932.
