### ISSUE TITLE
Inspect on grid (from asc ?)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1939]
[LAKWETCAM-modeles.zip](https://github.com/gama-platform/gama/files/368567/LAKWETCAM-modeles.zip)
### Steps to reproduce
1. Run the attached model

2. Right-click on any cell 

### Expected behavior
I was expected to be able to inspect the cell where I clicked

### Actual behavior
The inspector proposes only to inspect the cell0.
Note that the grid has been created from an ASC file ...

### System and version 
GAMA GIT MACOSX

**Comment by benoitgaudou** [comment]
To be more precise, when I add:
	   geometry shape <- envelope(dem_file);
in the global, the bug disappears.

So basically, the bug comes from the fact I had not redefined the environment.

**Comment by AlexisDrogoul** [comment]
OK. So, basically, either we close this bug or, when a grid is loaded from an ASC file (meaning it has georeferenced coordinates), we use this as the envelope of the world by default. Your choice ?

**Comment by benoitgaudou** [comment]
From my point of view, if we can see the agents, it is better to be able to click on them and inspect them.
Si either the two solution I see: the environment is set the envelope or the agents are displayed as/where they really are (in my case perhaps we will not be able to see any cell.

Benoit

**Comment by AlexisDrogoul** [comment]
I have implemented the first solution: the shape of the world is automatically sized if you load a dem and if the environment bounds are smaller. Note that if you were using a `species` layer, you would have not seen the agents, normally. But the `grid` layer projects the DEM image onto the environment size automatically, creating this visual artifact.
