### ISSUE TITLE
Highlight on grid layers does not work

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1940]
### Steps to reproduce
1. Run a model with a grid (in a java2D display)

2. Highlight a cell

### Expected behavior
The cell color changes (in turquoise)

### Actual behavior
The color does not change

### System and version 
GAMA Git, MAcOSX

**Comment by AlexisDrogoul** [comment]
And it will never work on grid displays. Or, actually, we need to perform so many changes for that that I dont think it is worth doing it. The only way is to change your layer to `species` instead. One "fix" for that could be to disable `Highlight` when right-clicking on a grid layer (but `Highlight` will still be present in the `Agents` menu and in the inspector, so the effect might be confusing).

**Comment by AlexisDrogoul** [comment]
I've chosen to implement the workaround. `Highlight` will not be available in the displays as a menu item. It might be confusing because it will still be present in the inspector and the global agent menu, but I dont think someone will notice...
