### ISSUE TITLE
dp853 variations discontinuities at each time step

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#1942]
### Steps to reproduce
1. when using dp853 with continuous charts

### Expected behavior
the red and yellow curves should be smoother:
### Actual behavior
there are some kind of variation discontinuities at each time step. Furthermore, curves don't start at x=0.

![capture](https://cloud.githubusercontent.com/assets/18676913/16993380/66ad63c2-4ea3-11e6-8ad4-e2770c6e555a.PNG)

There is no such problem with rk4.

### System and version 
Gama 1.7 continuous release, win 7 64

I don't know why I cannot upload the .gaml file, even in ZIP format, so I include the code as a .txt file

[Nouveau document texte.txt](https://github.com/gama-platform/gama/files/374137/Nouveau.document.texte.txt)

**Comment by hqnghi88** [comment]
I did not test with rk4 but at your side, did it work with rk4?

**Comment by hqnghi88** [comment]
The problem come from the wrong x_serie that integrator have returned. Using the x_serie to get the integrated time values will fix this discontinue.
