### ISSUE TITLE
missing point at first cycle in charts

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#1943]
### Steps to reproduce
1. use charts (with equations)

### Expected behavior
there should be one point at each time step

### Actual behavior
the point at time step 1 is missing

![capture](https://cloud.githubusercontent.com/assets/18676913/16993705/bc250c50-4ea4-11e6-8235-b8a979e26292.PNG)

actually, the simulation should stop after 8 cycles. Here it stops at t=9...

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by hqnghi88** [comment]
Hi,
There are several things in your issue:
1. The missing point caused by an issue of refresh:(every(1)) . you should remove it in the declaration of display Soil.
2. The first chart is missing the size facet so it overload the second.
3. Currently, the x_serie: (soil[0]).t[] is broken.
So the workaround solution for you is:


		display Soil 
		 {
			chart 'Organic Matter (gC/initial gC) of Arthrobacter 3R' type: series background: rgb ( 'lightGray' ) 
			size: { 0.5 , 1.0} position: { 0.0, 0.0 } 
			{
				data "CO2-model" value: first (soil).co2  color: °red ;	
		    	data "Fructose" value: first(soil).fructose  color: °orange;
			}

			chart 'chartcontinuous' type: series background: rgb('lightGray') 
			size: {0.5, 1.0} position: { 0.5,0.0 }
			{
				data "co2" value: (soil[0]).co2[] color: # red marker: false;
				data "fructose" value: (soil[0]).fructose[] color: # yellow marker: false;
			}
			
		}

**Comment by hqnghi88** [comment]
Ok i have fixed the x_serie, now you can specify the values of t as the x_serie:
display Soil 
     {
        chart 'Organic Matter (gC/initial gC) of Arthrobacter 3R' type: series background: rgb ( 'lightGray' ) 
        size: { 0.5 , 1.0} position: { 0.0, 0.0 } 
        {
            data "CO2-model" value: first (soil).co2  color: °red ;    
            data "Fructose" value: first(soil).fructose  color: °orange;
        }

        chart 'chartcontinuous' type: series background: rgb('lightGray') 
x_serie: (soil[0]).t[]
        size: {0.5, 1.0} position: { 0.5,0.0 }
        {
            data "co2" value: (soil[0]).co2[] color: # red marker: false;
            data "fructose" value: (soil[0]).fructose[] color: # yellow marker: false;
        }

    }
