### ISSUE TITLE
Various problems when changing layers properties

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1946]
The layers controls panel has a lot of problems (this following list is not exhaustive) : 

- Changing the "y" position/size of a layer changes automatically the value of the "z" field.
- Changing the size and the position sometime does not work (either no visual changes, or a layer disappears forever...)
- "Revert to original values" cause a null pointer exception
- What is the effect of the rectangle toggle next to the visibility one ? (maybe indicating the the use of this toggle with a infobubble ?)

A question comes to my mind : are all those commands really used ?

**Comment by AlexisDrogoul** [comment]
Right now, this part has been a bit neglected. But I think it's important to keep it and to add various other properties to layers (lights, cameras, etc.). The idea is to, eventually, have a "Save" button that can copy the definition of the display so as to reuse it in another experiment or paste it in the current one. 

I will check the errors. The little rectangle allows to tell whether or not the elements of the layer can be selected or not when right-clicking.

**Comment by AlexisDrogoul** [comment]
Bugs have been fixed. I've been unable, however, to reproduce the NPE. Was it after a particular sequence ?
