### ISSUE TITLE
Axis are too big when "Draw rotation helper" is disable.

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1947]
### Steps to reproduce
1. Choose preferences : "Draw rotation helper" OFF
                                      "Draw 3D referential" ON

2. Run a simulation

### Expected behavior
The axis should have the size of 1/6 of the max dimension

### Actual behavior
The axis have the size of max dimension

Note that this problem does not exist if "Draw rotation helper" is enabled.

**Comment by AlexisDrogoul** [comment]
I can't reproduce it. In my config, when 3D referential is off, no axes are displayed, neither in the left hand corner or in the center of the sphere when rotating. Are they displayed in your case ?

**Comment by mazarsju** [comment]
Ups, sorry, the problem appears when "Draw 3D referential" is set to "true" and when "Draw rotation helper" is set to "false".
