### ISSUE TITLE
ability to select a project when opening gaml file

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1952]
### Steps to reproduce
1. Open any .gaml file from finder/explorer by double clicking.

2. GAMA will tell you, that this file is not associated with any project, so will be opened in unclassified projects

I would like to request an enhancement that allows to select from the available projects where user would want to import the opened .gaml file.

Thanks

**Comment by AlexisDrogoul** [comment]
I've implemented the change, which opens a dialog for the user to select a project and/or a folder within a project, or -- if cancelled -- uses the previous behavior (puts the orphan file in `Unclassified Models`). I guess we need to wait for Travis to work again correctly to test it...

**Comment by sriramab** [comment]
Thank you Alexis.

**Comment by sriramab** [comment]
It works perfect.
