### ISSUE TITLE
Creation of grid from .asc modifies the shape of the global

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1953]
### Steps to reproduce
1. Consider the following model (complete model is attached
[TestGridShp.zip](https://github.com/gama-platform/gama/files/401091/TestGridShp.zip)
)

model ascimport

global {
	file grid_data <- file('../includes/hab10.asc') ;
	file file_shp <- shape_file("../includes/buildings_simple.shp");
	
	geometry shape <- envelope(file_shp);	

	init {
		create building from: file_shp;
	}
}

species building;

//grid cell file: grid_data{ }

experiment gridloading type: gui {
	output {
		display "As DEM" type: opengl{
			species building;
		}	
	} 
}

2. When we run it as it is, the building appears

3. Uncomment the line defining the grid, and run the model. 
The display is empty (building are created but seems to be wrongly projected)

### Expected behavior
nothing should change in the model by adding this creation.

### Actual behavior
It seems that the shape of the environment is changed when the grid is created.

### System and version 
GAMA Git, MACOSX

**Comment by AlexisDrogoul** [comment]
Well, you have to choose... Either you want grids to be correctly displayed in the absence of a shape for the environment (#1939), in which case they will change the shape of the environment if it is too small, or we revert this change, but it is up to the modeler to correctly set the desired shape.

**Comment by benoitgaudou** [comment]
my concern is that in this case the shape of the environment has been set to the size of a shapefile: 
geometry shape <- envelope(file_shp);

**Comment by AlexisDrogoul** [comment]
Hmmm.. And which one is the correct one ? It seems that your building and your asc file do not share the same envelope, or do they ? I can revert the previous commit, but in that case, not fixing the shape of the world when you load an asc file will result in a "bad" grid where most of the cells will not belong to the world.

**Comment by AlexisDrogoul** [comment]
Can you print the envelope of both your buildings and your grid ? I have the feeling I might have made an error in testing their inclusion, but I want to be sure first...

**Comment by benoitgaudou** [comment]
Hi,
Thanks for your answer.
If I have to choose between the two issues, I'd prefer not being able to
click on the cells rather than than changing the world shape (even when I
already have instantiate it with the envelope of a shapefile).

In fact what about this : as now the grid can be created from a
geo-referenced file with a given top-left coordinates and size of cells,
perhaps it could be interesting that the grid does not take automatically
all the world shape ?

As consequence, the creation of the grid will not have to change the world
shape (just as any other kind of agents) : given the world shape, the cells
can be bigger or smaller than the world shape, so can appear outside of the
world or in a small part...

Cheers

Benoit

2016-08-04 14:15 GMT+02:00 Alexis Drogoul <notifications@github.com>:
