### ISSUE TITLE
command operator does not respect PATH?

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1954]
### Steps to reproduce
1. if you have matlab, you can try this: write command("matlab"), it will return runtime  error (see attachment) 
2. in terminal if you type "matlab", it will invoke matlab instance. 

My feeling is that command is not accepting the extra PATH parameters defined in the system. 
I notice from the internet, there are couple of ways path is defined in macOS: one is using .bash_profile and other is using .profile and third method using /etc/path 

I am not aware which is the default PATH recognised in command operator in GAMA, I am not computer scientist :) for me only the third method works to add extra path and then "matlab" works at the terminal. 

Attached are two images for two different arguments passed in the command operator and they result in error. To the right in the coding window, you can see how I use the command operator. 

Please note, This problem (workaround?) however is resolved when using absolute path of the executable. 

So, I am not sure if something can be done for the command operator to understand all kind of PATH definitions.

![renewpsov3 gaml 2016-08-04](https://cloud.githubusercontent.com/assets/12668606/17395494/fe2c79c2-5a2e-11e6-8913-cb772a2c18e7.png)

![renewpsov3 gaml 2016-08-04 2](https://cloud.githubusercontent.com/assets/12668606/17395497/02776a32-5a2f-11e6-9e79-68255584c92a.png)

**Comment by AlexisDrogoul** [comment]
I have absolutely no idea on how to read PATH from the terminal opened by Java. If someone wants to contribute...

**Comment by AlexisDrogoul** [comment]
On a second thought: the command operator does not invoke a specific shell (i.e. `bash` or `cmd.exe`), so there is no path except the current working directory (which is, I think, the model directory).

**Comment by sriramab** [comment]
May be that is why it works with absolute path?

**Comment by AlexisDrogoul** [comment]
Exactly. So I can try to force the execution of bash (in MacOS X & Linux) and cmd.exe (on Windows), but I'm not completely sure of the consequences of this.

**Comment by AlexisDrogoul** [comment]
I have modified `command` so that it calls `/bin/bash` or `cmd.exe` explicitly. Can you please test it? If its works (i.e. if the PATH is correctly loaded by bash), then, I'll add a preference to specify the shell people want to use (`/usr/bin/bash`, `/bin/sh`, etc.).

**Comment by sriramab** [comment]
I probably will have to wait for the build to come onto github, then I can
download and test it.

**Comment by sriramab** [comment]
Making it specific to R: I have noticed that this happens also when R script file has its own system commands. GAMA returns java null error. As long as one avoids system commands within R script, the files seem to work in GAMA. 

Second reason that stops GAMA with java missing file error. It is common in R to define working-directory and save outputs in that directory. And is also common that a simple save command will then save output to that directory. However these direct save commands (without path) give error in GAMA because GAMA command operator does not understand the defined working directory in R script and this results in error. Again if you give absolute paths within R script, this error disappears. 

Third reason, it is also  better not to print results of R variables on the R console, because everything that is printed on R console is captured by the GAMA command operator. 
This may be good or bad depending on individual needs.

**Comment by AlexisDrogoul** [comment]
Have you been able to test this change ? Does it work ?

**Comment by sriramab** [comment]
Hi Alexis, It is not resolved. When I type r or matlab on my terminal, it invokes the respective applications. But when I do the same in command operator, it gives me error. 
I am using 10Aug2016 version, which is later than your commit.

Here a screenshot

![new gaml 2016-08-26](https://cloud.githubusercontent.com/assets/12668606/17996478/7748056a-6b69-11e6-871d-29cf80f49b8c.png)

**Comment by AlexisDrogoul** [comment]
Have you tried writing `/bin/bash -c r` in your terminal ? Does it work ?  Because if I use 'python' and a file, (e.g. `command("python something.py")` it works well (`R` is not installed on my machine).

**Comment by sriramab** [comment]
Yes, /bin/bash -c r works at my terminal but not when inside gama command operator. :(

**Comment by sriramab** [comment]
This is resolved if one uses "Rscript foo.R"
thank you Alexis.

**Comment by sriramab** [comment]
This workaround of giving full path does not work with google go language. Because google go needs a environment variable - $GOROOT and the command operator in GAMA is not able to recognize this. 

Please could you check that command can also use environment variables? 


for example: command("echo $PATH") in GAMA returns different values compared to echo $PATH at terminal. 

If you install go, Here is a small example to follow 
https://golang.org/doc/install?download

**Comment by AlexisDrogoul** [comment]
I have added two more forms of `command`. In addition to the commands themselves, you can add the working directory (a string) or the working directory (a string) and the environment (a map<string, string). Dont know if this solves your problem ? It it doesn't, maybe https://github.com/brettwooldridge/NuProcess or https://github.com/zeroturnaround/zt-exec may provide a solution...

**Comment by AlexisDrogoul** [comment]
Any update on this one ? Does the above addition provide some workarounds for directories ?

**Comment by sriramab** [comment]
I haven't checked as we moved to R instead of GO and GO will return in a few months. Please keep it to the pending list for a while?

**Comment by sriramab** [comment]
This may be related to #2197 where one way of recognizing  PATH was through setting global variables  as in this (tutorial)[https://www.youtube.com/watch?v=wm0UTTdMzzs]

**Comment by sriramab** [comment]
This seems to work very well with matlab, R, python. But I wonder about the following. This command returns a string to the GAMA Console, can there be a variant where for example instead of write statement or storing the string we just (R for example):
`do command( /usr/bin/Rscript someRscript.R) `
 just does the tasks in the script and creates output files or whatever it has to do. 

By no means I am suggesting that the string return variant should be discarded, because it is very useful in debugging any mistakes in the external script. I am just wondering of a variant where nothing has to be stored or printed.

**Comment by hqnghi88** [comment]
Hi Sriri
i didnot.get that clearly but if you dont want to display something,
redirect it to null or a temp file
usr.bin.Rscript somescript.r > null
or
usr.bin.Rscript somescript.r >  tmp.txt


On Oct 16, 2017 17:27, "Srirāma Bhamidipāti" <notifications@github.com>
wrote:

This seems to work very well with matlab, R, python. But I wonder about the
following. This command returns a string to the GAMA Console, can there be
a variant where for example instead of write statement or storing the
string we just (R for example):
do command( /usr/bin/Rscript someRscript.R)
just does the tasks in the script and creates output files or whatever it
has to do.

By no means I am suggesting that the string return variant should be
discarded, because it is very useful in debugging any mistakes in the
external script. I am just wondering of a variant where nothing has to be
stored or printed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gama-platform/gama/issues/1954#issuecomment-336846113>,
or mute the thread

**Comment by sriramab** [comment]
Thank you Nghi, this is resolved with your comments
