### ISSUE TITLE
Duration slider broken?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1955]
### Steps to reproduce
1.Run any model

2.Move the duration slider

3.Nothing changes...

### Expected behavior
Change the speed of the simulation

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
The official Gama 1.7 release. I did not try on the current version...

**Comment by agrignard** [comment]
I hope it only come from my configuration...

Gama official release1 1.7 & Mac Os X 10.11.15

**Comment by AlexisDrogoul** [comment]
Works well on the latest build. I guess it is something that has been handled in #1917 .

**Comment by agrignard** [comment]
I feel a bit worried that this essential feature is not in the "official"... No way to update officially the official? 

BTW is it still useful to report bug for the "official" release ?

**Comment by AlexisDrogoul** [comment]
Closes this one as it is fixed in the main trunk. I will reissue an "official" version soon.

**Comment by agrignard** [comment]
Any news about the  new  "official" version ? The duration slider is a key feature for "temporal scrolling"  or more complex animation, no?
