### ISSUE TITLE
OSM Loading Driving.gaml 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1956]
No way to run the model...
<img width="551" alt="screen shot 2016-08-12 at 14 42 15" src="https://cloud.githubusercontent.com/assets/3928502/17633380/017effba-609b-11e6-84aa-4cacdc9b0ccf.png">

Gama official release1 1.7 & Mac Os X 10.11.15

**Comment by AlexisDrogoul** [comment]
Works well on the latest configuration. You might want to try a newer build than the "official" release...

**Comment by AlexisDrogoul** [comment]
Closes this one as it has been fixed in the main trunk. Will release a new "official" version soon.
