### ISSUE TITLE
Call of event and action

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1957]
### Steps to reproduce
In the official release I have a model that does this inside a display in order to control the sim with a keyboard and it works but it does not work in the current version.
```
....
			event 's' action: _step_;
			event 'r' action: regenerateGrid;
...
```
with 
```
 action regenerateGrid (list<agent> selectedAgent, point mousePosition){
  	 do update;
 }
```

### Actual behavior
I just notice that this syntax does not compile anymore in the current Version of GAMA and it gives the following error:

Action 'regenerateGrid' cannot have arguments. Use '#user_location'
   inside to obtain the location of the mouse, and compute the
   selected agents in the action using GAML spatial operators

### System and version 
GAMA 1.7 current

**Comment by AlexisDrogoul** [comment]
Yes. It relates to a recent mail on gama-dev. Actions called by `event` cannot have arguments anymore. The rest is explained in the error message. Simply remove the arguments of the action and it will compile.
