### ISSUE TITLE
Inside operator returns empty

### ISSUE THREAD

**Issue by martinveenvliet** [gama-platform/gama#1959]
### Steps to reproduce
Create an shapefile with agents (points) and another shapefile with an area (Multi-polygon), where some point agents are located inside polygons.

Use the point shapefile to create agents (by using create Agent from: file;
Cast the multi-polygon to a geometry. (by using geometry Poly <- geometry(file)).

Ask the list of point agents inside the polygons by:
list Test <- point inside Poly

Also see: https://groups.google.com/forum/embed/?place=forum%2Fgama-platform&showsearch=true&parenturl=http%3A%2F%2Fgama-platform.org%2Fcommunity%23UserForum&theme=default#!topic/gama-platform/rBlp8SyIeT4

The problem did not appear to happen on another run, where the shapefiles were read as a single polygon and the coordinates were in the WGS 1984 Geographic coordinate system.

### Expected behavior
I would expect the model to return a list with the agents inside the geometry.

### Actual behavior
The list returns empty, even though the point agents are inside the polygons

### System and version 
GAMA 1.7.0 Standalone
Windows 10
The shapefiles are both projected in WGS 1984 World Mercator

A workaround was already given by Patrick Taillandier, adding a small buffer around the agents, by using create Agent {shape <- shape + 0.0001;} fixes the problem.

**Comment by ptaillandier** [comment]
As point out in the last message of the mailing list, the problem comes from the data and not from GAMA (sorry, it is my fault ;) ).
