### ISSUE TITLE
Closing a simulation switches focus 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1960]
### Steps to reproduce
1. Open five or six model files in your editor.

2. Load one of your models. and run the simulation for a while. Pause and hit stop button.

### Expected behavior
I expect the focus to return to the model file from where we loaded our experiment.

### Actual behavior
If we loaded the 6th file, the focus returns to the 5th file. or some random file among the 6 open files. Sometimes even the first file among the 6 open model files. 

### System and version 
GAMA 1.7 standalone, macOSX

**Comment by AlexisDrogoul** [comment]
What do you call the "stop" button ? The one that pauses the simulation or the one that closes it and returns to the modeling perspective ?

**Comment by sriramab** [comment]
The one that closes the simulation. The cross mark.

**Comment by AlexisDrogoul** [comment]
I can't seem to reproduce it. Do you have the editors pane open in the simulation perspective as well ? Or only in the modeling perspective ? Do you launch the simulations using the "green" buttons at the top of editors or using the items in the navigator ?

**Comment by sriramab** [comment]
Hmm. I always use the green button at the top of the editor. And the editor pane is almost always open at the bottom half even in simulation perspective. For some reason I am unable to reproduce it today. And closing the unrelated project folders has help in a lot of these GUI glitches/issues. If it happens again, I will post a video.
