### ISSUE TITLE
limit snapshot to world/envelope extent

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1961]
I notice that using snapshot takes a screenshot of the "entire" display window where snapshot is clicked. I would like to request if it is possible restrict the snapshot extent to the envelope defined in the model. I do not know if this is possible. 

Not a high priority.

Thank you.

**Comment by AlexisDrogoul** [comment]
Well. Maybe possible, but difficult to implement, especially because taking snapshots should also work with the zoom and because OpenGL displays can display things "outside" the envelope of the world.

**Comment by sriramab** [comment]
Not a priority. I will crop them in any editor. I will close it for now. Thank you :)
