### ISSUE TITLE
Ability to choose a path by agent

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1965]
This enhancement is in relation to combining k-shortest paths and the on: facet of goto statement in moving skills. The two features already exist and combining them will be helpful.

My hypothesis is that a user does not always select the shortest path to destination, sometimes due to lack of knowledge of the network (graph). Some users (agents ) will choose a non-shortest path. 

This is somehow difficult to replicate in GAMA because all agents go along the shortest path. 

1. Now consider, paths_between operator. It gives k paths between A and B. 
2. And consider the goto statement, it allows movement from A to B along shortest path. 

I would like to request a operator or facet probably that is takes two arguments (combining 1,2). For example:
goto target: B on: (graph, 3) 
or 
goto target: B on: (graph, k[3])

the first operand is the graph on which the agent will travel and 3 is the 3rd path in the list of path calculated from (paths_between). 

So the agent is asked to move on path 3 (3rd best shortest path). I think this would be interesting to increase the stochasticity of the model and to come closer to reality.

Not sure how to implement it, may be any ideas ? @ptaillandier 
thank you

**Comment by sriramab** [comment]
Or may be to say-> goto target:B on: (graph,false)
and the false would indicate that it is not necessary to go on shortest path. true remains default.

**Comment by AlexisDrogoul** [comment]
Have you tried to use the `follow` primitive ? It normally takes a path as a possible facet (`do follow path: k[3];`).

**Comment by sriramab** [comment]
Hmm, I tried, but the agent jumps off network randomly. 
Secondly, if I do this way, follow way, I don't think it follows the speed limits I have on the graph and also does not count the agent moving on the graph edge. (I have a small code that calculates number of agents moving on a graph edge)

**Comment by sriramab** [comment]
I put the code on the forum (goto vs follow). Please see. Thanks
