### ISSUE TITLE
Inspection of agent does not work in the opengl mode under Windows

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1968]
Hello,
I have a little issue with agent's inspection in the opengl mode
### Steps to reproduce
1. Open an model with an opengl display ( e.g. Tutorials\Road traffic \ model07.gaml)

2. Launch simulation

3. Click Pause, then right click on a building or a road for inspecting the agent.

### Expected behavior

- The inspection's window appears. 

### Actual behavior
- The inspection's window did not appear ( I have not got any error message)
Note: It works only on the first run and before starting the simulation.
However, It works fine in Java 2D mode. 
### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA): Git and Latest release , Windows 64 and 32 bit.

**Comment by AlexisDrogoul** [comment]
Verified under MacOSX as well. I add @mazarsju to this thread as he made several changes in the renderer architecture.

**Comment by mazarsju** [comment]
I ran the model you mentioned, clicked run, then pause, and right click on either a building or a road to inspect it, but it works well for me...
I'm running it from the Git version, on Windows 64 bit...

**Comment by tcquang** [comment]
Hi Julien,
I can't pull a newer Git version right now ( because I would keep the version that is working with the GM plugin). I just downloaded the GAMA1.7_Win_64_09.08.16_347bc5d version and tested it on Win 8 and win 10 64bit. It still have the same issue. It work well only on the first run ,  otherwise, I have to restart GAMA. I have the JDK 8u101 64bit.

**Comment by hqnghi88** [comment]
HI,
I confirmed that I still have the same issue . Git version , win 10 64bit.

**Comment by AlexisDrogoul** [comment]
Actually, I can confirm that the inspection of agents in OpenGL is completely broken. 

Besides the behavior described by Quang, I can reproduce these two bugs:

1) The agent inspected is always the same (whichever is picked up), number 1.
2) When clicking at 2 different locations before running the simulation, the menu shows up twice in the first location.

**Comment by AlexisDrogoul** [comment]
OK. I've found the cause of it. If you turn off the preference "Draw 3D referential", it will work. The problem is that this 3D referential is always selected first (with a selected index of 1) and prevents any agent from being "selectable". As a result, no one is selected and no menu is shown (as this referential is not an agent).
I have also corrected the small bug on the menu position. 

Now the problem remains on how to "remove" this referential from the selection... I'm digging.

**Comment by hqnghi88** [comment]
Thank you, just a very small sidenote, could we have an export file (.xml or txt) to verify the prefenrence's options between developers and maybe also modelers, because i remember that we have several problem based on the difference configuaration in  preference.

**Comment by AlexisDrogoul** [comment]
Just hit export... in the preferences view. You can then import this file to match the preferences of someone else.

**Comment by AlexisDrogoul** [comment]
I've fixed the issue. There is a small catch, however, as, to do that, I had to disable the referential during picking. Not a big deal, and even a nice touch (as there is a visual feedback when the menu is shown).
