### ISSUE TITLE
vps226121.ovh.net/updates p2 site down ?

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#1969]
Hi,

Two things, the first, after successful compilation, and deploy on gama vps server, i have now some problem to access p2 repository here [http://vps226121.ovh.net/updates](http://vps226121.ovh.net/updates)

Is there something which change in the configuration of vps recently ?

The second thing, do you think we can add an auto-deploy script for latest dev build (like nightmare build) in travis ? That could be great :)

**Comment by reyman** [comment]
I push gama update on another site for dev usage with openmole (compiling gama-plugin for openmole), you can use if you want : http://gama.unthinkingdepths.fr/

**Comment by gnoubi** [comment]
Hi, 

Maybe, there is not any change in the configuration of the VPS since a long time. 

Yes it is possible to add an auto-deploy script. It should be registered to the crontab of the vps

Nicolas

**Comment by AlexisDrogoul** [comment]
What is the state of this issue ? We need to test it quickly on a standalone version, so as to be sure that users will be able to update their platforms when they download it.

**Comment by reyman** [comment]
@gnoubi make some change on VPS. I test on my side with the latest continuous build, and the updates sites continue to display infinite "pending..."

About the auto-deploy, i suppose we only need to add `./deploy-p2.sh` to travis script. BUt IMHO, we need also to separate  "continuous update site url" and "release update site url"  .

**Comment by gnoubi** [comment]
Hi, 

Indeed, some changes have been done on the VPS. I have tried this morning, it seems working. 

Last week, we tried the update to setup network plugin on gama. It worked well when the computer use a direct connection such as Eduroam. Behind a proxy, « pending » error has happened. We didn't found how to configure proxy in gama menus whereas it is  possible with eclipse.

best
nicolas
-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06

**Comment by AlexisDrogoul** [comment]
Hi,

I've added the UI for the proxy/network preferences in GAMA (latest build). Can you please to see if it solves the issue of accessing the site behind a proxy ?

Alexis

**Comment by AlexisDrogoul** [comment]
What is the status of this issue ? @gnoubi ?

**Comment by gnoubi** [comment]
Hi

The problem had been fixed. I tested at university behind a proxy and it seemed work

Nicolas

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by AlexisDrogoul** [comment]
Great ! Thanks !
