### ISSUE TITLE
Continuous build stopped ?

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#1970]
It seems the [continuous build release](https://github.com/gama-platform/gama/releases/tag/latest) don't work, there 250 and more commit since the last upload.

There is a warning message in travis : 
```

0.11s$ bash ./github-release.sh "$TRAVIS_COMMIT"

_09/05/16_191fc96.zip

/home/travis/build/gama-platform/gama/ummisco.gama.product/target/products/Gama1.7-linux.gtk.x86.zip

GAMA1.7_Linux_32_09/05/16_191fc96.zip

/home/travis/build/gama-platform/gama/ummisco.gama.product/target/products/Gama1.7-linux.gtk.x86_64.zip

GAMA1.7_Linux_64_09/05/16_191fc96.zip

/home/travis/build/gama-platform/gama/ummisco.gama.product/target/products/Gama1.7-macosx.cocoa.x86_64.zip

GAMA1.7_Mac_64_09/05/16_191fc96.zip

/home/travis/build/gama-platform/gama/ummisco.gama.product/target/products/Gama1.7-win32.win32.x86.zip

GAMA1.7_Win_32_09/05/16_191fc96.zip

/home/travis/build/gama-platform/gama/ummisco.gama.product/target/products/Gama1.7-win32.win32.x86_64.zip

GAMA1.7_Win_64_09/05/16_191fc96.zip

Getting info of latest tag...

{ "message": "API rate limit exceeded for 52.0.240.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://developer.github.com/v3/#rate-limiting" }
```

**Comment by reyman** [comment]
There is a first path to follow here i think : https://gist.github.com/topheman/25241e48a1b4f91ec6d4

**Comment by hqnghi88** [comment]
Hi Sebastien,
The status of the tag is obsolet (or i am because i didn't found a solution to change it from cmdline). As pointed out in the paragraph:
The release file names are composed with a number of segments separated by _  :
    the version of the release, (e.g., GAMA1.7)
    the name of the OS: either Linux, Mac or Win
    the number of bits: 64 for 64bits, 32 for 32 bits
    the day it has been produced (e.g., 07.03.16 for the 3rd of July, 2016)
    the hashcode of the corresponding commit (e.g., bbe2b68 that can be retrieved at https://github.com/gama-platform/gama/commits/master)

The continous build is working. 
Regard the warning of "API rate limit exceeded...", i think  it have solved, we wait for a bit later to see.

**Comment by reyman** [comment]
@hqnghi88 OK sorry for mistake, i only see the tag and commit info, and didn't look to filename and hashtag.
