### ISSUE TITLE
NullPointerException when running Built-In Shapes (and maybe other models...)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1971]
It seems that this bug has been introduced with the massive compilation changes (commit https://github.com/gama-platform/gama/commit/d70ceef598f43dfa488afa642ffbd8f4e8fc2047)

**Comment by AlexisDrogoul** [comment]
Problem introduced in my latest commit -- it's due to a bad configuration of the dependencies between attributes and inherited attributes, and hopefully affects few models. Will try to correct it soon.
