### ISSUE TITLE
Do you have GAMA book,I want to learn how to program  

### ISSUE THREAD

**Issue by songweizhen** [gama-platform/gama#1973]
Do you have GAMA book,I want to learn how to program

**Comment by songweizhen** [comment]
thank you very much ,it's my first use this issue

**Comment by mazarsju** [comment]
Hi,

You have a pdf documentation if you want to learn GAML without a connexion. You can download it here : http://gama-platform.org/download#GAMA17

Note that for this kind of question, the gama-group mailing list is more accurate : https://groups.google.com/forum/?hl=en#!forum/gama-platform.

Cheers !

Julien.
