### ISSUE TITLE
Relaunch button in the minimal gui

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1980]
What about having a relaunch button at the left of the red cross ?  I know the relaunch button is available in the other tabs but it makes sense to have it at the same level of the play

**Comment by AlexisDrogoul** [comment]
We can perfectly add one, the only trouble being that it is strongly linked with the parameters view, as it is bound to take new parameters values as input. I have pushed a small change to move this button out of the view and into the main bar, please comment ( @gama-platform/committers ) if you have any trouble with this.

**Comment by agrignard** [comment]
Cool I did not think it would be so fast to add it.

It does the trick for me. Thanks
