### ISSUE TITLE
Keystoning & Shader

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1991]
Keystoning and shader are two different things.

We should be able to do keystoning without having to use shader. Shader are still experimental and not working on every model (especially on all the GIS geometry which means a lot of model...) whereas keystoning seems to work pretty well.

**Comment by AlexisDrogoul** [comment]
From what I have read so far, keystoning is just a matter of applying a deformation to the projection matrix. So I dont really get the difficulty of doing it (besides the maths, which I am more or less unable to figure out). You might want to give it a try in the renderer (first by correctly isolating the calls to the projection matrix, and then trying different parameters). After that, having the new "keystone" facet accepting either a list of values (as it does now) or a file containing these values is quite simple.

**Comment by mazarsju** [comment]
Some improvements/changes have been made for the keystoning : 
- Now you can drag & drop the 4 corners of the display by pressing "K". The key / mouse events have to be better handled, but it is working :) (the validation of the new position has to be done releasing the "K" key). There is also a button in the center of the display to go back to the default keystone setup.
- The facet "keystone" of the display is now only computed in the "init" (I don't want to have any conflict with the drag & drop). I also changed a bit the range of the positions : now you have to give coordinates in the intervalle [0,1] instead of [-1,+1].
- Since the facet "keystone" is no more computed at every step, I deleted the model about keystoning which was no more very interesting.

Enjoy !

![image1](https://cloud.githubusercontent.com/assets/12977635/18948616/017582ea-8662-11e6-99e2-955e994569b1.png)

**Comment by mazarsju** [comment]
(this feature is only disponible for "use_shader" display)

**Comment by agrignard** [comment]
This is great! One of the last step now would be to be able to save the
keystonibg parameters or at least to display its value while doing the
keystoning so that we can rerun the simulation with the same keystone.

**Comment by mazarsju** [comment]
Displaying the value is not complicated, I can add that.
About saving the parameters, I don't know where/how you want to save them... Any idea ?

**Comment by agrignard** [comment]
in processing the keystoning is saved in an xml file. When your kestonign is done you press S("save) and it will right the value in a file.

When you run a model if this .xml file exists it will be keystoned with this value. 

That looks like this 

<?xml version="1.0" encoding="UTF-8"?>
<keystone>
  <surface h="601" res="50" w="1692" x="254.0" y="173.0">
    <point i="0" u="0.0" v="0.0" x="1462.0" y="752.0"/>
    <point i="50" u="1692.0" v="0.0" x="-78.0" y="696.0"/>
    <point i="2550" u="0.0" v="601.0" x="1534.0" y="167.0"/>
    <point i="2600" u="1692.0" v="601.0" x="-30.0" y="75.0"/>
  </surface>
</keystone>


For now I think that if we can display (even in the console (because maybe it's not easy to read on a table) the keystone value it's ok.

**Comment by agrignard** [comment]
Sorry no way to copy/paste an xml in the github

**Comment by agrignard** [comment]
We are almost there.
The Kestoning works nice. 

The only thing is that (for example if I want to display something on the table ) I want to display (and keystone) only the model bounds and not the entire window.
For instance imagine that my Table is the one in the picture I don't want to have the white space, actually I just want my bound to be keystoned.
<img width="767" alt="screen shot 2016-09-29 at 08 18 33" src="https://cloud.githubusercontent.com/assets/3928502/18953648/757a656a-861d-11e6-8ea7-a8dcb1e296f3.png">

I don't exactly how to solve that. Maybe when having the keystone:true, we just displauy the bound of the world... but it means that the size of the window should be proportional....

**Comment by mazarsju** [comment]
Magic trick, with a black background and a white world.shape :)

![image1](https://cloud.githubusercontent.com/assets/12977635/18959517/ac7522da-8690-11e6-8a14-174aaf74958a.png)

**Comment by agrignard** [comment]
;-) yes indeed 

but you have to think that you are  constrained by a projector and you loose half of the surface with that solution which means you might have to put the projector 2 times higher ;-) but yes it' s a good temporary solution

**Comment by mazarsju** [comment]
I don't get your point : you just have to zoom in if you want to occupy more space of your screen with this solution.

**Comment by AlexisDrogoul** [comment]
I close this one as this seems to be only visual tricks.

**Comment by agrignard** [comment]
The end of the issue was a visual trick but not the beginning (differentiate keystone and shader). This could help to use keystone feature for a long demo (see #2049)
