### ISSUE TITLE
Calculation of NaN and Infinity values

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1992]
### Steps to reproduce

1.
Let run this model

model testnan

experiment maths type: gui {  
    reflex solving {
        float i<-(3\* fact(250)); 
        i<-i-3\* fact(250); 
        i<-i+2;
        float r<-1/i;
        write i;  
        write r;
    }  
}
### Expected behavior

Tell us what should happen (include all relevant expectations)
Is it reasonable if the calculation of i and r don't say anything about Infinity value or NaN value unless user write it to console
### Actual behavior

Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
No warnings or errors shown.
### System and version

Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)
Gama git

**Comment by AlexisDrogoul** [comment]
I'm sorry -- but I dont really understand what the problem is here. Is it the display of the number ? The computation ? What was you expecting ?

**Comment by hqnghi88** [comment]
Dear Alexis,
I talk about the 2 special values: NaN and Infinity. It come from Damien's discussion: he recognize that in ODE (or even normal calculation), these two value were not have any special messages (errors, warnings). For example, in my code, I (we?) expected this expression: float r<-1/i; should have a warning because it calcul on a Infinity/NaN number and he did not easily find the cause of wrong results.
["
Because i’ve lost my mind when trying to figure out where is my mistake, until I debug everything and understood that fact(255)
is too large to be saved inside a variable and is so reported as “Inf.” (NaN), and the Platform says nothing, just continue to run
without saying anything.
"]
BUT
Yes, if we accept the behavior of java that just accept the calculation on Inf/NaN and let the user do the validation with isNaN or isInfinity... 
What do you think?

**Comment by AlexisDrogoul** [comment]
Well. `#nan` and `#infinity` are already existing in GAML, so why shouldn't we use it ? I've changed a bit the casting to strings of float variables so that they output this constant instead of the `NaN` of Java. But for me, there is nothing more (or less) we should do.

**Comment by hqnghi88** [comment]
#nan and #infinity are fine. Thank you, nothing more (or less) I can propose for this.
