### ISSUE TITLE
Rotate at the layer level

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2003]
I'd like to be able to rotate the entire scene once it's drawn.

In the same spirit of the button rotate scene but with a value that I can choose. 

What about a facet rotate at the layer level , it makes ense has we have already size and position

**Comment by agrignard** [comment]
Just to explain. I want to display a video made from GAMA (unfortunattely not a simulation as we don't have yet a keystone fully fonctionnal) on this table. On this table the north is not really on the north so I need to rotate my GAMA model so that it fits
<img width="1008" alt="screen shot 2016-09-22 at 10 12 51" src="https://cloud.githubusercontent.com/assets/3928502/18751523/5afc6b40-80ad-11e6-9f78-81061e870501.png">
 to the table.

**Comment by AlexisDrogoul** [comment]
And turning the table or the projector is not an option ??

**Comment by agrignard** [comment]
Of course not ;-)!

**Comment by agrignard** [comment]
Different projects from differents soft (unity, processing, grasshoper) are display on that. I don't see my self saying "ok now let's show a gama project, just give me 2 sec I turn the table with an angle of 9.74 ° ;-) "

What do you think about a facet "rotate" at the layer level? in opengl shoudl be ok I don't know in Java2D?

**Comment by AlexisDrogoul** [comment]
easy enough in both cases (probably even easier in Java2D), but does it make sense to do it at the layer level ? maybe at the display level, like the keystone, no ?

**Comment by agrignard** [comment]
ok for the display level it was to be coherent with size and position  that we already have at the layer level

why not having both? I don't what use case but maybe one wants to rotate something on top of a backgroudn picture?

**Comment by mazarsju** [comment]
Note that with the new "use_shader" display, you can apply keystoning effect to make the rotation you want.

**Comment by mazarsju** [comment]
I added the rotate facet for the display. If it's ok for you, we can close this issue.

**Comment by agrignard** [comment]
Perfect!!!!

**Comment by agrignard** [comment]
Smal details. When we double click it goes back to the initial rotation. It would be better if it stays at the rotation defined in the rotate facet
