### ISSUE TITLE
Some OSM data in bz2 format failing to load

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2006]
### Steps to reproduce
1. Download (for instance) one of the OSM extracts available here: https://mapzen.com/data/metro-extracts/metro/hanoi_vietnam/
2. Try to load them in GAMA (using the "osm_file" operators). 
### Expected behavior

The maps should show up.
### Actual behavior

A first error on bz2 files saying that the Apache Commons Bz2 Compressor is not found (I corrected it).
But, once corrected, neither the bz2, pbf, osm (uncompressed XML) files accept to load (SaxParser exception). 
### System and version

Latest GIT version.

**Comment by AlexisDrogoul** [comment]
Ok. So there is definitely an issue with .pbf (binary) and .bz2 (compressed) formats. I've tried with several datasets and I can without problems import .gz or .osm formats, but the former two give me different errors. 

For bz2, it's a XML parser error (as if the decompressor didn't do its job correctly). For pbf, it's a OsmosisRuntimeError ("unable to process PBF stream"), and it seems the stream is closed prematurely.

**Comment by AlexisDrogoul** [comment]
I've tried to push osmosis to version 0.45, but no luck. Has somebody been able to read a pbf or bz2 formatted OSM file ?

**Comment by ptaillandier** [comment]
It was working with GAMA 1.6.1... I was not able to find a version of GAMA
1.7 that works with pbf files.

2016-09-25 18:52 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Yes, me neither. The first versions of GAMA 1.7 exhibit the same behavior. However, it works fine (even with 0.45) for osm and gz files (which are basically the same). Regarding bz2, it seems to be a problem encountered on the OSM forums in some cases: some files need to be decompressed in a certain way otherwise they fail. I wonder if it is not a question of UTF-8 encoding of some characters.

For pbf, the only clue I have is that the stream is closed at some point before the OsmosisReader has a chance to parse it. In the git version, where this reader is enclosed in a Thread (is it necessary ? because, essentially, the thread is created, started and then `join()` is called on it, which makes the current thread wait on it), two different calls to the parser seem to compete with each other. I've disabled both the thread and the computation of meta-data in the navigator, but it still fails.

**Comment by AlexisDrogoul** [comment]
I've been able to manage reading pbf files again. Dont know exactly how, though :) I've simplified the different calls and it works again. However, for bz2, we do have a problem, as some of them work again, but not others. 

It can be seen in this screenshot (one is displaying the correct number of objects, one is failing -- although its xml and pbf are correctly interpreted).

![modeling - features data importation models osm loading gaml - gama runtime 2016-09-26 09-42-24](https://cloud.githubusercontent.com/assets/579256/18821180/fb3662dc-83cd-11e6-8264-fd81e0d0e5bf.png)

I attach the two files to this thread if you want to make some experiments and see what's their difference... I suspect a different header and/or some encoding problem, but I dont know how to inspect this. This is a zip file containing the 2 bz2 files (as GitHub does not support bz2).



[Archive.zip](https://github.com/gama-platform/gama/files/492125/Archive.zip)

**Comment by AlexisDrogoul** [comment]
To close this issue, the display of metadata for failing bz2 files is now handled in a special way, indicating (when they fail): "error: decompress the file to an .osm file". So that the user is at least aware of a problem and of a solution...
