### ISSUE TITLE
Index out of bounds when playing with map

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2007]
### Steps to reproduce
1. Run this model
model naaaaaaaaew

experiment sss type:gui{
	map<int,string> a;
	reflex{
		int i<-rnd(5);
		a<<+i::""+i;
		write a;
		int j<-rnd(5);
		a>>-j::""+j;
		write a;
	}
}

2. Exception raises in GAMA after some step of simulation (running, not stepping).
1 occurence in sss0 at cycle 423: Java error: index out of bounds
in write a);
ArrayIndexOutOfBoundsException: null
in agent sss0
3.

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)
Gama git

**Comment by AlexisDrogoul** [comment]
The thing is that I dont really get what you're doing in this model. You ADD ALL to the keys of the map the 2 elements of a pair, the first being drawn randomly between 0 and 5, the second being its string value. That results in 2 key::value pairs in the map (1::1 and '1'::'1'). After that you draw another number and you REMOVE ALL the number and its string representation. Is that correct ?

**Comment by hqnghi88** [comment]
Dear Alexis,
I want to: add a pair to map, [doing something with map], remove a pair from map. I don't understand the mechanism why it got "out of bounds" because the case of removing "not exist" pairs still work at beginning.

add	4::"4" to map, we got map([4::'4'])
remove	5::"5"  from map, we got map([4::'4'])
add	2::"2" to map, we got map([4::'4',2::'2'])
remove	1::"1"  from map, we got map([4::'4',2::'2'])
add	3::"3" to map, we got map([4::'4',2::'2',3::'3'])
remove	0::"0"  from map, we got map([4::'4',2::'2',3::'3'])
add	5::"5" to map, we got map([4::'4',2::'2',3::'3',5::'5'])
remove	2::"2"  from map, we got map([4::'4',3::'3',5::'5'])
add	5::"5" to map, we got map([4::'4',3::'3',5::'5'])
remove	3::"3"  from map, we got map([4::'4',5::'5'])
add	2::"2" to map, we got map([4::'4',5::'5',2::'2'])
remove	1::"1"  from map, we got map([4::'4',5::'5',2::'2'])
add	5::"5" to map, we got map([4::'4',5::'5',2::'2'])
remove	0::"0"  from map, we got map([4::'4',5::'5',2::'2'])
add	3::"3" to map, we got map([4::'4',5::'5',2::'2',3::'3'])
remove	3::"3"  from map, we got map([4::'4',5::'5',2::'2'])
add	3::"3" to map, we got map([4::'4',5::'5',2::'2',3::'3'])
remove	5::"5"  from map, we got map([4::'4',2::'2',3::'3'])
add	3::"3" to map, we got map([4::'4',2::'2',3::'3'])
remove	3::"3"  from map, we got map([4::'4',2::'2'])
add	2::"2" to map, we got map([4::'4',2::'2'])
remove	3::"3"  from map, we got map([4::'4',2::'2'])
add	2::"2" to map, we got map([4::'4',2::'2'])
remove	2::"2"  from map, we got map([4::'4'])
add	1::"1" to map, we got map([4::'4',1::'1'])
remove	1::"1"  from map, we got map([4::'4'])
add	3::"3" to map, we got map([4::'4',3::'3'])
remove	1::"1"  from map, we got map([4::'4',3::'3'])

The model should be :
model naaaaaaaaew

experiment sss type:gui{
	map<int,string> a;
	reflex{
		int i<-rnd(5);
		a<<+(i::""+i);
		write "add\t"+i+"::\""+i+"\" to map, we got "+a;
		
		
		
		int j<-rnd(5);
		a>>-(j::""+j);
		write  "remove\t"+j+"::\""+j+"\"  from map, we got "+a;
	}
}

Actually it was something wrong with my ODE, I played with it several days, and I recognize this issue is exist with normal calculation without  ODE (Basically base on the TOrderedHashMap, I think).
P/s: I didn't get why we have (1::1 and '1'::'1'), because of the syntax <<+ is ADD ALL?

**Comment by hqnghi88** [comment]
In addition, issue or not? the syntax <+ and >- did not work for me

add	0::"0" to map, we got map([2::'2',0::'0',1::'1',5::'5',3::'3',4::'4'])
remove	3::"3"  from map, we got map([2::'2',0::'0',1::'1',5::'5',3::'3',4::'4'])
add	0::"0" to map, we got map([2::'2',0::'0',1::'1',5::'5',3::'3',4::'4'])
remove	0::"0"  from map, we got map([2::'2',0::'0',1::'1',5::'5',3::'3',4::'4'])

**Comment by AlexisDrogoul** [comment]
A map is an association between unique keys and (not mandatorily unique) values.

If you have an empty map, there are 3 main ways to add a "pair" inside:

`m<+ (0::'0')` will add 0 as a key and associates it with '0'
`m[1] <+ '1'` will associate 1 with '1'
`m <+ 1`; will add the pair 1::1

To remove elements, one has to use `>-' 

`m >- 1`will remove key 1 and its association (so `1` will be removed from the values)

However, if you write `m >- 1::'1'`, gama will lookup at the pair as a potential key (as pairs can also be keys of the maps) and so will not remove anything.

these statements have a ALL "variant" which works the same. The catch is that when you PUT ALL / ADD ALL a pair, it considers each elements of the pair (the first and the second) as as future key.

The problem seemed to occur, by the way, in the REMOVAL ALL (>>-) method.
