### ISSUE TITLE
Geometry with interior ring not considered with the new Display Architecture

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#2012]
I'll not have the time to correct this before my departure, so I write it here.

The GeometryObjectTransformer is computing fine the geometry which have no holes inside, but for the one with holes, there are some problems. The triangulation algorithm has to be a bit improved then. I think the easiest way to do so is simply to join each hole to the exterior ring to have only one exterior ring. So not much to change ;).

![image1](https://cloud.githubusercontent.com/assets/12977635/18987850/eaf777f4-872d-11e6-9620-e593f3644e31.png)

Example of GAML Code to test this functionnality : 

```
global
{
    init {
        create my_species;
    }
}

species my_species {
    aspect base {
        geometry geom1 <- polygon([{0,0},{5,-10},{40,0},{40,5},{10,5},{10,45},{40,45},{40,50},{0,50}]);
        geometry geom2 <- polygon([{0,0},{40,0},{40,50},{0,50},{0,45},{30,45},{30,5},{0,5}]);
        draw union([geom1,geom2]) color:#green;
    }
}

experiment expe type: gui
{
    output {
        display my_display type:opengl use_shader:true {
            species my_species aspect:base;
        }
    }
}
```

**Comment by agrignard** [comment]
Sounds like a tessellation problem... it reminds me good memories .-)

**Comment by AlexisDrogoul** [comment]
Yep. But havent we decided to use the JTS tessellation algorithms instead of the one in JOGL (or maybe the reverse ?). In any case, the one employed by default in the "classical" OpenGL displays was a very robust one so I'm surprised this is failing...

**Comment by AlexisDrogoul** [comment]
Regrouped with others in #2134
