### ISSUE TITLE
Some compilation errors in eclipse (may be my fault)

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2015]
### Steps to reproduce
I have 2 compilation errors in eclipse with the newest git.
1. In ValidationContext.java line 134
Multiple markers at this line
	- Type safety: The expression of type List needs unchecked conversion to conform to 
	 Iterable<? extends GamlCompilationError>
	- Type mismatch: cannot convert from Iterator<Object> to 
	 Iterator<GamlCompilationError>
2. In GamaFile.java line 302
Multiple markers at this line
	- Type safety: The expression of type IList needs unchecked conversion to conform to 
	 IList<K>
	- Type mismatch: cannot convert from Object to V

### Expected behavior
Tell us what should happen (include all relevant expectations)
I know that travis works well so
### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
May be something wrong on my side, I have try the Errors/Warnings in Preferences of Eclipse but it does not help.
Do we have any others configuration to make it work?
Thanks in advance.
### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Should be ok now (damn stupid Java not able to infer the types !)

**Comment by hqnghi88** [comment]
I have pull out and 3 of them are solved, but GamaFile.java line 302 still have :
- Type mismatch: cannot convert from Object to V

**Comment by AlexisDrogoul** [comment]
Well. Strange. getFromIndicesList() returns V values, so I dont see how it could complain about getting Object values... Did you change your compiler settings ?

**Comment by hqnghi88** [comment]
Did you mean Preference/Java/Compiler/Errors&Warnings? I did not change but even I tried with all Ignore, it did not help.

**Comment by AlexisDrogoul** [comment]
Closing / reopening the project, cleaning everything, relaunching Eclipse with "-clean", removing the error manually -- these sometimes help for sticky errors. Did you try ?

**Comment by hqnghi88** [comment]
Yes, sure, new eclipse neon, new git clone. I try with other pc now.

**Comment by hqnghi88** [comment]
I tried with eclipse Mars and it works. May be problem with my neon.
Thank you.

**Comment by hqnghi88** [comment]
Hi, I continue on this issue because it have one other more but may be still only on side.
ExperimentPlan.java line 225:
Type mismatch: cannot convert from Object to ExperimentAgent
Is it normal on your side?

**Comment by AlexisDrogoul** [comment]
No, dont have it.
