### ISSUE TITLE
Agent inspector/browser and multi-simulation: blank panel

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2016]
### Steps to reproduce
1. Open and run the Model Library/Toy Models/Ants/Ant foraging multi-simulation model

2. Inspect one of the agent

### Expected behavior
Get the inspector information in a panel

### Actual behavior
GAMA opens a blank (gray) panel

**Comment by AlexisDrogoul** [comment]
I can't reproduce it. Everything is working fine on my computer with the latest version.

**Comment by ptaillandier** [comment]
I tried to update GAMA (pull), restart my computer, clean the workspace,
create a new workspace, revert the preference to the default one... but I
still have this error (only for multi-simulation) (mac OS X, el capitan).

2016-10-06 12:51 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by hqnghi88** [comment]
Hi,
I can reproduce it with latest git.

**Comment by AlexisDrogoul** [comment]
Still can't. Can one of you make a dump of his preferences and attach it to this thread ?

**Comment by AlexisDrogoul** [comment]
Are there errors reported in the console ? (if nothing, try to enable the new preference on outputting display and outputs errors).

**Comment by hqnghi88** [comment]
Nothing even with new preference.

**Comment by hqnghi88** [comment]
Did you remember why InspectDisplayOutput.java line 243 have this question: "What to do in case of multi-simulations ??? "

**Comment by hqnghi88** [comment]
Hi,
The Inspector works only for the last simulation's display ( the 4th if 4 simulations).
