### ISSUE TITLE
Heatmap feature 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2017]
It would be great to have an HeatMap feature in GAMA.

We can take inspiration from here:

http://philippseifried.com/blog/2011/09/30/generating-heatmaps-from-code/

**Comment by hqnghi88** [comment]
Hi Arnaud, i don't know what are the mechanism and purpose of your heatmap,
but it really look like the diffusion map (a part of Partial diffetential
equations) that Benoit has developed. You can find some example in our
library (extension maths/diffusion statement)

**Comment by AlexisDrogoul** [comment]
Yep. Besides the tricks used (encoding into a 24bit color to store the information in a gradient map), it is either doable using diffusions or simply playing around with the grids' `color` and `gridValue` values. I guess a demo like this can be done in GAMA with a few lines of code (compared to the 2 pages of the example -- although it might not be as optimized, of course).

**Comment by agrignard** [comment]
Yes we can do it with using a grid but to have that fine grain we need a lots of cells...

**Comment by AlexisDrogoul** [comment]
Of course. But the link you sent is just a (clever) 2D image computation using blending and a palette, right ? With grids, you have more flexibility, you can output it in 3D very easily, you can take into account other elements (like obstacles, for example, or something like a "wind" effect) and the result can be queried by your agents in your simulation. You can even describe complex behaviors (e.g. different blending if you want) and have several "diffusions" occurring at the same time. Of course it requires a lot of horsepower and a lot of memory. 

BTW, if all you want is an image of a heat map, maybe you can superimpose a heat map chart layer with some transparency ?

**Comment by sriramab** [comment]
Some kind of heat map, using grid in GAMA , I did here.  Yes, need lot of cells, but I felt, you could do the same with a polygon layer, each polygon cell could be a gird cell.
https://www.youtube.com/watch?v=KU9ecNszFdU

**Comment by hqnghi88** [comment]
I consider this issue as closed... (the link died)

**Comment by AlexisDrogoul** [comment]
Please look at the new possibilities offered by `field` and `mesh` in implementing "heat maps"

**Comment by agrignard** [comment]
@AlexisDrogoul Awesome, I love it!! Yes we can definitely close this issue that will offer a lot of great new visualization! 
<img width="1092" alt="Screenshot 2021-07-15 at 14 56 41" src="https://user-images.githubusercontent.com/3928502/125792164-353dc967-c038-42c7-8feb-f4af18025b54.png">

**Comment by jdzucker** [comment]
Looks really nice !
Great job
Best

	 	
Jean-Daniel ZUCKER
Director • International Laboratory for Mathematical and Computational Modeling of Complex Systems (UMMISCO)
Senior Researcher • UMI 209 UMMISCO, IRD/SU, Bondy, France
Associate Researcher • Nutriomics, UMR-S 1269, INSERM/SU Laboratory
Homepage:  • [Skype] jdzucker
