### ISSUE TITLE
Format source creates more errors when the model already contains compilation error

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2018]
### Steps to reproduce
1. Open the following model:

```
model testFormat


global
{
	int max_K_paca <- 0;
	user_command "Create a hunter" { 
		create hunter nu mber: 1 with: [location::#user_location]{
			
		}
	} 
}

species hunter { } 

experiment testFormat type: gui {
	parameter "Paca max carrying capacity" var: max_K_paca min: 0 max: 100 category: "Carrying capacity" ; 
}
```

2. This model contains a compilation error (nu mber instead of number)

3. Select all the model, right-click on it and choose Source > Format

### Expected behavior
A better formatting of the model (e.g. to detect to missing closure brackets).

### Actual behavior
The Format introduces new compilation errors as it introduces space between facet names and the : symbol. As an example, the line starting by parameter becomes: 
parameter "Paca max carrying capacity" var: max_K_paca min : 0 max : 100 category : "Carrying capacity" ;

### System and version 
GAMA Git, MacOSX, El Capitan

**Comment by AlexisDrogoul** [comment]
Nothing we can do here to correct the behavior. The AST is wrong due to the error, and the formatter relies on the AST to create a formatted text. 
Instead, I have committed a fix that prevents formatting the source when the resource has errors (i.e. when the AST will be wrong).
