### ISSUE TITLE
Child species and map: warning 

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2021]
### Steps to reproduce
1. Write the following model:
model testChildMap
global {
	init {
		create childSpecies number: 10;
		map<parentSpecies, int> listAgs ;
		listAgs[one_of(childSpecies)] <- 1;
		
	}
}
species parentSpecies;
species childSpecies parent: parentSpecies;

experiment testChildMap type: gui ;

### Expected behavior
No warning

### Actual behavior
I get a waning for the line: listAgs[one_of(childSpecies)] <- 1;
"The type of the index of listAgs (parentSpecies) does not match
   with the type of one_of(childSpecies) (childSpecies). The latter
   will be casted to parentSpecies"

**Comment by AlexisDrogoul** [comment]
Cant reproduce it. I get no warning for this.

**Comment by ptaillandier** [comment]
Ok, with a clean workspace, the warning has disappeared....
