### ISSUE TITLE
bringing ?help to the interactive console

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2023]
Can it be possible to get help from interactive  console (IC) like in R. For example if you type the following in the IC: ?aspect 
then gama reads the section of aspect from the documentation and brings to the IC window. 

I had discussed this during the coding camp, but somehow it seems documentation does not recognise end of a operator description and the page just goes on and on .... till end of the document. This is also one of the issues that affects slow connections, especially the web help takes far too long to load.

Would it now be possible? Also the enhancement to bring the help to IC?

thank you.

**Comment by AlexisDrogoul** [comment]
Next commit will bring this. All features of GAMA are covered (skills, operators, species, attributes, primitives, constants). Reopen if you find anything wrong.

**Comment by sriramab** [comment]
Thank you for this update. It is very useful for beginners. I have realised two related issues. This feature would mean, a model has to be run before user can access the help via console. Do you think it (console) could also be available while in edit mode?

issue two and more important than the above, currently I notice that only description of the sought help is available and no sample code snippets/ statements. Would it be possible to show a sample code snippet on using the facet, operator etc. 

Then whole idea is overcome the lag time between availability of gama documentation ( all the pandoc processing) and the build availability. And also to reduce [ I carefully chose the word `reduce` instead of `avoid` :) ]the dependence on the web wiki. This would help in gama being a really independent tool. 

Just a petite opinion of social scientist. 😃

**Comment by sriramab** [comment]
Disclaimer (honestly no intention of nitpicking) .. when I used `?when` or `?when:` the console found no results. Is it meant to be like that?

Please see this the two issues above are not priority, just a luxury!

**Comment by AlexisDrogoul** [comment]
Hi,

I understand these points. However, they will not be solved immediately.

1) This point will be solved when #1421 will be addressed. That way, there will always be an agent to answer to you on the phone :)

2) snippets and other examples are currently a mess of different formats, etc. And most of the structures of the platform dont have any. And for the ones that have some, they are not indexed in the online help.

3) the facets are not indexed as well. It would require building a specific indexer for them; possible, but i'm afraid not a priority...

Will report any progress here !

Cheers
Alexis

**Comment by AlexisDrogoul** [comment]
Point 3 solved. It was actually easier than I thought.
