### ISSUE TITLE
Request: suppress #month and #year from the units

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2029]
### Problem

1. #minute, #second, #hour, etc. represent **exact durations** . We can even add #day and #week to this list (although, due to time-saving calendars, all the days, and hence all the weeks, do not have the same duration every year).

2. On the contrary, #month and #year represent **periods** of time defined by a calendar (of a given chronology). Their intrinsic value in terms of duration should vary over time and should not have any signification beside a given date **and** a given operation (the intrinsic value of a #month vary whether we add it or subtract it from a date, for instance). In GAMA, we have chosen, a bit lazily I must admit, to give them "default" values in a "fake" chronology, where months last 30 days and years 360 days.

3. Maintaining all these units together (allowing people to define steps with a value of 2#months, for instance, or 2#seconds, as they both had the same meaning) is a source a confusion in my opinion. This confusion is even higher when working with the dates. We can write `#now + 1#hour` in place of `#now add_hours 1` and both will be equal because we add the same duration. However `#now + 2#years` and `#now add_years 2` **will not be equal**.  

### Proposal
There are many ways to deal with this, and all require, more or less, to never have a notion of "month" or a notion of "year" independent of a date context. We could fix a default starting date (more or less the case right now) and have a "temporal" context like we have a "spatial" context, where #month and #year would have different values depending on the context, but it would probably be very costly to execute this, and there would be unavoidable evaluation problems. For instance: `(#now + 1 #year) - #now = 1#year` would return false in that case... Go explain this to a modeler !

So I propose to purely and simply remove these "units" (deprecate them first, then remove them) and, instead, invite the modeler to define, if needed, its own notions of "month" and "year" if he/she needs to (for instance, if you want the duration in seconds of a year now, `((#now minus_years 1) - #now)` will return it. Or if you simply want it to be a fixed duration `365 #days` will be sufficient in most cases. 

Since it might be handy to compute exact durations between two dates, I also propose to add two methods:  `years_between(date1, date2)` and also `months_between(date1, date2)`. All the other durations can be computed from the difference in seconds (i.e. `(date1 - date2) / #days`

**Comment by ptaillandier** [comment]
Hi,

I think it is a good idea to remove the #year and #month units (I discussed
about it with some GAMA modelers and there were also ok with this).

Cheers,

Patrick

2016-10-18 11:49 GMT+02:00 Alexis Drogoul <notifications@github.com>:
