### ISSUE TITLE
Compilation error with eclipse neon

### ISSUE THREAD

**Issue by ThomasHuraux** [gama-platform/gama#2032]
### Steps to reproduce
1. I'm using eclipse neon

2. I have the following compilation error :

```
	Type mismatch: cannot convert from Object to ExperimentAgent
	at msi.gama.kernel.experiment.ExperimentPlan.createAgent(ExperimentPlan.java:283)
```

### System and version
GAMA Platform - V1.7.0
Eclipse Neon Release (4.6.0)
Windows 10

**Comment by AlexisDrogoul** [comment]
I would advise you (as it is stated in the doc, here: https://github.com/gama-platform/gama/wiki/InstallingGitVersion#install-eclipse-mars-sr2) to use Mars instead of Neon, on which GAMA has not been tested.

**Comment by ThomasHuraux** [comment]
Ok, I will do that. Thanks.
