### ISSUE TITLE
install new software hangs gama on Windows 10

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2033]
### Steps to reproduce
1. Open GAMA 1.7, 24.10.2016 and go to install new software. For example install startexplorer from here http://basti1302.github.com/startexplorer/update/ .... gama hangs
2. Or try install Eclipse market place http://download.eclipse.org/releases/juno, it is installed. restart gama and try to go to marketplace and install any extension, doesnt work. gama just hangs
3. When I try step 2 with mars, it hangs.
### Expected behavior

Till about the version in august, it was possible to install market place and plugins via market place. 
### Actual behavior

GAMA hangs and has to be force exited.
### System and version

Gama 1.7 standalone 24.10.2016, java 8_112, windows 10

**Comment by AlexisDrogoul** [comment]
Hi,

I have tested this against the latest release and it works correctly (as it did before). Can you test with a fresh workspace to see if the problem comes from that ? 

Alexis

**Comment by sriramab** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12668606/19736495/ce5d1ea0-9baf-11e6-934a-66f10711d05b.png)

Hi Alexis, I changed workspace, but the same problem. 

Also  see that in windows standalone, there are two buttons in the menu that read - switch workspace. One contains "other" as submenu, while the other has no submenu.

![untitled2](https://cloud.githubusercontent.com/assets/12668606/19736606/54f43b56-9bb0-11e6-8515-4d25ff1956f2.png)

**Comment by AlexisDrogoul** [comment]
I've tested it, this time, on Windows 10, and I still can't reproduce it. I've installed StartExplorer and everything has been fine. So the problem comes from elsewhere (and for the double item in the menu, well, I dont have it either...). Did you install other extensions before  ?

**Comment by sriramab** [comment]
Yes, this is still a problem.  Could you try the following please: install eclipse market place inside GAMA standalone. and then from market place install start explorer. You should notice that as soon as you install eclipse marketplace plugin, GAMA hangs forever.  One can of course install plugins individually, but using marketplace is convenient to search and install.

**Comment by sriramab** [comment]
I close this issue. As soon as you create a complete new workspace, this is not a problem anymore. pity though having to copy all projects to new workspace.
