### ISSUE TITLE
Revert parameters button in Experiments does not behave as it should

### ISSUE THREAD

**Issue by PTranouez** [gama-platform/gama#2035]
### Steps to reproduce
For example:
1. Open Tutorial --> Predator Prey --> Model 03 
2. Launch experiment
3. Change Prey Max Energy from 1.0 to 2.0
4. Reload Simulation
5. Press the revert parameters button

### Expected behavior
I expect it to revert Prey Max Energy to 1.0, which is for me the initial value

### Actual behavior
It sticks to 2.0. It may make sense in the case of a simulation where parameters are changed by the actions of the agents during the simulation, but I think this is not the general case, and this is not the behavior generally expected. But hey, I may be the one who's buggy :-)
### System and version 
*** Date: mercredi 26 octobre 2016 11:30:26 heure d’été d’Europe centrale

*** Platform Details:

*** System properties:
MacOS 10.12.1 GAMA 1.7 10.25.16 Java 1.8.0_111
But it's probably a feature more than a bug: I doubt it is platform dependent.

**Comment by AlexisDrogoul** [comment]
Actually, yes, the initial value is considered with respect to the current simulation. If you change its "initial input" by doing a relaunch, like you did, then the value present in the parameters becomes the initial value of the new simulation. Otherwise, you have to reload the simulation (i.e. from the model view).

**Comment by PTranouez** [comment]
Do experiments parameters often change during simulations? I would have thought this is not the case. If I'm right, isn't the use case for the Revert button a bit too exotic?

But of course you're right, I can always close the experiment and reload from model to restore settings to saner values if I played with them too much.
