### ISSUE TITLE
Grid display with Shader

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2036]
### Steps to reproduce
1. Display a grid with use_shader_true '(e.g Data Importation/models/JSON file loading.gaml)
   <img width="1340" alt="screen shot 2016-10-27 at 10 03 06" src="https://cloud.githubusercontent.com/assets/3928502/19770333/daf19362-9c2c-11e6-9f0c-7880d6e68800.png">

2.

3.
### Expected behavior

We should see the line
### Actual behavior

We don't see line (see attached picture)
### System and version

Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Regrouped with others in #2134
