### ISSUE TITLE
Keystone values display interacting with light ?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2037]
Does any one have ever tried Keystone on Windows 7?

I am trying to use it but when I press "K" nothing happens...

**Comment by AlexisDrogoul** [comment]
Who the hell is still using Windows SEVEN ????

**Comment by agrignard** [comment]
right ;-)

**Comment by agrignard** [comment]
ok so the question is:

whoever is silly enough to run a computer with windows 7 , is GAMA compatible or not?

**Comment by tnguyenh** [comment]
I will try this tomorrow...

**Comment by tnguyenh** [comment]
OK everything works fine with Windows 7. However, we understood that there is an issue on a Mac...

This is what I get with windows 7:
![capture](https://cloud.githubusercontent.com/assets/18676913/19818991/c435a0b0-9d52-11e6-8147-a03c1dfd88e5.PNG)

This is what we get with Mac:
![screen keystone](https://cloud.githubusercontent.com/assets/18676913/19819029/f4785812-9d52-11e6-921f-30c9d37b7e20.png)

This is why Saad thought that nothing happened when pressing K, while using a black background...

**Comment by tnguyenh** [comment]
Just to be clear, it works on Mac, but the corners and numbers are just displayed as black circles and rectangles.

**Comment by agrignard** [comment]
ok this is so strange for me here I am testing on a Win7 computer and I get nothing when I press K... however it works on my mac...

<img width="1920" alt="screen shot 2016-10-28 at 15 37 05" src="https://cloud.githubusercontent.com/assets/3928502/19819818/6c2f5042-9d24-11e6-91f1-a97cc2c3154d.png">

**Comment by agrignard** [comment]
ok the corner and numbers are useful as you can the used it to load your keystone parameters.

**Comment by hqnghi88** [comment]
Hi, I have the black-background label as Tri's MacOS, but on my win10.

**Comment by hqnghi88** [comment]
with Procedural City, it works with lighting experiment: DisplayWithDynamicDiffuseLight , but black-background with experiment: DisplayTextured

**Comment by tnguyenh** [comment]
Hi, we still have the problem, and we are currently using it for a demo. The problem makes it quite difficult to use it (when we need to restart the simulation, we Gama crashes). A good enhancement (or a temporary patch) would be do display the corners coordinates in the console each time the K key is released. The main and important benefit would be that the user only needs to do a copy/paste from the console to the gaml file in order to set the keystone values configuration.

**Comment by AlexisDrogoul** [comment]
Hi,

I think the cause of this problem is whether lights are on or not. @hqnghi88 has probably identified it, as, with the same configuration, a model is working but not the other.

Alexis

**Comment by agrignard** [comment]
I close it at it is now in  #2105
