### ISSUE TITLE
Random color in road traffic 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2047]
### Steps to reproduce
1.I just ran the road traffic model and agent are not yellow any more. is it by purpose or maybe something related to the recent change sin term of initialization?

<img width="483" alt="screen shot 2016-11-08 at 11 15 40" src="https://cloud.githubusercontent.com/assets/3928502/20106946/d3f6e3b0-a5a4-11e6-87a5-5a4ee25daabc.png">

### Expected behavior
Random Color

### Actual behavior
yellow color (maybe because it was the default one)

### System and version 
Current version

**Comment by AlexisDrogoul** [comment]
Which model ?

**Comment by AlexisDrogoul** [comment]
In all the models of the "Driving Skill" folder, `color` is defined as `rgb color <- rgb([rnd(255),rnd(255),rnd(255)]) ;`, so yes, it is normal. They are yellow in the tutorial models.

**Comment by agrignard** [comment]
3D Visualization/models/Building Elevation.gaml

Ok sorry it's not a bug just someone that modifies it. People used to be yellow since ages but why not there have random color now:
rgb color <- rnd_color(255);

for me it put too much useless complexity  as the color does not represent any quantitative or qualitative attribute.
