### ISSUE TITLE
edge_betweenness operator for a graph

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2051]
Hi,

I am looking for a edge-betweenness operator which is similar to node-betweenness operator. I understand from the forums that it is easier to implement. Could you please add this operator to GAMA.

Thank you.

**Comment by ptaillandier** [comment]
I added a new operator: edge_betweeness. I also added an example of use of this operator in the Features/Graphs/Graph operator.gaml model

**Comment by sriramab** [comment]
Thank you Patrick. :) 👍

**Comment by sriramab** [comment]
Hi Patrick, Have you check if this is giving the correct results? I find it very strange results. I ran it on on graph in traffic tutorial 7.gaml and most of the highest betweenness indices are at the bottom of the graph where I feel nobody passes (shortest_path); i feel more or less the highest index should be for middle or middle to top parts of the roads. Could you please check if everything is ok?

**Comment by sriramab** [comment]
Also I dont think you committed the sample models (?). I updated my library but I dont see edge_betweeness in graph-operator.gaml

**Comment by ptaillandier** [comment]
Hi,

I think the results are good. I attached a figure obtained from the road
traffic tutorial: the highest is the edge betweenness index, the widest the
road is displayed.  Note that the edge betweenness indices of roads at the
bottom is quite high because there are many nodes (magenta square) at the
bottom.

The example is in the model Features/Graphs/models/Graph Operators.gaml

Cheers,

Patrick

2016-11-23 19:39 GMT+01:00 Srirama Bhamidipati <notifications@github.com>:

**Comment by sriramab** [comment]
Hmm, you seem to have forgotten the attachment. 
Secondly, edge-betweeness should be highly correlated to the betweenness-centrality, isnt ? 
I was trying to get the betweenness-centrality as output to a text file, I notices that this does not produce node_ids or vertex_id but their coordinates. Any reason that you do not output IDs ? 
Or could you suggest who to get also the nodeIDs with the betweenness-centrality. I like that in edge-betweenness it outputs the edgeID.

**Comment by ptaillandier** [comment]
I attached the file here :
![capture d ecran 2016-11-23 a 20 28 46](https://cloud.githubusercontent.com/assets/1506077/20579381/a032f710-b1cc-11e6-8df9-2e74f687f6b2.png)

Note that I compared the edge betweenness and the centrality betweenness and the results seem to be very correlated. I attached the model that I used to compared that  (compute ID from the road/points):  
[Model 03.txt](https://github.com/gama-platform/gama/files/610067/Model.03.txt)

**Comment by sriramab** [comment]
Thank you Patrick, I will have a look at it. It seems you have used the map:type to get the IDs. Thanks
