### ISSUE TITLE
draw random number from Gamma (shape,scale) distribution

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2052]
I would like to request an operator for drawing a random number from a Gamma Distribution given its shape and scale. Currently I am doing a lot of back and forth between R and GAMA and this process looks inefficient and creates a certain pause in the simulation especially with about 10000 elements requesting such a random value. 

I am not aware if GAMA already has a distributions library (stats?) to be able to draw such random numbers. 

I would like to request specifically Gamma (float Shape, float scale) operator. It probably exists in the stats extension of GAMA but does not have an operator?

Or  if some users are using an external plugin or created a plugin already, may be you wish to share here or in private?

thanks,

**Comment by ptaillandier** [comment]
Hi,

I just implemented a new gamma_rnd(shape, scale) operator. I added a use
example in the Features/Statistics/Statistic operators.gaml (or something
like that) model.

Cheers,

Patick

2016-11-22 17:52 GMT+01:00 Srirama Bhamidipati <notifications@github.com>:
