### ISSUE TITLE
Focus on an agent inside the inspect window

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2057]
When dealing with lots of agent, it's not always easy to localize them.

I was thinking: in the same way that we have the highlight boolean slider in the inspect window, would it be possible to also have a "focus on" option? So that you can easily localize the agent?

I know the focus option already exists but it's not in the inspect window.

**Comment by sriramab** [comment]
I have not tried but may be interactive console helps ? in interactive console you could type: 
focus_on species_agent(20);

**Comment by AlexisDrogoul** [comment]
The command is also available in the Agents menu. Maybe it would be
redundant to put it here. Or maybe we should implement the submenu in the
inspector?

Le 3 déc. 2016 1:33 AM, "Arnaud Grignard" <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Yep the command is also in the menu agent. I just notice that when you want to inspect a particular agent (e.g agent 321) you spend some time to find it in the Agent Menu and then you need to choose between 3 choice (Inspect, focus or highlight). Now imagine you choose inspect and then you want to focus on it, then you need to return to the Agent Menu scroll in the population refind the number 321 and ask for "focus on".

If possible I would be in favor to put everything in the inspect window. After all "focus on" and highlight is a kind of visual inspection no?

**Comment by sriramab** [comment]
yes, this quick and easy in interactive console. Please see commands: focus_on, highlight, inspect
just use the regular gaml syntax, and don't forget to end the command with a ;

**Comment by agrignard** [comment]
yes ok we can do it in a console... that's ok for people being used to use a console but what about "non coder" people? We are building a platform for every user not only for "coder" ;-)

**Comment by sriramab** [comment]
yes, i understand that very well, i am one of the non coders :) and i enjoy the interactive console.

I just mean the main advantage of interactive console is you do not have to go to long list agent menu, nor do you have pan all your model to find your agent and right click; just type in your species_agent(number) and you are zoomed in and inspect window also opens for further details.

I rest my case :)

**Comment by hqnghi88** [comment]
Hi,
My opinions are:
- interactive console are not only for coder, it's "interactive"!
- It would not be redundant to add a thing that increase the UX. But I don't support to add some more "sub-menu"
I think, we can provide the ability for the inspector view to : "**change the name, press enter, it focus the agent with name**".

**Comment by AlexisDrogoul** [comment]
The interest of putting a sub-menu here is that we can benefit (in the future, as it is not functional right now) from user commands defined in the code of a species, which would then become immediately available in the inspector of any agent of this species. A bit like the commands available for simulations. And the sub-menu would be exactly the same as the one available in the "Agents" menu.

**Comment by AlexisDrogoul** [comment]
I've implemented a working solution that provides more or less this menu (giving access to user_commands as well):

![road_traffic - users drogoul documents git gama msi gama models models features 3d visualization models building elevation gaml 2016-12-11 03-31-48](https://cloud.githubusercontent.com/assets/579256/21075976/96b2dcc6-bf52-11e6-95b2-4e9cd323c66e.png)

Please tell me if it is ok so that I can commit it.

**Comment by agrignard** [comment]
That was exactly what I was thinking! Maybe you can remove the "inspect" action as we are already in the inspect mode?
