### ISSUE TITLE
Chart flatification

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2059]
Is there a way to make the GAMA chart a bit more fancy ? I mean sometime I'd like to use the GAMA chart in a presentation but they don't look very very great (it's my opinion)

For instance I am not a super fan of the 90's effect of light diffusion that we have on the bar.

<img width="837" alt="screen shot 2016-12-07 at 12 53 06" src="https://cloud.githubusercontent.com/assets/3928502/20979836/38c43426-bc7c-11e6-84e6-b276d4a4028f.png">

What do you think? I would be more in favor to have something much more simple  bit like that 

<img width="916" alt="screen shot 2016-12-07 at 12 58 19" src="https://cloud.githubusercontent.com/assets/3928502/20979985/ddf70f22-bc7c-11e6-911d-21c4725b8611.png">

What do you think

**Comment by AlexisDrogoul** [comment]
I'm not in favor of anything so I added a preference (false by default to preserve the existing look) in the Displays section that allows to choose a default "flat" look to histograms.

**Comment by agrignard** [comment]
Cool!! Good idea to put a preference

**Comment by pcaillou** [comment]
I agree fancy is very important :)
And flat would be more in line with current Gama style (it should even
probably be flat by default).
The change to flatten is pretty straightforward (the two "non-flat" things
are the bars and the pie).
I am less used to preferences, I will juste have to find an example of
something else using a preference.

Philippe
(don't hesitate if you have other ideas to improve the chart fancyness!)

2016-12-08 15:55 GMT+01:00 Arnaud Grignard <notifications@github.com>:

**Comment by pcaillou** [comment]
Ok, I just saw Alexis already did the job, thanks!

Philippe

2016-12-09 14:11 GMT+01:00 Philippe Caillou <pcaillou@gmail.com>:
