### ISSUE TITLE
camera_pos strange behavior

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2061]
### Steps to reproduce
I just wanted to postiion my camera ina specific place on a given model.

I notice a very very strange behavior of the camera_pos facet.

In building elevation for instance if you put

display city_display type: opengl show_fps: true camera_pos: {world.location.x,world.shape.height*0.5,1000} camera_look_pos:{world.location.x,world.location.y,100}

this is what you get 
<img width="756" alt="screen shot 2016-12-07 at 16 13 15" src="https://cloud.githubusercontent.com/assets/3928502/20986805/15a074fc-bc98-11e6-955b-85b965976f1b.png">

The view is flipped but if you put

display city_display type: opengl show_fps: true camera_pos: {world.location.x,world.shape.height*0.6,1000} camera_look_pos:{world.location.x,world.location.y,100} then it's ok

### Expected behavior

{world.location.x,world.shape.height*0.5,1000} the camera shoudl be in the middle of the world

### Actual behavior
Flipped/rotated view

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by agrignard** [comment]
I don't know why but as soon at the value is under "world.shape.height*0.5" then we have this flipped behavior...

**Comment by dphilippon** [comment]
If you still need a quick fix, add the facet camera_interaction and set it to false for your display, it should manage the problem. I'm still looking at where exactly is the error in terms of computation in the code.

**Comment by AlexisDrogoul** [comment]
Fixed (albeit in a hacky way) by 2553eb21926cfc83603888c96ce2c602b088f3c6
