### ISSUE TITLE
Deadlock on GAMA launch (during Building workspace)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2062]
### Steps to reproduce
1. I pulled from GitHub the latest source code, clean, synchronize. I run GAMA and create a new workspace. I get a freeze of GAMA. The bar in the bottom show "Building workspace: (0%)".
Notice that in the Models pane, the three folders ( Library Models, Plugin Models and User models) appear empty (there is no number in the parentheses).

2. The profiling of this deadlock is the following one: 
Java-level deadlock detected

This means that some threads are blocked waiting to enter a synchronization block or
waiting to reenter a synchronization block after an Object.wait() call, where each thread
owns one monitor while trying to obtain another monitor already held by another thread.

Deadlock:

main is waiting to lock java.util.Collections$SynchronizedMap@4a85a3d8 which is held by Worker-5
Worker-5 is waiting to lock java.lang.Class@3a8ad810 which is held by main

Thread stacks

main [BLOCKED; waiting to lock java.util.Collections$SynchronizedMap@4a85a3d8]
 msi.gama.lang.gaml.ui.internal.GamlActivator.getInjector(GamlActivator.java:53)
 msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory.getInjector(GamlExecutableExtensionFactory.java:26)
 org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:51)
 org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:262)
 org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
 org.eclipse.emf.ecore.plugin.RegistryReader$PluginClassDescriptor.createInstance(RegistryReader.java:167)
 org.eclipse.emf.ecore.plugin.RegistryReader$ResourceFactoryDescriptor.createFactory(RegistryReader.java:189)
 org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.convert(ResourceFactoryRegistryImpl.java:92)
 org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$2.delegatedGetFactory(ResourceSetImpl.java:458)
 org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(ResourceFactoryRegistryImpl.java:144)
 org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(ResourceFactoryRegistryImpl.java:85)
 org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:431)
 org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:423)
 msi.gama.lang.gaml.resource.GamlResourceServices.getTemporaryResource(GamlResourceServices.java:207)
 msi.gama.lang.gaml.expression.GamlExpressionCompiler.getEObjectOf(GamlExpressionCompiler.java:1102)
 msi.gama.lang.gaml.expression.GamlExpressionCompiler.compile(GamlExpressionCompiler.java:177)
 msi.gama.lang.gaml.expression.GamlExpressionCompiler.compile(GamlExpressionCompiler.java:156)
 msi.gaml.expressions.GamlExpressionFactory.createExpr(GamlExpressionFactory.java:124)
 msi.gaml.descriptions.BasicExpressionDescription.compile(BasicExpressionDescription.java:95)
 msi.gaml.descriptions.SymbolDescription$2.visit(SymbolDescription.java:217)
 msi.gaml.descriptions.IDescription$FacetVisitor.execute(IDescription.java:70)
 msi.gaml.descriptions.IDescription$FacetVisitor.execute(IDescription.java:1)
 gnu.trove.map.hash.THashMap.forEachEntry(THashMap.java:319)
 msi.gaml.descriptions.SymbolDescription.visitFacets(SymbolDescription.java:155)
 msi.gaml.descriptions.IDescription.visitFacets(IDescription.java:212)
 msi.gaml.descriptions.SymbolDescription.compileTypeProviderFacets(SymbolDescription.java:212)
 msi.gaml.descriptions.SymbolDescription.computeType(SymbolDescription.java:467)
 msi.gaml.descriptions.SymbolDescription.getType(SymbolDescription.java:452)
 msi.gaml.descriptions.VariableDescription.getTitle(VariableDescription.java:273)
 msi.gaml.compilation.GamlIdiomsProvider.lambda$4(GamlIdiomsProvider.java:91)
 msi.gaml.compilation.GamlIdiomsProvider$$Lambda$81/1580751727.compare(unknown source)
 java.util.TimSort.binarySort(TimSort.java:296)
 java.util.TimSort.sort(TimSort.java:239)
 java.util.Arrays.sort(Arrays.java:1438)
 msi.gaml.compilation.GamlIdiomsProvider.<init>(GamlIdiomsProvider.java:91)
 msi.gaml.compilation.GamlIdiomsProvider.<init>(GamlIdiomsProvider.java:82)
 msi.gaml.compilation.GamlIdiomsProvider.<clinit>(GamlIdiomsProvider.java:46)
 ummisco.gama.ui.access.GamlAccessContents.createTable(GamlAccessContents.java:357)
 ummisco.gama.ui.access.GamlSearchField.createWidget(GamlSearchField.java:163)
 ummisco.gama.ui.access.GamlSearchField.installOn(GamlSearchField.java:449)
 msi.gama.lang.gaml.ui.reference.GamlReferenceSearch$1.runInUIThread(GamlReferenceSearch.java:51)
 org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
 org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
 org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
 org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
 org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
 org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
 org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
 org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
 org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
 org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
 org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
 org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
 org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
 msi.gama.application.Application.start(Application.java:42)
 org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
 org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
 org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
 org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
 org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
 sun.reflect.NativeMethodAccessorImpl.invoke0(native method)
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.lang.reflect.Method.invoke(Method.java:497)
 org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
 org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
 org.eclipse.equinox.launcher.Main.run(Main.java:1515)
 org.eclipse.equinox.launcher.Main.main(Main.java:1488)

Worker-5 [BLOCKED; waiting to lock java.lang.Class@3a8ad810]
 msi.gama.lang.gaml.resource.GamlResourceServices.getTemporaryResource(GamlResourceServices.java:190)
 msi.gama.lang.gaml.expression.GamlExpressionCompiler.getEObjectOf(GamlExpressionCompiler.java:1102)
 msi.gama.lang.gaml.expression.GamlExpressionCompiler.compile(GamlExpressionCompiler.java:177)
 msi.gama.lang.gaml.expression.GamlExpressionCompiler.compile(GamlExpressionCompiler.java:156)
 msi.gaml.expressions.GamlExpressionFactory.createExpr(GamlExpressionFactory.java:124)
 msi.gaml.descriptions.BasicExpressionDescription.compile(BasicExpressionDescription.java:95)
 msi.gaml.descriptions.SymbolDescription$4.visit(SymbolDescription.java:673)
 msi.gaml.descriptions.IDescription$FacetVisitor.execute(IDescription.java:70)
 msi.gaml.descriptions.IDescription$FacetVisitor.execute(IDescription.java:1)
 gnu.trove.map.hash.THashMap.forEachEntry(THashMap.java:319)
 msi.gaml.descriptions.SymbolDescription.visitFacets(SymbolDescription.java:155)
 msi.gaml.descriptions.IDescription.visitFacets(IDescription.java:212)
 msi.gaml.descriptions.SymbolDescription.validateFacets(SymbolDescription.java:645)
 msi.gaml.descriptions.SymbolDescription.validate(SymbolDescription.java:571)
 msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:741)
 msi.gaml.descriptions.SymbolDescription$5.visit(SymbolDescription.java:767)
 msi.gaml.descriptions.TypeDescription.visitChildren(TypeDescription.java:553)
 msi.gaml.descriptions.SpeciesDescription.visitChildren(SpeciesDescription.java:892)
 msi.gaml.descriptions.ModelDescription.visitChildren(ModelDescription.java:366)
 msi.gaml.descriptions.SymbolDescription.compileChildren(SymbolDescription.java:763)
 msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:748)
 msi.gaml.compilation.kernel.GamaMetaModel.getAbstractModelSpecies(GamaMetaModel.java:159)
 msi.gama.kernel.root.PlatformAgent.<init>(PlatformAgent.java:82)
 msi.gama.runtime.GAMA.getPlatformAgent(GAMA.java:413)
 msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider.createDescriptions(BuiltinGlobalScopeProvider.java:444)
 msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider.<clinit>(BuiltinGlobalScopeProvider.java:270)
 sun.reflect.NativeConstructorAccessorImpl.newInstance0(native method)
 sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 java.lang.reflect.Constructor.newInstance(Constructor.java:422)
 com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:85)
 com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
 com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
 com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
 com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 com.google.inject.Scopes$1$1.get(Scopes.java:65)
 com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
 com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
 com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
 com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 com.google.inject.Scopes$1$1.get(Scopes.java:65)
 com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
 com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
 com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
 com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
 com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
 com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
 com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 com.google.inject.Scopes$1$1.get(Scopes.java:65)
 com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
 com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
 com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
 com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:83)
 com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
 com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
 com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
 com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
 com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
 com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
 org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry.registerContextTypes(XtextTemplateContextTypeRegistry.java:45)
 org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry.<init>(XtextTemplateContextTypeRegistry.java:38)
 sun.reflect.NativeConstructorAccessorImpl.newInstance0(native method)
 sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 java.lang.reflect.Constructor.newInstance(Constructor.java:422)
 com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:85)
 com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
 com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
 com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
 com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 com.google.inject.Scopes$1$1.get(Scopes.java:65)
 com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
 com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
 com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
 com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
 com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
 com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
 com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
 com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 com.google.inject.Scopes$1$1.get(Scopes.java:65)
 com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
 com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
 com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
 com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
 com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
 com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
 com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
 com.google.inject.Guice.createInjector(Guice.java:95)
 com.google.inject.Guice.createInjector(Guice.java:72)
 com.google.inject.Guice.createInjector(Guice.java:62)
 msi.gama.lang.gaml.ui.internal.GamlActivator.createInjector(GamlActivator.java:67)
 msi.gama.lang.gaml.ui.internal.GamlActivator.getInjector(GamlActivator.java:55)
 msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory.getInjector(GamlExecutableExtensionFactory.java:26)
 org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:51)
 org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:262)
 org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
 org.eclipse.xtext.internal.ResourceServiceProviderDescriptor.getExtension(ResourceServiceProviderDescriptor.java:46)
 org.eclipse.xtext.internal.AbstractResourceServiceProviderDescriptor.get(AbstractResourceServiceProviderDescriptor.java:20)
 org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl$InternalData.getServiceProvider(ResourceServiceProviderRegistryImpl.java:46)
 org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl.getResourceServiceProvider(ResourceServiceProviderRegistryImpl.java:109)
 org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl.getResourceServiceProvider(ResourceServiceProviderRegistryImpl.java:129)
 org.eclipse.xtext.ui.resource.UriValidator.isValid(UriValidator.java:27)
 org.eclipse.xtext.ui.resource.Storage2UriMapperImpl.isValidUri(Storage2UriMapperImpl.java:247)
 org.eclipse.xtext.ui.resource.Storage2UriMapperImpl.getUri(Storage2UriMapperImpl.java:233)
 org.eclipse.xtext.builder.impl.ToBeBuiltComputer.getUri(ToBeBuiltComputer.java:345)
 org.eclipse.xtext.builder.impl.ToBeBuiltComputer.updateStorage(ToBeBuiltComputer.java:287)
 org.eclipse.xtext.builder.impl.ToBeBuiltComputer$2.visit(ToBeBuiltComputer.java:260)
 org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:119)
 org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:83)
 org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
 org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
 org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
 org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
 org.eclipse.core.internal.resources.Resource.accept(Resource.java:93)
 org.eclipse.core.internal.resources.Resource.accept(Resource.java:51)
 org.eclipse.core.internal.resources.Resource.accept(Resource.java:116)
 org.eclipse.core.internal.resources.Resource.accept(Resource.java:104)
 org.eclipse.xtext.builder.impl.ToBeBuiltComputer.updateProject(ToBeBuiltComputer.java:254)
 org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:318)
 org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
 org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
 org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
 org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
 org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
 org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
 org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Frozen threads found (potential deadlock)

It seems that the following threads have not changed their stack for more than 10 seconds.
These threads are possibly (but not necessarily!) in a deadlock or hung.

process reaper <--- Frozen for at least 53s
java.lang.UNIXProcess$ProcessPipeInputStream.processExited() UNIXProcess.java:528
java.lang.UNIXProcess.lambda$initStreams$271() UNIXProcess.java:299
java.lang.UNIXProcess$$Lambda$7.run()
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1142
java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:617
java.lang.Thread.run() Thread.java:745

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
GAMA Git, MacOSX, java 8

**Comment by benoitgaudou** [comment]
Note that this does not occur in a workspace that already contains user models.

**Comment by AlexisDrogoul** [comment]
Does it appear every time in the same workspace ? I mean, is it a systematic behavior or a random one? In that case, the state of the workspace matters a lot (open editors, etc.)

**Comment by benoitgaudou** [comment]
This seems to occur 100% of time when I launch GAMA and choose to create a new workspace.

But I never faced it in other cases (no problem with workspace with or without user models and even no issue when I choose a workspace than made GAMA freezed in the previous launch).
