### ISSUE TITLE
"Show in editor" does not work

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2065]
### Steps to reproduce
1. Make some error in simulation time to have the Error View.

2. Right-click on the error and chose "Show in editor"

### Expected behavior
Tell us what should happen (include all relevant expectations)
It should open a new editor which show the error message
### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
Nothing happens
### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Please document the type of error you are generating, whether or not the editors were already opened, and whether the model file was already opened also.

**Comment by hqnghi88** [comment]
Relating with #2064 , it was a Java error: nil value detected. There is no opened Error Editor and the model editor is already opened in same time with simulating displays

**Comment by AlexisDrogoul** [comment]
Well, for me, it works correctly. The editor is automatically opened (no need to invoke "Show in editor") and correctly positioned to the line of the error. Subsequent calls to "Show in editor" also work.

**Comment by hqnghi88** [comment]
OK, so may be it is related with Oxygen Release Milestone 3 (4.7.0 M3) and Windows 10 UI.

**Comment by hqnghi88** [comment]
It works well with a clean eclipse projects and synchronize in the .product. I close this issue.
