### ISSUE TITLE
Enhancement of error reporting: add a report button 

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2066]
### Steps to reproduce
1. When an error occurs in the Error View of GAMA, It should be nice to have a Report Button in that View to submit the issue to GitHub with all the environmental informations.

### Expected behavior
Tell us what should happen (include all relevant expectations)
A button
### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Should probably use this: https://developer.github.com/v3/issues/#create-an-issue

But I have no idea on how to invoke this API. Moreover, I am a bit concerned about the fact that we could be flooded by modeling errors (i.e. in the users' models) and not bugs (i.e. in the Java code).

**Comment by hqnghi88** [comment]
These api would be invoked by httprequest (post/get) in java. 
Yes, we would be flooded but I think we have further some policies: environemental informations, i.e. username, labeling, tagging, and time limited by GitHub, or even a new GitHub repos dedicated for errors or other tricks.
Well , it 's not urgent for the moment.

**Comment by AlexisDrogoul** [comment]
The more I think about it, the more I feel it might be a problem to do so. Think about all the people who have NPEs in their model, not because GAMA is at fault, but because they have `nil` somewhere... I will try to find a better solution, however, to ease the reporting of issues.

**Comment by AlexisDrogoul** [comment]
I implemented a compromise: a new contextual menu item has been added to errors, allowing to "Report error on GitHub". Then it simply directly opens an internal browser on the "new issue" page (asking for credentials the first time). Nothing more, nothing less. For me it is sufficient. Re-open if you need more features !
