### ISSUE TITLE
Small Compilation issue about color attribute

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2067]
### Steps to reproduce

Not really sure if it's a bug or a feature...

1. Create a basic species

species people {
	aspect base{
	  draw shape color:color;		
	}
}

2. Init the species

create people number:100{
 color <- #black;
}

### Expected behavior
We should have a compilation error as color does not exist in the species people?

### Actual behavior
It compiles but the color is not updated, if you declare the attribute color inside the species people then it works.

We should have an error or at least a warning if the user forgot to create the color variable

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Actually, no. If you take the time to look at the pop-up on `color`, GAMA will tell you that it is a global attribute (of model, in that case). So you have the right to use it (as you can use any global attribute defined in simulations).

**Comment by agrignard** [comment]
Ok I get the point. 

It might be confusing because a user can think (if he/She forgets to declare a color variable for the species) that he is manipulating the people color. But ok there is a pop-up (that I did not see indeed)
