### ISSUE TITLE
texture flipped

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2068]
I don't know when and how it happens but there is something wrong with the texture!

For instance run built-in shapes the GAMA logo is kind of flipped vertically (see attached picture) and actually I also notice it on other model...

It's a question of TEXTURE_2D position that is wrong 
<img width="1225" alt="screen shot 2016-12-12 at 17 15 54" src="https://cloud.githubusercontent.com/assets/3928502/21119075/d77c5b14-c08e-11e6-9979-f75a919b3072.png">

**Comment by AlexisDrogoul** [comment]
Normal OpenGL or shader architecture ?

**Comment by agrignard** [comment]
both.

**Comment by AlexisDrogoul** [comment]
Fixed by 2553eb21926cfc83603888c96ce2c602b088f3c6 (for the "normal" architecture).
