### ISSUE TITLE
Enhancement: redraw a scene without iterating through the simulation

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2071]
I think it would be great (maybe in a global action of the world or/and in the world inspection) to be able to redraw a scene without going to the next step of the simulation

For instance imagine you want to draw a circle with a fixed size in pixel and then you want to see different zoom level. Now if you want the circle to update their size according to the zoom level you need to run one simulation and then everything is redrawn.

The drawback of that is that you are not anymore in the iteration you wanted but at t+1 (which can be very different especially if you do data visualization)

With this feature you can update the view without updating the simulation

**Comment by AlexisDrogoul** [comment]
Have you tried `        ask experiment {do update_outputs();}` ?

**Comment by agrignard** [comment]
yep this work.

Not in favor to have a button somewhere from that? Is is to specific? Personally I think it's a nice feature

**Comment by AlexisDrogoul** [comment]
No, I'm not really in favor of multiplying buttons. You can implement one if you want in the Views menu or somewhere else. Otherwise, you could perfectly add a button to your simulation if you define a user_command in the model.
