### ISSUE TITLE
Define a size as a parameter in pixel

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2072]
### Steps to reproduce
1.I just notice that 

draw circle(2#px);

gives a different results than
float size <-2#px;
draw circle(size);

2.

3.

### Expected behavior
I would expect the same aspect

### Actual behavior
draw circle(2#px); give me a circle without border
![px](https://cloud.githubusercontent.com/assets/3928502/21157373/12749cf0-c147-11e6-9c06-7f8c1b397a13.png)

draw circle(size) give smaller circle with black border
![size](https://cloud.githubusercontent.com/assets/3928502/21157381/1688d004-c147-11e6-82b5-ad73669ecc05.png)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by ptaillandier** [comment]
Hi,

The result seems to be normal to me as the #px is a dynamic value whereas the size variable is static (just initialized at the beginning of the simulation)

The best way to achieve what you want is to write:
float size <-2;
draw circle(size#px);

**Comment by agrignard** [comment]
Ok thanks
