### ISSUE TITLE
user_command and action factorization

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2073]
### Steps to reproduce
I don't know how hard it is to implement this and I know it's a detail but

instead of writing:

user_command "Show trajectory" action:showTrajectory;
action showTrajectory{
...
}	
we could gain on line by writing this
action showTrajectory user_command:true{
...
}

**Comment by AlexisDrogoul** [comment]
Since the purpose is to gain a line, why not writing:
```
user_command showTrajectory {
...
}
```

?

**Comment by agrignard** [comment]
even better ;-)
