### ISSUE TITLE
Enhancement: Inheritance for display

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2074]
When using different display we sometime need to repeat several time the same information what about having a concept of inheritance for the display?

e.g
```
display France 
{   
  species building aspect: base refresh:false;
  species road aspect: base refresh:false;
  species people aspect: france;
}
display Spain 
{   
  species building aspect: base refresh:false;
  species road aspect: base refresh:false;
  species people aspect: spain;
}
```
at the end the only difference between both display is only one line
```
species people aspect: france;
```
vs
```
species people aspect: spain;
```

Would it be possible to have a "parent" display like that:
```
display ParentDisplay 
{   
  species building aspect: base refresh:false;
  species road aspect: base refresh:false;
}
```
and then we can imagine having
```
display France parent:ParentDisplay
{   
  species people aspect: france;
}
```

**Comment by AlexisDrogoul** [comment]
I come back to this one. The problem of having a "parent" display is that it would also show up, which is not really what you want. So this solution should also include the possibility to "hide" a display or declare it as abstract.

**Comment by agrignard** [comment]
Being able to declare abstract display can be a good option indeed

**Comment by AlexisDrogoul** [comment]
I have implemented the main part. It is now possible to declare displays as "virtual" (like species), which basically corresponds to abstract. It is also possible to add a facet "parent:" to the displays, passing the id (or a string if the id contains spaces) of the "parent" display from which to inherit. This parent can be in the same output definition or inherited from another experiment (if the enclosing experiment inherits from this other experiment).  The conflicts that might arise between layers are however not handled: redefining a layer will simply "erase" the inherited one if they have the same name. 

From now on, what I've implemented covers almost everything. I will close this request for enhancement -- please open a new issue if some problems arise.

**Comment by agrignard** [comment]
Nice feature i'm trying it but what is the syntax

display view1 virtual:true ? doesn't work

Also does the display need to be defined in the same experiment?

is it possible to have this
```
exp 1{
display view1 virtual:true
}

exp2{
  display view2 parent:view1
}
```

**Comment by AlexisDrogoul** [comment]
Well, should work. It works in my environment. If you use the Eclipse version, be sure to rebuild everything. Displays can inherit from displays defined in the same `output`/`permanent` block or from the ones defined in a parent experiment.

**Comment by agrignard** [comment]
It doesn't work in my case.

If I write this 
````experiment exp1 type:gui{
	output {
		display view1 virtual:true{	
		}
	}
}

experiment exp2{
	output {
  		display view2 parent:view1{
  	}
  }
}
```
I get the following error:

**Comment by agrignard** [comment]
It compiles when the 2 display are defined in the same experiment but the point is to be able to call a virtual display from different experiment

```
experiment exp1 type:gui{
	output {
		display view1 virtual:true{	
		}
		display view2 parent:view1{
	}
	}
}
```

**Comment by agrignard** [comment]
Ok my bad it's working I forgot to make the inheritance the syntax is
```
experiment exp1 type:gui{
	output {
		display view1 virtual:true{	
		}
	}
}

experiment exp2 parent:exp1{
	output {
  		display view2 parent:view1{
  	}
  }
}
```

**Comment by agrignard** [comment]
Great feature!!!!!!! save a lot of duplication code!!

**Comment by agrignard** [comment]
Just to finish on this issue. 

Does it makes sense to also have virtual experiment? In the exemple above there is no point to run exp1 as it only has a virtual display, so why not considering exp1 as a virtual one?

**Comment by AlexisDrogoul** [comment]
Since https://github.com/gama-platform/gama/commit/77734d96048aa9b9f90ee3b1f6982cb5175b0740, `species` and `experiment` can now sport the `virtual` boolean facet. This fixes the issue here.
