### ISSUE TITLE
graphics data position:{x,y,z} {...}

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2075]
It's a nice feature to be able to move a graphics layer with the position facet however it does not seem to take the z value into account.

**Comment by AlexisDrogoul** [comment]
It works on my version (with a z between 0 and 1, the latter being -- probably -- the altitude of the camera itself).

**Comment by agrignard** [comment]
you're right it works with value between 0 and 1 (relative value) but not with absolute.  x and y work in absolute

**Comment by AlexisDrogoul** [comment]
I also close this issue as the `world` has usually no predefined z value, which means it would be difficult to pass absolute values. I've modified the documentation accordingly.
