### ISSUE TITLE
"open in finder" option when right clicking on a file 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2077]
in the model library browser, a "open in finder" option when right clicking on a file would be great.

**Comment by AlexisDrogoul** [comment]
You can install the StartExplorer plugin for that (see https://github.com/gama-platform/gama/wiki/InstallingPlugins#startexplorer). If you run the developer version, install it in Eclipse and include the plugin in your run configuration, otherwise simply install it in GAMA.

**Comment by agrignard** [comment]
ok i did not know this package. Well yes I can install it however I was more thinking in general for the user lambda to have an "open in finder" by default. I guess that we don't put this plugin by defaut to avoid one more dependency? Anyway it's a detail
