### ISSUE TITLE
save statement in features in model library does not save

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2081]
### Steps to reproduce
1.  In latest builds, use the features> savetoshp example

2. try running - basically saving a shapefile.

3. I tried to save it as a different name by adding a new line from the save statement . But when you run the model, no shapefile is saved.

### Expected behaviour
I expect a shapefile to be saved with a name i gave

### Actual behaviour
Nothing saved as requested

### System and version 
macos, latest build 14 december 16

**Comment by ptaillandier** [comment]
I have tested on the latest build (14 december) and the save statement works. To test it, just copy the model in your workspace and test it.

However, there is a problem with the model library that seems to be in read-only mode. With this release, you cannot modify the files in the model library, neither write new files insides (for example the building shapefile).

**Comment by sriramab** [comment]
Makes sense to make it read only. Thank you Patrick.
