### ISSUE TITLE
save attributes to shapefile saves only latest attribute if field duplicated

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2084]
### Steps to reproduce
In any model save agents as a shapefile with some attributes. For example I used the following:
`action save2shp{
		save road to:"../includes/buildings.shp" type:"shp" with:[age::"AGE", age::"new" , my_id::"MYID", my_id::"something"] crs:"EPSG:28992";
	}` 

I wanted to save same variable into two attributes of shapefile. But only the latest variable was saved. 

### Expected behavior
same GAMA variable to be saved into different attributes of shapefile.

### Actual behavior
Only the latest saved.  in the example above only `new` and `something` were saved.

### System and version 
WIndows 7, GAMA standalone 28.12.2016

I do not know if this is intended or a bug. If not a bug, please remove the bug tag.

**Comment by ptaillandier** [comment]
Hi,

I think it is due to the fact that the with statement accept as argument a map. In a map, the key are unique, as you as you have two pairs with the same key, GAMA only takes the second pair into account. To save two "attributes" from the same variables, a solution could be to change the keys and values (the keys will be the attribute names in the shapefile, and the values the agent variables), but, it will introduce a lot of bugs in existing models. I am sure Alexis has a opinion about it ;) .

**Comment by sriramab** [comment]
Hi

I wanted to actually save some attributes to shapefiles. These attributes would be results of some calculations on a gama variable. I thought it would be easier to do this calculations right within the save statement for example: 
`save something as shapefile with: v1::attribute1 ,log(v1)::attribute2 ,sin(max(list_v2)::attribute3 `

that obviously did not work. So I started trying with passing variables with same value to different shapefile attributes so that I can do some calculations on the GIS side (outside GAMA). So I had this question in the issue.

I finally just created new variables within GAMA with some calculations before the save statement and saved them as new variables and then used the save statement.

just wanted to add a context :)

**Comment by AlexisDrogoul** [comment]
Well... Patrick is right. The map passed as an argument to `save` will automatically remove duplicated keys. 

I agree that the syntax is a bit awkward as it is now. It would be much clearer to reverse the keys and values of the map (and to introduce the possibility to do computations in the values, so as to achieve your initial goal). It would create a lot of problems, for sure... One possibility could be to introduce a new facet called `attributes` to serve this purpose.

**Comment by ptaillandier** [comment]
The attributes facet can be a good idea.

2017-01-04 4:49 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by sriramab** [comment]
Ok, then it is not a bug. I shall keep it as enhancement.

**Comment by AlexisDrogoul** [comment]
I have implemented the `attributes` facet for shape files (does not work, though, for csv files). Basically, it works as described above, as a kind of reversed form of `with`. It expects a `map` where the keys are the attribute names in the shape file and the values are any expressions (incl. names of vars) that can be executed, in turn, by each agent saved into the shape file. Note that `attributes` and `with` are exclusive. If both are declared, only `with` will be considered (for considerations of retro-compatibility).

**Comment by sriramab** [comment]
Please show an example save statement (to learn the syntax)

**Comment by AlexisDrogoul** [comment]
the "Save to SHP.gaml" model file of the library has already been updated.
