### ISSUE TITLE
Wrong number of elements in a map at creation

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2086]
### Steps to reproduce
1. In a species, I have a map<int, int> attribute, initialize at hand with 3 pairs:
map<int,int> dung_kgDM_Ncontent <- ([rnd(10)::rnd(10),rnd(10)::rnd(10),rnd(10)::rnd(10)]);

2. I initialize the model by creating 10 of these agents and I display the map for each agent (follows the complete model).

model testMap

global {
	init {
		create plot number: 10;
		
		loop p over: plot {
			write "" + p + " - " + p.dung_kgDM_Ncontent;			
		}		
	}
}

species plot {
	map<int,int> dung_kgDM_Ncontent <- ([rnd(10)::rnd(10),rnd(10)::rnd(10),rnd(10)::rnd(10)]);
}

experiment testMyriam type: gui {
	output {}
}

### Expected behavior
I am expecting to have 3 elements in each map.

### Actual behavior
I get a random number of element (from 1 to 3).

### System and version 
GAMA Git, MACOSX

**Comment by AlexisDrogoul** [comment]
Well. I'm keen to close this immediately, as what you obtain is perfectly normal : some of the `rnd(10)` keys will produce the same result, and will then represent only one entry. Or didn't I understand the problem well ?

**Comment by benoitgaudou** [comment]
OK, my bad! I may be a little bit rusted after holiday!
Thanks
Benoit
