### ISSUE TITLE
Importation of IFC BIM files

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2091]
"The Industry Foundation Classes (IFC) data model is intended to describe building and construction industry data [...] and is a commonly used collaboration format in Building information modeling (BIM) based projects." (wikipedia).

For many countries (France included), BIM are now mandatory for construction projects and so it can be interesting to be able to import this kind of vector files to create geometries (for instance, if we studies the evacuation of a building, being able to directly import a IFC file to create the building (walls, windows and so on) is very promising).

**Comment by ptaillandier** [comment]
With the help of Franck Taillandier, I made some investigations on the importation of IFC files. There is a java lib that can be used: http://www.ifctoolsproject.com/

For a free IFC viewer on mac/windows, this software can be used: https://www.solibri.com/

**Comment by agrignard** [comment]
Hi Patrick,

That's a nice feature, I was discussing yesterday with a colleague about
those BIM Format and I was wondering how to deal with this in GAMA.

I am happy to test it and help you on that

Arnaud

**Comment by ptaillandier** [comment]
To give some news, I have just commit a first draft version of a new plug-in dedicated to the loading of such file. The current version is barely usable (it will crash for most IFC files), but at least allows to generate some geometries from IFC files (see the 2 attached pictures.... no idea why there is a tree inside the building).

![capture d ecran 2017-01-12 a 16 58 04](https://cloud.githubusercontent.com/assets/1506077/21898100/f9e20efe-d8eb-11e6-9c70-c7dd2846f99b.png)
![capture d ecran 2017-01-12 a 16 57 44](https://cloud.githubusercontent.com/assets/1506077/21898104/fcfd38fc-d8eb-11e6-8f1d-dcfc36edb374.png)

**Comment by ptaillandier** [comment]
Just to give some news: I am able to generate the walls and the slabs with their attributes  (at least for simple geometries), but I have still a problem with the location of openings (reading the IFC spec guide + the javadoc of the lib that I used is like reading Chinese for me..... I cannot get the logic behind it).

**Comment by sriramab** [comment]
could you post a link and page number to the exact text of IFC spec for openings.

**Comment by ptaillandier** [comment]
Here: http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/index.htm
+ javadoc : file:///Users/administrateur/Downloads/ifc2x3javatoolbox_doc_2.0.1_20130524/index.html
Like this, it seems simple, but when I read the data, all become messy ;) .

**Comment by ptaillandier** [comment]
I am closing this issue as we are now able to load in a "acceptable" way the simple IFC files (you just have to add the extension miat.gama.extensions.ifcfile - we will soon deploy the plug-in in order to give the possibility to the GAMA release users to install this plug-in).
