### ISSUE TITLE
Random generator by default in Parameter window

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2092]
I know I already ask this and the answer was no, but who knows maybe one year after the answer would be different.

In order to get the most minimal interface I have always been dubious about the fact to always have by default the type of number generator as a parameter. I am quiet sure that no one uses it on a regular basis however everyone have it by default in its parameters window.

Would it be possible to set a preferences for that ?
(true by default why not even if I would be in favor to put it to false by default)

**Comment by AlexisDrogoul** [comment]
![monosnap 2017-01-11 23-24-04](https://cloud.githubusercontent.com/assets/579256/21856597/1ac1bda0-d855-11e6-9147-bfd1217c13d1.png)

**Comment by agrignard** [comment]
oups sorry ;-)

**Comment by agrignard** [comment]
And having it to false by default is not an option right?
