### ISSUE TITLE
(Enhancement) Logarithmic charts

### ISSUE THREAD

**Issue by nordie69** [gama-platform/gama#2096]
### Subject of enhancement
Logarithmic charts

### Expected behavior
At least the y-axis but also the x-axis of the charts should be able to use a logarithmic scale to display such type of scientific data in the right way. By using logarithmic scale on both axis a double-logarithmic chart should be able to be created.

### Actual behavior
There is no option in GAML to set up neither the y- nor the x-axis with a logarithmic scale.

### System and version 
All versions of GAMA.

**Comment by AlexisDrogoul** [comment]
Subsumed by #2210
