### ISSUE TITLE
placing points_along a line segment: something like points_at, points_on

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2098]
Hi, 

I was wondering if it is possible to have an operator that places a point along a line given its location in terms of percentage of distance from a starting point of the line. For example, If I say points_along( lineID_34, list(0.3, 0.68)) : this will place a point at 30% length and another at 68% length of line 34. This list can be n number of points. 

I would like to request such an operator `points_along`. This is useful for various transportation planning aspects and is generally referred to as `linear referencing ` 

Or is it already possible in GAMA ?

Thanks.

**Comment by ptaillandier** [comment]
Done. here a simple example model:

model TestPointsAlong

global {
	geometry line;
	list<point> points;
	init {
		line <- line([{10,10},{80,80}]);
		points <- line points_along ([0.3, 0.5, 0.9]);
	}
}

experiment TestPointsAlong type: gui {
	output {
		display view {
			graphics "line" {draw line color: #black;}
			graphics "points" {
				loop pt over: points {
					draw circle(1) color: #red border:#black at: pt;
				}
			}
		}

**Comment by sriramab** [comment]
Thank you Patrick. So If I have a roads species from a graph coming from a shapefile. Can I say:

road_agent_10 points_along ([0.3, 0.5, 0.9])
or
road_agent_10.shape points_along ([0.3, 0.5, 0.9])

I would basically have a csv

roadID, rate1, rate2, rate3

this roadID matches with the agentID. What you suggest seems good to me. But reading from csv helps. So was wondering if I could do one of these:

road_agent_10 points_along ([0.3, 0.5, 0.9])
or
road_agent_10.shape points_along ([0.3, 0.5, 0.9])

what do you suggest?

**Comment by ptaillandier** [comment]
Hi,

road_agent_10 points_along ([0.3, 0.5, 0.9])
or
road_agent_10.shape points_along ([0.3, 0.5, 0.9])
Both should work, the first solution is better as you have less to write :)
.




2017-01-17 12:13 GMT+01:00 Srirāma Bhamidipati <notifications@github.com>:

**Comment by sriramab** [comment]
Thank you Patrick.
