### ISSUE TITLE
CSV export of charts is broken

### ISSUE THREAD

**Issue by nordie69** [gama-platform/gama#2099]
### Steps to reproduce
1. Run a simulation with one or more charts
2. Toggle layer controls (on the left side)
3. Open the menue for the chart
4. Hit the "SAVE" button

### Expected behavior
The chart should have been exported in the subdirectory "charts.

### Actual behavior
There is no export of the chart. If there is no directory, the directory "charts" will (!) be created, but there are no charts.

### System and version 
Latest GIT version from 17.01.2017, Windos 8.1, JAVA JRE 1.8.121

**Comment by AlexisDrogoul** [comment]
Hi,

I've just tried it in 2 models of the library, and it works without a flaw. Can you tell me on which models it failed for you ? Either it is a bug specific to these models, or it is a problem of refresh of the resources / write access to the "charts" folder.

Cheers
Alexis

**Comment by AlexisDrogoul** [comment]
Closing this issue as more tests reveal that it is indeed working. If you happen to have more details (on the model, the charts, etc.), please reopen.
