### ISSUE TITLE
keystone on windows

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2105]
I know that many enhancements have been done in the "old" opengl. however as far as I remember (but actually I am not really sure) , keystone use (whic relies on the shader implementation) to work on windows (at east windows 10). I just retry it this morning with the last release and it seems that it doesn't work anymore.

Can someone try it on windows 10 ?

To do so just add that kind of display:

display cityMatrixViewKeystone   type:opengl use_shader:true keystone:true

and then press K (when the mouse is focused) to keystone the scene

Thanks

**Comment by agrignard** [comment]
I insist on this one, especially because it used to work few commit ago and I have many demos that rely on that so I am very block by this.

Maybe just a problem of keyboard listener on windows? I mean the problem is that the "K" key doesn't have any effect maybe it's not a "opengl" problem

**Comment by AlexisDrogoul** [comment]
Maybe. It works like a charm on my computer.

**Comment by agrignard** [comment]
yep me too it works like a charm on my mac (I am actually thinking about buying a mac mini for the demo room...) BUT it was working few days ago (before a HUGE commit ;-) ) , do we have any idea where it can come from? I mean what has changed in the shader part? no too much right?

**Comment by AlexisDrogoul** [comment]
keystone has now been implemented on the fixed pipeline. Please test it again without the "shaders" keyword (although the new implementation also uses shaders, as keystoning is a non-affine transform.

**Comment by agrignard** [comment]
I think we can close this issue. If at some point we need to use the keystoning with shaders we can always reopen it
