### ISSUE TITLE
Grid inside a bigger Continuous world

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2106]
### Steps to reproduce
I am surprised (I actually thought it was doable and already said so to some people, but finally it's not...)

I just want to put a grid inside a bigger world in order to be able to instantiate a gama model from the  following settings:

<img width="726" alt="screen shot 2017-01-31 at 15 03 14" src="https://cloud.githubusercontent.com/assets/3928502/22482418/e7e3afd4-e7c6-11e6-9a5f-c7169d05b8eb.png">

### Expected behavior
Not possible. The grid is by default defining the size of the world.

### Actual behavior
 One way is to build a fake grid with lots of "useless" cell but that's not very efficient. I think in term of multi-level modelling it makes sense to have a micro level represented as grid and a macro using a continuous environment (vice and versa)

**Comment by agrignard** [comment]
By using a bigger grid it works in that case. But if you have a very small grid compare to your world it might to greedy to create the whole grid. 
<img width="868" alt="screen shot 2017-01-31 at 15 17 16" src="https://cloud.githubusercontent.com/assets/3928502/22482793/7f911294-e7c8-11e6-80bb-b9ccd695f42f.png">

**Comment by AlexisDrogoul** [comment]
If you only need to have a few cells, why dont you define and use a regular species where the instances are cells ? As a matter of fact, grids are more an optimisation than anything else.

**Comment by agrignard** [comment]
well it's just that I have different people using this "tangible grid" and i have push a lot to use the grid species to deal with that. and actually the syntax using a grid is very easy to understand.

Right now my "hack" is working because the world is small. Just in term of modularity is it something doable to have a grid inside the world or is it too much refactoring?

**Comment by AlexisDrogoul** [comment]
I close this issue as you can (with a simple syntax) take any geometry, invoke one of the `as_grid` operators on it in order to obtain the cells, and invoke `create ... from:` this list of geometries to create your agents. Something like : `create cells from: the_geometry as_grid {10,10};` would do the trick (and you have different flavours of triangulation, squarization, etc. at your disposal as well)
