### ISSUE TITLE
Welcome page issue

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2108]
### Steps to reproduce
1. A bit hard to reproduce and explain (see gif)

2.Sometime when I click on a model tab instead of showing me the actual model editor it goes straight to the welcome.html page

![untitled](https://cloud.githubusercontent.com/assets/3928502/22554731/33ed6564-e92f-11e6-8633-165a80fb821f.gif)

**Comment by AlexisDrogoul** [comment]
I've tried, but no way to reproduce it. Please also indicate OS, version, etc.

**Comment by sriramab** [comment]
Well. I think this partly can be related to #1960 

When I run a experiment and the start a simulation, then stop the simulation ; it does not return to the model from where I ran the experiment. It returns mostly to the first tab or sometimes to previous tab 

I many a times typed into the wrong model only to realize with the error saying object not found, then I notice I am on the wrong model tab. 

Not so difficult to reproduce, happens quite often

I only use standalone versions on Mac and I can confirm it happened few days back when I reported the arc not displayed issue.

**Comment by agrignard** [comment]
I confirm it happens to me a lot also (switching between multiple tabs doesn't always shoes the good one  not only with the welcome page) but it's hard to reproduce.

Mac OS X 10.11.6

**Comment by AlexisDrogoul** [comment]
I finally succeeded in reproducing and isolating this bug. I havent been however able to determine its cause (seems to happen in the macOS implementation of SWT only, so probably there is a bug there). A fix, which forces back the selection to the correct tab (unfortunately with a not so elegant visual glitch) is on its way.
