### ISSUE TITLE
Include GDAL (> v. 2.1.0) for import and manipulation

### ISSUE THREAD

**Issue by BenBo2017** [gama-platform/gama#2109]
### Enhancement
- Enhancement: Include GDAL for import of various raster formats (like KEA)

### Wished behavior
- Bundeling the needed GDAL Java bindings in order to allow plugins that could ameliorate the use of raster data in GAMA.

### Done so far
- Tried to build GDAL with Java bindings on a Win 64 machine (without real success). Compiling GDAL is not that easy. (Target x64 is not compatible with machine x86 although running Windows on  64Bit processor with a 64Bit Windows)

**Comment by BenBo2017** [comment]
- [ ] Building java binaries for windows, mac and linux of JAVA with GDAL 

- [ ] Including GDAL JAR file in GAMA

**Comment by AlexisDrogoul** [comment]
As far as I know, GDAL is included with the latest GeoTools (at least the bindings, maybe not the binaries themselves)

**Comment by AlexisDrogoul** [comment]
Now tracked under #1362.
