### ISSUE TITLE
keystone side effect

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2113]
### Steps to reproduce
1. use keystone:true

2. zoom in or zoom out 

3. press k

### Expected behavior
having the for keystone point in every corner 

### Actual behavior
I am not sure to understand what happens but I think the zoom is not taken in account at some point. Why not but at least we should be able to reput the initial view when double clicking which is not the case

**Comment by AlexisDrogoul** [comment]
I have issued a "fix" where the view is completely reset before keystoning (incl. zoom). However, I think it would make more sense (in the light of #2114) to allow rotating, translating, zooming and transforming the display while setting up the keystone corners. This (in my opinion) would fix this issue as well as #2114 (by allowing to "move" and "scale" the display).

**Comment by AlexisDrogoul** [comment]
I may have not completely understood the requirements here, so I close the issue. Please reopen if I missed something.
