### ISSUE TITLE
keystone enhancement

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2114]
I am now trying the new keystone in real condition (A projector that displays the scene on a physical surface).

The current enhancements are great however three other things would help a lot to keystone a scene. I kind of agree that it can be done manually playing with the value of the for point but if we can enhance the user experience that's even better.

I don't know how difficult but maybe it's the good time to do it while "the iron is still hot" 

I have 3 requests.

- Now the 4 corners are set on the window corner is it doable  to set it the world corner or
<img width="914" alt="screen shot 2017-02-20 at 18 10 54" src="https://cloud.githubusercontent.com/assets/3928502/23144820/4824abd8-f798-11e6-87cc-15694e5ea13c.png">
or on any shape see attached file 

- Be able to drag and drop the current keystoned window (very useful to adjust the keystoning)

- Being able to defined several keystoning in one scene. This might be a bit more complicated to handle.

**Comment by agrignard** [comment]
Just trying to illustrate why a keystone at least on the world corner would be great.

- Most of the time the display window corner are outside of your physical table so they might be hard (and sometime impossible) to locate in order to click on it. See this case 
![img_5913](https://cloud.githubusercontent.com/assets/3928502/23145404/daaa4aaa-f79b-11e6-897f-9e3c38a92cbd.JPG)

- Also if you have the display window corner it makes it harder if you want to enlarge your initial world because the point need to be dragged outside of the projection.
![img_5914](https://cloud.githubusercontent.com/assets/3928502/23145434/0e727e98-f79c-11e6-9b9c-10907c0643c1.JPG)

I try to thing in every configuration but I think it makes sense to put by default the corner on the wolrd shape instead of on the display window (if it's doable).

**Comment by agrignard** [comment]
@AlexisDrogoul I can have a look at this if you point me where you handle the transformation

**Comment by agrignard** [comment]
just to illustrate In this picture this is how the keystoning (2 distinct one) works in order to map the physical table in the previous picture
<img width="1907" alt="screen shot 2017-02-21 at 15 26 32" src="https://cloud.githubusercontent.com/assets/3928502/23183518/574d43c4-f84a-11e6-834d-cc52cf95de89.png">

**Comment by AlexisDrogoul** [comment]
Having both at the same time would be complicated (i.e. if the deformations are not linked, it means having two render-to-textures processes) to say the least. However, it is possible to include a switch to choose between "keystoning from view corners" and "keystoning from world corners", whichever is the most suitable.

**Comment by agrignard** [comment]
Let's keep the 2 keystoning for enhancement
Yep this switch would be great. Then I think we are definitely ready to display properly GAMA simulation on a physical interactive table. Do you think you can commit this switch soon?

**Comment by AlexisDrogoul** [comment]
Actually, I'm not completely sure to have understood your requirements. Should the two deformations (from the world corners / display corners) be linked or independent ?

**Comment by agrignard** [comment]
For a first step let's focus on one keystone at a time. Personally I would prefer to have the corner on the world corner (much more easy to keystone as shown in the previous picture) but maybe some other people (if there is no other let's not do it) would prefer to have it form the view corners. So I would say if we can set it in the preferences or by a facet that would be perfect.

For multiple keystone we'll see later.

**Comment by AlexisDrogoul** [comment]
I've taken some time to implement something. Basically, the goal is to simplify as much as possible the interaction of the user with the screen and to have it as uncluttered as possible. 
So the "new" keystone works this way:

1) Pressing "K" lets the user enter the definition mode. Pressing "K" again it leaves it.
2) The screen is presented with the four corners and the four coordinates (as usual), with a bit of transparency in case.
3) Depending on the quadrant of the screen the mouse is in, one of the keystones is indicated as "hovered"
4) Pressing the mouse button selects this point (it turns to orange to show it).
5) From this moment, moving the mouse will apply a similar translation to this point.
6) Clicking again (anywhere) will release the point.
7) Whenever one of the points is dragged outside the screen, they are automatically placed inside the corners of the world (so the values remain visible). When they are all inside, the normal placement (display) is chosen. 

So it means keystoning can be defined by dragging from anywhere in a quadrant, which is in my opinion much easier than choosing a shape, the world, or the display as anchor points. I will commit soon and close this issue. Reopen if it doesnt work, but I won't probably spend more time on this !

**Comment by agrignard** [comment]
Ok I am looking forward to test it (indeed a dynamic/mouseable way to define the corner instead of hard code it is a good idea)

**Comment by agrignard** [comment]
PERFECT!!!!!!
