### ISSUE TITLE
Laggy zoom with "complex" shape with native tesselator to false

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2116]
### Steps to reproduce
1.I have a quiet simple model very similar to road traffic but using other GIS file (that might be the issue).

However it was working not so bad before (see release version in the gif) but I am now experiencing some lagging in the zoom with the current version

You can check the 2 different zoom speed first in a previous release version and secondly in the current git version

![untitled](https://cloud.githubusercontent.com/assets/3928502/23239419/1e1bb068-f935-11e6-876e-c511bc723bd5.gif)

### Expected behavior
The zoom is slow

### Actual behavior
Normal zoom

### System and version 
Current version

**Comment by agrignard** [comment]
Just a side note the GIS is not the cleanest one but it just to track the difference between both version

**Comment by AlexisDrogoul** [comment]
Do you have the GIS file and can you share it ? Geometries are now triangulated much more accurately and this might be the cause -- if you have complex ones, or ones with holes.

**Comment by agrignard** [comment]
[CityScope_Kendall.zip](https://github.com/gama-platform/gama/files/796611/CityScope_Kendall.zip)

 Almost the same model as road traffic but indeed the GIS file are "dirty". I am working on finding other GIS so it's not an emergency for me but more a way to track the difference between the 2 versions of GAMA. 

Actually in some release (I have different release version) the rendering is very strange with some Z value on some other there is no problem at all. So I guess the GIS has lots of Z strange values that might impact on the triangulation. Maybe (I don't know if it's generic enough) we can by default flatten (remove any Z composant) any GIS file?

**Comment by AlexisDrogoul** [comment]
Strange enough. I dont get any stuttering. It's even quite smooth, with or without running the simulation.  I've taken a quick and dirty video (the lags are mine on it !).

![2017-02-23 21_47_07](https://cloud.githubusercontent.com/assets/579256/23263725/b480effa-fa11-11e6-8c08-c437ce1e9d76.gif)

**Comment by agrignard** [comment]
also fix with native tesselator

**Comment by ptaillandier** [comment]
On my computer (windwos 7 laptop i7 (2016) with a "slow" Intel HD 520 GPU),
it is also bit laggy with the current version of GAMA (but less than on
Arnaud's computer).

Cheers,

Patrick

2017-02-23 15:48 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
I think people with Intel HD GPUs should not be able to post comments on OpenGL performances :)

Given the result on complex geometries, the default value should be to use the native tesselator, i.e. true. I checked and it is false by default (for "new" preferences), probably because I wanted to keep the better precision of JTS. I will commit the change soon.

**Comment by ptaillandier** [comment]
Just as a confirmation, it works well with the native tesselator (even with a Intel HD GPU).
