### ISSUE TITLE
Problem with rotation on some built-in shapes 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2118]
### Steps to reproduce
1. Run 3D Visualization/models/Built-In Shapes 

2.

3.

### Expected behavior
When the simulation is running all the shape are supposed to run

### Actual behavior
Problem with circle, hexagon and square - square

![untitled](https://cloud.githubusercontent.com/assets/3928502/23263296/cdbb2b9a-f9ab-11e6-9dac-4e6fc7315ec7.gif)

### System and version 
Current Git

**Comment by AlexisDrogoul** [comment]
Can I see your preferences in OpenGL ?? Here is what I obtain:

![3d shapes - users drogoul documents git gama msi gama models models features 3d visualization models built-in shapes gaml 2017-02-23 21-52-38](https://cloud.githubusercontent.com/assets/579256/23264074/c126b496-fa12-11e6-84b3-ee62e7079048.png)

**Comment by agrignard** [comment]
alright this come from native tesselator (it was false for me ) what is the default value?

**Comment by AlexisDrogoul** [comment]
Well. maybe I will remove this option altogether. Too bad, as JTS tesselator is quite superior for complex geometries (but seems to be a real crap for "simple" ones, strange enough...)
