### ISSUE TITLE
Incorporating external plugins

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2120]
Still keeping my passion for GAMA in these many years, I keep downloading new versions of GAMA standalone to get advanced features and corrections  ( and also because I am tired and given up on installing GIT version as a non computer scientist ) 

Then, I often have to install easy shell and TM terminal. Both are extremely useful and I think also stable. Is it not possible that GAMA can already pre-plugin them? Like it happened with editbox, the one that colours blocks of code. Or at least have some menu that says, install plugins and then these couple of extensions and their url to update sites are already listed... and I can just select them to install? This would really be very convenient. 

I would request this at least for those that GAMA already recommends as good extensions like here https://github.com/gama-platform/gama/wiki/InstallingPlugins 

I really like that Terminal TM gets into your recommended list as it makes it so easy to use R, python, pandoc, git all without leaving GAMA. I think Terminal TM comes from Eclipse themselves. 

I hope you will consider this request :)

**Comment by AlexisDrogoul** [comment]
Well. In the "Help>Install new software..." command, we can list other adresses (only Gama updates are listed there -- and they are still not functional as far as I know). So if you provide a list of plugins and their respective update/download sites, I can incorporate them in the default list that ships with the binary.

**Comment by sriramab** [comment]
Thank you Alexis. That would a great time saver

Easy Shell is listed on https://marketplace.eclipse.org/content/easyshell
update site http://anb0s.github.io/EasyShell


Terminal TM is listed on https://marketplace.eclipse.org/content/tm-terminal
update site http://download.eclipse.org/tm/terminal/marketplace
