### ISSUE TITLE
trace:true z increase

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2122]
### Steps to reproduce
1. use trace:true on any layer

2.

3.

### Expected behavior
usual Trace behavior

### Actual behavior
Something really strange happen: the agent are drawn with a kind of increasing z value...

<img width="798" alt="screen shot 2017-02-24 at 14 12 20" src="https://cloud.githubusercontent.com/assets/3928502/23317245/95687d60-fa9b-11e6-9ee0-0f11efdc3aa9.png">

**Comment by AlexisDrogoul** [comment]
Please post a very simple model that exhibits it.

**Comment by agrignard** [comment]
you can try on many different model.

As an example this is the behavior if you put trace:true for people on 3D Visualization/building Elevation the road are increasing in z (not the people which is very weird..)
<img width="900" alt="screen shot 2017-02-25 at 11 27 20" src="https://cloud.githubusercontent.com/assets/3928502/23332789/907d4b02-fb4d-11e6-895e-0bc5bbbf824a.png">

**Comment by AlexisDrogoul** [comment]
Think I fixed it. However, I will probably deprecate soon the 'trace: true' facet as it is completely unbounded and basically leads to a crash at some point. Or we can decide on a default (or pref) value for this case.

**Comment by AlexisDrogoul** [comment]
Closing the issue as the fix seems to work. Reopen in case of problem.
