### ISSUE TITLE
arc does not display anything

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2123]
### Steps to reproduce
1. If you use the arc operator if does not create/draw any arc

2. sometimes arcs are not visible if you have very small radius, so try using a large radius or use it inside a loop to make it visible, as here https://code.google.com/archive/p/gama-platform/issues/1183

### Expected behavior
I expect to see arcs drawn as in this [pic](https://17188364295374204847.googlegroups.com/attach/4d529ef7afc690fe/CaptureHeadlight.JPG?part=0.1&view=1&vt=ANaJVrHUsx3vKj4sSERt8GQROfoklx1rLGVmiTDSiKEtNcorhj-9_0kjhLR65wjMudhq0cVuyPJqTpeY3yL2kG32jbHAx4elxgDLu_vZLFS0No1bfTgk_Cg) 

### Actual behavior
No arcs are drawn

### System and version 
Standalone GAMA 1.7 mac version 24Feb2017

**Comment by AlexisDrogoul** [comment]
OpenGL ? Java2D ?

**Comment by sriramab** [comment]
I tried in OpenGL. Please try with just some circles as agent display draw
statement. then another draw statement with arcs to create a small example
as shown in the issue attachment.
Thank you.

**Comment by AlexisDrogoul** [comment]
Fixed. There was an internal problem in the GeometryFactory used. Arcs (and ellipses, etc.) are now drawn, and you can even combine it with the line/polyline feature of #2124 to produce nice things like that:

![tata - volumes media ws4 toto models new gaml 2017-02-27 23-33-47](https://cloud.githubusercontent.com/assets/579256/23369941/9326f4da-fd45-11e6-8f13-5441caa25c07.png)

(code : 

```
	aspect default
	{
		draw circle(1) empty: false color: color;
		loop i from: 1 to: 9
		{
			geometry g <- arc(i, heading, 60, false);
			draw polyline(g.points, 0.2) color: # blue;
		}

	}
```
