### ISSUE TITLE
Enhance the anti-aliasing when drawing line in opengl

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2127]
It's a problem here since the beginning of opengl rendering in GAMA. 

The rendering of thin line is a very law quality one in opengl. I guess we need to play with some anti-alisaing parameters to fix that it should'nt be too hard.

Here is for instance the same model rendered in java2D and opengl you can see that the line in opengl looks very "dashed".

<img width="1208" alt="screen shot 2017-02-26 at 18 55 46" src="https://cloud.githubusercontent.com/assets/3928502/23345048/74217e5c-fc55-11e6-9221-f4c24e22c565.png">
<img width="1290" alt="screen shot 2017-02-26 at 18 53 47" src="https://cloud.githubusercontent.com/assets/3928502/23345049/74248ad4-fc55-11e6-82de-59e28abf96d3.png">

**Comment by agrignard** [comment]
I tried that kind of stuff in the init of the joglrenderer but it doesn't change anything, it's even worth!
 
gl.glEnable(GL.GL_LINE_SMOOTH);
gl.glHint(GL.GL_LINE_SMOOTH_HINT, GL.GL_NICEST);
gl.glEnable(GL2.GL_NORMALIZE);

currently we have this gl.glDisable(GL.GL_LINE_SMOOTH);

**Comment by AlexisDrogoul** [comment]
No. It doesnt change anything (and it is even worse -- and not worth ! --) on some graphics cards, which is why GL_LINE_SMOOTH is disabled and should stay that way. Further, the performance hit can be quite important. And GL_NORMALIZE has nothing to do with lines (it should be enabled all time, by the way).

**Comment by AlexisDrogoul** [comment]
OK. I think I've found the solution (at least one). If you can share with me this precise file (which is interesting because it has lots of different lines), I will test it.

**Comment by agrignard** [comment]
[CityScope_Kendall_GAMA.zip](https://github.com/gama-platform/gama/files/819566/CityScope_Kendall_GAMA.zip)

**Comment by AlexisDrogoul** [comment]
Can you check if the recent commit has improved things or not ? I notice some improvement (but I dont project the displays, so it's quite subjective).

**Comment by agrignard** [comment]
Mmm sorry but I don't see the difference. to me it seems that there is still aliasing on the opengl rendering (see the 2 different snapshot made with opengl and java2D on a retina display)

![cityscope_kendall_model_display_cityscope_size_1865x1014_cycle_0_time_1490604749820](https://cloud.githubusercontent.com/assets/3928502/24348426/f8d4790a-12db-11e7-8efa-15be4e4ea0b0.png)
![cityscope_kendall_model_display_cityscope_size_1865x1014_cycle_0_time_1490604728813](https://cloud.githubusercontent.com/assets/3928502/24348425/f8d3d5ae-12db-11e7-920a-08f5038ec146.png)

**Comment by AlexisDrogoul** [comment]
Subsumed by #2209
