### ISSUE TITLE
Distributed simulation platform 

### ISSUE THREAD

**Issue by danceqq** [gama-platform/gama#2128]
# Steps to reproduce
1. To address the issues of resource availability, limited simulation scale, etc., in simulation system, an distributed simulation platform  is proposed. who can tell me whether Gama implements  distributed simulation？？
#  Expected behavior
 I have a large simulation ,but only a computer can't solve  effective,I expect the GAMA  can design distributed simulation platform
#  Actual behavior
I want to know the FIPA whether implement distributed simulation platform.
# System and version
GAMA Platform - V1.7.0

**Comment by AlexisDrogoul** [comment]
Hi, sorry to repeat myself, but what you write is a QUESTION and not an ISSUE. Can you please use the mailing list ? Thanks.
