### ISSUE TITLE
Problem with distance calcul between two agents

### ISSUE THREAD

**Issue by ILHEM88** [gama-platform/gama#2129]
I’m trying to write an example permitting to calculate for  each agent the distance to it nearest neighbor  and also updating the agents location (randomly). However I had noticed that  the distance between two closest agents is not the same when calculated in both ways (from agentA to agentB and vice versa). And when I set the agents locations the calculs become correct.

### Expected behavior
The distance between two agents at the same time in both directions should be the same. 

### System and version 
I use GAMA version 1.7 and Java version 8. 

[example.docx](https://github.com/gama-platform/gama/files/804391/example.docx)

**Comment by ptaillandier** [comment]
Hi,

I had a look at your model and there are two explanations to your problems:

   - by default, the normal scheduling of GAMA consists in activation one
   per one each of the agents: in your model each agent is then computing the
   closest agents, then moving.... so when the next one is activated, the
   distance to the previous agent can be different
   - it seems normal that the closest relation is not always reversible:
   the closest agent to agent A can be agent B, and the closest agent to B can
   be C and not A.

Cheers,


Patrick

2017-02-27 18:13 GMT+01:00 ILHEM88 <notifications@github.com>:

**Comment by ILHEM88** [comment]
Thank you very much for your reply. I wonder if there is a solution for this problem?

**Comment by ptaillandier** [comment]
No solution because there is no problem :) . I mean the results that you
obtain are perfectly normal.

2017-02-27 19:43 GMT+01:00 ILHEM88 <notifications@github.com>:

**Comment by ILHEM88** [comment]
Actually I want to update all the agents locations at the same time after calculating the distances non agent by agent and I don't know how to do it.
