### ISSUE TITLE
Invalidpath Exception at plugin load in Headless mode

### ISSUE THREAD

**Issue by chapinux** [gama-platform/gama#2130]
s### Steps to reproduce
1. launch headless mode in windows 7

2. remove every space from path and model name (in this case Predator Prey , and Model 04.gaml

3. replace the model directory of the experimentFile.xml of the headless mode documentation page  with the actual directory (something like  
<Simulation id="2" sourcePath="plugins\msi.gama.models_1.7.0.201702280323\models\Tutorials

\Predator_Prey\models\Model04.gaml" finalStep="1000" experiment="prey_predator">
)

change the parameter names and output names

3. launch with the experiment file (not the sample)

### Expected behavior
No error 
### Actual behavior
******************************************************************
* GAMA version 1.7.0                                             *
* http://gama-platform.googlecode.com                            *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC and Partners            *
******************************************************************
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/C:/Users/GIGABYTE/Desktop/gamaTest/plugins/simtools.gaml.extensions.traffic_1.7.0.201702280323.jar!/models/
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at msi.gaml.compilation.kernel.GamaBundleLoader.hasModels(GamaBundleLoader.java:165)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:81)
	at msi.gama.common.Activator.lambda$0(Activator.java:26)
	at java.lang.Thread.run(Unknown Source)
>GAMA plugin loaded in 421 ms: 	msi.gama.core
>GAMA plugin loaded in 0 ms: 	ummisco.gama.network
>GAMA plugin loaded in 16 ms: 	simtools.gaml.extensions.traffic
>GAMA plugin loaded in 15 ms: 	simtools.gaml.extensions.physics
>GAMA plugin loaded in 0 ms: 	irit.gaml.extensions.test
>GAMA plugin loaded in 0 ms: 	ummisco.gaml.extensions.maths
>GAMA plugin loaded in 16 ms: 	msi.gaml.extensions.fipa
>GAMA plugin loaded in 0 ms: 	ummisco.gama.serialize
>GAMA plugin loaded in 15 ms: 	irit.gaml.extensions.database
>GAMA plugin loaded in 0 ms: 	msi.gama.lang.gaml
>GAMA plugin loaded in 0 ms: 	ummisco.gama.java2d
>GAMA plugin loaded in 141 ms: 	msi.gaml.architecture.simplebdi
>GAMA plugin loaded in 0 ms: 	ummisco.gama.opengl
>GAMA total load time 671 ms.
>GAMA building GAML artefacts in 234 ms
cpus :8
Simulation is running...
....................................................................................................
Simulation duration: 8364ms

### System and version 

windows 7  Family SP1
GAMA 1.7 release GAMA1.7_Win_64_02.28.17_a8e752c
java oracle 64bits 1.8.0_121

**Comment by AlexisDrogoul** [comment]
Seems to be linked to this specific portion of code (which I havent written and which I dont really understand) in `GamaBundleLoader.hasModels()`:

```
		try {
			final URL new_url = FileLocator.resolve(url);
			final String path_s = new_url.getPath().replaceFirst("^/(.:/)", "$1");
			final java.nio.file.Path normalizedPath = Paths.get(path_s).normalize();
			file = normalizedPath.toFile();
		} catch (final Exception e) {
			e.printStackTrace();
		}
```

This code is not only useless (as the url is already located above) but it is also harmful, as it prevents plugins with models bundled in a .jar to be located (the method later returns false if the file is null).

I will comment it and commit the changes. If anyone @gama-platform/core recognizes his contribution, please acknowledge it (and explain it !).
