### ISSUE TITLE
pause / halt / die

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2132]
### Steps to reproduce
1. In order to stop a simulation in GAMA (GUI), it is either possible to use do pause, do halt or do die to the global.

2. The use of "do halt;" or "do die;" on global, does not seem to work anymore.
See the model : 
global {
	init {
		create toto number: 2;
	}
	
	reflex t when : cycle > 10000 {
		write "stop";
		//	do halt;	
		do die;
	}

	reflex f {
		write cycle;
	}
}

species toto { }
experiment testHalt type: gui {output {}}

### Expected behavior
I was expecting that do halt or do die; stop the simulation and stop the GUI .

### Actual behavior
When reaching the do halt or do die, the simulation seems to stop working (in the previous model, the number of the step is not displayed anymore), but the cycle count on the top left of the GUI continues to run (and much more faster).

### System and version 
GAMA Git MACOsX

**Comment by AlexisDrogoul** [comment]
This is normal: the simulation dies (or halts) but not the experiment. So the "global" counter only lists the experiment's steps (you can verify it by hovering on it -> it shouldn't show any simulation anymore). If you want to kill (or stop) the experiment, `do halt` or `do die` should be issued within it. Or you can use `ask experiment {do die;}` from within the simulation.
