### ISSUE TITLE
Different ways of displaying agents (in console) when single or in a list

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2133]
### Steps to reproduce
1. When we "write" agents in the console, if we write the agent itself, its name will appear, but if we write it in a list of agent, it will be displayed with its species and id.

2. In the following model:

```
global {
	init {
		create toto number: 2;
		
		write "" + list(toto);
		write toto(1);
	}
}

species toto {
	string name <- ""+rnd(10000);
}
experiment testHalt type: gui {output {}}
```

### Expected behavior
The expected result would be to have a homogeneous way of displaying agents.

### Actual behavior
In the console appear:

[toto(0),toto(1)]
2752

### System and version 
GAMA Git, MacOSx

**Comment by AlexisDrogoul** [comment]
I have chosen to harmonise both by outputting species(index) in both cases. If the modeler wants to output the names, he/she can use agent.name in that case.
