### ISSUE TITLE
Headless: number of cpu facet does not work

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2138]
### Steps to reproduce
1. When running a model in headless, the -hpc attribute can be used to specify the number of core.

### Actual behavior
When using -hpc 1 in the command line, the headless mode is ran with 8 cpu.

### System and version 
GAMA Git MacOsX

**Comment by AlexisDrogoul** [comment]
I've checked the code and it *should* work, although the log is misleading as it reports something like `cpus: nn`, but this is actually the number of *available* cpus, not the number of cpus *used*.  I have changed this mention by a more explicit one.
