### ISSUE TITLE
Models for BDI and Driving Skills extensions are not in the RC1

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2140]
### Steps to reproduce
1. Open the Plugin Models and look for the BDI and Driving Skill models.

### Expected behavior
I can find them :-)

### Actual behavior
I cannot find them.

Note: in the plugins.xml of the simpleBDI plugins, in Build pane, models folder is not ticked but in extensions pane there is the model extension.
In contrarily, in the fipa extension plugins, models folder is ticked but in the extension there is not the models extension....

### System and version 
GAMA MacOSX, RC1

**Comment by AlexisDrogoul** [comment]
Well.. If the "models" folder is not part of the build, they have not been added, I guess !
