### ISSUE TITLE
Problem with copy facets Camera

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2142]
### Steps to reproduce
1. Run any model like (road traffic for instance), find a specific angle and then save the camera parameters thnaks to the copy facets.

2. Past those facets in gaml

3. the position of the camera is not the one expected.

### Expected behavior
We should have the same position when copying a facet and rerunning a simulation

### Actual behavior
The camera is strangly placed?

### System and version 
GAMA RC1

**Comment by AlexisDrogoul** [comment]
Could you update this bug report with an example of what is wrong (i.e. is the copy itself false, or is fixing the camera at the beginning with the copied values wrong) ?

**Comment by agrignard** [comment]
if you copy and paste the value of the camera at a position A the camera is not "placed" at the same location (close to A but not exactly)

**Comment by AlexisDrogoul** [comment]
I've tried several times to reproduce it and I can't (but I've tried with simple camera settings). What do you exactly observe ? Are the values in the left panel different from what is entered in the facets ? Is it visually different ? More information would be welcome !

**Comment by agrignard** [comment]
Mmmm I cannot reproduce it so let's say this is fix (the copied value are now the right one)

**Comment by agrignard** [comment]
Yep just to confirm that the copy facet camera does not work on RC1 but work on the current version. I think that's an important feature to be sure to have in the final release
