### ISSUE TITLE
Console vs Interactive Console

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2143]
Just a suggestion as we are in the final detailed of the release. Now the interactive console is the one of top of the classical console. Personally when I debug my model with some write the information is in the original console you need one click to change from console.

I am just thinking that by default (or maybe a preferences) user are more used to use classical console no?

GAMA RC1

**Comment by sriramab** [comment]
Yes . This is something I also requested sometime ago. Console should be default :) thank you
