### ISSUE TITLE
blocking at start-up

### ISSUE THREAD

**Issue by FTaillandier** [gama-platform/gama#2145]
### Steps to reproduce
1. Open GAMA

2.

3.

### Expected behavior
GAMA starts normally

### Actual behavior
GAMA stops at 'Loading ummisco.gama.ui.shared.... but not always, but often.

### System and version 
GAM 1.7 RC
OSX El Capitan (10.11.5)

**Comment by AlexisDrogoul** [comment]
I need a bit more information: does it happen from a new workspace or an existing one ? What is the memory provided to GAMA ?

**Comment by sriramab** [comment]
For me this has always been the case since a year. I just force quit and open again. Second time open always works as much as first time doesn't work. Alexis could not reproduce also then (in Vietnam) and we concluded it perhaps is an HDD issue as nobody on SSD experienced this behavior.  I stand corrected.

I am on mac mavericks , java 8, version of 14march2017 still has this issue

**Comment by benoitgaudou** [comment]
I have also experienced this bug, even with my SSD. I allocate in general 8
Go of memory for GAMA.
I was not able yet to find a pattern (new workspace or old one, created or
not by another version of GAMA ...)

2017-03-15 6:26 GMT+01:00 Srirāma Bhamidipāti <notifications@github.com>:

**Comment by ptaillandier** [comment]
Hi,

With my old macbook (early 2011, without SSD and with El Capitan), I had
also this bug. Note that until now, I never had this bug with my windows 7
and Ubuntu computers.

Patrick

2017-03-15 7:58 GMT+01:00 benoitgaudou <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
It seems that this problem happens only on macOS. Are there any report of it happening on other systems ? @gama-platform/committers

**Comment by hqnghi88** [comment]
I have experienced 2 or 3 times, by chance , a blocking start-up on windows 10, but i fixed it with the administration launch of eclipse. And i can't reproduce it with current git version

**Comment by nordie69** [comment]
I am using Windows 8.1 and Java 1.8 and I have not had any problems with it.

**Comment by AlexisDrogoul** [comment]
After several experiments on freshly installed MacOS X versions, this issue seems definitely linked with the new "sandbox" policy in MacOS X. The workaround is to be found here: https://github.com/gama-platform/gama/wiki/Installation#macos
