### ISSUE TITLE
how to build GAMA from source

### ISSUE THREAD

**Issue by stone99** [gama-platform/gama#2146]
I download source from github , as descripted in https://github.com/gama-platform/gama/wiki/InstallingGitVersion I could run GAMA from eclipse by click on Launch an Eclipse Application. And then i follow the step in https://github.com/gama-platform/gama/wiki/CreatingAReleaseOfGama i cannot get an luanchable version of GAMA.
i want to build GAMA form source and I am not sure how to get it.

**Comment by benoitgaudou** [comment]
Please add the error you have (is it during the production of the release or when you execute it ?)

By the way, I tried to follow the instructions too and I get the following error:

Unable to find feature "org.eclipse.e4.rcp" with version in range [1.4.1.v20160212-1350,1.4.1.v20160212-1350].

On GAMA git, MACOSX

**Comment by AlexisDrogoul** [comment]
This page is clearly obsolete now, as one should use `maven` instead. At the root of the repository, the `build.sh` script is available to build GAMA.

**Comment by AlexisDrogoul** [comment]
I corrected the page <https://github.com/gama-platform/gama/wiki/CreatingAReleaseOfGama> to give some information on how to build GAMA since version 1.7.
