### ISSUE TITLE
Parameters window wrong layout 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2147]
### Steps to reproduce
1.Open any model (tested on Building Elevation)

2.Double click on the tabs with the name of the display (city_display) to be in full window mode (different from fullscreen)

3.try to show the parameters window

### Expected behavior
Having the parameters window

### Actual behavior
The parameter window does not show up correctly (note: it woks well when clicking on restore)

### System and version 
GAMA RC1

**Comment by hqnghi88** [comment]
Hi Arnaud,
It seems to work well on the latest build. "try to show ..." was "click on menu" or ...? In addition, the experiment "road_traffic_flying_off" have no parameter, and i can't show the param view only with that experiment.

**Comment by AlexisDrogoul** [comment]
Sorry -- I dont really understand the problem here. Some snapshots could be useful...

**Comment by AlexisDrogoul** [comment]
I've implemented a workaround (much more practical in my opinion) for these minimised/maximized views. When a view is maximised, activating a minimised one from the tray (small view icons) automatically restores the unmaximised layout. No need to click on restore again, simply clicking on a view will restore everything. If it is a bit too much, I can probably only restore the folder containing this view. Let me know how it works for you.
