### ISSUE TITLE
image in display not refreshed

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2148]
### Steps to reproduce
1. Create a display in an experiment 

2. use image file:somefile.jpg

3. do some simulation such that you save another jpg (snapshot perhaps) with the same name and in same folder

### Expected behavior
new jpg should overwrite old jpg, when using refresh = true

### Actual behavior
old jpg not replaced in display, even after gama restart. 

### System and version 
GAMA RC1, mac os, java 1.8 both java and opengl

**Comment by AlexisDrogoul** [comment]
As far as I know it has never been the case (as images are cached). So it is more an enhancement than a bug...

**Comment by AlexisDrogoul** [comment]
I've committed some changes which should provide this enhancement. Please test before I can close it! Note that, by default, `image` layers now define `refresh:` as `false`. Setting it to `true` allows to retrieve the image continuously (even if it changes).

**Comment by AlexisDrogoul** [comment]
I've made some quick tests and it should be ok. I close it, but please reopen if it doesn't correspond to what you were looking for.
