### ISSUE TITLE
update GAMA stand-alone without new downloads

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2158]
Hi

This is related to #2151  and #2150 

I have noticed that in the last few days, there are many improvements that now enable updating plugins without having to update whole of GAMA. I am very eager to have something similar for GAMA stand-alone itself. I already have more than 10 GAMA installations on my computer as a result of enhancements and corrections important to my work. Sometimes this is just too awkward having so many versions. 

Along the lines of #2151 and #2150, if it is possible to update GAMA stand-alone from within, that would be awesome !! Is something already happening in this direction? 

I know there was some issue stating this exact enhancement but I could not find it. 

Thank you .
Srirama

**Comment by AlexisDrogoul** [comment]
Hi Srirama, you should normally be able to do it right away. Have you tried ? Either "Help>Install new software..." or "Help>Check for updates".

**Comment by sriramab** [comment]
Yes, it does not work. I also did via advanced preferences, set reminder to update at each start of GAMA. I thought it will tell me there is update, because my GAMA is from 21 march 2017 and I can see that github has already version of 27 march 2017. 

please note I am referring only to GAMA stand-alone version.

**Comment by hqnghi88** [comment]
Hi Sriri,
Could you please recheck update now and we'll see?

**Comment by sriramab** [comment]
Do I first need to download latest GAMA? I currently have 21.03.2017 version

**Comment by hqnghi88** [comment]
No, just check update from Help

**Comment by sriramab** [comment]
![screen shot 2017-03-28 at 10 37 13](https://cloud.githubusercontent.com/assets/12668606/24396186/99f13258-13a2-11e7-8360-275903b117b0.png)

I got an update alert ( i did not get yesterday) then Some installation did happen. But when I look at Gama, it still shows 21.03.2017 as you can see in the attached pic.

**Comment by sriramab** [comment]
The update functionality seems to work. It updated something but how do I check if I have the latest version? When I usually download a new GAMA from github, I can see in installation details that it has a date. 

But after following this update, the GAMA date has not changed. So I wonder if update happened or not. If happened, how do I check?

thank you

**Comment by sriramab** [comment]
I do not think GAMA is updated because I still cannot resolve correction #2157 from march 26, 2017

**Comment by AlexisDrogoul** [comment]
Hi,

The information panel about plugins indicates, on your picture, that all plugins have been updated to 28.03.2017 (20170328). Where do you see 21.03.2017 ? 
Alexis

**Comment by sriramab** [comment]
on Gama below easy shell , 7th from top

**Comment by hqnghi88** [comment]
Hi Sriri,
I confirm that it didn't update the ummisco.gama.application.product . So it need more efforts. 
See you later.

**Comment by AlexisDrogoul** [comment]
But isn't it normal that the product is not updated ? What counts are the plugins, right, not the product itself. Or maybe I'm wrong (which means not updating the product will still call the "old" plugins) ?

**Comment by sriramab** [comment]
Yes, this issue #2158 is for the product itself. This request is not to download many GAMA installations on a computer but to have update the product itself from "within" is preferred.

**Comment by hqnghi88** [comment]
Please test one more time

**Comment by sriramab** [comment]
I hope you are not tricking by just changing the date 😄 . It is now 28.03.2017

**Comment by sriramab** [comment]
But the issue of being able to enter negative values in #2158 doesn't still work 
I am curios to hear from Alexis if 2158 was fixed? I am not able to change to negative points

on this code
model worldsetup

global {
	/** Insert the global definitions, variables and actions here */
	point a <-{-0.35,0,0};
}

experiment worldsetup type: gui {
	parameter "change point" var:a;
	/** Insert here the definition of the input and output of the model */
	output {
	}
}

**Comment by hqnghi88** [comment]
No, im not tricking just because my internet is too slow so i ask for your validation before mine finish. 2158 is fixed and it is not updated. More efforts. See you later

**Comment by AlexisDrogoul** [comment]
OK I will try with an old version of GAMA I have somewhere...

**Comment by hqnghi88** [comment]
Last try, Sriri, now.

**Comment by sriramab** [comment]
Wow, excellent !! It is working 🎉  🎈  Thanks a lot.  Wonderful. I can now have only one GAMA. yay !!

**Comment by AlexisDrogoul** [comment]
I confirm it is also working for me. By the way, I added a related note of information for macOS Sierra (and above) on how to obtain an "updatable" GAMA: https://github.com/gama-platform/gama/wiki/Installation#macos (preventing sandboxing and translocation mechanisms to mess up the process). I think we can close this issue. Thanks @hqnghi88 !
