### ISSUE TITLE
Flickering screen when moving mouse with trace on

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2159]
### Steps to reproduce
1. open any model (e.g building elevation)
2. define a trace on any layer (e.g species people aspect: base trace:10;)
3. mouve the mouse (no drag just mouve the mouse)

### Expected behavior
Normal display 

### Actual behavior
Flickering  rendering (light one but still)

### System and version 
GAMA 1.7 RC1

**Comment by AlexisDrogoul** [comment]
I'm unable to reproduce it. What do you mean by "flickering" ? 
Furthermore, is it visible when the simulation is paused ? Is the bottom overlay displayed ? Is the simulation synchronised with the display ?

**Comment by agrignard** [comment]
When the model is running and when the display is not synchronized.

**Comment by agrignard** [comment]
I confirm the facet true and fading have a very bad behavior when the display is not synchronized.

See the following example
 
![flicker](https://cloud.githubusercontent.com/assets/3928502/24655245/7b38b962-190b-11e7-9a53-31585e21476f.gif)

**Comment by AlexisDrogoul** [comment]
Subsumed by #2209
