### ISSUE TITLE
First cycle values not shown when using refresh every(n)

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2161]
### Steps to reproduce:
run a model using refresh every(n) or refresh every(n#cycle)

### Expected behavior
The curve should be plotted every 1 cycles

### Actual behavior

When running the attached model, the value computed at first cycle is not shown on the graph (no marker at time 1 on the curve).
When removing "refresh: every(1#cycle)", it works perfectly fine.

The same happens when replacing 1 by a value n, there is always one cycle missing at the beginning of the curve.

### System and version 
Gama continuous release (update 28/03), Win 7 64

```
model singlebacteria

/* Insert your model definition here */

global{

	list<float> CO2dataValues <- [0,1,2,3,4,5,6,7]	;
	float currentDataValue ;

	
	init{
		
	}
	
	
	reflex computeScore{
		currentDataValue<- CO2dataValues[cycle];	
	}
	
	reflex endSim{
		if (cycle = 7){
			do pause;
		}
	}
}



experiment simulation type: gui {
	output {
		display Soil refresh: every(2#cycle) {
			chart 'Organic Matter (gC/initial gC) of Arthrobacter 3R' type: series background: rgb ( 'lightGray' ) {
		    	data "CO2-data" value:currentDataValue color: #blue; 		
			}	
		}
	}
}
```

**Comment by AlexisDrogoul** [comment]
I've issued a fix for this. Please test.
