### ISSUE TITLE
Some close tab icons disappear

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2166]
### Actual behavior
Some tabs in the model interface don't have the button which allows to close them (the cross icon). The icon never appears, even when the mouse cursor is hoovering over the tab.

Wrong behavior:
![wrong](https://cloud.githubusercontent.com/assets/18676913/24693275/11373d22-19dd-11e7-98f8-012d240e2a0d.png)

It should be this:
![good](https://cloud.githubusercontent.com/assets/18676913/24693277/11acfe18-19dd-11e7-97e9-7a555a934f80.PNG)

### System and version 
Continuous release   1.7.0.201703280437, windows 7, jre1.8.0_121

**Comment by agrignard** [comment]
I already know the answer form @AlexisDrogoul: "Who on earth still uses Window 7 ? " ;-)

**Comment by AlexisDrogoul** [comment]
Probably related to http://stackoverflow.com/questions/36752848/can-not-close-an-editor-tab-in-eclipse, and yes, who the heck is still using this OS ? You should try the "fix" described (Close all editor) -- but this will be a "no fix" for GAMA as it seems to be tied to a combination of SWT and certain (old) OSes.
