### ISSUE TITLE
Using species in argument of a method

### ISSUE THREAD

**Issue by romainlardy** [gama-platform/gama#2169]
### Steps to reproduce
I need to use a species type in argument of a method. The old GAML syntax works but not the new one.
I mean, this code works: 
action constructionZonesAdministratives{
arg typeZA type: species default: zoneAdministrative;
}

while this way of writing does not compile:
action constructionZonesAdministratives (species typeZA <- zoneAdministrative){}

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)
I use GAMA 1.7 on windows (I did not checked the last continous build, I use the GAMA1.7_Win_64_03.06.17_0614ead )

**Comment by AlexisDrogoul** [comment]
In order to use the new syntax, you need to specify the ancestor of the species you want to pass. If you dont know it (i.e.. it can be any type of species), you can write `species<agent> typeZA <- ...`.

**Comment by romainlardy** [comment]
Thanks a lot, it works.
