### ISSUE TITLE
un-focus/ un-highlight an agent

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2170]
I may be wrong that it does not exist yet. :)

Through the inspect window, it is possible to focus and highlight an agent. I would now like to have a feature that allows to un-focus, un-highlight an agent. So may be in the actions menu within inspect, a check mark could indicate that current agent is in focus/ highlight and unchecking this should release the highlight/ focus of this agent. Because my understanding is that there is no way to un-focus or un-highlight an agent?

Thanks

**Comment by AlexisDrogoul** [comment]
Unfocusing an agent does not make a lot of sense (on which "view" do you unfocus ?). The "zoom fit" action is probably sufficient in that case. For removing the highlight, I have pushed a small modification that makes the highlight action run as a toggle (in the inspector, in the contextual menus and agents menu).
