### ISSUE TITLE
map from two lists create_map(list,list)

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2172]
Hi,

I was wondering if it is already possible to make a map variable from two same sized lists. Mostly a map variable will contain pairs of values. It is convenient to make this map variable with pair of equal sized lists. But I have see this in GAML yet. I have a pair for 5000 items, ie., 5000::5000. I can definitely not write them manually, so I would like to request for an enhancement that make it possible to simply 

` map newMap <- create_map(list1, list2) // each list of 5000 elements for example) `

thank you

**Comment by dphilippon** [comment]
Hi Sriri, 
I don't know if it interests you but you can do it like this : 
````
model sri

global
{
	list<float> listOne <- [1.0,2.0,3.0];
	list<string> listTwo <- ["a","b","c"];
	
	map<float,string> aMap <- listTwo index_by listOne[listTwo index_of each];
	
	init
	{
		write aMap;
	}
}
experiment test
{
	
}
````
The index one operator creates the key values of the map using the right hand operand, which in here is the corresponding item at the same index in listOne that the item in listTwo :)

**Comment by sriramab** [comment]
Hi Damien, Thank you for this workaround. It works.  But Can I leave this for an enhancement?  May be something you can add to GAMA code?? :) Thanks again!

**Comment by dphilippon** [comment]
Hi Srirama, 
I've just committed something for you : the create_map operator. 
The operator takes two lists, the left operand is the keys list, and the right one the values list.

Two comments : 
If the lists are different sizes, it will create a map with the minimum sizes between the two. 
If the keys list contains duplicates, it will throw an error. 

Is it good for you ? If so, feel free to close the issue ;) 

Here is a short model resuming what I've done 

````
model IssueSriMap

/* Insert your model definition here */

global
{
	map<int,float> aMap;
	string experimentType <- "keys smaller" among:["good","keys smaller","keys bigger","double keys"];
	list<int> keysMap<-experimentType="good"?[6,1,2,3]:(experimentType="keys smaller"?[6,1,2]:(experimentType="keys bigger"?[6,1,2,3,4,5]:[6,1,1,2]));
	list<float> valuesMap<-[0.1,0.2,0.3,0.4];
	init
	{
		aMap<- create_map(keysMap,valuesMap);
		write aMap;
	}
}
experiment goodMap type:gui
{
	parameter "exp type" var: experimentType <- "good";
}
````

You can choose the dropdown list to choose a scenario (creating with same sized lists, different sized lists and the worst case: duplicates in the keys). The result is written in the console.

**Comment by sriramab** [comment]
Excellent. Exactly what was needed. It works like a charm. Thank you so much for your time. 👍
