### ISSUE TITLE
Bad quality rendering after a keystone transformation 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2174]
I am finally trying to really use the keystone on a physical table. I am a bit disappointed by the final results. In the attached file you can see the initial rendering on the left and the keystone display on the right. => the quality of the rendering is somehow very bad on the right.

I was rendering maybe there is a parameter to "twick" in order to have a better rendering. What happens in the affine transformation is there somewhere a place where we predefine the quality of the transformation? 

![screen shot 2017-04-10 at 19 53 43](https://cloud.githubusercontent.com/assets/3928502/24887183/e8ad11a2-1e27-11e7-83bd-194f7d445156.png)

### Steps to reproduce
1. Use a Keystone display

2. Deforme it in order to fit your physical surface 

3.

### Expected behavior
Distorted display

### Actual behavior
Distorted display but with a lot of aliaising and a bad quality

### System and version 
GAMA RC1

**Comment by AlexisDrogoul** [comment]
The fact is that keystoning IS NOT an affine transformation (otherwise it would be pretty simple). Hence the results. Subsequent shaders (blurring, smoothing, etc.) should probably be applied, but it would be nice if someone else can handle the job, as I won't have no time to do it soon...

**Comment by agrignard** [comment]
I know this is super time consuming. No rush for this issue as I found one way to "keystone" using only camera pos. 

So it works with the latest build but unfortunately not with the RC1 (see issue #2142).

**Comment by AlexisDrogoul** [comment]
Subsumed by #2209

**Comment by AlexisDrogoul** [comment]
The rendering should now be a bit better.
