### ISSUE TITLE
Gama 1.7 RC1 & RC2 not working on a fresh Ubuntu

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#2179]
I can't get Gama working on my Ubuntu computer for a while now (exact same problems as described in this issue), so, I created a new system on a VM to have it working.

The system runs on VirtualBox,  and is a native Ubuntu 16.04 (LTS) amd64,  installed right from the desktop ISO.
I installed nothing on it, just Java 8 as explained in the wiki (using the webupd8team ppa).

My java config is correct and points toward this jre.

When launching Gama, the platform launch and the models (included) are correctly displayed.
But when opening any of those models, the experiment button is never (or sometimes, after like 10 minutes) "green" : it displays "Waiting...", for a very long time.

When trying to launch the experiment by unfolding the model file, it also fails : the experiment GUI is opened,  but seems to stop loading its content : there is no "launch" button, and nothing can be done :

![capture du 2017-04-14 19-04-25](https://cloud.githubusercontent.com/assets/807703/25050063/5e4bf0de-2145-11e7-9080-e8edda96b823.png)

When launching Gama from  terminal, no usefull crash/bug is logged, only some little useless graphical glitches.

To be short : Gama doesn't work on Ubuntu...

Some of your developpers are succesfully running Gama 1.7+on Ubuntu, so, there must be a way to have it work, but right now, with the informations described in the Wiki (troubleshooting included), it's not working.

I don't know if/how this can be solved, but it would for sure be usefull to have some recent versions of Gama working on Ubuntu, especially considering all the errors that have been corrected since 1.6

Any hint/idea/test/report would be highly appreciated :)

**Comment by AlexisDrogoul** [comment]
Did you try the procedures described here: https://askubuntu.com/questions/761604/eclipse-not-working-in-16-04 ?

**Comment by RCura** [comment]
I'll test that on tuesday, keeping you aware :)

**Comment by RCura** [comment]
Yes, this works :tada: 
I'm trying to make a PR to have this as default in Ubuntu, but I can't compile right now (the build.sh doesn't work here), so, can't test.

## Fix
Just in case it's not that wrong, here's what I wanted to try, in `ummisco.gama.product\gama.product` (don't know if this one should be changed or `gama.runtime.product` : 

Replace : 
```
      <programArgs>-nl ${target.nl} 
-data @noDefault 
--launcher.defaultAction
openFile
      </programArgs>
```

With : 

```
<programArgs>-nl ${target.nl} 
-data @noDefault
        <vmArgsLin>
--launcher.GTK_version
2
        </vmArgsLin>
        <vmArgsWin>
--launcher.defaultAction
        </vmArgsWin>
        <vmArgsMac>
--launcher.defaultAction
        </vmArgsMac>
openFile
      </programArgs>
```

This might work as a "working" gama.ini (in the build) is this one : 
```
-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417
-nl
${target.nl}
-data
@noDefault
--launcher.GTK_version
2
openFile
-vmargs
-server
-noverify
-Xmn128m
-Xss2m
-XX:+UseParallelGC
-XX:+UseAdaptiveSizePolicy
-XX:+OptimizeStringConcat
-Xms256m
-Xmx2048m

```

**Comment by AlexisDrogoul** [comment]
Thanks for the solution. Unfortunately, I couldn't add it in time to RC2 (which is just out), but we'll integrate it for the next release. Leaving this issue open for anyone having the same problem.
