### ISSUE TITLE
diffusion statement red rgb value in the middle

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2188]
### Steps to reproduce
1. run Diffusion Statement/ Uniform Diffusion.gaml

### Actual behavior
The model works fine but I am a bit surprised by the color of the cell in the middle which stays red wheras is should be blue (cf picture) 
<img width="541" alt="screen shot 2017-05-01 at 10 49 12" src="https://cloud.githubusercontent.com/assets/3928502/25582581/0c16211c-2e5c-11e7-91b9-441fa5a3a92e.png">

### System and version 
GAMA RC1

**Comment by dphilippon** [comment]
Hi , 
Why should it be blue ? According to the code, the cell in the middle has a variable "phero" updated each time step at 1.0 (to maintain the diffusion), which is the value used for the hsb. 1.0 being equals to a whole turn in the HSB palet, it will correspond to 360° or 1.0 or 0.0, which corresponds to red.  If it is just in terms of understanding, it is just the value used for the hsb that must be changed (like considering a maximum value to set the color, 0.7 for a deep blue for instance, but it could also be confusing as cells having phero between 0.7 and 1.0 will be displayed with the same color). I still can change it if you think it is better ;)

**Comment by agrignard** [comment]
Mmm i don't know visually it would make more sense no as in this visualization red means 0 but ok I got it's because of 1.0 is also 360...

**Comment by dphilippon** [comment]
Changed ! Now the maximal value taken for the color is 0.7 (so basically a blue color)

**Comment by agrignard** [comment]
I think you put 0.6 as the max value

Are we sure we never reach more than 0.6 in the phero?

**Comment by dphilippon** [comment]
We reach 1.0 as the maximal value, so if we consider this value, we will have a red cell in the middle. It's a choice we have to make...
