### ISSUE TITLE
halt and cycle elapsed that continues to increase

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2189]
### Steps to reproduce
1. Test the following model:
model scheduleglobal

global {
	init {
		create speciesA number: 2;
	}
	reflex info {
		write "---- " + cycle + " -----";
	}
	
	reflex end_sim when: cycle = 5 {
		do halt;
	}
}
species speciesA {
	reflex info {
		write name;
	}
}
experiment main type: gui ;

experiment batchmode type: batch until: cycle > 5;

2. Run the main experiment

### Expected behavior
The model should stop after 5 cycles

### Actual behavior
The model seems to stop after 5 cycles (no more message written on the console), but the cycle elapsed still continues to increase.

Note that it is working normally for the batch experiment.

### System and version 
Git version, Linux (Ubuntu 16)

**Comment by AlexisDrogoul** [comment]
From the (internal) documentation : "It is preferable to use 'die' instead to kill a simulation, or 'pause' to stop it temporarily". `halt` is deprecated and does not work anymore. I changed the way primitives display their documentation so that this information is available to the modeler.

**Comment by ptaillandier** [comment]
ok, I didn't know that killing a simulation was acceptable.
