### ISSUE TITLE
EPSG/CRS loading problem in OpenMole

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#2190]
Hi gamateam,

I try to run a simulation model using gamaHeadless with OpenMOLE. **I precise that this model works correctly using GUI and the one of the latest continuous dev version of Gama.** 

It seems we have a problem with geotools which cannot load an epsg during simulation initialization : 

```
PRￃﾉCIS: Setting the EPSG factory org.geotools.referencing.factory.epsg.DefaultFactory to a 1800000ms timeout
mai 04, 2017 6:15:27 PM org.geotools.referencing.factory.epsg.ThreadedEpsgFactory <init>
PRￃﾉCIS: Setting the EPSG factory org.geotools.referencing.factory.epsg.ThreadedEpsgFactory to a 1800000ms timeout
mai 04, 2017 6:15:27 PM org.geotools.referencing.factory.epsg.ThreadedEpsgFactory <init>
PRￃﾉCIS: Setting the EPSG factory org.geotools.referencing.factory.epsg.DefaultFactory to a 1800000ms timeout
mai 04, 2017 6:15:27 PM org.geotools.referencing.factory.epsg.ThreadedEpsgFactory <init>
PRￃﾉCIS: Setting the EPSG factory org.geotools.referencing.factory.epsg.DefaultFactory to a 1800000ms timeout
mai 04, 2017 6:15:27 PM org.geotools.referencing.factory.epsg.ThreadedEpsgFactory <init>
PRￃﾉCIS: Setting the EPSG factory org.geotools.referencing.factory.epsg.ThreadedEpsgFactory to a 1800000ms timeout
mai 04, 2017 6:15:27 PM org.geotools.referencing.factory.epsg.ThreadedEpsgFactory <init>
PRￃﾉCIS: Setting the EPSG factory org.geotools.referencing.factory.epsg.DefaultFactory to a 1800000ms timeout
mai 04, 2017 6:15:27 PM org.geotools.referencing.factory.FallbackAuthorityFactory createCoordinateReferenceSystem
PRￃﾉCIS: ￃﾉchec dans la fabrique primaire: Aucun code "EPSG:32647" de l'autoritￃﾩ "EPSG" n'a ￃﾩtￃﾩ trouvￃﾩ pour un objet de type "EngineeringCRS". La fabrique secondaire sera interrogￃﾩe.
```
I search if the EPSG exist into msi.gama.ext loaded by openMole which contain geotools jars  (`msi.gama.ext.jar/gt-epsg-wkt-14.5.jar/msi.gama.ext/epsg.properties`)

The EPSG:32647 exist in this file, so it seems this is more a problem with geotools which have problems to find resources. I found some [starting informations on SO](http://stackoverflow.com/questions/27429097/geotools-cannot-find-hsql-epsg-db-throws-error-nosuchauthoritycodeexception) but perhaps you have already noticed in your team this type of problem ?

### System and version 
Continous build version

**Comment by AlexisDrogoul** [comment]
Found a solution ? I havent had this problem in the desktop version, so maybe there is (as mentioned in SO) a problem of conflicting services in the gt libraries you load.

**Comment by AlexisDrogoul** [comment]
Any updates on this one ? Looking at the error you get, you are in a classical situation of conflicting libraries, which means you have to choose one and only one `epsg` library among the three some provided by GeoTools at deployment time. See for instance: http://docs.geotools.org/stable/userguide/faq.html#q-how-to-i-add-my-own-epsg-codes

So the problem should be more on Maven side (i.e. which plugins you include when you link to GeoTools from Maven) if you do it dynamically. On the other hand, if you include `msi.gama.ext`, you shouldn't run into it. So can you provide us with the way you load Geotools (if you do) ?

**Comment by AlexisDrogoul** [comment]
Now tracked under #2453

**Comment by hqnghi88** [comment]
@reyman Can you provide a model that i can test in headless mode (not with openmole). Thanks.

**Comment by reyman** [comment]
@hqnghi88 , i try to see that during summer.

**Comment by hqnghi88** [comment]
Any chance to see it sooner, as we wish to release an official Gama version next week.
Thanks.

**Comment by agrignard** [comment]
I didn't notice this bug, does it mean that any simulation dealing the loading of an EPSG loading in headless wouldn't work? I think that's a critical bug ? 

In my case the hello world I did with headless during the coding camp it was just to anticipate some more complicated or just simple model running on a GIS model  using an EPSG projection.

I just reopen this issue for 1.8 , just in case and I wiil try soon to reproduce the bug

**Comment by AlexisDrogoul** [comment]
@agrignard I guess it concerns OpenMole and the way they are loading libraries. You should try it on classical headless.

**Comment by AlexisDrogoul** [comment]
@gama-platform/core can someone test the use of EPSG codes in headless simulations ?

**Comment by agrignard** [comment]
I have try with one model using shapefiles it seems to work.

**Comment by AlexisDrogoul** [comment]
Closing this issue on which no information has been provided for a long time !
