### ISSUE TITLE
Broken updates.gama-platform.org ?

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#2192]
Hi,

As usual when i compile gama plugin for openmole, i'm trying to access the p2 repository  `http://updates.gama-platform.org` . Today url seems impossible to resolve, is there a problem ?

` Failed to load p2 repository with ID 'GAMA update site' from location http://updates.gama-platform.org
`

**Comment by hqnghi88** [comment]
Something is missing
[ERROR] Cannot resolve project dependencies:

[ERROR]   Software being installed: ummisco.gama.feature.core.feature.group 1.7.0.qualifier

[ERROR]   Missing requirement: msi.gama.headless 1.7.0.qualifier requires 'bundle femto.st.gama.mpi 1.7.0' but it could not be found

[ERROR]   Cannot satisfy dependency: ummisco.gama.feature.core.feature.group 1.7.0.qualifier depends on: msi.gama.headless 0.0.0

**Comment by hqnghi88** [comment]
It seem to be some missing feature of new plugin mpi (Nico?). I am currently fixing but with slow connection and slow travis.

**Comment by hqnghi88** [comment]
Hi Rey,
Could you please retry now?

**Comment by reyman** [comment]
OK for me :) Thanks
