### ISSUE TITLE
Organize the depency femto.st.gama.mpi;bundle-version="1.7.0" in headless plugin

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2193]
### Steps to reproduce
1. After the commit
https://github.com/gama-platform/gama/commit/5d7c56b214ec74c066a1a23d3c32609e2768bd84
2. headless plugin has the dependency on femto.st.gama.mpi;bundle-version="1.7.0"

3. Is it a default added feature of gama core repository or it should be on experimental repository?

### Expected behavior
Tell us what should happen (include all relevant expectations)

If it is mandatory to be presented  may be we could move it to gama core, because a git clone of gama core repository will complain about compilation error of dependency femto.st.gama.mpi

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
Bundle 'femto.st.gama.mpi' cannot be resolved
### System and version 
Gama git
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
This should clearly NOT be a dependency ! Please revert the commit.

**Comment by hqnghi88** [comment]
I have created a feature for mpi in experimental repo and remove the dependency . The continous builds re-worked on both core and experimental. Please pull and import the feature.mpi plugin.

**Comment by gnoubi** [comment]
Sorry

Maybe, I commit my modified core feature…. sorry. 

nicolas
-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06
