### ISSUE TITLE
Inspector impacts on the speed of the simulation

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2194]
### Steps to reproduce (Maybe a bit hard to reproduce as it seems to appears on large scale model)
1.Run a model

2.Inspect an agent, then the iteration slows down which is ok as all the information need to be updated

3.once you close the inspector I have the feeling that the simulation gets slower(maybe a question of synchronisation that is not release after the inspection?)

### Expected behavior
Simulation should run as fast as before

### Actual behavior
Simulation runs slower (once again it's only noticable on "heavy" model

### System and version 
GAMA RC2

**Comment by hqnghi88** [comment]
Hi Arnaud,
It was on the RC2 or continuous release? Could you reproduce the issue and view the Average duration in the hover popup of the Status bar, for before and after the inspectation. (It should show something like: Duration (ms) cycle xxx, Average xxx)

**Comment by agrignard** [comment]
Yes i check that but as I said it's only on a large large specific model. I'll try to share it asap.
