### ISSUE TITLE
buffer in draw statement has bad/no rendering

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2195]
### Steps to reproduce
1. Take any linear feature shape file

2. use: draw shape+1 colour:#black  // or as you like but with a buffer

### Expected behaviour
I expect a thicker line than original

### Actual behaviour
only partial display appears. in java2D: in 100 linear features in my case, only 20 odd were shown. There are no other species in display.
in OpenGL nothing was shown.

### System and version 
Mac 10.9, GAMA standalone 22/5/2017, java 1.8, display in java2D and OpenGL

**Comment by dphilippon** [comment]
Hi Srirama, 
Do you think you could provide me the shape file ?
I can't reproduce the bug (see the screen shot)

<img width="1172" alt="screenshot" src="https://cloud.githubusercontent.com/assets/15722750/26675047/9bc93044-46ec-11e7-9833-23c7edac3729.png">

**Comment by sriramab** [comment]
this is the file I am using
[Archive.zip](https://github.com/gama-platform/gama/files/1044443/Archive.zip)

**Comment by dphilippon** [comment]
Is this the output expected ? 
I increased a little bit (by 1000 instead of 1) the shape of the road. 
The file also seems to have geometry validity problems (I checked the validity on QGIS). Do you think it is possible for you to correct them and try again ? (just to be sure it is not a result from the error in terms of validity in the shapefile)

<img width="1125" alt="screenshot" src="https://cloud.githubusercontent.com/assets/15722750/26677719/55d5d636-46f7-11e7-9660-2ae8bbb5e392.png">

**Comment by sriramab** [comment]
how did you check the validity? I recently moved to QGIS, I do not know the right tool to check validity.

**Comment by sriramab** [comment]
And I think the problem is buffer value. If i have no buffer value: I can see the roads. If I have 1 as buffer value, I see nothing. If I have 100 as buffer value, i see faint lines. 

I wonder why it shows lines without any buffer, and why it does not show with +1 (or becomes faint as almost invisible) ? Is GAMA doing some kind of scaling by default when no buffer is given?

It works for you for a on the small tutorial file, because it covers a small area. Can you perhaps try to define a 10 times bigger envelope for the tutorial file and then try buffer values to see what I mean? 

I doubt that GAMA is doing some kind of scaling. My roads are for the whole country unlike the tutorial file which is just a small town.

**Comment by dphilippon** [comment]
Basically a road is of kind LINESTRING, which is a type of geometry in GAMA that is always displayed with one pixel of width (You can zoom in, or zoom out, it will always be one pixel, just as vector graphics).  However, when you add the buffer to this LINESTRING, it becomes what is called a POLYGON (being the result of enlarging the "shape" of the line). The thing is that POLYGON and LINESTRING are not displayed in the same way (as I told you, it's vector graphics for LINESTRING with 1 width no matter what the level of zoom is, while it is not the case with POLYGON).

**Comment by sriramab** [comment]
Thank you. This is the clearest answer I ever received 😄

**Comment by AlexisDrogoul** [comment]
Hi, Damien is right. Adding a buffer to a line creates a polygon, not a thicker line. I think the "width" or "line_width" facet has been added recently for this purpose.

**Comment by sriramab** [comment]
Thank you Alexis.

**Comment by agrignard** [comment]
By the way we all agree that it would be nice to be able to give a width to a line instead of directly having a polygon. But this is another story and I think it's already an issue ?

**Comment by dphilippon** [comment]
You can already do it by specifying the facet 'width' in the draw :-)

**Comment by agrignard** [comment]
oh that's right i did know this facet, great!!

How did you implement that? using gl_width? I remember that i faced some issue when I tried to do it (few years ago now ;-)

**Comment by dphilippon** [comment]
I didn't implemented it, but from what I know you have a native function called glLineWidth expecting a float to do that... so we just have an entry point to this function. It has been added for a long time already in OpenGL, as OpenGL 2.0 has it ;)
