### ISSUE TITLE
Feature Request - Adapt with_precision to geometry

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#2196]
Currently, geometries are exported to WKT when casted to strings.
This is very good for easy outputs and data exploration outside Gama.

When casting to string, you get 12 decimals for each coordinates, which is a precision that is below the nanometer, and thus, not that usefull.

There is no real problem with it though, except when exporting the files : having 12 decimals when 3-4 might be more than enough increases a lot the written files size.

It seems to me that for such situations, it could be handy to adapt the current `with_precision` operator to geometries, so that the casted points/lines/polygons would only have the specified number of decimals.

Considering `with_precision` can already be applied to `points`, I think it could also be applied to non-point geometries, i.e. points-lists geometries :)

**Comment by ptaillandier** [comment]
ok, I adapted it. You can now write:
geometry g_simp <- my_geom with_precision 1;
