### ISSUE TITLE
Batch: series in permanent skip the 1.0 coordinate

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2204]
### Steps to reproduce
1. In a bacth exploration, add a permanent block to display an indicator over simulations.

2. See for example, the following model: 
model testBatch

global {
	float parameter <- 0.0; 
	float indicator <- 0.0;
	
	reflex get {
		indicator <- rnd(parameter);
	}
	
}

experiment Sensibilite type: batch keep_seed: true repeat: 2 until: (cycle >= 1) {
	parameter parameter var:parameter min: 1.0 max: 3.0 step: 1.0;
	
	permanent {
		display i {
			chart "Indicator" type: series {
				data "I" value: mean(simulations collect each.indicator) style: spline color: #blue ;		
			}	
		}	
	}
}

### Expected behavior
We should have in the permanent, points at coordinates 0.0, 1.0, 2.0 ...

### Actual behavior
We do not have a point at 1.0

### System and version 
GAMA 1.7 RC2, MacOSX

**Comment by AlexisDrogoul** [comment]
First comment: this conflicts with the solution brought to issue #1273 ...
