### ISSUE TITLE
Gama-headless seems to run concurrent execution without any warning

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#2207]
Hi,

We found that for **one execution** of our model using _gama-headless_, gama systematicely run **two execution** of the simulation.

You could reproduce easily this error with OpenMOLE by printing **seed** during init phase and running phase. We could see two concurrent print, and many file lock error.

I don't know where the problem is but it cause multiple error on cluster environment (file lock, etc.)

**Comment by reyman** [comment]
Ok, we found the error... 
When we call the experiment in OpenMOLE Gama-task, my coworker use `batch` type, with `repeat 1` parameter. This is why gama run two time on the same call.

This is not totally clear for beginner, is it possible to create an `headless` type for experiment ? So i could check in gama-task if the experiment is correct ?

**Comment by AlexisDrogoul** [comment]
If only the seed is printed, pay attention to the fact that there are always two seeds: one for the experiment and one for the simulation. But this seems to be a different issue, and difficult to solve, too, without more details on the model actually tested, how the experiment is written, etc. If you can share the model, it might be easier to spot.

**Comment by AlexisDrogoul** [comment]
OK. Our answers arrived at the same time. I dont see what a `headless` experiment would bring ? Just create a normal one, no (i.e. `gui`) ? Or is there something I miss here ?

**Comment by reyman** [comment]
Hi, perhaps i misunderstand but, i think it's strange for users we want to run openmole + gamatask with no gui to indicate a "gui" for experiment , no ?

**Comment by AlexisDrogoul** [comment]
Just leave it blank. The default will be `gui`, but it is easier than having to define a special keyword for `headless` experiments (unless they allow for some special definitions like `method` for the `batch` and/or allow to manage the way they are run in OpenMole, for instance, but since it is not the case for the moment...)
