### ISSUE TITLE
Problem with transparence for cells in a grid

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#2208]
I got an error in terms of transparence, 
I don't really know for the moment from what it comes from.. Basically, I have
a grid with different cells. Each cell contains a certain number of values, representing what could
be a 3D cells. The cells could have different colors or textures to represent grass, stone, sand, water. 

For water cells, I simply draw a box with a color being a cyan with transparence. However, the transparence seems to be a little bit buggy with a certain angle (to define). 

Here are some screenshots to show you 

<img width="552" alt="screen shot 2017-07-12 at 9 06 43 pm" src="https://user-images.githubusercontent.com/15722750/28121978-0bcf3ab2-6747-11e7-9b4d-9af36893e5f0.png">
<img width="531" alt="screen shot 2017-07-12 at 9 10 32 pm" src="https://user-images.githubusercontent.com/15722750/28121977-0bc83654-6747-11e7-90f2-e890b1e420ca.png">
<img width="496" alt="screen shot 2017-07-12 at 9 10 35 pm" src="https://user-images.githubusercontent.com/15722750/28121979-0bdac4d6-6747-11e7-8743-b45eeae67c05.png">

**Comment by AlexisDrogoul** [comment]
Subsumed by #2209

**Comment by agrignard** [comment]
@dphilippon is it possible for you to send the model so I can have a look?

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
Without more information, I'm closing this.
