### ISSUE TITLE
Update the right GAMA platform version on the website

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2211]
Currently on the gama platform website download session, the GAMA1.7 is pointing to an old version and not the release candidate.

It happens a lot to me that people download the 1.7 instead of the release candidate. Ok i know this is written but by default the lambda user will use the 1.7 instead of the release candidate, isn't it?

So wouldn't it be better to put by default the release candidate as the official 1.7 ?

**Comment by dphilippon** [comment]
Done

**Comment by agrignard** [comment]
Nice as I see you are super reactive maybe on the release candidate we can only keep the last one, so people has no choice to download version 1 or 2 which is still a bit confusing?

**Comment by dphilippon** [comment]
Yeah, it has been changed
