### ISSUE TITLE
Try/Catch in GAML

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2212]
What about giving the possibility to have a kind of try/catch process in GAMA

I had a request from a colleague that are running a lot of simulation in batch mode and in some cases they'd like to be able to handle exception.

Is it something doable or very complex to implement in GAML?

**Comment by sriramab** [comment]
A good suggestion. +1

**Comment by AlexisDrogoul** [comment]
I've pushed a first proposal, necessary incomplete as it relies only on the current implementation of the error handling, which probably needs to be revised to accept a better flow of reporting. The syntax is 'classical', in that it relies on the `try` / `catch` keywords. A special string constant, `#current_error` is available. For instance:

```
try {
    error "One error";
} catch {
   write "an error occurred: " + #current_error;
}
```

Things to keep in mind in this implementation:
- Errors (i.e. exceptions) are not GAML objects and thus cannot be made available in the `catch` block with all their attributes (e.g., in which agent, etc.). I plan to introduce them later but this would need a completely new implementation of `GamlRuntimeError`(open a separate issue if you need it to be available)
- Errors are not reported in the interface when they are caught (only the Java stack trace mentions them) and the execution is not halted even if the global preference to stop simulations when an error occurs is set to true.
- The absence of the `catch` block disables any reporting and catching (i.e. the error is thrown silently).
