### ISSUE TITLE
No documentation/manual in PDF format

### ISSUE THREAD

**Issue by megapteropus** [gama-platform/gama#2213]
Everything is in the title... :-)

**Comment by AlexisDrogoul** [comment]
We actually did have a PDF version of the doc, but it was buried in some obscure sub-directories. Note that it is not the most up-to-date version: it is the one found at the [gama-platform](https://gama-platform.org) website, which is not updated often. The most recent documentation is always found in the [wiki](https://github.com/gama-platform/gama/wiki) and, soon, the [github.io website](https://gama-platform.github.io), as @dphilippon is now able to build it automatically at each build of the platform or change in the wiki. He also should normally be able to produce the PDF doc automatically now, too.

In the meantime, I nevertheless corrected the few dead links I could find in the wiki to replace them by the [correct one] (https://github.com/gama-platform/gama/wiki/resources/pdf/docGAMAv17.pdf).
