### ISSUE TITLE
Co Model Example broken?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2215]
### Steps to reproduce
1. Run Comodel Example (Mixed Behaviors).gaml and Comodel Example (Populations Mutated).gaml

2.

3.

### Expected behavior
Something happens

### Actual behavior
I have nothing moving for both model (only comodel display in Populations Mutated is updated actually)

### System and version 
GAMA RC2

**Comment by AlexisDrogoul** [comment]
@hqnghi88 any updates on this one ?

**Comment by hqnghi88** [comment]
i have worked on this and found it has problem witb paralleled experiement
(when it is on in prefs), but i did not found the solution yet
