### ISSUE TITLE
Programmatically toggle toolbar

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2218]
I know it sounds a tiny request but for demo purpose I have a demo where I systematically need to minimize the toolbar in a display. For me it's fine but most of the time other people that run the demo forget to do that and then the window has too much information. 

Would it be possible to programmatically turn it on/off with something like a facet on a display called toggle toolbar:true/false or worse case in the preferences?

<img width="645" alt="screen shot 2017-07-25 at 15 16 30" src="https://user-images.githubusercontent.com/3928502/28589471-554bad88-714c-11e7-8cad-487c3a738bb1.png">

**Comment by AlexisDrogoul** [comment]
I've added a new facet to displays: `toolbar` (`true` or `false`), which can be used to individually override a new global preference (in the Displays section) that makes toolbars initially visible or not in display views.

**Comment by agrignard** [comment]
great! thanks!
