### ISSUE TITLE
Annoying error when starting GAMA from Eclipse

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2220]
### Steps to reproduce
1. Launch GAMA 1.7 Git from Eclipse (using a default Launch Configuration)

### Expected behavior
Some information should be logged (loading of GAMA libraries, etc.)

### Actual behavior
An annoying error (although apparently harmless -- but this needs to be confirmed) shows up in the console: 

```
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ecf.provider.filetransfer.httpclient4 [80]
  Unresolved requirement: Import-Package: org.apache.http.auth; version="4.1.0"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

Am I the only one to observe this ? I dont know exactly when it appeared first, probably 2 weeks or so from now, but maybe it's older. 

### System and version 
GAMA 1.7 version Git, MacOS X 10.12.5

**Comment by hqnghi88** [comment]
Dear Alexis,
I use eclipse Version: Neon.3 Release (4.6.3) . I don't have that error
Here is my log:
>GAMA version 1.7.0.qualifier loading...
>GAMA models library version: .built_in_models_1500886575653
!SESSION 2017-07-26 14:31:34.390 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product msi.gama.application.runtime --launcher.defaultAction openFile
Command-line arguments:  -product msi.gama.application.runtime -data D:\wpNeon/../runtime-gama.runtime.product -dev file:D:/wpNeon/.metadata/.plugins/org.eclipse.pde.core/gama.runtime.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -data @noDefault --launcher.defaultAction openFile

!ENTRY org.eclipse.core.resources 2 10035 2017-07-26 14:31:40.672
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
>GAMA plugin loaded in 689 ms: 	msi.gama.core
>GAMA plugin loaded in 5 ms: 	ummisco.gama.network
>GAMA plugin loaded in 42 ms: 	simtools.gaml.extensions.traffic
>GAMA plugin loaded in 5 ms: 	simtools.gaml.extensions.physics
>GAMA plugin loaded in 5 ms: 	irit.gaml.extensions.test
>GAMA plugin loaded in 10 ms: 	ummisco.gaml.extensions.maths
>GAMA plugin loaded in 22 ms: 	msi.gaml.extensions.fipa
>GAMA plugin loaded in 14 ms: 	ummisco.gaml.extensions.stats
>GAMA plugin loaded in 9 ms: 	ummisco.gama.serialize
>GAMA plugin loaded in 15 ms: 	irit.gaml.extensions.database
>GAMA plugin loaded in 5 ms: 	msi.gama.lang.gaml
>GAMA plugin loaded in 5 ms: 	msi.gama.headless
>GAMA plugin loaded in 7 ms: 	ummisco.gama.java2d
>GAMA plugin loaded in 71 ms: 	msi.gaml.architecture.simplebdi
>GAMA plugin loaded in 16 ms: 	ummisco.gama.opengl
>GAMA total load time 996 ms.
GAMA Caught a workbench message : Perspective with name 'Simulation:neww_model:s' and id 'Simulation:neww_model:s' has been made into a local copy null
System font = [1|Segoe UI|9.0|0|WINDOWS|1|-12|0|0|0|400|0|0|0|1|0|0|0|0|Segoe UI]
>GAMA building GAML artefacts in 561 ms

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.788
!MESSAGE Duplicate template id: 'Species'
GAMA Caught a workbench message : Duplicate template id: 'Species' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.793
!MESSAGE Duplicate template id: 'Experiment.Batch'
GAMA Caught a workbench message : Duplicate template id: 'Experiment.Batch' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.800
!MESSAGE Duplicate template id: 'Definition.Attribute'
GAMA Caught a workbench message : Duplicate template id: 'Definition.Attribute' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.806
!MESSAGE Duplicate template id: 'Statement.Do'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Do' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.815
!MESSAGE Duplicate template id: 'Statement.If'
GAMA Caught a workbench message : Duplicate template id: 'Statement.If' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.821
!MESSAGE Duplicate template id: 'Statement.Loop'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Loop' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.826
!MESSAGE Duplicate template id: 'Statement.Loop'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Loop' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.831
!MESSAGE Duplicate template id: 'Statement.Loop'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Loop' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.836
!MESSAGE Duplicate template id: 'Statement.Loop'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Loop' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.843
!MESSAGE Duplicate template id: 'Statement.Create'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Create' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.848
!MESSAGE Duplicate template id: 'Statement.Create'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Create' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.852
!MESSAGE Duplicate template id: 'Statement.Ask'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Ask' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.912
!MESSAGE Duplicate template id: 'Species'
GAMA Caught a workbench message : Duplicate template id: 'Species' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.918
!MESSAGE Duplicate template id: 'Experiment.Batch'
GAMA Caught a workbench message : Duplicate template id: 'Experiment.Batch' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.924
!MESSAGE Duplicate template id: 'Definition.Attribute'
GAMA Caught a workbench message : Duplicate template id: 'Definition.Attribute' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.930
!MESSAGE Duplicate template id: 'Statement.Do'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Do' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.936
!MESSAGE Duplicate template id: 'Statement.If'
GAMA Caught a workbench message : Duplicate template id: 'Statement.If' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.945
!MESSAGE Duplicate template id: 'Statement.Loop'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Loop' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.952
!MESSAGE Duplicate template id: 'Statement.Loop'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Loop' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.959
!MESSAGE Duplicate template id: 'Statement.Loop'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Loop' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.965
!MESSAGE Duplicate template id: 'Statement.Loop'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Loop' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.970
!MESSAGE Duplicate template id: 'Statement.Create'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Create' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.980
!MESSAGE Duplicate template id: 'Statement.Create'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Create' null

!ENTRY org.eclipse.jface.text 2 0 2017-07-26 14:31:49.988
!MESSAGE Duplicate template id: 'Statement.Ask'
GAMA Caught a workbench message : Duplicate template id: 'Statement.Ask' null

**Comment by AlexisDrogoul** [comment]
Probably due to a bad configuration of my run configuration. Closing.
