### ISSUE TITLE
Travis broken on a strange error

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2221]
### Steps to reproduce
1. Nothing in particular. Just commit something to trigger a launch of Travis.

### Expected behavior
No compilation errors can be found in the committed version.

### Actual behavior
Travis stops running and issues the following statement: 

```
Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'eclipse-mars' from location http://download.eclipse.org/releases/mars: Unable to read repository at http://download.eclipse.org/releases/mars. Unable to read repository at http://download.eclipse.org/technology/epp/packages/mars/content.xml. Connect to download.eclipse.org:80 timed out 
```

see also the trace here: https://travis-ci.org/gama-platform/gama/builds/257570025?utm_source=email&utm_medium=notification

### System and version 
GAMA 1.7 Git

**Comment by hqnghi88** [comment]
I have tried several changes, but it seem that eclipse have some issue with its p2 repo . I continue to track

**Comment by AlexisDrogoul** [comment]
These is definitely something going on. The last Travis build has been running for 4 hours... By the way, I noticed something on Travis page: ` This job is running on our Trusty environment, which is gradually becoming our default Linux enviroment. Read all about this in our blog: Trusty as a default Linux is coming and take note that you can add dist: precise in your .travis.yml file to continue using Precise.' 

Could it be a reason ?

**Comment by hqnghi88** [comment]
I have tried to switch to precise but it didn't help. And the trusty is working well after weeks. And i cant access to all p2 repo of eclipse (also from eclipse update menu, and web): 
http://download.eclipse.org/releases/mars/ 
http://download.eclipse.org/releases/neon/
Could you try in your eclipse to see if it was a internet connection problem ? 
I wait a little bit and if it'll not fix by eclipse, i'll make a mirror p2 of all eclipse packages.

**Comment by dphilippon** [comment]
I can't either... But I don't trust my connection now since I can't sometimes see the Operators pages on github..

**Comment by hqnghi88** [comment]
It works again 2h ago when eclipse p2 was accessible. I commit the notification and then close this issue
