### ISSUE TITLE
if inside a display

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2223]
For animation purposes it would be very useful to be able to write a if condition in side a display.

For instance if you want to show an interaction graph only after 100 iteration you could write:
```
if(time>100){
  graphics "the graph" position:{0,0,0.25}{
    loop edge over: smart_grid_graph.edges {
   draw edge color: #green;
 }
```
I know that the if condition has been introduce inside a aspect sometime ago so it might be a bit redondant but why not.

**Comment by AlexisDrogoul** [comment]
The definition of layers is purely declarative (and should stay this way, for many different reasons). There are however ways to do what you want to do using the `transparency` facet: 

```
  graphics "the graph" position:{0,0,0.25} transparency: (time > 100 ? 1 : 0){
    loop edge over: smart_grid_graph.edges {
   draw edge color: #green;
 }
```

**Comment by agrignard** [comment]
Ok so inside a graphic it's actually possible to have a if (not inside a display)

The transparency facet can be an option but if the drawing is greedy (imagine a big graph) the display is still rendering it even if it's transparent.
