### ISSUE TITLE
Add the possibility to load several grid file in a GAMA grid

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2225]
Nowadays, GAMA allows to use one grid_file to initialize a grid. but cannot initialize a grid from several grid file. The idea is to allow such a feature:

grid cell files: [file1, file2....];

with using file1 as the reference file for the grid resolution.

**Comment by dphilippon** [comment]
Totally agree with this ! 
Do you have an idea yet on how to get the different 'grid_value' that contain the value of the files given in the facet ?
