### ISSUE TITLE
3D referential size is... huge

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2227]
I just did an update from the release RC2.

After restarting GAMA I have the drawn referential which is... HUGE!! 

<img width="438" alt="screen shot 2017-08-04 at 14 51 32" src="https://user-images.githubusercontent.com/3928502/28982604-769c75fa-7924-11e7-903c-d3a18f970f01.png">

**Comment by AlexisDrogoul** [comment]
Dont have it myself on the latest build. I know the updates didn't work at one point, maybe the latest ones have not been generated ?

**Comment by hqnghi88** [comment]
hi Arnaud,
Can you verify th version of plugin in the Menu Helps, installation details.

**Comment by agrignard** [comment]
Strange this is still here for me (after an update and a new workspace)

@hqnghi88 Here is a screenshot of the installation details

<img width="1919" alt="screen shot 2017-08-07 at 12 23 16" src="https://user-images.githubusercontent.com/3928502/29035950-7119e9b6-7b6b-11e7-94d0-4a0b695e9a69.png">

**Comment by hqnghi88** [comment]
Hi Arnaud,
I have downloaded a RC2 and updated it from p2. I cannot reproduce this issue with the default preference. Do you have any special change in the prefs?

**Comment by agrignard** [comment]
Ok i finally find a way to reproduce it.

Actually this only happens if "Draw rotation references axes" is set to false
