### ISSUE TITLE
graphic layer order of appearance

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2228]
After an update on the release version I have a graphical regression...

So maybe a a small detail but it was very useful for demo purpose

After showing all my agent there is a part of the screen where I don't want to display anything because there is a physical interface on top of that.

So i use to do at the end of my display once everything has been drawn
```
graphics "blackbox" 
{
  draw rectangle(900,700) rotated_by 9.74 color:#black at: { 2500, 2150};	
}
```

I have the feeling that now the graphic slayer is called before the species one, so the order is not taken in account and my agent are rendered on top of the black rectangle instead of being hidden...

**Comment by AlexisDrogoul** [comment]
If your agents have even a slight elevation (i.e., buildings, etc.), I dont see how this could even remotely work before, since you are simply drawing a plan at elevation 0, which should *always* be drawn behind the agents (whatever the index of the layer). Or maybe your whole display is different ?

**Comment by agrignard** [comment]
Well before everything was drawn on the same plan (z=0) so the order of definition of the layer was used as a trick (you put a rectangle at the very end of the display and it covers everything) . yes of course I can put rectangle with z value it will fix the issue but I just wanted to raise this issue to be sure that we didn't miss an important modification in the layer definition (I think it is fare to consider that the order of the layer as an impact (first defined first drawn))

**Comment by agrignard** [comment]
Well there is definitely something strange with the order of the layer now. We didn't have to put a z value before and playing with the order of the layer was the only way (and actually) a good one to put shape of top of each other.

Typically to put agent on top of a building you just had to do this

```
species building aspect:usage;
species people aspect:scale;
```
but it's not the case anymore for me (people are actually drawn under the building with this piece of code)

Anything related to z-fighting?

**Comment by agrignard** [comment]
in link with #2222 ?

**Comment by AlexisDrogoul** [comment]
I have not been able to reproduce this problem in the "standard" library models. Can you share one that actually displays this error in the order of layers ?

**Comment by agrignard** [comment]
You can reproduce it running Tutorials/Road Traffic/models/Model 03.gaml 

This is what I get (some people are under the building)

I am quiet sure it was not the case before 

<img width="1086" alt="screen shot 2017-09-07 at 17 50 10" src="https://user-images.githubusercontent.com/3928502/30186802-0937eb20-93f5-11e7-95ae-4cb2042a5830.png">

**Comment by AlexisDrogoul** [comment]
Should be fixed by https://github.com/gama-platform/gama/commit/9dc3ecdac294595cb7c475e745672a12ac0b0768

**Comment by agrignard** [comment]
I have the feeling that there is still this problem. I just realive an old model that use to work and I get again this strange behavior where I cannot see the agent (as they are on the same pplan). On this specific model the agent are displayed on top of a grid so it might have been fix for different species layer but not for the case where we have agent on top of a grid in opengl?

**Comment by AlexisDrogoul** [comment]
A feeling about an old model is probably not enough. Can you share a model where this behaviour can be consistently reproduced ?

**Comment by agrignard** [comment]
Well I say a feeling but yes for sure it was working before (on the RC1)

So here is the code
[CityGamatrix.zip](https://github.com/gama-platform/gama/files/1427863/CityGamatrix.zip)

You can just import this folder and then just run CityGamatrix_PEV.gaml (there is another problem (we used to make it worked in GAMA RC1) so the simulation is not running) but you can see the white point are not all displayed at the init. 

If you put
species pev aspect:base position:{0,0,0.001} then it's ok I guess it just a question of grid no?

The only thing I display is a grid and a species

species cityMatrix aspect:base;
species pev aspect:base;

**Comment by AlexisDrogoul** [comment]
Hmmm.. They appear on mine.

![simulation citygamatrix_pev_model display - features agent movement models goto directed graph gaml - gama runtime 2017-10-31 23-18-49](https://user-images.githubusercontent.com/579256/32235510-3e927cd2-be92-11e7-8ab5-a0695919a352.png)

**Comment by agrignard** [comment]
Ok sorry I thought I was using the lastest build (as I did an update from the GUI) but not.

So yes I can see them also with the latest build from the website. Sorry for the noise
