### ISSUE TITLE
headless mode over batch experiment

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#2229]
### Steps to reproduce
1. Use a simple batch model, i.e. : 
<details>
<summary>test_headless.gaml</summary>

    /**
    * Name: testheadless
    * Author: robin
    * Description: This model displays an awesome simulation of something 
    */

    model circle

    global
    {
        string experiment_type <- "gui";
        string param1 <- "A";
        int param2 <- 1;

        reflex blob {
            write(param1 + param2);
        }
        
        reflex stop_sim when: cycle >= 0{
            if (experiment_type = "batch"){
                do halt;
            } else {
                do pause;
            } 
        }

    }

    experiment gui_exp type: gui
    {
        parameter "experiment_type" var: experiment_type init: "gui";
        parameter 'Param 1' var: param1;
        parameter 'Param 2' var: param2;
    }

    experiment batch_exp type: batch repeat: 2 until: cycle >= 0
    {
        parameter "experiment_type" var: experiment_type init: "batch";
        parameter 'Param 1' var: param1 among: ["B","C"] init: "B";
        parameter 'Param 2' var: param2 among: [2, 3] init: 2;
    }
        
</details>
<hr />

2. Create the corresponding headless mode file, i.e. : 
<details>
<summary>test_headless.xml</summary>

    <?xml version="1.0" encoding="UTF-8"?>
    <Simulation id="2" sourcePath="/home/robin/Dropbox/1_These/Modélisation/GAMA/test_TR8/models/test_headless.gaml" finalStep="1" experiment="batch_exp" seed="3">
      <Parameters>
      </Parameters>
      <Outputs>
      </Outputs>
    </Simulation>
</details>
<hr />

3. Run the headless model : `$ ./gama-headless.sh samples/test_headless.xml samples/outputs`

### Expected behavior
As in gama platform (gui), this should display : 

    B2
    B2
    B3
    B3
    C2
    C2
    C3
    C3

### Actual behavior
The init (global) value is still used, resulting in this output (in the headless console) : 

    A1
    B2
    B2
    B3
    B3
    C2
    C2
    C3
    C3

When setting `repeat:` facet (in experiment) to 2, it will run this model ("A1") twice.

This means that the simulation is executed "once" more with the initial parameters values.
When running like 100 replications of a model, that mean that 100 run will be made for an unwanted configuration.

I know that the preferred experiment mode for headless is `gui`, but I have experiment plans already built as batch modes plans, and I'd like to be able to run them on an external server without GUI.

### System and version 
Gama git (today's), with JDK 1.8, and this bug affects gama for months.

**Comment by AlexisDrogoul** [comment]
Hi,

I admit I have a very limited expertise on the way the headless mode invokes experiments. It seems in this case it does not respect the fact that the experiment is a batch one (while nevertheless using the correct parameters to run different simulations *after* the initial simulation).

I will try to see what happens under the hood.

Cheers
Alexis

**Comment by AlexisDrogoul** [comment]
Hi, I've just committed a possible fix for this odd behavior. Can you check if it works ? Thanks.

**Comment by RCura** [comment]
It doesn't :cry: 

`Exception in thread "Thread-7" java.lang.NullPointerException
	at msi.gama.headless.job.ExperimentJob.play(ExperimentJob.java:261)
	at msi.gama.headless.job.ExperimentJob.playAndDispose(ExperimentJob.java:244)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:206)
`

Tried with compiling from this commit, but also with latest git commit. Always get this Thread-7 error.

**Comment by RCura** [comment]
Just checked the preivous commit (eccc8e5e9cd1a5c695f75cbdec0682417a03e9ad), and it "worked" : no error running, but the same issue as described in the thread :)

So, this small change corrupt the whole headless mode unfortunately.

**Comment by AlexisDrogoul** [comment]
OK. I havent seen that the ExperimentJob depends on the availability of a simulation scope to evaluate the running conditions. I've pushed another trial. Can you please try it ?

**Comment by RCura** [comment]
Number of cpus used:4 (available: 4)
    Simulation is running...
    .B2
    B2
    B3
    B3
    C2
    C2
    C3
    C3

    Simulation duration: 76ms

Bingo, congratulations and thanks a lot Alexis ! :tada:

**Comment by AlexisDrogoul** [comment]
You're more than welcome. Only problem is that the patch I have made is not really pretty. Anyway... Thanks for your patience !
