### ISSUE TITLE
Modifying points_on

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2231]
Hi,

I would like to request a modification for the points_on operator. 

I want to add points on a graph (although this could be any geometry) with a given list of locations. These locations are expressed between 0 and 1, where: 0 is the starting point of an edge and 1 is the ending point of that same edge. So If I give a list [ 0.2,0.63,0.87], the operator should be able to put points on these locations on the corresponding edge. 

Currently I think it is possible to use points_on for geometries but not a graph. 

I want to be able to change - during the simulation - the number of items in the list and of course the values of the items in the list. 

The idea is to create dynamic obstacles on the path of an agent.

Thank you

**Comment by ptaillandier** [comment]
Hi,

There is an operator called points_along that seems to do what you want (but not sure). Here an example:

model pointsAlong
global {
	geometry the_line;
	list<point> list_of_points;
	list<float> wanted_points <- [ 0.2,0.63,0.87];
	
	init {
		the_line <- line([{10,10},{80,50}]);
		list_of_points <- the_line points_along wanted_points;
	}	
}

experiment pointsAlong type: gui {
	output {
		display map {
			graphics "visu" {
				draw the_line color: #black end_arrow: 4;
				loop pt over: list_of_points {
					draw circle(1) color: #red border: #black at: pt;
				} 
			}
		}
	}
}

**Comment by sriramab** [comment]
Hi, Would this work on a graph? I want to place points on a graph (road)

**Comment by ptaillandier** [comment]
If you just want to compute the list of points for one or several edges, yes.
For example:
loop e over: the_graph.edges {
	list_of_points <- list_of_points + road(e) points_along wanted_points;
}

**Comment by AlexisDrogoul** [comment]
I guess the question has been answered. I close this one (reopen if it is not the case).
