### ISSUE TITLE
Moving skills with or without shape

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2233]
Don't know if it's an issue or an enhancement.

I just notice a big difference in term of simulation speed when using

```
do goto target: the_target on: road_graph ; 
```

There is a big difference if the agent has a shape or not (fast if no shape , slower if I defined something like shape<-circle();)

I kind of understand why but for the moving skills I don't see exactly how come the shape has an impact of the computation

**Comment by AlexisDrogoul** [comment]
Well, there is an impact of course in terms of the basic computations involved in the translation of the points composing the shape. The less points you have (i.e. if you dont define a shape, the shape of the agent is simply a point) the less computations are made when changing the coordinates. A circle is defined by something like 32 points (didn't check) so the change in coordinates (and envelope, etc.) is likely to be 32 times slower at most. It needs to be verified by more rigorous experiments, though (i.e. does a square shape make the move 4 times slower ?). The computation of the new location of the agent is also involved here, as, for a point, it is straightforward (i.e. the location is this point) while, for more complicated shapes, it needs to be computed as the mass center of the envelope (involving the computation of the envelope first, which is linear in terms of the number of points defining the shape).

**Comment by AlexisDrogoul** [comment]
Closing this one as it is more a question (to which I hope I answered above).
