### ISSUE TITLE
Gama Update from the GUI

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2234]
It seems that there is a problem when trying to update GAMA from the GUI.

It's possible to select the different update but once you click on Finish nothing happens.

**Comment by hqnghi88** [comment]
Hi, It seem to have problem again with ovh. I check tomorrow at lab cause i
dont have internet now.

-------
HUYNH Quang-Nghi
Ph.D.
Lecturer
GAMA http://gama-platform.org/
College of Information and Communication Technology - Can Tho University
Campus II, 3/2 street, Ninh Kieu district
Can Tho city, Vietnam
[Vietnam] +84909128322

**Comment by AlexisDrogoul** [comment]
Any update on this one ? Is OVH still down ?

**Comment by hqnghi88** [comment]
I've just tried but it seems still down, it dropped at downloading gama.ext package (46mb) . As far as i know if some package is corrupted when downloading, the update progess fail. I follow this issue.

**Comment by hqnghi88** [comment]
The second try have successful. So the packages on server are good. Just the connection/downloading is the cause.

**Comment by AlexisDrogoul** [comment]
I think we can close this one in favour of #2235 (which is the cause of this behaviour).
