### ISSUE TITLE
Re-organize features in order to not reload gama.ext each time

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2235]
### Steps to reproduce
1. Relating with the issue #2234 and for several months worked on "self-update progess" of GAMA (an eclipse application)

2. When update (in eclipse / Gama) or do maven build, if a required plugin is dropped (by disconnecting/ lagging/ server timeout) , the whole process will be stopped with/sometime without notifications.

3. In addition, most of package/plugins imported in gama.ext can be found in maven repository, so they can be downloaded automatically when building with travis. 

### Expected behavior
So, i would like to request an re-organization of gama.ext, to: decrease the size of must-download packages when updating, decrease the size of release package, make the updating progress more consitently.

### System and version 
Gama git

**Comment by AlexisDrogoul** [comment]
Ideally, we should have something like #146 already implemented (for the build). 

Regarding the online updating, would moving plugin `msi.gama.ext` from the feature `ummisco.gama.feature.core` to `ummisco.gama.feature.dependencies` change something ? 

The thing is that `ummisco.gama.feature.dependencies` does not change very often (and I hope it is not rebuilt and proposed for every commit), while `ummisco.gama.feature.core` changes a lot. Moving `msi.gama.ext` to the first one would then normally prevent it to be downloaded everytime something changes in the core.

**Comment by hqnghi88** [comment]
Sorry but i think ummisco.gama.feature.dependencies is built and uploading to ovh. I did not limit some  special packages. Moving the gama.ext may be a solution. In fact , I hope to decrease the size of ext by divide in several small packages or use a maven dependency for these plugins in gama.ext (most of them are geotools?)

**Comment by AlexisDrogoul** [comment]
What you mean is that `ummisco.gama.feature.dependencies` is built (and its version upgraded) each time we do a commit (i.e. each time travis builds a version) ? Is there a way to check if there is a change in a feature or not ? Or maybe we could move `msi.gama.ext` to the dependencies and build the dependencies only when, either, it is not built yet, or a special directive in the commit message tells so. Do you think it could be possible ?

**Comment by AlexisDrogoul** [comment]
Any comment on this, @hqnghi88  ?

**Comment by hqnghi88** [comment]
i take a careful test tomorrow for the "deploy on any changes". i have impression that now they are depend on the file name (all of them are 1.7.0.timestamp) so it means there is everytime new changes

**Comment by AlexisDrogoul** [comment]
So maybe we could simply (1) move `msi.gama.ext` to `ummisco.gama.feature.dependencies`; (2) remove the timestamp from the version number of this feature; (3) document the fact that to rebuild dependencies, one has to increase the version number ?

**Comment by hqnghi88** [comment]
https://cwiki.apache.org/confluence/display/MAVEN/Maven+3.x+Compatibility+Notes#Maven3.xCompatibilityNotes-Non-uniqueSnapshotDeployments
mentioned that we cannot remove timstamp. I trying with a script to check that build ext only when it had been changed.

**Comment by AlexisDrogoul** [comment]
Hmm.. I dont really see the relationship between your link and what we do. What prevents us from removing the `-SNAPSHOT` from the version number for `msi.gama.ext` ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Maven 3 do. It prevent us to remove the -snapshot.timestamp. I can't have a fixed version , i.e msi,gama.ext.1.7.0.jar .but i'm trying with shell script to build ext only when it was changed .

**Comment by AlexisDrogoul** [comment]
To be clearer, what prevents us from defining the `pom.xml` of `ummisco.gama.feature.dependencies` like this (see image) ?

![java - ummisco gama feature dependencies pom xml - eclipse - users drogoul documents eclipse 2017-09-26 17-30-19](https://user-images.githubusercontent.com/579256/30855883-b12a99be-a2e0-11e7-8896-6b1584029a74.png)

**Comment by AlexisDrogoul** [comment]
The update works on features, not individual plugins. `msi.gama.ext` is a plugin, included in `ummisco.gama.feature.core` for the moment. The idea is (1) to move it to `ummisco.gama.feature.dependencies`; (2) to freeze the version number of this feature so that it is not considered as "new" by the update mechanism. Basically, we do not care if Tycho/Maven/Travis rebuilds it or not, we just need the update mechanism to not consider it. So that's why I'm wondering why we can't just do what I propose (there may be other problems I am not aware of, of course).

**Comment by hqnghi88** [comment]
Dear Alexis,
I can't launch a mvn install with the "1.7.1"
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.25.0:validate-version (default-validate-version) on project ummisco.gama.feature.dependencies: Maven version 1.7.1 must have -SNAPSHOT qualifier for SNAPSHOT builds -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ummisco.gama.feature.dependencies

**Comment by hqnghi88** [comment]
Dear Alexis,
(1) to move it to ummisco.gama.feature.dependencies: because dependencies is not change too much so we move ext to dependencies, is it the reason?
(2) "to freeze the version number of this feature so that it is not considered as "new" by the update mechanism. Basically, we do not care if Tycho/Maven/Travis rebuilds it or not, we just need the update mechanism to not consider it" : the freezed version as  you said would be 1.7.0 (without the timestamp). The problem is tycho/maven prevents to have that kind of artifacts, it add everytime a suffix (maybe i missed or did not understand somewhere).

**Comment by AlexisDrogoul** [comment]
Nghi,

(1) Yes. This feature changes every 6 months or so (with new versions of libraries). 
(2) Well, maybe it means it should be built outside the "train" of the other plugins (because the parent imposes a snapshot). Like we do for the processor ?

**Comment by hqnghi88** [comment]
yes yes, im doing it. Thanks.

**Comment by hqnghi88** [comment]
I have successful several time of update with fixed version of dependencies feature, meaned that msi.gama.ext have not to be downloaded everytime. It still need more test with cron release.

**Comment by AlexisDrogoul** [comment]
Well done ! By the way, it would be a good thing to add a page to the wiki explaining how to commit with the different options: 

- fixes #xxxx : closes an issue
- ci aaaa : do something
...
etc.

For the moment, I guess you are the only one to use them...

**Comment by AlexisDrogoul** [comment]
And `ci` might not be the best choice of keyword (who can remember it ?). 

What about a small vocabulary with $ hashtags ? 

$update [doc | ext ] ==> forces the recreation of docs or external libraries
$clean ==> ?
$deploy ==> forces the deployment of the p2 repository

are there others ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Yes, sure, we can you more friendly vocabulary, the ci come from travis, it use "ci skip" to skip a build.
Actually, i have ci cron, ci clean, ci deploy, ci docs, ci release, ci ext . In addition, if we forgot to use these intruction in the commit message, we can add a environment variable of travis named "MSG" with the value is a string that contains these vocabulary "  ci cron, ci clean, ci deploy, ci docs, ci release, ci ext ".

**Comment by hqnghi88** [comment]
By the way, do you think that we can apply the same strategy for other plugins, they would be built only when they are changed. It will decrease the size of update stream and also increase the sucess rate.

**Comment by AlexisDrogoul** [comment]
Nghi, if this is automated, yes, why not. But only if we have a reliable way to know whether they are effectively changed or not. Otherwise, if we need to tell Travis each time, it would be too complicated...

**Comment by hqnghi88** [comment]
Dear Alexis,
It's not effectively because i use string comparisons. but this is automated by travis if a commit contains a plugin's modification. we dont need to tell Travis manually.

**Comment by AlexisDrogoul** [comment]
Hi Nghi,

If you think it is possible, then, yes, it would be a very good idea. Re-building only the modified plugins and deploying only them makes a lot of sense. 

Alexis

**Comment by AlexisDrogoul** [comment]
Hi Nghi,

Meantime, can we consider this issue to be closed ? I've used the manual build several times and it seems to work fine (however I've not played with changing the dependencies...).

Alexis

**Comment by hqnghi88** [comment]
Yes, as shown by travis, the dependencies stay forever at 27/september, farewell ext.
Installing ummisco.gama.application.product 1.7.0.201710010106.

Installing ummisco.gama.feature.core.ui.feature.group 1.7.0.201710010106.

Installing ummisco.gama.feature.core.extensions.feature.group 1.7.0.201710010106.

Installing ummisco.gama.feature.core.feature.group 1.7.0.201710010106.

Installing ummisco.gama.feature.dependencies.feature.group 1.7.0.201709270747.

Installing ummisco.gama.feature.models.feature.group 1.7.0.201710010106.

Installing ummisco.gama.feature.core.ui.feature.group 1.7.0.201710010106.

Installing ummisco.gama.feature.experiment.ui.feature.group 1.7.0.201710010106.

Installing ummisco.gama.feature.modeling.ui.feature.group 1.7.0.201710010106.
