### ISSUE TITLE
[Co-model] Create several instance of the same sub-models and display them

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2236]
### Steps to reproduce
1. I consider a simple weather model, with a single grid species plotWeather.
Files can be found here:
[Co-models.zip](https://github.com/gama-platform/gama/files/1299456/Co-models.zip)

2. I build a co-model, instantiating 3 simulations of this weather model.

import "weather.gaml" as weather

global {
init {	
		create weather.weather_coModeling number: 3 {
			write "" + int(self) + " " + self;
		}

		write "";
 		write "**** Display set of simulations ****";		
		write "" + weather.weather_coModeling collect each.simulation;
		write "" + weather.weather_coModeling accumulate each.simulation;	

 		write "**** Display set of agents ****";
		write "" + weather.weather_coModeling accumulate (each.simulation.plotWeather);
		write "" + weather.weather_coModeling collect (each.simulation.plotWeather);
	}
}

3. When I want to display all the simulation created, I used:
		write "" + weather.weather_coModeling collect each.simulation;

### Expected behavior
I was expected to have a list of all the simulations, such as:
[weather_model(0),weather_model(1),weather_model(2)]

### Actual behavior
Instead I get a list with the the first simulation, 3 times:
[weather_model(0),weather_model(0),weather_model(0)]

### System and version 
GAMA continuous built
MACOSX

**Comment by hqnghi88** [comment]
Dear Benoit,
Just to be sure, may be it was an ambiguous in naming, the 3 times:
[weather_model(0),weather_model(0),weather_model(0)] 	
are 3 simulations of 3 experiments (weather_coModeling(0)(1)(2)).

if you want to create more simulation in experiment, i think we can do this:
		create weather.weather_coModeling number: 3 {
			write "" + int(self) + " " + self;
			create world number:2;
		} 

in that case, we can have the result of 
		write "" + weather.weather_coModeling collect each.simulations;
[[weather_model(0),weather_model(1),weather_model(2)],[weather_model(0),weather_model(1),weather_model(2)],[weather_model(0),weather_model(1),weather_model(2)]]

It means 3 simulation in each experiment (we have 3 experiments).
What do you think?

**Comment by benoitgaudou** [comment]
Hi Nghi,
Thanks for your answer.
I start to understand the co-modeling, and I think you are right and I made a confusion between experiment instances and simulations.
So definitely not an issue.

Cheers

Benoti
