### ISSUE TITLE
[Co-model] high-level spatial operators (inside, overlaps...) and co-modeling

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2239]
### Steps to reproduce
1. I have 2 models (weather and plantGrow), each of them with a grid (plotWeather - with a rain attribute- and plotGrow).
I write a third co-model integrating these 2 models.
plotWeather cells are larger than plotGrow, and I want in my model that a plotWeather "gives" its rain water to all the plotGrow cells below it (see coModel2.gaml attached).

2. To this purpose, I wrote the following global block.

```
import "weather.gaml" as weather
import "plantGrow.gaml" as plantGrow

global {
weather weather_simu ;
plantGrow plantGrow_simu;

init {
create weather.weather_coModeling with: [grid_size::20,write_in_console_step::false];
weather_simu <- first(weather.weather_coModeling).simulation;
create plantGrow.plantGrow_coModeling with: [grid_size::40];
plantGrow_simu <- first(plantGrow.plantGrow_coModeling).simulation;
}

reflex simulate_micro_models_weather {
ask weather_simu { do step; }
}

reflex coupling {
ask weather_simu.plotWeather {
overlapped_plots <- myself.plantGrow_simu.plotGrow where (each.shape.location overlaps self);

ask overlapped_plots {
	available_water <- available_water + myself.rain;
}
}
```

### Expected behavior
To compute the plotGrow cells below the plotWeather, in a *not* comodel, I can write: 

list<plotGrow> overlapped_plots <- myself.plantGrow_simu.plotGrow inside self;

but in a comodel, it does not work (returning an empty list), which is not intuitive.

### Actual behavior
I have to use something like:
overlapped_plots <- myself.plantGrow_simu.plotGrow where (each.shape.location overlaps self);			

### System and version 
GAMA continuous built
MACOSX

**Comment by AlexisDrogoul** [comment]
I would say this behaviour is effectively counter-intuitive but normal: imported models do not share (to my knowledge) the same spatial index, hence the results...

**Comment by benoitgaudou** [comment]
So could it be possible to at least display a warning to express the fact that the index is not shared (at the compilation step or at runtime) ?

**Comment by AlexisDrogoul** [comment]
Just a comment: please use the mark ````` before and after lines of code to display them properly (otherwise it is sometimes difficult to read the issue).

**Comment by AlexisDrogoul** [comment]
A solution would be, at the creation of the simulation agents corresponding to the micro-models, to attach them to the spatial index of the macro-model simulation agent. Right now, each of them recreates a RootTopology with its own CompoundIndex, maybe we should try to share the same RootTopology at creation time ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Ok for the solution, i will try to understand the "topology" and implement it. Btw, how about : using topology(world)  or topology(micro-simulation) to tell operators to use such topology?

**Comment by AlexisDrogoul** [comment]
Hum... It will not be at the GAML level that this mix of topologies needs to be done, but in Java. Basically, we want to tell new simulations to merge their spatial index with the spatial index of the macro-model and add the other spatial indexes they manage (grids, graphs, etc.) to the compound spatial index of the macro-model. Sorry if this is not clear :) I will try some solutions and come back to this thread later.

**Comment by hqnghi88** [comment]
yes, i imagined something must be merged, so i proposed to use using(topology) to explicitly tell simulation use which topology, i think, but may be it is more complicated.

**Comment by AlexisDrogoul** [comment]
I have coded a "fix" for this, which allows micro-simulations to merge their topology within the topology of the macro-simulation. It works well and effectively enables macro/micro simulations and their populations to use the geometric operators. 

Now, I havent committed it yet, as I have two concerns:

- when simulations get disposed, they dispose their topology, which is a bad idea in that case (as micro-simulations would dispose the macro-topology). How can I avoid this ? i.e. is there a test that enables me to know whether a simulation is a micro-simulation or not ? 

- the results are unexpected when the sizes of the different environments (i.e. the shapes in which the topologies are defined) are different. To be frank, I havent tested it yet, and I wonder what would happen if you merge a micro-model in a 1000x1000 environment into a macro-model  with a 10x10 environment...

**Comment by hqnghi88** [comment]
Dear Alexis,
1. it is not effectively method to check directly a microsim, but hiw about
sim.getDescription().belongstoamicromodel()
2. for the representations of different size of environments, currently i
just have scaled the size of geometries. i did not test with such pure
environment s transformations, but is there anyway a translate or transform
method to scale the micro-env (may be to the macroenv size)?

**Comment by AlexisDrogoul** [comment]
OK. The exact sentence is `sim.getSpecies().getDescription().belongsToAMicroModel();`. 

Regarding the size of the environment, I dont understand your answer: do you scale the micro-simulations or not ? It does not seem to me that any scaling is performed (I didn't find any) but maybe I missed the portion of code responsible for it. Can you tell me where it is ?

**Comment by hqnghi88** [comment]
Dear Alexis,,
No, i mentin. the representation, it mean that i just play on gaml, i ve
done nothing in java.


On Sep 25, 2017 18:16, "Alexis Drogoul" <notifications@github.com> wrote:

OK. The exact sentence is sim.getSpecies().getDescription().
belongsToAMicroModel();.

Regarding the size of the environment, I dont understand your answer: do
you scale the micro-simulations or not ? It does not seem to me that any
scaling is performed (I didn't find any) but maybe I missed the portion of
code responsible for it. Can you tell me where it is ?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/gama-platform/gama/issues/2239#issuecomment-331850649>,
or mute the thread

**Comment by AlexisDrogoul** [comment]
Ok. I've committed the fix. But please keep in mind that, although it automatically merges the grids, it may create end up in odd behaviours for co-models that create two times the same simulation (with grids) or co-models with micro-models with completely different environment sizes. Please open separate issues for these cases -- and, by the way, the commit can be reverted quite easily, so no worries if the issues it generates are too much of a burden.

**Comment by AlexisDrogoul** [comment]
I am testing a more interesting strategy, by the way, which eliminates the first of the last comment: instead of indexing the spatial indexes by species, I index them by population (because 2 micro-simulations will share the same species, but 2 different corresponding populations). I need to test it a bit more deeply but it seems to work well.
