### ISSUE TITLE
[enhancement] being able to open a previous workspace with newer version

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#224]
**Is your request related to a problem? Please describe.**
Almost every time we publish a new version, or even just a newer alpha, the previous workspace is broken and the user have to create a new one. 
This is already a bit weird for most users and a bit frightening as they may think they corrupted data or something similar. But on top of it the whole user interface is broken and there's no indication that it is just a workspace problem, which makes many people think the problem is gama itself being broken.
As now we have a pretty regular release cycle, this problem happens more and more and I think it would make sense to solve this problem.

**Describe the improvement you'd like**
I don't know if it's possible but if there's a way to detect if we have that workspace issue in gama we could popup a window to ask if the user wants to "update" the workspace, or at least that everything is going to be broken and they should create a new one. Technically I think there's already such a popup but seems like it's not really working.
To be honest I don't even understand why all the user interface breaks, are there any jar dependencies of gama in the workspace ? If so, why doing this instead of packaging it in gama ?

**Describe alternatives you've considered**
A workaround would be to propose a default workspace name containing the gama version number, it would then be incremented for each version and people would more naturally bring their work from one workspace to another. But this doesn't really solve the base problem.

**Additional context**
People ask me all the time why their gama is broken (and probably waste some time trying to make it work)

**Comment by AlexisDrogoul** [comment]
I do not have this problem on macOS when I change version. The regular popup appears, asking whether I want to use a workspace created with an older version. What do you mean by "everything is broken" ? Are there more specific examples ?

**Comment by lesquoyb** [comment]
We do have this problem on macos too, I experimented it this morning on the mac mini :) 
I opened a workspace made in gama 1.9.3 with the latest alpha 2024-06 and the gui looks something like this:
![image](https://github.com/gama-platform/gama/assets/6374469/d9621888-fcd9-4a0b-974d-7fbffdd7da76)
If you find ways to close each view (project explorer, the text editor, the consoles etc.) and manually reopen them, it works as expected, but if you just restart gama on this workspace it will reopen with the same broken UI

**Comment by AlexisDrogoul** [comment]
Should be fixed (at least improved by https://github.com/gama-platform/gama/commit/d3622fdf389743528a8263b08332c3ea6e5ba00d). Please test !

**Comment by AlexisDrogoul** [comment]
By the way, have you observed this behavior recently between versions *after* 1.9.3 ? When one looks at the traces, it is easy to spot numerous errors (files not found, mainly) that begin with `plugin/ummisco.gama.ui.shared/...`, which was the path to the plugin in GAMA 1.9.3 (the new path is `plugin/gama.ui.shared/...`). It seems that the UI bugs come from this.
