### ISSUE TITLE
Display idea for helping agent behavior debug

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#2240]
Hi, 

I see on some gamedev twitter account an interesting idea to helping debug ABM by displaying extra information at "time t" for each agent : 

[img](https://j.gifs.com/P1XMV2.gif)

**Comment by AlexisDrogoul** [comment]
Well, interesting idea, already used in one of the "ants" models (where only the current state of the ism is displayed). The problem with this is that it cannot be easily automated: the level of details to show of the current stack of actions, which arguments of the actions to display, etc. are completely dependent on the level of details a user would want to display. And, in that case, building a dynamic string during the execution of the agent with this appropriate information and displaying this string near the agent is probably enough. We might add an example model on how to do it properly, maybe.

**Comment by AlexisDrogoul** [comment]
Not solved, but moved as a reference to a more general issue raised in #2261 -- i.e. fixing #2261 will require writing example models on the position of strings, one of which will likely include a representation like the one proposed here.
