### ISSUE TITLE
left-click on the display of a hexagonal grid (displaying a grid and the grid as a species) does not work

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2247]
### Steps to reproduce
1. I have an hexagonal grid, and have defined in it an aspect to draw the value of an attribute.
model testHexa

global {}

grid plot height: 11 width: 11 neighbors: 6 {
	int nb_road;
	
	aspect nbForest {
		draw ""+nb_road size: 10 color: #black;
	}
}

experiment testHexa type: gui {
	output {
		display d2  {
			grid plot lines: #black transparency: 0.7;
			species plot aspect: nbForest;	
		}			
		display d  {
			grid plot lines: #black transparency: 0.7;
		}
	}
}

2. On the display d2 (with the display of the plots as  grid and as a species), I try to let-click on a plot. 

### Actual behavior
The left-click does not work on the display of the plots as  grid and as a species, whereas it works on the display with only the grid. Moreover, the button to display all the species (on top of the display) does not work.
Notice that when we change the neighorhood number to 4 or 8, this issue does not appear anymore.

In addition, when I use an opengl display, it seems that in the d2 display I can click on the plot, but the button to display all the agents does not work.

### System and version 
GAMA Continuous Built
MACOSx

**Comment by ptaillandier** [comment]
fixes with my last commit
