### ISSUE TITLE
SQLITE connection false

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2250]
### Steps to reproduce
From [gama (6176)] 
@ LESCALIER Bruno 
"Hi,

I try to connect to sqlite database. For that I use the simple  example. (see attached model).
But the connection to sqlite is false.

I work on W10, with GAMA 1.7 (release candidate)

Thank you very much for your help!

Cheers

Bruno "
[sqlite_test.zip](https://github.com/gama-platform/gama/files/1325176/sqlite_test.zip)

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Any news on whether the commit solves the problem ?

**Comment by hqnghi88** [comment]
An addition step is : "For the spatialite on windows 10, i must set the Path in system environment to point to the directory that contains the mod_spatialite.dll . Then in preference- External tab, point to this dll also."
I am not sure about the environemnt in other OS.

**Comment by hqnghi88** [comment]
Dear Alexis,
I have sent email to Bruno. It worked on my win but with some specific configurations.

**Comment by benoitgaudou** [comment]
I just tried on MACOSX, preRelease 1.8, and the model works perfectly.
It was due to the fact that GAMA tried to import the spatiallite database, even if it was not on the system.
