### ISSUE TITLE
POSTGRES BOUNDS query

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2251]
### Steps to reproduce
From [gama (6171)]
@ 
1.

Database containts juste coordinates (srid'::'4326') of point.

    For the moment I want juste create one agent with this query :
     "select ST_AsBinary(geom) as geom from ais_iroise_gama where mmsi = 205359730 order by date limit 1"

    As you see, I get just one row.

First, I try to create boundary of area. I do :
map<string,string> BOUNDS <- [ 'srid'::'4326','host'::'192.168.129.135','dbtype'::'postgres','database'::'ais','port'::'5432','user'::'postgres','passwd'::'postgres','select'::'select ST_AsBinary(geom) as geom from ais_iroise_gama;'];
follow by
geometry shape <- envelope(BOUNDS);

In the init section I check the size of the bound, and the result is : POLYGON ((0 100, 100 100, 100 0, 0 0, 0 100))
For me, it is the default size give by GAMA.

Of course, the size is good if I use a shapefile.

Second, I try to get coordinates in order to create a specie. I do  :
create ais from: list(self select(params: PARAMS, select: query)) with:['shape'::geometry("geom")];
I have : 2 occurrences in 2 agents at cycle 0: Java error: nil value detected

OR

create ais from: list(self select(params: PARAMS, select: q)) with:['shape'::"geom"];
I have : 2 occurrences in 2 agents at cycle 0: Java error: wrong casting

2.

3.

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Any news on whether the commit solves this issue ?

**Comment by AlexisDrogoul** [comment]
Any updates on this bug ? I have absolutely no clue about what happens (or not) in the database plugin... Can someone take a look ? @gama-platform/committers @truongminhthai

**Comment by benoitgaudou** [comment]
I can have a look on all the 2 or 3 bugs related to databases ... but not
before the next Coding Camp.
Benoit

2017-10-31 18:49 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Is this bug fixed by the recent commits on DB ?

**Comment by hqnghi88** [comment]
Yes, it was. The issue fixed for  simple data, for more complex gis data (3d data,...) an example model has been added to show how to use sql to handle such kind of data. 
Please feel free to reopen if it still happens
