### ISSUE TITLE
Remove the warnings in some models in library 

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2252]
### Steps to reproduce
1. I found this warning in some models in library
No unit provided. If this frequency concerns cycles, please use
   the #cycle unit. Otherwise use one of the temporal unit (#ms,
   #s, #mn, #h, #day, #week, #month, #year)
2. It mostly come from the display with
 refresh: every(xxx#cycle)
3.

### Expected behavior
Could we remove them ( i have more than 10 warns)?

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Gama git

**Comment by AlexisDrogoul** [comment]
The warning is here for a reason: `every` now takes an exact time as its argument, and the unit of time needs to be set. What I dont understand is that you should not have it with `refresh: every(xxx#cycle)` (I don't as a matter of fact). Are you sure it happens in these cases ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Sorry, it disappear with new clean workspace. 
Thanks.
