### ISSUE TITLE
dynamic bins of a container

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2253]
Hi,

I have looked at the manual and could not find a suitable operator. Please correct me if I am wrong.

I want to split (bin) a float list based on user input using the parameters view. That is, I hope to have a dropdown menu (or other user input boxes) where user can select a bin size, and this should then be applied to a float list. An example is step size, sometimes we want to analyse with a step size ranging from 15 min 20 min 30 min or 60 min. 

I am not sure how this is possible with current set of operators.

currently, we are just reading a preprocessed csv of different intervals, like 15min.csv, 20min.csv etc. 

Is there any operator to do this binning? Else I would like to request  an operator something available in many statistical software where you can select number of bins and breaks of a bin.

Thanks.

**Comment by ptaillandier** [comment]
Hi,

Did you test the distribution_of operator:
list<float> list_floats <- [2.0, 3.0, 1.0, 5.5,8.0, 10.0, 3.9, 2.9,1.4];
write distribution_of (list_floats, 4);

Not sure that it exactly does what you want though.

Cheers,
Patrick

**Comment by AlexisDrogoul** [comment]
Hum... I'm not sure to exactly understand what you want to achieve. Could you provide us with an "ideal" example of how this operator would work (let's call it `split`) ?

**Comment by sriramab** [comment]
Hmm. It is more or less like creating a histogram. 

- Lets us assume we have a list of 100 float numbers, lets say using the `rnd()` we generate these 100 numbers, so they are between 0.0 and 1.0 . 
- Now I want to make a frequency table with breaks defined by a vector/list such as : `[ 0.2, 0.4,0.8,1.0]`. the elements inside this vector form the upper bounds of the bins. So here the bins are (1) 0 to 0.2 (2) 0.2 to 0.4 (3) 0.4 to 0.8 (4) 0.8 to 1.0
- For each given bin, I would like to count how many of the 100 numbers are within each bin.
- So the function returns a list of values (counts/frequencies) in each bin.

The other option (usually in other software) is to state number `n` of preferred bins. This assumes we want equal interval bins of number `n`

Use case: I have a list of observed values that I do not wish to go into deep statistics to understand all the moments of their distribution. But just simply get a quick frequency table. And quickly use this frequency table as input to `sample()` function as its `probability or weight`  argument. 

So lets say, we use 

```
list dummy_observation <- list_of_hundred[uniformly_distributed_rnd_numbers];
frequency_4_groups <- split(dummy_observation,4) // split( container, int)
frequency_manual_groups <- split(dummy_observation, [0.25,0.5,0.71,1]) // split(container, list)
``` 

I looked at the suggestion of Patrick, but it give a complex map variable as a result.

**Comment by AlexisDrogoul** [comment]
Well well. I'm a bit tired this morning, so sorry in advance for my stupid questions. Would it be possible that you give an example of the outputs you would like to obtain ? In the beginning, I thought you wanted to obtain a list of lists, split using the second argument (int or list<float>), but now it seems you need to get the number of elements in each interval ? In that case, the operator with an `int` parameter is more or less useless, isn't it ? 

I looked at `distribution_of` and I understand your perplexity, by the way. The documentation is absolutely *not* helpful. @pcaillou , did you write this part ? Would it be possible to get at least an example that makes sense ? 

Anyway, what I propose is to write an operators called `split_in`. Examples:

`[1,3,10,7, 22] split_in 4 => [[1,3],[10],[7],[22]]`
`[1,3,10,7, 22] split_in [1,5,30] => [[],[1,3],[10,7,22]]`

To obtain the count, you just need to iterate over it, like: 

`([1,3,10,7, 22] split_in [1,5,30] ) collect length(each) => [0,2,3]`

Would this answer your request ?

**Comment by sriramab** [comment]
Yes, I want to get number of elements in each interval. And your example is what I need. Usually there can be a second argument to `split_in` stating if or not upper or lower bound is included. Lets say we agree for upper bound and it looks like `split_in (container, container, true). 

in your example:

```
[1,3,10,7, 22] split_in ( [1,5,30] , true) => [[1],[3],[10,7,22]]
[1,3,10,7, 22] split_in ([1,5,30], false)  => [[],[1,3],[10,7,22]]
```

**Comment by sriramab** [comment]
As a reference, I would like you to refer to this (link) for an idea [https://www.rdocumentation.org/packages/graphics/versions/3.4.0/topics/hist] and the arguments : x, breaks, include.lowest, freq, right  in particular.

**Comment by AlexisDrogoul** [comment]
Another question: in the first case (i.e. with the number of bins passed as argument), should the `split_in` operator use *equal size* or *equal frequency* bins ?

**Comment by sriramab** [comment]
Hmm. I do not think having equal frequency helps, because idea is to draw probability. 
If not integer is provided then a rule of thumb  is as follows, bins(k) rounded to nearest integer `k=1+3.3*log<sub>10</sub>n` n=number of samples. 
If an integer is provided, then it is equal sized.

**Comment by AlexisDrogoul** [comment]
OK. I've made a first implementation of three operators: `split`, `split_in`, `split_using`. 

```
		list<float> samples <- [1,5,2,25.0,12, 100, 34, 13];
		write sample (split(samples));
		write sample(samples split_in 3);
		write sample(samples split_in (4, true));
		write sample(samples split_using [25, 38]);
		write sample(samples split_using ([25], false));
```

returns:

```
split(samples) -: [[1.0,5.0,2.0,25.0,12.0,13.0],[34.0],[100.0]]
split_in(samples,3) -: [[1.0,5.0,2.0,25.0,12.0,13.0],[34.0],[100.0]]
split_in(samples,4,true) -: [[1.0,5.0,2.0,25.0,12.0,13.0],[34.0],[],[100.0]]
split_using(samples,[25,38]) -: [[1.0,5.0,2.0,12.0,13.0],[25.0,34.0],[100.0]]
split_using(samples,[25],false) -: [[1.0,5.0,2.0,25.0,12.0,13.0],[100.0,34.0]]
```

I've normally taken care of abnormal parameters (empty bounds, etc.), and the result should be ok, but I let you test these new operators !

**Comment by sriramab** [comment]
Seems to be working. But why do you use the sample operator in your write statements?

**Comment by AlexisDrogoul** [comment]
Just to have a nicer log (if you look at the documentation of sample, it outputs both the expression and its results). 

I close it now, reopen if any problem !
