### ISSUE TITLE
Show an information tip when defining two reflexes with the same name

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2255]
### Steps to reproduce
1. In a species, when I define 2 reflexes with the same name, only the last one is executed.

### Expected behavior
Could it be possible to add an information tip expressing that a reflex has been redefined, or that 2 reflexes have the same name.
(in order to help modelers  to detect copy paste errors ... )

### System and version 
Gama continuous built MACOSX

**Comment by AlexisDrogoul** [comment]
It is already the case. Are you sure you havent deactivated the information marks ? 
![modeling - essai models bus gaml - gama runtime 2017-09-27 20-12-33](https://user-images.githubusercontent.com/579256/30915218-49bab4c2-a3c0-11e7-9a2e-86356d781f66.png)

**Comment by benoitgaudou** [comment]
Hi,
I made some more tests and you are right, it appears...
Sorry for that, it seems I was to deep in the model looking for errors to see this information...
