### ISSUE TITLE
update library not working

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2256]
After I updated GAMA from `Help>check for updates`,  It has erased my library models. I tried to `update library` from the context menu, but nothing was downloaded nor updated. 

I then downloaded continuous build of 27 Sep 2017, and it also does not have any models in the library, nor does `update library` downloads any models. 

Please could you check may be there is some missing link in the new builds?

MacOS Mavericks, GAMA Continuous build of 27.09.2017

**Comment by hqnghi88** [comment]
Hi Sriri,
I'm working on the update feature of gama, so it will be unstable for few days. But i 'm surprise that the downloaded release did not work. What is the exact name?

**Comment by sriramab** [comment]
Just now, 15minutes ago 
GAMA1.7_Mac_64_09.27.17_9116095.zip

**Comment by hqnghi88** [comment]
Hi Sriri,
I have tested the built today 09.28.17_dd9946d, it seems to work. Could you please try again?

**Comment by sriramab** [comment]
Hmm It only works with a new workspace, when I update in my existing workspace. It does nothing :(

**Comment by AlexisDrogoul** [comment]
It's probable, in that case, that your workspace got somehow corrupted. Have you tried to create a new one by cloning the corrupted one and updating it ?

**Comment by sriramab** [comment]
No I just installed new GAMA_standalone and used same workspace. In this case, it did not update. Then I switched to new workspace and hit update library again, and it worked.

May be then we should close this issue as a workspace issue?

**Comment by hqnghi88** [comment]
I think yes, workspace's cache issue, i have a lot or errors compilations which cannot be cleaned in my workspace except i decide to move to new one

**Comment by AlexisDrogoul** [comment]
I think so too. There is probably a way to "clean" the workspace (i.e. removing corrupted metadata) but I havent found it so far...
