### ISSUE TITLE
placement of user_command button

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2257]
Hi,

A user_command is placed at the top of the user_interface/ parameterView. Would it be possible to place it in sequence of statements where it is defined in the experiment? For example, If it is defined after two parameter statements, then the button appears after these two parameters. 

Or would it be possible to have a `category:` facet (similar to the facet in the parameter statement) for user_command also? May  be then buttons can be grouped more conveniently?

Thank you.

**Comment by AlexisDrogoul** [comment]
Makes perfectly sense. I've committed all the necessary changes, so that, for instance: 

```
model commands

global {
	int first_param;
	int second_param;
	int third_param;		
}

experiment test type: gui {
	user_command "1st command" color: #green { write "1st command"; }
	parameter "1st Param" var: first_param <- 10 ;
	user_command "2nd command"  { write "2nd command"; }
	parameter "2nd Param" var: second_param <- 100 category: "2nd group";
	user_command "3rd command" category: "2nd group" color: #violet { write "3rd command"; } 
	parameter "3rd Param" var: third_param <- 1000 category: "3rd group";
}
```

creates something like this:

![test - volumes media ws9 essai models bus gaml 2017-10-01 20-56-49](https://user-images.githubusercontent.com/579256/31055336-8c508f9a-a6eb-11e7-812e-a2154c97ed3d.png)

**Comment by sriramab** [comment]
Thank you so much :) 
If the size of the button cannot be controlled, it would visually be nice to have the button label aligned centrally on the button. Else, as in your latest screenshot, the buttons look similar to the category, but just indented.

**Comment by AlexisDrogoul** [comment]
OK. I've just made a small enhancement to enable the buttons to have different sizes (and to not show the gray background when hovered). Like this:

![test - volumes media ws9 essai models bus gaml 2017-10-01 21-27-43](https://user-images.githubusercontent.com/579256/31055617-c2cded0c-a6ef-11e7-8e77-8f7128610859.png)

**Comment by sriramab** [comment]
Works perfect.
