### ISSUE TITLE
Info.plist broken under macOS

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2258]
### Steps to reproduce
1. build GAMA using the standard build.sh command 

2. open the `/ummisco.gama.product/target/products/ummisco.gama.application.product/macosx/cocoa/x86_64/Gama.app/Info.plist` file

3. Its contents is:

```
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>Gama</string>
	<key>CFBundleGetInfoString</key>
	<string>Gama 1.7.0, Copyright UMMISCO IRD/UPMC and partners
								2006-2016 http://gama-platform.org</string>
	<key>CFBundleIconFile</key>
	<string>icon.icns</string>
	<key>CFBundleIdentifier</key>
	<string>Gama</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Gama</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.7.0</string>
	<key>CFBundleSignature</key>
	<string>GAMA</string>
	<key>CFBundleVersion</key>
	<string>1.7.0</string>
	<key>NSHighResolutionCapable</key>
	<string>True</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleDisplayName</key>
	<string>Gama</string>
</dict>
</plist>
```

### Expected behavior
This plist file should include some of the properties specified in `ummisco.gama.product/pom.xml`, namely the `CFBundleDocumentTypes` one, used to specify the link between `.gama` or `.experiment` files and `Gama.app`

### Actual behavior
This property is blank, meaning that the maven plugin used, https://libraries.io/github/buchen/fix-info-plist-maven-plugin, is not able to handle complex data structures (only strings and arrays) and is therefore useless. 

The best solution would be to include a correct `Info.plist` file somewhere and copy it at the right location when packaging the products. Anyone knows how to do this, @gama-platform/committers ?

### System and version 
Latest GAMA version, MacOSX

**Comment by hqnghi88** [comment]
Dear Alexis,
I didn't know the link and the usage of this file. But if the request is just to include at correct location, i think it is possible. Would you share a correct file?

**Comment by AlexisDrogoul** [comment]
Hi, 

I finally figured it out. Thanks for the offer ! I need to make a few tests before and I will commit it.

Cheers
Alexis
