### ISSUE TITLE
headless run for all models in library to assert their output after a commit

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2259]
### Steps to reproduce
1. Nowadays, we have:
- perfect headless mode
- travis as 24/7 worker to validate if commit will break build. 
2. I think we can have a progress on the combination, to have a headless script that step on library models (may be 100 steps) and compare each output with the standard (image comparison?) 

3. I remember Benoit or Julien have somewhere a script that use headless to generate output for all model in library (which leaded to the comodel headless issue).

### Expected behavior
Tell us what should happen (include all relevant expectations)
It can be huge process for travis but we can do it once a month?
And we must have to prepared the standard output of each model ( the correct output) of all models. Some result are stochastic but we can set a same seed for the tests.

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)
Gama git.

**Comment by AlexisDrogoul** [comment]
Hi,

There is no way to get "the output" of a model. For most models, it doesn't mean anything. However, three things could be done:

1. Verifying that all models compile correctly (i.e. no compilation errors). This can probably be done very quickly.
2. Launching test models (which need to be written using the framework created by @benoitgaudou), where "the output" is clearly defined. This would require to write proper test suites, either as models or when documenting the operators (there is a possibility to write tests in the documentation)
3. Defining a new class of experiments (test experiments), behaving like exhaustive batch experiments (with parameters to explore, etc.) that explicitly declares what the output should be for each set of parameters.

The first task does not really require a "perfect" headless, as no experiment will be launched. The second, however, needs the headless run to be clean, which is still not the case (see #2190 or #1821, for instance). @gnoubi is committed to provide fixes, but they are still pending. And the third requires creating this new type of experiments...

Alexis

**Comment by hqnghi88** [comment]
Dear Alexis,
most of them doesnt mean anything but some are useful, doee it?
1. i have no glue to validate all models except launching them or open them in Ide. we have validation method in gamlcompilation but it called only when model is loaded ?  how can we compile a model outside? may be a  headless compilation (load xtext but no agenta creation?)
2.yes, i tagged Benoit, they must be clearly defined. but i want something automated, so may be we compare with the previous validate "output" . i ll see these 2 issues.

3.why we need to define new experiment? i think step 2 is enough to assert the models outputs? why we need param explorations?
Cheers.

**Comment by AlexisDrogoul** [comment]
The point 3. would allow to test complete models (because point 2. is about the validation/testing of single operators or statement only), in all their parameter space (as defined by the experiment). For instance, a model may behave normally after a commit for one parameter set, but this commit may have altered its behaviour for other sets of parameters (limit conditions).

Regarding point 1., there are methods that allow to validate models and gather the compilation errors (if any). They should be callable from GAMA headless (I still have to look at it).

**Comment by AlexisDrogoul** [comment]
OK. I have added a `-validate` command to headless. Basically, the only thing to know to run this command is the absolute path of the `plugins` folder (within the GAMA executable) or any other folder containing models, by the way. 

```
sh ./gama-headless.sh -validate /Absolute/path/to/the/directory/where/plugins/are
```

will exit with a code of 0 if no compilation errors, >0 if there are errors (the code provides the number of errors), and they will be logged. 

With such a convention (if you have a way to run headless from the travis script -- which also means you have a way to identify the absolute path of Gama and its plugins directory), it should be easy to run this validation check once the products have been built and, depending on its exit value, to abort or not the build.

**Comment by AlexisDrogoul** [comment]
As a side note, actually, you could also run this script without passing the plugins directory, but a directory where the executable version of Gama resides, as it scans recursively all the sub-folders in search of a model.

**Comment by AlexisDrogoul** [comment]
Tell me if you succeed in incorporating this call to headless in the Travis process (i.e. in compile.sh, I guess). I'm now working on points 2 and 3, with a proposal made to @benoitgaudou on a "refresh" of this infrastructure.

**Comment by hqnghi88** [comment]
I try now and let you know then, i was working on headless comodeling.

**Comment by hqnghi88** [comment]
Dear Alexis,
Just an obvious question, where is the new gama-headless.sh or how can you bypass the 2 params of headless: input xml file and output folder, without these 2 params, headless always return error.

**Comment by AlexisDrogoul** [comment]
Which new gama-headless.sh ? I didn't touch it. That's the same as before. And the shell script does not bother about the actual parameters passed, as long as I know, it just passes them to GAMA.

**Comment by hqnghi88** [comment]
Yes, i  think so because i dont see any commit on .sh, so could you please show me your configuration in eclipse to launch headless. I have used 
-validate  -os ${target.os} -ws ${target.ws} -arch ${target.arch} -nl ${target.nl} -consoleLog "d:\\toto\\cm.xml" "C:\GitHub\gama\ummisco.gama.product\target\products\ummisco.gama.application.product\linux\gtk\x86_64\plugins"
but it return exceptions

**Comment by hqnghi88** [comment]
Ok, it works, but an error model will break the validation (crash)
C:\GitHub\gama\ummisco.gama.product\target\products\ummisco.gama.application.product\linux\gtk\x86_64\plugins\msi.gaml.extensions.fipa_1.7.0.201710061042\models\FIPA Skill\models\FIPA CFP (1).gaml
Can we keep it continue the validation and only increase the error count

**Comment by hqnghi88** [comment]
can I cover with try catch 
try {
				
				compile(createFileURI(p.toString()), errors);
			}catch(Exception ex) {
				System.out.println(ex.getMessage());
			}
and in addition, if we return an INT, how can we know which models failed? could we return a string name or even fullpath name?

**Comment by AlexisDrogoul** [comment]
For the moment, the ModelLibraryValidator is supposed to: (1) exit GAMA with an exit code > 0 (standard for all UNIX execs to show an error) if any errors have arisen; (2) output the errors  on System.out (so you can show them even in the console). It should continue even if we have compilation errors. 

What is the exception you get ? I dont have any myself. 

And, by the way, why do you need to pass all these arguments to headless ?

**Comment by AlexisDrogoul** [comment]
I run the command like this:

```
bash-3.2$ sh ./gama-headless.sh -validate /Users/drogoul/git/gama/msi.gama.models/models/
./gama-headless.sh
******************************************************************
* GAMA version 1.7.0 V7                                          *
* http://gama-platform.org                                       *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
******************************************************************
2017-10-06 18:23:33.457 java[42810:8711751] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
>GAMA plugin loaded in 406 ms: 	msi.gama.core
>GAMA plugin loaded in 5 ms: 	ummisco.gama.network
>GAMA plugin loaded in 19 ms: 	simtools.gaml.extensions.traffic
>GAMA plugin loaded in 5 ms: 	simtools.gaml.extensions.physics
>GAMA plugin loaded in 2 ms: 	irit.gaml.extensions.test
>GAMA plugin loaded in 8 ms: 	ummisco.gaml.extensions.maths
>GAMA plugin loaded in 11 ms: 	msi.gaml.extensions.fipa
>GAMA plugin loaded in 9 ms: 	ummisco.gaml.extensions.stats
>GAMA plugin loaded in 3 ms: 	ummisco.gama.serialize
>GAMA plugin loaded in 12 ms: 	irit.gaml.extensions.database
>GAMA plugin loaded in 3 ms: 	msi.gama.lang.gaml
>GAMA plugin loaded in 2 ms: 	msi.gama.headless
>GAMA plugin loaded in 47 ms: 	ummisco.gama.java2d
>GAMA plugin loaded in 48 ms: 	msi.gaml.architecture.simplebdi
>GAMA plugin loaded in 8 ms: 	ummisco.gama.opengl
>GAMA total load time 639 ms.
>GAMA building GAML artefacts in 236 ms
```
and this is what I get after having introduced an error in a model:
```
Error in Features/Agent movement/models/Follow Path.gaml: Unknown statement toto
239 GAMA models validated in built-in library and plugins.
```

**Comment by hqnghi88** [comment]
Dear Alexis,
I have successful run it. the exception is in a model of fipa skill, it was an exception so it really break the process. i manage the params and push ot to travis then for a test.

**Comment by hqnghi88** [comment]
i have 83 errors, may be a workspace cache issue? but headless have no workspace?

**Comment by hqnghi88** [comment]
ok so models in libs are good but plugins are not (even still have exception)

**Comment by AlexisDrogoul** [comment]
Interesting. It works however on my computer. It means here that the plugins are not correctly loaded (ie. and that GAMA headless is not correctly loaded, then), which is strange. The exceptions you've got point towards that, in any case. 

And, again, why do you pass all these arguments to gama-headless.sh ?

**Comment by AlexisDrogoul** [comment]
Have you tried running the headless.sh located in one of the products (i.e. here Linux, probably) and passing only the arguments I use ?

**Comment by hqnghi88** [comment]
i actually point to the released plugins of a product (linux 64). And i did not use the sh, i run directly headless as eclipse application in eclipse ide (the param is passed by run configuration so it contains something more)

**Comment by hqnghi88** [comment]
im trying again with sh in cmd

**Comment by AlexisDrogoul** [comment]
Yep. Because, in that case, you are more or less sure of the plugins loaded by Gama Headless. Using a "run configuration" has always proved very unreliable. 

So, basically, what I do is (1) build Gama locally (using build.sh) and then launch the headless.sh in the macOS product (probably win32 or Linux product for you) with the two arguments described above.

**Comment by hqnghi88** [comment]
It works perfectly. i manage to push to travis.

**Comment by hqnghi88** [comment]
Dear Alexis,
It works also on travis now, what will the strategy we chose: validates models with each commit ~ 8 min, and just compile the commit ~ 4mins + models validation once per day (in CRON)?

**Comment by gnoubi** [comment]
Hi

-validate is not at the good place. It must be placed at application parameter part (after consolLog) before it is java parameter part

Nicolas 

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by AlexisDrogoul** [comment]
@gnoubi using run configurations to launch headless is not a very good idea unless you are sure that all the required plugins are present in the configuration (which is not the case by default, if I judge by @hqnghi88 's error). 

@hqnghi88 before generalising it, we need to solve two problems:
- `Firefighters_BDI.gaml` **is not compiling** (`The type of argument predicate should be predicate` and `Unknown action or operator: remove_intention`). @mathieuBourgais @ptaillandier , any cue ?
- all the preferences related to the GUI in GAMA (for instance, `pref_editor_editbox_on`) **are not loaded**, obviously, by its headless version. The models that manipulate them (using for instance `gama.pref_editor_editbox_on <- true;`) will end up with compilation errors. 

I need to find a way to "forget" about these preferences, which are defined in plugins that headless doesn't load.

**Comment by gnoubi** [comment]
Hi
What do you mean by run configuration?

Nicolas

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by AlexisDrogoul** [comment]
@gnoubi https://www.tutorialspoint.com/eclipse/eclipse_run_configuration.htm

**Comment by AlexisDrogoul** [comment]
I've solved the second problem (GUI preferences), and now, probably, the BDI model will block the compilation ! But, in a way, it is a realistic situation. @mathieuBourgais, @ptaillandier the build of GAMA is now in your hands.

**Comment by gnoubi** [comment]
Hi, for me, 

This loading approach is suitable for debugging headless plugins, not to use gama in headless mode

Nico

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by AlexisDrogoul** [comment]
Hi,

Just want to point out that the same command, but with `-test` instead of `-validate`, is now able to run automated tests (which are summarised in the command line) and report the number of failed / aborted tests. This command looks for models present in the `tests` folder of plugins, which sport at least one "test" `experiment`, runs them in sequence and reports the passed and failed ones. 

Only trouble so far is that we dont have a lot of "test models" (only one) ... 

Alexis

**Comment by AlexisDrogoul** [comment]
An illustration (with a voluntary 'false' assertion)

![2 headless execution of gama bash 2017-10-09 17-16-56](https://user-images.githubusercontent.com/579256/31333816-c0ff35d6-ad15-11e7-95aa-5133623b1a74.png)

**Comment by ptaillandier** [comment]
Hi,

I am currently working on a test model dedicated to spatial operators....
it is not yet finished (just 2 operators finished, but the test allowed me
to already discover 2 bugs :p ). I going to commit it tonight.

Patrick

2017-10-09 12:04 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Great! Please note that you can perfectly have regular models in the tests
as well. As long as they sport at least one 'test' experiment. That would
probably ease the creation and tests of grids, etc.

**Comment by AlexisDrogoul** [comment]
Hi @hqnghi88 , 

I guess we are more or less done with this issue (at least the spirit of it). All the infrastructure is now in place, waiting for the good will of developers to add tests to their plugins (and to the core). 

There are two last things to do on this matter, but they are outside the scope of this issue:

1) transform some of the "examples" (marked as testable) in the @doc annotations into proper tests that would be built automatically (and then tested automatically).
2) allow to run the whole suite of tests from the GUI interface (since not everyone uses headless).

I will open issues on these two ones.

One thing I forgot to mention about test experiments is that they actually are exhaustive batch experiments. Defining parameters with ranges allows to test operators or other statements in different configurations. I should put an example of it in the Features section of the library.

**Comment by hqnghi88** [comment]
Dear Alexis,
Thank you for this enhancement. It's really great. I think we can close this issue now as the spirit is satisfied.
Cheers.

**Comment by AlexisDrogoul** [comment]
Just to mention that, since https://github.com/gama-platform/gama/commit/eabd06d4d8df8b6622aa0a619febddd7cd605814, `-test` and `-validate` options of headless do not require the path to the plugins anymore. These operations now operate on Bundles rather than Files and they can determine the path by themselves (actually, they dont even mess with the full path, just the ones relative to the bundles loaded).
