### ISSUE TITLE
Make graphs read/write comply with the GamaFile framework

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2260]
### Current situation
Graphs are read and written using special statements/operators, which rely on the `prefuse` library.

### Expected behavior
Graphs should be read and written as other types of data, using special flavours (subclasses) of the GamaFile infrastructure. Thanks to the new inclusion of JGraphT 1.0.1, we should also be able to get rid of `prefuse` (as JGraphT includes reading and writing to/from GML, GraphML, dot, which constitute the vast majority of the needs.

### System and version 
Git Version.

**Comment by hafidamine** [comment]
dear sir


i am computer engineer (algerian : speak french).

i want to create a model to simulate a traffic road with gama 1.7. i work with model that existe and i want to modify it to what i woul do(i am beguiner with gama). with qgis i create a shape file polyligne that contain 5 road conncted. and when lunch the simulation it seem that the car dispared when they arrived at the intersection and they not cotinnu its way. and when i modify the shape file(i fusion all road) it work but i want to work with several roads with attributes. my objectif it to simulation the circilation to reach 3 target (shapefile points) afet passed a rond-point.

another problem somme agents dont move in any case it's strong.

i cant (i try) contact you in google goupes in the posts of gama.
i need your help

thak you



my code

model traffic

global {
    //Shapefile of the buildings
    //file building_shapefile <- file("../includes/buildings.shp");
    file cible_shapefile <- file("../includes/cible1.shp");
    //Shapefile of the roads
    file road_shapefile <- file("../includes/pepisepare.shp");
    
    
    
    //Shape of the environment
    geometry shape <- envelope(road_shapefile);
    
    /**/
    //Step value
    float step <- 10 #s;
    //Graph of the road network
    graph road_network;
    //Map containing all the weights for the road network graph
    map<road,float> road_weights;
    
    init {
        
        create cible from: cible_shapefile;
        //Initialization of the road using the shapefile of roads
        create road from: road_shapefile;
        
        //Creation of the people agents
        create people number: 5{
            //People agents are located anywhere in one of the building
            //location <- any_location_in(one_of(building));
            location <- any_location_in(one_of(road));
            target <- any_location_in(one_of(road))  ;
          }
          //Weights of the road
          road_weights <- road as_map (each::each.shape.perimeter);
          road_network <- as_edge_graph(road);
          
    }
    //Reflex to update the speed of the roads according to the weights
    /*reflex update_road_speed  {
        road_weights <- road as_map (each::each.shape.perimeter / each.speed_coeff);
        road_network <- road_network with_weights road_weights;
    }*/
}
//Species to represent the people using the skill moving
species people skills: [moving]{
    //Target point of the agent
    point target ;
    //Probability of leaving the building
    float leaving_proba <- 0.05; 
    //Speed of the agent
    float speed <- 5 #km/#h;
    rgb color <- rnd_color(255);
    
    //Reflex to leave the building to another building
    /*reflex leave when: (target = nil) and (flip(leaving_proba)) {
        //target <- any_location_in(one_of(building));
        target <- any_location_in(one_of(road));
    }*/
    //Reflex to move to the target building moving on the road network
    reflex move when: target != nil {
        do goto target: target on: road_network recompute_path: false move_weights: road_weights;
        if (location = target) {
            target <- nil;
        }    
    }
    
    aspect default {
        draw circle(5) color: color;
    }
}
//Species to represent the buildings
//species building {
    //aspect default {
        //draw shape color: #gray;
    //}
//}
species cible {
    aspect default {
        draw shape color: #gray;
    }
}

//Species to represent the roads

species road {
    //Capacity of the road considering its perimeter
    float capacity <- 1 + shape.perimeter/30;
    //Number of people on the road
    int nb_people <- 0 update: length(people at_distance 1);
    //Speed coefficient computed using the number of people on the road and the capicity of the road
    float speed_coeff <- 1.0 update:  exp(-nb_people/capacity) min: 0.1;
    
    aspect default {
        draw (shape + 3 * speed_coeff) color: #red;
    }
}
experiment trafic type: gui {
    float minimum_cycle_duration <- 0.01;
    output {
        display carte type: opengl{
            //species building refresh: false;
            species cible refresh: false;
            species road ;
            species people ;

**Comment by AlexisDrogoul** [comment]
Now tracked under #1362

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
It is my understanding that this has been implemented (by @ptaillandier ?) and is now available in GAMA 1.9.1. See, e.g., https://github.com/gama-platform/gama/blob/GAMA_1.9.2/msi.gama.core/src/msi/gama/util/file/GamaGraphFile.java and its subclasses.
