### ISSUE TITLE
Enhancement for string display

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2261]
Hi,

We work on projects which require displaying strings, like the example shown in the attached figure:
![string display](https://user-images.githubusercontent.com/18676913/31237111-41fc8e4a-a9f6-11e7-88d3-d9938a44d581.PNG)

Calculating the location of the string is not very convenient. In the example, the space between the word "poulet" and the line should be the same size than the ones between the words on the right part of the chart and their respective lines . The location depends on the size of the bounding box, which is related to the font used, and also other factors such as (I think) the resolution of the screen. Right now, there are two issues about this:
- the location has to be determined manually. In the example, I have to compute an horizontal (and vertical) offset that is different for each word, and I don't see any other way than trying a value, then correct it, giving an adequate value after a few tries. This is not very convenient. Additionally, the string may change during the simulation (for example, it can be a number, with a varying number of digits). In this case, it would be very convenient to be able to compute the location automatically.
- the display may not be consistent when using another screen: after having computed the value on a laptop, switching to a videoprojector messes up with the display.

An enhancement would be more than welcome to deal with that. I think about the followings:
- a way to determine the size of the bounding box, given the text of the string and the font that is used
or
- the possibility to define the horizontal or vertical alignment of the text

I don't know if such a thing is doable without too much work, but this is quite an important limitation for projects which require a neat display.

**Comment by AlexisDrogoul** [comment]
I would rather give the possibility to draw lines with labels, which could be oriented above, under, left or right with respect to the line, and at a certain distance, for instance.  Otherwise we have no way to know on what the text should be aligned.

**Comment by agrignard** [comment]
In this case a line with label could work but some time it won't be with a line but just a text to place somewhere

How difficult is it to get the size of the bounding box of a text ?

**Comment by AlexisDrogoul** [comment]
Well, difficult in Java2D, and I would say almost impossible in OpenGL unless you use a raster font. But I can be wrong. Additionally, this would add a statement to get the bounding box, using the same parameters as the ones used to draw the text (size, font, etc.) and require to compute the location, etc. 

If you think lines with labels are too limited, then I would suggest another strategy (which can be more easily  interned in each IGraphics and doesn't require additional steps from the modeler): adding an `anchor` facet to `draw`, which could take several predefined constant values, like `#top_left`, `#bottom_left`, `#top_right`, `#bottom_right`, `#center`, `#top_center`, `#bottom_center`, `#left_center` and `#right_center` (see the figure). 

![images](https://user-images.githubusercontent.com/579256/31274488-4e3f53e6-aabd-11e7-82aa-1d3287d05dc9.png)

`anchor` would simply indicate which of these points is designated by `at`.

**Comment by tnguyenh** [comment]
This solution could be satisfying for a lot of cases, and if it can be implemented easily, I would be very interested. If later there is the possibility to compute the bounding box, it will allow more flexibility for display.

**Comment by agrignard** [comment]
I just notice a regression between RC2 and the latest bin in term of text this is what I get with the 2 version

RC2 (updated)
<img width="1267" alt="screen shot 2017-11-15 at 11 21 28" src="https://user-images.githubusercontent.com/3928502/32847180-43e23b8a-c9f7-11e7-9fdb-14322bb86b07.png">
BIN
<img width="1254" alt="screen shot 2017-11-15 at 11 20 46" src="https://user-images.githubusercontent.com/3928502/32847176-4025de70-c9f7-11e7-8f2b-6ae0b1d49ad5.png">

using 
````
aspect default{
			loop i from:0 to: length(values)-1{ 
				draw polygon(pies[i]) color: colors[i] ;
				draw polyline(label_lines[i]) color: colors[i] width: line_width;
				draw labels[i] font: font("Helvetica",font_size,#plain)  at: label_locations[i] color: colors[i] ;
			}
		}
```

It can be reproduced by running game_it_v1.0.gaml in this repo https://github.com/mitmedialab/CityScope_GAMA

**Comment by AlexisDrogoul** [comment]
No changes in the model between the 2 ? When I run the model, the font_size of the two pie agents are respectively computed to 7 and 5, that is below what is showable on screen (at least for OpenGL).

**Comment by agrignard** [comment]
Same model yes.. So two problems one in term of size of the circle and one with the size of the text.

**Comment by AlexisDrogoul** [comment]
No idea. Your shape file is in feet ?

**Comment by AlexisDrogoul** [comment]
OK. I think the difference between the two is probably the fix issued by @ptaillandier (on your request, btw : https://github.com/gama-platform/gama/commit/a449c0a1fc3d800e726e078325e2b8017f38cc47) for taking units into account in the definition of shape files. Now your shapes are ~3 times smaller than before (meaning that your font and display size of people are also 3 times smaller).

**Comment by AlexisDrogoul** [comment]
I've implemented the solution for Java2D and OpenGL, with an example model in Features>User Interaction>Text Display.gaml.

**Comment by AlexisDrogoul** [comment]
I think we can now safely close this issue ? Reopen if it doesn't work, of course.
