### ISSUE TITLE
Transform @example annotations into tests

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2264]
Right now, we have a nice infrastructure for automatically building a consistent documentation on all the GAML language features. It works reasonably well, but it is still missing a piece: transforming the examples provided in these @doc annotations into tests (when they are marked as testable). This would allow for a really powerful mechanism of both documenting and immediately validating new operators, etc., as tests are now performed (see #2259) automatically by the Travis build. 

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by benoitgaudou** [comment]
I have just commited a first attempt (with the generated files) in the last commit.
It is only a first attempt.
To generate the unit test from the documentation, simply run the file : MainGenerateUnitTest_vNew.java in the plugin msi.gama.documentation.

Benoit

**Comment by AlexisDrogoul** [comment]
Hi Benoit,

May I take a look into it or are you working on it now ? 

Alexis

**Comment by AlexisDrogoul** [comment]
I am wondering, looking at the annotation, whether it is not a bit too complex to handle now if we want people to just provide some basic tests quickly. Point is, there are many possible options in the `@example` annotation, and it's quite easy to get lost. Maybe it would be easier to let people enter the  tests in a straightforward way, specifying only what needs to be specified outside GAML. 

Basically, I can implement a new annotation that would take this form:
```
	@Retention (RetentionPolicy.RUNTIME)
	@Inherited
	public static @interface test {
		verify[] value() default {};

	}

	@Retention (RetentionPolicy.RUNTIME)
	@Inherited
	public static @interface verify {
		String value();
		boolean warning() default false;
	}
```

for example (for a `op` operator) : 
```
@test {
     @verify("op(100) = 13"),
     @verify("op(1000) = 32"),
     @verify(value="op(0) = 1", warning=true)}

```

Of course, this would be only convenient for operators, but I think we would definitely gain some more tests

**Comment by benoitgaudou** [comment]
Hi,

From my last commit/push, to generate tests model from the @example , we can simply run the file MainGenerateUnitTest.java (from msi.gama.documentation).
But, this file uses the xml file generated by the processor.
But from this morning ti seems that the processor does not generate these files anymore.
Is it on purpose?

It could be indeed great to help people to write test more easily, to have more of them.
I was thinking about adding another facet to the verify, that could be error , that checks whether the expression raises an error.

**Comment by AlexisDrogoul** [comment]
The is_error operator is already here for that. Regarding the documentation
process, I'm not sure it is necessary that the tests belong to it, as they
are code. I would generate them before and independently.

BTW, the errors in the doc generation may come from me, as I am refactoring
everything in the processor. XML generation, modularization... In order to
debug it a bit better.

**Comment by benoitgaudou** [comment]
Regardons test génération, They are independent from documentation
generation (different main), but it reliés on the xml files generated by
the processor.

Concerning the process it self, I do not know if a file with a main to
execute os the best way or if you need something else ?

Le dim. 15 oct. 2017 à 09:18, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
The doc files should now be regenerated normally. Regarding the tests itself, I would suggest we get rid of the variables when possible. As a matter of fact, an output like this one is difficult to interpret:

```
	passed: var8 = rgb([255,128,32])
	passed: var9 = (point(5.0,6.0,4.0))
	passed: var10 = (point(5.5,6.5,4.5))
	failed: var11 = circle(float(10))
	passed: var12 = matrix<float>([[5.5,8.5],[6.5,7.5]])
	passed: var13 = ([1,2,3,4,5,6,2,4,9])
	passed: var14 = ([1,2,3,4,5,6,0,8])
	passed: var15 = ([1,2,3,4,5,6,2])
```

For executing the generation itself, I would of course prefer something linked with the annotation processor (and running at the same time), although it might be difficult to output tests anywhere. I will look into this.

**Comment by hqnghi88** [comment]
Dear Alexis,
Just wonder about the failed, they are supposed to failed or were only a fault documented?

**Comment by AlexisDrogoul** [comment]
Nghi,

For the moment, we have probably the two cases. We have to refine the tests base in the documentation.

**Comment by AlexisDrogoul** [comment]
I'm working on integrating the generation of tests into the annotation processing. Right now, I can output a completely configured folder, inside the output folder, ready to welcome test models (and correctly configured as a GAML project, with the plugin name, the `.project` file, etc.). This folder will be processed either by GAMA itself when looking for tests or maybe by the Maven build by copying its contents to the tests folder inside the plugin, I still dont know which solution is the best. Both `@example` and `@test` annotations will be parsed to create the tests models (I still have to wire the work of Benoit into the processor, but it shouldn't be that hard).

**Comment by AlexisDrogoul** [comment]
OK. First of all, I've defined the @test and @tests new annotations (available on anything, and not only GAML artefacts). Only @test needs to be used (as it can be repeated), and the syntax is extremely simple (see below for the doc).

```
	@Retention (RetentionPolicy.RUNTIME)
	public static @interface tests {
		test[] value() default {};
	}

	/***
	 * The test annotation is intended to provide a simpler syntax than @example for producing tests. It allows to write
	 * unit tests for any GAML artefact. These tests are then automatically generated by the annotation processor and
	 * tested during the compilation of GAMA, to ensure that the code is correct (and that no regressions affect it).
	 * Tests are grouped together in test experiments (one experiment per GAMA plugin) that are automatically retrieved
	 * by GAMA (so that they are also available in the UI or headless version of the platform). Depending on where they
	 * are located, they are automatically named after the operator, constant, statement they annotate. For instance,
	 * for the '+' operator, this annotation will produce:
	 * 
	 * @test("10+10=20") -> test "+" { assert 10+10=20;}
	 * 
	 * It is possible to give them a more explicit name:
	 * 
	 * @test(value="10+10 = 20" name="int addition") -> test "int addition" { assert 10+10=20; }
	 * 
	 * Several @test() annotations can be attached to an operator or constant. In that case, the corresponding
	 * assertions are grouped together in a single GAML test statement. Example:
	 * 
	 * @test("10+10=20") @test("0+0 = 0")
	 * 
	 * will produce the following GAML test statement:
	 * 
	 * test "+" { assert 10+10=20; assert 0+0=0; }
	 * 
	 * If they are named, the name of the test statement is a concatenation of their names:
	 * 
	 * @test(value="10+10=20" name="int addition" ) @test(value="10+0 = 10" name="zero neutrality")
	 * 
	 * produces:
	 * 
	 * test "int addition and zero neutrality" { assert 10+10=20; assert 10 + 0 = 10; }
	 * 
	 * test annotations accept multi-line tests, provided that the last line is a boolean expression (i.e. an
	 * assertion). Simply separate (as you would do in GAML) the lines by a semi-colon. If there are no assertion (i.e.
	 * the last line ends with a semi-colon), the lines are simply copied to the GAML code. This can be handy if one
	 * wants to initialize a bunch of variables, for instance. These statements can even contain complete 'assert'
	 * statements.
	 * 
	 * Example:
	 * 
	 * @test("int a <- 10; int b <- 10;") @test("a+b = 20") @test("a+0 = a") @test("int c<- 0; assert c+b = b;")
	 * 
	 * produces:
	 * 
	 * test "+" { int a <- 10; int b <- 10; assert a+b = 20; assert a+0 = a; int c<- 0; assert c+b = 0; }
	 * 
	 * Note that no syntax verification occurs when writing these annotations. It is up to the programmer to produce
	 * syntactically correct codes, otherwise the automated validation of models (which occurs whenever the code is
	 * committed) will fail.
	 * 
	 * @author drogoul
	 *
	 */
	@Retention (RetentionPolicy.RUNTIME)
	@Repeatable (tests.class)

	public static @interface test {
		/**
		 * 
		 * @return the GAML expression or list of statements that need to be tested using the 'assert' statement. For
		 *         instance, '@test( "10+10 = 20")' will generate a test containing the statement 'assert 10+10 = 20;'
		 * 
		 *         To generate a multi-line test, use semi-colons to separate the statements (like in GAML). For
		 *         instance '@test( "int a <- 10; int b <- 10; a+b = 20") will generate the following test:
		 * 
		 *         test plus { int a <- 10; int b <- 10; assert a+b = 20; }
		 * 
		 *         If the string ends with a semi-colon, no attempt is made to infer the 'assert' statement and the
		 *         whole GAML code is simply copied into the test. This can be used to initialize variables, but also to
		 *         generate tests that will "abort" instead of "failing". For instance, consider these two annotations:
		 * 
		 *         '@test("int a <- 0; float b <- 100 / a ;")' // when tested, a runtime error will make this test abort
		 *         '@test("int a <- 0; !is_error(100 / a)")' // when tested, the runtime error will be caught but the
		 *         test will fail (as the division by zero IS an error)
		 * 
		 *         An empty value will produce an empty test statement (unless the @test annotation is preceded or
		 *         followed by other @test annotations)
		 * 
		 */
		String value();

		/**
		 * 
		 * @return the name of the test (see the general comment for the effect of naming tests). It is empty by
		 *         default.
		 */
		String name() default "";

		/**
		 * 
		 * @return whether the test, if false, will fail or simply emit a warning. 'false' by default.
		 * 
		 *         '@test("10+10 = 100" warning=true) will not be recorded as failing (i.e. it will not break the
		 *         compilation)
		 * 
		 *         Note that warning=true has no effect if the value of the test does not contain assertions (and it
		 *         simply influences the last assertion if there is one)
		 */
		boolean warning() default false;

	}
```

This allows to write things like:

```
	@operator (
			value = IKeyword.DIVIDE,
			can_be_const = true,
			category = IOperatorCategory.POINT,
			concept = {})
	@doc (
			value = "Returns a point with coordinates divided by the number")
	@test ("{2,5} / 4 = {0.5,1.25}")
	@test ("is_error({2,5} / 0)")
	public static ILocation divide(final IScope scope, final GamaPoint p, final Integer d) {
```

or more complex things, like:

```
	@operator (
			value = IKeyword.PLUS,
			can_be_const = true,
			category = IOperatorCategory.POINT,
			concept = { IConcept.POINT })
	@doc (
			value = "Returns a point with coordinate summing of the two operands.",
			usages = @usage (
					value = "if both operands are points, returns their sum.",
					examples = @example (
							value = "{1, 2} + {4, 5}",
							equals = "{5.0, 7.0}")))
	@test ("{1, 2} + {4, 5} = {5,7}")
	@test (value="point p <- {1, 2}; p + {0, 0} = p", warning=true)
	public static ILocation add(final GamaPoint p1, final GamaPoint p) {
```

And I obtain at the end, in the generated source folder, a complete project for the whole plugin with one (and only one) experiment file

```
experiment "Tests for msi.gama.core" type: test {

	test "Regular and Not" {
		assert norm({3,4}) = 5.0;
		assert norm({1,1}) = sqrt(2);
		assert norm({0,0}) = 0.0;
		assert norm({1,0}) = norm({0,1});
	}


	test "Operator +" {
		assert {1, 2} + {4, 5} = {5,7};
		point p <- {1, 2};
		assert  p + {0, 0} = p warning: true;
	}


	test "Operator /" {
		assert {2,5} / 4 = {0.5,1.25};
		assert is_error({2,5} / 0);
	}


	test "Operator *" {
		assert {2,5} * 4.0 = {8.0,20.0};
		assert {2,5} * 0.0 = {0.0,0.0};
	}


	test "Operator * (1)" {
		assert {2,5} * 4 = {8,20};
		assert {2,5} * 0 = {0,0};
	}

}
```


Now the last piece is to retrieve these files in both headless and GUI so that they are included in the automated build and accessible via the interface.

**Comment by AlexisDrogoul** [comment]
So we are not yet done, but the last commit provides a good infrastructure to make it work in a not so distant future:

- Allows to read models and tests from within jar packaged plugin at last ! (no more "Eclipse-BundleShape: dir" in manifest)
- Annotation processor now generates tests (only @test annotation so far) that are looked up at both runtime (in plugin>gaml>tests) and build (thanks to maven copy resources: in plugin>tests)
- Headless now uses OSGI bundles to retrieve models and tests rather than the good old "File" framework (necessary for reading into jars).
- As a consequence, the `-test` and `-validate` options of headless GAMA do not require the full path anymore (they will auto-determine it).

Now the goal is to wire the generation of tests from @usage / @example into the processor. Not completely easy as many things are hardwired in this generation -- but it will be done !
