### ISSUE TITLE
Refactoring of the template model files

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2267]
When creating a new model file, three types of template are proposed:
- Empty: only usefull when defining some specific types of models (i.e. test model).
- Skeleton: most used one
- Example: never used

We should maybe refactor a bit these three templates.

**Comment by AlexisDrogoul** [comment]
Agree. We should probably remove `Example`, add a `Test` template, a `gui experiment` and a `batch experiment` ones (with plenty of comments).

**Comment by AlexisDrogoul** [comment]
In the same spirit, removing the "images" folder and replacing it with a "tests" folder could be a good idea. As would be a new command to create "New Test...", maybe ...

**Comment by AlexisDrogoul** [comment]
I've done the minimum required. The 'example' template has been replaced by a 'test' template. The layout of projects is now simpler: only 'includes', 'models' and 'tests' folders are created by default. I would say it is enough for the moment... I close this issue, reopen if you need specific things !
