### ISSUE TITLE
Is there any ways to only display the failed tests?

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2271]
### Steps to reproduce
1. I'm using the new testing infrastructure on travis.

2. It displays many information (warning, passed, not run, failed). 

3. I think we could have a way to display only failed test, to concentrate in them. And they are also the only helpful message in the console (failed mean !passed and tested)

I can change the model validator, but for the test infrastructure, i don't want to break a new thing.
### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

GAMA git

**Comment by AlexisDrogoul** [comment]
I will be looking into this.
