### ISSUE TITLE
Manual build of GAMA broken by latest commits

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2273]
### Steps to reproduce
1. Do a manual build of GAMA using the `build.sh` script found at the root of the git repository

2. Various errors occur, and as a result nothing is built.

3. It seems that two commits are at fault here: https://github.com/gama-platform/gama/commit/0002d9e890a08579e0ce6e65e79db76373b75cde (see my comment below for more details) and https://github.com/gama-platform/gama/commit/318de6a59e80d4ed407b30d817ea5eb78ade3a38 (see also my comment).

### Expected behavior
It should build as usual. I can confirm (after replacing the files, `build.sh` and `pom.xml` in `msi.gama.parent`, with their previous versions) that the "old" build is working well. 

### Actual behavior
Errors occur before the building fails (see comments above)

**Comment by AlexisDrogoul** [comment]
New comment: it seems that the annotation processor is not working well, even after replacing the old build files. I've modified its pom.xml file (in https://github.com/gama-platform/gama/commit/14fce73106d3276982f11033be714cc7c0aa6d02) to issue warnings instead of errors regarding the use of non-API classes so maybe it is the problem. When I build it manually, a number of warnings are emitted, like: 

```
Access restriction: The method 'BaseMarkupSerializer.serialize(Document)' is not API (restriction on classpath entry '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/rt.jar')
```

Could it be the cause of this failure ?

**Comment by hqnghi88** [comment]
Dear Alexis,
i am working on it but i have found that headless throw exception and hang with successful build (console and eclipse). Do you have that behavior?

**Comment by AlexisDrogoul** [comment]
Probably yes. The annotation processor does basically nothing (i.e.. no XML file outputted, for instance). I will try another way of serialising XML files.

**Comment by hqnghi88** [comment]
obviously, but i must say , tried with run configuration for headless also fail. does it mean even in eclipse xml are not outputted?

**Comment by AlexisDrogoul** [comment]
XML files are correctly outputted in Eclipse, and the GamlAdditions.java file is correct. But it is not in the build: 

```
public class GamlAdditions extends AbstractGamlAdditions {
	public void initialize() throws SecurityException, NoSuchMethodException {
	initializeType();
	initializeFactory();
	initializeSpecies();
	initializeSymbol();
	initializeVars();
	initializeOperator();
	initializeFile();
	initializeAction();
	initializeSkill();
	initializeDisplay();
	initializeExperiment();
	initializeTest();
}public void initializeType()  {
}public void initializeFactory()  {
}public void initializeSpecies()  {
}public void initializeSymbol()  {
}public void initializeVars()  {
}public void initializeOperator() throws SecurityException, NoSuchMethodException {
}public void initializeFile() throws SecurityException, NoSuchMethodException {
}public void initializeAction() throws SecurityException, NoSuchMethodException {
}public void initializeSkill()  {
}public void initializeDisplay()  {
}public void initializeExperiment()  {
}public void initializeTest()  {
}
}
```

**Comment by AlexisDrogoul** [comment]
What fails using a run configuration ?

**Comment by hqnghi88** [comment]
exceptions when loading bundle in prebuildcontributionbundle.

**Comment by hqnghi88** [comment]
Exception in thread "Thread-2" java.lang.NullPointerException
	at msi.gama.database.CreateFromDatabaseDelegate.fromFacetType(CreateFromDatabaseDelegate.java:115)
	at msi.gaml.statements.CreateStatement.addDelegate(CreateStatement.java:354)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:103)
	at msi.gama.common.Activator.lambda$0(Activator.java:26)
	at java.lang.Thread.run(Thread.java:748)

**Comment by AlexisDrogoul** [comment]
Same here. But not when I launch the GUI version. It means, basically, that the types have not been built, i.e. no GAML artefacts have been built. Have you tried enabling a clean build in Eclipse before ?

**Comment by hqnghi88** [comment]
yes, gui is normal. probably yes as i set a automatic build is a clean build but maybbe i missed.

**Comment by hqnghi88** [comment]
Some corrupted gaml, i must delete manually the gaml folders, and clean again, headless by running configuration works

**Comment by AlexisDrogoul** [comment]
OK. I've succeeded in having a working annotation processor at last. For a strange reason, saving and reading the XML files did not work, so I had to tweak it to do it in memory (something that did not work before, by the way, go figure!). And the build is ok with the "old" build scripts.

**Comment by hqnghi88** [comment]
Great! im eager to see the tweak
