### ISSUE TITLE
QuadTree: No free or removed slots available. Key set full?!!

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2274]
### Steps to reproduce
1. Test the following model: https://drive.google.com/file/d/0BxvMwvAG0APzZmhjb242N2dsR2c/view?usp=sharing

2. Run it for more than 20000 simulation steps

### Expected behavior
No error

### Actual behavior
I get this error: 

java.lang.IllegalStateException: No free or removed slots available. Key set full?!!
	at gnu.trove.impl.hash.TObjectHash.insertKeyRehash(TObjectHash.java:358)
	at gnu.trove.impl.hash.TObjectHash.insertKey(TObjectHash.java:294)
	at msi.gama.util.TOrderedHashMap.put(TOrderedHashMap.java:268)
	at msi.gama.metamodel.topology.GamaQuadTree$QuadNode.add(GamaQuadTree.java:212)

### System and version 
Github version , with Windows 7, 64 bits, and 32go of RAM.

**Comment by AlexisDrogoul** [comment]
Hi,

I can't reproduce it (ran the model twice up to 30.000 cycles). However, I suspect the problem you have may come from the `parallel: true` facet of `species people`. Concurrent accesses to the quadtree are not exactly well handled if I remember correctly. Can you try on your machine without this facet ? 

Alexis

**Comment by AlexisDrogoul** [comment]
I have to precise that I ran the model with `parallel: true` as well. However, concurrency problems like this one are hard to reproduce on different machines with different number of cores.

**Comment by ptaillandier** [comment]
Seems to work without the parallel facet (at least on my new windows computer). I close this issue for the moment.
