### ISSUE TITLE
Impossible to run GAMA on macOS Sierra and new macbook pro

### ISSUE THREAD

**Issue by echen9898** [gama-platform/gama#2275]
### Steps to reproduce
1.After doing an update from the binary I cannot run GAMA anymore (even after doing a new workspace)

### Expected behavior
A working version

### Actual behavior
The GUI is stucked on "Updating the built-in models library"  and I have no model in the library as shown on the screenshot 
<img width="1792" alt="screen shot 2017-10-23 at 5 55 31 pm" src="https://user-images.githubusercontent.com/25084630/31915299-f0e8cf12-b81b-11e7-8efb-1d979e6170e6.png">

### System and version 
mac OS Sierra - macbook pro 2016

**Comment by sriramab** [comment]
Yes, solution for me is (new download ) AND (new workspace)

**Comment by AlexisDrogoul** [comment]
Have you tried the aforementioned advice (i.e. downloading a fresh binary) ? We've had some problems lately with the update, so maybe you've been a victim of those...

**Comment by agrignard** [comment]
Ok so indeed there is a problem in the update process we fixed it by downloading the latest build
