### ISSUE TITLE
Minor Issue about bright color in Opengl

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2276]
Very minor issue but I just notice that any shape with a color rgb value greater than around rgb(200,200,200) with a white background is impossible to distinguish

Here is 2 screenshots of the same rendering with opengl and java2D

<img width="1124" alt="screen shot 2017-10-24 at 15 03 16" src="https://user-images.githubusercontent.com/3928502/31962785-82d110d2-b8cc-11e7-8e7b-863bfc6e681d.png">
<img width="990" alt="screen shot 2017-10-24 at 15 02 53" src="https://user-images.githubusercontent.com/3928502/31962786-82dc36a6-b8cc-11e7-8301-b5436f4ad8bc.png">

**Comment by AlexisDrogoul** [comment]
I guess it is probably a problem of ambient light, no ? Does changing the light affect the colours ?

**Comment by agrignard** [comment]
Yes it might be related to this (and as far as I remember it was more or less reported in issue #828)

**Comment by AlexisDrogoul** [comment]
And does the workaround in #828 still work ? In any case, I move this to the tracker in #2209

**Comment by AlexisDrogoul** [comment]
To obtain exact colors, you can now use the `lighted: true/false` facet on an individual basis in a `draw` statement. Or turn the lights off globally.

**Comment by agrignard** [comment]
Ok nice. How does it look without light? not too dark? or it only disables the shadow effect?
