### ISSUE TITLE
Some strange compilation Errors 

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2277]
### Steps to reproduce
1. I've got some compilation errors from the unstable commits of processors change. Does anyone have this behavior or just me? it seem something wrong in java configuration/version? I use Eclipse Neon 4.6.3 and jdk 1.8.121

Type mismatch: cannot convert from Object to ExperimentAgent	ExperimentPlan.java	/msi.gama.core/src/msi/gama/kernel/experiment	line 372	Java Problem

The method sameThreadExecutor() is undefined for the type MoreExecutors	GamaExecutorService.java	/msi.gama.core/src/msi/gama/runtime/concurrent	line 39	Java Problem

The method firstNonNull(Scaling3D, Scaling3D) is undefined for the type Objects	GeometryObjectTransformer.java	/ummisco.gama.opengl/src/ummisco/gama/opengl/vaoGenerator	line 205	Java Problem

The method firstNonNull(Double, double) is undefined for the type Objects	AbstractTransformer.java	/ummisco.gama.opengl/src/ummisco/gama/opengl/vaoGenerator	line 91	Java Problem

The method firstNonNull(Double, double) is undefined for the type Objects	FieldDrawer.java	/ummisco.gama.opengl/src/ummisco/gama/opengl/scene	line 54	Java Problem

The method firstNonNull(Double, double) is undefined for the type Objects	FieldDrawer.java	/ummisco.gama.opengl/src/ummisco/gama/opengl/scene	line 222	Java Problem

The method emptyIterator() from the type Iterators is not visible	GamlResourceIndexer.java	/msi.gama.lang.gaml/src/msi/gama/lang/gaml/indexer	line 276	Java Problem

3.

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
1) Errors in Eclipse or errors in Maven ? 
2) The recommended version for running GAMA is Mars, not Neon
3) Most of your errors seem to come from Google Collections / GUAVA missing methods (an old version is used somewhere ?)

**Comment by hqnghi88** [comment]
Dear Alexis,
it come from eclipse.
ok so it seem to have a migration in the future ( oxygen is released and 1.9 also).
i have checked and the guauva is 22, prebuilt in eclipse neon, so i m confuse where is the old one.

**Comment by AlexisDrogoul** [comment]
I dont know and I dont think it is a good idea to develop GAMA in Neon, since Guava 22 has deprecated a number of things since Guava 15 (Objects methods, for instance, now available in MoreObjects), etc. 

I checked and for the moment there are no real fancy things in Neon or Oxygen -- not enough to justify migrating, at least.

**Comment by hqnghi88** [comment]
no-occurs in Mars.2 Release (4.5.2).
