### ISSUE TITLE
Update fail on release candidat 2

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2278]
### Steps to reproduce
1. I tried to figure out what happen with  #2275 and after updating , gama crashed with following log (the update process is success, all new packages have been downloaded): 

[1509350087776.log](https://github.com/gama-platform/gama/files/1426358/1509350087776.log)

2. Could it have reansonning with this log for something to be:
- cleared that the new packages have no problems.
- the solution for 2275 is a new download, but which version (continuous or release candidat)? 

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by sriramab** [comment]
In my case it is continuous build

**Comment by AlexisDrogoul** [comment]
Dont really understand what you're asking. However, there have been so many changes (in the build, in the organisation of packages, etc.) since RC2 that it is not surprising. I would say that downloading the continuous build is probably safer (and has less bugs, at least in theory).

**Comment by hqnghi88** [comment]
Dear Alexis,
I think i asked for a new official release (RC3), because the update wont work for RC2 (so it is obsolete?), and the continuous build is the recommendation.

**Comment by AlexisDrogoul** [comment]
Closing this (obsolete bug).
