### ISSUE TITLE
trace strange behavior when using cycle for the Z position

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2279]
### Steps to reproduce
1. In any model (e.g 3D Visualization/models/Building Elevation.gaml

2. Put a trace to people like this
```
species people aspect: base position:{0,0,0.01} trace: 100;

```
it works

but if you put this
```
species people aspect: base position:{0,0,cycle*0.01} trace: 100;
```
doesn't work anymore
### Expected behavior
I would expect to have a timespace cube

### Actual behavior
The trace seems not to work, is it only because cycle is a non constant value?

**Comment by AlexisDrogoul** [comment]
I have committed a possible fix  (since an exception was thrown at one point in your case study). The display occurs at least, and it is most visible when synchronising the view, by the way.

**Comment by agrignard** [comment]
Mmm it seems that it's still not working for me

**Comment by agrignard** [comment]
I cannot make it work on the latest build with 
````
display timelapse type: opengl background: #black{
  species people aspect: default position:{0,0,cycle*0.01} trace: 100;	
}
```
See https://github.com/mitmedialab/CityScope_GAMA/blob/master/CPG_CityScope_GAMA/models/game_it_v1.0.gaml

The layer is updated in Z value but trace is not doing its job (no trace at all)

**Comment by AlexisDrogoul** [comment]
Does not seem to be solved (or is it ?). Moved to the OpenGL tracker in #2209 in any case.

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
This issue was actually not an issue, more a misunderstanding about how `trace` works. As a matter of fact, the trace only concerns (concerned) the display of the agents, but not the layer itself with its attributes. I have issued a fix which allows to also keep track of the size and position of the layer  in the trace.
