### ISSUE TITLE
HTTP Get and Post Json file

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2280]
This is more a request than an issue about reading and writing a url with GAMA.

Now I am able to GET the content of a json file in gama by pointing to this url 

```
matrixData <- json_file("https://cityio.media.mit.edu/api/table/citymatrix_volpe").contents;
```
Everything works fine I can get the information in the matrixData and parse my JSON

Now I want to do the opposite operation and POST information to the server. 
Is it already possible to that in GAML and if not where should I start to look for?

**Comment by hqnghi88** [comment]
what is your post syntax and content? propably doable by command :
do command ("curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data");

**Comment by hqnghi88** [comment]
post a file named data.json:
do command("curl -d \"@data.json\" -X POST http://localhost:3000/")

**Comment by agrignard** [comment]
Can I do it without creating the file?

typically I would like to  modify my matrixData (the one that I GET) and POST it easily with some modification (I might need to POST every n iteration)

**Comment by hqnghi88** [comment]
the 1st syntax above sont create file.
problem is that Gama dont have json data type, what you read from Get is a matrix , if you post you must adapt the structure matrix to json

**Comment by agrignard** [comment]
```the 1st syntax above sont create file.```what do you mean?

There is a ```json_file```type no? I mean when I right this

```
matrixData <- json_file("http://45.55.73.103/table/citymatrix_ml").contents;
```
it means there is a json_file type no?

How can I adapt the matrix to a json?

**Comment by AlexisDrogoul** [comment]
The recommended way to do it would be to use what the file infrastructure already offers, i.e. 

```
json_file jf <- json_file("http://...", matrixData);
save jf;
```

However, it doesn't work right now because the http address is only used for reading (I think). The file infrastructure is by the way in **real need** of work (see #1362, #2260).

So the best way is (until someone writes it) is to save the file (i.e. `save json_file("temp.json", matrixData);`) and do what Nghi proposes.

**Comment by hqnghi88** [comment]
do command ("curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data"); 
it dont create a file, but i think it is not enough for your need.
json_file is a file type, not data type. it read .json file to memory, and when you access .contents, it convert the json structure to matrix so you can assign to a matrix variable.

 you can took a look in gamajsonfile , fillbuffers() there is a call to converttoGamaStructure.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 , no, json_file internal GAML format is a `map`, not a `matrix`.  So loading it and saving it is not a real problem as long as the structure of the map remains coherent.

**Comment by agrignard** [comment]
ok Il'' try that

@nghi you don't have a simplier synatax?

What is the minimal syntax? 

This one is a bit... how to say ... ;-) complex ?
```
do command ("curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data");
````

**Comment by agrignard** [comment]
The structure will stay the same what I want is just to change some value (that are typically the result of a simulation)

**Comment by hqnghi88** [comment]
@alexis yes a map. 
@arnaud no , it is strange for you (a cmd script) but not too complex. and even it is complex, someone can hide it under gaml syntax . so there have something already possible and something need to be wrote.
Cheers.

**Comment by agrignard** [comment]
ok i'll keep you update. 
@hqnghi88 for me it's ok I can deal with a cmd bu I am more thinking about the lambda user ;-)

**Comment by agrignard** [comment]
@hqnghi88 btw I still don't have the syntax right

what do you mean by '''{"key1":"value1", "key2":"value2"}''' can you write me a syntax where I can just send my matrix? I'll take care to update this matrix in GAML before but once it's modify I just want to resend it

**Comment by hqnghi88** [comment]
it depend in how your server will process thebjson data. it read whole json matrix or it can manipulate a single data element. if yes , each time you change a cell , 
do command ("curl -d '{"cellx":"value1"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data");
if not, Alexis's proposal is the only solution before CC

**Comment by agrignard** [comment]
No the server is waiting for the entire json (and it is ok to receive it as soon as it's a json valid)

BTW if you want more detail bout the server you can have a look here
https://github.com/mitmedialab/cityioserver
 For Alexis solution if I understand well:

I create a new json file (jfToPost) from the matrixData (why do I need to specify a url here?)
```
json_file jfToPost <- json_file("http://...", matrixData);
save jfToPost;
```
And then what do I with ``` jfToPost ``` once it's save how do I send it?

I do this?
````
do command("curl -d "@jfToPost.json" -X POST http://localhost:3000/")
````

**Comment by AlexisDrogoul** [comment]
To summarise:

`http://...` adresses are not taken into account in the `save(...)` and `flushBuffer(...)` methods of `GamaFile`. For the few ones that exist (including that of `GamaJsonFile`), we have to think about how to do it. Basically, the easiest way would be to do something very high-level, comparable to  what is already done when reading a file from an http address : at the level of `GamaFile`, create a temp file somewhere, set the path of the GamaFile to it, let the `flushBuffer` method write whatever is needed into it, and, once it's done, upload the file. 

So the solution I propose is not too different anyway (just in GAML instead of Java):

```
//create a local file
save json_file("temp.json",matrixData);
do command("curl -d "@temp.json" -X POST http://localhost:3000/");
```

**Comment by hqnghi88** [comment]
Alexis said about the post mechanism, when you do save it must resend data to server but for the moment it cant.
So, get:
m<- json_file("http://.....");
and when post:

save json_file("temp.json", m);
do command("curl -d "@temp.json" -X POST http://localhost:3000/");

**Comment by agrignard** [comment]
Ok so i get this error in GAML

````
do command("curl -d "@temp.json" -X POST http://localhost:3000/");
```

Multiple markers at this line
- Symbol 'temp' seems to be incomplete
- Unwanted or misplaced character ' . '
- Parenthesized expression do not begin or end correctly
- Unwanted or misplaced character ' @ '

**Comment by hqnghi88** [comment]
yea, sure, sorry i sent by phone,
itwas a string and it must be right escaped.
do command("curl -d \"\@temp.json\" -X POST http://localhost:3000/");

**Comment by agrignard** [comment]
What? I don't get it what do you mean by "right escaped"?

the last line you sent is the same?

**Comment by hqnghi88** [comment]
do command("curl -d \\"\\@temp.json\\" -X POST http://localhost:3000/");
github hide my backslash

**Comment by agrignard** [comment]
ok no rush. try the right syntax as soon as you are on a computer and get back to me.
````
do command("curl -d \"\@temp.json\" -X POST http://localhost:3000/");
`````
this is one is still not working but we are close ;-)
thanks

**Comment by hqnghi88** [comment]
what is still not working?

**Comment by sriramab** [comment]
Yes, command always works for me. i use it as brute force method for things not directly possible in GAMA. I think only the "quotes" and .dot. need an escape \slash\. Other issue with command operator not to work on Mac is that it is highly dependent on macOS environment settings (global local settings)

Just my two cents :)

**Comment by agrignard** [comment]
Any help to help me to execute this cmd line in GAML

````
do command("curl -d \"\@temp.json\" -X POST http://localhost:3000/");
````

as mentioned before this is not compiling

**Comment by AlexisDrogoul** [comment]
Is this not working (and in that case, is it throwing an error or simply doing nothing) or is it not compiling ? Can you post any valuable output (log, anything).

**Comment by agrignard** [comment]
actually even ```do command("ls");```  is not compiling so it's not a question of string \ escape etc

This is the error I have, so i guess i just don't call the command in the right way 
Description	Project	Resource	Location
Action command does not exist in CityIOGAMA_model	CityScope_GAMA	CityGamatrix.gaml	line: 40 /CityScope_GAMA/models/CityGamatrix.gaml

I tried ```command("ls"); ```as mention in the doc http://gama-platform.org/references#Operators#410_98_1707_operator-command

**Comment by agrignard** [comment]
with ```command("ls");```I get this error

````
Multiple markers at this line
- Symbol '"ls"' seems to be incomplete
- Parenthesized expression do not begin or end correctly
````

**Comment by agrignard** [comment]
ok got it

**Comment by agrignard** [comment]
so this is ok 
````
string s <- command("ls");
`````
but not this one

````
string s <- command("curl -d \"\@temp.json\" -X POST http://localhost:3000/");
````

**Comment by agrignard** [comment]
ah those \\\\\!!!

this is ok (at least it compile) 
 ````
string s <- command("curl -d \"@data.json\" -X POST http://localhost:3000/");
```

**Comment by agrignard** [comment]
Ok 

so this is the final one that WORKS
````
string s <- command("curl -H \"Content-Type: application/json\" -X POST -d '@temp.json' https://cityio.media.mit.edu/api/table/update/testTable");
````

Thanks everyone sorry for the noise (let's see now if it's working on a windows machine)

**Comment by AlexisDrogoul** [comment]
I have actually coded a preliminary POST method for sending to HTPP URLs in GamaFile. I will share it as soon as I fix an annoying compilation bug in the annotations.

**Comment by AlexisDrogoul** [comment]
It should work by simply writing `save(json_file("http://essai.com/", c));` where `c` is the map containing the JSON data. No way to test it, so probably it will fail, but at least the infrastructure is there...

**Comment by agrignard** [comment]
Great!! 

So the cmd option works but if the ```save(json_file("http://essai.com/", c));```that's even better

I'll test that as soon as the latest build is ready (I have to admit that my Eclipse is a bit outdated... I'll realive it for the CC)

**Comment by agrignard** [comment]
Ok so I ve updated my Eclipse

So the syntax works and compile however I get an error message

````
save(json_file("https://cityio.media.mit.edu/api/table/update/gamaTable", matrixData));
````

````
2 occurrences in 2 agents at cycle 0: Java error: I/O error
in save json_file('https://cityio.media.mit.edu/api/table/update/gamaTable',matrixData) ;
FileNotFoundException: https://cityio.media.mit.edu/api/table/update/gamaTable
sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
java.net.URL.openStream(URL.java:1045)
msi.gama.util.file.GamaFile.fetchFromURL(GamaFile.java:108)
msi.gama.util.file.GamaFile.<init>(GamaFile.java:61)
msi.gama.util.file.GamaFile.<init>(GamaFile.java:132)
in save json_file('https://cityio.media.mit.edu/api/table/update/gamaTable',matrixData) ;
````

**Comment by agrignard** [comment]
BTW this is the minimal GAML file that does the GET and POST if you want to debug
[GAMA.zip](https://github.com/gama-platform/gama/files/1435413/GAMA.zip)

**Comment by AlexisDrogoul** [comment]
Make sure you clean-build GAMA before executing it. It has become almost mandatory now with all the work happening behind the scene with the processor.

**Comment by AlexisDrogoul** [comment]
Seems to work on my version, but I have no way to verify if the file is effectively uploaded...

**Comment by agrignard** [comment]
can you post a table call ```"https://cityio.media.mit.edu/api/table/update/gamaTableAlexis" ````

for instance?
BTW the cmd option failed on windows
````
Error in console command. 'curl' is not recognized ... bla bla bla
```

**Comment by agrignard** [comment]
Then you can see if your post was successful by going there

````
https://cityio.media.mit.edu/````and if it was ok the Alexis table should be here

**Comment by agrignard** [comment]
Mmm ok so after a clean-build-clean-build, it compiles and run without error but i doesn't create the table on the server

````
save(json_file("https://cityio.media.mit.edu/api/table/update/gamaTableArnaud", matrixData));
````

**Comment by sriramab** [comment]
Specific to your curl, As I said, the curl not found is because of the environment settings. It is different on windows and mac (and within mac versions). If you have the latest windows, then use bash instead of dos prompt. The other trick to work is to create a bash file (sh) that successfully does all you want. and call it via command operator. Largely this bash file should work on both mac and windows.

**Comment by AlexisDrogoul** [comment]
I have tried the model, and all I receive from posting is a response of 500, which indicates normally an Internal Server Error. Cant do much more now, as I need to sleep...

**Comment by agrignard** [comment]
Yep no rush it's already a good start let's see later. good night!

**Comment by hqnghi88** [comment]
This curl work (remove the single quote before and after @temp.json).
	string s<-command(" curl -X POST -H \"Content-Type: application/json\" -d @temp.json https://cityio.media.mit.edu/api/table/update/testTable");

Im trying the new save but no success.

**Comment by hqnghi88** [comment]
In the solution of Alexis, if i remove utf-8 from content type header (in gamajsonfile), it works. So may be some issue in the byte convert or the mit server dont accept utf-8?
@Override
	protected String getHttpContentType() {
		return "application/json";
	}

**Comment by AlexisDrogoul** [comment]
OK, @hqnghi88 , good catch. For other servers, not setting the encoding does not work.. Go figure !

So, I will post a temporary solution, knowing that the definitive one will allow, in the save statement, to add facets like: `charset`, `content_type` and maybe `method`.

**Comment by AlexisDrogoul** [comment]
@agrignard , is it normal that when I post the file to the server you provided, all the values are empty ? i.e. I post a JSON string with values for "grid", etc. and what I see on the server after it has been posted is: 

```
{"error":"","grid":[],"id":"","objects":[],"timestamp":1509611911745}
```

**Comment by hqnghi88** [comment]
Dear Alexis,
I just repost, it works. What did you post? it seem on server there have a json validator that accept only wellformed json.

**Comment by AlexisDrogoul** [comment]
@nghi88 I never said it doesn't work, I only ask if there is some kind of special treatment done on the server side, because the original JSON object is full of values, while the one posted to the server is empty (as in my previous comment). When I inspect this JSON object in GAMA, or when I save it to a local file, it is full like this:

```
{"grid":[{"rot":180,"x":13,"y":0,"type":-2},{"rot":180,"x":12,"y":0,"type":-1},{"rot":180,"x":11,"y":0,"type":2},{"rot":180,"x":10,"y":0,"type":5},{"rot":180,"x":9,"y":0,"type":0},{"rot":180,"x":8,"y":0,"type":2},{"rot":180,"x":7,"y":0,"type":-1},{"rot":180,"x":6,"y":0,"type":0},{"rot":180,"x":5,"y":0,"type":5},{"rot":180,"x":4,"y":0,"type":1},{"rot":180,"x":3,"y":0,"type":5},{"rot":180,"x":2,"y":0,"type":0},{"rot":180,"x":1,"y":0,"type":0},{"rot":180,"x":0,"y":0,"type":2},{"rot":180,"x":13,"y":1,"type":-2},{"rot":180,"x":12,"y":1,"type":1},{"rot":180,"x":11,"y":1,"type":2},{"rot":180,"x":10,"y":1,"type":-1},{"rot":180,"x":9,"y":1,"type":2},{"rot":180,"x":8,"y":1,"type":0},{"rot":180,"x":7,"y":1,"type":3},{"rot":180,"x":6,"y":1,"type":5},{"rot":180,"x":5,"y":1,"type":5},{"rot":180,"x":4,"y":1,"type":1},{"rot":180,"x":3,"y":1,"type":5},{"rot":180,"x":2,"y":1,"type":5},{"rot":180,"x":1,"y":1,"type":1},{"rot":180,"x":0,"y":1,"type":7},{"rot":180,"x":13,"y":2,"type":-2},{"rot":180,"x":12,"y":2,"type":2},{"rot":180,"x":11,"y":2,"type":0},{"rot":180,"x":10,"y":2,"type":-1},{"rot":180,"x":9,"y":2,"type":5},{"rot":180,"x":8,"y":2,"type":0},{"rot":180,"x":7,"y":2,"type":5},{"rot":180,"x":6,"y":2,"type":-2},{"rot":180,"x":5,"y":2,"type":-2},{"rot":180,"x":4,"y":2,"type":-2},{"rot":180,"x":3,"y":2,"type":-2},{"rot":180,"x":2,"y":2,"type":-2},{"rot":180,"x":1,"y":2,"type":-2},{"rot":180,"x":0,"y":2,"type":-2},{"rot":180,"x":13,"y":3,"type":-2},{"rot":180,"x":12,"y":3,"type":7},{"rot":180,"x":11,"y":3,"type":4},{"rot":180,"x":10,"y":3,"type":4},{"rot":180,"x":9,"y":3,"type":4},{"rot":180,"x":8,"y":3,"type":7},{"rot":180,"x":7,"y":3,"type":4},{"rot":180,"x":6,"y":3,"type":-2},{"rot":180,"x":5,"y":3,"type":-2},{"rot":180,"x":4,"y":3,"type":-2},{"rot":180,"x":3,"y":3,"type":-2},{"rot":180,"x":2,"y":3,"type":-2},{"rot":180,"x":1,"y":3,"type":-2},{"rot":180,"x":0,"y":3,"type":-2},{"rot":180,"x":13,"y":4,"type":-2},{"rot":180,"x":12,"y":4,"type":2},{"rot":180,"x":11,"y":4,"type":-1},{"rot":180,"x":10,"y":4,"type":4},{"rot":180,"x":9,"y":4,"type":-1},{"rot":180,"x":8,"y":4,"type":-1},{"rot":180,"x":7,"y":4,"type":-1},{"rot":180,"x":6,"y":4,"type":-2},{"rot":180,"x":5,"y":4,"type":-2},{"rot":180,"x":4,"y":4,"type":-2},{"rot":180,"x":3,"y":4,"type":-2},{"rot":180,"x":2,"y":4,"type":-2},{"rot":180,"x":1,"y":4,"type":-2},{"rot":180,"x":0,"y":4,"type":-2},{"rot":180,"x":13,"y":5,"type":-2},{"rot":180,"x":12,"y":5,"type":0},{"rot":180,"x":11,"y":5,"type":-1},{"rot":180,"x":10,"y":5,"type":-1},{"rot":180,"x":9,"y":5,"type":0},{"rot":180,"x":8,"y":5,"type":-1},{"rot":180,"x":7,"y":5,"type":5},{"rot":180,"x":6,"y":5,"type":-2},{"rot":180,"x":5,"y":5,"type":-2},{"rot":180,"x":4,"y":5,"type":-2},{"rot":180,"x":3,"y":5,"type":-2},{"rot":180,"x":2,"y":5,"type":-2},{"rot":180,"x":1,"y":5,"type":-2},{"rot":180,"x":0,"y":5,"type":-2},{"rot":180,"x":13,"y":6,"type":-2},{"rot":180,"x":12,"y":6,"type":7},{"rot":180,"x":11,"y":6,"type":0},{"rot":180,"x":10,"y":6,"type":0},{"rot":180,"x":9,"y":6,"type":-1},{"rot":180,"x":8,"y":6,"type":7},{"rot":180,"x":7,"y":6,"type":0},{"rot":180,"x":6,"y":6,"type":-2},{"rot":180,"x":5,"y":6,"type":-2},{"rot":180,"x":4,"y":6,"type":-2},{"rot":180,"x":3,"y":6,"type":-2},{"rot":180,"x":2,"y":6,"type":-2},{"rot":180,"x":1,"y":6,"type":-2},{"rot":180,"x":0,"y":6,"type":-2},{"rot":180,"x":13,"y":7,"type":7},{"rot":180,"x":12,"y":7,"type":4},{"rot":180,"x":11,"y":7,"type":7},{"rot":180,"x":10,"y":7,"type":-1},{"rot":180,"x":9,"y":7,"type":1},{"rot":180,"x":8,"y":7,"type":-1},{"rot":180,"x":7,"y":7,"type":0},{"rot":180,"x":6,"y":7,"type":-2},{"rot":180,"x":5,"y":7,"type":-2},{"rot":180,"x":4,"y":7,"type":-2},{"rot":180,"x":3,"y":7,"type":-2},{"rot":180,"x":2,"y":7,"type":-2},{"rot":180,"x":1,"y":7,"type":-2},{"rot":180,"x":0,"y":7,"type":-2},{"rot":180,"x":13,"y":8,"type":0},{"rot":180,"x":12,"y":8,"type":5},{"rot":180,"x":11,"y":8,"type":0},{"rot":180,"x":10,"y":8,"type":0},{"rot":180,"x":9,"y":8,"type":-1},{"rot":180,"x":8,"y":8,"type":5},{"rot":180,"x":7,"y":8,"type":1},{"rot":180,"x":6,"y":8,"type":7},{"rot":180,"x":5,"y":8,"type":0},{"rot":180,"x":4,"y":8,"type":-2},{"rot":180,"x":3,"y":8,"type":-2},{"rot":180,"x":2,"y":8,"type":-2},{"rot":180,"x":1,"y":8,"type":-2},{"rot":180,"x":0,"y":8,"type":-2},{"rot":180,"x":13,"y":9,"type":0},{"rot":180,"x":12,"y":9,"type":5},{"rot":180,"x":11,"y":9,"type":2},{"rot":180,"x":10,"y":9,"type":5},{"rot":180,"x":9,"y":9,"type":5},{"rot":180,"x":8,"y":9,"type":4},{"rot":180,"x":7,"y":9,"type":0},{"rot":180,"x":6,"y":9,"type":2},{"rot":180,"x":5,"y":9,"type":0},{"rot":180,"x":4,"y":9,"type":5},{"rot":180,"x":3,"y":9,"type":0},{"rot":180,"x":2,"y":9,"type":0},{"rot":180,"x":1,"y":9,"type":-2},{"rot":180,"x":0,"y":9,"type":-2},{"rot":180,"x":13,"y":10,"type":3},{"rot":180,"x":12,"y":10,"type":-1},{"rot":180,"x":11,"y":10,"type":5},{"rot":180,"x":10,"y":10,"type":4},{"rot":180,"x":9,"y":10,"type":2},{"rot":180,"x":8,"y":10,"type":7},{"rot":180,"x":7,"y":10,"type":0},{"rot":180,"x":6,"y":10,"type":1},{"rot":180,"x":5,"y":10,"type":0},{"rot":180,"x":4,"y":10,"type":0},{"rot":180,"x":3,"y":10,"type":0},{"rot":180,"x":2,"y":10,"type":-2},{"rot":180,"x":1,"y":10,"type":-2},{"rot":180,"x":0,"y":10,"type":-2},{"rot":180,"x":13,"y":11,"type":-2},{"rot":180,"x":12,"y":11,"type":-2},{"rot":180,"x":11,"y":11,"type":5},{"rot":180,"x":10,"y":11,"type":0},{"rot":180,"x":9,"y":11,"type":0},{"rot":180,"x":8,"y":11,"type":3},{"rot":180,"x":7,"y":11,"type":1},{"rot":180,"x":6,"y":11,"type":2},{"rot":180,"x":5,"y":11,"type":0},{"rot":180,"x":4,"y":11,"type":0},{"rot":180,"x":3,"y":11,"type":4},{"rot":180,"x":2,"y":11,"type":-2},{"rot":180,"x":1,"y":11,"type":-2},{"rot":180,"x":0,"y":11,"type":-2},{"rot":180,"x":13,"y":12,"type":-2},{"rot":180,"x":12,"y":12,"type":-2},{"rot":180,"x":11,"y":12,"type":-2},{"rot":180,"x":10,"y":12,"type":-2},{"rot":180,"x":9,"y":12,"type":-2},{"rot":180,"x":8,"y":12,"type":2},{"rot":180,"x":7,"y":12,"type":1},{"rot":180,"x":6,"y":12,"type":0},{"rot":180,"x":5,"y":12,"type":0},{"rot":180,"x":4,"y":12,"type":5},{"rot":180,"x":3,"y":12,"type":3},{"rot":180,"x":2,"y":12,"type":-2},{"rot":180,"x":1,"y":12,"type":-2},{"rot":180,"x":0,"y":12,"type":-2},{"rot":180,"x":13,"y":13,"type":-2},{"rot":180,"x":12,"y":13,"type":-2},{"rot":180,"x":11,"y":13,"type":-2},{"rot":180,"x":10,"y":13,"type":-2},{"rot":180,"x":9,"y":13,"type":-2},{"rot":180,"x":8,"y":13,"type":-2},{"rot":180,"x":7,"y":13,"type":-2},{"rot":180,"x":6,"y":13,"type":-2},{"rot":180,"x":5,"y":13,"type":5},{"rot":180,"x":4,"y":13,"type":2},{"rot":180,"x":3,"y":13,"type":-2},{"rot":180,"x":2,"y":13,"type":-2},{"rot":180,"x":1,"y":13,"type":-2},{"rot":180,"x":0,"y":13,"type":-2}],"objects":{"pop_mid":0,"dockID":2,"dockRotation":90,"pop_old":0,"density":[20,7,1,24,14,13],"toggle1":3,"toggle2":0,"toggle3":0,"toggle4":0,"pop_young":0,"IDMax":15,"slider1":0},"id":"","error":"","timestamp":2051314887}
```

when I post it to the website it is empty:

```
{"error":"","grid":[],"id":"","objects":[],"timestamp":1509611911745}
```

**Comment by hqnghi88** [comment]
Dear Alexis,
I mean it have full values on server. I've just repost into gamaTableAlexis, using the gaml code Arnaud sent above.

		matrixData <- json_file(cityIOurl).contents;
		cells <- matrixData["grid"];
		density_array <- matrixData["objects"]["density"];
		loop c over: cells {
			int x <- int(c["x"]);
			int y <- int(c["y"]);
            cityMatrix cell <- cityMatrix grid_at { x, y };
            cell.type <- int(c["type"]);
        }  
        matrixData.pairs>- matrixData.pairs[0];
        write "Save";
        save(json_file("https://cityio.media.mit.edu/api/table/update/testTable", matrixData));

**Comment by AlexisDrogoul** [comment]
... I dont get it. When I post, it is blank. I use the same code, everything is rigorously the same, except the Java code that I have slightly modified (but with no influence, normally, on the contents). Can you send me the GamaFile.java and GamaJSonFile.java files you are using to get this result ?

**Comment by hqnghi88** [comment]
Sorry, my fault, i have add after remote.flush() in GamaFile.java

				remote.flush();

			    int res = connection.getResponseCode();
			    System.out.println(res);
			    connection.disconnect();

It seem server need to complete the transaction (someone receive the respond from server) to modify the data?

**Comment by AlexisDrogoul** [comment]
No, remote.flush() was already there in my code. It was **my** fault (forgotten to close an output stream in the new code). I upload the changes, much more readable than the previous version, which seems to work well.

**Comment by agrignard** [comment]
Hi guys, with the 12hours jetlag I am just jumping in the conversation.
It sounds pretty cool no? I can see some https://cityio.media.mit.edu/api/table/gamaTableAlexis

**Comment by agrignard** [comment]
Congrats @AlexisDrogoul and @hqnghi88 this issue was open less than 24 hour ago and it is solved!! it's a big step for me in the lab as I will be able to send some Gama results to any other other tools.

I'll test this soon but it seems that it works perfectly!
