### ISSUE TITLE
Mousing over toolbar in full screen creates new black fullscreen

### ISSUE THREAD

**Issue by echen9898** [gama-platform/gama#2281]
### Steps to reproduce
1. When running a simulation in fullscreen, mousing over "Experiment: cycles elapsed" or the green simulation speed scaler creates a new black full screen window.

2. Video:
[https://drive.google.com/open?id=0BwhlGAqlmv7GbzI0NmtJdTFFOHc]

### System and version 
GAMA latest binary. New macbook pro 2016, OS Sierra

**Comment by agrignard** [comment]
Yep I also experience some strange behavior also when poping up either the timer or the slide duration, I guess its 2 instances of the same object "a kind of window on top of the main one).

**Comment by AlexisDrogoul** [comment]
Fullscreen mode under MacOSX has never really worked -- it is not entirely our fault, as Eclipse has a lot of troubles too. This bug is also present in versions anterior to Sierra. I will try to investigate, but I can't promise anything.

**Comment by AlexisDrogoul** [comment]
By the way, as a "workaround", you can set the preference "Maximize GAMA window at startup". It's not a real fullscreen mode, just a magnified window that covers all the screen, but it's better than nothing...

**Comment by agrignard** [comment]
Just a detail this issue is not only in fullscreen and Sierra as I mention above I have also some strange behavior (on El Captan) in a normal screen mode. (typically the little window will stay on top of all my window even if I switch to another application)

**Comment by sriramab** [comment]
no problem in my good old mavericks :)

**Comment by agrignard** [comment]
@sriramab it's kind of hard to reproduce, it happens once in a while so who knows it might happen also in mavericks

**Comment by AlexisDrogoul** [comment]
I have issued a fix for this problem, changing to a more conventional approach based on Dialogs for these pop-up elements. Note that fullscreen mode under MacOS continues to have problems, esp. with the fullscreen displays (both modes kind of conflict together and the fullscreen display loses its keyboard focus).
