### ISSUE TITLE
Disabling model menu in simulation mode

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2283]
### Steps to reproduce
1. Run any simulation. 

2.In simulation mode: do Model>Insert Template Global 

3. //or use any other template 

### Expected behavior
This menu should be disabled while in simulation model

### Actual behavior
User can insert any insert element and no error is raised if by chance the inserted code in the right place. For example I could insert a second global and the model gave no error. When I inserted global inside ask statement, it gave an error. 

I somehow feel that this behavior should be avoided. Or GAMA should say inserts are possible only in modeling mode.  And this accidental insertion by users / beginners can be avoided

If not so difficult, I would like to request disabling this whole model menu from the toolbar when in simulation mode.

I label this as interface bug, but please remove the bug tag as you may see neccessary.

**Comment by AlexisDrogoul** [comment]
The model menu will be on if editors are shown. Did you try to disable them
in the view menu? If the model menu is still there after,  then it is a
bug.

Le 4 nov. 2017 20:43, "Srirāma Bhamidipāti" <notifications@github.com> a
écrit :

**Comment by sriramab** [comment]
Yes, I entered the simulation mode and then from View>show/hide editor. Even then there is a model menu. And I switch off the editors, and then model>insert> global is still inserted where the cursor previously was and thus creating syntax error in the model.

**Comment by AlexisDrogoul** [comment]
OK. I have posted a simple fix for it.

**Comment by sriramab** [comment]
Thank you Alexis. This is fixed.
