### ISSUE TITLE
Binary Continuous release on windows cant expand any project.

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2284]
### Steps to reproduce
1.
I downloaded the continuous release
2.
I verified all the packages are updated (201711071106) so not problem with travis
3.
I cant expand any project in navigator (they are there, the validator shows errors, warnings of models)
![image](https://user-images.githubusercontent.com/6105384/32492436-db0ec2dc-c3ec-11e7-863d-170a265a6b85.png)

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Probably due to the modifications allowing models to be found in jar files.
Do you have a log? Is there any error?

Le 7 nov. 2017 12:53, "HUYNH Quang-Nghi" <notifications@github.com> a
écrit :

**Comment by hqnghi88** [comment]
i tessted witth  the reeleaasse offline, it fixed, i cantt download frrom github due to vietnam netwworrk problem butt it should work
