### ISSUE TITLE
operator any_of

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2285]
Hi,

I would like to request a new operator which is very similar to `one_of`. I would like to request something like `any_of` or `inside_any_of`.

`inside_any_of( [agent container], [agent container or species] )`

I often have to check if an agent is inside any of the agents of another particular species. For example I want to check if student or students are inside the classroom or in the playground. If tourists are inside their hotel or in a restaurant. If tourists are inside any of the museums in the city or inside any of the churches in the city. 

So if an agent is inside a polygon( church, museum, restaurant, classroom), I want to be able to count them or do some behaviour appropriate for that polygon. 

Currently, the solution involves an ask statement, some overlaps operators, some inside operators. I am wondering if this could be simplified along the lines of `one_of`. So that I could write a statement:

``` bool in_restaurant<- self inside (any_of(restaurants_in_city)) ; ```

So the `any_of` loops self through each of the agent in `restaurants_in_city`;

May be my syntax is not so appropriate, but I hope I am able to make my request clear :) 

Thank you.

**Comment by benoitgaudou** [comment]
Hi,

Could you write something like testing that the set of restaurant
overlapping self is not empty ?
something like :

bool in_restaurant <- !empty(restaurants_in_city ovelapping (self)) ;
?

Benoit

2017-11-13 17:02 GMT+01:00 Srirāma Bhamidipāti <notifications@github.com>:

**Comment by hqnghi88** [comment]
Hi,
Just a small note with Benoit solution, because you said "often have to check", if the speed is your need not only the syntax, please see https://github.com/gama-platform/gama/wiki/OptimizingModels#container-of-agents-in-closestto-atdistance-overlapping-inside . So
bool in_restaurant <- !empty((restaurants_in_city at_distance 10 ) ovelapping (self)) ;
will speed up a little bit.

**Comment by sriramab** [comment]
Hi Thank you for the suggestions. Patrick also once suggested something similar. But .....

Now, here is my sample code. I do not get the desired results or I do not understand the overlapping operator. My understanding is that I am checking if the geometry of left hand operand is overlapping with geometry of right hand operand? For simplicity I just use one polygon and one agent and agent is placed (forcefully) inside the polygon. 

```
model over

global{
	
	init{
		
		create polygons number:1{
			shape<-square(10);
		}
		create rounds number:1{
			shape <-circle(1);
			location <- polygons[0].location;
		}
		
//		if !empty(rounds overlapping polygons[0]){
//			write "hello";
//		} else{
//			write "empty";
//		}
		
		
		
	}
	
}


species rounds{
	
	init{
		bool in_polygons <-empty(polygons overlapping (self));
		write in_polygons;
	}
	aspect a{
		draw shape color:#red;
	}
	
}

species polygons{
	aspect a{
		draw shape color:#green;
	}
}
experiment overlaps_inside{
	output{
		display first type:opengl{
			
			
			species polygons aspect:a;
			species rounds aspect:a;// position:{0,0,0.16};
			
		}
	}
}
```

**Comment by sriramab** [comment]
I notice that the overlapping works with cube and sphere but not with square and circle. 😞

**Comment by hqnghi88** [comment]
With my test, it was the problem of initialization, you have 2 place , one is the init declared inside species, one is the sequence in the create. The  execution order is init in species first then the create sequence. So when you write the value, the location and the shape of rounds species are not set.

**Comment by sriramab** [comment]
Yes, that is my understudying also. But I wonder why it worked with other geometries like cube and sphere.

**Comment by hqnghi88** [comment]
can you post again the code works with cube and sphere, because i really can't make it works

**Comment by sriramab** [comment]
```
model over

global{
	
	init{
		
		create polygons number:1{
			shape<-cube(10);
		}
		create rounds number:1{
			shape <-sphere(1);
			location <- polygons[0].location;
		}
		
//		if !empty(rounds overlapping polygons[0]){
//			write "hello";
//		} else{
//			write "empty";
//		}
		
		
		
	}
	
}


species rounds{
	
	init{
		bool in_polygons <-empty(polygons overlapping (self));
		write in_polygons;
	}
	aspect a{
		draw shape color:#red;
	}
	
}

species polygons{
	aspect a{
		draw shape color:#green;
	}
}
experiment overlaps_inside{
	output{
		display first type:opengl{
			
			
			species polygons aspect:a;
			species rounds aspect:a;// position:{0,0,0.16};
			
		}
	}
}
```

**Comment by hqnghi88** [comment]
Hello Sriri,
With your code it return true, it means fail (because you missed a ! )? do you get a "false"?

**Comment by sriramab** [comment]
Yes, it works as desired in sphere and cube, but it does not with circle and square.

**Comment by AlexisDrogoul** [comment]
Works with both for me (as it should). I close the issue -- feel free to reopen if it appears again !
