### ISSUE TITLE
Overlay positon not totally fix

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2288]
I definitely have lots of minor problems with all those updates...

So one more slight change that I notice between the last release  and a version that was running well few weeks ago (of course impossible to know which exact version it was as it s hard to know if the update is really updating or not.

I just notice that the overlay layers is now "moving" a bit on the screen whereas it was not moving at all in the previous version.

So now it's maybe a detail but for a layer that is suppose to be fixed it's not exactly fixed. On this specific model it moves sometime 

https://github.com/mitmedialab/CityScope_GAMA/blob/master/CPG_CityScope_GAMA/models/game_it_v1.0.gaml

**Comment by AlexisDrogoul** [comment]
Overlay is still broken on OpenGL. Basically it has never worked correctly (launch displays with or without the console / editors view and you'll see the difference !). And I have noticed the move in several models as well, by the way. However, I have no particular desire to work on this part in the coming months, so anyone is welcome to take over the work.

**Comment by agrignard** [comment]
The strange things is that it was working well(no little move) in a previous binary (around one month ago).

**Comment by AlexisDrogoul** [comment]
Added to the OpenGL issues tracker (#2209)
