### ISSUE TITLE
Control simulation with Launchpad interface

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2292]
I would be interested to control a simualtion with a Launchpad (e.g https://global.novationmusic.com/launch/launchpad-mini#).

There is already some java API (https://github.com/OlivierCroisier/LP4J) to do that it might be maybe no so hard to add it in GAMA.

**Comment by benoitgaudou** [comment]
Hi,

Will you bring one LaunchPad to the next Coding Camp, so that we can have
fun testing such a feature ?

Benoit

2017-11-17 23:17 GMT+01:00 Arnaud Grignard <notifications@github.com>:

**Comment by agrignard** [comment]
Yep I just ordered one, I hope it will be ready for the end of the next so I can travel with it

**Comment by AlexisDrogoul** [comment]
Guess we can close this issue :)

**Comment by agrignard** [comment]
Yep it is actually working  using a dedicated world skills available in an experimental plugins. 

I'll try to document it soon
