### ISSUE TITLE
charts: thickness facet on data vs datalist

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2294]
### Steps to reproduce
1. Open Series Examples.gaml in features folder of the library

2. in charts of datalist statement, try to add a thickness facet. 

### Expected behaviour
I expect the thickness facet to be correct syntax 

### Actual behaviour
thickness facet is accepted by data charts but not by datalist charts. There is a syntax error with unidentified `thickness:` facet

May be somewhere is just a missing line of code that allows datalist also to accept the thickness facet?

**Comment by pcaillou** [comment]
solved
