### ISSUE TITLE
Gama filling up log files

### ISSUE THREAD

**Issue by ierpe** [gama-platform/gama#2295]
### Steps to reproduce
1. Launch Gama with Debian Stable

2. tail or cat /var/logs/messages, /var/logs/syslog or /var/logs/uer.log

### The error : 
`Allocating size to SwtFixed 0x7f643d43d840 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?`
keeps occurring and fills up the log files, becoming quickly huge
Also, my computer heats up because it's always writing the logs...

### System and version 
GAMA Platform - V1.7.0
openjdk version "1.8.0_151"
Debian 9.2 (x86-64)

(if necessary, copy Help>Installation Details>Configuration in GAMA : btw Installation Details does not open on my OS

**Comment by AlexisDrogoul** [comment]
Hi,

Seems to be a bug with GTK 3.2 onward. See for instance https://bugs.eclipse.org/bugs/show_bug.cgi?id=486068

No immediate solution is available (except moving to Eclipse 4.7, in which the SWT version has been updated to remove the warnings) is available. One temporary fix can however be found in the comments of this discussion (https://www.eclipse.org/forums/index.php/t/1081230/): 

```
export SWT_GTK3=0
./gama
```

should work. Can you please try it and report back if it (temporarily) fixes the problem ? 

Another solution (but I have yet to test it) would be to build GAMA with the latest SWT library available. I'll try it sometime next week.

**Comment by ierpe** [comment]
Hi, thanks for the answer.

The temporary fix solves the problem yes. Much better for me while waiting a real fix :)

Let's keep the issue opened until you try a new build then.

**Comment by AlexisDrogoul** [comment]
The new build (with a correct version of SWT) is now available:  https://github.com/gama-platform/gama/releases/tag/oxygenCI

**Comment by AlexisDrogoul** [comment]
Warnings have been removed (as far as I am aware of it). Please reopen this issue if it is not the case.
