### ISSUE TITLE
Color 'green' is not green

### ISSUE THREAD

**Issue by DoryanKaced** [gama-platform/gama#2298]
### Steps to reproduce
1. 
rgb('green').green 

### Expected behavior
It should be 255

### Actual behavior
It shows 128

### System and version 
Gama 1.7
Java 8
MacOS
<img width="172" alt="screen shot 2017-12-03 at 00 13 08" src="https://user-images.githubusercontent.com/17123471/33517904-cc1a2e8e-d7be-11e7-9958-d57725030d66.png">

**Comment by agrignard** [comment]
Yes indeed GamaColor (that rely on awt color)  when you ask the 'green' color it produces rgb(0,128,0) for the green color. If you try rgb(0,255,0) you will have a much more lighter green that corresponds (something like rgb("lightgreen"))
