### ISSUE TITLE
Adding information about tests in GAML

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#2299]
This is more like an enhancement to make when using tests. 
Basically, you can do two kinds of tests now : 
* one inside the annotations (@test)
* one using gaml inside the GAMA Platform (asserts)
Since we have no way to know, on GAMA Platform side, if an operator has already been tested in the annotations, it could be quite useful to add an information icon (or warning icon) to inform the user using a GAML test that the operator he is currently testing has already been tested in the annotations.

**Comment by AlexisDrogoul** [comment]
Hi,

For me it would be overcomplicated to do this, as we have no safe way of knowing in which way the @tests cover or not the different operands; moreover, what should we tell when tests cover several operators at once ?

So I propose to close this one -- but I'm still open to new ways of displaying information about existing tests...

Cheers
Alexis
