### ISSUE TITLE
ability to select agents in the browse / inspect statement

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2301]
Hi, 

I would like to request a slight enhancement in the browse / inspect statement of output. Currently, browse or inspect statements can display one of, (manual) list of or all agents of a species. It would be nice to be able to select agents based on a criteria, perhaps in the style of - `select where` / `collect where` statements.

thank you

**Comment by AlexisDrogoul** [comment]
Actually it works and it has always worked. `browse my_agents where each.location.x > 0;` or `inspect my_agents first_with each.location.x > 50;` are perfectly accepted sentences.
