### ISSUE TITLE
sliders / dropdowns in inspect window

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2302]
Hi

As discussed, to create the illusion of multiple parameter-view panels, I would like to request the possibility to have like a slider and/or drop down controls that can have live interaction to a simulation. Currently a button like control can be shown with a boolean attribute. It is also possible now to have a step-up step-down control with min: max: facets. So, it would be nice to extend this to show a slider or drop down . 

the intention is to use this for participatory modelling where inspect windows may be used as control centers for participants to interact with the simulation model. Then, I would arrange these inspect windows to the four or more corners  of gama and the participants can interact with the controls from their own corner. 

I am also wondering if these windows can be made to float when display is on full screen mode. If this floating is possible, I feel that I can already bring my stakeholder interaction to a touch screen.

**Comment by AlexisDrogoul** [comment]
I had to make a very small change to address this. Drop-downs are available (as they always were) when defining a variable with the `among:` facet, while sliders are now available by default if the `min:`, `max:` and `step:` facets are correctly defined for a number variable.
