### ISSUE TITLE
Gama crashes when using write and division by zero with opengl

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2303]
When trying to write a division by zero in an aspect, Gama crashes when the display is opengl.

aspect base{
     write 2/0;
}

**Comment by hqnghi88** [comment]
![image](https://user-images.githubusercontent.com/6105384/33612542-6ec1010c-da04-11e7-9308-2103557bbd09.png)
I cant do it, how to by pass validation error

**Comment by AlexisDrogoul** [comment]
Hi,

Seems to only happen in a very specific configuration (after different tests in different environments) and this is probably related to the error handling of the OpenGL context of your machine (a MBA w/o a good graphic card). On other environments, either it passes or it fails with an error depending on your preferences. There is no real way to circumvent it, unfortunately, so I close this issue. 

Alexis
