### ISSUE TITLE
syntax highlighting for gaml in Github code blocks

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2304]
Hi,

I have been wondering if it is possible to have some custom gaml highlighting for code blocks in github markdown. For example, if you use a code block ```code block``` with a language preference for r , it highlights r keywords as below 

```r
library(gaml)
k=mean(rnorm(100,1,0.1)
```

or for python as below:

```python
import numpy as n
float f = n.sin(90)
```

or java as below:

```java
import numpy
float f = n.sin(90);
```

Is it possible to create a custom syntax highlight for gaml language on github markdown? I do not know how easy or difficult it is, but could be nice in sharing or exhibiting code on github tutorials.

**Comment by AlexisDrogoul** [comment]
This better belongs to the documentation issues, I believe.

**Comment by sriramab** [comment]
this has now reference to  gama-platform/gama.doc#34
