### ISSUE TITLE
Bug with reloading the current experiment ? 

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#2306]
### Steps to reproduce
1. Open the following model and launch the experiment. Change the value of the parameters in the parameters view to an other number, and reloads the experiment.
````

model test

/* Insert your model definition here */
global
{
	int nb_agents;
	
	init
	{
		create example number: nb_agents;
	}
}
species example
{
	aspect default
	{
		draw circle(1) color:#red;
	}
}
experiment "launch experiment" type:gui
{
	parameter "Number of agents" var:nb_agents <-10;
	
	output
	{
		display "example species"
		{
			species example aspect: default;
		}
	}
}

````
### Expected behavior
When modifying the number in the parameters view, and pressing reloading the experiment, it should takes into account the number modified (I used this a lot before to just try an experiment with different number values used only at the init). So if I change the value from ten to one in the parameters view, and reload the experiment, the experiment should have only one agent displayed, not ten.

### Actual behavior
Now it reinitializes the number to its "original" value (the one written in the model). 

So I don't know if it is a voluntary behavior change, but if so, I would like to request to have an other button that will take the modification done in the parameters view to initialize the model, and not revert the values of the parameters too, because we already have a button to revert to the initial values of the parameters. 

### System and version 
Git

**Comment by AlexisDrogoul** [comment]
Yep -- clearly a bug, probably introduced not so long ago... I will check.
