### ISSUE TITLE
sample on list of lists

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2310]
Hi,

I would like to use the sample function on list of lists. Currently the sample function only works on lists. When I use list of lists in the sample function, the result is always nil. Therefore I would like to request that the sample function also accept list of lists, so that it can return me a list from that list of lists.

thank you
Srirama

**Comment by benoitgaudou** [comment]
Hi Srirama,
I am not sure I have completely understood your question, but you can use the sample function with a list of list such as in the following model:

```
model Test

global {	
	reflex toto {
		container var0 <- sample([[2,10],[1],[3,6,3]],2,false);     
		write var0;
	}
}

experiment Test type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
	}
}
```

I let you close the issue if it matches with your expectations.

Cheers

Benoit

**Comment by sriramab** [comment]
Seems to work now. I will try on the original problem where I had a problem. I close for now.
