### ISSUE TITLE
copy paste / delete / rename / drag&drop all .shp and its associated files

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2313]
Hi,

Currently it seems that when you copy a shapefile using the project navigator, the paste only pastes .shp and not all the associated files of this shapefile. 

Would it be possible to have this feature to copy all associated files of a .shp when using copy/paste.

Thank you.

MacOS Sierra, GAMA 21.Dec.2017 Standalone.

**Comment by sriramab** [comment]
Thank you for this correction, but on the flip side... deleting shp file should also delete its associated files. Currently it only deletes the .shp file. Could you please make this change.

**Comment by AlexisDrogoul** [comment]
Hi Srirama, it's coming in the next commit.

**Comment by sriramab** [comment]
@AlexisDrogoul something related, renaming a shapefile in project navigation pane , does not rename all associated files of that .shp. Please could you check.

**Comment by benoitgaudou** [comment]
I  checked the following operation:
- rename: works
- delete: works
- copy  /  paste: works

but:
- move (drag and drop): doesn't work: it  only  moves the  .shp file

**Comment by benoitgaudou** [comment]
This works!
