### ISSUE TITLE
Documentation generation is broken

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#232]
**Describe the bug**
See this job for [example](https://github.com/gama-platform/gama/actions/runs/9693299853/job/26748460481).
It has been going on for more than 3 weeks from what I can see

**Comment by lesquoyb** [comment]
Seems to be repaired, I have seen some changes I made in the wiki on the current running website so the process went to its end. But I'm unable to see any change that I should have seen from the changes in the `DocProcessor.java` class (and others) brought by the pr #230 . @RoiArthurB, @benoitgaudou any idea where the problem might come from ?
Is it possible that the gha skipped the generation and/or used old xml files ?
Is it the way that the docprocessor class works that changed and should be called differently ?
Is it the code of docprocessor that is at fault and actually not doing anything different ?
Anything else ?
And as everyone is super busy I can investigate that myself if you give me pointers on how to proceed/what to check, but I must admit that rn I'm a bit clueless

**Comment by lesquoyb** [comment]
still not fixed in production, see [this job](https://github.com/gama-platform/gama/actions/runs/9770935450/job/26972914294)

**Comment by RoiArthurB** [comment]
Fixed with 3804b53 :) And validated in https://github.com/gama-platform/gama/actions/runs/9885574198
