### ISSUE TITLE
GEOTIFF File Import.gaml broken

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2321]
### Steps to reproduce
1. Run 1. Try to run GEOTIFF File Import.gaml

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
2 occurrences in 2 agents at cycle 0ÿ÷The format of bogota_grid.tif is not correct. Error: The format of bogota_grid.tif is not correct. Error: java.lang.IllegalArgumentException: input not a RandomAccessFile!

### System and version 
GAMA 1.8

**Comment by agrignard** [comment]
and then I guess its related Multi Raster Files import.gaml is also broken

**Comment by benoitgaudou** [comment]
I just checked this issue on GAMA Git Oxygen (a.k.a. the future GAMA 1.8), and I was not able to reproduce it.
By the way I get this issue on GAMA Git Mars (1.7), after few time of working, but I was not able to reproduce it later.

**Comment by agrignard** [comment]
Ok so it seems to be fixed on GAMA1.8_Mac_64_03.12.18_cc8afd1
