### ISSUE TITLE
Voronoi - closest_to : problem with SpatialIndexes?

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2324]
### Steps to reproduce
1. Open and run the voronoi model

### Actual behavior
GAMA Freezes.
The problem comes from the closest_to computation (center closest_to self.location).
This computation is supposed to be done in the World (continuous) topology, but sometimes I get an error in the GamaSpatialMatrix class (which is confirmed by the debugger).

### System and version 
Github Mars version

**Comment by ptaillandier** [comment]
Ok, after investigating the problem, the issue comes from this [commit](https://github.com/gama-platform/gama/commit/d1f1a2f13483ae57f0e85ae70ed2e8f37da82b06#diff-f239742651c290132e2e590e7d48066f) of Alexis linked to issue #2239.

More particularly, it is linked to this line:
if (id != null) { return firstAtDistance(scope, source, f, id); }
that was changed by:
if (id != rootIndex) { return firstAtDistance(scope, source, f, id); }

So, now, all the computations in which the rootIndex is concerned (all spatial continuous computation?) ask all the spatialIndexes to make the computation.... which is very very slow (and maybe wrong) when a grid is concerned. By just modifying (id != rootIndex) by (id != null) it works again.

As for me, making GAMA works normally is more important than the multi-level, I committed the "dirty" fix (rootIndex replaced by null), but I let this issue open to find a better solution.

**Comment by hqnghi88** [comment]
Dear Patrick,
Thank you, i 've just tested with the #2239 and it seem to work normally, the modification of Alexis is more complex than an equal comparison. I must investigate more if it have ghost effect. 
By the way, from when voronoi become Spheres instead of block of grid? or it just appear only for me.

**Comment by ptaillandier** [comment]
Ok, so we can close this issue now, and you can open a new issue about multi-modeling if necessary.
BTW, I simplified the voronoi model to have something more classical.
