### ISSUE TITLE
GAMA is stucked when searching for path inside disconnected graph

### ISSUE THREAD

**Issue by asaval** [gama-platform/gama#2325]
### Steps to reproduce
1. load a disconnected graph

2. when searching for a path between two non-connected nodes return a non visible NPE, hanging the simulation in the current state

### Expected behavior
GAMA should not hang if no path is available

### Actual behavior
Simulation is stuck in the same state 

### System and version 
GAMA from github repo with Mars

**Comment by ptaillandier** [comment]
It seems that someones (from Rouen?) has fixes this issue and it seems to work well now
