### ISSUE TITLE
Save Statement Broken?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2328]
### Steps to reproduce
1.Not really sure if its a bug or not 

2. When running SavetoCSV.gaml there is only one line in the bug.csv

3.

### Expected behavior
I would expect to have 50 lines (one per agent no?)

### Actual behavior
Only one line about bug49

### System and version 
Last build run from Eclipse Mars

**Comment by sriramab** [comment]
May be you need the rewrite facet of save statement?

**Comment by hqnghi88** [comment]
HI,
I confirm that using rewrite:false i had 50 lines.
Cheers.

**Comment by agrignard** [comment]
Can we put rewrite:true by default no?

**Comment by benoitgaudou** [comment]
I set the rewrite facet to false in the model, in order to save all the agents, in the commit cf6fa53d27e4450eb11314cd77f55a045b2b13a6
