### ISSUE TITLE
It is possible to create a project inside the "library models" container

### ISSUE THREAD

**Issue by grmpfhmbl** [gama-platform/gama#2330]
### Steps to reproduce

1. Right click on the "Library Models" container folder. (works with Plugin models as well)

2. Select "new -> GAMA project"

3. Finish the new project wizard.

### Expected behavior

I'd expect that the shipped models library is read-only. Either there is no "new" in the context menu of those containers, or the model will be shown under "User Models" despite the fact I clicked on a different container.

### Actual behavior

The new project appears in the "Library Models" container - see attached screenshot. The project will be saved in the workspace folder (as I would expect). So I can delete it from the "Library Models" container and re-import on "User Models".

![screenshot 2018-03-05 14 33 28](https://user-images.githubusercontent.com/5475895/36978390-a71de666-2084-11e8-8c5f-ca784f657da5.png)

### System and version 

- GAMA 1.7RC2 (22.04.2017)
- GAMA 1.7 (GAMA1.7 02.19.18_9f30b0a - continuous build)
- GAMA 1.8 (oxygenCI Tag release)

on MacOS 10.10.5, MacOS 10.12.5 both Java 1.8.0_131
and Win10 - Java  1.8.0_162

**Comment by benoitgaudou** [comment]
A small addition, when I try to create a project, from the dev version, in Debug mode and step by step, I do not have this issue anymore...

**Comment by AlexisDrogoul** [comment]
Actually, this behaviour is not a bug, rather an undocumented feature allowing users to place their models wherever they want. I understand, however, that this might confuse some users and so I chose to refine a bit the filter for displaying menus. New > Gama Project... will only appear when no selection is made, or when Users Folder is selected -- same for Import > Gama Project... It will prevent to accidentally create projects in the wrong place.
