### ISSUE TITLE
Revert to original values is gray does nothing if manual changes are made

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2331]
### Steps to reproduce
1. Open any model that has parameters. I tried regression.gaml in the library.

2. change x or y values that have input boxes, I did not check with dropdown or slider.

3. then try change values by manual entering a different value and not by + or -

### Expected behavior
If I press revert to original, original values should be restored. Basically the revert button is gray. It is active only when used with + or -

### Actual behavior
revert button is gray and therefore does not detect manual changes.

**The same applies to the large red revert button for whole model.**

### System and version 
MacOS Sierra, GAMA standalone of 5 march 2018

**Comment by hqnghi88** [comment]
Hi,
I tested on MacOs with Continuos release 6 March, i cant reproduce this issue. Manual adjust or button adjust both show the revert button. And it return re previous value when clicked

**Comment by sriramab** [comment]
Hmm, I updated some old version to the latest. Perhaps you downloaded a new one and it has different behavior? because i still have this problem on my machine. Then i should download new GAMA ? i hate to download it many times :(

**Comment by benoitgaudou** [comment]
I tried on the GAMA Git version and was not able to get this issue.
Do you still have it ?

**Comment by sriramab** [comment]
Yes, it is still a problem on GAMA that is updated and it seems not a problem on new download. May be you can tag as low-priority?

**Comment by AlexisDrogoul** [comment]
I close this issue as updates have had some problems during feb/mar, which seem to be solved now.
