### ISSUE TITLE
Urban growth model

### ISSUE THREAD

**Issue by gwallentin** [gama-platform/gama#2333]
### Steps to reproduce
1. Open Views -> Preferences -> External and set "Let GAMA decide wich CRS to use to project data" to false,
2.  change the default CRS epsg:32648 (Vietnam) to any other CRS, e.g. 4326.
3. set "Let GAMA decide wich CRS to use to project data" back to true again and save the settings
4. Run the Model Library Toy Model "Urban Growth"

### Expected behavior
The model would run without problems

### Actual behavior
The model throws a runtime error at initialisation.

### System and version 
GAMA 1.7 RC2

### suggested bug fix
The cantho_1999_v6.prj is empty. Fill this file with the correct CRS (epsg: 32648) 
* download from here: http://spatialreference.org/ref/epsg/wgs-84-utm-zone-48n/ and change the name to cantho_1999_v6.prj  OR
* use the attached file in my previous bug report: https://groups.google.com/forum/#!topic/gama-platform/lEKTcLZW7Ks

**Comment by ptaillandier** [comment]
Thanks, the problem comes indeed from the fact to the prj file of cantho_1999_v6.asc was empty.
I added to this data the right prj and it is now working.
