### ISSUE TITLE
error caused by masked_by in the Library model "continuous field of vision"

### ISSUE THREAD

**Issue by gwallentin** [gama-platform/gama#2334]
### Steps to reproduce
1. Run the GAMA library model - Feature models - Agent Perception - continuous field of vision.
2. Let it run for some time.
3. This report actually reopens issue #2214

### Expected behavior
The model would run forever without error

### Actual behavior
At some point it throws a runtime errror (the same error comes up much faster in more complex geometries): 
Java error: exception in JTS library
in perceived_area <- masked_by(perceived_area,obstacle,precision);

### System and version 
GAMA 1.7 RC2

**Comment by ptaillandier** [comment]
With the last version of GAMA (https://github.com/gama-platform/gama/releases/tag/latest), I was not able to reproduce this bug.  Could you test it?

**Comment by gwallentin** [comment]
Dear Patrick,
I confirm that the issue is resolved with the latest version.
thanks, Gudrun
