### ISSUE TITLE
Shortest Path algorithm issues

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2340]
### Steps to reproduce
1. Run the Features / Agent movement / Goto network.gaml

2. Change the Type of optimizers

### Expected behavior
All types of optimizers should works.

### Actual behavior
some of the optimizers do not work:
- Dijkstra : only some agents move to the target (the other ones do not move).
- BellmannFord : at the first step, I get the following Exception:

<img width="590" alt="capture d ecran 2018-03-13 a 13 39 24" src="https://user-images.githubusercontent.com/1555274/37342156-03a482e2-26c4-11e8-8f46-eaa3b8605389.png">

### System and version 
GAMA 1.8 pre-release
(I do not get it on the GAMA Git Mars version, without being able to test on the 1.7 nightybuilt)

**Comment by ptaillandier** [comment]
I tested it on GAMA 1.7 (nightly built) and it works well, so I suppose it is due to the modification of the version of jgrapht.

**Comment by AlexisDrogoul** [comment]
I suppose it is the new version of JGraphT the problem, as well. Which is a bit annoying to say the least... @hqnghi88 do you think we can revert commit https://github.com/gama-platform/gama/commit/25bc6b12dca069c5d424d5bf9ea31af450401d6a without breaking everything?  There are some stuff in it unrelated to graphs, but they don't target specific bugs as far as i can see.

**Comment by hqnghi88** [comment]
Yes we can easily do it. You mean revert the jgrapht 1.10 to 1.01?

**Comment by AlexisDrogoul** [comment]
Well, revert the whole commit. Because it implied modifications on many different aspects (graph interfaces, etc.). Hopefully it won't break any of the merges done in https://github.com/gama-platform/gama/commit/2e9dc9e343128a2e92eaa71885ebcdac5c1ada87 and https://github.com/gama-platform/gama/commit/33f7c65d5465d3b5a2b79725846305fd280427d9 ...

**Comment by hqnghi88** [comment]
Well, these two merge should be redo but as i experienced, it seems to be easier because the change of jgrapht was complicated to be merged in these two commits (i dont know it was correctly merged)

**Comment by sriramab** [comment]
I think there are some still issues. I opened a related issue.
