### ISSUE TITLE
OSM File Import from Internet

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2342]
When loading the experiment Load OSM from Internet

1 occurence in Load OSM from Internet0 at cycle 0: Java error: WebbException
WebbException: Request failed: 404 Not Found
msi.gama.util.file.http.Response.ensureSuccess(Response.java:210)
msi.gama.util.file.http.Webb.execute(Webb.java:315)
msi.gama.util.file.http.Request.asStream(Request.java:372)
msi.gama.util.file.GamaFile.fetchFromURL(GamaFile.java:121)
msi.gama.util.file.GamaOsmFile.fetchFromURL(GamaOsmFile.java:308)
msi.gama.util.file.GamaFile.<init>(GamaFile.java:71)
msi.gama.util.file.GamaFile.<init>(GamaFile.java:58)
in agent Load OSM from Internet0

-------------------------------------------------------------
GAMA1.8_Mac_64_03.12.18_cc8afd1

**Comment by benoitgaudou** [comment]
It seems that the URL is not available anymore:
https://s3.amazonaws.com/metro-extracts.mapzen.com/hanoi_vietnam.osm.pbf

Anyone has a better link ?

**Comment by benoitgaudou** [comment]
Issue fixed in commit c1b389dab75733aba2ac0538fbdca1e6f79d5402  thanks to new data URL from @ptaillandier on the Andorra road network
