### ISSUE TITLE
Abstract actions with a parameter

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2343]
### Steps to reproduce
1. See the following model:

```
model NewModel

global {
	init {
		create enf number: 10;
		
		ask agents of_generic_species(papa) {
			do GPM;
			do GPMparam(10);
		}
	}
}

species papa {
	action GPM virtual: true;

	action GPMparam(int t) virtual: true { }
}

species enf parent: papa {

	action GPM {
		write "toto " + self;
	}

	action GPMparam(int tot) {
		write tot;
	}
}

experiment name type: gui {
	output {}
}
```

### Expected behavior
The following action should be written:
```
	action GPMparam(int t) virtual: true ;
```

### Actual behavior
But the following writing triggers a compilation error.
```
	action GPMparam(int t) virtual: true ;
```

If I write it like that:
```
	action GPMparam(int t) virtual: true { }
```
When I implement it in a subspecies, the parameter has the value nil.

### System and version 
GAMA 1.8 pre-release.

**Comment by AlexisDrogoul** [comment]
I have identified the problem: the types and names of parameters must be identical. Will issue a fix soon in the form of an error if the signatures of the two actions are not exactly equivalent.
