### ISSUE TITLE
Save to Georeferenced Image

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2344]
### Steps to reproduce
1. In the model library, run the model Features / Save Statement / Save to Georeferenced Image.gaml

2. Look at the saved image

### Expected behavior
The produced image should contains 50 x 50 pixels

### Actual behavior
Instead the image grid.png is empty (and displayed in GAMA with a dimension -1 x -1.

### System and version 
GAMA 1.8 pre-released, and GAMA 1.7 Git

**Comment by ptaillandier** [comment]
It seems to be linked to JAI.
I got this error when trying to save the grid as a png, bmp or jpg image. Note that I can save the data as a tif or gif (at least I have no error... but the image is black) :
java.lang.RuntimeException: - Unable to render RenderedOp for this operation.
	at javax.media.jai.RenderedOp.createInstance(RenderedOp.java:827)

If we cannot find a solution, I can change the image type from png to tif.

**Comment by AlexisDrogoul** [comment]
Now tracked under #1362.
