### ISSUE TITLE
Multi-level Exceptions in displays

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2345]
### Steps to reproduce
1. Run the model: Library models / Features / Multi Level Usage / Balls, Groups and Clouds

2. Run each experiment

### Expected behavior
Works without Exception

### Actual behavior
The model seems to work perfectly, but in the console many Exception appears (ion both experiments):
- java.util.ConcurrentModificationException
- java.lang.ClassCastException: java.lang.Boolean cannot be cast to msi.gama.util.IContainer
- java.lang.NullPointerException

### System and version 
GAMA Git Mars & Oxygen, MAcOSX

**Comment by hqnghi88** [comment]
It still have some concurrency must be fixed. But I realized the mechanism of multi level have so many adding/removing object in a simulation step (migrate, capture statement of macro micro agents). So most of these errors come from the fact that opengl (or display) cannot draw or access the geometry of a dead agent (which is capture in macro agent or migrated, released macro agent). I ve try with the synchronize button in display , which mean no gap of "living agents" and "drawing agents", it would eliminate some execption.
