### ISSUE TITLE
Voronoi.gaml

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2347]
### Steps to reproduce
1. run the model Toy models / Voronoi.gaml

### Expected behavior
The Voronoi shapes on a simple 2D space.

### Actual behavior
I get the agents as sphere and the Voronoi surfaces do not appear.
In addition the simulation cannot make even 1 step.

Note that Patrick has made a correction recently in the master branch, about this model, so there is only a need of merging commit on the Osygen branch.

### System and version 
GAMA 1.8 preRelease

**Comment by hqnghi88** [comment]
i ve just bring to oxygen up to this commit https://github.com/gama-platform/gama/commit/bf1b077ae27b805c5d25ab00da90a09350dd3bb5 . This issue should be fixed in 15 mins when travis produce release to test
