### ISSUE TITLE
Headless does not run

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2352]
### Steps to reproduce
1. Get the last release 

2. Run GAMA in headless mode from the console following the Wiki command (in the Gama folder):
```
MacBook-Pro-de-ben:Contents ben$ sh headless/gama-headless.sh headless/samples/predatorPrey.xml outputHeadless
headless/gama-headless.sh
******************************************************************
* GAMA version 1.7.0 V7                                          *
* http://gama-platform.org                                       *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
******************************************************************
Erreur : impossible de trouver ou charger la classe principale org.eclipse.core.launcher.Main
MacBook-Pro-de-ben:Contents ben$ 
```

### Expected behavior
Run GAMA in headless mode

### Actual behavior
GAMA does not run in headless mode and we get the following error message:
```
******************************************************************
* GAMA version 1.7.0 V7                                          *
* http://gama-platform.org                                       *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
******************************************************************
Erreur : impossible de trouver ou charger la classe principale org.eclipse.core.launcher.Main
MacBook-Pro-de-ben:Contents ben$ 
```

### System and version 
MacOSX, GAMA 1.8 pre-release

**Comment by hqnghi88** [comment]
Normally there is always a headless launch when building process is finish. I just checked travis and it eas executed successfully. I didn't check wiki docs but here is the validation in headless
java  -cp ../plugins/org.eclipse.equinox.launcher*.jar -Xms512m -Xmx2048m  -Djava.awt.headless=true org.eclipse.core.launcher.Main  -application msi.gama.headless.id4 -data $passWork -validate $mfull $outputFile

**Comment by benoitgaudou** [comment]
Sorry my bad, I simply followed the wiki, that contains a small error in terms of location where I should run the shell script. It works.
