### ISSUE TITLE
Classic Graph generation - very ressource consuming !

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2354]
### Steps to reproduce
1. Run the model  Features / Graphs / Classic Graph Generattion.gaml, with hundreds agents to generate (e.g. 500)

### Actual behavior
The generation is too resource consuming too be used: generation of a complete graph of 300 agents use more than 5-6 Go ....

### System and version 
MACOSX, GAMA 1.8 pré-release, GAMA Git Mars

**Comment by AlexisDrogoul** [comment]
Is this using the generation from graphstream (or prefuse, I never remember which one is which).

**Comment by benoitgaudou** [comment]
I had a look and it seems that the graph generation is based on graphstream and the layout on prefuse.

**Comment by AlexisDrogoul** [comment]
We definitely should have a look at and integrate the new version (1.2.0) of JGraphT (https://github.com/jgrapht/jgrapht). There have been some API changes from the one we use (1.0.1), which makes things a bit complicated, but we could dump GraphStream altogether as JGraphT covers most of our needs in GAMA (see https://github.com/jgrapht/jgrapht/blob/master/HISTORY.md).

**Comment by chapuisk** [comment]
Dig this old issue out to mention few bugs on layout of graph. The layout is based on Prefuse, which is no more in development, while jgrapht suggests to use jgraphx. May be a good things to upgrade jgrapht to 1.3 and replace all Prefuse by jgraphx
