### ISSUE TITLE
The network plugin deserves a documentation 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2361]
### Steps to reproduce
1. I look hard for a documentation about the network plugin.

2. Even on the github wiki or on the website

### Expected behavior
I was expected to find one.

### Actual behavior
I just found the automatic documentation generated from the skill.
A recipe explaining what to install in addition to GAMA (server ...), the differences between the various network protocols (TCP, UDP, MQTT)... could be nice !

### System and version 
MACOSX

**Comment by AlexisDrogoul** [comment]
Moved to meta-issue #2449

**Comment by benoitgaudou** [comment]
The Java code contains now documentation through annotations (that should be introduced in the website soon).
A Recipes / tutorial page has been created to describe how to use the network plugin: 
https://github.com/gama-platform/gama/wiki/UsingNetwork

Benoit
