### ISSUE TITLE
Co model Simple Model hangs one when opening a new display

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#2362]
### Steps to reproduce
1. Launch the main experiment of the model Library models / Features / Co-model Usage / Simple Comodel

2.  Do one step and then switch to the first tab on the left

3. Do one step

### Expected behavior
It should works (ie a tab should be closed at the end and a new one opened, meaning that we killed a simulation and opened a new one)

### Actual behavior
Gama hangs on, do not respond and no error is shown on Eclipse console. I think it is related to the thread of the first window that is waiting but not answering since it has been closed in a brutal way.  It doesn't work also with the continuous build of 1.7. 

### System and version 
Gama Oxygen, Git version, Gama 1.7

**Comment by hqnghi88** [comment]
Dear Damien,
It works on my win, unfortunately i cant test on  a macos. I 'll try to do that

**Comment by benoitgaudou** [comment]
I have a freeze on my Mac, just after the first step (with the 1.8 preRelease)

**Comment by hqnghi88** [comment]
I can reproduce it, but not with step-by-step. it hangs when i clicked Run .

**Comment by dphilippon** [comment]
I don't have any problem to run it, it close one display and open a new one. However, if I do put the focus on the first tab (the one being the most at the left) it hangs.

**Comment by hqnghi88** [comment]
I must say it works very well on win (:P ). I can test on mac and try to fix with workaround (im afraid nothing to do more on these conflict).

**Comment by benoitgaudou** [comment]
I just tested and it seems to work ... even on MAcOSx, so I think I can close it
