### ISSUE TITLE
MQTT : side effect of connection error 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2364]
### Steps to reproduce
1. Open a model that wants to connect to a MQTT server (such as Plugin models/ Network/MQTT. Example_MQQT_SED.gaml

2. Do not run the server, but run the model.

### Expected behavior
An error appears, then I can close the exeperiment to go back to the modeling perspective.

### Actual behavior
An error appears. But when I want to close the experiment, it seems to remains on the simulation perspective, with the error message still opened.
By the way, it seems to produce some trouble to run later other models (I had to close GAMA before running new ones).

### System and version 
MACOSx, GAMA Git MArs & GAMA 1.8 preRelease

**Comment by AlexisDrogoul** [comment]
Moved to meta-issue #2449
