### ISSUE TITLE
Display zoom in a little bit too much when initially displaying a environment (Java2D)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2367]
### Steps to reproduce
1. Run the following model (that draws the environment in java2D)
```
model NewModel 

global { 
	int size <- 80 ; 
	geometry shape <- square ( size # m ) ;
} 

experiment name type: gui { 
	output { 
		display dOpengl type: opengl { } 
		display d { 
			graphics "world" { 
				draw world.shape border: #black empty: true ;
			} 
		}
	}
}
```

2. Look at the Java2D display

### Expected behavior
The Java2D should display all the square drawing the shape of the environment.

### Actual behavior
Some part of the square are hidden (by the border of the display). It appears when we zoom out.
See image below:

<img width="690" alt="capture d ecran 2018-03-19 a 09 54 27" src="https://user-images.githubusercontent.com/1555274/37586092-8e184e9a-2b5b-11e8-91bc-fb80c0811ca1.png">

### System and version 
MacOSX, GAMA 1.8 preRelease, Git MArs

**Comment by AlexisDrogoul** [comment]
Obviously, removing the border around displays (in the Preferences) removes this artefact...

**Comment by benoitgaudou** [comment]
yes indeed, we can see everything by removing the border.
But with the border we can see the left border, so it is not symetric that we cannot see the right one.
(very very low priority "issue", as it is not really annoying, but I reported it here, because we had a question on it).

**Comment by sriramab** [comment]
May be related, the right and bottom border of a grid also not visible.
