### ISSUE TITLE
Plugin Rjava : effect on the model library

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2368]
### Steps to reproduce
1. Install the plugin Rjava in the preRelease 1.8

### Expected behavior
Everything works as a charm

### Actual behavior
Here are some issues that appear:
- After installing the plugin and restarted GAMA, the model library is empty.
An error appears as there is, in the .project file, a link toward a picture, with a full absolute path, that does not work on any computer but Nghi's one.
- Once removed this absolute path, the models appear in the Plugin models as expected, but with the name "models" instead of a meaningful "Rjava Plugin" 

### System and version 
MacOsx, GAMA 1.8 rpeRelease

**Comment by hqnghi88** [comment]
Hi, it should have been fixed in experimental. Please uninstall and re install it from oxygen updatesite

**Comment by benoitgaudou** [comment]
I try a new commit on experimental to have a "nice" models example added in the Plugin models...
