### ISSUE TITLE
New splashscreen ?

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2373]
### Steps to reproduce
1. Run the GAMA preRelease 1.8

### Expected behavior
A new splashscreen

### Actual behavior
The splashscreen of the version 1.7 appears :)

### System and version 
MACOSX, GAMA preRElease 1.8, Git Oxygen

**Comment by AlexisDrogoul** [comment]
A quickly assembled one. Please comment !
![splash](https://user-images.githubusercontent.com/579256/37756445-1977e14e-2ddc-11e8-9b0d-3ea5264bdf28.png)

**Comment by hqnghi88** [comment]
Dear Alexis,
is it possible with an attempt to move 1.8 (without blue ground) into the center of the big G. And the 2 text are small for me. i cant read without glasses , sorry.

**Comment by AlexisDrogoul** [comment]
Something like this ? 

![splash2](https://user-images.githubusercontent.com/579256/37757153-9282b0d0-2dde-11e8-9d4e-8f47ceb3edcc.png)

**Comment by dphilippon** [comment]
I think the second one is better than the first one. Although my OCD is a bit triggered by the fact that the orange rectangle is a bit too much at the right (but I understand the effect wanted with the orange line defining the borders of the orange rectangle, and the yellow line defining the borders of the yellow one)

**Comment by hqnghi88** [comment]
Almost, but  i m wonder the equity  number of elements and the number of colors. I mean the color of "1.8", it would be blue?

**Comment by benoitgaudou** [comment]
I was wondering, as the border lines are straight and squared whether we could use the straight and squared version of the logo ?
![image](https://user-images.githubusercontent.com/1555274/37757678-1a0829a8-2dae-11e8-9b9c-f0d3ace7e05e.png)

**Comment by AlexisDrogoul** [comment]
Hmm.. The goal was to have a contrast, but why not. 

![splash3](https://user-images.githubusercontent.com/579256/37757764-a787c5ea-2de0-11e8-939c-e759c7337604.png)

![splash4](https://user-images.githubusercontent.com/579256/37757813-cd8ba7fc-2de0-11e8-9b08-59c17f33df68.png)

**Comment by sriramab** [comment]
I would prefer the first design with bigger font for text blocks or 
![37757153-9282b0d0-2dde-11e8-9d4e-8f47ceb3edcc](https://user-images.githubusercontent.com/12668606/37757864-9fddea68-2dae-11e8-809d-2bf17ba67cfc.png)

**Comment by sriramab** [comment]
The blue box of ummisco is more clear :)

**Comment by AlexisDrogoul** [comment]
Or... 
![splash5](https://user-images.githubusercontent.com/579256/37758123-a82a0dae-2de1-11e8-9180-71c71ed6031d.png)

**Comment by benoitgaudou** [comment]
Just small detail: "https://gama-platform.org" does not work. "http://gama-platform.org" only does.

**Comment by hqnghi88** [comment]
im ok with this
![image](https://user-images.githubusercontent.com/6105384/37758423-c42eaefa-2de2-11e8-8a75-fd67855e0efe.png)

**Comment by sriramab** [comment]
Hmm, Alexis, in your last image, 1.8 looks like secondary information. I feel it should be the primary information to convey. The first image had an impactful presence of 1.8. Also see if you can consider transparency beyond all your squares so that splash screen takes the shape of your design and not remain a big white square. I rest with my comments :)

**Comment by hqnghi88** [comment]
![image](https://user-images.githubusercontent.com/6105384/37758996-d05a259a-2de4-11e8-87f7-24c5efaa99cd.png)
Is It good?
Objection! Transparency is not good. Instead, the size of bonded white rectangle must be resize a bit

**Comment by AlexisDrogoul** [comment]
This ? 

![splash6](https://user-images.githubusercontent.com/579256/37760914-b611188c-2dea-11e8-8833-eb15ac0d41f2.png)

**Comment by AlexisDrogoul** [comment]
If this version is selected, we need to see where to put the progress bar. Maybe we should add some more whitespace on the bottom in order to put the bar there ?

**Comment by hqnghi88** [comment]
Dear Alexis, you mean more space than in my screenshot? Or we can customize also the style of pbar

**Comment by sriramab** [comment]
I just wonder, all the past versions I was working with, explicitly mention the name GAMA on the splash screen. Has it been overlooked? Is it assumed user will know ? just saying :blush:

**Comment by hqnghi88** [comment]
Very good sriri, you are right, the discussion continue, i proposed again to place ama at middle  of circles and be fore 1.8

**Comment by AlexisDrogoul** [comment]
Hum... Not sure I adhere to this, but here are two possibilities.

![splash8](https://user-images.githubusercontent.com/579256/37766883-e7826334-2dfa-11e8-85cc-7641848beb58.png)
![splash7](https://user-images.githubusercontent.com/579256/37766884-e7cb86fe-2dfa-11e8-9d65-66eb55bd1441.png)

**Comment by AlexisDrogoul** [comment]
And a third one (better angle)

![splash9](https://user-images.githubusercontent.com/579256/37766980-380c2dc6-2dfb-11e8-830c-07c5e383c10f.png)

**Comment by hqnghi88** [comment]
The second, no background and textcolor is orange, please.

**Comment by hqnghi88** [comment]
Or the first but with 1.8higher, align witb G and  ama vector

**Comment by AlexisDrogoul** [comment]
Orange text ? Yurk :(

![splash11](https://user-images.githubusercontent.com/579256/37767247-07e2e99a-2dfc-11e8-9455-70cac1b5d1f4.png)
![splash10](https://user-images.githubusercontent.com/579256/37767248-081681c4-2dfc-11e8-9513-6e8c9e3e9b4f.png)

**Comment by AlexisDrogoul** [comment]
![splash12](https://user-images.githubusercontent.com/579256/37767354-6f3e8f36-2dfc-11e8-82b9-a9f327aa6a4f.png)

**Comment by hqnghi88** [comment]
Yah you are right orange text is not good.

**Comment by hqnghi88** [comment]
I llike this

**Comment by hqnghi88** [comment]
Anyway where are you @agrignard from MIT?

**Comment by AlexisDrogoul** [comment]
A bit of correction (text size, distance, angle)

![splash13](https://user-images.githubusercontent.com/579256/37767513-f70489c0-2dfc-11e8-9abe-01c615df69be.png)

**Comment by hqnghi88** [comment]
Do we llace the pbar inside 3 rectangle or outside?

**Comment by sriramab** [comment]
https://user-images.githubusercontent.com/579256/37766884-e7cb86fe-2dfa-11e8-9d65-66eb55bd1441.png

I think blue box and orange box for GAMA and 1.8 resp with white font below the logo might look better, almost similar to 1.7. 

The AMA is so strong , that G is easy to miss :(

**Comment by anvd** [comment]
What a tight competition! All the proposed splashscreen candidates for 1.8
are gorgeous. Really difficult to pick the winner :)

Cheers,
An.

**Comment by hqnghi88** [comment]
Bonjour Anh Annnnn, cheerss

**Comment by hqnghi88** [comment]
I prefer this https://user-images.githubusercontent.com/579256/37767513-f70489c0-2dfc-11e8-9abe-01c615df69be.png
for the all of innovations, artistic, the advancing to future, the supporting below of ummisco, the http fky on the top... Tobe comleted

**Comment by AlexisDrogoul** [comment]
@hqnghi88 I agree too. This is the one I prefer.

**Comment by agrignard** [comment]
Hi everyone, I am just jumping in the conversation so it might be too late as lot of iteration has been made... I was more in favor of a minimal design like this one
<img width="605" alt="screen shot 2018-03-23 at 15 45 21" src="https://user-images.githubusercontent.com/3928502/37835794-402ec214-2eb1-11e8-8a1d-4a011235ca14.png">

I don't know why but the oriented Text and Bounding box remind me a bit like a promotion icon
<img width="329" alt="screen shot 2018-03-23 at 15 48 02" src="https://user-images.githubusercontent.com/3928502/37835929-98a7b658-2eb1-11e8-94ee-80cda8fddee6.png">

Also the GAMA logo is so nice that even google is copying it for Grammarly ;-)
<img width="355" alt="screen shot 2018-03-23 at 15 51 33" src="https://user-images.githubusercontent.com/3928502/37836172-217e05b8-2eb2-11e8-9325-d0ac0a211b0c.png">

**Comment by AlexisDrogoul** [comment]
Actually, I like the "dynamic" one a lot, as it reminds me (albeit from very far away and probably unconsciously) of constructivist attempts with its geometrical/text features (Rodchenko's work, for instance, or Lissitzky's), with a touch of Kandinsky for the colours. 
Actually, I would even go further and incorporate some circle to enhance the geometrical aspect. 

![splash14](https://user-images.githubusercontent.com/579256/37882909-467284b8-30d1-11e8-9e2f-c3e8c735e444.png)
![rodchenko_16](https://user-images.githubusercontent.com/579256/37882910-46c1085e-30d1-11e8-8932-fc68104960b8.jpg)
![lissitsky](https://user-images.githubusercontent.com/579256/37882911-46fbe316-30d1-11e8-9e3e-6cb733aeaab9.jpg)
![rodchenko](https://user-images.githubusercontent.com/579256/37882912-4767d260-30d1-11e8-9359-bdb026175fae.jpg)

**Comment by AlexisDrogoul** [comment]
Further exploration along the constructivist style... 

![splash15](https://user-images.githubusercontent.com/579256/37886182-9fff0440-30e3-11e8-8bda-a27af22c5bf2.png)

**Comment by hqnghi88** [comment]
The 1st please, these others give some blank feelling on the top right

**Comment by benoitgaudou** [comment]
The last one is really Nice indeed !!
Benoit

Le lun. 26 mars 2018 à 06:35, HUYNH Quang-Nghi <notifications@github.com> a
écrit :

**Comment by ysklab** [comment]
I like the last one too!

**Comment by benoitgaudou** [comment]
I am wondering how it could be with a triangle instead of a circle for the number of the version and the AMA text ( so close to Lissitzky's picture) ?

**Comment by agrignard** [comment]
Why not for the constructivism approach but then we should go a bit deeper
<img width="704" alt="screen shot 2018-03-27 at 00 14 39" src="https://user-images.githubusercontent.com/3928502/37935969-e6d517fe-3153-11e8-9fa3-261ac3d8760a.png">

**Comment by agrignard** [comment]
Some input (clearly not final but to iterate on the constructivist way and very inspired from one of the picture) 
<img width="982" alt="screen shot 2018-03-27 at 21 04 57" src="https://user-images.githubusercontent.com/3928502/37989124-e07c1678-3202-11e8-87e2-ec591c2297e7.png">

**Comment by AlexisDrogoul** [comment]
Hmmm.. Another iteration from the "destructured" but still structured, with a circle to soften the angles. We have to decide quickly, by the way, if I judge by the imminence of the pre-release... 

![splash18](https://user-images.githubusercontent.com/579256/38008577-b0422a0c-3279-11e8-91c9-35d0230b9280.png)

**Comment by dphilippon** [comment]
I really like the last one with the 1.8 in the orange circle. However, can you move the "AMA" a bit on the right just so the A is not crossing the lines and the intersection point (OCD speaker here, really sorry).

**Comment by AlexisDrogoul** [comment]
You mean something like this ?

![splash19](https://user-images.githubusercontent.com/579256/38009009-3c3ad156-327c-11e8-91e6-20c1a4c527d2.png)

**Comment by sriramab** [comment]
Although I have some comments, but I like the most recent one among all others.

**Comment by agrignard** [comment]
Nice iteration. 

What about changing also the color of the font for gama-platform (to blue) and ummisco (to yellow) ,so we just use the 3 same color. At least the black one

Maybe the 1.8 font could be a bit "lighter"

**Comment by AlexisDrogoul** [comment]
@agrignard Something more like this ?

![splash20](https://user-images.githubusercontent.com/579256/38086727-a9de9d92-337f-11e8-8340-14f8781c3eed.png)

**Comment by agrignard** [comment]
Nice one! I think we are getting there.

**Comment by agrignard** [comment]
Little detail but what about having a very minimal global frame? 

When opening GAMA when you have already something running in white in background it gives a strange rendering as it's hard to see the boundary of the splashscreen

**Comment by AlexisDrogoul** [comment]
Hum... OK. Something like this ? 

![splash](https://user-images.githubusercontent.com/579256/38352018-11997b76-38dc-11e8-8a1b-1f716cc3d986.png)

**Comment by hqnghi88** [comment]
Dear. just a feeling, blue diagonal could be revert to the previous version?

**Comment by AlexisDrogoul** [comment]
AH yes. Sorry.

![splash2](https://user-images.githubusercontent.com/579256/38352690-383e3274-38de-11e8-86d8-41cb3fb0e0a4.png)

**Comment by agrignard** [comment]
yes
