### ISSUE TITLE
Equality between #nan numbers and between #infinity numbers

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2374]
### Steps to reproduce
1. In a model write:
			write #nan = #nan;
			write #infinity = #infinity;

### Expected behavior
Intuitively, I would see true in both cases.

### Actual behavior
The result is false in both cases.
Even if we want to keep the fact that #infinity is not equal to #infinity, we should need an operator to test that a number is #infinity / #nan.

### System and version 
MACOSX, GAMA Git Oxygen

**Comment by AlexisDrogoul** [comment]
I would be likely to close this issue, as 

1. #nan and #infinity follow the rules of Java regarding NaN and infinite numbers (they can't be equal to themselves)

2. There are two operators (`is_finite` and `is_number`) that serve the purpose written above (knowing whether a number is infinite or #nan).

**Comment by benoitgaudou** [comment]
You are right, that's exactly what I was looking for ... but searching is_infinity or is_nan operators ... 
Thanks
