### ISSUE TITLE
Is export missing in GUI?

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2375]
hi

There used to be a export button in context menu and also file menu of GAMA. I do not see it in the new versions. **Please bring it back**. It was an ideal way for exchange with colleagues and students.

Srirama

**Comment by hqnghi88** [comment]
Dear all,
I 've check and realize that export wizard has never implemented in code base. It's strange that it appear in RC2, not in continuous build and also in oxygen.
Do you have any idea on this issue?

**Comment by benoitgaudou** [comment]
I tried after the commit 5e42d1a9099cf5d364c9a787e29b8d3e6239ab03 and works for me.
I close the issue, do not hesitate to reopen it in case of trouble.

**Comment by sriramab** [comment]
Hi,

The export option as of now, shows all the projects in the navigator including Library, Plugin, Test and User models. I would like to request a modification, so that export shows only the current project that user right-clicked on and wants to export.

Srirama
