### ISSUE TITLE
embed system terminal/console 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2377]
Hi,

I would like to request an integrated/embedded system console. This is these days available in all GUI IDEs like RStudio, PyCharm, IntelliJ, Visual Studio Code etc. it would really be nice to deal with files from within GAMA. I am aware EasyShell and StartExplorer can be configured to do this, but they all open new windows. Then there is a lot of minimize and maximize of windows. If it is embedded, then it is just a little convenient to handles files ( git, R, python etc) 

I know this is possible in Eclipse with some plugins, but would be nice if this could be ported to GAMA Standalone. 

Thank you
Srirama

**Comment by AlexisDrogoul** [comment]
Hi, I have tried several plugins in Eclipse and I am absolutely not convinced by their functionalities, i.e. compared to a standalone shell or terminal. Given this situation, we won't include a terminal/shell in GAMA, but feel free to report any incompatibilities between existing Eclipse plugins and GAMA, in which case I can help in integrating them better.

**Comment by sriramab** [comment]
This works super in Windows, I have issues on mac. 

https://marketplace.eclipse.org/content/tm-terminal 


May be something i dont understand. Could you try please. Reminder: it is already in list of plugins within GAMA as per my 2 year old request. Would also be super to integrate eGIT? Like this

http://www.eclipse.org/egit/download/ 

But the terminal solves all problems. egit is not priority.

**Comment by AlexisDrogoul** [comment]
I have tried M Terminal on eclipse (and then on GAMA). Several problems in macOS on both configurations. Unless a better plugin is developed (I havent found any good ones), I would not put it in GAMA... Egit, why not, but you'd need to open a more focused issue (i.e. what doesn't work, etc.). Thanks !
