### ISSUE TITLE
GAMA 1.8 and HDPI (windows) computer: preferences panel and opengl display 

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2378]
### Steps to reproduce
1. Open the preference panel: it is so big, that I cannot even close it (I cannot see the bottom of the panel). I can solve this issue by modifying the text zoom in the display property in windows

2. Run the Start experiment of the 3D camera and trajectories (features/3Dvisualization): the image with the bird is very small (in the corner of the total display: see the following image). 

![problem_opengl](https://user-images.githubusercontent.com/1506077/38097219-11a50246-3375-11e8-9002-6a08c6d23cfa.PNG)

### System and version 
GAMA 1.8 release
Windows 64 bits
Dell XPS 2017 15" : resolution : 3840 x 2160 (default resolution) - text zoom : 250 % (default value)

**Comment by hqnghi88** [comment]
Dear Patrick,
Hard to have this configuration . Have you ever try with the override  high dpi setting of Gama.exe properties
![image](https://user-images.githubusercontent.com/6105384/38100747-703990aa-33a8-11e8-999f-faca1ddafe41.png)

**Comment by ptaillandier** [comment]
It does not work with "Application", but it works with "System" and the
result is so so (see the screenshot  - at least I do not have a display
bug, but the rendering is not so good).

Thanks a lot, it will be ok for now.

2018-03-29 18:26 GMT+02:00 HUYNH Quang-Nghi <notifications@github.com>:

**Comment by hqnghi88** [comment]
you mean the screenshot above (with small birds) or another? Regarding the renderer on windows, dellxps 15 should have nvidia 1050, there is some more settings in nvidia control panel that you can try to see if it have any effects.
![image](https://user-images.githubusercontent.com/6105384/38101681-29170b0a-33ab-11e8-8c31-0523a77cf5da.png)
![image](https://user-images.githubusercontent.com/6105384/38101729-5611a084-33ab-11e8-9c0b-c8e959c65718.png)

**Comment by AlexisDrogoul** [comment]
Is this behaviour still happening ? I however don't really see it as a GAMA bug but rather as a complex interaction between Windows / Dell / Nvidia / Java / Individual Application settings... (i.e. the reason why I am on macOS  :) ). I close from now on, reopen if the display is still terrible.

**Comment by ptaillandier** [comment]
Yes, it is still happening, but as we already have a workaround, it is ok
to close it for the moment (we just have to update the doc if it is not
already the case). Maybe, it will be fixed with the new version of Java.

2018-07-03 13:16 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by agrignard** [comment]
I am reopening this issue. as I didn't get what is the way to fix it? I indeed as a NVIDIA control Panel but what should I do?

**Comment by agrignard** [comment]
Ok so it seems that override high dpi setting of Gama.exe  and scaling perform by "System" is doing the trick. 

Do we document this somewhere? Or is it very specific to Nvidia computers?

**Comment by agrignard** [comment]
I am just  reopening this issue as one of my student @LuanaMarrocco (that might tell us a bit more on her specific problem here) got the same issue. 

In her case when we right click on GAMA.exe we don't have the same windows (french version) and we cannot override the HDI protocol

So same issue with Windows 10 and a "High Resolution" screen on  a LeNuvo Computer , as it is the 2nd time in a raw in 2 attempts that I see this behavior on a Windows I am just wandering if there is no way to fix this directly from GAMA? or maybe document it in the install session?

**Comment by AlexisDrogoul** [comment]
Can you try a workaround in class `Abstract3DRenderer`? 

It is by no means a fix, but if it works on Windows, well... We might include it in the release. 

Replace the method `createDrawable(final Composite parent)` by : 


```java
	public GLAutoDrawable createDrawable(final Composite parent) {
		final GLProfile profile = GLProfile.getDefault();
		final GLCapabilities cap = new GLCapabilities(profile);
		cap.setDepthBits(24);
		// cap.setBackgroundOpaque(true);
		cap.setDoubleBuffered(true);
		cap.setHardwareAccelerated(true);
		cap.setSampleBuffers(true);
		cap.setAlphaBits(8);
		cap.setNumSamples(8);
		canvas = new GLCanvas(parent, SWT.NONE, cap, null) {
			public Rectangle getClientArea() {
				return DPIUtil.autoScaleUp(super.getClientArea());
			}
		};
		canvas.setAutoSwapBufferMode(true);
		final SWTGLAnimator animator = new SWTGLAnimator(canvas);
		// animator.setIgnoreExceptions(!GamaPreferences.Runtime.ERRORS_IN_DISPLAYS.getValue());
		animator.setUpdateFPSFrames(FPSCounter.DEFAULT_FRAMES_PER_INTERVAL, null);
		canvas.addGLEventListener(this);
		final FillLayout gl = new FillLayout();
		canvas.setLayout(gl);
		return canvas;
	}
```

And let me know if it works (without any special DPI settings in the properties of Eclipse or GAMA...)

**Comment by LuanaMarrocco** [comment]
I have found how to do with my french computer ! Same as above, but in french ! 

![capture](https://user-images.githubusercontent.com/39154211/43923274-45905b2c-9bef-11e8-82ee-d8334de81749.PNG)

**Comment by AlexisDrogoul** [comment]
I've pushed a commit that should work only for windows. Please try it (w/o setting any specific DPI settings on Windows).

**Comment by tcquang** [comment]
Dear Mr. Alexis Drogoul,
This really good news for windows users.
But in the windows of preferences, I could not find the field to change the
Maximum memory located. It's normally located on the Startup tab of the
window.
Please see the picture attached!

Thank you very much!

Quang

**Comment by AlexisDrogoul** [comment]
Hi Quang, no picture attached and it's quite a different subject -- but the corresponding pref has been moved with the memory management preferences.

**Comment by AlexisDrogoul** [comment]
BTW, I still need to know whether it is working or not for the OpenGL displays....

**Comment by tcquang** [comment]
Dear Mr. Alexis Drogoul,
I found the new place of the pref (It's now in the Execution tab).
The OpenGL mode works fine!

Thank you very much!

Quang

**Comment by AlexisDrogoul** [comment]
OK. So we can consider this as closed. Would be interesting to see if the same problem affects Ubuntu, by the way.

**Comment by agrignard** [comment]
Ok I tested it with the last version on windows 10 and it works like a charm!!! Thanks for the quick fix.

Just as a side note but I guess this is just one example and it will appear in other configuration.
If I don't change the settings the opengl works fine (that was the main problem of this issue) however I think in some part the GUI is kind of wrong. Just for example I wanted to play with the layer display and here is what I get (I don't get that if I change the HDPI settings)
![img_3086](https://user-images.githubusercontent.com/3928502/44155355-0547cad8-a07b-11e8-8a97-b3c85b423d38.jpg)

It seems clearly due also to a bad computing somewhere of the size of the display. There is also this weird black pixel close to the transparency position and size x,y. I mean I notice some small """glitch""" in the interface on windows with High Resolution screen but I don't think we can do a lot and I don't think we are the only one to have this issue (I'll try to do a more specific issue with some screenshots). 

For the OpenGL this is fixed and that's the most important.
