### ISSUE TITLE
Quality of a high resolution picture as a background

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2380]
### Steps to reproduce
1. display an image with
```
image 'background' file:'./../includes/images/ModelWhite.jpg'
```
2. Run on display in java2D

3. An another one in opengl

### Expected behavior
Same rendering of the picture as good as the original

### Actual behavior
The Opengl looks very bad (the line are not well defined) , it's better in java2D but still I have the feeling that it's not the same definition as the original

<img width="1328" alt="screen shot 2018-03-30 at 10 03 35" src="https://user-images.githubusercontent.com/3928502/38130100-0056b966-3402-11e8-9259-dde64fdc2a74.png">

<img width="1622" alt="screen shot 2018-03-30 at 10 03 13" src="https://user-images.githubusercontent.com/3928502/38130101-0104998c-3402-11e8-8c1b-7a2a4921167d.png">

**Comment by AlexisDrogoul** [comment]
What is the original resolution of the image and the resolution of the display ? Interpolation algorithms in Java are maybe not optimal. Have you also selected the antialising option ? It usually helps in rendering images (by choosing the optimal interpolation methods).

**Comment by agrignard** [comment]
The antialiasing doesn't change anything. The original resolution is pretty high (5668x4039).

**Comment by agrignard** [comment]
I couldn't find the picture anymore. But it basically happening with any picture that are let say more than fullHD (1920x1080). I think you can even take the one in the issue the one showing the java2D results (even by screenshooting it) it should be enough to see the difference between java and opengl

**Comment by AlexisDrogoul** [comment]
I think the quality produced by Java2D is probably the best we can have, given the initial dimensions, in terms of interpolation. OpenGL, on the other hand, is effectively awful. I move this issue to the meta-issue #2209 on OpenGL rendering problems.

**Comment by AlexisDrogoul** [comment]
OK. I have played a bit with parameters and image loading/caching, and I think I have made substantial progresses. I think it should also improve #2174. A side note: the fact that the antialias (in the side controls) had no effect was probably due to the fact that the image was not refreshed by default. So it needed to be set in the preferences beforehand (or in the model, using preferences).

**Comment by AlexisDrogoul** [comment]
Remember you have to turn antialias on in the Preferences (or in the model) to see any difference.

**Comment by agrignard** [comment]
I try this model

``````
model Tuto3D

global {

  init {
  	shape<-rectangle(3840,2392); 
  }  
} 
  

experiment Tuto3D  type: gui {
  init{
  		gama.pref_display_antialias <- true;	
  }	
  output {
  	
  	display ViewJava type:java2D {
      image 'background' file:'./../images/HD_Background.png';
    }
    
    display ViewOpenGL type:opengl{
      image 'background' file:'./../images/HD_Background.png';
    }
  }
}
``````
and I still have this result (java is still better than opengl)
<img width="1919" alt="screen shot 2018-08-14 at 16 38 36" src="https://user-images.githubusercontent.com/3928502/44117225-ac4e1238-9fe0-11e8-9196-a59dc4255c90.png">
Reproduce it
[GamaSandBox.zip](https://github.com/gama-platform/gama/files/2288426/GamaSandBox.zip)

GAMA1.8_Mac_64_08.14.18_ec6cf84

**Comment by AlexisDrogoul** [comment]
And it will always be until we define our own interpolation algorithms and do not rely on the mipmaping of OpenGL. Move it back to #2209. If someone wants to work on it...

**Comment by AlexisDrogoul** [comment]
As a side note, I cant quite reproduce your results. Two views side by side of the same picture (snapshot of 3840x2400) with antialias set to true give results that are largely comparable in java2D and OpenGL. 

![image](https://user-images.githubusercontent.com/579256/44166001-70d0da00-a0f4-11e8-9d49-26461b70b07a.png)

**Comment by AlexisDrogoul** [comment]
And here the bigger size (not shrunk to Retina scales):

<img width="1920" alt="monosnap 2018-08-16 01-41-39" src="https://user-images.githubusercontent.com/579256/44166465-a7f3bb00-a0f5-11e8-9fd9-dde50a5846fb.png">

**Comment by agrignard** [comment]
... interesting... I will retry. Did you use the .zip that I sent? To be sure we run the same model and the same image?
