### ISSUE TITLE
Interactive console does not work

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2381]
### Steps to reproduce
1. Run a model

2. Try to use the interactive console

### Actual behavior
The interactive console does not seem to work. the prompt appears, but what is typed in it is not executed. The prompt does not appear anymore after.

### System and version 
MACOSX / Windows, GAMA 1.8 Release Candidate

**Comment by sriramab** [comment]
Hi

It seems there return of interactive console command is also being written on the regular console . So not sure if this needs a fix or if it is intentional. 

Srirama

**Comment by AlexisDrogoul** [comment]
I obtain this behaviour only if I begin the expressions with `write`, which is perfectly normal. Otherwise, the result is only displayed in the Interactive Console. Which expressions have you been entering ?

**Comment by sriramab** [comment]
Indeed you are "write" :) 
Works as you describe.
