### ISSUE TITLE
Gama 1.8 & Java 10

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2383]
### Steps to reproduce
1. Run Gama with a java jdk 10 installed

### Actual behavior
Gama crashes before the choice of the worspace

### System and version 
Gama 1.8 rc, java 10 jdk oracle

**Comment by AlexisDrogoul** [comment]
https://stackoverflow.com/questions/49436841/how-to-set-up-java-10-in-eclipse-oxygen

The support for Java 10 is still experimental for Eclipse, so it is no surprise GAMA does not work with it...

**Comment by AlexisDrogoul** [comment]
I close this issue after having added some lines in the documentation (Installation) regarding the fact that GAMA 1.7/1.8 are not supposed to be compatible with Java 1.9/1.10.
