### ISSUE TITLE
New project pop up window too small

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2385]
### Steps to reproduce
1. In GAMA, File / New ... / Gama Project

3.

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
The popup window is too small to let appear the field to enter the new of the project.
We had to increase the size to use it properly.

### System and version 
GAMA 1.8 RC, seems to be Windows 10 only

**Comment by sriramab** [comment]
For me this happened when using java9, when I switched back to java8, this was resolved. Windows7

**Comment by benoitgaudou** [comment]
Thanks !
I ll try to check the Java version !

Benoit

**Comment by AlexisDrogoul** [comment]
Any new updates on this one ?

**Comment by sriramab** [comment]
This still happens on windows 7 latest build of 2nd July 2018

**Comment by AlexisDrogoul** [comment]
Could you try with the latest commit I have made ? It should normally fix this issue.

**Comment by AlexisDrogoul** [comment]
Anyone using Windows out there ? :)

**Comment by hqnghi88** [comment]
Well, i dont have it on my windows 10

**Comment by sriramab** [comment]
Works good on windows 7 5th/july/2018 update.

**Comment by AlexisDrogoul** [comment]
Thanks guys :)
