### ISSUE TITLE
Compiler issue with parameter statement in output block

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2387]
### Steps to reproduce
1. In any model, add a parameter statement in the output block.

2. For example, open Tutorials / Incremental models / Incremental Model 1.gaml

3. Move the parameter:
```
	parameter "Infection distance" var: infection_distance;
```
in the output block.

### Expected behavior
A compilation error appears.

### Actual behavior
No compilation error appears. The button to run the experiment still appear.
But clicking on it does not make anything.
In addition, if a compilation error is introduce in the model and corrected, it still appears as an error.

### System and version 
GAMA 1.8 RC, Java 8

**Comment by hqnghi88** [comment]
in general, any variable declaration in output block cause this issue. I dont know if it exxist before or because the xtext updates.
