### ISSUE TITLE
White (empty) display of agents

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2388]
### Steps to reproduce

(sorry not sure to know exactly how to reproduce it ...)
1. After a crash of GAMA, re launch GAMA and run a modèle

### Actual behavior
An empty screen appears for the Java 2D display with agents

### System and version 
GAMA 18.RC, macosx and ubuntu

**Comment by AlexisDrogoul** [comment]
Did this manifest again ? The description is too vague to conduct any serious investigation. I will close until something more "reproducible" can be shown...
