### ISSUE TITLE
Improve documentation of the install of GAMA (the java to install)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2390]
### Steps to reproduce
1. Ask to trainees to install GAMA and if needed to get Java (from here https://github.com/gama-platform/gama/wiki/Installation)

### Expected behavior
Everybody has downloaded and installed Java 1.8 JDK Oracle

### Actual behavior
Most of them had installed Java 10 JDK Oracle.
The documentation seems to contain some flaws that should be corrected...

### System and version 
GAMA 1.8 RC

**Comment by hqnghi88** [comment]
The link to jdk download page has leaked out the info of 9 and 10, we should change to directly 8 
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
ANYWAYS, it has a bold Java 1.8 in system requirement.
