### ISSUE TITLE
arcball vs freefly

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2391]
### Steps to reproduce
1.trigger arcball (cmd+drag)

2.double click

### Expected behavior
Top view in arcball mode

### Actual behavior
Wrong view

### System and version 
GAMA 1.8 Release

**Comment by AlexisDrogoul** [comment]
What does "wrong view" mean ?

**Comment by agrignard** [comment]
Mmm I cannot reproduce it, I download the last release and it's not there anymore. 

Yesterday I noticed a switch between arcball and freefly even I didn't trigger it. And then if you double clicked (to reset the view with a top view) it was in an already oriented configuration

Let's assume it was a very weird configuration. I close the issue and I will double check if it rehappens.
