### ISSUE TITLE
Facet header: in the save - save of data in an experiment

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2393]
### Steps to reproduce
1. Open the model Toy Models / Segregation (Schelling) / Segregation (Agents).gaml

2. Add to the model an additional experiment, to save indicators of batch experiments : 
```
experiment ExploExhaustive type: batch until: (sum_happy_people = length(people)) or (cycle > 2000) {
	parameter "Number of groups:" var: number_of_groups <- 2  ;
	parameter "Width and height of the environment:" var: dimensions <- 40;
	parameter "Distance of perception:" var: neighbours_distance <- 2;
	
	parameter "Desired percentage of similarity:" var: percent_similar_wanted <- 0.5 min: 0.0 max: 1.0 step: 0.1;
	parameter "Density of people:" var: density_of_people <- 0.7 min: 0.01 max: 0.99 step: 0.1;
		
	method exhaustive;
		
	init {
		save ["percent_similar_wanted","density_of_people","cycle"] to: "result.csv" type: "csv" rewrite: true;		
	}	
	
	reflex save_data {
		save [percent_similar_wanted,density_of_people,cycle] to: "result.csv" type: "csv" rewrite: false ;		
	}	
}
```

### Expected behavior
The aim is to be able to run this batch experiment several times and to take into account the fact that the file result.csv can exist, and should be cleaned before storing data from an experiment plan.
So I used the init of the experiment to only clean the csv file (by for example just writting the headers).

So I was expecting that the header is written in the header, and then each sacve_data will store a line in the csv file.

### Actual behavior
When I write ["percent_similar_wanted","density_of_people","cycle"]  in the init, the first save of save_data first write the header (again) and then data. (I tried to use header: true and false in the save_data, without any change in the result).

So I tried another init:
```	
	init {
		save [] to: "result.csv" type: "csv" rewrite: true;		
	}	
```
In this case (regardless the value to the facet header in the save_data), I get nothing as header.

### System and version 
GAMA 1.8 RC, MACOSX

**Comment by hqnghi88** [comment]
Does this help?
experiment ExploExhaustive type: batch until: (sum_happy_people = length(people)) or (cycle > 2000) {
	parameter "Number of groups:" var: number_of_groups <- 2  ;
	parameter "Width and height of the environment:" var: dimensions <- 40;
	parameter "Distance of perception:" var: neighbours_distance <- 2;
	
	parameter "Desired percentage of similarity:" var: percent_similar_wanted <- 0.5 min: 0.0 max: 1.0 step: 0.1;
	parameter "Density of people:" var: density_of_people <- 0.7 min: 0.01 max: 0.99 step: 0.1;
		
	method exhaustive;
	bool initialized<-false;
	reflex save_data {
		save [percent_similar_wanted,density_of_people,cycle] header:true to: "result.csv" type: "csv" rewrite: !initialized ;	
		initialized	<-true;
	}	
}

**Comment by hqnghi88** [comment]
and if you still like init block
experiment ExploExhaustive type: batch until: (sum_happy_people = length(people)) or (cycle > 2000) {
	parameter "Number of groups:" var: number_of_groups <- 2  ;
	parameter "Width and height of the environment:" var: dimensions <- 40;
	parameter "Distance of perception:" var: neighbours_distance <- 2;
	
	parameter "Desired percentage of similarity:" var: percent_similar_wanted <- 0.5 min: 0.0 max: 1.0 step: 0.1;
	parameter "Density of people:" var: density_of_people <- 0.7 min: 0.01 max: 0.99 step: 0.1;
		
	method exhaustive;
		
	init {
		save ["percent_similar_wanted","density_of_people","cycle"] header:false  to: "result.csv" type: "csv" rewrite: true;		
	}	
	
	reflex save_data {
		save [percent_similar_wanted,density_of_people,cycle] header:true to: "result.csv" type: "csv" rewrite: false ;		
	}	
}

**Comment by benoitgaudou** [comment]
Hi,
thx, it works well...
I made things too complicate I guess.
