### ISSUE TITLE
Update process not working?

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2394]
Hi,

It seems the Help>Updates is not working. It always shows no updates, while I can see there are many commits on the repository. Please check.

Srirama
GAMA1.8RC, Mac Sierra, java 1.8

**Comment by hqnghi88** [comment]
Can you retry with new build https://github.com/gama-platform/gama/releases/tag/oxygenCI ?

**Comment by sriramab** [comment]
seems to be working. Thank you.
