### ISSUE TITLE
Mouse event

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2395]
### Steps to reproduce
1. The code source specifies that we can use following events:  "mouse_up", "mouse_down", "mouse_move", "mouse_enter", "mouse_exit"

### Actual behavior
I was not able to find a model that works properly and illustrates the mouse_enter and mouse_exit

### System and version 
GAMA 1.8 RC

**Comment by AlexisDrogoul** [comment]
Actually, mouse_enter and mouse_exit could be useful for some purposes (brightening/dimming the displays if the mouse enters or exits it, for instance). It's true that they are not used now in the examples. For the other proposal, it might be interesting to open a specific issue (although I'm quite sure it has been asked somewhere before).

**Comment by AlexisDrogoul** [comment]
I've added a quick and dirty model to show the use of these two events.

**Comment by agrignard** [comment]
Funny model!!  In my case  the exit mouse is working  well (as soon as the mouse exit the model window eyes are turning black), however for the mouse_enter I have to switch application (cmd+tab) in order to reopen the eye maybe that's what @hqnghi88 was mentioning?

**Comment by AlexisDrogoul** [comment]
Have you tested it with the latest version ?

**Comment by agrignard** [comment]
Ok cool works well sorry I was one week late with my gama version. Works ok with GAMA1.8_Mac_64_07.02.18_9d27238.app
