### ISSUE TITLE
java error： wrong casting (with the whole project file)

### ISSUE THREAD

**Issue by you68681** [gama-platform/gama#2397]
### Steps to reproduce
1.

[project1.zip](https://github.com/gama-platform/gama/files/1876035/project1.zip)

please run the stage 4 in model.
2.
the error is 
<img width="620" alt="wx20180404-005746 2x" src="https://user-images.githubusercontent.com/38044351/38293578-653f9866-382b-11e8-9ad0-b23d94c8de8d.png">

3.

### Expected behavior
At stage 4, I use at_distance function at line 152. But it shows java error: wrong casting. But at stage 5, I replace it with the inside function. It can run successfully.

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
gama 1.7 system mac java verison 1.8

**Comment by agrignard** [comment]
@you68681 I think you sent me a personal mail this morning with your model. I forward it here it's easier for us to fix it.

So here is the project and apparently you have some issue when running stage4.gaml

On my side I don't have any problem to run it. Can you double check the version of GAMA and JAVA that you are using?

[project1.zip](https://github.com/gama-platform/gama/files/1875954/project1.zip)

**Comment by you68681** [comment]
@agrignard @AlexisDrogoul After I down the Gama with  https://github.com/gama-platform/gama/releases/tag/oxygenCI from this link and run it again. This code becomes correct. But the speed becomes slow. My JDK version is jdk1.8.0_144.jdk. Is this version cause Gama become slow

**Comment by agrignard** [comment]
Can you update your jdk to 161 or 162 
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by you68681** [comment]
@agrignard yeah, I have updated it. It seems like better. Thanks a lot, I will close my question.
