### ISSUE TITLE
Import GAMA Project Broken?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2398]
### Steps to reproduce
1.Right click on user models
Import GAMA Project
Choose the right folder

### Expected behavior
Have the project in the user models

### Actual behavior
Nothing... it used to work before no? Did I miss something here?

### System and version 
GAMA1.8_Mac_64_04.04.18_9b6de35

**Comment by agrignard** [comment]
It works with Import->Other->General->Existing Project into workspace

**Comment by agrignard** [comment]
@sriramab what do you mean by "they are imported into the workspace" in my case I cannot see my model "user models" stays empty

**Comment by sriramab** [comment]
Yes, I mean User_models as workspace. I have no problems on Mac Sierra on 1.8RC. Import or Import>Other or Import archive, all are working. However, only importing archive  imports everything to a folder. All "non-archive" methods are putting folders in User_models. 

I am not sure but a wild guess is may be you are using git and you have a gitignore file that rejects .project of GAMA ? I think if you dont have the .project of GAMA, then projects go weird.  Just a guess.

**Comment by agrignard** [comment]
I have my .project it use to work before so I think something has changed no?

Can someone double check? 
Arno:GAMA_LLL Arno$ ls -altr
total 24
-rw-r--r--   1 Arno  staff   434 Mar 28 02:56 .project
drwxr-xr-x   4 Arno  staff   136 Apr  3 06:23 ..
drwxr-xr-x   6 Arno  staff   204 Apr  5 08:41 includes
drwxr-xr-x   6 Arno  staff   204 Apr  5 08:57 .
-rw-r--r--@  1 Arno  staff  6148 Apr  5 08:59 .DS_Store
drwxr-xr-x  10 Arno  staff   340 Apr  6 13:45 models

**Comment by agrignard** [comment]
Lets consider I have something strange in my configuration. I close this issue for now (it is working normally for other project so something might be wrong in the .project
