### ISSUE TITLE
save graph to shape file

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2401]
### Steps to reproduce
1. In a model, create a road graph and try to save it in a shp file.

### Expected behavior
I do not know :-)
Either an error if it is not possible or a save of the road geometries.

### Actual behavior
I do not have any error message.
The experiment button is neither red, nor green (in waiting state).
I get an internal error in the validator, making the next validation totally wrong. I mean that when I make an error on purpose, it is detected ; but when I correct it, the error message remains.

### System and version 
GAMA 1.8 RC

**Comment by hqnghi88** [comment]
Dear Benoit,
it interesting and curious, can you post the code, you mean the save statement with type:shp and data is a graph?

**Comment by benoitgaudou** [comment]
Here it is.

[toshp.zip](https://github.com/gama-platform/gama/files/1890454/toshp.zip)

Benoit

**Comment by hqnghi88** [comment]
AFAIK, it was not the graph which cause the exception but the attributes list, int(self) is nothing when the current context is graph/list
		list<geometry> ss<-shapefile_route;
		save ss to:"../includes/main_gr.shp" type:"shp"
		attributes: ["ID":: int(self)] 
		;

**Comment by hqnghi88** [comment]
I emit an error compilation because i have no idea to do with facet attributes when applied to a graph/list/geometry

**Comment by benoitgaudou** [comment]
Hi

Great an error is great for me. Thanks

More generally is there a way to prevent the fact that an exception in any
Validator breaks the compilator ?

Benoit


Le lun. 9 avr. 2018 à 19:12, HUYNH Quang-Nghi <notifications@github.com> a
écrit :

**Comment by hqnghi88** [comment]
Dear, it seems to be an old ways before validator has born. The exception occurs before validator has been taken into account. So it is really a bug, i think, no more general abstraction unless HE knows it.

**Comment by AlexisDrogoul** [comment]
Yes, there was a NPE when the species could not be extracted from the data to save, and this NPE froze the validation. I've changed a few bits but mostly accepted the correction by @hqnghi88 .
