### ISSUE TITLE
easy access to date and time in a date variable

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2403]
Hi

Currently the date variable is of format yyyy-mm-dd hh:mm:ss. Now if I want to access only date part (yyyy:mm:dd), it is just too comple. One has to change it to a string and then cast it as a date. The same with the time part (hh:mm:ss) of the date.   As suggested on the forum, the workaround is like

```php

write "current_date at cycle " + cycle + " : " + date(string(current_date, "yyyy-MM-dd"));

```

I am wondering if this can be made easy (may be with a different terminology, i use calendar and clock) ....

to get a date part of the date variable 

```php 
date d <- current_date.calendar ;
 or 
date d <- date(current_date, "calendar") ;
```

the same for the time part of the date variable: 

```php
date c <- current_date.clock;

or 

date c <- date (current_date, "clock") ;
```

internally when calendar is asked, the clock is set to 00:00:00, and when clock is asked: calendar is set to 0000:00:00, and the still use a date casting because may be it is still useful that the result is a` list<int>` of 3 items [ year, month, day] or [hour, minute, second] ... just in case that somebody wants to access individual elements of calendar and clock.

I still keep them as date so that all the current date operators can work like (difference between just the calendar dates, plus_* and minus_* among others. An example can be, I collect the current date and add some hours to it (plus_hours) based on some other logic, so if it remains a date, I can use calendar plus_hours 10 or if I collect a clock, then I can do plus_days

thank you
Srirama

**Comment by sriramab** [comment]
so if current_date is 2018-04-10 12:31;50, then current_date.calendar is 2018-04-10 00:00:00, and user can still access any of 2018, 04, 10 individually. 

and 

current_date.clock is 0000-00-00 12:31:50, and user can still access any of 12, 31, 50 individually.

**Comment by AlexisDrogoul** [comment]
Many comments here. 

First, you can access the individual components of a date by using the respective fields (.month, .year, .day, .minute, .second, .hour), which makes it easy to compose whatever information you want. 

Second, a date with no "calendar" component does simply not exist: even if year is 0, month is 1 and day is 1 (this is the minimum you could set), it is still a date in the calendar. So the `.clock` field does not make a lot of sense for me. And if what you want is a list of the time components, something like `[my_date.hour, my_date.minute, my_date.second]` is probably enough, no ? 

The only thing we could provide is a new field that would return a date with all the time components set to zero (the equivalent of `.calendar` above), although I am not completely sure of its usefulness, but you tell me !

**Comment by AlexisDrogoul** [comment]
The `.date` field has been added to `date` values, returning a new date object with only the "calendar" components (year, month, day).

**Comment by AlexisDrogoul** [comment]
I close this issue for now on. Reopen if I didn't understand the request !
