### ISSUE TITLE
problem with default editor vs external editor

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2404]
### Steps to reproduce
1. within gama, create (type) a csv (value comma value comma etc etc) , try to read it. it does not read or not read  properly

 write an excel file(2-3columns) and save as csv, read into gama, it works perfect

2. write a R script in default text editor, read it, does not work = returns NULL

write a R script in external editor, read it, works perfect

I feel something is not right with the default editor. 

### System and version 
Windows 7, GAMA 1.8RC

**Comment by AlexisDrogoul** [comment]
Hi,

Could you be more specific on how you "create" these files ? I've tried to create CSV files (using "Untitled Text File" and "File" templates (New... > Other...) and it worked well. 
Also, what do you mean by "does not read or not read properly". Without an indication of the problem, it's difficult to fix anything ... :)

Alexis

**Comment by sriramab** [comment]
Yes, It works now :) 
Nghi also made important changes to the R reader, may be that also works. I will open again if I face a problem
Thank you
