### ISSUE TITLE
how to create vertical growth cub in Gama

### ISSUE THREAD

**Issue by you68681** [gama-platform/gama#2406]
### Steps to reproduce
1.first I create a cube on the base map

2.then I want to build a new cube on the top of the specific previous cube

3.How could I take a specific previous cube and how could I build new cub on that one

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA 1.8

**Comment by ptaillandier** [comment]
Hi,

You can do something like that:
model Cube

global {
geometry bottom_cube;
geometry top_cube;
init {
bottom_cube <- cube(80);
top_cube <- cube(50) at_location (location + {0,0,bottom_cube.height});
}
}

experiment Cube type: gui {
output {
display map type: opengl {
graphics "cubes" {
draw bottom_cube color: #red border: #black;
draw top_cube color: #yellow border: #black;
}
}
}
}

Cheers,

Patrick

2018-04-14 7:30 GMT+02:00 you68681 <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
I would like to point out that this issue is not really an "issue". Please use the GAMA users mailing-list for such questions.
