### ISSUE TITLE
shortest path not always true with weights

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2407]
Please run the attached model. I have indicated the resistance of each edge on the display. I notice that agent is not always choosing a path based on the weights. If you dont see it the first time, run a few times or sometimes use the reload button. For me atleast 2 or 3 in 5 times, there is a problem. For example, if you select the home to the right top, agent should go along the diagonals, but agent travels via the side. 

Please check
[shortestPath.zip](https://github.com/gama-platform/gama/files/1919332/shortestPath.zip)

**Comment by hqnghi88** [comment]
Add this after as_edge_graph line
		g<- g with_optimizer_type "Dijkstra";
will make agent go exactly along the diagonals.
AFAIK, your problem come from the fact that default shortest path algorithm changed to NBAstar (https://codereview.stackexchange.com/questions/144376/nba-very-efficient-bidirectional-heuristic-search-algorithm-in-java-follow-u). Any heuristic algorithm will have their worst case, but it give a acceptable global view  (do every millions people can follow exactly their shortest paths?). DIjkstra compute shortest path of each road to the others so it always return true result, but you lost the computation time.
The list of algorithm can be found in libray model
["NBAStar", "NBAStarApprox", "Dijkstra", "AStar", "BellmannFord", "FloydWarshall"]
You can try to get your prefers.
