### ISSUE TITLE
save the data to the .txt file

### ISSUE THREAD

**Issue by you68681** [gama-platform/gama#2409]
### Steps to reproduce
1
when the running the following code, in the Game documentation.  the data should be saved as a new line into the file as each iteration. But when I run it, the data is overwritten in each iteration. I want the data could be saved as each iteration in a new line. How to do it?.

.model SavetoText

global {
    init {
        //Create the agents that will be saved in the text file.
        create bug number: 50;
    }

    //Reflex saving the agents every 10 steps. 
    reflex save_data when: every(10){
        //save the following text into the given text file. Note that each time the save statement is used, a new line is added at the end of the file.
        save ("cycle:" + cycle + ", mean size: " + mean(bug collect each.size)) to: "../results/data.txt";
    }
    //Reflex that will pause the simulation when the number of cycles reach 100.
    reflex end_simulation when: cycle = 100 {
        do pause;
    }
}

//Species bug that will be saved using the skill moving
species bug skills:[moving]{
    float size <- 1.0 + rnd(4) min: 1.0 max: 5.0;
    float speed <- 1.0 + rnd(4.0);

    //At each step, the size of the agent is update according to the number of bugs close to the agent
    reflex update_size {
        int nb_neigh <- length(bug at_distance 20.0);
        if (nb_neigh > 5) {
            size <- size + 1;
        } else {
            size <- size - 1;
        }
    }   

    //Make the agent move randomly
    reflex move {
        do wander;
    }

    aspect default {
        draw circle(size) color: #red;
    }
}

experiment main type: gui {
    output {
        display map {
            species bug;
        }
    }
}

2.

3.

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by dphilippon** [comment]
Hi, 
to answer your question, you need to add the facet **rewrite** and set it to true in your save statement : 
```save ("cycle:" + cycle + ", mean size: " + mean(bug collect each.size)) to: "../results/data.txt" rewrite:false;```
This facet precises that the file must not be rewritten every time that this line is executed. 
So your model should be like that : 
```
global 
{
	init 
	{
		//Create the agents that will be saved in the text file.
		create bug number: 50;
	}

	//Reflex saving the agents every 10 steps. 
	reflex save_data when: every(10#cycle)
	{
    	//save the following text into the given text file. Note that each time the save statement is used, a new line is added at the end of the file.
    	save ("cycle:" + cycle + ", mean size: " + mean(bug collect each.size)) to: "../results/data.txt" rewrite:false;
    }
	
	//Reflex that will pause the simulation when the number of cycles reach 100.
	reflex end_simulation when: cycle = 100 
	{
	    do pause;
	}

}

//Species bug that will be saved using the skill moving
species bug skills:[moving]
{
	float size <- 1.0 + rnd(4) min: 1.0 max: 5.0;
	float speed <- 1.0 + rnd(4.0);

	//At each step, the size of the agent is update according to the number of bugs close to the agent
	reflex update_size 
	{
	    int nb_neigh <- length(bug at_distance 20.0);
	    if (nb_neigh > 5) 
	    {
	        size <- size + 1;
	    } 
	    else 
	    {
	        size <- size - 1;
	    }
	}   

	//Make the agent move randomly
	reflex move 
	{
	    do wander;
	}
	
	aspect default 
	{
	    draw circle(size) color: #red;
	}

}

experiment main type: gui 
{
	output 
	{
		display map 
		{
			species bug;
		}
	}
}
```

But please, be informed that the current github issues system for Gama Platform is used only to report issues (or bugs), ask enhancements to the developers. For questions regarding the use of GAMA or its language GAML, you can go to this google group (or forum) [gama-platform@googlegroups.com](https://groups.google.com/forum/#!forum/gama-platform).

Regards,
Damien

**Comment by you68681** [comment]
thanks. I have another problem. Now I can achieve don't overwrite data. How to achieve when my model starts a new running, the previous data can disappear and add the new data into that file without overwriting.
