### ISSUE TITLE
Error with geometry shape

### ISSUE THREAD

**Issue by carlyxjack** [gama-platform/gama#2412]
### Steps to reproduce
Sorry, if my question seems very stupid, I am very new to the software GAMA, so I have not much experience with GAMA
I have written (but mostly copied from the traffic road model) code from internet in order to have agents and features available on a map

### Expected behavior
I want to have moving agents moving from buildings going outside to the road

### Actual behavior
However I already get a error related to the geometry of the envelope, which I find very weird. This problem hadn't occured to me before, but suddenly now it occurs. I don't know whether there is a problem with the path of the shapefile, but I am not sure about that .

This is the error I get 
2 occurrences in 2 agents at cycle 0: File denoted by C:/Users/vliet059/Downloads/shapefile/streets_network.shp not found.
in geometry shape <- envelope(roads_shapefile) ;
C:\Users\vliet059\Downloads\walkingv2\C:\Users\vliet059\Downloads\shapefile\streets_network.shp
C:\Users\vliet059\Downloads\walkingv2\C:\Users\vliet059\Downloads\shapefile\streets_network.shp
when applying the envelope operator on msi.gama.util.file.GamaShapeFile@17dfb75d
in initializing attribute shape
in agents Simulation 0, main_experiment60

The feature and the code of my gama project are below
[shapefile.zip](https://github.com/gama-platform/gama/files/1950635/shapefile.zip)
[help_github.txt](https://github.com/gama-platform/gama/files/1950637/help_github.txt)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by benoitgaudou** [comment]
Duplicate issue  #2410
