### ISSUE TITLE
A small issue with the existing multi-lines comment at the top of the model

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#2413]
### Steps to reproduce
1. Create a new gaml model

2. Write something in description area at the top of the model then press enter.

### Expected behavior
Tell us what should happen (include all relevant expectations)
A new comment line is inserted

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
A new line with   '  */ '  was automatically added and it showed errors (please take a look on the figure attached).
But there is any issue with a new multi-line comments 

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

GAMA 1.8 continuously built on Windows 10 64 bit, Java 1.8
![multi-lines comments](https://user-images.githubusercontent.com/11825516/39413668-14b53fa4-4c58-11e8-9360-20b66cbde405.png)

**Comment by AlexisDrogoul** [comment]
Weird behaviour indeed. It doesn't show up, however, with comments surrounded by `/***` and `***/`, so I've made a small change to the `New...` wizards to generate these multiline comments instead. I close the issue because, besides that, there is not much I can do on this "auto-edit" strategy...
