### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Amirpour** [gama-platform/gama#2414]
I am very new to GAMA. I have problem in running models in GAMA!!

My system is windows 64 and I installed Java jre1.8.0171!! But whenever I try to run something GAMA will terminate automatically with out any error. and it is not able to run anything.

Do you know what went wrong? Is the Java version correct? I have already changed the Path in system Environment.

**Comment by sriramab** [comment]
Hi

Which version of gama are you using ? try this latest version 
[link to latest](https://github.com/gama-platform/gama/releases/download/latest/GAMA1.8_Win_64_05.08.18_2b4e536.zip)

**Comment by Amirpour** [comment]
Hi,
I downloaded the latest version that you gave me. the path of the system variable is "C:\Program Files\Java\jre1.8.0_171\bin"
But it is still not working! I have windows 7...

**Comment by Amirpour** [comment]
This time when I open GAMA I saw this error "Plug-in ummisco.gama.ui.shared was unable to load class ummisco.gama.ui.views.InteractiveConsoleView."

**Comment by Amirpour** [comment]
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000576c95ab, pid=5288, tid=0x0000000000001a84
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  0x00000000576c95ab
#
hs_err_pid5288 file:
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by hqnghi88** [comment]
Hi,
I propose to install JDK (not jre), its written on document (https://github.com/gama-platform/gama/wiki/Installation) and close this topic (not a real issue). You can find more helps for installations in forums ( http://gama-platform.org/community#UserForum)
