### ISSUE TITLE
Problem with map (and date?)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2415]
### Steps to reproduce
1. test the following expression:
map<date,float> vals2 <- [date([2011,1,1])::1.0];
write current_date in vals2.keys;
write vals2[current_date];

### Expected behavior
The first "write" should write "true" and the second, "1.0"

### Actual behavior
The first "write" writes true, but the second writes nil.

**Comment by AlexisDrogoul** [comment]
Hashcode of dates were not correctly computed. Hence the error.
