### ISSUE TITLE
Gama 1.8 Linux 64 RC1 not starting on Debian 10 + openjdk 10 

### ISSUE THREAD

**Issue by ierpe** [gama-platform/gama#2416]
### Steps to reproduce

1. Extract and launch Gama 1.8 Linux 64 RC1 on Debian 10 (Buster / Testing) with openjdk 10 installed

2. Gama starts and offers to select a new workspace because of outdated libraries, which I do.

3. Gama crashes and error message says to look into the logs

Results from terminal : 

```
⇒  ./Gama 
Bad value: "${target.nl}" for NL. Using system default.
>GAMA version 1.7.0.201804170248 loading...
>GAMA models library version: .built_in_models_1526460126420
```

Log file : [gama.log](https://github.com/gama-platform/gama/files/2008236/gama.log)

### System and version 
Debian 10 (Buster / Testing) + openjdk 10

**Comment by benoitgaudou** [comment]
Hi,

I admit that GAMA is not expected not run well with java 10 AND the openjdk.
In fact, it is developed and expected to be used with Java Oracle JDK 1.8.

Cheers

Benoit


2018-05-16 10:52 GMT+02:00 Piero <notifications@github.com>:

**Comment by ierpe** [comment]
And that is perfectly fine thanks you :)
Switching to jdk 1.8 solved it.
