### ISSUE TITLE
Date parsing with months in words not working properly

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2417]
### Steps to reproduce
1. get a date as a string and convert it as a date:
```
global{
	
	init{	
		date date1 <- date("1999-12-30", 'yyyy-MM-dd');
		write date1;
		
		date date2 <- date("14:02:31",'HH:mm:ss');
		write date2;
		
		date date3 <- date("1999-12-30 14:02:31", 'yyyy-MM-dd HH:mm:ss');
		write date3;		
	}	
}


experiment simulation {
}
```

### Expected behavior
It should display three dates.

### Actual behavior
It works for date1 (calendar day) and date2 (time of the day), but not with a mix of them (date3):

1999-12-30 00:00:00
1970-01-01 14:02:31
1970-01-01 14:02:31

Additionnaly, parsing month as text (Jan, Jul) does not seem to work, whatever the syntax (MM, MMM, LLL, L, ...)

### System and version 
Gama 1.7.0
Java 1.8

After a quick search on the internet, it seems that some changes could have occur for the date with Java 1.8...

**Comment by AlexisDrogoul** [comment]
I've normally fixed 2 of the 3 issues displayed in this thread (please make separate ones next time). Please check. The remaining one is "parsing Month as text", which I don't really understand (are you using the ISO format ?)

**Comment by tnguyenh** [comment]
Yes, it's working now. For parsing Month as text, I mean something like this:

		date date4 <- date("03 Jan 2007","dd LLL yyyy");
		write date4;

This still does not work.

Next time I'll open different issues. I thought all of these might have had the same cause.

**Comment by AlexisDrogoul** [comment]
Two problems detected here: case sensitivity (ISO patterns are case sensitive unless they are built to accept mixed cases), and locale... As a matter of fact, you were probably trying to decode the text using the default locale on your computer ("fr").

I've then turned Formatters to be case insensitive (both "Jan" and "jan" are parsed the same) and a new operator date(...) that takes the locale as an argument in case you don't want to use the default one. 

Not all the combinations seem to work well, but things like:  

```
date date4 <- date("03 Janvier 07","dd MMMM yy","fr");
date date4 <- date("03 Jan 07","dd MMM yy","us");
date date4 <- date("03 JANUARY 07","dd MMMM yy","us");
```

are now recognised and parsed correctly.
