### ISSUE TITLE
Can't run the predatorPrey model in headless mode

### ISSUE THREAD

**Issue by AntonLuca** [gama-platform/gama#2418]
Good morning everyone, 
I'm having trouble while trying to run the predatorPrey model in headless mode.  I am working on a project with @agrignard at the MIT Media Lab using GAMA Platform. I would greatly appreciate any help you can provide me with.
### Steps to reproduce
1. I have a Window machine.  I've installed GAMA1.8, the lastest version of Java and Eclipse DSL Oxygen 3A. The last step was made by following the instruction in https://github.com/gama-platform/gama/wiki/InstallingGitVersion. It was an attempt to meet the issue reported in the log.

2. I've followed the instruction in https://github.com/gama-platform/gama/wiki/Headless and https://github.com/gama-platform/gama/wiki/Headless-mode-for-dummies

3. Specifically, 
[gamaConfiguration.txt](https://github.com/gama-platform/gama/files/2055753/gamaConfiguration.txt)
I've replaced the absolute path in the gama-headless.bat (otherwise it will not work), then I've open a command prompt, moved in the headless directory and executed the command "C:\Program Files\GAMA1.8\headless>gama-headless.bat samples/predatorPrey.xml outputHeadLess"

### Expected behavior
The execution would run successfully providing the results of the execution in the output directory.

### Actual behavior
The execution stops, returning this issue:

******************************************************************
* GAMA version 1.7.0                                             
* http://gama-platform.googlecode.com                            
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC and Partners            
******************************************************************
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
An error has occurred. See the log file
C:\Program Files\GAMA1.8\headless\.work19132\.metadata\.log.

The Log content is reported below:

!SESSION 2018-05-30 23:19:51.712 -----------------------------------------------
eclipse.buildId=4.7.3.M20180330-0640
java.version=10.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -application msi.gama.headless.id4 samples/predatorPrey.xml outputHeadLess
Command-line arguments:  -application msi.gama.headless.id4 -data .work19132 samples/predatorPrey.xml outputHeadLess

!ENTRY org.eclipse.osgi 4 0 2018-05-30 23:19:53.144
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "msi.gama.headless.id4" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.ant.ui.antRunner, org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.emf.codegen.CodeGen, org.eclipse.emf.codegen.JMerger, org.eclipse.emf.codegen.ecore.Generator, org.eclipse.emf.importer.ecore.Ecore2GenModel, org.eclipse.emf.importer.java.Java2GenModel, org.eclipse.emf.importer.rose.Rose2GenModel, org.eclipse.emf.mwe.core.WorkflowRunner, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.director, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.publisher.InstallPublisher, org.eclipse.equinox.p2.publisher.EclipseGenerator, org.eclipse.equinox.p2.publisher.ProductPublisher, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, org.eclipse.equinox.p2.reconciler.application, org.eclipse.equinox.p2.repository.repo2runnable, org.eclipse.equinox.p2.repository.metadataverifier, org.eclipse.equinox.p2.artifact.repository.mirrorApplication, org.eclipse.equinox.p2.metadata.repository.mirrorApplication, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor, org.eclipse.equinox.p2.updatesite.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.CategoryPublisher, org.eclipse.oomph.setup.core.SetupArchiver, org.eclipse.pde.build.Build, org.eclipse.pde.junit.runtime.uitestapplication, org.eclipse.pde.junit.runtime.legacytestapplication, org.eclipse.pde.junit.runtime.coretestapplication, org.eclipse.pde.junit.runtime.coretestapplicationnonmain, org.eclipse.pde.junit.runtime.nonuithreadtestapplication, org.eclipse.ui.ide.workbench, org.eclipse.help.base.infocenterApplication, org.eclipse.help.base.helpApplication, org.eclipse.help.base.indexTool, org.eclipse.jdt.apt.core.aptBuild, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
	at org.eclipse.core.launcher.Main.main(Main.java:34)

### System and version 
Just  in case,  I'm attaching the content of Help>Installation Details>Configuration
[gamaConfiguration.txt](https://github.com/gama-platform/gama/files/2055756/gamaConfiguration.txt)

**Comment by benoitgaudou** [comment]
Hi,
I just tried the headless of this example and it work perfectly for me.
But I was on MacOSX ... 

I used the GAMA 1.8 preRelease version (the compiled and release version of GAMA).
I did not change the launch script and run it from inside the headless forlder...

**Comment by hqnghi88** [comment]
if you use win 10, try in powershell , with the sh script (version of linux)

**Comment by agrignard** [comment]
@AntonLuca what OS are you using?

**Comment by AntonLuca** [comment]
![os](https://user-images.githubusercontent.com/7645227/40851684-7ba8ceea-65c8-11e8-9252-6748ad998bc0.png)
Also, I downloaded the Gama version for Linux and tried to run it with the PowerShell but it returns this error message:
"sh : The term 'sh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ sh gama-headless.sh samples/predatorPrey.xml outputHeadLess"

**Comment by agrignard** [comment]
@hqnghi88 It seems that @AntonLuca still have some problem with the headless. They would love to use it to explore there model. Any idea?

**Comment by hqnghi88** [comment]
use win64 version (i mentioned sh in powershell, not the linux version).
open powershell and cd to headless folder in gama. then call this:

.\gama-headless.bat .\samples\predatorPrey.xml samples

![image](https://user-images.githubusercontent.com/6105384/41358053-bd83e902-6f51-11e8-92ab-95b1786349c7.png)

**Comment by AntonLuca** [comment]
Thank you very much for your assistance. 
Unfortunately by following your instructions it is still not working. 
Some additional information that may be needed: I am using JRE 10.0.1 and Eclipse Oxygen.3a Release (4.7.3a) Build id: 20180405-1200.  After its installation, I've followed the instructions in https://github.com/gama-platform/gama/wiki/InstallingGitVersion. 

It  follows what i obtain when I open powershell, cd to headless folder in gama, and call .\gama-headless.bat .\samples\predatorPrey.xml samples

![shell](https://user-images.githubusercontent.com/7645227/41362471-c2d010cc-6f31-11e8-9445-c9599e7eddce.png)

The log file:

!SESSION 2018-06-13 17:27:52.801 -----------------------------------------------
eclipse.buildId=4.7.3.M20180330-0640
java.version=10.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -application msi.gama.headless.id4 .\samples\predatorPrey.xml output
Command-line arguments:  -application msi.gama.headless.id4 -data .work27013 .\samples\predatorPrey.xml output

!ENTRY org.eclipse.osgi 4 0 2018-06-13 17:27:54.545
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "msi.gama.headless.id4" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.ant.ui.antRunner, org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.emf.codegen.CodeGen, org.eclipse.emf.codegen.JMerger, org.eclipse.emf.codegen.ecore.Generator, org.eclipse.emf.importer.ecore.Ecore2GenModel, org.eclipse.emf.importer.java.Java2GenModel, org.eclipse.emf.importer.rose.Rose2GenModel, org.eclipse.emf.mwe.core.WorkflowRunner, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.director, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.publisher.InstallPublisher, org.eclipse.equinox.p2.publisher.EclipseGenerator, org.eclipse.equinox.p2.publisher.ProductPublisher, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, org.eclipse.equinox.p2.reconciler.application, org.eclipse.equinox.p2.repository.repo2runnable, org.eclipse.equinox.p2.repository.metadataverifier, org.eclipse.equinox.p2.artifact.repository.mirrorApplication, org.eclipse.equinox.p2.metadata.repository.mirrorApplication, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor, org.eclipse.equinox.p2.updatesite.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.CategoryPublisher, org.eclipse.oomph.setup.core.SetupArchiver, org.eclipse.pde.build.Build, org.eclipse.pde.junit.runtime.uitestapplication, org.eclipse.pde.junit.runtime.legacytestapplication, org.eclipse.pde.junit.runtime.coretestapplication, org.eclipse.pde.junit.runtime.coretestapplicationnonmain, org.eclipse.pde.junit.runtime.nonuithreadtestapplication, org.eclipse.ui.ide.workbench, org.eclipse.help.base.infocenterApplication, org.eclipse.help.base.helpApplication, org.eclipse.help.base.indexTool, org.eclipse.jdt.apt.core.aptBuild, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
	at org.eclipse.core.launcher.Main.main(Main.java:34)

**Comment by hqnghi88** [comment]
Dear,
Firstly, Java version must strictly be JDK (not JRE) 1.8 (build 161 or greater). 10 and even 1.9 are not supported now. Secondly, why did you alway mention about git version? Just download a release then you can use headless mode already. Or i missed something, do you want to run headless in eclipse? If not, i recommend to remove 10 and install the right version (jdk 1.8). we ll see.

**Comment by AntonLuca** [comment]
No, you are right I don't need to run headless in Eclipse.
Anyway, I removed the former version of java and installed the JDK 1.8.
It gives me the same result as before.
******************************************************************
* GAMA version 1.7.0                                             *
* http://gama-platform.googlecode.com                            *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC and Partners            *
******************************************************************
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
An error has occurred. See the log file

The log file

!SESSION 2018-06-13 20:55:55.868 -----------------------------------------------
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -application msi.gama.headless.id4 .\samples\predatorPrey.xml samples
Command-line arguments:  -application msi.gama.headless.id4 -data .work2245 .\samples\predatorPrey.xml samples

!ENTRY org.eclipse.osgi 4 0 2018-06-13 20:55:57.604
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "msi.gama.headless.id4" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.ant.ui.antRunner, org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.emf.codegen.CodeGen, org.eclipse.emf.codegen.JMerger, org.eclipse.emf.codegen.ecore.Generator, org.eclipse.emf.importer.ecore.Ecore2GenModel, org.eclipse.emf.importer.java.Java2GenModel, org.eclipse.emf.importer.rose.Rose2GenModel, org.eclipse.emf.mwe.core.WorkflowRunner, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.director, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.publisher.InstallPublisher, org.eclipse.equinox.p2.publisher.EclipseGenerator, org.eclipse.equinox.p2.publisher.ProductPublisher, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, org.eclipse.equinox.p2.reconciler.application, org.eclipse.equinox.p2.repository.repo2runnable, org.eclipse.equinox.p2.repository.metadataverifier, org.eclipse.equinox.p2.artifact.repository.mirrorApplication, org.eclipse.equinox.p2.metadata.repository.mirrorApplication, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor, org.eclipse.equinox.p2.updatesite.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.CategoryPublisher, org.eclipse.oomph.setup.core.SetupArchiver, org.eclipse.pde.build.Build, org.eclipse.pde.junit.runtime.uitestapplication, org.eclipse.pde.junit.runtime.legacytestapplication, org.eclipse.pde.junit.runtime.coretestapplication, org.eclipse.pde.junit.runtime.coretestapplicationnonmain, org.eclipse.pde.junit.runtime.nonuithreadtestapplication, org.eclipse.ui.ide.workbench, org.eclipse.help.base.infocenterApplication, org.eclipse.help.base.helpApplication, org.eclipse.help.base.indexTool, org.eclipse.jdt.apt.core.aptBuild, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
	at org.eclipse.core.launcher.Main.main(Main.java:34)

**Comment by AntonLuca** [comment]
Some additional information that may be needed: I am using JDK 1.8.0_171 and Eclipse Oxygen.3a Release (4.7.3a) Build id: 20180405-1200.

**Comment by AlexisDrogoul** [comment]
And does this version of GAMA (UI) run normally ?

**Comment by AntonLuca** [comment]
Yes, it does. 
And Thanks again for the contribution you all are putting into this issue. I appreciate that very much!

**Comment by hqnghi88** [comment]
Can you rum powershell as admin by right click,  run as admin. Or move the gama1.8 folder out of program files, or even Drive C. Then retry

**Comment by AntonLuca** [comment]
Tes, I did. But with no lucky!

![shell](https://user-images.githubusercontent.com/7645227/41484246-61d8f796-70dc-11e8-83d0-4dcc162d1101.png)

**Comment by agrignard** [comment]
@AntonLuca and @hqnghi88 I think you found the problem, can you update the documentation according to what was missing so it will benefit to potential other user?

**Comment by AlexisDrogoul** [comment]
And please explain the solution in the issue as well. Or put a link to the doc, but don't close it before.

**Comment by hqnghi88** [comment]
Sorry for late comment, i did not found a real technical solution for his case. His gama is placed in "Program Files" folder, a mysteriuos place as same as App in MacOS. The code in bat cannot find the required jar for the classpath , to execute java headless. I fixed the path in .bat file  on Anton machine to point directly to plugin folder so it can run in "Program Files". 
I ve just tested and if he move Gama to a user's folder (such as "C:/User/his_name") , batch command work well. (antone have only 1 logical drive C, i suggest to move to D, but he couldnt)
SO, may be we documented it to not place gama it that folder, OR someone else found solution to execute in such context?
Cheers.

**Comment by tcquang** [comment]
Dear AntonLuca,
Did you try to give the full control permissions to users who access the
folder?
By default, Windows 64bit does not allow users (programs) to write temporal
files in any folder located inside of Program Files.
Thus, you can give full control to the user "EveryOne" for the folder of
Gama if you want to put it in the Program Files.
https://social.technet.microsoft.com/Forums/ie/en-US/3dd0d2f9-5b2f-46df-950f-36887c98369c/give-full-permission-for-the-users-in-program-files-folder?forum=w7itprogeneral

Cheers,
Quang

**Comment by AntonLuca** [comment]
Indeed, Nghi (1) fixed the path names in the .jar and in .bat files, (2) changed the access permission to the files in the headless folder and in the Program Files,  and (3) used PowerShell as the system administrator.
Please @hqnghi88, if I'm forgetting any step of the procedure you made, feel free to add it to the procedure I just described.
So, maybe yes the easiest solution would be to place GAMA in a folder which is not subject to restrictions on access, such as "C:/User/his_name", as @hqnghi88 says.
Bests,
Antonio Luca
PS: I take this opportunity to thank the whole team and @hqnghi88 in particular for the valuable help I was given.

**Comment by AlexisDrogoul** [comment]
So we can close this issue (has the case been documented, @hqnghi88 ?). Thanks to all.
