### ISSUE TITLE
Ubuntu / Menu of species agents is empty

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2419]
### Steps to reproduce
1. When running a model, on the top-level menu "Agents" > Simulation 0 > click on a species

### Expected behavior
The list of each agent of this species appears, and we can click on 1 agent to inspect it.

### Actual behavior
No agent name is dsiplayed in the menu.

### System and version 
GAMA 1.8 preRelease, Ubuntu

**Comment by AlexisDrogoul** [comment]
Which JDK are you running GAMA on ?

**Comment by benoitgaudou** [comment]
I was pretty sure it was on the oracle jdk 1.8.
But it was on some other people computer, so I need to test it on my own one before being sure.

**Comment by AlexisDrogoul** [comment]
Any update on this one ?

**Comment by hqnghi88** [comment]
Just test on ubuntu 18 , oracle 8. works
![screenshot from 2018-07-03 02-09-07](https://user-images.githubusercontent.com/6105384/42181730-1b2915fa-7e66-11e8-8ec7-d97b9c7d4963.png)

**Comment by AlexisDrogoul** [comment]
OK. thank you @hqnghi88. So lets close this thread.
