### ISSUE TITLE
Physics Engine model loading asc file crashes after rerunning an experiment 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#242]
**Describe the bug**
Physics Engine broken and it seems to be link with the loading of asc file as it's not happening with other physics engine model

**To Reproduce**
1. Open Physics Engine/Flow on terrain.gaml
2. Launch any experiment
3. Run it (it works)
4. Relaunch the experiment
5. Gama crashes 

**Expected behavior**
No crash

**Desktop (please complete the following information):**
 - OS: Mac OS
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: GAMA2024_06 with JDK (runnign with an embeded jdk21) not happening with 1.9.3
 - Java version: jdk21

**Comment by AlexisDrogoul** [comment]
After fixing #265, I cannot reproduce the problem anymore described here. @agrignard can you test it by switching to the branch https://github.com/gama-platform/gama/tree/Addresses-bugs-in-physics-plugin-%23265-%23242 ?

**Comment by lesquoyb** [comment]
It has been merged into the main branch, you can just pull the latest commits on the usual branch to check :)
Working on my computer, I don't have any crash for the version before the commits but there were errors in the eclipse console that are not here anymore after so I guess it's fixed. Letting @agrignard closing it though

**Comment by lesquoyb** [comment]
I consider this lack of answer as a "everything's fine now". Feel free to reopen in case it was not the case
