### ISSUE TITLE
Init order (in global variables) with grid agents

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2420]
### Steps to reproduce
1. I run the following model:
````
model NewModel1

global {
	int i1 <- 12;
	int i2 <- 45 - 70;
	int i3 <- i1 + i2;

	init {
		write "--- init global --";
		write i1;
		write i2;
		write "i3 == " + i3 ;
		write "----FIN IG ----";		
	}
}

grid toto width: 1 height: 2 {
	init {
		write "--- init Itoto -- " + self;		
		write i1;
		write i2;
		write "i3 == " + i3 ;
		write "----FIN Itoto ----";				
	}
}

experiment name type: gui {}
````

### Expected behavior
I was expected the following result.
This would mean that first the global variables are initialized.
Here it appears that i3 is not initializaed as it is computed from 2 other global variables.
````
--- init Itoto -- toto(0)
12
-25
i3 == -13
----FIN Itoto ----

--- init Itoto -- toto(1)
12
-25
i3 == -13
----FIN Itoto ----

--- init global --
12
-25
i3 == -13
----FIN IG ----
````

### Actual behavior
I get the following result. It means that when the init of the grid is called, the i3 variable has not been yet initialized properly.
````
--- init Itoto -- toto(0)
12
-25
i3 == null
----FIN Itoto ----

--- init Itoto -- toto(1)
12
-25
i3 == null
----FIN Itoto ----

--- init global --
12
-25
i3 == -13

----FIN IG ----
````

### System and version 
GAMA Git, MACOSX

**Comment by AlexisDrogoul** [comment]
I've fixed it, but the fix reveals a number of compilation issues (cycling issues) in at least 4 models of the library (basically models where a species uses a global variable, whose value is initialised using the agents of this species). I have to correct them before pushing the fix. Other possible issue: a (limited, but perceptible) decrease in performances in the validation of models, as the whole syntactic tree is now traversed to identify dependencies between variables.
