### ISSUE TITLE
problem to rotate text in opengl

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2422]
Hi

The rotate  is not able to rotate the text in the draw statement. There is also a unanswered question in the forum about how to rotate the text but there is no solution yet. May be a bug?

I am using  the following syntax, but it has no impact on rotation.
```php
draw string("Satisfaction") at:{-3,5} rotate: 90::{0,1,0} color:#black font:font("Helvetica", 20 , #plain) perspective:false;
```

**Comment by sriramab** [comment]
[here](https://groups.google.com/forum/#!searchin/gama-platform/text$20rotation%7Csort:date/gama-platform/s_Dus7V8XKE/x05hCkxNBQAJ) the forum post

**Comment by sriramab** [comment]
here is the result without any effect on rotation 

![aspects_model_display_d2_size_763x893_cycle_0_time_1528290602541](https://user-images.githubusercontent.com/12668606/41040158-e6bf2d2e-699b-11e8-8435-334bef2cf3bb.png)

**Comment by AlexisDrogoul** [comment]
Right. I've enabled the rotation for texts in my forthcoming commit, but, obviously, it will only work for `perspective: true`.

**Comment by sriramab** [comment]
Thank you Alexis. It works but they are placed very far away from their intended location.
![rotate far](https://user-images.githubusercontent.com/12668606/41140892-2e4808d2-6af0-11e8-905a-fed561537072.png)

**Comment by sriramab** [comment]
Here is what I used 

```php
/**
* Name: mm
* Author: Ram
* Description: 
* Tags: Tag1, Tag2, TagN
*/
model mm


global
{
/** Insert the global definitions, variables and actions here */
//
	init
	{
		float seed <- 123.789;
		create a number: 10
		{
			location <- { rnd(100), rnd(100) };
		}

		create b number: 5;
	}

}

species a skills: [moving]
{
	aspect default
	{
		draw circle(3) color: # blue;
		draw string(name) color: # black rotate: 40;
	}

	reflex aa
	{
		do wander;
	}

}

species b
{
	rgb col <- # red;
	list<a> aaa;
	reflex c_capture when: cycle = 10
	{
		aaa <- a at_distance 15;
		if !empty(aaa)
		{
			col <- # orange;
		}

		capture target: aaa as: c;
	}

	reflex c_release when: cycle > 15
	{
		release c as: a in: world;
		if empty(aaa)
		{
			col <- # purple;
		}

	}

	aspect default
	{
		draw circle(3) color: col;
	}

	species c parent: a skills: [moving]
	{
		reflex cc
		{
			do wander speed: 5;
		}

		aspect default
		{
			draw circle(3) color: # green;
		}

	}

}

experiment mm type: gui
{
/** Insert here the definition of the input and output of the model */
//float seed <- 123.789;
	output
	{
		display d type: opengl
		{
			species a;
			species b;
		}

	}

}

```
