### ISSUE TITLE
write species writes the name of the species

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2423]
Hi

Not sure if this a bug, here is the case.

If you have any species, and then in a write statement ` write species_name ` , I was hoping it would write all the agents of that species. I am wrong, so I then changed to ` write list(species_name)` .. then I get the correct result = list of all agents. However, if you just use `write species_name` it prints species_name to the console. This is odd to me because i think a write statement should take a string or show contents of a variable and not take the species_name and literally print the species_name to the console. Is this what is intended?

Srirama

**Comment by AlexisDrogoul** [comment]
Hi, it is intended to be this way. Species are first-class citizens of the model so when you "write" them, they write their name (like agents, for instance). And you did the right thing asking for the list to get the agents. Actually, `agents of_species my_species` would also work.
