### ISSUE TITLE
Action fails to return result but does with do statement and returns facet

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2424]
I try to retrieve a list from an action and as advice in the wiki, I catch the return statement in a temporary variable. While it works with the deprecated do / returns combo, it does not seems to work with the new syntax. 

```
model bugreturnaction

global{
	init{
		create caller_species;
		create called_species;
	}
	reflex stop_simu when:step=1{ do pause;}
}

species called_species{
	
	list<int> super_action {
		int x;
		list<int> my_x;
		loop i from:1 to:10{
			x <- x+1;
			add x to:my_x;
		}
		return my_x;
	}
	
}

species caller_species {
	reflex call_super_action {	
		ask called_species {
			do super_action returns:my_super_return;
			write sample(my_super_return);
			
			list<int> my_bad_return <- list<int>(

super_action);
			write sample(my_bad_return);
			
		}
	}
}

experiment name type: batch {}
```

### Expected behavior

We should have the same result for both syntax

### Actual behavior

Consol output is:
```
my_super_return -: [1,2,3,4,5,6,7,8,9,10]
my_bad_return -: [0]
```

### System and version 
Up to date with GitHub master repository, on Mac OSX High sierra

**Comment by AlexisDrogoul** [comment]
Simply a problem of syntax. 

- `list<int> my_bad_return <- list<int>(super_action);` stores in `my_bad_return` the casting of `super_action` as an `action` to a `list` of `int`, effectively returning `[0]`. Removing the cast to `list<int>` lets a warning appear about this. 

- `list<int> my_bad_return <- self.super_action();` or `<- super_action();` will do what you want.
