### ISSUE TITLE
content assist missing in new versions

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2425]
Hi

There used to be content assist in GAMA GUI previously, but in the new versions of 1.8 it seems to have been disabled (or removed).  I would like to request to restore this feature as it is really useful for coding especially when dealing with agent attributes. 

If it has been disabled, how do I re-enable it ?

Thank you.

**Comment by AlexisDrogoul** [comment]
Working for me on macOS. Please precise your environment, etc.

**Comment by sriramab** [comment]
I am on Windows 7, GAMA Standalone updated 7th June 2018 
Or do you mean something else as environment?

**Comment by AlexisDrogoul** [comment]
Any update ? Content assist seems to work for everyone.

**Comment by hqnghi88** [comment]
Works for me on win 10.

**Comment by sriramab** [comment]
strangely working again  in the new build :+1:

thank you
