### ISSUE TITLE
batch permanent display is blank after resizing

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2426]
### Steps to reproduce
1. I run the toy example:

```

model Schelling

global { 
	float tolerance <- 0.5 ;
}


experiment SchellingBatch type: batch 
 				until: (flip(0.1)) 
 				repeat: 2
{	
	parameter "Tolerance rate" var: tolerance min: 0.5 max: 0.7 step: 0.1;
	
	method exhaustive;
	
	permanent {
		display d2 {
			chart "nb Cycles" type:series {
				data "nb cycle" value: mean(simulations collect(each.cycle)) 
					y_err_values: [
						mean(simulations collect(each.cycle)) - mean_deviation(simulations collect(each.cycle)) ,
						mean(simulations collect(each.cycle)) + mean_deviation(simulations collect(each.cycle))
					]
					thickness: 3;
			}			
		}
	}		
}
```

2. When I run the experiment, at the end of the experiment plan, the permanent display contains the various data. 

### Expected behavior
When I resize the permanent display, it should repaint the data.

### Actual behavior
After resizing the display, the display remains blank.

### System and version 
MAC OSX, Git

**Comment by AlexisDrogoul** [comment]
Well. Yes. Never thought it could be a problem until you tried it ! Basically, the screen becomes empty because the experiment agent is disposed (dead) right after all the simulations are run. I don't see clearly how to change this behaviour right now.
