### ISSUE TITLE
agent does not enter/ exit reversed polylines on a graph 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2429]
This has reference to my forum post [link](https://groups.google.com/forum/#!topic/gama-platform/f1SslrlogfE). I believe this to be a bug as it leads to wrong calculations of path. 

In summary, an agent when using moving skills (on a network created with reversed polylines for two-way roads) does not exit or enter the graph on these reversed polylines. 

A model is attached 

Srirama

```php 
/***
* Name: pathModels
* Author: Srirama Bhamidipati
* Description: 
* Tags: Tag1, Tag2, TagN
***/
model pathModels


global
{
/** Insert the global definitions, variables and actions here */
	list<geometry> gg <- [polyline([{ 10, 10 }, { 20, 20 }]), polyline([{ 20, 20 }, { 20, 40 }]), polyline([{ 20, 40 }, { 40, 80 }]), polyline([{ 50, 20 }, { 20, 20 }]), polyline([{
	50, 50 }, { 20, 20 }])];
	graph g;
	init
	{
		create road from: gg
		{
		}

		loop i over: road
		{
			create road
			{
				shape <- polyline(reverse(copy(i.shape.points)));
			}

		}

		create building number: 1
		{
			location <- { 16, 9 };
		}

		create building number: 1
		{
			location <- { 27, 80 };
		}

		create building number: 1
		{
			location <- { 60, 20 };
		}

		create people number: 2
		{
			location <- any_location_in(building[1]);
			the_target <- building[0];
			people[0].my_name <- "srirama";
			people[1].my_name <- "unknown";
		}

		g <- directed(as_edge_graph(road));
		g <- g with_optimizer_type "Dijkstra";
	}

}

species people skills: [moving]
{
	building the_target;
	string my_name;
	path p;
	path pp;
	path p2;
	reflex keep_moving when: location != the_target.location
	{
	//		path path_followed <- self goto [target::the_target, on::g, return_path::true, recompute_path::true];
	//		write agent_from_geometry(path_followed, path_followed.edges[0]);
	//		write path_followed;
		using g
		{
			p2 <- path_to(self, the_target.location);
		}

		if my_name = "srirama"
		{
			do follow path: p2;
			write p2;
			write "--------------";
		} else if my_name = "unknown"
		{
		//path path_followed <- self goto [target::the_target, on::g, return_path::true, recompute_path::true];
		//	write path_followed;
		}

	}

	aspect default
	{
		draw circle(1) color: # red;
		draw my_name color: # black;
	}

}

species building
{
	geometry shape <- square(5);
	aspect default
	{
		draw shape color: # orange;
		draw string(int(self)) color: # black;
	}

}

species road
{
	aspect default
	{
		draw shape + 0.1 color: # blue; // end_arrow: 4;
		//draw shape end_arrow: 2 color: # white;
		draw string(int(self)) color: # black font: font(10) rotate: direction_to(self.shape.points[0], self.shape.points[length(shape.points) - 1]);
	}

}

experiment doesnt_Work type: gui
{
/** Insert here the definition of the input and output of the model */
	output
	{
		display "d"
		{
			species road;
			species building;
			species people;
		}

	}

}

```

**Comment by sriramab** [comment]
Almost the same model as above but I flipped the original and reversed polylines, and I get a different  result, and I notice that I can get not two extra but two less edges depending on which side of the polyline  the destination is.


```php
/***
* Name: pathModels
* Author: Srirama Bhamidipati
* Description: 
* Tags: Tag1, Tag2, TagN
***/
model pathModels


global
{
/** Insert the global definitions, variables and actions here */
	list<geometry> gg <- [polyline([{ 20, 20 }, { 10, 10 }]), polyline([{ 20, 20 }, { 20, 40 }]), polyline([{ 40, 80 }, { 20, 40 }]), polyline([{ 50, 20 }, { 20, 20 }]), polyline([{
	50, 50 }, { 20, 20 }])];
	graph g;
	init
	{
		create road from: gg
		{
		}

		loop i over: road
		{
			create road
			{
				shape <- polyline(reverse(copy(i.shape.points)));
			}

		}

		create building number: 1
		{
			location <- { 16, 9 };
		}

		create building number: 1
		{
			location <- { 27, 80 };
		}

		create building number: 1
		{
			location <- { 60, 20 };
		}

		create people number: 2
		{
			location <- any_location_in(building[1]);
			the_target <- building[0];
			people[0].my_name <- "srirama";
			people[1].my_name <- "unknown";
		}

		g <- directed(as_edge_graph(road));
		g <- g with_optimizer_type "Dijkstra";
	}

}

species people skills: [moving]
{
	building the_target;
	string my_name;
	path p;
	path pp;
	path p2;
	reflex keep_moving when: location != the_target.location
	{
	//		path path_followed <- self goto [target::the_target, on::g, return_path::true, recompute_path::true];
	//		write agent_from_geometry(path_followed, path_followed.edges[0]);
	//		write path_followed;
		using g
		{
			p2 <- path_to(self, the_target.location);
		}

		if my_name = "srirama"
		{
			do follow path: p2;
			write p2;
			write "--------------";
		} else if my_name = "unknown"
		{
		//path path_followed <- self goto [target::the_target, on::g, return_path::true, recompute_path::true];
		//	write path_followed;
		}

	}

	aspect default
	{
		draw circle(1) color: # red;
		draw my_name color: # black;
	}

}

species building
{
	geometry shape <- square(5);
	aspect default
	{
		draw shape color: # orange;
		draw string(int(self)) color: # black;
	}

}

species road
{
	aspect default
	{
		draw shape + 0.1 color: # blue; // end_arrow: 4;
		//draw shape end_arrow: 2 color: # white;
		draw string(int(self)) color: # black font: font(10) rotate: direction_to(self.shape.points[0], self.shape.points[length(shape.points) - 1]);
	}

}

experiment doesnt_Work type: gui
{
/** Insert here the definition of the input and output of the model */
	output
	{
		display "d"
		{
			species road;
			species building;
			species people;
		}

	}

}

```

**Comment by sriramab** [comment]
I just created a very simplified model and you will notice this strange behavior clearly. Agent do not take the shortest path using the reverse road, but first go to original road and then to the reverse road

```php
/**
* Name: speed
* Author: Ram
* Description: 
* Tags: Tag1, Tag2, TagN
*/
model speeds


global
{
/** Insert the global definitions, variables and actions here */
	list<geometry> g <- polyline([{ 10, 50 }, { 90, 50 }]); //, polyline([{ 10, 70 }, { 90, 70 }])];
	geometry dest <- square(3);
	graph gr;
	init
	{
		create dest_location from: dest
		{
			location <- { 5, 50 };
		}

		create road from: g
		{
			create road
			{
				shape <- polyline(reverse(copy(myself.shape.points)));
			}

		}

		gr <- directed(as_edge_graph(road));
		create people number: 2;
		people[0].location <- { 50, 30 };
		people[1].location <- { 30, 70 };
	}

}

species dest_location
{
	aspect default
	{
		draw shape color: # orange;
		draw "Target" color: # black font: font(20) at: location + { -3, -5, 0 };
	}

}

species road
{
	aspect default
	{
		if int(self) = 0
		{
			draw shape + 0.1 at: location + { 0, -2, 0 } color: # black end_arrow: 3;
			draw "original road" at: location + { 0, -3, 0 } color: # black;
		} else
		{
			draw shape + 0.1 color: # red end_arrow: 3;
			draw "reverse road" at: location + { -20, 3, 0 } color: # red;
		}

	}

}

species people skills: [moving]
{
	reflex movement
	{
		do goto target: dest_location[0] on: gr speed: 1.0;
	}

	aspect default
	{
		draw circle(3) color: # green;
		draw string(int(self)) color: # white;
	}

}

experiment speeds type: gui
{
/** Insert here the definition of the input and output of the model */
	output
	{
		display d
		{
			species people;
			species road;
			species dest_location;
		}

	}

}

```

**Comment by benoitgaudou** [comment]
Hi Srirama,

I think that  to compute the shortest path on the graph, GAMA need a
staring road in the graph and a target.
My bet (but I am not an expert ...) is that in your example that GAMA finds
the closest road that is the one in the "wrong" direction.
So from this road, GAMA computes the shortest path, that is the one that
appears conter intuitive.

I modified a little bit your example by moving a little bit the roads, and
agents find their (shortest path) way...

Cheers

benoit


model speeds


global
{
geometry g <- polyline([{ 10, 50 }, { 90, 50 }]); //, polyline([{ 10, 70 },
{ 90, 70 }])];
list<geometry> l_g <- [
polyline([{ 10, 51 }, { 90, 51 }]),
polyline([{ 90, 51 }, { 90, 49 }]),
polyline([{ 90, 49 }, { 10, 49 }]),
polyline([{ 10, 49 }, { 10, 51 }])
];
geometry dest <- square(3);
graph gr;
init
{
create dest_location
{
shape <- dest;
location <- { 5, 50 };
}

create road from: l_g{}

gr <- directed(as_edge_graph(road));
create people number: 2;
people[0].location <- { 50, 30 };
people[1].location <- { 30, 70 };
}

}

species dest_location
{
aspect default
{
draw shape color: # orange;
draw "Target" color: # black font: font(20) at: location + { -3, -5, 0 };
}

}

species road
{
aspect default {
draw shape color: #black end_arrow: 3;
}
aspect base
{
if int(self) = 0
{
draw shape + 0.1 at: location + { 0, -2, 0 } color: # black end_arrow: 3;
draw "original road" at: location + { 0, -3, 0 } color: # black;
} else
{
draw shape + 0.1 color: # red end_arrow: 3;
draw "reverse road" at: location + { -20, 3, 0 } color: # red;
}

}

}

species people skills: [moving]
{
reflex movement
{
do goto target: dest_location[0] on: gr speed: 1.0;
}

aspect default
{
draw circle(3) color: # green;
draw string(int(self)) color: # white;
}

}

experiment speeds type: gui
{
output
{
display d
{
species people;
species road;
species dest_location;
}

}

}

2018-06-29 7:46 GMT+02:00 Srirāma Bhamidipāti <notifications@github.com>:

**Comment by sriramab** [comment]
Benoit,

That is not the issue here. The prescribed GAMA method for dealing with two-way roads is to use `reverse`. There are a few models in the library and also recommended in the forum questions. But when one uses `reverse`, the path calculations are incorrect because the agent **never** enters the graph or leaves the graph from a `reverse` road. 

I agree with all your points on closest geometry and your modification of the code. But my emphasis is on use of `reverse` and its impact on path calculations. 

Srirama

**Comment by benoitgaudou** [comment]
Hi,

never, never ... you are too hard with GAMA I think :-)
When you change the order of creation of the roads, you have the expected
behavior (create the reverse one and after the non-reverse one).


create road

{

shape <- polyline(reverse(copy(first(g).points)));

}


create road

{

shape <- first(g);

}

But without joking, this could lead to counter intuitive effect ...

If there is something to improve, it is not the fact an agent does not
enter in a reversed polyline,
but rather the fact that GAMA does not take into account the two roads on
which the agent can enter on the graph.
A small enhancement for Patrick :-)

Cheers

Benoit

2018-06-29 8:33 GMT+02:00 Srirāma Bhamidipāti <notifications@github.com>:

**Comment by sriramab** [comment]
:) I understand. It is just that if `reverse` method is being recommended by GAMA (Features>Agent Movement > model > Goto Directed Graph.gaml ) , then it is giving incorrect results and needs a relook and modification or an enhancement as you say :)

**Comment by benoitgaudou** [comment]
Could you please post an issue/enhancement on this point on the
github/issue please ?

Cheers

benoit

2018-06-29 9:05 GMT+02:00 Srirāma Bhamidipāti <notifications@github.com>:

**Comment by sriramab** [comment]
This is already an issue on github  and this discussion is happening on github :)

**Comment by sriramab** [comment]
I do not think this has fixed the issue. The agent still gets the wrong direction. With this correction the agents gets the shortest path, but ignores the directed graph. You may run my latest simplified model above in this thread.

**Comment by ptaillandier** [comment]
Which model? The two models you posted in this thread seem to work normally for me.

**Comment by sriramab** [comment]
ok. I refer to the model speeds. 
- There are two roads. the road on top goes west to east and road in the bottom goes east to west. 
- There are two agents. one agent is north of the road and the second agent is south of the road. 
- the target is to the west end

-  because it is a directed graph and you may consider left hand drive or right hand drive, select one of those. 
- Then the agent on the top should select the top road , go east and then take the bottom road to go west to the target. The bottom agent should then take the bottom road and go directly to the target.

- or otherwise : Then the agent on the top should select the bottom road , go west to the target.  The bottom agent should then take the top road and then bottom road to go west to the target.

After correction, they both take the road and direction closest to the target.

I understand this could be tricky because of roads overlapping each other, but it looks very odd when agent is exiting the graph. For example, the agent is travelling west on a bottom road and suddenly jumps into a destination building on the north. 

I admit that the example might not exhibit this, but perhaps look at the very first example pathModels, there are many buildings and roads.

**Comment by benoitgaudou** [comment]
Hi Patrick,

I works for me now !
But I played with Srirama's model, to test and I removed one road. So the graph contains only 1 road...
And now I have a big hugly StackOverflowException ...
```
	at msi.gama.metamodel.topology.graph.GraphTopology.pathBetweenCommonDirected(GraphTopology.java:574)
```
(if you create 2 roads, by uncommenting the second create ... no more Error).



The model:
```
model speeds

global
{
	geometry g <- polyline([{ 10, 50 }, { 90, 50 }]); //, polyline([{ 10, 70 }, { 90, 70 }])];
	
	geometry dest <- square(3);
	graph gr;
	init
	{
		create dest_location from: [dest]
		{
			location <- { 5, 50 };
		}

		create road 
		{
			shape <- polyline(reverse(g.points));
		}		

//		create road 
//		{
//			shape <- g;
//			shape <- polyline(reverse(g.points));
//		}	

		gr <- directed(as_edge_graph(road));
		create people number: 2;
		people[0].location <- { 50, 30 };
		people[1].location <- { 30, 70 };
	}

}

species dest_location
{
	aspect default
	{
		draw shape color: # orange;
		draw "Target" color: # black font: font(20) at: location + { -3, -5, 0 };
	}

}

species road
{
	aspect default
	{
		draw shape color: #black end_arrow: 3;
	}

}

species people skills: [moving]
{
	reflex movement
	{
		do goto target: dest_location[0] on: gr speed: 1.0;
	}

	aspect default
	{
		draw circle(3) color: # green;
		draw string(int(self)) color: # white;
	}
}

experiment speeds type: gui {
	output {
		display d {
			species people;
			species road;
			species dest_location;
		}
	}
}
```

**Comment by sriramab** [comment]
Ok. I Understand. I have made a parallel line operator as a workaround. 
Thank you for your time Patrick :)
