### ISSUE TITLE
Problems of initialisation of global variables when manually creating a simulation in the init of an experiement

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2430]
### Steps to reproduce
1. In an experiment, I want to create several simulations by hand and set some global variables. 

2. When I use the `with:` facet of the `create` statement, it works fine:
```
		create simulation with: [seed::126.4, dummy_var::1.0];
``` 

3. But when I initialize it from the inside block of the `create`, it does not work (the global variables still have their initial values):
```
create simulation {
			self.seed <- 126.4;	
			dummy_var <- 1.0;
		}
```
 
4. See the attached model to have an example:
```
model NewModel

global {

   float seed <- 123.789;
   float dummy_var <- 20.0;

	init
	{
		write "" + self;
		write seed;
		write " dummy_var " + dummy_var;
		write rnd(10000);
	}
}

experiment mm type: gui {
	
	init {
		create simulation with: [seed::126.4, dummy_var::1.0];
		create simulation {
			self.seed <- 126.4;	
			dummy_var <- 1.0;
		}	
	}
}
```

### Expected behavior
I was expected both syntaxes in the previous model to be equivalent.

### Actual behavior
Only the one with the with facet: set the global variables to the expected values.

### System and version 
MACOSX,  GAMA Git

**Comment by AlexisDrogoul** [comment]
However, your report made me find another bug (a real one, this time). When passing a block to one create, it seems that all the simulations run it... Might be linked to some shortcuts made in the populations of simulations. I will investigate.

**Comment by AlexisDrogoul** [comment]
Closed with 24f0b15327debd9a62d4807b9280477f631d671e

**Comment by benoitgaudou** [comment]
Hi,
I just made a pull this morning. 
I agree with the order of init, so I defined a model to test the behavior of the init on the various variables. In particular, In the following model, the  two variables `seed` and `state` follow the same init steps. (the variable `a_float`is only here for a test).

I notice that:
- the init of `state` is OK for me (which was not the case before the commit... or I was wrong in my model).
- the init of the `seed` is less understable for me. The seed has the same value in all the simulations (`100.0`), whereas it should have the value `12.2` in 1 simulation.

```
global {

    float seed <- 123.789;
    float a_float <- 0.0;
	string state <- "var_definition";

	init
	{
		state <- "init_global";
		seed <- 100.0;
	}
	
	reflex r {
		write "" + self + " - " + seed;
		write sample(state);
		write sample(a_float);
	}
}

experiment mm type: gui {	
	init {
		create simulation with: [seed::1.3, state :: "with_facet", a_float::23.0];
		create simulation {
			state <- "block_create";
			seed <- 12.2;
			a_float <- 10.0;
		}	
	}
}
```

**Comment by AlexisDrogoul** [comment]
Well... Another peculiarity you have been running into. seed is defined in both experiments and simulations with the same name. What you are modifying here is the seed of the experiment. To modify  the seed of the simulation itself you should write `self.seed <- 12.2`

**Comment by benoitgaudou** [comment]
Arg my bad ... sorry.
so everything is find for me now :-)

Thanks

**Comment by hqnghi88** [comment]
Dear Benoit,
I want to confirm : 
1, if i use _init_ to create only 1 sim

``
model NewModel
global {
	float step <- 1#s;
    float seed <- 123.789;
	reflex r {
		write "" + self + " - " + seed;
		write sample(step);
	}
}
experiment mm type: gui {	
	action _init_ {		
		create simulation {
			self.seed <- 12.2;
			self.step <- 100#s;
		}	
	}
}
``

this returns step 1.0 and as you said in last comment if step was not declared in global, it works.

2. Now, if i use [ ] syntax

``
model NewModel
global {
	float step <- 1#s;
    float seed <- 123.789;
	reflex r {
		write "" + self + " - " + seed;
		write sample(step);
	}
}
experiment mm type: gui {	
	action _init_ {	
		create simulation with: [step::10#s, seed::1.3];
	}
}
``
it returns 
NewModel_model(0) - 123.789
step -: 1.0

AND even remove step in global, it returns:
NewModel_model(0) - 123.789
step -: 10.0
it mean step is ok but seed is not.
Is it the right behavior for you?

**Comment by hqnghi88** [comment]
![image](https://user-images.githubusercontent.com/6105384/48787937-58d4ac00-ed1c-11e8-9d3e-45c585fd09f2.png)
I tried your original model and change global init to reflex. 
theorically i must have 2 seed of 126.4 (1 created by [], 1 created by {} ) but no, it seems [] dont work well?

**Comment by AlexisDrogoul** [comment]
I close this one as it has been superseded by #2574
