### ISSUE TITLE
"Towards" and related functions are deceiving

### ISSUE THREAD

**Issue by megapteropus** [gama-platform/gama#2433]
Not really a bug, but an implementation oddity that generates inaccurate behavior in models.

### Steps to reproduce
1. Simply use _towards_, _direction_between_, or _direction_to_ :-)

### Expected behavior
The returned angle should be a float, otherwise it introduces important inaccuracies in derived calculations. (The documentation is, however, clear, in that it states that these functions return an **integer** representing the angle in degrees.)

### Actual behavior
By design choice, the returned angle is an integer (probably for performance optimization?). 

### Suggested solution
Rewrite the function to return a float, or rename the function (e.g. to approx_towards) to avoid misinterpretation. If the prototype of these functions shall remain, at least a clear warning to users should be placed in the documentation as this behavior is counter-intuitive/unexpected.

### System and version 
All versions.

**Comment by ptaillandier** [comment]
I passed all the angles (moving skill, operators and so on) from int to float.

**Comment by AlexisDrogoul** [comment]
Just a comment (I've modified some documentations in the Maths operators, so you should probably pull first :)) Knowing that angle are now floats, shouldn't we change the behaviour of sin(Double) and cos(Double) in Maths.java ? They cast their operand to an int and it doesn't seem to be coherent with the new type... I let you do the change :) (and close)
