### ISSUE TITLE
"destination" attribute (moving skill) does not depend on the simulation step

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2434]
### Steps to reproduce
1. When I look at the read-only "destination" attribute of the moving skill, we can notice that the computation does not depend on the simulation step.

```
	@getter (IKeyword.DESTINATION)
	public ILocation getDestination(final IAgent agent) {
		if (agent == null) { return null; }
		final ILocation actualLocation = agent.getLocation();
		final double dist = getSpeed(agent);
		final ITopology topology = getTopology(agent);
		return topology.getDestination(actualLocation, getHeading(agent), dist, false);
	}
```

### Expected behavior
As the move depends on the step of the simulation, the destination should also take into account the step.

### Actual behavior
The destination does not take into account the simulation step.

### System and version 
GAMA Git, MacOSX

**Comment by AlexisDrogoul** [comment]
OK. So what would be the correct computation ? Use `final double dist = computeDistance(..)` instead of `final double dist = getSpeed(agent);`?

**Comment by benoitgaudou** [comment]
As I have not implemented this class, I wanted to be sure to be in the spirit.
I guess that is the way to do it is as you propose with a: 
```
// final double dist = getSpeed(agent);
final double dist = computeDistance(agent.getScope(),agent);	
```

Testing with a Sriram's small model (see at the end), I notice that, with the change of the computation of the destination attribute, the destination of the first agent is wrong (located on the {0,0} coordinate).
After digging a little bit, I guess it is because the location is outside of the boundary on the environment.
This is done in the `normalizeLocation` method of the Topology.
But I noticed that this method has a boolean operand `nullIfOutside`. This attribute is set to false in the computation of the point in the `getDestination`method. So it should not return null if outside.

I notice that in the method the boolean operand is never used. 
I was wondering if this is the expected behavior ?

In `AbstractTopology.java`
```
	@Override
	public ILocation normalizeLocation(final ILocation point, final boolean nullIfOutside) {

		// TODO Subclass (or rewrite) this naive implementation to take care of
		// irregular
		// geometries.

		// TODO Take into account the fact that some topologies may consider
		// invalid locations.
		if (environment.getGeometry().covers(point)) { return point; }

		if (isTorus()) {
			final Point pt = GeometryUtils.GEOMETRY_FACTORY.createPoint(GeometryUtils.toCoordinate(point));

			for (int cnt = 0; cnt < 8; cnt++) {
				final AffineTransformation at = new AffineTransformation();
				at.translate(adjustedXVector[cnt], adjustedYVector[cnt]);
				final GamaPoint newPt = new GamaPoint(at.transform(pt).getCoordinate());
				if (environment.getGeometry().covers(newPt)) { return newPt; }
			}
		}

		return null;
	}
```




Srirama's small model: 
```
model speeds

global
{
	float step <- 2#s;
	list<geometry> g <- [polyline([{ 10, 50 }, { 90, 50 }]), polyline([{ 10, 70 }, { 90, 70 }])];
	init
	{
		create road from: g;
		create people number: 2
		{
			people[0].location <- { 10, 50 };
			people[1].location <- { 10, 70 };
			people[0].speed <- 10 # m / # s;
			people[1].user_speed <- 10 # m / # s;
			people[0].my_target <- { 70, 50 };
			people[1].my_target <- { 70, 70 };
		}

	}

}

species road
{
	aspect default
	{
		draw shape + 0.1 color: # black;
	}

}

species people skills: [moving]
{
	float speed;
	float user_speed;
	point my_target;
	aspect default
	{
		draw circle(1) color: # red;
		draw name color: # red font: font(15) at: location + { 0, -4 };
		draw int(self) = 0 ? "speed = " + speed : "user_speed = " + user_speed color: # green font: font(15) at: location + { 0, -7 };
	}

	aspect dest
	{
		draw square(1) color: # blue at: destination;
		draw string("predicted destination of people") + int(self) color: # black font: font(15) at: destination + { 0, -1 };
	}

	reflex movement
	{
		do goto target: my_target speed: int(self) = 0 ? speed : user_speed;
	}

}

experiment speeds type: gui
{
	output
	{
		display d
		{
			species people;
			species road;
			species people aspect: dest;
		}
	}
}
```

**Comment by AlexisDrogoul** [comment]
See my comment on the dev mailing-list a bit earlier: `"destination" is (in my opinion) an attribute we should remove from GAMA. It may have been useful once, when we only had continuous topologies, but it has not been maintained for a long time and doesn't take into account (beside the speed) the topology itself: the result will be the same whether you are in a graph or on a grid or in a continuous space. 
There might be some cases where it can be useful, probably, so we might want to turn it into an operator that takes a location, a speed and a heading to compute a "next location" in a continuous space. `

**Comment by AlexisDrogoul** [comment]
Actually, the two computations show the same flaws, namely that without a proper heading and/or speed at the beginning, the result might be completely wrong (the first computation did not show it because of the initial location of the agent (10,50) and the fact that the speed was 10. 
The choice made in "normaliseLocation()" is a default (maybe bad) choice: if a location is outside the environment, we return null (and it is up to the modeler to decide what to do). 
So I will do the minimum: change the computation to at least take the step into account, but change the documentation of the attribute to add a "deprecated" flag and explain it's only for continuous spaces.
