### ISSUE TITLE
Git Wiki for operators A-B and C-H cannot be displayed

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2435]
### Steps to reproduce
1. On the Github Wiki, I tried to open the operators pages : 
Operators [A-B]
Operators [C-H]

### Expected behavior
I can open the pages.

### Actual behavior
These 2 pages cannot be opened, as they are too heavy.

### System and version 
Github

**Comment by AlexisDrogoul** [comment]
I think the solution is to change the ranges in the processing of doc annotations, no ?

**Comment by AlexisDrogoul** [comment]
However, I noticed this on https://travis-ci.org/gama-platform/gama-platform.github.io




<img width="721" alt="image" src="https://user-images.githubusercontent.com/579256/42009032-bc0723d4-7ab2-11e8-9141-fee420331f1c.png">

**Comment by hqnghi88** [comment]
sorry, but it has nothing on wiki now, i must review it deeper

**Comment by AlexisDrogoul** [comment]
Linked, most probably, with https://github.com/gama-platform/gama-platform.github.io/issues/9

**Comment by hqnghi88** [comment]
Seems to be fixed.
