### ISSUE TITLE
speed and real_speed : what is the point ?

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2436]
### Steps to reproduce
Agents provided with the `moving` skill get 2 variables: `speed` and `real_speed`. The documentation about them is a bit obscure, but reading the code allows, more or less, to understand that `speed` can be set to express a "desired_speed", while `real_speed` is set internally to represent the speed the agent has been effectively able to take given the topology, etc. 

### Questions
1) Why can `real_speed` be set from GAML also ? To remain coherent, it should be a read-only variable.
2) Why not to use one and only one attribute (`speed`) ? It could be set by the user to express a desired speed, but could also be modified internally to represent the "real" speed once the different actions have been done (`move`, `wander`, et...). I don't clearly see any use-case where this wouldn't work (but I may be wrong). Having two different variables to represent this is in my opinion a bit confusing. 

Any comments welcome (esp. @ptaillandier !)

**Comment by ptaillandier** [comment]
Hi,

You are right, the real_speed attribute should be read-only. Concerning the
fusion between real_speed and speed, I am not sure it is a good idea as if
your real speed is lower than the speed because of an event (traffic jam or
something), it means that at the next step the "ideal" speed will become
the real_speed whatever if the event is already finished.

A subsidiary question: how should be computed the real speed value? For
instance, imagine a simple model where an agent moves toward a target (goto
action) which is at a distance of 3 meters of the agent. The speed of the
agent is 6 m/s and the step is 1s.
The real speed should be 3m/s (distance traveled / step) or 6 m/s (as we
consider that the agent reaches the target after 0.5 s)?




2018-06-27 11:56 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
I don't know what choice to make for the computation of real_speed -- you already probably made one in the driving skill, no ? 

However, thinking about this, my understanding is that we should have one and only one `speed` attribute, **read-only**, which would reflect the current speed of the agent. And then have the various behaviours that require a desired speed take it as a mandatory argument (or, if not mandatory, take the current speed as the default). It is by the way more or less the current way the moving skill is implemented (with the only difference that speed can be modified and serve as an implicit argument to these behaviours).

**Comment by sriramab** [comment]
Also considering the very many questions asked on the forum, moving skills should perhaps also have something for "distance travelled by the agent during an interval or so far" , " number of people that used the road so far in the simulation or during an interval" , number of people currently on the road" . These are all now possible but considering the frequency of questions, if some of these are possible to include... that would be great. 

For real_speed and speed, I currently use them to distinguish between a moving agent and a stationary agent.

**Comment by sriramab** [comment]
I mean these are all currently possible with a few lines of code, but perhaps can be as inbuilt variables.

**Comment by ptaillandier** [comment]
Some answers:

   - removing the speed variable (and having just the real_speed variables
   that will become the new speed variable: why not, but it will introduce a
   lot of (silent) errors in existing models (model library, tutorials....).
   - distance traveled by the agent during an interval or so far": this one
   is easy to add
   - number of people that used the road so far in the simulation or during
   an interval/number of people currently on the road": difficult as the
   moving skill is attached to the "people" and not to the road... so we just
   have the point of view of a moving agent and not of the road.



2018-06-28 7:34 GMT+02:00 Srirāma Bhamidipāti <notifications@github.com>:

**Comment by sriramab** [comment]
But lets us say, agent keeps track of all the edges it travelled. Then cumulatively, for all the agents, if we remove_duplicates of edges travelled by each agent, we already have a number of agents for each road. The only problem then I see is for two way reverse roads. May be you have a clever solution :) 
Also please see #2429 , it is related to moving skills and has error in its path calculations.

**Comment by AlexisDrogoul** [comment]
@sriramab, patrick is right: if an attribute like "number_of_people_that_used_this_road" should be available, it would be on the road agents, not on the moving agents. And basically, you already have the algorithm to do the computation in your model if you keep track of the roads in the agents :)

@ptaillandier, why would these errors be "silent" ? If we make "speed" read-only, the compiler would flag all the places where it is assigned a value (when it is redefined, for instance). In the other cases, when it is assigned a value just before calling move or wander, the compiler would also flag it.

**Comment by AlexisDrogoul** [comment]
Hi, so let't not change too many things at once if you're afraid it might introduce bugs. However, I have the feeling that these two variables are not necessary : one is sufficient to both indicate the speed wanted before moving or calling a primitive  of the skill (i.e. the modeler changes it to its desire) **and** to report the change once the move has been done (i.e. GAMA modifies the value). I close the case, but if you have time, try a modification of the skill **without** `real_speed`, I'm quite sure it will work well.
