### ISSUE TITLE
Operator pages - Duplicate categories

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2438]
### Steps to reproduce
1. In any operator (see https://github.com/gama-platform/gama/wiki/OperatorsAA) page, look at the operator by categories.

### Actual behavior
Some categories are repeated:
- Containers-related operators (x2)
- Files-related operators (x3)
- FIPA-related operators (x2)
- Iterator operators (x20 ... I know these operators are important but ...)

### System and version 
WIKI online

**Comment by hqnghi88** [comment]
Maybe somewhere missed changed, i review it. But must say that AA range is a little bit weird already

**Comment by AlexisDrogoul** [comment]
And some operators should not be on this page as well: R_file, for instance, shouldn't be in [A-A]...

**Comment by hqnghi88** [comment]
The repetition has been fixed.
@AlexisDrogoul the document processor is based on processor and annotations. I found these  wrong-placed names are: a type (like Sanction ,Norm ,BDIPlan ), a second name of an operator (corR R_correlation, meanR, R_mean ) or some other case that i did not realise.  I investigate more hoping that is not complicate

**Comment by AlexisDrogoul** [comment]
I must admit I have no clues on how these categories, etc. are processed and transformed.

**Comment by hqnghi88** [comment]
I found a wrong comparison of operators names. I commited in processor, but i cant reproduce a msi.gama.processor.jar. I clicked in export plugin in processor/plugin.xml but it seem not reproduce the good one.
Could you please reproduce it later?

**Comment by AlexisDrogoul** [comment]
There is a jardesc file called `Generate Processor.jardesc`. Simply double-click on it, hit OK with the default settings, OK for the warnings and off you go.

**Comment by hqnghi88** [comment]
I was outdated for that jardesc file. I can reproduce and commited the processor.jar.
Thank you.
