### ISSUE TITLE
Creating an agent from a file doesn't work anymore

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#244]
**Describe the bug**
It seems like using the facet `from` of the `create` statement with a file as a value doesn't work anymore, and somehow no agents are created ?

**To Reproduce**
1. Go to `Serialize and restore agents.gaml`
2. in the action `create_clones_from_disk` add this at the beginning to kill all current people agents:
```
ask people {
	do die;
}
```
4. Run the model and start by saving the agents on the disk
5. once done, you can check that the files are present on disk and execute the create clones from disk action
6. execute one step and see that no agent has been created

You can add a line in the loop to create people to make sure the paths are correct:
```
write file(string(folder("../people"))+"/"+saved);
```
And in that loop if you remove the `from` facet and run previous instructions you will see that new agents are created as expected, so the problem seems to come from that facet.

**Expected behavior**
The model works as it used to be

**Comment by AlexisDrogoul** [comment]
Fixed in https://github.com/gama-platform/gama/commit/455ecdf8b9e36522f6dc079335877ad48a69512e. Please test.
