### ISSUE TITLE
GoldMiner_BDI : miners do not get the three last golds 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2444]
### Steps to reproduce
1. Run the model GoldMiner_BDI.gaml in the BDI Architecture model library

### Expected behavior
The simulation should ends at some steps, with an empty environment; all the gold been taken by agents.

### Actual behavior
I run the model several times, and there are always 3 golds the are not taken in the environment.

### System and version 
GAMA Git, MACOSX

**Comment by ptaillandier** [comment]
It seems to be fixed (with the last commit on agent comparison). @benoitgaudou could you test it and close the issue if it is solved?

**Comment by benoitgaudou** [comment]
Seems to work, Thanks!
