### ISSUE TITLE
CityEscape_BDI_Emotions.gaml : 1 driver agent seems lost at the end...

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2445]
### Steps to reproduce
1. run the model CityEscape_BDI_Emotions.gaml from the BDI Architecture model library

### Expected behavior
The model should stops when all the agents have reached a shelter.

### Actual behavior
I run it several times, and I always observe at the end 1 single agent moving from shelter to shelter...

### System and version 
GAMA Git, MacOSX

**Comment by ptaillandier** [comment]
It seems to be fixed (with the last commit on agent comparison). @benoitgaudou could you test it and close the issue if it is solved?

**Comment by benoitgaudou** [comment]
Seems to work, Thanks!
The green agent takes a lot of time to evacuate ...
