### ISSUE TITLE
Test: when run as a GAMA model, issue with displaying the GUI of tests

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2446]
### Steps to reproduce
1. Run a Test model, as any GAMA model, e.g. GraphTest.experiment in Test models / Basic Tests

2. Run it with the GraphTest button

### Expected behavior
I am expected to make appear a View Test, with the graphical representation of the various tests.

### Actual behavior
The Test View appears, but it remains empty.
In addition, after having run the model (the View is still empty). 
When I stop the simulation with the red cross button, the graphical representation of the tests appear for half a second before closing.

Note that when the test are run from the validation view, the GUI is correct.

### System and version 
GAMA Git, MACOSX

**Comment by AlexisDrogoul** [comment]
Due to the fix provided to #2426 ...
