### ISSUE TITLE
Issue when using a function (->)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2450]
### Steps to reproduce
1. Consider the following model: 
```
model NewModel

global {
	list<p> p_actif -> {p where(each.test)};
	init {
		create p number: 10 { test <- flip(10.0); }
	}
}

species p {
	bool test <- false;
	
	reflex r {
		write p_actif;	
	}
}
```

### Expected behavior
No error.

### Actual behavior
I get a compilation error on the definition of the p_actif variable, as soon as I use it in a reflex of the p species.

```
Cycle detected between p_actif and [p]. These attributes or sub-species depend on each other for the computation of their value. Consider moving one of the initializations to the 'init' section of the model	TestToto	New Model.gaml.
```

I remember this is a recent issue fix, and it makes sense in the case of an initialization (in this case it would better to initialize the variable in the init of the global).
But in the case of a function, I do not see another way to define it.

### System and version 
GAMA Git, MACOSX

**Comment by AlexisDrogoul** [comment]
You're right. I push a fix right now.
