### ISSUE TITLE
category for monitors 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2451]
Hi

I think it would be nice to have category facet for monitors also as it helps in grouping monitors.  I would like to request this enhancement as it could make tracking easier and visually appealing.

use case: For a modeler and also the decision maker (= non modeler) , it also can make easier to visually pair to the categories in parameters to their consequences in monitors.

Srirama

**Comment by AlexisDrogoul** [comment]
Hi, already proposed in #1634 ... and already closed. That would require too many changes right now... Sorry for this answer :(
