### ISSUE TITLE
csv to excel or a delimiter in save statement

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2452]
Hi

I get many requests to be able to save to excel file. I know csv can be imported to excel, but sometimes when saving csv and storing a list into csv gives conflict with comma separation with list items. 

May be easier introduce a delimiter to the save statement as it is in the csv read operator? So if i specify a delimiter of my choice say `;` instead of `,` then the problem with lists and lists of lists can be resolved. 

thank you
Srirama

**Comment by AlexisDrogoul** [comment]
Hi, instead of adding more and more facets to the already bloated `save` statement, you might want to motivate @gama-platform/core  (GAMA developers) to develop the 'flushBuffer()' method in `GamaCSVFile` so that all the existing infrastructure for reading can be reused for writing... :)

**Comment by AlexisDrogoul** [comment]
Tracked under #1362.

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
In GAMA 1.9.2, the separator can now be set as a preference, enabling it to be set for a model with `gama.pref_csv_separator <- ';'` for instance. I think this answers the request !
