### ISSUE TITLE
Image layers do not seem to accept dynamic positions in OpenGL displays

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2454]
### Steps to reproduce
1. Open Toy Models > Ants (Foraging and Sorting) >models>Ants Foraging (Complex).gaml

2. Run the "Displays" experiment (which comes with an OpenGL display)

### Expected behavior
The first layer of the display (`image ... `) should move in the screen together with the others. 

### Actual behavior
It stays put at {0,0}. The behaviour is however correct if the display is changed to Java2D

### System and version 
Latest Git version on all OSes.

**Comment by AlexisDrogoul** [comment]
Ok, closed. The documentation was pretty clear about it ... but I didn't read it : `refresh, optional, expects bool - (openGL only) specify whether the image display is refreshed or not. (false by default, true should be used in cases of images that are modified over the simulation)`. Shame on me. The addition of `refresh:true` solves the problem.

**Comment by agrignard** [comment]
I don't know if this is something doable but maybe one option can be to check if there is a dynamic facet position and if yes set the refresh to true?

**Comment by AlexisDrogoul** [comment]
No, it's not doable. Something "dynamic" (like a variable, or a random location) might perfectly be there to give the initial value, but not the remaining ones. We can't read the mind of the modeler and decide on behind of him/her. So it's better to keep things this way (I've added to the documentation that image layers are treated specially in OpenGL).
