### ISSUE TITLE
Add Show in - System Explorer in Project Explorer pop up menu 

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2455]
### Steps to reproduce
1. In eclipse we have the menu to open the project in the system file explorer (when rightclick on a project, show in)
![image](https://user-images.githubusercontent.com/6105384/42484361-dd31386a-841c-11e8-85a1-6b3211420cf6.png)

2. It should be better for modeler to get/verify the path of files/input data 

3.

### Expected behavior
SOmething like the one in eclipse

### Actual behavior
No way except installation external plugin in Gama
### System and version 
gama Git

**Comment by AlexisDrogoul** [comment]
Fixed by adding "a Reveal in OS" menu entry in navigator.
