### ISSUE TITLE
Allow to replace `each` by an arbitrary variable name in iterators

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2457]
### Current situation
All iterators declare a special pseudo-variable, `each`, that takes in turn the values of each (hence the name) of the container elements they are applied on. Like, e.g.: 

```
      list<int> result <- [1, 2, 3, 4, 5] collect (each * 2);
```

### Proposed enhancement
While this syntax covers most of the needs (and remains simple to use and memorise), it might be interesting to automatically create an alternate syntactic form of these iterators that takes a variable name to replace the default `each` pseudo-variable. 
For instance: 
```
      list<int> result <- [1, 2, 3, 4, 5] collect (number | number * 2);
```

### Proposed syntaxes
```
Smalltalk-like
      list<int> result <- [1, 2, 3, 4, 5] collect (number | number * 2);
```
```
Java-like
      list<int> result <- [1, 2, 3, 4, 5] collect (number -> number * 2);
```
```
Comma (bit of confusion with the passing of arguments, though)
      list<int> result <- [1, 2, 3, 4, 5] collect (number,  number * 2);
```

Any comments welcome !

**Comment by sriramab** [comment]
Sorry, I do not understand what is the variable name that is replacing `each`? The variable name is `result` and your replacement has `number`

**Comment by AlexisDrogoul** [comment]
@sriramab Make a diff on the differences between the lines :) 
1st line: `each` is the default name for the pseudo-variable used inside the iterator (and it will stay this way, in any case)
2nd line: this default name can be replaced, if needed, by a more informative name (e.g. `number`).

**Comment by AlexisDrogoul** [comment]
The solution chosen is finally simpler than the ones proposed in the initial enhancement. Iterators will allow these two forms:

```
 list<int> result <- [1, 2, 3, 4, 5] collect (each * 2);
```
or 
```
 list<int> result <- [1, 2, 3, 4, 5] collect (var_name: var_name *2);
```
where var_name can be anything (except `each`).

An upcoming commit will close this issue.
