### ISSUE TITLE
GamaPopulation uses `hashCode` for equality tests

### ISSUE THREAD

**Issue by martijnbastiaan** [gama-platform/gama#2459]
A recent commit added precomputed hashes:

https://github.com/gama-platform/gama/commit/7fd3ead930554c42799aedf904817a11360bb83f#diff-1440e4e881a653519ff01aa5119997b8R568

`hashCode` is computed [here](https://github.com/gama-platform/gama/blob/7fd3ead930554c42799aedf904817a11360bb83f/msi.gama.core/src/msi/gama/metamodel/population/GamaPopulation.java#L145). This is fine on its own, but is used in an equality test over [here](https://github.com/gama-platform/gama/blob/7fd3ead930554c42799aedf904817a11360bb83f/msi.gama.core/src/msi/gama/metamodel/population/GamaPopulation.java#L567). This is incorrect.

Instead of:

```java
	@Override
	public boolean equals(final Object o) {
		if (!(o instanceof GamaPopulation)) { return false; }
		return ((GamaPopulation<?>) o).hashCode == hashCode;	
	}
```

`equals` shoudl read something like:

```java
	@Override
	public boolean equals(final Object o) {
		if (!(o instanceof GamaPopulation)) { return false; }
 
		(GamaPopulation<?>) gp = (GamaPopulation<?>) o;
		return (gp.host.equals(host) && gp.species.equals(species);
	}
```

My Java skills aren't up to par, and I can't get GAMA to compile on my machine so I can't check if this code is actually correct.

**Comment by AlexisDrogoul** [comment]
Hi,

Why is this incorrect ?

Populations are unique in a simulation (i.e. you can't have, under the same host, two populations of the same species) and their hashcode is computed using these two attributes. Moreover, populations can't change host or species, and hosts (agents) and species are also unique in a model. So there is no point in recomputing the equalities you propose. 

To be frank, we are in a case where equality is similar to identity, so we could perfectly, by the way, simply write: 

```
	@Override
	public boolean equals(final Object o) {
		return this == o;
	}
```

Alexis

**Comment by martijnbastiaan** [comment]
Hi Alexis!

Generally `hashCode`s are supposed to be able to determine if two things are unequal, but not the other way around. In other words, two objects which are the same always have the same `hashCode`, but two different objects *might* have different `hashCode`s. Therefore, when testing for equality, one should not rely on `hashCode`s alone. Because `hashCode`s are made to be as unique as possible (to enable data structures like `HashMap`) you won't very often encounter situations wherein two hashes are the same, but the objects are not. However this might sometimes happen.

In very concrete terms: it might happen that `Objects.hash(getSpecies(), getHost())` returns the *same* hash, even though species / host is different.

I came across this issue because a friend of mine kept hitting this bug when using a big number of agents:

![photo_2018-07-09_22-47-12](https://user-images.githubusercontent.com/5658854/42495601-ccaccc46-8423-11e8-8dc2-f5a72432f851.jpg)

I suspected it might be related to this bug:

![photo_2018-07-09_23-50-36](https://user-images.githubusercontent.com/5658854/42495613-d2470748-8423-11e8-9f15-317938acf471.jpg)

And then I encountered this implementation of `equals`. I'm not sure if these bugs are actually related, because I'm unable to build and test. Hopefully you can see if they are. 

Does this help?

**Comment by martijnbastiaan** [comment]
Also, if identity is actually equal to equality in this case, you could definitely write `return this == o;` :)

**Comment by AlexisDrogoul** [comment]
Hi,

Actually, this is what these recent commits on populations and agents hashcodes have (normally) fixed. Previous versions of GAMA were hit by this bug, but the recent ones should not exhibit it. If they do in the recent builds, you should report it as an issue by itself (explaining in which context it happens).

You're right in that there is no need to redefine equals in agents and populations, but instead rely on the default identity test in Object. I will probably remove these methods sooner or later. 

Cheers
Alexis

**Comment by martijnbastiaan** [comment]
These issues have been encountered with the continuous build of yesterday. I plead you to read what I wrote and recognize that the behavior of the equality test is wrong. Not unneeded, but wrong. The issue occurs when using a large number of agents (in this case, 200.000 in the whole model). This corresponds to the hypothesis I just laid out: the likelihood of `hashCode(..)` returning the same hash increases when increasing the number of agents increases. 

If `equals` corresponds to `id` that's fine, you should remove custom implementations of both `hashCode` and `equals`. If they are not, you should make sure that whenever `o1.equals(o2)` it is also true that `o1.hashCode().equals(o2.hashCode())`. The first screenshot I sent very clearly shows this assumption.

**Comment by martijnbastiaan** [comment]
Alright, I see you did actually change it, thanks!

**Comment by martijnbastiaan** [comment]
Btw, does the continuous build actually update? It says:

```
 @hqnghi88 hqnghi88 released this on 18 Apr · 65 commits to master since this release 
```

So I'm confused.

**Comment by hqnghi88** [comment]
Yes, i am quite sure that it is actually updated. There is a message to explain:

The release file names are composed with a number of segments separated by _ :

_ the version of the release, (e.g., GAMA1.8)
_ the name of the OS: either Linux, Mac or Win
_ the number of bits: 64 for 64bits, 32 for 32 bits
_ the day it has been produced (e.g., 07.03.18 for the 3rd of July, 2018)
_ the hashcode of the corresponding commit (e.g., bbe2b68 that can be retrieved at https://github.com/gama-platform/gama/commits/master)
And for that outdate message, we just dont want to spam mail as it need to change a tag on github (which lead to an email to everyone).

**Comment by martijnbastiaan** [comment]
> two agents with the same hashCode should be identical and equal 

Yes, that's correct. That doesn't mean that when two hashcodes are equal, two agents are the same. You're confusing `a implies b` with `b implies a`. While `a.equals(b) -> a.hashCode().equals(b.hashCode())` must hold, the reverse `a.hashCode().equals(b.hashCode()) -> a.equals(b)` does not. Please read [this wikipedia page](https://en.wikipedia.org/wiki/Java_hashCode()) on hash codes. It explicitly mentions:

>  and while two unequal objects having different hashes is very desirable, this is not mandatory (that is, the hash function implemented doesn't need to be a perfect hash)

In fact, it CANNOT be a perfect hash because it can store arbitrary data. The code uses hashCodes to determine if two objects are equal but it is not allowed to do this, as two DIFFERENT agents might map to the SAME hashcode. 

If anything is unclear, please say so.

**Comment by AlexisDrogoul** [comment]
@martijnbastiaan I surely appreciate your theoretical comments on hashCodes and equality, but we're talking identity here, not equality. Hashcodes in GAMA are produced in such a way that two different agents cannot map to the same hashcode.

**Comment by martijnbastiaan** [comment]
@hqnghi88 Thanks for your comment, that clarifies a lot! Sorry for not catching that earlier.

**Comment by martijnbastiaan** [comment]
@AlexisDrogoul 

> Hashcodes in GAMA are produced in such a way that two different agents cannot map to the same hashcode.

Please, don't humor me. You are/were using Java's internal hashCode algorithm, which means you don't get to choose. My friend is trying to use 200.000 agents, at which point the change of a hash collision is almost guaranteed as pointed out in [this article](https://eclipsesource.com/blogs/2012/09/04/the-3-things-you-should-know-about-hashcode/) and this graph:

![hashcode-collisions](https://user-images.githubusercontent.com/5658854/42534142-35eaca10-848c-11e8-8cd9-9d72d3ce0645.png)

Anyway, this is it for me. If you don't care to acknowledge issues in your own code or do any testing with more than a trivial number of agents, I don't care to report any more bugs or participate in discussion.
