### ISSUE TITLE
Drag and drop of files and resources + Relative path on Windows

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2467]
### Steps to reproduce
1. Open a model, use the new drag and drop feature (just drag and drop) to import a gaml model

2. 
![image](https://user-images.githubusercontent.com/6105384/43046756-e4326ba4-8df7-11e8-843f-3ab30fd72481.png)

3. As in screenshot, the relative path of importation is false.

### Expected behavior
import "New.gaml"

### Actual behavior
import "/JTD_2017/models/New.gaml"

### System and version 
Gama git, Win OS

**Comment by AlexisDrogoul** [comment]
Works fine for me now with the latest commit (I should put a reminder to **never** use URIs in Windows). Can you test it ?

**Comment by hqnghi88** [comment]
It works.
