### ISSUE TITLE
Request a Save/Save as button 

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2468]
### Steps to reproduce
1. As in any IDE/Editor , we can access to Save/Save as by clicking on Menu File, and Item Save, but most of them do propose a toolbar/shortcut/1click access save button 
### Expected behavior
A Save button on toolbar (after switch perspective), or on the editor toolbar ( before the search bar). Or the capability to customize the toolbar as in eclipse

### Actual behavior
I realize a glitch when editing/customizing the model , and then i must use my hand, to press Ctrl+S, or 2-click (File/Save)

### System and version 
Gama git.

**Comment by AlexisDrogoul** [comment]
Hum... When you're editing a model, you don't use your hands ? :)

I don't want to pollute the toolbars with unnecessary buttons. There are already too many for my taste -- and Eclipse is awful regarding this. 

Yes, customising the toolbar could be nice, but it would be too much trouble to maintain over the different perspectives (a perspective is recreated for every experiment). And again, it would go against decluttering the interface. 

As a side workaround, if you want a zero-button / zero-keyboard solution, you can configure auto-save in the Advanced Preferences for Editors. Or it is also available in the pop-up menu (but right-click + click is too much gestures, isnt'it ? :) )

So, if there is a very strong popular requests for a save button, why not adding one. But it seems you are the first one to request for it...

**Comment by hqnghi88** [comment]
Yes Sir, i mean my other hand. Yes may be i am the only one who reach that speed of testing stuffs with mouse (gamer style or win user style?!?!?). Yes, i can imagine the taste. Or do we make an implicit saving for the switch perspective button: when you want to switch pers, save the model first.

**Comment by AlexisDrogoul** [comment]
That is a very good idea. I can add a preference for that. Another preference could be (in the case of launching a model) to propose to save all dirty editors instead of just the current one.

**Comment by AlexisDrogoul** [comment]
I have added a preference to save editors when switching perspectives.
