### ISSUE TITLE
Drag and Drop - Several enhancement request

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2471]
**Is your request related to a problem? Please describe.**
I'm playing with new drag and drop feature
**Describe the solution you'd like**
I have some remarks that may be the enhancement
**Describe alternatives you've considered**
* external folder is static, i mean when a dropped item has been removed, it is not removed in external folder (yes, as same as include, user must clean their data, but may be we propose a menu to help that: check unused files). And moreover, its broken link with file on disk (file deleted) still open and show a blank editor
* The dropped item are declared with variable that use file name. This behavior can be improved with checking the current scope 's variables list to add numbered suffix. 

	image_file cubetexture_image_file <- image_file("C:/eclipseoxy/cubetexture.png");
	
	image_file cubetexture_image_file1 <- image_file("../external/cubetexture.png");

	image_file cubetexture_image_file2 <- image_file("../external/cubetexture.png");
And MAY BE we should swap suffix to prefix bc sometime , file name start with number:
	image_file 1cubetexture_image_file <- image_file("../external/1cubetexture.png");

* The declaration of group dropped resources are not created in right place, as i chose 1 gaml and 2 other file types, drop them into gama. They are declared at top of model.

import "../external/Circle.gaml"

	file eclipse_file <- file("../external/eclipse.exe-1516330536998.p2bu");

	image_file 1cubetexture_image_file <- image_file("../external/1cubetexture.png");
**Additional context**
gama git , win 10.

**Comment by AlexisDrogoul** [comment]
There are no syntactic analysis performed when dropping files (otherwise it would be too complex). So the only way is a "best guess" given what is known (the text itself, not the AST). And regarding grouped files, I would be surprised if it was a common practice.

**Comment by AlexisDrogoul** [comment]
I have committed a fix for the two last problems. Although I don't check the existence of previous variables (I have no real way to do it, especially quickly, as drag'n drop needs to be done quickly). And regarding dropping mixed files, you still have to point to where you want to put the declarations (the import will find its place on its own). 


I will not commit anything for the first one. Yes, the links remain, and as you say, it is similar to includes. And if a link is broken, well, at least you can edit it (in its Properties), which provides an interesting way to keep the structure (and the text of the model) while changing the path to the data. 

Please check and close if you think it's ok.

**Comment by hqnghi88** [comment]
Dear Alexis,
I feel ok for the 2 last. But for the first one , i think we could have the dialog to say that the file does not exist anymore instead of opening a blank editor. Can i wait for this or i should close here?

**Comment by hqnghi88** [comment]
Thank you. It works like a charm.
Cheers.
