### ISSUE TITLE
[Feature/Regression] Unescape strings when saving variables to csv

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#2475]
Hi,
There's been a little change (i don't know when) between Gama versions regarding string escaping.

Let's test it with this example model : 

```
/**
* Name: StringEscapingIssue
* Author: robin
*/

model stringEscapingIssue

global {
	list myList <- [0,1];
	geometry myPolygon <- square(10);
	string quotedList <- "'" + string(myList) + "'";
	string quotedPolygon <- "'" + string(myPolygon) + "'";
	
	reflex saveStrings {
		save [myList, string(myList), quotedList, myPolygon, string(myPolygon),quotedPolygon]
		to: "/home/robin/test.csv" type: "csv" header: true rewrite: false;
	}
}

experiment stringExperiment type: gui {
}
```

- In **Gama 1.8 RC1**, here is the content of the test.csv file :
```
myList,string(myList),quotedList,myPolygon,string(myPolygon),quotedPolygon
[0,1],[0,1],\'[0,1]\',polygon ([{45.0,55.0,0.0},{55.0,55.0,0.0},{55.0,45.0,0.0},{45.0,45.0,0.0},{45.0,55.0,0.0}]),POLYGON ((45 55, 55 55, 55 45, 45 45, 45 55)),\'POLYGON ((45 55, 55 55, 55 45, 45 45, 45 55))\'

```

- And here is it in **Gama 1.7 (git commit 9484b484f0e07981670fcab6122209292c0c3f5a)**, here is the content of the test.csv file :
```
myList,string(myList),quotedList,myPolygon,string(myPolygon),quotedPolygon
[0,1],[0,1],'[0,1]',polygon ([{45.0,55.0,0.0},{55.0,55.0,0.0},{55.0,45.0,0.0},{45.0,45.0,0.0},{45.0,55.0,0.0}]),POLYGON ((45 55, 55 55, 55 45, 45 45, 45 55)),'POLYGON ((45 55, 55 55, 55 45, 45 45, 45 55))'
```

The old behavior (unescaping the quotes) is way better, as the produced outputs can easily be loaded in any CSV reading tool.
The current behavior, escaping the quotes with this `\` character is terrible for writing outputs, and I'm struggling to read the results of my model experiments.

Would it be possible to propose an option, in the `save` statement, to unescape the strings outputted ?

----

*PS : Note that I'm using the `'` character to isolate strings because the usual `"` has been escaped in the same way for a long time.*

**Comment by RCura** [comment]
Great, thanks !
So, according to my understanding of the commit, should I use 
```
string quotedList <- toCleanString("'" + string(myList) + "'");
save [quotedList] to: "/home/robin/test.csv" type: "csv" header: true rewrite: false;
```
?

I won't be able to test it until the next CI build is created, which should be tomorrow.

**Comment by RCura** [comment]
Hey @ptaillandier and @AlexisDrogoul ,

Thanks for the fix, this now prints to csv in a good way, when writing `string blob <- '"' + string([1,2,3]) + '"'`, the output is correct regarding to quotes
```
blob
"[1,2,3]",
``` 

But, I think this fix (or other commits) also introduced some regressions/bugs :

### 1. Absolute paths vs relative paths :
When saving to a path, even absolute, it's now always relative to the place of the experiment file.
To be more clear, if I have a model in `/home/me/model/model.gaml`, that saves a csv to `/home/me/test.csv`, the resulting csv will be created in `/home/me/model/home/me/test.csv`.
Of course, when using the usual tilde, the same problem applies : saving to `~/test.csv` writes the output to `/home/me/model/~/test.csv`

### 2. Additional commas at the end of the csv :
When writing a simple csv, like this 
```
string abc <- "DEF";
write [abc] to: "~/test.csv" type: "csv" header: true rewrite: false;
```
The outputs is like this :
```
abc
DEF,
```
So, at the thend of each line (except the header), there's an extra/excessive comma.

### 3. Binary writing when supplying a wrong variable

I don't know if it's related, as this version is extremely bugged in my Ubuntu computer (had to reboot almost each time I launched/ quitted an experiment due to total computer freeze. Meaning had to full reboot approx 10 times to write this issue), but when trying some combinations of `string()` with lists, geometries and things like this, it sometimes produced "binary format" CSV, meaning that when opening those CSV in my text editor, the structured looked like a binary file (blocks of 4 (? I think) characters, each block separated from the next with a space).

**Comment by AlexisDrogoul** [comment]
Hi,

For the first regression, you're probably right, it has certainly been introduced by the new commits on the handling of global files (ironic, isnt'it ?). Actually, local files are now tested before global files, meaning that if they are not supposed to exist, GAMA will happily create them in the workspace. I will see how to revert this when files are not supposed to exist. 

For the second and third one, however, I have no clues about what may cause this behaviour. 

Cheers
Alexis

**Comment by AlexisDrogoul** [comment]
A remark: has the tilde worked once on GAMA/Linux ? It doesn't on GAMA/ macOS -- and I guess it has never worked as a substitute of "user.dir" on this platform (although it's an UNIX).

**Comment by RCura** [comment]
You're right, I thought it worked, but testing on an older version of Gama that I used until now, it does'nt work.
It creates a `~` directory inside the model folder.

**Comment by AlexisDrogoul** [comment]
OK. I fixed the first problem (and gave you the "~" for free !)

**Comment by RCura** [comment]
I confirm, both absolute path and "tilded" path works perfectly with this latest commit :)
Thanks @AlexisDrogoul !
I edit my first post.

**Comment by AlexisDrogoul** [comment]
Hi Robin,

Considering the last issue (binary content ?), I propose that you open a separate issue with a reproducible use case (ie something we can test in terms of data corruption). I think we can close this one now. 

Cheers
Alexis

**Comment by RCura** [comment]
@AlexisDrogoul : Sorry to reopen this, but I have a new issue regarding the folder detection.
In my model, thousands of agents save their attributes to csv files.
With your modifications in `msi.gama.core/src/msi/gama/common/util/FileUtils.java`, I now have thousands of `Hit with EFS-based search:` messages in my standard output, flooding my terminal and blocking me from watching my okwn `write` statements.

Is this change ([here](https://github.com/gama-platform/gama/blob/f767416bb75baa69e6081a3223ab3a14cadcdd07/msi.gama.core/src/msi/gama/common/util/FileUtils.java#L87) and [here]() I guess ) a debug oversight ? If not, would it be possible to add an option so that it doesn't get displayed to stdout each time a file is found ?
