### ISSUE TITLE
Java2D displays prevent user interaction on Ubuntu

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2476]
**Describe the bug**
On Ubuntu, no SWT mouse/keyboard events seem to be fired in Java2D (Swing) displays.

**To Reproduce**
1. Open a Java2D display, try to trigger the contextual menu (like in #2379), nothing happens
2. Put it in fullscreen mode (like in #2386) and no other combination of keys / mouse events can put it back to normal state.
The two issues (there are probably others, did anyone try to drag the display ?) seem to be strongly linked. I close them and open this new one to focus on its common resolution. 

**Expected behavior**
It would be expected that the Java2D displays work like their OpenGL counterparts (i.e. normally), or like they do on Windows and macOS.

**Screenshots**
Several screenshots available in #2379 and #2386. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - GAMA version: git
 - Java version 1.8

**Additional context**
The two issues are clearly linked. It seems that the Java2D display components (a Swing component) captures the keyboard/mouse focus on Ubuntu (it doesn't on Windows or macOS), but that it does it only partially (i.e., as reported by @hqnghi88, no focus event is fired). This last behaviour (partial capture) might be however a consequence of choices made earlier to disable all activities on the Swing side and have a common listener on the SWT side, which maybe need to be relaxed when the OS is Ubuntu.
 - **[EDIT]*** A few mouse events are fired under macOS (mouseMoved, mouseExited, mouseEntered). The others (key, focus, mouse) are possibly blocked because of the design of the Java2D displays. However, they don't block the corresponding SWT events.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 to attach the listener, you can try to do it in the AWT event loop, ie like that (in `AWTDisplayView`: 

```java
			@Override
			public void afterComponentCreatedAWTThread() {
				new AWTLayeredDisplayMultiListener(decorator, getSwingComponent(), getDisplaySurface());
			}

```

(this method is normally empty).

**Comment by hqnghi88** [comment]
Dear Alexis, i broke my linux environment, i let you know in 1 hour if it work,

**Comment by AlexisDrogoul** [comment]
Hi @hqnghi88 , ok. 

In the meantime, I've played on macOS, and I can report positive things (although these changes break macOS behaviour, but it was expected). 

If you change the `AWTDisplayView.createSurfaceComposite(final Composite parent)` method by this one, do you see changes in the fired events ? 

```java
	@Override
	protected Composite createSurfaceComposite(final Composite parent) {

		if (getOutput() == null) { return null; }

		surfaceComposite = new SwingControl(parent, SWT.NONE) {

			@Override
			protected JComponent createSwingComponent() {
				return getDisplaySurface();
			}

			@Override
			protected void preferredSizeChanged(final Point minSize, final Point prefSize, final Point maxSize) {
				WorkbenchHelper.asyncRun(() -> {
					surfaceComposite.setSize(prefSize);
					parent.layout(true, true);
				});

			}

			@Override
			public Composite getLayoutAncestor() {
				// AD 02/16 Seems necessary to return null for displays to show
				// up and correctly initialize their graphics environment
				return null;
			}

			@Override
			public boolean isSwtTabOrderExtended() {
				return false;
			}

			@Override
			public void afterComponentCreatedSWTThread() {}

			@Override
			public void checkWidget() {

			}

			@Override
			public void afterComponentCreatedAWTThread() {
				new AWTLayeredDisplayMultiListener(decorator, getDisplaySurface(), getDisplaySurface());
			}
		};
		// surfaceComposite.setEnabled(false);
		WorkaroundForIssue1594.installOn(AWTDisplayView.this, parent, surfaceComposite, getDisplaySurface());

		return surfaceComposite;
	}
```

**Comment by AlexisDrogoul** [comment]
Great. And what about the interaction ? I mean, beside the messages, are there any other meaningful effects ? Right-click (and menu), dragging the display, etc. ? Are the keys logged, too ?

**Comment by hqnghi88** [comment]
No Sir, just the messages, no visual interraction as drag nor popup. Do we need other lines of code?

**Comment by hqnghi88** [comment]
It reach the dispatch but the ``listeners`` is blank in Java2Ddisplaysurface
 
		for (final IEventLayerListener gl : listeners) {
			switch (swtMouseEvent) {
				case SWT.MouseDown:
					gl.mouseDown(x, y, 1);
					break;
				case SWT.MouseUp:
					gl.mouseUp(x, y, 1);
					break;
				case SWT.MouseMove:
					gl.mouseMove(x, y);
					break;
				case SWT.MouseEnter:
					gl.mouseEnter(x, y);
					break;
				case SWT.MouseExit:
					gl.mouseExit(x, y);
					break;
			}
		}

**Comment by AlexisDrogoul** [comment]
Well, we'll see. The important thing is to record all the event that are successful in AWTLayeredDisplayMultilistener.

**Comment by AlexisDrogoul** [comment]
I (finally, sigh 😢 ) resolved to install Ubuntu on my Mac. What I can say from the first tests I made is that we **should try to not** give the focus to the AWT component, as it doesn't give it back properly after (i.e. impossible to type in the editor even when the view is closed). Of if we have to, then we must ensure that the listener is removed after every activation of the view (and put back again when its SWT parent gets focus, which might be complicated to do). I'll continue digging and understanding this situation...

**Comment by hqnghi88** [comment]
You mean a real ubuntu on a Mac? Congrat.
Well, it's mean AWTLayeredDisplayMultiListener is useless? .... Cheers.

**Comment by hqnghi88** [comment]
I just test again and opengl work, i use VM too. linux is really mess. i broke 2 times 2 machines

**Comment by AlexisDrogoul** [comment]
Coming back to this issue, @hqnghi88 ... Has the move to Eclipse 2019-03 changed anything ?

**Comment by hqnghi88** [comment]
Just test on ubuntu 19 with eclipse 19-03 and git.
Right click works but fullscreen blocked but it depends mostly on OS (it is not full fullscreen, and use task manager to chose the fullscreen process, then keys works)
![Screenshot from 2019-05-05 19-51-07](https://user-images.githubusercontent.com/6105384/57194268-2c7db680-6f6f-11e9-939a-5b96b3394487.png)

**Comment by AlexisDrogoul** [comment]
Ah. Good news, then !? Maybe we can take some time tomorrow to resolve the fullscreen issue (as it is a bit complex also on other OSes...)

**Comment by hqnghi88** [comment]
Arthur is right, right click works however mouse position is not updated in java2d display.
