### ISSUE TITLE
Gama Git hang at loading ummisco.gama.ui.shared

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2490]
**Describe the bug**
Gama Git hang at loading ummisco.gama.ui.shared

**To Reproduce**  
1. Launch gama git (dev version) . Gama splash screen shown, but gama hangs at loading the ummisco.gama.ui.shared . In eclipse there are several exception about lock state (attached file)
[log.txt](https://github.com/gama-platform/gama/files/2250153/log.txt)

**Expected behavior**
No exception 

**Desktop (please complete the following information):**
 - OS: win 10
 - GAMA version: git
 - Java version 1.8

**Additional context** 
Youcef try with creation of new workspace and it seem to work, gama can launch. I use old eclipse workspace. I cannot try with new workspace for instance.

**Comment by AlexisDrogoul** [comment]
You probably had a crash before in this workspace (happens only -- normally -- for the dev version). Try to find a file with the extension ".snap" and delete it.

**Comment by ysklab** [comment]
I had this issue the last couple of days, which is actually caused by a crash in the used workspace.  So I was unable to run Gama until I changed the workspace. Now, after having the .snap file deleted (in the damaged workspace), Gama works fine.

**Comment by hqnghi88** [comment]
Thanks Alexis, so it,s considered as fixed.

**Comment by AlexisDrogoul** [comment]
I've added a sanity check at the beginning (in WorkspacePreferences). Not sure if it will be effective, but it shouldn't harm (and will make the work for you in case).

```java
	private static void testWorkspaceSanity(final File workspace) {
		System.out.println("[GAMA] Checking for workspace sanity");
		File[] files = workspace.listFiles((FileFilter) file -> file.getName().equals(".metadata"));
		if ( files.length == 0 ) { return; }
		files = files[0].listFiles((FileFilter) file -> file.getName().equals(".plugins"));
		if ( files.length == 0 ) { return; }
		files = files[0].listFiles((FileFilter) file -> file.getName().equals("org.eclipe.core.resources"));
		if ( files.length == 0 ) { return; }
		files = files[0].listFiles((FileFilter) file -> file.getName().contains("snap"));
		if ( files.length == 0 ) { return; }
		if ( MessageDialog.openQuestion(Display.getDefault().getActiveShell(), "Corrupted workspace",
			"The workspace appears to be corrupted (probably due to a previous crash. Would you like GAMA to clean it ? Once it is done, you should exit the platform and restart it again to finish the cleaning process.") ) {
			for ( final File file : files ) {
				file.delete();
			}
			return;
		}
		System.out.println("[GAMA] Workspace appears to be " + (files.length == 0 ? "clean" : "corrupted"));
	}
```

**Comment by AlexisDrogoul** [comment]
I've tested it and it works well. .snap files / .log files are cleansed and after a restart, everything is back to normal. Now, the interesting thing would be to force this restart if the cleaning is done. 

Notice that this lock can also happen if several instances of GAMA run at the same time and use the same workspace (which is absolutely not advised !)

**Comment by hqnghi88** [comment]
Just a side note, is this related with the lock argument in the ini? Because we dont have it before (or i am wrong)

**Comment by AlexisDrogoul** [comment]
No, it's two different problems that can arise. One concerns the workspace, the other one the install location (configuration space). I've always had the .snap problem, from time to time. And it is quite common in Eclipse as well. Now, the "lock" problem may have, most of the time, "hidden" the .snap problem (as they both arise when GAMA has crashed, but the lock happens normally before, when loading the plugins)

**Comment by AlexisDrogoul** [comment]
Yep. This is (from the point of view of the platform) equivalent to a crash.
