### ISSUE TITLE
Unused "external" folder in Library\Features

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2491]
**Describe the bug**
There exist an unused external folder in  Library\Features

**To Reproduce**
1. Just create new Gama workspace
2. Go to Features in Model Library. 

**Expected behavior**
It should be inside a project or removed

**Screenshots**

![image](https://user-images.githubusercontent.com/6105384/43559083-ab4676ea-9636-11e8-8149-9e4c75046ce5.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - GAMA version: git (may be CI)
 - Java version 1.8

**Comment by AlexisDrogoul** [comment]
Actually, it is at the right place (but this one has been put accidentally so it can be safely removed from git). `Features` is a project.

**Comment by hqnghi88** [comment]
Yes, you are right, seem an outdated file (which has been added to gitignore). So it is only on my pc, not on git anymore.
