### ISSUE TITLE
Overlay Strange behavior

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2496]
I have a strange behavior with an overlay that use to work before. I know lots of improvement has been made those last months maybe it's just the syntax that has changed.

Here is the gif basically the size of the text is inversely proportional to the zoom level.

Does the syntax has changed or is it a bug?

Here is the gif that shows the behavior 
![untitled mov](https://user-images.githubusercontent.com/3928502/43600716-5c925064-9659-11e8-84bd-eb579589d875.gif)

And the model can be run from here 
https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/Game_IT.gaml

**Comment by agrignard** [comment]
maybe link to this one
https://github.com/gama-platform/gama/issues/2288

**Comment by agrignard** [comment]
Ok so I found  a clue (that doesn't solve the problem but it can help to track it):
When I put the text in bitmap:false then behavior is fine (the text stay at the same size)

**Comment by AlexisDrogoul** [comment]
I'm curious to understand why you use pixels in the definition of the fonts (i.e. since `font("Helvetica", 12, #bold)` is already expressed in points).

**Comment by agrignard** [comment]
You right it s a mistake I was experimenting different option to make it
works. The px are useless (even if  it seems to work also)

Le ven. 3 août 2018 à 05:59, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
`bitmap:` is deprecated and I was surprised that it could change anything, but now I understand : there is a mistake in the way this facet is handled (i.e. using `bitmap` or `perspective` is exactly the same). So what seems to work in your case is `perspective: false` (i.e. using bitmap fonts). In that case, it's more normal and perfect it's only a simple test on whether or not we draw in an overlay that is missing (related to #2261, actually).

**Comment by agrignard** [comment]
ok I see so yes perspective:false and size not in #px it's ok for me. 

What about forcing the perspective to false as soon as we are in overlay? 

Issue almost closed no?

**Comment by AlexisDrogoul** [comment]
Well, actually, no. I have to add a test somewhere so that you can draw using perspective: true or false (the first gives you more choice of fonts and sizes).

**Comment by AlexisDrogoul** [comment]
I've fixed the issue with the zoom for "perspective" fonts. Fixed also a number of small issues related to the overlays. They are now quite functional in OpenGL (as they are in Java2D). The commit will come soon. Beware that it may change a bit the size of the text on display (actually increase it a bit).
