### ISSUE TITLE
Virtual experiment and display

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2497]
**Describe the bug**
When runnign a display that inherits from another one the parent display is displayed (it shouldn't)
**To Reproduce**
run this model
`````
/**
* Name: Basic model
* Author: Arnaud Grignard
* Tags:
*/

model Tuto3D

global {
  int nb_cells <-100;	
  init { 
    create cells number: nb_cells { 
      location <- {rnd(100), rnd(100), rnd(100)};       
    } 
  }  
} 
  
species cells{                      
  aspect default {
    draw sphere(1) color:#blue;   
  }
}

experiment exp1  type: gui virtual:true{
  output {
    display View1 type:opengl {
      species cells;
    }
  }
}

experiment exp2  type: gui parent:exp1{
  output {
    display View2 type:opengl parent:View1 {
      species cells;
    }
  }
}

`````
**Expected behavior**
When running exp2 I would expect to see only display View2. It used to be like this initially the idea was to be able to inherit from a display or an experiement and being able to enhance it (without displaying the parent view)

**Screenshots**
However we see View2 and View1 
<img width="1920" alt="screen shot 2018-08-02 at 14 39 28" src="https://user-images.githubusercontent.com/3928502/43603754-e61eb234-9661-11e8-9c13-f16afeb746a5.png">

**Desktop (please complete the following information):**
GAMA1.8_Mac_64_08.02.18_995a64d

**Comment by AlexisDrogoul** [comment]
You have to declare `virtual` the displays you want to inherit from and don't want to use (or show). Like actions in virtual species.

i.e.
```
experiment exp1  type: gui virtual:true{
  output {
    display View1 type:opengl virtual: true {
      species cells;
    }
  }
}
```

**Comment by agrignard** [comment]
Ok sorry it was already documented here #2074 indeed
