### ISSUE TITLE
Wrong bounding area and/or Camera position and z near value-  OpenGL- windows 10

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2498]
I just uploaded the last version of GAMA (August 3rd) to upgrade to GAMA 1.8 on a windows 10 Computer.

I got a strange behavior with the rendering.  (it doesn't happen on my mac) but the boundary is bigger that expected and wrong and the world is not display entirely . I t doesn't happen in Java

Maybe it is  related to the recent change in the frustum and z near z far etc no?

![img_2956](https://user-images.githubusercontent.com/3928502/43670718-55ddf84a-975d-11e8-9081-c4e9c4116e7a.jpg)
![img_2955](https://user-images.githubusercontent.com/3928502/43670719-55fcee1c-975d-11e8-9d60-374f19dd35eb.jpg)

**Comment by benoitgaudou** [comment]
Hi

I remembrer Patrick got a similat issue when he ran model on his new laptop
with Windows with a high résolution screen.
I do not remember what to do, but he changed some thing in the Windows
preferences to make it work ( downgrading screen résolution perhaps ?)

Cheers
Benoit

Le sam. 4 août 2018 à 02:42, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by ptaillandier** [comment]
Hi,
Indeed, same problem as here: https://github.com/gama-platform/gama/issues/2378#issuecomment-377291922

**Comment by agrignard** [comment]
Close as it is related to #2378
