### ISSUE TITLE
Console enabled by default when running GAMA 1.8 on Windows

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2499]
When running GAMA 1.8 from Windows 19 there is a console running (see image) 

![img_2957](https://user-images.githubusercontent.com/3928502/43670813-7376c44e-975e-11e8-8ad2-7828144c1b81.jpg)

I am not sure we want to keep it for the release version no? 

BTW maybe the  warning message can be interesting ?

**Comment by AlexisDrogoul** [comment]
I have no console running when launching one of the continuous builds on Windows.

**Comment by hqnghi88** [comment]
I dont have it too, on insider build. But i remember it exist, so may be for old version. What is your winver exactly?

**Comment by agrignard** [comment]
Ok I'll have a look at this windows version that seems to be exotic (it's also on this computer that #2498 has been discover). It's a windows 10. I won't have access to this computer today but I'll update the info soon

**Comment by agrignard** [comment]
Ok so this is there version running on this exotic computer
10.0.17134.165 if it can helps

**Comment by AlexisDrogoul** [comment]
My feeling is that it has nothing to do with GAMA. Can you please check what's on the Java Control Panel "Advanced" settings ? There is an option there to enable/disable the console when running Java apps.

**Comment by hqnghi88** [comment]
In this https://stackoverflow.com/questions/2908188/how-to-turn-off-eclipse-console-on-windows show the solution, I commited the change for win_with_jdk 
-vm
./jdk/bin/java

to
-vm
./jdk/bin/javaw

It should be fixed after new CI release

**Comment by AlexisDrogoul** [comment]
OK. Let's close this, then ! Thanks @hqnghi88

**Comment by agrignard** [comment]
Yes indeed I forget to mention it was with Gama_with_jdk.

Just for a user point of view if we can avoid to have the console I think it s better. I ll try with new build and keep you update. Thanks!

**Comment by agrignard** [comment]
Ok I confirm the console doesn't appear anymore in the last GAMA_with_JDK

Thanks!!
