### ISSUE TITLE
Documentation: the page for statement is not rendered properly

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2501]
**Describe the bug**
The page of documentation for the statements on the GAMA website is not properly rendered: https://gama-platform.github.io/wiki/Statements .
In particular, the end of code blocks is not correctly recognized.
For example, for the `ask` statement is displayed as follow.

**To Reproduce**
1. Go to statement webpage:
https://gama-platform.github.io/wiki/Statements

**Expected behavior**
The block code should be properly recognized.

**Screenshots**

<img width="863" alt="capture d ecran 2018-08-06 a 16 14 15" src="https://user-images.githubusercontent.com/1555274/43721699-d4d4617e-9993-11e8-9e3c-65430e157c8f.png">

**Comment by AlexisDrogoul** [comment]
Moved to https://github.com/gama-platform/gama-platform.github.io/issues/11
