### ISSUE TITLE
Continuous Release update?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2508]
I am trying to download the last release build (I was expecting to get the one from the 10 of August however the website only proposes the one from the 8th of August)

https://github.com/gama-platform/gama/releases/tag/latest

Did I miss anything?

**Comment by benoitgaudou** [comment]
In fact, it seems that Travis cannot compile for two days...
https://travis-ci.org/gama-platform/gama

Error in the GridLayerData file.
Strange .. I do not have the error in my own Eclipse/GAMA.

Benoit

Le ven. 10 août 2018 à 15:04, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
It's becoming a bit annoying to have two different compilers (Eclipse and JDK), with different levels of compliance towards casting. Now it's the simpleBDI plugin that is breaking... And I'm also surprised we don't receive an alert anymore when Travis breaks. Anyway, let's continue this discussion in a more appropriate place (mailing list).
