### ISSUE TITLE
Setting a display to fullscreen sometimes misses "reshaping" the OpenGL surface

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2509]
**Describe the bug**
When setting an OpenGL display to fullscreen, the view sometimes appears distorted and wrongly scaled. The resizing event does not seem to call the reshape() method of the renderer in those cases, for a reason I have yet to understand.

**To Reproduce**
1. Launch any model with an OpenGL display
2. Press ESC to put it fullscreen
3. On some "random" occasions, the objects on the display are slightly distorted as if the original canvas was not reshaped, but simply stretched to fit the new dimensions of the full screen.

**Expected behavior**
The reshape() method should systematically be called when the display is resized. 

**Screenshots**
Dont have any yet, but will try to take one.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - GAMA version: git / Eclipse
 - Java version: 1.8

**Additional context**
It seems that after a bit of playing with the display (zooming, resizing) everything comes back to normal, as it should be in the first place.

**Comment by agrignard** [comment]
I never noticed that (even if I am a big user of full screen ;-)) but I will try to reproduce it. Does it appear on a specific model (heavy one?) or most of them?

**Comment by agrignard** [comment]
I saw it once today but indeed very random. I am not sure I ever saw that, is it something recent?

**Comment by AlexisDrogoul** [comment]
Since we moved to Oxygen. I guess the SWT implementation of GLCanvas misses some events sometimes.

**Comment by agrignard** [comment]
Maybe related to this one, i see sometime that the double click function (that is suppose to reput back the view in its initial state) does not its job properly.

For instance if I had slightly rotated the model (ctrl+drag) and then double click to go back to the initial view it will some time stay with the same rotation value.

**Comment by AlexisDrogoul** [comment]
It has normally nothing to do with it. If you have a repeatable test case, I suggest you open a different issue.
