### ISSUE TITLE
GoldBDI example appears to have error please?

### ISSUE THREAD

**Issue by Bazmundi** [gama-platform/gama#2510]
Using GAMA 1.8

And the [final model from goldbdi example](https://gama-platform.github.io/wiki/GoldMinerModel_step5) copied and pasted gives the following code block starting at line 172:

perceive target:goldmine where (each.quantity > 0) in:viewdist {
		**focus id:mine_at_location var:location;** 
		ask myself {
			if (has_emotion(joy)) {do add_desire(predicate:share_information, strength: 5.0);}
			do remove_intention(find_gold, false);
		}
	}

The bolded text has error: _<<reports "Unknown facet id">>_

Is there an update to the model post release of version 1.8?

**Comment by mathieuBourgais** [comment]
Hello,

I just tested the code and it's workig fine for me. Do you have the latest
version of GAMA ? The id facet of the focus statement has been added in
June, so you need to have a newer version since June.

Regards

Mathieu

**Comment by Bazmundi** [comment]
Thanks. I grabbed copy from 1.8 continuous build and so the problem seems
to be in 1.8 release candidate 1 but not 1.8 continuous build.
