### ISSUE TITLE
Benchmarking with chart broken

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2512]
**Describe the bug**
I am experimenting with benchmark feature, I have the feeling that when there is a chart in the experiment something is wrong. It works fine without chart. Related to #2462

**To Reproduce**
add a display chart in your experiment

```````
display chart{
			chart 'test'{
				data "test" value: 1 color:#red;
			}
		}
```````

run the experimebt with benchmark:true
**Expected behavior**
Normal

**Actual behavior**
NPE
``````
2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in display 'chart'  {
	chart 'test'  {
		data 'test' color: #red value: 1 ;
	}
}

NullPointerException: null
java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1645)
msi.gama.runtime.benchmark.Benchmark$ScopeRecord.find(Benchmark.java:21)
msi.gama.runtime.benchmark.Benchmark$ScopeRecord.getStopWatchFor(Benchmark.java:25)
msi.gama.runtime.benchmark.Benchmark.record(Benchmark.java:37)
msi.gama.runtime.GAMA.benchmark(GAMA.java:452)
msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:373)
msi.gama.runtime.IScope.execute(IScope.java:504)
in agents Simulation 0, selfOrganizedGarbageCollection0

``````

**Desktop (please complete the following information):**
GAMA1.8_Mac_64_08.06.18_0c7200b & Mac OS

**Additional context**

**Comment by AlexisDrogoul** [comment]
It's not a feeling, it's a fact. Bad programming (a statement built with a null description...). I've committed the fix.
