### ISSUE TITLE
Memory warning from GAMA too intrusive

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2513]
I am trying to clean  and refactorize a pretty heavy model right now.

I am thankful to GAMA to tell me that the memory is too high (I am kind of aware of it) and that I should close GAMA and increase the memory however it's a bit too intrusive. 

1. When the simulation is still on it will always give the focus to the keyboard to the place where the memory is low which is my case is in the init of the main model (by the way why this specific part of the model?). Then there is no way to edit your model 

2. If I close the experiment and reload it I will still get the warning that the memory is too high even before to run the model.

This is the message I get 
`````
at cycle 0: Memory is low (364 megabytes). You should close the experiment, exit GAMA and give it more memory
`````

**Comment by AlexisDrogoul** [comment]
If it's too intrusive, change the default values:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/579256/44112971-d08c5ab0-a030-11e8-9195-0a5c55b75977.png">

**Comment by agrignard** [comment]
That's an option indeed, however for the default behaviour I am not sure the focus to a part of the model is really relevant no?

I can get that GAMA is using to much memory but what is the choice behind that choose to point the focus on a specific part of the model? Do you see what I mean?

**Comment by AlexisDrogoul** [comment]
Sorry, no, I don't. Every error focuses on where it originates from and focuses on this part in the editor. It just means that the out of memory error is systematically produced there in your case.

**Comment by AlexisDrogoul** [comment]
I have added a preference for opening the editor automatically if an error appears (it is true by default, to keep the original behaviour). The link with the editor is of course still available if you click on the stack trace. Remember that out of memory errors are very specific exceptions in Java (i.e. you can't really deal with them like you deal with normal exception, as they can happen everywhere, even in parts that are unrelated to your model, hence, probably, the fact that GAMA points at your init section, in an attempt to find a relevant part in the model. The monitoring of memory is even more complicated to trace, as it is not possible to tell which part of the model has used the most of the memory). So setting this preference to false will ensure no editor is brought to front even in the case of out of memory errors.
