### ISSUE TITLE
Initial value of Split distance is not correct

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2514]
**Describe the bug**
The split layer seems broken. Except the first layer the otehr are either very high or simply not displayed 

**To Reproduce**
Run 3D Visualization/Building Elveation.gaml
In the side controls/OpenGL activate Split Layers

**Expected behavior**
Split Layers

**Actual behavior**
Only the first layer is displayed

**Screenshots**
![screen shot 2018-08-14 at 18 19 58](https://user-images.githubusercontent.com/3928502/44121706-f8ccbc00-9fee-11e8-9f1e-66d0ff2a5403.png)

**Desktop (please complete the following information):**
GAMA1.8_Mac_64_08.14.18_ec6cf84

**Comment by AlexisDrogoul** [comment]
It's not broken. If you adjust the split value, it will run normally. It's just that the initial value of split is wrongly computed (should be from 0 to 1, and instead it show 9.203). I will see this.

**Comment by agrignard** [comment]
Oups sorry I didn't check the distance that was just below. So yes the layer was not "broken" it was the computation of the distance ;-)  Anyway this is fixed! cool!
