### ISSUE TITLE
Problem to import a project with remote resources tracked as linked resources

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2516]
**Describe the bug**
Impossible to open a project with a LinkedResources produced on a Mac in Windows. Here is the repo of the project 
https://github.com/agrignard/BlockCar/tree/master/CS_CityScope_GAMA_BlockCar

**To Reproduce**
Import a model that has a LinkedResources description in the .project. Then it throws an error saying that the .project is corrupted and that the project already exists in the workspace however we are in a new empty workspace. See attached file

Note that he model has been produced from a Mac so the location is this one:
`````			<location>/Applications/GAMA1.8_Mac_64_08.06.18_0c7200b.app/Contents/MacOS/C::/Users/CPG/Documents/GAMA/WorkSpace/CityScope_Volpe_1.8/.cache/cityio.media.mit.edu+_++_+api+_+table+_+citymatrix_volpe</location> 
``````
However I am not sure to understand why need to store this information (which seems very local) in a .project

Also we are able to import this project on a older version of GAMA (July 2018)

**Expected behavior**
Normal importation

**Screenshots**
<img width="1639" alt="screen shot 2018-08-15 at 16 33 12" src="https://user-images.githubusercontent.com/3928502/44213998-15770a00-a13d-11e8-94c8-eaa24f7b7584.png">

**Desktop (please complete the following information):**
GAMA1.8_Mac_64_08.15.18_2ef8bfc and Windows10

**Comment by AlexisDrogoul** [comment]
Two things.

Linked resources are effectively not intended to be used outside a given
context as they point to local files. That's why a workspace exist, and
thats why projects intended to be shared should always use workspace-local
resources. Sharing projects with linked resources  makes no sense. The fact
that this information is stored in the project file is how Eclipse works.

I'm a bit surprised however by the error, and also by the fact that you had
been able to import it on Windows with Mac paths... (Or the reverse, I
didn't really understand what you tried to do).

So the goal is to understand what causes this strange error, and probably
to erase in advance the resources that cannot be found.


Le jeu. 16 août 2018 à 21:20, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
_I'm a bit surprised however by the error, and also by the fact that you had
been able to import it on Windows with Mac paths... (Or the reverse, I
didn't really understand what you tried to do)._

It's the opposite the project has been pushed as it is in the github from a Mac and we tried to import it from a windows. 

IS this something new that we store this information in the project? This is the folder that we see name external now right?

**Comment by AlexisDrogoul** [comment]
Yep. It is new that it is done systematically (before, you could always add linked resources manually) and it makes sense to allow users to manage these resources as if they were present in the workspace (i.e. have access to them by ctrl-click, track them in the 'uses' part in the navigator, display them in the viewers).  

I however wonder what is the goal of sharing a project with local-only resources ?

In any case, since it is a very uncommon scenario and that I am not completely sure of what kind of "fix" can be offered:
- you can delete the external folder and its contents before exporting the project 
- you can delete the lines directly in the '.project' file whenever you need to import the project back

**Comment by AlexisDrogoul** [comment]
To be frank, when I look at the path of the file that causes a problem, I'm not surprised it raises an error:

`/Applications/GAMA1.8_Mac_64_08.15.18_2ef8bfc.app/Contents/MacOS/C::/Users/Arno/Projects/Gama/MIT/Gama1.8_August_2018_Doc_2/.cache/cityio.media.mit.edu+_++_+api+_+table+_+citymatrix_volpe`

So it is not a linked resource but a remote resource you are using (i.e. from a server) ? And it went back and forth macOS and Windows, right ? (not only one time). Because the second path is from a workspace in Windows and the first (the one causing problem) belongs to macOS.

**Comment by agrignard** [comment]
Yes exactly I usually develop on my mac and then different user can update from github  on their computer (e.g windows for the demo) and eventually repush. 

This model indeed accesses to a remote file on a sever (this is how we communicate between apps)

I get the fact that the path is wrong but bow can we avoid to write this in the linkderesource of the porject?

**Comment by AlexisDrogoul** [comment]
I've pushed a possible fix for this issue. To test it, you should remove the two offending lines from the .project file and run the model again. After the first run, the linked resources should not be absolute but relative (to a path variable named `CACHE_LOC`) and you should be able to import / export it in different configurations.

**Comment by agrignard** [comment]
OK I will test it between 2 different OS cumputer what it did right now on my computer  is removing this

`````
<location>/Applications/GAMA1.8_Mac_64_08.15.18_2ef8bfc.app/Contents/MacOS/C::/Users/Arno/Projects/Gama/MIT/Gama1.8_August_2018_Doc_2/.cache/cityio.media.mit.edu+_++_+api+_+table+_+citymatrix_volpe</location>
`````
Then rerunning the model that has produced this:

`````
<location>/Users/Arno/Projects/Gama/MIT/Gama1.8_15_August_2018_5/.cache/cityio.media.mit.edu+_++_+api+_+table+_+citymatrix_volpe</location>
`````

Again I am not sure to understand why we need to store those data in the .project file as the file is access remotely. And in this new solution there is still my local path hardcoded in the .project which is weird no?

Anyway I'll keep you update if it works from the other windows computer

**Comment by AlexisDrogoul** [comment]
The file is accessed remotely, but it is stored locally during the session (and it can even be kept in the cache if you specify it in the preferences), so this resource should be accessible like any other resource (esp. if you want to display it, modify it locally, etc.).

I'm a bit surprised that your complete path is stored in the `.project`, however. It shouldn't. Do you use the file only for reading the data or also for storing it ?

**Comment by AlexisDrogoul** [comment]
I've run a model locally, where I just download the JSON data. What I get in the `.project` is: 

```
        <linkedResources>
                <link>
                        <name>external/citymatrix_volpe</name>
                        <type>1</type>
                        <locationURI>CACHE_LOC/cityio.media.mit.edu+_++_+api+_+table+_+citymatrix_volpe</locationURI>
                </link>
        </linkedResources>
```

So not my complete path. How come yours is still showing ?

**Comment by agrignard** [comment]
I only use the file to read the value of a grid.json store in a server (and then I instanciate a GAMA grid, I don't really need to store it and it is accessible from a server)

Ok so I don't see CACHE_LOC using GAMA1.8_Mac_64_08.20.18_8193129
What I do I erase the resources directly in the . project so my .project look like this. I will try with the version of today also

For the preferences ok I could disable it but I try to be as compatible with the default preference settings as I am sharing those models with different people that most of the time will have the default settings in GAMA

``````
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>CityScope_GAMA</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.xtext.ui.shared.xtextNature</nature>
		<nature>msi.gama.application.gamaNature</nature>
	</natures>
</projectDescription>
``````

and then I rerun  the model this is what I have 
``````
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>CityScope_GAMA</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.xtext.ui.shared.xtextNature</nature>
		<nature>msi.gama.application.gamaNature</nature>
	</natures>
	<linkedResources>
		<link>
			<name>external/citymatrix_volpe</name>
			<type>1</type>
			<location>/Users/Arno/Projects/Gama/MIT/Gama1.8_15_August_2018_6/.cache/cityio.media.mit.edu+_++_+api+_+table+_+citymatrix_volpe</location>
		</link>
	</linkedResources>
</projectDescription>

``````

**Comment by AlexisDrogoul** [comment]
No, the preferences means keeping the file in the cache between sessions, not the URL. It doesn't affect what is put in the project as linked resources. And you shouldn't have your path in the `.project`. I don't have it myself when I run your model. It's quite strange.

**Comment by agrignard** [comment]
This is one is close to be done however I still have a strange behaviuor on a windows machine. i'll document it better tomorrow

**Comment by agrignard** [comment]
Weird behavior I can only reproduce it on one machine and unfortunately this is the demo machine of the lab. It used to work three days ago
So it is related to accessing a remote file from a server calling this piece of code, so I guess it is linked to this issue (something is wrong in the path)

'''
try {
  cityMatrixData <- json_file("https://cityio.media.mit.edu/api/table/citymatrix_volpe").contents;
} catch {
  write #current_error + "Connection to Internet lost or cityIO is offline";
}'
'''''
and here is the error:
'''
2 occurrences in 2 agents at cycle 0: Java error: illegal argument
in cityMatrixData <- file<string, unknown>(cityIOUrl).contents;
InvalidPathException: Illegal char <:> at index 2: /C:/Users/CPG/Documents/GAMA/WorkSpace/CityScope_Volpe/.cache/cityio.media.mit.edu+_++_+api+_+table+_+citymatrix_volpe
sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
java.nio.file.Paths.get(Paths.java:84)
msi.gama.common.util.FileUtils.isAbsolutePath(FileUtils.java:97)
when applying the as operator on 'https:\/\/cityio.media.mit.edu\/api\/table\/citymatrix_volpe' and 
'''
So I guess this again this wonderful eternel war between  / and \ ?

it should be C:\Users ? Can I do something here to fix this?

**Comment by AlexisDrogoul** [comment]
Well. The problem is that you shouldn't have the absolute path in the first place (all the C:/.../ should be replaced by `CACHE_LOC). Is the version of GAMA on the demo machine up to date ? Can you tell me exactly what you did before obtaining this error ? I.e. run the model on a Mac, then share it to a PC, and run it again ... ? And what was the state of the '.project' file at each step ?

**Comment by agrignard** [comment]
Yes I am using the version of today

This is the .project that I push in the github (from a mac computer)

````
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>CityScope_GAMA</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.xtext.ui.shared.xtextNature</nature>
		<nature>msi.gama.application.gamaNature</nature>
	</natures>
</projectDescription>
`````

**Comment by agrignard** [comment]
I have check in the windows version the .project is the same as in the github

**Comment by AlexisDrogoul** [comment]
I have pushed a commit that could address this problem (although I don't clearly understand it). It's not normal that you don't have a trace of the cached file in your .project.

**Comment by agrignard** [comment]
... weird did yo start with a .project without any ressources like this one:

````
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>CityScope_GAMA</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.xtext.ui.shared.xtextNature</nature>
		<nature>msi.gama.application.gamaNature</nature>
	</natures>
</projectDescription>
`````

or with one where you just remove the path 
`````
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>OTO</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.xtext.ui.shared.xtextNature</nature>
		<nature>msi.gama.application.gamaNature</nature>
	</natures>
	<linkedResources>
		<link>
			<name>external/citymatrix_volpe</name>
			<type>1</type>	</link>
	</linkedResources>
</projectDescription>`````

**Comment by agrignard** [comment]
Ok so I tried it on the windows computer with the build of today and I can finally run everything well. I can access the json file without any error

I think we are closed to close this issue , I just want to know if in the case of a remote url file is GAMA is suppose to write anything in the linkedRessources or not? I mean what am i suppose to have in this file a linked ressources a line ith CACHE_Loc or just nothing? 

I didn't have time to check the .project of the windows computer I'll check it tomorrow and let you know.

**Comment by cpgmedialab** [comment]
ok so this is how look the .project from this windows computer.

@AlexisDrogoul I let you close the issue if you think this is the right behavior.

```
?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>CityScope_GAMA</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.xtext.ui.shared.xtextNature</nature>
		<nature>msi.gama.application.gamaNature</nature>
	</natures>
</projectDescription>
```

**Comment by agrignard** [comment]
I think we can close this issue.  It's working ok now to share projects that access a remote ressources from Mac to Windows
