### ISSUE TITLE
Rotation with axis equal to zero {0,0,0} - rotate or not?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2517]
I don't if it's bug or a feature:

When using this aspect

`````
	aspect rotation{
 		draw square(1)  rotate: cycle::{0,0,0};
	}
`````

I would assume that the shape won't rotate as the the angle is 0 how ever it behave as if the angle value was {1,0,0}. 

Maybe it's a choice that if the angle is equal to zero we consider it to {1,0,0} it my case I would like to be able to set the angle to 0 (no rotation) sometime but still calling the same aspect.

You can see this in running this model( the idea is to trigger the rotation by pressing on a keyboard but by default it's already spinning)

```````
model model1

global{
  point angleAxes<-{0,0,0};
  init {  
  	  loop i from: 1 to: 1000{
		  create pointCloud{		
		    location<-{rnd(100),rnd(100),rnd(100)};
		    target<-{rnd(100),rnd(100),rnd(100)};
	      }		
	  }		
  }
  action updateRotation(string axe){
  	switch (axe) {
	  match "x" {angleAxes<-{1,0,0};}
	  match "y" {angleAxes<-{0,1,0};}	
	  match "z" {angleAxes<-{1,0,0};}			
	}
  }
  
  action updateX{
  	angleAxes<-{1,0,0};
  }
  action updateY{
  	angleAxes<-{0,1,0};
  }
  action updateZ{
  	angleAxes<-{0,0,1};
  }
  action updateT{
  	angleAxes<-{1,1,1};
  }
}

species pointCloud skills:[moving]{
	float intensity;
	point target;
	reflex move{
		do goto target:target speed:intensity/10;
	}
	aspect rotation{
 		draw square(1) color:rgb(intensity*1.1,intensity*1.6,200,255) rotate: cycle::angleAxes;
	}
}

experiment OK type:gui {
	float minimum_cycle_duration <- 0.0333; //(fps 30)
	output{
		display pointcloud type:opengl background:#black draw_env:false fullscreen:true{
			species pointCloud aspect:rotation;
			event["x"] action: updateX;
			event["y"] action: updateY;
			event["z"] action: updateZ;
			event["t"] action: updateT;
		}	
	}
}

```````

**Comment by AlexisDrogoul** [comment]
There is some confusion here: the first term of the pair is the *rotation angle* while the value (second term) is the *rotation axis* (i.e. the axis around which the shape is supposed to rotate). So you don't specify a zero angle of rotation, but a zero axis of rotation (which is something that is probably not checked, I will verify).

**Comment by AlexisDrogoul** [comment]
I have added a check to the "nullity" of the axis that should cancel the rotation in that case. Please try.
