### ISSUE TITLE
event layer syntax with GAML code 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2518]
**Is your request related to a problem? Please describe.**
GAML Improvement

**Describe the solution you'd like**
What about having a simplier syntax for event where you can just call some GAML code

for instance imagine you just want to change the value of a global boolean variable ````myBool```` by pressing one key we could imagine to have 

`````
event["x"] {myBool<-!myBool};
`````

Right now the event layer is waiting for an action which make then the code a bit more complex (basically you need to write a specific action that will just change a boolean)

**Comment by AlexisDrogoul** [comment]
Could you take a look at the 'event' layer documentation ? 

https://gama-platform.github.io/wiki/Statements#event


There you have your answer. event 'x' action: { ... statements... };
