### ISSUE TITLE
operators "quantile" and "quantile_inverse" not working with unsorted lists

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2520]
**Describe the bug**
Operators "quantile" and "quantile_inverse" do not work as intended. For example, for the list:

list<float> truc <- [24.5,6,4,9,12.5,21,1,5,24,12];

quantile(truc, phi) should return a value T for which a fraction phi of the elements of the lists is < T.
So quantile(truc, 1) should be 24.5, quantile(truc, 0.5),  should be around 10.5.

Instead, we obtain quantile(truc, 1) = 12 and quantile(truc, 0.5) = 16.75. 

That means quantile(truc,1) returns the last element, and quantile(truc, 0.5) returns a value corresponding to the "middle position" of the list. That would be right if the list was sorted, which is not the case.

**Desktop (please complete the following information):**
 - OS: Win 7
 - GAMA 1.8
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
No, it's not a bug, that's how the CERN Colt library handle things. I've updated the documentation for the operators that are concerned.
