### ISSUE TITLE
Wrong casting list problem related

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2523]
**Describe the bug**
I have  model that used on this version of GAMA GAMA1.8_Mac_64_08.15.18_2ef8bfc but not on this one GAMA1.8_Mac_64_08.20.18_8193129)

I guess it is strongly related to this fix
https://github.com/gama-platform/gama/issues/2521

It might occur in many other model?
**To Reproduce**
So I now have a wrong casting error calling this line 
``````
list<list> instances <- trashBin collect ([each.location.x, each.location.y]);
``````
where trashBin is a species

this is the error I get:

``````
2 occurrences in 2 agents at cycle 0: Java error: wrong casting
in list<list> instances <- trashBin collect ([each.location.x,each.location.y]);
ClassCastException: msi.gama.util.GamaList cannot be cast to msi.gama.metamodel.agent.IAgent
gaml.additions.GamlAdditions.lambda$523(GamlAdditions.java:581)
msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:69)
msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:78)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:69)
msi.gaml.expressions.ListExpression._value(ListExpression.java:108)
msi.gaml.expressions.ListExpression._value(ListExpression.java:1)
when applying the . operator on [0.0] and location
in list<list> instances <- trashBin collect ([each.location.x,each.location.y]);

``````

I am not the author of this model (maybe it is not properly written and the author propably didn't update GAMA yet) however I am just anticipating how to handle the situation, does he have to change its code or does GAMA needs to adapt to this by throwing a warning or a deprecated?

**Expected behavior**
It used to work well it is now throwing a java error:wrong casting
Let me know if you need more information (I cannot really share the hole model)

**Comment by benoitgaudou** [comment]
I tried with the following model, without any error: 
```
model NewModel

global {
	init {
		list<list> instances <- trashBin collect ([each.location.x, each.location.y]);
		
	}
}

species trashBin {}

```

**Comment by agrignard** [comment]
did you run the model? in my case it compiles the model throw an error

**Comment by AlexisDrogoul** [comment]
Oops. Yes. Stupid error of mine. Should be fixed in the next commit.
