### ISSUE TITLE
3D Referential drawn when rotating a model

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2524]
Bug or feature?

When rotating the model the referential is now drawn in the middle of the model.I think it's a bit redundant with the sphere rotation drawing but why not.

**Comment by AlexisDrogoul** [comment]
It has always been the case since at least 3 years... 😄

**Comment by agrignard** [comment]
nope I don't think so

I am speaking about the 3D referential orange,red and blue it was not like
that this 3 years for sure

**Comment by agrignard** [comment]
For instance it's not happening on this
GAMA1.8_Mac_64_08.15.18_2ef8bfc

whereas it is happening in this one 
GAMA1.8_Mac_64_08.21.18_9698f81

**Comment by AlexisDrogoul** [comment]
Yes it was a bug that I fixed not so long ago. But the thing has been here for a very long time (I think that you implemented it, by the way).

**Comment by AlexisDrogoul** [comment]
So in any case it's not a bug but a feature (pretty handy when you rotate with the camera very close and the axes are out of sight). Case closed, all right 😄 ?

**Comment by agrignard** [comment]
I don't think we speak about the same stuff. I cannot take a screen shot because it happens when I cmd+ drag (I am already pressing cmd so I cannot do cmd+3) but when you rotate the model using cmd+drag in the GAMA1.8_Mac_64_08.21.18_9698f81 version the 3D referential is drawn in the middle of the model (I am not speaking about the sphere in the middle that yes can be desactivate and that is here for a while). So maybe you reimplementent this referential in the middle but for sure not 3 years a ago or I have never used a version with this "feature". However I think it's redondant with the sphere drawing no?

**Comment by AlexisDrogoul** [comment]
We're speaking about exactly the same stuff, which is in GAMA since exactly 2 years and a half : https://github.com/gama-platform/gama/commit/cc6ac02b9c26135551e0515b574e21cb633e7176#diff-1130ad4d9d068287cb0a288663cc6269. And Julien was the one who implemented it. 

Again, it is not redundant with the sphere as the sphere does not provide any direction: when too close to the scene (without the axes in sight), or when the scene is too complex, having the axes in view is handy when rotating.

**Comment by agrignard** [comment]
@AlexisDrogoul I know what is this sphere drawing made by Julien. I am not speaking about that, When this option is set to false the referential use not to move. On the currrent version of gama even with draw rotation axes to false the referential move, it was not the case before

See in the gif the behavior is different between 
GAMA1.8_Mac_64_08.15.18_2ef8bfc (the referential doesn't move)
and
GAMA1.8_Mac_64_08.21.18_9698f81 (the referential moves)
![untitled mov](https://user-images.githubusercontent.com/3928502/44439849-79615e80-a593-11e8-8d92-05fdee6c12e1.gif)

**Comment by AlexisDrogoul** [comment]
OK. So this is a feature indeed (if it was your question). Because the axes might be out of sight when rotating close to the scene.

**Comment by agrignard** [comment]
No the behavior is different in the 2 version. Can you see it on the gif?

**Comment by agrignard** [comment]
With draw rotation axes to false in the preference the axes doesn't move in the first part of the video ( gama 15th of August) and move ont the 2nd part (gama 19th)

**Comment by AlexisDrogoul** [comment]
Yes. That's what I said, and we won't probably spend one week on this. It is the intended behaviour (the last one) but due to a bug it didn't work for several weeks; I fixed this bug a few days ago and it works now as expected for this feature, because the axes might be out of sight when rotating close to the scene.

**Comment by agrignard** [comment]
Well I can see here that there is no way to get on the same page. Anyway we are splitting hair in two here maybe some other user has some opinion on that? it s not a big deal on my side the only thing I know is that never saw this behavior before and I find it weird to move a referential especially when there is already a dedicated rotation helper. So of course I can always turn of draw_env and rotation helper.
