### ISSUE TITLE
Layer event in the toogle side control shouldn't appear

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2525]
**Describe the bug**

**To Reproduce**
define a layer event like this 

`````
species pointCloud aspect:base;
event["e"] action: {drawEnv<-!drawEnv;};
event["b"] action: {variableSize<-!variableSize;};
`````
**Expected behavior**
Event layer should appear in the side controls however they are

<img width="520" alt="screen shot 2018-08-21 at 23 13 40" src="https://user-images.githubusercontent.com/3928502/44440871-17efbe80-a598-11e8-875d-2802e82bc30a.png">

I think it doesn't make sense to display them right?

**Comment by AlexisDrogoul** [comment]
Right. Fixed in the forthcoming commit.
