### ISSUE TITLE
experiment button status? 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2526]
I know I already request this.

In order to get a very minimal interface are we sure we want to keep this button? Most of the time when developing a model I have one or 2 experiment and most of the modification are made in the model itself. Creating a new experiment is not something you do often. So does it really make sense to keep this grey button?

<img width="131" alt="screen shot 2018-08-21 at 23 18 08" src="https://user-images.githubusercontent.com/3928502/44441038-b2e89880-a598-11e8-99a3-bb39ca34b0d8.png">

**Comment by AlexisDrogoul** [comment]
Actually, this has been already addressed by 035966d55eb487b06e04be38fdf49a74a93d0bc5. 
Simply add the `no_experiment` pragma on top of your model.

**Comment by agrignard** [comment]
I personnaly can live with this button I was more thinking about the lambda users that I think won't use it too much but it s just my 2 cents

**Comment by AlexisDrogoul** [comment]
Well, actually, it has proved to be quite useful for beginners (in training sessions, for instance), allowing them to quickly define skeletons of new experiments. The pragma is for more advanced users who define models to be imported, for instance.
