### ISSUE TITLE
Toolbar in fullscreen enhancement request

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2527]
I really like the feature where you have fullscreen plus the little toolbar in the lower part of the screen where you can still control your model. However sometime I would just lie to control the speed of the model and also relaunch it (without having to esc the fullscreen mode and coming back)

so what about replacing this
<img width="95" alt="screen shot 2018-08-21 at 23 24 25" src="https://user-images.githubusercontent.com/3928502/44441232-9c8f0c80-a599-11e8-9bcc-e35936df6040.png">
by this (or at least just adding the relaunch button if the slider is too much)
<img width="258" alt="screen shot 2018-08-21 at 23 24 36" src="https://user-images.githubusercontent.com/3928502/44441287-dbbd5d80-a599-11e8-8ff2-c4bfd1bee82a.png">

Then the user will have the same control as in the GUI

**Comment by AlexisDrogoul** [comment]
Well, not so easy to do, but I managed to have a working version (committed next). One thing to remember, and there is nothing that can be done about it, is that the reload item will exit the fullscreen, reload the simulation and reenter fullscreen only if the display mentions it is fullscreen. Otherwise, if you enter fullscreen manually, it will reload the simulation in its normal state.

**Comment by agrignard** [comment]
Maybe I was not clear in the initial issue, I am not saying that the fullscreen 100% shoudln't exist anymore (it is crucial) I am just speaking abotu enhancing the toolbar when in fullscreen.

So  I can see the new toolbar now  however is it possible that toolbar facet is now not working anymore?

I get the toolbar even if I put ```toolbar:false```` (Windows and Mac)

**Comment by agrignard** [comment]
I close this issue to make one more specific about toolbar

**Comment by agrignard** [comment]
I notice sometime that after turning into fullscreen and going back (pressing esc) it happens that the simulation rendering stop. Not the simulation (step are still increasing) itself but the visualization of the simulation (we can still however move in the 3D scene)

**Comment by AlexisDrogoul** [comment]
Only with the toolbar on ? In which model ?

**Comment by agrignard** [comment]
Mmm I cannot find a reproductible way to reproduce it.... neither on the library "normal" model, it's happening an a "heavier" but not always.

I think I might close this one as it's hard to reproduce.

The only very little detail that is reproductible (and that might be the cause), when you run a model the "Runs or Pause" button is on play it displays a pause icon but as soon as you go to fullscreen mode it displays a play button whereas it is in play mode (it should display a pause button)
