### ISSUE TITLE
camera position facet copying

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2528]
When copying the facet of the camera position the value pasted are quiet big it makes then the code a bit verbose

e.g

````
camera_pos: {122.8749315,163.91616231655615,393.38231154008434} camera_look_pos: {122.8749315,163.90929649999998,0.0} camera_up_vector: {-6.123233994804145E-17,0.9999999998476914,1.74532868054623E-5}
````

would it be possible to keep let's say 3 or 4 digits max and also replacing 1.74532868054623E-5 by 0

**Comment by AlexisDrogoul** [comment]
Hum.. Complicated, as this was the case before, but it appears it was a problem to truncate camera coordinates. Will see what I can do for just the copy.

**Comment by AlexisDrogoul** [comment]
I have set, by default, a max. precision of 4 digits when copying. Should correct this issue.
