### ISSUE TITLE
Memory indicator in GAMA vs Activity Monitor or Task manager

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2532]
In link with this issue https://github.com/gama-platform/gama/issues/2531

The level of memory display in the bottom left of the UI in GAMA doesn't seem to be coherent with what the activity monitor or the task manager is displaying. 

Also when pressing on the trash (to garbage collect) in the UI the level decrease but it has no impact on the activity monitor 

In this screenshot I just press the garbage collector then GAMA indicates a consumption around 160Mb whereas my activity monitor is style indicating 970 Mb
<img width="1671" alt="screen shot 2018-08-26 at 11 35 32" src="https://user-images.githubusercontent.com/3928502/44629924-4668f300-a924-11e8-8836-2e219f420642.png">

Are this 2 indicator showing the same thing?

**Comment by AlexisDrogoul** [comment]
Maybe a little Google search before could avoid asking these questions in the issues ? 

http://karunsubramanian.com/uncategorized/why-is-there-a-discrepancy-between-windows-task-manager-memory-and-java-heap/

https://plumbr.io/blog/memory-leaks/why-does-my-java-process-consume-more-memory-than-xmx

etc. etc. etc. There are thousands of links about this, the different kinds of memory (heap memory, class memory, etc.), and why tasks manager & co are absolutely not useful to monitor Java applications.

**Comment by agrignard** [comment]
Well... ok that explain the difference between what we see between GAMA and the task manager . So let's close this question let's then call it the "Memory footprint of the JVM and NOT just the Java Heap of the JVM" in issue #2531.

**Comment by agrignard** [comment]
One other article pretty interesting for the record
https://betsol.com/2017/06/java-memory-management-for-java-virtual-machine-jvm/
