### ISSUE TITLE
toolbar facet not working 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2534]
The toolbar facet doesn't work anymore (toolbar is always on wiether you put toolbar to true or false)

see 

````
model multiscreen

global {
 init{
 	create people number:100;
 }
}

species people{
	aspect base{
		draw circle(1);
	}
}
experiment multiscreen type: gui{
	output {		
		
        display CityScope type:opengl toolbar:false{
        	species people aspect: base;
        }
		display CityScopeTable   type:opengl fullscreen:1 {
			species people aspect: base;
		}
	}
}
````
---------------
Latest build - Mac OS & Windows

**Comment by agrignard** [comment]
ok the toolbar is not there anymore however there is still the overlay (should we use a dedicated facet for this?)
<img width="1920" alt="screen shot 2018-08-27 at 17 27 31" src="https://user-images.githubusercontent.com/3928502/44687263-c3789300-aa1e-11e8-82bd-4a395f741531.png">

**Comment by AlexisDrogoul** [comment]
Check your preferences, maybe ?

**Comment by agrignard** [comment]
Ok with changing the preferences I can remove the overlay. However  if it's possible i prefer to be sure that anyone is running this model as the behavior I am defining with the default version of GAMA. 

By default now we have the overlay, this is new no? What do you think to put it off by default (or adding a overlay facet?)

**Comment by AlexisDrogoul** [comment]
Normally it's off by default. But you can always force the preference in your model (just make sure you set it back to its value after).

i.e. 

experiment {
    bool previous <- gama.prefXXX;
    init {
        gama.prefXXX <- new_value;
   }

    abort {
          gama.prefXXX <- previous;
    }
}

**Comment by agrignard** [comment]
Ok for the toolbar it's fixed I close this one
For the overlay I might be wrong but it seems on by default for me, what about you?

see issue ##2536
