### ISSUE TITLE
Save a json file that doesn't exist in CACHE_LOC

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2535]
**Describe the bug**
After fixing the get issue here (#2516) now is the turn of the post
So according to this API GAMA is suppose to be able to talk to a server and send a json file
https://github.com/CityScope/CS_CityIO_Backend/wiki/API

So the following model  to get a grid stroed as a json file from a server then modify this grid in GAMA and resend the json with another name to a server. 

I just discover that is doesn't work anymore and I guess it is linked to this Shared Ressources CACHE_LOC new feature

**To Reproduce**
Run this model (problem appears on cycle 1 (when I try to save))
````
model CityIOGAMA

global {

	geometry shape <- square(1 #km);
 	string cityIOurl <-"https://cityio.media.mit.edu/api/table/virtual_table";
    map<string, unknown> matrixData;
    map<int,rgb> buildingColors <-[-2::#red, -1::#orange,0::rgb(189,183,107), 1::rgb(189,183,107), 2::rgb(189,183,107),3::rgb(230,230,230), 4::rgb(230,230,230), 5::rgb(230,230,230),6::rgb(40,40,40),7::#cyan,8::#green,9::#gray];
    map<string, unknown> header;
    map<string, unknown> spatial;
	int refresh <- 100 min: 1 max:1000 parameter: "Refresh Grid rate (cycle):" category: "Grid";
	int nbCols;
	int nbRows;

	init {
	 do initGrid;
	}

	action initGrid{
        matrixData <- json_file(cityIOurl).contents;
		spatial <-matrixData["header"]["spatial"];
		loop i from: 0 to: nbCols-1 {
			loop j from: 0 to: nbRows -1{
				cityMatrix cell <- cityMatrix grid_at { i, j };
				cell.type<-int(matrixData["grid"][j*nbCols+i][0]);
				cell.depth<-int(matrixData["grid"][j*nbCols+i][1]);
			}
        }  
	}

	action pushGrid (map<string, unknown> _matrixData){
	  save(json_file("https://cityio.media.mit.edu/api/table/update/cityIO_Gama_from_virtual", _matrixData));
	}

	reflex updateGrid when: ((cycle mod refresh) = 0){
		do initGrid;
 	}
 	
 	reflex pushGrid when:cycle=1{
 	do pushGrid(matrixData);	
 	}
}

grid cityMatrix width:nbCols height:nbRows {
	int size;
	int type;
	int depth;
    aspect base{
	  draw shape color:buildingColors[type] depth:depth;
	  draw string(type) color:#black border:#black at:{location.x,location.y,depth+1};		
	}
}


experiment Display  type: gui {
	action _init_ {
   		map<string, unknown> data <- json_file("https://cityio.media.mit.edu/api/table/virtual_table").contents;
		create CityIOGAMA_model with: [nbCols::int(data["header"]["spatial"]["ncols"]), nbRows::int(data["header"]["spatial"]["nrows"]),matrixData::data];
	}

	output {	
		display cityMatrixView  type:opengl  background:#black {
			species cityMatrix aspect:base;
		}
	}
}
````
**Expected behavior**
We are suppose to post a table that then should appear here:
https://cityscope.media.mit.edu/CS_CityIO_Frontend/

**Actual Behavior**
It is looking for a file in CACHE_LOC that doesn't exist (yes this file is just meant to be sent to a server not to be store in CACHE_LOC
**CACHE_LOC/cityio.media.mit.edu+_++_+api+_+table+_+update+_+cityIO_Gama_from_virtual (No such file or directory)**
````
1 occurence in Simulation 0 at cycle 1: Java error: I/O error
in save json_file('https:\/\/cityio.media.mit.edu\/api\/table\/update\/cityIO_Gama_from_virtual',_matrixData) ;
FileNotFoundException: CACHE_LOC/cityio.media.mit.edu+_++_+api+_+table+_+update+_+cityIO_Gama_from_virtual (No such file or directory)
java.io.FileOutputStream.open0(Native Method)
java.io.FileOutputStream.open(FileOutputStream.java:270)
java.io.FileOutputStream.<init>(FileOutputStream.java:213)
java.io.FileOutputStream.<init>(FileOutputStream.java:162)
msi.gama.util.file.GamaJsonFile.flushBuffer(GamaJsonFile.java:134)
msi.gama.util.file.GamaFile.save(GamaFile.java:492)
msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:279)
in save json_file('https:\/\/cityio.media.mit.edu\/api\/table\/update\/cityIO_Gama_from_virtual',_matrixData) ;

````
**Desktop (please complete the following information):**
 - Mac OS
 - Latest Build
 - Java version: [e.g. 1.8]

**Comment by AlexisDrogoul** [comment]
No, the file should exist (ie should be created in the cache) for the save method to work. It is only after having been saved to the cached file that it is uploaded.

**Comment by agrignard** [comment]
Ok I understand with this structure (CACHE_LOC) it should be like that.

The way I saw this feature  before was the following case:

Imagine you want to send a json at each iteration (or n iteration) you might not want to save this file before to send it. 

So this is not a blocking issue for sure and maybe I am not using the good way to send a post using the save statement maybe there is another way?

**Comment by AlexisDrogoul** [comment]
Actually, the cache has been there from the beginning (i.e. the first http connections).

**Comment by agrignard** [comment]
Ok I use to send json to a server a while ago with this syntax. Anyway I will first save a local file to make it work.

**Comment by agrignard** [comment]
yes! It works!
https://cityio.media.mit.edu/api/table/cityIO_Gama_from_virtual
