### ISSUE TITLE
Overlay facet true by default

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2536]
**Describe the bug**
I got the last version of GAMA GAMA1.8_Mac_64_08.27.18_927c433 I run it on a new workspace in order to get the preferences by default 
**To Reproduce**
The overlay is true by default 

**Expected behavior**
Overlay false by default 

**Screenshots**
<img width="1920" alt="screen shot 2018-08-27 at 17 59 22" src="https://user-images.githubusercontent.com/3928502/44688740-20764800-aa23-11e8-9f04-76e72545e011.png">

**Desktop (please complete the following information):**
 Mac os X
GAMA1.8_Mac_64_08.27.18_927c433

**Additional context**

**Comment by AlexisDrogoul** [comment]
The preferences of GAMA are not local to one particular workspace. So you probably turned this on in a previous run of GAMA in another workspace. 

See GamaPreferences.java, line 346 for the default value of this preference (false).

If you want to wipe all preferences, run the class called PreferencesWiper in Eclipse.

**Comment by agrignard** [comment]
ok! sorry for that. I thought the preferences were linked to a workspace. is there a way to wipe all the preferences from GAMA to set the pref by default? For people like me that are always turning it on and off and don't remember what they did?

**Comment by agrignard** [comment]
ok from Eclipse it's working. I was just throwing the concept that this wipe could be done from GAMA. Imagine a user that doesn't use Eclipse that played with different settings of the preferences and doesn't know how to come back to the GAMA default (like me). There is the revert button we could imagine to have a load defaults preferences.

(not a big deal at all)
