### ISSUE TITLE
gama icon as a build in variable

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2537]
**Is your request related to a problem? Please describe.**
It might sounds a bit to branding and/or design oriented but in the same way that we have hardcoded color like #gamared, #gamaorange and #gamablue what about about having a harcoded gama icon?

In some model  I use to put the Gama logo in the lower part of the screen.

<img width="1117" alt="screen shot 2018-08-28 at 15 49 32" src="https://user-images.githubusercontent.com/3928502/44747155-7954e780-aada-11e8-8070-3d78ec24115c.png">

The way I am doing it is by putting a gama .png in includes and displaying a normal .png icon but I was wandering if you would be ok to embed this variable using something like #gamalogo or #gamaicon and then be able to write something like ```draw #gamalogo size:40#px at:{world.shape.width*0.95, world.shape.height*0.95};```

 I don't know if it makes sense and if it's possible to hard code a picture

**Comment by AlexisDrogoul** [comment]
Blocked by https://github.com/gama-platform/gama/issues/1164.

**Comment by AlexisDrogoul** [comment]
Now tracked in #2728

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
Depends on #1164
