### ISSUE TITLE
floating attribute tables

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2538]
**Is your request related to a problem? Please describe.**
The species attribute table is a docked frame and sometimes makes it difficult to scroll wide tables.

**Describe the solution you'd like**
A floating attribute table that can be moved around or to a second screen to help in looking the variables in context of a running simulation or to review some misbehaving attributes.

**Comment by AlexisDrogoul** [comment]
I don't understand what you call the "species attribute table". Is it the population inspector ? if yes, it is neither "fixed" nor "docked", as you can see on this picture. 
<img width="833" alt="image" src="https://user-images.githubusercontent.com/579256/56143198-48261a80-5fca-11e9-96b0-ca46fe603736.png">
