### ISSUE TITLE
Exception (in GAMA?) when loading a picture.

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2542]
**Describe the bug**
Exception in Opengl

I don't know if it's new or not I just notice a weird beahvior on this model that seems to be linked to the fact that I am displaying a picture. Not only it displays an excpetion but then GAMA is difficult to use throwing "Processing quit unexpectedly" message

**To Reproduce**
In a aspect draw an image
1. draw imageRFID size:2#m;	

**Expected behavior**
Normal

**Screenshots**
Non power-of-two textures available: true
Loading static texture : gama_black.png
Non power-of-two textures available: true
Loading static texture : gama_black.png
Non power-of-two textures available: true
Loading static texture : gama_black.png
Non power-of-two textures available: true
Loading static texture : gama_black.png
Non power-of-two textures available: true
Non power-of-two textures available: true
Non power-of-two textures available: true
Non power-of-two textures available: true
Non power-of-two textures available: true
Non power-of-two textures available: true
Non power-of-two textures available: true
Non power-of-two textures available: true
Loading static texture : rfid-tag.png
Exception in OpenGL:Waited 5000ms for: <b6d52ab, 5aabdb6>[count 1, qsz 0, owner <main>] - <Animator thread>
java.lang.RuntimeException: Waited 5000ms for: <b6d52ab, 5aabdb6>[count 1, qsz 0, owner <main>] - <Animator thread>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:168)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
	at ummisco.gama.opengl.view.SWTGLAnimator.displayGL(SWTGLAnimator.java:199)
	at ummisco.gama.opengl.view.SWTGLAnimator.run(SWTGLAnimator.java:180)
	at java.lang.Thread.run(Thread.java:748)
Exception in OpenGL:Waited 5000ms for: <b6d52ab, 5aabdb6>[count 1, qsz 0, owner <main>] - <Animator thread>
java.lang.RuntimeException: Waited 5000ms for: <b6d52ab, 5aabdb6>[count 1, qsz 0, owner <main>] - <Animator thread>

**Desktop (please complete the following information):**
 - OS: [e.g. macOS High Sierra]
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: [e.g. git, 1.7.1, etc.]
 - Java version: [e.g. 1.8]
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

-----------------------------------------------
also the log of the unexpected quit:

Process:               Processing [67661]
Path:                  /Applications/Processing.app/Contents/MacOS/Processing
Identifier:            org.processing.app
Version:               3.3.7 (0264)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Processing [67661]
User ID:               501

Date/Time:             2018-09-04 11:39:26.139 -0400
OS Version:            Mac OS X 10.11.6 (15G1611)
Report Version:        11
Anonymous UUID:        E2AEA7ED-C5D6-B3BC-4DDB-B94E203CB156

Sleep/Wake UUID:       37C2FEED-EA4C-48F5-BBB1-915893C1D33D

Time Awake Since Boot: 870000 seconds
Time Since Wake:       5100 seconds

System Integrity Protection: enabled

Crashed Thread:        24  Java: Java2D Queue Flusher

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000002
Exception Note:        EXC_CORPSE_NOTIFY

**Additional context**
Git version

**Comment by AlexisDrogoul** [comment]
Hi, I don't really understand: the exception is related to Processing, not GAMA. And without the image you try to display, it's difficult to tell anything (since png images load correctly). The "Non power-of-two textures available" is just a message, not an exception.

**Comment by agrignard** [comment]
... I don't understand everything either. Maybe processing was running in //

I cannot reproduce it however I still have this error in eclipse
```
Exception in OpenGL:Waited 5000ms for: <71a029c1, 7f67d985>[count 1, qsz 0, owner <main>] - <Animator thread>
java.lang.RuntimeException: Waited 5000ms for: <71a029c1, 7f67d985>[count 1, qsz 0, owner <main>] - <Animator thread>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:168)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
	at ummisco.gama.opengl.view.SWTGLAnimator.displayGL(SWTGLAnimator.java:199)
	at ummisco.gama.opengl.view.SWTGLAnimator.run(SWTGLAnimator.java:180)
```

**Comment by agrignard** [comment]
... it seems more related to a "too long?" initialization. 

I will close this issue for now
