### ISSUE TITLE
Welcome page appears although a model file was requested

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2544]
**Describe the bug**
Once again not always happening and hard to reproduce. But it happens sometime that when clicking on one model tabs the welcone page appear instead of the model:

![welcome mov](https://user-images.githubusercontent.com/3928502/45071728-bc4c2780-b0a5-11e8-9b37-64b6998c64da.gif)

Git&last 1.8

**Comment by agrignard** [comment]
Hard to reproduce indeed... we can close this one if we consider it comes from a corrupted workspace

**Comment by hqnghi88** [comment]
Well, not to be considered but in your gif there are 2 strange things: blank interractive console and 2 welcome.html tab ....

**Comment by agrignard** [comment]
Still able to reproduce it (sometimes) in the last version, with a relatively clean workspace

![Uploading welcome.mov.gif…]()

**Comment by agrignard** [comment]
Might be linked to a very specific usage (see #2560) corrupting my workspace. Closing it for now.
