### ISSUE TITLE
Grey background when initialising the outputs of a model

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2545]
**Describe the bug**

Bug or feature ?

I notice this few version ago. When initializating a big model we now see a gray window during the initialization phase. We use to see the editor. I think it was much more better to see the editor that the gray window which now  gives the feeling of something going wrong and slow whereas before the indicator in orange saying that instantiating agent was enough

See here a screen shot of the initialization phase for a previous version of GAMA (July 27th)
<img width="1920" alt="screen shot 2018-09-05 at 01 01 37" src="https://user-images.githubusercontent.com/3928502/45072150-ab041a80-b0a7-11e8-8ef6-3d19660709a7.png">
 and the current one
<img width="1920" alt="screen shot 2018-09-05 at 01 02 26" src="https://user-images.githubusercontent.com/3928502/45072156-b1929200-b0a7-11e8-9a78-90b462e9cb3b.png">

**Comment by agrignard** [comment]
mmmm... i am personally not a big fan of this settings I think for the lambda user perspective it really give s the feeling that something is going wrong in the software or that your simulation is super heavy. What about a progression bar or something like that? Why didn't you like the "non grey option" is it a design question or a optimization/software problem? 

I cannot find in the preferences, which option is it?

**Comment by AlexisDrogoul** [comment]
Well. It's a matter of taste, of course. But getting rid by default of the editors in the simulation perspective is a good thing in any case.

The preference is here:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/579256/45121425-51751c00-b18b-11e8-9aa7-b793425452dd.png">

**Comment by agrignard** [comment]
matter of taste ok...
Is progression bar an option?

**Comment by agrignard** [comment]
It's fine it's clearly not a bit deal, it is just maybe my feeling only but when working on heavy model you see a lot this gray screen each time you restart a computer but the preferences can be set so let's say it's fine. It clearly not a priority
