### ISSUE TITLE
Disable numerical key triggering the camera

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2556]
**Describe the bug**
I am more and more using the digits keys form 0 to 10 to trigger some event in a simulation using event. 

However from 0 to 6 has been assigned to preset  the camera position in opengl. I don't find this very useful. Would it be possible to had a preferences (maybe there is already one) to disable this feature.

**Expected behavior**
Add a preferences or disable it by default.

**Comment by hqnghi88** [comment]
Can you give a glue as i 've never use it, no idea where is it. Of course it could be a preference, but true by default.

**Comment by agrignard** [comment]
When you press 2,4,6,8 in opengl it affects the position of the camera. I am not a big fan of this feature I don't think a lot of people use it. But yes if we would have it in the preferences to disable it that would ne great

**Comment by hqnghi88** [comment]
2468 ok i see (not really 0-6). 2468 is like arrows key but for 3d camera so for me, it helps for most win/linux machine as they soften have numeric keyboard in the right and mostly mousepad of win is not good as mac. Even sometimes we also move mouse with 2468. Anyway a preference is surely the solution. I ll post it soon
