### ISSUE TITLE
fullscreen in Windows produces a white line on the edge of the window

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2557]
### Steps to reproduce
0. use a windows computer
1. press esc on any running simulation to go in fullscreen mode

### Expected behavior
100% fullscreen

### Actual behavior
in mac the fullscreen is a 100% fullscreen whereas in windows there is a tiny white line in the frame (1px)

This might sounds as a detail but in the case of an exhibition where you display a model with a black background you don t want to see the frame of the projector. 

### System and version 
Gama 1.8 RC2

**Comment by hqnghi88** [comment]
Not reproducible on mine win. Did you check the preference (border around view)
![img_20181022_151528](https://user-images.githubusercontent.com/6105384/47283405-850de780-d60d-11e8-944e-80187af7f3c9.jpg)

**Comment by agrignard** [comment]
MMM it seems that this feature is set to false by default. 

I will try to recheck on a windows computer asap but i have the feeling that by default there is the border (where as is not here on mac)

**Comment by hqnghi88** [comment]
Can we close this now?
