### ISSUE TITLE
A link of visualisation with "should-displayed" agents

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2558]
**Is your request related to a problem? Please describe.**
No problem, just an enhancement idea

**Describe the solution you'd like**
Currently, we have the zoom level in displays, and also a preference to only simulate displayed agents in the view. I think we could have something to control/access these attributes, it should help the simulation's speed and also to make some animation in details, i.e: for a city, when zoomed in a house scale, people agent inside shown and play.

**Describe alternatives you've considered**
- multi level modeling , i did not explore carefully.
- a global attribute for zooming (xx%?) or/and built-in attribute of agent relate to the "only simulate displayed agent" (like boolean displayed )that should be true of false. So we can get a list of currently displayed agent, or depend on the zoom level, we can make some sympa simulation then.

**Additional context**
No more.
Thanks.

**Comment by AlexisDrogoul** [comment]
The zoom value is already available so you can use it for that purpose.

**Comment by hqnghi88** [comment]
Thank you, it works perfectly for `#zoom` . I just did not know it work only in aspect, not in reflex.

**Comment by hqnghi88** [comment]
Thank you, it works perfectly for `#zoom` . I just did not know it work only in aspect, not in reflex.
