### ISSUE TITLE
fullscreen:1 no way to escape

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2560]
**Describe the bug**
In a normal configuration (no external screen) write fullscreen:1 in a display

**Expected behavior**
Fullscreen on your main screen and being able to escape fullscreen mode by pressing esc 

** Actual behavior**
Pressing esc doesn't have any effect, the computer stays stuck on the gama simulation and the only way to quit gama is to force quit.

**Comment by sriramab** [comment]
Please see, if you are on a mac, make sure you have not assigned GAMA to any desktop. I had this problem resolved by not assigning GAMA to any desktop.

**Comment by agrignard** [comment]
What do you mean by "assigning GAMA to any desktop"?

**Comment by sriramab** [comment]
If you right click any app in the dock on a mac, you can assign the app to a "desktop" (or screens). Dont assign any desktop/screen to GAMA.

**Comment by agrignard** [comment]
In term of "missing details" and "missing use case" this issue is pretty straightforward to reproduce no?

**Comment by AlexisDrogoul** [comment]
@agrignard which OS ? which version (Eclipse / desktop) ? With ou without JVM, etc...

**Comment by agrignard** [comment]
Gama 1.8 RC 1 and mac os 10.11.6 (I know its a bit old) and it also happenign on another mac os (newer) I 'll check which one

**Comment by agrignard** [comment]
Ok so it's also happening on a macbook pro running High Sierra (the desktop os assign to none by default). 

It is clearly not a critical bug I just want to get a trace of it

**Comment by agrignard** [comment]
Has been "fixed" here https://github.com/agrignard/URBAM/commit/d6c1531ad40467e6c11c67e352d0d943f9647ffd

there was a ````layout```` set in the same time of a ````fullscreen```` which doesn't make sense, however should we document it?

**Comment by agrignard** [comment]
I tested on a "classic" model using fullscreen and layout at the same time and it seems to work

So I close this issue for now.
