### ISSUE TITLE
New operator to get the N closest agents/geometries to a given agent/geometry

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2562]
**Is your request related to a problem? Please describe.**
For the moment, there is no optimal way to get the N closest agents/geometries to a given agent/geometry. 

**Describe the solution you'd like**
An operator that will use the quadtree to do that.

**Comment by hqnghi88** [comment]
Dear Patrick, i see some commit on n_closest operator, but have it finished yet this issue?
