### ISSUE TITLE
About the transparency. 

### ISSUE THREAD

**Issue by ILHEM88** [gama-platform/gama#2565]
Hi, 

I just have a small question about transparency in GAMA. I noticed that the transparency in the Toggle side controls is 1-the transparency used in the code. So if in the code the transparency=1 (which means complete transparency ) it shows 0 value in the Toggle side controls. 
I want to know if this is made on purpose. I mean why we don't keep the same mechanism?

Thank you in advance 
Ilhem

**Comment by hqnghi88** [comment]
Yes, there is a glitch on GUI , as i found some misleading calculation. But the main point in this issue: @AlexisDrogoul @agrignard What is the right value for "transparency" ? 0 mean no trans and 1 mean total trans or reverse. I remember sometime in the pass we have the opacity term which is not exist anymore but somehow the calculation of transparency still meant opacity. Somewhere in the document also: 
agent layer: transparency (float): the transparency applied to this layer (between 0 and 1, 1 means no transparency)

**Comment by hqnghi88** [comment]
I changed the code base to make transparency from 0 (solid) to 1 (total transparent).

**Comment by hqnghi88** [comment]
See my last comment, and it marked as fixed if you find it is not, please reopen then.

**Comment by ILHEM88** [comment]
Dear Nghi, 
Yes I know actually I can't update GAMA now (I have to continue using the versionRC1 1.8). So I'm asking if I can continue using the old transparency (included in the old versions of GAMA)? If it will not affect other things? 
Thank you in advance 
Ilhem
