### ISSUE TITLE
Assigning `nil` to variables of type `message` assigns a value that is not `nil`

### ISSUE THREAD

**Issue by lodo1995** [gama-platform/gama#2573]
**Describe the bug**
Assigning `nil` to a variable of type `message` does not generate any warning or error, but causes that variable to contain a valid message instead of being a null reference.

**To Reproduce**

    model bug

    experiment bug {
        init {
            message msg <- nil;
            write 'Nil message: ' + msg;
            agent a <- nil;
            write "Nil agent: " + a;
            point b <- nil;
            write "Nil location: " + b;
        }
    }

**Expected behavior**
The first `write` should print `null`, as the second and third one do (included as reference behaviour). 

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - GAMA version: 1.8 RC 2
 - Java version: 1.8

**Additional context**
This bug can have quite big unexpected results. For example, users would expect `one_of (proposes where <some_condition>)`  to return `nil` if no propose message satisfies the condition. Instead, that expression will return a valid reference to a message that never existed. It's a very unexpected behaviour.

**Comment by hqnghi88** [comment]
How about `one_of (proposes where (each.content!=nil and <some_condition>))`?
In this issue i cannot say it's worst or better to give nil from an nil assign. It is depend on how is the rule that we decide assigning nil to a data type, as there was some issue on list and map,
    	map mm<-nil;
    	write mm;
    	list ll<-nil;
    	write ll;
You'll get map([]) and [] , the container. And i prefer for the current solution, an assign nil to message return the container with "null content" (it shown correctly). I think only the documentation is not good enough.

**Comment by lodo1995** [comment]
@hqnghi88 Ok. Now I understand what's going on. But I don't think it's the best approach. The behaviour of `nil` is currently very inconsistent, as it is both a value and a constructor of different values. It's very strange that if I do `message msg <- nil`, then `msg = nil` evaluates to `false`.

**Comment by lodo1995** [comment]
Also, there is apparently no rule on what can have value `nil` and what can't: `map`, `list` and `message` get an "empty container", while `string`s become `nil` (why not the empty string?). Numerical types receive value `0`, while `point`s receive `nil` (why not the point `{0, 0, 0}`?).

**Comment by hqnghi88** [comment]
Lets say about inconsistent, Gama is built on top of java and the big objective is for non-computer-expert scientists. So we faciliate most of the things that will take time and efforts for them. Think about a world that you must place every where the check =nil without these auto-casting. Most of programming languages chose the default value for their data types. So i cannot answer all your "whys". And not-nil-container is an enhance for the "big objective" i mentioned. You can surely open a discussion in google group and if there will be any changes we can place another concrete issue.
Thanks.

**Comment by lodo1995** [comment]
Ok. Thank you for your time. I'll open a discussion on the mailing list as soon as I have time and put a link here.
