### ISSUE TITLE
Allow the creating of global actions/functions that every species/level can use

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#2576]
In most computer/ABM languages, it's possible to define functions that can be executed independently of the caller.
Ie.,  a function to print the current time, to define a logger, to simplify a list computation etc.

Currently, afaik, this is not possible in Gama : a function (`action`) is only accessible from the scope it was declared into, and not from dependent scopes.

Ie., when declaring a global action, it can't be used by agents species, even if it has nothing to do with the calling agents.

Here's an example of what fails :
```
model NewModel
global {
	action printSomething {
		write("globalPrint");
	}
	init{
		create blob number: 2;
		ask blob {
			do printSomething;
		}
	}
}
species blob{}
experiment NewModel type: gui {}
```

And here's how to make it work :
```
model NewModel

global {
	action printSomething {
		write("globalPrint");
	}
	init{
		create blob number: 2;
		ask blob {
			do printSomething;
		}
	}
}
species blob{
	action printSomething {
		write("globalPrint");
	}
}
experiment NewModel type: gui {}
```

This means that for every species calling a function, we have to redefine this same function for each of those, except when defining all species as parents of some super-specise having the intended action.
When dealing with multiple species, this appears to be really cumbersome and verbose.

Would it be possible to introduce a facet (or argument) to actions so as to define the scope of those actions ?
For example, this could be expressed like this

```
action printSomething(global: true)
```

I understand that it feels like hacking/crafting,  but the only alternative (afaik...) is creating java functions inside gama source-code, which seems really heavy. I'm really not sure of my proposal, but yet, I'm convinced that it would be valuable to be able to define functions (or global actions), as it's a very important component of every language and habit of programming.

**Comment by hqnghi88** [comment]
How about ask world{do printSomething;} ? Overall, the logic is to ask the agent that has the action execute its action. "global" is also an agent (world), just as same as any other agents.

**Comment by hqnghi88** [comment]
And if you want a hack, something like craft
model NewModel
global {
	bool printSomething {
		write("globalPrint");
		return true;
	}
	init{
		create blob number: 2;
		ask blob {
			unknown call<- world.printSomething();
		}
	}
}
species blob{}
experiment NewModel type: gui {}

**Comment by RCura** [comment]
> 
> 
> And if you want a hack, something like craft
> model NewModel
> global {
> bool printSomething {
> write("globalPrint");
> return true;
> }
> init{
> create blob number: 2;
> ask blob {
> unknown call<- world.printSomething();
> }
> }
> }
> species blob{}
> experiment NewModel type: gui {}

This is a very good idea, and works perfectly for my use case !
For the outputs, I was using an `enquote` action, like this :
```
	action enquote (unknown text) {
		return '"' + string(text) + '"';
	}
```
I had to define this same action for every species of agent.
But now, I can simplyf redefine it as :
```
	string enquote (unknown text) {
		return '"' + string(text) + '"';
	}
```

And use it everywhere as `string blob <- world.enquote(myString);`

So, this is perfect ! Thanks @hqnghi88 

This issue might be closed as it's a quite simple way (and I guess that's the solution most commonly used) to declare and use global functions.

**Comment by hqnghi88** [comment]
You're welcome. so i close this.
