### ISSUE TITLE
GoogleMaps Image Import.gaml broken (WebbException) 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2577]
**Describe the bug**
WebbException

**To Reproduce**
1. Run GoogleMaps Image Import.gaml

**Expected behavior**
Display a map

**Screenshots**
<img width="1920" alt="screen shot 2018-11-30 at 10 04 55" src="https://user-images.githubusercontent.com/3928502/49296905-6d851280-f487-11e8-884f-a62d86a5617b.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - GAMA 1.8 RC2

**Additional context**

**Comment by hqnghi88** [comment]
What is the exact value you paste in the dialog?

**Comment by agrignard** [comment]
Maybe we could think about a OpenStreetMap alternative?

**Comment by hqnghi88** [comment]
I cannot found alternative on OsM. but mapquest has a static map like that. see MapQuestImageImport.gaml. I consider this issue as closed

**Comment by agrignard** [comment]
Should we keep the GoogleMapsModel in the release?

**Comment by AlexisDrogoul** [comment]
I strongly suggest we change the model to move to Bing (https://docs.microsoft.com/en-us/bingmaps/rest-services/?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fbingmaps%2Frest-services%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2FBingMaps%2Fbreadcrumb%2Ftoc.json). However, this requires a Bing Maps account. @hqnghi88 , do you think you can create one for GAMA ?

**Comment by hqnghi88** [comment]
I created a hotmail: gama-platform@hotmail.com and sign in bing map to get this "secret" (we should public it in the model in the library??) key: AvZ5t7w-HChgI2LOFoy_UF4cf77ypi2ctGYxCgWOLGFwMGIGrsiDpCDCjliUliln

**Comment by AlexisDrogoul** [comment]
Hum... You're right. I'm not sure we are allowed to post it in the models (and not sure we can post it here neither !)

**Comment by AlexisDrogoul** [comment]
Does it work, though ? With Bing ?

**Comment by AlexisDrogoul** [comment]
OK. I see https://github.com/gama-platform/gama/commit/327be84d5e08a3924bb06b5e2030ec42c5518ea8, so I guess we can safely remove the GoogleMaps one...

**Comment by hqnghi88** [comment]
Dear Alexis,
Yes, i commit the model, just remove it if you think the secret key policy is not good.
Cheers.

**Comment by AlexisDrogoul** [comment]
No, it's ok. Only thing is that it would be nice to be able to enter a query or an address rather than the lat,lon pair. It was possible with GoogleMaps, I think it is possible with Bing, but I don't have enough time to look at their REST API. If you are courageous enough to do it (i.e. get the input from the user, maybe the size of the map too ?), then you can safely remove the Google Maps example and close this issue ! :)

**Comment by hqnghi88** [comment]
For googlemaps, it requires a billing account , means an account with a valid visa card, not for pay but i am not really happy with this policy (as i have once to pay 300$ for an automatic rebilling cycle - after 30days free try). So if the data from other source (MapQuest, bingmap) is acceptable, i think we can remove googlemaps.
Cheers.
