### ISSUE TITLE
Wrong version displayed for version 1.8 in Finder on OS X Mojave

### ISSUE THREAD

**Issue by jdzucker** [gama-platform/gama#2579]
When asking for info in the menu of the Gama Platform (A propos de GAMA Platform) it says
"GAMA Platform  - V1.7.0". It should say V1.8.X".
It ought to be corrected in the Config.ini file.

**Comment by hqnghi88** [comment]
Dear Jean-Daniel,
Is it in the "About Gama"? I just checked and it shows V1.8.0
![image](https://user-images.githubusercontent.com/6105384/49788222-5a155980-fd5b-11e8-87a5-a9eb5457b984.png)

**Comment by sriramab** [comment]
I think it is one of the RC , one of the users on the form also reported this

**Comment by hqnghi88** [comment]
OK , may be an old rc, as i just download rc2 and it is V1.8.0

**Comment by jdzucker** [comment]
> Le 11 déc. 2018 à 15:42, HUYNH Quang-Nghi <notifications@github.com> a écrit :
> 
> Dear Jean-Daniel,
> Is it in the "About Gama"? I just checked and it shows V1.8.0
> 
Dear Nghi,
Not on the users one As Sirima said.
Best
Jean-Daniel

**Comment by AlexisDrogoul** [comment]
Checked as well and everything is ok on the development version.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/579256/49909931-690f1f80-feb3-11e8-961b-cf502933f1cd.png">

You should specify the version number you are using (it's probably RC1).

**Comment by jdzucker** [comment]
You are write. I reloaded the very last version and it says now 1.8. However on Mac OS X Mojave 10.14.1 in the finder when doing cmd+I it says version 1.7
![image](https://user-images.githubusercontent.com/12623800/50049813-77ae3e80-0120-11e9-80ce-491782ef5210.png)
