### ISSUE TITLE
Wrong parameters value in Tutorial

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2582]
**Describe the bug**

Run Tutorials/Road Traffic/models 03.gaml
 
<img width="1915" alt="screen shot 2018-12-12 at 15 01 05" src="https://user-images.githubusercontent.com/3928502/49895651-fc4a4580-fe1e-11e8-811c-e5950ed671ca.png">

With this syntax:

`````
parameter "maximal speed" var: max_speed category: "People" max: 50 #km/#h;

`````
**Expected behavior**
I would assume to see 50 km/h as a max but we have 1.3888888888888888

**Comment by AlexisDrogoul** [comment]
Why would you assume to see 50 km/h ? In the model, you can find the definition of `max_speed` as follows:
```
	float max_speed <- 5.0 #km / #h; 
```
which, according to #1566, displays as `1.38888` **m/s** (implicit unit).

So the display is correct.
