### ISSUE TITLE
Code from main model is executed twice in headless mode

### ISSUE THREAD

**Issue by ThibautDemare** [gama-platform/gama#2583]
Hello,

**Describe the bug**

In headless mode (no problem in GUI mode), if I start a simulation from a model file which import another file which itself import the "main" file, then the code from the main file is executed twice.

**To Reproduce**

Execute the attached model in headless mode. 
In this model, I create only one agent in the main file called "TestHeadless.gaml". This file imports "TestImport.gaml" which itself imports "TestHeadless.gaml".

[model_test.zip](https://github.com/gama-platform/gama/files/2676617/model_test.zip)

**Expected behavior**
It should display in the console :
Asking to MyAgent
I am an agent !

but instead it displays :
Asking to MyAgent
I am an agent !
I am an agent !

**Desktop (please complete the following information):**
 - OS: executed in headless mode inside a Docker container under Ubuntu
 - GAMA version: developer version
 - Java version: 1.8

Cheers,
Thibaut

**Comment by AlexisDrogoul** [comment]
Grouped in #2453 with other headless issues.

**Comment by hqnghi88** [comment]
@AlexisDrogoul @gnoubi i found a replication of compilation of the imports (differs of platform resources uris and non-platform resource uris - absolute/relative paths) so a recursive importation of main model has not been eliminated, i added a check and conversion to cannonical path . Please correct it if you have time.

**Comment by gnoubi** [comment]
Thanks Nghi, 

I will check. I will try to take time before the coding camp. If not, I will fix bug during the coding camp 

Nico

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by ThibautDemare** [comment]
Just wanted to share this little piece of code 
https://gist.github.com/ThibautDemare/83d0708c81a70a63684da837102f11df
It merges all gama files (from the current directory) into one to avoid this bug. It could help someone who encounter the same bug until it is fixed.
