### ISSUE TITLE
Problem with the driving skill

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2584]
**Describe the bug**
In some case, an agent can overtake another one in a one-lane road (at the end of the segments).

**To Reproduce**
Test model Driving-Skill-Road-Traffic-simple-(Simple-track) and observe the one-lane road.

**Expected behavior**
In the one-lane road, no agent should overpass another one.

**Comment by AlexisDrogoul** [comment]
Driving skill has been deprecated so we wont address this issue.
