### ISSUE TITLE
Saving to shape file seems to turn the shapes upside down

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2586]
**Describe the bug**
Try the library model "Save to SHP.gaml".

**To Reproduce**
1. Execute the experiment
2. Locate the saved SHP file (in `results`)
3. Open it in the shape file viewer
4. see the difference (cf. image)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: all
 - GAMA version: git
 - Java version: 1.8
<img width="672" alt="image" src="https://user-images.githubusercontent.com/579256/52159414-480ec200-26df-11e9-87a2-5819fe4cf046.png">

**Comment by hqnghi88** [comment]
Any glue for this issue? I tried to understand but cannot see where it should be wrong from history. @ptaillandier

**Comment by AlexisDrogoul** [comment]
What is surprising is that the resulting shape file is clearly upside down (QGis opens it this way) but, read again in GAMA to create agents, it's ok. For instance, if one changes the model to :

```java
model Savetoshapefile

global {
	init {
		geometry free_space <- copy(shape);
		
		//creation of the building agents that will be saved
		create building number: 10 {
			shape <- square(5.0);
			location <- any_location_in (free_space - 5.0);
			free_space <- free_space - shape;
		}
		//save building geometry into the shapefile: add the attribute TYPE which value is set by the type variable of the building agent and the attribute ID 
		save building crs: 4326 to:"../results/buildings.shp" type:"shp" attributes: ["ID":: int(self), "TYPE"::type];
		create b2 from: shape_file("../results/buildings.shp");
	}
}
  
//species that represent the building agents that will be saved
species building {
	string type <- flip(0.8) ? "residential" : "industrial";
	aspect default {
		draw shape color: type = "residential" ? #lightgray : #yellow;
	}
}

species b2;
experiment main type: gui {
	output {
		display map background: #black{
			species building;
			species b2 {
				draw shape - 1 color: #red;
			}
		}
	}
}
```

one obtains the correct result: 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/579256/56866181-8bd44780-6a00-11e9-973c-2e838ffc9296.png">

**Comment by ptaillandier** [comment]
Hi,

This issue only appears when GAMA has no reference CRS (like in this
model): in this case, GAMA is not going to apply any transformation to the
geometries when saving them... so the geometries will be upside down as the
"y-axis" is reverse in GAMA.
If you add in the global section: geometry shape <- envelope(
file("../results/buildings.shp"));, the save statement is going to work
normally (no more " upside down").
So, the solution is just, when saving geometries and when no CRS is defined
to apply a reverse transformation on the y-axis.

Le dim. 28 avr. 2019 à 16:57, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
@ptaillandier two things which I find counterintuitive, if not buggy, then: 
1. I though GAMA had a "default" reference CRS for saving files. which is available in the preferences (see first and second images). However, setting it to true or false does not change the behaviour. 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/579256/56939458-a9a1c980-6b32-11e9-89d7-16de0045ce78.png">
<img width="617" alt="image" src="https://user-images.githubusercontent.com/579256/56939471-b9b9a900-6b32-11e9-9935-7b5ff018c5c2.png">
2. Passing a crs to the save statement does not change the results either (while it probably should, isnt'it ?). E.g. `save building crs: 4326 to:"../results/buildings.shp" type:"shp" attributes: ["ID":: int(self), "TYPE"::type];`

Any thoughts on this ?

**Comment by ptaillandier** [comment]
You are right. I am going to fix this issue.
