### ISSUE TITLE
Add an operator 'contains_any' or 'any_with'

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2587]
**Is your request related to a problem? Please describe.**
Knowing if a container contains an element with some properties is, syntax wise, a bit cumbersome in GAML. `(cc count each.property) > 0` or `!empty(cc where each.property)` are working solutions, but painful to write.

**Describe the solution you'd like**
A simpler operator, which could be one form of `contains_any`, for instance: `(cc contains_any each.property)`

**Describe alternatives you've considered**
see above

**Comment by AlexisDrogoul** [comment]
I've implemented the addition to GAML with 3 operators (if the container contains any, at least one or no elements with the property), with however a doubt on the name to give them:

- In the report above, `contains_any` is suggested, which would lead to `contains_one` and `contains_all`. Beyond the confusion with the already existing `contains_any`, the names themselves are not particularly well chosen: `cc contains_any each.property` is difficult to write and read.

- Another choice would be to use `one_matches`, `none_matches` and `all_match`. I find it a bit more readable. 

Can you give me your opinion on this ?

**Comment by sriramab** [comment]
may be other verbs like: include, carry, consist or just a simple `has`

**Comment by hqnghi88** [comment]
Dear,
Agree with Srirama, has or has_any, has_one ...
