### ISSUE TITLE
Size of snapshots in headless mode

### ISSUE THREAD

**Issue by hblitza** [gama-platform/gama#2588]
**Problem:**
In headless mode the output of displays results in 500x500px images.

**Proposed solution:**
Possibility to set custom image output size in headless mode.

**Describe alternatives you've considered**
The autosave parameter (e.g. autosave:{2000,2000} within the experiment does not save images in headless mode - correct me if I'm wrong.

If this proposed solution is not feasible, do you have ideas for a workaround?

**Comment by AlexisDrogoul** [comment]
Should be something to set in the headless script file, in my opinion (i.e. not in GAML).

**Comment by AlexisDrogoul** [comment]
Grouped in #2453 with other headless issues.

**Comment by hqnghi88** [comment]
@hblitza You can now specify the size of snapshot (continuous build of gama) in the headless xml, for ex:

  <Outputs>
    <Output id="1" name="SS" framerate="1" width="1500" height="1500" />
  </Outputs>

**Comment by hblitza** [comment]
Thank you for taking care of this!
Unfortunately the result is not how I expected it to be. I can set custom image size now but the resolution seems to be the same, see the attached screenshot (also tested with bigger image dimensions). I would expect to recognize the single roads and dots clearly.
Sorry if I mix up something, don't know if I explained my issue well enough in the beginning - and thanks for your help!
![resolution_issue](https://user-images.githubusercontent.com/37144910/56682615-3a5c4d80-66cc-11e9-9bf7-326ce67e26d6.png)

**Comment by AlexisDrogoul** [comment]
@hqnghi88 It's probably because the internal size of the display is not changed -- only the size of the output..

**Comment by hqnghi88** [comment]
I did not test the autosave in gui but i have the feeling that it is really another issue: change dpi , not only the size, of the output. I will take a look.

**Comment by gnoubi** [comment]
Hi

I am agree with the analysis of Alexis. Headless defines is own size of canvas.

Nicolas

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by hqnghi88** [comment]
Sorry, I think it is really a dpi issue, not the size of canvas as he declared his needs is to recognize single road.
I tested the autosave in GUI, on the left a 5000px and on the right 15000px, they are both on 20% zooming. As once the snapshot is write out, it is raster, it is not anymore vector as in simulation display, zooming has no effect to show clearly the small elements.


![image](https://user-images.githubusercontent.com/6105384/56704679-454cc780-6738-11e9-9dca-2e1e801252c5.png)


@hblitza workaround is to use the camera facet to zoom in the area that you want to observe

![image](https://user-images.githubusercontent.com/6105384/56704874-04a17e00-6739-11e9-842b-1d158d1d4b57.png)

**Comment by hblitza** [comment]
@hqnghi88 ok, thanks for the error analysis and your proposed workaround. I will try to make use of the camera facet for now. Yet, it would be helpful to change the dpi of screenshots in headless mode too, but that's another issue as you said.
