### ISSUE TITLE
Batch model with repeat and keep_seed to false has the same seed

### ISSUE THREAD

**Issue by bruesba** [gama-platform/gama#2589]
Closed issue 2184 that was reported by dphilippon also occurs for me (GAMA 1.8, JDK 8), and on 2 different machines with the same specs. The original description:

### Steps to reproduce
1. Create a model using batch, the facet repeat to repeat the simulation and the facet keep_seed set to false so that we can repeat the simulation having stochasticity with different seed. Add a monitor that will give the seed of the simulation (or use the one I give).
2. Launch the batch experiment and look at the monitors...

### Expected behavior
The seeds should be different...

### Actual behavior
The seeds are the same

```
model repeatNoKeep

/* Insert your model definition here */
global
{
	bool finished<-false;
	int an_integer<-0;
	
	reflex update
	{
		if(cycle>5000)
		{
			finished<-true;
		}
	}
}
experiment batchTest type: batch keep_seed: false repeat:4 until: finished
{
	float minimum_cycle_duration <- 0.1#s;
	parameter "An Integer" var: an_integer min:0 max:10;
	output
	{
		monitor "Seed" value: seed;
	}
}
```

**Comment by ptaillandier** [comment]
Hi,

You made a small mistake in your model: the seed displayed by the monitor is the one of the experiment, not the one of each simulation.

In the init block of the global section, if you display the value of the seed, you will see that the values are different:
init {
		write "seed: " + seed;
	}

**Comment by ILHEM88** [comment]
@ptaillandier 
I noticed that the value of the seed when the facet keep_seed is true is much bigger than when it is false. Can I know why? 
Thank you in advance 
Ilhem
