### ISSUE TITLE
Parameter does not compute expression in among

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2591]
**Describe the bug**
In an experiment, when a parameter has a set of possible values specified in the among facet by expressions, these expressions are not evaluated. This is also the case when using units.
See the model below, that shows a warning on the parameter:

```
model Test

global {
	float t <- 1#h;
}

experiment Test type: gui {

	parameter "T" var:t among: [1#h,1#s];

}
```

**Expected behavior**
no warning :-)

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git
 - Java version: 1.8

**Comment by hqnghi88** [comment]
The same on win. and ,more magic:
	parameter "T" var:t among: [#h,#s];
worked

**Comment by benoitgaudou** [comment]
Hi

No magic here I think: my guess is that is at the compilation step there is
one step that checks whether the init value is in the among list (and that
in this step some expressions are not evaluated).
So when there is no init value, no problem 😀

Cheers

Benoit

**Comment by hqnghi88** [comment]
OK totally, you are right.
I tested this: 
	float ty <- 1.0; 
	parameter "Ty" var:ty among: [(0.9 +0.1), 1.2];
You'll fix it?

**Comment by hqnghi88** [comment]
Problem come from containsValue of ListExperssion i think, and it is written by purpose to not compute non-constant value, i dont know the vague effect then.
