### ISSUE TITLE
User-customized perspectives

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2592]
**Is your request related to a problem? Please describe.**
Relate with #1841 , if we agree to let modelers(who want to deploy theirs models) customize GAMA perspective even with GamaWeb, the current structure underground does not allow to several opration such as : chose main perspective (to first launch), lock/prevent switch perspective, customize menu/toolbar. 

**Describe the solution you'd like**
Somehow, in the model or a config file (relate with the experimental plugin Gamr) , modelers can design the perspective. I imagine a pragma ` @ launchSimulation`  that will lock the simulation perspective, prevent to switch to modeling perspective and also hide other stuff like navigator,toolbar,menu. etc...

**Comment by agrignard** [comment]
Hi Nghi, Thank you for having a look at this. I am sure there is a big complexity here.

Just to be sure to start on the same page. For me there is a difference between locking the modelling perspective ones the experiment is launch that means that at the initial state the user is in the modelling perspective and thus has access to the code. The idea of a .gamr would be to directly open the simulation perspective without seeing the modeling one. That means it would be generated by the modeller ones the model is "done".

**Comment by AlexisDrogoul** [comment]
I think the new options for `layout` (cf. gama-platform/gama#2740) completely cover this purpose. If there is absolutely a need to remove some menus, etc. please open a dedicated issue with more details.

**Comment by agrignard** [comment]
I agree too and it also answers to some of the question (not all)  raised in https://github.com/gama-platform/gama2/issues/12
