### ISSUE TITLE
Difference between the expected value of simulation time and the calculated/displayed one

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#2597]
**Describe the bug**
I have a model with a step of 10#minute, but after many steps, instead of showing one year and something, it shows 0 year and something. I have put some screenshots of the displayed time one step before the year have passed and one step further.
![bug_cycle_4](https://user-images.githubusercontent.com/15722750/52850962-d5c2c680-314f-11e9-8a38-ba436d97c3c5.PNG)
![bug_cycle_5](https://user-images.githubusercontent.com/15722750/52850963-d65b5d00-314f-11e9-9d36-31b41273312b.PNG)

Note that this bug is present in both GIT version (at least the one downloaded from today) and also the RC 2 for 1.8 (I do not know for previous versions). 

**To Reproduce**
1- Launch a model, with whatever step lower than 1#year (for obvious reasons)
2- Execute it
3- Look at the displayed time in the execution bar (the one where the number of cycles is displayed) When it reaches 1 year, the first year is not taken into account. 

**Expected behavior**
After one year has passed, it should be 1 year and something, not 0 year and something.

**Desktop (please complete the following information):**
 - Windows 10
 - 1.8 RC 2 AND The version downloaded from today's build (I don't know for other previous versions)

**Comment by hqnghi88** [comment]
Can you give the simple model , Damien? it seems that i cant reproduce this.

**Comment by dphilippon** [comment]
Sure ! 

Use this model, and when the model pauses, look at the simulated time, it should be the last day of the year, 23:50. The following step should add 10 more minutes, making it to one year simulated. You will see that the time simulated is not correct. 
<img width="380" alt="screenshot 2019-02-23 at 7 22 33 pm" src="https://user-images.githubusercontent.com/15722750/53285823-7a708400-37a0-11e9-9e3f-0d41e8bffbe5.png">

<img width="402" alt="screenshot 2019-02-23 at 7 22 42 pm" src="https://user-images.githubusercontent.com/15722750/53285825-7b091a80-37a0-11e9-8710-7f51121b6bd9.png"> 
^here it should be 1y 00m 00d 00:00

```
/***
* Name: Show_Bug_Year
* Author: Damien
* Description: 
* Tags: Tag1, Tag2, TagN
***/

model Show_Bug_Year

/* Insert your model definition here */

global
{
	int tmp <- 10;
	
	float step <- 10#minute;
	
	reflex pause_before_year when: cycle=365*24*6-2
	{
		do pause;
	}
}

experiment show_bug type:gui
{
	
}

```

**Comment by hqnghi88** [comment]
Thanks Damien, your model reproduce the bug. I did not find the solution yet.
