### ISSUE TITLE
No coherence between Date and every(#month), every(#year) ... 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2598]
**Describe the bug**
I want that some reflexes are executed every month or every year, with a real calendar.
So I wanted that a reflex executed every year is executed when the variable current_date is the first of January and a reflex executed every month is executed when the current_date is the first of the month.

But it is not the case. For example, for a reflex executed every year, I get the following outputs in the console:
```
Every year : 1970-01-01 01:00:00
Every year : 1970-12-27 01:00:00
Every year : 1971-12-22 01:00:00
Every year : 1972-12-16 01:00:00
```

And I get similar results for a reflex executed every month.

**To Reproduce**
1. Run the following model and observe the console.
```
global {
	float step <- 1#d;
	date starting_date <- date([1970,1,1,1,0,0]);
	
	reflex y when: every(#year) {
		write "Every year : " + current_date;
	}
	
	reflex m when: every(#month) {
		write "   Every Month : " + current_date;
	}	
	
	reflex w when: every(#week) {
		write "       Every Week : " + current_date;
	}		
}

experiment NewModel3 type: gui {
	output {}
}
```

**Expected behavior**
I am expecting in the previous model, to get (for the reflex executed every year):
```
Every year : 1970-01-01 01:00:00
Every year : 1971-01-01 01:00:00
Every year : 1972-01-01 01:00:00
Every year : 1973-01-01 01:00:00
```

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - GAMA version: git
 - Java version: 1.8

**Comment by hqnghi88** [comment]
Hi,
I tried to compare with a reflex ys when: (current_date.day=1 and  current_date.month =1 ) 

Every year : 				1970-01-01 01:00:00 days:0
current_date.day=1 
and  current_date.month =1: 1970-01-01 01:00:00 days:0

Every year : 				1970-12-27 01:00:00 days:360
current_date.day=1 
and  current_date.month =1: 1971-01-01 01:00:00 days:365

Every year : 				1971-12-22 01:00:00 days:720
current_date.day=1 
and  current_date.month =1: 1972-01-01 01:00:00 days:730

Every year : 				1972-12-16 01:00:00 days:1080
current_date.day=1 
and  current_date.month =1: 1973-01-01 01:00:00 days:1096

It seems the counter is ok but there is of course no coherence from every syntax. I dont know how to make it work as every count a fix amount (may be in second) so every(#month) or every(#year) mean every 30*24*60*60 sec (#month) or every 12*30*24*60*60 sec (#year) . how could ew separate the syntax of every amount and every calendary?
Any suggestion?

**Comment by AlexisDrogoul** [comment]
As far as I know, and it has been discussed in the mailing list I think, it is impossible to reach a complete coherence between the computation by dates and the (simple) computation based on durations, because some durations are not exact. #year and #month (contrary to #day or #minute, for instance) do not represent exact durations, but durations depending on the current date (and, in the case of the `every` operator, on the starting date as well).

**Comment by AlexisDrogoul** [comment]
After discussions, there is nothing we can do to improve this behaviour. `Every month` is intrinsically ambiguous in English, as is `every year`, and I don't see how we could (and should) remove this ambiguity in GAML. So the only solution for modellers is to use explicit conditions, like testing the number of the day, etc.

I therefore close this issue.
