### ISSUE TITLE
Documentation embedded in the hover popup is broken in some cases

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#260]
**Describe the bug**
I noticed that the documentation of the image layer in the popup window that appears on hovering  the image keyword seems broken:
It includes the titles of the `usage` parts of the documentation without the actual examples, which is really weird:
![image](https://github.com/user-attachments/assets/ac86d7f4-c0d7-43eb-9fc0-82a55d05f116)

**To Reproduce**
1. write an image layer in a display
2. hover over the image keyword with your mouse

**Expected behavior**
Either the Usage part is completely ignored, or it is displayed including the examples.
Another alternative would be to write the documentation a bit differently so it won't feel weird to only have the value of usage and not the examples, but I think in that case there's probably a lot of statements and operators to redo.

**Comment by AlexisDrogoul** [comment]
Should be fixed by https://github.com/gama-platform/gama/pull/307/commits/45808cb0898097afaba0a56c5810be9f9185d35f . Please test.
