### ISSUE TITLE
Draping effect for geometries on DEM

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2600]
**Is your request related to a problem? Please describe.**
GAMA allows with OpenGL display to draw a grid as a 3D DEM. But, it is difficult to display agents on the top of the DEM. So, a nice enhancement would be to give the possibility to let GAMA manage the fact that geometry is displayed with a draping effect on the DEM.

**Comment by agrignard** [comment]
As far as I remember we used to display agent on top of a DEM like in this video https://youtu.be/ycbeYxV2B7M?t=38

What is the problem you are facing? What do you mean by draping?

**Comment by AlexisDrogoul** [comment]
Now tracked in #2728

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
Actually closing this issue as it does not really make sense to do it automatically -- but it can be done easily in models by forcing the Z value of the location of agents. An exemple of the effect wanted is to be found in `Eroding Vulcano.gaml`, where it is done automatically by the physics engine.
