### ISSUE TITLE
The Preference "Default step for the delay slider" is never used

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2603]
**Describe the bug**
The modification of the preference "Default step for the delay slider"  in Preferences does not have any effect on the slider when running the simulation.

Notice that, after looking at the source code, the `CORE_DELAY_STEP` variable is never used :
```
public static final Pref<Double> CORE_DELAY_STEP = create("pref_experiment_default_step",
				"Default step for the delay slider (in sec.)", 0.01, IType.FLOAT, true).in(NAME, EXECUTION);
```

**To Reproduce**
1. Open Preferences, change the value of the "Default step for the delay slider"
2. Run any model
3. change the value on the top slider
4. observe that the step defined does not have any effect.

**Desktop (please complete the following information):**
 - OS: macOSX Mojave
 - GAMA version: git
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
Well. Its not really a bug. It's more a non-feature 😄

**Comment by AlexisDrogoul** [comment]
I've made the decision to disable the pref, as it is a bit cumbersome to implement.
