### ISSUE TITLE
Problem with texture (opengl) - z -axis

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2604]
**Describe the bug**
For some complex shape, the use of textures for obj files seems to give weird results....

**To Reproduce**
1. Test the attached model

**Expected behavior**
With GAMA 1.8 RC1, the result was ok, but since GAMA RC2, the result is .....just awful (Zombie effect)... there is a problem with the "z-axis".... I think it's called having your head in your feet....

**Screenshots**
Result with GAMA 1.8 RC1
![GAMARC1](https://user-images.githubusercontent.com/1506077/54194041-a0459a80-44bb-11e9-828d-6f7b99561fe9.png)

Result with GAMA 1.8 RC2
![GAMARC2](https://user-images.githubusercontent.com/1506077/54194047-a3d92180-44bb-11e9-94ef-46da4a7143de.png)

Model:
[bugtexture.zip](https://github.com/gama-platform/gama/files/2956384/bugtexture.zip)

**Comment by AlexisDrogoul** [comment]
Which OS ? I would bet on an image loading problem in the JOGL library (image upside down), but I can't point out which part can be responsible for that.

**Comment by ptaillandier** [comment]
Same problem with Windows (10 - 64bits) and Linux (Ubuntu 16.04 64 bits) -

**Comment by AlexisDrogoul** [comment]
OK. I think the inversion (of the image) is on the Y-axis, btw. Have you tried with other image formats ?

**Comment by ptaillandier** [comment]
I have the same problem with the 5 different obj files that I have on my computer

**Comment by AlexisDrogoul** [comment]
Did you try with JPG files ? It's the same ?

**Comment by ptaillandier** [comment]
I tried converting the png file to jpg (and modify the mtl file to take the new file into account), and I got the same result.

**Comment by AlexisDrogoul** [comment]
Can you try to add `texture.setMustFlipVertically(true);` at line 366 of `GamaObjFile.java` to see if it solves the problem on your side ?

**Comment by ptaillandier** [comment]
Nope, it does not change anything. Note that I use an image editor (gimp) to flip vertically the image, it works.

**Comment by ptaillandier** [comment]
Another thing: if I set "useCache" to false, Line 365 of GMAObjFile, it works without having to set mustFlipVertically to true:
texture = gl.getTexture(f, false, **false**);

**Comment by hqnghi88** [comment]
In TextureCache2.java , replace line 169
final TextureData data = AWTTextureIO.newTextureData(gl.getGLProfile(), file, true, null);
by:
BufferedImage image=ImageIO.read(file);
final TextureData data = AWTTextureIO.newTextureData(gl.getGLProfile(), image, true);

**Comment by AlexisDrogoul** [comment]
@hqnghi88 be aware that changing the TextureCache will affect all textures (not only for OBJ files). 
Actually, the fix is twofold because (1)  the images in the static cache are not loaded the same way as the images in the volatile cache; (2) regular objects emit texture coordinates in 2D (not 3D), which means the y-axis needs to be reversed in that case in OpenGL.java.
I will commit the changes soon.
