### ISSUE TITLE
Problem with shapefile attributes that have the same name as geometry built-in attributes

### ISSUE THREAD

**Issue by Brunste** [gama-platform/gama#2606]
I'm trying to import two GIS shapefiles for my display: one for major roads (roads_clip.shp) and one for smaller streets (street_clip.shp). The major roads display fine, but the smaller streets become a strange, squiggly line in the top left corner of the display. When I view the shapefile using GAMA's shapefile viewer, the file looks fine. I created all shape files by importing an OSM file to QGIS and cropping it to the size I needed.

Any advice would be greatly appreciated. I've included links to pictures of the issue, a download link for my files, and my code below.

[Display error occuring](https://i.postimg.cc/2jhspTcT/squiggle.png)
[Comparison of error and shapefile viewer](https://i.postimg.cc/Y9cdbBH7/comparison.png)
[Shapefiles](https://github.com/gama-platform/gama/files/2967936/GIS.zip)

Here's a copy of my very simple code
```
model modelname

global
{
	file shape_file_buildings       <- file("../includes/cus/buildings.shp");
	file shape_file_major_roads <- file("../includes/cus/maj_roads.shp");
	file shape_file_streets          <- file("../includes/cus/streets.shp");
	geometry shape <- envelope(shape_file__buildings);
	
	init 
	{
		create building from: shape_file_buildings;
		create road      from: shape_file_major_roads;
		create street    from: shape_file_streets;
	}
}

species building
{
	rgb color <- #black;
	
	aspect base {
		draw shape color: color;
	}
}

species road
{
	rgb color <- #black;
	aspect base {
		draw shape color: color;
	}
}

species street
{
	rgb color <- #gray;
	aspect base {
		draw shape color: color;
	}
}

experiment modelname type: gui
{
	parameter "Shape file for buildings: "      var: shape_file__buildings category:     "GIS";
	parameter "Shape file for major roads: " var: shape_file_major_roads category: "GIS";
	parameter "Shape file for streets: "         var: shape_file_streets category:           "GIS";

	output {
		display displayname type: opengl {
			species building aspect: base;
			species road     aspect: base;
			species street   aspect: base;
		}
	}
}
```

**Comment by ptaillandier** [comment]
Hi,

The problem comes from the fact that you have one of the attributes of your
objects on the street shapefile that is called "location" that
interferes with the location attribute of the agents.
So a simple solution is to modify the name of the attribute in your
shapefile (for "loc" for instance). But we should add a warning (and maybe
modify the name of the attribute on the fly) to warn the modeler.

Cheers,

Patrick

**Comment by AlexisDrogoul** [comment]
The problem is that... it is **not an issue** ! The reading of attributes from shapefiles is intended to work this way: if you have an attribute with the same name in your species, then it is automatically set. It would therefore be strange to emit a warning.

**Comment by Brunste** [comment]
That did it. Thank you both so much, you're the best. I'll go ahead and close this "issue".
