### ISSUE TITLE
Wrong casting from GamaPair to String!

### ISSUE THREAD

**Issue by Damapproject** [gama-platform/gama#2607]
**Describe the bug**
I don't know whether this is a bug or not, but it took me some time to figure out the problem. This little code throws a wrong casting exception.

**To Reproduce**
string msg0 <- "Put some value";
string v0 <- "v0";
map values <- user_input(msg0,[v0::"0"]);

**Expected behavior**
Normally it should display the user input form, but it throws this exception:
2 occurrences in 2 agents at cycle 0: Java error: wrong casting
in map values <- user_input(msg0,[v0 :: '0']);
ClassCastException: msi.gama.util.GamaPair cannot be cast to java.lang.String
msi.gaml.operators.System.userInput(System.java:212)
gaml.additions.GamlAdditions$349.run(GamlAdditions.java:387)
gaml.additions.GamlAdditions$349.run(GamlAdditions.java:1)
msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:77)
msi.gaml.statements.LetStatement.privateExecuteIn(LetStatement.java:83)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57) when applying the user_input operator on 'Put some value' and [v0 :: '0']
in map values <- user_input(msg0,[v0 :: '0']);
in init  {
	string msg0 <- 'Put some value';
	string v0 <- 'v0';
	map values <- user_input(msg0,[v0 :: '0']);
}

**Solution**
v0 is already a string, however it needs to be casted to string or at least surrounded by brackets "()".

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - GAMA version: 1.7.0
 - Java version: 1.8.0_191

**Comment by benoitgaudou** [comment]
Another solution that would make it work is to transform the list into a map:
```		
map values <- user_input(msg0,map([v0::"0"]) );
```
