### ISSUE TITLE
access matrices and vectors - one or n index

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2609]
hi 

This has reference to forum discussion 
https://groups.google.com/forum/#!topic/gama-platform/2I9UkvANqJ8

The main issue is to access a vector with single index. The access gives a warning, but it works. But if we try to access a vector in a if statement, we get syntax error. So something seems inconsistent. 

I request you to kindly check this issue

**Comment by AlexisDrogoul** [comment]
Hi,

I have tried the following code: 

```java
global {
	matrix<float> velocity_vector <- matrix([[21.505438470235408, -15.331647084409788]]);

	init {
		write type_of(velocity_vector);
		write sample(velocity_vector);
		write sample(length(velocity_vector));
		write sample(velocity_vector[0]);
			write sample(type_of(velocity_vector[0]));
		write sample(velocity_vector[0, 1]); //returns nil
		if velocity_vector[0] > 20 {
			velocity_vector[0] <- 20;
		}

	}

}

experiment ee;
```

I get warnings, and an execution error when executing `velocity_vector[0] <- 20;` (which needs to be fixed). But the remaining of the execution is correct: 

```java
matrix<float>
velocity_vector -: matrix<float>([[21.505438470235408],[-15.331647084409788]])
length(velocity_vector) -: 2
velocity_vector[0] -: 21.505438470235408
type_of(velocity_vector[0]) -: float
velocity_vector[0,1] -: -15.331647084409788
```

So, 2 things here:

1. The matrix is declared as `matrix([[21.0, -15.0]])` but its literal value (using `sample`) returns `matrix<float>([[21.0],[-15.0]])`... There is a problem here, no ? 
2. `velocity_vector[0] <- 20` returns an error while it should work like when reading the value at index 0. 
3. When the matrix is declared as `matrix([[21.0], [-15.0]])`, `velocity_vector[0, 1]` returns `nil` like in the original issue, though I don't really understand why (and its literal value is incorrect again: `matrix<float>([[21.0, -15.0]])`).

**Comment by AlexisDrogoul** [comment]
Well... I have fixed most of the issues above, with only point 1) remaining.

**Comment by AlexisDrogoul** [comment]
Closing this one (the literal value does not seem to cause a problem -- or does it (in that case, please reopen) ?

**Comment by sriramab** [comment]
> Hi,
> 
> I have tried the following code:
> 
> ```java
> global {
> 	matrix<float> velocity_vector <- matrix([[21.505438470235408, -15.331647084409788]]);
> 
> 	init {
> 		write type_of(velocity_vector);
> 		write sample(velocity_vector);
> 		write sample(length(velocity_vector));
> 		write sample(velocity_vector[0]);
> 			write sample(type_of(velocity_vector[0]));
> 		write sample(velocity_vector[0, 1]); //returns nil
> 		if velocity_vector[0] > 20 {
> 			velocity_vector[0] <- 20;
> 		}
> 
> 	}
> 
> }
> 
> experiment ee;
> ```
> 
> I get warnings, and an execution error when executing `velocity_vector[0] <- 20;` (which needs to be fixed). But the remaining of the execution is correct:
> 
> ```java
> matrix<float>
> velocity_vector -: matrix<float>([[21.505438470235408],[-15.331647084409788]])
> length(velocity_vector) -: 2
> velocity_vector[0] -: 21.505438470235408
> type_of(velocity_vector[0]) -: float
> velocity_vector[0,1] -: -15.331647084409788
> ```
> 
> So, 3 things here on which I need your comments before proceeding:
> 
> 1. The matrix is declared as `matrix([[21.0, -15.0]])` but its literal value (using `sample`) returns `matrix<float>([[21.0],[-15.0]])`... There is a problem here, no ?
Hmm, I do not see a problem. It is indeed a float matrix. 
> 2. `velocity_vector[0] <- 20` returns an error while it should work like when reading the value at index 0.
Yes, this is very strange for me.
> 3. When the matrix is declared as `matrix([[21.0], [-15.0]])`, `velocity_vector[0, 1]` returns `nil` like in the original issue, though I don't really understand why (and its literal value is incorrect again: `matrix<float>([[21.0, -15.0]])`).
Equally strange for me.

**Comment by sriramab** [comment]
This seems to be working. Thank you Alexis

```php
model NewModel

global {
	/** Insert the global definitions, variables and actions here */
	init{
		
		list<float> velocity <- [rnd(1.0), rnd(1.0)];
		matrix velocity_vector <- matrix(velocity);
		write velocity_vector;
		write velocity_vector[1];
		
		if velocity_vector[1]  < 1 {
			write " this cannot be, it is a uniform distribution";
			
		}
		if velocity_vector[1]  < 1 {
			velocity_vector[1] <- 100;
			write velocity_vector;
			
		}
	}
}

experiment ee type: gui {
	/** Insert here the definition of the input and output of the model */
	}
```
