### ISSUE TITLE
Import 3DS file in GAMA

### ISSUE THREAD

**Issue by JeanRemiPIAT** [gama-platform/gama#2610]
Hi,

I would like to import a 3DS file to GAMA. I tried to import my file in the _includes_ folder in GAMA but it didn't work. Do I need some plugins ? Which 3D file can I use to create a 3D model in GAMA ?

**Comment by agrignard** [comment]
Hi @JeanRemiPIAT usually this kind of question goes to the mailing list as it's not an issue related to a bug or a feature to develop.

i would suggest to have a look at the different model in Data Importation (e.g Obj File loading.gmal)
