### ISSUE TITLE
Drag and drop interaction on touchscreen

### ISSUE THREAD

**Issue by JesusLopezBaeza** [gama-platform/gama#2613]
We noticed issues with the user interaction when the model is running on a touch-table computer. Our model takes this part of the code from the model "Moving Agents.gaml" found in Library Models-Features-User Interaction.

On a laptop, when clicking the 'agent to move' with the mouse, one can move, copy and delete them.

However, since thouch-tables have no mouse, these interactions misbehave. Tapping the screen is equivalent to clicking with the mouse, but there's no cursor.

I'm guessing the issue is referring to these interactions through '#user_location' and 'difference'. Is there a way to re-model these interactions using the position of the 'clicks' unrelated to the position of a mouse?

**Comment by hqnghi88** [comment]
Hi,
It must have some solutions. One workaround that you can try is implementation of double click. here is the Moving Agent.gaml with double click gesture (change the extension from txt to gaml).
 
[Moving Agents.txt](https://github.com/gama-platform/gama/files/3046137/Moving.Agents.txt)

**Comment by JesusLopezBaeza** [comment]
Hi,
I tried with double click (see video attached). Now I'm guessing that the issue is displacement: Simply moving around the mouse on the laptop equals to click and drag on the touch-table. Then the agents are selected with double click but one can't move them around and leave them on a different location.
[IMG_2261.MOV.zip](https://github.com/gama-platform/gama/files/3053749/IMG_2261.MOV.zip)

**Comment by hqnghi88** [comment]
Hi,
Sorry, can you try to drag the circle when it is green (after double click)? I see in the video that you chose by doubleclick then double click on another place. It seem touch driver on win dows did not recognize the mouse position. I dont have touch windows device but i remote a Win by mobile phone (by touching) , see clip https://photos.app.goo.gl/REzTSBLbufbSijrp7

**Comment by JesusLopezBaeza** [comment]
Hi, 
Dragging did not work - it would only change the camera position. 
However, the double-click version works when tapping with two fingers.
Thanks!

**Comment by hqnghi88** [comment]
Well, it is a workaround, so feel free to reopen or request a new issue if you encounter other problem.
Cheers.
