### ISSUE TITLE
Add edge with weight

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2614]
**Describe the bug**
In order to add an edge to a graph with a weight, it is possible to write 
```
add edge({10,10},{90,50}, 10.0) to: the_graph2 ; 
```

but we can also write:
```
add edge({10,10},{90,50}) to: the_graph2 weight: 10.0;
```
But the second way of writing does not work: the weight is not taken into acocunt.
We should either let it work or remove it.

**Desktop (please complete the following information):**
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
I've deprecated `weight:` in both the `add` and `put` statements. They were effectively not used anymore except in conjunction with the `edge:` and `node:` facets, themselves deprecated...
