### ISSUE TITLE
Access to an edge in a hand-made graph

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2615]
**Describe the bug**
In the code below, I create a graph and add an edge (edge({10,10},{90,50},10.0)) with a weight. then I display the weight of all the edges, by looping over the edges. This works as expected. 
```
global {
	graph<geometry, geometry> the_graph2;
	
	init {		
		the_graph2 <- graph<geometry, geometry>([]);
		add edge({10,10},{90,50},10.0) to: the_graph2;
		
		loop e over: the_graph2.edges {
			write e;
			write the_graph2 weight_of e;
		}
	}
}
```

But intuitively I had the feeling that (at least) one of the 2 following should work:
```	
	write the_graph2 weight_of edge({10,10},{90,50},10.0);
	write the_graph2 weight_of edge({10,10},{90,50});
```

In the Java code, it seems that `edge({10,10},{90,50})` is not recognized as being contained in the graph.

**Desktop (please complete the following information):**
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
The `edge` operator is supposed to work only when adding / setting edges in graphs. But you'e right: this is a bit counterintuitive (what works is `write the_graph2 weight_of ({10,10}::{90,50});` (i.e. using a pair)). So I've rewritten `weight_of` (and also `contains_edge` and `contains_node`) to accept objects created with `edge` and `node`. There might be some other operators which could be enhanced this way, please reopen and list them if it is the case.
