### ISSUE TITLE
facet size for text drawing doesn't work 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2616]
I am a bit surprised that I never notice this before, I have the feeling that using the facet size when drawing text doesn't have any impact. Uisng the facet font gives the possibility to change the siez of the font but it seems to me that size was used at some point, should we deprecate it or document that it's not working with text?

GAMA 1.8 RC2

**Comment by hqnghi88** [comment]
you use perspective: false or true?

**Comment by agrignard** [comment]
in both case i have an issue, do you?

**Comment by tnguyenh** [comment]
I remember having had a similar issue when dealing with text drawings (in MarrakAir for example). Unless if I missed something, it is very difficult to deal with the size of text drawing. Zooming in the display make the text not fit the space as intended, as in the attached picture.

![text_with_zoom](https://user-images.githubusercontent.com/18676913/55661298-6726ee80-580b-11e9-93c4-7f950be61025.png)

Not having a tool to manipulate properly text drawings is not harmful for the scientific purpose of the models. However this is very limiting when it is required to have a clean and informative display, that keeps being consistent when zooming, switching to full screen, or running a simulation on another computer of video projector. I suggest to change this issue to enhancement enquiry.

**Comment by hqnghi88** [comment]
@Tri there is a model "Text display" in Feature\User Interaction. I think it fit your needs.
![image](https://user-images.githubusercontent.com/6105384/55663802-80e92580-584d-11e9-91dc-cd3e6fc5da9a.png)
@Arnaud you are right, facet size  does not affect the text size in both perspective values and display types.

**Comment by AlexisDrogoul** [comment]
@tnguyenh "manipulate properly text drawings" does no mean anything. Many tools are already available to do it in GAMA (including the one cited by @hqnghi88, which corresponds to  #2261), so you need to be more specific on what is missing/required, possibly in another request for enhancement. 

@agrignard indeed the `size` facet is not used anymore for drawing texts (at least since `font` exists, I think). I've changed the documentation to reflect that.

**Comment by agrignard** [comment]
I am with @tnguyenh regarding the fact that "manipulate properly text drawings" can be challenging and I can take some of the responsability on some of this especially on the OpenGl part and I dont think @AlexisDrogoul would say the contrary. This issue  was just remembering that size was one way to play with the size; I see that using font is doing also the job, I just wante to be sure that it was at least stated in the documentation. I will have a look also at the tool mention by @hqnghi88 that spunds prette interested.

**Comment by agrignard** [comment]
I reopen this issue as I have some trouble to change the size of the font when using draw string in an overlay

`````
draw string("xxx") at: { 10#px, 20#px } color: #white font: font("Helvetica", 20,"bold"); 
`````

The size font doesn't have any effect.

**Comment by AlexisDrogoul** [comment]
Please open a separate issue as this is likely a different problem (i.e. nothing to do with the `size:`  facet)
