### ISSUE TITLE
Listening 2 different UDP port from GAMA

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2618]
**Is your request related to a problem? Please describe.**
I'd like to have a GAMA simulation that would be able to listen 2 different UDP port. 

**Describe the solution you'd like**
The idea would be to create to NetworkAgent like this:

`````
create NetworkingAgent number: 1 {	
do connect to: url protocol: "udp_server" port: 9777 ;
}
create NetworkingAgent number: 1 {
do connect to: url protocol: "udp_server" port: 9778 ;
} 
`````
**Describe alternatives you've considered**
Right now it seems that GAMA is "only" able to listen to one port at the same time(the first one that is connected in this case 9777). 

**Additional context**
In my specific case I have a scanner sending a lego grid from one process and a physical interface controling the simulation with arduino slider from another process.

**Comment by AlexisDrogoul** [comment]
Hi, it seems that the skill tries to reuse connectors as much as possible and caches them in a map stored in the simulation, with the address of the server as the key. Obviously, this is where the problem lies: the port is not part of the key ! I'll try to look into it.

**Comment by AlexisDrogoul** [comment]
@agrignard the fix I provided needs to be seriously tested, as I don't use this skill...

**Comment by agrignard** [comment]
ok i'll test it asap

**Comment by agrignard** [comment]
Great! it seems to work like a charm! I will stress test it a bit more. 
Pretty cool feature I am controlling a simulation both from a scanner webcam sending on one udp port) and from and arduino for other parameters.

thanks for the quick fix!
