### ISSUE TITLE
Should throw an error when we use the species statement in a display

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2619]
**Describe the bug**
I made the following mistake in a model: I use the keyword `species` instead of `draw` in an aspect. No error is thrown by GAMA but the agents are not displayed.
For example: 
```
model NewModel

global {

	init {
		create building  {
			shape <- square(10.0);
		}
	}
}

species building {
	string type; 
	rgb color <- #gray  ;
	
	aspect base {
		species shape color: color ;
	}
}


experiment road_traffic type: gui {
	
	output {
		display city_display type:opengl {
			species building aspect: base ;
		}
	}
}
```

**Expected behavior**
An error should appear to not allow species in aspect.

**Desktop (please complete the following information):**
 - OS: macOSX
 - GAMA version: git
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
Funny. You've entered a black hole of the semantic validation ! As a matter of fact, these also work: 

```java
species building {
	string type;
	rgb color <- #gray;   
	action dd {
		species ff facet: "facet";
		grid toto;
	} 
	aspect base {  
		species ff;
		grid toto;
	}

} 
```

`species` and `grid` declarations, with arbitrary facets, as long as they were syntactically correct, were simply overlooked during the semantic validation when they were inside a block. 

I've closed the hole. Thanks for reporting it.
