### ISSUE TITLE
Parameter list is not dynamically initialized with init values

### ISSUE THREAD

**Issue by Damapproject** [gama-platform/gama#2623]
**Describe the bug**
Parameter can't be dynamically initialized even when using the "_init_" example from "Init Action.gaml". The problem is that I am reading my list of parameters from a file, so I can't initialize my Parameter directly in global.

**To Reproduce**
I want to reproduce the same result as this : 
```
model model1
global {	
	list<string> district_names	<- ["dist1", "dist2","dist3"];
	string district_name <- district_names[0];
}

experiment Dis {
	parameter "District choice : " var: district_name among: district_names;
}
```

Doesn't work : empty parameter list.
```
model model1
global {	
	list<string> district_names	<- [];
	string district_name <- "";
	
	init{
		district_names <- ["dist1", "dist2","dist3"];
		district_name <- district_names[0];
    }
}

experiment Dis {
	parameter "District choice : " var: district_name among: district_names;
}
```

Doesn't work either :
```
model model1
global {	
	list<string> district_names	<- [];
	string district_name <- "";
}

experiment Dis {
	action _init_ {
		list districts <- ["dist1", "dist2","dist3"];
		string first_dist <- districts[0];
		create model1_model with: [district_names::districts, district_name::first_dist];
	}
	parameter "District choice : " var: district_name among: district_names;
}
```

**Expected behavior**
Parameter list should display my strings list.

**Comment by AlexisDrogoul** [comment]
If your goal is to read a value of a simulation attribute from a file, then you do not need all of this (and you do not need to declare a parameter either, by the way). Something like this would work perfectly:

```
model model1
global {	
	string district_name <- "";
}

experiment Dis {
	list districts <- text_file("districts.txt").contents;
	action _init_ {		
		create simulation with: [ district_name::districts[1]];
	}
}
```

If you want to define a parameter as well, something like this would do:

```
model model1
global {	
	string district_name <- "";
}

experiment Dis {
	list districts <- text_file("districts.txt").contents;
	action _init_ {		
		create simulation with: [ district_name::districts[1]];
	}
	parameter "District choice : " var: district_name among: districts;
}
```
Basically, once you have defined the experiment attribute from the file, you can do whatever you want with it. `districts.txt` is attached to this comment. 
[districts.txt](https://github.com/gama-platform/gama/files/3079621/districts.txt)

**Comment by Damapproject** [comment]
Oh! Thank you very much. It works like a charm 👍
