### ISSUE TITLE
variable with update: is not updated

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2624]
**Describe the bug**
Sorry in advance for this issue, it seems to me so strange that I have the feeling of missing something very basic...

I have a *very* strange "bug". When I run the following model, the variable `l` is not updated.
When we run it step by step we can observe it in the console.
```
model mainModel

global {
	list<string> l <- [] update: People collect each.name;
	
	init {
		create People;
	}	

	reflex tototdjsfds {
		write People collect each.name;
		write l;
	}
}

species People {
		
	reflex takePill {
	//	write "toto";
		write sample(Pill as list);
	}
}

species Pill{
	action use(People p){	}
}

experiment mainExp type: gui { }
```

The result of the execution is:
```
['People0']                // result of write People collect each.name;
[]                               // result of write l;
list<Pill>(Pill) -: []
['People0']
[]
list<Pill>(Pill) -: []
```

**To Reproduce**
Now the strangest part: the variable `l` seems to not be updated because of 2 lines of code:
- `write sample(Pill as list);`
- `action use(People p){	}`

If one of these 2 lines is commented, the variable `l`is correctly updated.

**Desktop (please complete the following information):**
 - GAMA version: 1.8RC2, git
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
Briefly: seems to come from the TopologicalOrderIterator used to sort updatable variables, which documentation states that its results are uncertain if the graph is cyclic... Which is the case here: Pill and People depend on each other. I still have to understand why it appears in this specific setup (and not in others, while these dependencies are quite common) and how to circumvent it...

**Comment by AlexisDrogoul** [comment]
@benoitgaudou I've conducted several tests and the fix seems solid. Basically, it amounts to avoiding adding cycles to the dependency graph when it comes to compute the order in which variables are computed or updated, and it should work
