### ISSUE TITLE
Conditional call to related_to on create and update

### ISSUE THREAD

**Issue by aidevdev** [gama-platform/gama#2625]
Hello, 
I have a graph topology with many (1000s) nodes but not many edges (100s). I read in two files, with nodes and edges. These are just CSV files where nodes have an ID and edges have to/from IDs. 

I load nodes with `create node_agent from:csv_file()` where agent is a 
`species node_agent parent: graph_node edge_species: edge` 
Edges are read into a map for quick reference in the `related_to` method. 

However, I noticed that related_to is called each time a node_agent is read in from a CSV file and whenever an update is made. This means it is called 1000^2 times, once for each node-pair. 

Can I control when related_to is called, and for which node? 
Thanks

**Comment by AlexisDrogoul** [comment]
This is precisely the role of this callback function to be invoked each time a node is added. If you don't want it to be called each time, but only when you have loaded/created all your nodes first, which I can understand, then you have to build your graph manually (i.e. creating the graph, adding all the nodes and creating edge agents for each pair in your map), making sure your node species does not derive from graph_node...

**Comment by AlexisDrogoul** [comment]
Just to note: you can perfectly control, in your own code, whether or not `related_to` should be run or not. For instance, you can add a boolean attribute `run_related`, set its value accordingly and use it at the beginning: e.g. `if !run_related {return false;}`. The call will be issued, but it won't take too much time. 
I close this issue on this advice. Feel free to reopen if you think it deserves more attention.
