### ISSUE TITLE
Problems using network (e. g. Mqtt) with other applications

### ISSUE THREAD

**Issue by thmensing** [gama-platform/gama#2626]
Since v1.8 using network - I'm speaking of **MQTT** - seems to work different? As you changed the examples code from localhost to **GAMA demo server**, using mqtt to third party applications (I'm using **Unity**) works but with GAMA demo server only. I tried to change host in GAML to different test servers, as well as to my own one on localhost, but GAMA then won't compile my code right. 
Can you help me out? Or give some details about the demo server's config to be able to copy that?

**Works:**
do connect  with_name:"ping";  // using gama demo server

**Doesn't work since v1.8, but with v1.7:**
do connect to: "localhost" with_name: "ping" (same with iot.eclipse.org or test.mosquitto.org)

Gama keeps saying "Can't connect to..."

Thx in advance!

**Comment by gnoubi** [comment]
Hi,

Did you setup Mqtt brocker such as activemq? If you did, did you modify default password ?

Best
Nicolas

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by benoitgaudou** [comment]
Dear,

I remember that there was an issue in the GAMA 1.8RC2 on this point and
that it has be fixed some times ago.

I just tried with the code source version of GAMA and it works with an
ActiveMQ.

Could you try the coutinuous built version of GAMA (or even the source code
version if you want) ?
https://gama-platform.github.io/download#

Cheers

Benoit

**Comment by thmensing** [comment]
OK, it works with the RC2 continuos build and localhost broker. Great!!
And thanks for the fast support!

Tested with:
Apache ActiveMQ 5.15.9
Unity 2018.3.9
