### ISSUE TITLE
GAML reference does not support copy-paste

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2627]
**Describe the bug**
The GAML Reference toolbar (on top right) does not support copy paste of text.

**To Reproduce**
1. Copy a text (ctrl + C or CMD + C)
2. Try to paste some text in GAML Reference toolbar.
3. Nothing is pasted.

**Desktop (please complete the following information):**
 - OS: OSX
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Should be fixed by the next commit. Might be necessary, in the developer version, to resynchronise the product with the plugins.
