### ISSUE TITLE
opengl display and Ubuntu - error (with Eclipse 2019-03)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2628]
**Describe the bug**
Opengl display does not work.

log (with the error)
```

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

libEGL warning: DRI2: failed to authenticate
!SESSION 2019-05-02 14:58:48.995 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_201
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Framework arguments:  -product msi.gama.application.product --launcher.defaultAction openFile --launcher.GTK_version 2
Command-line arguments:  -product msi.gama.application.product -data /home/pataillandie/eclipse-workspace_2019/../runtime-gama.product -dev file:/home/pataillandie/eclipse-workspace_2019/.metadata/.plugins/org.eclipse.pde.core/gama.product/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog -data @noDefault --launcher.defaultAction openFile --launcher.GTK_version 2

!ENTRY org.eclipse.e4.ui.workbench.swt 4 2 2019-05-02 14:59:11.085
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench.swt".
!STACK 0
java.lang.ExceptionInInitializerError
	at com.jogamp.opengl.swt.GLCanvas.<init>(GLCanvas.java:349)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface$1.<init>(SWTOpenGLDisplaySurface.java:141)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface.createCanvas(SWTOpenGLDisplaySurface.java:141)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface.createAnimator(SWTOpenGLDisplaySurface.java:128)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface.<init>(SWTOpenGLDisplaySurface.java:114)

(...)

Caused by: com.jogamp.nativewindow.NativeWindowException: java.lang.NoSuchFieldException: GTK_VERSION
	at com.jogamp.nativewindow.swt.SWTAccessor.<clinit>(SWTAccessor.java:203)
	... 146 more
Caused by: java.lang.NoSuchFieldException: GTK_VERSION
	at java.lang.Class.getField(Class.java:1703)
	at com.jogamp.nativewindow.swt.SWTAccessor.<clinit>(SWTAccessor.java:183)
	... 146 more
```

**To Reproduce**
Just a run a model with an opengl display

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.5 LTS 64 bits
 - PC Model: Intel® Xeon(R) CPU E5-1650 v4 @ 3.60GHz × 12 ; Quadro K420/PCIe/SSE2
 - GAMA version: git (date : 2/05/2019)
 - Java version: Oracle : 1.8.0_201
 - Graphics cards / Display system: Quadro K420/PCIe/SSE2

**Additional context**
It was working before using the last version of Eclipse (2019-03 (4.11.0)).

**Comment by AlexisDrogoul** [comment]
Well...we're not alone. 

1. http://forum.jogamp.org/com-jogamp-opengl-swt-GLCanvas-does-not-work-with-Eclipse-4-8-under-Linux-td4039229.html
2. https://forum.jogamp.com/bugzilla/show_bug.cgi?id=1362

The good news here is that the Bugzilla forum for JOGL is reopened (https://forum.jogamp.com/bugzilla/buglist.cgi?bug_status=__open__&no_redirect=1&order=Importance&query_format=specific) and that the production of beta versions for the 2.4.0 version of JOGL has resumed (see for instance https://jogamp.org/deployment/autobuilds/master/jogl-b1483-1483/). 

So it should be interesting to test if this new version solves this bug and #2472 on Linux.

**Comment by AlexisDrogoul** [comment]
Actually, we'll better test this with the following build : http://jogamp.org/deployment/archive/master/gluegen_916-joal_642-jogl_1483-jocl_1122/jar/

The interesting files (to replace the previous libraries and the `jog amp-fat.jar`) to pick up in this build are: 
```
gluegen-rt-natives-linux-amd64.jar
gluegen-rt-natives-macosx-universal.jar
gluegen-rt-natives-windows-amd64.jar
gluegen-rt.jar
jogl-all-natives-linux-amd64.jar
jogl-all-natives-macosx-universal.jar
jogl-all-natives-windows-amd64.jar
jogl-all.jar
```
Can't test it right now, as it takes forever to download.

**Comment by AlexisDrogoul** [comment]
Tested it. The substitution works like a charm... Except that the initial display (size and position of the center of the world) is completely false for all models on macOS (and probably on Windows/Linux too). 

<img width="638" alt="image" src="https://user-images.githubusercontent.com/579256/57085017-9571ee00-6d25-11e9-922f-08e412e39875.png">

So we need to fix this before thinking about using this new version of the library... @nghi, since you like experimenting, can you confirm that the scaling bug is also present with these new libraries on Windows ? Thanks !

**Comment by hqnghi88** [comment]
Dear,
I replaced the files 
![image](https://user-images.githubusercontent.com/6105384/57086952-f52fb100-6cb3-11e9-840d-f49b562598c8.png)
but it seems i dont have the mispositioning issue on my win. Do i need to replace jogamp-fat? where is the right link then?

**Comment by AlexisDrogoul** [comment]
Well, here is the contents of my plugin with the new libraries (no more jogamp-all.jar).
<img width="261" alt="image" src="https://user-images.githubusercontent.com/579256/57116972-bfa5c900-6d82-11e9-8844-e103fd9a812c.png">
And my `MANIFEST.MF` file. 
[MANIFEST.MF.zip](https://github.com/gama-platform/gama/files/3140469/MANIFEST.MF.zip)

**Comment by AlexisDrogoul** [comment]
I think the problem comes from this commit on jogl: https://github.com/sgothel/jogl/commit/ca7f0fb61b0a608b6e684a5bbde71f6ecb6e3fe0

The sizes passed to reshape() in JOGLRenderer are now systematically doubled when using a Retina display (and probably other HiDPI screens).

**Comment by AlexisDrogoul** [comment]
OK. I have the fix for the 2 problems (Ubuntu + wrong size display on macOS). I cant unfortunately test it right now on Windows. @hqnghi88 do you have the same issue than on macOS ? Waiting for your comment before rolling out the new version + libraries.

**Comment by hqnghi88** [comment]
wait for me 15 mins, i have a strange phenomenon when used your manifest. no display shown out. but may be my fault.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 : maybe you have to change the build.properties file accordingly ? 

i.e. 

```
source.. = src/,\
           gaml/
output.. = bin/
bin.includes = META-INF/,\
               plugin.xml,\
               .,\
               gluegen-rt-natives-linux-amd64.jar,\
               gluegen-rt-natives-macosx-universal.jar,\
               gluegen-rt-natives-windows-amd64.jar,\
               gluegen-rt.jar,\
               jogl-all-natives-linux-amd64.jar,\
               jogl-all-natives-macosx-universal.jar,\
               jogl-all-natives-windows-amd64.jar,\
               jogl-all.jar
jre.compilation.profile = JavaSE-1.8

```

**Comment by hqnghi88** [comment]
Thanks, but no needs for build.properties as i missed copy the new jogl-all.jar. So with the set of new jar in yours ss, i confirm that it work on gamaruntime (eclipse 19-03) on non-hdpi win.

**Comment by AlexisDrogoul** [comment]
And do you have the possibility to test on HiDPI Windows as well ?

**Comment by hqnghi88** [comment]
I can try a customized resolution for hidpi on a pc but in 2 hours later.

**Comment by AlexisDrogoul** [comment]
All right. So let me commit the current version first, so that others can also test the fix(es). I will restrict it to macOS for the moment.

**Comment by ptaillandier** [comment]
Hi,

I tested the commit (just did a pull - did I need to do something more?) on
my Windows HDPI computer and it works.
Patrick

Le ven. 3 mai 2019 à 08:34, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
@ptaillandier can you test it on Ubuntu as well ? (to verify the first issue, w. and w/o HiDPI if you can)

**Comment by hqnghi88** [comment]
![Untitled](https://user-images.githubusercontent.com/6105384/57130151-d2d88900-6dc2-11e9-8aef-c3a29c4a61ac.png)
obviously work on a virtual HiDPI win. I dont have ubuntu now, i 'll setup one for CC tonight.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 @ptaillandier As soon as it is verified on Windows and Ubuntu (HiDPI and non-HiDPI screens), we can close this one. It's working w/o problems on macOS now.

**Comment by hqnghi88** [comment]
ubuntu 19 non-hidpi is ok. Cannot have an ubuntu hidpi i dont see a chance :(
