### ISSUE TITLE
GAMA DTW results do not match with R results

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2629]
**Describe the bug**

I tested the DTW algorithm implemented in GAMA. See the following:

```
float var1 <- dtw([32.0,5.0,1.0,3.0],[1.0,10.0,5.0,1.0]); 	
write " " + var1;
```

The result provided is `38.0`.

I compared with the R implementation of the algorithm with the following lines:
```R
install.packages("dtw")
library(dtw) 

r<-c(32.0,5.0,1.0,3.0) 
s<-c(1.0,10.0,5.0,1.0) 

dtw(r,s)$distance
```

The result provided by R is `42.0`.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Normal. **42** IS the ultimate answer to everything 😄

**Comment by ptaillandier** [comment]
In fact, 42 is correct, but 38 as well.... Indeed, it depends on the step patterns used. 
In R, by default, the step pattern used is symetric2 (see https://rdrr.io/cran/IncDTW/man/dtw.html) while in GAMA, the step pattern used is symetric1.
You can test in R using: 
r<-c(32.0,5.0,1.0,3.0) 
s<-c(1.0,10.0,5.0,1.0) 
dtw(r,s, keep.internals = TRUE,  step.pattern=symmetric1)$distance

The answer is 38 and not 42.... For the moment, GAMA only includes step pattern symetric1, but if you want to have more step pattern, feel free to open a new enhancement issue.
I modified the documentation to clarify that.
