### ISSUE TITLE
[Unix] OpenJDK 11 doesn't work

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2635]
**Describe the bug**
The GAMA software crash when launching an experiment with OpenJDK 11 (default one on Unix system)

**To Reproduce**
1. Having 11/default unix OpenJDK 
`sudo apt install default-openjdk`
2. Open any Gama file
3. Launch any experiment (bash, gui, etc)

**Expected behavior**
Having the experiment running

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS x86_64 and Manjaro Illyria (18.0.4) x86_64
 - GAMA version: git
 - Java version: 
```
$ java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)
```

**Additional context**
Everything works properly with OpenJDK 8 (on both OS)

**Comment by hqnghi88** [comment]
well, not OPEN jdk, and not even 9 yet so openJDK 11 is surely not working.

**Comment by AlexisDrogoul** [comment]
As it is clearly stated in the documentation that GAMA will only work with JDK8, I close this issue, not totally unexpected ! (see https://github.com/gama-platform/gama/wiki/Installation)
