### ISSUE TITLE
Possibility to set CAMERA_PRESET as a facet with GAML

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2640]
Currently it's possible to control the camera preset using the interface with Toggle Side Controls however we cannot do it using a facet.

An enhancement could be to be able to use it as a facet (right now it's possible to have the same effect as the presetCamera by specifying the camera_pos, look and up) 

Possible syntax 

`````
presetCamera: "fromTop"
`````

**Comment by AlexisDrogoul** [comment]
Now tracked in #1878.

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0. See #2757 also.

**Comment by AlexisDrogoul** [comment]
The `display` statement now sports a `camera:` facet that can accept constants designating preset cameras (`#from_front`, etc.) or cameras defined in the body of the display. If it not defined, the camera named `default` is chosen. Either from the global preferences (in the `Displays` section) or in the display body (with `camera default ...`).
