### ISSUE TITLE
Wiki example for control:user_only - Don't know how to run the example code

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#2647]
Hello,
I have tried to run the example in from the wiki of control user_only. There are errors on 
advanced_user_control variable but I don't know howto fill the missed variable.

Please take a look on the attached model.
Thank you,
Quang

/***
* Name: NewModel
* Author: tcquang
* Description: A model dedicated to run unit tests
* Tags: Tag1, Tag2, TagN
***/

model NewModel

global {
	/** Insert the global definitions, variables and actions here */

	init {
		
		create user;
	}
	
}

species user control:user_only {
   user_panel default initial: true {
      transition to: "Basic Control" when: every (10) and !advanced_user_control;
      transition to: "Advanced Control" when: every(10) and advanced_user_control;
   }
   
   user_panel "Basic Control" {
      user_command "Kill one cell" {
         ask (one_of(cell)){
            do die;
         }
      }
      user_command "Create one cell" {
        create cell ;
      } 
      transition to: default when: true;
   }
   user_panel "Advanced Control" {
      user_command "Kill cells" {
        user_input "Number" returns: number type: int <- 10;
        ask (number among cell){
           do die;
        }
      }
      user_command "Create cells" {
        user_input "Number" returns: number type: int <- 10;
        create cell number: number ;
      } 
      transition to: default when: true;
   }
}
species cell{
	aspect default{
		draw circle(1.0) color: #orange ; 
	}
	
}

experiment NewModel type: gui {
	/** Alternatively or in addition, you can insert here tests definitions */
	output {
		display user_only_example{
			species cell;
		}
	}
	
}

https://gama-platform.github.io/wiki/ControlArchitecture.html

**Comment by benoitgaudou** [comment]
The full model is provided in the GAMA model library:
User Control Architecture.gaml

I updated the documentation to mention it.
