### ISSUE TITLE
Zoom level set to 1.0 by default in Opengl

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2653]
Open question (just to be sure we are on the same page)

The zoom level per default (after a double click) is set to 1 (instead of 1.5 before). 

Feature or bug? for some model especially in 3D 1.0 can be to close as some building might be out of the screen

**Comment by AlexisDrogoul** [comment]
I don't understand the question: which zoom level ? To my knowledge, it has always been reset to 1.0 with a double-click. Beyond that, there is an internal zoom factor, which is represented by an initial z-factor in camera, set to 1.46 when the environment is drawn and 1.2 otherwise.

**Comment by AlexisDrogoul** [comment]
Closing this for now on. The initial zoom factor can always be turned at one point into a parameter.
