### ISSUE TITLE
Init in experiment not taken in account in Headless

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2654]
**Describe the bug**

The code written  inside an  ````init````section of an  ````experiment````  is not taken in account in headless

**Comment by AlexisDrogoul** [comment]
Not `taken into account`? Not compiled ? Not run ? Is it also the case for the `_init_` action ?

**Comment by agrignard** [comment]
The code compiles but is not executed.

Also the case with   ```` _init_````

**Comment by gnoubi** [comment]
bug fixed. can you try?

**Comment by agrignard** [comment]
@AlexisDrogoul or @gnoubi can you test it with this model?

[cityIO_Gama.zip](https://github.com/gama-platform/gama/files/3155454/cityIO_Gama.zip)
