### ISSUE TITLE
remove_duplicates for matrix return a list

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#2667]
Hello,
In documentation, I found that remove_duplicates() can remove  duplicate row of a matrix. But it returned a list of values without duplicate.
		matrix mat1 <- matrix([["c11","c12","c13","c13"],["c21","c22","c23","c23"]]);  
		write mat1;
		write remove_duplicates(mat1);
Thank you,
_________________

c11;c21
c12;c22
c13;c23
c13;c23

**Expected behavior**
c11;c21
c12;c22
c13;c23

The result:
['c11','c21','c12','c22','c13','c23']

**Comment by AlexisDrogoul** [comment]
What about changing this operator so that it returns a list (with only one occurence of each) of the elements present in the matrix ? @tcquang @benoitgaudou @ptaillandier

**Comment by benoitgaudou** [comment]
I agree and change the doc in accordance.

**Comment by benoitgaudou** [comment]
closed by 2667
