### ISSUE TITLE
Possibility to have an infinite simulation in headless

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2668]
**Describe the solution you'd like**
Right now we need to give a finalStep condition in headless to finish the simulation. 

**Describe alternatives you've considered**
Would it be possible to run infinite simulation without finalStep

**Comment by agrignard** [comment]
Just for information with ```` finalStep="#infinity" ```` I get an error

**Comment by AlexisDrogoul** [comment]
Implemented in 6c476898756fad1abd8eb1f8d299bb6673b7aef1

**Comment by gnoubi** [comment]
use the code "INFINITY" in the finalStep attribute.

**Comment by gnoubi** [comment]
tested...
