### ISSUE TITLE
Enhancements for 'step' facet in ODE solver (step value is too high, name ambiguity)

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2669]
The step for integration in ODE solver is set to 1 by default for fixed steps methods. This is too high and does not allow enough precision. In maple for example, step=min((Tf-T0)/3, 0.005), when the problem is solved from T0 to Tf.

I think defining a default absolute value of 0.005 would be irrelevant in Gama. If the time scale in the simulation is too high (step=#1day), then it will result in too many integration steps.

Furthermore, I think the name 'step' is ambiguous, since it is the same name used to describe the duration of one cycle in the simulation.

I suggest the followings:
- if you think it is better to remove ambiguity in the name, change it from 'step' to 'stepsize' as in maple 
- make the default value small enough and relative to the simulation step. Defaut stepsize = 0.005 * step (where step here refers to the simulation step)
- change the documentation: 'stepsize (float): specifies the integration step for fixed step methods.
 (default value: 0.005*step)'

**Comment by AlexisDrogoul** [comment]
Implemented in 1290296359b8979ad946903d7c466b1243d773e4
