### ISSUE TITLE
Mismatch between the scale display on the overlay and the real size of the world in OpenGL

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2671]
The scale of the legend is not coherent with the real size of the world. Much more slower in this case (27m and should be closer to 100m) 
OpenGL is wrong
<img width="1920" alt="Screen Shot 2019-05-08 at 16 08 22" src="https://user-images.githubusercontent.com/3928502/57363571-8ec2fb00-71ab-11e9-9d70-08c2123b2f22.png">

Java2D is ok (98m)
<img width="1920" alt="Screen Shot 2019-05-08 at 16 11 18" src="https://user-images.githubusercontent.com/3928502/57363761-f711dc80-71ab-11e9-9b2c-6e9ee85e40a0.png">

Maybe a problem of feet vs meter?

**Comment by AlexisDrogoul** [comment]
Seems to be almost ok now (cf. screenshot). I close this issue, feel free to reopen it (or a new one) with a usecase where it would cause a problem. 

<img width="697" alt="image" src="https://user-images.githubusercontent.com/579256/57979027-b0d93a80-7a41-11e9-86ad-08734cdd2e6c.png">
