### ISSUE TITLE
Layout bug with multi-simulation display 

### ISSUE THREAD

**Issue by jdzucker** [gama-platform/gama#2680]
**Describe the bug**
When a layout is defined for a multi-simluation the screen is divised in more layout

**To Reproduce**

```
/***
* Name: testLayout
* Author: jdz
* Description: 
* Tags: Tag1, Tag2, TagN
***/

model testLayout

global {
	int nb_agents <- 10;


	init {
		create dummy number: nb_agents;
	}
}

//definition a simple species that just move randomly at a given speed
species dummy skills: [moving]{
	
	aspect default {
		draw circle(2) color: #black;
	}
}

experiment main type: gui {
	init {
			create simulation with: [nb_agents:: 5];
		
	}
	output {
		layout horizontal([0::5000,1::4000]) tabs:true editors: false;
		display map {
			species dummy;
		}
	}
}
```

**Expected behavior**
Only two displays should be visible 

**Screenshots**
![image](https://user-images.githubusercontent.com/12623800/57397480-fbafb280-71f6-11e9-8963-a85bbc4dd390.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.4
 - PC Model:  MacbookPro 2018
 - GAMA version: 1.8
 - Java version: 1.8
 - Graphics cards / Display system: 
**Additional context**

**Comment by AlexisDrogoul** [comment]
This issue has been put on stand-by, as using "fixed" layouts with multiple simulations is a bit complicated. The solution -- workaround actually -- is to use a built-in layout algorithm, like `#split` .
