### ISSUE TITLE
Problem with float operator on map

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2686]
**Describe the bug**
In this model go to experiment_urban_growth.gaml line 223 a cast is needed and it should'nt

[NewGAMA1.8Model.zip](https://github.com/gama-platform/gama/files/3160981/NewGAMA1.8Model.zip)

Work
`````
global_happiness[self] <- float((float(neighbours[self])  + float(services[self])  + float(roads[self])  + float(pollution[self]) ) / (4.0));
`````
doesn't work 
`````
global_happiness[self] <- float((neighbours[self]  + services[self]  + roads[self]  + pollution[self] ) / (4.0));
`````

**Comment by AlexisDrogoul** [comment]
Closing this as the model has a number of flaws (`pollution` defined two times, etc.) which make it difficult to understand...
