### ISSUE TITLE
Possibility to define the color of the parameters controlers

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2689]
**Is your request related to a problem? Please describe.**
Right now the color by default of the parameters controller are in green

![Uploading Screen Shot 2019-05-09 at 16.51.43.png…]()

**Describe the solution you'd like**
It would be great to be able to specify another as a global variable possibly in the preferences. 

Why not in a long term having also the possibility to specify the color for each parameter controller

**Comment by agrignard** [comment]
Do we keep the panel in green also or use the same color of the slider (blue) ?

<img width="279" alt="Screen Shot 2019-05-13 at 19 48 49" src="https://user-images.githubusercontent.com/3928502/57622656-4c892780-75b8-11e9-80df-49cd7c7e6eee.png">

**Comment by AlexisDrogoul** [comment]
Blue was a mistake. But I have had some problems with GitHub lately.

**Comment by AlexisDrogoul** [comment]
Now everyone can display hideous UI elements. Enjoy ! I've updated the example model (GUI Interactive Elements) accordingly. 

<img width="291" alt="image" src="https://user-images.githubusercontent.com/579256/57665275-6ca30000-7625-11e9-9eaa-bf064f8e53c5.png">
