### ISSUE TITLE
introduce ?help in interactive console to bring help into console

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2691]
**Is your request related to a problem? Please describe.**
Currently, the search box in GAMA can be used to lookup for operators and hovering over the results would show @doc text in a small purple window. This window can be missed by the user because it does not appear close to the search result and neither does it stay visible for long. Its visibility is subject to mouse hovering on the correct search result. This is inconvenient as is normal tendency to move your mouse towards this purple window or the mouse sometimes moves unexpectedly and we lose this purple window.

**Describe the solution you'd like**
A more common query system such as it exists in matlab, R, python where user can use queries starting with `?` and the query string (usually the method or function required).

So you can write e.g., `?intersects` , `?covers` and press enter, this is parsed as a query similar to the search box and the results of the **exact** match are shown in the interactive console. I would prefer that along with @doc value, @example is also shown. 

I do not request all kinds of wild card queries, but just an exact match. The idea is largely to help users who know the name of the operator, but do not fully remember the number and type of arguments or the return type.

thank you

**Comment by AlexisDrogoul** [comment]
Hi,

I don't clearly see what this enhancement would add to what's already implemented in the console.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/579256/57449145-69a2bb00-7285-11e9-86f5-a47679363624.png">


Can you be more precise ?

**Comment by sriramab** [comment]
Thank you Alexis. I close for now, this works for me.
