### ISSUE TITLE
Seed defined in global is not taken into account, contrary to the documentation

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2693]
A seed defined in global or init is not taken into account, contrary to the documentation:

[https://gama-platform.github.io/wiki/RunSeveralSimulations.html#random-seed](https://gama-platform.github.io/wiki/RunSeveralSimulations.html#random-seed)

**Comment by AlexisDrogoul** [comment]
Please include a small model so that the issue becomes a bit more understandable ! What does "is not taken into account" mean ? In which context ?
