### ISSUE TITLE
Bug on frequency_of on list of int

### ISSUE THREAD

**Issue by jdzucker** [gama-platform/gama#2700]
**Describe the bug**
The frequency_of does not beahve correctly on int

**To Reproduce**
1. In console type  [2,3,4,4,5] frequency_of each.size
2. it responds nil
3. type  [2,3,4,4,5] frequency_of each
4. it says " Error: " 

**Expected behavior**
Should consider them and give a map.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.4
 - PC Model:  MacbookPro 2018
 - GAMA version: 1.8
 - Java version: 1.8
 - Graphics cards / Display system: 

**Additional context**

**Comment by sriramab** [comment]
`[2,3,4,4,5] frequency_of each` works for me as expected.

**Comment by ptaillandier** [comment]
Same for me, it works well, so I close the issue.
