### ISSUE TITLE
GAML additions (operators and statements) defined in the headless plugin are not available in GAMA

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2701]
**Describe the bug**
The headless plugin defines some operators and statements.
(e.g. run,start_simulation...).

Although the headless plugin is loaded at the GAMA launch, the headless operators and statements are not available in a model.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Turns out that `msi.gama.lang.gaml` was exporting its own `gaml.additions` package, preventing the headless plugin (which is directly importing it) to find and load its own additions.
