### ISSUE TITLE
Problem with casting the sum of a row of matrix

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2704]
**Describe the bug**
Is it normal that this syntax make a compilation error?
model NewModel

/* Insert your model definition here */

global{
	init{
	
		matrix<int> a;
		int spop;
		write (spop - (sum(a rows_at 1)));	
	}
}
it make:
Multiple markers at this line
- No operator found for applying '-' to types [int, unknown]
   (operators available for [types [species, agent], types [int,
   matrix], types [int, float], types [int, int], types [point,
   point], types [container, container], types [list, unknown],
   types [point, float], types [geometry, container], type point,
   types [geometry, geometry], type float, type int, types [point,
   int], types [float, matrix], types [geometry, float], types
   [date, date], types [float, float], types [float, int], types
   [rgb, rgb], types [matrix, matrix], types [rgb, int], types
   [map, map], types [map, pair], types [matrix, float], types
   [matrix, int], types [date, float], types [date, int]])
- Unknown action or operator: rows_at

Even with int casted:
		write (spop - int(sum(a rows_at 1)));	
The error is the same 
Multiple markers at this line
- Unknown action or operator: rows_at
- No operator found for applying '-' to types [int, unknown]
   (operators available for [types [species, agent], types [int,
   matrix], types [int, float], types [int, int], types [point,
   point], types [container, container], types [list, unknown],
   types [point, float], types [geometry, container], type point,
   types [geometry, geometry], type float, type int, types [point,
   int], types [float, matrix], types [geometry, float], types
   [date, date], types [float, float], types [float, int], types
   [rgb, rgb], types [matrix, matrix], types [rgb, int], types
   [map, map], types [map, pair], types [matrix, float], types
   [matrix, int], types [date, float], types [date, int]])

**Comment by ptaillandier** [comment]
right operator: row_at (and not rows_at)
