### ISSUE TITLE
csv_file contents type does not depend on the type given in the constructor

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2705]
**Describe the bug**
In the `csv_file` operator, a type can be given. 
As a consequence, it is expected that the content to be a matrix of this type.

In particular, in the following model, as float is given as a parameter, `matrix(my_csv_file)` or `my_csv_file.contents` are expected to be of type matrix<float>, whereas they are of type matrix.

```
	file my_csv_file <- csv_file("../includes/iris.csv",",",float);
	matrix<float> data <- matrix(my_csv_file);
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
There is always the possibility to use 

```
file<float> my_csv_file ... 
```
but it also gives a warning. 

Actually, I don't see any solution there, as file constructors can not be tagged, and so it is impossible to tell which of the arguments can provide the contents type...

**Comment by AlexisDrogoul** [comment]
I've committed what is probably a solution for this problem. Any constructor that accepts a type as a parameter will now consider that it defines the contents type of the file.
