### ISSUE TITLE
triangle vs pyramid

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2707]
Is it possible that the modif of the triangle size has an impact on the pyramid?

That doesn't look anymore exactly like a pyramid? the base is bigger

<img width="1053" alt="Screen Shot 2019-05-11 at 04 06 50" src="https://user-images.githubusercontent.com/3928502/57556917-841e8680-73a2-11e9-8ec7-86873b3734b2.png">

**Comment by sriramab** [comment]
I don’t know if triangle and pyramid are connected but Actually base of triangle has become smaller after the correction

**Comment by sriramab** [comment]
I suggest you use, triangle(base, height ), to get the height you need for your model.

**Comment by AlexisDrogoul** [comment]
Just to close this, I don't observe the same effet in the library of models. 
<img width="530" alt="image" src="https://user-images.githubusercontent.com/579256/57564759-ac76a700-73db-11e9-9765-a75dc9544af7.png">

Do you draw your base yourself ? In that case, effectively, the difference is that you probably need to use some simple trigonometric computations to place the base directly (sqrt(3/2) ? ).
