### ISSUE TITLE
'Java error: nil value detected' with charts with a lot of values

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2712]
**Describe the bug**

Maybe the simplest gama file with an issue...

Running an experiment with with the following code with long simulations eventually ends with a Java error: nil value detected. The error is raised randomly between cycles 50000-60000.

model Issue

experiment simulation type: gui autorun: true {
	output { 
		display LV name: "Time series" refresh: every(1#cycle) {
			chart "Population" type: series memorize: false x_range: 100 {		
					data "data 0" value: 0 color: #blue marker: false;
					data "data 1" value:0 color: #blue marker: false;
					data "data 2" value: 0 color: #blue marker: false;
					data "data 3" value:0 color: #blue marker: false;
			}
		}
	}
}

We tried playing with minimum_cycle_duration, memorize and x_range, but it did not solve the problem.

**Comment by pcaillou** [comment]
Ohhh a nice bug to look at, thanks :)

Philippe

Le sam. 11 mai 2019 à 10:03, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by pcaillou** [comment]
Ok, not a very nice bug…
The simulation is too fast for the chart :)
For example the simulation is at 60000 when the chart is still at 30000, and 30000 charts are waiting to be drawn, a little too much :)

A workaround : 

refresh : every(10)
for the display, for me it works…

Now I will try to find a way to skip the useless chart drawing without that!

Philippe



De : Tri Nguyen-Huu
Envoyé le :samedi 11 mai 2019 10:03
À : gama-platform/gama
Cc : Subscribed
Objet :[gama-platform/gama] 'Java error: nil value detected' with chartswith a lot of values (#2712)

Describe the bug
Maybe the simplest gama file with an issue...
Running an experiment with with the following code with long simulations eventually ends with a Java error: nil value detected. The error is raised randomly between cycles 50000-60000.
model Issue
experiment simulation type: gui autorun: true {
output {
display LV name: "Time series" refresh: every(1#cycle) {
chart "Population" type: series memorize: false x_range: 100 {
data "data 0" value: 0 color: #blue marker: false;
data "data 1" value:0 color: #blue marker: false;
data "data 2" value: 0 color: #blue marker: false;
data "data 3" value:0 color: #blue marker: false;
}
}
}
}
We tried playing with minimum_cycle_duration, memorize and x_range, but it did not solve the problem.

**Comment by AlexisDrogoul** [comment]
Good workaround, I think. I will add this to the model ASAP. And close this issue unless you think it needs more discussion -- @pocaillou, if you come up with a solution for the charts (I've also tried some time ago), it would be very nice !

**Comment by hqnghi88** [comment]
Sorry, i want to adjust with my workaround: 
minimum_cycle_duration<-0.05;
is enough on my machine (not too slow, but still have all data of chart at every cycle).

**Comment by AlexisDrogoul** [comment]
hmmm.. In that case a `synchronized: true` on the display is probably more adapted, no ? In that it ensures that the simulation cannot go faster than the chart...

**Comment by AlexisDrogoul** [comment]
3 workarounds have been proposed so far:

- `display ... refresh: every(10 #cycle) ... `
- `display ... synchronized: true ... `
- `minimum_cycle_duration<-0.05;`

All having the effect of slowing down either the simulation or the display or both. I think we can then close this issue as there are no "magical" formulae that would allow to draw all points every time (which is quite unfortunate !)
