### ISSUE TITLE
internal update not working

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2714]
HI, 

I used the help>update menu. It worked well on GAMA that installed during coding camp. But on my office computer with gama from march, could not update, after accepting all conditions, the dialog disappears after clicking "install anyway"

**Comment by sriramab** [comment]
I notice it says , insufficient access privileges to apply this update - on the Available updates dialog.
. Never seen this before. Any changes to access related files? How do i resolve this. 

If this protection is applied, it is not stopping user to choose - select all or deselect all . The installation continues and user can keep clicking next next to go through the procedure. If access is  insufficient, shouldn't the installation stop right away?

**Comment by AlexisDrogoul** [comment]
Sorry, which version are you talking about ? And on which environment ?

**Comment by sriramab** [comment]
Mac High Sierra , gama stand-alone

**Comment by hqnghi88** [comment]
which stand-alone please?

**Comment by AlexisDrogoul** [comment]
Do you know when it was produced ? Was it the RC2 ? Another one ? Since March, we have moved to a new version of Eclipse (2019-03) and I'd bet the previous one and new one are considered as not compatible anymore in the update functionality...

**Comment by sriramab** [comment]
![Gama Installation Details 2019-05-13 17-23-02](https://user-images.githubusercontent.com/12668606/57633459-ebefef80-75a3-11e9-9ebf-65bae8df6d95.png)

**Comment by sriramab** [comment]
This version in the pic no longer updates

**Comment by AlexisDrogoul** [comment]
The reason is provided above (different version of Eclipse backing GAMA). And we cant do anything about this, unfortunately. I suspect the problem will raise again if we update Eclipse in the future. I close the issue for now on, feel free to reopen if you think you have a solution !
