### ISSUE TITLE
casting problem with pair when using rotated_by 

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2715]
**Describe the bug**

A wrong casting is thrown when using specific gama pair in rotated_by. rotated_by expects a gamaPair float::point. When the user give the hard coded int::point, a cast exception is thrown. However if you give a GamaPair as a variable, with a hardcoded int (such as pair<float, point> good_pair2 <- 1::{1,0,0}), it works.

**To Reproduce**
````

/**
 *  essai
 *  Author:
 *  Description: 
 */

model essai
 

global{
	pair<float, point> good_pair <- 1.0::{1,0,0};
	pair<float, point> good_pair2 <- 1::{1,0,0};
	pair<int, point> bad_pair1 <- 1::{1,0,0};
	
	init{
		create leaf;
	}
}

species leaf {

   aspect bad {
   		draw circle(50) at: {50,50,0} color: #grey;
		draw circle(10) rotated_by(good_pair) at: {50,75,2} color: #yellow border: #yellow;
		draw circle(10) rotated_by(good_pair2) at: {75,50,2} color: #red border: #red;
		draw circle(10) rotated_by(bad_pair1) at: {25,50,2} color: #green border: #green ;
		draw circle(10) rotated_by(1::{1,0,0}) at: {50,25,2} color: #blue border: #blue;
   }
   
   aspect good {
   		draw circle(50) at: {50,50,0} color: #grey;
		draw circle(10) rotated_by(good_pair) at: {50,75,2} color: #yellow border: #yellow;
		draw circle(10) rotated_by(good_pair) at: {25,50,2} color: #green border: #green;
		draw circle(10) rotated_by(good_pair) at: {75,50,2} color: #red border: #red;
		draw circle(10) rotated_by(good_pair) at: {50,25,2} color: #blue border: #blue;
   }
}

experiment simulation type: gui { 

 	output { 
 		layout #split;
		display good type:opengl {
	        species leaf aspect: good;
	    }		
	    display bad type: opengl{
	    	species leaf aspect: bad;
	    }
	}
}


	





````
In the bad display, the blue and the green circle are not displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/18676913/57631042-06739a00-759f-11e9-958a-b6ecd3c6650e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS High Sierra]
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: [e.g. git, 1.7.1, etc.]
 - Java version: [e.g. 1.8]
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by AlexisDrogoul** [comment]
This behaviour is normal, as far as I can tell, as the second solution, by using a variable, casts the value to an acceptable type (float::point) while the first obviously doesn't take this possible type into account.

**Comment by tnguyenh** [comment]
OK, what bothered me is that usually in Gama, when you write an int instead of a float, you get a warning. Writing rotated_by(20::{1,0,0}) instead of rotated_by(20.0::{1,0,0}) seems to be a natural mistake to me, so I think this should be fixed, but a warning would be fine.

If I understood well, this may be difficult in that case because of the type erasure with something like GamaPair<Double, GamaPoint> in Java. So I just used the type GamaPair instead, and casted the key as a Double, and it works with both integers and floats. But I am not sure it is the proper way to fix this issue for Gama...

**Comment by AlexisDrogoul** [comment]
I don't think there is a _proper_ way to achieve this. Probably the best would be to pass an IExpression to the different variants of rotated_by and have a custom validator that emits a warning or directly casts the pair. But yours is correct as well, with maybe a safer way to handle the casting, like for instance: `GamaPair<Double, GamaPoint> argument = (GamaPair<Double, GamaPoint>) GamaType.from(Types.PAIR, Types.FLOAT, Types.POINT).cast(scope, rotation, null, false);`. A bit long but safe !
