### ISSUE TITLE
Continuous build error : mistake version of "gama-headless.*" files

### ISSUE THREAD

**Issue by gnoubi** [gama-platform/gama#2716]
**Describe the bug**
The continuous build version of gama contain an old version of the gama-headless.sh or bat file. 

**To Reproduce**
1. Go to 'headless directory in command line
2. sh gama-headless.sh
3. see
sh gama-headless.sh samples/predatorPrey.xml truc
gama-headless.sh
******************************************************************
* GAMA version 1.8.0                                           *
* http://gama-platform.org                                       *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
******************************************************************

**Expected behavior**
* (c) 2007-2019 UMI 209 UMMISCO IRD/SU & Partners              * 
******************************************************************
as mention in the msi.gama.headless plugin (ext/unix/gama-headless.sh file)

**Comment by hqnghi88** [comment]
well, the script which imported in relase are at ummisco.gama.product/extraresources/headless/ , not directly in headless plugin, so i copied and make a release could you retry the continuos build?
