### ISSUE TITLE
Test feature make GAMA hang a while without any message

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2717]
**Is your request related to a problem? Please describe.**
Use the test feature by clicking on  "Run all tests" button.
All the tests are executed that make GAMA hang for a while (10 - 30s) not only because the network tests but also the number of tests. 
**Describe the solution you'd like**
A solution to separate the GUI threads avec le execution thread of the tests , for that, user can continue using the GUI

**Comment by AlexisDrogoul** [comment]
Fixed in the last commit. Problem is (1) the network tests are waaaayyy too long (they introduce pauses), so we need to find a way to run them in parallel if possible; (2) the user can mess with the GUI while the tests are running, and I can't guarantee the result...
