### ISSUE TITLE
inconsistency between release and GitHub file

### ISSUE THREAD

**Issue by gnoubi** [gama-platform/gama#2719]
**Describe the bug**
there  is a file inconsistency in the produced release.

ummisco.gama.product/extraresources/sample/roadTraffic/model7.gaml in the release is different than the GitHub

obtain file : 

entities {
	species building {
		string type; 
		rgb color <- rgb('gray')  ; 
		aspect base {
			draw shape color: color ;
		}
	}

expected :
	species building {
		string type; 
		rgb color <- rgb('gray')  ; 
		aspect base {
			draw shape color: color ;
		}
	}

**Comment by hqnghi88** [comment]
Sorry, i did not see "inconsistency" but old/out-date on both git and release (continuous). Should it be the model 7 in Incremental tutorial? I reup and make a release now.
![image](https://user-images.githubusercontent.com/6105384/57851504-f19b3e80-780a-11e9-8047-d89a7e01b238.png)

**Comment by gnoubi** [comment]
not in incremental tutorial but the model contained by the extraresources/headless/samples/ folder of gama.product plugin

you can see inconsistency

**Comment by gnoubi** [comment]
maybe I make a mistake...

**Comment by hqnghi88** [comment]
fixed in continuous build 23fea49
