### ISSUE TITLE
closest_to operator returns nil value when the shape of the environment is changed dynamically

### ISSUE THREAD

**Issue by gnoubi** [gama-platform/gama#2720]
**Describe the bug**
sometime, the operator "closest_to return nil value even if agents are located in the world. 

	reflex truc
	{
		Follow c <- Follow closest_to self;
		write c;
	}
sometime c = nil whereas Follow agents are located in the space

**To Reproduce**
run the attached model
[test_gama.zip](https://github.com/gama-platform/gama/files/3188437/test_gama.zip)

**Expected behavior**
a value different than nil

**Comment by sriramab** [comment]
May be related to #2699 ?

**Comment by ptaillandier** [comment]
Hi,

It is due to the fact that you define the geometry of the world in the init... shape <- square(1#km).
Was it working with an older version of GAMA? If yes, it is maybe due to the fix of issue #2586

**Comment by AlexisDrogoul** [comment]
It seems that, as soon as the shape of the world is modified, it produces such errors. As if the QuadTree or similar structures were not updated correctly. 

For instance: 

```
	geometry shape <- square(1#km);

	init{
		 shape <- square(2#km);
		create Human number:20;
		create Follow number:20;
	}
```

Produces less `nil` but still some.

**Comment by AlexisDrogoul** [comment]
I've added (again ?) a warning when the shape of the world is to be changed dynamically in a model, advising the user to redefine the attribute instead. I've also changed 3 models which were exhibiting this warning in the library: Radiohead and two network related ones.
