### ISSUE TITLE
Output console of headless very verbose

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2721]
**Describe the bug**
When running an headless model from the terminal it is writting one point every iteration I guess which quickly make something not really nice from a terminal user point of view:

<img width="1440" alt="Screen Shot 2019-05-16 at 23 58 44" src="https://user-images.githubusercontent.com/3928502/57889975-92ebba00-7836-11e9-8c01-7ed646123051.png">

Anyway to make the headless more quiet in term of output? 

 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by AlexisDrogoul** [comment]
When using a Terminal, I think you can easily divert the output by adding `> /dev/null 2>&1` to your command. So it's not really a GAMA issue !

**Comment by hqnghi88** [comment]
one more thing, i think Nico has disable all stream out unless you specify -c or -v ,did you ? may be i missed
