### ISSUE TITLE
Equal object contract violation using mirror agent with OpenGL and unsynchronized display

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2722]
**Describe the bug**
When a mirror agent follow the location of its "target" on a OpenGL display, Gama throw an error claiming that equal agent should have the same Hashcode

**To Reproduce**
1. Go to Toy Models > Multi-level Data Analysis > Graph from bug
2. Run the model for hundreds of simulation step
3. When display is synchronized, you have no error

**Expected behavior**
No error

**Screenshots**
<img width="1680" alt="Capture d’écran 2019-05-17 à 17 57 50" src="https://user-images.githubusercontent.com/13599506/57923730-4c956a00-78cd-11e9-85ba-281bafd04b59.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Actually, the problem came from the way the aspects were coded in this model. One of them was directly modifying the shape of the agent, creating all the conditions, when not synchronised, for concurrent accesses...
