### ISSUE TITLE
Draw a geometry, without color: (java2D)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2724]
**Describe the bug**
Consider a species with an aspect, that contains a draw of a geometry without the color: facet, BUT with the border: facet. When this species is displayed in a Java2D display, whereas all the agents seem to be drawn with the color of the border, the first agent seems to have a different color. See below the model and snapshot.

```
model NewModel

global {
	init {
		create people number: 10;
	}
}

species people {
	aspect sq {
		draw circle(10.0) border: #darkblue;
	}
}

experiment exp2D type: gui  {	
	output {		
		display d type: java2D {
			species people aspect: sq;
		}
	}
}
```

**Screenshots**

<img width="889" alt="Capture d’écran 2019-05-18 à 12 02 28" src="https://user-images.githubusercontent.com/1555274/57964757-d47a8300-7964-11e9-9e17-02b001301cc6.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Actually, the draw here was contradictory (draw something solid, color  unknown !), and GAMA did not really play well with this contradiction. Since the preferences define a default solid color for such cases, it is now applied by default for solid geometries without colors or textures
