### ISSUE TITLE
Draw a geometry, without color: facet in an OpenGL display with transparency

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2725]
**Describe the bug**
Consider a species, having an aspect, drawing a geometry without the color facet: *BUT with the border: facet* (without the broder: the issue does not appear).
When it is displayed in an opengl display with a transparency, only the first agent appears (more precisely, many agents appear, but disappear quickly).

See the model below and the screenshot.

```
model NewModel

global {
	init {
		create people number: 10;
	}
}

species people {
	aspect sq {
		draw circle(10.0) border: #darkblue;
	}
}

experiment expOpengl type: gui  {	
	output {		
		display d type: opengl {
			species people aspect: sq transparency: 0.5;
		}
	}
}
```

**Screenshots**
<img width="784" alt="Capture d’écran 2019-05-18 à 12 05 07" src="https://user-images.githubusercontent.com/1555274/57964804-a5184600-7965-11e9-9a42-7fa43591eed6.png">

Note that when we right-click on the agents, some other agents appear:
<img width="916" alt="Capture d’écran 2019-05-18 à 12 05 23" src="https://user-images.githubusercontent.com/1555274/57964819-bd886080-7965-11e9-95ad-093240b1aa63.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Same problem here as in #2724. This contradictory draw statement led OpenGL into a funny state... It is now fixed.
