### ISSUE TITLE
draw text with perspective: true does not seem to take into account anchor (in opengl)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2726]
**Describe the bug**
In an `aspect`, when drawing some text with the `perspective:` facet set to true, it seems that the value given to the `anchor:` facet is not taken into account.

As an example, when we look at the model : GAML Syntax / Species definition / Aspects.gaml,
and in particular, in the following `aspect`, the only difference comes from the value of the `perspective:` facet. 
```
	aspect simple_text {
		draw "Agent: " + name + "(rotate!)" at: location + {0,8,0} color: #green font: font("Arial",10,#bold) perspective: false anchor: #bottom_center;
		draw "Agent: " + name at: location + {0,6,0} color: #blue font: font("SansSerif",15,#italic) perspective: true anchor: #bottom_center;		
	}
```

But the result is different:

<img width="224" alt="Capture d’écran 2019-05-19 à 11 22 07" src="https://user-images.githubusercontent.com/1555274/57977704-5ed7eb00-7a28-11e9-817e-d0e5f57e79d2.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Will put it in the doc. anchor: only works with perspective: true in OpenGL.
