### ISSUE TITLE
Model Comodel Example (Populations Mutated).gaml throws a warning

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2729]
**Describe the bug**
Run the model named: Comodel Example (Populations Mutated).gaml in Modeling / Model coupling / Co-Prey Predator.

After few cycles (~100 steps), a warning is throwed: "Cannot evaluate location as the target agent is dead".

<img width="557" alt="Capture d’écran 2019-05-20 à 15 17 25" src="https://user-images.githubusercontent.com/1555274/58006493-65db2800-7b12-11e9-9cd0-0cd61a380015.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
I cant reproduce it. I've tried many different configurations, but cant reproduce it. The only bad practice I've found in the model is the console writing in a graphics, but it doesn't explain why you get the warning.

**Comment by hqnghi88** [comment]
Use preference "Show error in display" will reproduce this issue.
