### ISSUE TITLE
seed not initialized with GUI 

### ISSUE THREAD

**Issue by gnoubi** [gama-platform/gama#2732]
**Describe the bug**
when a seed is defined in the init block of the experiment. It is never used to load the simulation

**To Reproduce**
experiment myModel type:gui {
	init
	{
		self.seed<- 1.0;
	}
	output {
	}
}

**Comment by AlexisDrogoul** [comment]
It is not a bug -- the seed defined in the experiment is different from the one defined in the simulation. First, when you run `init` in the experiment, it is executed *after* the default simulation has been created. Second, `self.seed` refers here to the `seed` of the `experiment`, not the `seed` of this simulation. 

So if you want to change it, either you define it as the initial value of the experiment's seed (this value will be passed to its simulations by default), or you define it in the simulations' own `init` block. 

e.g. 

```
experiment myModel2 type: gui {
	
	float seed <- 100.0;

	init {
		write simulation.seed;
	}

} 
```

or 


```
model NewModel

global {
	init {
		seed <- 100.0;
	}
}


experiment myModel2 type: gui {
	

	init {
		write "Experiment: " + self.seed;
		write "Simulation: " + simulation.seed;
	}

} 
```

**Comment by gnoubi** [comment]
Thanks! I forget that in experiment init we are in experiment context not in a simulation. 

Could a warning help? Ideed, I think it was working in the previous version of gama.

Maybe documentation. I am going to add something about that.

Nicolas 

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906
