### ISSUE TITLE
Errors when displaying multipolygons

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#2734]
Hello,
I have an issue with display with polygon:
Polygon agents are displayed with errors in the GAMA1.8_Continuous_Win_64bits_05.22.19 
compared with the GAMA 1.8 RC2

**To Reproduce**
- Please try the attached model. [display_map.zip](https://github.com/gama-platform/gama/files/3206176/display_map.zip)
- Lunch the experiment 
- Polygons displayed as figure1
![error_map](https://user-images.githubusercontent.com/11825516/58155410-06118800-7c9e-11e9-987e-ca215747b498.png)

**Expected behavior**
Polygons display with out errors ( as in the old version of GAMA  )
![normal map](https://user-images.githubusercontent.com/11825516/58155453-188bc180-7c9e-11e9-86ca-a19de764d8e2.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: GAMA1.8_Continuous_Win_64bits_05.22.19_866a0ab
 - Java version: 1.8
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by AlexisDrogoul** [comment]
It would be easier if you can isolate **one** polygon that doesn't draw well...

**Comment by hqnghi88** [comment]
Here is one polygon
[test.txt](https://github.com/gama-platform/gama/files/3206402/test.txt)

**Comment by AlexisDrogoul** [comment]
The problems only come from multipolygons ??

**Comment by hqnghi88** [comment]
His shp have 11 multipolygons but hard to see if all of them have a hole?

**Comment by hqnghi88** [comment]
using RC2 to display wireframe of extracted data (by write in console) in 2 case:
![image](https://user-images.githubusercontent.com/6105384/58161264-25aead80-7caa-11e9-91c9-b827dc9aa6c8.png)
if seems in currently version, there is some algorithm that fix (or remove) some error in multipolygons. 
Here is model with extracted shapes
[test.txt](https://github.com/gama-platform/gama/files/3206537/test.txt)

**Comment by ptaillandier** [comment]
The problem seems to come from bug fix #2632 that try to "clean"
multi-polygons". If we need a quick fix, We can solve the issue by just not
using multiPolygonManagement method in GAMAGisFIle. I will try to
investigate to find a better solution.


Le mer. 22 mai 2019 à 10:58, HUYNH Quang-Nghi <notifications@github.com> a
écrit :
