### ISSUE TITLE
toolbar: false in display does not work

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2737]
**Describe the bug**
Add `toolbar: false` to a display. Launch the experiment. The toolbar is there (either on top or in the bottom in fullscreen).

**Comment by hqnghi88** [comment]
No, in fact it does.
![image](https://user-images.githubusercontent.com/6105384/58416079-a7d41300-80aa-11e9-8b19-e221f05eab40.png)
You mean in this model?

**Comment by AlexisDrogoul** [comment]
No, actually, I was targeting the toolbar facet of display. But it's fixed now !
