### ISSUE TITLE
Documentation does not show up for skill attributes

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2738]
**Describe the bug**
When you move your mouse over a built-in skill attribute, the pop-up says that there is no documentation while it is documented with annotation in the java code.

**To Reproduce**
1. Go to Plugin Models > Driving Skill > Driving Skill.gaml
2. Pass over maxspeed or lanes variable in init of roads 
3. See that the (very useful ;) documentation is actually in the plugin code

**Expected behavior**
Show what have been written using doc annotation in the plugin 

**Desktop (please complete the following information):**
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Well done @hqnghi88 ! The issue is fixed.
