### ISSUE TITLE
Strange behavior of cmd+R ?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2741]
**Describe the bug**
If I remember well it's possible to run a model by using cmd+R however I notify a strange behavior on my mac

Reproduce it

Open any model 
Run a simulation by clicking on the simulation button (e.g Run Me! in GAMA1.8)
Go back to the modelling perspective
Press cmd+R

or open another model and run it with cmd+R

In my case It seems that the previous instance of the simulation is not closed 

As you can see in this screenshot I have the display of GAMA.18 model and the one of the mondrian City together which is supposed to be impossible to have right? 

In this case I run first GAMA 1.8 normally and the Mondrian City using cmd+R
<img width="1920" alt="Screen Shot 2019-05-28 at 17 47 02" src="https://user-images.githubusercontent.com/3928502/58492232-cac8fa80-8170-11e9-8506-5af2cb05039b.png">

It happens on the GIT version and I have no error in Eclipse

**Comment by AlexisDrogoul** [comment]
I wonder how you arrived there and I cannot reproduce it using the sequence described. As a matter of fact, CMD-R (or CTRL-R) is not intended to run a model but to reload it. 

<img width="155" alt="Gama_Workspace11 - Toy Models:Ants (Foraging and Sorting):models:Ant Foraging gaml - Gama (runtime) 2019-05-29 06-50-26" src="https://user-images.githubusercontent.com/579256/58524787-91859e80-81f3-11e9-81a6-05134d346f90.png">

What is sure, however, is that the keystroke should not be active in the modelling perspective.
