### ISSUE TITLE
Add a model in Visualization called Camera Position.gaml 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2742]
It could be nice to have a minimal model to illustrate the usage of the Camera Position in the new library model.

**Comment by AlexisDrogoul** [comment]
I propose that you list these issues under #1878 if possible !

**Comment by agrignard** [comment]
I have a first model here however two display are still problematic. ````FollowObjectCamera ````because of #2744 and I am not sure about the supposed behavior of th facet ```` focus ```` (I didn't use it for a while) but in the display ````FollowObjectCamera````the behavior is maybe not the one intended

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0
