### ISSUE TITLE
Layout #split with one display doesn't show up

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2743]
**Describe the bug**

Not a big deal and I know it doesn't' make sense to use ````layout #split```` with an experiment that has only one display but I prefer to report it.

So if layout #split is used the display doesn't show up

See this (on Mondrian City adding layout #split), if I go to another app and come back to Gama then the display reappears.

<img width="1920" alt="Screen Shot 2019-05-28 at 18 58 59" src="https://user-images.githubusercontent.com/3928502/58496685-ac67fc80-817a-11e9-9c1c-fb55776fdd74.png">

Would it be possible to raise a warning of there is only one display?

**Comment by AlexisDrogoul** [comment]
Also the case for Java2D displays in multiple views layout (see Ant Foraging>4 Simulations experiment), and it seems only on macOS
