### ISSUE TITLE
Java2D displays do not show up in layouts with tabs: false

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2745]
**Describe the bug**
Create a model with one or several displays, including at least one java2D display. 
Add a layout like, for instance : `layout #split tabs: false;`

**Expected behavior**
All the displays show up.

**Actual Behaviour**
All the displays except the java2D one show up. Turning `tabs:` to `true` makes all the display show up (including the java2D one). 

**Screenshots**
<img width="712" alt="image" src="https://user-images.githubusercontent.com/579256/58547515-af71f400-8231-11e9-8425-1c0deda53c0e.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Happens only on macOS.

**Comment by hqnghi88** [comment]
@AlexisDrogoul can we have your export preferecences?

**Comment by AlexisDrogoul** [comment]
Here they are: 
[Preferences.gaml.zip](https://github.com/gama-platform/gama/files/3252682/Preferences.gaml.zip)

**Comment by AlexisDrogoul** [comment]
Should be fixed by https://github.com/gama-platform/gama/commit/1bb9ece301a8541b577f0bc935aa6f7ef24b427b . Please test !
