### ISSUE TITLE
focus facet on display doesn' work

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2746]
**Describe the bug**
Open Visualisation and Interaction/3D Visualization/Camera_Position.gaml

There is a display illustrating the usage of focus
`````
display FocusPerson type:opengl focus:first(object){
  species object aspect:default;
}
`````
**To Reproduce**
Run the model 

**Expected behavior**
In the display ````FocusPerson```` it should focus on the sphere 

**Actual Behavior**
There is no motion

<img width="1340" alt="Screen Shot 2019-05-29 at 11 59 23" src="https://user-images.githubusercontent.com/3928502/58548248-39f22d80-8209-11e9-8344-560329e3c49a.png">

Gama GIT

**Comment by agrignard** [comment]
listed in #1878

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
`focus` is now deprecated and will be removed soon. It has been replaced by the much more precise `camera` statement inside `display`. Also note it does not have any effect on Java2D anymore.
