### ISSUE TITLE
Negative value in a position facet

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2747]
**Describe the bug**

I am working on different layer rendering by using the facet ````position```` and it took me a while to understand that it's not possible to put negative value.

Try something like ````position:{-10,0,0}```` (which can be useful in some cases)

I would expect to have an offset of -10 on the X value but it's not the case. The offset is  110 (for a world of 100x100)

**Comment by AlexisDrogoul** [comment]
Actually, it is possible to use negative values, but is has been documented at some point and then left out (but the thing is working). see #2164 and #1555

**Comment by agrignard** [comment]
Ok I didn't remember my own issues (thank you GitHub!). However in this specific case it was a bit different as I wanted to use a dynamic value in the facet position layer (in order to draw  an object having a dynamic location on a static position) and this dynamic value some time was negative implying this issue.

I found a way to make the same effect in an aspect.
