### ISSUE TITLE
French accents are not well displayed when read from a file

### ISSUE THREAD

**Issue by Damapproject** [gama-platform/gama#2748]
**Describe the bug**
GAMA displays well french accented characters when put directly in the code, but not when read from a file.

**To Reproduce**
This simple code reproduces the problem :
```
init{
	write "Aérodrome";
	loop line over: text_file("fichier.txt"){
		write line;
	}
}
```
fichier.txt contains only one word "Aéroport".

**Expected behavior**
The result is :
```
Aérodrome
AÃ©roport
```
The file encoding is set to UTF-8, but GAMA seems to read it as ISO-8859-1.

**Comment by Damapproject** [comment]
Executing `write "Aéroport";` in the interactive console gives `'A?roport'`

**Comment by hqnghi88** [comment]
which version of GAMA and which OS do you use? there is a bug on encoding and it is fixed in the 1.8 release and continuos build.

**Comment by Damapproject** [comment]
GAMA 1.8.0 and Windows 10 Pro.
I forget to precise that it works perfectly on MAC 10.14, but not on my Windows.

**Comment by hqnghi88** [comment]
Just test the current Continuous and also GAMA1.8_Official_Win_64bits (https://github.com/gama-platform/gama/releases/tag/latest)
![image](https://user-images.githubusercontent.com/6105384/58697179-4de18f00-83c3-11e9-8afb-1a9f793d1cfd.png)
So please verify your version, and if you can, verify in gama.ini do you have the line -dfile.encoding in screenshot
![image](https://user-images.githubusercontent.com/6105384/58697262-74072f00-83c3-11e9-9d36-4d051bbac483.png)

**Comment by Damapproject** [comment]
You didn't try to reproduce it ! I said that GAMA works with strings put in the code. My problem is when I read the text from a file !

**Comment by Damapproject** [comment]
Anyway, the parameter `-Dfile.encoding=UTF-8` solved the problem. It was not in my gama.ini by default.
Thank you very much.

**Comment by hqnghi88** [comment]
Sorry , i did not see clearly your post as you say also in interractive console. SO 
![image](https://user-images.githubusercontent.com/6105384/58698614-c1849b80-83c5-11e9-99bc-1124485db379.png)
AND no, you did not fully check my suggest. I mean that param must be BY DEFAULT in gama 1.8 . So review again your version .
Thanks.
