### ISSUE TITLE
Slider precision with parameter value in a tiny range

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2750]
Let's consider the following model, with a parameter that can take only two values 0 or 1.
```
global {
	int v <- 0 ;
}

experiment exp {
	parameter "V" var: v min: 0 max: 1 step: 1;
}
```

Given its definition, it will be displayed as a slider in the interface.

So in the expected slider, the slider bar should be able to take only 2 locations. 
But here it is possible for it to be located in the middle of the slider, which is counter intuitive. 
Intuitively, when I move the slider bar, I have in mind that value of the parameter changes.

<img width="496" alt="Capture d’écran 2019-06-03 à 06 56 39" src="https://user-images.githubusercontent.com/1555274/58769056-62917300-85cd-11e9-83fb-dc7839670d5e.png">

**Comment by AlexisDrogoul** [comment]
Wouldn't it be better to have a boolean parameter in that case 😄  ?

**Comment by benoitgaudou** [comment]
Yep :-) but if the max is set to 2, we have the same "issue" :-)
