### ISSUE TITLE
Problem displaying an image raster when combining with some specific Camera Value

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2754]
**Describe the bug**
Pretty hard to reproduce however in some specific case when trying to draw an image as a raster combining with some specific value of the camera and using a point or an int in the size of the image I get some different rendering here is the code

``````
model NewModel

/* Insert your model definition here */

global{
	file imageRaster <- file('./../images/Kent_Sketches.png');
}

experiment TEST{
	output{
		layout #split;
		display good type:opengl 
		{
			graphics "image" {
				draw imageRaster size:500#px;
			}
		}
		
		display goodwithcam type:opengl background:#white draw_env:true camera_pos: {50.0,50.0025,146.0} camera_look_pos: {50.0,50.0,0.0} camera_up_vector: {0.0,1.0,0.0}
		{
			graphics "image" {
				draw imageRaster size:{750#px,500#px};
			}
		}	
		
		display badwithCam type:opengl background:#white draw_env:true camera_pos: {1848.6801,2083.7744,2369.1066} camera_look_pos: {1848.6801,547.195,3.0723} camera_up_vector: {0.0,0.8387,0.5447}
		{
			graphics "image" {
				draw imageRaster size:{750#px,500#px};
			}
		}
		display goodwithCam2 type:opengl background:#white draw_env:true camera_pos: {1848.6801,2083.7744,2369.1066} camera_look_pos: {1848.6801,547.195,3.0723} camera_up_vector: {0.0,0.8387,0.5447}
		{
			graphics "image" {
				draw imageRaster size:750#px;
			}
		}			
	}
}

``````

[TestImage.zip](https://github.com/gama-platform/gama/files/3249325/TestImage.zip)

**Screenshots**
<img width="1342" alt="Screen Shot 2019-06-03 at 16 22 11" src="https://user-images.githubusercontent.com/3928502/58831985-e83c0f80-861b-11e9-9e43-5b76a6610d02.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS High Sierra]
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: [e.g. git, 1.7.1, etc.]
 - Java version: [e.g. 1.8]
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by AlexisDrogoul** [comment]
Now tracked under #2209 -- for the OpenGL adventurous !

**Comment by agrignard** [comment]
I don't know if this is a pure OpenGL Problem of something related to the GUI interface like SWT etc... as the size of the window for instance as an impact on this bug. I have the feeling also that this bug is relatively new.

**Comment by AlexisDrogoul** [comment]
It is OpenGL as the camera_pos has no meaning in Java2D.

**Comment by agrignard** [comment]
Yes agree for camera_pos but the resizing of the window is more  SWT things no? Anyway it sounds like a tricky bug

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
I am not completely sure to understand (almost 3 years after !) what the problem was exactly.

**Comment by agrignard** [comment]
I took me a while to reunderstand my own issue too. I think it was related to the up vector feature (which is not here any more) so I think we can forget this issue as testing with the new camera statement  I am not able to reproduce it. 

However I have discover another issue related to camera position mixed with an image raster.

In this model 
[TestImage.zip](https://github.com/gama-platform/gama/files/8539688/TestImage.zip)

I have 3 display
- First display without Camera
- Second display with a zoomedIn camera with a camera statement
- Third Display with a zoomedOut with a camera statement
When I run the experiment I got this
<img width="1291" alt="Screenshot 2022-04-22 at 16 50 47" src="https://user-images.githubusercontent.com/3928502/164682929-08bfbb1c-142f-445a-a109-c0b79cb03e37.png">

Now if i replace my camera by hand on each display to a 'normal" postion (zoom=1) you can see that the displayed image has a different size. 

<img width="1293" alt="Screenshot 2022-04-22 at 16 51 04" src="https://user-images.githubusercontent.com/3928502/164683171-d22c40a0-760c-48f2-a526-9f64f86e7fe5.png">


Maybe it is because the size of the image is defined in pixel?

**Comment by AlexisDrogoul** [comment]
Sorry I do not understand the issue -- what does "replace my camera by hand on each display" mean ?

**Comment by AlexisDrogoul** [comment]
In any case, please open an issue specific to this "zoom" problem (which I still do not get).
