### ISSUE TITLE
Mouse_down event emitted when contextual menu displayed (i.e. ctrl-click) on Windows

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2756]
**Is your request related to a problem? Please describe.**
For the moment, (at least on windows), clicking on both left and right button on the mouse trigger a mouse_down event, which is not really practical when wanting just to inspect an agent (or use an user_command). 

**Describe the solution you'd like**
A simple solution is to modify ummisco.gama.ui.views.displays.SWTLayeredDisplayMultiListener and more particularly the mouse_down and mouse_up methods to let them call the delegate action only when e.button == 1:
```
@Override
	public void mouseDown(final MouseEvent e) {
		if (!ok.get()) { return; }
		if (e.button == 1)
			delegate.mouseDown(e.x, e.y, (e.stateMask & SWT.MODIFIER_MASK) != 0);
	}

	@Override
	public void mouseUp(final MouseEvent e) {
		if (!ok.get()) { return; }
		if (e.button == 1)
			delegate.mouseUp(e.x, e.y, (e.stateMask & SWT.MODIFIER_MASK) != 0);
	}
```

I did not commit anything as I do not know the impact of such modification.

**Comment by hqnghi88** [comment]
Dear,
I think there is no negative impact, but i wonder is it better if we introduce something `#mouse_button` in gaml (like `#user_location` in gaml for mouse location in java), and give modeler the right to check which button pressed :)

**Comment by AlexisDrogoul** [comment]
Actually, @hqnghi88 is right. A right mouse click **is** a mouse down event (actually, it is the case in all MouseListener). So giving the modeler the possibility to test is probably the way to go (something like `#mouse_button` and two constants `#mouse_left` and `#mouse_right`). And it would be logical with respect to the enhancement asked in #1918 (the proposed changes here go a bit against this enhancement).

Besides, the events passed and the order in which they are passed, are different on macOS, Windows and Linux. On macOS, `menuDetected(..)` is the first method to be called when right-clicking (and after that `mouseDown(..)`, which is filtered afterwards as the menu has been detected), maybe on Windows it is a different order ? In that case, if you come up with a solution, it probably needs to be Windows specific (and Linux should be tested) -- and I wouldn't filter it so high, by the way (`LayeredDisplayMultiListener` would be a more appropriate choice in my opinion...).

**Comment by ptaillandier** [comment]
ok. As it is a bit hazardous to do that for the forthcoming final 1.8 release, I add a 1.9 tag.

**Comment by AlexisDrogoul** [comment]
I verified and it is exactly what I suspected: on Windows, the `mouseDown` event is sent before the `menuDetected` event (while it is the contrary on macOS and Linux...)

**Comment by AlexisDrogoul** [comment]
I've patched it for Windows -- in a way that allows to revert easily the patch and pass the mouse button to GAMA.
