### ISSUE TITLE
Possibility to play with the camera position with the "camera" statement

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2757]
**Is your request related to a problem? Please describe.**
Right now when we used  ````camera_pos```` it is impossible to navigate in the model while it's running as the ````camera_pos```` is always updated (I know this is the wanted behavior) 

**Describe the solution you'd like**
It could be nice to specify an initial camera_pos that would be only at the beginning of the simulation and then the user can navigate (ultimately it will also be used to replace the camera when double clicking (instead of repositing the camera at the default position according to the environment)

**Describe alternatives you've considered**
Maybe a boolean facet like ````camera_init```` could specify that the camera_pos is just used at the init and not updated every iteration.

**Comment by AlexisDrogoul** [comment]
Actually, I am a bit fed up with all the facets added to `display`, which is becoming completely  unreadable. We better use the unused `camera` statement (that can be used like a layer) for all these things (incl. the recently added `z_near` and `z_far` facets). It would make things more concise and much more logical !

**Comment by AlexisDrogoul** [comment]
Now tracked under #1878 -- for the OpenGL / Camera adventurous !

**Comment by agrignard** [comment]
Yes I agree that the number of facet in display is getting really big. Do we have an example of Camera Statement usage in .gaml?

**Comment by AlexisDrogoul** [comment]
`camera` (`CameraDefinition`) **is not** used for the moment. It's there, waiting to be defined and used !

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
An overview of what it to be expected as a fix to this issue, #2742 , #1159 ,  #579 , #2746 and #2640 
![screencast 2022-02-27 19-56-36](https://user-images.githubusercontent.com/579256/155883485-b9fee57f-6e3b-4261-8833-dc0ffb174932.gif)
