### ISSUE TITLE
event mouse down and camera interaction interfering

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2758]
**Describe the bug**
event mosue down and camera interaction are not working together . I don't thnik it shoudl have any dependencies right?

For example run 

Go to  ````Mouse Exit and Enter.gaml```` 
add in the display
````camera_interaction:false````

The event are not working  (it's happening in any model defining an event mouse down)

**Comment by AlexisDrogoul** [comment]
Well, mouse and keyboard events on OpenGL displays **are completely interdependent** with the camera operations. Actually, the camera itself is the mouse and key listener in OpenGL displays (at least, part of it). But you can try to separate them by identifying where "cameraInteraction" is used in the XXXCamera classes, and trying to use this filter with a finer grain (i.e. not preventing to set things like the mouse position or the key identifiers when no cameraInteraction is allowed, for instance).

**Comment by agrignard** [comment]
Thanks!! Seems to work perfectly in my case (I didin't check for all cases)

Great feature to be able to use a display as a GUI combining event mouse down and a non interactive camera.
