### ISSUE TITLE
Quick fix for casting expressions uses wrong position when applied on a literal constant

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2760]
**Describe the bug**
Open the following model:
````
model testCast

global {
	init {
		float toto <- 2;
	}
}

experiment testCast type: gui;
````
**To Reproduce**
1. click on the warning icon to let GAMA try to fix the warning issue by casting the int to float.
The result is:
global {
	init {
		float(float) toto <- 2;
	}
}

Instead of:
global {
	init {
		float toto <- float(2);
	}
}

**Comment by agrignard** [comment]
I get also this issue in the following case assuming density is a float

if I write ````density <- 2;````and use the auto casting it will write this ````density float(<-) 2; ```` (which does not compile)
