### ISSUE TITLE
Possibility to rotate a display in the 3D axes

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2761]
Right now the rotate facet only take a value that is applied to rotate around the Z position.
What if we also allowed to give a quaternion so that the display can be rotated in any direction

For instance being able to do this kind of stuff
http://www.playmapscube.com/

Or also displaying some chart in this style (where the image could be a dynamic chart)
<img width="839" alt="Screen Shot 2019-06-05 at 19 04 19" src="https://user-images.githubusercontent.com/3928502/58996085-c5992a80-87c4-11e9-91b9-168af0c916e1.png">

**Comment by agrignard** [comment]
I actually found a funny profetic vintage mail from 2013 send to gama-dev called "The third dimension of the third dimension" where I am writting this 

````I did this morning in GAMA  after watching this video from MIT Media Lab````

![The_third_Dimension_of_the_Third_Dimension mov](https://user-images.githubusercontent.com/3928502/58996770-a2bc4580-87c7-11e9-888e-7ef8752dd343.gif)

So I remember doing this directly from OpenGL but I don't remember if we did it in GAML at some point

**Comment by AlexisDrogoul** [comment]
Tracked under #2728 -- we just need now to find someone willing to tackle all these graphical requests !

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
Implemented with https://github.com/gama-platform/gama/commit/a6d88bdfe0b9cf244bb247c1e1b3e04c028baaf6 .
The new `rotation` statement allows to completely specify complex 3D rotations (angle, axis, and center) and whether or not they are dynamic. Only mandatory facet is the angle (like when writing `rotate:` in `display`, now deprecated).  If the axis is not specified, it is by default the z-axis. If the center is not defined, it is by default the centroid of the world.

**Comment by agrignard** [comment]
This sounds like a great feature. To keep pushing on this direction I recently notify that the rotate facet could aslo be useful at the layer level.

I have a very specific use case where I want to use a species ```legend``` (the overlay is unfortunattely not providing what i need)  to have a dynamic legend with text , shape etc, however I need to rotate the all scene to align with a physical table (I do it with the rotate at the display level but the rotation doesn't apply on the text. 


To illustrate it in this picture I'd like to have the text align with the Y axes (currently it's align with the X axes) 
<img width="1062" alt="Screenshot 2022-03-08 at 14 58 17" src="https://user-images.githubusercontent.com/3928502/157252289-5635cd1b-492e-4116-8901-7a7d77f80881.png">



I was thinking to be able to write something like

species legend aspect:base rotate:-90

Would it make sense knowing that we have a ```position``` and ```scale``` facet at the species level?

**Comment by agrignard** [comment]
Ok so it was already mention here by me... thank you github for keeping our memory safe
https://github.com/gama-platform/gama/issues/2176

**Comment by AlexisDrogoul** [comment]
This issue is solved and tested AFAIK -- please reopen in case something is missing.

**Comment by agrignard** [comment]
I am trying to test it. However I ma not sure about the syntax to specific the axis of rotation?

Right now ```species legend aspect:base rotate:90;```works but the rotation is around the center of gravity of the world (as described in the doc) however how can I ask to rotate around the centroid of the agent legend. 

According to this commit https://github.com/gama-platform/gama/commit/a6d88bdfe0b9cf244bb247c1e1b3e04c028baaf6#diff-a004a9756dee07ea1ac8d3c808dfac8b9be46aadc6e3bd32f5cbde4ac85a785e it seems that i can use ```center```, ```axis``` , ```dynamic```  as a facet but those facets are unknown at the layer level

**Comment by agrignard** [comment]
Ok I was maybe  not clear in the writing of the issue but I was describing the issue at the layer level/

It's good anyway to have it at the display level.

For me it makes sense also to have it at the layer level (as described in the exemple above)

Should I create another issue specific to the layer?

**Comment by agrignard** [comment]
those rotation modification are always tricky...

So I tested this new version , however what about the overlay? I was using an overlay as a legend now if I rotate the scene using the rotation layer my overlay is also rotated...

For me it's one more reason that justify to be able to make a rotation as a facet of the layer ```species``` or ```overlay```in addition of the rotation statement.

**Comment by AlexisDrogoul** [comment]
Yep. Right. I have fixed this error on overlays (they won't rotate like all the other layers, obviously). For adding a 3D rotation to each layer, I'm more skeptical about the need. Right now, there is a rotation about the center of the world and the Z-axis, do you really need more ? If you wish you can try to implement it by adding the possibility to define `axis` and `center` at the layer level, but for myself I am going to stop here, since these statements are really becoming too bloated...

**Comment by agrignard** [comment]
Ok great for the overlay.

At the layer level the only interest I see to have a more complex rotation is for a text layer. (e.g text on the facade of a building in a XZ or YZ axis, if ones need to rotate is model because of a projection on a table like in this example:)

Here is an example.

So without rotation (north is facing up in the Y axis, I can display my text as a legend )

<img width="420" alt="Screenshot 2022-03-27 at 10 02 27" src="https://user-images.githubusercontent.com/3928502/160272781-f7d19620-28e8-4987-ac89-5614154d62ab.png">



However when rotating the scene (in my case because I am displaying on a physical interface I need to display it like this and here we can see that the text could be easily realigned with a rotation arund its axis (the text is the aspect of a species legned)
<img width="1025" alt="Screenshot 2022-03-27 at 10 02 47" src="https://user-images.githubusercontent.com/3928502/160272739-d1f55512-4b7e-4ea4-af80-3822f77d85bc.png">

**Comment by AlexisDrogoul** [comment]
So what happens when you rotate the layer by 90° ?

**Comment by agrignard** [comment]
This is how it looks with the rotaion:90 (as excepted the rotation is made around the z axis)
<img width="565" alt="Screenshot 2022-05-05 at 20 06 12" src="https://user-images.githubusercontent.com/3928502/166929124-dc71e0e6-e20f-4e4d-b3ff-2281d1a10fcd.png">

Indeed one solution is to add those "bloatet" facet (```axis``` and ```center```) at the layer level. But indeed the syntax starts to be weird and it implies that those  facet become independant of each other. what if you use the  ```axes```facet with out the ```rotation```one , etc etc...

**Comment by AlexisDrogoul** [comment]
Please describe some enhancement specific to layers you would like in a separate issue -- I consider this one to be fixed as it was mentioning the displays.
