### ISSUE TITLE
brewer_colors with more than available colors in the palette bug 

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2763]
**Describe the bug**
When you try to initialize a palette of color using brewer_colors with more categories than available in the original palette, Gama bug ! No error message (but error tab launch) in Gama nor Eclipse.

**To Reproduce**
Steps to reproduce the behavior: copy/past code and launch

```
model errorbrew
global {	
	init {
		list<rgb> palette <- brewer_colors("Dark2", 100);
	}	
}
experiment my_xp {}
```

**Expected behavior**
warning on the max number of colors for each palette if possible. At least an error output with the limit number of colors

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Well.. passing null instead of the scope to runtime errors is a very bad idea ! I have fixed the runtime issue and also added a static validation, which, obviously, only works with constant values.
