### ISSUE TITLE
Failed to start GAMA (v. with JDK included) with Ubuntu 18.04

### ISSUE THREAD

**Issue by imartinezl** [gama-platform/gama#2764]
Hi GAMA community!
I was doing a project with @agrignard, and we came out with the following issue:

**Describe the bug**
Not able to run GAMA with JDK included, on Ubuntu 18.04.
When running the Gama executable, a window prompts up with the following message:

> The Gama executable launcher was unable to locate its companion shared library.

![Screenshot from 2019-06-07 17-15-36](https://user-images.githubusercontent.com/20516006/59134407-0fab1900-8949-11e9-9b72-1c3d99e95a72.png)

And from the terminal we get the following:

```
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.900.v20180922-1751: cannot open shared object file: No such file or directory
Gtk-Message: 17:12:04.019: GtkDialog mapped without a transient parent. This is discouraged.
```

**To Reproduce**
1. Go to [Gama Download](https://gama-platform.github.io/download)
2. Click on [Linux with JDK](https://github.com/gama-platform/gama/releases/download/latest/GAMA1.8_Official_withJDK_Linux_64bits.zip)
3. Extract the downloaded zip file
4. Run the 'Gama' executable

**Expected behavior**
To open GAMA

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - PC Model: DELL XPS 13 9350
 - GAMA version: 1.8
 - Java version: 1.8

**Additional context**
Minimal Ubuntu installation.

**Comment by benoitgaudou** [comment]
Hi Nghi,

**Comment by benoitgaudou** [comment]
Hi Nghi,
Just to be sure of the fix (for me and for @imartinezl), @imartinezl should now try to download the last *continuous built* of GAMA for Ubuntu with JDK and is bug will be fixed?

Cheers

**Comment by hqnghi88** [comment]
Hello Benoit,
Yes, try to download https://github.com/gama-platform/gama/releases/tag/continuous . The 1.8 is still building in travis.

**Comment by AlexisDrogoul** [comment]
Works for me.

**Comment by agrignard** [comment]
@imartinezl can you try on your laptop with the continous build (with JDK)
https://github.com/gama-platform/gama/releases/tag/continuous

**Comment by imartinezl** [comment]
Yes, I downloaded the continuous build (with JDK) and now it works perfectly.
Thank you so much for your help!

**Comment by agrignard** [comment]
Ok good to know. So it was not coming from your specific Ubuntu settings then
