### ISSUE TITLE
Operators documentation is broken

### ISSUE THREAD

**Issue by Darmo117** [gama-platform/gama#2768]
Hello,

I tried to look up the documentation for operators but part of it is broken. [OperatorsNR](https://github.com/gama-platform/gama/wiki/OperatorsNR) page says that it took too long to render.

Thanks in advance.

**Comment by Darmo117** [comment]
It appears to be fixed.

**Comment by hqnghi88** [comment]
Hello,
FYI, i think it was a limitation of github, you can use documentations on website https://gama-platform.github.io/wiki/Home , it is the same with github but the renderer is better.
