### ISSUE TITLE
Errors in an user_command in an Experiment mess the experiment up

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2771]
**Describe the bug**
When we run a simulation AND an error occurred in an user_command located in the Experiment, then the next step of the simulation still call the user_command.

```
model NewModel

experiment name type: gui {
	user_command t {
		write "hello " + cycle;
		error "end game";
	}
}
```

**To Reproduce**
1. Run the previous model
2. Click on the t button and observe the error
3. Now do one step, the write statement is still executed, which means that the user_command is also executed, whereas the `t` button has not been pressed on this cycle.
4. In addition, the experiment step (displayed in the top bar) is not increased anymore, whereas the simulation step is.

**Expected behavior**
When an error occurs in an user_command in an Experiment, if we do another step, the user_command should not be called anymore.

**Desktop (please complete the following information):**
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
I can't reproduce it. The error stops the user_command and it is not run again in my case.

**Comment by benoitgaudou** [comment]
If you *do one more step after the stop* due to the error, there is not a new message in the console ?

**Comment by AlexisDrogoul** [comment]
No. Nothing.

Le mar. 18 juin 2019 à 17:43, benoitgaudou <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
I've tried several times and in different configurations and I cant reproduce this behavior. Are there any other information you'd want to share about your configuration ?

**Comment by benoitgaudou** [comment]
I checked my Preferences, and I notice that I have : "Stop simulation at the first error" that is true.
In this case, with the attached model:
1. I run the model
2. I click on the t button, and get for example the following console (the simulation has stopped):
```
hello 102359
hello 102360
hello 102361
hello 102362
hello 102363
hello 102364
hello 102365
```
and in the top bar, I have different steps for the experiment and simulation:
<img width="411" alt="Capture d’écran 2019-06-19 à 10 40 32" src="https://user-images.githubusercontent.com/1555274/59735178-b57e5200-927e-11e9-90d3-c0d611d54ce9.png">
3. I do one step and the console displays:
```
hello 102366
```

When I set "Stop simulation at the first error" to false.
1. I run the simulation
2. I click on the t button, I get an error that appears, and in the console only the following message:
```
hello 107589
```
and the simulation continues running.
3. I make a pause in the simulation, and do step on the simulation.
Nothing appears in the console.

I attach my preferences just in case.
[Preferences.gaml.zip](https://github.com/gama-platform/gama/files/3304325/Preferences.gaml.zip)

**Comment by AlexisDrogoul** [comment]
Hum... I still cant reproduce it exactly, but I know (I guess) where the "sticky" action problem comes from. If the simulation is running, actions like this one are posted as "one-shot" actions and executed at the end of the cycle to minimise the interferences with the execution of the agents. Problem is, if an exception occurs while it is run, the line that removes it from the "one-shot" actions queue is (was) never executed.
