### ISSUE TITLE
[UX] Cycle through GAML tabs with keyboard shortcut

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2774]
**Is your request related to a problem? Please describe.**
I'm a big fan of keyboard shortcut to navigate on my laptop and I have the reflex to navigate through my tabs with one. So I would like to have some shortcuts to browse open tabs in GAMA.

**Describe the solution you'd like**
The best shortcut would be to use same as in many software (Sublime Text, Mozilla Firefox, Google Chrome, etc) : 
 - To move to the next open tab : `Ctrl` + `Tab`
 - To move to the previous open tab : `Ctrl` + `Shift` + `Tab`

**Additional context**
For now, `Ctrl` + `Tab` just move me to the search bar (which could also be set on a shortcut like `F1`... :innocent: ), and after to every input (button, field, etc) on the current interface.

**Comment by hqnghi88** [comment]
You mean this tabs ?
![image](https://user-images.githubusercontent.com/6105384/60231219-b50b3a00-98c2-11e9-8bb7-e0a815f86f13.png)
ON win, it is Ctrl+Pageup/PageDown.

**Comment by RoiArthurB** [comment]
Yes I'm talking about this tabs ! :D 
So the problem is that I don't have PageUp/Down buttons... :/

**Comment by hqnghi88** [comment]
See in Keys preference or it is an os problem???

**Comment by RoiArthurB** [comment]
No it's just not a key on my laptop's keyboard ^^"

**Comment by hqnghi88** [comment]
In the Keys preference, there is somewhere to set that combination?

**Comment by RoiArthurB** [comment]
I didn't find any keymapping any feature in GAMA. I only saw that shortcut in "Show Active Keybindings..." (`Shift` + `Ctrl` + `L`)

**Comment by hqnghi88** [comment]
Do you have this? 
![image](https://user-images.githubusercontent.com/6105384/60384486-851d8b80-9aa8-11e9-830c-4a3dfc4d7259.png)

**Comment by RoiArthurB** [comment]
No, here's what I have...

![Screenshot from 2019-06-29 20-59-25](https://user-images.githubusercontent.com/16764085/60385211-f9f4c380-9ab0-11e9-98c5-5323990d09e2.png)

I'm using GAMA 1.8 Latest w/o JDK if it can help?

**Comment by hqnghi88** [comment]
Click on Advanced button in bottom, but it seem your dialog is small, it should be in the same place with Revert to default, Import, Export.

**Comment by AlexisDrogoul** [comment]
This is the bottom of my Preferences dialog on macOS:

<img width="735" alt="Monosnap 2019-07-02 16-05-50" src="https://user-images.githubusercontent.com/579256/60499816-635c1880-9ce3-11e9-94ed-52b83e2a0267.png">

There seems to be a small problem on Ubuntu...

**Comment by RoiArthurB** [comment]
Oh yes, I don't have this button ! 
Even on my big laptop (1920x1080) they collapse :speak_no_evil:

**Comment by AlexisDrogoul** [comment]
Can you try if commit 32ba41cd62e3e86ea72d6983a81f9fa8c8787a87 changes anything ?

**Comment by hqnghi88** [comment]
@RoiArthurB  can you find it on the menu bar, i think some unix will display advanced menu on top menu bar

**Comment by AlexisDrogoul** [comment]
@RoiArthurB can you test if the buttons are now displayed under Ubuntu ? Thanks.

**Comment by RoiArthurB** [comment]
Hello,

It's fixed on the Continuous Build (with Manjaro, but it should work the same on Ubuntu) and so now I can access Advanced settings :)

![Screenshot_2019-07-15_09-41-39](https://user-images.githubusercontent.com/16764085/61193324-f84c1200-a6e4-11e9-84dd-fcf1536d2049.png)
