### ISSUE TITLE
Keystone completely messed up on MacOS X w. retina display

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2778]
**Describe the bug**
Invoking keystone (press k in an OpenGL display) produces really strange behaviours on MacOS X w. a Retina display. Only one corner can get selected, the display is initially too small, the corners don't stick, etc.. 

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - PC Model: MBP 15" (Retina display)
 - GAMA version: git, with Eclipse 2019-03
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
@gama-platform/core can someone confirm ? I will issue a fix, but I'm a bit surprised this bug only shows up now. As if nobody had used keystoning w. a Retina display...

**Comment by agrignard** [comment]
I use it with Retina actually. but I am still with El Capitan so that might be the reason I didn't notice anything

**Comment by benoitgaudou** [comment]
Hi,
When developping HoanKiemAir, I used Mojave and a Retina screen. And plugged on a projector everything worked well. I just tried on my computer without plugged screen and before the issue fix, the keystone was really not working well, but after the commit it seems to work.
