### ISSUE TITLE
An action declared without a return type has no check over its actual return

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#278]
**Describe the bug**
I don't know if it's by design or not, but when declaring an action like this:
```
action t{}
```
I'm expecting the action to return nothing, but I can actually return anything I want with the `return` statement inside of the function.
And conversely I can assign the result of `t` to a variable even though there's no return type specified.
I understand that it could be useful for polymorphism, but it also means there's no type checking done at all. Which in my opinion is an easy way to have silent logical errors.
I'm raising this issue because I'm in a case where development becomes extremely difficult because of that, but it's far from being the first time I see code using that kind of untyped action call and that should have been typed instead and caused unnecessary waste of time.
If that's a design choice then I would suggest we add something to the grammar to differentiate actions that are meant to return nothing from the ones that can return anything. Else then I guess it's a bug.
Something that is extremely weird is that through this mechanism we can change the return type with inheritance (see example below).

**To Reproduce**
1. Run this model:
```
model actions

/* Insert your model definition here */
global {


	init {
		let i <- a();
		write 'global no return action: ' + type_of(i) + " " + i;
		
		let j <- c();
		write 'global no type action with a return statement: ' + type_of(j) + " " + j;
		
		create s1;
		let k <- s1[0].b(); 
		write 'action without return in a species: ' + type_of(k) + " " + k;
		
		create s2;
		let l <- s2[0].b(); 
		write 'inherited no return action overriden with an int return: ' + type_of(l) + " " + l;
		
		create s3;
		let m <- s3[0].b(); 
		write 'inherited no return type action but returning an int, overriden with a string return: ' + type_of(m) + " " + m;
		
	}
		
	action a {
		
	}
	action c {
		return "coucou";
	}
}

species s1 {
	action b{}
}
species s2 parent:s1 {
	action b{
		return 1;
	}
}
species s3 parent:s2{
	action b{
		return "hello";
	}
}


experiment t;
```
2. observe the madness

**Comment by AlexisDrogoul** [comment]
All actions return something. A declaration of `action` without a return type is strictly equivalent to defining an action with `unknown` as the return type. Except from the fact that it is not properly documented, I do not see any logical problem here.

**Comment by lesquoyb** [comment]
Ok that makes way more sense now, I also got confused because I thought gama was doing some type infering to set the type of the action in case you don't explicitly write it.
