### ISSUE TITLE
Scheduling species with inheritance

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2782]
**Describe the bug**
When a species inherits from another one, it is scheduled at last whatever the code ordering is.   The other thing with child species, is that the code from the class is executed before the parent one. 

**To Reproduce**

```
global {
	init {
		create the_last;
		create second_bis;
		create one_bis;
		create one;
	}
}

species one {
	reflex first {
		write sample(self)+" FIRST";
	}
}

species second_bis parent:second {
	reflex second_b {
		write sample(self)+" SECOND";
	}
}

species one_bis parent:one {
	reflex one_b {
		write sample(self)+" THIRD";
	}
}

species second virtual:true {
	reflex second_b {
		write sample(self)+" FORTH";
	}
	
	reflex second_r {
		write sample(self)+" VIRTUAL FORTH";
	}
}

species the_last {
	reflex last {
		write sample(self)+" LAST";
	}
}

experiment sch {
	output {
		
	}
}
```

**Expected behavior**

1) keep ordering of declared species for scheduling, regardless of inheritance

2) give priority to parent reflexes, unless overloaded. If you want child reflexes to be triggered before, define it in parents (choose the ordonnancement) and overloads it.

**Desktop (please complete the following information):**
 - OS: Mojave
 - GAMA version: 1.8
 - Java version: JDK embedded

**Comment by AlexisDrogoul** [comment]
Hmm... Why should species be scheduled in the order of their definition ? The default choice here is to schedule them using the hierarchy as well. You can always define a new scheduling strategy in the model. And why should parent reflexes executed first ? I don't really understand it, can you elaborate ? Again, you can define your own ordering by defining actions, etc.

**Comment by chapuisk** [comment]
Of course, if user can define the scheduling process it is fine. When I try it though, I have an ArrayStoreException:``global schedules:[second_bis+one_bis+one+second+the_last]``

For the execution of the reflexes, I thought it will be better to schedule parent first because in this case you have the ability to redefine some, so the one to be executed is actually the one define in the child. Whereas, if child reflexes are executed first, there is no mean for user to have control on reflexes order, which will always be child and then parent reflexes

**Comment by AlexisDrogoul** [comment]
First point should have its own issue. You use the wrong syntax, but it should be pointed out as a warning or error (the correct syntax is: `global schedules: second_bis+one_bis+one+second+the_last`)
I don't understand the second one. Sorry...

**Comment by chapuisk** [comment]
For the first point, It only works if all the species are unscheduled. I don't know if it is a regular behavior or not ...

For the second point, the idea is that if for example I have a species ``people`` and then ``firefighter`` and ``civilian`` that inherit from it, user may want all child species to execute ``people`` reflexes first and then they specific behaviors. In the current state, modelers have no control over execution order of reflexes, which will always be child and then parent species. in the case of ``people`` reflexes are scheduled first, user can overload them and hence have control over execution ordering. Hope you'll understand .... and by the way, you said that scheduling respect hierarchical structure, so child are schedule last while it is the other way for reflexes !

**Comment by chapuisk** [comment]
@AlexisDrogoul you free to close the issue if you find it irrelevant ;)
