### ISSUE TITLE
Installing Rjava crashes GAMA

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2786]
I downloaded GAMA and installed experimental plugin Rjava. After restarting GAMA, GAMA crashes with the following log.

macOS Sierra 

[log.txt](https://github.com/gama-platform/gama/files/3387863/log.txt)

**Comment by hqnghi88** [comment]
Hello Srirama,
Which gama version and which link did you use for install rjava?

-------------------------------------------
HUYNH Quang-Nghi, Ph.D.
Lecturer
GAMA http://gama-platform.org/
College of Information and Communication Technology - Can Tho University
Campus II, 3/2 street, Ninh Kieu district
Can Tho city, Vietnam
[Vietnam] +84909128322

**Comment by sriramab** [comment]
Both java and non java gama from continuous build of yesterday

**Comment by hqnghi88** [comment]
ok, retry today CI or tomorrow, because yesterday the releases (both CI gama and experimental) have problem, i think.

**Comment by sriramab** [comment]
Ok. There are not builds yet . I will wait.

**Comment by AlexisDrogoul** [comment]
Yes, please use the latest builds. A lot has changed in the 1.8 API and I havent had the reflex to update the experimental plugins (but @benoitgaudou did most of the job).

**Comment by sriramab** [comment]
Hmm. Does not work even on todays build :( I also changed workspace many times, but no success. Could it be that java GAMA is based on and java rJava is based on has some conflicts?

**Comment by hqnghi88** [comment]
Hi,
I will take a look today or tomorrow and let you know. It seems the
experimental plugins are still broken.

-------------------------------------------
HUYNH Quang-Nghi, Ph.D.
Lecturer
GAMA http://gama-platform.org/
College of Information and Communication Technology - Can Tho University
Campus II, 3/2 street, Ninh Kieu district
Can Tho city, Vietnam
[Vietnam] +84909128322

**Comment by hqnghi88** [comment]
Hello ,
I tested on my local build and install rjava from experimental repository (updates.gama-platform.org/experimental) . There is no syntax error and no crash (i did not configure the R environment). Could you try again with Continuous build?
![image](https://user-images.githubusercontent.com/6105384/61193608-a3a99680-a6e6-11e9-9e27-f5588cbada84.png)

**Comment by sriramab** [comment]
GAMA crashes without installing plugins in GAMA (GAMA1.8_Continuous_withJDK_Win_07.18.19_b7575bb.zip)

This time on windows, and here is the error file 
[errorwindows.txt](https://github.com/gama-platform/gama/files/3406258/errorwindows.txt)

**Comment by hqnghi88** [comment]
Oh my poor Srirama, i must say as i just saw a new change (just few hours ago) in the continuous build that you tried. AND , in your log, it exist R_plugin, so it should still be in your workspace. 

Caused by: java.lang.NoClassDefFoundError: msi/gaml/compilation/GamaGetter$Unary
	... 62 more
Caused by: java.lang.ClassNotFoundException: msi.gaml.compilation.GamaGetter$Unary cannot be found by ummisco.gaml.extensions.rjava_1.0.0.201907150319

I will take a look again and let you know.

**Comment by AlexisDrogoul** [comment]
@sriramab : the text explicitly mentions RJava : `Caused by: java.lang.ClassNotFoundException: msi.gaml.compilation.GamaGetter$Unary cannot be found by ummisco.gaml.extensions.rjava_1.0.0.201907150319`

**Comment by sriramab** [comment]
Ok, seems fishy. too many GAMA on my computer. :(

**Comment by hqnghi88** [comment]
I tried and no problem (local and CI). Could you please retry with clean workspace?

**Comment by sriramab** [comment]
Ok. I had installed Microsoft R and it was conflicting with Cran R.  I removed Microsoft R, and it works now on windows. I will check on mac later.

**Comment by sriramab** [comment]
Not working on mac. Can someone please check on a mac machine? I just cannot install rJava plugin.

**Comment by AlexisDrogoul** [comment]
What is not working ? Do you have any specific logs or errors ? Does it crash GAMA like the orignal issue ?

**Comment by sriramab** [comment]
There is no error log, I just cannot install rJava plugin
Install New Plugins>experimental url> Rjava
This installation just stops abruptly, please see screenshot.

Is there anyway I can extract the log?

![Gama Installation Details 2019-07-23 06-48-19](https://user-images.githubusercontent.com/12668606/61683508-00740500-ad16-11e9-8d30-efcb962c41b2.png)

**Comment by AlexisDrogoul** [comment]
Can someone test the process with the official release ? @hqnghi88 @benoitgaudou

**Comment by benoitgaudou** [comment]
Hi,

I tested, on MacOSX with the release (at 12h).
It worked perfectly after the configuration steps specified in the
connection model provided and a relaunch of my computer.

Benoit

Le mer. 31 juil. 2019 à 15:49, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
OK. So lets consider it is solved, then ! Thanks.
