### ISSUE TITLE
How to uninstall GAMA?

### ISSUE THREAD

**Issue by bruesba** [gama-platform/gama#2791]
Hi,

GAMA has been extremely useful to me, however I'm freeing up space and intend to uninstall the platform. I can't seem to find a way to do so, however. There does not seem to be an uninstaller, I can't find the software in control panel, and uninstallation isn't documented in the readme/FAQ. 

So how would I go about uninstalling GAMA from my Windows 10 machine? Thank you in advance and to the developers; a million thanks for facilitating my thesis research.

Blue

**Comment by AlexisDrogoul** [comment]
Hi,

Putting the application / folder into the trash and emptying it doesn't work ?

**Comment by AlexisDrogoul** [comment]
Well.. I guess you have succeeded since you wrote this issue -- thank you to acknowledge it or post a more detailed issue (i.e. why can't you simply trash the app ?).

**Comment by bruesba** [comment]
Hi Alexis,

Sorry, I could not access the internet for a while. I was wondering whether there would be any residual files/setting upon thrashing and emptying, but that seems like a silly assumption given your reaction. Thank you for the suggestion - all worked out fine!

Best
