### ISSUE TITLE
closest_to between a non-empty list of agents and a point  returns nil

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2802]
**Describe the bug**
Run the model `Mas KMean Interactive.gaml` located in `Toy Models / Learning `.
Start by creating some circle and cross agents (by clicking on the associated image in the Tools panel display and clicking in the map display).

Now click on the eraser picture in the Tools Panel display and then click on the map display, on white space (i.e. not on an agent).

The following Exception occurs:
```
Can not execute ask on a nil agent
	at msi.gama.runtime.exceptions.GamaRuntimeException.error(GamaRuntimeException.java:61)
	at msi.gaml.statements.AskStatement.privateExecuteIn(AskStatement.java:217)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
...
```

Indeed, if I had some `write` in the code such as:
```
			match 2 {
				list<agent> close_ag <- agents overlapping (circle(5) at_location #user_location);
				write sample(close_ag);
				if not empty(close_ag) {
					write sample(#user_location);
					write sample(close_ag closest_to #user_location );
					write sample(close_ag with_min_of(#user_location distance_to each.location));
					ask close_ag closest_to #user_location {
```

I can observe that the `closest_to` operator returns a nil agent, whereas the list (`clos_ag` ) is not empty and the geometry is not nil. In addition, when we compare with `with_min_of` operator, I observe the `with_min_of distance_to ` combination returns a result.
```
close_ag -: [button(2)]
#user_location -: {1.5873015873015872,64.37389770723104,0.0}
closest_to(close_ag,#user_location) -: nil
close_ag with_min_of distance_to(#user_location,each.location) -: button(2)
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
The model is clearly fishy. You can see it in your logs : buttons are returned but they should not ! However, what it revealed is nevertheless a bug in the compound spatial index (used when you have a mixture of grids and species), which was returning the wrong spatial index. I've corrected this and also corrected the model.
