### ISSUE TITLE
Question : why empty experiment in Die and create models.gaml

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2811]
In the `Die and create models.gaml`model, in `Modeling / Model Coupling / Flies and Mosquitos `, there is an experiment that is empty and the model does not display anything in the console.

So what is the purpose of this model ? we can remove it ?

**Comment by hqnghi88** [comment]
Dear Benoit,
It is not the purpose of this model. Actually, it should display 2 micro-display in initial, with the console , then in 100 step, it write out the things in micro-models. At each 100 steps, it will kill the micro-model and recreate a new one. This is the simplest syntax of comodeling so i think i should keep in library.
However, the behavior is a bit strange as the console is not displayed, i did not find the syntax to show it in the model unless go to menu and show console.
