### ISSUE TITLE
Console does not appear in Create and kill models.gaml

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2813]
**Describe the bug**
The Console does not appear after a run of the model `Create and kill models.gaml` (from `Modeling / Model coupling / Flies and Mosquitos`.

In fact, it seems that both consoles are open, but are close immediately.

Note that I was not able to find another model with this issue (among the (only) 10 ones I tried).

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
It does not appear **in** the model or it does not appear **after** the model has run ?

**Comment by benoitgaudou** [comment]
It does not appear in the simulation perspective after the execution of the experiment.
(in fact, I can see that the console view is created when the simulation perspective is open, but it is close after a very brief time).
