### ISSUE TITLE
The headless script has error (launched from GAMA Git source code version)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2817]
**Describe the bug**
I was trying to run GAMA (in its Git code source version) in headless mode, from the script provided in the msi.gama.headless plugin.

Following the README.txt file, I write in my Terminal:
```
 sh gama-headless.sh samples/predatorPrey.xml samples/predatorPrey
```

I get the following error:
```
MacBook-Pro-de-ben:unix ben$  sh gama-headless.sh samples/predatorPrey.xml samples/predatorPrey
./gama-headless.sh
******************************************************************
* GAMA version 1.8    	                                       *
* http://gama-platform.org                                       *
* (c) 2007-2019 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
./gama-headless.sh: line 109: syntax error near unexpected token `('
./gama-headless.sh: line 109: `echo "				      -m [mem]    				-- allocate memory (ex 2048m)"'
```

Notice thay I tried with the GAMA continuous built verions from the 20 of July, and the script worked well ...

**Desktop (please complete the following information):**
 - OS: macOS
 - PC Model: MBP
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
A search on Google of `syntax error near unexpected token` shows that it is emitted by bash, likely when one is using parentheses in the wrong way. Have you tried removing the `(ex 2048m)` from the script ?

**Comment by RoiArthurB** [comment]
Hello,
I'm currently working on the script (and how to launch GAMA-Headless more generally) on the [gama#gaml-headless branch](https://github.com/gama-platform/gama/blob/gaml-headless/ummisco.gama.product/extraresources/headless/unix/gama-headless.sh) (not sure if it's working, I'm working on it) ^^

As Alexis said, I've changed the shebang on previous commit because it was calling the wrong executer, it's a *Bash* script and not an *Unix Shell* script. 
So the easiest way to use it is to make it executable and run it as it is : 
```
cd /path/to/gama/headless
sudo chmod +x gama-headless.sh
./gama-headless.sh [your arguments]
```

Could you tell me if it solved the problem? If not copy/paste the error message and your `bash` and `sh` version please :smile:

**Comment by benoitgaudou** [comment]
Hi,

The three ways of executing the script:
- `sh gama-headless.sh samples/predatorPrey.xml samples/predatorPrey`
- `bash gama-headless.sh samples/predatorPrey.xml samples/predatorPrey`
- `./gama-headless.sh samples/predatorPrey.xml samples/predatorPrey` (with a `chmod u+x gama-headless.sh` previously)

 provide the same error: 
```
MacBook-Pro-de-ben:unix ben$ ./gama-headless.sh samples/predatorPrey.xml samples/predatorPrey
./gama-headless.sh
******************************************************************
* GAMA version 1.8    	                                       *
* http://gama-platform.org                                       *
* (c) 2007-2019 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
./gama-headless.sh: line 109: syntax error near unexpected token `('
./gama-headless.sh: line 109: `echo "				      -m [mem]    				-- allocate memory (ex 2048m)"'
```


In fact, it seems that the following lines are the cause of the error (when I remove them, there is no more error at this location):
```
echo "List of available options:"
echo "		final String res = " Welcome to Gama-platform.org version "+GAMA.VERSION
echo "	"
echo "				sh ./gama-headless.sh [Options] [XML Input] [output directory]"
echo "				List of available options:"
```



Nevertheless, I get now the following error:
```
gama-headless.sh: line 143: cd: /Users/ben/Dev/GitRepository/gama/msi.gama.headless/ext/plugins: No such file or directory
ls: /*.jar: No such file or directory
GAMA is starting...
``` 

due to lines : 
```
gamaDirectory=$(cd $GAMAHOME/plugins && pwd)
DUMPLIST=$(ls  $gamaDirectory/*.jar )
```

I can notice that this is perfectly normal, given the organization of files that is different in release and in the Git code source.

Given that, I think that in fact, this is not an issue as I have the feeling that this file is not expected to be executed in Git source code version of GAMA...
