### ISSUE TITLE
Parameter of an action being a given species or one of its children

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2827]
In the MAELIA model, it is common to have an action (with a species as parameter) used to create an agent of the associated species. Below an example of such a case study.

It seems that it worked in a previous version of GAMA, but now does not compile anymore (`idGen` is an attribute to any species in general), which is in fact totally right.

My question would be to know how it is possible to specify that the parameter `spec` is not a species in general, but either `general` species or any of its children (`s1`or `s2`)? 

```
model NewModel

global {
	init {
		create s1;
		create s2;
		create general;
		
		do cre(species(one_of(agents)));
	}
	
	action cre(species<agent> spec <- general) {
		create spec {
			idGen <- "create from action";
		}
	}
}

species general {
	string idGen;
}

species s1 parent: general {}
species s2 parent: general {}

experiment name type: gui {}
```

**Comment by AlexisDrogoul** [comment]
just use `species<general>` instead of `species<agent>`

**Comment by benoitgaudou** [comment]
OK Thanks
