### ISSUE TITLE
Ant Foraging shows no ants in 3D view experiment

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2829]
**Describe the bug**
Just simple as the title
![image](https://user-images.githubusercontent.com/6105384/62190240-da043880-b3ab-11e9-80ac-a206045d8562.png)
No exception in eclipse.

**Expected behavior**
Show the starving ants 

**Desktop (please complete the following information):**

win 10
gama git / gama very near 1.8

**Comment by benoitgaudou** [comment]
Digging in the various models of the library, it seems to come from the `draw` statement of an .obj file, when the `size:` facet has a value

**Comment by AlexisDrogoul** [comment]
Yep. Same problem with "Moving 3D Object", with actually one thing I noticed : the object appears briefly at the beginning before disappearing.

**Comment by AlexisDrogoul** [comment]
Immediate diagnostic shows that applying a size (and then a scaling) seems to nullify the cached envelope ... I continue.

**Comment by AlexisDrogoul** [comment]
OK. Fixed. We need to regenerate the official release, I guess...

**Comment by hqnghi88** [comment]
Thanks. I will do it.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 already launched !
