### ISSUE TITLE
Trigger a parameter with multi simulation 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2831]
**Describe the bug**
I have some parameters that trigger displays option (show interaction, showgrid etc..).

I just discover that when using the parameter in a multi-simualtion mode the parameter affects the last simulation

**To Reproduce**
Run the following model (modified form the model library)
`````


model multi_simulation

global {
	//definition of three global variables of which the initial values will be used by the first simulation 
	int nb_agents <- 10;
	float agent_speed <- 1.0;
	rgb agent_color <- #green;
	
	bool showDummy<-true parameter: "Draw Dummy:" category: "Interaction";
	
	
	init {
		create dummy number: nb_agents;
	}
}

//definition a simple species that just move randomly at a given speed
species dummy skills: [moving]{
	rgb color <- #green;
	reflex move {
		do wander speed: agent_speed;
	}
	aspect default {
		if (showDummy){
		  draw circle(2) color: agent_color border: #black;	
		}
	}
}

experiment main type: gui {
	//definition of a minimal duration for each cycle. As the model is very simple, it can run too fast to observe the results, so we slow it down.
	float minimum_cycle_duration <- 0.1;
	
	//we define a init block to create new simulations
	init {
		//we create a second simulation (the first simulation is always created by default) with the following parameters
		create simulation with: [nb_agents:: 5, agent_speed:: 5.0, agent_color:: #red];
		
	}
	output {
		layout horizontal([0::5000,1::4000]) tabs:true editors: false;
		display map {
			//we use an overlay to display the speed of the agents in the simulation
			overlay position: { 5, 5 } size: { 180 #px, 30 #px } background: # black transparency: 0.5 border: #black rounded: true
            {
               draw "agent_speed: " + agent_speed color: # white font: font("SansSerif", 20, #bold) at: { 10°px, 20°px };
            }
			species dummy;
		}
	}
}
``````
Trigger "Draw Dummy" Parameters
**Expected behavior**
I would assume to trigger the display of the dummy species in both simulation but it only happens in the last one (S1) in this case
**Desktop (please complete the following information):**
Official 1.8 release

**Additional context**
Not sure if it's a bug or an expected behavior

**Comment by AlexisDrogoul** [comment]
That's  the principle of the parameter section, they only concern the last
simulation, trigger or not. Otherwise use actions in menus, this should
probably work.

Le jeu. 1 août 2019 à 06:25, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
And, as a reminder, you have access to two variables in an experiment :
simulation and simulations. The first one concerns the last simulation
created. The other, all the simulations available. So simply define your
actions, in the on_change facet, so that they ask the simulations to do
something, rather than implicitly relying on the latest.

Le jeu. 1 août 2019 à 06:25, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Ok got it
