### ISSUE TITLE
[REQUEST] Possibility to truncate parameter title in simulation view

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2834]
**Is your request related to a problem? Please describe.**
I have a quite small screen with a not very high resolution (so everything is big on my screen) and I have long parameter titles which makes it impossible to use it without resizing parameter panel (see below).
![2019-08-01-150808_1366x768_scrot](https://user-images.githubusercontent.com/16764085/62276531-755de200-b46e-11e9-8e4c-3f235953118d.png)

The problem is that, if my title are a little bit long (7 - 8 words) I have to extend the parameter panel on more than half of my screen width (see example below)
![2019-08-01-150740_1366x768_scrot](https://user-images.githubusercontent.com/16764085/62276529-742cb500-b46e-11e9-8b2d-81e47d09271d.png)

**Describe the solution you'd like**
I nice work around could be to automatically truncate titles to always have the possibility to change values.
E.g : 
Default panel size : 
| Prob... [SLIDER] | _Other panel_
Bigger panel size : 
| Probability to wear a... [SLIDER] | _Other panel_

**Describe alternatives you've considered**
If it's too complicated to automatically truncate title, adding a facet in parameter statement to have a smaller title.

**Comment by AlexisDrogoul** [comment]
I've actually implemented another solution, hopefully more elegant, which enables the title to automatically wrap on several lines when necessary. 

<img width="162" alt="image" src="https://user-images.githubusercontent.com/579256/62338732-b522d900-b503-11e9-831a-d424ba6fdcea.png">

**Comment by RoiArthurB** [comment]
Your solution makes the panel really great, but it's a little buggy sometimes...
![image](https://user-images.githubusercontent.com/16764085/62518070-e0cef780-b852-11e9-90de-a82540d9fb2e.png)
The input file is always at the same size

**Comment by AlexisDrogoul** [comment]
That is a different issue on the 'value' box of some parameters. Please open a new one! Thanks.
