### ISSUE TITLE
[Screenshot] Doesn't take the right screenshot when zooming in a display

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2835]
**Describe the bug**
When I'm zooming in my map display, the screenshot is moved on the right-bottom...

What I want to screenshot
![Screenshot_2019-08-01_16-28-23](https://user-images.githubusercontent.com/16764085/62282440-c8896200-b479-11e9-8ad1-b0e00aae12ac.png)

What I actually screenshot
![main_model_display_map_size_580x582_cycle_35167_time_1564651707560](https://user-images.githubusercontent.com/16764085/62282477-d9d26e80-b479-11e9-916c-f624625607c7.png)

**To Reproduce**
1. Run a simulation with a map displayed
2. Zoom in clicking the + button
3. Click on the screenshot button (the camera one)

**Expected behavior**
I'm expecting the same view as when I'm clicking on the button

**Desktop (please complete the following information):**
 - OS: Manjaro 18.0.4 Illyria
 - Kernel: Linux 5.1
 - PC Model: [Clevo N240WU](https://www.clevo.com.tw/clevo_prodetail.asp?id=1055&lang=en)
 - GAMA version: Continuous
 - Java version: OpenJDK 1.8 and Embedded JDK
 - Graphics cards / Display system: Intel Chipset

**Comment by AlexisDrogoul** [comment]
Java2D ? OpenGL ? 
Any difference when setting the preference below to true ?

<img width="494" alt="image" src="https://user-images.githubusercontent.com/579256/62294623-9128ae80-b495-11e9-8bf8-347f717d31f0.png">
