### ISSUE TITLE
Serialization of colors

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2836]
**Describe the bug**
I noticed that the serialization in GAMA / Java of a color like `#white` will return the string `°white`.
But if I give this string to the method `staticCast` of the class `GamaColorType` (in order to get back a color object from this string), it throws an Exception as the string `°white` is not known as a color (whereas `white` is).

Similarly, but I do not know whether this is related, when I try to do the same in GAML by writing (in a GAML model):
```
		write rgb(to_gaml(#white));
```
I get an Exception: `'°white' is not a valid color'.

So I was wondering whether there is an issue in the serialization of color? or its staticCast ?

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Stupid old code sticking around from the old days...

**Comment by benoitgaudou** [comment]
Thanks, but even with the new serialization of color, I still have the same Exception when writing (I am expecting to get a white GAML color object after the evaluation of the expression `rgb(to_gaml(#white))`)
```
write rgb(to_gaml(#white));
```

And the `staticCast` of the class `GamaColorType` cannot transform the string `#white` into a GamaColor.

**Comment by AlexisDrogoul** [comment]
It's a different issue (not of serialisation) and I'm not completely sure we should keep it as an issue, by the way. 

in `rgb(to_gaml(#white));`, you ask GAMA to produce a color from the string representing the GAML code used to produce this color (a constant beginning with a #). But the casting functions have never been "unserializers" even though, for some types, they try to interpret what's inside a string (for floats, ints, points). If you write `rgb(to_gaml(rgb(10,10,10)));`, do you expect the casting function to interpret the GAML code representing this color ? 

So we can of course change the casting of colors and interpret strings beginning with #, as the job is already done for their names ('white', 'black', etc.). But maybe it would be better, if this is needed of course, to more systematically test the serialiser/unserialiser couple of `to_gaml`/`eval_gaml` (which is probably what you are looking, but I'm not sure they are working correctly for all types).

**Comment by benoitgaudou** [comment]
I think you are right and what I am looking was the `eval_gaml`.
I also think I have to dig in this direction to tackle issue https://github.com/gama-platform/gama/issues/2837
