### ISSUE TITLE
In headless, some parameters are not well serialized (in XML) and unserialized

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2837]
**Describe the bug**
This issue is highly related to issue #2836 about the serialization of colors, but it can be larger and I prefer to let it here as a reminder.

As noticed by the gamar development team (in https://github.com/r-and-gama/gamar/issues/13), for some models of the model library, the exportation of an XML file and its run using headless throws an exception.

As far as I have investigated yet, this is due to issues in the serialization of parameters value in the XML file and their deserialization when the xml is used to run simulations in headless model (with color as an example).

As an example, we can try to generate the XML of the `Life.gaml` model and execute this xml using the headless. 

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Is this issue still relevant ? It seems to have been closed by #2836 and I'm not sure of the benefit to let it open..

**Comment by AlexisDrogoul** [comment]
Closing it now as my previous question does not seem to ring any bell ...
