### ISSUE TITLE
GAMA Platform page in Wikipedia

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2838]
We have been discussing about this during the last coding camp with @AlexisDrogoul and @RoiArthurB 

What about having a dedicated Wikipedia page for GAMA?

Right now we are only references ones here
https://en.wikipedia.org/wiki/Agent-based_model

We use to be referenced in this page but we are not there anymore
https://en.wikipedia.org/wiki/Comparison_of_agent-based_modeling_software
Every entry point has its own wikipedia page so that's maybe the reason why we are not anymore in the list.

**Comment by agrignard** [comment]
It won't be that straightforward to create this page. Wikipedia required a validate and already active account with many edits. 

See this for instance https://en.wikipedia.org/wiki/Help:Your_first_article

I just create an account, so I will start edit some part of wikipedia and see how it goes. If anyone has more experience or has already create a wikipedia page let me know

**Comment by RoiArthurB** [comment]
Maybe you should remove the _Developer documentation_ and _GAMA Dev mailing list_ parts... :thinking: 
It doesn't add any useful information for non-user, and, because of it, it really looks like an ad ^^'

**Comment by RoiArthurB** [comment]
I think that we should do a clean page following the same structure as other same software (like NetLogo : https://en.wikipedia.org/wiki/NetLogo )
Also, be careful on the title! On your draft you named it _Gama Platform_, but on the [Comparison board](https://en.wikipedia.org/wiki/Comparison_of_agent-based_modeling_software) we are referenced at _GAMA Platform_ (in caps)

**Comment by chapuisk** [comment]
I agree ! although I am not sure to fully understand how being several to contribute increases our chance to be published, I proposed some modification on your draft.

**Comment by agrignard** [comment]
@RoiArthurB  Yep it's a first version, for now I took some info from the website but it needs to be more like the netLogo,Repast one of course. You are welcome to make some edit. I also change the caps you're right.

@chapuisk more edits means more input from a different source so for wikipedia it means more chance that the information is relevant.

**Comment by RoiArthurB** [comment]
@agrignard Just to correct you, the number of edition on a page doesn't mean anything (you could use a VPN to edit your page from 20 different country if you want, it's not a valuable point). What really matter is references !
Also be careful with copy/pasting, it could disadvantage your draft if too much content is copied from gama website (Wikipedia content should be original content).
If anyone want to read what Wikipedia want and want not to see in there article, here you have it in [french](https://fr.wikipedia.org/wiki/Aide:Admissibilit%C3%A9_d%27un_article) and here in [english](https://en.wikipedia.org/wiki/Help:Your_first_article#Gathering_references).

**Comment by agrignard** [comment]
Ok I meant more editor but indeed it's not that straight forward to be published. So let's iterate on this draft before to submit it. 

On another source of inspiration can be this page
https://fr.wikipedia.org/wiki/Processing

**Comment by RoiArthurB** [comment]
Hi all,

I've updated the Wikipedia page by adding a [Software Infobox](https://en.wikipedia.org/wiki/Template:Infobox_software) (the sidebar with some quick information on the top right).

![image](https://user-images.githubusercontent.com/16764085/66739982-31d71980-ee9c-11e9-9d15-2150cd3996ee.png)

I think that we can submit the page, what do you think?

**Comment by RoiArthurB** [comment]
Hi all,

Just to update  all about the Wikipedia GAMA page: I did submit the [french](https://fr.wikipedia.org/wiki/Utilisateur:RoiArthurB/Brouillon/Gama_Platform) and [english](https://en.wikipedia.org/wiki/Draft:Gama_Platform) version which were both rejected (mainly because of issues with maintaining a neutral point of view).

The French version should be fine now (I'm on it) and if you have some time to change the english version, feel free to participate 😀

**Comment by agrignard** [comment]
Great!

I also did some slight update also recently on the english. I will work a bit on the content to have something more "neutral" even though it's not that bad as it is.

And then let's coordinate when we think it's a good timing to resubmit it.

**Comment by RoiArthurB** [comment]
The french page has been published ! 🥳🥳🥳
https://fr.wikipedia.org/wiki/Gama_Platform

**Comment by AlexisDrogoul** [comment]
Time to close this issue I guess :)

**Comment by RoiArthurB** [comment]
For posterity, the English version is published here : https://en.wikipedia.org/wiki/GAMA_Platform 🥳🥳🥳
