### ISSUE TITLE
Parameter value doesn't match variable value if changed in GAML code

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2840]
**Describe the bug**
When a variable value linked to a parameter change in GAML code, the parameter interface doesn't change and so the value display is not the variable value anymore.

**To Reproduce**
Try this small model :
```
model NewModel

global {
	float toto update: rnd(100.0) on_change: {write(toto);};
}

experiment NewModel type: gui {
	parameter "Toto" var: toto category: "Transmission" init: 5.0 min: 0.0 max: 100.0 on_change: {write("PARAM : "+toto);};
}
```
![image](https://user-images.githubusercontent.com/16764085/62511193-b4a87c00-b83c-11e9-88dd-46692bf56458.png)

**Expected behavior**
I'm waiting the slider to display the effective value of the linked variable.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra && Manjaro Linux
 - GAMA version: git
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
No, this is exactly how the parameters view is intended to behave: it is an input which is based on the initial values of variables, but does not reflect their current values. Monitors and inspectors (outputs) are here for that.
