### ISSUE TITLE
No warning when default CRS of the world does not match shape file CRS

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2841]
**Describe the bug**
When using shapefile of a different CRS than of the world's default CRS (WSG 84 / Pseudo-Mercator), you can have unwanted behavior: e.g. any save statement will then change CRS to be the one of the world, blank display. the issue is also related to #2769

**To Reproduce**
There is two situation where you can find this problem:
1. When you do not change the shape of the world while using shape file of a different CRS, e.g. using Gama to modify a shape file (clean, prepare for further simulation, etc.)
2. When you redefine the shape of the world using geometries of a shape file with a different CRS rather than the file itself:
``geometry shape <- envelope(union(shapefile.contents));`` 

**Expected behavior**
Raise a warning/error when manipulating shapefiles that do not have the same CRS as the one of the world. In fact, this is not obvious that modifying the shape of the world also change the CRS and may be we should add this to the documentation

**Desktop (please complete the following information):**
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
I think these two situations correspond to very narrow (and different) use cases. It would be better to split them into two issues with example models to test the fixes. Thanks !
