### ISSUE TITLE
Update GAMA : GAMA plugins to be updated  are not categorized

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2845]
**Describe the bug**
In the GAMA release, the update of GAMA, from the "Install new software" pane, is not easy as the plugins to update are not categorized whereas the default configuration has the option "Group items by categories" selected. In this case, no plugin to be updated appears.

**To Reproduce**
1. Go to 'Install new software...'
2. Add the address: `http://updates.gama-platform.org` in the "Work with" text field (to access the updates of GAMA. 
3. No package appears to be updated
4. You need to uncheck the option "Group items by categories" to make appear all the packages that can be updated

**Expected behavior**
Even when "Group items by categories" is set, all the packages to update should appear. 

**Screenshots**
<img width="970" alt="Screenshot 2019-08-13 at 14 15 22" src="https://user-images.githubusercontent.com/1555274/62922118-d2458a80-bdd4-11e9-8603-a044ab7ff6a6.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.8.0

**Comment by hqnghi88** [comment]
fixed
![image](https://user-images.githubusercontent.com/6105384/63227195-3ff71980-c20e-11e9-8967-c2f602909267.png)
