### ISSUE TITLE
In the model navigator, .obj are not displayed as used by a model

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2846]
**Describe the bug**
In the model navigator, when we expand a model.gaml node, we can see a *Uses* sub node, showing all the data files needed/used in the model.

It seems to work with data type such as `.png`, `.svg` or `.jpg`.

But `.obj` does not appear.

**To Reproduce**
1. Expand the `Toy Models` / `Ant Foraging` / `Uses`
or 
1. See the following screenshot.

**Expected behavior**
The `.obj` should appear in the Uses .

**Screenshots**
<img width="1396" alt="Screenshot 2019-08-14 at 15 56 48" src="https://user-images.githubusercontent.com/1555274/63008508-f5dc0400-beac-11e9-9e65-c1bf96ce08ce.png">

**Desktop (please complete the following information):**
 - OS: macOS X
 - GAMA version: 1.8.1

**Comment by AlexisDrogoul** [comment]
This is not a bug (and not new): only the files that have a built-in viewer (or a well-known content types, like .txt) are displayed in this structured view. All the others (the ones with a question mark) are not.
