### ISSUE TITLE
The experiments green buttons are not the same as the experiments that appear in the navigator after expanding a model

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2847]
Let consider a model (with 4 experiments) importing a model (with 1 experiment).

In the editor of this model, we can observe 5 green buttons to launch the 4 +1 experiments available from this model.

But when we expand the model node in the model library, only the 4 experiments written in the model appear.

I do not know whether it is expected or an issue.

<img width="1154" alt="Screenshot 2019-08-14 at 16 37 05" src="https://user-images.githubusercontent.com/1555274/63011280-31c59800-beb2-11e9-8bd2-7a7858be2bd9.png">

**Comment by AlexisDrogoul** [comment]
The navigator displays the structure of each model file, so only 4 experiments are displayed, which is normal. Should be the same with species, etc.
