### ISSUE TITLE
"Z-axis rotation" label could be changed to be clearer

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2853]
**Is your request related to a problem? Please describe.**

In the case of an OpenGl display, the left sidebar, pane **General** can activate/desactivate a continuous rotation of all the agents arounf the Z axis.
The rotation speed is set in the text field with the label `Z-axis rotation`. Which was not clear to me when I try to use it. 
When I change its value, I thought it would modify the rotation axis (the value would be an angle wrt the Z-axis to define the new rotation axis, ... even if I admit that a value it not enough to define such an axis...).

<img width="448" alt="Screenshot 2019-08-17 at 10 01 27" src="https://user-images.githubusercontent.com/1555274/63205941-2ce12e00-c0d6-11e9-8165-dc138508bfa5.png">

**Describe the solution you'd like**
Change the label text to reflect the effect of the value: e.g. `Rotation speed` (and this text field could be relocated below the toggle button (to make clearer it is the rotation speed of the continuous rotation).

We could also think at adding a way to redefine the rotation axis (3 values x,y,z ?)

**Comment by AlexisDrogoul** [comment]
Three things here: 
- the name of this operation is precisely "Z-axis rotation" (see e.g., https://www.cs.helsinki.fi/group/goa/mallinnus/3dtransf/3drot.html) or "Rotation about z-axis". We can change it, of course, but it's not obvious to find something more informative ("2D rotation angle" ?)
- The value is an angle, not a speed (except when "Continuous rotation" is on, and it becomes the angular speed).
- Inverting the two controls would not really make sense, no ? "Z-axis rotation" can be defined independently of "Continuous rotation", while the reverse is not true (a zero angle would not allow rotation). Maybe it would be better to can grey out the continuous switch when the angle is zero.

**Comment by benoitgaudou** [comment]
OK thanks, I misunderstood this command... and thus no need to change.

Nevertheless, notice that it is a little bit painful to use: 
each modification of the number is evaluated and the cursor goes back to the left of the text field.
So if I want to type 180 in a row, I will get 081 in the textfield (after the first 1, the cursor goes to the left, then the 8 is typed before the 1 ...).
