### ISSUE TITLE
Question : does SHIFT + UP/Down/Left/Right has a special effect? 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2855]
Reviewing the documentation for GAMA 1.8.0, in the page about Displays
https://github.com/gama-platform/gama/wiki/Displays

It is specified that for ArcBall camera, there are the following commands:

keys | Function
-- | --
SHIFT+Up | Rotate the model up (decrease the phi angle of the spherical coordinates)
SHIFT+Down | Rotate the model down (increase the phi angle of the spherical coordinates)
SHIFT+Left | Rotate the model left (increase the theta angle of the spherical coordinates)
SHIFT+Right | Rotate the model right (decrease the theta angle of the spherical coordinates)

I tried my best but cannot see any difference with simply Up / Down / Left / Right (on Mac OS) ... Should we keep these commands ?

**Comment by benoitgaudou** [comment]
I may add that the `SHIFT + mouse` seems to create a ROI (Region Of Interest ?).
I admit that, being not sure to understant how it works, I would prefer someone else to add a part in the doc about this feature.

**Comment by AlexisDrogoul** [comment]
I changed the doc to reflect the fact that SHIFT is not used anymore (CTRL or CMD on macOS are the modifiers used).
