### ISSUE TITLE
Preferences documentation

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2856]
Dear all,

I did my best to review the documentation page for Preferences (https://github.com/gama-platform/gama/wiki/Preferences). 

I admit that it definitely be improved... but in particular, here are the points I think  need to be: 
- Startup: _Maintain the state of the navigator across sessions_
- Apearance: _Reduce the height of views' toolbars_
- Data and Operators: _Optimizations …_ : all of them

In addition, concerning _Reduce the height of views' toolbars_, I tried to switch between true and false... without identifying the effect. Issue ?

**Comment by AlexisDrogoul** [comment]
Done.
