### ISSUE TITLE
Question about - operator on list and element: 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2858]
**Describe the Question**

The `-` operator applied on a list and an element (but a list) is described in the document to behave like:
```
if the left operand is a list and the right operand is an object of any type (except list), - returns a list containing the elements of the left operand minus all the occurrences of this object
```
https://github.com/gama-platform/gama/wiki/OperatorsAA#-

but when trying it, I get only a list without the first element of the list:
```
write sample([1,5,7,6,7]) - 7);
```
displays:
```
([1,5,7,6,7]) - 7 -: [1,5,6,7]
```

what is the correct behavior?

**Comment by AlexisDrogoul** [comment]
The documentation is wrong. This operator has been aligned a long type ago with `remove` in Java.
