### ISSUE TITLE
FSM: check that final state does not have any transition

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2865]
**Is your request related to a problem? Please describe.**
In a Final State machine, it seems that GAMA permits out-transition from a final state (`state toto final: true {` ) whereas I was expecting a compilation error in the following code (there is no out-transition and exit expected in a final state): 

```
	state state2 final: true {
		write string(cycle) + ":" + name + "->" + "state2";
		transition to: state1 when: flip(0.5) { 
			write string(cycle) + ":" + name + "->" + "transition to state1";
		}
		exit {
			write string(cycle) + ":" + name + "->" + "leave state2";
		}
	}
``` 

**Describe the solution you'd like**
Throw a compilation error in this case.

**Comment by AlexisDrogoul** [comment]
Actually, `exit` is legit, as it represents what would happen when the agent leaves the state (in the case of a `final` state, it is when dying that the state can be left). I've added the required code in the `FsmArchitecture` class (in addition to emitting an error if a transition is written).
