### ISSUE TITLE
FSM: one single final state is accepted

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2866]
**Describe the bug**
[Perhaps not a bug ...depending on the definition of a finite-state machine]
When a species has the fsm architecture, it can define `state`, with facet final and initial.

I was expecting that in a fsm, we can find one single initial state (GAMA checks that properly), but that the fsm can have several final state.

But GAMA throws a compilation error when we define 2 state as final. 

**To Reproduce**
Look at the following model:
```
species dummy control: fsm {       
	state state2 final: true { }
	state state3 final: true { }   
}
```

**Expected behavior**
I was expecting that the compilation is fine.

**Desktop (please complete the following information):**
 - OS:  macOS
 - GAMA version: 1.8.0

**Comment by AlexisDrogoul** [comment]
Indeed. It's fixed by now.
