### ISSUE TITLE
Equation: integrated_times and integrated_values do not return anything

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2868]
**Describe the bug**
When I look at the model `Solve statement options.gaml`, it tried to show the values returned by the facets  `integrated_times` and `integrated_values`, that are expected to contain the time interval / list of values inside the integration process.

Nevertheless, they seem to always be empty. (cf. the model above).

**To Reproduce**
1. Run the model `Solve statement options.gaml`
2. observe the console

**Expected behavior**
Elements in the 2 lists.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.8.0

**Comment by hqnghi88** [comment]
Dear Benoit,
May be i should remove these 2 facets (i think i made them deprecated in the last Codingcamp). The updated syntax is using [] with the integrated variables , like S[] or t[]
what do you think?

**Comment by benoitgaudou** [comment]
Hi Nghi,

It seems that they are not deprecated, so they should be, at least.
I will update the document by removing them and adding a reference to the
bracket notation.

Thanks
Benoit



Le lun. 26 août 2019 à 08:09, HUYNH Quang-Nghi <notifications@github.com> a
écrit :

**Comment by benoitgaudou** [comment]
Close with 468720f

**Comment by hqnghi88** [comment]
Thanks Benoit :😃
