### ISSUE TITLE
Prey Predator tutorial: all the predators die quickly ! (inheritance & init question)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2869]
When I run one of the pres-predator tutorial model (e.g. Model 7.gaml), I noticed that after the first simulation step, almost all the predator agents die.

It is not the expected behavior, and the model worked previously properly ... 

The problem comes from the fact that the agents have their energy initialized to 0.
It could be initiallized in the generic species, which could add a problem ...

```
species generic_species {
	float max_energy;
	float max_transfert;
	float energy_consum;
	float energy <- (rnd(1000) / 1000) * max_energy  update: energy - energy_consum max: max_energy ;
}

species prey parent: generic_species {
	rgb color <- #blue;
	float max_energy <- prey_max_energy ;
	float max_transfert <- prey_max_transfert ;
	float energy_consum <- prey_energy_consum ;
	float proba_reproduce <- prey_proba_reproduce ;
	int nb_max_offsprings <- prey_nb_max_offsprings ;
	float energy_reproduce <- prey_energy_reproduce ;
}
```

**Comment by ptaillandier** [comment]
it seems like the value of max_energy (overridden in the child species)  is set after the value of energy (that is set in the parent species). You have the same issue for prey, but as their first reflex consists of eating, they do not die all.

If you set the value of energy in the init, it works well:
species generic_species {
	...
	float energy update: energy - energy_consum max: max_energy ;
	
	init {
		energy <- (rnd(1000) / 1000) * max_energy  ;
		location <- myCell.location;
	}

I have no idea if it is normal or not.

**Comment by benoitgaudou** [comment]
Hi,
I am almost sure that this tutorial worked better previously, so it seems that there is here a change in the assignment behavior.

The question is thus: is it on purpose or is it an unexpected and undesirable side effect?

**Comment by AlexisDrogoul** [comment]
> I am almost sure that this tutorial worked better previously
I checked, and it seems it comes from the building of the dependency graph between attributes (`energy` is the only attribute not redefined in the subspecies, which creates an odd situation when ordering the attributes). Since this computation has been introduced something like 3 years ago, it probably means that the tutorial is not so used 😄
