### ISSUE TITLE
[batch] possible false error at batch initialisation

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#287]
**Describe the bug**
Following issue #285 I tried to get to the core of what's causing the error message and I ended up with this model:
```
model keepsim

global{
	map<bool, string> a <- [true::"a", false::"b"];
	string b;
}

experiment simulationBase type: batch repeat:100 parallel:3 keep_simulations:false until:cycle=100{
	parameter 'b' var: b <- a[true];
}
```
If I let `keep_simulations` at false I will have an error message saying `Error when opening the experiment: This experiment does not keep its simulations. a cannot be retrieved in this context` but I don't understand why it's the case, `a` is not dependent on other simulations, it's a normal variable of global.

**To Reproduce**
1. Run the model given above
2. See error

**Expected behavior**
The simulation can be initialized as it's the case in GUI or when `keep_simulations` is true. Or clearer indications of what's wrong

**Comment by AlexisDrogoul** [comment]
Should be fixed by https://github.com/gama-platform/gama/commit/dbe514304758a60549e7a71f27707cea5798fc7e. Please test !
