### ISSUE TITLE
Problem with old syntax with list of string

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2875]
**Describe the bug**
I am not sure how to describe this bug but it might be useful

I have a model that works (compile and run) on GAMA 1.8 nut doesn't compile anymore on the last bin

Here the model
https://github.com/CityScope/CS_Proxymix/tree/master/ProxymixABM

And the specific part of the code that doesn't compile anymore 

`````
ask ML_people{
  list<list<string,string>> cells <- collaborationFile[people_username];            
  loop mm over: cells {  
    ML_people pp <- ML_people first_with( each.people_username = string(mm[0]));
    if (pp != nil) {
      real_graph <<edge(self,pp,float(mm[1]));
    }
 }
}
`````

On this specific part

`````
mm[0]
``````
and 

```````
mm[1]
```````
Producing this error:

```````
Multiple markers at this line
- No operator found for applying 'first_with' to types [species,
   unknown] (operators available for [types [container, unknown]])
- a list<string> should not be accessed using a int index
- The contents of this list can only be accessed with string
   keys
- No operator found for applying '=' to types [string, unknown]
   (operators available for [types [float, int], types [int, int],
   types [float, float], types [unknown, unknown], types [date,
   date], types [int, float]])
```````

I guess I am doing something wrong here but it is working on 1.8 and not on the current one

**Comment by AlexisDrogoul** [comment]
See the previous fix (on the access with the brackets or 'at'). Validation
has been enforced on the type of the data you access.

Le mar. 27 août 2019 à 05:56, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
By looking at your code again, what is list<string, string> supposed to
mean? Although the syntax is accepted (gama is a bit too laxist here), it
is likely to produce this error.

Le mar. 27 août 2019 à 05:56, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
Yep. Now it's checked and I will soon commit a check on the declaration of parametric types to disallow these declarations from now on.

**Comment by agrignard** [comment]
I reopen this issue for a specific question as I think it's related to this modif.

I have lots of model that works on GAMA 1.8 and doesn't work anymore on the current build. I guess it's because of the parametric types modification

So one of those  model
https://github.com/CityScope/CS_CityIO/blob/master/examples/GAMA/cityIO_Gama/models/cityIO.gaml

The problem is always the same when trying to access information from this kind of remote json
https://cityio.media.mit.edu/api/table/virtual_table

So for instance if I declare 

`````
map<string, unknown> spatial;
`````
and then try to get this value using 

`````
spatial <-inputMatrixData["header"]["spatial"];
`````

with

`````
map<string, unknown> inputMatrixData;
`````

I get the follwoing error

`````
No operator found for applying 'internal_at' to types [unknown,
   list] (operators available for [types [container, list], types
   [geometry, list], types [agent, list]])

`````

I get this error in many part of my code and many different models but I think it comes all from the same old syntax that I am using.

**Comment by AlexisDrogoul** [comment]
Well, it seems normal to me. `inputMatrixData["header"]` returns an `unknown` value as per the definition of `inputMatrixData`, so you can't access it like a `list` or a `map` unless you cast it first (e.g. `map(inputMatrixData["header"])["spatial"]`)
