### ISSUE TITLE
Improve the BDI Tutorial models to better understand the impact of each added component

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2880]
**Is your request related to a problem? Please describe.**

I reviewed the BDI tutorials (Gold Miner model).
From step 2, gold miner are introduced first with only BDI-driven behavior, then social relationship, emotion, and norms.
The tutorial illustrates step by step the introduction of each of these components.

Nevertheless, it is not possible for the learner to really visualize (and thus understand) what each component brings to the model.

The models need to add more visualization (charts, monitors or something else) to see that:
(i) the new elements are really working (e.g. illustration of social relationship or emotions)
(ii) the new elements bring something (e.g. what is the impact of efficiency, inequality ... ) through charts.

**Comment by mathieuBourgais** [comment]
I'll look at it in 10 days when i'll have a bit more time for this.

**Comment by mathieuBourgais** [comment]
What I propose is : 

Step 3 : add a display of the social links between miners, with different colors depending on the liking value.
Step 4 : write or display something when an agent has a joy emotion.
Step 5 : Add a chart to show the gold possed by each miner and by the policeman.

If you have any other propostion, don't mind telling them.
I will implement this (and do a bit of debug) in the next days, and change the tuto on the wiki after.
