### ISSUE TITLE
A test experiment does not support the model: facet

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2883]
**Describe the bug**
The `.experiment` allows to create a model limited to an experiment. It comes with the `model:` facet allowing to referring to the model that is experimented (and imported in a hidden way).

But we can also want to create an experiment only file, related to tests a model and thus be allowed to write something like: 

```
experiment NewExperiment1 model:'New Model.gaml' type:test { }
```

but this throws a compilation error: (on the facet `model`):
`Symbol 'model:' seems to be incomplete`.

In addition, the Wizard window to create a test experiment should provide the option to choose a model to experiment (as it is done in the experiment file wizard).

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git - master

**Comment by AlexisDrogoul** [comment]
Actually, your example is misleading as this one should work. The problem comes from experiments where the `model:` facet is not the first one after the name. It is a limitation of the grammar, now documented in `experiment`. `model:` *must be* the first facet.
