### ISSUE TITLE
OpenGL display: how to switch off all the lights?

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2884]
To see clearly the impact of all the possible lights, I am trying to switch off all the lights in a OpenGL display.
Given the documentation: https://github.com/gama-platform/gama/wiki/ManipulateLight, there are 2 ways of manipulating lights: 
* `ambient_light` facet of the display
* `light` statement in the display (and 7 lights can be defined in a display).

To switch off the lights, I tried to set all these lights to black in the following model:
```
model test_light

grid cells {
    aspect base {
	draw square(1) at:{grid_x,grid_y} color:#white;
    }
}

experiment my_experiment type:gui{
    output {
	display my_display type: opengl background: #darkblue ambient_light: #black {
		light id:1 color: #black;
		light id:2 color: #black;
		light id:3 color: #black;
		light id:4 color: #black;
		light id:5 color: #black;
		light id:6 color: #black;
		light id:7 color: #black;
		
	    species cells aspect: base;
	    graphics "my_layer" {
		draw square(100) color:#white at:{50,50};
		draw cube(5) color:#lightgrey at:{50,30};
	    }
	}
    }
}
```

I get the following screenshot (I am not an expert, but I have the feeling there is still light ...):
<img width="797" alt="Screenshot 2019-09-02 at 10 44 18" src="https://user-images.githubusercontent.com/1555274/64089106-b3e90400-cd6e-11e9-90b2-61eaf491637f.png">

Now I tried to use the facet `light` of the statement display (set to `false`):
<img width="791" alt="Screenshot 2019-09-02 at 10 46 06" src="https://user-images.githubusercontent.com/1555274/64089147-e561cf80-cd6e-11e9-874b-581a683d1b1a.png">

So I am wondering:
* Did I miss something on lights (and in particular a kind of light) ? 
If not:
* why there is still light when all of them are set to #black? 
* why setting all the lights to black is not equivalent to set the `light` facet to false?
* even when the `light` facet is set to false, is it "normal" to see the cube on the square (everything should be black no ?).
* how to get a uniform display such as the one on the light documentation: 
![image](https://user-images.githubusercontent.com/1555274/64089291-936d7980-cd6f-11e9-91b0-ff329312c4fd.png)

**Comment by AlexisDrogoul** [comment]
The last effect can be achieved by setting the ambient_light to 0 and all the lights (from 1 to 7) to active: false. However, there might be other combinations available.
