### ISSUE TITLE
Headless problems with memory

### ISSUE THREAD

**Issue by mathieuBourgais** [gama-platform/gama#2885]
An error is raised about a problem of memory when runing a model on gaa headless, no problem with "normal" gama

[headlessError.zip](https://github.com/gama-platform/gama/files/3566371/headlessError.zip)

1. Run gama headless with the model enclosed (the XML inpu fil is also enclosed in the ZIP)

**Expected behavior**
It works (the computation is very long (around 45 minutes).

**Desktop:**
 - OS: tried on windows 10 but also on a remote server.
 - GAMA version: latest build
 - Java version: 1.8

**Additional context**
The error message is : 
Gama raised an exception: | java.lang.OutOfMemoryError: Java heap space

Once again, it works perfectly well on normal gama.

**Comment by YoucefSklab** [comment]
Hi,
Have you tried with more allocated memory? 
You can allocate more memory to your simulation with the -m parameter. So, for instance, to run a simulation with 5GB memory, you should write: bash gama-headless.sh -m 5120m.

By default, allocated memory is 2GB. You may need 4 or even 6GB.

**Comment by mathieuBourgais** [comment]
I tried to run it on a server (with openMole) by allocating up to 50 GB of memory and the error was the same (Without Gama headless, the model does not need so much memory)

**Comment by hqnghi88** [comment]
Hi Mathieu,
2 thing you can try ( if you havent tried) while waiting for headless expert:
- commented the lines with monitor...., 
- set finalStep="501"  in xml to 499

**Comment by RoiArthurB** [comment]
Hi @mathieuBourgais 

It's really difficult for us to dig in your bug without more precise information. If you can provide us full logs and the command line you're running with the exact version of gama, it will help us a lot.

From what I saw your code should run just fine (just taking a while). I tried with the [Docker image](https://github.com/gama-platform/gama.docker) (still under heavy development) without any trouble... So the problem may comes from OpenMole or your headless commands (your XML is really different from what the headless would generate, so I'm wondering how you're using it).

Waiting for more information from you ^^

**Comment by AlexisDrogoul** [comment]
I'm closing it but please reopen if you have new elements. Thanks
