### ISSUE TITLE
Content and Style of labels of pie chart 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2887]
I am not sure if it's a bug or not but maybe it is missing in the doc of the label of the chart.

@pcaillou maybe you have an idea?

Here is the described issues

https://github.com/CityScope/CS_Simulation_GAMA/issues/54

**Comment by benoitgaudou** [comment]
The option you colleague is looking for is the facet `tick_font` of the statement `chart`.
Note that, I have updated the doc to be more precise about its effect.
Note 2, there was an issue on the website generation that have prevented the website to have the last version of the description of this facet (the wiki was a little bit more precise).
