### ISSUE TITLE
GAMA release: strange options in the Gama.ini

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2888]
**Describe the bug**

Here are some remarks about the Gama.ini file (at least on MacOS):
* in the GAMA with JDK version, the path to the jdk is an absolute path:
`-vm /Applications/Gama.app/Contents/jdk/Contents/Home/bin/java`
It should be replaced by something like: 
`-vm ../jdk/Contents/Home/bin/java`
* Even if the Properties of GAMA specify that GAMA uses UTF-8 encoding, it seems that on Windows, characters with accents or Vietnamese letters are not well supported when a model is executed.
The following option should be added in the GAMA.ini:
`-Dfile.encoding=UTF-8`
* the memory allocated to GAMA is only 2Go. Nowadays, we could move to 4Go.

**Desktop (please complete the following information):**
 - OS: macOS & Windows
 - GAMA version: release 1.8.0

**Comment by hqnghi88** [comment]
HI Benoit,
* Agree, if it is the gama.ini in jdk repository (for Gama with JDK) it means i was missed something (one more time).
* Which release? i just checked and i remember and i am sure that the -Dfile already added in product (old closed issue), If it appear again it should be report as separated issue.
* Not really appreciated, i agree that we eliminated 32bit version (actually, eclipse, not us), but windows and even linux machines AFAIK still have 4gb ram as max config. Hoping in 1 or 2 years the status should be upgraded . OR we implemente a strategy to check the ram amount and suggest a number at first launch of gama :D

**Comment by benoitgaudou** [comment]
Hi @hqnghi88 ,

OK for points 1 and 3.

For point 2, I just check on the source code and in the Windows GAMA continuous built 
I was not able to find it....

**Comment by hqnghi88** [comment]
Here it is
https://github.com/gama-platform/jdk/blob/master/win/64/Gama.ini

For 1, we must recheck

**Comment by benoitgaudou** [comment]
Here is the GAMA.ini in the continuous built for Windows.

**Comment by benoitgaudou** [comment]
-vm
./jdk/bin/javaw
-startup
plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1000.v20190125-2016
-nl
${target.nl}
-data
@noDefault
--launcher.defaultAction
openFile
-vmargs
-server
-Dosgi.locking=none
-noverify
-Xmn128m
-Xss2m
-XX:+UseParallelGC
-XX:+UseAdaptiveSizePolicy
-XX:+OptimizeStringConcat
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.retryAttempts=10
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.closeTimeout=6000
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.readTimeout=6000
-Declipse.log.level=ERROR
-Dosgi.checkConfiguration=false
-Xms256m
-Xmx2048m

**Comment by hqnghi88** [comment]
Very strange indeed Mr Gaudou,
i just downloaded the latest CI (w/wo JDK) for win and the 2 gama.ini have same thing (-dfile included)
-vm
./jdk/bin/javaw
-startup
plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1000.v20190125-2016
-nl
${target.nl}
-data
@noDefault
--launcher.defaultAction
openFile
-vmargs
-server
-Dosgi.locking=none
-noverify
-Xmn128m
-Xss2m
-XX:+UseParallelGC
-XX:+UseAdaptiveSizePolicy
-XX:+OptimizeStringConcat
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.retryAttempts=10
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.closeTimeout=6000
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.readTimeout=6000
-Declipse.log.level=ERROR
-Dosgi.checkConfiguration=false
-Dfile.encoding=UTF-8
-Xms256m
-Xmx2048m

**Comment by benoitgaudou** [comment]
You seem to be right Mr. Huynh, I might have downloaded a wrong version.
I think I can thus close this issue.
