### ISSUE TITLE
[HEADLESS] Invalid java execution command with embedded JDK

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2890]
**Describe the bug**
If I'm installing a GAMA_with_JDK version, I can't use the headless version if I don't have Java installed

**To Reproduce**
0. Do not have any java version installed in your computer
1. Install GAMA_with_JDK version
2. Unzip the archive
3. Run the `gama-headless.sh` script
```
sh gama-headless.sh 
gama-headless.sh
******************************************************************
* GAMA version 1.8                                               *
* http://gama-platform.org                                       *
* (c) 2007-2019 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
gama-headless.sh: line 29: java: command not found
```

**Expected behavior**
The script should use the archive java bin and not simply running the `java` command.

**Desktop (please complete the following information):**
 - OS: Based unix
 - GAMA version: all
 - Java version: None

**Additional context**
To fix this issue, the command line 29 of the shell script should be changed from 
```
java -cp ../plugins/org.eclipse.equinox.launcher*.jar -Xms512m -Xmx$memory  -Djava.awt.headless=true org.eclipse.core.launcher.Main  -application msi.gama.headless.id4 -data $passWork $PARAM $mfull $outputFile
```

To :
```
../jdk/bin/java -cp ../plugins/org.eclipse.equinox.launcher*.jar -Xms512m -Xmx$memory  -Djava.awt.headless=true org.eclipse.core.launcher.Main  -application msi.gama.headless.id4 -data $passWork $PARAM $mfull $outputFile
^^^^^^^^^^^
```

But it should be fixed only for _with JDK_ versions, so I don't know how to change in on Travis 😓😓😓

**Comment by hqnghi88** [comment]
Hi,
Feel free to adapt the gama.ini of your os in this repo https://github.com/gama-platform/jdk . And it will be imported in the with_jdk release :D

**Comment by hqnghi88** [comment]
Ah sorry, misunderstood, just thought gama did not find jdk. But it should , isnt it? Or you can do the same thing with gama.ini : create your right headless bash file and copy it into release.

**Comment by RoiArthurB** [comment]
Maybe I was not clear... The problem is that the script `gama-headless.sh` is the same on archive w/ and w/o JDK. But it should be different (otherwise, a computer using the version w/ JDK will not use the archive JDK but an installed java on his computer)....

So the workaround is to change the java call command in giving the java bin from the jdk folder !

_TL;DR :_
`gama-headless.sh` script should be different in the w/JDK's version and in the w/o JDK's version

w/ JDK : `../jdk/bin/java -cp [......]` <- Using the embedded JDK
w/o JDK : `java -cp [......]` <- Using the Java system on the machine
