### ISSUE TITLE
Allows array-first JSON files to be saved.

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2893]
**Describe the bug**
This is related to a discussion that we have had by mail here
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gama-dev/HiiWNdWniZM/EPrAfZG4EgAJ

It has been fixed in this commit and it used to work
https://github.com/gama-platform/gama/commit/23f1a7e66074f7d7fddc498d6cd2a091a6fc13dc

However, with the last version of GAMA (update from the master branch) and the json is not anymore compatible

It is pushing the old Json Map format see
https://cityio.media.mit.edu/api/table/grasbrook/cityIO_Gama_Hamburg

** Reproduce it **
Run this model 
https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/MicroSimulationFromMacroMobilityModel.gaml

Check the result here
https://cityio.media.mit.edu/api/table/grasbrook/cityIO_Gama_Hamburg

**Expected behavior**
A json list

**Desktop (please complete the following information):**
Master branch and latest build GAMA1.8_Continuous_withJDK_Mac_09.25.19_700ea7c
**Additional context**
I have a doubt wether or not this has been implemented in the master branch or if it is integrated in 1.9

**Comment by AlexisDrogoul** [comment]
Two things here, because your 'save' reflex is really fishy: 
- first you create a json file using strings, save it, then load it, and finally save the result in a new file. Why not creating the structure (map) directly in memory ? I'm a bit confused here.
- second, the file under which you save the results is `https://cityio.media.mit.edu/api/table/update/"+city_io_table+"/cityIO_Gama_"` (where `city_io_table` can presumably be Hamburg, etc.), which does not seem to correspond to the name you provide. 
Can you verify these two things first ?

**Comment by AlexisDrogoul** [comment]
Any update on this one ? I cant really test anything right now...

**Comment by agrignard** [comment]
Hi Alexis thatnks for the help.

Very sorry there has been a bad commit that I didn't check in the corresponding repo and indeed the name of the file was not the good one. So my bad this was not an issue.

However regarding your first comment I would be interested to have a better syntax that the one I have now I agree it' s a bit fishy. 

What can be less fishy than this ?

`````
string t;
		save "[" to: "result.json";
		ask people {
			t <- "{\n\"mode\": "+mode+",\n\"segments\": [";
			int curLoc<-0;
			loop l over: locs {
				
				point loc <- CRS_transform(l).location;
				if(curLoc<length(locs)-1){
				t <- t + "[" + loc.x + ", " + loc.y + ", " + l.z + "],\n";	
				}else{
				t <- t + "[" + loc.x + ", " + loc.y + ", " + l.z + "]\n";	
				}
				curLoc<-curLoc+1;
			}

			t <- t + "]\n}";
			if (int(self) < (length(people) - 1)) {
				t <- t + ",";
			}

			save t to: "result.json" rewrite: false;
		}

		save "]" to: "result.json" rewrite: false;
		file JsonFileResults <- json_file("./result.json");
        map<string, unknown> c <- JsonFileResults.contents;
		try{			
	  	  save(json_file("https://cityio.media.mit.edu/api/table/update/"+city_io_table+"/ABM", c));		
	  	}catch{
	  	  write #current_error + " Impossible to write to cityIO - Connection to Internet lost or cityIO is offline";	
	  	} 
`````

**Comment by AlexisDrogoul** [comment]
I mean, you create a file in json format "by hand" just to save it, then read it, then convert it into a map and save its contents as another json file... Why not simply create the map and save it ?

**Comment by agrignard** [comment]
Yes indeed I see what you mean I produce this temporary file to produce an exact geojson 

Using the map approach if I write 
``````
map<string, unknown> test;
test<+"path"::locs;
``````
it produces
`````
'path'::[{821.0808071679203,575.7220994206145,500.0}]]
``````
instead of 
``````
'path'::[[10.010473026257165,53.533094166794065]]
``````

**Comment by AlexisDrogoul** [comment]
Nothing prevents you from filling your map with lists of ordinates instead
of points...

Le jeu. 10 oct. 2019 à 00:26, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
In that case, `locs` should be a `list<list<float>>` instead of being a `list<point>`. Writing `test<+"path"::list<list<float>>(locs)` or `test<+"path"::(locs collect ([each.x, each.y, each.z]))` does not work ?

**Comment by AlexisDrogoul** [comment]
Any changes ? I close this.
