### ISSUE TITLE
Trying to run an Headless Model

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2895]
**NOTE: This issue doesn't concern the  1.8 Official release**

I don't know whether it's a problem form the headless or from the documentation in the website, however:

**Describe the bug**
Trying to Run a basic model in Headless following the website documentation here
https://gama-platform.github.io/wiki/Headless

So from a terminal I am going to the Gama folder 
`````
/Applications/GAMA1.8_Continuous_withJDK_Mac_09.25.19_700ea7c.app/Contents/headless
`````

Here is my headless xml to execute this model https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/MicroSimulationFromMacroMobilityModel.gaml
`````
<?xml version="1.0" encoding="UTF-8"?>
<Experiment_plan>
 <Simulation id="1" sourcePath="./../models/MicroSimulationFromMacroMobilityModel.gaml" finalStep="-1" experiment="Display">
  <Parameters>
  </Parameters>
  <Outputs>
  </Outputs>
 </Simulation>
</Experiment_plan>
``````

I then run this command line
``````
bash gama-headless.sh /Users/Arno/Projects/GitHub/CS_Simulation_GAMA/CS_CityScope_GAMA/headless/MicroABM.xml OutputHeasless
``````

and get this output
`````
gama-headless.sh
******************************************************************
* GAMA version 1.8                                               *
* http://gama-platform.org                                       *
* (c) 2007-2019 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
gama-headless.sh: line 28: ../jdk/bin/java: No such file or directory
`````

**Desktop (please complete the following information):**
 - El Capitan
 - GAMA1.8_Continuous_withJDK_Mac_09.25.19_700ea7c

**Comment by hqnghi88** [comment]
Should relate with #2890 , i revert the change for macos. Please test again after 20 mins.

**Comment by hqnghi88** [comment]
Hi Arnaud, 
Did you retry with new continuous build?

**Comment by ptaillandier** [comment]
With windows 10 (and GAMA release: GAMA1.8_Monthly_withJDK_Win_10.01.19_700ea7c), I had to modify the last line of the bat file (ugly modifications with explicit launcher version) to make it works:
call "../jdk/bin/java"  -cp "..\plugins\org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar" -Xms512m -Xmx%memory%  -Djava.awt.headless=true org.eclipse.core.launcher.Main  -application msi.gama.headless.id4 -data "%workDir%" !param!

**Comment by RoiArthurB** [comment]
@ptaillandier If you were talking about the code in the Batfile, the code is now fixed with the correct path. If you were following the README, it's normal to call the JDK binary with a relative path (the extracted GAMA doesn't add the JDK in the default path of your OS) :)

@agrignard I started to develop a Docker container for the GAMA-Platform in Headless usage (here on [Github](https://github.com/gama-platform/gama.docker) and [Docker Hub](https://hub.docker.com/r/gamaplatform/gama)). The container is a little heavy for now (I uploaded the whole GAMA project inside) but I'm working on light it up, and do not hesitate if you want to help :smile:

**Comment by RoiArthurB** [comment]
Tried on Mac with the monthly and default, it should be fixed. Feel free to reopen it if the bug remain to try to solve it ^^
