### ISSUE TITLE
geometry of cell in grid environment mismatch

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2896]
**Describe the bug**
geometry of cell in grid environment are not always aligned: neighbored cells could have no points in common (at least when testing for explicit coordinate, e.g. p1 = p2). Because of rounding sometime points of cell shape are equal, sometimes not, depending on cell size, number, number of neighbors and world shape.

**To Reproduce**
```
model GridGeometrymismatch

global {
	
	map dpl;
	map dpn;
	
	float world_length parameter:true init:100 min:99 max:101;
	float cell_size parameter:true init:4#m min:1#m max:10#m;
	int cell_number parameter:true init:20 min:10 max:50;
	float epsilon parameter:true init:0.0001;
	
	geometry shape <- square(world_length);
	
	init {
		list ap <- cell_l accumulate each.shape.points;
		loop p over:ap {
			point cp <- ap first_with (each distance_to p < epsilon and each != p);
			if not (cp = nil) {add cp at:p to:dpl;}
		}
		
		ap <- cell_n accumulate each.shape.points;
		loop p over:ap {
			point cp <- ap first_with (each distance_to p < epsilon and each != p);
			if not (cp = nil) {add cp at:p to:dpn;}
		}
	}
	
}

grid cell_l cell_width:cell_size cell_height:cell_size {}

grid cell_n width:cell_number height:cell_number {}

experiment xp type: gui {
	output {
	 	display "cell with length" { 
	 		graphics disclosed_points {
	 			loop p over:dpl {
	 				draw cross(0.1) at:p color:rnd_color(255);
	 			}
	 		}
	 	}
	 	display "cell with number" {
	 		graphics disclosed_points {
	 			loop p over:dpn {
	 				draw cross(0.1) at:p color:rnd_color(255);
	 			}
	 		}
	 	}
	}
}
```

**Expected behavior**
Build cell shape using explicit coordinate for points of neighbor cell to be equal

**Desktop (please complete the following information):**
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Well, it seems quite normal and not a bug as the equality operation suffers the same problems as the one in Java. Better use a precision operator to conduct such tests (like `with_precision`)

**Comment by chapuisk** [comment]
I agree, I was not sure to label it as a bug or request for improvement. It's totally understandable but if you build the grid with explicit coordinates you can give points for cell shape the exact same locations. The fact that points might or might not be equal is a bit confusing, even if totally understandable: for exemple, cell.shape inter one_of(cell.neighbors).shape might or might not be an empty geometry !

**Comment by AlexisDrogoul** [comment]
I tried to reproduce your issue but I can't. What are your two displays supposed to show ? The mismatched points, right ? They are both empty in my case. I cant find any point fulfilling your "mismatching" conditions. Can you share the results you obtain ? (i.e. either the displays or the maps). And can you check the value of the presence called "Tolerance for the comparison of points" ? It is 0.0 for me (the default).

**Comment by AlexisDrogoul** [comment]
To be sure, I created a small model, which basically tries to identify situations where the points of a cell would be different from the points of its neighbours. A bit like your model, but simpler.

```gaml
model GridGeometrymismatch


grid cells width:50 height:50 {
	int intersecting_points;
	
	init {
		intersecting_points <- length((neighbors accumulate (each.shape.points)) inter shape.points);
	}
}


experiment xp type: gui {
	output {
	 	display "Neighbors" { 
	 		graphics disclosed_points {
	 			loop p over:cells {
	 				draw p.shape color:#black;
	 				draw string(p.intersecting_points) color: #white at: p.location;
	 			}
	 		}
	 	}

	}
}
```

**Comment by chapuisk** [comment]
Dear @AlexisDrogoul ,
Using your model with 51x51 (give same kind of results for 60x60) width and/or height of the grid (which by the way will often be the case with GIS data) I have those kind of result:
![ResGrid_missmatch](https://user-images.githubusercontent.com/13599506/75057558-9acd3e80-54d9-11ea-91b5-5b5bff45ab29.PNG)
Best,
Kevin

**Comment by AlexisDrogoul** [comment]
Indeed,  you're right. When the dimensions are not equal and/or when they're not simple dividers of the environment dimensions, we can observe interesting patterns... 

![image](https://user-images.githubusercontent.com/579256/75082708-e6223400-554f-11ea-86ff-e7820a50305a.png)
