### ISSUE TITLE
Font size doesn't work in an overlay 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2898]
**Describe the bug**
I have some trouble to change the size of the font when using draw string in an overlay (both opengl and jav2D)

`````
draw string("xxx") at: { 10#px, 20#px } color: #white font: font("Helvetica", 20,"bold"); 
`````

The size font doesn't have any effect.

**To Reproduce**
GAMA 1.8

**Expected behavior**
Give a size font

**Comment by AlexisDrogoul** [comment]
Cant reproduce it.

```
draw type at: { 40#px, y + 4#px } color: # white font: font("Helvetica", 30, #bold);
```
![image](https://user-images.githubusercontent.com/579256/74538383-14fc4100-4f77-11ea-9908-b63643194a7d.png)
or
```
draw type at: { 40#px, y + 4#px } color: # white font: font("Helvetica", 12, #bold);
```
![image](https://user-images.githubusercontent.com/579256/74538427-2ba29800-4f77-11ea-9614-adada0cc51fc.png)

produce clearly different images.
