### ISSUE TITLE
Recompute_path facet (on grid?)

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2899]
**Describe the bug**
It seems that the recompute_path is not taken in account on a grid 

**To Reproduce**
I am writing this in this model 
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/models/Proxymix.gaml

`````
do goto target:the_target speed:10.0 on:cell where (each.is_wall=false) recompute_path:false;
`````

wether i set recompute_path to true or false it is always very long.

Then by only computing the path once

`````
currentPath<-path_between(cell where (each.is_wall=false),location,the_target);
``````

and call

``````
 do follow path: currentPath;	
``````
it is faster
**Expected behavior**
Compute the path only once

**Screenshots**

**Desktop (please complete the following information):**
GAMA 1.8 

**Additional context**

**Comment by benoitgaudou** [comment]
Hi,

First of all I have tested and checked whether the `recompute_path:` facet is taken into account in the `goto` on grid, and it is the case. 
In particular, the path is not recomputed.

I had a look at your model, and I noticed that the difference is not only that you use `path` + `follow` vs `goto`, but also that you do not compute the path for all the agents in the `follow` version. As a consequence you are comparing :
- a case where you try to do a `goto` for all your agents (and in many cases, they cannot reach their target)
- a case where you first compute some paths (only a few, one or two per step) and then you execute a follow on all the agents. When the path is `nil` the `follow` is be very quick.

I close the issue; feel free to reopen it if needed.
