### ISSUE TITLE
asc file format from QGIS

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2901]
**Describe the bug**

I just export an asc file from QGIS the header looks like this

`````
ncols        564
nrows        466
xllcorner    586695.747600000002
yllcorner    2278480.017399999779
dx           123.009257092199
dy           122.966236480688
``````
and GAMA doesn't recognize it as the header we use is 
``````
ncols        2258
nrows        1865
xllcorner    586695.747600000002
yllcorner    2278480.017362179235
cellsize     30.725075730735
``````

So one solution is to change it by hand but we can also take in account the 2 formats

**Comment by ptaillandier** [comment]
Hi,
The normal formatting of asc file is the second one: asc file are supposed to have square cells. However, GAMA should normally be able to manage both formats. If it is not working, it is a bug.

**Comment by rmejean** [comment]
Hi,
I confirm that the first asc file format (from QGIS) does not work, I still need to modify them by hand (to create a cellsize line).
