### ISSUE TITLE
pause and resume from gaml

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2904]
**Is your request related to a problem? Please describe.**
Would it be possible to have the possibility to pause and resume a simualtion. Write now it' possible to do 
`````
do pause;
`````

I'd like to be able to resume the simualtion in certain case (mainly through a user interaction )

**Describe the solution you'd like**
I guess it would be something like calling the play/pause button but from Gaml
`````
do resume or play
`````

**Comment by AlexisDrogoul** [comment]
Just do it by yourself, no ? Schedule your agents according to a boolean flag in the different species (and the simulation too), and use some conditions in the experiment to change its value.

**Comment by agrignard** [comment]
Nice! Can be useful when controlling a simulation with a physical interface
