### ISSUE TITLE
Skills moving: order of initialization of the heading variable

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2909]
**Describe the bug**
I have defined a species (`car`) with the skill `moving` (it thus gets the `heading` attribute).

The initialization of new `car` agents is set in 2 steps:
* in the inside block of the `create` statement
* in the `init` block of the species.

The issue comes when:
* `heading` is initialized in the `init` block
* the `location` of the agent is set in the `create`

My guess is that the initialization of the `location` has an effect on the initialization of the `heading` attribute...

**To Reproduce**
Here is an example: 
```
model TestInitLocationAndHeading

global {
	init {
		create car ;
		create car {
			heading <- 45.0;
		}

		create car2 {
			location <- any_location_in(world);
		}
		create car2 {
			location <- any_location_in(world);
			heading <- 90.0;
		}
	
		write sample(car collect each.heading);
		write sample(car2 collect each.heading);
		
	}
}

species car skills:[moving] {
	init {
		heading <- 90.0;
	}
}

species car2 skills: [moving] {
	init {
		heading <- 90.0;
	}	
}

experiment TestInitLocationAndHeading type: gui { }
```

**Expected behavior**

We can observe that in the case of the species `car` (when the location is not changed), the heading is set to the expected value (expected, i.e. the value that is given to it).
But in the case of car2, if the heading value is not set in the inner block of the create, its value is not the one given in the `init` block.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.8 release

**Comment by AlexisDrogoul** [comment]
Yes. For me it is not a bug but precisely what you describe: when the location is set (in the `create`, after the `init`) it changes the `heading`...

**Comment by AlexisDrogoul** [comment]
To be more specific: agents are created with a random location and a random heading. Setting a new location will change the heading, as if the agent was moving, and it would be difficult to change this behaviour in the skill.
