### ISSUE TITLE
[batch] simulation duration increases steadily over time

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#291]
**Is your request related to a problem? Please describe.**
I noticed that the duration of the exact same simulation was constantly increasing as it is simulated again in a batch experiment.
For example with this model:
```
/**
* Name: keepsim
* Based on the internal empty template. 
* Author: baptiste
* Tags: 
*/


model keepsim

global{
	float seed <- 3.1415;
	float start;
	init {
		start <- gama.machine_time;
	}
	reflex d {
		int size <- 100;
		let m <- matrix_with({size,size}, rnd(0,255));
		m <- shuffle(m);
		loop i from:0 to:size-1 {
			loop j from:0 to:size-1 {
				m[i,j] <- rnd(255);
			}
		}
	}
	
	reflex s when:cycle=99{
		save [int(self), gama.machine_time - start] to:"logs/simulationDuration.csv" rewrite:false;
	}
	
}

experiment simulationBase type: batch repeat:500 parallel:1 keep_simulations:false until:cycle=100;
```

The duration looks like this:
![image](https://github.com/user-attachments/assets/3d0af736-b5d3-42af-af18-a5196b6dfda0)
There's a clear linear-like increase in time

**Describe the improvement you'd like**
The duration of a same simulation should be somewhat constant in a batch experiment

**Comment by AlexisDrogoul** [comment]
I have the same phenomenon, but it does not seem linear in my case. 

<img width="574" alt="image" src="https://github.com/user-attachments/assets/1af40425-5d38-4cc5-9ff4-cb396732819e">

**Comment by lesquoyb** [comment]
It's weird, even if I run 1000 simulations instead of 500 I still end up with something that looks linear:
![image](https://github.com/user-attachments/assets/75ee6d8f-fcfd-41b1-a093-3f2e2df19aba)
Maybe the difference is cpu/os related ?

**Comment by AlexisDrogoul** [comment]
You will be happy to know that, thanks to your oral comments and the use of YourKit, I've been able to spot a clear bug. 

I've run it and the results seem ... quite good I think 😅

![Image 2024-08-26 13-33-36](https://github.com/user-attachments/assets/9f482741-1edf-4405-b049-bdbdf97d896c)

it is a one-line bug correction (I've also taken the occasion to comment some DEBUG.OUT statements that, surprisingly, take some time). I will try to make the whole PR thing to submit it.
