### ISSUE TITLE
Combine batch and  multi simulation

### ISSUE THREAD

**Issue by lutapp** [gama-platform/gama#2911]
Hello, 

i am new to GAMA, so maybe there is already a solution, but is it possible to combine batch-experiments with multi simulation? Something like that:

```
experiment batch type: batch repeat: 5 keep_seed: true until: empty(agent) {
	int nb_ag <- 10;

	init {
		loop times: 5 {
			create simulation with: [nb_students::nb_ag];
			nb_ag <- nb_ag + 1;
		}

	}

	reflex save {
		ask simulations {
			save cycle to: "results.csv" type: "csv" rewrite: false;
		}

	}

}
```

So that each of five simulations with specific parameter value samples runs five times? Something like the experiment plan in the headless mode but in the GAMA-IDE......

Thanks
Lukas

**Comment by benoitgaudou** [comment]
Dear Lukas,

First of all, welcome in the GAMA community!
I do not know if combining multi-simulation and batch works :-)

Concerning your question, in fact it seems to be equivalent to have an
exhaustive exploration with a parameter nb_ag that is explored between 10
and 15.

If you are thinking about a case that cannot be covered by the batch mode,
do not hesitate to ask more questions.

Cheers

Benoit

**Comment by AlexisDrogoul** [comment]
Hi, @benoitgaudou 's answer is correct. Batch processes **are** multi-simulations and there is no need to mix the two techniques. So I close this issue unless there is a specific exploration you can't do.
