### ISSUE TITLE
border:false in java2D has not effect?

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2913]
Hi 

I just noticed on a couple of models, that a polygon agent with a display facet `border:false` still shows a border. 

  Gama	1.7.0.201908130708	on Windows 10.

Not sure if this has been fixed recently.

Srirama

**Comment by hqnghi88** [comment]
how about empty:true?

**Comment by sriramab** [comment]
That is for "no fill" I think?

**Comment by hqnghi88** [comment]
ah sorry , you mean "no different colored border" like this? 
![image](https://user-images.githubusercontent.com/6105384/70060348-ed9f0480-1614-11ea-84f2-68e2b580a958.png)

**Comment by sriramab** [comment]
Yes, I do not want the yellow border on those black squares.

**Comment by hqnghi88** [comment]
"border, optional, expects any type in [rgb, bool] - if used with a color, represents the color of the geometry border. If set to false, expresses that no border should be drawn. If not set, the borders will be drawn using the color of the geometry."
simply remove the facet  or set it to the same color with polygon? (no idea with the false btw)

**Comment by sriramab** [comment]
Thats a good workaround, but previously border:false worked.

**Comment by hqnghi88** [comment]
So it seems the new version has new behavior, but i just tested and border is alway 1 pixel thickness, so "no border" is somehow as same as "same colored border" ?
BUT if you have a more detail case, please continue to describe it and make this an enhancement.
Thanks
