### ISSUE TITLE
Documentation (context window) on connect (in Network skill) refers to connect (in AgentDB species)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2915]
**Describe the bug**
The contextual documentation of the `connect` action defined in the `network` skills displays the documentation of the `connect` action of the `AgentDB` species.
 
**To Reproduce**
1. Open the model Network > 1 Get Started > 1 Simple Ping Pong.gaml
2. Put the mouse on the `connect` code in: 
```
		create PING_PONG with:[name::"ping",dest::"pong"]{
			do connect with_name:name;
		}
```
3. The documentation that appears is the one of the `connect` action of the `AgentDB` species.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - GAMA version: git, master branch
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
I've pushed a fix for this bug. Please test !

**Comment by benoitgaudou** [comment]
it works  !
