### ISSUE TITLE
The interactive console return buggy value

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2917]
**Describe the bug**
For somehow reasons, the interactive console (in the simulation perspective) returns some buggy results (results from previous command, nonsense results, etc).

The bug seems to be created when the console is looking across some large lists of agents or when copy-pasting text on it. However, the bug does not reproduce every time.

**To Reproduce**
Totally random 🙊🙈🤷

**Expected behavior**
Returning agents / properties requested every time

**Screenshots**
![Screenshot from 2019-12-12 10-53-19](https://user-images.githubusercontent.com/16764085/70681513-35d1bd00-1cce-11ea-866c-817119135b22.png)
_The command in the black box is a copy/paste which bugged, the intended text is the command just below_

![image](https://user-images.githubusercontent.com/16764085/70681993-f99f5c00-1ccf-11ea-9ec2-538823004188.png)
_I've restart the simulation after the screenshot above, wrote the first 3 lines by hand and just pressed the ⬆ arrow 1 time and execute the code displayed (which is the real code executed, but not the code displayed at the execution)_

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 🐧 / macOS Mojave 🍎
 - PC Model: Asus Republic of Gamers / MacBook Pro
 - GAMA version: git (probably all but not tested)
 - Java version: OpenJDK 1.8 / Oracle JDK 1.8
 - Graphics cards / Display system: NVIDIA GeForce GTX 1050 Ti Mobile

**Workaround**
The code executed is the previous line of code executed like below :
```
[1] gaml> corridor[2192].shape
nil
[2] gaml> corridor[2711].agents_on
polyline ([{748.278338593198,207.89073161548004,0.0},{724.1182492005173,273.08670051489025,0.0}])
    ^--- Result from the previous command (code 1)
[3] gaml> length(corridor[2711].agents_on)
[people(89)]
    ^--- Result from the previous command (code 2)
[4] gaml> fieohezhiofezhi
1
    ^--- Result from the previous command (code 3)
[5] gaml> corridor[2711].agents_on
> Error: Block definition does not begin or end correctly
    ^--- Error from the previous command (code 4)
```

So, it's the most annoying workaround ever, but it's possible to get some results that way

**Additional context**
The problem is not a memory bug I'm starting GAMA with 4Go of RAM (to 10Go max) and the software never fill that init amount.
Also I'm using the ESCAPE Project when I'm talking about "large lists of agents" 

_EDIT_ : Add screenshots & workaround

**Comment by RoiArthurB** [comment]
Got it !!
It's reproducible on a way : if you copy-paste a multi line code !!

If you do so it will execute it line by line and queue every following line :
```
gaml > polygon([
{10,10,10}, 
{110,10,10}, 
{110,110,10}, 
{10,110,10}, 
{10,10,110}, 
{110,10,110}, 
{110,110,110}, 
{10,110,110}]
)
> Error: Parenthesized expression do not begin or end correctly
    ^--- Try to execute `polygon([`

gaml> cycle
> Error: Block definition does not begin or end correctly
    ^--- Try to execute ` {10,10,10}, `

gaml>  <anything>
> Error: Block definition does not begin or end correctly
    ^--- Try to execute `{110,10,10}, `

gaml>  <anything>
> Error: Block definition does not begin or end correctly
    ^--- Try to execute `{110,110,10}, `

gaml>  <anything>
> Error: Block definition does not begin or end correctly
    ^--- Try to execute `{10,110,10}, `

gaml>  <anything>
> Error: Block definition does not begin or end correctly
    ^--- Try to execute `{10,10,110}, `

gaml>  <anything>
> Error: Block definition does not begin or end correctly
    ^--- Try to execute `{110,10,110}, `

gaml>  <anything>
> Error: Block definition does not begin or end correctly
    ^--- Try to execute `{110,110,110}, `

gaml> <anything>
> Error: Block definition does not begin or end correctly
    ^--- Try to execute `{10,110,110}]`

gaml>  <anything>
> Error: Parenthesized expression do not begin or end correctly
    ^--- Try to execute `)`

gaml>  <anything>
229
    ^--- Finally execute my "secondly" queued command `cycle`
```

Not sure if it's the only way to produce the bug, but that way makes the bug append every time

**Comment by AlexisDrogoul** [comment]
Yep. Probably the reason why. End-of-lines should be removed from the line before it is evaluated (as carriage returns / end-of-lines mean interpretation of the line).

**Comment by RoiArthurB** [comment]
But, if the console store all the followed lines, isn't it possible to execute them all at once? It will avoid having a buggy console after a bad copy-paste 🤔

What's sure is that the console do not handle multi-line well (if we want to erase a multi-line command, the cursor will stay on the last line but can erase every lines)

**Comment by AlexisDrogoul** [comment]
`What's sure is that the console do not handle multi-line well`. It **does not handle multi-lines command**, that's how it is designed.

**Comment by RoiArthurB** [comment]
Not an issue => Closing issue
