### ISSUE TITLE
Metadata from Batch processing

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2918]
Hi all,

I'm using Batch to do some explorations stuff and I want to same result during the simulation process and at the end of every simulation. 

For now, I'm using real time stamp ( [machine_time](https://gama-platform.github.io/wiki/GlobalSpecies#machine_time) ) to identify csv files, but it's not really friendly... Below 4 simulations executed in parallel 

```
╰─$ ll
total 105M
-rw-rw-r-- 1 roiarthurb roiarthurb 221 Thg 1 16 15:24 batchFinal1.576484661947E12.csv
-rw-rw-r-- 1 roiarthurb roiarthurb 209 Thg 1 16 15:24 batchFinal1.576484680151E12.csv
-rw-rw-r-- 1 roiarthurb roiarthurb 221 Thg 1 16 15:27 batchFinal1.576484809867E12.csv
-rw-rw-r-- 1 roiarthurb roiarthurb 209 Thg 1 16 15:27 batchFinal1.576484827183E12.csv
```

It would be way easier if I could used Run number, a unique simulation ID or some other kind of meta-data linked to the batch experiment.

![](https://gama-platform.github.io/resources/images/runningExperiments/batch_Information_bar.png)

I didn't find anything related on the GAMA documentation so I'll be glad if anyone could give me some information ^^

**Comment by AlexisDrogoul** [comment]
In my opinion, using the index of each simulation (`int(self)`in an `ask simulations`, for instance) should be enough. Otherwise, their `name`?
