### ISSUE TITLE
Multiple grid facets (if not every) in display do not work

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2923]
**Describe the bug**
At least elevation, triangulation, grayscale and texture facet to display grid have not any effect on visualization

**To Reproduce**
1. Go to Library models > Data > Data Importation > models > Grid DEM.gaml
2. Run the model

**Expected behavior**
Take into account the facets of grid to be displayed as requested (e.g. with elevation and grayscale)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PC Model: Dell Precision Tower 5810
 - GAMA version: 1.8 official release
 - Graphics cards / Display system: Quadra K420

**Additional context**
The issue does not shows up on my MacBook Pro (2019)

**Comment by AlexisDrogoul** [comment]
1. Does the last version exhibit the same behaviour ? 
2. Does the graphic card support OpenGL ? 
3. Is exactly the same version running on the MBP and the Dell ?

**Comment by chapuisk** [comment]
Continuous build (few hours ago) with JDK included does render elevation and other facets correctly @AlexisDrogoul thanks for pointing that out ! I let you close or not the issue if you want people that uses current release to be aware of the workaround in latest build.
