### ISSUE TITLE
csv graph

### ISSUE THREAD

**Issue by mayaaq** [gama-platform/gama#2926]
global {
	
	init { create node_agent from:csv_file( "../includes/artist_edges.csv",true) with:
			[ node_1::int(get("n1")),node_2::int(get("n2"))];	}
}
species node_agent parent:  graph_node edge_species:edge_n {
here } 
Where n1 and n2 are nodes list inside csv 
how can add edge between each row n1>n2 until end of file?

**Comment by benoitgaudou** [comment]
As for the previous issue you opened, this is not an issue but a question to the community.
As it, it should be asked on the related mailing list.

**Comment by mayaaq** [comment]
I can't enter to the group that you sent to me

**Comment by benoitgaudou** [comment]
you may need to be connected with your gmail account

**Comment by mayaaq** [comment]
I used gmail account, but it told me I should take permission from admin to enter this group ;)

**Comment by sriramab** [comment]
So take permission. All instructions are on the forum. Or you can search online or watch YouTube to learn how to join google groups.

**Comment by benoitgaudou** [comment]
It seems that the group was set for an unknown reason as private, so only members can access to it.
Could you please try again ?
Thank you for your feedback!

(note: a remark about your question: you will need to be clearer than the messages you have posted here, in order that some people can help you: a context (what you want to do from a general point of view, a clearer idea of your data file : a sample or the whole file, and your attempt).
