### ISSUE TITLE
No csv-benchmark-output is generated

### ISSUE THREAD

**Issue by lutapp** [gama-platform/gama#2929]
**Describe the bug**
No csv.-File is generated if you run the benchmark experiment from the benchmark example model (Library models > GAML Syntax > System > Benchmarking.gaml). I cannot close the experiment, only reload it. Only the folder "benchmarks" is generated. I tested the model on two different systems. Maybe i'm missing something?

**To Reproduce**

1. Open the benchmark example model
2. Start it

**Expected behavior**
A csv-output 

**Desktop (please complete the following information):**
 - OS: Win 10 Pro/Win 10 Edu
 - GAMA version: 1.8/1.8
 - Java version: 1.8/1.8

**Comment by benoitgaudou** [comment]
What do you mean by "I cannot close the experiment"?
I tried the model (on GAMA 1.8 release, on MAC OS), and did not have any problem...

<img width="493" alt="Screenshot 2020-02-12 at 11 10 03" src="https://user-images.githubusercontent.com/1555274/74299677-68f50300-4d88-11ea-8ac1-2a710191c203.png">

**Comment by lutapp** [comment]
When I click on the 'close icon' to close the experiment, the program does not respond and does nothing. But I can start the experiment again or reload it. I also get an output from the model....

![gama](https://user-images.githubusercontent.com/38818150/74324162-e1f35b00-4d86-11ea-897c-5ddf5e991459.JPG)

**Comment by benoitgaudou** [comment]
One reason that could provoke this behavior is that the creation of the file (containing the benchmark information) is not allowed. 
Could you try: (i) to run this model GAMA in a workspace that you are sure to have all the authorizations of access/write: choose a new workspace,  create a new project and copy-paste the model file of the benchmark.
(ii) to observe the access right of the created folder "benchmark"
(iii) run GAMA in a terminal (using command line), with the hope to see a related error message.

**Comment by lutapp** [comment]
I tested the model with a new workspace and from the command line, but not csv-File is generated and i also get no error messages. All users/user groups got read&write-permissions on the created folder.....

I also tested the model on a Ubuntu-VM and there it works

**Comment by hqnghi88** [comment]
Hi,
I confirm that the red-X did not work, and no csv created on win10, git version

**Comment by benoitgaudou** [comment]
Hi Nghhi,

Thanks for trying.
Could you test, in Java,to remove the date (hours/minute/second) in the
name of created file.
The intuition is that the name of the file contains unauthorized symbol
like ":".

Cheers

Benoit
