### ISSUE TITLE
How can I change 3D perspective？

### ISSUE THREAD

**Issue by Rinstein** [gama-platform/gama#2935]
When I make a 3D model, I can‘t find anyway to change perspective through my mouse or graphic button. I want to change perspective of observation, is there anyway? Thanks for your reply.

**Comment by Rinstein** [comment]
I have find the way to do that

**Comment by hqnghi88** [comment]
Which operating system are you using? On win , press Ctrl and mouse drag, on mac press cmd and mouse drag 
And you should post in google group, as it is not an issue here.
Thanks.

**Comment by Rinstein** [comment]
ok ,thank you
