### ISSUE TITLE
Test the existence of a folder

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2939]
**Is your request related to a problem? Please describe.**

In order to test if a file (non-folder) exists, it is possible to write something like:
```
string my_file <- "toto.txt";
if(!file(my_file).exists){  ...   }
```

But in the case of a folder, something like:
```
string my_folder <- "toto/";
if(!folder(my_folder).exists){  ... }
```
throws an Exception as the folder does not exist.

In addition, the structure: `if(!file(my_folder).exists){` works when the folder `my_folder`does not exist. But as soon as it exists, an exception is thrown expressing that:
`... is a fodler. Files can not overwrite folders.`

**Describe the solution you'd like**
That the following structure works: 
```
string my_folder <- "toto/";
if(!folder(my_folder).exists){  ... }
```

**Comment by AlexisDrogoul** [comment]
We already have the `file_exists` operator, so the best would be to create `folder_exists`, maybe ? A bit redundant with `.exists`, but well... I will try (1) to make `.exists` and to create the new operator.

**Comment by benoitgaudou** [comment]
Thanks. `folder_exists` resolves the issue.
Nevertheless:
- `folder_exists(my_folder)` and `folder(my_folder).exists` seems to be redundant as you said
- "files and folders manipulated this way are supposed to exist. ": as there is the plan to use files directly in the `save` statement, we cannot require that the file exists when we write something like: `save my_object to: file(my_file);" , right?

**Comment by AlexisDrogoul** [comment]
To clarify things: yes, there is a redundancy at the level of folders. But you are right, files are not supposed to always exist: they should when they are built using the 1 parameter argument, but whenever a contents is passed, they are not required to exist (obviously). Regarding `save`, the goal is to be able to write `save file("...", my_objects);`.
