### ISSUE TITLE
Datatype documentation very lean

### ISSUE THREAD

**Issue by natohutch** [gama-platform/gama#2942]
When looking at the datatype documentation only a small amount of information can be found on the attributes of different datatypes. Would it be possible in future to give a single page for each datatype, with plenty of information?

I ask this because at present I would like to know how to grab an individual column from a matrix, however I am unsure of the tools available. Currently I am just using a loop.

Thank you.

**Comment by benoitgaudou** [comment]
Dear Nathanael,

In fact, the documentation of data types is expected to present what is the data structures, how modeler can initialize it, what are the data type fields / attributes...
It is not expected to present the way to manipulate it, this is mainly the roles of operators.

I agree that it could be informative to add a link from the data type page toward the associated operators.

For examples, on matrices, you have several operators working on matrices
[https://gama-platform.github.io/wiki/OperatorsAA#matrix-related-operators](https://gama-platform.github.io/wiki/OperatorsAA#matrix-related-operators):

Matrix-related operators
-, /, ., *, +, append_horizontally, append_vertically, column_at, columns_list, determinant, eigenvalues, index_of, inverse, last_index_of, row_at, rows_list, shuffle, trace, transpose,

I think that the operator you are looking for is: column_at .

**Comment by natohutch** [comment]
Thanks for the help.
