### ISSUE TITLE
Problem of context (myself) in action

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2943]
**Describe the bug**
GAMA seems to be lost when myself is used in an action.
 
**To Reproduce**
```
model NewModel1

global {
	init {
		create cell;
		create dummy number: 2{
			cell a_cell <- one_of(cell); 
			ask a_cell {
				write self;
				write myself;
				do write_arg(myself);
			}
		}
	}
}

species dummy;
species cell {
	action write_arg(dummy a) {
		write a;
	}
}
experiment test_xp type: gui ;
```

Result obtained:
cell(0)
dummy(0)
dummy(0)
cell(0)
dummy(1)
**dummy(0)**

**Expected behavior**
cell(0)
dummy(0)
dummy(0)
cell(0)
dummy(1)
**dummy(1)**

**Desktop (please complete the following information):**
 - GAMA version: git

**Comment by YoucefSklab** [comment]
I have got the expected result with the release version. but not with the git one.
