### ISSUE TITLE
Fuzzy logic control implementation

### ISSUE THREAD

**Issue by ewirth** [gama-platform/gama#2944]
**Is your request related to a problem? Please describe.**
Since behavior often modeled with fuzzy logic, it could be significant development.

**Describe the solution you'd like**
A would like some built-in functions with fuzzy membership functions and evaluation can be done.

**Describe alternatives you've considered**
AnyLogic has this feature. This advantage moved me to try AnyLogic (which does not handle GeoTiff e.g.). 

**Additional context**
There is no ultimate agent-based environment yet, but this feature can a big plus. Since behavior often modeled with fuzzy logic.

**Comment by benoitgaudou** [comment]
Thank you for your interesting remark.

In order to help us to develop such a feature, do you have a description of your use case?
And basically how you would like to use Fuzzy logic in agents and even if you have a concrete case study to provide ideas.
(Even if you have ideas of new GAML syntaxes that you would like to use fuzzy logic ?)

**Comment by benoitgaudou** [comment]
An implementation has been added in the gama.experimental github.
This is definitely a first "lazy" version.
An example model is provided with the model.

Please send feedback whether it fits or not your needs.

The main aspect of Fuzzy Logic reasoning:
- all the FIS is defined in an external file, using the fcl standard
- agents need to have the `fuzzy_logic` skills
- at initialization, the FIS is initialized from the FCL file, and agents attributes are linked to FIS variables
- set the agent attribute and evaluate the FIS
- get output values

**Comment by ewirth** [comment]
Thank you so much,
i will test in the close future, and writing you.
Just a bit busy these days (project proposals with deadlines)...

**Comment by benoitgaudou** [comment]
I  close this issue as it  is inactive for a while.
Do not hesitate to reopen it if needed.
