### ISSUE TITLE
Lack of match_regex

### ISSUE THREAD

**Issue by natohutch** [gama-platform/gama#2946]
I currently need to parse some mqtt data coming in, and it is quite difficult to parse the data without regex. Currently I am having to use replace_regex in rather a hacky way to get what I want.

It would be great to add a simple function which takes in a string, and a regular expression, and simply outputs a list of matches to the regular expression.

Thank you :)

**Comment by AlexisDrogoul** [comment]
Good idea. The function you are describing certainly makes sense (with a different name, though: wouldn't `regex_matches` be more appropriate ?). We could also think of using this name to add one more branch to the `switch` statement. In addition to `match`, `match_one` and `match_between`, a `match_regex` would be quite interesting.

**Comment by natohutch** [comment]
Thanks for the update. Could you recommend an alternative method for in the meantime? Thanks

**Comment by AlexisDrogoul** [comment]
I have added the operator and the `match_regex` branch to `switch` to GAMA 1.8.2.

**Comment by AlexisDrogoul** [comment]
Closing it now (I've tested these two new additions in different scenarios). Reopen if something is missing ?
