### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by bachir513** [gama-platform/gama#2947]
hi everybody.
i just go to know gama software. i started programming. but currently i have a problem coding a forest fire. i started and created the tree cells, fire cell, road cell and others but i am struggling to programm the propagation of the fire and after the trees are on fire, let them be ashes at the next step.
Thanks

**Comment by benoitgaudou** [comment]
Hi,
First of all welcome in the GAMA community.
This is the place for issues related to GAMA, not the place for questions related to your models and helps.
For questions, you have: 
Mailing list
 - For Users
gama-platform@googlegroups.com
 - For Developers
gama-dev@googlegroups.com

And also, the model library contain many models! a fire model has been implemented in FireFighter.
