### ISSUE TITLE
Error when relaunching an experiment using MATLAB agent

### ISSUE THREAD

**Issue by natohutch** [gama-platform/gama#2948]
Launching an experiment with a MATLAB agent works the first time, but after closing the experiment will throw the following error, where mat is a species with parent agent_MATLAB.

3 occurrences in 3 agents at cycle 0: Error in the initialization of the path to Matlab.
in 
in create mat  {
	do eval (expression:'a = sin(5)');
	write self.value_of(variable_name:'a') ;
}

in init  {
	create mat  {
		do eval (expression:'a = sin(5)');
		write self.value_of(variable_name:'a') ;
	}

}

in agents mat0, Simulation 0, test0

**Comment by sriramab** [comment]
Cant say about MATLAB, but the commercial software I use does not allow two instances of license. This license runs a server, which takes a minute to close before I can relaunch it. May be something similar happening in your case?

**Comment by natohutch** [comment]
I tried waiting over an hour while working on something else, and still had the same error.

**Comment by benoitgaudou** [comment]
Could you check that there is no hidden process or task that continue to
run below?
By the way, which version of Matlab do you use ?

Cheers

Benoit

**Comment by natohutch** [comment]
Thanks Benoit,

I tried looking for running processes, I did find a matlab one running after exiting the simulation, however after exiting it and restarting it did not fix my problem.

After trying this again, I noticed there was no matlab process running.

The version I use is 2019a.

Thanks again :)

**Comment by natohutch** [comment]
I managed to find the template file, it works every time as it has a path to matlab.

Thanks for the help
