### ISSUE TITLE
Text editor read Only in the preferences

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2950]
**Is your request related to a problem? Please describe.**
In the context of public installation when ones need to start a simulation, I notice that there is a chance that the user accidentally modify the code (imagine just inserting a character anywhere would break the compilation)

**Describe the solution you'd like**
Would it be an option (even if I agree that very few people might use it) to have a preferences that would give the possibility to put the text editor in read only mode?

**Comment by agrignard** [comment]
Ok just I just tested it works great. I am ok to close this issue. Just a quick question Does it make sense to have it in the preferences ? 

It's ok for me as it is as it's a very specific use case.

**Comment by AlexisDrogoul** [comment]
Preferences would be a bit overkill for this task. It is really specific. OK. I close it !
