### ISSUE TITLE
Set seed in headless mode

### ISSUE THREAD

**Issue by romainreuillon** [gama-platform/gama#2953]
Dear GAMA devs,

I am developing GAMA OpenMOLE connector using the version of GAMA on the docker hub (https://hub.docker.com/r/gamaplatform/gama) and the headless mode: https://github.com/gama-platform/gama/wiki/Headless

In this context would have to set the seed used by GAMA while running the simulation in headless mode. Is there any way to provide the seed in headless mode (in the input.xml or through command line arguments...) ?

Romain

**Comment by romainreuillon** [comment]
I dug into the XML file and I found the seed attribute :)

**Comment by RoiArthurB** [comment]
Just to give the solution to people who may look that issue : 

You can set a seed value in the XML file, more precisely as an attribute of the _Simulaton_ tag as in the example below : 

```
<Experiment_plan>
    <Simulation experiment="prey_predatorExp" finalStep="1000" id="0" seed="1.0" sourcePath="/tmp/predatorPrey.gaml">
                                                                      ^^^^^^^^^^
        <Parameters>
            ...
        </Parameters>

        <Outputs>
            ...
        </Outputs>

    </Simulation>
</Experiment_plan>
```
