### ISSUE TITLE
A preference to set a model to run at startup

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2955]
I would like to have a option in Preference, to point to a model. If it is set, it will be open/launch the simulation when gama started. 
We already have the option to use command line/script for gama execution in console, but it is not friendly as we must type in command or create outside-gama shortcut to call it. 
So it could be nice for modelers/users to do it right in gama GUI/preference.

**Comment by AlexisDrogoul** [comment]
I have implemented a solution. Please test it and report !

**Comment by hqnghi88** [comment]
Dear Alexis,
I tested and it works very well. More over, i prefer a more friendly way if you accept to provide this feature (just like in some IDE, to set the default launching project...), we can add 1 item in this popup menu , ie "Set as auto-startup experiment"?
<img width="295" alt="image" src="https://user-images.githubusercontent.com/6105384/152683176-9fae0975-af43-41ae-91f4-8ed398ea72c1.png">
What do you think??

**Comment by AlexisDrogoul** [comment]
Very nice, yes, but I wouldnt be against some help in the development :)

**Comment by AlexisDrogoul** [comment]
Hi. Thanks for the implementation. One thing : I guess it would be necessary to also set the CORE_STARTUP_MODEL preference to true if it isn't already.

**Comment by hqnghi88** [comment]
Yes, i think about that, it should displayed as Set/Unset... item for setting the flag Core_startup_model.

**Comment by hqnghi88** [comment]
I changed to Set/Unset to set also the Core_startup_model flag.
