### ISSUE TITLE
masked_by operator throws Java error: illegal argument (IllegalArgumentExeption)

### ISSUE THREAD

**Issue by pcbarbosa** [gama-platform/gama#2956]
**Describe the bug**
I implemented masked_by operator in my building evacuation model for the purpose of detecting exits, nodes, etc. using a circle that is masked_by a GIS shapefile of walls. It throws an error IllegalArgumentException which says that "This method does not support GeometryCollection arguments".

**To Reproduce**
1. Import a GIS shapefile that will be used as a mask
2. Implement masked_by by drawing a circle which is to be masked by the imported GIS shapefile
3. Run the experiment

**Expected behavior**
I expect that the imported GIS shapefile can mask the drawn circle even though it is a geometry collection, just as how the sample code "Continuous Field of Vision" works.

**Desktop**
 - OS: Windows 7 x64
 - GAMA version: 1.8 (stable) with JDK
 - Graphics cards / Display system: AMD Radeon R7

**Comment by benoitgaudou** [comment]
Could you add your model to this issue, to reproduce the issue.

**Comment by pcbarbosa** [comment]
Tried it again and it suddenly worked. Will see what went wrong previously. Thank you for the response @benoitgaudou !
