### ISSUE TITLE
imported 3D shapefiles not being drawn in GAMA 1.8 but is drawn fine in GAMA 1.6.1

### ISSUE THREAD

**Issue by pcbarbosa** [gama-platform/gama#2957]
Hello! I am working on a building evacuation model with multilevel floors connected with a network of paths. I tried to import my 3D shapefiles (which I made from ArcGIS ArcScene) in GAMA 1.8 with JDK (stable version) but it does not draw the shape at all. I tried downloading GAMA 1.6.1 from the website and opened the model in this version. It was able to draw the shapefiles I imported.

Is the feature drawing 3D shapefiles not supported anymore? Or is there a way (like the syntax, etc) on how to be able to draw 3D shapefiles in GAMA 1.8? Thank you

**Comment by benoitgaudou** [comment]
Could you share your model and data, to be able to reproduce the issue.

**Comment by pcbarbosa** [comment]
Here is my code:

[sample_sample.zip](https://github.com/gama-platform/gama/files/4347062/sample_sample.zip)

**Comment by benoitgaudou** [comment]
In your code, pay attention to the redefinition of the shape of the global agent:

you need to replace the line:
```
	geometry space <- envelope(building_floor);
```
by
```
	geometry shape <- envelope(building_floor);
```

In addition, you should look at the warning and solve them.

**Comment by pcbarbosa** [comment]
Thank you for that! I tried replacing space with shape and got the shapefile drawn, but it seems to be only in 2D (seems projected in one plane) as can be seen in this screenshot
![image](https://user-images.githubusercontent.com/32195860/76930634-ed0b4f00-6921-11ea-9d97-d7e321bf1b66.png)

In GAMA 1.6.1 it displays like this:
![image](https://user-images.githubusercontent.com/32195860/76930677-014f4c00-6922-11ea-86df-24e9d430c6b8.png)

**Comment by benoitgaudou** [comment]
When looking at your data, the z value is 0.0, so the floors are displayed all at the same elevation: 

<img width="1616" alt="Screenshot 2020-03-18 at 13 15 28" src="https://user-images.githubusercontent.com/1555274/76931238-d281a780-691a-11ea-9b2b-874216def0c1.png">

So you have to either change your data, or update either the display of the shape of your agents by translating them vertically, ssuch as:

```
species floors {
	aspect default {
		draw shape translated_by {0,0,int(self)} color: #gray;
	}
}
```

or
```
create floors from: building_floor {
	shape <- shape translated_by {0,0, 10* int(self)};
}
```

**Comment by hqnghi88** [comment]
hi,
what make me surprise is that if it was the same code, it would never displayed as layered in 1.6.1 (without any translate, add_z....). what was wrong?

**Comment by pcbarbosa** [comment]
I appreciate all of your responses!

I agree with hqnghi88, how come version 1.6.1 can display the same model just fine?

By the way, tried doing your suggestion benoitgaudo, it resulted to this (as if each attribute of each shapefile was translated one by one)
![image](https://user-images.githubusercontent.com/32195860/76934762-b38b1180-692a-11ea-8813-eba06ee186d0.png)

**Comment by ptaillandier** [comment]
Hi,

I have the solution and an explanation :) .
In GAMA 1.8, by default, the third is not taken into account when loading a
shapefile (because of numerous bugs due to 3D in some shapefiles), so you
just have to say that you want to take it into account. How to do that? It
is very simple, just write (for all your shapefile):
file building_exit <- shape_file("../includes/Exits.shp", true);
instead of
file building_exit <- file("../includes/Exits.shp");

Cheers,

Patrick

**Comment by pcbarbosa** [comment]
It worked! Thank you very much sir @ptaillandier !

**Comment by hqnghi88** [comment]
Very pleased, big heart.

**Comment by hqnghi88** [comment]
@pcbarbosa as Patrick said, you will have some issue if still use the old (updated) syntax, so Benoit's solution is much more stable
