### ISSUE TITLE
2 issues: (1) Agents not being drawn on their assigned location, (2) Some agents not doing reflex

### ISSUE THREAD

**Issue by pcbarbosa** [gama-platform/gama#2958]
Hello! I would like to seek your guidance with 2 of the issues I encountered in my game (evacuation) model.

First is that the agents are not being drawn in their assigned locations (I used a 3D shapefile as their spawn locations).

Second is that some of the agents are not doing their reflex, which is to do goto to an assigned target on a defined graph from an imported shapefile (network of lines).

Here is my model:
[sample_sample.zip](https://github.com/gama-platform/gama/files/4355097/sample_sample.zip)

**Comment by benoitgaudou** [comment]
Hi, 
Few remarks:
- this is the place for issues about GAMA, not to discuss models. 
Please repost your message on the GAMA mailing list.
https://groups.google.com/forum/#!forum/gama-platform
- Your questions are too vague: you should mention   what you get and what you are expecting.
  - As an example, saying "agents are not drawn in their assigned locations". What is the issue ? Are they located in right {x,y} coordinates but not z ... ? Have you check that there location is really the one you are expected it is ? ....
  - For your second point, once again is it the reflex that is not executed as a whole ? or is the reflex executed, but not the goto action ? or is the goto action executed, but the agent does not move ? ...
