### ISSUE TITLE
to_GAMA_CRS not working

### ISSUE THREAD

**Issue by natohutch** [gama-platform/gama#2959]
I have a number of coordinates in a csv file, which I would like to instantiate agents from at the particular coordinates. Doing so allows for greater flexibility than manually creating a shape file and then importing it.

Using CRS_transform correctly converts the coordinate pairs to their values in the project CRS, however when using to_GAMA_CRS, I simply get the same value as CRS_transform with the x coordinate's sign flipped.

Am I using the function correctly, and there is a bug? Or is this function supposed to be used in a different manner.

Thank you,
Nathanael

**Comment by mayeulk** [comment]
Hello Nathanael, I guess if you manage to give a short reproducible example (see http://sscce.org/ for advice), it would help answer.

**Comment by natohutch** [comment]
Sorry for the long delay.
I've tried to get as close as possible without attaching any files, I can provide links if anyone wants to test using actual files as well.
Basically the goal is to take the GPS coordinates given to the sensor to set it's location, somewhere inside the shape of the world. However the location it ends up being set to is the coordinates in the projection of the shape used to set the world shape, i.e. what you see as the coordinates in QGIS.
I couldn't actually set the CRS of the world using the square, however the logic still makes sense.

Hopefully someone can tell me if I've done something wrong, and the correct way to do what I'm trying if so.

Thank you

`model gis_error

global {
	//file catchments_gis <- file("../../../data/model/catchment_shape.shp");
	//geometry shape <- envelope(catchments_gis);
	
	geometry shape <- CRS_transform(square(10000), "EPSG:28356");
	
	init {
		create catchment from: [square(1000) at_location {1500, 1000}];
		create sensor {
			lat <- -34.358048;
			lon <- 150.894627;
			location <- CRS_transform({lat, lon});
			
		}
	}
}

species catchment {
	
	aspect default {
		draw shape;
	}
}

species sensor {
	float lat;
	float lon;
	geometry shape <- circle(1000);
	
	aspect default {
		draw shape;
	}
}

experiment Visualise type: gui{
	output {
		display main type: opengl{
			species catchment;
			species sensor;
		}
	}
}`

**Comment by ptaillandier** [comment]
Hi,

It would be easier to test with the shapefile. Some remarks:

   - you should not use : "geometry shape <- CRS_transform(square(10000),
   "EPSG:28356");", but simply  "geometry shape <- square(10000);" ou using a
   shapefile to initialize the shape of the world.
   - rather than using "location <- CRS_transform({lat, lon});", you should
   use "location <- to_GAMA_CRS({lat, lon}, "EPSG:28356").location;"

Cheers,

Patrick

**Comment by natohutch** [comment]
I simply put the square in as a placeholder for the shape file linked here: [http://s000.tinyupload.com/index.php?file_id=01820159516343923661](url)
I've used both CRS_transform and to_GAMA_CRS, neither of them work. Also supplying an EPSG projection does not seem to change anything.

**Comment by ptaillandier** [comment]
Hi,

The link doesn't work...

Patrick

**Comment by natohutch** [comment]
[Fixed :)](http://s000.tinyupload.com/index.php?file_id=01820159516343923661)

**Comment by ptaillandier** [comment]
With this code, it works (but the point {150,8 -34.35} is not in the
catchment area - confirmed when verifying by using QGIS).


model testCRS

global {
file catchments_gis <- file("../includes/catchment_shape.shp");
geometry shape <- envelope(catchments_gis);

init {
create catchment from: catchments_gis;
create sensor {
lat <- -34.358048;
lon <- 150.894627;
location <- to_GAMA_CRS({lon, lat}, "EPSG:4326").location; // you have to
give the EPSG of the coordinate.
}

}

}

species catchment {

aspect default {
draw shape color: #gray border: #black;
}

}

species sensor {
float lat;
float lon;

aspect default {
draw circle(1000) color: #red;
}

}

experiment Visualise type: gui {
output {
display main type: opengl {
species catchment;
species sensor;
}

}

}

**Comment by natohutch** [comment]
The shape file is projected using EPSG:28356, which I did also project specifying that in the code as another alternative. However with our without it, there was no difference for me. What I found happened was the sensor was placed at the projection coordinates which are the same as in QGIS appx 300000, 6200000, but the catchments were not projected in that location. Is there anywhere else you could see there being a problem? Happy to provide screenshots etc.

**Comment by ptaillandier** [comment]
To be honest, I not sure to understand your problem.
GAMA projects all the data into its own CRS (if the data are already
projected, GAMA just applies a translation and inverses the y-axis). The
to_GAMA_CRS allows to project a geometry or a point into this CRS as well
(I just had to specify the origin CRS of the point/geometry - which is
WGS84 in your case).

See my screenshot below : GAMA gives exactly the same result as QGIS.

a) with GAMA
[image: GAMA.PNG]

b) With QGIS
[image: QGIS.PNG]

**Comment by natohutch** [comment]
Sorry I can't see your images

**Comment by ptaillandier** [comment]
Here the images:
with GAMA (with GAMA CRS): 
![GAMA](https://user-images.githubusercontent.com/1506077/79834010-9ffd1b80-83ac-11ea-9f37-4429a8389431.PNG)

with QGIS (with WGS84 CRS):
![QGIS](https://user-images.githubusercontent.com/1506077/79834026-a8555680-83ac-11ea-974c-b420a819f1d4.PNG)

**Comment by AlexisDrogoul** [comment]
I propose we close this issue here, unless there are some unanswered points, in which case feel free to reopen it
