### ISSUE TITLE
Same variable names for tutorial doc and gaml (*_transfert)

### ISSUE THREAD

**Issue by mayeulk** [gama-platform/gama#2960]
In prey_predator tutorial, there is a discrepancy sometimes between the variable names for:
- tutorial documentation :  energy_transfer, max_transfer
- and gaml : energy_transfert, max_transfert
See:
https://github.com/gama-platform/gama/wiki/PredatorPrey_step3
https://github.com/gama-platform/gama/blob/04000ca513629beb51a32e750a47b6bfad2cff3a/msi.gama.models/models/Tutorials/Predator%20Prey/models/Model%2003.gaml

This could be corrected manually. I'd suggest (for the sake of coherence) the English "transfer" instead of the French "transfert". I can help with sed's regex if needed. Here's a pointer: https://stackoverflow.com/questions/1585170/how-to-find-and-replace-all-occurrences-of-a-string-recursively-in-a-directory-t
Also, if it is possible to extract the variable names from the code, a simple grep on the wiki could help check semi-automatically that the correct spelling is used.
(PS: Thanks a lot for these great tutos)

**Comment by benoitgaudou** [comment]
Dear Mayeul,

I just wanted to thank you for your email, and acknowledge we get your
remarks.
We will definitely take them into account, but perhaps rather after the
CoVid19 pandemic.

By the way, if you are available and wish to help us to improve the
documentation, you are more than welcome !
The pages of the tutorials come from the wiki of the gama github : so
anybody can modify them easily (the website will be generated fro it).
https://github.com/gama-platform/gama/wiki

Cheers

Benoit

Le mer. 25 mars 2020 à 15:33, Mayeul Kauffmann <notifications@github.com> a
écrit :

**Comment by benoitgaudou** [comment]
Addressed with manual method.
