### ISSUE TITLE
Extends before and after operators to test dates other than current_date

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2961]
**Describe the bug**
``before`` and ``after`` operators for dates seems broken

**To Reproduce**
Run this simple model:
```
global {
	
	date starting_date <- #now;
	
	init {
		
		date d1 <- date([current_date.year,1,1]);
		date d2 <- date([current_date.year,6,1]);
		
		write sample(d1);
		write sample(d2);
		write sample(current_date);
		
		write "Should be true: "+sample(d1 before current_date);
		write "Should be true: "+sample(d2 after d1);
		write "Should be true: "+sample(current_date between (d1,d2));
		
	}
	
}

experiment xp {}
```

**Expected behavior**
Fix the operator

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: git and monthly build

**Comment by chapuisk** [comment]
I may have miss something ... looking at the code, it seems that ``after`` and ``before`` are not meant to test if a date is after or before another one, but always after or before current_date ... This is rather strange, even more if Gama does allow you to write things like ``if date1 after date2 {do something_cool;}``

**Comment by AlexisDrogoul** [comment]
No we don't need to extend anything. `before` and  `after` are designed to build frequency arguments to be used with `every:`. It is maybe not explicit in the documentation (but I think it is stated somewhere), like `until` or `since`. Rather than these operators, use `>` and `<` comparison operators.
