### ISSUE TITLE
Eclipse DSL 2020-03 incompatible with GAMA Git

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2964]
**Describe the bug**
The last update of Eclipse DSL is not compatible with the Git version of GAMA

**To Reproduce**
1. Install the last Eclipse DSL 2020-03 version
2. Import GAMA Git
3. Try to build or clear project

**Expected behavior**
Compile GAMA Git

**Screenshots**
![image](https://user-images.githubusercontent.com/16764085/78131543-730cb700-7445-11ea-8576-3a6ef75fffed.png)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - PC Model: Dell XPS
 - GAMA version: git
 - Java version: 1.8
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**
https://github.com/eclipse/che/issues/13179 Here's a similar issue which advice to switch to latest version of JDK to fix the issue

**Comment by AlexisDrogoul** [comment]
The https://github.com/gama-platform/gama/tree/GAMA_2.0 branch is compatible with it (and JDK 11).
