### ISSUE TITLE
Can't change the color of the labels on histogram chart

### ISSUE THREAD

**Issue by DAM-Philippon** [gama-platform/gama#2965]
**Describe the bug**
Hi, 
I'm trying to get a histogram chart to have white font for the labels of the bars. With series plot, it is not a problem, a simple color facet to #white in the chart statement does the trick. However, it does not for histogram charts. 

**To Reproduce**
You can use the following model to see what I'm talking about: 

```
model error_example

/* Insert your model definition here */

global
{
	int nb_1 <- 15;
	int nb_2 <- 25;
}


experiment test type:gui
{
	output
	{
		display "chart"
		{
			chart "histo" type:histogram
			{
				data "One" value: nb_1 color:#gray;
				data "Two" value: nb_2 color:#gray;
			}
		}
		display "chart_black"
		{
			chart "histo" type:histogram background:#black color:#white axes: #white
			{
				data "One" value: nb_1 color:#gray;
				data "Two" value: nb_2 color:#gray;
			}
		}
	}
}
```

**Expected behavior**
The "One" and "Two" labels should be in white in the black background display. 

**Screenshots**
![okay](https://user-images.githubusercontent.com/61393694/78340914-1209ee00-75c1-11ea-8808-7ccf4cc89b0f.PNG)
![not_okay](https://user-images.githubusercontent.com/61393694/78340919-133b1b00-75c1-11ea-989c-a3b8cb9dccb5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - GAMA version: Continuous build

**Comment by pcaillou** [comment]
Solved with commit https://github.com/gama-platform/gama/commit/5e41f06ad729db5d660ee42a6fd5eba099ed67cf
