### ISSUE TITLE
Possibility to remove the legend in charts

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2966]
Sometimes, it is interesting to not display the legend of a chart (in particular when displaying the values of an attribute of all the agents). I do not think it is possible right now (or not documented)

**Comment by pcaillou** [comment]
Hi Patrick,

(Almost) everything is possible with charts :)
Documented... Less...
   series_label_position:none
Seems to fit your needs, or do you meen something else?

for example:

  display "chart"
{
chart "histo" type:series series_label_position:none
{
data "One" value: nb_1 color:#gray;
data "Two" value: nb_2 color:#gray;
}
}

Philippe

Le sam. 4 avr. 2020 à 19:14, ptaillandier <notifications@github.com> a
écrit :

**Comment by ptaillandier** [comment]
Perfect! But it should be documented ;) .
