### ISSUE TITLE
Find references  does not work (Ctrl+Shift+G)

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2969]
In the version git of gama, working on a model with some import ,  i cannot find the references from imported model of variable,action... by pressing Ctrl + shift +G anymore, it just find the element in current opened model.
Gama git, jdk 1.8, win 10

**Comment by AlexisDrogoul** [comment]
Does it work on the release version ?

**Comment by hqnghi88** [comment]
Sorry, it takes time to download with the current network connection of vietnam... It did not work in release version (official release and CI ). And also, the remane (factoring) doesnt work as it link with finding references.

**Comment by AlexisDrogoul** [comment]
Seems this issue has come back...

**Comment by hqnghi88** [comment]
Yes it is

**Comment by AlexisDrogoul** [comment]
And I really cant find where it comes from. Was it really working when I closed the issue ? I have doubts now, because none of the changes from then have any impact on the compilation ...  I really don't get it.

**Comment by hqnghi88** [comment]
Sorry, you are right, it was never fixed, i rebuilt binary from the commit above and no changes, no fixes was done.
