### ISSUE TITLE
transparency facet has Inversed effect with its documentation

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2971]
In display , overlay and species support transparency facet and documented:
transparency, optional, expects float - the transparency rate of the agents (between 0 and 1, 1 means no transparency)

using overlay with transparency:1 , it shows no transparent.
But for species layer, it is inversed, 0 for no transparent and 1 for full transparent.
I remember some old notion about opacity and transparency , so may be the code is not up-to-date with documentation??

**Comment by AlexisDrogoul** [comment]
Right. I've harmonised all of this, so that 0 means opaque and 1 fully transparent. The doc has been harmonised too.
