### ISSUE TITLE
Index_of for multiple items, not just the first or last

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2973]
Hi

Currently, the `index_of `operator gives the index of first occurrence of a match. I would like to request a variation, where all occurrences satisfying the expression inside `index_of` are returned. 

I have multiple lists of the same number of elements and I would like to extract same(i'th) element from each list based on a condition satisfied in one base list. This is currently not possible. 

For example, If my condition expression in `index_of` returns indices 2,22,48, I would like to extract 2nd, 22nd and 48th element of all other lists. 

If it is not so difficult to implement, I would like to request this please, because it will help in me to not make many loops. 

I marked it high priority, because it is critical for me, please lower it if you feel so.

Thank you.

**Comment by sriramab** [comment]
I am open to any workarounds if they exist

**Comment by benoitgaudou** [comment]
Hi Srirama,

I am not sure to get exactly what you want.

If I am not wrong, you would like a new operator, let's name it `indexes_of`, with such behavior:
`[1,2,3,1,2,3,1] indexes_of(1)` --> `[0,3,6]`

For the second part of your question (with multiple lists), it is not clear to me if you want new operators or if it is only to illustrate your request?

Cheers

Benoti

**Comment by sriramab** [comment]
Hi Benoit, 

Yes you are correct in interpreting my question. :)

I primarily request a new operator for lists that gives indices of elements satisfying a condition. 

The second part is largely to explain my use case. 

But if you look at it, GAML does not have `list slicing` as some other popular languages have. Therefore, Modeller has to do a lot of looping which is error prone.  

So, both first and second part involve lot of looping and my request is to have an operator that reduces looping for the first part of the problem.

**Comment by benoitgaudou** [comment]
Hi Srirama,
I just added the operator `all_indexes_of` operator (on lists only for the moment): 
```
		test "all_indexes_of" {
			list var0 <- [1,2,3,1,2,3] all_indexes_of 1; 	// var0 equals [0,3]
			assert var0 = [0,3]; 
			list var1 <- [1,2,3,1,2,3] all_indexes_of 4; 	// var1 equals []
			assert var1 = []; 

		}
```

About your other remarks, for list slicing, you can use the `copy_between` operator right ?

Now to get elements from a list given a list of indexes, you can use a `collect`:

```
list l <- [1,2,3,4,1,2,3,4];
list l2 <- .... ;
list<int> indexes <- l all_indexes_of(4);
list res <- indexes collect(l2[each]);
```

**Comment by sriramab** [comment]
Thank you so much Benoit. I will check the new build when it is released tmrw.
