### ISSUE TITLE
Headless scrap virtual output

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2976]
**Describe the bug**
When generating an XML file for the headless with the headless, GAMA add virtual outputs as _real_ outputs and make the headless executing failing every time. They will be scrapped from current experiment or imported one.

**To Reproduce**
1. Simple testing model
```
model badImport
global {}
experiment exp type: gui {
	output {
		display "Main" virtual: true {}
	}
}
```

2. Generate headless XML
```
$ ./gama-headless.sh -xml exp ~/Documents/Dev/GAML-scripts/models/badImport.gaml /tmp/test.xml
```
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Experiment_plan>
	<Simulation experiment="exp" finalStep="1000" id="0" seed="1.0" sourcePath="/home/roiarthurb/Documents/Dev/GAML-scripts/models/badImport.gaml">
		<Parameters/>
		<Outputs>
			<Output framerate="1" id="0" name="Main"/>
		</Outputs>
	</Simulation>
</Experiment_plan>
```
3. Start the headless with the new XML
```
$ ./gama-headless.sh -hpc 1 /tmp/test.xml /tmp/output
```
4. See error at the first try to write output data
```
******************************************************************
* GAMA version 1.8                                               *
* http://gama-platform.org                                       *
* (c) 2007-2019 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> JAI/ImageIO subsystem activated
Number of cpus used:1 (available: 8)
.
 The simulation has stopped before the end due to the following exception: 
Output unresolved
	at msi.gama.runtime.exceptions.GamaRuntimeException.error(GamaRuntimeException.java:62)
	at msi.gama.headless.core.RichExperiment.getRichOutput(RichExperiment.java:45)
	at msi.gama.headless.job.ExperimentJob.exportVariables(ExperimentJob.java:355)
	at msi.gama.headless.job.ExperimentJob.doStep(ExperimentJob.java:337)
	at msi.gama.headless.job.ExperimentJob.play(ExperimentJob.java:313)
	at msi.gama.headless.job.ExperimentJob.playAndDispose(ExperimentJob.java:284)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:240)
```

**Expected behavior**
Having the headless XML generator not scrapping virtual outputs.

**Desktop (please complete the following information):**
 - OS: Linux
 - GAMA version: git
 - Java version: 1.8

**Additional context**
A workaround is to clean the generated file by hand

**Comment by AlexisDrogoul** [comment]
What do you mean by "not scrapping" ? Do you want to include them in the XML or not ?

**Comment by RoiArthurB** [comment]
Not include them because it makes the headless crash (but if they are _parent_ of another display/output/else without any modification, it works)

**Comment by AlexisDrogoul** [comment]
OK. So you want to scrap them ;)

**Comment by RoiArthurB** [comment]
I just don't want to have a line in the generated XML for gaml output definition with the `virtual: true` facet setting

**Comment by AlexisDrogoul** [comment]
I've pushed a possible fix. Please test it !

**Comment by RoiArthurB** [comment]
It's fixed, well done ! :D
