### ISSUE TITLE
user_input with min and max facets bypass user command in user control architecture

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2978]
**Describe the bug**
When using both min and max facets in user_input to ask user to choose within a range, the user control architecture (first, last and only) run out of user control : i.e. user command panel is blinking and user is not requested values anymore and regular cycles goes indefinitely 

**To Reproduce**
Here is a very simple model to test :
````
global {
	
	bool test_bug parameter:true init:false;
	
	init{
		create dummy;
	}
}

species dummy control: user_last {
	
	user_panel "init" initial: true {
      transition to: "dummy user" when: test_bug;
      transition to: "less dummy" when: !test_bug;
   }
	
	user_panel "dummy user"  {
		user_command "dummy command" color: #red {
	  		user_input "dummy decision" returns: dum slider:true type:float min:0 max:5;
	  	}  
	  	transition to: "init" when: true;
	}
	
	user_panel "less dummy" {
		user_command "not so dummy command" color: #green {
			user_input "dummy decision" returns: dum slider:true type:float among:[0,1,2,3,4,5];
		}
		transition to: "init" when: true;
	}
	
}

experiment dummy_xp { output {	} }
````

**Expected behavior**
Be able to set min and max value with sliders and still makes it possible to actually control agents

**Desktop (please complete the following information):**
 - OS: Catalina
 - GAMA version: latest build downloaded the 28 of march

**Comment by AlexisDrogoul** [comment]
Well, the main reason is that no initial value is provided, which creates a NPE when the slider is supposed to be computed... I don't know which initial value to compute in that case however. The minimum ? The maximum ? The middle ?
