### ISSUE TITLE
possibility to save attributes of a list of geometries into a shapefile

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2982]
**Is your request related to a problem? Please describe.**
For the moment, when saving agents or list of geometries, the modeler has to specify the explicit list of attributes to save (using either the with or attributes facets).

It could be very interesting to just have to specify in a way that we want to save all the attributes of the agents/geometries.

**Describe the solution you'd like**
A solution that was used for csv file (no idea if it still working) is to use an empty map for the facet attributes to specify that we want all the attributes of the agents/geometries. But, because of the validator, I think it is not possible for the moment to write something like:
save people type:shp to:"people.shp" attributes:[]; 

There is also the question of set of geometries with different attribute list - in this case, a first should be to define the complete list of existing attributes in the list of geometries.

**Comment by hqnghi88** [comment]
How about save all the attributes by default, withou attributes facet?

**Comment by AlexisDrogoul** [comment]
Isntit possible to get all the attributes of the agents in a list by interrogating their species? Or by using an expression like remove_duplicates((the_agents accumulate ((each as map)).keys)?

**Comment by ptaillandier** [comment]
Getting the list of attributes is possible (you can use your solution or use "attributes" of shape - see below), but right now it is not possible to use with the attributes facet (because of the validator ?)

Here a simple model to test:
```
model bugsaveallatt
global {
	init {
		create simple_ag;
		list<string> atts <- remove_duplicates(simple_ag accumulate ((each as map)).keys);
		write "solution1:" + atts;
		list<string> atts2 <- first(simple_ag).shape.attributes.keys;
		write "solution2:" + atts2;
                //how to use these lists in the save statement?
		save simple_ag type: shp to: "simple_ag.shp" attributes: ...;
	}	
}

species simple_ag {
	int int_att <- 2;
	float float_att <- 2.0;
	string string_att <- "2";
}

experiment test_xp ;
```

**Comment by AlexisDrogoul** [comment]
OK. So I see two things to do if you agree: 

- one is to relax the constraints on the `attributes:` facet to accept list of arbitrary strings
- second is to implement the solution of @hqnghi88 , which makes sense: if passed an empty list, no attributes shall be saved, if not defined, all attributes should be

What do you think ?

**Comment by AlexisDrogoul** [comment]
OK. I didn't wait for the answer. I implemented the solution described above, minus the last point: if `attributes:` is not defined, no attributes are saved (same as the empty list/map).
so, now, for instance, to save all attributes of species `my_species`: 

```gaml
save my_species type: shp to: "xxxxx.shp" attributes: my_species.attributes;
```

or, if you want to remove specific attributes: 

```gaml
save my_species type: shp to: "xxxxx.shp" attributes: my_species.attributes - ["peers", "host"];
```

Note that when passing a list, contrary to a map, we evaluate only once the expression, so as to keep the set of attributes constant. No validation is made (obviously) on the existence of the attributes, so if the list contains an attribute name which does not belong to the species, it will simply return nil for all agents.

**Comment by ptaillandier** [comment]
Great! It works well for species of agents!

But, is it possible to do the same thing for lists of geometries?

**Comment by AlexisDrogoul** [comment]
That was not possible with the previous save statement, was it ? Attributes were only available for saving agents, right ? It will probably require to change several things in the statement... I'll check.
