### ISSUE TITLE
Add a toggle parameter 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2986]
**Describe the solution you'd like**
It would be nice to have the possibility to trigger something from the parameter interface by just pressing a button. right now we can switch a boolean but we can trigger something (e.g I want to reinitialize a specific condition) which is different from switching from true to false

**Describe alternatives you've considered**
Having a button to click one

**Comment by hqnghi88** [comment]
user_command "Trigger something" category: "Triggers" color: #darkblue {
		ask world {
			do reinitialize;
		}

	}
