### ISSUE TITLE
Add a facet to make a layer visible or not

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2987]
**Describe the solution you'd like**
Would it be doable, and compatible with the GAML syntax to have a facet at the layer level to specify either a key or a boolean to activate ot not a layer

something like this
`````
species people aspect:base activated_by:myBoolean/"myKey";
`````

**Describe alternatives you've considered**
Right now there is a way to do it using the Side Controls but it would be great to be able to do it by switching a parameter (from a parameter or from a key). Right now the only way to change a parameter though a key (so though any external interface) is to define an if statement inside an aspect (which is ok but implies more code).

**Comment by AlexisDrogoul** [comment]
Possible that we can expose the `visible` property of layers through a facet, but it will use a boolean, not a key. Up to you to switch the value of this boolean (for instance by listening to the key in an event layer).
In the meantime, you can easily emulate it with the `transparency: ` facet. 

Something like :

```gaml
experiment ee {
    bool tt;
    user_command Toogle { tt<-!tt;}
    display d {
        species ss transparency: tt ? 0 : 1;
    }
}
```

**Comment by agrignard** [comment]
Is the ```visible```property ready to be exposed? Indeed that can be a good enhancement and could be easily trggerred by an even like 
````
species people visible:show_people;
event["p"] {show_people<-!show_people;}
````

or even better but not really it's in the GAML syntax style, something like this
````
species people visible:event["p"];
```` 
For the workaround proposed, why not emulating it with the transparency, however it means object are still drawn. So yes it's a possible workaround/twick from GAMA.

**Comment by agrignard** [comment]
Perfect!!! Very useful feature!
