### ISSUE TITLE
String Parameter and "/" symbol 

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2988]
**Describe the bug**
test the following model:

```
model test_param

global {
  string parameter_name <- "../includes/parameters1.json";

  reflex step {
  	write parameter_name; 
  }
}

experiment main type: gui {
	parameter 'Fichier parametre'  var: parameter_name category: 'Simulation' ;
}
```

Run the model, and try to change the value of "Fichier parametre". An error appear (I was not able to read it because of my HDPI windows screen) and the value of the variable parameter_name  is not changed.  If I replace the "/" by another symbol (for example "_"), it works well.

**Desktop (please complete the following information):**
 - OS: windows 10
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Well. Comes from the fact that `/` is escaped when the string is read from the control (by the method `toGamaString(..)`, but I don't know why it is (or was) necessary to escape this character.  As a consequence, when evaluated as a "Gama string" the escape sequence is misinterpreted... Problem is that I'm a little  bit afraid to touch this method (as many others rely on it).
