### ISSUE TITLE
Benchmark-Output

### ISSUE THREAD

**Issue by lutapp** [gama-platform/gama#2993]
Hello, 

I'm not sure if that belongs in Github, but I have a question about the benchmark output. I'm not sure how to interpret that.

The total_duration of a simulation run is not equal to the summed up execution time of all code lines from the corresponding benchmark. How should the output be interpreted? 

### Steps to reproduce
1. Produce a benchmark output of the benchmarking.gaml-Model in GAML Syntax > System

2. Compare the total_duration of the run with the execution time in the output

### Expected behavior
The total_duration of a simulation run is equal to the summed up execution time of all code lines from the corresponding benchmark. 

### Actual behavior
The total_duration of a simulation run is not equal to the summed up execution time of all lines of code.

![benchmark](https://user-images.githubusercontent.com/38818150/83040398-800de700-a03f-11ea-98f9-65518b7e27f5.PNG)

![benchmark_modell](https://user-images.githubusercontent.com/38818150/83040378-7a180600-a03f-11ea-9477-3d644d017d61.PNG)

Do I miss something?

### System and version 

- OS: Win 10 Pro
- GAMA version: 1.8
- Java version: 1.8

**Comment by AlexisDrogoul** [comment]
Hi, I am sorry, but I don't really get what you are comparing here using these different screenshots. If you are worried by the fact that `The total_duration of a simulation run is not equal to the summed up execution time of all lines of code.`, well, it is relatively normal as some internal processes (scope switching, scheduling of agents, etc.) are not counted as "GAML operations" and thus not benchmarked _per se_, contrary to operators or statements...

**Comment by benoitgaudou** [comment]
I close this issue.
For more questions, the most relevant place is the gama-platform mailing list:
gama-platform@googlegroups.com
