### ISSUE TITLE
problem with relative path (outside the project location) and file operator

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2997]
**Describe the bug**
The use of operators such as file_exists that try to locate a file from a relative path return errors when the relative path is a reference to a location that is not inside the project. 

**To Reproduce**
[test_file_exists.zip](https://github.com/gama-platform/gama/files/4756967/test_file_exists.zip)

1. Import the attached model
2. Run "model1.gaml"
2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in write 'sub_model: ' + file_exists(the_path) ;
NullPointerException: null
msi.gama.common.util.FileUtils.findInWorkspace(FileUtils.java:162)
msi.gama.common.util.FileUtils.constructAbsoluteFilePath(FileUtils.java:134)
msi.gaml.operators.Files.exist_file(Files.java:115)
gaml.additions.GamlAdditions.lambda$551(GamlAdditions.java:612)
msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:84)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:76)
when applying the file_exists operator on ../../includes/test.txt
in write 'sub_model: ' + file_exists(the_path) ;
in init  {
	write 'sub_model: ' + file_exists(the_path) ;
}

in agents Simulation 0, submodel0

2. Run "model2.gaml"
2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in write 'sub_model: ' + file_exists(the_path) ;
NullPointerException: null
msi.gama.common.util.FileUtils.findInWorkspace(FileUtils.java:162)
msi.gama.common.util.FileUtils.constructAbsoluteFilePath(FileUtils.java:134)
msi.gaml.operators.Files.exist_file(Files.java:115)
gaml.additions.GamlAdditions.lambda$551(GamlAdditions.java:612)
msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:84)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:76)
when applying the file_exists operator on ../../includes/test.txt
in write 'sub_model: ' + file_exists(the_path) ;
in init  {
	write 'sub_model: ' + file_exists(the_path) ;
}

in agents Simulation 0, model20

**Expected behavior**
Should write true or false (depending on the rule concerning the management of paths when dealing with model that imports other models)

**Desktop (please complete the following information):**
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Can you test the fix I just pushed ?
