### ISSUE TITLE
UDP connect size_packet missing facet 

### ISSUE THREAD

**Issue by edcafenet** [gama-platform/gama#2998]
I am trying to change the packet size of my UDP server connection in Gama from 1024 to 2048. I think that might solve this error that I get at random times in my UDP connection:

`ConcurrentModificationException: null
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
ummisco.gama.network.udp.UDPConnector.fetchAllMessages(UDPConnector.java:54)
ummisco.gama.network.skills.NetworkSkill.fetchMessagesOfAgents(NetworkSkill.java:374)
ummisco.gama.network.skills.NetworkSkill.lambda$0(NetworkSkill.java:416)
msi.gama.kernel.experiment.ActionExecuter.executeActions(ActionExecuter.java:80)
msi.gama.kernel.experiment.ActionExecuter.executeEndActions(ActionExecuter.java:57)
in agent Simulation 0`

According to the documentation I can change this parameter with the size_packet facet in the connect action. However, my Gama 1.8 doesn't recognize that facet. Thanks!

**Comment by benoitgaudou** [comment]
Hi,

If I remember correctly, I added this facet recently, so it is not included
in the GAMA 1.8 release version.
It should be in the continuous built (and in the upcoming 1.8.1).

Cheers

Benoit

Le ven. 19 juin 2020 à 22:19, Eduardo Castello <notifications@github.com> a
écrit :

**Comment by benoitgaudou** [comment]
I close this issue. Do not hesitate to reopen it if needed.
