### ISSUE TITLE
Occurence in UDP Server

### ISSUE THREAD

**Issue by edcafenet** [gama-platform/gama#3010]
I create a UDP server for each agent in my gama simulation with the following code:

```
init {
		create robot number:number_of_robots {
		   do connect to: url protocol: "udp_server" port: port+i;
		   i<-i+1;
		}
	}
```

I have around 20 agents sending information at a rate of 10Hz to their correspondent UDP server. The information (a long string separated by ;) is collected with the fetch reflex for each agent:

```reflex fetch when:has_more_message() {
		loop while:has_more_message()
		{
			message s <- fetch_message();
	
			// De-encapsulation of the UDP packet received
			list packet <- string(s.contents) split_with(";");
			// name of the robot
			robot_name <- packet[0];
			
			// location and orientation of robot in 2D
			float y <- (float(packet[1])*100);
			float x <- (float(packet[2])*100);	
			float z <-(-float(packet[3])+90);	
			location <- tracking_correction(x,y);
			heading <- z;
                         .......
                 }
````

However, every now and then I get this following error message: 

```
1 occurence in Simulation 0 at cycle 210811: Java error: ConcurrentModificationException
in reflex calculateTrajectory when: draw_trajectory = true  {
	loop while: length(current_trajectory) > trajectory_length  {
		current_trajectory >- first(current_trajectory);
	}

	current_trajectory <+ location;
}

ConcurrentModificationException: null
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
ummisco.gama.network.udp.UDPConnector.fetchAllMessages(UDPConnector.java:54)
ummisco.gama.network.skills.NetworkSkill.fetchMessagesOfAgents(NetworkSkill.java:388)
ummisco.gama.network.skills.NetworkSkill.lambda$0(NetworkSkill.java:430)
msi.gama.kernel.experiment.ActionExecuter.executeActions(ActionExecuter.java:80)
msi.gama.kernel.experiment.ActionExecuter.executeEndActions(ActionExecuter.java:57)
in agent Simulation 0

```

Which is extremely weird because the function calculateTrajectory is not even executed since the draw_tracjetory variable is always false. I tried to increase the UDP packet size to 4096 but the error still appears. Any idea about how to tackle the problem would be super appreciated! Thanks.

**Desktop (please complete the following information):**
 - OS: macOS High Catalina
 - PC Model: Macbook Pro
 - GAMA version: 1.8.1
 - Java version: JDK provided with Gama

**Comment by AlexisDrogoul** [comment]
Have you been able to solve this problem ? 
If no, do you run your agents in parallel ? Everything indicates here that there is a concurrent modification appearing in a list (which one, I dont know).

**Comment by YoucefSklab** [comment]
hi @edcafenet, Are you still facing the issue? I can't reproduce it! I have tried with 20 servers and sent messages with packet sender ([https://packetsender.com/](https://packetsender.com/)) and it works fine.

**Comment by edcafenet** [comment]
I will test it next moth. I will repeat the experiments that lead to this error. I will keep you updated.

**Comment by AlexisDrogoul** [comment]
Any news to report ? Seems like the issue hopefully doesn't appear anymore...

**Comment by lesquoyb** [comment]
Closed for inactivity
