### ISSUE TITLE
The built-in model (fipa no protocol)

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3011]
I was trying to learn the fipa skill from the built-in models in Gama library. One model (fipa no protocol) when it runs, the result in the console shows results like this:
Participant0 with conversation: [ ]; mailbox: [ ]
These lists (conversation, mailbox) should not be empty. According to the code, a content should be written, but this is how the output appears. What is going wrong?

**Comment by benoitgaudou** [comment]
Dear,

I run the model with GAMA 1.8.1 and made 3 steps.
I get the following outputs in the console.

Initiator0 with conversations: []; mailbox: [] 0.0

Participant0 with conversations: []; mailbox: []


Initiator0 with conversations: []; mailbox: [] 1.0

Participant0 with conversations: [Conversation between initiator:
Initiator0 and participants: [Participant0]]; mailbox: [['Hello from
Initiator0']]


Initiator0 with conversations: [Conversation between initiator: Initiator0
and participants: [Participant0]]; mailbox: [] 2.0

Participant0 with conversations: [Conversation between initiator:
Initiator0 and participants: [Participant0]]; mailbox: [['Hello from
Initiator0']]

Participant0 receives message with content: ['Hello from Initiator0']

Note that I slightly modify a write to display the time:

reflex print_debug_infor {

write *name* *+* ' with conversations: ' *+* *string*(*conversations*) *+* ';
mailbox: ' *+* *string*(*mailbox*) *+* ' ' *+* *time*;

}

Given the fact  that  the messages  are sent from  the time  = 1,  results
seem  intuitive.
( reflex say_hello when: (*time* *=* 1) {)

Cheers

Benoit

Le jeu. 9 juil. 2020 à 20:49, Aya-Badawy89 <notifications@github.com> a
écrit :
