### ISSUE TITLE
Shortest path and driving  graph

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3012]
**Describe the bug**

It seems there is something strange with the graph generated with the `as_driving_graph` operator and the way the shortest path is computed.

In the following model, slightly modified from the `Driving Skill` model), I compute the distance travelled by a vehicle and I compare the distances computed with the continuous environment, with the topology of the graph computed with the `as_driving_graph` operator and with the topology of a graph created with the `as_edge_graph` operator.
Driving skill_Test_Distance.gaml 
[Driving skill_Test_Distance.gaml.zip](https://github.com/gama-platform/gama/files/4941501/Driving.skill_Test_Distance.gaml.zip)

Here are the computation:
```
float distance_parcourue_cont <- self.location distance_to p_before_move;

float distance_parcourue_graph2 <- 0.0 ;
using (topology(road_network)) {
distance_parcourue_graph2 <- (self.location distance_to p_before_move) ;
}

float distance_parcourue_graph_rr <- 0.0 ;
using (topology(rr_net)) {
distance_parcourue_graph_rr <- (self.location distance_to p_before_move) ;
} 
```
(`rr_net`is the graph computed with `as_edge_graph`).

Here are some results:
``` 
   -------------- people(0)---- 9
distance_parcourue_cont -: 9.294194065863913
distance_parcourue_graph2 -: 832.7321012405148
distance_parcourue_graph_rr -: 9.825
self.real_speed -: 9.825
self.speed -: 9.825000000000001
```
__

**To Reproduce**
1. Copy  the   attached  model in the  Driving skill  project
2.  Run it

**Expected behavior**
At  least, `distance_parcourue_graph2`and `distance_parcourue_graph_rr`should  have the  same values.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: 1.8.1 with JDK

**Comment by ptaillandier** [comment]
Hi,

In your model, you use:
rr_net <- (as_edge_graph(road) with_weights general_speed_map);

However, the graph obtained with as_driving_graph is directed.

Could you test with:
rr_net <- directed(as_edge_graph(road) with_weights general_speed_map);




Le sam. 18 juil. 2020 à 13:07, benoitgaudou <notifications@github.com> a
écrit :

**Comment by ptaillandier** [comment]
Ok, I tested and it is not a bug: 
 - first, you have to set rr_net to directed.
 - even with that, sometimes the distance is different - it is due to the fact that when the agent is located on a bidirectional road (two overlapping road with inverse orientation), the "starting" road is chosen randomly... so the distance can be very different.
