### ISSUE TITLE
try/catch an occurence in gama?

### ISSUE THREAD

**Issue by edcafenet** [gama-platform/gama#3014]
Hi, I am experiencing an occurence in my gama model:

`1 occurence in Simulation 0 at cycle 210811: Java error: ConcurrentModificationException`

While I understand the causes of this error, it would be helpful to be able to catch the exception to keep the model running. I imagine this is possible since when Gama throws the exception I can keep the model running without problems by pressing play again.  Thanks a lot in advance!

**Comment by AlexisDrogoul** [comment]
Hi,

The try / catch combo exists in GAMA. See https://gama-platform.github.io/wiki/Statements#try

Alexis
