### ISSUE TITLE
Problems with as_edge_graph, it does not show nodes

### ISSUE THREAD

**Issue by ecallejasbriones** [gama-platform/gama#3015]
Hi,

I'm using _**as_edge_graph**_ and it does not show me all the nodes of graph (a map), also the nodes that GAMA shows are not connected between other nodes.

![shapeGAMA](https://user-images.githubusercontent.com/26755268/88639663-05873500-d08b-11ea-9f9f-5132afa8d9a2.JPG)

my code

```
model Prueba2

global {
    //file roads_shapefile <- file("../maps/SectorIquiqueV2/lineas_sectorIqqV2.shp");
    file roads_shapefile <- file("../maps/Iquique2/polylines_iqq.shp");
    //file roads_shapefile <- file("../includes/road.shp");
    geometry shape <- envelope(roads_shapefile);
    graph road_network;
    point prueba;
    float varprueba;
    int var1 <- 0;

    init {
    	create road from: roads_shapefile;
    	road_network <- as_edge_graph(road);
    	
    	varprueba <- connectivity_index(road_network);
    	write varprueba;
    
    	prueba <- point(one_of(road_network.vertices));
    	
    	loop Nombreloop over: road_network.vertices{
    		create Nodo{
    			location <- road_network.vertices[var1];
    		}
    		var1 <- var1 + 1;
    		write "Var1 = " + var1;
    	}
    	
    }
}

species road {
    aspect geom {
    draw shape color: #black;
    }
}

species Nodo {
	aspect base{
		draw circle(10) color: #yellow border: #black;
		draw string(road_network degree_of location) color:# black;
	}
}

experiment main_experiment type:gui{
    output {
    display map {
        species road aspect:geom;
        species Nodo aspect:base;
    }
    }
}
```

In QGIS where I did the conversion from OSM to SHP I can visualize the map and the nodes.
![shapeQGIS](https://user-images.githubusercontent.com/26755268/88639665-06b86200-d08b-11ea-9926-fbf499be3cd8.JPG)

I want GAMA to show all the nodes and edges of a graph (my map), how could I solve it?.

**Comment by ptaillandier** [comment]
Hi,

The problem comes from your data: GAMA does not create new nodes, but just
uses the extremities of the roads to create nodes.
You have two solutions to solve the problem:

   - directly using the OSM data in GAMA, and not the shapefile exported
   with QGIS from the OSM data.
   - use the clean_network operator: just replace "create road from:
   roads_shapefile;" by "create road from:
   clean_network(roads_shapefile.contents, 0.0, true,true);"


Cheers,

Patrick

**Comment by ecallejasbriones** [comment]
Hi!,

this solution it's works for me, thanks  @ptaillaindier!

> use the clean_network operator: just replace "create road from: roads_shapefile;" by "create road from: clean_network(roads_shapefile.contents, 0.0, true,true);"

![imagen](https://user-images.githubusercontent.com/26755268/88717540-ad821a00-d0ee-11ea-8659-552694a764ad.png)
