### ISSUE TITLE
Date type: use of min, max, among when declaring a date variable

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3017]
**Is your request related to a problem? Please describe.**
GAMA  allows to define some attributes with `min`, `max`or `among` facets:
```
	int i <- 0 min: -1 max: 10;	
	int j <- 0 among: [0,5];
``` 

Nevertheless, the equivalent declaration with `date` variables does not work:
```
	date di <- date(2019,12,5) min: date(2019,12,1) max:  date(2019,12,30);
```
throws a compilation error:  `Unknown facet min` (similar for `max`)

```
	date dj <- date(2019,12,5) among: [date(2019,12,5),date(2019,12,10)];
```

provokes  a warning: 
```
Facet 'among:' should only be provided with a literal constant
   list for its definition. Proceed at your own risk with this
   variable
```

**Describe the solution you'd like**
These facets should also be available for date attributes.

**Comment by AlexisDrogoul** [comment]
Just to mention that I am working on it (together with `point`)

**Comment by benoitgaudou** [comment]
Thx!
I just tried: `min` and  `max`work perfectly.

Nevertheless:
````
	date dj <- date(2019,12,5) among: [date(2019,12,5),date(2019,12,10)];
```
still triggers a  warning (whereas it should not as the element in the among are constant):
```
Facet 'among:' should only be provided with a literal constant
   list for its definition. Proceed at your own risk with this
   variable
```

**Comment by benoitgaudou** [comment]
@AlexisDrogoul I still  have  a warning on  the `among`, expressing that date(2019,12,5) and date(2019,12,10) are not literal constant.

Is it expected ? I am not sure to understand why, that is why I removed the  Fix to be tested label previously

**Comment by AlexisDrogoul** [comment]
Should be completely fixed now. `TypeExpression`s were actually systematically returning false when asked if they were context independent...

**Comment by AlexisDrogoul** [comment]
Closing it now (I've tested it myself in different scenarios). Reopen if it still manifests itself.
