### ISSUE TITLE
Batch: access to a  tif file blocks repetitions + (after quitting blocked batch, simulations are blocked trying to open any file  at initialization)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3020]
**Describe the bug**
I want to explore in batch mode a model that reads a .tif file at each simulation step to update its data.
The model contains a grid (a DEM of a landscape, with a water elevation on it). Each step I read a tif file that contains water elevation, computed by another tool.

The issue is twofold:
* when I run the batch experiment, with a `repeat: 8` (or any value greater than 1), the batch blocks at the first step when reading the tif file.  If `repeat: 1`, then no problem occurs.
* when the batch is run with `repeat: 8` and has blocked, I close it (clicking on the red cross button). When I try to run with `repeat: 1`, I notice  that the simulation is blocked, but on the reading of the file at initialization this time.

The model is below, the problematic reading is in the  `reflex  update_data`.

```
global {
	file grid_data <- file("../includes/Hello DEM 200x100.MergedInputs.tif");
	
	//computation of the environment size from the geotiff file
	geometry shape <- envelope(grid_data);
	date  starting_date <- date("2019-07-25 00:01:00"); 
	float step <- 1#mn;	
	
	// Parameters
	int evac_minutes <- 60;

	init{
		create hydroManager;
	} 

}

species hydroManager /*skills: [hecrasSkill]*/ {

	reflex update_data {

		string hrs <- current_date.hour < 10 ? "0" + current_date.hour : "" + current_date.hour;
		string min <- (current_date.minute=59)? 58:( current_date.minute < 10 ? "0" + current_date.minute : "" + current_date.minute);

		file grid_dataa <- grid_file("../includes/HWC/Plan 03/Depth (25JUL2019 " + hrs + " " + min + " 00).MergedInputs.tif");
		
		list<float> water_depth_list <- grid_dataa accumulate(float(each["grid_value"])); 
	}	
}

grid mnt file: grid_data neighbors: 4 {}

experiment evalAlertTime type: batch repeat: 1 until: (cycle > 2) {
	parameter  "Alert minutes" var: evac_minutes min: 20 max: 60  step: 5;
}
```

If I remove the following line, the issue disappears. 
```
		list<float> water_depth_list <- grid_dataa accumulate(float(each["grid_value"])); 
```

**To Reproduce**
1. Get, unzip and  import in GAMA the following project
[TestBatchDate.zip](https://github.com/gama-platform/gama/files/5006888/TestBatchDate.zip)
2. Run the experiment with `repeat:  1`   and  notice that there  is no deadlock
3. Run the experiment with `repeat:  8`   and  notice that there  is a deadlock
4. Close the blocked experiment
5. Run the experiment with `repeat:  1`   and  notice that there  is a deadlock (but on the reading of the file at  initialization)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Would this issue be solved by using a `field` rather than a `grid` to read the file ?

**Comment by AlexisDrogoul** [comment]
![Eclipse Workspace for GAMA 1 8 2021-09-06 14-57-08](https://user-images.githubusercontent.com/579256/132181208-8015fd8e-0012-4025-8be5-39ffdf03c05d.png)


It happens that several threads initialising the TIFF file from Geotools become stuck waiting for the same lock (or equivalent), which I suspect is linked to some concurrent access to the metadata holding the CRS information. I am not completely sure about how we can easily solve this. One obvious solution would be to NOT recalculate the metadata over and over, of course. Maybe some cache system could be usable there.

It is also maybe linked to the fact that GAMA (UI) is unable to display these metadata in the navigator. it it was possible then it wouldn't probably be necessary to load it for each simulation.

**Comment by AlexisDrogoul** [comment]
Can you test the commit I have just made ? The addition of a short-term CRS cache seems to solve the problem...

**Comment by AlexisDrogoul** [comment]
I re-tested it with a different input (and also with shape files) and it seems ok ! I close it for now on.
