### ISSUE TITLE
color contrast in issue labels

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#3022]
Hi

I just realized that the color contrast with issue labels is not so good , for example, github itself uses white text on green background for ` issue` and this combination has a good visibility, while GAMA uses black text on dark green background for `enhancement` and this is hardly visible. Similarly

red exclamations in dark red `priority critical`
red tools icon in `affects maintainability`
yellow warning sign icons in yellow `missing* `
black monitor icon in dark green `Display All` 
almost red face emoji in a red `Bug` 

may be others also need a relook

**I have given many labels to this issue, just to highlight the problem**. Please feel free to remove the labels.

thanks

**Comment by AlexisDrogoul** [comment]
Hi Srirama,

Unfortunately, GitHub does not provide us any ways to choose the label color as far as I know... It seems to pick it according to the radiance/brightness of the button color.
Same goes with Emojis: it's impossible to change their color. I will make some adjustments, but I think you can too edit labels (in the "Labels" dropdown menu, last choice)
Alexis

**Comment by AlexisDrogoul** [comment]
Closing this now as the "new" color scheme seems a bit more adapted ?
