### ISSUE TITLE
"udp_emitter" doesn't send packets to no destination address but localhost

### ISSUE THREAD

**Issue by edcafenet** [gama-platform/gama#3023]
Hi, 

I have need to setup a UDP client between Gama (10.0.0.251) and a UDP server (10.0.0.250). Therefore, I do the following:

```
create arena_state_udp_client number:1 {
    		do connect to: "10.0.0.250" protocol: "udp_emitter" port: 9876;
		}
	}
```

and

```
species arena_state_udp_client skills:[network]{
	reflex send {
		do send contents: '......';
	}
}
```

However, Gama doesn't send packages to the the server address (10.0.0.250). I checked this with Wireshark. At the moment, I can only send UDP packets to the desired destination if I make Gama send packets to "localhost" and then have an additional server/client pair which eventually sends packets to the UDP server.

**Comment by benoitgaudou** [comment]
It  seems that the url was  not correctly retrieved, and  thus always trying to send to localhost.
The last commit  should have  fix this point.

Nevertheless I do not have a way to test the actual reception by an UDP server (on another IP than localhost).
Could you try (GAMA git version or next continuous  built coming tomorrow) and close  the issue  if it works?

Thank  you in advance

**Comment by benoitgaudou** [comment]
I close  it now, please  reopen if the issue appears again
