### ISSUE TITLE
Use all available CPUs for a single simulation process in Headless

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#3024]
**Is your request related to a problem? Please describe.**
In a project, I created a few experiments to generate static files used to run the final *real* simulation. 

To generate a release with all these files generated, I use GAMA Headless in a CI/CD (like Travis) with an XML file listing all the experiments to launch and in what order (some may depend on previous ones). 

The problem is that, I have to force the usage of a single core (`-hpc 1`)to serialize the launch of these experiments in the same order (which takes a lot more time).

**Describe the solution you'd like**
Adding a flag on the GAMA Headless to launch the experiments one after the other (and using every cores on them) like : 

```shell
$ ./gama-headless.sh -m 16g -noParallel ./generateHeadless.xml ./output
```

**Describe alternatives you've considered**
Another solution would be to add a complementary attribute in the XML file like so : 

```xml
<Simulation id="1" sourcePath="./osm_hanoi.gaml" finalStep="1" experiment="load_OSM" seed="0" parallel="no">
	<Parameters/><Outputs/>
</Simulation>
```

**Additional context**
This feature may be interesting to add for the **batch mode** too.

**Workaround**
The only current way to do it is to subdivide XML files to have a single simulation tag per XML and launch them all. It uselessly complicates the workflow, but it's a workaround 🤷

**Comment by AlexisDrogoul** [comment]
Should we keep this open or has is been _de facto_ replaced by the possibility to use batch files in headless mode ?

**Comment by RoiArthurB** [comment]
Yeap we can :)
