### ISSUE TITLE
Benchmarking can't exit

### ISSUE THREAD

**Issue by natohutch** [gama-platform/gama#3025]
**Describe the bug**
When running an experiment in benchmark mode, it becomes impossible to close it. You can restart the experiment, but not exit it.

**To Reproduce**
Simpy add benchmark: true to your experiment, this happens with or without any particular benchmarked sections within the code

**Desktop:**
 - OS: Win10
 - GAMA version: 1.8
 - Java version: 8

**Comment by benoitgaudou** [comment]
Hi,

I tried to add `benchmark: true` in the experiment of a random model in the model library (Toy Models / Urban Growth).
I tried several times to run,  relaunch, quit, switch perspectives without any trouble.

I tried on  both GAMA 1.8.0 release  and the GAMA git (the last up to date version).

Could you be  more precise by specifying a model that let this issue appears.
(before  that  can you  try  to run on a new workshop)

Thank  you in advance

**Comment by natohutch** [comment]
This issue happens on any model I use, I even made an empty model with an empty gui experiment which still shows the same issue, this was also in a new workspace. I tried it with the urban growth model, and it definitely gives the same problem.

**Comment by benoitgaudou** [comment]
I tried again with the GAMA Continuous  Built (so an updated version of  GAMA 1.8.1). And still no freeze...
Could you try with this version to check if you still have the same issue...
If this is the case, could you try with the git version and check whether you have some messages, errors, or exceptions in the  Eclipse console?

**Comment by benoitgaudou** [comment]
In addition, the  continuous  built  version has been  updated: on can  now run:
```
Gama.exe -console
``` 
to  get the  console message  during the execution of GAMA

**Comment by AlexisDrogoul** [comment]
No update on this one ? I guess we can close it safely. Feel free to reopen, however, if the issue pops up again
