### ISSUE TITLE
Unable to run graphic simulation on linux

### ISSUE THREAD

**Issue by aurelmegn** [gama-platform/gama#3026]
**Describe the bug**
When I run Predactor Prey model, or Road traffic model, gama exit just after the "Building output" step

**To Reproduce**
1. Go to "Library models" on the left side bar
2. Click on Tutorials
3. Scroll down to Predactor prey or Road traffic

```

(Gama Platform:151646): GLib-CRITICAL **: 06:14:35.328: g_once_init_leave: assertion 'result != 0' failed

(Gama Platform:151646): GLib-GObject-CRITICAL **: 06:14:35.328: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(Gama Platform:151646): GLib-GObject-WARNING **: 06:14:35.328: invalid (NULL) pointer instance

(Gama Platform:151646): GLib-GObject-CRITICAL **: 06:14:35.328: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(Gama Platform:151646): GLib-GObject-WARNING **: 06:14:35.328: invalid (NULL) pointer instance

(Gama Platform:151646): GLib-GObject-CRITICAL **: 06:14:35.328: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(Gama Platform:151646): GLib-GObject-WARNING **: 06:14:35.396: cannot register existing type 'GdkDisplay'

(Gama Platform:151646): GLib-CRITICAL **: 06:14:35.396: g_once_init_leave: assertion 'result != 0' failed

(Gama Platform:151646): GLib-GObject-CRITICAL **: 06:14:35.396: g_type_register_static: assertion 'parent_type > 0' failed

(Gama Platform:151646): GLib-CRITICAL **: 06:14:35.396: g_once_init_leave: assertion 'result != 0' failed

(Gama Platform:151646): GLib-GObject-CRITICAL **: 06:14:35.396: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe67c050907, pid=151646, tid=0x00007fe65ed84700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgdk-x11-2.0.so.0+0x4d907]  gdk_display_open+0x67
#
# Core dump written. Default location: /home/aurel/Documents/tmp/GAMA_1.8.1_Linux_with_JDK/core or core.151646
#
# An error report file with more information is saved as:
# /home/aurel/Documents/tmp/GAMA_1.8.1_Linux_with_JDK/hs_err_pid151646.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

```

**Expected behavior**
Gama should not exit and I should have the simulation running

**Desktop (please complete the following information):**
 - OS: Manjaro
 - PC Model: HP Pavilion Laptop 15-cs0xxx 
 - GAMA version: 1.8.1
 - Java version: 1.8
 - Graphics cards / Display system: Mesa Intel UHD Graphics 620 (KBL GT2)

**Comment by RoiArthurB** [comment]
Hello,

I ran the simulations with GAMA 1.8.1 JDK on Manjaro and I haven't any application crashes...

It's really strange that GAMA crash at this point. On the log you copied, can you, please, send me the referred crash log  at that location : 
```
/home/aurel/Documents/tmp/GAMA_1.8.1_Linux_with_JDK/hs_err_pid151646.log
```

It's known that GAMA may have some graphical issues (especially on rolling distros like Manjaro), especially for `opengl`'s graphical simulations. The problem seems to come from the version of OpenGL used in GAMA (which start to be a bit old) and latests graphical drivers do to support them (freezing distro like Ubuntu doesn't have these problems because they keep legacy packages, but not arch rolling's ones). I'm currently working on a solution for it :)

To be sure that your problem comes from your drivers you can :
- Send me your graphical drivers installation (`$ inxi -Gxz`)
- Try these simulations by changing `opengl` to `java2D` (in the _output_ block, on the _display_ line)

**Comment by aurelmegn** [comment]
Thank you for the help, 
Here is the log file https://pastebin.com/atUmjbsv , I put it on a pastebin because of the length.

$ inxi -Gxz 
```
Graphics:  Device-1: Intel UHD Graphics 620 vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.8 driver: i915 resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.1.3 direct render: Yes 

```

**Comment by RoiArthurB** [comment]
It's very strange that each time you try to compile a model (switching on the simulation view) it crashes...

Based on what you told me and your pastebin, I think that the archive that you downloaded is corrupted. So here's the SHA1 of each to verify the integrity of what you downloaded :
```
$  sha1sum GAMA_1.8.1_Linux*   
a2cd256106ab6dbc42ad64c03010acfe4490f3ca  GAMA_1.8.1_Linux_with_JDK.zip
ac6c1a6981cd450a4abad161d78fb14fedae9de9  GAMA_1.8.1_Linux.zip
```

Because the problem seems to come from the embedded Java, I'll recommand you to use the regular _GAMA_1.8.1_Linux_ and to install OpenJDK 8 as your Java (on Manjaro you just have to launch : `sudo pacman -S jdk8-openjdk`)

**Comment by aurelmegn** [comment]
The sha1sum matches with the GAMA_1.8.1_Linux_with_JDK.zip I have, so I'm trying the second solution

**Comment by aurelmegn** [comment]
After downloading an installing the GAMA_1.8.1_Linux.zip, Gama does not crash when I ran the simulations but there is no output on the simulation display window. I then change the opengl to java2D and I have the simulation display.
In the terminal log of the new Gama, I can read 
```
Exception in OpenGL:Profile GL4bc is not available on X11GraphicsDevice[type .x11, connection :1, unitID 0, handle 0x7f9a066855d0, owner true, ResourceToolkitLock[obj 0x5392c0a7, isOwner true, <bb9bad9, 1435feb6>[count 1, qsz 0, owner <Animator thread>]]], but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw], GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]
com.jogamp.opengl.GLException: Profile GL4bc is not available on X11GraphicsDevice[type .x11, connection :1, unitID 0, handle 0x7f9a066855d0, owner true, ResourceToolkitLock[obj 0x5392c0a7, isOwner true, <bb9bad9, 1435feb6>[count 1, qsz 0, owner <Animator thread>]]], but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw], GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at jogamp.opengl.GLContextImpl.verifyInstance(GLContextImpl.java:1491)
	at jogamp.opengl.GLContextImpl.setGLFunctionAvailability(GLContextImpl.java:1962)
	at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:395)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:960)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:659)
	at ummisco.gama.opengl.view.SWTGLAnimator.displayGL(SWTGLAnimator.java:201)
	at ummisco.gama.opengl.view.SWTGLAnimator.run(SWTGLAnimator.java:182)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RoiArthurB** [comment]
Strange that you have error on the version with JDK but not the other one... Can you try to redownload it in case ?

About your log, it's exactly what I explained you previously : Your graphical drivers are too early and the OpenGL version of GAMA is too old, so you have some issues I'm working on. Sorry for that :/
