### ISSUE TITLE
[wiki] Referencing papers proposal and duplicated content

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#3027]
Hello everyone,

I wanted to submit a few new "papers" using Gama as a simulation platform.
It seems the listing in the website are based on the wiki, so, I can't edit/PR it, and I'll just list it here.

1. This made me wonder why there's 2 different sections on the wiki about paper/projects about Gama, that seem quite redundant ![image](https://user-images.githubusercontent.com/807703/89417006-661f0d80-d72e-11ea-9e58-e740f0cb3d7c.png)
Maybe it could be worth merging those two listings ?  

2. Anyway, here are the papers that I wanted to propose for inclusion :

#### PhD theses that use GAMA as modeling/simulation support
- **Robin Cura**, "Modéliser des systèmes de peuplement en interdisciplinarité. Co-construction et exploration visuelle d'un modèle de simulation", Université Paris 1 Panthéon-Sorbonne, defended March 6th, 2020.
(-> still not available on a public repository, should be ok around September, waiting for the univ. administration)
####  2020
- [Tannier C., Cura R., Leturcq S. and Zadora-Rio E., 2020. An agent-based model for exploring the combined effects of social and demographic changes on the concentration and hierarchy of rural settlement patterns in North-Western Europe during the Middle Ages (800–1200 CE). Journal of Anthropological Archaeology, vol. 59. https://doi.org/10.1016/j.jaa.2020.101204](https://www.sciencedirect.com/science/article/abs/pii/S027841651930279X)
####  2019
- [Cura R., 2019. « Model Visualization ». In Pumain D. (dir), Geographical Modeling: Cities and Territories, John Wiley & Sons, Ltd, pp. 151‑91. https://doi.org/10.1002/9781119687290.ch6](https://onlinelibrary.wiley.com/doi/abs/10.1002/9781119687290.ch6)
(-> There's a french version also, but I think this one is enough)

And by the way, the link to Justin Emery's thesis (2016) is not working. It should link to this : https://tel.archives-ouvertes.fr/tel-01436123v2 

Thanks !

**Comment by benoitgaudou** [comment]
Hi,

I updated the publication page  following  your remarks.

I have  also started to  totally change the project page ... to refer  to projects  instead of publications.
It  will take time. 
Do not hesitate if you have  projects you want to add.
