### ISSUE TITLE
Impossible to make import with absolute path

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#3028]
**Describe the bug**
I tried to make a GAML file import with an absolute path (to a file inside the same project and outside this project) and it returns an impossible path to compute.

**To Reproduce**
1. Create an empty GAML file
2. Make a full path GAML import 
3. See error

**Expected behavior**
Being able to import any GAML file existing on the computer.

**Screenshots**
![image](https://user-images.githubusercontent.com/16764085/89774944-ff846000-db30-11ea-84d9-2e617b93ad90.png)
None of these imports works

**Desktop (please complete the following information):**
 - OS: Linux && MacOS
 - GAMA version: 1.8.1
 - Java version: 1.8

**Comment by hqnghi88** [comment]
how about: import "**file://**home/roiarthurb/................

**Comment by RoiArthurB** [comment]
Wouha ! It works !! 🤩

Do you have any explanation about that specificity ?

**Comment by hqnghi88** [comment]
No , i dont, i requested some protocols in  gama-platform/gama2#14 and just file:// is implemented, others seem to be complex for moment
