### ISSUE TITLE
Headless mode cannot run in Daily Build "Error: Could not find or load main class org.eclipse.core.launcher.Main"

### ISSUE THREAD

**Issue by jameshumann** [gama-platform/gama#3030]
**Describe the bug**
In the Daily Build (and build from git), attempting to run Headless Mode causes an error:
"Error: Could not find or load main class org.eclipse.core.launcher.Main"

**To Reproduce**
1. Go to headless directory in Windows Powershell
2. Run command: "./gama-headless.bat samples/predatorPrey.xml outputs"
3. See error

**Expected behavior**
Headless mode should run and create files in outputs folder, but nothing happens after error message.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PC Model: Asus
 - GAMA version: 1.8.1 Daily Build and git
 - Java version: e.g. 1.8
 - Graphics cards / Display system: NVIDIA

**Comment by benoitgaudou** [comment]
Dear,
I  just tried, on a Windows virtualized on a Mac, with the  Continuous Built of today.
There were an issue with the headless script on Windows, but it  does  not produce the  same error  message as you, and  it had been fixed this morning.

By  the way, we also tested with success the headless in the git version and it worked well on the preyPredator example.

So could you try again  with the tomorrow's version of GamaCC to  check if it works now ?

Cheers

**Comment by jameshumann** [comment]
It worked for me, thank you!
