### ISSUE TITLE
GAMA runs out of memory

### ISSUE THREAD

**Issue by mikhailsirenko** [gama-platform/gama#3032]
**Describe the bug**
GAMA runs out of memory even though it was provided with Xmx 102400m.

**To Reproduce**
1. Open Gama.ini
2. Change Xmx from 2048m to 102400m
3. Save changes
4. Go to headless folder
5. Execute gama-headless.sh in connection with experiment file XML
6. See error "Runtime error: Memory is low (716 megabytes). You should close the experiment, exit GAMA and give it more memory"

**Expected behavior**
Since the maximum amount of memory is way too high for such a model, I expected no error whatsoever.

**Screenshots**

![image](https://user-images.githubusercontent.com/40139771/92913969-83c94c00-f42b-11ea-9c6d-0855e12c426b.png)

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server release 7.8 (Maipo)
 - PC Model: Not applicable
 - GAMA version: 1.8.1
 - Java version: openjdk version "11.0.8" 2020-07-14 LTS
                         OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
                         OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode, sharing)
 - Graphics cards / Display system: Not applicable

**Additional context**
Just for a reference, the same model runs with GAMA Platform (not in a headless mode) on a Windows 10 laptop with Xmx 8192 without any warnings.

**Comment by RoiArthurB** [comment]
Hello,

GAMA headless doesn't read the file `Gama.ini`, so you have to specify in your command line the max memory you want to give to your JVM.

By default, the headless will assign 4096Mo to the JVM, but you can increase this with the flag `-m`.

So in your case, the command should look like something like this :
```
$ ./gama-headless.sh -m 102400m ./headless.xml ./output
```

More generally, you can see all the available flags with the command `gama-headless.sh -help` :+1: 

I'll wait to know if it works for you before closing this issue :smile:

**Comment by mikhailsirenko** [comment]
@RoiArthurB thanks a lot! I completely overlooked the specification of gama-headless.bat (memory=4096m) 😅. Works perfectly fine now 👍.
