### ISSUE TITLE
Exception in OpenGL:Profile GL4bc is not available of opengl displays on Ubuntu/Linux

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3033]
**Describe the bug**
On ubuntu/ archlinux , some configuration of some user has encountered representation problem of opengl display

**To Reproduce**
1. Go to *Visualization and User Interaction* > *Visualization* >
*3D Visualization* > *models* > *Building Elevation.gaml*
2. Click on experiment button
3. See error
Exception in OpenGL:Profile GL4bc is not available on
X11GraphicsDevice[type .x11, connection :0, unitID 0, handle
0x7f0d129b4000, owner true, ResourceToolkitLock[obj 0x22277482, isOwner
true, <670481b2, 4474c514>[count 1, qsz 0, owner <Animator thread>]]],
but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw],
GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw],
GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw],
GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw],
GLProfile[GL2GL3/GL4.hw]]
com.jogamp.opengl.GLException: Profile GL4bc is not available on
X11GraphicsDevice[type .x11, connection :0, unitID 0, handle
0x7f0d129b4000, owner true, ResourceToolkitLock[obj 0x22277482, isOwner
true, <670481b2, 4474c514>[count 1, qsz 0, owner <Animator thread>]]],
but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw],
GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw],
GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw],
GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw],
GLProfile[GL2GL3/GL4.hw]]
     at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
     at jogamp.opengl.GLContextImpl.verifyInstance(GLContextImpl.java:1491)
     at
jogamp.opengl.GLContextImpl.setGLFunctionAvailability(GLContextImpl.java:1962)
     at
jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:395)
     at
jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
     at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
     at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
     at
jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
     at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
     at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
     at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:960)
     at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:659)
     at
ummisco.gama.opengl.view.SWTGLAnimator.displayGL(SWTGLAnimator.java:201)
     at ummisco.gama.opengl.view.SWTGLAnimator.run(SWTGLAnimator.java:182)
     at java.lang.Thread.run(Thread.java:748)

**Desktop (please complete the following information):**
 - OS: ArchLinux /Ubuntu 18 
 - GAMA version: git
 - Java version: openjdk 8 265
 - Graphics cards / Display system: Intel integrated card, Nvidia dedicated GPU

**Additional context**
My (brilliant) student @duongdominhchau find out on his computer, there is a thread related with this error message
http://forum.jogamp.org/Crash-after-latest-mesa-driver-update-from-ppa-oibaf-td4040300.html#a4040302
And it seem the version of jogl is the cause. When he update to jogl 2020-03-07 (https://jogamp.org/deployment/jogamp-next/jar/) in ummisco.gama.opengl, the issue is fixed. I tried too on windows os, and no glitch for a quick test.
But can you @gama-platform/core review this issue and the required version of jogl  .
Cheers.

**Comment by RoiArthurB** [comment]
May be related : [on Manjaro (ArchLinux)](https://github.com/gama-platform/gama/issues/3026) and [MacOS](https://github.com/gama-platform/gama/issues/3031)

In short, the problem comes from the too old version of OpenGL within GAMA.

**Comment by amaothree** [comment]
The daily build is work well now. Seem is has fixed in the next version.
