### ISSUE TITLE
Problem with multi-files grid with not projected files

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#3035]
**Describe the bug**
When creating a grid from several init files, if the first file is not projected, there is a problem when loading the data of the other files.

**To Reproduce**
1. Import and launch the attached model
2. Inspect the grid: the second value of the band is nil
[TestGridFiles.zip](https://github.com/gama-platform/gama/files/5246107/TestGridFiles.zip)

**Comment by benoitgaudou** [comment]
I just tried on the last  Git, andd  I  get a -1 value on  the second value of the band, 
so guess it works.

<img width="303" alt="Screenshot 2021-11-25 at 12 07 48" src="https://user-images.githubusercontent.com/1555274/143430671-549af9e7-6dc9-4abb-9b5f-94b59b8c3edd.png">
