### ISSUE TITLE
IndexOutOfBounds error when trying to reload my experiment by changing parameter settings from the GUI; Problem related to reading CSV files and passing then in the GUI

### ISSUE THREAD

**Issue by bitmixes** [gama-platform/gama#3036]
**Describe the bug**
Hi,

I am facing this weird issue and am not able to work out a solution. 

My experiment runs fine when I run it for the first time. Weirdly though, when I click the buttons (1. Reload the current experiment or 2. Add a new simulation with the current parameters from the parameters tab), even if I have not changed the value of any parameter, I run into this index out of bounds error. This forces me to go back to the global of my code and change any parameter value, which is not really fancy by any means.

I understood that the problem lies within the lines where I am creating my agents from a CSV file and using this global file variable as a parameter in the GUI. It runs without errors the first time, but once I try to reload the experiment with a different parameter value from the GUI, it throws an `Index Out Of Bounds Error`. I have been able to reproduce the error in a GAML file (**CSV Agents.gaml**) that comes with GAMA.

Thanks in advance,
Debjit.

**To Reproduce**
```
model CSVfileloading

global {
	file agents_input <- csv_file( "../includes/iris.csv",true);
	init {
		//create iris agents from the CSV file (use of the header of the CSV file), the attributes of the agents are initialized from the CSV files: 
		//we set the header facet to true to directly read the values corresponding to the right column. If the header was set to false, we could use the index of the columns to initialize the agent attributes
//		create iris from:csv_file( "../includes/iris.csv",true) with:
		create iris from:agents_input with:
			[sepal_length::float(get("sepallength")), 
				sepal_width::float(get("sepalwidth")), 
				petal_length::float(get("petallength")),
				petal_width::float(get("petalwidth")), 
				type::string(get("type"))
			];	
	}
}

species iris {
	float sepal_length;
	float sepal_width;
	float petal_length;
	float petal_width;
	string type;
	rgb color ;
	
	init {
		color <- type ="Iris-setosa" ? #blue : ((type ="Iris-virginica") ? #red: #yellow);
	}
	
	aspect default {
		draw circle(petal_width) color: color; 
	}
}

experiment main type: gui{
	
	parameter "CSV file for PT stops data:" var: agents_input category: "Input files" ;
	
	output {
		display map {
			species iris;
		}
	}
	
}
```

**Expected behavior**
I would really appreciate some help in this matter if possible, as I would like to select the CSV file of choice from the parameter box in the GUI.

**Comment by AlexisDrogoul** [comment]
Sorry to have been so long in replying to this bug. It was actually a silly bug, where the size of the matrix would be decremented each time the file was reloaded. The presence in the parameters was making the file object persistant, explaining why the error would only manifest in that case (when not in parameters, the file object is recreated at each run). It is now fixed in the branch 1.8.2
