### ISSUE TITLE
Headless mode: processing always delayed when call GAMA with exec() from webpage via PHP

### ISSUE THREAD

**Issue by hlan** [gama-platform/gama#3039]
Hi, 
I'm trying to run GAMA headless mode with PHP from web page. I'm using:

exec('ABM/jdk/bin/java -cp ABM/plugins/org.eclipse.equinox.launcher*.jar -Xms512m -Xmx2048m -Djava.awt.headless=true org.eclipse.core.launcher.Main -application msi.gama.headless.id4 ' .$xmlFile.$output);

It works normal and all results can be generated as expected. 
However, it does create the output folder fast (after I run it from webpage) but it always take about 3 mins until snapshots started to be created.  
Tried shell_exec(), system() and passthru() but nothing changed. Tried add "&> /dev/null &" or "&" after this running command but it still not shorten the delay time.
Tried to use bash gama-headless.sh to replace this java command. Still delay.
Tried to run this command and bash command in terminal directly. Everything goes normal and it took only less than 10 seconds to produce the results snapshots.
I feel this problem may happen between the output folder creation and the model running by using exec(). Any idea about this issue? Many thanks!

Best,
Hai

**Comment by RoiArthurB** [comment]
Hi,

Could you give me more information about all your stack (PHP version, GAMA version, dev environment, etc) and your PHP/GAML code please ? I don't have enough information to help you...

I'll try to run something on my side waiting for your answer :smiley:

**Comment by hlan** [comment]
Hi Arthur,
Thank you for your help!
I guess all models with GAMA may have the same issue. A quick reproduce could be done by using "roadTraffic" example in the headless folder. You can reproduce this issue by creating a .php file, add single statement with proper path. e.g. :

"ABM/jdk/bin/java -cp ABM/plugins/org.eclipse.equinox.launcher*.jar -Xms512m -Xmx2048m -Djava.awt.headless=true org.eclipse.core.launcher.Main -application msi.gama.headless.id4 ABM/headless/samples/roadTraffic.xml test1"

Host this php file  in web server with php enabled. Launch this page from any web browser. 

Here list my env stack:
Apache web server with CentOS
PHP 7.0.33 (cli) (built: Dec  6 2018 22:30:44) ( NTS )
CentOS Linux release 7.7.1908 (Core)
GAMA 1.8.1
Build-in java with GAMA
Chrome or Firefox web browser

Please feel free to let me know if you need further info. Many thanks!

Best,
Hai

**Comment by RoiArthurB** [comment]
Hello,

From what I'm trying it does work perfectly with PHP...

I'm doing some tests within the terminal in interactive mode and here's what I have : 
```
$ php -v
PHP 7.4.10 (cli) (built: Sep  2 2020 05:15:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

$  php -a               
Interactive shell

php > $time_start = microtime(true); shell_exec("~/.local/share/GAMA_1.8.1_Linux/headless/gama-headless.sh ~/.local/share/GAMA_1.8.1_Linux/headless/samples/roadTraffic.xml /tmp/head/out3"); $time_end = microtime(true); $time = $time_end - $time_start; echo "Took $time seconds\n";
Took 30.23508810997 seconds
```

Which is related to the execution time of the simulation : 
```
$ cat /tmp/head/out3/console-outputs-2.txt
/home/roiarthurb/.local/share/GAMA_1.8.1_Linux/headless/samples/./roadTraffic/models/model7.gaml model is being compiled...
Adding object pool: Execution Context
Adding object pool: Agent Execution Context
Adding object pool: Envelope 3D
Creation of road_traffic0
....................................................................................................Simulation duration: 24459ms
```

The launch time is around 5 seconds, which may also cover GAMA starting time 🤔

I'll try to create a short page script to launch GAMA and see the time there, but it more sounds like a performance problem from your server than from GAMA or PHP...

> Note : I'm using the bash script because it's simplier, but it works the same with the full java launch command :smiley:

**Comment by hlan** [comment]
Hello,

I tested in both bash and java way on my server with PHP interactive shell, it does work perfectly as you represented here. No delay at all. But the problem still exist when I applied a webpage to execute it, no matter using bash or java command. 

My guess is it might be some issue related to web server permission in the OS during execute the GAMA command. Because I did not see any significant delay when I was trying to test some system commands e.g. exec('mkdir someFolder') from webpage via PHP. 

Please let me know once you try it on web page and see how it goes. Thanks!

**Comment by hqnghi88** [comment]
Hi,
I tested with a local web server for php (wamp) and there is no delay.
![image](https://user-images.githubusercontent.com/6105384/96277095-04b4ce00-0ffe-11eb-950f-e4bbf7f7bd44.png)

**Comment by hlan** [comment]
Hi,
I tested it on Windows server with WAMP, it works perfect. I think you are right. It results from the deployment environment. But I'm not sure it is due to my specific CentOS env or for all linux-based OS. I'll double check and get back to you. Again! Many thanks! Problem solved.
