### ISSUE TITLE
MacBook Pro 2020 with macOS Catalina : the symbole ^ does not work

### ISSUE THREAD

**Issue by jferdelyi** [gama-platform/gama#3040]
**Describe the bug**
It seems to be impossible to write ^ in GAML. I can copy-paste from another place but, if I try to push twice the key next to 'P' (with ¨ and ^), it’s not working. 

**Desktop:**
 - OS: macOS Catalina
 - PC Model: MacBook Pro 2020
 - GAMA version: git
 - Java version: 1.8
 - Graphics cards: Intel Iris Plus Graphics 1536 Mo

**Comment by sriramab** [comment]
Is it the case with an external keyboard? I had a problem with an external keyboard. With a native keyboard, I did not have this problem.

**Comment by jferdelyi** [comment]
Yes indeed, but also sometimes with my native keyboard, it's really strange.

**Comment by AlexisDrogoul** [comment]
I can't reproduce this error, but I have a different configuration. macOS Big Sur and JDK 11 (actually it is the branch 1.8.2 which uses Eclipse 2021-03). Can you confirm you still get this issue with the new version of GAMA ?

**Comment by AlexisDrogoul** [comment]
@jferdelyi any updates on this one ?

**Comment by AlexisDrogoul** [comment]
Closing since it's impossible to reproduce it
