### ISSUE TITLE
Cannot inspect agents in a comodel (in opengl display)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3042]
**Describe the bug**
In a pure coupling model (such as City Boids Comodel.gaml), I was not able to inspect any agent of the simulation, neither from the Agents menu, nor from a right-click on the agent: no agents (but the world is proposed to be inspected in  the menus).

Note that the issue  appears only in an opengl display.

**To Reproduce**
1. Run the City Boids Comodel.gaml (from the model library)
2. Right-click on an agent to try to inspect it.

**Expected behavior**
To be able to inspect agents.

**Desktop (please complete the following information):**
 - OS: macOs Catalina
 - GAMA version: git

**Comment by jferdelyi** [comment]
**Describe the bug**

I have also some OpenGL issues but without co-modeling. (with the agent inspector too but sometimes without apparent reasons)

Some java stack like this

```
Exception in OpenGL:Waited 5000ms for: <23eaa00b, 5a3f2e62>[count 1, qsz 0, owner <main>] - <Animator thread>
java.lang.RuntimeException: Waited 5000ms for: <23eaa00b, 5a3f2e62>[count 1, qsz 0, owner <main>] - <Animator thread>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:170)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:975)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:674)
	at ummisco.gama.opengl.view.SWTGLAnimator.displayGL(SWTGLAnimator.java:201)
	at ummisco.gama.opengl.view.SWTGLAnimator.run(SWTGLAnimator.java:182)
	at java.lang.Thread.run(Thread.java:748)
```

Or macOS stack like this

```
Application Specific Signatures:

Process:               java [7759]
Path:                  /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java
Identifier:            java
Version:               1.0 (1.0)
Code Type:             X86-64 (Native)
Parent Process:        eclipse [7066]
Responsible:           eclipse [7066]
User ID:               501

Date/Time:             2020-11-03 11:40:01.432 +0100
OS Version:            Mac OS X 10.15.7 (19H2)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
Anonymous UUID:        1E1F5A6A-1682-44C9-B9BA-DE92AB04F51A


Time Awake Since Boot: 130000 seconds

System Integrity Protection: enabled

Crashed Thread:        52  Java: Animator thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Application Specific Signatures:
Graphics hardware encountered an error and was reset: 0x00000803
```

**Desktop**:

OS: macOS Catalina
PC Model: MacBook Pro 2020
GAMA version: git
Java version: 1.8
Graphics cards: Intel Iris Plus Graphics 1536 Mo

**Comment by AlexisDrogoul** [comment]
the two issues seem to be somewhat unrelated, and we are missing some information on the first one. Do OpenGL displays prevent the agents to appear also in the `Agents` menu ? Is it working correctly with Java2D displays ?

**Comment by AlexisDrogoul** [comment]
The issue dosent show up on my computer running Big Sur. So either it is linked with Catalina, or it was due to the more general bug on inspection and display sizes in HiDPI environments like yours. 
![main - UsersdrogoulGitgamamsi gama modelsmodelsToy ModelsComodelsCity BoidsCity Boids Comodel gaml 2021-09-19 23-29-08](https://user-images.githubusercontent.com/579256/133935285-f3875218-8c2e-4c99-b74d-6aeff987fff2.png)

I close it for now. Feel free to reopen if it manifests itself again.
