### ISSUE TITLE
Zoom in Java2D: cannot come back from a high zoom out

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3043]
**Describe the bug**
In any display with a Java2D display, when I zoom out too much, I cannot zoom in anymore.
When I try to zoom out, GAMA seems to move the camera instead.

**To Reproduce**
1. Run a model with a Java  2D display
2.Zoom out to the maximum
3. Try to zoom  in.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Looks like the problem comes from the solution for #2367. I have implemented a solution, please test !
