### ISSUE TITLE
comodels "Flood evacuation model" error

### ISSUE THREAD

**Issue by TGISer** [gama-platform/gama#3046]
**Describe the bug**

2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in 
NullPointerException: null
msi.gama.metamodel.topology.CompoundSpatialIndex.mergeWith(CompoundSpatialIndex.java:280)
msi.gama.metamodel.topology.continuous.RootTopology.mergeWith(RootTopology.java:53)
msi.gama.kernel.simulation.SimulationAgent.adoptTopologyOf(SimulationAgent.java:873)
msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:510)
msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:449)
msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
in agents Simulation 0, simple0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS High Sierra]
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: [e.g. git, 1.7.1, etc.]
 - Java version: [e.g. 1.8]
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]
macOS
GAMA version: 1.8.1

**Additional context**

**Comment by hqnghi88** [comment]
Hi, This error has been fixed in the continuous version of gama. Please recheck.

**Comment by TGISer** [comment]
Thank you so much! I will check it!
