### ISSUE TITLE
Save console output to a log file

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3047]
When applying GAMA in social simulations that involve communication, the output in the console is extremely useful because it traces the how the communication took place

Can you please allow saving the console output into a logfile?

**Comment by AlexisDrogoul** [comment]
The next version available (1.8.2) adds the "Saving to log" feature to the console and the interactive console.

**Comment by AlexisDrogoul** [comment]
Hi, have you been able to test it ? I'm closing it now as the functionality have been implemented and tested (by myself). Feel free to reopen if you discover flaws.

**Comment by Aya-Badawy89** [comment]
Hello Alexis,

I have just downloaded version 1.8.2 released 31/08. I tried it, and it worked. Thank you very much.
I was working on 1.8.1 till now, that’s why I did not test it, but I will move to the 1.8.2 to explore until the official release.

Best regards,
Aya
