### ISSUE TITLE
Where is RScript configuration in GAMA 1.8.1?

### ISSUE THREAD

**Issue by ichsan2895** [gama-platform/gama#3051]
Sorry for my newbie question

I have read https://gama-platform.github.io/wiki/CallingR.
I got stuck in In `"Config RScript's path", browse to your "Rscript" file (R language installed in your system).`
Where is that button in the "Preference"?

I have installed rJava plugin in GAMA v1.8.1
I have installed rJava library in my RStudio + configure `jri.dll` to correct directory

**Comment by hqnghi88** [comment]
Sorry , this place is not for asking questions, it is the place for posting issue, real problem of GAMA. Please refer to other channel as GAMA google group, GAMA facebook page.
And the button you are finding is in the last tab of preference dialog, you will see it when switch to the right tab.
Thanks.

**Comment by RoiArthurB** [comment]
Just to complete the answer, here's link to communicate with us : 

**Mailing list** :mailbox: 
- For Users: gama-platform@googlegroups.com (Here's the best place to ask questions :wink:  )
- For Developers: gama-dev@googlegroups.com

**Social networks** :+1: 
- https://www.facebook.com/GamaPlatform/
- https://www.linkedin.com/company/gama-platform/

**Comment by ichsan2895** [comment]
Thank you, I am already join that group recently
