### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3052]
**Describe the bug**
Two files in `mi.gama.core` have compilation errors:
 * GamaGMLFile.java (because of GMLReceiver and GMLFilter* object are not known)
 * LayoutGrid.java (because of import sun.awt.util.IdentityArrayList; )

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: git, eclipse 2020-09
 - Java version: java jdk 11

**Comment by AlexisDrogoul** [comment]
Should be solved by now !
