### ISSUE TITLE
SQLSKILL insert multiple rows

### ISSUE THREAD

**Issue by natohutch** [gama-platform/gama#3054]
I'd like to collect all the data for each agent over the experiment, and then at the end upload all the rows for each agent. I currently must ask each agent to upload a row on each timestep which is tremendously slow. I haven't found any documentation on how to do this so I assume the functionality is missing.

**Comment by hqnghi88** [comment]
Hi,
executeUpdate statement is the solution, you must gether your all rows with right SQL syntax (insert into ( ) values(...)) of each agents into a concatenated string and at the end you have a kind of : "insert into xxx values(); insert into xxx values(); insert into xxx values();", then do an executeUpdate with this string.

**Comment by natohutch** [comment]
Thanks got that to work :)
