### ISSUE TITLE
plus_days incorrect result

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#3056]
plus_days is adding seconds instead of adding days. 

example:

write type_of(current_date); // just to check that current_date is of date type.
write current_date plus_days 1; // expected to add a day, but adds seconds.

**Comment by sriramab** [comment]
Sorry, forgot to mention, Using   Gama	1.8.1.202006230234on macos Catalina.

**Comment by benoitgaudou** [comment]
Hi Srirama,

Using GAMA  1.8.1 (the release) with MacOs Catalina,

When  I write  :

global {

    init {

    write *date*('2000-01-01') *plus_days* 12;



    write (*current_date*); // just to check that current_date is of date
type.

write *current_date* *plus_days* 1; // expected to add a day, but adds
seconds

    }

}

I  get as result:

2000-01-13 00:00:00


1970-01-01 02:00:00

1970-01-02 02:00:00


This means that the  plus_days 1  behaves as  expected by adding  one  day
to the  date...

Cheers

Benoit

**Comment by sriramab** [comment]
Indeed. It was the reflex that was adding seconds along with  plus days. My bad.
