### ISSUE TITLE
GAMA 1.8.2 doesn't work well on my macOS Big Sur

### ISSUE THREAD

**Issue by jferdelyi** [gama-platform/gama#3057]
**Describe the bug**

GAMA doesn't work if I double click on the icon but work in the terminal. 
I did some tests: the click seems to not work correctly, because if I click on an element on the scene, the element is not selected.

I also tried to install the git version, and it's not working. I followed the git tutorial to install the git version but some steps are not the same.

**Screenshots**
<img width="416" alt="Capture d’écran 2021-01-28 à 10 50 44" src="https://user-images.githubusercontent.com/4105962/106120906-3d188c00-6157-11eb-83a1-6ca75bedb062.png">

<img width="619" alt="Capture d’écran 2021-01-28 à 11 35 26" src="https://user-images.githubusercontent.com/4105962/106126103-40af1180-615d-11eb-9dd0-9ec4271e89af.png">

<img width="716" alt="Capture d’écran 2021-01-28 à 10 55 30" src="https://user-images.githubusercontent.com/4105962/106121013-5c171e00-6157-11eb-94e0-a95cf60b9cde.png">

**Desktop:**
 - OS: macOS Big Sur
 - PC Model: MacBook Pro (13 pouces, 2020)
 - GAMA version: git 1.8.2 and alpha 1.8.2
 - Java version: 15.0.1
 - Graphics cards / Display system: Intel Iris Plus Graphics 1536 Mo
 - Eclipse:  2020-09 (4.17.0)

**Comment by hqnghi88** [comment]
Hi,
1. When did you download the alpha 1.8.2? It could have problem with the newest, but if it was 1 week ago, it should work well.
2.  The zoom, click in 3D environment sometime have glitch as my experience, but we could review it.
3. The important thing is, your eclipse show that you are using adoptopenjdk-8.jdk, which is not the one we tested on mac big sur,  we used jdk 15.0.1 , eclipse 2020-12 and git branch 1.8.2 , please retry with this combo and we ll see.

**Comment by jferdelyi** [comment]
Hi,

1. I downloaded the alpha yesterday.
2. It's strange because this bug occurs only on my built-in screen and never on my external screen.
3. You are right, I was sure that the good JDK was set.

Thank you it is working now

**Comment by benoitgaudou** [comment]
@jferdelyi Can we  close this issue now ?

**Comment by AlexisDrogoul** [comment]
The selection problem in OpenGL is probably related to #3086 and HiDPI screens. SWT has changed its support so it's probable that some of the workarounds we had implemented before are now causing these problems. I'll try to review it.

**Comment by AlexisDrogoul** [comment]
OK. Closing this one in favour of #3086, with the hope that you can test it.
