### ISSUE TITLE
GAMA gets stuck at "generating outputs" before the experiment 

### ISSUE THREAD

**Issue by sophiela92** [gama-platform/gama#3060]
[model_input.zip](https://github.com/gama-platform/gama/files/5983006/model_input.zip)

I am using GAMA version 1.8. Currently I am trying to transfer the Salzburg bicycle traffic model to another study area. I am slipping from error message to error message. The current one crashes GAMA and I don't understand why. The initialization code runs through, but GAMA gets stuck at "generating outputs" before the experiment can be started. 
I have attached the model code to this issue as well as the error message and the input data. 
To reproduce the error you have to start the model and wait until "No feedback" appears in the window. 

![2021-02-15 17_51_28-Gama](https://user-images.githubusercontent.com/79104477/107974456-eb755b80-6fb6-11eb-9b31-58ff8768895b.png)
[Tue_bicycle_model.txt](https://github.com/gama-platform/gama/files/5982987/Tue_bicycle_model.txt)

)

**Expected behavior**
Usually GAMA should not crash and continue to run normally

**Desktop (please complete the following information):**
 - OS: Windows10 Home
 - PC Model: HP Pavilion Power Laptop 15 -cb0xx
 - GAMA version: 1.8
 - Java version: 11.0.2 (64-bit=
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Comment by hqnghi88** [comment]
Hi,
Could you try one thing: replace all opengl by java2D display? I tried your model with model_input, wait until it show this (i removed other displays)
![image](https://user-images.githubusercontent.com/6105384/108015860-c24edc80-7043-11eb-84f5-b74e228fc317.png)

**Comment by sophiela92** [comment]
Hi,

I tried hiding the displays, but unfortunately it didn't have the desired
effect. Unfortunately, I don't know how to hide the parameters on the left
side without excluding them completely.

**Comment by hqnghi88** [comment]
Hi,
"desired effect" means it does not crash or it still crash? I just want you to test if they are all java2D displays, does it crash anymore? Because i have experience on win OS, some version have conflict with "automatically switch to high performance graphics". So i must declare in win OS that GAMA use always "High performance GPU" and it works.

**Comment by AlexisDrogoul** [comment]
Hi, any update on this one or can we close it ?
