### ISSUE TITLE
Two different user_input syntax

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3062]
In the current version (1.8.2 and also 1.8) , and related with #3061, i found that we have 2 totally different syntax of a keyword "user_input". It is conflict/ambiguous in some case.
![image](https://user-images.githubusercontent.com/6105384/108734575-2f8dd080-7562-11eb-833c-576af0a06fe3.png)
Should we change the one that pop up a dialog to "user_input_dialog" to distinct with the "user_input" in user panel view?

**Comment by AlexisDrogoul** [comment]
You're right. I've deprecated `user_input` in its operator form in favour of `user_input_dialog`. I've also updated the models using the deprecated form.

**Comment by AlexisDrogoul** [comment]
I guess this one can be closed, right ?
