### ISSUE TITLE
Gama 1.8.2 Alpha doesn't work with OpenJDK8/11

### ISSUE THREAD

**Issue by ndgnuh** [gama-platform/gama#3063]
**Describe the bug**
Gama 1.8.2 (the without-JDK version) crash on opening.

**To Reproduce**
1. Setup Java env (both openjdk8 and openjdk11 will reproduce the bug)
2. `./Gama`

**Desktop (please complete the following information):**
 - OS: Linux 5.10
 - PC Model: Lenovo Thinkpad13
 - GAMA version: 1.8.2 alpha, downloaded from release page
 - Java version: openjdk8, openjdk11,
 - Graphics cards / Display system: Intel HD Graphic 620

Log for openjdk8: https://pastebin.com/raw/1UzmCenf
Log for openjdk11: https://pastebin.com/raw/HwsLMz9i

**Comment by hqnghi88** [comment]
Hi,
How about jdk 15?

**Comment by ndgnuh** [comment]
I have not installed it yet. I'll report back after testing.

**Comment by ndgnuh** [comment]
Openjdk15 doesn't cause such crash, I used the RI version.

**Comment by hqnghi88** [comment]
Ok Thanks,
Jdk 8 will be outdated soon so gama 1.8.2 base in 11+.  However it seem jdk 11 is not compatible with jdk 15 binary. I will rebuild gama 1.8.2 for jdk tomorrow and let you know.

**Comment by hqnghi88** [comment]
Can you please retry today build?

**Comment by ndgnuh** [comment]
I can open 1.8.2 with openjdk11 now, thank you. It still doesn't run with openjdk8, but jdk8 is going to be deprecated anyway, so it's irrelevant.
