### ISSUE TITLE
Theme change in Gama 1.8.2

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3064]
**Bug Description:**
In Gama 1.8.2, when changing the appearance theme, the change is applied well before the restart. After restarting, the appearance looks different from the one applied as if it returned back to normal.

**Desktop:**
 - GAMA version: 1.8.2
 - Java version: 15
![Screenshot 2021-02-24 11 39 15](https://user-images.githubusercontent.com/60944260/108996022-cdce8300-7695-11eb-86c5-10fc1298316f.png)
![Screenshot 2021-02-24 11 39 56](https://user-images.githubusercontent.com/60944260/108996026-cdce8300-7695-11eb-8049-0bc6c5a49418.png)

**Comment by AlexisDrogoul** [comment]
This is normal and unavoidable (this is how Eclipse works). To make sure users get a correct experience, setting the preference to a new theme now invites to restart GAMA as soon as possible.
