### ISSUE TITLE
The size of the display layer

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3065]
When we display number of charts in GAMA, the layer size seems to fill the screen.
If I added a species aspect or an event statement in the same display, the layer  automatically shrinks.
I have attached a screenshot of the two cases. How can I keep the layer of charts filling the screen?

![Screenshot 2021-03-01 12 03 10](https://user-images.githubusercontent.com/60944260/109494693-216e1180-7a86-11eb-90d5-697cb45e885d.png)

![Screenshot 2021-03-01 12 33 19](https://user-images.githubusercontent.com/60944260/109497728-65fbac00-7a8a-11eb-97f8-0b26329f660e.png)

**Comment by benoitgaudou** [comment]
Dear

Could you share the code of your experiment to try to help you ?

Cheers

Benoît

Le lun. 1 mars 2021 à 13:35, Aya-Badawy89 <notifications@github.com> a
écrit :

**Comment by Aya-Badawy89** [comment]
Hello Benoit,

Thank you for your reply.
Suppose we take the model in the library named (XY.gaml).
1) Open the simulation perspective and observe how it looks
2) Go back to the modelling perspective and add any image to the display.
3) If you go back to the simulation perspective again, you will find that the display looks smaller!

I don't know how I can solve this.

Regards,

Aya Badawy

PhD Candidate, Planning and Environmental Management
Spatial Policy and Analysis Lab, Manchester Urban Institute
University of Manchester, UK, M13 9PL


________________________________

**Comment by Aya-Badawy89** [comment]
This issue was solved by changing the environment size in the global species
