### ISSUE TITLE
[1.8.2] Some tutorials is broken, weird behavior introduced.

### ISSUE THREAD

**Issue by ndgnuh** [gama-platform/gama#3066]
**Describe the bug**
Weird behavior and uncaught exception in (many) tutorial models.

**To Reproduce**
1. Go to Library models, Tutorials, Predator Preys (Model 13)
2. Editor will show errors:
```gama
reflex save_result when: (nb_preys > 0) and (nb_predators > 0) { /* <--- Error at this line */ }
```

Description | Project | Resource | Location
---|---|---|---
No operator found for applying 'and' to types [unknown, unknown] (operators available for [types [predicate, predicate], types [bool, unknown]]) | Tutorials | Model 13.gaml | line: 40 /Tutorials/Predator Prey/models/Model 13.gaml
3. Additionally, force casting the comparision to `bool` fix it, but this is very annoying and seems unwanted since comparisons should produce a `bool` already.
4. Afterward, run the model and receive another exception:
```
3 occurrences in 3 agents at cycle 0: Java error: nil value detected
in color <- rgb(map_init at nil);
NullPointerException: Cannot invoke "msi.gama.metamodel.shape.ILocation.getX()" because "<parameter2>" is null
msi.gama.util.matrix.GamaMatrix.get(GamaMatrix.java:282)
msi.gama.util.matrix.GamaMatrix.get(GamaMatrix.java:1)
msi.gama.util.file.GamaFile.get(GamaFile.java:311)
msi.gaml.operators.Containers.at(Containers.java:353)
gaml.additions.core.GamlAdditions.lambda$493(GamlAdditions.java:555)
msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
when applying the at operator on file('/home/hung/opt/GamaNoJDK182/configuration/org.eclipse.osgi/225/0/.cp/models/Tutorials/Predator Prey/includes/data/raster_map.png') and nil
in color <- rgb(map_init at nil);
in ask vegetation_cell  {
	color <- rgb(map_init at nil);
	food <- 1 - ((list<int>(color) at 0) / 255);
	food_prod <- food / 100;
}

in ask vegetation_cell  {
	color <- rgb(map_init at nil);
	food <- 1 - ((list<int>(color) at 0) / 255);
	food_prod <- food / 100;
}

in init  {
	create prey number: nb_preys_init ;
	create predator number: nb_predators_init ;
	ask vegetation_cell  {
		color <- rgb(map_init at nil);
		food <- 1 - ((list<int>(color) at 0) / 255);
		food_prod <- food / 100;
	}

}

in agents vegetation_cell0, Simulation 0, prey_predator0
```

which points to these lines of code:
```
init {
	create prey number: nb_preys_init;
	create predator number: nb_predators_init;
	ask vegetation_cell {
		color <- rgb(map_init at {grid_x, grid_y}); // <--- this one
		food <- 1 - (((color as list) at 0) / 255);
		food_prod <- food / 100;
	}
}
```

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/33273948/109608789-04584200-7b5d-11eb-9048-3b354dc170ae.png)
![image](https://user-images.githubusercontent.com/33273948/109609232-a37d3980-7b5d-11eb-8634-105f72601830.png)

**Desktop (please complete the following information):**
 - OS: Linux 5.10.19
 - PC Model: Lenovo Thinkpad 13
 - GAMA version: 1.8.2 No JDK Version, commit 652f6fb, downloaded from release page
 - Java version: OpenJDK 15 (RI)
 - Graphics cards / Display system: Intel HD Graphics 620

**Additional context**
Gama log file: https://paste.c-net.org/WindowGreta

**Comment by AlexisDrogoul** [comment]
Strange. Are you using the developer version or did you download the executable ?
If you are using the developer version, try to clean and rebuild all projects before running GAMA.
If you are using the app, try to create a new workspace and switch to it. 
I hope one of these two fixes will help you !

**Comment by ndgnuh** [comment]
I downloaded the executable from release page. I tried downloading the version bundled with JDK and create a new workspace, it doesn't help though, I can still reproduce the errors.

**Comment by hqnghi88** [comment]
Hi,
Just tested with new download withJDK package and new blank workspace on windows 10 OS, there is no error at all. May be @RoiArthurB can have a test on linux or i will try later. But why did you mentioned commit 652f6fb ? the current release of 1.8.2 is https://github.com/gama-platform/gama/releases/download/1.8.2/GAMA_1.8.2_Alpha_withJDK_Linux_02.24.21_e71f3454.zip

**Comment by ndgnuh** [comment]
I thought that there were some commits between 1.8.2 before and 1.8.2 after #3063, so I put the hash there to distinguish them :facepalm:  If they are irrelevant, please don't mind the commit hash then

**Comment by hqnghi88** [comment]
I tested on ubuntu mate 20.0.4, with the withJDK release, and have some glitches : displays are blank, but i have no syntax errors in any models. 
One possible reason is the different of jdk 11 and jdk 15. For a previous issue of @ndgnuh , i rebuilt this release by using jdk 11 and for jdk 11, so it could have some compability problem with jdk 15. I relaunch a build for a release base on jdk15 and we ll see.

**Comment by ndgnuh** [comment]
Have we had any progress on this issue yet? I found out that there's some thing wrong with the `->` operator. Some Gama would not be able to infer the type of variable declared by `int nb_preys -> length(prey);`. But this would be totally fine:
```gaml
int nb_preys <- length(prey.population) update: length(prey.population);
```

Also, the same kind of bug happens with `grid_x` and `grid_y` (which is used in the `Predator Prey/model13` file, also). Inside a `reflex`, `ask`..., `self.grid_x`  works but not  `grid_x`.

**Comment by ndgnuh** [comment]
We managed to figure out that something is wrong with the cache directory. If one install Gama from Eclipse, they can workaround by setting the cache path to something else by pressing on the `Run configuration`
![image](https://user-images.githubusercontent.com/33273948/113376013-ee77b000-939a-11eb-9cc1-501ed0b576dd.png)

under `Workspace data`, change the path to `${workspace_loc}/runtime-gama.runtime.product` (or any directory that you may access, maybe). After that, clean and rebuild Gama. Finally, in Gama, click on clean and validate the models.
![image](https://user-images.githubusercontent.com/33273948/113376337-a60cc200-939b-11eb-9bc7-4c403f491927.png)

**Comment by AlexisDrogoul** [comment]
It is probably something related to the ownership of the cache directory. 
Can we close this issue or should we establish a specific documentation somewhere on the developer section ?

**Comment by ndgnuh** [comment]
But how do we workaround this error on GAMA only? I don't see the option the set the cache directory.

**Comment by AlexisDrogoul** [comment]
Have you been able to circumvent this error ? The data location (where settings and data reside) can be set in Gama.ini the same way that it is set in the Run Configuration, so I guess this is the solution for this unusual behaviour...
