### ISSUE TITLE
Problem with variables declaration

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#3068]
**Describe the bug**

This issue seems to be related to [https://github.com/CityScope/CS_Proxymix/issues/164](https://github.com/CityScope/CS_Proxymix/issues/164) that was discussed by mail with @hqnghi88.

There is a problem related to variables declaration. In a model, we declare a dummy variable that is never used, and the simulation crashes (it works if the declaration is commented). It seems like there is something like too many variables.

**To Reproduce**

1. get the following model [proxymix](https://github.com/CityScope/CS_Proxymix). Sorry it is quite a large model, but since this strange behavior is related to the complexity of the model, we don't have a simplified version for this issue.
2. Install the pedestrian skill.
3. Run the experiment "Episode 1 Mask" in Proxymix_Scenario.gaml. At this point, the simulation should work fine.
4. Uncomment line 13 ("bool dummy_very_weird_variable;") in CityScope_Coronaizer.gaml. It just declares a dummy variable that is used at all in any file of the model.
5. The model crashes, with non-reproducible behavior. Sometimes there is a division by 0, sometimes it seems to initialize but it is not possible to run the experiment, and sometimes the experiments load indefinitly.

**Desktop (please complete the following information):**
 - OS: Win10 and Mac
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: 1.8.1 with JDK and 1.8.1 daily build.

**Comment by AlexisDrogoul** [comment]
What the history of this bug, as you say it has been discussed before. Has there been a fix proposed ? A workaround ? Specific commits on GAMA ?

**Comment by hqnghi88** [comment]
Dear Alexis,
It was not a clearly a discussion, as i just mentioned about my debugging traces (you should already received the private email from Arnaud and Patrick). So no workaround and no commit.

**Comment by ptaillandier** [comment]
To facilitate the tracking of this issue, I propose a more simple
model (attached to this email) using no data, no plugins and no imported
file. Just load the debug experiment and run the model (at least one step).

I tested the model with GAMA 1.8.1 (release) and GAMA 1.8.2 (git) and I
have the same issue: if you uncomment line 161, the VirtualPeople agents
(mirror species) are well created; if commented, the agents are not
created.... If line 170 is uncommented,  the agent are created....
If you change one line of the code, the behavior is changed..... I do not
understand at all.....

Patrick

Le jeu. 11 mars 2021 à 12:48, HUYNH Quang-Nghi ***@***.***> a
écrit :

**Comment by agrignard** [comment]
@ptaillandier I am not sure you sent the simple model? Indeed it would be easier to have it to debug it.

**Comment by AlexisDrogoul** [comment]
Needs to be tested, but the issue has been completely solved on my side.

**Comment by agrignard** [comment]
I don't remember how we can test this one?
