### ISSUE TITLE
Workspace setting windows can not change size on Wayland.

### ISSUE THREAD

**Issue by amaothree** [gama-platform/gama#3070]
**Describe the bug**
Workspace setting windows display too small to show all content on Wayland. And the windows can not resize.

**To Reproduce**
1. Run Gama

**Expected behavior**
The window is resizable.

**Screenshots**
![Screenshot-20210313025915-399x467](https://user-images.githubusercontent.com/26244249/111015952-7f1a2c00-83ab-11eb-881b-919264c950bc.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux - kernel-5.11.5.arch1-1
 - PC Model: MSI GS65 (CPU: Intel 9750H)
 - GAMA version: 1.8.2 Alpha-03.03.21
 - Java version: I tried openjdk 15 and the gama with jre version
 - Graphics cards / Display system: Intel UHD Graphics 630 + NVIDIA GeForce RTX 2070 Mobile (Only Intel card is working.) Gnome on Wayland

**Comment by minhduc0711** [comment]
I believe that the GAMA IDE is based on Eclipse, and Eclipse itself is very buggy when running on native Wayland.
If you haven't tried this, a workaround is to install `xwayland` to run GAMA as an Xorg client. 
(fyi, after that you can use `xeyes` to check if GAMA is running under X, i.e. if the eyes move as you move the mouse cursor inside GAMA)

**Comment by amaothree** [comment]
> I believe that the GAMA IDE is based on Eclipse, and Eclipse itself is very buggy when running on native Wayland.
> If you haven't tried this, a workaround is to install `xwayland` to run GAMA as an Xorg client.
> (fyi, after that you can use `xeyes` to check if GAMA is running under X, i.e. if the eyes move as you move the mouse cursor inside GAMA)

This is right.

Xwayland is installed in my system. However it will not enable automatically when a java program running. I have to override the environment variable.
