### ISSUE TITLE
Edit google docs spreadsheet with Gama

### ISSUE THREAD

**Issue by FlorenceTauc** [gama-platform/gama#3075]
Hi everyone! I would like to edit existing google docs spreadsheet with Gama (as it is possible in R), and it would be great to add this feature to the platform. 
As I want to make my project easily accessible to non-specialist persons, I would rather not call R in Gama (because the links between Gama and R are not easy to make).

Thank you very much!

**Comment by AlexisDrogoul** [comment]
There is no real reason to want to edit GDoc spreadsheets directly within GAMA. What would be the point ? I close this issue, but if you have a real use-case, we might reconsider !

**Comment by hqnghi88** [comment]
In fact , i agree that edit only docs or spreadsheet does not make sense. but i;ve got real usecase on other office file types (word, excel - instead of csv). i will create another more specific issue.
