### ISSUE TITLE
Accessing GAMA in server mode through the headless

### ISSUE THREAD

**Issue by choisy** [gama-platform/gama#3076]
**Description of the problem:**
We are developing an R package that interfaces GAMA. One thing that this package does is reading a GAML file using the parser of the headless of GAMA. If the user happens to have to read several GAML files, this involves relaunching the JVM as many times as the number of GAML files (s)he need to read, which represents quite a big fixed cost in terms of time, just for parsing GAML files.

**Proposed solution:**
Is it possible to have GAMA running in some sort of a server mode that we could access through the headless? It could be a switch option on the way to use the headless: leaving GAMA alive and available once the job sent through the headless is done, or not.

**Comment by RoiArthurB** [comment]
TODO:
- [ ] Create a headless daemon (unix definition)
  - [ ] Single command to start the headless in daemon
  - [ ] Flag within a headless command
- [ ] Destroy the daemon (command)
- [ ] Auto-Redirect any headless command on the daemon

Other things to test : 
- [ ] Compatibility with [GAMAR](https://github.com/r-and-gama/gamar/) project

**Comment by RoiArthurB** [comment]
@choisy Do you think the work started there ( https://github.com/gama-platform/gama/discussions/3088 ) could help in your issue too ? 🤔🤷

**Comment by choisy** [comment]
Sure! That is something I've proposed in 2015 or 2016 but nobody seemed to be keen on this idea back then...

**Comment by ndgnuh** [comment]
So after a while searching for way to create a daemon, this link came up:

https://stackoverflow.com/questions/45233882/make-a-unix-daemon-in-java

In short, there's no way to create a daemon purely and directly from Java, without JNI or some linux command that won't work on both Windows and MacOS.

**Comment by AlexisDrogoul** [comment]
Just one question : why do you want to make a daemon out of GAMA (wouldn't a running program answering requests through a pipe work as well) ? And if building a daemon is absolutely mandatory, why not simply use http://commons.apache.org/proper/commons-daemon/ ? It should work on all environments.

**Comment by ndgnuh** [comment]
About that, I have not been able to try out pre-written libraries in Java yet as I'm struggling with adding dependencies to the project

**Comment by hqnghi88** [comment]
Can you push it somewhere on github and we can help for accelerate the process

**Comment by ndgnuh** [comment]
Nevermind, I really just adding dependency, nothing else, I think I've figured that out.

Anyway, if I understand correctly, the idea is to write a new, compact headless module which does not do anything but processing the cli args. Another module (the current headless)  will do the actual work and loaded by the new one. That way, the new module will act as a client to send request to the "daemon". Obviously the old headless will have to implement server-like functionality.

It's not necessary to have an actual daemon, we just need a long lived process which can do communication somehow.

**Comment by AlexisDrogoul** [comment]
Hi @hqnghi88, are the recent commits (d600af94af0d8d40d73cbb3fe893b536201fdb37 and 82f67f8d7b2f44f84eb00352ede821e1f8f7166b) related to this issue ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Yes, im trying to provide something can be test in public

**Comment by AlexisDrogoul** [comment]
No problem if I try to fix #2984 in parallel ? I try to make it "self-contained" (i.e. better manage things inside the class)

**Comment by hqnghi88** [comment]
Yes, no problem, i will update on my side. I see something could be changes in that class but later

**Comment by AlexisDrogoul** [comment]
@hqnghi88 should we consider this issue as closed ?

**Comment by hqnghi88** [comment]
Dear Alexis,
i would like to try it on gamar before close this issue (today, after the bug of tcp model).

**Comment by AlexisDrogoul** [comment]
Any news ?

**Comment by hqnghi88** [comment]
Sorry, i did not successfully make a conversation with R in mode listening because the current code base of rama is still base on the normal headless. 
<img width="586" alt="image" src="https://user-images.githubusercontent.com/6105384/160275361-a34813cb-4808-4dfb-b17e-fe6690e2a4b8.png">

I am looking for small modif in rama then, i supposed that we can close this issue for now and i will come back later soon,

**Comment by choisy** [comment]
Great! @hqnghi88 any possibility we have a zoom call sometimes so that you show me through the new headless?

**Comment by hqnghi88** [comment]
Dear Marc,
Yes of course, maybe next week, i need one more week to make this feature more friendly abd stable.

**Comment by choisy** [comment]
Wonderful, any time is convenient for you, just let me know when you're ready.
Thanks a lot.

**Comment by hqnghi88** [comment]
Hi,
I add here a draft tutorial that i just try on R. Assumed that we have a gama headless listener started (by out-of-R terminal or by call java in R): the different syntax with normal headless is -socket num_port, ie 
gama-headless.bat -socket 6868
./gama-headless.sh -socket 6868
<img width="875" alt="image" src="https://user-images.githubusercontent.com/6105384/160694329-d51be22a-7b88-4c63-aa62-aa965a9a64db.png">



Then in R, after installation of websocket package, i tried:
library(websocket)
ws <- WebSocket$new("ws://localhost:6868/launch", autoConnect = FALSE)
ws$onOpen(function(event) {
  cat("Connection opened\n")
	 ws$send("launch@C:\\git\\COMOKIT-Model\\COMOKIT\\Experiments\\Lockdown\\LockDown.gaml@Lockdown@false")
})
ws$onMessage(function(event) {
  cat("Client got msg: ", event$data, "\n")
})
ws$onClose(function(event) {
  cat("Client disconnected with code ", event$code,
    " and reason ", event$reason, "\n", sep = "")
})
ws$onError(function(event) {
  cat("Client failed to connect: ", event$message, "\n")
})

Note: api syntax: launch@path_to_model@name_of_experiment@export_variables
When we connect this socket to listener
ws$connect()
The model will be compiled and the experiment will start. We'll get the return message when it's ready.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/6105384/160694723-4e131696-ff82-449d-817a-bb1d5d85e415.png">
In that message, we have the id of socket and id of experiment which is important to be reused after : exp@**1091299022**@**0**
(dont know if r can split string to extract this information??
socket_id= 1091299022
experiment_id= 0
)
Next, we can control the life cycle of that experiment by other api: play, pause, step, stop, given the id_of_experiment in previous message.
ws$send("play@0")
ws$send("pause@0")
ws$send("step@0")

We can launch other experiment of models in parallel without restart/start other instance of gama listener.
And beside the export files as normal headless did as usual. we can ask for expression evaluation in runtime with websocket connect to endpoint /output. For example, i create another ws1

ws1 <- WebSocket$new("ws://localhost:6868/output", autoConnect = FALSE)
ws1$onOpen(function(event) {
  cat("Connection opened\n")
})
ws1$onMessage(function(event) {
  cat("Client got msg: ", event$data, "\n")
})
ws1$onClose(function(event) {
  cat("Client disconnected with code ", event$code,
    " and reason ", event$reason, "\n", sep = "")
})
ws1$onError(function(event) {
  cat("Client failed to connect: ", event$message, "\n")
})
Then asking for **length(all_individuals where (each.is_infectious))** evaluation of the **experiment** launched by **socket** (the socket_id and experiment_id above, return from ws)

ws1$send("expression@**1091299022**@0@length(all_individuals where (each.is_infectious))")

or simpler:
ws1$send("expression@**1091299022**@0@cycle")  
<img width="385" alt="image" src="https://user-images.githubusercontent.com/6105384/160696355-3028d086-4930-4766-be21-ce68742c64f7.png">


I hope that it is fit with your requirement, of course there are many thing to optimize.
