### ISSUE TITLE
Using (between) operator

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3077]
**Describe the bug**
When writing: 
`bool feasible <- between(0.8 ,0.01, 1);`

**Expected behavior**
It returns false when it should give true. The problem is solved when we convert the (1) to a float with 2 decimal places. This means that if integers are used with float in this operator, it does not function properly

**Comment by benoitgaudou** [comment]
When I look at the documentation, between is only defined with 3  integers or 3  floats as parameters.

In this case, it  is used with float, float , int. 
In  this situation,  GAMA displays a message explaining that the float operands will be truncated as integer (which you explain  your issue).

<img width="483" alt="Screenshot 2021-03-25 at 22 51 43" src="https://user-images.githubusercontent.com/1555274/112548604-c39ac400-8dbc-11eb-8763-1e6e2472aaa9.png">

**Comment by RoiArthurB** [comment]
The way to fix it will be to turn the last `int` in `float` like this : 
```
write between(0.8, 0.01, 1.0);
```

Also, here's the documentation for this operator : https://gama-platform.github.io/wiki/OperatorsBC#between
