### ISSUE TITLE
Sharing of Formatter templates and Working Sets

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3082]
Dear @AlexisDrogoul ,
This is just a reminder.
It seems to be easier for new developers to begin with the gama git version in eclipse. We would like to have a shared formatter templates for codes formatting. And also an Exported Working Sets (as a guide below) 
![image](https://user-images.githubusercontent.com/6105384/113420919-5f978180-93f4-11eb-97a1-228cdd2ccf49.png)

**Comment by AlexisDrogoul** [comment]
I've exported four files which should cover the main preferences. CleanUp actions, Formatter, WorkingSet & Projects, as well as general prefs.

**Comment by AlexisDrogoul** [comment]
I've tried it in another Eclipse installation and it works well ! We should probably, in order to simplify the installation, put it in a special project, ask people to only download this project first and then let the magic happen when they choose to import projects/working sets/preferences.

**Comment by hqnghi88** [comment]
You mean a new repository with only 1 project - Starter ?

**Comment by hqnghi88** [comment]
@AlexisDrogoul i tried and it seems ok, but  one small point: 
the git code compiled with maven, however, in eclipse it does not, is it normal with the current commit or just my mistake? does it relate with some preference about error in eclipse?
![image](https://user-images.githubusercontent.com/6105384/113541251-0bff8080-960c-11eb-818d-bb8ac2f36290.png)

**Comment by ndgnuh** [comment]
> ![image](https://user-images.githubusercontent.com/6105384/113541251-0bff8080-960c-11eb-818d-bb8ac2f36290.png)

I got this error too. Maybe caused by 83f0652f8ad9455a715f574d4c0624bd06b871ae (I traced to the last working commit)

> the git code compiled with maven, however, in eclipse it does not

Why are we using two build system and not one?

**Comment by hqnghi88** [comment]
Ok, we wait a bit for coming changes.
@ndgnuh one for development (ide with all gui possiblities) one for CI/CD (maven, there is gradle but we chose maven).

**Comment by AlexisDrogoul** [comment]
It does not happen in my MacOS installation. Strange. Anyway, I've committed a temporary fix for this as I have no time to dig which library declares java.xml in addition to the JVM (I'd bet it is jaxb, but we need to have it).

@ndgnuh : the two build systems are necessary for enabling both the incremental build in Eclipse and the Maven build (you don't want Maven to kick in and recompile everything  everytime you write a change). On the other hand, having a Maven build is necessary to package the desktop versions, etc.

**Comment by hqnghi88** [comment]
this issue is fixed already with 4 files in ummisco.gama.product.
