### ISSUE TITLE
Wrong size of  the environment and location of  the  {0,0} point

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3086]
**Describe the bug**
When launching simulations with GIS data, the size of the environment seems to be wrong, and the {0,0} point is not localized in the upper-left corner.

**To Reproduce**
1. Launch the Road  Traffic Tutorial, model 1
2. Find the {0,0} point

**Expected behavior**
The {0,0} should be in the upper-left corner and the size of the environment should  be the same at when viewing the GIS file in GAMA.

**Screenshots**
Here the road should be 1km long.
![image](https://user-images.githubusercontent.com/1555274/114152859-09a86980-991f-11eb-8b47-df72b9d4135c.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina and  Big sure
 - GAMA version: 1.8.2

**Comment by AlexisDrogoul** [comment]
Looks like the move to GeoTools 25 and JTS 1.8.1 is maybe creating problems ...

**Comment by AlexisDrogoul** [comment]
Hi,
I have followed your instructions, but I cannot reproduce anything... are you sure it is the right model you're talking about ?

**Comment by ptaillandier** [comment]
I tried as well, and I have no problem with the {0,0} point. Concerning the size of the roads/world, it seems ok as well (I compared with QGIS). The only issue I get is with the "scale" that seems to show wrong values (not a critical issue, but we should fix it).

**Comment by ptaillandier** [comment]
Just a note: the problem with the scale only occurs with Opengl and not with java2D... maybe a perspective issue (I didn't check the result with GAMA 1.8.1).

**Comment by AlexisDrogoul** [comment]
Like @ptaillandier. I re-checked and I have no issue with the `{0,0}` point but the scale is actually wrong (and I would bet it has something to do with the way HiDPI screens are (better) handled now by SWT).

**Comment by benoitgaudou** [comment]
Hi,
On the source code version of GAMA 1.8.2, I just launched the Road Traffic Tutorial, model 1.
Depending on the size of the windows, the {0,0} is not localized at the same position.  See pictures below.
Two remarks:
- I have the issue only on an OpenGL display.
- It seems to be only a display issue: when I create an agent at {0,0}, it appears on the top-left corner (expected location)

<img width="1762" alt="Screenshot 2021-04-21 at 11 04 42" src="https://user-images.githubusercontent.com/1555274/115528228-25522f00-a292-11eb-9c1d-8da5fd2e6d6d.png">
<img width="1762" alt="Screenshot 2021-04-21 at 11 05 57" src="https://user-images.githubusercontent.com/1555274/115528250-2a16e300-a292-11eb-928c-aaaf17e0baf5.png">

**Comment by AlexisDrogoul** [comment]
Did the recent commits solve this issue ? I cant reproduce it anymore on macOS.

**Comment by benoitgaudou** [comment]
I can't repoduce it ... so it should be fixed :-)
thx!
