### ISSUE TITLE
[REQUEST] Enable flat design by default

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#3089]
**Is your request related to a problem? Please describe.**
Since an option in `Preference` allow switching GAMA's graphs in flat design, I think it would be a good point to have it enabled by default. The current default display really start to look old and it'll easily enhance the UI.

Current default display :
![2021-04-13_13-22](https://user-images.githubusercontent.com/16764085/114506339-da199a00-9c5b-11eb-9f26-75eb207a6210.png)

Flat display (requested default) : 
![image](https://user-images.githubusercontent.com/16764085/114506839-878cad80-9c5c-11eb-9150-04788f9c4eb1.png)

**Describe the solution you'd like**
Enable the _flat design_ by default.

**Addition informations**
The option is currently under Preferences > Displays > Charts Preferences > Display 'flat' histograms
![image](https://user-images.githubusercontent.com/16764085/114507077-d4708400-9c5c-11eb-9fb6-a4f43ca83138.png)

**Comment by AlexisDrogoul** [comment]
Agree. Will push the (simple) fix now.
