### ISSUE TITLE
GIS coordinate system preference - inconsistent true/false flag

### ISSUE THREAD

**Issue by f-colli** [gama-platform/gama#3092]
Dear all,
it seems that the preference: _Let GAMA find which CRS to use to project GIS data_ is set to _true_ by default, inconsistently with the documentation: https://gama-platform.github.io/wiki/Preferences#data-and-operators which states it is set to false. Furthermore, the option for the CRS specification is not greyed out even if the main flag is set to _true_.
I went through this issue as I found that the sample data from Hanoi in the _Segregarion (Schelling)_ folder, is not projected (WGS84DD) so I was wondering how GAMA managed these data. The model is not used for planar calculation, however it is maybe better to include projected data in order to avoid distortions in the representations.
Back to the main issue, you may want to fix either the default value in the interface or the documentation:

![preferences](https://user-images.githubusercontent.com/19976452/115141476-cb0c6080-a03c-11eb-983d-f2d25691efb4.jpg)
![preferences2](https://user-images.githubusercontent.com/19976452/115141505-0313a380-a03d-11eb-8476-3776b9c616ac.jpg)

Best,
Francesco

**Comment by AlexisDrogoul** [comment]
Hi,

Thanks a lot for this detailed report. You are right, the default is `true` and it should be documented this way (I will fix as soon as possible). Concerning the greying out of the second option, actually, the EPSG code is used for two purposes: either forcing the CRS to use when the first preference is false, or a fallback option when GAMA is unable to determine which CRS to use. However, I admit it is a little bit ambiguous.

Finally, regarding the _Segregation_ model, there are lots of models in the libraries that do not provide projected coordinates. Unprojected coordinate systems like WGS84DD should be sufficient for what these models are supposed to demonstrate. But feel free, especially if you think it would be important for users, to submit a request for improvement or even a pull request with some default projections. 

Thanks again ! 
Alexis

**Comment by AlexisDrogoul** [comment]
Documentation has been edited. Wait a few hours before it is regenerated.

**Comment by f-colli** [comment]
Thank you @AlexisDrogoul for this fix, I am happy to collaborate! I understand that option is used as fallback as well hence should not be greyed out in any case. Concerning the sample datasets, I see this in the _Segregation_ and the Can Tho one in _Urban Growth_ are not projected. However, I agree with you that both suffice the purpose of demonstration. I'll take your suggestion to open a separate request in the case.

**Comment by AlexisDrogoul** [comment]
Thanks for your comment. I've verified that the documentation has been updated correctly. I now close this issue.
