### ISSUE TITLE
replace_regex removes backslash in the regular expression

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3095]
**Describe the bug**

In  a regular expression, `\w` is used to findd a word character (i.e. equivalent to `[_0-9a-zA-Z]`).

If I use  it in the `replace_regex` operator, it is not taken into account (undertood by GAMA as a  w):
`write sample(replace_regex("MY_TEXT","\\w","a"));`  
the result is: `replace_regex('MY_TEXT','w','') -: 'MY_TEXT'`

Nevertheless, if I stored `\w` in a local variable and use this local variable in the replace_regex operator, it works perfectly:
``` 
string s <- "\\w";
write sample(replace_regex("MY_TEXT",s,"a"));
```
the result is: `replace_regex('MY_TEXT',s,'a') -: 'aaaaaaa'`

**Desktop (please complete the following information):**
 - OS: macOs Catalina
 - GAMA version: 1.8.1 release
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
I just committed a possible solution to this problem. Please test.

**Comment by benoitgaudou** [comment]
Great, it works. Thanks.
