### ISSUE TITLE
Problem loading the simulation against a backup file

### ISSUE THREAD

**Issue by grnsteven** [gama-platform/gama#3110]
Description of the problem:
I made a backup of my simulation. But when loading this backup, there is a outofmemory error. To solve this problem, I added memory to gama and used the compact_memory method.. But the mistake is still there.

Proposed solution:
Do you have a solution for this problem ?

**Comment by AlexisDrogoul** [comment]
I'm sorry but this issue is really poorly documented -- I close it for now, reopen it with a clear case study / example. 
Thx !
