### ISSUE TITLE
"New" shortcut has no effect

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#3114]
The shortcut assigned to "New" , command + option + N, has no effect. Perhaps because the shortcut does not know which specific item from the new menu it should open?

I propose:

1. (best option and most used by modelers) command+option+N is assigned specifically to File>New>New model or
2. command+option+N is assigned to a group of three (New Model, Experiment File, Test Experiment File) where a user can choose between them.... like it is currently with command+N

Thank you

======
OS MacOS catalina
GAMA:  Gama	1.8.1.202006230234

**Comment by benoitgaudou** [comment]
Work on my side
