### ISSUE TITLE
Default/Save path for workspace should be registered by instance of application

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3115]
Working with several instance of gama (even with different configuration and different versions), for now, GAMA always take only 1 default/saved path of workspace, so we must chose another one, or it can be corrupted by conflicting of some metadata between versions. It is not a big deal to chose different folder at each startup time, but sometime accidentally chose same workspace can cause a corruption, and it is hard to remember which gama used that workspace.
I think we can just change way to register the workspace in gama.ini instead of register it in "register" of OS :)

**Comment by AlexisDrogoul** [comment]
I'm not sure we can manipulate `gama.ini` so easily. And since the information related to one particular instance of GAMA is to be saved in its workspace, there is a problem of logic here: we cannot obviously save the workspace path in the workspace itself (or retrieve it that way !).

**Comment by AlexisDrogoul** [comment]
Hi, I come back to this. You can now specify if GAMA will use global preferences or "configuration" ones (ie one set per instance of GAMA) by passing the VM Argument `-Duse_global_preference_store=true` or `false`. `true` corresponds to the current default. If set to `false`, the preferences will be unique to this instance (incl., normally, the workspace location). Can you test and tell me if it solves your request ?

**Comment by hqnghi88** [comment]
I tried to set some new -D in gama.ini with 2 copy in folder 03, 06, one should point to workspace 202103 and other must point to 202106 (as in SS)
![image](https://user-images.githubusercontent.com/6105384/129446925-2d31b42e-fd73-410d-a4c1-b660b15ed796.png)
but unfortunately, after close these 2 instance, relaunch gama.exe in these 2 folder did not work as expected, both instance pointed to 202103 
![image](https://user-images.githubusercontent.com/6105384/129447002-bd8682ca-c0d0-4e72-a3ed-fc992d00a605.png)

**Comment by AlexisDrogoul** [comment]
Yeah. Right. I forgot that the workspace preferences were managed on their own. I've made a commit that should help on this matter, by reintegrating the workspace related preferences into the default preference store. Can you test ? Thanks !

**Comment by hqnghi88** [comment]
Thank you very much, it works like a charm
![image](https://user-images.githubusercontent.com/6105384/129488850-b2a55563-7539-4a0e-aac6-c1282ec5ae18.png)
