### ISSUE TITLE
Autosave facet at the experiment level 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3121]
**Is your request related to a problem? Please describe.**
We currently have the possibility to autosave a picture for a given display using the facet `autosave`. However more and more several displays are used in the same experiment (e.g with Comokit) 
<img width="1792" alt="Screenshot 2021-06-30 at 10 01 40" src="https://user-images.githubusercontent.com/3928502/123924387-369e7280-d98a-11eb-941f-b25c08de0d61.png">

**Describe the solution you'd like**
I was wondering if it would make sense (and if it's sounds doable)  to have an `autosave` facet at the `experiment` level

**Describe alternatives you've considered**
If not possible it's always possible to save every display one by one and reconstruct the full experiment by hand but this facte would save lots of time

**Additional context**

**Comment by sriramab** [comment]
I support this request. May be at the "new" layout level ?

**Comment by AlexisDrogoul** [comment]
`experiment` no of course, but probably at the `output` level. Or `layout`. But in that case, it would save all the views (incl. monitors, parameters, etc.) using a simple call to `Robot.createScreenCapture()`. Nothing more than the average screen capture you can take with your computer, only difference being that it is synchronised with the simulation cycles.

**Comment by agrignard** [comment]
@AlexisDrogoul yes this will be helpful and the output level and easier to produce videos/timelapses (e.g for the comokit example). Something not very possible with the default screen capture of the mac that is indeed not sync with the simulation.

**Comment by AlexisDrogoul** [comment]
I've pushed a simple implementation for this. The `autosave:` facet is added to `output` and accepts either a `bool` or a `string`(file name, which can be dynamic, i.e. evolve with the cycle, etc.).

**Comment by hqnghi88** [comment]
Tested! 
<img width="987" alt="image" src="https://user-images.githubusercontent.com/6105384/162014509-c1bb6820-2f4f-4590-959f-98a98dd198d5.png">
