### ISSUE TITLE
problème pour utiliser les données SIG

### ISSUE THREAD

**Issue by 20315022** [gama-platform/gama#3123]
### Steps to reproduce
1.

2.

2 occurrences in 2 agents at cycle 0: File denoted by ../includes/buildings.shp not found.
in file<int, geometry> buildings_shapefile <- file<int, geometry>('../includes/buildings.shp') ;
C:\Users\PASCO\Documents\IFI\gama\Projetepidemie\models\..\includes\buildings.shp
C:\Users\PASCO\Documents\IFI\gama\Projetepidemie\models\..\includes\buildings.shp
in initializing attribute buildings_shapefile
in agents Simulation 0, Bertoua20

**Comment by ptaillandier** [comment]
I don't think it's a GAMA bug. It's simply that you didn't specify the path to the file correctly.

For this type of question, you should rather use the google group (gama-platform@googlegroups.com) and share both your model and your data.
