### ISSUE TITLE
relevant expectations

### ISSUE THREAD

**Issue by 20315022** [gama-platform/gama#3124]
### Steps to reproduce
1.

2.

3.

Tell us what should happen (include all relevant expectations)
 at cycle 0: File denoted by ../includes/building.shp not found.
C:\Users\PASCO\Documents\IFI\gama\Projetepidemie\models\..\includes\building.shp
C:\Users\PASCO\Documents\IFI\gama\Projetepidemie\models\..\includes\building.shp
Impossible to obtain the value of Shapefile for the buildings:

**Comment by hqnghi88** [comment]
HI, As Patrick said in (may be) your previous issue:
"
I don't think it's a GAMA bug. It's simply that you didn't specify the path to the file correctly.

For this type of question, you should rather use the google group (gama-platform@googlegroups.com) and share both your model and your data. "
