### ISSUE TITLE
The method `implementsSkill()` does not work correctly with subspecies

### ISSUE THREAD

**Issue by minhduc0711** [gama-platform/gama#3126]
**Describe the bug**
The method `implementsSkill(some_skill)` returns `true` for a species which has `some_skill` attached, but returns `false` for a child species. 

**To Reproduce**
For example, we have this in GAML:
```
species people skills: [moving] {}

species pedestrian parent: people {}
```
Then in Java:
```
peopleAgent.getSpecies().implementsSkill("moving")  // returns true
pedestrianAgent.getSpecies().implementsSkill("moving")  // returns false
```

**Expected behavior**
`implementsSkill` should return `true` for `pedestrian` as well.

**Comment by minhduc0711** [comment]
It's still returning false for me after 9ebe8c9.

**Comment by AlexisDrogoul** [comment]
Well. In which context are you calling it and when ? Because this method can of course return false if you call it before the skills are inherited, for instance.

**Comment by minhduc0711** [comment]
Ah sorry, here's an example model for reproducing the issue
```
model repro

global {
	init {
		create pedestrian number: 1;
	}
}

species people skills:[moving] {
	reflex print {
		write speed;
	}
}

species pedestrian parent: people {}

experiment exp {}
```

Then if you set a breakpoint at https://github.com/gama-platform/gama/blob/b6fc25beb1f4f76e21cfd7a491e1d7ca2d10a8ab/msi.gama.core/src/msi/gaml/skills/MovingSkill.java#L159
you can evaluate `agent.getSpecies().implementsSkill("moving")` to see that it returns `false`.

**Comment by AlexisDrogoul** [comment]
Do we work on the same branch ? Because I cant catch any call to implementSkill()

**Comment by minhduc0711** [comment]
No, the expression does not exist there. You can use the expression view in Eclipse to quickly see the result of that expression.

**Comment by AlexisDrogoul** [comment]
Yep. I was tired when I wrote the fix :) new version committed soon.

**Comment by minhduc0711** [comment]
It is working well now, thank you :raised_hands:
