### ISSUE TITLE
GAMA 1.8.2: Fields cannot be saved because of a CRS problem

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3128]
**Describe the bug**
Using `save grid_file("xxxx.tif", my_field)` always returns an error of CRS, even though it seems to be correctly set. Some work needs to be done in GamaGridFile presumably !

**Comment by ptaillandier** [comment]
I push a fix.... not sure about the efficiency in terms of computation and memory, but at least it works.

**Comment by AlexisDrogoul** [comment]
Thanks. I tested it and it seems to work quite well.
