### ISSUE TITLE
Gama 1.8.2: Visual Question/issues related to dark mode on Mac OS

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3131]
**Describe the bug**
Sorry for this bug which is really related to the new Dark Mode form Mac and that I guess will imply some choice from the GAMA side.

on Mac Os Big Sur GAMA 1.8.2 behaves differently comparing with GAMA 1.8.1

With a Dark Mode on on Mac OS this is how GAMA 1.8.1 looks like 
<img width="1792" alt="Screenshot 2021-07-15 at 12 34 32" src="https://user-images.githubusercontent.com/3928502/125774609-ce4b6b5f-3712-4ba6-8a69-baee9d5b5be9.png">

And here is GAMA 1.8.2 with the same settings
<img width="1792" alt="Screenshot 2021-07-15 at 12 37 26" src="https://user-images.githubusercontent.com/3928502/125774781-2d7ca6c0-4b20-4f9a-be79-0e416fc6e3f4.png">

**Expected behavior**
I don't have the right answer and no real opinion on this. I was personally ok to have a white GAMA with a Dark Mode On on Mac but it might make sense to have a real dark mode Gama when Dark Mode on. So to try to summarize what I ve seen so far as potential problem and not to create one issue per item here is a short list

- If I am not wrong the font of the code is not the same regardless of the dark mode on/off. This might be a specific issue
- The current color schema of the text (which seems to be the same for Dark and Light))  makes the code really hard to read in Dark Mode.
- When in light mode ON the highlighting of the tabs seems to be inverted, the selected/Active tabs looks as if it was not active a s you can see here 
<img width="1506" alt="Screenshot 2021-07-15 at 12 51 09" src="https://user-images.githubusercontent.com/3928502/125776474-da085d27-b95a-4b9f-ad64-306db9970105.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Catalina]
 - GAMA version: [GAMA_1.8.2_Alpha_withJDK_Mac_07.05.21_86ad2069]

**Comment by AlexisDrogoul** [comment]
I'm working on some improvements to this right now. Please note that you have a preference to follow or not the theme of the OS.

**Comment by AlexisDrogoul** [comment]
Some enhancements have been made regarding the highlighting configurations, etc. I will open issues specifically dedicated to the "small" UI glitches found in macOS, windows and Linux.

**Comment by agrignard** [comment]
I briefly retested the dark mode which looks more or less ok for me (I didn't check all the feature though)

**Comment by AlexisDrogoul** [comment]
Let's close this "too broad" issue in favor of more specific ones (like #3193).
