### ISSUE TITLE
Gama 1.8.2: Accessing Fields model Java error 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3132]
**Describe the bug**
Run Modelling/Spatial Topology/Fields/Accessing Fields.gaml

**To Reproduce**
1. Run it

I get an out of bounds error

**Expected behavior**
Run

**Screenshots**
<img width="1791" alt="Screenshot 2021-07-15 at 14 28 19" src="https://user-images.githubusercontent.com/3928502/125788326-f52ca750-16e8-497b-8cf3-f8686375d4be.png">

**Desktop (please complete the following information):**
 - OS: [emacOS Catalina]
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: [Gama 1.8.2 alpha]

**Additional context**

**Comment by AlexisDrogoul** [comment]
Fixed. The torus property of the environment was not taken into account.
