### ISSUE TITLE
Gama 1.8.2: Dem Generator model

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3133]
In  link with a post by @AlexisDrogoul on FB, this DEM Generator look really really impressive and I am pretty impatient and curious to see it running!

Is it plan to push it in the 1.8.2? It doesn't seems to be here in the alpha version neither the current git version either?

it might be great if the model is not too heavy (I would assume it's only pure code) to have it in the library and according to the screenshot it seems to be ready to be pushed in the Visualisation Model library ;-)

<img width="1430" alt="Screenshot 2021-07-15 at 15 38 12" src="https://user-images.githubusercontent.com/3928502/125797644-d08f21a9-7cc1-450d-963f-85cfae9f076d.png">

**Comment by AlexisDrogoul** [comment]
It's already here : https://github.com/gama-platform/gama/blob/GAMA_1.8.2/msi.gama.models/models/Visualization%20and%20User%20Interaction/Visualization/DEM%20Generator.gaml . You might need to refresh your workspace to make it appear.

**Comment by agrignard** [comment]
Ok it's here in the very last new release (not sure it was in the previous one but anyway)

**Comment by agrignard** [comment]
On this model I just notice a small issue related to the triangulation inti

The first time you run it the rendering is ok (even though you see very briefly the triangulation) and it looks like this
<img width="1248" alt="Screenshot 2021-07-16 at 11 24 10" src="https://user-images.githubusercontent.com/3928502/125925523-dca02746-297f-4f44-be94-ef944610e539.png">
 Reload/Relaunch it this is how it looks for me (I see the triangulation) as soon as I update a prameter the triangualtion disapear
<img width="1251" alt="Screenshot 2021-07-16 at 11 24 20" src="https://user-images.githubusercontent.com/3928502/125925701-aa760a3a-c96e-41ac-848e-0b244e2f6099.png">
