### ISSUE TITLE
Linux visual glitches in GAMA 1.8.2

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#3137]
Similar as #3136 but focus on Linux systems, this issue is here to collect multiple glitches and bugs in the display on Linux display.

- [x] #3183
![Peek 2021-07-16 15-04](https://user-images.githubusercontent.com/16764085/125914434-3b977818-6c01-44b0-ac07-a311074bc96c.gif)

- [x] #3189
![Peek 2021-09-10 10-42](https://user-images.githubusercontent.com/16764085/132796191-ef4a04d6-4f52-4872-a7cf-0f4dc9fb3cc2.gif)

---

From @ndgnuh [comment](https://github.com/gama-platform/gama/issues/3137#issuecomment-881300323)

- [x] Terrible dark theme, always have to export GTK_THEME=Adwaita before launching Gama

- [x] Dark text on dark background
(My theme based on numix and color scheme of Firefox)
![image](https://user-images.githubusercontent.com/33273948/125923139-0ceab2e5-623d-46db-8df2-8d3468e3255b.png)
![image](https://user-images.githubusercontent.com/33273948/125922764-7b8bfd38-ccc0-4b5a-b40d-dc05c01486ca.png)
(Adwaita dark)
![image](https://user-images.githubusercontent.com/33273948/125923513-6c81cf1f-1932-424d-afe6-4cc4e983c070.png)
![image](https://user-images.githubusercontent.com/33273948/125923705-a09c7a10-4ad6-4047-81e1-ed1492219f79.png)

- [x] Elements overlapping
![image](https://user-images.githubusercontent.com/33273948/125923018-cf5c976f-9fac-4067-b588-b4ff7c2cc88c.png)
> Fixed ![image](https://user-images.githubusercontent.com/16764085/132795184-75e47c15-33ca-45d2-9f3e-c89b6f0a7b1d.png)

- [x] These text inputs are made for 9pt fonts?
![image](https://user-images.githubusercontent.com/33273948/125923254-697a24c6-ff0e-4b08-b1bb-3963e7530b12.png)

- [x] You probably couldn't see it but the cursor is before the prompt
![image](https://user-images.githubusercontent.com/33273948/125924023-7aeea1de-6b2d-48dc-8405-68c772e0d346.png)
> Considered as fixed
> Yes you can have your cursor anywhere in the prompt console, but it's going at the right place (end of last line) everytime you type a character
> ![Peek 2021-09-10 10-35](https://user-images.githubusercontent.com/16764085/132795504-6d75b6ba-10ca-4734-8a32-180e1716ec71.gif)

---

Please add comments or edit this issue to add your findings (there are probably tons of them) so that we can progressively phase them out and have a better user experience on Linux systems.

**Comment by minhduc0711** [comment]
At least the box appears shortly for me, but it is in the middle of the screen.

![test](https://user-images.githubusercontent.com/34294427/125916745-6ace2e66-df78-4c19-980f-4abdd2befcdd.gif)

**Comment by ndgnuh** [comment]
- Terrible dark theme, always have to export GTK_THEME=Adwaita before launching Gama
- Dark text on dark background
(My theme based on numix and color scheme of Firefox)
![image](https://user-images.githubusercontent.com/33273948/125923139-0ceab2e5-623d-46db-8df2-8d3468e3255b.png)
![image](https://user-images.githubusercontent.com/33273948/125922764-7b8bfd38-ccc0-4b5a-b40d-dc05c01486ca.png)
(Adwaita dark)
![image](https://user-images.githubusercontent.com/33273948/125923513-6c81cf1f-1932-424d-afe6-4cc4e983c070.png)
![image](https://user-images.githubusercontent.com/33273948/125923705-a09c7a10-4ad6-4047-81e1-ed1492219f79.png)

- Elements overlapping
![image](https://user-images.githubusercontent.com/33273948/125923018-cf5c976f-9fac-4067-b588-b4ff7c2cc88c.png)
- These text inputs are made for 9pt fonts?
![image](https://user-images.githubusercontent.com/33273948/125923254-697a24c6-ff0e-4b08-b1bb-3963e7530b12.png)
- You probably couldn't see it but the cursor is before the prompt
![image](https://user-images.githubusercontent.com/33273948/125924023-7aeea1de-6b2d-48dc-8405-68c772e0d346.png)

**Comment by minhduc0711** [comment]
The cursor in the text editor also disappears rather randomly.

**Comment by ndgnuh** [comment]
> The cursor in the text editor also disappears rather randomly.

That is an SWT bug, somehow Java doesn't play well with GTK

**Comment by AlexisDrogoul** [comment]
@RoiArthurB @minhduc0711 The dropdown works for me without problems under Ubuntu 20. 


![screencast 2021-09-09 19-17-21](https://user-images.githubusercontent.com/579256/132684376-470f2fa6-b2a4-40b9-886f-a28d13aae3af.gif)

**Comment by minhduc0711** [comment]
Probably because we both use a different window manager (I believe Arthur uses i3, and I use sway) instead of Mutter on Ubuntu.

But somehow the popups when hovering over the run/reload buttons seem to work fine. Are these popups and the clock popup implemented in the same way?

**Comment by RoiArthurB** [comment]
@AlexisDrogoul this issue is fixed. 

However, as @minhduc0711 said, because of our _weird_ windows manager (tiling ones) it's not acting as wanted. The problem comes from this : 

Normal behavior : 
- GAMA is active window
- Hover Experiment input 
- create a small pop-up (new window) with extra info

Tiling behavior :
- GAMA is active window
- Hover Experiment input 
- create a small pop-up (new window) 
  - Tiling switch the pop-up as the active window
- GAMA is not the active window anymore
- GAMA destroy the pop-up
- [repeat] ⇒ Display quick pop-up flashing

I don't think it's necessary to try to fix that "bug" (I think we're the 2 last guys using tiling windows), but I wanted to leave the explanation of why it's happening :)

**Comment by RoiArthurB** [comment]
@ndgnuh Is the black background fixed (your second point)? 

The work on Dark theme ( #2994 ) and the new Eclipse base (dark mode friendly) on GAMA 1.8.2 should make everything fine now :) (here's me on Match Dark) 
![image](https://user-images.githubusercontent.com/16764085/132794858-a12ae2ce-ddc2-4c8c-88dc-44545037426f.png)

**Comment by AlexisDrogoul** [comment]
All of these points are considered as fixed, at least for the most usual WM on Linux. Impossible to test / fix for all the exotic ones, sorry guys...
