### ISSUE TITLE
Problem with operators on predicates in BDI (BEN)

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3140]
**Bug 1: the (add-values) to predicates in BDI**
When we add values to predicates and try to recall them, it sends an error
Reproduce the bug:
```
species bug control:simple_bdi {
	predicate info <- new_predicate('info', ['a'::1]);
	init {
		do add_belief(info);
		info <- info add_values ['b'::2];
		write info.values['b'];
	}
}
```
It gives an error while it should give (2)

**Bug 2: truth value of predicates in BDI**
When we change the truth value of a predicate to false, it ruins the values map of the predicate and throws an error when trying to recall it
Reproduce (use the same predicate info in the bug 1)

-Patrick: I put the bug concerning FIPA in a new issue -

**Comment by ptaillandier** [comment]
@Aya-Badawy89 : it is normally fixed, you can test it (with the new alpha release).
