### ISSUE TITLE
Problem with FIPA skill

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#3141]
Bug reported by "Aya-Badawy89"

```
species bug skills:[fipa]  {
	
	reflex reply when:!empty(mailbox){
		write 'message received';
	}
}
species bug2 skills: [fipa] {
	init {
		do start_conversation to:[bug[0]] performative:'propose' protocol:'no-protocol' contents:['hello'];
	}
}
```
Agent bug2 should write message received but this does not happen. If we replace mailbox with proposes, it works.

**Comment by AlexisDrogoul** [comment]
I"ve pushed a possible fix. Problem comes that we have two similar notions: `messages` (which comes from the FIPA protocol), but also `mailbox`, inherited from the "messaging" skill. I've redefined `mailbox` so that it basically does the same as `messages`. Please test !

**Comment by Aya-Badawy89** [comment]
I tested now the same code (which I wrote in the issue) again, but still it does not work unfortunately

**Comment by AlexisDrogoul** [comment]
And if you use `messages` instead ?

**Comment by Aya-Badawy89** [comment]
It gives a syntatic error when I write messages

**Comment by Aya-Badawy89** [comment]
I downloaded the lastest 1.8.2 version released from 6 days, and I found it working now 👍 with (mailbox)

**Comment by AlexisDrogoul** [comment]
Yes, sorry. Actually `messages` did not exist anymore and had been replaced by `mailbox` -- but the Java code had still some traces of it. It's fixed now.
