### ISSUE TITLE
GAMA git on macOS doesn't working anymore

### ISSUE THREAD

**Issue by jferdelyi** [gama-platform/gama#3142]
**Describe the bug**
After git pull commits (until Mon Jul 19 18:53:09 2021 +0700) GAMA doesn't work. The window is empty and there is an huge stack on eclipse console.

**To Reproduce**
Git pull the last commits on MBP 13" 2020 until Mon Jul 19 18:53:09 2021 +0700, compile and execute. 

**Screenshots**
<img width="1037" alt="Capture d’écran 2021-07-20 à 14 53 58" src="https://user-images.githubusercontent.com/4105962/126328369-34ccdc1f-ab12-4452-b14a-a759fff9b3ee.png">
<img width="1552" alt="Capture d’écran 2021-07-20 à 14 53 36" src="https://user-images.githubusercontent.com/4105962/126328379-a4c36406-9e46-4db2-937b-9d2e54fb3a87.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sure
 - PC Model: MBP 13", 2020,
 - GAMA version: git (1.8.2)
 - Java version: 15
 - Graphics cards / Display system: Intel Iris Plus Graphics 1536 Mo

**Comment by jferdelyi** [comment]
Everything is working with Eclipse 2021-06 (4.20.0)

**Comment by AlexisDrogoul** [comment]
Sorry for the inconvenience. It was however indicated on https://github.com/gama-platform/gama/blob/GAMA_1.8.2/README.md and discussed in the Slack gama group.

**Comment by jferdelyi** [comment]
OK thanks
