### ISSUE TITLE
GAMA macOS crash in OpenGL experiment

### ISSUE THREAD

**Issue by jferdelyi** [gama-platform/gama#3143]
**Describe the bug**
When I try to run an experiment with an opengl display on my MBP, GAMA crashes. It works with java2D.

**To Reproduce**
1. Pull the last commit: gama and experimental 
2. Launch GAMA
3. Launch opengl experiment
4. See errors

**Screenshots**
<img width="1063" alt="Capture d’écran 2021-07-21 à 09 52 43" src="https://user-images.githubusercontent.com/4105962/126452201-e1a3c1e5-a9d9-479b-bc23-be136aa63433.png">

**Desktop**
 - OS: macOS Big Sur
 - PC Model: MBP 13" 2020
 - GAMA version: git (1.8.2 branch)
 - Java version: 15
 - Graphics cards / Display system: Intel Iris Plus Graphics 1536 Mo
 - Eclipse version: 2021-06 (4.20.0)

**Additional context**
The full repport: [error_stack.txt](https://github.com/gama-platform/gama/files/6853744/error_stack.txt)

**Comment by AlexisDrogoul** [comment]
Have you tried with a different VM ? I see you're using OpenJDK.

**Comment by jferdelyi** [comment]
I have switched to JDK and it's working, thanks
