### ISSUE TITLE
Picking Broken in OpenGL

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3146]
**Describe the bug**
I phope it's not something ot difficult to fix but I just notice on some cases that the picking (right click to inspect an agent) is kind of buggy. It can be easily reproduce on the calssic famous GIS

**To Reproduce**
Run Tutorials/Road Traffic/Model 01.gaml
Try to select any agent

Here are 2 exemple that shoes with a drawn crossed the picked elements:
- first case one where I click on a building I cannot inspect it 
- Second case where I click on a building and it choose another one

It sounds like an offset are something like this that doesn't return the right mouse position.

**Expected behavior**
Classic picking

**Screenshots**
<img width="589" alt="Screenshot 2021-07-22 at 13 03 39" src="https://user-images.githubusercontent.com/3928502/126629779-622fb4f4-68cf-43ec-aeb0-3c15d409f52f.png">
<img width="694" alt="Screenshot 2021-07-22 at 13 04 36" src="https://user-images.githubusercontent.com/3928502/126629786-ce4fd169-2cb1-4b3a-b6e3-7332d7d748a7.png">

**Desktop (please complete the following information):**
 - OS: MAC OS Catalina
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: 1.8.2

**Comment by AlexisDrogoul** [comment]
Is it a retina screen you're using (i.e. a MBP) ? Because I think the entire clicking / selecting / coordinates reporting is broken under HiDPI screens. And it is a bit tedious to fix because in some cases you have to scale up the coordinates and in other cases to scale them down (some components pre-calculate the scaling, some, like JOGL canvases, don't).

**Comment by agrignard** [comment]
Yes sorry I didn't specify it in the issue I am using a retina  with default parameter 

The problem is it represents something like 90% (not to say more) of the Mac now ? Doesn't sound like a good news for Mac User

**Comment by AlexisDrogoul** [comment]
Nope and the same for PC users with HiDPI screens (actually probably more numerous than Mac users). Maybe asking JOGL politely to take HiDPI screens into account will work ? 🤣

**Comment by agrignard** [comment]
But how did you make it work with 1.8.1?

**Comment by AlexisDrogoul** [comment]
"But how did you make it work with 1.8.1?": well. Different JDK version, different SWT version, different JOGL version. Need I say more ? Fixing this is not complicated, it is just long, tedious and boring. Basically, it involves calling the right methods on `PlatformHelper` (`autoScaleUp`, `autoScaleDown`, etc.) when you deal with MouseTrackEvents / MouseEvents and screen / view coordinates (most of them being in `AbstractCamera`, `KeystoneHelper` and `SWTOpenGLDisplaySurface`). It can take 10 minutes if you are lucky or much more if you are not and want to test all configurations.

**Comment by agrignard** [comment]
Ok seems better now. I would be ok to close it for now. @ptaillandier you were also mentionning some issue here?

**Comment by ptaillandier** [comment]
It works better for me.

**Comment by agrignard** [comment]
Actually I notice now new issues... I guess it's potenially due to the usage of mesh (I will try to write an atomic model)

**Comment by agrignard** [comment]
Seems to work now except for this specific use case https://github.com/gama-platform/gama/issues/3190 so let's close this one for now.
