### ISSUE TITLE
Display disappear when switching between modelling and simulation  perspective 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3147]
**Describe the bug**

**To Reproduce**
Open any Opengl model display
Run it
Go to modelling perspective
Go back to simulation, perspective, everything is gone
Press play it's back 

**Screenshots**
![Untitled mov](https://user-images.githubusercontent.com/3928502/126641708-39a2c0ab-b88d-4c2e-9737-46f3b0bbb612.gif)

**Desktop (please complete the following information):**
 - OS: MAC OS 
 - GAMA version: Alpha Version 1.8.2 (1dfe2b6c)

**Additional context**

**Comment by AlexisDrogoul** [comment]
Which JDK are you using ?

**Comment by agrignard** [comment]
I am using this release GAMA_1.8.2_Alpha_withJDK_Mac_07.21.21_1dfe2b6c

**Comment by agrignard** [comment]
Enable to reproduce it so far

**Comment by agrignard** [comment]
Still happening (for instance with Tutorials/Road Traffic/models/Model 03.gaml)

Mac OS catalina 
GAMA_1.8.2_Alpha_withJDK_Mac_08.31.21_989e5a4e

**Comment by agrignard** [comment]
Cannot reproduce it on the last version 
GAMA_1.8.2_Alpha_withJDK_Mac_09.10.21_f9f09e1b

**Comment by AlexisDrogoul** [comment]
Let's close it for the moment. Reopen if it manifests again.
