### ISSUE TITLE
Add spatial queries (to have all the couples *s and *ing)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3153]
The first spatial query that new developers use is often `overlap`, and they are happy to use `overlapping` to get all the agents overlapping a  given agent.
But later when they want to use `intersection`, `cover` ... they are surprised to not have a `covering` or an `intersecting` operator and that hey have to combine a `where` and `covers`.

Could we have a uniform approach and  have the couple `*s` and `*ing` for all the spatial queries:
- `overlaping` and  `overlaps`
- `covering` and `covers`
- `intersecting` and `intersects`
- `partially_overlaping` and `partially_overlaps`
- `touching` and  `touches`
- `crossing` and `crosses`

**Comment by ptaillandier** [comment]
I added new spatial queries operator. It is illustrated through a new example model (Spatial queries in Modeling/Spatial Topology/Spatial Operators). Could you test it and close the issue if it is ok?

**Comment by benoitgaudou** [comment]
Thanks @ptaillandier for thee implementation.
I tried the model (with  the  last updated version of GAMA  Git...), and the model seems  to have an  issue: 

```
			match "overlapping" {
				agents_concerned <- (polyline_agent) overlapping selected_agent;
			}
```
seems to work correctly (meaning the polyline_agent appears red when they  overlap the selectec_agent. 

But that one does not:
````
			match "overlapping" {
				agents_concerned <- (polygon_agent + polyline_agent + point_agent) overlapping selected_agent;
			}
```
In this case `agents_concerned` is always an  empty  list (and  thus no agent appears in red).

**Comment by ptaillandier** [comment]
@AlexisDrogoul it is due to the fact that in CompoundSpatialIndex, filter.getPopulation(scope) (line 219) returns a empty list - indeed, (polygon_agent + polyline_agent + point_agent) is a list of agents of different species, but all that species have the same parent species "agent_base". Thus, filter.getPopulation(scope) tries to return all the agents of type "agent_base" instead of returning all the agents of the list. As I think, you worked recently on this point, I prefer to let you fix this issue (easy to fix, but difficult to know the impact).

**Comment by AlexisDrogoul** [comment]
Yeah. Right. The semantics of these filters is not really clear. Should we answer `null` then for the population ? That would be the most logical.

**Comment by ptaillandier** [comment]
It is ok for me if it doesn't break anything else.

**Comment by AlexisDrogoul** [comment]
The addition of populations was actually not correctly returning a MetaPopulation (but a list). I have corrected the operator and transformed the model into an interactive one. Can you test ?

**Comment by benoitgaudou** [comment]
Thanks, this works well now.

Another issue with one of the operator: `covering`.
The following screenshot seems  to indicate that the covering does not work properly, as the circle seems to be covered by the square, but is not displayed in red ...

<img width="1153" alt="Screenshot 2021-08-19 at 18 32 59" src="https://user-images.githubusercontent.com/1555274/130107950-a58ca257-9213-43a9-bbfa-f69f9a5dfda4.png">
