### ISSUE TITLE
[batch] make exploration use all the threads instead of a sequential ordering

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#316]
**Is your request related to a problem? Please describe.**
Currently it is not possible to run a batch exploration on multiple threads. We can run the same set of parameters in parallel, but in case of a deterministic simulation this doesn't make sense and we would benefit greatly from using the available cores to run other sets of parameters instead.
I think taking better advantage of the available cores of the machine in general is a key point in rebuilding an efficient batch "engine".

**Describe the improvement you'd like**
When running a batch exploration with parallel set to a number>1 and repeat=1 (actually should work with repeat < parallel in general but I understand this would imply greater deeper changes), the engine should be able to use one core per parameter set of the exploration.

**Comment by AlexisDrogoul** [comment]
Isnt'it precisely the point of this preference ? 

```
	public static final Pref<Boolean> CONCURRENCY_SIMULATIONS_ALL = create("pref_parallel_simulations_all",
			"In batch, allows to run simulations with all available processors"
					+ "[WARNING: disables reflexes and permanent displays of batch experiments]",
			false, IType.BOOL, true).in(GamaPreferences.Runtime.NAME, GamaPreferences.Runtime.CONCURRENCY);

```

 or maybe it does not work ?

**Comment by lesquoyb** [comment]
No you're right I just forgot about this parameter (again)
