### ISSUE TITLE
Heatmap transparency impacting on Overlay layer transparency 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3161]
**Describe the bug**
When, using an heatmap layer with a transparency, it seems that the transparency also impact on the overlay

**To Reproduce**
Run this 
````
/**
* Name: Heatmap
* A model that demonstrates how to build a simple heatmap based on fields and how to display it WITHOUT CHANGING A LINE OF THE ORIGINAL MODEL IMPORTED. 
* This heatmap records the number of people passed in each area of the city.
* Author: Alexis Drogoul
* Tags: 
*/
model BuildingHeatmap

import "3D Visualization/models/Building Elevation.gaml"

global {
	int size <- 300;
	field heatmap <- field(size, size);

	reflex update {
		ask people {
			loop i from: -(size/100) to: size/100 step: 2 {
				loop j from:  -(size/100) to: size/100 step: 2 {
					heatmap[location + {i, j}] <- heatmap[location + {i, j}] + 5 / (abs(i) + 1);
				}
			}
		}
	}
}

experiment "Show heatmap" type: gui {
	output {
		layout #split;
		display HeatmapPalette type: opengl draw_env: false background: #black {
		  
		mesh heatmap scale: 0 color: palette([ #black, #cyan, #yellow, #yellow, #red, #red, #red]) transparency: 0.75 position: {0, 0, 0.001} smooth: 4 ;
		          overlay position: { 5, 5 } size: { 180 #px, 100 #px } background: # black  border: #black rounded: true
            {
            	//for each possible type, we draw a square with the corresponding color and we write the name of the type
                draw "TRANSPARENCY TEST" at: { 500#px,500#px } color: # white font: font("Helvetica", 32, #bold);
                
            }
		}
		display HeatmapGradient type: opengl draw_env: false background: #black {
			species building refresh: false {
				draw shape border: #white wireframe: true width: 3;
			}

			species road refresh: false {
				draw shape color: #white width: 3;
			}

			species people {
				draw circle(1) color: #white at: {location.x, location.y};
			}
			//palette([#black, #darkorange, #orange, #orangered, #red])
			// The resulting field is displayed a little bit above the other layers, with no 3D rendering, and a smoothness of 3 (meaning three passes of box blur are being done to "spread" the values)
			mesh heatmap scale: 0 color: gradient([#black::0.1, #orange:: 0.5, #red::1]) transparency: 0.2 position: {0, 0, 0.001} smooth:4 ;
		}
		

	}

}
````
**Expected behavior**
I would except that the transparency of the heatmap layer does not affect the overlay one. Like when you put a transparency to a species layer it doesn't not impact the overlay

**Screenshots**
<img width="576" alt="Screenshot 2021-08-04 at 10 49 58" src="https://user-images.githubusercontent.com/3928502/128151818-dfcae3d1-94f2-47a8-bf64-5603e638077c.png">

**Desktop (please complete the following information):**
Mac OS - GAMA 1.8.2

**Comment by agrignard** [comment]
Great! Sounds good now. I close this issue

**Comment by agrignard** [comment]
I guess this is somehow related to this issue.

It seems that the mesh layer is always drawn on top of the species layer even if it's declare before in the display.

e.g if I want to see my building on top of a heatmap mesh on top of this, I have to set a transparency.

However I would have assume that if I draw first my heatmap then I can can surimpose the building writing something like this
`````
mesh heatmap position: {0, 0, -0.01} scale: 0.0 color: palette([ #white, #cyan, #yellow, #yellow, #red, #red, #red]) smooth: 4 triangulation:true;
species building aspect: base refresh:false transparency:0.5 position: {0, 0, -0.015};			
`````

However with this syntax I get this
<img width="917" alt="Screenshot 2021-09-01 at 11 21 06" src="https://user-images.githubusercontent.com/3928502/131646657-7e7bad1f-12cd-4a45-8a99-f3bbde715f23.png">

But I would assume to have this (to be able to see the building). 
<img width="936" alt="Screenshot 2021-09-01 at 11 21 45" src="https://user-images.githubusercontent.com/3928502/131646701-dda99590-e904-4961-8a2b-c8502b2d58a8.png">

**Comment by AlexisDrogoul** [comment]
Why do you specify the z-position of the layers ?

**Comment by agrignard** [comment]
Sorry  it was not an issue indeed
