### ISSUE TITLE
`compareTo` method of `AbstractAgent` only compares indices

### ISSUE THREAD

**Issue by minhduc0711** [gama-platform/gama#3162]
**Is your request related to a problem? Please describe.**
I was trying to construct a `TreeMap<IAgent, Double>` but I observed weird behaviors. After a while, I finally realized that there were some "equal" agents that are actually different. 
I believe these are the relevant lines: https://github.com/gama-platform/gama/blob/7978fd8a369e4b3bd986ed753c32f3657c72137f/msi.gama.core/src/msi/gama/metamodel/agent/AbstractAgent.java#L241-L244
i.e. if I have two species `dog` and `cat`, then `compareTo` would return `0` for `dog5` and `cat5`.

**Describe the solution you'd like**
Can we compare something more unique to agents? Maybe this could work:
```
@Override
public int compareTo(final IAgent o) {
	  String thisName = getSpeciesName() + getIndex();
	  String otherName = o.getSpeciesName() + o.getIndex();
	  return thisName.compareTo(otherName);
}
```

cc @AlexisDrogoul

**Comment by AlexisDrogoul** [comment]
This method is used to order agents from the same species (like compareTo() in Java). It doesn't make sense to compare agents from two different species. 
If you want to do such a thing then create your SortedMap with a custom Comparator that implements your own logic.
