### ISSUE TITLE
Simulation freezes when `synchronized: true` is set in a Java2D display

### ISSUE THREAD

**Issue by minhduc0711** [gama-platform/gama#3166]
**Describe the bug**
With `FLAGS.USE_OLD_SYNC_STRATEGY = false`, a GUI experiment immediately freezes at cycle 1 if the facet `synchronized: true` is set in a Java2D display. No error or exception is printed in the console log.

**To Reproduce**
1. Open `Plugin models/Driving Skill/models/Drive Random.gaml`
2. Run the experiment

**Desktop (please complete the following information):**
 - OS: Linux 5.13.9-arch1-1 x86_64 GNU/Linux
 - PC Model: Acer Aspire A5
 - GAMA version: git
 - Java version: AdoptOpenJDK 15.0.2
 - Graphics cards / Display system: Intel UHD Graphics 620 / XWayland

**Additional context**
Does not happen when `FLAGS.USE_OLD_SYNC_STRATEGY = true`.

**Comment by AlexisDrogoul** [comment]
Can anyone try on Windows ? It seems to work on macOS.

**Comment by hqnghi88** [comment]
It freeze the simulation not whole gama, we can relaunch and it will stuck as soon as we sync the display (sync button clicked), AND it seems the threads are still alive, i tried 4 times and there are 4 thread in stock.
![image](https://user-images.githubusercontent.com/6105384/129329807-af2c60fd-1fc5-4503-8a63-2640db2bc54c.png)

**Comment by AlexisDrogoul** [comment]
OK. Thanks ! I will try to solve this. In the meantime, the workaround is of course to use the "old" sync strategy...

**Comment by minhduc0711** [comment]
It's fixed for me now :+1:

**Comment by hqnghi88** [comment]
Fixed on win.
Cheers.

**Comment by AlexisDrogoul** [comment]
Cool ! Thanks.
