### ISSUE TITLE
Cannot start Gama using git install

### ISSUE THREAD

**Issue by LSADOU** [gama-platform/gama#3167]
**Describe the bug**
Unable to launch GAMA application from eclipse using sources from GAMA_1.8.2 git branch. Seems that loading stops right after the plugins load.

<img width="1440" alt="Capture d’écran 2021-08-18 à 16 26 04" src="https://user-images.githubusercontent.com/63230249/129916475-6d5a083a-e2d0-4469-9315-19fccbcd67a2.png">

During building the projects I got this error that, maybe, lead to my problem:

<img width="1085" alt="Capture d’écran 2021-08-18 à 16 29 18" src="https://user-images.githubusercontent.com/63230249/129916859-f98168c8-eae4-425d-8984-2da34eb4561b.png">

I tried using both eclipse 2021-03 and eclipse 2021-06 with both jdk 11.0.12 and jdk 15.0.1 but nothing changed.

**Desktop** 

    OS: macOS Big Sur 11.4
    PC Model: Macbook pro M1 2020
    GAMA version: git branch "GAMA_1.8.2"

**Comment by AlexisDrogoul** [comment]
If you already have a workspace, can you try to rename it (temporarily) so that GAMA doesn't try to open it ? And what is this `databases` problem you have ? Is it a project of yours ?

**Comment by LSADOU** [comment]
There is nothing in my workspace, all those projects are imported from a git repository.
I don't have any project in this workspace, i thought `databases` was a piece of a GAMA project.

**Comment by AlexisDrogoul** [comment]
I'm talking about the workspace used by GAMA, not the one used by eclipse. Have you already run GAMA ? Do you still have a workspace in which your models were located ? If yes, then try to rename it manually and relaunch GAMA. 

Regarding `databases`, I don't know what it is and why you have this in your Eclipse workspace.

**Comment by LSADOU** [comment]
So I tried to rename my GAMA workspace where I have some models and nothing changed too, the launch still freezing right after loading the plugins. This is a fresh install of GAMA, so I am assuming that a GAMA workspace path isn't even configured yet.
Strange fact: each time I clean/build the GAMA projects this error is duplicating.
<img width="1075" alt="Capture d’écran 2021-08-19 à 09 08 17" src="https://user-images.githubusercontent.com/63230249/130023954-ed8071ec-364d-4d06-9a01-79c3df77a865.png">

Moreover I found a directory named "Databases" in a GAMA project:
<img width="342" alt="Capture d’écran 2021-08-19 à 09 15 50" src="https://user-images.githubusercontent.com/63230249/130025009-3ed9ac9e-45cd-4201-9cc3-02ba669aae2c.png">
Maybe there is a link between the error and this directory ?

**Comment by minhduc0711** [comment]
You have to uncheck this box when importing projects into Eclipse, it's probably why you have this error
![image](https://user-images.githubusercontent.com/34294427/130027573-c6601a4d-8bba-41c0-b6b7-7409ed5d844e.png)
But I think this error does not cause to GAMA to freeze.

**Comment by hqnghi88** [comment]
![image](https://user-images.githubusercontent.com/6105384/130047262-0e238bfa-f7ec-4868-b0e6-436feae10c1e.png)
Can you show this ErrorLog view?

**Comment by ptaillandier** [comment]
I checked with him and cleaned his workspace. He now has no more errors,
but GAMA still freezes at the start. We tested with the last release and it
is working fine. So no idea of the problem.

Le jeu. 19 août 2021 à 16:46, HUYNH Quang-Nghi ***@***.***> a
écrit :

**Comment by AlexisDrogoul** [comment]
Another option is to run GAMA in debug mode to see what happens.

**Comment by LSADOU** [comment]
Just tried "Launch an Eclipse application in Debug mode" and got the same result. Is there a log file as output for this debug mode ?

**Comment by AlexisDrogoul** [comment]
Are there stuck processes ? You  can access this by looking at the different threads in the Debug perspective ("pause" them to see what they are doing)

**Comment by LSADOU** [comment]
I paused the threads and this is what I got:
<img width="444" alt="Capture d’écran 2021-08-19 à 14 39 21" src="https://user-images.githubusercontent.com/63230249/130070007-92d448e1-38dc-48f7-913c-8e52f71bc2a9.png">
<img width="432" alt="Capture d’écran 2021-08-19 à 14 39 36" src="https://user-images.githubusercontent.com/63230249/130070022-7378f52c-ba66-4b6a-86fc-c31e96d24a48.png">

**Comment by AlexisDrogoul** [comment]
OK. It clearly indicates (first line) that it is waiting for you to pick a workspace using the dialog...! Do you, by any chance, run Eclipse fullscreen ? If yes, try to run it in a normal (floating) window, and run GAMA again. The dialog should appear. Otherwise, you need to go back and forth using command-tab. It seems that model dialogs at launch have a hard time displaying correctly when launched from Eclipse in fullscreen mode.

**Comment by LSADOU** [comment]
It worked !
Lot of thanks, that was tricky !

**Comment by AlexisDrogoul** [comment]
Good to know. That's exactly the kind of thing we need to put in the FAQ (https://github.com/gama-platform/gama/wiki/FAQ)
