### ISSUE TITLE
layout #split with a mix of  Java2d and OpenGL displays makes

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3168]
**Describe the bug**
Basically when  I had  `layout #split` in an experiment with a mix of Java2D and OpenGL displays (e.g. model6 of Luneray Tutorial), when I launch the experiment, the displays are created correctly, but at the time of splitting them, GAMA  crashes with the following mesage in the Eclipse console.

I tried on another model (3 displays and no monitor). Again displays are well created, but when comes the time to split them, the parameter view disappears.
Note, that when I want to resize the GAMA windows, it is in fact the environment displaying the agents that are resized.
And click on the red cross to stop simulation does not do anything.

```
--------------------------------------------------------------------------------
---------- RESHAPING TO 321X359 ------------------------------------------------
--------------------------------------------------------------------------------
Camera zoom level                  1.0
Size of env in units               3657.758092411532 | 2697.7657217532396
Ratio width/height in units        1.3558471971518737
Initial Size of env in pixels      586.3969116210938 | 554.7424926757812
Size of env in pixels              851.7938232421875 | 750.4849853515625
Ratio width/height in pixels       1.1349911588746404
Window pixels/env pixels           0.37685175830246803 | 0.4783573382641726
Current XRatio pixels/env in units 0.2328731976587895 | 0.2781876051356428
Device Zoom =  200
AutoScale down =  161 180
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fff23016d28, pid=11425, tid=259
#
# JRE version: Java(TM) SE Runtime Environment (15.0.2+7) (build 15.0.2+7-27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (15.0.2+7-27, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [AppKit+0x3ead28]  -[NSApplication _crashOnException:]+0x15b
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Applications/eclipse-dsl-2021-062/Eclipse.app/Contents/MacOS/hs_err_pid11425.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
# 
```

**To Reproduce**
1. Add `layout  #split` in  the model6.gaml of Luneray Tutorial
2. Launch the simulation

**Desktop (please complete the following information):**
 - OS: macOS Big  Sure
 - GAMA version: git,  branch 1.8.2
 - Java version: JDK 15

**Additional context**
Comment from Alexis: 
"It happens to me as well on macOS BigSur (each time I have a combination of displays, but not always. For instance Ant Foraging works well). The issue is in native code.
"

**Comment by AlexisDrogoul** [comment]
Seems like the particular combination of SWT 2021-03 / 2021-06 and JDK 15 (J9, used in the release) has removed this problem. I cant reproduce it anymore. Please reopen if it still happens on your computer.
