### ISSUE TITLE
Add warning when  2 parameters have the same name

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3169]
**Is your request related to a problem? Please describe.**
I wrote the simple model as follows:

```
model Dates

global {
	int i;
	int j;
}

experiment intBatch type: batch repeat: 2  until: (cycle>2) {	
	parameter "Alert time" var: i <- 0 min: 0 max: 10 step: 1;
	parameter "Alert time" var: j <- 0 min: 0 max: 10 step: 1;
}
```

The point is that I made a mistake: the 2 parameters have the same name "Alert time".
GAMA will  consider only the last one (and  in the case of the batch mode, will only run  11 experiments (and thus 22  simulations).

**Describe the solution you'd like**
Add a warning when 2 or more parameters have the same name.

**Comment by AlexisDrogoul** [comment]
Done. I've also taken into account the parameters defined in the model attributes (an Information is displayed).
