### ISSUE TITLE
[Model] Following Paths.gaml in Driving Skill is not meaningfull

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3170]
**Describe the bug**
When I  run the model `Following Paths.gaml` in Driving Skill plugin, I cannot understand what it is doing...
But  agents do not seem to follow any path.

**To Reproduce**
1. run the model `Following Paths.gaml` in Driving Skill plugin

**Screenshots**
<img width="595" alt="Screenshot 2021-08-23 at 11 46 35" src="https://user-images.githubusercontent.com/1555274/130426977-48857474-9bc6-40a5-b47c-1c8e39bc35a5.png">

**Desktop (please complete the following information):**
 - OS: macOS big sure
 - GAMA version: git 1.8.2
 - Java version: 15

**Comment by minhduc0711** [comment]
Hi Benoit, the vehicle is supposed to follow a path resembling the GAMA logo. But we agree that it is not a good example model, and thus will be replaced soon.

**Comment by minhduc0711** [comment]
I created a simpler model in `Following Paths.gaml` (commit 8a3afe7dfd2c74f31473b0dc7a6b6d2543b03965), please reopen if something still needs improving.
