### ISSUE TITLE
Environment drawing disappears when inspecting agent

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3173]
**Describe the bug**
Not sure if it's a bug or a feature but just in case I notice that in opengl when you inspect an agent (right click) the 3D referential disapear during the selection?. Maybe it's by purpose but as it was not like this before I prefer to report it just in case.

**Screenshots**
![Untitled9 mov](https://user-images.githubusercontent.com/3928502/131644109-4a059917-b93e-49ef-acd1-fb66d5b28890.gif)

**Desktop (please complete the following information):**
 - Catalina
- GAMA_1.8.2_Alpha_withJDK_Mac_08.26.21_0c64cc94

**Comment by agrignard** [comment]
The overlay also is disappearing when inspecting

**Comment by AlexisDrogoul** [comment]
Regarding the "world"/"axes", it's been five years that this behaviour is implemented. And the overlay has just recently followed this logic when becoming a "full" layer in OpenGL. The logic here is to remove all distractions while inspecting or invoking the menu, reinforcing the fact that it is a "different mode" than the normal one.

**Comment by agrignard** [comment]
Ok my bad!
