### ISSUE TITLE
Problem with simulation ( using moving skills , but only some of agents can move.)

### ISSUE THREAD

**Issue by Cindyyang57** [gama-platform/gama#3178]
Sorry I'm a beginning student in writing GAMA code, and I just tried to have agents to move on my GIS road file, then I used moving skills , but I have some problems while implementing the simulation . I wonder where is the problem with my code.  Thank's for your help !
### Steps to reproduce
**Attached  shp files**
[attached files.zip](https://github.com/gama-platform/gama/files/7116490/attached.files.zip)

**Here are my code**
model mainnewtest

global {
	//Shapefile of the buildings
	file building_shapefile <- file("../../QGIS file/buildings.shp");
	//Shapefile of the roads
	file road_shapefile <- file("../../QGIS file/new road.shp");
	file shape_file_bounds <- file("../../QGIS file/bound.shp");
	//Shape of the environment
	geometry shape <- envelope(shape_file_bounds);
	//Step value
	float step <- 10 #s;
	//Graph of the road network
	graph road_network;
	//Map containing all the weights for the road network graph
	
	init {
		//Initialization of the building using the shapefile of buildings
		create building from: building_shapefile;
		//Initialization of the road using the shapefile of roads
		create road from: road_shapefile;
		
		//Creation of the people agents
		create people number: 1000{
			//People agents are located anywhere in one of the building
			location <- any_location_in(one_of(building));
      	}
   
      	road_network <- as_edge_graph(road);
	}	
}

//Species to represent the people using the skill moving
species people skills: [moving]{
	point target;
	float speed <- 5 #km/#h;
	rgb color <- rnd_color(255);

	//Reflex to leave the building to another building
	reflex leave when: (target = nil)  {
		target <- any_location_in(one_of(building));
	}
	//Reflex to move to the target building moving on the road network
	reflex move when: target != nil {
	
		path path_followed <- goto (target: target, on: road_network, recompute_path: false, return_path: true);

		if (location = target) {
			target <- nil;
		}	
	}
	
	aspect default {
		draw circle(50) color: color;
	}
}

species building {
	aspect default {
		draw shape color: #gray;
	}
}

species road {
	aspect default {
		draw shape color: #red;
	} 
}

experiment traffic type: gui {
	
	output {
		display carte type: opengl{
			species building refresh: false;
			species road ;
			species people ;
		}
	}
}

### Expected behavior
All people agent created will move to the target through the GIS road I created.

### Actual behavior
Only some of them move ..... if  I only create few people agents, all of them won't move, however, if I created a lot of people agents, only some of them will move. I want all of them to move regardless of number , and I don't know why only some of them can move...

**Sceenshot**
![image](https://user-images.githubusercontent.com/90191212/132228968-708bfc1f-b5ba-40cc-a34c-d3bc56bdbca2.png)

### System and version 
GAMA 1.8.1 , window 10 OS

**Comment by benoitgaudou** [comment]
Dear,
First of  all, it  is not a GAMA issue,  but rather a question about your model.
Youu have the GAMA  mailing list for  this kind  of  questions.

Second, your issue may come from your  data file (roads are not well-connected, so your  agents cannot find a path in the  graph of  roads). In  GAMA, you have  a  model to clean your road shapefile (in the model library).
Cheers

**Comment by Cindyyang57** [comment]
Oh! I’m really sorry!Thanks’ for your help. I’ll try it again! 🙏🏻

benoitgaudou ***@***.***>於 2021年9月6日 週一，22:28寫道：
