### ISSUE TITLE
[Save] index out of bounds when trying to save to a file from a gaml file outside of the workspace 

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#318]
**Describe the bug**
When calling the `save` statement in a model that is not in the workspace, Gama stoped with an index out of bounds exception 

**To Reproduce**
1. Create a txt file with extension .gaml anywhere in your computer
2. copy/pass
```
global {
	init {
		save ["toto","tata"] to:"../res.csv" format:"csv";
	}	
}
experiment xp {}
```
3. WARNING : don't forget to put `model nameofyourfile` as header of the file
4. Import gaml file but *do not* copy it in workspace
5. Launch the experiment
6. See error

**Expected behavior**
Save statement works fine wherever the gaml file is 

**Desktop (please complete the following information):**
 - OS: MacOS and Windows 10
 - PC Model: Laptops
 - GAMA version: git and 1.9.3

**Context**
During a training session, I share a gaml files with participants and many of them have the error

**Comment by AlexisDrogoul** [comment]
If the file is not copied, it is linked then, right ? Maybe there is a relation with #203 ? 
In any case, can you copy and paste the stack in both macOS and Windows ?

**Comment by chapuisk** [comment]
* To answer first question, yes ! I asked trainee to simply drag & drop file they downloaded into Gama.
* Second question : yes it is related to the same issue, meaning that any I/O raises the same issues
* Thrid:
2 occurrences in 2 agents at cycle 0: Java error: index out of bounds
in Simulation 0
in init  {
	save ['toto','tata'] format: 'csv' to: '../res.csv' ;
}

ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
msi.gama.common.util.FileUtils.lambda$1(FileUtils.java:164)
java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
in agents Simulation 0, xp0

**Comment by AlexisDrogoul** [comment]
@chapuisk can you test the code in the #364 PR ? This should close this issue.
