### ISSUE TITLE
World coordinates issue in Java2D displays on HiDPI

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#3180]
**Describe the bug**
Pinking is not working in Java2D (I cannot select an agent by right clicking on it)

**To Reproduce**
1. Open Toy Models/Circle/Circle.gaml
2. Run the model
3. Try to right click on one of the agent to select it

**Desktop (please complete the following information):**
 - OS: Windows 10 HDPI scree -  tested with the laptop screen and with an external 4k screen
 - PC Model: xps 15 4K
 - GAMA version: git (1.8.2)

**Comment by AlexisDrogoul** [comment]
Does it work when you pause the model or the display ?

**Comment by ptaillandier** [comment]
It does not work for me either with my HDPI laptop screen or with the external 4K screen (The coordinates are wrong). However, for my HDPI screen, the coordinates seem less wrong than before the last commit.

**Comment by AlexisDrogoul** [comment]
Can you output somewhere the zoom being applied (you can get it using `DPIUtil.getDeviceZoom();` anywhere in a piece of code that deals with UI).  I've tried it on Win10 with 100%; 200%, and 150% zooms (as set in the Preferences of Windows) and everything worked like a charm. Unless you have another piece of software to manage your HiDPI screen than simply Windows ? (Graphic cards utility ??)

**Comment by ptaillandier** [comment]
with my 4k external screen: 100% (as expected)
With my HDPI screen: 200% - something that is weird, is that when I check in the options of windows, the zoom level is set to 250% (default and recommended value). I tried to set it to 200%, I got the right value for DPIUtil.getDeviceZoom() (200%) and it works well (the picking).
So the problem seems to comes from "DPIUtil.getDeviceZoom()", but, I don't know if it is very specific to my computer (in this case, it is maybe not very important) or not.

**Comment by AlexisDrogoul** [comment]
From the comment on `DPIUtil`: 

```
/**
	 * System property that controls the autoScale functionality.
	 * <ul>
	 * <li><b>false</b>: deviceZoom is set to 100%</li>
	 * <li><b>integer</b>: deviceZoom depends on the current display resolution,
	 *     but only uses integer multiples of 100%. The detected native zoom is
	 *     generally rounded down (e.g. at 150%, will use 100%), unless close to
	 *     the next integer multiple (currently at 175%, will use 200%).</li>
	 * <li><b>integer200</b>: like <b>integer</b>, but the maximal zoom level is 200%.</li>
	 * <li><b>quarter</b>: deviceZoom depends on the current display resolution,
	 *     but only uses integer multiples of 25%. The detected native zoom is
	 *     rounded to the closest permissible value.</li>
	 * <li><b>exact</b>: deviceZoom uses the native zoom (with 1% as minimal
	 *     step).</li>
	 * <li><i>&lt;value&gt;</i>: deviceZoom uses the given integer value in
	 *     percent as zoom level.</li>
	 * </ul>
	 * The current default is "integer200".
	 */
```


So you might want to try and run GAMA with `-Dswt.autoScale=quarter` in the VM args, for instance, to see if it works better. If true, then we can set it as the default (or at least make it a preference to not slow down the system, because I suspect that these choices are here for performance).

**Comment by ptaillandier** [comment]
It works well with this VM args (both with the HDPI screen and with the
external 4K screen). There is one side effect, just on the 4K external
screen, concerning the display of all icons (see the attached images).

Le ven. 10 sept. 2021 à 10:33, Alexis Drogoul ***@***.***> a
écrit :

**Comment by AlexisDrogoul** [comment]
There are no images attached.

**Comment by ptaillandier** [comment]
<img width="213" alt="without" src="https://user-images.githubusercontent.com/1506077/132797600-c5e8bba5-7948-4bfe-a741-361b7f03ad45.PNG">
<img width="246" alt="with" src="https://user-images.githubusercontent.com/1506077/132797603-abd6c731-2ece-4311-b09d-145b6bc26b32.PNG">

**Comment by AlexisDrogoul** [comment]
There is another property you can set in DPIUtil about how to scale images. Can you try it ?

**Comment by ptaillandier** [comment]
With the "exact" option, I get the same result.

**Comment by AlexisDrogoul** [comment]
No, I was talking about this one: 
```
	/**
	 * System property that controls the method for scaling images:
	 * <ul>
	 * <li>"nearest": nearest-neighbor interpolation, may look jagged</li>
	 * <li>"smooth": smooth edges, may look blurry</li>
	 * </ul>
	 * The current default is to use "nearest", except on
	 * GTK when the deviceZoom is not an integer multiple of 100%.
	 * The smooth strategy currently doesn't work on Win32 and Cocoa, see
	 * <a href="https://bugs.eclipse.org/493455">bug 493455</a>.
	 */
	private static final String SWT_AUTOSCALE_METHOD = "swt.autoScale.method";
```

Try  to set, for instance `-Dswt.autoScale.method=smooth` to see if something changes (but do not expect too much either !). Best in my opinion would be to stay with well-known values like 200% of scale.

**Comment by ptaillandier** [comment]
With this option, the icons are not displayed.  But, your are right. We can leave it like and just add a note in the documentation (about the zoom level and the VM args -Dswt.autoScale=quarter)

**Comment by AlexisDrogoul** [comment]
I have created a specific flag in ummisco.gama.dev.utils.FLAGS (to be passed in the same way than swt.autoScale, but easier to use) : 

```
        /**
	 * Used in msi.gama.application.Application to transmit the value of "quarter" (if true) to property
	 * org.eclipse.swt.internal.DPIUtil.SWT_AUTOSCALE, enabling more precise scaling methods for HiDPI screens.
	 * Otherwise the default is used by DPIUtil (see #3180). False by default.
	 */
	public static final boolean USE_PRECISE_AUTOSCALE = get("use_precise_autoscale", false);
```

So one just needs to pass `-Duse_precise_autoscale=true` to enable the `quarter` property. Otherwise the default will be used.
