### ISSUE TITLE
Bugged (black box flash appear and disappear) cycle dropdown in simulation view

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3183]

**Comment by RoiArthurB** [comment]
Explaination [here](https://github.com/gama-platform/gama/issues/3137#issuecomment-916598669)

> Normal behavior : 
> - GAMA is active window
> - Hover Experiment input 
> - create a small pop-up (new window) with extra info
>
>Tiling behavior :
> - GAMA is active window
> - Hover Experiment input 
> - create a small pop-up (new window) 
>   - Tiling switch the pop-up as the active window
> - GAMA is not the active window anymore
> - GAMA destroy the pop-up
> - [repeat] ⇒ Display quick pop-up flashing
>
> I don't think it's necessary to try to fix that "bug" (I think we're the 2 last guys using tiling windows), but I wanted to leave the explanation of why it's happening :)
