### ISSUE TITLE
Ubuntu & macOS: spacer icons appear black on dark gray background

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3185]
**Describe the bug**
On Ubuntu (latest version) the "invisible" space icons are visible in dark mode (black over a dark gray background). But not in the light mode.
![Ubuntu Linux 2021-09-09 19-04-30](https://user-images.githubusercontent.com/579256/132682696-54345dac-c237-44a8-979a-c2e4c2546bb2.png)

Conversely, the narrower spacer icons  appear in the light mode.
![Ubuntu Linux 2021-09-09 19-07-48](https://user-images.githubusercontent.com/579256/132683412-3f56ce6a-a54a-4e32-be7b-174cfadfb7fe.png)

**Expected behavior**
they should both be invisible to the user.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - PC Model: VM under macOS
 - GAMA version: git
 - Java version: 15
 - Graphics cards / Display system: Emulated GC

**Comment by AlexisDrogoul** [comment]
Same in macOS

**Comment by RoiArthurB** [comment]
Reproduced on non-VMed Manjaro Linux with X.org display 

![image](https://user-images.githubusercontent.com/16764085/132792940-ae916500-c3d4-4584-a726-10155d88b5df.png)

**Comment by AlexisDrogoul** [comment]
This is fixed by two successive commits. Tested on Ubuntu & macOS. Closing it now !
