### ISSUE TITLE
No visual separation between displays in the UI

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3187]
**Describe the bug**
Define several displays, the separation between tabs doesn't show up visually (as shown between inandout and contact)

**Screenshots**
<img width="329" alt="Screenshot 2021-09-09 at 15 17 52" src="https://user-images.githubusercontent.com/3928502/132693187-ff9a676f-eba8-4dba-9540-5519b58cf860.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 
 - GAMA version: GAMA_1.8.2_Alpha_withJDK_Mac_08.31.21_989e5a4e

**Additional context**

**Comment by RoiArthurB** [comment]
No separator display on the latest version on Linux

but the different background for the active tab + the changing one when hovering a tab seems enough 🤷

![image](https://user-images.githubusercontent.com/16764085/132796724-17024079-cc52-4b2c-ab0c-9adbdc93fbd5.png)

**Comment by AlexisDrogoul** [comment]
I have added an argument (declared in FLAGS) that can be passed to GAMA (`-Duse_old_tabs=true` or `=false`) to choose either the "old" tabs (with a visible border) or the "new" ones (without). A CSS style sheet is injected dynamically in the first case. 

```
	/**
	 * Used in msi.gama.application.workbench.ApplicationWorkbenchWindowAdvisor to impose the use of the "classic" view
	 * tabs (with a visible border) and inject a specific CSS stylesheet. See #3187. True by default.
	 */
	public static final boolean USE_OLD_TABS = get("use_old_tabs", true);
```

The "old" tabs are used by default.
