### ISSUE TITLE
Experiment separators are interactive button (clickable)

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#3189]
![Peek 2021-09-10 10-42](https://user-images.githubusercontent.com/16764085/132796191-ef4a04d6-4f52-4872-a7cf-0f4dc9fb3cc2.gif)

Doesn't do anything when clicked, but still an un-desired behavior

**Comment by AlexisDrogoul** [comment]
Fixed by two successive commits that drop spacers in the profit of separators. Tested on Ubuntu. Closing it now !
