### ISSUE TITLE
Cannot inspect an object when having a mesh

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3190]
**Describe the bug**
Cannot inspect agent when using a mesh

**To Reproduce**
1. Run BuildingHeatmap.gaml
2. Try to inspect an agent

**Expected behavior**
Being able to inspect an agent

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - GAMA_1.8.2_Alpha_withJDK_Mac_09.10.21_f9f09e1b

**Additional context**

**Comment by benoitgaudou** [comment]
I just tested. 
When the simulation is not launched, the inspect works well.
When I launch the simulation (and let the simulation running) , the richt-click continues to work.
But  after some time, the contextual menu is not  displayed anymore...

**Comment by AlexisDrogoul** [comment]
The solution is probably to hide completely the mesh while doing the inspection.

**Comment by AlexisDrogoul** [comment]
Closing it now (I've tested it myself in different scenarios, and the mesh disappears while inspecting, a bit surprising at first, but quite useful). Reopen if it still manifests itself.
