### ISSUE TITLE
Combination of macOS Dark Theme with Eclipse Light Theme

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3193]
Although the combination of macOS Dark Theme with Eclipse Light Theme is possible (in Eclipse), the result in GAMA is terrible: a number of components consider their default background as black or dark gray or their default font as white, as if they were styled by a dark style. 
However, when requesting the theme used (`ThemeHelper.isDark()` and `Display.isSystemDarkTheme()`) both values are correct: false and true. Strangely, the other way around works fine (i.e. macOS Light with GAMA Dark)

![New Model gaml - Gama (runtime) 2021-10-19 02-04-35](https://user-images.githubusercontent.com/579256/137791553-8ff13802-4b06-4492-bbe1-3c6aa97fc6d1.png)

**Comment by Phillipus** [comment]
> Fixed thanks to a tip from an Eclipse developer

Correction - I'm not an "Eclipse developer", I'm an Eclipse masochist.

It would be way more pleasant to gouge my own eyes out with a blunt spoon than develop anything using Eclipse. 😉
