### ISSUE TITLE
"New..." dialog resizing and displaying problems

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3194]
**Describe the bug**
The general "New" popup window has some issues in resizing / relocating its content.

**To Reproduce**
1. Right-click on User models
2. New ... > **Other**
3.  Click on GAMA  / GAMA Project  
  ==> 1) The information  are  displayed on  the bottom of the  window
4. Click on Back
   ==> 2) The white-background part with the various options is too small for the screen.  (a  click on an  option  resize it)
5. Click on Model  file, choose a project
6. Click on Back button
   ==> 3) The Sselect a wizard window is empty and grey. We need to resize it to   see the options.

**Screenshots**
   ==> 1) The information  are  displayed on  the bottom of the  window
<img width="588" alt="Screenshot 2021-09-13 at 05 59 16" src="https://user-images.githubusercontent.com/1555274/133022761-994e58fa-cd3f-46f5-994c-d5fcc547505e.png">

   ==> 2) The white-background part with the various options is too small for the screen.  (a  click on an  option  resize it)
<img width="588" alt="Screenshot 2021-09-13 at 05 59 24" src="https://user-images.githubusercontent.com/1555274/133022773-82787c79-0118-453e-9978-1d3c141b5f4b.png">

   ==> 3) The Sselect a wizard window is empty and grey. We need to resize it to   see the options.
<img width="587" alt="Screenshot 2021-09-13 at 05 59 48" src="https://user-images.githubusercontent.com/1555274/133022790-27cd13a6-5fa6-43c8-a1f9-35cc06f5483e.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sure
 - GAMA version: git
 - Java version: 11

**Comment by AlexisDrogoul** [comment]
Actually, the same issue arises with different wizards as well (text, folder, etc.), which are not managed by GAMA, once one of the GAMA wizards have been previously chosen. I dont quite get it.

**Comment by AlexisDrogoul** [comment]
Closing it now (I've tested it myself in different wizards). Reopen if it still manifests itself.
