### ISSUE TITLE
Freeze of GAMA when vertically resizing the main window  (with at least one openGL  display)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3195]
**Describe the bug**
GAMA freezes when  resizing the main window (displaying 2 OPENGL displays) (seems linked to a resize of one display).

**To Reproduce**
1. Run the model Building HeatMap.gaml > experiment Show heatmap.
2. Resize the main window

**Screenshots**

<img width="1245" alt="Screenshot 2021-09-13 at 12 20 30" src="https://user-images.githubusercontent.com/1555274/133068281-cb1c34a3-bb5f-4f3f-8833-c0d73fde563d.png">

**Desktop (please complete the following information):**
 - OS: macOS Big  Sure
 - GAMA version: git

**Comment by agrignard** [comment]
I don't have it on Mac Catalina 10.15.7

**Comment by AlexisDrogoul** [comment]
Cant reproduce it either... Would it be linked to specific preferences  ? Can you show your display preferences ?

**Comment by RoiArthurB** [comment]
Not sure if it's related, but the experiment `Library Models > Vizu and User Interaction > Visualisation > Charts > models > Ant Foraging (Charts Examples).gaml` makes GAMA crash when the layout try to split. It may be a margin behavior of the OpenGL window being resized over some Java2D windows...

Here's the [crash log](https://pastebin.com/HX72nsvU)

**Comment by AlexisDrogoul** [comment]
I have implemented a workaround that forces the main window to resize its views asynchronously (i.e. accumulate the resize events and deliver them all at once when the mouse is released). It is enabled by default on macOS, but can activated on other environments (with slow graphics, for instance) using the `-Duse_delayed_resize=true` flag, documented in `ummisco.gama.dev.utils.FLAGS.java` (and that we should document somewhere with the other flags).
