### ISSUE TITLE
bug in coupling models in version 1.8.2

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3198]
**Describe the bug**
When we let one model assign parameters to the imported model. It works well in version 1.8.1. However, in version 1.8.2, the parameters of the imported model do not change. Try running the small test below in both versions:

**To Reproduce**
1. Create two models: one called big and the other called small

 Code of small model:
```
global {
	int friend <- 5;
	
	init {
		write 'friend= ' + friend;
	}
}

experiment small type: gui {

}
```
Code of big model:

```
import 'small model.gaml' as small_model
global {
	action create_small (int friend) {
		create small_model.small with:[friend:friend];
	}
	
	init {create person;}
}

species person {
	reflex when:time=1 {
		ask host {
			do create_small (friend:7);
		}
		ask first(small_model.small).simulation {do _step_;}
	}
}
experiment big type: gui {}
```
**Expected behavior**
When we run big model, the console should write (7) which is the action of the small model after changing the parameter. In Gama 1.8.2, it writes 5, which means that it did not change the value of the imported model. If you run the same code in version 1.8.1, it works well. So, I think there is something wrong

**Comment by Aya-Badawy89** [comment]
I clicked on help--check for updates in 1.8.2. I did the same when I returned to version 1.8.1. However, there is now a problem in updating version 1.8.1, and the coupling (which used to work in 1.8.1) does not work at all now !
I do not know if it was wrong to update both versions. I re-installed version .1 but coupling gives an error

**Comment by AlexisDrogoul** [comment]
@Aya-Badawy89 : the update problem is probably related to #3013 , sorry for that. We are in the process of separating the updates of 1.8.1 and 1.8.2 but @hqnghi88 has had some problems and could not finish the task.

**Comment by Aya-Badawy89** [comment]
Thank you, Alexis. for your reply.
The problem is that without the update, comodelling does not work at all on version 1.8.1. So, at the moment, I cannot run my models because  v1.8.2 has the parameters problem and v1.8.1 has the update problem.
I would be really grateful if @hqnghi88 can help in resolving the issue of the parameters (descibed above) in 1.8.2, so that I can run the model.

**Comment by hqnghi88** [comment]
Hi, i will see this today. For the update, i separated the 2 version already. What is the errro @Aya-Badawy89 ?

**Comment by Aya-Badawy89** [comment]
Hello,

Here are the exact details of the error which appears to me:

Cannot complete the install because of a conflicting dependency.
 Software being installed: Dependencies of GAMA 1.8.1.202109040337 (ummisco.gama.feature.dependencies.feature.group 1.8.1.202109040337)
 Software currently installed: Gama 1.8.1.202006230234 (ummisco.gama.application.product 1.8.1.202006230234)
Only one of the following can be installed at once: 
 Equinox Provisioning Drop-in 1.3.0.v20181023-0914 (org.eclipse.equinox.p2.reconciler.dropins 1.3.0.v20181023-0914)
 Equinox Provisioning Drop-in 1.3.500.v20210116-1855 (org.eclipse.equinox.p2.reconciler.dropins 1.3.500.v20210116-1855)
Cannot satisfy dependency:
From: Equinox p2, backward compatibility support 1.4.300.v20190218-2100 (org.eclipse.equinox.p2.extras.feature.feature.group 1.4.300.v20190218-2100)
To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.reconciler.dropins [1.3.0.v20181023-0914,1.3.0.v20181023-0914]
Cannot satisfy dependency:
  From: Gama 1.8.1.202006230234 (ummisco.gama.application.product 1.8.1.202006230234)
 To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.extras.feature.feature.group [1.4.300.v20190218-2100,1.4.300.v20190218-2100]
Cannot satisfy dependency:
From: Dependencies of GAMA 1.8.1.202109040337 (ummisco.gama.feature.dependencies.feature.group 1.8.1.202109040337)
 To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.reconciler.dropins [1.3.500.v20210116-1855,1.3.500.v20210116-1855]

Comodeling in 1.8.1 does not work unless I make the update. I am used to that. But now, while having a problem with the update, comodelling is not working. It does not create the imported model saying nil value

**Comment by AlexisDrogoul** [comment]
I think the issue comes from the fact that, at some point, 1.8.2 files have been uploaded to the "regular" 1.8.1 update site. Now every update of 1.8.1 fails more or less. Is that correct, @hqnghi88 ? And if it is, is there a way to revert this upload (this would also allow to fix #3013).

**Comment by hqnghi88** [comment]
@Aya-Badawy89 can you retry with the updating , i just redeployed a full stack, as Alexis said it should have corruption somewhere.
The coupling model tested and did not fixed yet, i still investigate the modifications.

**Comment by Aya-Badawy89** [comment]
Yes, the update works now. I will move to 1.8.1 for now until 1.8.2 is modified. 
Thank you very much

**Comment by AlexisDrogoul** [comment]
@hqnghi88 any update on that one ? Can I help ?

**Comment by hqnghi88** [comment]
Yes, please, i need your help, as i stuck in the GamaPopulation. orderAttributes. The attributes are well computed for normal agents (experiment, simulation, gamlagent) but it did not recognized all attributes from micro-simulation agent. Something relate with the DirectedAcyclicGraph?

**Comment by AlexisDrogoul** [comment]
Hum.... Seems like a consequence of fixing #3068. I'll take a look.

**Comment by AlexisDrogoul** [comment]
Hi,

I've simplified the code to just keep the bug (otherwise, with all the `ask xxx {...}` and their different contexts, it was easy to be lost). 

```gaml
model SmallModel

global {
	int friend <- 5;
	
	init {
		write string(self) +' friend= ' + friend;
	}
}

experiment small;
```

and 

```
model Issue3198


import 'small model.gaml' as small_model
global {
	init {create small_model.small with:[friend:7];}
}

experiment big;
```

and I wonder: was this code even supposed to work at all ??? `friend` is a variable of `small_model`, not a variable of its experiment called `small`. So we shouldn't normally allow this expression. @hqnghi88 did we allow this before ?

**Comment by hqnghi88** [comment]
I see the different of variable of sim or exp.  I tried declare another in exp but it seems not to work. 
And yes, we allow this before (as Aya said it worked for 1.8.1) and i remember some comodel use this to change the value of variable of the default simulation.

**Comment by AlexisDrogoul** [comment]
OK. I guess we'll have to revise this seriously for https://github.com/gama-platform/gama/tree/GAMA_2.0 ^^ (@RoiArthurB, listen !). In the meantime, I'll try to see why this variable is not recognised and correctly initialised...

**Comment by AlexisDrogoul** [comment]
From what I can see, the Java code is doing the right thing: asking the `ExperimentPopulation` to create one agent, then browsing through the variables declare in this population -- and not finding `friend` of course... -- to initialize them. 

But I think I found the problem. It is in `ExperimentPopulation`. Before, the method `createVariables` was redefining `createVariables` in `GamaPopulation` -- but it is not the case anymore (and it is where the simulation variables were modified !). Same for createAgents, by the way; it seems it is never called. I will try to change this.

**Comment by Aya-Badawy89** [comment]
There is another remark too. If you notice, the console prints friend twice, when it should print it only once because it created one experiment. In 1.8.1, it writes it once whereas in 1.8.2, it writes it twice.

Side remark: as you were discussing the code, I also noticed yesterday that if we want to get an attribute from an agent in the imported model, we write: 
ask ((imported model.experiment at 0) . simulation) . the agent {}
which I felt is a bit long..

**Comment by AlexisDrogoul** [comment]
Fixed. I will close this issue now -- @Aya-Badawy89 the discussion about the syntax of co-modeling should maybe be open in "Discussions", especially if you have ideas on how it should be simplified.
