### ISSUE TITLE
Model visualization problem when using GAMA 1.8.2 in MacOS Big Sur

### ISSUE THREAD

**Issue by rcr147** [gama-platform/gama#3200]
**Describe the bug**
The visualization of my model is somewhat "distorted" when using GAMA 1.8.2 in Mac OS Big Sur.

![image](https://user-images.githubusercontent.com/21116606/133885452-dca8c0ad-b5b2-416c-9a29-3032fb036a89.png)

Previously, when using GAMA 1.8.1 in Mac OS El Capitan, the model's visualization was intact. 

![image](https://user-images.githubusercontent.com/21116606/133885360-b226a66e-256e-4e8e-92a3-fb572f04aa3d.png)

**To Reproduce**
GAMA Project: https://drive.google.com/file/d/1vliKtqacb4KJ8aJkqOmmYy4SRjbuXW5F/view?usp=sharing

1. This is the part of the model that is causing the problem, but this is working in GAMA 1.8.1.
                    
                create households from:csv_file( "../includes/householdAgents.csv",true) with:
                [ hhID::int(get("HouseholdID")), 
                        headOfHousehold::string(get("HeadOfHousehold")), 
                        incomeLevel::string(get("IncomeLevel")),
                        levelOfEducation::string(get("LevelOfEducation")), 
                        hasSmallKids::bool(get("PresenceOfChildren")),
                        hasElderly::bool(get("PresenceOfElderly")),
                        withDisability::bool(get("PresenceOfDisabledMembers")),
                        houseOwnership::bool(get("HouseOwnership")),
                        yearsOfResidency::bool(get("YearsOfResidency")),
                        pastTyphoonExperience::bool(get("TyphoonExperience")),
                        houseQuality::string(get("HouseQuality"))
                ]	
                {	
                        choice <- first(buildingShuff);
                        remove choice from: buildingShuff;
                        location <- any_location_in(choice);
                        speed <- rnd(2, 5)#km/#h;
                }

		create rescuers number:nb_rescuers_init
		{

			location <- any_location_in(one_of(points));
			startPoint <- location;
		}
				
		create shelterManagers number:nb_shelterManagers_init
		{
			evacCenter <- first(evacuationCentersShuff);
			remove evacCenter from: evacuationCentersShuff;
			location <- any_location_in(evacCenter);
			acceptedEvacuees <- 0;
			full <- false;
		}		

2. Commenting out this part of the code somewhat resolves the visualization problem.

          //		create rescuers number:nb_rescuers_init
          //		{
          //			location <- any_location_in(one_of(points));
          //			startPoint <- location;
          //		}
          //				
          //		create shelterManagers number:nb_shelterManagers_init
          //		{
          //			evacCenter <- first(evacuationCentersShuff);
          //			remove evacCenter from: evacuationCentersShuff;
          //			location <- any_location_in(evacCenter);
          //			acceptedEvacuees <- 0;
          //			full <- false;
          //		}		

**Desktop (please complete the following information):**

OS: macOS Big Sur
GAMA version: 1.8.2 Alpha

**Comment by AlexisDrogoul** [comment]
Hi. I'm using the exact same configuration as yours, and here is what I obtain:

![Typhoon_BETA gaml 2021-09-18 22-18-51](https://user-images.githubusercontent.com/579256/133893744-6818f177-f574-4ce5-891a-2a3cd7d70495.png)

Are you sure you're using the latest alpha version (it changes a lot these days, sorry for the inconvenience) ?

**Comment by rcr147** [comment]
Hello, I installed the GAMA 1.8.2 version a month ago. Today I installed and tried the latest version and indeed the visualization problem is resolved. Thank you very much!
