### ISSUE TITLE
Max memory in developer (git) version is wrongly displayed

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3203]
**Describe the bug**
Open the preferences and go to "Execution" tab. The settings beginning with "The max. memory ..." displays a strange value.

**Screenshots**
![Monosnap 2021-09-20 13-53-23](https://user-images.githubusercontent.com/579256/133965684-c9a4c851-3c3a-4b57-8a6f-b1e99bd9474b.png)

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - PC Model: MBP 16"
 - GAMA version: git (launched from Eclipse)
 - Java version: 15.0.2

**Comment by minhduc0711** [comment]
Might be related: I have been seeing this message recently when running a GUI experiment
```
 at cycle 507: Memory is low (0 megabytes). You should close the experiment, exit GAMA and give it more memory
```
