### ISSUE TITLE
Things to do before 1.8.2 release

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3209]
@gama-platform/committers / @gama-platform/core 

Here are the various things to check (and do) before releasing 1.8.2, in addition to fixing the issues for this milestone (https://github.com/gama-platform/gama/milestone/9). Please edit this issue to add new items. 

- [x] Verify that the version is 1.8.2 everywhere (product, maven, code, MANIFESTs, images, documentation..)
- [x] Verify that the updates correctly use the new "1.8.2" subdirectory and do not interfere with 1.8.1
- [ ] Conducts tests of the standalone version on Linux, macOS and Windows w. and w/o the J9 JDK
- [x] Tests that 1.8.2 still works under macOS Monterey and Windows 11 (beta versions)
- [ ] Prepare the front page of the website to announce 1.8.2
- [ ] Make a list of the changes between 1.8.1 and 1.8.2
- [ ] Remove any broken or not "ready for prime time" functionality 
- [ ] Verify the tutorials at https://gama-platform.org/wiki/Tutorials (see #3253)

**Comment by hqnghi88** [comment]
I test a release on windows 11, all the library models seem to work well, comokit also.

**Comment by hqnghi88** [comment]
I modified manifest, plugin.xml, pom.xml and .product to have 1.8.2. It still need to review images and documentations.

**Comment by AlexisDrogoul** [comment]
Closing in favour of more specific issues.
