### ISSUE TITLE
Toolbar icons do not refresh correctly on macOS

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3210]
**Describe the bug**
When opening the simulation perspective or coming back to it, sometimes (not always) icons do not get refreshed in the main toolbar or in the displays (esp. visible when multiple displays are at play). See the small gif that shows it quite well.
**To Reproduce**
1. Open an experiment with several displays (seems more prominent with openGL displays)
2. Move back and forth the edition and experiment perspectives. The main toolbars or some displays have "lost" their icons.

**Expected behavior**
That the refresh is immediate. 

**Workaround**
Resizing the windows, the views, or passing on the buttons with the mouse is sufficient to make them reappear.

**Screenshots**
![screencast 2021-09-25 00-51-41](https://user-images.githubusercontent.com/579256/134720123-e9682667-f99e-49f7-baf6-9a2c0beb6a65.gif)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - PC Model: MBP 16" 
 - GAMA version: git
 - Java version: 15.0.2 (J9)
 - Graphics cards / Display system: AMD Radeon Pro 5500M 8 Gb -- 34" screen

**Comment by AlexisDrogoul** [comment]
Happens also when trying to close a previous simulation 

![HANOI30 - Visualization and User InteractionVisualization3D VisualizationmodelsBuilding Elevation gaml - Gama 2021-09-25 15-59-44(1)](https://user-images.githubusercontent.com/579256/134765946-97a208a3-9f5e-4906-b766-fc4e19c8c3a4.png)

**Comment by AlexisDrogoul** [comment]
@ptaillandier @hqnghi88 @RoiArthurB any occurrence of this bug on Windows and Linux ?

**Comment by hqnghi88** [comment]
No, i dont have this on win11.

**Comment by AlexisDrogoul** [comment]
It has been fixed by the above commit, although it is more a workaround than a fix ! It is far from perfect as it doesn't cover the missing toolbars at simulation launch described in #3217.
