### ISSUE TITLE
Decimals precision changes in loop

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3211]
**Describe the bug**
When looping over a float number and decreasing it in each step, the number starts having 15 decimal places

**To Reproduce**
please check the following code:
```
init {
	float n <- 4.00;
	loop while: n > 3 {
		n <- n - 0.05;
		write n;
	}
}
```

**Expected behavior**
(n) should be written as:
3.95
3.90
3.85
3.80
.
.

In the console, (n) is written:
3.95
3.9000000000000004
3.8500000000000005
3.8000000000000007
3.750000000000001
3.700000000000001
.
.
.

Although the two sides of the equation are with the same precision, why the answer starts gaining more decimal places?

**Comment by Aya-Badawy89** [comment]
The problem sometimes happens when I insert a parameter (of type integer) through user_input and then I assign it to a float. Instead of adding 1 decimal place, sometimes it adds 15. I do not know why it behaves so.

**Comment by AlexisDrogoul** [comment]
This is a general issue of precision in decimal numbers (not specific to GAML). For the (long) background on this: https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html 

GAML uses Java's `Double` objects for its `float` type, and there is unfortunately nothing we can do automatically, except providing some tools to enable modellers to do manual corrections, like `with_precision`. In your case, the following code should fulfil your needs:

```gaml
init {
	float n <- 4.00;
	loop while: n > 3 {
		n <- (n - 0.05) with_precision 2;
		write n;
	}
}
```
