### ISSUE TITLE
Multiple big image layer in display causes problem of stability

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3212]
It is hard to reproduce with small (simple) model, but i think i should report this phenomenon.
I have a simple test model with just multiple image layer in display, where the image are big enough (50MB)
![image](https://user-images.githubusercontent.com/6105384/134754202-d6d0021d-d0ed-4b6f-bf90-8c148641aa75.png)
When i launch the model, the loading time is long (normally) and in eclipse console, there is several block of this exeption.
Exception in OpenGL:Waited 5000ms for: <409d4238, 4e5aa45b>[count 1, qsz 0, owner <main>] - <Animator thread>
java.lang.RuntimeException: Waited 5000ms for: <409d4238, 4e5aa45b>[count 1, qsz 0, owner <main>] - <Animator thread>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:170)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:975)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:674)
	at ummisco.gama.opengl.view.SingleThreadGLAnimator.displayGL(SingleThreadGLAnimator.java:239)
	at ummisco.gama.opengl.view.SingleThreadGLAnimator.run(SingleThreadGLAnimator.java:219)
	at java.base/java.lang.Thread.run(Thread.java:832)
The simulation however can launch, but the stability is unpreditable, it can crash at anytime.
Mostly it is the problem with graphic card, or memory problem....
Gama 1.8.2 git,
windows 10, 11

**Comment by AlexisDrogoul** [comment]
Hi Nghi,

Is it only the problem of these messages displaying in the console (they simply tell that the transformation of the images into textures takes too long) ? Or does it crash after that ? And in that case, do you have any other logs / error report ? What happens exactly ? 

Alexis

**Comment by hqnghi88** [comment]
Dear Alexis,
Sometimes, it crash with the technical report, no exception in the console , just a message of out of memory.
[hs_err_pid13860.log](https://github.com/gama-platform/gama/files/7229209/hs_err_pid13860.log)
[replay_pid13860.log](https://github.com/gama-platform/gama/files/7229210/replay_pid13860.log)

**Comment by AlexisDrogoul** [comment]
Hmmm... No way you can follow what's happening (in terms of memory) with YourKit ? I have a license key, by the way, that I can PM you. It is probable that the creation of textures uses some non-heap memory (NIO buffers).

**Comment by hqnghi88** [comment]
https://drive.google.com/file/d/12DDWQ-9pbwCJF_piV6moiasSyy-F4mNl/view?usp=sharing 
Here is the model with these big images.

**Comment by AlexisDrogoul** [comment]
Yes. it is a problem of memory. I've monitored the loading of images with YourKit, and a lot of cached information is produced, not to mention the garbage and the other things... I have committed a version with a new preference (called `pref_display_use_cache`) that you can set in your simulation to false, reducing the memory used by approx. 2x. Just give it a try and tell me if it is better.

**Comment by hqnghi88** [comment]
It change, the behavior: when launch the test model, the display are shown but gray:
![image](https://user-images.githubusercontent.com/6105384/135717748-222efa2d-4c94-4026-a932-4b95667b2c89.png)
a bit long later, the images are shown. But Yes, it is stable now, i can reload, relaunch many times with our exception, crashes.

**Comment by AlexisDrogoul** [comment]
So we consider it fixed ? I have to find a way to indicate that we are loading images, maybe ?

**Comment by hqnghi88** [comment]
Yes, it fixed. Thanks. And yes, the indicator should be somewhere (status?) because the display is still gray when status is already green
