### ISSUE TITLE
Undetected semantic error in enter() operator 

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3213]
**Describe the bug**
Apologies for posting a lot these days.
In user_input_dialog, I inserted an initial value greater than the maxium by mistake. However, Gama did not detect an error. The console prints the initial value as it is although it is less than the max.
When testing the same with an attribute using min and max facets, I found that if the initial value is bigger than max, Gama behaves differently by printing the maximum not the initial value

**To Reproduce**
```
int a <- 4 min:0 max:3;
	reflex start when: time=1 {
		map check <- user_input_dialog('Check', [enter('Max',15,0,12,1)]);
		write check['Max'];
		write a;
```

**Proposed correction**
I think we should get an error when inserting an initial value not between the min and max, or if, in this case, Gama will automatically take the maximum as it did with the attribute, then we should have ay least warning that the initial value will be changed.

**Comment by AlexisDrogoul** [comment]
I've fixed this issue by (1) clamping the value in `enter(..)` like it is in the attribute declaration; (2) documenting this fact in both cases. 
Thank you for spotting this.
