### ISSUE TITLE
Problem with fullScreen (esc) scale 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3218]
**Describe the bug**
I just notice this by trying to make some screenshot in fullScreen. Sometimes the scale of the display is screwed as shown in the gif.

Maybe this is due to my "weird" configuration having an "oooooold" macbook from 2016 ;-) as it seems not to happen on another more normal macmini, in this case I might stop to report graphical issue until I have a new one. 
(It was working like a charm and use many many time on this computer on Gama 1.8.1)

So maybe also related to this one #3199 
 
![Screen Recording 2021-09-28 at 19 49 52 mov](https://user-images.githubusercontent.com/3928502/135140107-69d70b0a-b815-4779-996b-656200c1a4af.gif)

**To Reproduce**
Any opengl display (here Raod Traffic tutorial)

**Desktop (please complete the following information):**
 - (Catalina, Ram 16 GB, AMD Radeon R9 M370X 2 GB
Intel Iris Pro 1536 MB)

**Additional context**

**Comment by AlexisDrogoul** [comment]
My guess is that it is more related to the interplay between macOS Catalina and JDK 11++ than to the age of the MBP. Mine from 2015, on macOS Big Sur, doesn't have these problems. The reason of the move is here : #3050

**Comment by agrignard** [comment]
Ok I see so not maybe not an issue? Who is still running a mac on Catalina except me ? What would be your advice ? Update to Big Sur? Does the GAMA 1.8.2 works well on Big Sur?

**Comment by AlexisDrogoul** [comment]
Seems (heard from Srirama) that the pre-release of 1.8.2, with the right JDK and SWT lib, works fine on Catalina. Otherwise, to use the git version, [JDK 15 J9](https://adoptopenjdk.net/archive.html?variant=openjdk15&jvmVariant=openj9) and Eclipse 2021-09 are advised !
I will close this issue from now on.
