### ISSUE TITLE
GAMA git version does not respect VM memory args

### ISSUE THREAD

**Issue by minhduc0711** [gama-platform/gama#3220]
**Describe the bug**
No matter what I set for `-Xms` and `-Xmx` in the run configuration, the actual values seem to be fixed at 256MB initial and 1024MB maximum.

**To Reproduce**
1. Set arbitrary values for the VM args `-Xms` and `-Xmx`
2. Go to `gama.runtime.product` and click on `Synchronize this configuration with the product's defining plug-in`
3. Launch GAMA and hover over the memory bar at the bottom to see the actual values

**Expected behavior**
These VM args are respected.

**Screenshots**
![20210929_15h53m57s_grim](https://user-images.githubusercontent.com/34294427/135237761-1e473f7a-71f1-4044-b792-39f5af20f84f.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - GAMA version: Git
 - Java version: java-15-adoptopenjdk

**Comment by minhduc0711** [comment]
Issue went away after I delete and re-imported projects in Eclipse.

**Comment by minhduc0711** [comment]
Reopening because it came back and I found out how to reproduce it: it happens after I click on `Synchronize` in `gama.runtime.product` and launch GAMA.

![image](https://user-images.githubusercontent.com/34294427/135606076-04d5eb12-4127-4fcc-9004-10cc7c358b61.png)

This does not happen when I checked out an old commit (a4da4f346), re-import projects and rebuild everything. I can try bisecting to see the bad commit that led to this issue.

**Comment by RoiArthurB** [comment]
@minhduc0711 Sorry for the delayed response, didn't see the ping.

We don't **need** different memory arguments particularly for Linux, simply that some time ago these parameters where unique per OS (still visible in ` gama/ummisco.gama.product/gama.product`) and been recently moved to global arguments, and Linux should have been forgotten. 🤷🤷🤷

I'll push the cleaned version :)
