### ISSUE TITLE
Some update sites do not exist anymore

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3223]
![image](https://user-images.githubusercontent.com/6105384/135634046-98944263-876c-4e3b-84d7-13f7bf9d121c.png)
It seems above update sites are disconnected. We should remove or resurrect them?

**Comment by AlexisDrogoul** [comment]
For EasyShell, the correct one is : https://github.com/anb0s/EasyShell/releases/tag/v2.2.1
For TM Terminal, it is now incorporated in the CDT project releases at: https://download.eclipse.org/tools/cdt/releases/10.4
(maybe we can remove this one ?)

**Comment by hqnghi88** [comment]
and genstar @benoitgaudou @chapuisk ?

**Comment by RoiArthurB** [comment]
Genstar is included by default now, isn't it ? 🤔🤔🤔
