### ISSUE TITLE
Problem with Path generation from DXF FIle

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3224]
**Describe the bug**
Sorry this issue might be very project oriented but maybe it will raise a more high level issue from GAMA

**To Reproduce**

0. Clone this repository  https://github.com/CityScope/CS_Proxymix
1. Import the ProxymixABM  project in GAMA
2. Open models/ToolKit/generate_pedestrian_network.gaml
3.  Run ```generate_pedestrian_network``` experiment 

In my case I get the following error when trying to generate the path 

````
2 occurrences in 2 agents at cycle 0: Java error: NoSuchElementException
in save pedestrian_path collect each.free_space type: shp to: free_space_path ;
NoSuchElementException: No value present
java.base/java.util.Optional.get(Optional.java:141)
org.geotools.data.shapefile.shp.PolygonHandler.write(PolygonHandler.java:529)
org.geotools.data.shapefile.shp.ShapefileWriter.writeNonNullGeometry(ShapefileWriter.java:225)
org.geotools.data.shapefile.shp.ShapefileWriter.writeGeometry(ShapefileWriter.java:197)
org.geotools.data.shapefile.ShapefileFeatureWriter.write(ShapefileFeatureWriter.java:418)
org.geotools.data.shapefile.IndexedShapefileFeatureWriter.write(IndexedShapefileFeatureWriter.java:98)
org.geotools.data.shapefile.IndexedShapefileFeatureWriter.next(IndexedShapefileFeatureWriter.java:75)
in save pedestrian_path collect each.free_space type: shp to: free_space_path ;
in if build_pedestrian_network or not(file_exists(pedestrian_paths_path))  {
	geometry walking_area_g <- copy(shape);
	if empty(wall)  {
		ask dxf_element  {
			walking_area_g <- walking_area_g - shape;
			walking_area_g <- walking_area_g.geometries with_max_of each.area;
		}
	
	}else  {
		if build_pedestrian_network  {
			ask dxf_element  {
				loop pt over: entrances  {
					walking_area_g <- walking_area_g - at_location(square(0.05),pt);
				}
			
			}
		
		}
````
**Expected behavior**
A generated path and the possibility to run ```test_pedestrian_network```

**Screenshots**
<img width="1440" alt="Screenshot 2021-10-04 at 16 13 35" src="https://user-images.githubusercontent.com/3928502/135867078-934d1f9e-e172-4103-bebf-6e98a6808ca2.png">

**Desktop (please complete the following information):**
This is happening with the last 1.8.2 release on Catalina and also on Mojave (I don't know if it can comes from that) . For @ptaillandier it is working on his computer. There is also an issue about this on the corresponding repo https://github.com/CityScope/CS_Proxymix/issues/188

**Comment by ptaillandier** [comment]
I don't have this issue either with the last release or with the git
version (on windows). Can someone with a mac test it?

Le mer. 6 oct. 2021 à 22:16, Arnaud Grignard ***@***.***> a
écrit :

**Comment by benoitgaudou** [comment]
Hi
I just tried on my Mac with Big Sure and the 1.8.2 Alpha (from this
morning).
I get exactly the same error as Arnaud.

Cheers

Benoit

Le mer. 6 oct. 2021 à 17:46, ptaillandier ***@***.***> a
écrit :

**Comment by agrignard** [comment]
Now fix on the new release
