### ISSUE TITLE
Problem when saving data into a shapefile

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#3225]
**Describe the bug**
Bug related to the release version of GAMA 1.8.2 alpha (not happening with the git version). When trying to save data into a shapefile, I get this error:
2 occurrences in 2 agents at cycle 0: Java error: NoClassDefFoundError
in save building to: '../results/buildings.shp' type: shp attributes:  ['ID'::int(self),'TYPE'::type]  ;
NoClassDefFoundError: org/geotools/data/shapefile/ShapefileDataStore
msi.gaml.statements.SaveStatement.saveShapeFile(SaveStatement.java:1138)
msi.gaml.statements.SaveStatement.saveShape(SaveStatement.java:792)
msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:372)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:359)
msi.gama.runtime.IScope.execute(IScope.java:506)
in save building to: '../results/buildings.shp' type: shp attributes:  ['ID'::int(self),'TYPE'::type]  ;

**To Reproduce**
1. Run model "Data/Data Exportation/Save to SHP.gaml

**Desktop (please complete the following information):**
 - GAMA version: release : GAMA_1.8.2_Alpha_withJDK_Win_10.01.21_bad7cb43.zip

**Additional context**
Concerns only the release (1.8.2 alpha), not the git version

**Comment by hqnghi88** [comment]
a release on my machine dont have this issue. i will try with a new download from github

**Comment by hqnghi88** [comment]
i cant reproduce with Data Exportation/Save to SHP.gaml from GAMA_1.8.2_Alpha_Win_10.01.21_bad7cb43.zip

**Comment by ptaillandier** [comment]
I tested with the latest version (10/06/2021) and it works...so I don't know why I had this bug, but we can close this issue.
