### ISSUE TITLE
Problem with Agent browsing on a specific (but simple) model

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3229]
**Describe the bug**
With this specific model I cannot browse the population of agent created (here district). I guess it might be due to the information in the district species (data are coming from Data Grand Lyon)

However everything seems ok and I can inspect the created agent but not browse it

**To Reproduce**
Run this model 
`````
model lyon_reagent   

global {
	file district_file <- geojson_file("https://download.data.grandlyon.com/wfs/grandlyon?SERVICE=WFS&VERSION=2.0.0&request=GetFeature&typename=adr_voie_lieu.adrarrond&outputFormat=application/json;%20subtype=geojson&SRSNAME=EPSG:4171");

	geometry shape <- envelope(district_file);
	init {
		create district from: district_file with: [name::read("nom")];
	}
} 

species district {
	rgb color <- rnd_color(255);
	rgb text_color <- (color.brighter);
	
	aspect default {
		draw shape color: color wireframe:true border:#black width:2;
		draw name font: font("Helvetica", 12 + #zoom, #bold) color: #black at: location + {0,0,0.01} perspective:false;
	}
}


experiment Display  type: gui {
	output {
		display Lyon type: opengl{	
			species district;		
		}
	}
}
`````
Try to browse the population of district
Nothing appaears
**Expected behavior**
Inspection 

**Screenshots**

<img width="1440" alt="Screenshot 2021-10-06 at 18 31 25" src="https://user-images.githubusercontent.com/3928502/136245641-9b18bb8f-96ad-4986-983c-d9b2047befc3.png">
Inspection 
<img width="401" alt="Screenshot 2021-10-06 at 18 33 14" src="https://user-images.githubusercontent.com/3928502/136245929-ea9c46a3-dda3-4046-9db6-9b27f923f6ee.png">

**Desktop (please complete the following information):**
 - OS: Last Release 1.8.2 - Mac OS Catalina

**Additional context**

**Comment by RoiArthurB** [comment]
@agrignard The fact that you're still on an old version of MacOS can be interesting. Can you first try to see which combinaison JDK/SWT works the best for you and report results in a comment on the dedicated issue ([here](https://github.com/gama-platform/gama/issues/3219)) please :)
