### ISSUE TITLE
Search tool model expansion 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3230]
**Is your request related to a problem? Please describe.**
As shown in the gif, when using the search box in model library, ones you type a key it will show you all the model with the occurrence, however if you just enter one letter it will expand all the model and when you go back to an empty field all the model stays expanded

**Describe the solution you'd like**
Going back to non expanded model library (like it does when typing more than one characters?)

![Screen Recording 2021-10-06 at 18 46 34 mov](https://user-images.githubusercontent.com/3928502/136248492-0aa243b5-16ec-4ad9-9d29-b0aa674a96db.gif)

**Comment by benoitgaudou** [comment]
tested and the fix works
