### ISSUE TITLE
ConcurrentModificationException when saving attributes of agents attached with driving skill

### ISSUE THREAD

**Issue by 3GFL** [gama-platform/gama#3234]
I've been dealing with the error - **2 occurrences in 2 agents at cycle X: Java Error: ConcurentModificationException** (image below).
This error occurs at different cycles. I spotted the line which is responsible for the error, but I didn't get why and how to overcome it. This happens in the move function when I try to export the agents' variables:

_reflex move when: the_target != nil {  
                    do drive;
                    my_road <- road closest_to self;
                    string file_name <- "../includes/output/drivers_" +_self.name_;
                    **_save "" + self.name + "\t" + model_time + "\t" + my_road.name+"\t"+ self.real_speed +"\t"+ self.objective  to: file_name+".csv" type: "text" rewrite: false;_**_ 
      
At first, that line was saving everything to one file (without the _self.name_ in defining the _file_name_). I thought that this was happening because of the parallelization - that two agents' variables tried to write them in the same file's line, so I make it saving to files for each agent individually (as it is shown above). However, I've still got it. The next clue was that specific attribute was responsible. So I tried to save only agents' name, still got it. Then I created a new reflex for exporting the attributes, didn't resolve it. This error usually happens after few created files.

The model is pretty much similar to the example in the library which demonstrates the functioning of advanced traffic. The timestep is one second.

I tried to run the model on 3 different computers. Two of them have windows10, a third one has centos OS. In all 3 cases, I used  version 1.8.1 with JDK.

![slika](https://user-images.githubusercontent.com/92312940/136820604-19a673a1-0904-45b9-9e66-b61d8385ba33.png)

EDIT/UPDATE: 
I tried to overcome the issue by storing all attribute values to a string variable, and exporting the variable every 30 minutes. However, I bumped into the same issue before 30 minutes in the model passed, so it was not cause of the export.

In global i defined a variables:

string model_output <-nil;
int minutes <- 0;

and created a reflex:

reflex export when: every(30#mn){
    minutes <- minutes + 30;
    string file_name <- "../includes/output/drivers_"+minutes ;
     save model_output   to: file_name+".csv" type: "text" rewrite: false;
     model_output   <-nil;
}
In reflex move i put:
model_output <- model_output  + "\n" +  self.name + "\t" + model_time + "\t" + my_road.name+"\t"+ self.real_speed +"\t"+ self.objective;

**Comment by AlexisDrogoul** [comment]
Any new development on this issue ?

**Comment by minhduc0711** [comment]
Forgot to close this, sorry! It was parallel scheduling that caused the error, since agents with driving skill need to execute sequentially.

@AlexisDrogoul Is it possible to get the value that option in `Preference` programatically, so I can print a more meaningful error?

**Comment by AlexisDrogoul** [comment]
The preference is accessible at `msi.gama.runtime.concurrent.GamaExecutorService.CONCURRENCY_SPECIES`.
