### ISSUE TITLE
GAMA mac dmg auto mounts

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#3237]
Hi

Then new mac dmg image auto mounts everyday and also after every restart. May be some small attribute must be modified while building the dmg image ?

**Comment by AlexisDrogoul** [comment]
Look first if you are not in that case: https://discussions.apple.com/thread/251893090

Otherwise, have you tried to (1) copy GAMA to Applications; (2) delete the .dmg file; (3) empty the trash ?
