### ISSUE TITLE
Chart is skewed with multi-simulation and layout splitted.

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3239]
**To Reproduce**
1. Launch this simple model:
```
model test
global {
	int soca <- 0;
	int death <- 0;
	int reco <- 0;
}
experiment test type: gui {
	action _init_ {
		create simulation number:2;
	}
	output {
		layout #split navigator: false consoles: false;
		display "states_evolution_chart" {
			chart "Population epidemiological states evolution" { 
				data "F0" value: soca * 100 color: #red marker: false thickness: 5;
				data "Death" value: death * 100 color: #black marker: false thickness: 5;
				data "Recovered" value: reco * 100 color: #blue marker: false thickness: 5;
			}
		}
	}
}
 
```
2. The 2 chart shown, but one of them is skewed 
![image](https://user-images.githubusercontent.com/6105384/137771105-e9a581ae-d7b3-4104-8bd0-aafd9930d5c5.png)

**Expected behavior**
Not skewed

Gama git 1.8.2,
windows 11 dev.

**Comment by AlexisDrogoul** [comment]
Does a resize readjust the second display ? I'm sorry, I can't reproduce it on my computer.

**Comment by hqnghi88** [comment]
No sir, it is a clean build. Here is my prefs
[gama.zip](https://github.com/gama-platform/gama/files/7369436/gama.zip)

**Comment by AlexisDrogoul** [comment]
OK. I can reproduce exactly your findings under Windows 11. Scale at 100%, no problem; scale at 200%, the second display is enlarged. What is funny is that for 3, 4, 5, 6 screens, it is always the last screen that ends enlarged like this.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 does it occur with OpenGL displays (with and without the `use_native_opengl_window` flag set to true) ? does it occur without multi simulation (i.e. with several displays in one simulation) ? Both answers are false in my case, but I want to be sure we are addressing the same issue...

**Comment by hqnghi88** [comment]
Sorry, i missed with other issue about opengl. So i confirm that opengl display dont have this issue (w/wo -Duse). But it occurs in a simple java2d display (1 display, without layout, nor multi simulation).

**Comment by AlexisDrogoul** [comment]
OK. thanks. And with 2 or more displays, same ? The last one always exhibits the problem ?

**Comment by hqnghi88** [comment]
I tried :
- 1 simulation with 4 displays without layout: all displays (stacked, no splitted) have issue.
- 1 simulation with 2 displays with `layout split`: the second have issue
- 1 simulation with 3 displays with `layout split`: no issue 
- 1 simulation with 4 displays with `layout split`: no issue

**Comment by hqnghi88** [comment]
The charts or display are not scaled anymore, they are in the original resolution even if system scaling are 200%. So , the text in chart  are very small, comparing with other element 
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/6105384/159171243-563bb7a7-ea29-489f-82c0-23f26f975be8.png">

**Comment by hqnghi88** [comment]
Sorry, it was 150% of system, if i increase to 200%, it is better
![image](https://user-images.githubusercontent.com/6105384/159171300-932cde67-4886-46cd-9a8f-9e5afc0b059c.png)

**Comment by hqnghi88** [comment]
I close this issue, as it was fixed, there no wrong skew causing miss-presentation of charts.
