### ISSUE TITLE
Experiment do not start when a constant value is used in a min or max facet

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#3243]
**Describe the bug**
It is impossible to launch an experiment (button does not respond at all) if a variable is defined with a min or max facet using a constant variable. 

**To Reproduce**
1. Go to any model
2. Copy past those two lines 
      ``float dum_epsilon <- 1^-6 const:true;``
     ``float dum_int_param <- 1.0 min:dum_epsilon max:1.0;``
3. Hit any experiment button
4. Nothing happen

**Expected behavior**
Either a warning or error mentioning a bad use of constant variables in facets or to make the experiment work 

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: tested with 1.8.1 release and git branch 1.8.2

**Comment by benoitgaudou** [comment]
I tested on Bubble Sort  3D.gaml model (adding the 2  lines in the global).
And  I am able to launch the experiment.
