### ISSUE TITLE
Layer split in z when updating the display (or pressing esc)

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3245]
**Describe the bug**
Again a very weird visual bug/issue  where just pressing ```esc``` or inspecting an agent  split the layers in Z...

**To Reproduce**
I didn't find a way to reproduce it on one of the model library but it is happening in the following model 
1. Clone this repo https://github.com/VCityTeam/UD_ReAgent_ABM
2. Import ReAgent in GAMA
3. Run ```load OSM```from OSM File Import.gaml
4. Press esc to go tu full screen

**Expected behavior**

**Screenshots**
![Screen Recording 2021-10-27 at 10 14 50 mov](https://user-images.githubusercontent.com/3928502/139027370-80d155dd-e581-4d29-88a9-849b0a269729.gif)

**Desktop (please complete the following information):**
 - OS: Catalina
 - GAMA_1.8.2_Alpha_withJDK_Mac_10.10.21_b2cae38f

**Comment by benoitgaudou** [comment]
I  just tried on the last Git version and do not have the layer split in fullscreen.
So  I guess it is fixed.


<img width="1680" alt="Screenshot 2021-11-25 at 12 14 31" src="https://user-images.githubusercontent.com/1555274/143431675-bba4fd8f-2736-4965-86c4-f99846f1cd41.png">
