### ISSUE TITLE
Still experiencing the seed issue as in #3242 with 1.8.2

### ISSUE THREAD

**Issue by gitting-around** [gama-platform/gama#3246]
Hi, I tried with the pre-release, and I get the same issue for multiple agents as in issue #3242. Could you perhaps try again on your side, more details on how to change the number of agents is in a reply for #3242.

**Comment by AlexisDrogoul** [comment]
Hi,

I'm sorry, but I am not completely sure of what you are describing as an issue here. Would it be possible to have a very simple model where you can reproduce the problem ? Does it happen during the simulation ? Between simulations ? I've browsed your files but I do not know what result I should be looking at.

**Comment by AlexisDrogoul** [comment]
One question (important) : did you have the preference "Make species schedule their agents in parallel" set to `true` or `false` ? 

![Monosnap 2021-11-04 00-42-09](https://user-images.githubusercontent.com/579256/140163378-915b1863-4d66-443c-a3d2-a75bea4d6df2.png)

In order to guarantee the reproducibility of simulations, this setting must be set to `false` (as, otherwise, the management of the threads will introduce a random sequencing that we cannot control).

**Comment by gitting-around** [comment]
Hi,

Sorry for the late reply. I will check the schedule thing now, and get back to you. I will describe the case better if still needed after this check.

**Comment by gitting-around** [comment]
Hi,

Yes it was set to false. I even set the nr of threads to 1. See pic:
![Screenshot 2021-11-04 at 17 30 01 (2)](https://user-images.githubusercontent.com/11443476/140380245-50b03042-f262-4af4-a9aa-e5376af53460.png)

I made the logging a bit clearer, for a simulations with 10 agents. Basically I am printing the cycle, the seed, the name of the agent, the rng_value, and location in that part where I call the wander function. I expect, given the same seed, the logging produced to be the same. It is possible to see that both simulations start the same, but by cycle 2 they start diverging, e.g. in the attached files [16.0_log_a.txt](https://github.com/gama-platform/gama/files/7476552/16.0_log_a.txt) for simulation 1 [16.0_log_b.txt](https://github.com/gama-platform/gama/files/7476553/16.0_log_b.txt) for simulation 2, keeping the same seed. It starts at line 108, where the rng_usage is not the same anymore between the two logs at the same step (each log -- one separate simulation).

I am re-attaching the sample project, with hopefully logging that is more comprehensible.
[models.zip](https://github.com/gama-platform/gama/files/7476573/models.zip)

I wonder if it has something to do with the convoluted structure of the project? Maybe the random number generator is used somehow in between.

**Comment by gitting-around** [comment]
Hej, any news on this? Can you reproduce the issue on your side the new files?

**Comment by benoitgaudou** [comment]
Dear,
I just tried on the last GIT version.
I launched the _main.gaml file, run for 10 steps.
And I get  that 2 executions of  the simulation provides the exact same result.

**Comment by hqnghi88** [comment]
@benoitgaudou i launch particle (the message in his log is written in that model so i think particle is the one he mentionned). 
I got 2 different file: seem identical at beginning but then we have different value of rng_usage and the location

**Comment by benoitgaudou** [comment]
I  tried to launch particle too (but it is  the  same experiment as in _main.gaml).

I tried 2 launches:
- 10 cycle step by step and closing the simulation at the  end
- 100 cycles  in a "normal" launch.

Result:
- the 10 step-by-step are identical until the end (cycle 10).
- in the 100 steps file, I  get a difference  from the step 2 ...

Here  are the files
[16.0_log_a_100_2.txt](https://github.com/gama-platform/gama/files/7602687/16.0_log_a_100_2.txt)
[16.0_log_a_10_1.txt](https://github.com/gama-platform/gama/files/7602684/16.0_log_a_10_1.txt)
[16.0_log_a_10_2.txt](https://github.com/gama-platform/gama/files/7602685/16.0_log_a_10_2.txt)
[16.0_log_a_100_1.txt](https://github.com/gama-platform/gama/files/7602686/16.0_log_a_100_1.txt)

so my last try was to run in step-by-step mode until step 100.
Result: I have identical output files.
[16.0_log_a_100_stepBytep_1.txt](https://github.com/gama-platform/gama/files/7602706/16.0_log_a_100_stepBytep_1.txt)
[16.0_log_a_100_stepBytep_2.txt](https://github.com/gama-platform/gama/files/7602707/16.0_log_a_100_stepBytep_2.txt)

**Comment by hqnghi88** [comment]
it take me 10 mins to read the paragraph "functions of functions of functions....". Thanks Benoit for 100-step-clicking x 2 , also.

**Comment by gitting-around** [comment]
Thanks for this! I will follow your recommendation :).

**Comment by AlexisDrogoul** [comment]
In a general comment to this, I would like to underline that, although a number of precautions have been taken is separating the processes, it is an example where graphical outputs can have an impact on the execution of simulations, which is an issue. There are many ways to fix this: one is to use a separate random number generator for everything related to outputs, the other one is to use the RNG of the experiment in outputs (rather than the one of simulations). Thanks @gitting-around (Gita) for reporting this ! I'm gonna close this one and open a new request for enhancement based on these findings.
