### ISSUE TITLE
Difference between GAMA 1.8.1 and 1.8.2 on CityScope reading

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3249]
**Describe the bug**
On 1.8.1 we developed a version of GAMA being able to read from a URL a CityScope table. It used to works fine on 1.8.1 but it doesn't anymore on 1.8.2. It shouldn't be a big deal and I could change the gaml code itself however but it might important to keep the retrocompatibility so that ideally the same code  run on 18.1 and 1.8.2.

So this is the original grid
<img width="346" alt="Screenshot 2021-11-17 at 14 27 05" src="https://user-images.githubusercontent.com/3928502/142209421-178a26da-fb8e-49a7-9923-3b94b834a744.png">

This is how it looks (OK) on 1.8.1
<img width="768" alt="Screenshot 2021-11-17 at 14 27 00" src="https://user-images.githubusercontent.com/3928502/142209455-92ba2f76-27d7-4358-b324-384c2de6fc67.png">

And I just discover by realiving this project that it's not looking ok on 1.8.2
<img width="779" alt="Screenshot 2021-11-17 at 14 26 44" src="https://user-images.githubusercontent.com/3928502/142209527-7c68f560-d7ac-40e0-99cf-dd8708945995.png">

**To Reproduce**
1. Clone this repo https://github.com/CityScope/CS_GAMABrix
2. Import GamaBrix
3. Run cityIO.gaml experiment ```CityScope```

**Expected behavior**
Same for 1.8.1 and 1.82

**Desktop (please complete the following information):**
 - OS: MAC OS

Also reported here
https://github.com/CityScope/CS_GAMABrix/issues/9

**Comment by agrignard** [comment]
Here is a GIF showing the same code running on 1.8.1 (working) and 1.8.2 (not working). What we see is that the id of the brix seems coherent in 1.8.1 going from 0 to 19 on the first line then 20 to 39 and so on.

However on 1.8.2 the order is kind of weird, I don't actually see the logic.

here is the gif that I hope will help to find the issue 

![yo mov](https://user-images.githubusercontent.com/3928502/142234555-e792854b-40cd-49e7-addc-9b6a2ddf22a6.gif)

**Comment by ptaillandier** [comment]
It is due to the order of the geometries import from the Geojson file (geogrid). No idea why (new version of geotools?) , but it is not very important, you can just order the geometries before creating the agent:
First, you can specify the type of the geojson file in the global section:
`geojson_file geogrid;`
	
The in the initializd_brix action, just order the geometries according to their location.
```
action initialize_brix {
		float coeff <- world.shape.perimeter;
		list<geometry> orderd_geom <- inverse_xy? geogrid.contents sort_by (- each.location.x  - coeff * each.location.y) : geogrid.contents sort_by ( coeff * each.location.x + each.location.y) ;
               create brix from:orderd_geom with: (name:nil);
		
...
	
```

**Comment by agrignard** [comment]
Great! Thank you for the trick! So it works both on 1.8.1 and 1.8.2. Now the question is why there is a difference between 1.8.1 and 1.8.2, certainly a different geotools version with the new one not reading the geojson in the same order...
