### ISSUE TITLE
support discrete event simulation

### ISSUE THREAD

**Issue by litingzhen** [gama-platform/gama#3252]
Can gama provide a new control architecture to support discrete event simulation?
If I want develop a plugin for this, please give me some tips.

**Comment by chapuisk** [comment]
Dear @litingzhen,
There is a template to issue request for enhancement in this github repository. Please consider using it, improving a bit your issue and resend it.
You may also consider using the mailing list first, which might be a better call, if you have broader scope issues and question, like what would be the steps toward DES in Gama. This will allow developers and other users to exchange on this topic.
Best
