### ISSUE TITLE
Error in the Predator Prey tutorial.

### ISSUE THREAD

**Issue by Maro1F431** [gama-platform/gama#3253]
In the second part of the Predator Prey tutorial, inside the display code block example (https://gama-platform.org/wiki/PredatorPrey_step2#display) the "border" facet is used. It seems like this facet is deprecated and "lines" should be used instead.

**Comment by benoitgaudou** [comment]
Dear,
Thank you for the remark!
The code is in fact still in line with GAMA 1.8.1 (the official release).
We will change it when the new version (1.8.2) will be released.

**Comment by AlexisDrogoul** [comment]
Thanks for pointing this. The tutorials will be soon updated.
