### ISSUE TITLE
Library, Plugin and test Models empty 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3258]
**Describe the bug**
Certainly not an issue and maybe due to the use of Catalina (but I prefer to report it just in case)

After downloading the last release (GAMA_1.8.2_MacOS_with_JDK_11.29.21_645eef43.dmg) When launching GAMA (with a new workspace) I am not able to load any model (Buildign Workspace progression bar goes to 100% but the models don't show up)

**Screenshots**
<img width="1440" alt="Screenshot 2021-12-07 at 13 10 39" src="https://user-images.githubusercontent.com/3928502/145027052-70aef522-ed2b-4606-bcc6-bf1f26160127.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina (maybe that's the issue)
 - GAMA version: GAMA_1.8.2_MacOS_with_JDK_11.29.21_645eef43

**Comment by RoiArthurB** [comment]
Reproduced on Linux. But everything appeared normally if closing and restarting GAMA once the new workspace has been created

**Comment by agrignard** [comment]
Ok same for me indeed after a restart (cmd+Q + restarting GAMA with the same workspace) I can see the model

**Comment by hqnghi88** [comment]
No idea why it happens . it seems some corruption/error in loading models/caches for the first time? @RoiArthurB can you reproduce it with local build?

**Comment by RoiArthurB** [comment]
@hqnghi88 Strangely, when I create a new workspace with GAMA from Eclipse, the workspace doesn't refresh (screen loading stuck at 0%, but GAMA works fine). And restarting GAMA doesn't fix anything :/

![image](https://user-images.githubusercontent.com/16764085/145517027-7106752b-f9e0-480b-8a41-a63595065203.png)
