### ISSUE TITLE
Operator `corR` launch an error 

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#3260]
**Describe the bug**
When using `corR` operator to assess Pearson's correlation coefficient, an error is launch by Gama. The error says that Gama is not able to fund the RCaller library

**To Reproduce**
1. Go to any model
2. use `corR` operator, e.g., `corR([1,2],[4,8])`;
3. See error

**Expected behavior**
Either drop `corR` (alias `R_correlation`) to only use `correlation` from the cern stat API or fix the error

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: 1.8.1 and git version 1.8.2

**Comment by sriramab** [comment]
This is not supposed to work since the introduction of Rjava plugin. I do not think anybody is maintaining it ! @chapuisk 

May be @hqnghi88  should remove it. 

If you wish to use R, the supported method is to you Rjava plugin by @benoitgaudou and @hqnghi88. I have this covered in one of my youtube video

**Comment by chapuisk** [comment]
Dear @sriramab my intention was not to use R, but native statistical tools ... however, I can see that some of them are based on Rjava somehow. The point goes beyond this particular issue. For instance, we have 2 files (Stats and Stats2) in package ummisco.gaml.extension.stats with duplicates operators (e.g. kurtosis) based on different resources.

**Comment by AlexisDrogoul** [comment]
Am I allowed to remove these operators ? for these simple operators, I really do not see the point of using R.

**Comment by hqnghi88** [comment]
Dear Alexis,
Please, remove it, thank you very much.

**Comment by chapuisk** [comment]
'correlation' operator works properly and 'corR' has been removed so this issue too
