### ISSUE TITLE
Network generation without edge (and node) species is broken

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#3262]
**Describe the bug**
When networks are generated without specifying the species for edges, Eclipse launches different types of error, depending on the generator used. Tested with random and scale-free generator.

**To Reproduce**
1. Go to Graph.gaml in GAML Syntax library model forlder
2. Launch the experiment
3. Choose Random or Scale-free generator (should be the same for Small-world and Complet)
4. Create the graph => works fine
5. Turn either "node_species_only" or "no_species" to true
6. Create the graph => through error

**Expected behavior**
Makes it possible to use generator without specifying the species of edges and nodes.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: git 1.8.2

**Comment by AlexisDrogoul** [comment]
The problem is that when you create a graph without a species, the vertices are not shapes/agents by default. So there is nothing to draw... hence the error.

**Comment by AlexisDrogoul** [comment]
To be more precise : it is not an issue, for me, if GAMA refuses to draw a non spatial/geometrical graph. What we could maybe provide is an operator, in that case, that would create a spatial graph from a non-spatial one : random points for the vertices, with the previous value as an attribute of this geometry, and links between them as the edges... `as_spatial_graph` would return the same graph if its argument is already a spatial graph...

**Comment by AlexisDrogoul** [comment]
I've created an experimental `as_spatial_graph` operator and modified `Graph.gaml` accordingly. Please test it when you have time !

**Comment by benoitgaudou** [comment]
I ve  just  tested,  and no error so I close.
