### ISSUE TITLE
get in creating agents from a csv_file returns nil

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3266]
When we create agents from a shapefile, we have two ways to access attributes from the shapefile:
- either using `read` in the facet with of the `create`
- or using `get`in the `create` body 
E.g.:
```
create zone_fine from: Zones_fines_CA_Albi0_shape_file with: [
	Z_Fines::string(read("Z_Fines"))
] {
	write get("Sec");
}
```

The point is that, when we want to create agents from a csv file, we can still use the `read`operator in the `with` facet, 
but the `get` in the body of the `create` always returns nil.

Is it an issue, a feature ? Should it be changed ?

**Comment by AlexisDrogoul** [comment]
You were right. This is a bug. I have committed a solution where, like in SHP files, extra attributes declared in CSV files are now copied to the agent attributes (as with SHP files) and accessible anytime during the agent lifetime (with `read` or `get`).

**Comment by AlexisDrogoul** [comment]
The problem has been solved as far as I can test and tell. Closing the issue now.
