### ISSUE TITLE
Error in 'generate' from a csv file

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3267]
**Describe the bug**
I tried to generate a population of agents with 2 attributes Age and Sexe, from a data table from the INSEE website.
I get the following error at the generation:

```
2 occurrences in 2 agents at cycle 0: Java error: illegal argument
in generate people number: 10000 from: [csv_file('../includes/INSEE-Sexe-Age.csv',';')] attributes:  ['Age'::['0 à 14 ans','15 à 29 ans','30 à 44 ans','45 à 59 ans','60 à 74 ans','75 à 89 ans','90 ans ou plus'],'Sexe'::['Hommes','Femmes']]  ;
IllegalArgumentException: To collapse matrices you must build at least one first: see the buildDataTables method
gospl.distribution.GosplInputDataManager.collapseDataTablesIntoDistribution(GosplInputDataManager.java:272)
espacedev.gaml.extensions.genstar.generator.FileBasedGenerator.manageRawData(FileBasedGenerator.java:215)
espacedev.gaml.extensions.genstar.generator.FileBasedGenerator.generate(FileBasedGenerator.java:156)
espacedev.gaml.extensions.genstar.statement.GenerateStatement.privateExecuteIn(GenerateStatement.java:182)
espacedev.gaml.extensions.genstar.statement.GenerateStatement.privateExecuteIn(GenerateStatement.java:1)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
in agents Simulation 0, AlbiPopGenStar0
```

**To Reproduce**
1. Launch the following model:
````
model minimal_gosp

global {
	init {	
		generate species:people number: 10000 
			from:[csv_file("../includes/INSEE-Sexe-Age.csv",";")] 
			attributes:[
				"Age"::["0 à 14 ans", "15 à 29 ans", "30 à 44 ans", "45 à 59 ans", "60 à 74 ans", "75 à 89 ans",  "90 ans ou plus"],
				"Sexe"::["Hommes", "Femmes"]
			];			
	}
}

species people {
	int Age;
	string Sexe;
}
````

with the csv file:
[INSEE-Sexe-Age.csv](https://github.com/gama-platform/gama/files/7761430/INSEE-Sexe-Age.csv)

I also tried with an extended file (with total lines and columns), with the same result:
[INSEE-Sexe-Age-full.csv](https://github.com/gama-platform/gama/files/7761431/INSEE-Sexe-Age-full.csv)

**Desktop (please complete the following information):**
 - OS: macOs big Sure
 - GAMA version: git, branch 1_8_2

**Comment by AlexisDrogoul** [comment]
@chapuisk any update on this one ?

**Comment by ptaillandier** [comment]
Normally it is fixed (fixed also the "too many 5-years old" issue) .... but understanding how Genstar works is very complex, thus I am not sure of the quality of my fixes. I let you test it.

**Comment by hqnghi88** [comment]
@chapuisk can you please take a look or should we count on the black magic (seems ok i tested with data in the original post)?

**Comment by chapuisk** [comment]
@hqnghi88 Patrick told me he solved it with "black magic", so let it be ;)

**Comment by hqnghi88** [comment]
Thanks, Yes, i am very and always faithful with black magic.
