### ISSUE TITLE
the image map does not coincide with the road vector 

### ISSUE THREAD

**Issue by litingzhen** [gama-platform/gama#3269]
Gama 1.8.1: 

Operation:
1) In QGIS, load the googlemap and a dem file.
2) Cut a rectangle region, size is 16KM*32KM, and export googlemap image(png format) and dem(asc format, 4326) of this region.
3) In gama, load the region's dem(asc format) and use it as the world.
4) In gama, at the "output" section, create a image layer using the region's image(png format)

Phenomenon:
1) In gama, mouse click the landmark of the satelite image, then use CRS_transform transform the #user_location to latitude and longitude, we find the result is wrong.
2) If load a route vector(shp format), we find the route vector and the route in satelite image are not fit. And, mouse click one point of the route vector, and use CRS_transform transform the #user_location to latitude and longitude, we find the result is right.

Question:
1) Is it possible to directly attach a large-scale image map to the world of gama? Although the four edge points of the image map are consistent with the world, the map has been deformed due to the different projection methods of the image map？
2）Is there any way to solve the above problem？

**Comment by ptaillandier** [comment]
Hi,

Is it possible to share the data + model to test with the latest version of GAMA?

**Comment by lesquoyb** [comment]
closed for inactivity
