### ISSUE TITLE
Problems with QGIS shapefiles 

### ISSUE THREAD

**Issue by BenRuss** [gama-platform/gama#3270]
Dear everyone,

this is my first bug report. I'm currently attending a course at the University of Salzburg/Austria (UNIGIS professional). In one of our assignments we had to use our own GIS data within an existing GAMA-model. After days of struggling to make it work I contacted my professor and we came to the conclusion, that the problem seemed to be a software related bug in GAMA 1.8.1. Now I hope I am not wasting anyone's time. Here we go: 

**Describe the bug**
I have a GAMA-model to simulate segregation. When loading a shapfile into this model it will not be built up correctly. Even though GAMA is depicting the shapefile correctly before executing the script (screenshot_01), all polygons within the shapefile will be stacked upon each other once you execute the experiment (screenshot_02).

![screenshot_01](https://user-images.githubusercontent.com/96590634/147279963-b5b85488-0276-4ef4-92af-1bf1e842285b.png)
_screenshot_01_

![screenshot_02](https://user-images.githubusercontent.com/96590634/147275603-1c57c772-e1c3-477f-a935-a067200781b9.png)
_screenshot_02_

This only happens when the shapefile was exported with QGIS. When exported with ArcGIS Pro the problem doesn't occur. I tried different projections, I tried to insert the "type" facets (opengl, java2D). I also checked my preferences which you can see here:

![screenshot_03](https://user-images.githubusercontent.com/96590634/147280915-96f32eab-202b-404d-80d7-5c99d75f73d9.png)
_screenshot_03_

**To Reproduce**
This is the model code:
[model segregation.docx](https://github.com/gama-platform/gama/files/7770760/model.segregation.docx)

Here is the data I'm working with:
[GitHub bug.zip](https://github.com/gama-platform/gama/files/7770776/GitHub.bug.zip)

Within the folder there is the GeoJson-File that I exported from OSM as my GIS data. You can use it to reproduce the shapefile in QGIS/ArcGIS yourself. I also included the two shapefiles I exported, both georeferenced (EPSG:31464):

giesing_DHDN (-> QGIS shapfile)
giesing_arcgis (-> ArcGIS shapfile)

Insert the shapefiles into the code at the following line:

``
file shape_file_name <- file ("../gis/giesing_DHDN.shp") parameter: "Shapefile to load:" category: "GIS specific";
``

Then execute the experiment. 

**Expected behavior**
What should happen after inserting the shapefile and executing the experiment is that the polygons should be distributed according to their distribution irl as shown in the following screenshot:

![screenshot_04](https://user-images.githubusercontent.com/96590634/147277429-afc3a0fb-8646-4297-9692-ac390fce1e86.png)
_screenshot_04_

But when inserting a shapefile that is exported with QGIS, it will produce the above mentioned error. 

**Desktop:**
 - QGIS version 3.14.15-Pi
 - ArcGIS Pro 2.7.2
 - OS: Windows 10
 - GAMA version: 1.8.1

Let me know if you have any further questions or need anything else to reproduce the bug. Thanks for all your work and I hope I can contribute a little with this bug report :)

**Comment by ptaillandier** [comment]
Very interesting issue, that is not really an issue, but due to your data :) 

It took me a little while to understand the difference between the two shapefiles: it is absolutely not related to geometries or projections, but simply to attributes. In the DHDN file, there are many more attributes, including an attribute called "location" of type string. However, one choice in GAMA is to automatically read the attributes of the shapefile that have the same as an attribute to set the value of these attributes. And every agent has an attribute called "location" (location of the agent - of its centroid). So, GAMA creates the agents with the right geometries, but in the case of the DHDN file, it will then replace the location value by what it will find in the shapefile (as it is a string, it will translate this by the {0,0} coordinate). If you change the name of the location attribute (or delete it) in the shapefile, it will work normally.

**Comment by AlexisDrogoul** [comment]
Maybe we should propose this (ie reading directly the attributes) as an option ? It would be a bit complex in some cases, but worth it if `location` is an attribute automatically added by QGis. Or, at the very least, make sure that we can decode these strings if they are also standard in QGis. 
Forget this comment if the `location` attribute is specific to the project.

**Comment by BenRuss** [comment]
@ptaillandier haha, I'm glad it wasn't a boring "issue". I wasn't aware of the difference you are mentioning. At least now others who might face the same problem have a way to get past it. Thank you for your work!! Appreciate it <3

@AlexisDrogoul I don't think that this "issue" is specific to my project. There were several people in my class with the same problem so it has something to do with QGIS. This issue might even come up with other QGIS-shapefiles. I will contact Anita Graser. She is also teaching in Salzburg and one of the lead developers at QGIS. If you want to contact her yourself, here's her website: https://anitagraser.com/

Thanks again everyone!
