### ISSUE TITLE
dynamically create grid for local region

### ISSUE THREAD

**Issue by litingzhen** [gama-platform/gama#3274]
Now the grid will auto create at the start of the simulation for the whole world.  In my situation,  the world is too large , and in the simulation, I need create a local grid with small size near my movable agent,  and use this grid to navigate(avoid local obstacle). 

How can it be achieved, please give some instructions.

**Comment by AlexisDrogoul** [comment]
Hi,

This is not a bug nor a precise request for enhancement, so I would suggest that you ask this question either on the mailing-list (forum.gama-platform.org) or in the discussions on this site (https://github.com/gama-platform/gama/discussions). Thanks !
