### ISSUE TITLE
Batch experiments do not launch on linux with Gama1.8.2 

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#3275]
**Describe the bug**
Not any batch experiment can be launched 

**To Reproduce**
1. Go to library models > model exploration > Batch simulation > Batch.gaml
2. Click on any experiement button
4. See error no error, no simulation

**Expected behavior**
experiment should be launched or an error triggered

**Desktop (please complete the following information):**
 - OS: Linux (Kubuntu 21.10 updated)
 - PC Model: 64bit
 - GAMA version: gama git 1.8.2 (same with jdk17 branch)
 - Java version: openJDK 16 and JDK17

**Comment by RoiArthurB** [comment]
GAMA git on branch `GAMA_1.8.2` officially run on the JDK 15, can you manage to test this JDK first please ? :)

**Comment by AlexisDrogoul** [comment]
@chapuisk, is it still happening ? This behaviour is very surprising, especially if no graphical environment is involved...

**Comment by chapuisk** [comment]
As pointed out by @RoiArthurB this was because of the JDK version. Now that I move back to 17 it is ok. Still need to test with JDK17 now that 1.8.2 has bump to this version
