### ISSUE TITLE
OpenGl display shows artifacts with certain camera configurations

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#3279]
**Describe the bug**
When using an opengl display with camera_location and camera_target facets having similar values for x and y, the display does not show what was intended but insteaded some kind of artifacts. It goes back to normal as soon as the camera position moves.

**To Reproduce**
```
model TestBugOpenGl

experiment exp {
	
	output{
		
		display test type:opengl camera_location: {100,100,100} camera_target: {100,100,0} {}
	}
}
```

what is displayed :
![image](https://user-images.githubusercontent.com/6374469/149277150-5a8668a3-b038-4fc9-9a3a-fdae6f2f9382.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/6374469/149277674-d408753f-c527-4d38-b792-437a7afcf128.png)

**Desktop :**
 - OS: windows 11
 - PC Model: lenovo legion 5, ryzen 5 5600H
 - GAMA version: 1.8.2
 - Java version: 15 
 - Graphics cards / Display system: nvidia geforce RTX3060 laptop

**Comment by agrignard** [comment]
I am bit concerned by this issue as currently it's impossible to set a camera position , thus impossible to use GAMA on a physical interface where the camera position is a key feature to setup correctly the projection 

As this facet use to work for a while, do we have an idea of the reason why it's not working? Is it something related to OpenGL? Or the facet ````camera_position```` that is not well recognized in GAMA?

Currently the possible workaround are:
- the keystone could emulate the camera position feature but not in every use case (typically if you need to enlarge your display the keystone is not an option)
- Playing with the bound of the world to emulate a "zoom"

**Comment by AlexisDrogoul** [comment]
There was  an issue when values of upVector were completely aligned with the "lookAt" vector (position - target). Please test !

**Comment by lesquoyb** [comment]
Yes it works now
