### ISSUE TITLE
Keystone combined with rotate facet problem

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3285]
**Describe the bug**
I am actually working on a physical table i just discover that combining a keystoning while defining a rotate:180 in the display is very confusing. The keystone is not beaving the same and pretty weirdly. In my opinion that fact that the display is rotate shouldn't impact on the keystoning itself.

In my case I have to do a rotate:180 because I cannot set the projector to display a 180 image.

**To Reproduce**
define rotate:180 in a display and press K (also the value of the Keystone doesnt show up)

**Comment by AlexisDrogoul** [comment]
I've committed a fix. rotateModel() was actually called outside of the main drawing loop and was basically trying to rotate the keystone frame, which is wrong (it is the scene drawn inside the keystone frame that needs to be rotated). Fix to be tested of course.
