### ISSUE TITLE
Problem when reading a csv file

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#3289]
**Describe the bug**
GAMA have some issue to read some csv file (with a date?).

**To Reproduce**
1. Import the attached model
2. Load it

The variable data is null after reading the file. Note that if I use:
csv_file data <- csv_file("../includes/meteo_INSEE_27507_2006-2019.csv");

GAMA is able to read the file, but "cast" the first column as a float (csv_file data <- csv_file("../includes/meteo_INSEE_27507_2006-2019.csv",string) does not work either).
		

[csv_file import.zip](https://github.com/gama-platform/gama/files/7923635/csv_file.import.zip)

**Comment by AlexisDrogoul** [comment]
Isnt'it fixed by d3f3b5b467c2df5bdc584b2efe8c22fb8cfddcb9 ?

**Comment by ptaillandier** [comment]
It works !!! Thanks 👍
