### ISSUE TITLE
Potential limitation on the size of a UDP message

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3295]
**Is your request related to a problem? Please describe.**
I am working on a project with a model that is fetching UDP message coming from a python script. I have realized that the strings I received was longer than 256 characters (around 1024 characters) so I couldn't read and process the entire message in GAMA. I was wondering if this is a limitation from GAMA

**Describe the solution you'd like**
Would it be possible to set the size of the UDP package and ideally increase it? I am not sure if UDP is meant to send longer message and there is maybe a reason why we limit this size.

**Comment by AlexisDrogoul** [comment]
In the Plugin Models library, the file `UDP Listener Mouse from Processing For camera.gaml` (that you have written yourself, by the way !) contains the following connection code: 
`do connect to: url protocol:"udp_server" port: port size_packet: 1024;	`
Have you tried tweaking the last parameter ?

**Comment by agrignard** [comment]
Ok good to know I didn't remember this facet so maybe that can solve the issue. and maybe by default it is set to a lower value. I will do more test on this

**Comment by lesquoyb** [comment]
@agrignard Have you tested it yet ? It would be nice to know if there is a real bug or not as we are moving toward a stable 1.8.2

**Comment by hqnghi88** [comment]
I close this, as i tested (and i remember who implemented that facet). Feel free to reopen or create new issue related
