### ISSUE TITLE
Error launching GAMA 1.8.2 after installing argumentation plugin

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3301]
**Describe the bug**
I installed the argumentation plugin from help as normal, but an error now occurs in launching GAMA. It does not start. I don't know if this problem is only with me or a bug.

**To Reproduce**
1. Install argumentation plugin
2. GAMA will ask to restart. But whenever we try to start it, an error appears.
I have attached the log file of the error for your consideration

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GAMA version: [1.8.2 with JDK release 25/1/2022]

**Additional context**
The log file of the error:
[1645101644695.log](https://github.com/gama-platform/gama/files/8088679/1645101644695.log)

**Comment by hqnghi88** [comment]
Sorry for the inconvenient, if i remember, the 1.8.2 alpha is based on jdk17 and the experimental plugins (include argumentation) are still link with 1.8.2 alpha java 15. I will re-deploy new version of these plugin , soon, today

**Comment by Aya-Badawy89** [comment]
Yes, it is fixed. Thank you very much. I will close the issue
