### ISSUE TITLE
[ENHANCEMENT] Add warning if a file is imported several times

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#3302]
**Is your request related to a problem? Please describe.**

In big project, it's easy to import several times a same file and make the whole project messy (cf. slide below where 129 imported files created 1088 import lines, but could be factorized in only 232 import lines).

![image](https://user-images.githubusercontent.com/16764085/154616293-ea497d73-d44b-4de9-8f80-0e81b411ce97.png)

**Describe the improvement you'd like**

It would be great if, like in Eclipse IDE below, GAMA warns if a file is already imported by another file in the project.

![image](https://user-images.githubusercontent.com/16764085/154617143-c7ffb1da-d5c2-4d9a-95a3-4b2fca8c7a06.png)

**Comment by RoiArthurB** [comment]
I understand and, in the Eclipse implementation, it is also displayed as a hint and not as a warning :)

**Comment by AlexisDrogoul** [comment]
OK. Enhancement provided as far as I can test it (in Comokit, for instance).
