### ISSUE TITLE
Warning when a shapefile contains a location column

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3305]
**Is your request related to a problem? Please describe.**
Let's consider the following  shapefiile.
[Archive.zip](https://github.com/gama-platform/gama/files/8115724/Archive.zip)

It contains a column named "location",  with only  NULL value.

When used to create agents in a model, all the  agents are located on {0,0}, as it takes the value of the location column in order to initialize the "location" attribute.

**Describe the improvement you'd like**
A least a warning  should  be triggered to inform the modeler that  all the agents have been created with the location iniitialised to NULL / {0,0}

**Comment by AlexisDrogoul** [comment]
I find it difficult to do it in the compilation of the model. In the meantime I have added a small addition to the navigator to ease the exploration of shape files : 

![New Model gaml - Gama (runtime) 2022-03-10 17-43-02](https://user-images.githubusercontent.com/579256/157645623-3dada613-686b-4ec7-ae3b-70c970028d39.png)

With that we can have an instant access to the names of the attributes. One possibility, then, could be, here, to indicate the attributes that correspond to built-in variables in GAMA. What's your opinion on this ?

**Comment by AlexisDrogoul** [comment]
Implemented: built-in attributes should now be signalled in red in the navigator.
