### ISSUE TITLE
Multiple Raster Files Import Error

### ISSUE THREAD

**Issue by litingzhen** [gama-platform/gama#3306]
**Describe the bug**
Using 1.8.1, run msi.gama.models/models/Data/Data Importation/models/Multiple Raster Files Import.gaml, "Java error: index out of bounds" occurs.

**Desktop (please complete the following information):**
 - OS: [windows10]
 - GAMA version: [1.8.1]
 - Java version: [1.8]

**Comment by AlexisDrogoul** [comment]
The bug you observed has been fixed in the 1.8.2 branch. I'm afraid it will not in 1.8.1. 
It manifests itself when the first file of a series of grid files (ASC or TIFF) has no CRS / Projection references. So the only workaround in 1.8.1 is to geolocalize and reference the first file.

**Comment by AlexisDrogoul** [comment]
Bug has been fixed as far as I know. Please reopen if it still occurs.
