### ISSUE TITLE
EulerSolver gives Infinite value in certain cases

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#3312]
**Describe the bug**
Running the model `Influence of the integration method (LV).gaml` from the plugin models library raises a Java error :

```
1 occurence in LVEuler0 at cycle 130: Java error: exception in Math library
in solve eqLV method: #Euler step_size: h ;
NotANumberException: NaN is not allowed
ummisco.gaml.extensions.maths.ode.utils.solver.Solver.lambda$0(Solver.java:115)
ummisco.gaml.extensions.maths.ode.statements.SystemOfEquationsStatement.executeInScope(SystemOfEquationsStatement.java:533)
ummisco.gaml.extensions.maths.ode.utils.solver.Solver.solve(Solver.java:86)
ummisco.gaml.extensions.maths.ode.statements.SolveStatement.privateExecuteIn(SolveStatement.java:335)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:440)
msi.gama.runtime.IScope.execute(IScope.java:568)
in agent LVEuler0
```
At some point (step 129) the solver for the Euler's method seems to give "infinity" as a value for x and y which results in the `solve` method from the `Solver` class to throw a NotANumberException and the simulation to stop.

**To Reproduce**
1. run the simulation of the `Influence of the integration method (LV).gaml` until step 130

**Expected behavior**
The solver doesn't throw an exception 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GAMA version: git
 
**Additional context**
I tried to reproduce the original euler's method steps with the initial data of the experiment, but I had different values than the simulation for x and y at the first iteration, so maybe there is something to investigate here (or maybe I'm just bad at math).

**Comment by benoitgaudou** [comment]
I guess that it is not impossible that one of the population in LV
model tends to reach an infinity value , as we can have  a kind of
exponential growth of one population when the other one is very small and
does not influence it.

Nevertheless, I tested several values for the parameter h, and even with
quite small values of h, I was surprised that Euler does not provide better
results...

Si I do not know whether  this is really  a  bug  ...

Benoit

Le lun. 7 mars 2022 à 17:46, HUYNH Quang-Nghi ***@***.***> a
écrit :

**Comment by AlexisDrogoul** [comment]
In my opinion it is not really a bug, but part of the "normal" behaviour of Euler's methods.

**Comment by lesquoyb** [comment]
I do not know if there is a bug or not in implementation of Euler's method, but a model given as an example for the plugin shouldn't crash in my opinion.

But to go a bit further in the bug hypothesis :
If we take the data of the model:
Adding the line `write "cycle:" + cycle + " x:" + x + " y:" + y + " alpha:" + alpha + " beta:" + beta + " delta:" + delta + " gamma:" + gamma + " h:" + h;` just before the `solve` line in the `solving` reflex gives me this:
```
cycle:0 x:2.0 y:2.0 alpha:0.8 beta:0.3 delta:0.85 gamma:0.2 h:0.1
cycle:1 x:2.693753112593424 y:1.331525857026177 alpha:0.8 beta:0.3 delta:0.85 gamma:0.2 h:0.1
```
So the initial data are:
```
x(0)=2
y(0)=2
alpha = 0.8
beta=0.3
delta=0.85
gamma=0.2
h=0.1
```
and the derivative of x and y are described by:
```
diff(x,t) =   x * (alpha - beta * y);
diff(y,t) = - y * (delta - gamma * x);
```
if I understand correctly Euler's method we should have for the first step:
```
x(0+h) = x(0)+h*x'
x(0+h) = 2 + h * (x(0) * (alpha - beta * y(0))
x(0+h) = 2 + h * (2 * (0.8 - 0.3 * 2)
x(0+h) = 2 + h * 0.4
x(0.1) = 2.04
```
but the value given by the solver for the first cycle is 2.69.... which is quite different from the expected value

So is it me that didn't understand what should have happened or is there a problem in the model ?

**Comment by hqnghi88** [comment]
@Benoit Yes, it is not much better with smaller h, it s just slow down the appearance of Inf. But the document said that, it seem to be the worse integrator.
@Baptiste yes, and it easy to prevent the crash : pause at cycle 100 .
And wow, i have no skill to calculate that derivative,  i strongly request the best support from my best dear friend @tnguyenh ... :D

**Comment by benoitgaudou** [comment]
Hi,
If I  am right, after one step  on the GAMA  simulation, you will not do 1
step of integration,  but 1/h  so 10.
(not that this could  also depend  on the value of step;

Cheers

Bbenoit

Le jeu. 10 mars 2022 à 10:07, Baptiste Lesquoy ***@***.***> a
écrit :

**Comment by baptiste** [comment]
not me, thanks

**Comment by lesquoyb** [comment]
Ok it makes more sense if one gama cycle = 1/n steps of integration. So I just ran a small script to check 10 steps of integration and got exactly the same output as gama. So if we go for a try catch or just pausing the simulation I see no more bug here

**Comment by hqnghi88** [comment]
> not me, thanks

sorry, wrong tagging, my bad

**Comment by lesquoyb** [comment]
I tried a few more comparisons between the script and the model and saw no difference, also the fix proposed by @hqnghi88 works so I consider this issue closed. Thanks everyone
