### ISSUE TITLE
macOS: OpenGL display "hide" other displays

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3318]
**Describe the bug**
I run an experiment with 1 opengl display and 1 chart display (without display layout).
The 2 panes appears, but when I click on  the name of the display to switch display, only the OpenGL one is displayed.

**To Reproduce**
1. Run the Ant Foragin.gaml model, with the following experiment:
```
experiment "Classic" type: gui {
	output {
		display Ants type: opengl synchronized: true antialias: false  {
			light #ambient intensity: 127;
			light #default intensity: 127;
			image terrain refresh: false;
			agents "Grid" transparency: 0.4 value: ant_grid where ((each.food > 0) or (each.road > 0) or (each.is_nest));
			species ant aspect: info;
		}

		display charts {
			chart "d" {
				data "ants" value: length(ant);
			}
		}
	}
}
```
3. Try to switch between the opengl display  and the chart display.

<img width="510" alt="Screenshot 2022-03-11 at 06 14 45" src="https://user-images.githubusercontent.com/1555274/157806597-08810da5-fa8b-4c9b-ba01-93e48d8ab59e.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - GAMA version: git, 1.8.2 branch
 - Java version: 17

**Comment by AlexisDrogoul** [comment]
Tested under Ubuntu 20.04 and Windows 11 and this issue doesn't manifest.

**Comment by AlexisDrogoul** [comment]
It has been tested and fixed for macOS and Ubuntu. There is however one bug on Windows that I cannot really explain (when the Java2D display is under the OpenGL one, then it cannot be selected -- only briefly before going back to the OpenGL one -- until it is moved once, after what it is ok).
