### ISSUE TITLE
Warnings produced by GAMA on Ubuntu

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3322]
**Describe the bug**
This is an apparently harmless bug, but still.GAMA is producing a lot of warnings in its UI version when running on Ubuntu 20.04.

```
(Gama Platform:31947): Gtk-WARNING **: 09:27:36.881: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(Gama Platform:31947): Gtk-WARNING **: 09:27:36.929: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(Gama Platform:31947): Gtk-WARNING **: 09:27:51.190: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(Gama Platform:31947): Gtk-WARNING **: 09:27:51.210: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(Gama Platform:31947): Gtk-WARNING **: 09:27:51.221: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(Gama Platform:31947): Gtk-WARNING **: 09:27:51.232: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(Gama Platform:31947): Gtk-WARNING **: 09:27:51.283: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(Gama Platform:31947): Gtk-WARNING **: 09:27:51.292: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(Gama Platform:31947): Gtk-WARNING **: 09:27:51.299: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)

(Gama Platform:31947): Gtk-WARNING **: 09:27:52.594: Negative content width -12 (allocation 1, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
```

**To Reproduce**
Just launch GAMA from a console or from Eclipse

**Expected behavior**
No warnings produced

**Desktop (please complete the following information):**
 - OS: stock Ubuntu 20.04
 - PC Model: MacBookPro 2018 Intel
 - GAMA version: git 1.8.2
 - Java version: 17.02 Temurin
 - Graphics cards / Display system: NVidia

**Comment by RoiArthurB** [comment]
It's an Eclipse warning which doesn't create any error. It has been documented (at least) : 
- [there on a directly related issue](https://github.com/dbeaver/dbeaver/issues/12360)
- [there in the full log (not focus on this point, but displaying that it comes front Eclipse)](https://github.com/dbeaver/dbeaver/issues/5845#issuecomment-725797547)
- [there in 2018 on another software (the variable export never worked for me)](https://community.jaspersoft.com/questions/1086126/jasperstudio-651-extremely-slow).

On a more personal point of view, I think it's a problem with fonts added by GAMA which uses negative offsets (see screenshot below), and GTK will cancel (set at 0 or 1) this offset. It's totally speculative and I never tried any fix (as it doesn't create any problem else than ugly logs) 🤷

![image](https://user-images.githubusercontent.com/16764085/158099446-639afea4-e87a-41b8-ad10-a81c6256b5cd.png)

**Comment by AlexisDrogoul** [comment]
These are all due to the use of the "Separator" item in menus, and it has been reported abundantly in Eclipse issue trackers -- it doesn't seem to cause any harm however, so I guess we can just close the issue.
