### ISSUE TITLE
Test with M1 processors

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3324]
GAMA 1.8.2 needs to be tested with M1 processors (macOS) to understand what works and doesn't with Rosetta and to produce and test an M1. 

If you have the chance to do it, please comment on this issue.

**Comment by AlexisDrogoul** [comment]
For information : 

- the execution of GAMA compiled for Intel processors on M1 Macs (using Rosetta) is confirmed. Absolutely no problem (so far) to report except a very minor one where the same color applied to the background of a display and to the toolbar would appear slightly different
- the execution of GAMA in a "native way" (Native JDK, native Eclipse w. native SWT libraries, native JOGL libraries) is quite good too (UI working, engine too, Java2D working -- with what appears as huge improvements in terms of sped), with the (big) exception of JOGL crashing immediately the application (see https://github.com/jzy3d/jogl/issues/23)...

**Comment by AlexisDrogoul** [comment]
I added the missing SWT component in the product. 

@RoiArthurB now we just need tycho to pull the right JVM and to build the native components -- and this issue will be closable !

**Comment by RoiArthurB** [comment]
GAMA is compiling for native M1 since 4822a6220f216a86a77e0162f9477da88d6ecec0 and since b90d5d4 Github Action should be able to make full release with M1 too 🥳

**Comment by RoiArthurB** [comment]
Please, try the new release with the brand new M1 native build, and if it works we can close this issue :) 
https://github.com/gama-platform/gama/releases/tag/1.8.2

**Comment by AlexisDrogoul** [comment]
Closing #3331 in that case !

**Comment by AlexisDrogoul** [comment]
Seems that the previous solution was the good one. I now close this issue -- as we have a more specific one open on modal views (#3332 )

**Comment by agrignard** [comment]
I see in the release that we have one release for Mac and one specific for M1, is it temporary? On my case I was not using Rosetta but the classic mac with JDK and it was ok.

let me know how I can help. Testing the M1 release for instance?

**Comment by AlexisDrogoul** [comment]
It is not temporary at all. In your case, if you have an M1 processor, you have been using Rosetta -- but without knowing it. 
The speed increase is impressive : running GAMA side by side on Rosetta or natively sees the latter run 2 to 3 times faster.

**Comment by agrignard** [comment]
Ok i might have miss something. I am running a "normal" (by normal I mean it doesn't contain the string M1 in the name of the release) GAMA version  as I was not able to install Rosetta (as described here https://github.com/gama-platform/gama/issues/3282)

I will try the new M1 on the M1 then. Looking forward to seeing the speed
