### ISSUE TITLE
Display java2D and mesh 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3326]
**Describe the bug**
When a field  is attempted to be display in a Java2D  display, the display remains white.

**To Reproduce**
In the model `Fields.gaml` (Data Types and Structure), change the type  of one of  the displays to java2D and observe the display.

**Expected behavior**
I  would expected either that something is displayed in Java 2D (a  projection in 2D), or simply a  warning (at compilation or at execution) explaining that a field can only be visualized in an opengl display.

**Desktop (please complete the following information):**
 - OS: macOS  Big sur
 - GAMA version: 1.8.2 git
 - Java version: 17 Teemurin

**Comment by AlexisDrogoul** [comment]
I have implemented a warning that also concerns `camera`, `light`, and also `rotation`. Note, however, that it is limited and might declare some false positive, for instance when a display inherits from a display declared in a parent experiment.
