### ISSUE TITLE
1.8.2: Wrong assignment of imported variables - model works in 1.8.1

### ISSUE THREAD

**Issue by lwinkeler** [gama-platform/gama#3330]
**Describe the bug**
Reference to [request on GoogleGroups](https://groups.google.com/g/gama-platform/c/Fgv-pY0ikTA/m/fX-OdFhRCQAJ):

We built a model, where different variables shall base on imported csv-files. As the csv-files are matrices, they are imported as a matrix with either integers or floats. The code for this is basically as following:
matrix network_employed <- matrix(csv_file("../includes/csv-data_socio/2021-11-18_V1/network_employed_V1.csv", ",", int, true));

So now some of our team use macOS, that's why they needed to try GAMA1.8.2. Unfortunately it is not possible to run the model (while it works pretty well in 1.8.1).
GAMA keeps telling us that the variables that should be for instance floats are bools. The error notice is primarily "no operator found for applying "*" to types [bool, int].

Is it just because there are some differences in calling/defining the variables between 1.8.1 & 1.8.2 or are these some issues with the compiler or else?

**To Reproduce**
1. Start the model with GAMA 1.8.1 and with GAMA 1.8.2
2. Possible to run it in 1.8.1 / Impossible to run it with 1.8.2

**Expected behavior**
No difference

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS big sur]
 - GAMA version: [1.8.2 with jdk]
 
 &

- OS: [windows (by wineskin winery & Ubuntu)]
- GAMA version: [1.8.1 with jdk]

**Additional context**
Find an adapted version for troubleshooting under this [link](https://seafile.zfn.uni-bremen.de/d/e6d0a0fd64ee47ec95e9/) *(valid until 2022-04-01)*

**Comment by ptaillandier** [comment]
Hi,

The model was written in a rather old style :) . I have fixed this. In particular:
- I typed all the lists/matrices/maps
- you can't do an ask on a null value anymore (before it did nothing, now it returns an error).

It seems to work now (you can test it - just change the extension of the file from .txt to .gaml).
[qscope_ABM.txt](https://github.com/gama-platform/gama/files/8308595/qscope_ABM.txt)


Cheers,

Patrick

**Comment by lwinkeler** [comment]
Hey Patrick,

I tested it and it works in both 1.8.1 & 1.8.2!
Good to know about the change of processing null values. Also good, that it's actually "not an issue" so the countdown for the release of 1.8.2 is not disturbed. 

Thank you very much for your help!

Cheers
Lennart

**Comment by ptaillandier** [comment]
Hi,

The model was written in a rather old style :) . I have fixed this. In
particular:
- I typed all the lists/matrices/maps
- you can't do an ask on a null value anymore (before it did nothing, now
it returns an error).

It seems to work now (you can test it).

Cheers,

Patrick
