### ISSUE TITLE
Preferences do not close when clicking "Save" on M1

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3332]
**Describe the bug**
Open the preferences view in GAMA. Change a few things and hit "Save". The view does not close. One has to hit "Cancel" to close it.

**Expected behavior**
That the view closes. 

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3
 - PC Model: MacMini M1
 - GAMA version: 1.8.2 / git
 - Java version: 17.0.2+8

**Comment by hqnghi88** [comment]
"By chance", i test this issue on my win and i can reproduce it. So it seems not only m1?

**Comment by hqnghi88** [comment]
I dont know if it is a effect of this fix, but i cant open PreferenceView with this error in eclipse console.

java.lang.NullPointerException: Cannot read field "editors" because "ummisco.gama.ui.views.GamaPreferencesView.instance" is null
	at ummisco.gama.ui.views.GamaPreferencesView.lambda$0(GamaPreferencesView.java:122)
	at ummisco.gama.dev.utils.DEBUG.TIMER(DEBUG.java:165)
	at ummisco.gama.ui.views.GamaPreferencesView.preload(GamaPreferencesView.java:115)
	at ummisco.gama.ui.utils.CleanupHelper$1.run(CleanupHelper.java:77)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Part Opened:Parameters

**Comment by AlexisDrogoul** [comment]
Can you try to debug to see if you have a prior exception when loading the Preferences ?
