### ISSUE TITLE
TCP Server And Client Example model give ConcurrentModificationException

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3334]
**To Reproduce**
1. Go to Plugins models \Network\2 Available protocols\TCP protocol\TCP Server And Client Example .gaml
2. Launch experiment.
3. See error
2 occurrences in 2 agents at cycle 1: Java error: ConcurrentModificationException
in write (name + ' received : ') + mm.contents color: color ;
ConcurrentModificationException: null
java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
java.base/java.util.TreeMap$KeyIterator.next(TreeMap.java:1540)
com.thoughtworks.xstream.core.util.PrioritizedList$PrioritizedItemIterator.next(PrioritizedList.java:91)
com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:73)
com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:472)
com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:56)
com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
when applying the contents operator on ummisco.gama.network.common.CompositeGamaMessage@7b6c7db2
in write (name + ' received : ') + mm.contents color: color ;
in loop while: self.has_more_message()  {
	message mm <- self.fetch_message();
	write (name + ' received : ') + mm.contents color: color ;
}

in reflex receive when: self.has_more_message()  {
	loop while: self.has_more_message()  {
		message mm <- self.fetch_message();
		write (name + ' received : ') + mm.contents color: color ;
	}

}

in agents Server0, Simulation 0

However the TCP Teleportation still works well.

**Expected behavior**
No error

gama git 1.8.2, win 11

**Comment by hqnghi88** [comment]
@AlexisDrogoul @gnoubi @benoitgaudou i tried a solution that provide the xstream by class, for thread safe. It seems to work, but i tested only network model, not the serialized Experiment. So it require a clear review and reimplementation as Alexis said in #3288 " one instance per agent / model / message sending/receiving,"

**Comment by benoitgaudou** [comment]
tested and  seems to work. Thanks !
