### ISSUE TITLE
connect with force_network_use false duplicate the message in mailbox

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3335]
**To Reproduce**
1. Use this simple network model
model Socket_TCP_HelloWorld_Server
global { 
	init {
		do create_server;
		do create_client;
	}
	action create_server {
		create Server number: 1 {
			do connect protocol: "tcp_server" port: 3001 with_name: name force_network_use: false;
//			do join_group with_name: "server_group"; 
		} 
	}
	action create_client {
		create Client number: 1 { 
			do connect to: "localhost" protocol: "tcp_client" port: 3001 with_name: name force_network_use: false;
			do join_group with_name: "client_group"; 
		}
	}
	reflex space {
		write "";
		write "";
	}
}
species Server skills: [network]  { 
	reflex send {
		do send to: "client_group" contents: ("Server " + name + " give " + rnd(10) + " to client_group at " + cycle);
	}
}

species Client skills: [network] {
	reflex receive when: has_more_message() {
		loop while: has_more_message() {
			message mm <- fetch_message();
			write name + " received : " + mm.contents color: color;
		}
	}
}

experiment "TCP Server Test" type: gui {
}
3. Launch and step 2 or 3 cycle
4. We see that the message box of client have a duplicated message from server, but server actually do only one send command.
![image](https://user-images.githubusercontent.com/6105384/159825519-3507873b-d7d3-42f4-8950-6c8712b63925.png)

5. If we change facet force_network_use to true , it give the right result , 1 message per cycle:
![image](https://user-images.githubusercontent.com/6105384/159825727-564f52f4-4612-4e97-bbbf-0a730ac2936d.png)

**Expected behavior**
As it was the tcp connection, i wonder what is the purpose of force_network_use (it said local, mean internal of gama, but most of the case we have at least 2 instant of gama to communicate through tcp)
Anyway, it should have only 1 message in mailbox because the server did only one sending.

Gama git 1.8.2

**Comment by AlexisDrogoul** [comment]
When looking at the code of `ummisco.gama.network.common.Connector.send(IAgent, String, GamaMessage)`, it seems that the message is indeed sent twice when `force_network_use` is false and the receiver is local. I just made a simple change, tell me if it works !

**Comment by hqnghi88** [comment]
Thank you, It is fixed.
