### ISSUE TITLE
A problem about #year

### ISSUE THREAD

**Issue by lgten1** [gama-platform/gama#3336]
**Describe the bug**
If i use "write 0.1#year", the result is 0.0. It looks like only integers are supported.Decimals are not supported.

![image](https://user-images.githubusercontent.com/91418750/160580857-8590b8d0-0a75-4f22-8d87-86ce5977bead.png)
A double to long, 0.1 will be 0. So, what about doing like this: 
![image](https://user-images.githubusercontent.com/91418750/160581240-b7515ace-238d-4943-b023-191f5cc4f57e.png)
Parameter passed in 1, then result multiply by number

**Comment by AlexisDrogoul** [comment]
Thanks for your reporting of this error and the proposal of a solution. I've implemented a similar solution directly on `msi.gaml.operators.Dates.approximalQuery(IScope, IExpression, IExpression)` as changing the behaviour of `public GamaDate plus(final double duration, final TemporalUnit unit)` could be an issue with the other calls of the method. Please close this issue if your tests show it is solved !
