### ISSUE TITLE
Problem of visualization when many experiments are defined

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#3338]
**Describe the bug**
When many experiments are defined, it is difficult to see the one on the second line.
![visu_xp](https://user-images.githubusercontent.com/1506077/160752318-688890b6-1ee2-40b0-a89c-1ba36baf2c86.PNG)

**To Reproduce**
Test the following model:
```
model multixp
experiment do_nothing_xp1 type: gui ;
experiment do_nothing_xp2 type: gui ;
experiment do_nothing_xp3 type: gui ;
experiment do_nothing_xp4 type: gui ;
experiment do_nothing_xp5 type: gui ;
experiment do_nothing_xp6 type: gui ;
experiment do_nothing_xp7 type: gui ;
experiment do_nothing_xp8 type: gui ;
experiment do_nothing_xp9 type: gui ;
experiment do_nothing_xp10 type: gui ;
experiment do_nothing_xp11 type: gui ;
```

**Desktop (please complete the following information):**
 - OS: tested on windows 10 and Mac OS X (mac M1)
 - PC Model: windows with Hi-DPI screen and Mac mini M1
 - GAMA version: git

**Comment by lesquoyb** [comment]
If that can help : I noticed that the height of the toolbar is correctly defined once you resize the window, so maybe there is an easy fix to do by forcing the display to refresh after adding all the toolbar items

**Comment by lesquoyb** [comment]
Reopening because it's not working on linux 
![image](https://user-images.githubusercontent.com/6374469/167295160-aa36cd9b-7f4f-462d-b769-c34f7c07f77f.png)

**Comment by AlexisDrogoul** [comment]
It seems that the bug is widespread and not handled (for the moment) by SWT/Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=570732 . So let's put it on stand-by for the moment, hoping the SWT team will come with a solution !

**Comment by AlexisDrogoul** [comment]
Given that we can probably wait a long time before seeing this bug solved, I have implemented a general workaround, which allows to collapse all buttons into a menu when their combined width exceeds the possible width of the toolbar. It is governed by two new preferences:

<img width="249" alt="Monosnap 2022-05-31 00-32-59" src="https://user-images.githubusercontent.com/579256/171038998-96569715-d988-440e-9448-c25b2c698711.png">

When the first is set, experiments will always be presented as a menu (false by default). When the second is set (false by default except on Linux), this is what happens : 

![screencast 2022-05-31 00-38-12](https://user-images.githubusercontent.com/579256/171039792-8721d1cf-afc2-4d41-b0cb-5ac18d274470.gif)

This will be committed a bit later.
