### ISSUE TITLE
Pie chart label enhancement

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3343]
**Is your request related to a problem? Please describe.**
The request is related to pie chart graphism
Here is how a pie chart looks like so far in GAMA 
<img width="637" alt="Screenshot 2022-04-01 at 09 05 54" src="https://user-images.githubusercontent.com/3928502/161212970-4ba790f6-7373-47df-835f-fef047b117c7.png">

**Describe the improvement you'd like**
it would be great for 'design' purpose to be able to change the display of the value (A,B,C) 
1. Change the color of the rectangle and the text label
3. Give the possibility not to display it

**Describe alternatives you've considered**
(I am not sure there is a facet for this (if yes I didn't find it) )

**Comment by agrignard** [comment]
Trying to work on this 

I might be wrong as far as I understand the code related to this might be here
ChartJFreeChartOutputPie.java

In this method

`````
public void createChart(final IScope scope) {
super.createChart(scope);
if (IKeyword.THREE_D.equals(style)) {
	chart = ChartFactory.createPieChart3D(getName(), null, false, true, false);
} else if (IKeyword.RING.equals(style)) {
	chart = ChartFactory.createRingChart(getName(), null, false, true, false);
} else {
	chart = ChartFactory.createPieChart(getName(), null, false, true, false);
}
}
`````

The doc is here 
https://www.tabnine.com/code/java/methods/org.jfree.chart.ChartFactory/createPieChart

**Comment by ptaillandier** [comment]
It is already possible to not display the label of a pie chart using the facet: series_label_position: "none" 

I added the possibility to define the label color: label_text_color: #red label_background_color: #lightgray axes: #red (axes already existed).

**Comment by agrignard** [comment]
Tested! Ok for me!
