### ISSUE TITLE
Improve the installation process

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#3350]
**Is your request related to a problem? Please describe.**
While the gama installation process is quite simple, it could still be improved by following each platform's philosophy e.g: the user would just have to deal with a package for linux, an installer program for windows and a dmg for macos (which is already the case)

**Describe the improvement you'd like**

1. Adding github jobs to generate linux packages and windows installers
2. Updating the installation documentation accordingly

**Additional context**
There previously has been some work done to [generate a ppa](https://github.com/gama-platform/gama/issues/2767)
The [installation page](https://github.com/gama-platform/gama/wiki/Installation) and a related [issue](https://github.com/gama-platform/gama-platform.github.io/issues/96)

**Comment by RoiArthurB** [comment]
Here's a list to keep track of each process : 
- [x] MacOS
  - [x] DMG signed install archive 
- [x] Linux @RoiArthurB 
  - [ ] PPA done on #2767 but need to be updated and automated
  - ⛔ Snap for Ubuntu distro
    - `.deb` is enough
  - ⛔ Flatpak for any distro
  - [ ] (?) AUR for Arch based distro
    - Need to be done from Ubuntu (as Github Actions Runner), so may not be done 
- [ ] Windows @lesquoyb 
  - [x] MSI installation file
    - [ ] Stable release should be proposed over winget with its installer ✅
  - [ ] winget https://github.com/microsoft/winget-pkgs/pull/4157 (waiting for ZIP install support)

**Comment by hqnghi88** [comment]
Just to recall there was too old win installer here , to be replaced https://github.com/gama-platform/gama.installer

**Comment by RoiArthurB** [comment]
> Just to recall there was too old win installer here , to be replaced https://github.com/gama-platform/gama.installer

I removed the old repo as it has been re-do inside GAMA in [ummisco.gama.product/extraresources/installer/windows](https://github.com/gama-platform/gama/tree/GAMA_1.8.2/ummisco.gama.product/extraresources/installer/windows) 😁

**Comment by RoiArthurB** [comment]
For track : We won't add deb meta-data as we would need to use another utility ([AppStream](https://www.freedesktop.org/wiki/Distributions/AppStream/)) to package GAMA (cf. https://gitlab.gnome.org/GNOME/gnome-software/-/wikis/software-metadata )
