### ISSUE TITLE
Glitch with the contextual help in editor

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#3352]
**Describe the bug**

Text in the contextual help is covered with horizontal black lines or white dots after scrolling.

**To Reproduce**

- Hover on a piece of code to get the context help.
- Scroll down. 
- Some parts of the text are difficult to read.

**Screenshots**

![image](https://user-images.githubusercontent.com/18676913/164196173-71c91eff-7b23-4998-886b-bd2461fffe18.png)

![image](https://user-images.githubusercontent.com/18676913/164196336-b1708eea-3907-4f6b-9e8f-6c3be3557d58.png)

**Desktop (please complete the following information):**
Windows 10
Gama 1.8.1 and 1.8.2
Nvidia RTX 4000

**Comment by lesquoyb** [comment]
In order to have a complete overview of your setup, do you have a windows scaling higher than 100% ?

**Comment by tnguyenh** [comment]
Yes, 150%.

**Comment by AlexisDrogoul** [comment]
Can't reproduce it on Windows 11, dark mode (I assume it is your case), 250% of zoom. 
![popup](https://user-images.githubusercontent.com/579256/167052680-5fb80fa1-5aef-467d-939c-6566fab15e58.jpg)
