### ISSUE TITLE
[batch] batch experiments that have a parent crash gama

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#340]
**Describe the bug**
When an experiment of type batch has a parent experiment containing at least one parameter, gama crashes when trying to play the experiment.

**To Reproduce**
1. Run this model:
```
model batchparent

global{
	float i;
}

experiment batch_abstract {
	parameter "plop" var: i min: 0.1 max: 1.0 step: 0.1;
}

experiment 'bug' parent: batch_abstract type:batch{
}
```
2. observe the crash
3.  change the type of the `bug` experiment to gui and observe that it works normally

**Expected behavior**
No crash

**Additional information**
The bug was not happening in the july release, which makes me think it is related to recent changes in batch

**Comment by lesquoyb** [comment]
More information on this: it seems like it is something introduced by the pr #186 a long time ago and more precisely in this [commit](be2df517970936e97b35f78de504fba65d5e3b64) (coucou @chapuisk)

**Comment by AlexisDrogoul** [comment]
Actually, having a parameter in the parent or not does not play a role here. What is significant is to have some float parameter as the method `AExplorationAlgorithm.getFloatParameterSwip()` is clearly prone to infinite looping...
