### ISSUE TITLE
Event Layer model make Gama hang when cursor move into display boundary

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#341]
**Describe the bug**
Event Layer model make Gama hang when cursor move into display boundary
**To Reproduce**
1. Go to 'Event Layer.gaml'
2. Click on 'Displays' button
3. Click on Play button
4. Move the mouse into the display area
5. Gama hang with waiting cursor

**Expected behavior**
NO hanging
**Screenshots**
It happen from the commit 7ae6a3e 
**Desktop (please complete the following information):**
 Git version

**Comment by lesquoyb** [comment]
I tried to not hover the display directly and the model works for me for a few seconds, then drastically slows down for aparently no reason. After that the model can run forever but as soon as I hover the display it stops the whole program as you said:
![image](https://github.com/user-attachments/assets/dbeb7e1c-97d1-4b6f-b32d-ba4a9bbce545)
Fun thing is if you start clicking on the display before running the simulation it doesn't crash.
Also if you de synchronize the display everything works properly

**Comment by hqnghi88** [comment]
I tested on the branch and there is no hang . I let @lesquoyb to merge it then.
Thanks.
