### ISSUE TITLE
[optimization] add a way to log each function call and duration

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#342]
**Describe the bug**
While writing documentation about how to optimize models I noticed that in some case you have no choice but to log every action/reflex called and their duration to get an idea of where to look for optimizations.
This process is quite tedious and always the same so it's perfect for automating and I was thinking that we could provide to the users an execution mode that would automatically do it and export the results in a csv or something to be visualized in an external program

**Comment by AlexisDrogoul** [comment]
Isnt'it the purpose of the existing `benchmark` mode ?

**Comment by lesquoyb** [comment]
Benchmark only works for the code contained inside of it, I was thinking about an execution mode that would basically wrap every action/reflex by an equivalent of benchmark.
Another problem with benchmark is that it doesn't produce raw data and do not give access to it in other way than a text in the console (as mentioned in #329)

**Comment by lesquoyb** [comment]
So to give some updates on that, there's a `benchmark` mode on the experiment level, which is different from the statement I was thinking about.
This mode records all lines of code executed with the number of calls and accumulated duration.
I've added this information to the [page](https://gama-platform.org/wiki/next/AnalysingCodePerformance) I'm currently building on optimization so closing this issue, but I'm quite that if people actually use it, it will need to be refined a bit
