### ISSUE TITLE
Support long seed for gama RNG

### ISSUE THREAD

**Issue by romainreuillon** [gama-platform/gama#348]
The setSeed primitive takes a double argument. This might lead to rounding problem. It is especially problematic given that it is very common that modellers initialise seeds sequentially or using millisecond of the computer. For sufficiently high numbers the double approximation will lead to initialize the RNG with the same long seed for different double seeds.

**Comment by AlexisDrogoul** [comment]
Actually, I have checked the code, and we only convert longs to doubles (using the LongBitsToDouble method), which means we do not lose precision (in bits) by casting them. I temporarily close this issue, then.
