### ISSUE TITLE
[UI] The lock button can be clicked when camera is dynamically set

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#350]
**Describe the bug**
When defining a display with a camera with `dynamic` location, it is by default locked (which makes sense), but the user can still click on the lock button in the toolbar and deselect it.
Which leads to misunderstanding as the camera is still "locked" (it's impossible for the user to move it) but the lock button is not selected anymore.

**To Reproduce**
1. Run this model:
```
model dynamiccam

species s;

experiment x {

	init {
		create s;
	}	
	output {
		display "test" type: 3d {
			camera #default dynamic: true;
			species s;
		}
	}	
}
```
2. click on the lock button
![image](https://github.com/user-attachments/assets/462af04a-ff40-4165-a4eb-378a52b57e55)
3. Try to move the camera

**Expected behavior**
Either the lock button stays selected or it is not in the toolbar at all

**Comment by AlexisDrogoul** [comment]
The button is now disabled when the camera is declared as dynamic, but not when it is set to locked. This issue can be closed safely once the PR is merged.
