### ISSUE TITLE
[batch legacy] Add the possibility to run directly an experiment

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#361]
**Is your request related to a problem? Please describe.**
From what I understand, currently with batch legacy if we need to run an experiment we have to run gama two times: once to generate an xml and a second time to run the experiment plan described in the xml. 
We could probably add the possibility to create the xml and execute it right away with the same command, that would make things easier in many cases.

**Describe the improvement you'd like**
Be able to create and execute an experiment plan in the same command call for batch legacy

**Comment by RoiArthurB** [comment]
This could be a good idea, but not using the XML file.

As the current state of the headless using XML, it's gathering too much legacy code and starts to diverge from the GAMA core. Therefore I'd be more in favor of adding a new flag (eg. `-gaml`) which would run the gaml file directly in headless.

**Comment by lesquoyb** [comment]
So without passing through all the legacy code, right ?
But then how do we get the outputs ?
I think having the outputs serialized as it is done in legacy is very valuable for many users.

A bit different but that makes me think that we could add functionalities to gama-server to generate the xml files and to run them too.

**Comment by hqnghi88** [comment]
@lesquoyb by using autosave of output  (obviously no 3D i think) or save statement of snapshot.... we tested with Alexis in some previous coding camp but i did not remember exactly what it was, but it's possible

**Comment by lesquoyb** [comment]
While inspecting the code I noticed there's actually already a `-gaml` flag that runs directly experiments in headless mode, using the xml serialization. 

It is weird I never saw it mentioned anywhere and that even you @RoiArthurB was not aware of it.

Currently its use is incompatible with the current parameters' verification, but I'm fixing this in the pr #362 along with few minor other things.

It would still need to be documented though

**Comment by lesquoyb** [comment]
The pr restoring the `-gaml` parameter has been merged and tested (for simple cases at least).
I edited the documentation of legacy to add this method, so I think that's enough for this issue.
