### ISSUE TITLE
Closing simulation in GAMA Server finish with state "PAUSED"

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#371]
**Describe the bug**
While running GAMA Server, each state of the running experiment is broadcasted on it's web socket. Therefore, while starting a simulation, the state goes from `NONE` > `NOTREADY` > `PAUSED` > `RUNNING`.

However, while closing a simulation, the state goes like this : `PAUSED` > `NOTREADY` > `NONE` > `PAUSED`. This last state should not exists since we're back on the edtior view

**To Reproduce**
1. Use GAMA Server
2. Open a simulation
3. Close the simulation with GAMA Server command
4. See wrong last state

**Expected behavior**
Finishing with the `NONE` state and not the `PAUSED` one

**Desktop (please complete the following information):**
 - OS: Linux
 - GAMA version: Alpha 2024-11
 - Java version: 21

**Additional context**
Related to this issue : https://github.com/project-SIMPLE/simple.webplatform/issues/35

**Comment by lesquoyb** [comment]
That's only in server mode for gama GUI btw as for now headless server is not sending any state (as mentioned in #1)

**Comment by RoiArthurB** [comment]
I'll re-create a new issue as the problem was coming from the way I implemented my application; however there's an issue while closing a `RUNNING` experiment without pausing it first (no message seems to be sent at all; I need to inspect it deeper).

**Comment by lesquoyb** [comment]
up ? @RoiArthurB
