### ISSUE TITLE
OpenGL: Enable the possibility to pick a grid cell when z_fighting is enabled

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#475]
```
What steps will reproduce the problem?
1. On the model using such definition of grid:
   grid cell file: dem_file neighbours: 8 frequency: 0  use_regular_agents: false use_individual_shapes:
false use_neighbours_cache: false {

(such as the training session one)

What is the expected output? What do you see instead?

The agents can be picked (right-click in picking mode), whereas cells cannot

Please use labels and text to provide additional information.

GAMA 1.6, MACOS
```

Original issue reported on code.google.com by `benoit.gaudou` on 2013-07-17 15:33:58

**Comment by AlexisDrogoul** [comment]
I wonder what happened recently (beside my own commit, but I've not touched the code in charge of picking), but this issue has surfaced again, in an even more complex form: when a grid is displayed, almost no agents can be selected. You can try in the 'Ant Sorting' model: disable the grid, and the ants become selectable. Reenable it, and nothing is selectable. What was the original fix ?

**Comment by agrignard** [comment]
whooo... I don't like this. 

One change has been done to fix this issue https://github.com/gama-platform/gama/issues/1414 but I don't see how it can change the picking behavior.

And I did some change for the picking of the cached geometries in this commit:
https://github.com/gama-platform/gama/commit/ae470aa6612065a9740a0c0e048e65fc5b0f6109

but this is also unrelated...

**Comment by agrignard** [comment]
BTW the picking in general is not working no?

The geometries are not drawn in red anymore when picked...

**Comment by AlexisDrogoul** [comment]
Issue also fixed with the latest commits.
