### ISSUE TITLE
More options for highlighting

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#498]
```
For the moment, the user can only change the color of the highlighting square, but even
with that, it is sometime difficult to find the highlighted agent.

It can be a good idea to give more options to the user for the highlighting: thickness
of the square lines, blinking,...
```

Original issue reported on code.google.com by `patrick.taillandier` on 2013-08-13 07:14:11

**Comment by AlexisDrogoul** [comment]
I have implemented the second solution. Modelers can now define, in addition to the special `default` aspect, an aspect with the name of `highlighted` if they want to specify exactly how the agent should be displayed when highlighted. If no `highlighted` aspect is defined in a species, the standard highlight will apply (i.e. change of the color). I added a small documentation on this in `AspectStatement` as well. 

Interesting side effects can be obtained with this enhancement: for instance, highlighted agents can be declared as transparent, enabling the user to use highlight to reveal agents behind, etc.
