### ISSUE TITLE
Save and manage camera positions in the model and UI

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#579]
```
What is the expected output? What do you see instead?

It could be nice to be able to save the camera position in a simple way.
For example if the modeler spends 15 min to move, rotate the camera, it could be nice
that he could be able to save this position or to be able to enter it as initial value
of the model....


```

Original issue reported on code.google.com by `benoit.gaudou` on 2013-09-03 18:32:16

**Comment by AlexisDrogoul** [comment]
Enhancements described in #1234 and #1235 have been regrouped under this issue. Not real duplicates, but part of the solution.

**Comment by AlexisDrogoul** [comment]
Some progress has been made (the `camera` pseudo-layer can now be defined), but still a long way to go before it is available. Pushing it to the final release.

**Comment by AlexisDrogoul** [comment]
Hi,

To make some progress on this issue, would it be possible to have the list of cameras described in #1553 with their target, position and up_vector ? ( @mazarsju )

Cheers
Alexis

**Comment by mazarsju** [comment]
From the "AbstractCamera", you can have position the camera by adding this following code : 
```
lookPosition(cameraLookAtPos.x, cameraLookAtPos.y, cameraLookAtPos.z);
updatePosition(cameraNewPos.x, cameraNewPos.y, cameraNewPos.z);
upPosition(upVector.x,upVector.y,upVector.z);
updateSphericalCoordinatesFromLocations();
```
The "cameraLookAtPos" will always be equal to : `GamaPoint(getRenderer().getEnvWidth()/2,-getRenderer().getEnvHeight()/2,0);`

Here are the values of cameraNewPos and upVector for the different cameras : 
* fromTop : 
  * cameraNewPos = `GamaPoint(cameraLookAtPos.x,-cameraLookAtPos.y,getRenderer().getMaxEnvDim()*INIT_Z_FACTOR)`
  * upVector = `GamaPoint(0,1,0)`
* fromLeft : 
  * cameraNewPos = `GamaPoint(cameraLookAtPos.x-getRenderer().getEnvWidth()*INIT_Z_FACTOR,cameraLookAtPos.y,0)`
  * upVector = `GamaPoint(0,0,1)`
* fromLeftWithElevation : 
  * cameraNewPos = `GamaPoint(cameraLookAtPos.x+getRenderer().getEnvWidth()*INIT_Z_FACTOR,cameraLookAtPos.y,getRenderer().getMaxEnvDim()*INIT_Z_FACTOR)`
  * upVector = `GamaPoint(0,0,1)`
* fromRight : 
  * cameraNewPos = `GamaPoint(cameraLookAtPos.x+getRenderer().getEnvWidth()*INIT_Z_FACTOR,cameraLookAtPos.y,0)`
  * upVector = `GamaPoint(0,0,1)`
* fromRightWithElevation : 
  * cameraNewPos = `GamaPoint(cameraLookAtPos.x+getRenderer().getEnvWidth()*INIT_Z_FACTOR,cameraLookAtPos.y,getRenderer().getMaxEnvDim()*INIT_Z_FACTOR)`
  * upVector = `GamaPoint(0,0,1)`
* fromFont : 
  * cameraNewPos = `GamaPoint(cameraLookAtPos.x,cameraLookAtPos.y - getRenderer().getEnvHeight() * INIT_Z_FACTOR,0)`
  * upVector = `GamaPoint(0,0,1)`
* fromFrontWithElevation : 
  * cameraNewPos = `GamaPoint(cameraLookAtPos.x,cameraLookAtPos.y - getRenderer().getEnvHeight() * INIT_Z_FACTOR,getRenderer().getMaxEnvDim()*INIT_Z_FACTOR)`
  * upVector = `GamaPoint(0,0,1)`

There is still a problem with the upVector for the view "fromTop", I'll see that tomorrow.

**Comment by agrignard** [comment]
So.... where are we now in this "big" issue? What is the current state of the code?  where should I start?

**Comment by AlexisDrogoul** [comment]
There is a CameraStatement that can be used for supporting all the enhancements (giving a "name" to cameras, specifying its coordinates, etc.). That can be a good starting point. After that, the side layer controls offer a natural shell for supporting a light UI allowing to change the camera between the one defined and predefined ones. And probably, also, saving the current one.

**Comment by agrignard** [comment]
Is there already a way to specify in GAMA that we want to use a preset camera?

Something like camera_preset:"up_front". Right now I am using the overlay and then copy the facet which is fine but a bit longer in term of code. If we have access to the preset from Gaml that might be even better

**Comment by AlexisDrogoul** [comment]
In the light of #2757, it becomes necessary to have a real `camera` statement, supporting all the facets introduced in `display`: `z_near`, `z_far`, position, look-position, `lens`, `interaction`, etc.

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0
