### ISSUE TITLE
topology and spatial operators

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#582]
```
What steps will reproduce the problem?
1. Open the attached model
2. run it


What is the expected output? What do you see instead?
The at_distance operator does not take into account the grid topology (distance 1 in
the grid topology does not mean a circle of 1m).
Another problem (that is not directly link... but not far) concern the filtering of
the grid neighborhood in grid topology.  The getNeighboursOf of the Grid topology should
take into account the filter just as the continuous topology.

```

Original issue reported on code.google.com by `patrick.taillandier` on 2013-09-04 16:16:43
<hr>
 * *Attachment: [grid_at_distance.gaml](https://storage.googleapis.com/google-code-attachments/gama-platform/issue-581/comment-0/grid_at_distance.gaml)*

**Comment by ptaillandier** [comment]
Ok, this general issue is normally fixed. If you have a problem with a specific operator (and topology) feel free to open a new issue.
