### ISSUE TITLE
Enhancement: Move Database access to GeoTools library

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#762]
```
Describe which enhancement/addition to GAMA you would like to see:

With the recent work on the handling of CRS across geometries stored in files, databases,
etc. I have been wondering why we did not make use of the facilities offered by GeoTools
(which we already use for reading shape files, grid files, etc.) for handling all JDBC
tasks. After reading some of the documentation, it seems that moving the codebase to
GeoTools would provide a great deal of advantages (but maybe some disadvantages as
well, so please comment on this possible "enhancement"):

- access to "data stores" consistent with what is already done in shape files handling.
- automatic handling of CRS retrieval (and access to advanced features such as SRS)
- access to remote databases (not sure it is already the case in our codebase)
- thread-safe operations (not sure it is already the case in our codebase)
- low-level operations already handled (like envelope computation, etc.)
- possibility to define a SQL parser that could be invoked by the GAML parser to provide
some degree of validation
- an extended set of SQL dialects and DB providers
- and, finally, relying on a well-maintained library that is used and tested throughout
many projects.

For me, the most important feature is the first one, as it would allow to define a
consistent interface that would allow to retrieve data from files and databases in
a consistent manner (effectively subsuming IGamaFile into a more generic IGamaData
functionality, declaring database access like we declare file access now, e.g. data("uri
to the database", "user", "pwd", "SQL query"), etc. with only a few lines of Java if
we rely on the DataStore concept).

Please comment on the usefulness (and possibility) of this move — but also on the work
possibly involved.


```

Original issue reported on code.google.com by `alexis.drogoul` on 2014-01-01 04:03:37

**Comment by truongminhthai** [comment]
Dear All,

After some days I worked on geotools for database and tracked on GamaFile, GamaGisFile, GamaShapeFile and other types of file, in my opinions, I think that:
-  GamaFile and GamaGisFile could be changed to a more generic such as GamaData and GamaGisData (Pcaillaou told about that on above) which will support generic functions for almost data types in GAMA. 
- The GamaShapeFile, GamaSqlConnection ... will inherit from  these Gama data. The GamaShapeFile, GamaSqlConnection... will support the specific function to connect shapefile, many kind of database server, geoserver (data store)... and then retrieve data form the data store and transform the retrieved data to Gama data.

By the way, we can retrieve data from csv, shape file, database servers or geoserver for  creating agent or other activities in Gama in the same way. In addition, developers of Gama also don't care so much about changes of Gama core in such way.

Cheers,
Truong Minh Thai

**Comment by AlexisDrogoul** [comment]
Hi Thai,

Good work. Changing the hierarchy of GamaFile is in my opinion not a good solution right now. Instead, I’d better « modularize » things so that the real « access » to the data (be it with files, databases, remote connexions) is part of a different hierarchy, something more or less equivalent to your GamaData, but in a separate hierarchy. Each GamaFile would have a link to GamaFileData, and other classes part of the GamaFile hierarchy could have a link to another kind of data access. 

I will think about how to reorganize things so that your contribution can fit and be usable immediately from GAML. In the meantime, do not hesitate to continue filling your classes under « GamaXXXFile » even if it is not completely appropriate, and tell me when you think they are finished and ready for both testing and refactoring ! 

Cheers
Alexis





> Le 1 juin 2015 à 09:07, truongminhthai <notifications@github.com> a écrit :
> 
> Dear All,
> 
> After some days I worked on geotools for database and tracked on GamaFile, GamaGisFile, GamaShapeFile and other types of file, in my opinions, I think that:
> 
> 	• GamaFile and GamaGisFile could be changed to a more generic such as GamaData and GamaGisData (Pcaillaou told about that on above) which will support generic functions for almost data types in GAMA.
> 	• The GamaShapeFile, GamaSqlConnection ... will inherit from these Gama data. The GamaShapeFile, GamaSqlConnection... will support the specific function to connect shapefile, many kind of database server, geoserver (data store)... and then retrieve data form the data store and transform the retrieved data to Gama data.
> By the way, we can retrieve data from csv, shape file, database servers or geoserver for creating agent or other activities in Gama in the same way. In addition, developers of Gama also don't care so much about changes of Gama core in such way.
> 
> Cheers,
> Truong Minh Thai
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Senior Researcher, UMI UMMISCO 209, IRD & UPMC, France.
--
alexis.drogoul@gmail.com | http://goo.gl/4ewFdJ
[Vietnam] +84915088155 [France] +33608698845
--
GAMA: http://gama-platform.org

**Comment by AlexisDrogoul** [comment]
Hi,

Coming back to this issue again… What is the status of the port of database access to GeoTools ? I'm a bit lost in the different Java files claiming to offer some access to databases, some of them being seemingly usable, some of them not.. 

Thanks in advance,
Alexis

**Comment by AlexisDrogoul** [comment]
Now tracked under #1362

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
Recent developments on the database plugin have made this issue a bit obsolete.
