### ISSUE TITLE
Enhancement: grid definition

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#804]
```
Describe which enhancement/addition to GAMA you would like to see:

I was wondering if grid definition could be enhanced, something like here

http://help.arcgis.com/en/arcgisdesktop/10.0/help../index.html#//00170000002q000000





```

Original issue reported on code.google.com by `b.srirama` on 2014-02-13 06:23:42

**Comment by AlexisDrogoul** [comment]
The first enhancement has been addressed long ago, and the second one requested make it a duplicate of gama-platform/gama2#2 (changing the location of grids). I close this issue.
