### ISSUE TITLE
main toolbar slightly hidden

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#821]
Hi,

The main toolbar with run |step |reload (see attachment) is slightly hidden. The buttons (run |step |reload ) are circular but the the whole circle is not visible. (only 90% visible)
![toolbar](https://cloud.githubusercontent.com/assets/12668606/7895809/72baafb2-06a1-11e5-8e95-0420bdc5615c.png)

thanks
Srirama

**Comment by AlexisDrogoul** [comment]
This issue has normally been solved by the move to Eclipse Mars. I then close it.
