### ISSUE TITLE
"follow" with java2D and opengl

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#868]
```
What steps will reproduce the problem?
1. Open a model with an agent moving (for instance Goto Action, Weighted Network)
2. Load it,
3. focus on the agent
5. In java2D, it is not possible to follow the agent

Add type: opengl to the display.
2. Load the model,
3. focus on the agent
4. follow the agent
5. the camera does not seem to follow the agent at all

Please use labels and text to provide additional information.
I am using jogl and not jogl2
```

Original issue reported on code.google.com by `patrick.taillandier` on 2014-03-16 09:09:58

**Comment by AlexisDrogoul** [comment]
Two things to do here:

- reimplement follow using the focus on a shape (already done)
- find a way to add something to the UI to stop following the agent simply

**Comment by agrignard** [comment]
Any update on this one?

I realive this very old issue but I think this feature would be great: Following an agent during the simulation

**Comment by AlexisDrogoul** [comment]
Can be done in OpenGL using the camera_xxx facets on the display, but maybe worth to reopening it to provide a simpler way to do it ? Reopening this issue for the next round of development on GAMA 2.0, at least for Java2D

**Comment by AlexisDrogoul** [comment]
It is actually doable now very easily using something like : 

`camera default target: my_agent dynamic: true;`

You can of course play with the other facets, like `location`(from where does the camera look at the agent ?), or `distance`...

**Comment by AlexisDrogoul** [comment]
Please note that it has been decided not to port this functionality to Java2D. I therefore close this issue as it is implemented for OpenGL
