### ISSUE TITLE
Cast of nil

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#951]
```
What steps will reproduce the problem?
1. I notice that : 
  - int (nil) -> 0, 
  - list(nil) -> [] 
and so on.

What is the expected output? What do you see instead?

I was expecting that list(nil) -> nil. But I do not know whether it is a choice or
an issue...

Please use labels and text to provide additional information.

GAMA, SVN MAC
```

Original issue reported on code.google.com by `benoit.gaudou` on 2014-03-31 17:33:23

**Comment by benoitgaudou** [comment]
Default values have been checked:
- 0, 0.0 and false for int, float and bool
- black for rgb
- [] and map([]) for list and map
- null for others

closed with commit 4c98e649083ab11bf9e7a16e16cf6440a247dee0
