### ISSUE TITLE
Enhance the orthographic(isometric) projection 

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#995]
```
Describe which enhancement/addition to GAMA you would like to see:

We should have a preference to choose weither the user want to have an isometric(orthographic)
projection or a perspective projection (the actual one). 




```

Original issue reported on code.google.com by `agrignard` on 2014-04-16 05:33:21

**Comment by agrignard** [comment]
the facet orthographic_projection:false/true is working so I think we can close this issue.

**Comment by agrignard** [comment]
The facet are working but the result is not the best we can have. Especially when the user zoom out when the projection is orthographic the rendering disapears

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0 -- not sure if there are any specific enhancements to make, but still worth to look at it.

**Comment by AlexisDrogoul** [comment]
I actually added a simple camera definition called `#isometric`, which I think is enough for 99% of the cases. The facet `orthographic_projection`, which doesn't work very well, will be soon deprecated.

**Comment by agrignard** [comment]
Great feature! Looking forward to testing it!

**Comment by hqnghi88** [comment]
@agrignard can you test this and report back?

**Comment by AlexisDrogoul** [comment]
Closing it
